### ISSUE TITLE
Enter on a masked textbox with the Tab key

### ISSUE THREAD

**Issue by epikarma** [RobinHerbots/Inputmask#1]
If you enter on a masked textbox with the tab key the mask doesn't show.

I propose to add to the event declaration chain this code:

.bind('keyup.inputmask', function (event) {
    if (event.keyCode == '9') {
        setTimeout(function () {
            caret(input, checkVal(input, buffer, true));
        }, 0);
    }});

**Comment by RobinHerbots** [comment]
I added the change . (v 0.2.8)

thx

Robin
