### ISSUE TITLE
Input nask error in FF

### ISSUE THREAD

**Issue by plewasebastian** [RobinHerbots/Inputmask#100]
I have installed new version jquery.masked input version 1.0.20. In 1.0.19a was OK.
Masks disappeared from inputs in FF. In Opera, IE is OK.

Firebug shows error in line: 

RangeError: invalid array length

if (maxLength < _buffer.length) _buffer.length = maxLength;

If if set maxlength for input field, it works correct without error.

Is maxlength for input fields required for version 1.0.20 and higher?

Regards
Sebastian

**Comment by RobinHerbots** [comment]
fixed!!
