### ISSUE TITLE
Jquery inputmask IE Issue

### ISSUE THREAD

**Issue by arunchudmunge** [RobinHerbots/Inputmask#1000]
HI RobinHerbots,

Thanks for " jquery.inputmask " It's really helping me to format input.

But I'm facing few issue in IE .

$revenue.inputmask('£9{1,3}.9{1}', {placeholder : '0', numericInput: true, greedy:false});

I'm using this for currency formatting, my issue is after retrieving these values from the server, in IE the prefix '£' is only showing after focus in that input.

Second issue is on tabbing the value disappears in IE.

can you please take a look and help me to fix these issues.

**Comment by RobinHerbots** [comment]
@arunchudmunge , 

Can you make a jsfiddle for it and which version of IE are you using.  Do you also have the problem in Chrome or FF

Maybe set the clearMaskOnLostFocus option to false.

**Comment by arunchudmunge** [comment]
Hi RobinHerbots,

Working as expected after taking the latest lib file & giving the '$revenue.inputmask()' @ the end of JS file.
you can close the issue, Thanks for your prompt reply.
