### ISSUE TITLE
Plus sign related issue

### ISSUE THREAD

**Issue by licarus** [RobinHerbots/Inputmask#1005]
I'm trying to put a mask on integer field where if it's a positive integer, it'll automatically adds '+' sign as prefix. But I don't want to prefix '+' sign to always show so that negative number can still be added.

I don't think the input mask can handle that. So, I just added a plus sign on blur in my code. The problem I'm encountering now is when I tab back to that field trying to correct something, the value is selected (including the plus sign) but I it doesn't take any input from keyboard, so I can't delete it or override it with anything. I suspect it's due to the value having a prefix of '+'.

I can just delete one character at a time, but I'd like to be able to delete the entire highlighted value.

I've tried allowPlus and prefix but neither worked as I would like.

Any help is appreciated.
Thanks

**Comment by RobinHerbots** [comment]
@licarus , 

Can you try with this http://jsfiddle.net/ot3py0xc/2/

As an extra I understand that you always want to show the + in case of a positive?

Robin

**Comment by licarus** [comment]
Your example is showing that the plus sign is allowed and when I have the whole text highlighted, and type something it automatically deletes the whole value. That's exactly how I want it.
The thing is, I would also like a way to always show the + in case of positive. The way I do it now, I manually append "+" in front of the number when I tab away. It works as far as appending it, but when I tab back (whole value highlighted with + sign as part of it), pressing keys won't remove it.

**Comment by licarus** [comment]
I just got the latest version (3.2.0) and this is working how I described. yay!
But I do notice something that may be a bug. For decimal input mask, if I have a number with decimal, and when I tab to it with the whole value selected and hit delete key, instead of clearing it, it leaves a 0. I have to hit the delete again to clear that one.

Check it out: http://jsfiddle.net/ot3py0xc/3/

**Comment by RobinHerbots** [comment]
@licarus , 

This is fixed in the latest version
