### ISSUE TITLE
Leading with radix issue

### ISSUE THREAD

**Issue by licarus** [RobinHerbots/Inputmask#1006]
For decimal mask, is there a way to allow entering the value starting with a dot and automatically append the 0 in the front.

For example, I type in '.' and it'll show up as '0.'.

I noticed in your code under radixhandler, you check for the digits to be more than 0. When I commented that part out, it worked.

If it's not too much trouble, could you add a new config to allow for leading radix?

Thanks

**Comment by RobinHerbots** [comment]
@licarus , 

That is already the case:

http://jsfiddle.net/ot3py0xc/  and start typing a '.'
