### ISSUE TITLE
extra zeros in currency alias

### ISSUE THREAD

**Issue by claudiogg88** [RobinHerbots/Inputmask#1008]
Hello Robin,

I have an issue with a currency field, i have the following config:
    {  
   "digits":"6",
   "integerDigits":"12",
   "radixFocus":true,
   "showMaskOnHover":false,
   "showMaskOnFocus":false,
   "skipOptionalPartCharacter":true,
   "clearIncomplete":true,
   "alias":"currency",
   "digitsOptional":true,
   "groupSeparator":".",
   "radixPoint":",",
   "autoUnmask":true,
   "rightAlign":false
   }
and this is what i see

![sin titulo](https://cloud.githubusercontent.com/assets/7227926/9316727/35c6e530-450d-11e5-9296-911746f3f95f.jpg)

why the extra 0, after ,82 are not removed?

**Comment by paulo-raca** [comment]
I believe that's exactly what {digits:6} mean.
You could use {digits: "*"} for automatic number of digits.

**Comment by claudiogg88** [comment]
thanks, that's work, how can i limit input to 6 decimal (max), and hide if they are 0??

**Comment by paulo-raca** [comment]
This seems to work: {digits: "0,6"}

**Comment by claudiogg88** [comment]
yes, thanks! excelent plugin!

**Comment by RobinHerbots** [comment]
@claudiogg88 , 

Actually this is a bug.  The workaround works but the digitsOptional true should result in the same behavior.  I will fix this.
