### ISSUE TITLE
Mask for number contains 5 or 9 digits?

### ISSUE THREAD

**Issue by plewasebastian** [RobinHerbots/Inputmask#101]
I need mask for numbers which contains 5 or 9 digits.
99999[9999] is not OK, because mask allow  for number contains 6, 7 and 8  digits, but only 5 or 9 digits is allowed.

Is it possible with current inputmask version?

Regards

**Comment by RobinHerbots** [comment]
Hi l0pez,

Yes and no, you need to help the plugin a bit.

create 2 masks 99999 and 999999999 and then you can bind on the keypress
event and depending on the length of the input you apply mask 99999 or
999999999

best regards,

Robin

2012/8/4 l0pez <
reply@reply.github.com
