### ISSUE TITLE
Could I set date inputmask like "dd-mm-yyyy", but retrieve "yyyy-mm-dd"?

### ISSUE THREAD

**Issue by thearabbit** [RobinHerbots/Inputmask#1013]
I would like to set `date inputmask` like `dd-mm-yyyy`.
But I want to retrieve `yyyy-mm-dd`.
Please help me.

**Comment by RobinHerbots** [comment]
@thearabbit , 

Implement onunmask and do the conversion

**Comment by thearabbit** [comment]
Excuse me, could example for me?

**Comment by thearabbit** [comment]
Now I base on `Meteor + Vue`, I work fine
