### ISSUE TITLE
how to custom "retrieve value"?

### ISSUE THREAD

**Issue by thearabbit** [RobinHerbots/Inputmask#1014]
I would like to custom the `retrieve value` like this

``` js
$(selector).inputmask('dd-mm-yyyy', ......)
// retrieve: yyyy-mm-dd
```

**Comment by RobinHerbots** [comment]
@thearabbit , 

Cuurently this is only possible by implementing the logic in the onunmask fn yourself.

I will make this possible for dates in milestone 3.4

**Comment by thearabbit** [comment]
Thanks for your reply.
I would like to custom retrieve value like `decimal number`

``` js
view: dd-mm-yyyy
get: yyyy-mm-dd
```

**Comment by thearabbit** [comment]
Now I base on `Vue`, it work fine
