### ISSUE TITLE
Dynamically switching mask in same input box not functioning as expected

### ISSUE THREAD

**Issue by csoseman** [RobinHerbots/Inputmask#1016]
I have a select box I'm using to determine the proper mask for a text input. What happens is that the direction (ltr/rtl) property of the mask seems to inherit the state of the initially selected mask if you switch/change between the 2. I have created a test case in jsFiddle with specific steps to recreate the issue. A big thank you in advance to anyone who could provide some valuable input!

Test Case: http://jsfiddle.net/csoseman/c6eLfcqp/

**Comment by RobinHerbots** [comment]
@csoseman , 

Sorry for the late reply, it seems that when you select local first, then it behaves correctly, but when you select the standard option first it behaves wrong. 

I will have a look at it this week.

best regards, 
Robin

**Comment by RobinHerbots** [comment]
@csoseman , 

Just upgrade to the latest version.

Have a look http://jsfiddle.net/c6eLfcqp/14/

**Comment by gkostov** [comment]
Hi, I'm trying to add/remove a % suffix depending on some criteria but updating with the "option" method does not work.
http://jsfiddle.net/23sm7err/7/

Seems the only way for now is to recreate the mask.

Cheers

**Comment by RobinHerbots** [comment]
@gkostov , 

The option method is intented for adding extra options like callbacks, etc at a later time to the mask.  Changing the mask itself or options which are used to generate the mask will not change the mask behavior.

**Comment by gkostov** [comment]
Oh, that explains it then. Thank you for the very quick response.

Not a great deal, but was wondering what the reason could be for this decision? It feels like a glitch there because the method does actually update the internal options hash. I use this like:

```
var inputMask = Inputmask({alias:'decimal', suffix:''}).mask(someElement);

// ... then later when I need to add the suffix
inputMask.option({suffix:'%'});  // only update "suffix" in the internal options hash
inputMask.mask(inputMask.el);  // rebuild the mask
```

which feels a bit hacky but does the job well :-)

Cheers

**Comment by RobinHerbots** [comment]
@gkostov , 

I did have a quick look at the option method and actually I did implement remasking, , I shall see why the above does not work without calling the remasking.

**Comment by RobinHerbots** [comment]
@gkostov , 

Have a try with the latest greatest  ;-)

**Comment by gkostov** [comment]
Works just fine now :-)

Great work, thanks!
