### ISSUE TITLE
Remove or Change Thousand/Decimal Seperator

### ISSUE THREAD

**Issue by mlhk2007** [RobinHerbots/Inputmask#1017]
I'm currently using the numeric alias to achieve
1500.00 m for 1500 metre, i would like to know is there anyway to remove or change the thousand and decimal separator as i'm developing a multi-language web app where thousand separator might be space or even . in different region of the globe

**Comment by RobinHerbots** [comment]
@mlhk2007 , 

use the radixPoint and groupseparator options to alter them.
