### ISSUE TITLE
IE8 - Member not found

### ISSUE THREAD

**Issue by reinos** [RobinHerbots/Inputmask#1018]
On IE8 I get this error using this jquery version http://code.jquery.com/jquery-1.11.3.js.

![image](https://cloud.githubusercontent.com/assets/633730/9439525/24d5cfce-4a68-11e5-86a4-411866a7579b.png)

Any idea?

**Comment by RobinHerbots** [comment]
@reinos , 

Can you create a jsfiddle for it as I cannot reproduce the problem.
