### ISSUE TITLE
Can't paste into input.

### ISSUE THREAD

**Issue by plewasebastian** [RobinHerbots/Inputmask#102]
Cannot paste text into input with set maxlength and mask in FF, Opera, Chrome, IE8.

**Comment by RobinHerbots** [comment]
Can you also provide a little example of the mask used?

best regards, 
Robin

**Comment by plewasebastian** [comment]
mask "999999999"
input field has placeholder "_________", maxlength set to 9

**Comment by plewasebastian** [comment]
How about this issue?

**Comment by RobinHerbots** [comment]
I fix it when I find some time. I am busy with other things right now.
Best regards
Robin
 Op 8 aug. 2012 11:21 schreef "l0pez" notifications@github.com het
volgende:

**Comment by plewasebastian** [comment]
ok, i look forward to the new version.

**Comment by RobinHerbots** [comment]
Hi lopez, 

Why do you specify the maxlength?  Do you need it for another plugin or something else or is it just to make sure that the input isn't more then the maximum allowed length.
Robin

**Comment by RobinHerbots** [comment]
checkout the latest version

Robin

**Comment by plewasebastian** [comment]
I set maxlegth always for input fields. Then I set inputmask only for required fields, and i wouldn't like edit html files once again and remove unneeded maxlengths.

I will check last version next monday, and i'll give feedback.

Sebastian

**Comment by plewasebastian** [comment]
Hi,

It seems to be OK. Thanks.

**Comment by plewasebastian** [comment]
I've found not error but small inconvenient. Paste to masked input field works OK, but if I drag and drop text to masked input, dragged text appear at the end of mask and disappear. It looks like:
"_________" CTR-C, CTR-V "121211221" -> OK
"_________' drag and drop '121211221" -> "_________121211221" and -> "_________" -> NOT OK

This inconvenient has been announced by users of web apps written by me.
It is small inconvenient for them.

Regards
Sebastian

**Comment by plewasebastian** [comment]
Annnnd I,ve found next error. If  I click label than I am in input assigned to label, but mask is not show.

Example:

```
  <label for="plant_cost_centre">Cost centre</label>
  <div class="fields"><input id="plant_cost_centre" maxlength="9" name="plant[cost_centre]" placeholder="_________" size="9" type="text" value="" /></div>
```

I hope it's last error that i found.

Regards

**Comment by RobinHerbots** [comment]
Hi Sebastian, 

Thx for the feedback.  I created 2 new issues for it.

I will close this one.

Best regards, 

Robin

**Comment by plewasebastian** [comment]
OK, Thanks..

Tomorrow i go on holiday. I will be back in September. In the free time I'll follow the progress.

Bye for now,
Sebastian

**Comment by RobinHerbots** [comment]
Have a nice holiday!!

I"m going to France (Frejus) next week on Holiday, so not much will happen
the next weeks ;-)

cya,

Robin

2012/8/13 l0pez notifications@github.com
