### ISSUE TITLE
Mask cleared on ajax submit or jquery unobtrusive validation error

### ISSUE THREAD

**Issue by reverence89** [RobinHerbots/Inputmask#1020]
I am using this plugin for phone number fields on my MVC app which uses Jquery, jquery unobtrusive validation, and jquery ajax validation from Microsoft (see screenshot of my scripts directory).

I've noticed an issue when you post the form or when you have a jquery validation on the input field, the mask is clearing and not coming back.

Please see video attached (http://www.fastswf.com/asJcSB4).

Here is the alias code I am using for the phone #:
    $.extend($.inputmask.defaults.aliases, {
        'customPhone': {
            'mask': ["999-999-9999","9-999-999-9999"],
            'autounmask': true,
            'placeholder': "**_-**_-____",
            'clearMaskOnLostFocus': false,
            'removeMaskOnSubmit': true
        }
    });

Is this an issue, or is there something I am doing wrong?
![2015-08-28_1306_jslibraries](https://cloud.githubusercontent.com/assets/5864485/9552391/b173655c-4d85-11e5-8ac2-05801836079e.png)

**Comment by reverence89** [comment]
@RobinHerbots Hi, since you added it to the Main label and a milestone, is that safe to say that it is an issue and will be fixed?

**Comment by RobinHerbots** [comment]
@reverence12389 , 

Yep, I will have a look at it and try to fixed it.

**Comment by RobinHerbots** [comment]
@reverence12389 , 

Fixed inthe latest version
