### ISSUE TITLE
Why does jquery.inputmask.js refer to the jQuery module as "jQuery", not "jquery"?

### ISSUE THREAD

**Issue by jonesnc** [RobinHerbots/Inputmask#1022]
[Line 9 of jquery.inputmask.js](https://github.com/RobinHerbots/jquery.inputmask/blob/3.x/dist/inputmask/jquery.inputmask.js#L9) refers to the jquery module as "jQuery", not as it's usual module name, "jquery". Is this a bug, or is there a specific reason for this?

The reason I ask is I'm getting incorrect behavior where requireJS is trying to import /base_path/jQuery.js instead of /correct/path/jquery.js, so it's not recognizing the module "jQuery" as it's defined in my require.config().

**Comment by RobinHerbots** [comment]
@jonesnc , 

Fixed.  That was a typo (bug)
