### ISSUE TITLE
Invalid JSON phone-uk.js

### ISSUE THREAD

**Issue by crberube** [RobinHerbots/Inputmask#1025]
I have this plugin installed via bower. The 3.2 update recently added phone-uk.js along with the other extra phone codes to the default install. This has completely broken everything because phone-uk.js is not a valid JSON file.

On line 202 I get the following error: "Uncaught SyntaxError: Unexpected identifier".

This file was originally introduced in this commit: https://github.com/RobinHerbots/jquery.inputmask/commit/626c7042d562eb2441b63d872e8dfa868c563616#diff-30a0f0bc1cf5ebb5f93d3c55ba118ea3R201

I'm not sure why the offending code was added but it either needs to be removed or modified to fit whatever purpose it was intended to serve.

**Comment by RobinHerbots** [comment]
How does it break everything?  Do you include it automatically?  I know the
phone-uk.js file is incomplete.

Op di 8 sep. 2015 om 19:44 schreef Christopher Berube <
notifications@github.com>:

**Comment by crberube** [comment]
I think I see what's going on here. I am using the [Rails Assets](https://github.com/rails-assets/rails-assets/) project which takes the bower.json file and automatically requires files listed in the _main_ directive (which is pretty standard as far as build tools go I believe). It looks like the phone-uk.js file has a bunch of placeholders at the bottom for masks that should be added in the future.

The problem stems from the fact that these placeholders are not commented out. It tries to parse the JSON file but then runs into invalid syntax. As this is a .js file, we can simply comment out everything beyond line 201. This seems to solve the issue for me.
