### ISSUE TITLE
Extra number after delete part of value and typing new number

### ISSUE THREAD

**Issue by mmilczewski** [RobinHerbots/Inputmask#1027]
This bug is very similar to #904.
Steps to reproduce:
1. I have a placeholder with **100,00**.
2. Delete only number before coma (**100**).
3. Start typing new value, for example **12**, then I got **121,00**.

However I think that in #904 solution isn't good too, because if I delete first number, I got **0,00** and caret is before whole number, so when i start typing, for example **1**, I got **1,00**, instead **10,00**, what I expect.

**Comment by RobinHerbots** [comment]
@mmilczewski ,

Can you make a jsfiddle for it.

The placeholder?  Do you mean an initial value or really the placholder?

**Comment by mmilczewski** [comment]
Yes.
Here: http://jsfiddle.net/qmemcvdb/

I mean initial value, not placeholder - my fault.

**Comment by RobinHerbots** [comment]
@mmilczewski , 

eu, ... i cannot reproduce the first issue.

**Comment by mmilczewski** [comment]
You have to mark **100** and then start typing new value.

**Comment by RobinHerbots** [comment]
@mmilczewski , 

This is fixed in the latest version
