### ISSUE TITLE
inputmask is not a function error after 3.2 update

### ISSUE THREAD

**Issue by reverence89** [RobinHerbots/Inputmask#1029]
Just upgraded my project to use the latest version (3.2), and I am getting an uncaught TypeError that inputmask is not a function.

```
$(".phone-number-field").inputmask();
Uncaught TypeError: $(...).inputmask is not a function
```

Here is the full code for configuring defaults:

```
$(document).ready(function () {
    // Hidden fields on accordion still validate
    $.validator.setDefaults({
        ignore: [],
        // any other default options and/or rules
    });

    Inputmask.extendDefaults({
        'autounmask': true,
        'removeMaskOnSubmit': true
    });

    Inputmask.extendAliases({
        'customPhone': {
            'mask': ["999-999-9999","9-999-999-9999"],
            'autounmask': true,
            'placeholder': "___-___-____",
            'clearMaskOnLostFocus': true,
            'removeMaskOnSubmit': true
        }
    });

    $(".phone-number-field").inputmask();
});
```

And the code used to configure the field with the custom alias:

```
@class = "phone-number-field", type = "tel", data_inputmask = "'alias' : 'customPhone'", placeholder = "___-___-____"
```

Here is a screenshot of my bundles config:
![capture](https://cloud.githubusercontent.com/assets/5864485/9769189/ab89b0ea-56f6-11e5-92dd-34a6e158bea1.PNG)

The question is, should jquery.inputmask.js AND inputmask.js be included, or both?

**Comment by RobinHerbots** [comment]
Both and you need to include jquery.inputmask.js after inputmask. Js

**Comment by reverence89** [comment]
Including inputmask.js BEFORE jquery.inputmask.js resolved my issue. Thanks.

**Comment by Zapnologica** [comment]
I have the following:

`   bundles.Add(new ScriptBundle("~/bundles/inputmask").Include(
            "~/Scripts/jquery.inputmask/inputmask.js",
            "~/Scripts/jquery.inputmask/jquery.inputmask.js",
            "~/Scripts/jquery.inputmask/inputmask.extensions.js",
            "~/Scripts/jquery.inputmask/inputmask.date.extensions.js",
            //and other extensions you want to include
            "~/Scripts/jquery.inputmask/inputmask.numeric.extensions.js"));
`

and I still get this error?

**Comment by RobinHerbots** [comment]
Remove the comment in the bundles .add

", //and other extensions you want to include "~/Scripts/jquery.inputmask/
inputmask.numeric.extens...

also did you reference the bundle in your page?
Did you include jquery?

Op di 30 jan. 2018 om 08:45 schreef Dylan <notifications@github.com>:
