### ISSUE TITLE
The DOM 'input' event is not triggered on inputmask field

### ISSUE THREAD

**Issue by ghost** [RobinHerbots/Inputmask#103]
http://dev.w3.org/html5/spec/common-input-element-apis.html#event-input-input

A form with text inputs, some use inputmask, others don't.

``` javascript
$form.on('input', '.textinput', function(){
   console.log('test');
});
```

Only non-inputmask fields trigger the callback for some reason.

Ubuntu 12.04, Google Chrome

**Comment by RobinHerbots** [comment]
Hi Chetzof, 
The input is not triggered because we return false in the keypress event when handling the masking; otherwise the input event interferes with the masking

Best regards, 
Robin
