### ISSUE TITLE
Browserify error: `Error: Cannot find module 'inputmask' from '/Users/.../node_modules/jquery.inputmask/dist/inputmask`

### ISSUE THREAD

**Issue by bioball** [RobinHerbots/Inputmask#1030]
I'm having an issue bundling this library into my project using Browserify. I installed the package via npm, and am on version 3.2.0. I'm getting this error:

```
Error: Cannot find module 'inputmask' from '/Users/.../node_modules/jquery.inputmask/dist/inputmask
```

And the code where I'm including this module looks like this:

``` js
require('jquery.inputmask')
```

Am I missing something here? Looks like the problem stems from this line in jquery.inputmask.js, where the modules are required via absolute paths:

``` js
"object" == typeof exports ? module.exports = factory(require("jquery"), require("inputmask"))
```

This could be fixed by changing the requires to:

``` js
"object" == typeof exports ? module.exports = factory(require("jquery"), require("./inputmask"))
```

I also noticed that the version of package.json in npm is missing `dependencyLib.js`, whereas the version currently in master is just including the entire `dist/` folder

**Comment by RobinHerbots** [comment]
@bioball , 

I looked at the specs and indeed the requires need to be relative when they are not packages.

Just your opinion.  I have a bundle file,  ...   when I add it to the files it will be included and picked up by browserify i guess....

**Comment by RobinHerbots** [comment]
@bioball , 

I updated the refs and the package.json.

Can you have try.

**Comment by bioball** [comment]
Seems to work fine now.

**Comment by bioball** [comment]
So I added a test for bundling with browserify! Did this to verify that your changes fixed things, feel free to merge if you'd like.
