### ISSUE TITLE
Decimal sign shifts when editing

### ISSUE THREAD

**Issue by sillentkil** [RobinHerbots/Inputmask#1032]
Hi i got a weird problem after i updated to the latest version when using mask.

i'm use the following html and script its just an simple version of what im using:
[input class="maskValuta2digits" type="text"  value="12.55]

$('.maskValuta2digits').inputmask('mask', {
  mask: '9{1,*}.99{1,1}',
});

When i select the 2 and change it so say 6 it changes from "12.55" to "165.5_"

if i use the following it is working as expected:

$('.maskValuta2digits').inputmask('mask', { 
  alias: "numeric",
  digits: 2,
});

**Comment by RobinHerbots** [comment]
@sillentkil 

Fixed in the latest version

**Comment by sillentkil** [comment]
You are the best, many thanks.
