### ISSUE TITLE
oncomplete not called when set with option function

### ISSUE THREAD

**Issue by brownbl1** [RobinHerbots/Inputmask#1033]
I'm attempting to set the `oncomplete` method using the new `option` function, but something seems to be going wrong.

``` html
<!DOCTYPE html>
<html>
<head>
  <title>Testing</title>

  <script type="text/javascript" src="jquery-1.11.2.js"></script>
  <script type="text/javascript" src="inputmask.js"></script>
  <script type="text/javascript" src="jquery.inputmask.js"></script>

  <script type="text/javascript">
    $(document).ready(function() {
      $("#my-val").inputmask("999-99-9999", {
        oncomplete: function() {
          console.log("howdy!");
        }
      });

      $('#my-val').inputmask('option', {
        oncomplete: function() {
          console.log("hello!");
        }
      });
    });
  </script>
</head>
<body>
  <input type="text" id="my-val" />
  <input type="text" />
</body>
</html>
```

calling `$('#my-val').inputmask('option', 'oncomplete')` shows that the function has indeed been updated to reflect the new `"hello!"` message, but when I actually complete the mask, it still logs the original `"howdy!"` message.

**Comment by brownbl1** [comment]
By the way, it seems that this is true for other options besides `oncomplete`.

For example:

``` js
$('#my-val').inputmask('option', {
  mask: '999'
});
```

seems also to not actually change the mask, but when you ask for the mask value using the `option` function, it gives you `"999"`.

**Comment by brownbl1** [comment]
@RobinHerbots I tried to follow the documentation you added for the `option` function, but am I doing it wrong? Also, if there are any options that you know for a fact work with this function, let me know and I can try my hand at a fix for this.

**Comment by RobinHerbots** [comment]
@itslittlejohn , 

Fixed,

**Comment by brownbl1** [comment]
Thank you! I will test out the new version.
