### ISSUE TITLE
Cannot read property 'matches' of undefined

### ISSUE THREAD

**Issue by pricejt** [RobinHerbots/Inputmask#1035]
I am getting this error in the console when i try to use a regular expression.  Am i doing something wrong?

```
var heightSelector = "input[name$='Height']";
var widthSelector = "input[name$='Width']";

var mask = "^\s*(((\d+)(\d{2})(\d{2}))|(([\d.]+)'?)?[\s-]*((\d+)?[\s-]*((\d+)\/(\d+))?\"?)?)\s*$";

$(document).ready(function() {
      if ($(heightSelector).length){
     $(heightSelector).inputmask(mask)
    }
if ($(widthSelector).length){
    $(widthSelector).inputmask(mask);
  } 
});
```

**Comment by RobinHerbots** [comment]
@pricejt , 

You need to use the regex extension to use regular expressions as a mask.  See https://github.com/RobinHerbots/jquery.inputmask/blob/3.x/README_regex.md

**Comment by pricejt** [comment]
@RobinHerbots Ok i am getting no errors now but my text box doesn't allow me to type numbers anymore only alpha characters. Here is my new code. 

```
if ($(heightSelector).length){
    $(heightSelector).inputmask('Regex', {regex: "^\s*(((\d+)(\d{2})(\d{2}))|(([\d.]+)'?)?[\s-]*((\d+)?    [\s-]*((\d+)\/(\d+))?\"?)?)\s*$" });
}
```

**Comment by RobinHerbots** [comment]
@pricejt , 

I will have a look at it
