### ISSUE TITLE
_getValue throwing error on form submit() after removing inputmask

### ISSUE THREAD

**Issue by gbronzer** [RobinHerbots/Inputmask#1036]
This is a peculiar scenario, I'll try to describe.

I have a AJAX loaded modal that loads some phone inputs that use inputmask. I then support allowing the user to disable the inputmask to enter international numbers. This is done via $(el).inputmask('remove'). When I submit the modal, I'm getting this JS error.

![image](https://cloud.githubusercontent.com/assets/5521279/9885809/1e3f9696-5bb5-11e5-9718-fb6b8752458a.png)

I tracked it down to the section of the function mask declaration shown below. Because inputmask was removed the `$el[0].inputmask._valueGet()` was failing. I simply added a check for `$el[0].inputmask` and it fixed the issue. The odd part is it doesn't seem to happen when the page is loaded normally, only when it's an AJAX loaded jquery modal.

**Note:** I am using Version: 3.1.64-180 due to another fix you made for me.

``` javascript
        function mask(el) {
            $el = $(el), opts.showTooltip && $el.prop("title", getMaskSet().mask), ("rtl" === el.dir || opts.rightAlign) && $el.css("text-align", "right"), 
            ("rtl" === el.dir || opts.numericInput) && (el.dir = "ltr", $el.removeAttr("dir"), 
            el.inputmask.isRTL = !0, isRTL = !0), $el.unbind(".inputmask"), ($el.is(":input") && isInputTypeSupported($el.attr("type")) || el.isContentEditable) && ($el.closest("form").bind("submit", function() {
                undoValue !== getBuffer().join("") && $el.change(), opts.clearMaskOnLostFocus && -1 === getLastValidPosition() && $el[0].inputmask._valueGet && $el[0].inputmask._valueGet() === getBufferTemplate().join("") && $el[0].inputmask._valueSet(""), 
                opts.removeMaskOnSubmit && $el.inputmask("remove");
            }).bind("reset", function() {
```

I fixed my version, but I thought you'd want to validate and make any proper changes to your codebase.

Thanks for the great work.

**Comment by RobinHerbots** [comment]
@gbronzer, thx for reporting!!  I shall see why it happens.

**Comment by RobinHerbots** [comment]
Upgrading to version 3.2 should fix it.
