### ISSUE TITLE
inputmask is not a function

### ISSUE THREAD

**Issue by gabrielcht** [RobinHerbots/Inputmask#1038]
While testing an asp.net MVC application firefox show:
TypeError: $(...).inputmask is not a function

This are my scripts

<script src="~/Scripts/jquery-1.10.2.min.js"></script>

```
<script src="~/Scripts/jquery.js"></script>
<script src="../../Scripts/jquery.inputmask/inputmask.js"></script>
<script src="~/Scripts/jquery.inputmask/jquery.inputmask.js" type="text/javascript"></script>
<script src="~/Scripts/bootstrap/bootstrap.min.js"></script>    

<script>
    $(document).ready(function () {
        $('#Telefono').inputmask('(99) 9999[9]-9999');
    });
</script>
```

**Comment by RobinHerbots** [comment]
Is the path to inputmask.js correct?   ../../scripts  the others state
~/Scripts/...

Op vr 18 sep. 2015 om 01:15 schreef gabrielchavezt <notifications@github.com

**Comment by gabrielcht** [comment]
Thanks RobinHerbots. I just need to configure bundle.cs and _layout
