### ISSUE TITLE
oncompleate set value incorrect action

### ISSUE THREAD

**Issue by serGlazkov** [RobinHerbots/Inputmask#1039]
If in "oncomplete" callback make setVal action with other masked input, you can see incorrect reactions in Chrome and Safary, well work in FF
Demo: http://jsfiddle.net/serGlazkov/nxLzq82o/

**Comment by RobinHerbots** [comment]
@serGlazkov , 

I updated the jsfiddle to the latest version of inputmask.

http://jsfiddle.net/nxLzq82o/1/   I see that the input looses focus.

**Comment by RobinHerbots** [comment]
@serGlazkov , 

Try again with the latest version
