### ISSUE TITLE
Visualize regular expressions

### ISSUE THREAD

**Issue by socrim** [RobinHerbots/Inputmask#1040]
Hi

We have evaluated a lot of plugins similar to yours but
jquery.inputmask ROCKS!!
Are there any plans to add visualization to your plugin?

Best
Mirco

**Comment by RobinHerbots** [comment]
@socrim , 

Thx  ;-)

Do you mean visualization to the regex extension?

**Comment by socrim** [comment]
Hi Robin, 

yes I mean visualizing the regex. E.g.: the mask would look like this, e.g. a
simple license code.

xxxx-xxxx-xxxx

A user would not have to type the dashes instead the cursor skips these and
forwards to the next position in the mask where user can enter something.
This would be a great extension to your plugin.

Best

Mirco

**Comment by RobinHerbots** [comment]
@socrim , 

.... and why can't you use a mask instead of a regex?

**Comment by socrim** [comment]
in our software regex is used to define a mask.

the problem we have is visualizing this mask.
I thought that this would be an extension to your plugin.

But, sorry if I did not understand your question right.

Best
Mirco

**Comment by RobinHerbots** [comment]
@socrim , 

Don't get me wrong, I was just asking.  

It is definitly a feature I want to add to the regex extension.  I just have to figure out which way to go.  Or translate the regex to a mask definition or analyse the regex and show a valid placeholder.
..

**Comment by socrim** [comment]
Hi Robin, 

probably translating the regex to a mask definition would be step 1 and showing
a placeholder like

12345-abcde-a1b2c3

where the fixed chars are somehow styled differently maybe like this:

12345-abcde-a1b2c3

then you start typing and what you type then looks like this.

0815-abcde-a1b2c3

What do you think?

Best

Mirco

**Comment by RobinHerbots** [comment]
@socrim , 

Can you provide the regex you want to use and I guess I dont see a styling difference?

**Comment by socrim** [comment]
I have attached the differences in style as attachment.

They propably did not make it through my email client.

**Comment by mririgoyen** [comment]
Would like to chime in on this feature request. We would greatly appreciate the addition of this functionality. All our validation rules are configured in RegEx and the visualization of the pattern (and the need to not type in things like hyphens, etc.) would be very helpful to our user's experience.

**Comment by RobinHerbots** [comment]
@socrim , @goyney , 

Finally there is some progress on this.
You can try with
Inputmask({ regex: "your regex" }).mask(selector);

There is no need for the extension anymore.
