### ISSUE TITLE
Decimal point/comma not working on Android 4.4

### ISSUE THREAD

**Issue by nsomlai** [RobinHerbots/Inputmask#1041]
`<form:input path="nHa" wstype="float1" size="5" class="ui-state-default"/>`

`$("[wstype='float1']").inputmask({alias: 'numeric', groupSeparator: ' ', radixPoint:',', autoGroup: true, digits: 1, digitsOptional: true, removeMaskOnSubmit: true});`

This simple mask works fine everywhere I tested, including my two Android 4.2 devices. However, it's not possible to enter the decimal part on my client's Android 4.4 devices. Both the comma and the dot key gets ignored.

The two devices in question:
- Vodafone Smart Tab 4G, Android 4.4.4, Chrome 33 or stock browser
- Samsung GT-I9195, Android 4.4.2, Chrome 28 or stock browser

Any workaround is appreciated until this gets fixed.

**Comment by afattahi54** [comment]
May be duplicate with 
https://github.com/RobinHerbots/jquery.inputmask/issues/898
https://github.com/RobinHerbots/jquery.inputmask/issues/897

**Comment by RobinHerbots** [comment]
@nsomlai ,  @afattahi54 , 

Can you retest with the latest version

**Comment by stealthjong2** [comment]
@RobinHerbots Is it possible this bug still exists? 

With both a Samsung GT-P5220 (Android 4.4.2) and a Nexus 7 (2013, Wifi, Android 6.0.1) I can't insert a dot/decimal mark on an alias:decimal or alias:numeric input (both stock browser, as I load it in a webview). The rest works as expected (no other chars except numbers, and minus sign).

`<input type='text' data-inputmask-alias='decimal'>`

`Inputmask().mask(document.querySelectorAll('input[data-inputmask-alias]'))`

On my computer (chrome 51.0), it works just fine. Using jquery inputmask 3.3.2-43 (bundle)

**Comment by Enfree** [comment]
@RobinHerbots
Still can reproduce under Android 4.4.2 and 5.0.0. Using inputmask 3.3.1

**Comment by carlossanabria** [comment]
Still can reproduce under Android 6.0.1. Using inputmask 3.3.2-65

**Comment by carlossanabria** [comment]
It is not a duplicate with 
#898
#897
