### ISSUE TITLE
$input is not defined in unmaskedvalue(input) function.

### ISSUE THREAD

**Issue by LukeFranky** [RobinHerbots/Inputmask#1043]
Chrome gives me the following error since updating to the latest version (3.2.1-55)...
Uncaught ReferenceError: $input is not defined

I tracked this down to line 694 of jquery.inputmask.bundle.js. This bug is in the unmaskedvalue(input) function. Renaming $input to input fixes the problem.

**Comment by RobinHerbots** [comment]
@LukeFranky , 

Thx for reporting.
