### ISSUE TITLE
Mask not cleared on mouseleave, when using showMaskOnHover

### ISSUE THREAD

**Issue by mboltuc** [RobinHerbots/Inputmask#1045]
I'm using v3.2.0,  I have a input with a date mask (mm/dd/yyyy) in a form.  When I submitted the form, it submitted the mask.  Upon investigation, it appears that if you hover over an element and then move the mouse out, the input mask does not get cleared.  Turning off, showMaskOnHover solved the issue for me.

**Comment by RobinHerbots** [comment]
@mboltuc , 

Can you make a jsfidlle with the exact mask and options as this should work.

best regards, 

Robin

**Comment by mboltuc** [comment]
I can't seem to reproduce in a jsfiddle, must be something wacky with our implementation.  I spend some more time with it later, and repost if I can reproduce outside our product.
