### ISSUE TITLE
iOS8, Safari when using Regex pattern is forcing caps lock

### ISSUE THREAD

**Issue by SomethingSexy** [RobinHerbots/Inputmask#1046]
I am using version 3.2.0 and I have the following regex pattern for an input field

```
"^[a-zA-Z '\\\\-]*$"
```

This being added via the 'Regex' property to a text field.  It seems on the iPhone that this is forcing the field to always being capitalized.  You can lowercase it manually, however it is ignoring the "autocapitalize" attribute and by default every character entered is capitalized. Has anyone else run into this problem?

**Comment by RobinHerbots** [comment]
@SomethingSexy , 

Can you create a jsfiddle with the exact mask used to make it more clear.

**Comment by ryr** [comment]
https://jsfiddle.net/g85gtfLx/6/
