### ISSUE TITLE
DependencyLib error in Internet Explorer

### ISSUE THREAD

**Issue by gthlopez** [RobinHerbots/Inputmask#1047]
Hi friend , I use this library with RequireJS , but when I use Internet Explorer, this dependence ( dependencyLib.js ) is throwing me the following error. Thanks for the input.
![captura](https://cloud.githubusercontent.com/assets/12861278/10036003/54f19a98-6166-11e5-950b-fc34d6187994.PNG)

**Comment by RobinHerbots** [comment]
@gthlopez , 

This is fixed.  Be aware that you still can use jquery as the dependency.  Have a look in the dist folder for other possible dependencyLibs.   The dependencyLib.js will be a vanilla javascript dependency but is still a WIP.  For the events I still rely on jquery.
