### ISSUE TITLE
I have a problems with mask input, I can't input Ukraine phone +380(XX)XXX-XX-XX

### ISSUE THREAD

**Issue by snizhok** [RobinHerbots/Inputmask#1050]
You can find this problem on you demo website. There is also problems with some other codes. I can't write three characters begining with +38. Can anyone help to find where is the problem. Thanks.

**Comment by ap-arto** [comment]
$("#phone").inputmask("+38(099)9999999", { greedy: false,
            "onincomplete": function(){ $(this).addClass("input-unvalid");},
            "oncleared": function(){ $(this).removeClass("input-unvalid");},
            "oncomplete": function(){ $(this).removeClass("input-unvalid");}
        });

**Comment by snizhok** [comment]
Thanks, but I need to use other codes too, so I need all functionality of mask, but mask for Ukraine and some other countries with codes +38.. is not working. I can't put third symbol to the input field besides "(". This is main problem. I need to use phone-codes.js file in my app. But input mask do not working with that file correctly.

**Comment by RobinHerbots** [comment]
@snizhok , 

I will have a look why the alternation fails.

also see #1051 & #1019

**Comment by RobinHerbots** [comment]
@snizhok , 

With the latest commit you can enter Ukraine numbers.  (+380)

Best regards, 

Robin
