### ISSUE TITLE
Deleting character from input with 'email' alias shifts all data

### ISSUE THREAD

**Issue by ivodopyanov** [RobinHerbots/Inputmask#1052]
See here: https://jsfiddle.net/xe23sw0x/1/ 
1) Type "zxc@vbn.com" in input
2) Set cursor between 'c' and '@'
3) Press backspace

Data in input I see: zxv@bnc.om
Data in input I expect: zx@vbn.com

Same if I delete character between '@' and '.' - data after '.' gets shifted too.
I'd like to be able to edit parts of email independently.

Same for 'mac' alias

**Comment by RobinHerbots** [comment]
@ivodopyanov , 

Again I agree ;-)

I will fix these.

**Comment by RobinHerbots** [comment]
@ivodopyanov , 

The above described issue is already fixed, but if you do delete instead of backspace you get zxcbn.com@_ which is not the expected zxc@bn.com

**Comment by RobinHerbots** [comment]
@ivodopyanov , 

2nd issue also resolved in the latest greatest ;-)
