### ISSUE TITLE
Distinguish empty value and '$ 0.00' value for currency alias

### ISSUE THREAD

**Issue by ivodopyanov** [RobinHerbots/Inputmask#1053]
See here: https://jsfiddle.net/jo7xxm9r/2/ 

1) click on input, type '1', press 'get value' button. Alert says '$ 1.00' - right
2) click on input, delete '1', type '0', press 'get value' button. Alert says nothing - wrong. 

I'd like to get '$ 0.00' value from input if user entered it manually and empty value if user haven't touched that field.

Same for 'percentage' alias

**Comment by RobinHerbots** [comment]
@ivodopyanov , 

I agree.

**Comment by RobinHerbots** [comment]
@ivodopyanov , 

Have a try with the latest

**Comment by ptutt1** [comment]
This seems to work for the use case described, however, how does one always return 0.00 whether the user has entered 0, or deleted the current value?
1. current value is 123.00
2. Tab to textbox and press delete key
3. Tab off text box

expected: .val() return "0.00"
actual: .val() returns ""

https://jsfiddle.net/jo7xxm9r/4/

To get around this, I added the following to my code:
`
$("input.currency").focusout(function () {
            if(!$(this).val())
            {
                $(this).val("0.00");
            }
        });`

**Comment by RobinHerbots** [comment]
@ptutt1 , 

So you would like to return 0.00 in case of 0 or null?

**Comment by ptutt1** [comment]
In my case, yes.  The model property is not nullable.  I understand that
this is not the desired behaviour of others...I was just wondering if there
was something that I could configure to produce that behaviour.

**Comment by RobinHerbots** [comment]
@ptutt1 , 

I was thinking in the same direction.  Something like a nullable option.

**Comment by ptutt1** [comment]
That makes sense to me.

**Comment by RobinHerbots** [comment]
@ptutt1 , 

nullable option added
