### ISSUE TITLE
Pasting to masked input not working on Android

### ISSUE THREAD

**Issue by paulpolushkin** [RobinHerbots/Inputmask#1061]
$('#cardnumber').inputmask('999999', {placeholder: ''});

1) Copy any number value to buffer.
2) Try to paste from buffer to masked input field (The field is empty initially)
3) The field is still empty. The cursor is set at the beginning of the field.

Android version: 4.2, 4.3
Browsers: Google Chrome 42 and above, Opera 32
Inputmask version: 3.2.0

**Comment by paulpolushkin** [comment]
Inputmask version: 3.2.0

**Comment by AlexanderMorou** [comment]
I can confirm this on an LG G2 with Android Version 5.0.2, using the built-in browser.

**Comment by RobinHerbots** [comment]
@paulpolushkin , @AlexanderMorou , 

Can you retest with the latest version

**Comment by Enfree** [comment]
Reproduced under

Android version: 4.4
Inputmask version: 3.3.0

https://jsfiddle.net/5adcra82/1/

**Comment by RobinHerbots** [comment]
@Enfree, 

Version  3.3.1 should work.

**Comment by Enfree** [comment]
@RobinHerbots,
It seems its not ;'(
https://jsfiddle.net/5adcra82/2/

**Comment by RobinHerbots** [comment]
http://caniuse.com/#feat=clipboard
