### ISSUE TITLE
Currency with autogroup and no digits not working

### ISSUE THREAD

**Issue by sdahbour** [RobinHerbots/Inputmask#1062]
If I use the following settings, things get a little bit crazy.  After a couple of keystrokes (often on the first keystroke), the cursor jumps all the way to the left and my keystrokes are prepended to the number - basically, it starts typing backwards.

alias: 'currency',
autoGroup: true,
digits: 0,

What I'm trying to achieve is a textbox that accepts currency in whole dollars (no decimal point or digits to the right).  I'd like to have commas every 3 digits.  It works fine when I remove the autoGroup or the digits, but using both causes a problem.

Am I doing something wrong? Or should this work?
Thanks!  (And thanks for an incredibly useful component!)

**Comment by sdahbour** [comment]
I found out a bit more.
The behavior happens when I attach another keypress (or keyup) event that actually sets a value on another textbox that has an input mask.  The scenario is there are multiple textboxes (all of which have a mask like the one above).  There is a keypress event set on all of the textboxes (except the last).  On  the keypress, a function will take the (numeric) value of each textbox, sum it up, and put it in the last box.  This seems to cause the problem.  

Thanks.

**Comment by RobinHerbots** [comment]
Can you create a jsfiddle for the scenario.  I will have a look on monday

**Comment by sdahbour** [comment]
Here is a jsfiddle that displays the issue:  http://jsfiddle.net/sdahbour/4d6eom3k/

I'm glad you asked for it.  I strip away all the stuff from my application to create a nice, easy to follow example that demonstrates the problem and isolated what actually causes the issue.

I have 4 fields with a mask.  When you type into the first 3 fields, a keypress handler sums up the 3 fields and sets the value into the 4th field (which also has an input mask and is readonly).  Simply typing into any of the 3 fields causes the problem.

There are different problems in different browsers.  Chrome (v 45.0.2454.93 m) moves the cursor to the left and starts typing backwards.  in IE (v 11.0.9600.17498) the cursor jumps into the 4th field.  And Firefox (v27.0.1) doesn't display the problem at all (although, the there's a delay if you type too fast).

If I remove the inputmask from the 4th field, the problem goes away.  Obviously, if I do that, then my 4th field won't be formatted, so that's a problem.  But it seems that setting the value of a masked field during a keypress (or keyup) event is causing the problem.

THANK YOU for looking into it.  And major thanks for a really great component.

**Comment by RobinHerbots** [comment]
@sdahbour , 

Can you have a test yourself.

Be aware that the deletes don't trigger the keypress.  There is also a callback onKeyValidation which triggers on every keystroke in the inputmask.

**Comment by sdahbour** [comment]
Perfect!  That works great.  And thanks for the note about deletes not triggering the keypress.  I'll switch back to keyup which does get triggered by a delete.  

Thanks again for an outstanding piece of software and for your responsiveness.

**Comment by ponmani** [comment]
@RobinHerbots 

I have tried to use globalized comma separated.  INR format wrongly showed. plz help me.

 $("#rate").inputmask("integer", {
                autoGroup: true, groupSeparator: ",", groupSize: 3, greedy: false, clearMaskOnLostFocus: true,
                removeMaskOnSubmit: true, autoUnmask: true
            });
