### ISSUE TITLE
Generating change event on Enter press

### ISSUE THREAD

**Issue by rommcr** [RobinHerbots/Inputmask#1063]
Now change event fired only when element losing focus. Is it possible to catch change event on Enter button press (like on standart HTML inputs)?

**Comment by RobinHerbots** [comment]
@rommcr , 

No it also fires when pressing enter after changes.

http://jsfiddle.net/k05L2zto/

**Comment by rommcr** [comment]
@RobinHerbots 
Since which version? I use version 3.1.63 (composer updates asset to this version), and this feature doesn't works.

By the way, in FF change action fires twice when pressing enter. Looks like lost focus fires the second one. May You fix it?

**Comment by RobinHerbots** [comment]
Since version 3.2

Op vr 9 okt. 2015 om 13:53 schreef rommcr notifications@github.com:

**Comment by rommcr** [comment]
@RobinHerbots 

Thanks. How about double change action in FF?

**Comment by RobinHerbots** [comment]
@rommcr , 

Can you create a new issue for it.
