### ISSUE TITLE
Missing comma in bower.json and component.json

### ISSUE THREAD

**Issue by sigra** [RobinHerbots/Inputmask#1064]
I got a syntax error in `bower.json`. I think this is due to a missed comma in one of the latest commit.

https://github.com/RobinHerbots/jquery.inputmask/commit/5adc6b8797a86cdd367a3b122880ea42d8ad77d4#diff-0a08a7565aba4405282251491979bb6bR14

**Comment by RobinHerbots** [comment]
@sigra , 

Yes I know.  Thx for reporting and version 3.2.2 is just released ;-)
