### ISSUE TITLE
Numeric aliases insert '0' in input after clearing if there was fraction part

### ISSUE THREAD

**Issue by ivodopyanov** [RobinHerbots/Inputmask#1067]
Small inconvinience, see here: https://jsfiddle.net/sdy342wd/

1) Write '123' into the input.
2) Select all data in input (with Ctrl+A, for example) and press Delete.
3) Input has nothing - right.

1) Write '123.123' into the input.
2) Select all data in input and press Delete.
3) Input has '0' instead of empty - wrong.

After that you can press Delete again and erase '0'.

**Comment by KrunchMuffin** [comment]
Further to this issue, in this demo https://jsfiddle.net/sdy342wd/3/ if you select the text then enter any one number or . (period), it will insert 2 periods.
