### ISSUE TITLE
How to unbind 9

### ISSUE THREAD

**Issue by Sepaka22** [RobinHerbots/Inputmask#1069]
I want my mask contains only integers.  It looks like "(999) 999-99-99"
But the second symbol must be 9. Not 8, not 7...
I tried to print like this "(\999) 999-99-99", but it was useless.

**Comment by RobinHerbots** [comment]
just double escape (\\999) 999-99-99

**Comment by Sepaka22** [comment]
i tried this too. But it's not workin.
![1](https://cloud.githubusercontent.com/assets/13955452/10381501/0451106c-6e24-11e5-8f57-a14a967af89c.png)

**Comment by RobinHerbots** [comment]
@Sepaka22 , 

Have a look at http://jsfiddle.net/7jhzf6oh/

**Comment by Sepaka22** [comment]
May be it's error only in yii2 widget?
http://www.yiiframework.com/doc-2.0/yii-widgets-maskedinput.html

**Comment by RobinHerbots** [comment]
@Sepaka22 , 

Possibly, maybe they need to update to a newer version of the inputmask.  I did some fixes for escaping chars in version 3.2

**Comment by samdark** [comment]
Yii uses 3.1.x. Is 3.2 compatible with 3.1?

**Comment by RobinHerbots** [comment]
Yep

Op vr 9 okt. 2015 om 12:58 schreef Alexander Makarov <
notifications@github.com>:

**Comment by samdark** [comment]
Updated. This issue should be closed, I guess.

**Comment by RobinHerbots** [comment]
@samdark , 

Ok thx
