### ISSUE TITLE
Doesn't work on Android

### ISSUE THREAD

**Issue by nfort** [RobinHerbots/Inputmask#1073]
it's doen't work if i use Android Browser on Sony Xperia, Samsung S3 (4.4.2), Samsung S5 (4.4)
http://grab.by/Lhyq

**Comment by dnasir** [comment]
I can confirm that this plugin doesn't work on the default Android browser on a Samsung Galaxy S4 (5.0.1). It behaves exactly as described by @nfort

**Comment by RobinHerbots** [comment]
@nfort , @dnasir , 

Can you retest with the latest version
