### ISSUE TITLE
Cannot get it to work at all, am I missing something ? - TODO UPDATE README

### ISSUE THREAD

**Issue by quorton** [RobinHerbots/Inputmask#1075]
I installed the package via nuget in VS 2015, added the bundle
 bundles.Add(new ScriptBundle("~/bundles/inputmask").Include(
                        "~/Scripts/jquery.inputmask/inputmask.js",
                        "~/Scripts/jquery.inputmask/jquery.inputmask.js",
                        "~/Scripts/jquery.inputmask/inputmask.extensions.js",
                        "~/Scripts/jquery.inputmask/inputmask.date.extensions.js",
                        //and other extensions you want to include
                        "~/Scripts/jquery.inputmask/inputmask.numeric.extensions.js"));
Just for testing I added In my layout 
input data-inputmask="'alias': 'date'" /><br />
input class="simple-field-data-mask-reverse" data-inputmask="'alias':'numeric'" /><br />
input class="simple-field-data-mask-reverse" data-inputmask="'alias': 'decimal'" /><br />
input class="simple-field-data-mask-reverse" data-inputmask="'mask': '99-9999999'" /><br />
@Scripts.Render("~/bundles/inputmask")

And nothing happens, they're just plain input boxes

**Comment by RobinHerbots** [comment]
you need to load the plugin

use something in document ready like  $(":input").inputmask();

**Comment by RobinHerbots** [comment]
Maybe I should write a binder to automate the hookup.

**Comment by quorton** [comment]
thanx, that did it
Maybe the readme could have been a little bit clearer about this, especially to someone new to JS/jquery
Or maybe a full example ?
But thanx for replying so quickly

**Comment by settysreekanth** [comment]
@quorton  @RobinHerbots i have similar sort of issue, could you please tell me what I am missing here, my plunker
http://plnkr.co/edit/RDLPxZVUXkvUXSIA9Cvm?p=preview

**Comment by AlexanderMorou** [comment]
@settysreekanth: Like RobinHerbots said: you need some startup code in your javascript to identify which inputs need the input mask to function.  In your sample: $('#test').inputmask();  However you also need additional input-mask based data annotations, or initialization properties, to indicate what limitations you want on the input element.  Read the documentation on the annotations to learn more.  Essentially most properties discussed if you prefix with: data-inputmask-%NAMEHERE% where %NAMEHERE% is replaced with the property will be your first step.

**Comment by AlexanderMorou** [comment]
@RobinHerbots 
If you add a binder to automate the hookup, is there any way that could be optional?

I use multiple input masks on certain inputs and is there a way to specify that without using your own binder?  Right now I specify it on a different data- parameter: data-input-masks delimited with ÿ, then I build the parameters for the initialization binder by hand.  Is there a way currently to specify the mask directly with multiple variations?  Using '(' around them and using an alternator '|' I don't think worked exactly as intended, unless I'm just doing it wrong...?

**Comment by RobinHerbots** [comment]
@AlexanderMorou , 

Can you provide an example to clarify what you mean exactly.
