### ISSUE TITLE
IE8 Null values after submit

### ISSUE THREAD

**Issue by reinos** [RobinHerbots/Inputmask#1076]
Hi,

this form https://risicofonds.nl/test/test has the following rules

``` javascript
$('.dform').each(function(){
    $(this).find('.field_name_bevoegd_gezagnummer').inputmask("99999", {removeMaskOnSubmit: true, autoUnmask: true});  //static mask
    $(this).find('.field_name_brinnummer_1, .field_name_brinnummer_2, .field_name_brinnummer_3, .field_name_brinnummer_4, .field_name_brinnummer_5').inputmask("****", {removeMaskOnSubmit: true, autoUnmask: true});  //static mask
    $(this).find('.field_name_datum_wijziging, .field_name_geboortedatum, .field_name_eerste_ziektedag, .field_name_datum_overlijden, .field_name_datum_ingang_betaald_ouderschapsverlof, .field_name_geboortedatum_kind_waar_dit_verlof_betrekking_op_heeft').inputmask("d-m-y",{ "placeholder": "dd-mm-jjjj"});  //static mask
    $(this).find('.field_name_percentage_ziek_volledig_100, .field_name_percentage_ziek_hersteld_0').addClass('validate[max[100]]').inputmask("999", {removeMaskOnSubmit: true, autoUnmask: true});  //static mask
});
```

But in IE 8 it goes wrong, the field `brinnummer` get the value of `null`.

Any idea how this is possible?

**Comment by RobinHerbots** [comment]
Is this working within another browser?

Op di 20 okt. 2015 om 16:14 schreef Rein notifications@github.com:

**Comment by reinos** [comment]
Yes, chrome works fine and any other browser.

**Comment by RobinHerbots** [comment]
Ok, I will have a look at it.

Op 17:19 DI 20 Okt 2015 schreef Rein notifications@github.com:

**Comment by RobinHerbots** [comment]
@reinos , 

Can you have a try with the latest version

**Comment by reinos** [comment]
No luck...

I used this file, is that ok? https://github.com/RobinHerbots/jquery.inputmask/blob/3.x/dist/jquery.inputmask.bundle.js

**Comment by RobinHerbots** [comment]
Yes that is ok.

I tested on your form with ie11 in ie8 mode and ethe values are getting
submit.

![image](https://cloud.githubusercontent.com/assets/318447/10753706/2c514ca8-7c93-11e5-9a21-1d394dd9425b.png)

[image: pasted1]

Op di 27 okt. 2015 om 09:01 schreef Rein notifications@github.com:

**Comment by reinos** [comment]
What is you submit the form without any value posted. here on ie8 i`m gettings the values null back.

![image](https://cloud.githubusercontent.com/assets/633730/10757413/3ac0a136-7cab-11e5-9d51-5953cfa76f6a.png)

**Comment by RobinHerbots** [comment]
@reinos,

Ok, I can replicate it on browserstack and see the problem.  
In IE8 when you set null as value it converts it to a string "null" in real browsers it sets an empty string.

**Comment by RobinHerbots** [comment]
@reinos , 

Ok try again with the latest.

**Comment by reinos** [comment]
Yes that fixed the issue :+1: 

Thanks for your work!
