### ISSUE TITLE
upper/lower case handling in 'data-inputmask-*'

### ISSUE THREAD

**Issue by johnny-the-coder** [RobinHerbots/Inputmask#1079]
If trying to set inputmask property via html attribute 'data-inputmask-*' it does not work correctly if property name contains upper case characters e.g. insertMode.
See following jsfiddle: https://jsfiddle.net/wwLg6z35/

In my opinion it should work at least with lower case, i.e. 'data-inputmask-insertmode'.

**Comment by RobinHerbots** [comment]
@jmalkiewicz , 

All fixed ;-)

**Comment by jmalkiewicz** [comment]
Super! :)

________________________________

Capgemini Polska Sp. z o.o.,
Al. Jerozolimskie 96, 00-807 Warszawa,
Sąd Rejonowy dla M.ST. Warszawy, XII Wydział Gospodarczy Rejestrowy, nr KRS: 0000040605,
NIP: 526-11-84-467,
Wysokość kapitału zakładowego: 16.403.320,00 zł.
This message contains information that may be privileged or confidential and is the property of the Capgemini Group. It is intended only for the person to whom it is addressed. If you are not the intended recipient, you are not authorized to read, print, retain, copy, disseminate, distribute, or use this message or any part thereof. If you receive this message in error, please notify the sender immediately and delete all copies of this message.

**Comment by johnny-the-coder** [comment]
Super! :)
