### ISSUE TITLE
onincomplete not being called

### ISSUE THREAD

**Issue by lucianogreiner** [RobinHerbots/Inputmask#108]
Hello.

I am trying to integrate jquery.inputmask into AngularJS by creating a directive, and i am facing a problem regarding the callbacks.

I have a field with this simple mask "99" or "9[9]". For the first mask, the "onincomplete" callback is never called.
For the second one, with the optional second digit, neither the oncomplete or onincomplete callbacks are called after i do fill the first digit, not even when the field focus is lost.

How could i make it work? 

Thank you!

**Comment by RobinHerbots** [comment]
Hi, 

I will have a look at it.

best regards, 

Robin

**Comment by RobinHerbots** [comment]
Hi Luciano, 

Do you use the numericInput option or others?  Can you give me a an example

input.inputmask("99", {  which options

best regards, 

Robin

**Comment by RobinHerbots** [comment]
see issue 117
