### ISSUE TITLE
Option: clearMaskOnLostFocus

### ISSUE THREAD

**Issue by johnny-the-coder** [RobinHerbots/Inputmask#1082]
I would expect that when flag 'clearMaskOnLostFocus' is set to 'true' and I fill only a part of the mask, extra '_' characters would be removed on lost focus.  

See following jsfiddle containing example and explanation: https://jsfiddle.net/wwLg6z35/3/

**Comment by RobinHerbots** [comment]
@jmalkiewicz , 

It will only clear if the positions are optional.

https://jsfiddle.net/wwLg6z35/4/

**Comment by johnny-the-coder** [comment]
Ok, thanks for quick answer, I think the use of optional part will do the job in my case.
