### ISSUE TITLE
Samsung Android 5.0 & 5.0.1 problem with repeated numbers in phone and SSN masks

### ISSUE THREAD

**Issue by mreiden** [RobinHerbots/Inputmask#1083]
Using versions 3.2.3-16 and 3.1.63-47 of inputmask with numeric masks for phone and SSN causes problems on Android 5.0 / Chrome if you repeat a number.  Typing two of the same number garbles the data.  Works fine on iPhone and desktop browsers as well as the Chrome desktop device emulator.

Code used was simply:

```
$("#ssn").inputmask("999-99-9999");
$("#phone").inputmask("(999) 999-9999");
```

**Comment by atakangktepe** [comment]
+1

**Comment by RobinHerbots** [comment]
see #745
