### ISSUE TITLE
No-strict mask

### ISSUE THREAD

**Issue by xenaio-daniil** [RobinHerbots/Inputmask#1084]
Hello, i need to format some input without validation. EX: There is an input with mask: 99 99 999999. But if user don't follow it (e.g. enter some thing like this: 34SF247800) the input must allow this.

I found pre-solution by setting mask like (99 99 999999)|(*{+}) but it works only if input starts with non-numerical symbols.

Example on jsfiddle.net: http://jsfiddle.net/65wyLfkd/

**Comment by xenaio-daniil** [comment]
@RobinHerbots Can you give an advice about this?

**Comment by RobinHerbots** [comment]
@dekdegiv , 

I will have a look at it.

**Comment by RobinHerbots** [comment]
@dekdegiv , 

Have a look at http://jsfiddle.net/65wyLfkd/1/

**Comment by xenaio-daniil** [comment]
Thank you, @RobinHerbots. 
But it does not work propertly. You can see it on alt1 in your example: the string match first mask, but it formats like normal (without spaces). So in fact we got only one mask: *{+}. Or I don't understand something?
It works only if we set space after first 2 digits. And then we can't use letters after space. So if we have string like 80 KS 569434 we can't enter it.
If it will help you, this is for passport numbers.

**Comment by RobinHerbots** [comment]
@dekdegiv , 

For that you need the keepStatic option.  See readme

http://jsfiddle.net/65wyLfkd/2/

**Comment by xenaio-daniil** [comment]
Thank you, now it works awesome!
