### ISSUE TITLE
Object does not support property or 'getComputedStyle' method <=IE8

### ISSUE THREAD

**Issue by chrisscasta** [RobinHerbots/Inputmask#1085]
Hi Robin,

I´m get the error when the focus is set to the field:

Object does not support property or 'getComputedStyle' method

jquery.inputmask.bundle.3.2.3-9.min.js

Thanks for your help.

**Comment by RobinHerbots** [comment]
@chrisscasta , 

This should be fixed by getting the latest version from github.

Best regards, 

Robin

**Comment by chrisscasta** [comment]
Ready.

Thanks Robin.

Best regards.
