### ISSUE TITLE
formatting a <span>

### ISSUE THREAD

**Issue by punchi** [RobinHerbots/Inputmask#1086]
Tried (but failed) to inputmask a value for a < span >, it's possible?
`<span id="total" class="inputmask_moneda">1234567</span>`
--> 1,234,567.00

It looks "autoNumeric" plugin have the option, but I don't want to use 2 plugins, one for inputs (inputmask) and other to format <span> (autoNumeric), I'm already using jquery.inputmask

**Comment by RobinHerbots** [comment]
@punchi ,

Add the contentEditable="true" attribute. or do you just want to set the formatted value in the span?

**Comment by punchi** [comment]
Thank you! :D went back to "jquery.inputmask-3.2.2" too, looks like I was stuck with a dev version.
