### ISSUE TITLE
Provide a method to check if element is masked pattern

### ISSUE THREAD

**Issue by haovn** [RobinHerbots/Inputmask#109]
It will be perfect if there are a method to check if element is masked pattern.
I want to use this plugin with Jquery Validation. When user input a incorrect (incomplete) value, an error message is displayed beside element.

**Comment by RobinHerbots** [comment]
Hi, 

I will add this soon.

Best regards, 

Robin

**Comment by RobinHerbots** [comment]
Do you mean an method which indicates wheter the value of the element will be masked when retrieved?

**Comment by RobinHerbots** [comment]
checkout the hasMaskedValue fn in the dev branch
