### ISSUE TITLE
Wrong behavior for symbol delete in ip alias

### ISSUE THREAD

**Issue by ivodopyanov** [RobinHerbots/Inputmask#1092]
How to reproduce:
At your demo page: http://robinherbots.github.io/jquery.inputmask/
1) Input "123.123.123.123" into ip input
2) Position cursor after any '1' and delete it with backspace.
Value in input modifies into "123.2_3.123.123" (for corresponding '1') and even counts as 'complete'
If you delete any '2' then value will be "123.13_.123.123"

**Comment by ivodopyanov** [comment]
Similar bug is observed for optional group of symbols:
https://jsfiddle.net/yg3gkh6r/ 
If you enter "zxc1234" in input then delete 'c', value in input will be 'zx_-1234' and will be considered as completed.
This does not reproduce if optional group are last symbols in value - in that case placeholder symbol is deleted correctly

**Comment by RobinHerbots** [comment]
@ivodopyanov,

The optional part is seen as a whole.  
It should be more like this:

https://jsfiddle.net/yg3gkh6r/2/

but I see that the delete is not as expected.

**Comment by RobinHerbots** [comment]
@ivodopyanov , 

Ip mask is solved, but is still a problem With the optional mask in combination of the dynamic mask it seems.

**Comment by ivodopyanov** [comment]
Thanks.
Great work!
