### ISSUE TITLE
Performance with many fields

### ISSUE THREAD

**Issue by JeffJackrabbit** [RobinHerbots/Inputmask#1093]
I have a page with about 100 fields with a time inputmask ('h:s t') and takes about 4 seconds to render.  What is the recommended pattern to follow when using input mask on many fields to achieve the best performance?

**Comment by RobinHerbots** [comment]
@JeffJackrabbit , 

Can you make a jsfiddle with the page.  That makes it easier to see the behavior and fix some bottlenecks.

**Comment by JeffJackrabbit** [comment]
@RobinHerbots ,
Thanks for your response.  We ended using a "lazy init" strategy that is working well.

``` javascript
function addTimeMask(el) {
    if (!el.hasClass('maskapplied')) {
        el.addClass('maskapplied');
        el.inputmask('h:s t');

        //This is needed to get the placeholder to show up 
        //the first time it is focussed.
        el.focus(); 
    }
}

jQuery('input.timeMask').focus(function () {
    addTimeMask($(this));
});
```

**Comment by RobinHerbots** [comment]
@JeffJackrabbit , 

That is a solution but I still want to investigate to improve the performance.

**Comment by RobinHerbots** [comment]
@JeffJackrabbit , 

I did some testing and got a duration of 788 ms for 100 inputs

```
  var t0 = performance.now();
        Inputmask("h:s t").mask(document.querySelectorAll("#inputcontainer > input"));
        var t1 = performance.now();
        alert("Duratiion " + Math.round(t1 - t0) + " milliseconds.")
```

I will have a look how I can improve this.  Maybe the lazy init approach can help.

**Comment by osaris** [comment]
Same here, I have a form with 400+ fields and it takes something like 4000ms to init inputMask :-(

Using `$('.integer').inputmask('integer', { rightAlign: true });` rather than `data-inputmask` attribute is a little bit faster (2800ms rather than 4000ms).

**Comment by RobinHerbots** [comment]
@osaris , 

Do you always use the same mask for the 400+ fields or different masks?  I want to mimich the page so I can test to improve init performance.

**Comment by osaris** [comment]
@RobinHerbots some have no mask, most are integer and other are decimals.

**Comment by osaris** [comment]
@RobinHerbots don't know if it helps but it looks like most of the time is spent in garbage collection (according to Chrome devtools)

**Comment by RobinHerbots** [comment]
I got for 400 integer masks an init of  1514 ms.

I will further investigate to try to optimise
