### ISSUE TITLE
Missing jquery.inputmask.bundle.min.js

### ISSUE THREAD

**Issue by listepo** [RobinHerbots/Inputmask#1095]
@RobinHerbots why removed dist/min/jquery.inputmask.bundle.min.js?

**Comment by RobinHerbots** [comment]
@listepo, 

Ah, I will put it back

**Comment by listepo** [comment]
:+1:

**Comment by listepo** [comment]
github tag 3.2.3?

**Comment by RobinHerbots** [comment]
Soon

Op wo 4 nov. 2015 om 15:27 schreef Ivan notifications@github.com:
