### ISSUE TITLE
It is not possible to edit the email

### ISSUE THREAD

**Issue by carlagromero** [RobinHerbots/Inputmask#1102]
Hi Robin!

Please, could you try this
https://jsfiddle.net/f1dhs1xm/

Once entered the email I cannot edit what is before the @
It's weird because it is a simple expression "[a-z0-9]+"
(I tried with a lot of expressions)

Thanks!

**Comment by RobinHerbots** [comment]
@carlagromero , 

Can you retry with the latest version?  Is this browser specific?  Tested in Chrome and I see no problem.
