### ISSUE TITLE
Definition {_} throws an exception

### ISSUE THREAD

**Issue by ivodopyanov** [RobinHerbots/Inputmask#1106]
I've tried $(...).mask(MASK), where MASK = 'a{_}', '9{_}', 'aa-9{_}' - they all throw exception with text "Inputmask: There is probably an error in your mask definition or in the code. Create an issue on github with an example of the mask you are using."

Is that syntax correct?

**Comment by RobinHerbots** [comment]
@ivodopyanov , 

You need to escape the { and }

**Comment by ivodopyanov** [comment]
No, I wanted to use {_} as dynamic mask. 
{+} definition works but {_} doesn't

**Comment by RobinHerbots** [comment]
ANd what should the {_} mean?  it should be +, \* or n,m

**Comment by ivodopyanov** [comment]
Ah. It seems read.me file is a bit outdated. It says "Also {+} and {_} is allowed. + start from 1 and _ start from 0."
* should be instead of _, right?

**Comment by RobinHerbots** [comment]
@ivodopyanov , 

It seems that atom-beautify the \* converts to _ for a md file ;-(
