### ISSUE TITLE
static mask on td

### ISSUE THREAD

**Issue by afattahi54** [RobinHerbots/Inputmask#1110]
The static mask is not working on td with a class:

```
<td class="mask-date">930915</td> (This is not working! but others does)
<div class="mask-date">930915</div>
<span class="mask-date">930915</span>

$(".mask-date").inputmask("99/99/99");
```

sample at https://jsfiddle.net/9n7u4mk6/

**Comment by RobinHerbots** [comment]
@afattahi54 , 

Have a look at https://jsfiddle.net/9n7u4mk6/1/

This is because the td is not picked up by the jQuery selector.
