### ISSUE TITLE
write a global function for onKeyValidation

### ISSUE THREAD

**Issue by afattahi54** [RobinHerbots/Inputmask#1111]
Is It possible to make a global function mask which handles  "onKeyValidation" .

I try below but no luck:

``` javascript
Inputmask.prototype={
     "onKeyValidation" : function(result){
         if (!result){
             alert('Your input is not valid')
            }
    }
}

//This also didn't work
Inputmask.prototype.onKeyValidation=
         function(result){
            if (!result){
                alert('Your input is not valid')
               }
       }
```

**Comment by RobinHerbots** [comment]
@afattahi54 ,

use 
Inputmask.extendDefaults({
    onKeyValidation:
         function(result){
            if (!result){
                alert('Your input is not valid')
               }
       }
});

**Comment by afattahi54** [comment]
Thanks, it worth adding this to site documents ;)

**Comment by afattahi54** [comment]
Thanks! 

Here a tip which may be useful for some one ...

If the user tries to enter more data than input size, the mask plugin consider it as invalid key. So this may be useful:

```
function(key, result){
        var currentElement = $(this);
        if( currentElement.val().length >= currentElement.attr('maxlength')){
            return;
        } 
       console.log.....
}           
```
