### ISSUE TITLE
alias options from 'data-inputmask' is not used anymore

### ISSUE THREAD

**Issue by StennikovDmitriy** [RobinHerbots/Inputmask#1113]
This markup works in 3.1.34. Options _integerDigits_, _allowMinus_ and _allowPlus_ are applied to input. But in latest 3.2.3 release this is not works anymore.

``` html
<input type="text" class="inputmask" data-inputmask="'alias':'integer', 'integerDigits': 3, 'allowMinus': false, 'allowPlus': false" />
```

The issue is in importAttributeOptions function [inputmask.js:328](https://github.com/RobinHerbots/jquery.inputmask/blob/3.x/js/inputmask.js#L328)
_data-inputmask_ json data parsed in _dataoptions_. But this object used to populate only general inputmask options. Alias options is not populated from this json and stay with default values.

**Comment by RobinHerbots** [comment]
@StennikovDmitriy , 

Fixed!
