### ISSUE TITLE
Numeric extensions don't supported with vanilla DependencyLib

### ISSUE THREAD

**Issue by artptr** [RobinHerbots/Inputmask#1116]
Example: https://jsfiddle.net/kxrvzcxy/

Each 'keydown' event cause an error 'An invalid or illegal string was specified' at [line #92 of inputmask.dependencyLib.js](https://github.com/RobinHerbots/jquery.inputmask/blob/3.x/extra/dependencyLibs/inputmask.dependencyLib.js#L92). It caused by illegal calling at [line #392 of inputmask.js](https://github.com/RobinHerbots/jquery.inputmask/blob/3.x/dist/inputmask/inputmask.js#L932). After the commit 15c9202 there is no more `this` binding, but [inputmask.numeric.extensions.js](https://github.com/RobinHerbots/jquery.inputmask/blob/3.x/dist/inputmask/inputmask.numeric.extensions.js#L391) relies on that.

**Comment by RobinHerbots** [comment]
@artptr , 

Thx for reporting.  This was also a problem with other dependencyLibs, but they didn't bring it forward.
I will add the vanilla dependencyLib to the unittests.
