### ISSUE TITLE
Error: optionData.indexOf is not a function

### ISSUE THREAD

**Issue by KrunchMuffin** [RobinHerbots/Inputmask#1123]
I just updated from 3.2.3 to 3.2.4 and I am getting the error `optionData.indexOf is not a function` on line 38 on the bundle.
here is my mask
`data-inputmask="'mask': 9,'repeat':5,'showMaskOnHover':false"`

9 is numeric, so it's failing. if I do `optionData.toString().indexOf()` it works.

**Comment by RobinHerbots** [comment]
@KrunchMuffin , 

Can you first try with version 3.2.5 as there was some update concerning this.

**Comment by RobinHerbots** [comment]
@KrunchMuffin , 

Tested your mask and there is no problem with the latest version
