### ISSUE TITLE
jquery.inputmask don't read options from data-inputmask attribute

### ISSUE THREAD

**Issue by pmaxs** [RobinHerbots/Inputmask#1126]
Docs for jquery.inputmask https://github.com/RobinHerbots/jquery.inputmask#usage says that it is possible to configure plugin behavior via attribute data-inputmask, but this don't work for my code.

```
<script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.inputmask/3.2.4/inputmask/inputmask.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.inputmask/3.2.4/inputmask/inputmask.numeric.extensions.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.inputmask/3.2.4/inputmask/jquery.inputmask.js"></script>

<input id="currency1" data-inputmask="'alias': 'currency', 'groupSeparator': '', 'prefix': ''" />
<input id="currency2" />

<script>
    jQuery(document).ready(function() {
        jQuery('#currency1').inputmask();

        jQuery('#currency2').inputmask({
            'alias': 'currency',
            'groupSeparator': '',
            'prefix': ''
        });
    });
</script>
```

First input shows "$", but in code I've wrote that prefix should be empty "'prefix': ''"

**Comment by RobinHerbots** [comment]
@podbeltsev , 

This is fixed in the current version.  See changelog

**Comment by ponmani** [comment]
@RobinHerbots is it possible group seperator based on culture. for the example

jQuery.preferCulture("en-IN");
var price = jQuery.format("3867567659.8880", "n4");

"3,86,75,67,659.8880"

**Comment by RobinHerbots** [comment]
@ponmani , 

This could be possible and would be nice but this is currently not implemented.
Can you create e new issue for this?

**Comment by ponmani** [comment]
@RobinHerbots when will you implement. we have hosted in Live this kind of feature. The client was told us we need based on culture.
