### ISSUE TITLE
Numeric mask which allows TBD characters

### ISSUE THREAD

**Issue by srivshreya** [RobinHerbots/Inputmask#1127]
I have a requirement in which the user can either type numeric Amount for which I am using numeric alias or the user can type TBD (to be decided) if the amount is not yet decided.
Please help me with the issue

**Comment by RobinHerbots** [comment]
@srivshreya , 

Which extra options do you use for the numeric mask?

**Comment by srivshreya** [comment]
var mask = {
alias: 'numeric',
groupSeparator: ',',
autoGroup: true,
digits: pattern.indexOf('.00') > -1 ? 2 : 0,
digitsOptional: true,
//placeholder : '0',
rightAlign: false,
prefix: pattern.indexOf('$') > -1 ? '$ ' : void 0,
greedy: false,
integerDigits: pattern.indexOf('l') > -1 ? 11 : 10,
allowMinus: false
}
These are the options I am using.

**Comment by srivshreya** [comment]
Is there a way we can achieve or is there any enhancement needed?

**Comment by RobinHerbots** [comment]
@srivshreya , 

You will need to extend the numeric alias for this
as mask you will need (the generated mask from the numeric alias)|(TDB)

I will have a quick try and will post it here

**Comment by srivshreya** [comment]
Thanks @RobinHerbots . I'll try from my side as well. Do post the code, if it works from your end.

**Comment by RobinHerbots** [comment]
@srivshreya , 

Try something like 

``` javascript
Inputmask("numeric", {
            mask: function(opts){
                var baseMask = Inputmask.prototype.defaults.aliases["numeric"].mask.call(this, opts);
                return "(" + baseMask + ")|(TBD)";
            },
            onBeforeWrite:  function (e, buffer, caretPos, opts) {
                if(buffer.indexOf("T") === -1){
                    Inputmask.prototype.defaults.aliases["numeric"].onBeforeWrite.call(this, e, buffer, caretPos, opts);
                }
            }
        }).mask("test1");
```

**Comment by srivshreya** [comment]
That's awesome. But when I enter TBD, I am not able to remove. I mean , I enter 12345 and it gets formatted. I then delete it and then enter TBD. But if I try to delete TBD and enter numbers again , I am unable to do so.

http://jsfiddle.net/8Jpdd/1314/

**Comment by RobinHerbots** [comment]
I will fix that, but then you owe me a beer ;-)

**Comment by RobinHerbots** [comment]
@srivshreya , 

I tried your fiddle in google chrome and I an able to renenter numbers after the TBD

**Comment by srivshreya** [comment]
Hey, Yeah actually it wasn't working as i was trying on my Android phone. That's not an issue. I checked in computer. It does work. But there is just one issue. When i remove or delete a number the commas are removed. How can i resolve this. And yes, I definitely owe you a beer :)

**Comment by RobinHerbots** [comment]
@srivshreya , 

There seems to be a problem with the caret positioning.

That will need a much closer look.

**Comment by srivshreya** [comment]
Thanks. I really appreciate your help!

**Comment by srivshreya** [comment]
Hey. I removed onBeforeWrite and it seems to work.
Can you have a look once? Why am I not able to type 'd' for "tbd"
http://jsfiddle.net/8Jpdd/1319/

Also, I am using https://cdnjs.cloudflare.com/ajax/libs/jquery.inputmask/3.2.4/jquery.inputmask.bundle.min.js
in my project.
3.2.4 version. This version seems to be creating problem. :(

Fiddle using 3.2.4 version of lib http://jsfiddle.net/8Jpdd/1320/

There is one more issue, if I make autounmask:true, then i don't get any value if I enter TBD. I want TBD to be saved as value. Can autounmask be conditional depending on the input.

**Comment by srivshreya** [comment]
Also, I am using https://cdnjs.cloudflare.com/ajax/libs/jquery.inputmask/3.2.4/jquery.inputmask.bundle.min.js
in my project.
3.2.4 version. This version seems to be creating problem. :(

**Comment by srivshreya** [comment]
@RobinHerbots 

I tried to resolve the issues. I succeeded to some extent but not sure if its the right approach.
http://jsfiddle.net/8Jpdd/1321/

There seems to be a problem with decimal. Something goes wrong when i put decimal. I guess caret position is the culprit

Quick help will be highly appreciated.

**Comment by RobinHerbots** [comment]
@srivshreya , 

Ah we forgot to return the result of onbeforewrite.

Have a look at http://jsfiddle.net/8Jpdd/1322/

**Comment by srivshreya** [comment]
This almost resolved all my issues, except the lib version issue https://jsfiddle.net/8Jpdd/1323/ Doesn't seem to work with 3.2.4 version. I have been using this version in my project. Can you give me a quick fix for this as well?

**Comment by RobinHerbots** [comment]
Just upgrade?

Op 06:36 WO 4 Mei 2016 schreef srivshreya notifications@github.com:

**Comment by srivshreya** [comment]
Yeah. But I am using percentage and other max , min functions of this lib. And the behaviour is different for them in upgraded version.

In 3.2.4 it doesn't allow me enter me more than 100 % but in 3.3.1 it allows me to enter but rounds of. I want the first behavior.

**Comment by srivshreya** [comment]
ok. So i upgraded the library. So i had metioned this use case, if I make autounmask:true, then i don't get any value if I enter TBD. I want TBD to be saved as value. Can autounmask be conditional depending on the input.
Even if i remove the autoUnmask, I dont get TBD value on element.val()

how do I handle this?
http://jsfiddle.net/8Jpdd/1325/

Hopefully this is the last time I am bugging you. Its a little ugent.

**Comment by RobinHerbots** [comment]
@srivshreya , 

IHave a look at http://jsfiddle.net/8Jpdd/1329/

**Comment by srivshreya** [comment]
@RobinHerbots

Thanks a lot Robin! I really appreciate your help!
