### ISSUE TITLE
jQuery(element).change() not call complete\incomplete methods in inputmask

### ISSUE THREAD

**Issue by FRAGnatt** [RobinHerbots/Inputmask#1129]
jQuery(element).change() not call complete\incomplete methods in inputmask

**Comment by RobinHerbots** [comment]
@FRAGnatt , 

What is the issue?  Can you better explain.

**Comment by FRAGnatt** [comment]
When I have element with mask for example

jQuery('#myElem').inputMask({
'mask':'#{1,3}',
'oncomplete' :function(){console.log(1)}})

When After inputMask is completed, I want to revalidate my inputmask.
In previously version I used jQuery('#myElem').change(). And my callback was called. But in version 3.2 I had problem with it.

Actually it's a bad that a new version with bugs and not compatible with old

**Comment by RobinHerbots** [comment]
@FRAGnatt , 

Hmmm I never had an event binding to the change event, ...  In which version was this behavior?

Concerning your other remarks.  
It is impossible for me to test all cases with every release.  I only see that the unittests pass.  Be welcome to contribute to the unittests!

**Comment by FRAGnatt** [comment]
Hmmmm. Sorry, I think it is mistake my old code. At now I test jQuery().change() at version 3.1.63 And it's not work. Sorry, I think I made a mistake when I wrote this issue.
Can you help me? How I can trigger event to validate my input with inputmask ?  Not validate him, not use method isComplete. I want trigger my callback from the outside. The event  onincomplete or oncomplete, or maybe onkeydown

**Comment by RobinHerbots** [comment]
@FRAGnatt , 

Try with    $(selector).trigger("setvalue.inputmask");
