### ISSUE TITLE
Change the default datetime extensions validation

### ISSUE THREAD

**Issue by fabricioferracioli** [RobinHerbots/Inputmask#113]
The actual validation for dates allow only dates between 1900 and 2099, using the 'd-m-y' mask.
It's desirable to add a validation option as parameter, giving the desired years range.

**Comment by RobinHerbots** [comment]
Hi fabricioferracioli,

The yearrange option is added in the date.extensions

best regards, 

Robin

**Comment by fabricioferracioli** [comment]
Hello Robin.

Very good work man!

Thanks for your attention

On Thu, Jan 17, 2013 at 5:23 AM, Robin Herbots notifications@github.comwrote:

> Hi fabricioferracioli,
> 
> The yearrange option is added in the date.extensions
> 
> best regards,
> 
> Robin
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/RobinHerbots/jquery.inputmask/issues/113#issuecomment-12362010.

## 

Fabrício Ferracioli
-- about.me/fabricioferracioli --
-- @fferracioli --
