### ISSUE TITLE
Double enter for submit

### ISSUE THREAD

**Issue by FrancoisPecasse** [RobinHerbots/Inputmask#1131]
Hello,

I have a problem to submit an input box.

My code is like this:

``` javascript
$(document).ready(function(){
    $("#code").inputmask("999999");  
});
```

``` html
<input id="code" type="text" name="code" placeholder="123456" maxlength="6" />
```

The mask works perfectly! But I need to press enter 2 times before it submits.
Anyone knows what I did wrong?

**Comment by RobinHerbots** [comment]
Can you create a jsfiddle for it, which shows and isolates the problem.

Op di 8 dec. 2015 om 11:38 schreef FrancoisPecasse <notifications@github.com

**Comment by FrancoisPecasse** [comment]
Hello,

Thanks for the quick reply.
http://jsfiddle.net/ewdk5gs5/

**Comment by RobinHerbots** [comment]
@FrancoisPecasse , 

Ok that makes it clear.  I will create a fix asap.

**Comment by FrancoisPecasse** [comment]
Thanks!

**Comment by victorwpbastos** [comment]
Please release a tag.

**Comment by RobinHerbots** [comment]
@victorwpbastos , 

I will do it very soon

**Comment by 4eRTyaka** [comment]
Hello,

i have the same problem, i tried 3.2.5 and 3.3.1 versions, does problem fixed?

Thanks!
