### ISSUE TITLE
Multiple masks scenario

### ISSUE THREAD

**Issue by RobinHerbots** [RobinHerbots/Inputmask#1132]
@aeont commented on 17 Feb
Hi!
Please check this http://jsfiddle.net/79m65yt3/2/ , I believe it's related.. 
We have masks like this: '0X XXXX XXXX' OR '04XX XXX XXX' OR '1300 XXX XXX' OR '1800 XXX XXX' OR '13X XXX' and they are working fine with version 2.5.10.. latest 3.1.61 doesn't.

Test cases which works on 2.5.10:
1) type 1300 than space - not allowed. i.e. 1300 000 000 not possible to enter
2) type 132 than space -132 000 not possible.

Thank you,
Vlad

**Comment by VolodymyrMuzyka** [comment]
@RobinHerbots Thank you! Tested on 3.3.2-106 - all works as expected
