### ISSUE TITLE
Initial value like VAA gets truncated to V-__ with mask like "I{1,3}-ZZ"

### ISSUE THREAD

**Issue by rgafaric** [RobinHerbots/Inputmask#1134]
I have masks like this "I{1,3}-ZZ", where 'I' and 'Z':
            Inputmask.extendDefinitions({
                'Z': { "validator" : "[A-Za-z]", cardinality: 1  },
                'I': { "validator" : "[ivxlcdmIVXLCDM]", cardinality: 1 }
            });
Then I put the correct value "I-AA" to my field with the mask. But when I focus to my field the last symbols "AA" are cleared

**Comment by xafizoff** [comment]
Actually, the problem described not quite well. If you apply mask with hypen symbol like `I{1,3}-ZZ` to the text field with unmasked value, symbols after hyphen are cleared.
How to reproduce:
1. Extend definitions like mentioned above.
2. Enter text `VAA` to the text field
3. Execute JS: `$(selector).inputmask('I{1,3}-ZZ')` -> text field value is `V-__`

**Comment by rgafaric** [comment]
Thanks, it works !
