### ISSUE TITLE
IE9 SCRIPT445: Object does not support this action 

### ISSUE THREAD

**Issue by jgi74** [RobinHerbots/Inputmask#1135]
Version: 3.2.6-11

with IE 9, I got this msg in the console ->

SCRIPT445: Cet objet ne gère pas cette action 
jquery.inputmask.bundle.min.js, Ligne 8 Caractère 19350

seems to be sthg relative to event??  ->  var d=new Event("keypress");d.which=b.charCodeAt(0),.....

my usage ->

var options = {
            prefix: "",
            groupSeparator: "'",
            digits: 0,
            min:minValue,
            max:maxValue,
            showMaskOnHover: false,
            showMaskOnFocus: false,
            clearMaskOnLostFocus: true
        };
$('.myClass").inputmask("currency", options);

(it was ok with version 3.2.6-11)

**Comment by RobinHerbots** [comment]
@jgi74 , 

Yes, I know.  I will fix that soon.
