### ISSUE TITLE
auto-casing regex mask

### ISSUE THREAD

**Issue by davemolton** [RobinHerbots/Inputmask#1136]
Is it possible to define a regular expression mask like so:

[0-9A-Z-_\$]{0,10}

and have the plugin auto-capitalize the input for the alpha characters instead of blocking non caps input?

I'm trying to duplicate behavior of the Devex TextEdit control defined with same mask which will do the auto-capitalization and I'm forced to use the RegEx options instead of A.

I have a fiddle with a mock up here: http://jsfiddle.net/dmolton/c0pvjaxu/

**Comment by RobinHerbots** [comment]
@davemolton,

It's been a long time since you opened the issue but have a look at the updated fiddle

http://jsfiddle.net/c0pvjaxu/2/
