### ISSUE TITLE
"-00" Allowed in Decimal Alias When digits:1 and digitsOptional:false Are Set

### ISSUE THREAD

**Issue by jmanos** [RobinHerbots/Inputmask#1137]
Using the following alias, I managed to get "00" in the input:

``` javascript
.inputmask({ alias: "decimal", digits: 1, digitsOptional: false, placeholder:"0" })
```

The input will, by default contain `0.0`. First enter `-` to change the input to `-0.0`. Then lose focus on the input which will change the value back to `0.0`. Then highlight the first `0` and enter `-`. This will change the value to `-.0` (this value is questionable, in my opinion). Again, enter `-` which will change the value to `-00`. Since digits should not be optional, this value is invalid.

As an aside, entering `-` a third time will produce `00.0` and any further `-` will toggle the negative sign on and off. And, of course, this can be done with `+` as well.

**Comment by RobinHerbots** [comment]
@jmanos , 

This is fixed in the current version on github
