### ISSUE TITLE
Firefox, Android - cursor jumps to the left in numeric mask 

### ISSUE THREAD

**Issue by barskuk** [RobinHerbots/Inputmask#1138]
On Firefox (Android) cursor jumps to the left if in numeric mask is found spaces, parentheses or dashes. On iOS no problem. I'm using the latest code.

**Comment by RobinHerbots** [comment]
@barskuk , 

Can you restest with the latest version.

**Comment by barskuk** [comment]
@RobinHerbots ,
Problem still exists.

**Comment by RobinHerbots** [comment]
@barskuk , 

Can you provide some fiddle with the exact settings used for the mask.

**Comment by barskuk** [comment]
@RobinHerbots ,
mask: +7 (999) 999-9999

**Comment by RobinHerbots** [comment]
@barskuk , 

Ok I can reproduce.  I will see how to fix it.

**Comment by barskuk** [comment]
@RobinHerbots ,
thank you!

**Comment by RobinHerbots** [comment]
@barskuk , 

I just retested this on android firefox and I cannot reproduce.  Can you confirm this is solved with version 3.2.7.

**Comment by barskuk** [comment]
@RobinHerbots ,
The problem is resolved, 
Thank you!
