### ISSUE TITLE
Store cents in database but enter and display currency via InputMask

### ISSUE THREAD

**Issue by andreasba** [RobinHerbots/Inputmask#1140]
Good evening,

thanks for your great plugin, it really boosts usability on the website, to well done! :-)

I have a question: I store currency amounts in cents, e.g. if a price is 22,90 EUR I store 2290 as the amount in my database.

Now I was wondering whether there is an easy way to display the cents I have saved as proper whole Euro/USD amounts by using input mask? Meaning I store 2290 but Inputmasks displays 22,90 EUR ir 1.548,99 in case of 154899.

Thanks
Andreas

**Comment by RobinHerbots** [comment]
@andreasba , 

I guess, just using the currency alias with the numericInput: true option will do or otherwise extend the onBeforeMask to add the radixPoint at the correct position.

**Comment by andreasba** [comment]
Thanks, that did the trick! :) :+1:
