### ISSUE TITLE
Show placeholder as user types

### ISSUE THREAD

**Issue by brownbl1** [RobinHerbots/Inputmask#1141]
Similar to issue #183, I would like to be able to hide the mask placeholder that has not yet been encountered by the user's typing. This is a common feature of many input masks and I think it would be a great addition (plus it's something that we really need). 

For example, I have a date mask where the placeholder is __/__/____.

Currently, when I focus on the input, the placeholder text shows. What I'd like to see is something like when the user enters: "12", what is shown is "12/" instead of "12/__/____". Continuing, if they kept typing so that what they had entered was now "12345", they would see "12/34/5" instead of "12/34/5___". 

I don't think it is possible to do this using some sort of non-greedy mask, since I still want it to validate against the full mask. Using an empty placeholder almost get's me what I want, but I still see "//".

Does that make sense?

I'd be willing to work on a pull request if this is something that the maintainers think is desirable and feasible.

**Comment by RobinHerbots** [comment]
@itslittlejohn , 

This reminds me to the story about VHS and betacam, ....

Anyway, I added the jitMasking option.  Set this to true, to disable the masking template.

best regards, 

Robin

**Comment by brownbl1** [comment]
Wow! Thanks.
