### ISSUE TITLE
error with min and max attributes on "integer"

### ISSUE THREAD

**Issue by aclaramonte** [RobinHerbots/Inputmask#1143]
using inputmask with "integer" and setting min 700 and max 1800  , when you try to write 800 runs well but if you start to writting 1200 when you put 120 and the last 0 the plugin change automatically to the minimun value 700, thats a bug i think, it has to wait to the number of digits of the max. 

alex.

**Comment by RobinHerbots** [comment]
@aclaramonte , 

I will review the min value setting

**Comment by ghost** [comment]
Sorry, I want to ask if you have to fix this bug in the latest version :)

**Comment by RobinHerbots** [comment]
@manhninh91 , 

Yes I will fix this soon ;-)

**Comment by ghost** [comment]
Thank you :)

**Comment by RobinHerbots** [comment]
@aclaramonte , @manhninh91 , 

FIxed in the latest on github

**Comment by aclaramonte** [comment]
Thank you very much, i update my inputmask version, and try the problem to see you fix it correctly, great plugin, and thanks for you effort.
Alex.

**Comment by aclaramonte** [comment]
works fine!! , thanks a lot!.
