### ISSUE TITLE
IE11 clear not working in emulated IE9 mode

### ISSUE THREAD

**Issue by juliocgs** [RobinHerbots/Inputmask#1144]
Hello,

I'm having the same problem described in issue #304 .
After clearing the field with IE 11's clear button, if the field gets focus again it is filled with the old value.
It only happens when forcing IE to emulate IE9 with meta tags and I need it that way.

I'm using version 3.1.63 and here is a fiddle(you will need to open IE developer tools and set it to emulate to IE 9):
https://jsfiddle.net/jlionheart/dw58gdj7/1/
Can you help me with that?

Thanks.

**Comment by RobinHerbots** [comment]
@jlionheart , 

In a real IE9 there is no clear button.  In the emulated the clear button does not trigger any events.  

I guess the best solution is the hide the clear button through css

**Comment by juliocgs** [comment]
That's not possible, emulated IE also does not recognize the CSS applied to hide the button.

And it does not seem to be a solution for this. As you can see in the link below:
https://connect.microsoft.com/IE/feedback/details/783743

I guess the only solution is to not render IE in compatibility mode.

Thanks.

**Comment by RobinHerbots** [comment]
@jlionheart , 

It is not perfect but have a try with the latest version on github.

**Comment by juliocgs** [comment]
I've tested it. It's no use.
Anyway, at least we tried. It's Microsoft's fault for not emulate the behavior correctly.

Thanks.
