### ISSUE TITLE
"1024" numeric with seperator issues

### ISSUE THREAD

**Issue by serlogo53** [RobinHerbots/Inputmask#1145]
hi 
i am using numeric with seperators.
when i input 1.024 saving db. after opening it shown 1,024 but 
123.123 after opening it it shown 123.123 do i making mistakes? please help.

opening : sending a input text from db.

**Comment by RobinHerbots** [comment]
@serlogo53 , 

Can you make a jsfiddle for it.  The exact mask implementation with the values.

Robin

**Comment by serlogo53** [comment]
hi. i think the problem is mysql locale. i am using  format(value/1024,0, 'en_GB').
when i remove format it's ok. thanks.
