### ISSUE TITLE
Integer min & max value

### ISSUE THREAD

**Issue by Aifz** [RobinHerbots/Inputmask#1146]
Hey Robin,

First of all, congratulations for this plugin that is really amazing and usefull.
I'm using the following configuration : 
'alias': 'integer', 
'min': '0', 
'max': '40', 
'allowMinus': 'false', 
'allowPlus': 'false'

When I set a value over the max value, you can't write the value at all (but you have no way to know what is the max value).
Is there a way you add an option true/false to force max value if value set is over max ?
That way, in my case, if user fill in 50, it automatically replace with 40 (max value).

I wish you a good day !

**Comment by RobinHerbots** [comment]
@Aifz , 

The current implementation will set the max value when leaving the field.

**Comment by adummy832** [comment]
Hi, is there an event I can hook up into this. Because i want to run a function after the value 50 has been replaced by 40, lets say run a custom function/alert() to notify user that this has only 40 max value in it? Thanks @RobinHerbots .
