### ISSUE TITLE
regex inputmask buffer issue

### ISSUE THREAD

**Issue by hliu0080** [RobinHerbots/Inputmask#1149]
Hi, I was using regex to mask a time format like 11:00 AM. After entering a valid time, if I move cursor to the middle of that field and start deleting using backspace, I won't be able to completely clear that field. Also I can't seem to enter any new value either. Not sure if it's a bug with the regex extension or if I'm doing something wrong with the expression. Please take a look and kindly let me know. Thank you.

JSFiddle: https://jsfiddle.net/6ekwhv5s/
Screencase: http://screencast.com/t/JVTMHYsyV8By

Thanks,
Han

**Comment by thebrambo** [comment]
It looks like it jumps back to its original position (where the bug happens) when your select a different position with the mouse onclick.

Following this for the fix,
Bram

**Comment by ghost** [comment]
So i have looked at the problem this is what i have found:
in the inputmask.js 
function w() {
            return void 0 == i().buffer && (i().buffer = h(!0, o(), !0)), i().buffer
        }

where buffer contains the characters, if people fill in a lot of text in a inputfield with Regex and then select a portion and delete it, the Buffer still holds the same size : for example
[a][b][c][d][" "][e][f][g]   <- [" "] is a spacebar
if you remove [c][d][" "] the array does continue to be 
[a][b][""][""][""][e][f][g]   <- [""] double quotes without space and the array is still the same size that is bugging the application. Im also looking at a solution, but maybe you can point me in the right direction what to search for.

**Comment by hliu0080** [comment]
Hey, thanks for looking into this. I wish i could help but I'm more of a back end PHP dev... I was able to print out the buffer like what you had in the example and see the problem, but Javascript just drives me crazy... sorry. I'll try to look more.

**Comment by rsteuber** [comment]
any progress on this one?

**Comment by RobinHerbots** [comment]
@hliu0080, @rsteuber, @ghost,

I plan to remove the regex extension as I'm adding support for regex mask directly in the inputmask core.

I will not look into the specific problem in the regex extension, but will use your case to further enhance the new implementation.

Current status see jsfiddle
https://jsfiddle.net/6ekwhv5s/3/

**Comment by RobinHerbots** [comment]
@hliu0080, @rsteuber, @ghost,, 

The regex is working now.  Have a look https://jsfiddle.net/6ekwhv5s/3/
