### ISSUE TITLE
TypeError: element is undefined on special keys

### ISSUE THREAD

**Issue by kumm** [RobinHerbots/Inputmask#115]
I've created a custom mask:
        'Z' : {
            validator: "[A-Za-z0-9/*-]",
            cardinality: 1,
            casing: "upper"
        }

applying to an input:
zz.inputmask({mask: "Z", repeat: 10, greedy: false });

I get an error on spceial keys (home,end, backspace etc....)

TypeError: element is undefined
setBufferElement(buffer=["", "8", "7", 2 more...], position=1, element=undefined)jquery...mask.js (line 328)
clearBuffer(buffer=["", "8", "7", 2 more...], start=0, end=5)jquery...mask.js (line 378)
checkVal(input=input.edit_input_req, buffer=["", "8", "7", 2 more...], clearInvalid=false, skipRadixHandling=true)jquery...mask.js (line 406)
(?)()jquery...mask.js (line 886)
[Break On This Error]   

elem = element.toUpperCase();
jquery...mask.js (line 328)

Returning from setBufferElement when element is null seem to fix this.

**Comment by RobinHerbots** [comment]
Hi Kumm,

I wil have a look at it.

Best regards,

Robin

2012/9/14 kumm notifications@github.com

**Comment by RobinHerbots** [comment]
Fixed in the latest version

best regards, 

Robin
