### ISSUE TITLE
UAE mobile phone numbers are not validated correct

### ISSUE THREAD

**Issue by emkookmer** [RobinHerbots/Inputmask#1151]
United Arab Emirates mobile phone numbers are not validated correctly,

When i use the demo and I enter 971512 it sees it as +971-5-12 instead of +971-51-2
I've was using Chrome on Windows and MacOSX

![screen shot 2016-01-11 at 11 33 54](https://cloud.githubusercontent.com/assets/1932444/12231378/421ebdd6-b857-11e5-803b-776d3b6182fc.png)

**Comment by RobinHerbots** [comment]
@emkookmer , 

I will have a look at it.

**Comment by RobinHerbots** [comment]
The same issue as #678

**Comment by RobinHerbots** [comment]
Remove Phone alias #1981
