### ISSUE TITLE
How to keep 0 as value on numeric

### ISSUE THREAD

**Issue by jeboersema** [RobinHerbots/Inputmask#1152]
How will I be able to keep the 0 value on the numeric mask when the control looses focus ?

Currently it clear the control if the value is 0.

Regards

**Comment by MrCsabaToth** [comment]
+1, same here

**Comment by MrCsabaToth** [comment]
This fiddle http://jsfiddle.net/csabatoth/SEXAj/2984/ demonstrates that while hovering over the input the "$ 0" is in it, but it disappears if we hover off. It stays in the input only if it is focused. I want the "$ 0" always in the box if it's empty. Hopefully we are talking about the same issue.

**Comment by jeboersema** [comment]
Yes. That is exactly the problem.

**Comment by jeboersema** [comment]
Maybe a option to specify an emptyValue that will display when the control is empty and the mouse is not hovering over the control or when the control is disabled (as in my case) ?

**Comment by RobinHerbots** [comment]
@jeboersema , @MrCsabaToth ,

Have a look at http://jsfiddle.net/SEXAj/2988/

**Comment by MrCsabaToth** [comment]
That jsfiddle looks like working, thanks @RobinHerbots . So we should just add "clearMaskOnLostFocus: false" to the mask configuration.
