### ISSUE TITLE
Conflict with jquery-placeholder on valHooks

### ISSUE THREAD

**Issue by oruchreis** [RobinHerbots/Inputmask#1153]
When we use inputmask together with jquery-placeholder plugin, they conflicts when the browser doesn't support placeholder attribute. For instance, in IE 9, any input with placeholder attribute are handled by jquery-placeholder plugin by valHooks."set". But if we apply inputmask on this input, then inputmask overrides the jquery-placeholder's valHooks.set, so if the browser doesn't support placeholder attribute, the plugin doesnt work.

**Comment by RobinHerbots** [comment]
@oruchreis , 

Can you provide a link to the jquery-placeholder.

**Comment by RobinHerbots** [comment]
@oruchreis ,

Is it https://github.com/mathiasbynens/jquery-placeholder/blob/gh-pages/jquery.placeholder.js?

I think it is the other way around.  The placeholder plugin overwrites the valhook without considering valhooks from other plugins.  My plugins respects the current implementation and extends it with what is needed for the inputmask.Can you try by loading&initializing the placeholder plugin first and afterwards apply the mask.  If that works open an issue with the placeholder plugin.

Can you also create a jsfiddle which shows the problem.  That makes it easier to investigate.

best regards, 

Robin
