### ISSUE TITLE
 JavaScript runtime error: Unable to get property '0' of undefined or null reference

### ISSUE THREAD

**Issue by MrCsabaToth** [RobinHerbots/Inputmask#1155]
This came after I upgraded 3.2.3 -> 3.2.5. I have several currency input fields with "$ " prefix, no decimal precision (so integer dollar values). When I have more of these inputs on a page and I rotate the focus with the mouse, I receive this JavaScript error.

Call stack:

>   getTest [inputmask.js] Line 330 Script
>     isMask [inputmask.js] Line 611  Script
>     clickEvent [inputmask.js] Line 1069 Script
>     Anonymous function [inputmask.js] Line 816  Script
>     jQuery.event.dispatch [jquery-2.2.0.js] Line 4731   Script
>     elemData.handle [jquery-2.2.0.js] Line 4543 Script

In the getTest the pos is -1. This lead back to the clickEvent line 1069 which had code change.

Downgrading solves the error. Is it possible that my inputmask configuration is faulty or weird, so modifying it could solve the error?

``` javascript
$(element).inputmask('decimal', {
      'alias': 'numeric',
      'groupSeparator': ',',
      'autoGroup': true,
      'digits': 0,
      'radixPoint': false,
      'digitsOptional': true,
      'allowMinus': true,
      'prefix': '$ ',
      'suffix': '',
      'placeholder': '0',
      'autoUnmask': true,
      'unmaskAsNumber': true
});
```

**Comment by MrCsabaToth** [comment]
I'm using the latest available NuGet package, 3.2.5

**Comment by MrCsabaToth** [comment]
I haven't been able to reproduce the problem in a JSFiddle yet. http://jsfiddle.net/csabatoth/SEXAj/2984/
It should have come just if we click from one input box to another. Now I'm thinking if some other JS library may interfere, I use bootstrap 3.3.6, the values are knockout bound to the controls (ko 3.4.0). I use numeral.js for formatting non editable elements. I use a whole bunch of other libraries, like mousetrap.js for hotkey handling.

**Comment by RobinHerbots** [comment]
@MrCsabaToth ,

Isn't this the same as #1133?

This is already fixed but not yet released.  Can you try by using the latest from github.

**Comment by MrCsabaToth** [comment]
I'll let you know as soon as I try it

**Comment by MrCsabaToth** [comment]
I tried the tree/3.x/dist (3 days old) and it cures the exception.

**Comment by RobinHerbots** [comment]
@MrCsabaToth , 

Ok great ! Fixed then in the next release
