### ISSUE TITLE
Issue with reset of inputmask field

### ISSUE THREAD

**Issue by andrelemos** [RobinHerbots/Inputmask#1157]
1) I created next input:
2) I created code in JS file:
$(":input").inputmask();

3) When I'm entering phone number and after reset form with method form.reset() all other fields are resetted and fields with mask too, BUT when mask field has focus, old value is restored.

**Comment by RobinHerbots** [comment]
@andrelemos , 

Due to a refactoring I wrongly binded the resetEVent.  I will push the fix soon.
