### ISSUE TITLE
Synchronous XMLHttpRequest warning/error

### ISSUE THREAD

**Issue by sverhagen** [RobinHerbots/Inputmask#1164]
Great plugin!

Chrome giving the following warning/error:

```
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.
```

When using the phone mask:

```
Inputmask('phone', {url: 'some-relative-address/phone-codes.json`})
```

With the following stack trace:

```
send (jquery-1.9.1.js:8492)
jQuery.extend.ajax (jquery-1.9.1.js:7978)
b.extendAliases.phone.mask (jquery.inputmas…ndle.min.js:10)
g (jquery.inputmas…undle.min.js:8)
b.isValid (jquery.inputmas…undle.min.js:9)
ContactDetailValueHelper.self.isValid (contactdetail.js:18)
...
```

Tried with jquery-1.9.1 and jquery-1.12.0.

Tried with jquery.inputmask.bundle.js version 3.2.6-33.

**Comment by ichepurnoy** [comment]
@sverhagen hi, I've across this warning too. We had a situation, where this even caused error,  in a case when the Ajax was not ready by the time the rest of the code was expecting it. 
_Ideally, imho, this is solved via Promises in javascript_, I just had no time to look deep in the lib.
Maybe @RobinHerbots could look into it someday. 

So far, I've simply moved the phone-codes.js right into the Inputmask.bundle, thus eliminating 1 Ajax call, so no warning/error, + a bit of speed-up.
If you like, I can share this primitive customisation, it's v.3.2.7, minified

**Comment by RobinHerbots** [comment]
@sverhagen , 

The phone alias is refactored to eliminate the synchronous ajax call
