### ISSUE TITLE
Time mask with fixed minute value

### ISSUE THREAD

**Issue by oliveiraddb** [RobinHerbots/Inputmask#1169]
Hi,

First of all i want to thank for this amazing plugin, it's one of the best plugins i've ever seem.
Second, i want to ask if there's a way i can set a time mask with a fixed value on minutes..

For example:

__:59

I'm trying but with no success.

Thanks

**Comment by RobinHerbots** [comment]
Include the inputmask.extensions.js and use

Inputmask("h:59").mask(selector);

**Comment by oliveiraddb** [comment]
I tried it but it doesn't worked for my.. A mask like this: h:5_ appears instead

**Comment by RobinHerbots** [comment]
I make you a jsfiddle tomorrow.

Op 18:58 WO 27 Jan 2016 schreef Danilo de Brito Oliveira <
notifications@github.com>:

**Comment by RobinHerbots** [comment]
@oliveiraddb ,

https://jsfiddle.net/vf8c0jus/
