### ISSUE TITLE
The clear icon (x) in the right side of the input only appear in IE

### ISSUE THREAD

**Issue by MrCsabaToth** [RobinHerbots/Inputmask#1172]
The x clear icon appears in IE when the input gets the focus, but doesn't appear on Chrome or FF.
Is that the -ms-clear pseudo element? https://stackoverflow.com/questions/14007655/remove-ie10s-clear-field-x-button-on-certain-inputs

**Comment by MrCsabaToth** [comment]
I may ask this in a different way: is there a way to make it appear on FF or Chrome?

**Comment by MrCsabaToth** [comment]
Tell me if it's not even inputmask scope issue.

**Comment by RobinHerbots** [comment]
@MrCsabaToth , 

This behavior comes from IE and is out of scope.
