### ISSUE TITLE
Completely does not work inputmask.js:607 error

### ISSUE THREAD

**Issue by sstyle** [RobinHerbots/Inputmask#1176]
inputmask.js:607 Uncaught TypeError: Cannot read property 'isGroup' of undefined

<script src="http://yandex.st/jquery/1.9.1/jquery.min.js" type="text/javascript"></script>

```
    <script src="js/inputmask.js" type="text/javascript"></script>
    <script src="js/inputmask.extensions.js" type="text/javascript"></script>
    <script src="js/inputmask.date.extensions.js" type="text/javascript"></script>
    <script src="js/inputmask.numeric.extensions.js" type="text/javascript"></script>
    <script src="js/inputmask.phone.extensions.js" type="text/javascript"></script>
    <script src="js/inputmask.regex.extensions.js" type="text/javascript"></script>
    <script src="js/jquery.inputmask.js" type="text/javascript"></script>
```

Same thing if I connect like this:
`<script src="http://yandex.st/jquery/1.9.1/jquery.min.js" type="text/javascript"></script>
<script src="jquery.inputmask.bundle.js"></script>`

**Comment by sstyle** [comment]
My mistake

**Comment by Artenes** [comment]
Leaving this reply for someone that encountered the same error:

This usually happens when you have a syntax error in your mask definition. Just review your mask and see if something is off.
