### ISSUE TITLE
min value issue

### ISSUE THREAD

**Issue by Aifz** [RobinHerbots/Inputmask#1177]
Hi,

I found out that if you set min: '5' and you want to type '40' it will automatically replace the 4 by 5 and doesnt care some value are filled in after typing 4.
I'm not sure if there is a trick or option to have it working as expected.

Please let me know, thanks !
PS: You are doing a really good job here.

**Comment by Skulli** [comment]
Not sure if its the same bug but i have very odd behaviour when using decimal and min/max definitions. With the latest version i am not able to type any radix values

```
$(".weight_input").not(".no_mask").inputmask 'decimal',
  placeholder: "",
  digits: 2,
  digitsOptional: true,
  min: 0,
  max: 399,
  radixPoint: ",",
  groupSeparator: ".",
  autoGroup: true,
  clearMaskOnLostFocus: false,
  removeMaskOnSubmit: true,
  autoUnmask: true,
  allowMinus: false,
  decimalProtect: false,
  suffix: "kg"
```

Thats my current definition for weight-input. If i remove the min/max-definition, everything gonna work again.

**Comment by osaris** [comment]
+1 I confirm the same bug

**Comment by serGlazkov** [comment]
reproduced at v3.3.3

**Comment by RobinHerbots** [comment]
@serGlazkov , 

What exactly is reproduced?  I retested and it works as expected.

Can you make a jsfiddle to make it more clear.

**Comment by serGlazkov** [comment]
@RobinHerbots sure, thats my example https://jsfiddle.net/z9cr9hng/

**Comment by RobinHerbots** [comment]
@serGlazkov , 

Ok and what is the problem?

**Comment by serGlazkov** [comment]
@RobinHerbots steps:
1) input value = 30
2) clear last number and not move focus from input field
**Current result**
value changing to 18
**Expected result**
value changing to 3

**Comment by RobinHerbots** [comment]
@serGlazkov , 

Ok, he should only check on blur.
