### ISSUE TITLE
min value for decimal isn't working

### ISSUE THREAD

**Issue by Aifz** [RobinHerbots/Inputmask#1178]
Hi,

I'm using the following tag : data-inputmask="'alias': 'decimal', 'radixPoint': ',', 'digits': '2', 'min': '0,3', 'allowMinus': 'false'"

This should prevent from setting values minor to 0.3 but I can type in 0.2 or any lower value.

Let me know if there is a trick or option to handle it. Thanks.

**Comment by RobinHerbots** [comment]
@Aifz , 

There are some issues with the numeric alias, I will deal with them at a later point.

For the above you should not set a quote around false

```
data-inputmask="'alias': 'decimal', 'radixPoint': ',', 'digits': '2', 'min': '0,3', 'allowMinus': false"
```
