### ISSUE TITLE
Can not clear value when select all and press BACKSPACE in some circumstance

### ISSUE THREAD

**Issue by majiangl** [RobinHerbots/Inputmask#1179]
You can recur this issue in in the official demo site: http://robinherbots.github.io/jquery.inputmask/ with following steps:
1. In the currency input, input 110.55
2. select all and press BACKSPACE, you can see value is not cleared, and cleared event is also not triggered.

**Comment by majiangl** [comment]
@RobinHerbots
I use your plugin in my project, I have to fix this problem. What do you think about this bug, will it take lots of effort to fix it? Can you give me some advise?

**Comment by RobinHerbots** [comment]
@majiangl , 

I will have a look at it.

**Comment by RobinHerbots** [comment]
@majiangl , 

Fixed

**Comment by majiangl** [comment]
Thank you, I'm very appreciated.
