### ISSUE TITLE
Array.prototype.indexOf causes IE to fail when using for in to loop around an array.

### ISSUE THREAD

**Issue by robjay** [RobinHerbots/Inputmask#118]
The Array.prototype.indexOf extension that has been added causes Internet Explorer to fail with the following type of code:

for (i in array) {
}

indexOf is being returned in the list, which may be undesirable if you are looping around a set of objects, expecting certain properties.

Would be preferable to use the jQuery.inArray function instead.

**Comment by sompylasar** [comment]
Would be preferrable to use a plain old `for` loop to loop through arrays:

```
var i, ic;
for (ic = array.length, i = 0; i < ic; ++i) {
}
```

To make looping through objects via `for..in` safe, the `hasOwnProperty` method call is required. It should also be polyfilled for older browsers.

```
for (i in obj) { if (obj.hasOwnProperty(i)) {
} }
```

**Comment by RobinHerbots** [comment]
robjay, 

I will refactor the plugin  to use $.inArray function.

sompyfasar, 

I agree ;-)

best regards, 

Robin

**Comment by RobinHerbots** [comment]
Hi robjay, 

In the dev branch you can find the refactoring.

best regards, 

Robin

**Comment by robjay** [comment]
Thanks for that, seem to work OK.
