### ISSUE TITLE
Mask not working in newest version of Android Chrome browser

### ISSUE THREAD

**Issue by tracyIcebreaker** [RobinHerbots/Inputmask#1182]
Wonderful plugin - 

I'm using it on my site for as a date of birth mask `__/__/____`.  It works fine in chrome on Android < 6, but in the newest version of Android it says `_valueGet()` is not a function, and I end up with an input that looks like this `01012010__/__/____`.

I traced this to:

`function mobileInputEvent(e) {
    var input = this, caretPos = caret(input), currentValue = input._valueGet();
    currentValue = currentValue.replace(new RegExp("(" + Inputmask.escapeRegex(getBufferTemplate().join("")) + ")*"), ""), 
    caretPos.begin > currentValue.length && (caret(input, currentValue.length), caretPos = caret(input)), 
    getBuffer().length - currentValue.length !== 1 || currentValue.charAt(caretPos.begin) === getBuffer()[caretPos.begin] || currentValue.charAt(caretPos.begin + 1) === getBuffer()[caretPos.begin] || isMask(caretPos.begin) ? inputFallBackEvent.call(this, e) : (e.keyCode = opts.keyCode.BACKSPACE, 
    keydownEvent.call(input, e)), e.preventDefault();
}`

where you're defining currentValue.  If I change it to input.inputmask._valueGet() then it works fine for new and older slightly older browsers.  I have tested this on Android 5.1.1 chrome, Android 6.0.1 chrome & firefox.  

I'm not sure why it wasn't input.inputmask._valueGet() in the first place, presumably you had a reason though.  I did not dig deep enough to see if _valueGet() was actually defined on the mobileInputEvent prototype somewhere, but Android 6 certainly doesn't think it's defined.

**Comment by RobinHerbots** [comment]
@tracyIcebreaker , 

You are correct that it should have been input.inputmask._valueGet().... but which version do you use, as in the current version the mobileInputEvent is already gone ;-)  When you want to use the inputmask on android, you definitely should take the latest version.  3.2.7

**Comment by tracyIcebreaker** [comment]
Wow I only installed it a month and a half ago!  I'm on version 3.2.5 which I obtained from bower.  Thanks for the info, I guess I'd better update. :)
