### ISSUE TITLE
input placeholder with a mask

### ISSUE THREAD

**Issue by dudo** [RobinHerbots/Inputmask#1183]
http://jsfiddle.net/ra542/290/

really, I'd just like to use `$('.money').inputmask('currency')`, but that example shows how I was trying to work around it. It's not really working as I would expect.

That being said, can we use the default input placeholder with a mask like 'currency'?

**Comment by RobinHerbots** [comment]
@dudo , 

Have a look at http://jsfiddle.net/ra542/292/
