### ISSUE TITLE
Plugin  causes unexpected behavior on Samsung Galaxy J 7

### ISSUE THREAD

**Issue by StraDIVar** [RobinHerbots/Inputmask#1185]
This problem occurs only on Samsung Galaxy J 7 (Android 5.1.1) with native keyboard (I think the keyboard is a problem).

How to reproduce:
I use mask `'9{0,8}'` for text input. 
Type on keyboard "123" - in the input you will see only "23"
But if you pressed backspace key - problem disappears until page is refreshed

I understand that it is very rare case but maybe you know how to fix it easy.

**Comment by RobinHerbots** [comment]
@StraDIVar , 

Only on the Galaxy J7  or only on android 5.1.1 ?

**Comment by StraDIVar** [comment]
On some another devices I can't reproduce this bug. But it reproduces also on **Samsung Galaxy S6** (I checked it on https://www.browserstack.com)

**Comment by RobinHerbots** [comment]
@StraDIVar , 

Just tried on browserstack using samsung S6 and don't see the problem.

Can you create a jsfiddle to test with or retry with the latest version.

**Comment by StraDIVar** [comment]
Thank you for your time, but now I don't see this bug. May be it was fixed in android or keyboard application. I think we can close it!
