### ISSUE TITLE
AutoUnmask not working on IE11 

### ISSUE THREAD

**Issue by vikasdomakunti** [RobinHerbots/Inputmask#1187]
On IE11 the autounmask function is not working. It is retrieving masked values even after the option is set true. Does the option not work in IE browser.

**Comment by RobinHerbots** [comment]
@vikasdomakunti , 

Can you provide some info.

The mask used and some context.  Maybe a jsfiddle.

**Comment by vikasdomakunti** [comment]
$("#callNumber").inputmask("(999) 999-9{4,46}",{autoUnmask: true});

This is the mask used.

**Comment by RobinHerbots** [comment]
@vikasdomakunti , 

And how do you want to retrieve the value?  by getting the value or on submit, ...

**Comment by vikasdomakunti** [comment]
I was checking on IE11 for autounmask option working or not.

Here is the fiddle https://jsfiddle.net/p1n4q6z1/6/

**Comment by RobinHerbots** [comment]
@vikasdomakunti , 

Have a look at https://jsfiddle.net/p1n4q6z1/7/

Use $.val instead of requesting the value property.

In chrome && FF it works with the value property because they allow to alter the native value property of the input.

**Comment by vikasdomakunti** [comment]
Thanks Robin that solved the problem.

**Comment by RobinHerbots** [comment]
@vikasdomakunti , 

I reviewed the value patch and it is now working for IE also.

Have a look at https://jsfiddle.net/p1n4q6z1/9/
