### ISSUE TITLE
Mobile Performance to Format

### ISSUE THREAD

**Issue by dougdomi** [RobinHerbots/Inputmask#1188]
Hi,

When I use Inputmask.format method....

`Inputmask.format('2000-40-20 08:15:59', {alias: 'datetime.dd/mm/yyyy hh:mm:ss'}) )`

Mobile devices takes 3~4 seconds to return the result. I tryied another masks too.

**Comment by RobinHerbots** [comment]
@dougdomi , 

Which version do you use?

Can you also give the code from the alias as it seems a custom alias.

**Comment by dougdomi** [comment]
I use the last version 3.2.7.

/\* Datetime Custom */

```
'datetime.dd/mm/yyyy hh:mm:ss': {
        mask: "1/2/y h:s:s",
        placeholder: "__/__/____ __:__:__",
        alias: "datetime",
        timeseparator: ":",
        hourFormat: "24",
        autoUnmask: 1,
        clearIncomplete: 1,
        onUnMask: function(maskedValue, unmaskedValue) {
            var date = maskedValue.split(' ')[0].split('/');
            var time = maskedValue.split(' ')[1].split(':');
            return date[2] + '-' + date[1] + '-' + date[0] + ' ' + time[0] + ':' + time[1] + ':' + time[2];
        },
        onBeforeMask: function(value) {
            var date = value.split(' ')[0].split('-');
            var time = value.split(' ')[1].split(':'); 
            return date[2] + date[1] + date[0] + time[0] + time[1] + time[2];
        }
    },
```

The datetime alias is from the current plugin mask version.

Thank you.

**Comment by RobinHerbots** [comment]
@dougdomi , 

On which mobile device do you test?  I tested the same and got +- 311 ms

**Comment by dougdomi** [comment]
Hi Robin,

LG Optimus L7 II .

**Comment by RobinHerbots** [comment]
@dougdomi , 

Can you make a fiddle which shows the measurement?
Is there a device on browserstack which compares to the LG Optimus l7 II?
