### ISSUE TITLE
error occurs in safari 9.0.3 (11601.4.4)

### ISSUE THREAD

**Issue by xukaifu** [RobinHerbots/Inputmask#1191]
http://jsfiddle.net/ra542/292/

![1 pic](https://cloud.githubusercontent.com/assets/574294/13133120/82d97dd0-d633-11e5-8e83-ca47423753f1.jpg)

**Comment by RobinHerbots** [comment]
@xukaifu , 

Safari 3.0.9 seems not to return a setter/getter while using Object.getOwnPropertyDescriptor or document.**lookupGetter**

So now it  uses a jQuery.valhook.
