### ISSUE TITLE
Can not change integer part when it is "0"

### ISSUE THREAD

**Issue by gharlan** [RobinHerbots/Inputmask#1192]
I use this:

``` js
element.inputmask('numeric', {
    digits: 2
});
```

Example: Initital value is "0.12".
Now select the "0", and type "3". Result is "30.12". Expected "3.12".

It works when the integer digit is non-zero. 
Or when the "0" is not selected, but the cursor is placed after "0", then it works, too.

**Comment by RobinHerbots** [comment]
@gharlan , 

FIxed in the latest version

**Comment by gharlan** [comment]
Thanks! But it does not work for me. Same behavior as before.
Version: 3.2.8-11

**Comment by gharlan** [comment]
I'm sorry. It works!!

But there is a new issue. When the value is `0.00`, and I select the first 0 (integer part), type `2`, I get: `200`. 
Expected: `2.00`

**Comment by RobinHerbots** [comment]
I will push the fix soon.

**Comment by RobinHerbots** [comment]
@gharlan , 

Fixed

**Comment by gharlan** [comment]
thanks!
