### ISSUE TITLE
Vanilla dependencyLib - does not trigger setvalue

### ISSUE THREAD

**Issue by RobinHerbots** [RobinHerbots/Inputmask#1193]

**Comment by dmitrykurmanov** [comment]
@RobinHerbots, hello, thank you for the library. Could you please tell how to trigger the "setvalue" event with vanilla dependencyLib?

**Comment by RobinHerbots** [comment]
Hi,

I got your question via email but I can't see the question on github?  It
it ok?

Op do 2 nov. 2017 om 12:07 schreef DUODVK <notifications@github.com>:

**Comment by dmitry-kurmanov** [comment]
@RobinHerbots, hello! I am sorry about it. I 've removed my question because I found the answer (may be this is the bad idea). I have a problem with ReactJS and now I don't sure that this is "inputmask" issue. Thank you for the fast responce.
