### ISSUE TITLE
Paste does not work properly when using numericInput

### ISSUE THREAD

**Issue by s-a** [RobinHerbots/Inputmask#1195]
On Chrome it does work as expected, but on IE11 nothing happens.

**Comment by s-a** [comment]
I just figuerd out that when I jump with the cursor to the 1.st position. It works as expected.

**Comment by RobinHerbots** [comment]
@s-a , 

Ah ok, can you provide some example of the mask you are using.

**Comment by s-a** [comment]
```
$(".formated-order-number:enabled").inputmask("R9999999999", {
    "placeholder": "0",
    "showMaskOnFocus": false,
    "numericInput": true
});
```

**Comment by RobinHerbots** [comment]
@s-a , 

It is due that the placeholder is a valid input for the mask.  when pasting at the end the masks is presented with for example.

R000000000123456789

Maybe I can fix this be stripping away the placeholder

**Comment by s-a** [comment]
@RobinHerbots I am using your plugin in production environment. Do you have any idea when you will publish a resolving release? By the way a NPM support would be great.

**Comment by RobinHerbots** [comment]
@s-a ,

There is already npm support.

When I publish a fix for it you can already pull the latest unreleased version from github.

**Comment by s-a** [comment]
I can confirm that this works now :+1:
