### ISSUE TITLE
Chrome, Android - cursor jumps to the left in phone mask

### ISSUE THREAD

**Issue by KimRoman** [RobinHerbots/Inputmask#1196]
On Chrome (Android) cursor jump to the left when we type number befor opening bracket in phone mask. Same problem has occurred in firefox and was resolved in issue #1138

**Comment by RobinHerbots** [comment]
@KimRoman , 

On which version of android and which version of chrome?

**Comment by KimRoman** [comment]
Android 4.1.2
Chrome 48.0.2564.95

**Comment by RobinHerbots** [comment]
@KimRoman , 

Can you provide some more info.  The mask used.  Can this be reproduced on browserstack? Or an emulator?

**Comment by jonimnim** [comment]
$("#phone").inputmask("+7(999) 999-9999", {"placeholder": "_"});
For such a mask in the Android 4.4.2 in chrome carriage does not move during the input and it turns out that the figures entered in reverse order. And when it comes to the end of the numbers can be entered next and the last removed.

**Comment by Enfree** [comment]
The same as #1205
http://plnkr.co/edit/d2zQVyZ4cmPRk3VvumAt?p=preview
Bug can be reproduced under Samsung S4 - Android 5.0.1 (Chrome), Nexus 5X - Android 6.0.1. (Chrome)

**Comment by ryr** [comment]
@Enfree ,
your example does not work for me too, but https://jsfiddle.net/g85gtfLx/5/ (3.3.1) and https://jsfiddle.net/g85gtfLx/6/ (3.x) works fine (chrome 52, android 5.1.1; redmi 3)

**Comment by RobinHerbots** [comment]
@KimRoman , @jonimnim , @Enfree , 

Is this still actual with version 4.x beta ?

http://embed.plnkr.co/hJ3mNFtmUaQGRlf4hbqq/

**Comment by jonimnim** [comment]
on version 4.x beta works on android 4.4 and 5.0 phones
