### ISSUE TITLE
Mask appear when I press TAB & showMaskOnFocus: false, showMaskOnHover: false

### ISSUE THREAD

**Issue by Topheur** [RobinHerbots/Inputmask#1198]
I have created two inputs text with the hh:mm mask with options showMaskOnFocus and showMaskOnHover to false to don't display the mask.

However when I fill my first input, press TAB to go to the second and type some numbers, the mask appear.

This is my code :

``` html
<input type="text" class="mask_time" value="00:00"/>
<input type="text" class="mask_time" value="02:00"/>
```

``` javascript
<script type="text/javascript">
$(document).ready(function(){
$('.mask_time').inputmask('hh:mm', {
showMaskOnFocus: false,
showMaskOnHover: false
}
);
```

});

**Comment by Sturtaz** [comment]
I too am experiencing this issue. The mask appears when field is focused via tab. showMaskOnFocus and showMaskOnHover are both set to false. The mask does not appear when clicking on the field or hovering over it.

**Comment by RobinHerbots** [comment]
@Sturtaz , @Topheur ,

Currently fixed in the 4.x branch.  It will be merged back to the 3.x also.
