### ISSUE TITLE
Characters disappearing and changing position upon input on Android stock browser Chromium (Samsung Mobile)

### ISSUE THREAD

**Issue by szaszendre** [RobinHerbots/Inputmask#1201]
Problem:

[See video of the issue](https://youtu.be/mjLmayg9MYs).

With the mask 
`"aa99 **** **** **** **** **** **** **** **"`
some characters disappear on input or change position
on the `Samsung Galaxy S3 GT-I9301I` Stock Browser.

However on the `Samsung Galaxy S2 Stock Browser` it works fine.

[See JSFiddle](https://jsfiddle.net/rzr999/t9q2xm8e/4/)

Browser: Stock Browser "Internet" Chromium (latest update)
App: `Internet 1.5.28 1528`
Version: `Chrome/28.0.1500.94`
Android: `4.4.2 GT-I9301I`

**Comment by szaszendre** [comment]
I think this will be very similar to #416.

**Comment by s-a** [comment]
My users also reporting such a behaviour. The Input completely disapears while my tests. 
I just connected with USB remote debugger to check whats going wrong where inputs from PC keyboard works as expected. So my guess is that input behavior differs from virtual mobile keyboard from the PC one. 

Any fast help is highly appreciated because I am using this plugin in production on a high traffic page.
I am using jquery.inputmask version 3.3.1.

**_My device info:**_  

```
Google Inc.
Copyright 2016 Google Inc. Alle Rechte vorbehalten.
Google Chrome   50.0.2661.89 (Offizieller Build) (32-Bit)
Ãœberarbeitung    78c36d241d8eebad599e33e13fe50f05393635ab-refs/branch-heads/2661@{#619}
Betriebssystem  Android 5.0.2; HTC One Build/LRX22G
Blink   537.36 (@78c36d241d8eebad599e33e13fe50f05393635ab)
JavaScript  V8 5.0.71.33
User-Agent  Mozilla/5.0 (Linux; Android 5.0.2; HTC One Build/LRX22G) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.89 Mobile Safari/537.36
Befehlszeile    --use-mobile-user-agent --top-controls-show-threshold=0.5 --top-controls-hide-threshold=0.5 --use-mobile-user-agent --enable-begin-frame-scheduling --enable-pinch --enable-overlay-scrollbar --validate-input-event-stream --disable-gpu-process-crash-limit --main-frame-resizes-are-orientation-changes --disable-composited-antialiasing --ui-prioritize-in-gpu-process --profiler-timing=0 --prerender-from-omnibox=enabled --enable-dom-distiller --flag-switches-begin --flag-switches-end --top-controls-show-threshold=0.5 --top-controls-hide-threshold=0.5 --top-controls-show-threshold=0.5 --top-controls-hide-threshold=0.5 --top-controls-show-threshold=0.5 --top-controls-hide-threshold=0.5
AusfÃ¼hrbarer Pfad    Datei oder Verzeichnis nicht vorhanden
Profilpfad  /data/data/com.android.chrome/app_chrome/Default
Build-ID    83b74c4c-a412-4c86-9c4c-9de3addf1634
```

**Comment by RobinHerbots** [comment]
@s-a , 

On most mobile devices, all input is detected throught the inputFallBackEvent as the other events are not triggered (from the android keyboard) and also to handle the input suggestions.  

Send me the mask used and an input example where it goes wrong.  Usefull is also which data gets to the inputevent and in which sequence.

**Comment by s-a** [comment]
Thanks for the fast reply.
I have tried to handle `inputFallBackEvent` like follows, but it does not trigger.  Have I instelled it correctly?
On my device every input goes to nirvana.

`datamask : "**********************"`

``` javascript

  Inputmask.extendDefinitions({
    '*': {
        casing: "upper",
        placeholder: " "
    },
    '9': {
        placeholder: " "
    }
  });

// ...
// document ready
      $(".masked-input").each(function(){
        var mask = $(this).data("mask");
        var im = new Inputmask(mask, {
            inputFallBackEvent: function () {
                console.log(arguments);
            }
        });
        im.mask(this);
      });

```

**Comment by s-a** [comment]
I successfuly hooked into 

``` javascript
            onKeyValidation: function () {
                console.log(arguments);
            }
```

here there goes nothing to console if I input values from mobile device.

**Comment by RobinHerbots** [comment]
@s-a , 

Nono, it's not an event but the eventhandler used inside the inputmask.js(   bound to the inputevent.

So basically see what happens inside tha handler.

**Comment by s-a** [comment]
I think it is reproducable at http://robinherbots.github.io/jquery.inputmask/ #demo #ipadress-example but irregular.   

The `If` condition here https://github.com/RobinHerbots/jquery.inputmask/blob/b5841950c5697314c61b2b20566f9d20d8fb1250/js/inputmask.js#L2417 return permanent false if input comes from virtual keyboard on smartphone.

**Comment by s-a** [comment]
![image](https://cloud.githubusercontent.com/assets/1270662/15072392/b68ff5f4-1392-11e6-9f04-63e170cd564b.png)

While "F" comes from PC Keyboard

**Comment by RobinHerbots** [comment]
@s-a , 

Can you reproduce it on browserstack?

Updated the fiddle from above https://jsfiddle.net/t9q2xm8e/6/
Can you add your mask to this fiddle.  I will have try.

**Comment by s-a** [comment]
what do you mean browserstack?

**Comment by RobinHerbots** [comment]
https://www.browserstack.com

**Comment by s-a** [comment]
there it works even from smart device. Sorry for the noise it seems it is something related to my own code .

**Comment by s-a** [comment]
sorry i have no browserstack account . tried at jsfiddle. 
just commented out my custom eventhandlers without success. could you see something suspicious? I missed to describe that my controls are created at runtime with handlebars.js

**Comment by s-a** [comment]
in `inputFallBackEvent` I wonder why is `e.which` is `undefined` isnt it the property holding the pressed key value?

**Comment by RobinHerbots** [comment]
@s-a , 

The inputfallback acts on the input event.

Can you send me your jsfiddle

**Comment by s-a** [comment]
https://jsfiddle.net/00sa/u9v761cg/2/

A friend reportet it works on his device. weird... 
![image](https://cloud.githubusercontent.com/assets/1270662/15074241/1eab8206-139e-11e6-9426-646cb2229def.png)

**Comment by RobinHerbots** [comment]
@s-a , @rzr999 , 

It this still an issue when using version  4.x beta?

**Comment by s-a** [comment]
Not anymore involved to the project now. Cannot say something about new version. Sorry.
