### ISSUE TITLE
Lost zero while replacing a digit in group

### ISSUE THREAD

**Issue by schmulschubiak** [RobinHerbots/Inputmask#1202]
I have an inputmask with radix, (20,00), when i select the "2" and replace it with another digit, like "5", i get "5,00", instead of "50,00", could it be a problem in the leading zero handler?
[http://jsfiddle.net/qmemcvdb/1/](http://jsfiddle.net/qmemcvdb/1/)

**Comment by RobinHerbots** [comment]
@schmulschubiak , 

Fixed in the latest
