### ISSUE TITLE
Complex regex is not working

### ISSUE THREAD

**Issue by eklnc** [RobinHerbots/Inputmask#1203]
I can't implement this regex(email regexp):

'/^(([^<>()[]\.,;:\s@\"]+(.[^<>()[]\.,;:\s@\"]+)*)|(\".+\"))@(([[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}])|(([a-zA-Z-0-9]+.)+[a-zA-Z]{2,}))$/i'

Can you help me?

**Comment by eklnc** [comment]
Hey, i said its not working. Can yo look at this?

**Comment by RobinHerbots** [comment]
@eklnc ,

I tried your regex at https://regex101.com/#javascript and it seems not valid for email)

**Comment by eklnc** [comment]
I wrote wrong regexp i think. I've done with a workaround solution. So, you can close this issue.

**Comment by RobinHerbots** [comment]
@eklnc , 

You could also use the email alias

Inputmask("email").mask(input);
