### ISSUE TITLE
Caret bug on Android WebView

### ISSUE THREAD

**Issue by dva-re** [RobinHerbots/Inputmask#1205]
Hello. In last Chrome and in WebView-based applications on Android expected bug with caret position. Only on new version. On old versions - all is ok.

I captured screencast. 
https://drive.google.com/file/d/0BxwxhrDDVsEKdC00b281dWJmaTQ/view?usp=sharing

In application content - it is https://dva.re/index.php (uses inputmask and inputmask multi (https://github.com/andr-04/inputmask-multi/). May be bug in it, not in inputmask, don`t know. Will test it. 
After uninstalling all webview updates - mask working correct. After installing updates - bug goes back.

Sorry for my bad english,
Regards

**Comment by ixth** [comment]
Seems like `keydown` sometimes sends `keyCode` 229 instead of 8: https://gielberkers.com/what-is-keycode-229/

**Comment by Enfree** [comment]
Found that replacing 
`result = keypressEvent.call(input, keypress, true, false, strict, pos);` 
in checkValue method with 
`result = keypressEvent.call(input, keypress, true, true, strict, pos);`
solves the problem, but not sure that it is an adequate solution >_>

**Comment by RobinHerbots** [comment]
@Enfree, 

Thx for sharing, ... the writebuffer method called within checkval is missing some caret related logic, which could explain why the patch works.  Although looking at the initial issue, I think it will be more something in the inputfallback.  Can someone create a jsfiddle.

**Comment by Enfree** [comment]
@RobinHerbots , here it is - i took inputmask from current 3.x
http://plnkr.co/edit/d2zQVyZ4cmPRk3VvumAt?p=preview
Bug can be reproduced under Samsung S4 - Android 5.0.1 (Chrome), Nexus 5X - Android 6.0.1. (Chrome)
