### ISSUE TITLE
jquery input mask typeError: can't redefine non-configurable property "value"

### ISSUE THREAD

**Issue by afattahi54** [RobinHerbots/Inputmask#1206]
Some time when I call input mask on dom element for example TDs which have specific class  `$(".mask-date).inputmask("99/99/99")`, I face this error.

```
  jquery input mask typeError: can't redefine non-configurable property "value"
```

I just have see why this happens at http://stackoverflow.com/questions/6924250/error-in-accessor-property-cant-redefine-non-configurable-property-status

**Comment by RobinHerbots** [comment]
@afattahi54 , 

Do you use the latest version from github?  Browser?
