### ISSUE TITLE
"[object Object]" value after `$element.inputmask('setvalue', '')` call

### ISSUE THREAD

**Issue by futpib** [RobinHerbots/Inputmask#1208]
This can be easily [reproduced](https://jsfiddle.net/fc27q8zd/) or seen [in the code](https://github.com/RobinHerbots/jquery.inputmask/blob/fc73180bae1728973e418c75d1d74b624a1172fb/js/jquery.inputmask.js#L23)

**Comment by RobinHerbots** [comment]
@futpib , 

This will be fixed by the next commit.  Thx for reporting
