### ISSUE TITLE
Сan i use carret , seekNext,  seekPrevious method in onKeyDown event?

### ISSUE THREAD

**Issue by setdream** [RobinHerbots/Inputmask#1209]
It is necessary to specify the behavior of the following keys:

DELETE or Backspace - delete left or right symbol
HOME or END - move to very left or very right through HH or MM
_UP or DOWN - increase or decrease value
LEFT or RIGHT_ - move left or right through HH and MM

**Comment by RobinHerbots** [comment]
@setdream , 

No you do not have access to it.

Is the above functionality not already present? (except the increase/decrease)
