### ISSUE TITLE
How to remove autofill on hover/focus

### ISSUE THREAD

**Issue by gubi** [RobinHerbots/Inputmask#1214]
Is it possible to remove or hide the underscore pattern (eg. "____") during the filling field?
![screenshot](https://cloud.githubusercontent.com/assets/746559/13598469/3354fc18-e51e-11e5-82fb-467fafc30b27.png)

**Comment by gubi** [comment]
Sorry, seeing your code I found the solution, simply passing the `definition: " "` option like this:

``` javascript
$("#item").inputmask("A", {
    placeholder: " ",
    definitions: {
        "A": {
            validator: "[a-zA-Z0-9]",
            casing: "upper"
        }
    }
});
```

Note that is not well documented!

**Comment by RobinHerbots** [comment]
Yes you can alter the placeholder with the placeholder option.

Feel free to update the readme with a better explanation.

Op di 8 mrt. 2016 om 11:15 schreef Alessandro Gubitosi <
notifications@github.com>:
