### ISSUE TITLE
Clicking on a highlighted masked field does not set the caret to the first valid position (Chrome)

### ISSUE THREAD

**Issue by khcung** [RobinHerbots/Inputmask#1218]
In Firefox or IE, if you highlight a masked field (i.e. tabbing into a date or ssn masked field) and then click on the field, it will set the caret to the first valid position.  However, in Chrome, if you click on a highlighted masked field, the caret will just stay at the position you click.  Clicking again will do.

**Comment by khcung** [comment]
@RobinHerbots 
I think the problem is that in Chrome, when a click event occurs, the call to caret() function always returns the positions of the current input selection.  Whereas in Firefox and IE, the current input selection is cleared out first, therefore the call to caret() returns the correct cursor positions.  Is there any way we can do that for Chrome?  Thanks for your help.

**Comment by RobinHerbots** [comment]
Put a settimout around the clickevent. I will test it on monday.  Thx for further investigating.

**Comment by khcung** [comment]
@RobinHerbots Yes, that resolved the issue!  Thank you very much.
