### ISSUE TITLE
document.activeElement unspecified error when loading in iframe with IE9

### ISSUE THREAD

**Issue by valgen** [RobinHerbots/Inputmask#122]
I'm using JQuery 1.7.2 and  jquery.inputmask 1.0.24 and I'm loading the plugin in an iframe with IE9
I received a javascript error on document.activeElement - unspecified error.

To work around the issue I had to remove the following code:
   if (document.activeElement === el) { //position the caret when in focus
         $input.addClass('focus.inputmask');
         caret(el, lastPosition);
   } else

**Comment by RobinHerbots** [comment]
Hi Valgen,

Thx for the notice.

I will have a look at it when I find some time ;-)

best regards,

Robin

2012/10/10 valgen notifications@github.com

**Comment by RobinHerbots** [comment]
I committed a fix in the dev-branch

**Comment by RobinHerbots** [comment]
todo use iframe contentDocument Property, to check focused element in iframe

**Comment by valgen** [comment]
Tx Robin

**Comment by RobinHerbots** [comment]
iframe.contentDocument not needed for funtionality
