### ISSUE TITLE
'alias': 'numeric', zero value

### ISSUE THREAD

**Issue by CodeOfDavid** [RobinHerbots/Inputmask#1221]
Im finding that the cursor position, when I have '0' (Zero) in the input, is to the left of the 0 not to the right of the zero. If it was to the right of the zero, the user input of numbers would overwrite the zero, instead the number the user types are added to the left of the zero, making a 0 become 10 etc. sometimes oddly the cursor will put itself to the right of the zero, but this happens less often than not. I think this is new (buggy) behaviour

**Comment by RobinHerbots** [comment]
@CodeOfDavid , 

There is a difference between 0 as user input and 0 as a placeholder.  When 0 is set by the server or by the user, put the caret to the left and additional input will be added.  When placed after the 0, it will overwrite as ex: 01 is not valid.

When there is nothing entered yet and you have a placeholder 0, all input will overwrite the 0.  The positioning of the caret will depend on the position you click in the input.

**Comment by CodeOfDavid** [comment]
@RobinHerbots Thanks for this explanation, is there a setting to make the 0 behaviour of value 0 to be the same as a the behaviour of the placeholder 0?

**Comment by RobinHerbots** [comment]
@CodeOfDavid , 

No but I can add that.

There should be some voting mechanism in github so I can make a poll for it.  
It is more about what should be the default option?

**Comment by CodeOfDavid** [comment]
@RobinHerbots I would appreciate it if you add this functionality, I suspect it could be the default as 0 is rarely the first digit in a number. Im sure it would be a popular feature. Thank you.

**Comment by RobinHerbots** [comment]
@CodeOfDavid , 

Maybe the previous behavior of overwriting 0 regardless the user has already inputted 0 was better.

**Comment by CodeOfDavid** [comment]
@RobinHerbots I think so, you can always provide an option to allow the user to choose the current behaviour.

**Comment by RobinHerbots** [comment]
@CodeOfDavid , 

I trying for 1 behavior to rule them all ;-)

So with the caret in front:
0              type 1 => 1
0.00         type 1 => 1.00
0.02         type 1 => 1.02  or 10.02 ?

**Comment by CodeOfDavid** [comment]
@RobinHerbots 
Re. 0.02 type 1 => 1.02 or 10.02 ?
difficult to say....on the balance of things, since the user is already in the text box and can add the zero to make 10 I would say 1.02. There answer to this probably depends on what value the user wanted to end up with.

**Comment by RobinHerbots** [comment]
@CodeOfDavid , 

10.02 would be the most logical.  The user can also press the insert key to switch to overwrite mode.

The behavior in a spreadsheet is also 10.02

**Comment by CodeOfDavid** [comment]
@RobinHerbots that works too :)

**Comment by pavel-mironchik** [comment]
@RobinHerbots, did you change this behavior since then?
In [jsfiddle](https://jsfiddle.net/brunen9/5vej4bkd/1/):

1. Put the caret to the left of `0`.
2. Press `1`.
3. Field value will become `10`, but not `1`, as expected.

**Comment by RobinHerbots** [comment]
@brunen9 , 

Have a look at this updated  https://jsfiddle.net/5vej4bkd/2/

**Comment by pavel-mironchik** [comment]
@RobinHerbots , I see your point - using placeholder for this case. But try this in your fiddle:

1. Place caret in `input2`.
2. `0` will appear.
3. Press `1` - input value will become `1`, good.
4. Select all and delete - input value will become `0`.
5. Press `1` - input value is `10` now. Ooops :)
