### ISSUE TITLE
validate regular expression for indian vehicle registration number

### ISSUE THREAD

**Issue by ankitajain32** [RobinHerbots/Inputmask#1223]
I need to apply 'either' and 'OR' regular expression between the alphabet 'C' and 'S' for verify the delhi vehicle registration no like DL 12C AS 1234 OR DL 12S AS 1234.
I tried:-
$('#registration_no').inputmask("mask", {"mask": "a{2} 9{1,2}(c|s) a{1,3} 9{4}"});
or
$('#registration_no').inputmask("mask", {"mask": "a{2} 9{1,2}[cs] a{1,3} 9{4}"});

but it accepts the C by default always.

**Comment by RobinHerbots** [comment]
@ankitajain32 , 

You should escape the s as this is also a definition symbol.

$('#registration_no').inputmask("mask", {"mask": "a{2} 9{1,2}c|\s a{1,3} 9{4}"});

Maybe this one:
$('#registration_no').inputmask("mask", {"mask": "A{2} 9{1,2}C|S A{1,3} 9{4}"});

This mask works, only there is some visual mistake the initial mask is __ ____ ____ and should be __ ___ _ ____ but that is something that is on the todo list ;-)

**Comment by ankitajain32** [comment]
Thanks for replying 
But in both case it takes 'c' as default.If i try to replace 'c' by 's'  it takes 's' in next slot.

**Comment by RobinHerbots** [comment]
Did you try this one? $('#registration_no').inputmask("mask", {"mask": "A{2} 9{1,2}C|S A{1,3} 9{4}"});

**Comment by ankitajain32** [comment]
yes sir.:-)
Firstly it replaces the 'c' by 's' but when we go in next slot then 's' again changes into 'c'.basically it takes c as default.

**Comment by RobinHerbots** [comment]
@ankitajain32 , 

Give me some examples, ...

**Comment by ankitajain32** [comment]
Sir, I need a  DL 12C ASD 1234 or DL 12S ASD 1234

$('#registration_no').inputmask("mask", {"mask": "a{2} 9{1,2}a a{1,3} 9{4}"});

**Comment by RobinHerbots** [comment]
@ankitajain32 , 

Have a look at https://jsfiddle.net/2xc3o61o/1/

**Comment by ankitajain32** [comment]
Thanks robin but it not works it didn't allow me to replace 'c' with 's'.

**Comment by RobinHerbots** [comment]
@ankitajain32 , 

I tested again and you are right! You can type the S initially, but you cannot replace the C by an S.

I will have a look at that.

**Comment by ankitajain32** [comment]
Thanks and please also tell me, which event we use to allow edit the value of input text take by the input mask?

**Comment by RobinHerbots** [comment]
@ankitajain32, 

Have a look at the updated fiddle https://jsfiddle.net/2xc3o61o/3/

**Comment by ankitajain32** [comment]
Thanks Robin, Now it works fine.Can you please tell me how we make the masking editable.Suppose We have the DL 12S ASD 1321 and we want to change DL 12C ASD 1321,means edit the character from mid.so which option we can use to edit the masking.

**Comment by RobinHerbots** [comment]
@ankitajain32 , @ankiSuccessive,

Or you select the char and start typing or press insert to switch to overwrite mode or set the insertMode option to false to enable the overwrite mode by default.

**Comment by ankiSuccessive** [comment]
Hi Robin ,

Edit is not working can you please give the proper syntax that i can use in code for make my input mask editable.

**Comment by RobinHerbots** [comment]
@ankiSuccessive , 

I guess you mean this.  See https://jsfiddle.net/2xc3o61o/5/

**Comment by ankitajain32** [comment]
@robin 

By default the text fox in which we apply masking is editable,if we move left it goes.

But in my case the masking is not editable,if i try to edit the character between the string it does  not allow me.insertMode is not working.

**Comment by RobinHerbots** [comment]
@ankitajain32 , 

Can you explain step by step what you do?  Or even better can you submit a PR with a unit test which shows the problem.

**Comment by ankitajain32** [comment]
@RobinHerbots 

I want to edit the mask.
Suppose we enter the registration Number DL12C AB 1234.Now we want to change 'C' with 'S' without remove AB 1234 with backspace.Need goes to the 'C' place with left key and then remove C with backspace  and insert S there.

This will do default in your jsfiddle textbox but in my text box it is only allow first remove forward part 'C'
with backspace and then replace C with S.

**Comment by RobinHerbots** [comment]
Can you create a jsfiddle with your text box as an example?

Op wo 6 apr. 2016 om 08:19 schreef ankitajain32 notifications@github.com:

**Comment by ankitajain32** [comment]
Hi Robin
please check the jsfiddle.

I want to edit a character A by C without removing the forward characters of A.

https://jsfiddle.net/ankitajain32/Lzr6Lsv0/10/

**Comment by RobinHerbots** [comment]
@ankitajain32 , 

Due the keyup event you reapply the mask on every keystroke.  Why do you do that?

Have a look at https://jsfiddle.net/Lzr6Lsv0/12/

**Comment by ankitajain32** [comment]
@RobinHerbots 

actually i want to test the registration number  on every add new character.

And robin please help to solve one more issue,i want to append a character forcely. How i can do it?

Suppose a user enter the Registration No. DL 3C AB 1234. and i want update this string into DL 03C AB 1234..'0' will append forcely.

**Comment by RobinHerbots** [comment]
@ankitajain32 , 

The inputmask will do the validation for you.  So you do not need to test the registration number on every keystroke.  
Have a look at these
oncomplete: $.noop, //executes when the mask is complete
onincomplete: $.noop, //executes when the mask is incomplete and focus is lost
onKeyValidation: $.noop, //executes on every key-press with the result of isValid. Params: key, result, opts

 Can you provide some info on the correct format for the registration.

When should the 0 be appended?  In which cases?  Give some examples.

**Comment by ankitajain32** [comment]
if the user enter the value DL 1C  AB 4242 ,I want to append DL 0 before the 1C.

Please Have a look at https://jsfiddle.net/Lzr6Lsv0/12/

**Comment by ankitajain32** [comment]
Hello,

If we bring data from cache in textbox on which input masking is applied and delete /slash/erase the content and submit the form then an extra space is automatically add in that textbox.

How to removee Extra space?

**Comment by RobinHerbots** [comment]
@ankitajain32 , 

Can you simulate that in a jsfiddle.  The exact mask with options

**Comment by ankitajain32** [comment]
Hi Robin

Please check the jsfiddle

https://jsfiddle.net/ankitajain32/vczht14u/5/

Please delete the entire content from the textbox and then submit you will the extra space in textbox.

**Comment by ankitajain32** [comment]
Hi Robin,

Any update?

**Comment by RobinHerbots** [comment]
Hi @ankitajain32, 

I updated your fiddle to make it clear what is happening.

https://jsfiddle.net/vczht14u/7/

I replaced the spaces in your mask with S.  What you see is not some extra spaces but the masktemplate.

Add the  jitMasking: true option to your mask to solve the problem.

**Comment by ankitajain32** [comment]
Thanks Robin
