### ISSUE TITLE
Decimals

### ISSUE THREAD

**Issue by NurGuz** [RobinHerbots/Inputmask#1224]
When I click on the decimal part it makes me focus on the integer part ( so do not let me write in decimal ) When writing where it has made me focus upsets me the order of the number as I write

this is my mask

$('.currency').inputmask("currency",
        {
            groupSeparator: '.', radixPoint: ',', autoGroup: true, digits: 2, digitsOptional: false, prefix: '',
            showMaskOnHover: false, showMaskOnFocus: false, placeholder: ''
        });

**Comment by RobinHerbots** [comment]
add the radixFocus option

$('.currency').inputmask("currency",
{
groupSeparator: '.', radixPoint: ',', autoGroup: true, digits: 2, digitsOptional: false, prefix: '',
showMaskOnHover: false, showMaskOnFocus: false, placeholder: '', radixFocus: false
});

**Comment by NurGuz** [comment]
Don't work man =( 
If I write in decimals, automatically written to the integer part and I change the order of numbers (my input is empty)

**Comment by RobinHerbots** [comment]
@NurGuz , 

Can you make a jsfiddle to make it more clear. 

Can you give an example as it is not very clear to me what you mean.

**Comment by NurGuz** [comment]
**Html**:  < name="dcDisExpensesAccruals" data-ng-model="numericos.dcDisExpensesAccruals" type="text"  class="currency" >

$('.currency').inputmask("currency",
{
groupSeparator: '.', radixPoint: ',', autoGroup: true, digits: 2, digitsOptional: false, prefix: '',
showMaskOnHover: false, showMaskOnFocus: false, placeholder: '', radixFocus: false
});

**Comment by RobinHerbots** [comment]
@NurGuz , 

Can you retry with the latest version from github.

**Comment by NurGuz** [comment]
dont work, i am using jquery.inputmask.bundle.js

**Comment by RobinHerbots** [comment]
@NurGuz , 

Can you explain a bit more the problem.   I don't get the problem.
