### ISSUE TITLE
phone field mask on Mobile phone

### ISSUE THREAD

**Issue by MyDark** [RobinHerbots/Inputmask#1233]
The jQuery.inputmask bug when browsing the website from mobile phone.
When you writing numbers on the field "phone", the caret don't moving to the next block, and stucks on first block. Example:
+7 (___) ___ __ __
so the +7 is always standing and never changing character, the 1st block (___) 3 numbers, after 2nd block ___ 3 numbers, after third block with 2 numbers __, and the last 4th block, again 2 numbers __.
Example phone can be:
+7 (123) 456 78 90.

So after the user completing the last number of 1st block (123), the caret reseting at his first position, to the begining of this block, and don't moving to the next block.
On the PC/Mac browsers everything working fine, but this bug only when you viewing the website with Mobile phone. And the problem is just with the mask of "phone" field.
Best regards.

**Comment by MyDark** [comment]
Hi. After updating to the latest version of your plugin, the "bug" with phone field mask has disappeared. 
Sorry for losing your time.
Thank you very much for fixing this bug.
Best regards.

**Comment by RobinHerbots** [comment]
@AgressorT , 

No problem, thx for reporting the bug in the first place!

best regards, 
Robin
