### ISSUE TITLE
YUI Compressor fails with issues

### ISSUE THREAD

**Issue by szaszendre** [RobinHerbots/Inputmask#1242]
column 74: missing variable name
`\t␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣var buffer = maskset.buffer.slice("").reverse(), char = buffer[opts.prefix.length];`
column 37: identifier is a reserved word
`\t␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣if ("0" === char && void 0 === maskset.validPositions[pos - 1]) return {`
column 29: syntax error
`\t␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣pos: pos,`
column 32: syntax error
`\t␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣␣remove: buffer.length - opts.prefix.length - 1`
Compilation produced 4 syntax errors.

**Comment by rice2007** [comment]
I also have this issue, but the fix is simple. `char` is technically a reserved word in JavaScript, and this causes YUI Compressor to fail. Rename the variable to something else, and the compressor will succeed without issue.
