### ISSUE TITLE
Email alias _@_._

### ISSUE THREAD

**Issue by BenasPaulikas** [RobinHerbots/Inputmask#1245]
Hey, how do we achieve this ? 

http://prntscr.com/apng7t

I tried using placeholder, but with no luck :(

**Comment by RobinHerbots** [comment]
@BenasPaulikas , 

For this you need to alter the email alias.  Remove the optionality of one of the last parts

Maybe I could make this the default.  _@_._ looks more clear as placeholder

**Comment by BenasPaulikas** [comment]
I think more people are putting x@domain.com rather than x@localhost or something :D ?
