### ISSUE TITLE
Phone alias problem

### ISSUE THREAD

**Issue by panchenkodv** [RobinHerbots/Inputmask#1252]
When I start type 0 and continue typing numbers for complete phone plugin tell me, that mask is { "mask": "+90(###)###-####", "cc": "TR", "cd": "Turkey", "desc_en": "", "name_ru": "Турция", "desc_ru": "" }.

Why Turkey? All phone numbers starting with 0 is Turkey? There is no mask starting from 0.

And another problem. If I put some 'countrycode', why it not displayed in the field on focus?

**Comment by RobinHerbots** [comment]
Remove Phone alias #1981
