### ISSUE TITLE
Safari date mask - Context switch when jquery.valhook fallback is used

### ISSUE THREAD

**Issue by Bandab** [RobinHerbots/Inputmask#1255]
Hi,
I've spent hours trying to resolve my issue with getting a value of an input with date mask.
I used $.val() to get that value. Unfortunately, it works in all browsers but Safari. You can successfully set the value using $.val(), but it always returns empty value when getting one. Once I removed the mask, everything works fine. I think there must be something that doesn't want to work with Safari.

**Comment by oruchreis** [comment]
I'm struggling with this too. Also android default browser has the same issue.

**Comment by RobinHerbots** [comment]
@Bandab , @oruchreis , 

I will have a look at this.
