### ISSUE TITLE
Losing the decimal part when the maximum number of digits is reached

### ISSUE THREAD

**Issue by Guito** [RobinHerbots/Inputmask#1257]
Having the following specifications:
`.inputmask("numeric", {
                allowMinus: allowNegative,
                allowPlus: false,
                groupSeparator: ".",
                radixPoint: ",",
                autoGroup: true,
                digits: 2,
                digitsOptional: false,
                integerDigits: 5
            });`

If I have a input which value is 12345,12, then it's coverted to 12345,00. This doesn't happen if I have a number which value is 1234,12. In other words, it only happens whe the integerDigits number is reached.

It's happening in v3.3.0

Regards

**Comment by kamihouse** [comment]
@Guito, like this? https://github.com/RobinHerbots/Inputmask/issues/1418

**Comment by Guito** [comment]
@kamihouse Not sure to be honest! It could be :)

**Comment by RobinHerbots** [comment]
@Guito , 

The issue should be fixed in the latest version on github.

@kamihouse , 

Can you retest issue #1418, with the current version on github

**Comment by kamihouse** [comment]
Sure!

**Comment by kamihouse** [comment]
@RobinHerbots, see this: https://github.com/RobinHerbots/Inputmask/issues/1418#issuecomment-254803800

**Comment by Guito** [comment]
I have tested this and it is working now. Thank you!
