### ISSUE TITLE
How to display url mask  on focus case

### ISSUE THREAD

**Issue by sreelalks** [RobinHerbots/Inputmask#1262]
on focus case how can i show 'http://' mask url ?

**Comment by RobinHerbots** [comment]
@sreelalks , 

```
Inputmask("\\http://a{+}").mask(selector);
```

**Comment by brada1703** [comment]
The problem with @RobinHerbots solution is that it does not accept the period "." So, you cannot write `something.com`.

Instead, you can do this with Regex:

`$('selector').inputmask({ regex: "http://.*" });`

Hope this helps someone! :)

**Comment by zarpio** [comment]
> @sreelalks ,
> 
> ```
> Inputmask("\\http://a{+}").mask(selector);
> ```

Please guide how to allow dots thanks.

**Comment by zarpio** [comment]
> The problem with @RobinHerbots solution is that it does not accept the period "." So, you cannot write `something.com`.
> 
> Instead, you can do this with Regex:
> 
> `$('selector').inputmask({ regex: "http://.*" });`
> 
> Hope this helps someone! :)

Not working for me :-(

**Comment by RobinHerbots** [comment]
@zarpio , 

You can use Inputmask("url").mask(selector);

**Comment by zarpio** [comment]
> @zarpio ,
> 
> You can use Inputmask("url").mask(selector);

Thanks, it is working, now the issue is in the Vuejs v-model is not working on this masked field. :-( do you know how your Inputmask works with Vuejs?

**Comment by RobinHerbots** [comment]
@zarpio , 

I think your problem with vue is related to #2307 
I still need to investigate that.

**Comment by zarpio** [comment]
@RobinHerbots ,

Please check below example, the mask is working but v-model is not working
[https://jsfiddle.net/zarpio/j493fxgr/10/](https://jsfiddle.net/zarpio/j493fxgr/10/)

**Comment by RobinHerbots** [comment]
@zarpio ,

Import the inputmask.js instead of the jquery.inputmask.js
