### ISSUE TITLE
'setvalue' on mask with a suffix results in suffix being doubled, while `$.fn.val` works fine

### ISSUE THREAD

**Issue by futpib** [RobinHerbots/Inputmask#1267]
[setvalue demo (broken)](https://jsfiddle.net/zqp9j3qw/1/)
[val demo (works)](https://jsfiddle.net/9p04cL12/1/)
1. `$input.inputmask('.{+}QWERTY', ...)`
2. `$input.inputmask('setvalue', 'Value')`
3. value is now `ValueQWERTYQWERTY`

Also, README has a [section on setvalue](https://github.com/RobinHerbots/jquery.inputmask#setvalue) that kind of says that `setvalue` does some additional work compared to `val`, so I tend to use `setvalue` just to be sure. Isn't it an inputmask-specific substitute for val? (am I using it wrong?)

**Comment by RobinHerbots** [comment]
https://jsfiddle.net/zqp9j3qw/2/
