### ISSUE TITLE
Currency InputMask Input Value issue with numericInput: true

### ISSUE THREAD

**Issue by sadhuria** [RobinHerbots/Inputmask#1269]
I am trying to use inputmask with Currency Alias and numericInput as true to get the input formatted as Calculator/atm style. It works great when there is no value of input text (Add mode). But when the page is loaded with an input value of something it incorrectly formats the value provided. I am not sure what am I missing. Any help would be greatly appreciated ! Please see JSFiddle below. Note that the input value is pre-populated to "4545.56" but it somehow mask it to "$ 55.56"
http://jsfiddle.net/msj5qfu1/102/

**Comment by RobinHerbots** [comment]
@sadhuria , 

It has something todo with the numericinput option.
I will have a look.

**Comment by sadhuria** [comment]
Thanks Robin !

**Comment by RobinHerbots** [comment]
@sadhuria , 

This is fixed in the current on github

**Comment by vercotux** [comment]
Just dropping by to confirm that this is indeed fixed. :+1:
