### ISSUE TITLE
Hidden input value reseted when its value doen't fit the mask

### ISSUE THREAD

**Issue by mtomas-mpm** [RobinHerbots/Inputmask#1273]
I've recently updated from version 3.1.8 to 3.3.1 to solve a problem with decimal masks on IE, but now I've another problem: I've some inputs with masks that are hidden, with the old version, the value doesn't reset when it doesn't fit the mask, but with the current version it's deleted. I understand that the new behavior it's correct, but it generates some errors on my current application. Is there any parameter to configure, or something similar?

JSFiddleSample: (press show button to view differences)
3.1.8: https://jsfiddle.net/skq7jt2g/1/
3.3.1: https://jsfiddle.net/5z4dz0k6/1/

**Comment by RobinHerbots** [comment]
@mtomas-mpm , 

You should adapt the mask to an alternator mask which also allows the nonNumericInput as value.

I will have a look also, but I'm very busy for the moment

**Comment by mtomas-mpm** [comment]
No problem, I've solved it easier avoiding to set the mask to hidden input's. The visibility is static and I don't need to mask the hidden values.

Thanks for your time,

Marc.
