### ISSUE TITLE
Leading Zero been stripped

### ISSUE THREAD

**Issue by richyrb00** [RobinHerbots/Inputmask#1275]
Hi,

I'm using the input mask for telephone validation and new to the library.

I currently have 3 websites that require validation for US, UK and CA.

I'm currently working on the UK version of the validation and the telephone numbers for the most parts start with Zero. but when they are submitted it then goes to a Verify screen, If the details were not correct then they go back to the input form but the number that was added has the leading Zero stripped :(

**Comment by RobinHerbots** [comment]
Can you provide some example to make it more clear.

**Comment by richyrb00** [comment]
Hi Robin,

So we are loading.
inputmask.js
inputmask.phone.extensions.js
jquery.inputmask.js

We are adding data-inputmask="'alias':'phone'" to the phone input

along with 

selector.inputmask({
      "mask"          : "9{10,11}",
      "removeMaskOnSubmit" : true,
});

we are also doing onincomplete and oncomplete although i don't think this is relevant to this issue as it just checks if this is true and then changes colour of text etc..

So a user enters their Telephone Number into the input field, we are not checking for country code..

when the user submits the form. it takes them to a page where it summarises the customer data.

The telephone number in this summery is CORRECT. But say if the address isn't and the user chooses to go back to the form page to re-enter the address etc. If they do go back to this page for some reason the phone number looses the first number in the telephone number and this then turns the phone number to invalid and so the user cannot confirm the form data as its setup to only progress if the phone number is valid...

I hope that is enough information for you.. please let me know if you have any further questions.

**Comment by RobinHerbots** [comment]
@richyrb00 , 

Actually you don't use the phone alias correct.  (see readme for the phone alias, mask url missing)
Retry with removing the phone extension and the data-inputmask attribute.

**Comment by richyrb00** [comment]
Thank you Robin this looks to have fixed the issue i was having.
