### ISSUE TITLE
'casing' : 'title'

### ISSUE THREAD

**Issue by Especially** [RobinHerbots/Inputmask#1277]
How do I make the input mask casing become title case? Such that when I type, after each space, the first letter will be capitalized,

**Comment by RobinHerbots** [comment]
@Especially , 

Ok, I will add that.

**Comment by RobinHerbots** [comment]
@Especially , 

casing: "title" added

**Comment by Especially** [comment]
@RobinHerbots 
Currently receiving an error now that I've implemented it:
`jquery.inputmask.bundle.min.js:8 Uncaught TypeError: Cannot read property 'isGroup' of undefined`

**Comment by RobinHerbots** [comment]
Can you provider An example in jsfiddle.

**Comment by Especially** [comment]
Whoops, It was because I failed to add \* to my {2,25}
