### ISSUE TITLE
Numbers get swapped when cursor near suffix.

### ISSUE THREAD

**Issue by acanha** [RobinHerbots/Inputmask#1278]
The first two numbers on the input get swapped when the cursor is near the suffix.

To reproduce follow these steps:
1 - Click on the input and press the right arrow on the keyboard, the cursor should be close to the suffix.
2 - Then enter two numeric values like 2 and 5. 

The number is swapped showing 52 instead of 25.

https://jsfiddle.net/68utp3eg/

**Comment by RobinHerbots** [comment]
@xklepio , 

I see, thx for reporting.

I will fix this.

**Comment by RobinHerbots** [comment]
@xklepio , 

Finally fixed!

**Comment by sajanyamaha** [comment]
this is still happening in Ver : 3.3.4-108 for android default browser ,below Ver 6
