### ISSUE TITLE
Right to Left Input

### ISSUE THREAD

**Issue by hot-Whiskey** [RobinHerbots/Inputmask#1279]
Hey! First off, thank you so much for this! This is awesome.
My question is how to make inputs go from right to left. 

This is my input box:
<input type = "text" name = "jquery-mask" id = "jquery-mask" placeholder = "0:00:00" dir="rtl">

This is the code I am using for input mask:
$(document).ready(function(){
  $("#jquery-mask").inputmask("99:99:9",{"placeholder": "0"}); 

When I type in "12345" I want it to look like 1:23:45. Instead it looks like 5:43:21. So technically it is going from right to left but in the way that I want it to :-) 

Is this something that can be easily fixed? Thank you!!

**Comment by RobinHerbots** [comment]
@hot-Whiskey , 

I wrongly implemented rtl support.  I still need to fix it.  But in your case adding the numericInput: true option will do. See #956

**Comment by hot-Whiskey** [comment]
Woo! Thank you! In case any one else is having this issue, you need to have numericInput: true BEFORE the placeholder value : 
$(document).ready(function(){
  $("#jquery-mask").inputmask("9:99:99",{numericInput:true},{"placeholder": "0"});

Otherwise it doesn't change the behavior. 

Thank you Robin!

**Comment by RobinHerbots** [comment]
@hot-Whiskey,

Actually you need to use it like below, the order doesn't matter.

```
$("#jquery-mask").inputmask("9:99:99", { numericInput: true, placeholder: "0"});
```

Robin ;-)

**Comment by hot-Whiskey** [comment]
hey @RobinHerbots  - I'm having the same issue above but on Android. It's working perfectly fine on iPhone and desktop browsers but in Chrome on Android it is entering the way I mentioned at first. Any ideas? I tried the insertMode:true but didn't seem to help. Thanks!

**Comment by mdtyrrell** [comment]
It only appears to be a problem on Chrome on Android. It works fine on Firefox on Android.
Cheers, Michael

**Comment by dmikester1** [comment]
Any updates on this?  I would love to use your plugin, but it's broken in Chrome on Android.

**Comment by muriloecfaria** [comment]
Same issue in Chrome on Android here
