### ISSUE TITLE
How Can I have caret position on decimal digit(after decimal point) for currency inputmask ?

### ISSUE THREAD

**Issue by sadhuria** [RobinHerbots/Inputmask#1282]
In currency inputmask, by default when I click on the input box the caret is positioned right before the decimal point. I would like to have caret position stay after decimal point if clicked there. I tried many different options but not able to do it. could you please let me know if it is possible and if yes, how ?

Thanks,
Saunak

**Comment by RobinHerbots** [comment]
@sadhuria, 

Set the radixFocus: false

**Comment by sadhuria** [comment]
I tried it but no luck. Still same behavior. When I click after the decimal point to have caret at that position it still jumps back to the default integer position. Please advice.

**Comment by RobinHerbots** [comment]
@sadhuria , 

It is actually a feature to position the caret ;-) Maybe I should leave a choice here to not reposition the caret?  Maybe I can add something like positionCaretOnClick with options: none, lvp (based on the last valid position - current implementation), radixFocus

**Comment by sadhuria** [comment]
Thanks !

**Comment by RobinHerbots** [comment]
@sadhuria , 

The positionCaretOnClick option is added which controls the behavior of the caret on click.  Try setting the value to "none"

**Comment by sadhuria** [comment]
Thanks ! This works perfect !
