### ISSUE TITLE
character limit is only 10 for all masks

### ISSUE THREAD

**Issue by naitsir** [RobinHerbots/Inputmask#1284]
i can't set a number like 9,999,999,999.00
the currency mask limit me to 999.999.00
or 99.999.999
just 10 chars on the input

**Comment by naitsir** [comment]
No solution to this problem?

**Comment by RobinHerbots** [comment]
@naitsir , 

Sorry for the late response, but I couldn't spend much time on the inputmask currently.
Can you provide some more info.  Do you use some extra options?  A specific browser?  platform?

**Comment by RobinHerbots** [comment]
@naitsir, 

In the current version there is no such limit
