### ISSUE TITLE
Unable to add the $ to numericInput

### ISSUE THREAD

**Issue by jwright04** [RobinHerbots/Inputmask#1285]
Hello, 

I'm trying to configure a text field similar to how the example pages are done.  Right now i have:

```
$("#mask-carAmount").inputmask('$99,999', {
numericInput: true,
jitMasking: true
});
```

Which gives me the dollar amount, but I want to also add the "$" in front.  Similar to whats being done here: http://robinherbots.github.io/jquery.inputmask/ but without the .00 at the end.  Can someone give me a hand with the setup?

**Comment by jwright04** [comment]
Looks like I was able to just add the currency alias to accomplish most of what I wanted.  I'm still trying to figure out how to remove the cents  and show my input fields placeholder.

**Comment by RobinHerbots** [comment]
@jwright04 , 

Use the integer alias with a prefix.

best regards, 

Robin
