### ISSUE TITLE
Input event doesn't fire in IE

### ISSUE THREAD

**Issue by artptr** [RobinHerbots/Inputmask#1287]
```
var el = document.getElementById("input");
el.addEventListener("input", function (e) {
    console.log(el.value);
});
new Inputmask({ alias: "date" }).mask(el);
```

https://jsfiddle.net/dp9uoxz8/

In Chrome and FF the input event fires on each change of the text field. It doesn't fire in IE that way. But when the IE's clear button (X) was pressed it fires the input event with previous content while the text box clears.

**Comment by Liversage** [comment]
I came here to report this exact problem with IE as I depend on the `input` event to provide suggestions to the user on a masked text input. To me it seems that there are two different issues:
1. When IE's clear button is pressed the `input` event is fired but the value of the text box at the time of the event is whatever was in the text box before clear button was pressed.
2. When deleting input from the text box (e.g. using backspace) the `input` event is not always fired.
