### ISSUE TITLE
unmaskAsNumber causing jquery serialize to fail

### ISSUE THREAD

**Issue by mtsunu** [RobinHerbots/Inputmask#1288]
using this options:

```
{
  alias: 'numeric',
  groupSeparator: '.',
  radixPoint: ',',
  autoGroup: true,
  digits: 2,
  digitsOptional: false,
  placeholder: '0',
  unmaskAsNumber: true,
  autoUnmask: true,
  removeMaskOnSubmit: true
}
```

calling jquery.serialize will throws exception saying that replace is not a function.
this is because jquery serialize assume that the fields value is string and tries to escape new line characters if any.

[https://jsfiddle.net/mtsunu/8Ldejeeq/](url)

the other issue is when setting unmaskAsNumber: false.
notice i'm using comma as radixPoint.
when i input 12.000,24 the serialized value is 12000,24 (i'm guessing the unmask value will be wrong too, haven't tried it though)

what is the correct options for that situation?

**Comment by RobinHerbots** [comment]
@mtsunu , 

Maybe the unmaskAsNumber should return a numeric parsable string.

**Comment by mtsunu** [comment]
won't it be better to fix the custom radixPoint issue?

with the option named "unmaskAsNumber", it would make sense if we expect it to return a number rather than numeric string..

**Comment by RobinHerbots** [comment]
The custom radixPoint issue is not really An issue as some backends want it that way to parse it correctly depending the culture settings. You can always extend the current implementation.

**Comment by RobinHerbots** [comment]
@mtsunu , 

An example

```
Inputmask.extendAliases({
        "mynumeric": {
      alias: 'numeric',
      groupSeparator: '.',
      radixPoint: ',',
      autoGroup: true,
      digits: 2,
      digitsOptional: false,
      placeholder: '0',
      autoUnmask: true,
      removeMaskOnSubmit: true,
      onUnMask: function (maskedValue, unmaskedValue, opts) {
                if (unmaskedValue === "" && opts.nullable === true) {
                    return unmaskedValue;
                }
                var processValue = maskedValue.replace(opts.prefix, "");
                processValue = processValue.replace(opts.suffix, "");
                processValue = processValue.replace(new RegExp(Inputmask.escapeRegex(opts.groupSeparator), "g"), "");
                if (opts.radixPoint !== "" && processValue.indexOf(opts.radixPoint) !== -1) 
             processValue = processValue.replace(Inputmask.escapeRegex.call(this, opts.radixPoint), ".");

                return processValue;
            },
    }
});
```

https://jsfiddle.net/8Ldejeeq/1/

**Comment by mtsunu** [comment]
Thanks for the code.

I think you're right, I really need to fix my backend culture settings.
But what if I can't change my backend culture settings? Is that make sense?

So, have you decide what to do with unmaskAsNumber?

**Comment by RobinHerbots** [comment]
@mtsunu , 

unmaskedadnumber stays as is, also the unmasking.

When the culture setting of the backend are fixed, you can use the extension above.  But I cannot think a reason why you could not change the culture settings on the backend.

**Comment by mtsunu** [comment]
Okay.
Maybe you should put a warning on the documentation.

Thanks for the help!
