### ISSUE TITLE
inputmask is not a function when using Bundle

### ISSUE THREAD

**Issue by weisborg** [RobinHerbots/Inputmask#1290]
I've seen a couple issues with this, but they weren't using the bundle.

I have my scripts included at the bottom of the body like this:

```
<script src="~/js/jquery-2.2.4.min.js"></script>
<script src="~/js/jquery-ui.min.js"></script>
<script src="~/js/jquery.inputmask.bundle.min.js"></script>
<script src="~/js/jquery.validate.min.js"></script>
<script src="~/js/jquery.validate.unobtrusive.min.js"></script>
<script src="~/js/jquery.serializejson.min.js"></script>
<script src="~/js/bootstrap.min.js"></script>
<script src="~/js/site.js"></script>
```

In site.js I have calls like:

```
// Setup all Date Inputs
$(".MyDate").inputmask("mm/dd/yyyy", { "clearIncomplete": true });

// Setup all Time Inputs
$(".MyTime").inputmask("hh:mm", { "clearIncomplete": true });
```

It fails on the very first call saying inputmask is not a function.  It worked before in a straight HTML/Javascript page declared the same way, and only seemed to give this error at random.  I then decided to try the library in an ASP.NET MVC type page, and not it gets this error every time and doesn't work.  I even upgraded from 3.3.2 to  3.3.2-1 and no improvement.

So, am I missing something, or should the bundle be all that is needed?

**Comment by RobinHerbots** [comment]
@weisborg , 

The bundle includes all you need.  

The serverside technology used shouldn't matter.  

I don't know the contents of the site.js, but maybe try like

```
$(document).ready(function(){
// Setup all Date Inputs
$(".MyDate").inputmask("mm/dd/yyyy", { "clearIncomplete": true });

// Setup all Time Inputs
$(".MyTime").inputmask("hh:mm", { "clearIncomplete": true });
});
```

**Comment by weisborg** [comment]
That was the first thing I tried.  Still fails with the bonus of not running any other ready calls after since it doesn't return a value due to the error.

**Comment by weisborg** [comment]
Could there be something with jQuery 2.2.4?

**Comment by weisborg** [comment]
Found the problem.  Another developer had included a library that bundled in jQuery again and it was wiping out the previous jQuery that inputmask was attached to.  Sorry for the false alarm.
