### ISSUE TITLE
onUnMask is not being called

### ISSUE THREAD

**Issue by Tomcatus** [RobinHerbots/Inputmask#1291]
Hello. We've been working with this plugin for some time, works really lovely but I recently came across a little problem I think. An input field uses 'percentage' alias and that doesn't have any value entered. I've passed an onUnMask function to the mask options but when I try to retrieve the unmaskedvalue of the input I get null and that method is not even called. Why is this so? I want it, because I want to make the input field's unmaskedvalue to return 0 when no value has been entered.

**Comment by RobinHerbots** [comment]
Set the nullable option to false

**Comment by Tomcatus** [comment]
``` coffeescript
PERCENTAGE_OPTIONS =
    alias: 'percentage'
    rightAlign: false
    suffix: '%'
    onUnMask: (maskedValue, unmaskedValue) ->
      console.log 'onUnMask', maskedValue, unmaskedValue
    nullable: false
$inputs.inputmask PERCENTAGE_OPTIONS
```

This is how I add the mask after your answer. When I try to get: `$el.inputmask 'unmaskedvalue'` I still get null and the onUnMask function is not being called.

**Comment by RobinHerbots** [comment]
This will need a fix.  I will submit asap.

**Comment by RobinHerbots** [comment]
@Tomcatus 

Grab the latest from github an try 

```
Inputmask({
            alias: 'percentage',
            rightAlign: false,
            suffix: '%',
            autoUnmask: true,
            nullable: false
        }).mask($inputs);
```

**Comment by Tomcatus** [comment]
Works like a charm, thanks! :) but I have a question, bower can't find the current version even if I pass him `"jquery.inputmask": "https://github.com/RobinHerbots/jquery.inputmask.git#3.3.2-9"` Any ideas why? It says the version is not available.

**Comment by RobinHerbots** [comment]
Because version 3.3.2 is not released.   You should take the latest from
github

Op ma 6 jun. 2016 om 09:32 schreef Tomasz Pawlak notifications@github.com:

**Comment by Tomcatus** [comment]
Ok, thanks again for the quick fix :)

**Comment by webzest** [comment]
Hi,
Thank you for your work.  I have been trying to update my email and URL entry and when I saw your latest code, i thought i had reached my finished source; however, I can't seem to get the masks to work.  would you please recommend an approach to finish the URL and email masking from this page:
http://johnnysandaire.com/contact/index.php?modal=2
