### ISSUE TITLE
cant output negative numbers

### ISSUE THREAD

**Issue by Lilmonkey** [RobinHerbots/Inputmask#1293]
i was using an older version of the plugin, i just updated to the last version but for some reason my custom numeric inputmask are not working properly i am using a custom inputmask "degrees"

```
'degrees': {
      suffix: "°C",
      alias: "numeric",
      digits: 2,
      digitsOptional: true,
      placeholder: "--.- F",
      clearMaskOnLostFocus: true,
      allowMinus:true
    }
```

when ever i receive "-2.0°C" as a input value the plugin transform my value into 2.0°C

i have tried to debug it and the issue seems to come from the checkVal function just before the "result = opts.onBeforeWrite ..." call. the buffer trimmed the "-" is there any way to work around that or am i doing something wrong.

**Comment by Lilmonkey** [comment]
fyi :  i have hotfixed my issue for the time being by manually adding the minus back in the maskset however now i am having issue with the caret position after doing that fix.

**Comment by Lilmonkey** [comment]
I removed my placeholder and everything was fixed.

**Comment by MrCsabaToth** [comment]
I would still consider this a bug. Why would you have to remove the placeholder to get it to work? I have somewhat connected problem: https://github.com/RobinHerbots/Inputmask/issues/1500
