### ISSUE TITLE
Bug when typing after a fixed character

### ISSUE THREAD

**Issue by gayanj** [RobinHerbots/Inputmask#1299]
1. [Open this js fiddle](https://jsfiddle.net/esojkpwp/)
2. Hold right arrow key until caret is after a fixed character
3. Press any character-key (e.g. "a")
4. The fixed characters will be generated at the start of the input value. 
   (e.g. BV_B___Vs_ where B and S are fixed characters and s is the character which is typed in. Notice the two fixed characters generated at the start)

**Comment by RobinHerbots** [comment]
Update fiddle
https://jsfiddle.net/esojkpwp/6/

**Comment by RobinHerbots** [comment]
@gayanj , 

Fixed!

Have a look at the new https://jsfiddle.net/esojkpwp/7/
