### ISSUE TITLE
Disable show mask on hover

### ISSUE THREAD

**Issue by tslatt** [RobinHerbots/Inputmask#130]
When you hover over a field, it shows the mask. I only want it to be shown when you actually click in side the field. Is there any way to do that?

**Comment by RobinHerbots** [comment]
Hi tslatt, 

I will add an extra option showMaskOnHover.

best regards, 

Robin

**Comment by tslatt** [comment]
Thank you so much! I am using the “over label” technique as described on ALA http://www.alistapart.com/articles/makingcompactformsmoreaccessible/ , and with the masking guide showing up on hover, you can see both it and the label overlapping each other. Since the label disappears on click, having the mask not show up until click would be ideal.

Thanks for the quick response!

Tonya Slatt

**Comment by RobinHerbots** [comment]
Done !!

**Comment by nyomanid** [comment]
Thanks, i also looking for this answer.

Great!!!

**Comment by dmacompton** [comment]
Thank you @RobinHerbots
