### ISSUE TITLE
Rounding error for numeric aliases

### ISSUE THREAD

**Issue by ivodopyanov** [RobinHerbots/Inputmask#1300]
https://jsfiddle.net/LtjyjL1p/

Input number "111111111111111.13" - it transforms into "111111111111111.12"

Obviously, this happens because parseFloat function in numeric.onBeforeWrite.
Maybe, you could've omit that conversion string -> float -> string if float number fits in min-max interval? So that original value would remain unchanged.

**Comment by RobinHerbots** [comment]
@ivodopyanov , 

This is fixed in the current version on github.  Can you confirm?

**Comment by ivodopyanov** [comment]
@RobinHerbots Yes, it's working. Thanks.
