### ISSUE TITLE
Persian Character

### ISSUE THREAD

**Issue by SBrh** [RobinHerbots/Inputmask#1306]
Hi,
can i use the mask for persian characters?
does it support persian?

**Comment by afattahi54** [comment]
Yes it supports, but you need to define valid Persian character range

```
Inputmask.extendDefinitions({
        //Persian character and numbers (and space!)
        'f': {
            validator: "[0-9\u060C-\u0638\u0639-\u0648\u06A9\u06AF\u06CC\u067E\u0686\u064A\u0649\u0626\u0698 ]",
            cardinality: 1
        }
});
```

and then

```
            input.inputmask( "f{*}");
```

**Comment by SBrh** [comment]
thank you
After your guidance, I used this code and it works:
$.extend($.inputmask.defaults.definitions, {
        'f': {  //masksymbol
            "validator": "[0-9\u060C-\u0638\u0639-\u0648\u06A9\u06AF\u06CC\u067E\u0686\u064A\u0649\u0626\u0698\A-Za-z!#$%&'*+/=?^_`{|}~\-]",
            "cardinality": 1
        }
    });

**Comment by SBrh** [comment]
thank you
After your guidance, I used this code and it works:

```
$.extend($.inputmask.defaults.definitions, {
        'f': {  //masksymbol
            "validator": "[0-9\u060C-\u0638\u0639-\u0648\u06A9\u06AF\u06CC\u067E\u0686\u064A\u0649\u0626\u0698\A-Za-z!#$%&'*+/=?^_`{|}~\-]",
            "cardinality": 1
        }
    });
```

**Comment by RobinHerbots** [comment]
@afattahi54 , 

Thx for replying

**Comment by oghanbari** [comment]
> Yes it supports, but you need to define valid Persian character range
> 
> ```
> Inputmask.extendDefinitions({
>         //Persian character and numbers (and space!)
>         'f': {
>             validator: "[0-9\u060C-\u0638\u0639-\u0648\u06A9\u06AF\u06CC\u067E\u0686\u064A\u0649\u0626\u0698 ]",
>             cardinality: 1
>         }
> });
> ```
> 
> and then
> 
> ```
>             input.inputmask( "f{*}");
> ```

hi, how we can apply groupSeperator : ',' for this custom definition?
