### ISSUE TITLE
Using with webpack (AMD)

### ISSUE THREAD

**Issue by osaris** [RobinHerbots/Inputmask#1308]
I can't get jquery.inputmask to work with webpack through bower (tell webpack to look into bower folder and use bower.json to find the main file, nothing fancy).

The problem is :

```
ERROR in ./resources/assets/vendor/jquery.inputmask/dist/inputmask/inputmask.js
Module not found: Error: Cannot resolve module 'inputmask.dependencyLib' in /workspace/resources/assets/vendor/jquery.inputmask/dist/inputmask
 @ ./resources/assets/vendor/jquery.inputmask/dist/inputmask/inputmask.js 9:48-94
```

If I look at line 9 of inputmask.js, the code try to use `inputmask.dependencyLib` as a dependency : `define([ "inputmask.dependencyLib" ], factory)` but there is no `inputmask.dependencyLib` in the jquery.inputmask package ?

Can you help me ?

**Comment by RobinHerbots** [comment]
@osaris , 

I still need to fix the configs for the different packaging systems.

Have a look at #861

**Comment by ksrb** [comment]
@osaris check out this [gist](https://gist.github.com/ksrb/47f9124c2f5be13f39dc645405a12608) and see if it works for you.

**Comment by RobinHerbots** [comment]
@ksrb , 

Thx for sharing !!

**Comment by stijnherreman** [comment]
@ksrb works for me as well, thanks. I've referenced your gist on http://stackoverflow.com/questions/38016359/what-is-the-proper-way-to-import-jquery-inputmask/38093593#38093593

**Comment by ksrb** [comment]
Great to see that it works for you too.

**Comment by RobinHerbots** [comment]
@osaris , 

Do you still have problems? Otherwise update to version 3.3.5.  I also updated the readme
