### ISSUE TITLE
change addEventListener not fired in IE11

### ISSUE THREAD

**Issue by sozedk** [RobinHerbots/Inputmask#1310]
I have an application written almost completely in vanilla js and now I am having difficulties integrating inputmask;

`Inputmask().mask(document.querySelectorAll('input'));
document.querySelector('.js-myfield').addEventListener('change', function () { console.log('hello world'); });`

If I do not use inputmask my change event is fired, but if I use inputmask the change event is not fired. If I rewrite the code to use jQuery - e.g. $('.js-myfield').change(.... - instead then it is fired, but rewriting every event to jQuery it not an option.

Any idea why and/or how to fix it?

**Comment by RobinHerbots** [comment]
@kila03 , 

Try using the inputmask.dependencyLib.js  from extra/dependencyLibs

**Comment by sozedk** [comment]
@RobinHerbots 

It makes no difference - only a jquery change event is triggered, not the vanilla js. My inputmask is working as expected.

I have tried using the bundle in dist, single inputmask and numeric extensions js files from dist/inputmask and different order of the js-files but with same result.

**Comment by RobinHerbots** [comment]
@kila03 , 

But did you load the vanilla dependencylib?

I will have a try.

**Comment by RobinHerbots** [comment]
@kila03, 

That seems to work.

So you added 

```
<script src="extra/dependencyLibs/inputmask.dependencyLib.js"></script>
<script src="js/inputmask.js"></script>

....

Inputmask("0800-999-9999").mask("test3");
document.querySelector('#test3').addEventListener('change', function () {
            console.log('hello world');
});

....

```

**Comment by sozedk** [comment]
@RobinHerbots 

Yes, vanilla dependencylib was included. I deleted everything, downloaded the package again and started over and now it works - must have been a spelling mistake or something. Thanks for the help and your patience :+1:

**Comment by sozedk** [comment]
@RobinHerbots 

Sorry for reopening this issue, but I have some new testing results. The example you gives puts on mask in all tested browsers, but only in FF and Chrome the change event is fired, in IE11 the change event is not fired. I have tested with release 3.3.1 and 3.3.2-65.

**Comment by RobinHerbots** [comment]
@kila03 , 

No problem.  I will have a look when time allows.

**Comment by sozedk** [comment]
@RobinHerbots 

I have been digging a bit more because this has high priority in my solution (guess everybody says that...) and I have a bit extra information if that can help you in any way. If I dont add the keypress and input event in the dependencyLib - I am just temporary adding

`if (ev === 'keypress' || ev === 'input') { return; }`

in top of the addEvent function - then my change events works as expected. Mayhaps that can narrow down your search.

**Comment by RobinHerbots** [comment]
@kila03 , 

There was a bug in the inputmask.dependencylib.js.  The eventname was not passed correctly.

**Comment by sozedk** [comment]
@RobinHerbots 

Awesomeness :+1:  - except I should probably have seen that myself :)
