### ISSUE TITLE
change inserting value

### ISSUE THREAD

**Issue by ChocoTUx** [RobinHerbots/Inputmask#1311]
Hi, pls I need help. 

I want change some char (escape diacritics 'č' to 'c') before apply mask regular restriction. But I cant find any usefull method. I think, that is function of onBeforePastes, but its whit no effect. 

Thank you. 

Roman

**Comment by RobinHerbots** [comment]
@ChocoTUx , 

So you want to substitue the 'č' to 'c'?

**Comment by ChocoTUx** [comment]
Ye, and other similar chars using in UTF-8 and not included in ASCII (all czech, polish, slovakia etc... special symbols).

**Comment by RobinHerbots** [comment]
Create a custom definition which accepts all chars.

To give an idea

```
Inputmask("r{*}", {
            definitions: {
                "r": {
                    validator: function (chrs, maskset, pos, strict, opts) {
                        var isvalid = //check chrs is valid input also include the special chars
                        if(isValid){
                            if(special char){
                                return  { c: substituted };
                            }

                            return true; 
                        }
                        return false;
                    },
                    cardinality: 1
                }
            },
        }).mask(selector);
```

**Comment by RobinHerbots** [comment]
@ChocoTUx , 

Sorry I didn't read thorough.  You want to substitude before.

Use the onBeforeMask

**Comment by ChocoTUx** [comment]
In fact I want change during writing new symbols (some active after onKeyDown and mask apply on it). onBeforeMask change only first initional or it have no efect at new symbols (I set return fixed "A" and nothing change).

**Comment by RobinHerbots** [comment]
@ChocoTUx , 

Then you need a custom definition as showed previously

**Comment by ChocoTUx** [comment]
@RobinHerbots yep, Im sory, Im not concentrate on your code, it looks like good way to solve my problem. 
Thank you.I´ll go try it. 

Roman

**Comment by ChocoTUx** [comment]
Thank you one more time. Its work, but I know this solotions is absolutly out of my possible without your help. 

``` javascript
'B': {
       validator: function (chrs, maskset, pos, strict, opts) {
             var valExp3 = new RegExp("[0-9A-Za-z.,\-/ ]");
            if (!valExp3.test(chrs)) {
                 var removed = removeDiacritics(chrs);
                 if (!valExp3.test(removed)) {
                       return false;
                      } else {
                     return { c: removed };
                 }
              } else {
                 return true;
             }
       },
       cardinality: 1,
           casing: "upper"
}`
```
