### ISSUE TITLE
No left bracket

### ISSUE THREAD

**Issue by EASemashko** [RobinHerbots/Inputmask#1313]
Hello, I use plugin, but my mask looks like this
http://i.imgur.com/p3Bd3KE.png

**Comment by ksrb** [comment]
@EASemashko going to save the author a little effort, but you should definitely make a minimal use case (aka a jsfiddle or codepen) for him to view or else no one is going to be able to help you.

**Comment by ksrb** [comment]
@EASemashko I had [codepen](http://codepen.io/anon/pen/WxExmk?editors=1010) I created earlier that I've updated to use the latest version of jquery.inputmask.

**Comment by RobinHerbots** [comment]
@EASemashko ,

Is this solved, what is the mask?  Can you provide some more info

**Comment by esoyke** [comment]
I had to double escape square brackets [ ] to allow them in my pattern
