### ISSUE TITLE
Cannot enter 0 when number is highlighted AND using placeholder.

### ISSUE THREAD

**Issue by briguybart** [RobinHerbots/Inputmask#1315]
If there's a numeric field that is highlighted, and it has a placeholder, I cannot enter 0.  Any other digit can be entered, but not 0.

Here's a fiddle:

http://jsfiddle.net/wxjn96rk/3/

Thanks!

**Comment by RobinHerbots** [comment]
@briguybart, 

Fixed in the current on github
