### ISSUE TITLE
Provide minified versions of JavaScript files in NuGet package jQuery.InputMask

### ISSUE THREAD

**Issue by maboivin** [RobinHerbots/Inputmask#1318]
In the NuGet package jQuery.InputMask (https://www.nuget.org/packages/jQuery.InputMask/), please provide the minified versions of all the JavaScript files. They seem to be already available in the releases. JQuery includes them, Knockout does it also and many other libraries do it.

For us, we're using RequireJS and would use the minified version for Release builds and debug versions in Debug builds. In our case, we don't use ASP.NET bundles anymore.

**Comment by RobinHerbots** [comment]
@maboivin , 

The next release will include the minified files on nuget
