### ISSUE TITLE
On IE and Opera, when you tab into a field, the cursor is positioned after the mask.

### ISSUE THREAD

**Issue by tslatt** [RobinHerbots/Inputmask#132]
In any other browser, tabbing into a field selects the entire mask, so that when you type a character, it goes in the first character position. However, in IE and Opera, it does not select the entire mask. Instead, it puts the cursor after the last character position, so that typing does nothing. The use then has to reposition the cursor to type.

How can we force the cursor to be at the first character position?

**Comment by RobinHerbots** [comment]
Hi tslatt, 

With which versions does this occur?  Can you also provide a little demo (jsfiddle).

best regards, 

Robin

**Comment by tslatt** [comment]
This happens on IE 7/8/9 and Opera 11.5. It works fine on FF16, Chrome 22, and Safari 5. Sorry, I couldn't quite figure out how to set up a jsfiddle (so far), and my site isn't live yet, so it's difficult to show an example.

**Comment by tslatt** [comment]
OK, I figured out how to do a jsfiddle: http://jsfiddle.net/3MHJY/

Type something in the first field and then click the tab button to get to the next field. In IE and Opera, the cursor will be positioned after the "**_-**_-____", so that if the user just starts typing, nothing will happen because they need to reposition the cursor first.

**Comment by RobinHerbots** [comment]
Hi tslatt, 

Thx for the feedback.

Issue fixed

Best regards

Robin
