### ISSUE TITLE
Phone 89xxxxxxxx

### ISSUE THREAD

**Issue by Dr0id14** [RobinHerbots/Inputmask#1321]
If i input phone (+8-963-345-67-89) instead (+7-963-345-67-89), the page freezes. This occurs when the quick commissioning "896". Why?

**Comment by RobinHerbots** [comment]
@Dr0id14 , 

Is this about the phone alias?  Can you give an example of the mask with option.  (jsfiddle)

Which version do you use?

**Comment by Dr0id14** [comment]
In version 3.3.2-43 does worked. Thank you.
