### ISSUE TITLE
IP Address looks like it forces 3 digit (b-bit part)

### ISSUE THREAD

**Issue by surfer190** [RobinHerbots/Inputmask#1323]
So an ip like: `182.112.232.211` is fine but `10.0.0.2` is not

**Comment by RobinHerbots** [comment]
@surfer190 , 

It does not force you 3 digits.  Try with just typing 10.0.0.2 also type the dots

**Comment by surfer190** [comment]
Sorry my mistake, it works a charm.
Thanks for making this repo.
