### ISSUE TITLE
Autogroup cursor position problem

### ISSUE THREAD

**Issue by tendais** [RobinHerbots/Inputmask#1325]
Using the decimal mask with
        radixPoint: ",",
        digits: 2,
        digitsOptional: false,
        autoGroup: true,
        groupSeparator: ".",
        groupSize: 3
The mask has a strange behavior. When the input is selected, the cursor goes to the last position after de radix comma, the deciimal part of the number, and when a digit is inserted two digits are displayed before radix comma  on the int part of the number.
If AutoGroup is disabled the cursor continuous to go to the last position after de redix comma, when a digit is inserted, only one number appears but appears before the comma.

I have already try use 
        rightAlignNumerics: false,
        numericInput: true

but i don't have any luck.

I want the cursor on the last place before de comma, like before i have updated to this last version and like when i move to the input using the tab where the behavior is the correct one..

You can see the sample here https://jsfiddle.net/ujf3ncsy/2/

**Comment by RobinHerbots** [comment]
@tendais , 

Can you retry with the current version on github
