### ISSUE TITLE
Wrong value on init

### ISSUE THREAD

**Issue by douglasdtc** [RobinHerbots/Inputmask#1328]
With the mask alias "numeric" and "numericInput" set to "true", when trying to inicialize the component with the default value "237,38" it ignores the first digit and considers only the "37,38". If we initialize it with the value "23738" it works fine.

Here's a demo:
http://jsfiddle.net/msj5qfu1/162/

**Comment by douglasdtc** [comment]
@RobinHerbots, why is this modified to milestone 3.5? We have another issue open too, also modified to milestone 3.5. We would like to know if it's going to take too long, if that's the case, we will need to change the plugin, or custom build one. Thank you.

**Comment by RobinHerbots** [comment]
Don't worry you got my attention.

**Comment by douglasdtc** [comment]
Thank you for the quick feedback @RobinHerbots , that's great.
