### ISSUE TITLE
Can't insert . with numeric alias

### ISSUE THREAD

**Issue by stealthjong2** [RobinHerbots/Inputmask#1329]
With both a Samsung GT-P5220 (Android 4.4.2) and a Nexus 7 (2013, Wifi, Android 6.0.1) I can't insert a dot/decimal mark on an alias:decimal or alias:numeric input (both stock browser, as I load it in a webview). The rest works as expected (no other chars except numbers, and minus sign).

`<input type='text'`data-inputmask-alias='decimal'>`

`Inputmask().mask(document.querySelectorAll('input[data-inputmask-alias]'))`

On my computer (chrome 51.0), it works just fine. Using jquery inputmask 3.3.2-43 (bundle)

**Comment by RobinHerbots** [comment]
@stealthjong2 , 

The latest commit fixes the entry of the radixPoint on android.  
But beware that there are still some other issues when used on android.  (inputfallback)  I still got issues regarding positioning the caret when using ex.  currency alias.
