### ISSUE TITLE
Buggy numeric extension with pre init value

### ISSUE THREAD

**Issue by xicond** [RobinHerbots/Inputmask#133]
Buggy numeric extension with pre init value 522525, result as 522 with
$('.numeric').inputmask('decimal', { radixPoint: ',', autoGroup: true, groupSeparator: '.', groupSize: 3, repeat:22, digits:2 });
is there any mistake I'd write?

**Comment by RobinHerbots** [comment]
hi xicond,

The pre init value issue is fixed in the latest version.

best regards, 

Robin
