### ISSUE TITLE
Prefix for custom regexp

### ISSUE THREAD

**Issue by andrey-lizunov** [RobinHerbots/Inputmask#1334]
Hello. Is it possible to add prefix for custom regexp, not for `decimal`?
For example, I want to add `http://` prefix in inputs for social network accounts.
Thx.

**Comment by RobinHerbots** [comment]
@andrey-lizunov , 

Can you explain a bit more?  Example.

**Comment by andrey-lizunov** [comment]
@RobinHerbots For example for decimals I can set `prefix: '$'` and it will be not erasable prefix in input.
How can I make the same prefix in non decimal fields?

**Comment by RobinHerbots** [comment]
@andrey-lizunov , 

Just put it in the mask.  Ex: TT-

```
Inputmask("TT-999999").mask(selector);
```
