### ISSUE TITLE
Specific unmasking

### ISSUE THREAD

**Issue by hinduCoder** [RobinHerbots/Inputmask#1335]
I have a mask "+7 (\999) 999-99-99". I need an unmasked value to be +79123456789. What is the best way? Can I use some magic or I have to do it by hand?

**Comment by RobinHerbots** [comment]
@hinduCoder , 

implement the onUnMask callback, which passes already the masked and unmaskedvalue as arguments.

So if you add +79 before the unmaskedvalue and return it you are done.

**Comment by RobinHerbots** [comment]
@hinduCoder , 

I will add the functionality to specify the outputformat for unmasking.  Follow issue #2526
