### ISSUE TITLE
Question: numeric mask extension

### ISSUE THREAD

**Issue by Enfree** [RobinHerbots/Inputmask#1337]
Hi, I'm looking for workaround for https://github.com/RobinHerbots/jquery.inputmask/issues/1329
Found that rootcause in events, firing by browser: it seems, keydown event doesn't trigger, only keypress and input. Input handler (inputFallBackEvent) invokes checkVal, checkVal invokes onBeforeWrite, where is clause
`if (e && (e.type === "blur" || e.type === "checkval" || e.type === "keydown"))`
e.type is 'checkval' and its cause 
`processValue = floatValue.toString().replace(".", opts.radixPoint).split('');`
that loses radix symbol. With clause 
`if (e && (e.type === "blur" || e.type === "keydown"))`
all works fine. Could it be that `e.type === "checkval"` is redundant?

**Comment by RobinHerbots** [comment]
@Enfree , 

Thx for the extra info.  Sorry that there is barely response currently but all time I spend on the inputmask goes to the alternation logic..

Can you pass inputEventOnly: true as extra option and test the same in Chrome on PC.    Does this gives the same issue?

**Comment by Enfree** [comment]
@RobinHerbots ,
Thx for reply :)

Yep, with inputEventOnly: true issue the same. Tested under PC Chrome(45.0.2454.101) and Firefox(47.0.1)

**Comment by RobinHerbots** [comment]
@Enfree , 

Latest commit fixes the entry of the radixPoint. 

I still struggle with positioning the caret correctly when using the currency alias with the inputfallback.
