### ISSUE TITLE
'max' on numeric aliases ... how do I do it?

### ISSUE THREAD

**Issue by CrowdForge** [RobinHerbots/Inputmask#1338]
So in the simplest form, I've tried this:

```
jQuery("#award-entry").inputmask({
  alias: 'currency', max: '999'});
```

However I'm allowed to enter a number of any size.  How do I limit the size of the number that can be entered?

**Comment by RobinHerbots** [comment]
@CrowdForge , 

The validation against the max and min value is done at blur.

You can use the postValidation callback to implement the bahavior.

**Comment by CrowdForge** [comment]
Ah just one more question, when I get "buffer" it displays the value as an area.  The docs say  buffer, currentResult, and opts are passed to postValidation.  How do I convert that buffer to a value for testing?

**Comment by CrowdForge** [comment]
Got it actually!  Thanks for the great plugin!
