### ISSUE TITLE
with Chrome and jquery ui datepicker:  Uncaught TypeError: Cannot read property 'textContent' of null 

### ISSUE THREAD

**Issue by thebirisi** [RobinHerbots/Inputmask#134]
Hı 
I have used the datepicker with inputmask 

chrome console throw error.   when a date selected from datepicker

Error: Uncaught TypeError: Cannot read property 'textContent' of null 

$(".date").datepicker();
$(".date").inputmask("dd.mm.yyyy", { "placeholder": "_", "clearIncomplete": true });

**Comment by RobinHerbots** [comment]
Hi theberisi, 

I will have a look at it.

Which versions do you use? jquery-ui & inputmask.

Can you create an example in jsfiddle?

best regards, 

Robin

**Comment by thebirisi** [comment]
jquery ui 1.8.2 and inputmask 1.2 

Thank you for your interest in

**Comment by thebirisi** [comment]
http://jsfiddle.net/pWyPm/3/
I have wrote code this
but there are no error

**Comment by RobinHerbots** [comment]
I will close the issue.  

If you can reproduce the issue, feel free to reopen and give more info.

best regards, 

Robin
