### ISSUE TITLE
Unable to get property 'forwardPosition' of undefined or null reference IE11

### ISSUE THREAD

**Issue by iamonzon** [RobinHerbots/Inputmask#1342]
Hi bud, 
I'm having a little trouble with IE11 compatibility. It's working perfectly on Firefox & Chrome. 
I'm working with accessibility technologies, like screen reader and aria-attribs. The first challenge was to place the pointer at begin of mask (| **/**/***_) I had a lot of troubles to solve thisone, because there's no easy function to place it where you want.
I solved it by : 
`if(isIE())
                {
                        $("#formCreateSR\:sec_InfoVC_Fecha").on('focus', function()
                        {
                            setTimeout(function()
                            {
                            $("#formCreateSR\:sec_InfoVC_Fecha").inputmask(
                                        "d/m/y",
                                        {"placeholder": "_",
                                         showMaskOnHover: false,
                                         showMaskOnFocus: false
                                });
                            }, 100);
                        });
                       }`

It places the pointer at beginning at then apply the mask. 
The next challenge, is to get out from this field.  Apparently, when I press TAB it doesn't redirect to the next field. It's like it shows the complete mask pointing at the end (**/**/***\* |)  And then, it places again at the beginning, like at first. 
I get this error : SCRIPT5007: Unable to get property 'forwardPosition' of undefined or null reference
inputmask.js (1805,5)

Thanks for your help, and I hope we can find a solution to make this even better. 
Thanks for your effort, keep it up ! 

Best regards, Iván.

**Comment by RobinHerbots** [comment]
@ivanlp10n2 , 

Which version do you use of the inpurmask?
Can you make a jsfiddle for this.  That makes it much easier for me.
