### ISSUE TITLE
By default, tabbing into input field selects all text inside. How can I make it to set cursor at beginning of blank space?

### ISSUE THREAD

**Issue by stil** [RobinHerbots/Inputmask#1343]
I have some input fields, that are prefilled with numbers.
However, you have to fill the rest of it manually, so it usually looks like this:

`123___`

Now, I like to use Tab to switch between fields. It makes my work so much faster, than using mouse.
The problem is that tabbing into partially filled field selects all text inside.
I would like to set cursor after `3` as in example, just at beginning of blank space.

Is there any simple hack to solve my problem?

**Comment by desyncr** [comment]
Try with: 

``` js
  positionCaretOnClick: "lvp",
  radixFocus: true,
```

Good luck!

**Comment by stil** [comment]
``` js
positionCaretOnTab: true
```

did the trick for me. Thanks for help!

**Comment by RobinHerbots** [comment]
@stil , 

Great, you already figured it out.  Maybe I should change the default to true for positionCaretOnTab

**Comment by stil** [comment]
I think it's a good idea, from the perspective of UX. If someone uses Tab to navigate between fields and he needs to select all text, he can just use `Ctrl + A`.

Most people use mouse instead of keyboard, but those who use keyboard will very likely also know `Ctrl + A` or `Ctrl + X`.

I use your library mainly for rewriting data from paper documents to the database. I find default behaviour of Tab (selecting all text) useless, so I just changed mentioned setting right now.

**Comment by RobinHerbots** [comment]
@stil , 

Done!
