### ISSUE TITLE
dual symbols on windows mobile

### ISSUE THREAD

**Issue by AliveDD** [RobinHerbots/Inputmask#1344]
phone: Lumia 535
platform: WP10
browser: Microsoft Edge
testing page: http://robinherbots.github.io/jquery.inputmask/
**i write 1234567 in input phone field and i get 11223445667**
dont ignore it, please help

---

![oq_c-ebbm2o](https://cloud.githubusercontent.com/assets/5255027/17212557/0ff2edb0-54e1-11e6-8a4f-581031db6f3c.jpg)

**Comment by AliveDD** [comment]
also, if we use inputmask in a project with webpack and uglyfy, and insert the plugin in a project with string `require('./vendor/jquery.inputmask.bundle.min.js')` — code does not open in windows edge. App dropped with error:
`SCRIPT606: Failed to complete the action. Error 800a025e.
main.js (14367,91)`

its a translate from Russian:
`SCRIPT606: Не удалось завершить действие. Ошибка 800a025e.
main.js (14367,91)`

**Comment by AliveDD** [comment]
Windows takes about 2 percent of the worlds mobile market (by 2016).
Can we close this task? without performing

**Comment by RobinHerbots** [comment]
@AliveDD , 

Do you still have the problem with the current version on github?  Tried with browserstack without problems
