### ISSUE TITLE
HTML5-like placeholder when numeric mask is empty

### ISSUE THREAD

**Issue by stil** [RobinHerbots/Inputmask#1345]
How can I achieve similiar behaviour like in this example: https://jsfiddle.net/55eb6pky/1/

Basically, when input is empty I'd like to set its value to custom text (in my case, about a dozen of asterisks). However, when I start entering number values, the placeholder disappears and only numbers are shown.

My jsfiddle example is _almost_ working, except that `placeholder=""` attribute is not actually included in POST fields on form submit. Any hint how to make it work?

**Comment by RobinHerbots** [comment]
@stil , 

Sorry, but what exactly is missing?  Can you explain better what you mean.

**Comment by stil** [comment]
Sorry if I wasn't precise enough.
I would like the placeholder text (`***** kg` in my case) to be included in POST field when submitting the form. It doesn't work like that and just the empty value is sent.
Look at this fiddle: https://jsfiddle.net/jqus9y3o/

How would I have this behaviour, but without actually using HTML5 `placeholder=""` attribute, as we know it isn't sent over POST form.

**Comment by stil** [comment]
Okay, hacked it. Here is my solution, with super clever use of prefix option: https://jsfiddle.net/r2wc7ou1/

**Comment by SalomaoMiguel** [comment]
Yes cool. Amazing
