### ISSUE TITLE
Version 1.2 Issue

### ISSUE THREAD

**Issue by noahc** [RobinHerbots/Inputmask#135]
I have found an issue with version 1.2 that didn't happen previously with 1.0.x. 

When I have something like: $("#something").inputmask "mm/dd/yyyy"

and I enter 01/01/2012 and then want to delete the whole line and start again and I hit the backspace three times and get "01/01/202" and the oncomplete also fires, which I don't believe it should.

Any thoughts on why this is happening?

After further testing it affects Firefox 16.0.2, but not Safari, Chrome, or IE 8.0

**Comment by RobinHerbots** [comment]
Hi Noah,

Can you specify in which browser as I cannot reproduce the problem.

best regards,

Robin

2012/11/12 Noah Clark notifications@github.com

**Comment by noahc** [comment]
Firefox 16.0.2 specifically.

Here is a video I made of the issue: http://www.youtube.com/watch?v=RS1jltjOoLg

**Comment by RobinHerbots** [comment]
Ok will check this tomorrow.

Best regards, 

Robin

**Comment by RobinHerbots** [comment]
fixed!

Robin
