### ISSUE TITLE
How can I define a custom mask allows any value but with custom prefix and postfix?

### ISSUE THREAD

**Issue by artptr** [RobinHerbots/Inputmask#1350]
Hello! Thank you again for the great library.

We need to apply various masks to input dynamically. And there is a special case when an input should be unrestricted (i.e. as simple text field) but it may contain some non-removable prefix or postfix.

For example:
- prefix="$", input: `$20`, `$10000+15%`, `$100-$500`, `$1000 incl. VAT`,...
- postfix=" year(s)", input: `5 year(s)`, `no more than 10 year(s)`, `two year(s)`,...

Also the prefix and postfix may contain any symbols including special mask symbols. We can't foresee it.

Is it may be implemented with custom definition?

**Comment by RobinHerbots** [comment]
@artptr , 

Can't you use Inputmask("_{_} \ye\ar(\s)").mask(selector)

**Comment by artptr** [comment]
Thank you. I already tried to make it the same way:

```
function escapeAll(str) {
    return str.replace(/(.)/g, "\\$1");
}

var mask = {
    definitions: {
        "*": {
            validator: ".",
            cardinality: 1,
        }
    },
    mask: escapeAll(prefix) + "*{*}" + escapeAll(postfix)
};
```

But there is a bug with the postfix: its first symbol is repeated before the inputed symbol if we input it while the caret is placed in the end of the postfix – https://jsfiddle.net/ezdtqqrr/1/

**Comment by RobinHerbots** [comment]
Updated fiddle  https://jsfiddle.net/ezdtqqrr/2/

But the above case is intresting.

**Comment by artptr** [comment]
I'm sorry, but what did you change in the fiddle?

**Comment by RobinHerbots** [comment]
@artptr , 

Just the ref to the inputmask.  The cdn was behind.

**Comment by artptr** [comment]
Wow! Thank you!
