### ISSUE TITLE
Currency digits and delete

### ISSUE THREAD

**Issue by kousenlsn** [RobinHerbots/Inputmask#1351]
When using the currency alias, pressing delete does not reach the digit numbers.

```
    $('#HourlyCost').inputmask({
        max: '99999999.99',
        alias: 'currency',
        prefix: '',
        allowPlus: false,
        autoUnmask: true,
    });

```

If using decimal protection, pressing delete works, but if you enter a value like 32.32, blur and refocus the field, and enter any value like 2, it will change to 23232.00

**Comment by kousenlsn** [comment]
Would appreciate any help or input on that

**Comment by RobinHerbots** [comment]
When I am back trom vacation I will fix it.

Op ma 15 aug. 2016 18:33 schreef Kousen Luersen notifications@github.com:

**Comment by RobinHerbots** [comment]
@kousenlsn , 

Which version do you use?  Can you make a jsfiddle which shows the problem.

I cannot reproduce.

**Comment by kousenlsn** [comment]
https://jsfiddle.net/kousenlsn/a4ngsc0p/

I couldn't reproduce the issue with the decimalProtect option here, but it is behavering exactly the same not reaching the digits when pressing delete.

Version: 3.2.6-24 I think
