### ISSUE TITLE
data-inputmask-casing not run with mask "*"

### ISSUE THREAD

**Issue by mbraz** [RobinHerbots/Inputmask#1352]
Hi, data-inputmask-casing not run with mask "*". 

The values not changed to upper case.

<input ...
data-inputmask-mask="***.***.***[.999]" 
data-inputmask-casing="upper"
/>

**Comment by RobinHerbots** [comment]
@mbraz , 

The casing is at the definition level and not as a general parameter.

But I will add such functionality.

**Comment by mbraz** [comment]
Thanks Robin!!

Enviado do meu iPhone 4S

**Comment by RobinHerbots** [comment]
This is fixed.
