### ISSUE TITLE
Initialize failed with autofocus

### ISSUE THREAD

**Issue by MHajisoft** [RobinHerbots/Inputmask#1353]
Hi

if an input has **autofocus** attribute, when initialize it by $('input').inputmask('Regex') it failes and shows the error below:

> jquery.inputmask.bundle.js:757 Uncaught TypeError: Cannot read property 'forwardPosition' of undefined
> 
> var caretPos = document.activeElement === input ? initiatingEvent ? caret(input).begin : result.forwardPosition : void 0, offset = getBuffer().length - input.inputmask._valueGet().length;

Edited: 
I am using the version 3.3.2-106

**Comment by RobinHerbots** [comment]
Which version do you use?

Op za 6 aug. 2016 07:51 schreef MHajisoft notifications@github.com:
