### ISSUE TITLE
Invalid date - 31/02/2016

### ISSUE THREAD

**Issue by iamonzon** [RobinHerbots/Inputmask#1356]
Hi Robin! I know you're pretty busy, there are a lot of people who's asking for different bugs. 
Probably you've already solved my actual-new issue. So here we go : 

I successfully added your plugin(input-date) into my page, and it works wonderful. Actually, I can input, for example, a 02/31/2017 date. Which is invalid :( 
Is there somehow way to fix this ? I'm thinking about using an array with onComplete and get the inputed value. Probably there's a more efficient way than that.

Can you give a hint? Thanks for your time and support.

**Comment by RobinHerbots** [comment]
@ivanlp10n2 , 

How did you define your mask?

**Comment by ghost** [comment]
Hi, Robin! I also found this issue.
You can enter invalid dates, like 02/31 or 04/31.
The mask is defined as "m/d/y" [fiddle](https://jsfiddle.net/e4saxfb6/)

**Comment by RobinHerbots** [comment]
@OzzyKh , @ivanlp10n2 ,

Only the date aliases include extra date validation.  d, m, y are just simple definitions.
I guess I will remove these definitions to prevent more mistakes.

```
"d": { //basic day
        validator: "0[1-9]|[12][0-9]|3[01]",
        cardinality: 2,
        prevalidator: [{
            validator: "[0-3]",
            cardinality: 1
        }]
    },
    "m": { //basic month
        validator: "0[1-9]|1[012]",
        cardinality: 2,
        prevalidator: [{
            validator: "[01]",
            cardinality: 1
        }]
    },
    "y": { //basic year
        validator: "(19|20)\\d{2}",
        cardinality: 4,
        prevalidator: [{
            validator: "[12]",
            cardinality: 1
        }, {
            validator: "(19|20)",
            cardinality: 2
        }, {
            validator: "(19|20)\\d",
            cardinality: 3
        }]
    }
```

**Comment by ghost** [comment]
Thank you for the reply. I'll be using other date aliases then.
