### ISSUE TITLE
当点击文本输入框时，光标会从最初位置向左跳动一格。

### ISSUE THREAD

**Issue by tuxiantian** [RobinHerbots/Inputmask#1358]
当点击文本输入框时，光标会从最初位置向左跳动一格。

**Comment by RobinHerbots** [comment]
@tuxiantian , 

Can you provide some more info about the mask used.  Or create a jsfiddle?

google translate:
你能否提供关于所使用的面膜一些更多的信息。或创建的jsfiddle ？
