### ISSUE TITLE
How can I get "-$123.45", not "$-123.45"?

### ISSUE THREAD

**Issue by thorn0** [RobinHerbots/Inputmask#1360]
There are prefixes, in particular currency symbols, which when used with negative numbers, should follow the minus sign, not precede it. `€-9.95` looks terribly wrong. Seems like jquery,inputmask doesn't support this so far. Would be great to have such a config option. It might look like following:

``` js
negationSymbol: { afterSuffix: "-" }
```

**Comment by JCMais** [comment]
If you can take the hit of having another plugin just for monetary value: https://github.com/plentz/jquery-maskmoney

But I still think both are wrong, negative monetary values should be inside parenthesis. `(€ 9.95)`

**Comment by RobinHerbots** [comment]
@JCMais , @thorn0 , 

The () notation is also supported.

I will make the change to reposition the negationSymbol.

**Comment by RobinHerbots** [comment]
done
