### ISSUE TITLE
In valid Leap Year dates can be entered

### ISSUE THREAD

**Issue by Vaccano** [RobinHerbots/Inputmask#1368]
First, great mask.  This is the best one out there by far.

Here is the issue:
- Go to the [demo site](http://robinherbots.github.io/jquery.inputmask/) and enter this in to the date field: 28/02/1975
- Arrow back to the day field and change it to 29 (leap day)
- Tab out of the field
- RESULT: 29/02/1975 has been entered.  This is not a valid date (1975 was not a leap year.)

Expected:
- 29 would not be allowed because the year is 1975 (not a leap year)

**Comment by ghost** [comment]
Here's a possible fix #1389

**Comment by ghost** [comment]
@Vaccano, right, this change won't  fix your case - editing the date, but it works for another case - editing the month.

So, if you type 29/01/1975 and then try change 01 to 02 it won't let you do it.

For you case there's no code at all in the component.

**Comment by RobinHerbots** [comment]
@Vaccano , 

Finally fixed!

**Comment by Vaccano** [comment]
@RobinHerbots  Sweet!  Thanks for the fix!  Yours is the best mask library around.
