### ISSUE TITLE
Release for 3.3.2? locator undefined error

### ISSUE THREAD

**Issue by jamesj2** [RobinHerbots/Inputmask#1369]
Using the current release version (3.3.1) I'm hitting an `jquery.inputmask.bundle.js:613 Uncaught TypeError: Cannot read property 'locator' of undefined` error.   I've tested it with version 3.3.1, 3.3.0, 3.2.7 and 3.3.2-106 and it I can't reproduce it in 3.3.2-106 but it exists in the other versions.  So my question is will 3.3.2 be released soon?

[working](https://jsfiddle.net/jamesj22/zqbsr1kc/) and [failing](https://jsfiddle.net/jamesj22/zqbsr1kc/2/) fiddles

If you fill the mask by holding down the number 1 it works fine.  After highlighting and removing everything after the date (including space) and entering more #'s like three or 4 the locator undefined error shows up.  It usually happens on the second or third try.

**Comment by RobinHerbots** [comment]
@jamesj2 , 

I will release soon.  (september)
I want to complete the alternation logic for the phone alias before releasing.
