### ISSUE TITLE
Caret positioning automatic move last value?

### ISSUE THREAD

**Issue by ntnhieu** [RobinHerbots/Inputmask#1371]
Hi @RobinHerbots  and all,
I have a problem about when define a inputmask with Regex on input and after that I remove mask (using $(input).inputmask("remove")). 
Before I remove mask, the caret positioning is in top on value. But after removed mask, the caret positioning automatic move on last value?
How can disable it?
Thank you!!!

**Comment by RobinHerbots** [comment]
@ntnhieu , 

Can you make a jsfiddle to make the problem more clear.
