### ISSUE TITLE
Input Mask with Optional Characters

### ISSUE THREAD

**Issue by Sabayyal** [RobinHerbots/Inputmask#1372]
Hello Everyone,

I am very new to this!! I have one project that is using jquery.inputmask on one control.

I have Users to input their ID number which can be 5 digits to 9 digits long. (All numeric)
I am using following mask 

99999[9][9][9][9] 

According to my understanding first 5 can be digits only (0-9) then next 6th, 7th, 8th,9th should be numeric but should be OPTIONAL. (As I have used Optional Markers) . However the mask that shows up on TextBox Control is 

_ _ _ _ _ _ _    (7 digits only!!)

I can input 5 ,6 or 7 digits OK so the mask is working fine up to 7 digits but 8th and 9th digits are not being input.

Please help!

Thanks

Sabby

**Comment by RobinHerbots** [comment]
I tested with, and have no problem typing 123456789.  Which version do you use?  Can you create a jsfiddle. 

```
Inputmask("99999[9][9][9][9]", {greedy: false}).mask("test5");
```
