### ISSUE TITLE
Mask for numeric digits of variable length

### ISSUE THREAD

**Issue by Zaveed** [RobinHerbots/Inputmask#1373]
Hi,

I want to create a Mask for variable length of numeric characters. I want such a mask which would allow digits with any length from 5 to 9. But the Mask 99999[9][9][9][9] only allows seven digits and the mask 99999[9999] allows either 5 or 9 digits and nothing in between i.e.6,7 or 8 are not allowed. Can you please help me

**Comment by RobinHerbots** [comment]
duplicate of #1372
