### ISSUE TITLE
How to handle mask digits and allowed digits

### ISSUE THREAD

**Issue by GaikwadVikas** [RobinHerbots/Inputmask#1374]
I want to mask default two digits after the decimal, But allow to enter up to four digits.
How can I achieve it?
Kindly, reply. Thanks in advance.

**Comment by GaikwadVikas** [comment]
Hello, Any update please?

One more issue I am not able to change selected text to 0.

**Comment by RobinHerbots** [comment]
@GaikwadVikas , 

It is not possible out-of-the box.

I will add the functionality

**Comment by RobinHerbots** [comment]
@GaikwadVikas , 

Can you create a new issue for the second question and make a jsfiddle

**Comment by GaikwadVikas** [comment]
@RobinHerbots ,
Please, visit your [demosilte](http://robinherbots.github.io/Inputmask/)
Now enter any amount in Currency input. After that select that amount and press 0. It will not allow, But it is working for other than 0.
I want to change entered amount into 0.

I extended Aliases as below:

Inputmask.extendAliases({
                currency: {
                    prefix: "",
                    groupSeparator: "",
                    alias: "numeric",
                    placeholder: "0",
                    autoGroup: false,
                    digits: 4,
                    digitsOptional: true,
                    positionCaretOnClick: "none",
                    clearMaskOnLostFocus: false,
                    removeMaskOnSubmit: true,
                    autoUnmask: true
                }
            });

**Comment by GaikwadVikas** [comment]
@RobinHerbots ,
I think you should provide **maskDigits** option. If value not available for **maskDigits**, use digits.
So, I will set maskDigits to 2 and digits to 4.

**Comment by RobinHerbots** [comment]
@GaikwadVikas , 

Use "'2,4" as digits option

**Comment by GaikwadVikas** [comment]
Thank you very much @RobinHerbots ,
Love you man  😄
