### ISSUE TITLE
Problems with greedy dynamic masks in current version 3.x

### ISSUE THREAD

**Issue by Enfree** [RobinHerbots/Inputmask#1375]
Hi, there is a problem in current 3.x version
TC: 
- input 45464748 (got 4546 4748)
- put caret between 45 and 46
- try to input 0909

ER: got 4546 0909 4748
AR: got 454604748, cannot input any other letter

Reproduced under FF, Chrome, IE11
http://plnkr.co/edit/MLs5KsCXKHZfhlFC5T2K?p=preview
In 3.1 release version there was no such problem.

**Comment by RobinHerbots** [comment]
@Enfree , 

I added a unittest for it.

**Comment by Enfree** [comment]
@RobinHerbots 
Great! Can you tell when 3.4 will be realised? :)

**Comment by RobinHerbots** [comment]
@Enfree , 

There will be a 3.2.2 because solving for 3.4 will take too long.
