### ISSUE TITLE
Request for event hook

### ISSUE THREAD

**Issue by zdfs** [RobinHerbots/Inputmask#138]
I'd like to request an event hook. Currently, when a mask is applied and a user tries to key something that the mask won't allow, nothing happens. If the plugin fired an event whenever this happened, we could call a function that provided some sort of visual feedback.

Thoughts?

**Comment by RobinHerbots** [comment]
Hi Zachary,

I will add this as an optional extensions.

best regards

Robin

2012/11/18 Zachary Forrest y Salazar notifications@github.com

**Comment by zdfs** [comment]
Thank you sir.

**Comment by RobinHerbots** [comment]
Checkout latest in dev branch - onKeyValidation

Not implemented as an extention but just in the base.  See readme
