### ISSUE TITLE
input  12345.56 with decimals/money format and get the value ....

### ISSUE THREAD

**Issue by tiger822** [RobinHerbots/Inputmask#1380]
<input type="text" id="fl_sale_price" name="fl_sale_price" />

<script>
   $(document).ready(function(){
    $("#fl_sale_price").inputmask(m_messages.yuan+'999,999,999.99', { numericInput: true,   rightAlignNumerics: true, greedy: false,autoUnmask: true});
}
  $("#fl_sale_price,#fl_qty").change(function(){
       var lvPrice=$("#Win_Insert_d #fl_sale_price").val()*1.0;
       console.log(lvPrice);
});
);
</script>

console output 1234556

**Comment by tiger822** [comment]
`$("#fl_sale_price").inputmask(m_messages.yuan+'999,999,999.99', { numericInput: true, rightAlignNumerics: true, greedy: false,autoUnmask: true});

var lvPrice=$("#Win_Insert_d #fl_sale_price").val()*1.0;
console.log(lvPric);
`

**Comment by RobinHerbots** [comment]
@tiger822 , 

This is correct!  With the option autoUnmask: true you get the unmasked value on retrieving the value.

You can implement onUnMask callback to alter the unmasking value or use the numeric alias or set the autoUnmask to false
