### ISSUE TITLE
Not allowing to change existing number to 0

### ISSUE THREAD

**Issue by GaikwadVikas** [RobinHerbots/Inputmask#1381]
@RobinHerbots ,
Please, visit your [demosilte](http://robinherbots.github.io/Inputmask/)
Now enter any amount in Currency input. After that select that amount and press 0. It will not allow, But it is working for other than 0.
I want to change entered amount into 0.

I extended Aliases as below:

Inputmask.extendAliases({
                currency: {
                    prefix: "",
                    groupSeparator: "",
                    alias: "numeric",
                    placeholder: "0",
                    autoGroup: false,
                    digits: 4,
                    digitsOptional: true,
                    positionCaretOnClick: "none",
                    clearMaskOnLostFocus: false,
                    removeMaskOnSubmit: true,
                    autoUnmask: true
                }
            });

**Comment by GaikwadVikas** [comment]
One more thing, If value is zero then we get blank while posting data. If I forcefully enter zero value then it should work. Rather it sholud always return zero insted of blank. Because, I am using numeric masking.

Zero key should work like decimal key if all text is selected.

**Comment by GaikwadVikas** [comment]
@RobinHerbots , If you have in work around to fix this issue please tell me. I am stuck due to this issue.

Thanks

**Comment by RobinHerbots** [comment]
@GaikwadVikas , 

I will fix this, when time allows.

**Comment by BLSully** [comment]
+1 to this issue. This is the only pain point I've found so far using this plugin for doing currency input masks. For the application I'm working on, zeroing out an input is a common need.

Current workaround is "highlight and hit delete". This return 0 when the unmask() is called with the default placeholder of "0" and "unmaskAsNumber" set to true

**Comment by GaikwadVikas** [comment]
@BLSully , thanks buddy.

**Comment by ToddHoff** [comment]
Hi, does this issue have a fix or a workaround? I'm still experiencing it as a problem. Tab into a currency field and you can't enter a 0, which is a common task.

**Comment by Zoopme** [comment]
> 
> 
> Hi, does this issue have a fix or a workaround? I'm still experiencing it as a problem. Tab into a currency field and you can't enter a 0, which is a common task.

Same here. using `$field.val(0);` and getting an empty field.
