### ISSUE TITLE
Build failure in heroku after release of 3.3.2

### ISSUE THREAD

**Issue by infomongo** [RobinHerbots/Inputmask#1384]
Got a build failure in heroku this am. Error is:

 Running "browserify:website-dist" (browserify) task  
remote:        >> Error: Cannot find module './inputmask.dependencyLib.jquery' from '/tmp/build_b19e952dfeffdca824373dbe7f5ac4dd/node_modules/jquery.inputmask/dist/inputmask'  
remote:        Warning: Error running grunt-browserify. Use --force to continue.   

our package.json looked like this
`"jquery.inputmask": "^3.2.7",`

Changing it to the following fixed our build problem

`"jquery.inputmask": "3.3.1",`

Leaving this mostly as it might help others.

**Comment by RobinHerbots** [comment]
The dependencymib is moved tot extra/dependencylibs

**Comment by dangreen** [comment]
After installing jquery.inputmask@3.3.2 from npm:
`node_modules/jquery.inputmask/dist/inputmask/inputmask.js`  file requires `./inputmask.dependencyLib.jquery`, but `node_modules/jquery.inputmask/dist/inputmask/inputmask.dependencyLib.jquery` doesn't exist.

**Comment by RobinHerbots** [comment]
@infomongo , @dangreen , 

I will put the depencylib back in place
