### ISSUE TITLE
Uncaught SyntaxError on jquery.inputmask.bundle.js:42

### ISSUE THREAD

**Issue by cloudcaptain** [RobinHerbots/Inputmask#1385]
### Error: Unexpected token I in JSON at position 1

**Here's my mask:**
`var IDR={"alias":"numeric","prefix":"Rp","digits":0,"digitsOptional":false,"decimalProtect":true,"groupSeparator":",","radixPoint":".","radixFocus":true,"autoGroup":true,"autoUnmask":true,"removeMaskOnSubmit":true};`
`Inputmask.extendAliases({"IDR": {"alias":"numeric","prefix":"Rp","digits":0,"digitsOptional":false,"decimalProtect":true,"groupSeparator":",","radixPoint":".","radixFocus":true,"autoGroup":true,"autoUnmask":true,"removeMaskOnSubmit":true} });
`

**The following ALL produce the error:**
`jQuery('selector').inputmask(IDR)`
`jQuery('selector').inputmask("IDR")`
`jQuery('selector').inputmask(eval(IDR))`
`jQuery('selector').inputmask({'mask':'IDR'})`
`jQuery('selector').inputmask({'alias':'IDR'})`

Appears to be a problem with the following line of code:
`42: dataoptions = JSON.parse("{" + attrOptions + "}")), dataoptions) {`

**Comment by cloudcaptain** [comment]
From the Docs: https://github.com/RobinHerbots/Inputmask

> `Inputmask.extendAliases({
>   'myNum': {
>     alias: "numeric",
>     placeholder: '',
>     allowPlus: false,
>     allowMinus: false
>   }
> });`
> Once defined, you can call the alias by:
> `$(selector).inputmask("myNum");`

However, it is not possible to use `data-inputmask="myNum"` because this will error with JSON.parse().  

> You can also apply an inputmask by using the data-inputmask attribute. In the attribute you specify the options wanted for the inputmask. This gets parsed with $.parseJSON (for the moment), so be sure to use a well-formed json-string without the {}.

I was using both `data-inputmask="myNum"` and `$(selector).inputmask("myNum");`, but the `data-inputmask="myNum"` was getting evaluated before `$(selector).inputmask("myNum");` had a chance to run.  Removed `data-inputmask="myNum"` and the error went away.

**Comment by RobinHerbots** [comment]
@cloudcaptain , 

You should have used data-inputmask-alias="myNum'

**Comment by cloudcaptain** [comment]
Thanks for the tip.  Didn't see that in the docs.  I tried it and it is working great!
