### ISSUE TITLE
Copy and Paste not workin' correctly

### ISSUE THREAD

**Issue by AliveDD** [RobinHerbots/Inputmask#1386]
Safari 9.1.3 / Mac 10.11.6
[video 1](https://www.dropbox.com/s/wgscjryilbqfxce/copypaste.mov?dl=1)
[video 2](https://www.dropbox.com/s/h9t6jec91gftrlo/paste.mov?dl=1)

**Comment by RobinHerbots** [comment]
Remove Phone alias #1981
