### ISSUE TITLE
File generated by rails-assets.org does not include the jquery plugin

### ISSUE THREAD

**Issue by afr1983** [RobinHerbots/Inputmask#1387]
Hi,

I'm using this plugin in a rails project through rails-assets, however only the inputmask.js file is being included, not the jquery.inputmask.bundle.js which contains everything plus the jquery integration.

Is it a matter of bower.json being wrong? I am not certain but I think rails-assets reads bower.json to decide which files to include.

**Comment by RobinHerbots** [comment]
@afr1983 , 

I made some changes to the bower.json.

Can you retry against the current version in Github

**Comment by afr1983** [comment]
Rails-assets.org only processes released (tagged) versions, otherwise I would have to download rails-assets.org and run it locally, which goes beyond my current knowledge. Once you release 3.3.4 I will check it again.
