### ISSUE TITLE
I need prefixed value with 8591824

### ISSUE THREAD

**Issue by JakubKontra** [RobinHerbots/Inputmask#1390]
Hi guys,
i need prefixed value with mask -> 8591824999999999999999999 but everytime i get this 
85_1824__________________

I need:
8591824__________________

How can i get this? 

Thank you so much.

**Comment by RobinHerbots** [comment]
@JakubKontra , 

85\\91824999999999999999999

**Comment by JakubKontra** [comment]
TY!
