### ISSUE TITLE
Input mask can't be applied to input type="number"

### ISSUE THREAD

**Issue by airomero** [RobinHerbots/Inputmask#1395]
No matter what i do, i can´t apply a mask to input type number. Am i doing something wrong or there is some limitation i ignore.

**Comment by sirgallifrey** [comment]
type="number" is not allowed as it is not on this list: https://github.com/RobinHerbots/Inputmask#allowed-html-elements and probabily for a good reason, it's behaviour is somewhat different, see here: https://html.spec.whatwg.org/multipage/forms.html#number-state-(type=number)

That being said, it would be very nice to have type="number" working somehow, as it is the best way to get a numeric keyboard on mobile devices right now. type="tel" is a workaround but it have a different keyboard which is not suitable for many number fields use cases.

**Comment by stueynet** [comment]
@sirgallifrey does type=tel work for you? Doesn't work for me. Can you paste your code here where tel is working? For me it brings up the right keyboard but no mask.

**Comment by stevenbriscoeca** [comment]
@RobinHerbots Any plans to add the type number? Would love to hear your thoughts and concerns on the matter! 

By the way, love the plugin keep up the awesome work!

**Comment by lplohmann** [comment]
@stueynet , it works for me. Here' my code:

`<input type="tel" name="telephone" id="telephone">`

`$('input[name*="telephone"]).inputmask("(99) 9999-9999[9]");`

 I tested it in IE9+, Chrome, iOS Safari and Android Chrome.

**Comment by sirgallifrey** [comment]
@stueynet My masks work well with type="tel", there must be something else going on

**Comment by RobinHerbots** [comment]
Input type = number is not allowed due to https://html.spec.whatwg.org/multipage/forms.html#do-not-apply

@stephenbe , 

In combination with the colormask I could implement a working input type=number.  The colormask can fake the caretposition.  But there are currently no plans to implement it.
