### ISSUE TITLE
Error with regex on 3.3.3

### ISSUE THREAD

**Issue by tiagoporto** [RobinHerbots/Inputmask#1398]
If I use regex on inputmask like this

``` js
$("input").inputmask("Regex", {regex: "[0-9]*"});
```

In the input show the text `Regex`.

**Comment by RobinHerbots** [comment]
@tiagoporto , 

Did you also load the inputmask.regex.extensions.js?

**Comment by tiagoporto** [comment]
Thanks @RobinHerbots now its working.
