### ISSUE TITLE
Error on 3.3.3: Uncaught TypeError: Cannot set property 'generatedInput' of undefined

### ISSUE THREAD

**Issue by khanpn** [RobinHerbots/Inputmask#1399]
I used inputmask with maskpattern "-{0,1}9{0,3},{0,1}9{0,3},{0,1}9{0,3},{0,1}9{0,3},{0,1}9{0,3},{0,1}9{0,3}".
But the input allows character at first position.
The issue happens when I upgraded version from 3.3.1 to 3.3.3.
The issue has not happened on 3.3.1

Error thrown at:
_isValid(maskPos, staticChar, strict), getMaskSet().validPositions[maskPos].generatedInput = !0);

**Comment by RobinHerbots** [comment]
@khanhnp , 

Thx for reporting.  I will have a look.

**Comment by RobinHerbots** [comment]
@khanhnp , 

Should be fixed with the latest version on github
