### ISSUE TITLE
Reset mask position

### ISSUE THREAD

**Issue by rickysullivan** [RobinHerbots/Inputmask#14]
I'm swapping the mask based on the type that it is.

This is read from the 2nd digit, in Australia, 07 would be a landline and all mobiles are 04.

So I'm swapping the masks as it's being typed.

However the mask when applied, moves the caret to the end and you can continue typing.

http://jsfiddle.net/wNCKs/

**Comment by RobinHerbots** [comment]
Hi Ricky, 

I made the change to corectly position the caret after applying a mask.

Can you do the test.

Robin

**Comment by rickysullivan** [comment]
Awesome.

Thanks heaps.

http://jsfiddle.net/DpFen/
