### ISSUE TITLE
Cannot bind click event to read only input field with inputmask

### ISSUE THREAD

**Issue by yngvark** [RobinHerbots/Inputmask#140]
I'm trying to bind a jQuery click event to a read only input field with an inputmask, but it does not work. See code below.

```
<html>
<head>
    <script type="text/javascript" src="jquery-1.8.1.js"></script>
    <script type="text/javascript" src="jquery.inputmask.js"></script>

    <script type="text/javascript">
        $(document).ready(function() {
            $("#fieldReadOnly").inputmask("99/99");

            $("#fieldReadOnly").click(function() {
                alert("CLICKED");
            });

            $("#fieldNormal").click(function() {
                alert("CLICKED");
            });     });
    </script>
</head>

<input id="fieldReadOnly" type="text" value="doesn't work" readonly="readonly" />
<input id="fieldNormal" type="text" value="works" readonly="readonly" />​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​
</html>
```

**Comment by RobinHerbots** [comment]
Hi Yngvar,

the readonly blocks all events, ...

best regards,

Robin

2012/11/27 Yngvar Kristiansen notifications@github.com

**Comment by yngvark** [comment]
Somehow my comments were not pasted in my code, but anyway: The #fieldNormal click event works even though the field is readonly, it's only the field with the input mask that does not work.

**Comment by RobinHerbots** [comment]
That because the inputmask blocks all events in readonly mode, ...

What do you want to accomplish?  Maybe a need to fine tune which events the
plugin blocks in readonly.

best regards,

Robin

2012/11/27 Yngvar Kristiansen notifications@github.com

**Comment by yngvark** [comment]
I see. I am actually trying to make the caret/input cursor\* in a read only input field disappear in IE8 when clicking on it. I know, this is IE8's problem, not yours. Anyway, I can achieve that by calling
    $("#readOnlyInputField").click(function() { this.blur(); });

However, this does not work when I'm using a mask on #readOnlyInputField.

My workaround right now is to disable the mask when making the input field read only, and setting the mask again when enabling the field again, but that's not an optimal solution.

Thanks for quick replies.
- (Not sure about the word, that vertical line that blinks in an input field, indicating that the text field is editable.)

**Comment by RobinHerbots** [comment]
Do you mean when the inputmask is readonly and clicked on it in IE8 the
caret is visible?  Does this only happen i IE8 or also in other browsers?

I will try to fix this or apply your workaround.  Does it olso occurs in
ie9 when set in ie8-mode?

Robin

2012/11/27 Yngvar Kristiansen notifications@github.com

**Comment by yngvark** [comment]
To be exact: When the input field is set to read only, like this:
- input id="readOnlyInputField" type="text" readonly="readonly"

Then, in Chrome when you click on this field, no caret is visible, and this is what I think is correct behavior, because a caret indicates that the input field is editable. However, in IE8, the caret is visible even though the field is read only, and it is a bug/problem with IE8.

(I'm not sure what you mean with 'the inputmask is readonly', I didn't know this was possible.)

To fix it, I use the blur() workaround described in last post. But this blur() workaround doesn't work when I'm using an inputmask on readOnlyInputField, because no click-event can be handled.

I'm not sure the best way to fix this, but one solution in my opinion is to make a inputmasked read only field behave exactly as other read only fields. I.e. make the click event available also in read only mode. However, that's just a suggestion. (To implement the blur-workaround inside of inputmask feels wrong, because then a inputmasked field behaves differently from other read only input fields - but I'm not sure if this is what you were thinking of.)

I'm unfortunately not able to test it in IE9 right now, as I'm on a restricted work machine.

Best regards
Yngvar

**Comment by sompylasar** [comment]
Read-only means a user can read the value and maybe select and copy it. The selection may be controlled with a keyboard, so the current caret position should be visible when the field is focused for a user to know where the selection could start. The described Chrome behavior for readonly fields (haven't tested this myself) misses that use-case.

**Comment by yngvark** [comment]
Yeah, you're right about that - IE8 is actually has the correct behavior. Unfortunately, the Chrome behavior is what I want. To elaborate: My input fields are actually transparent (i.e. invisible), but the value of the input field is shown. I.e. I want my input fields to look and feel just like normal text, and in regular text a caret is never shown. The reason I am doing this is because I want the values of these input fields to be a part of a form submit / HTTP POST request when I'm submitting the form.

This may not be how it should be done, and I would understand that this use case not may be worth a fix in inputmask. However, there may be other use cases for wanting to use events on read only input fields with inputmasks.

**Comment by sompylasar** [comment]
Add `<input type="hidden" />` for your data to be sent and `<div />` or `<span />` to display the values as text. You will have to duplicate the data in the markup but you'll get the exact behavior you want.

**Comment by RobinHerbots** [comment]
Event behavior is now the same as a normal input.
