### ISSUE TITLE
Inputmask dosen't work with decimal double

### ISSUE THREAD

**Issue by epetitmediconecta** [RobinHerbots/Inputmask#1400]
I'm using a jquery libary called inpunt mask, I have a problem with it when I loaded data inside the inputs, for example: 

[![imagen](http://i.stack.imgur.com/git3L.png)](http://i.stack.imgur.com/git3L.png)

In the first image I put the data, I saved the data, when I want to show the data again, in the second image the inputs show me the information like this:

[![enter image description here](http://i.stack.imgur.com/LHoss.png)](http://i.stack.imgur.com/LHoss.png)

If I do inpect in html page the value in the first input shows me 2.2 (`value="2.2"`) but in the box shows me 22.

I want to save the data 2.2 and when I needed show the same (2.2 not 22.0).
## code

Assinging value to the input: 

```
_vista.Temperature = (double)_vista.appointment.Temperature ;
```

When I'm debugin the value of `(double)_vista.appointment.Temperature` is 2.5, also I tried using hardcode, `_vista.Temperature = 2.5;` and is the same, dosen't work.

The controltextbox: 

```
<cc:ControlTextBox runat="server" ID="txtTemperature" ValidationType="Number" AllowDecimal="true" DecimalPlaces="2" MaxLength="6"/>
```

when the browser rendere the input 

```
<input name="ctl00$cphW$ucSoap$ucObjective$txtTemperatura" value="2.5" maxlength="6" id="cphW_ucSoap_ucObjective_txtTemperatura" class="form-control" type="text" onkeypress="return onlyDigits(event, this.value,true,true,true,',','.',2);" size="8">
```

The javascript:

```
$(document).ready(function() {
        separador = ",";     
        $('#cphW_ucSoap_ucObjective_txtTemperatura')
            .inputmask("9{1,3}[" + separador + "9{0,2}]");
});
```

**(the input's value is 2.5 but in box shows me 25)**

**Comment by RobinHerbots** [comment]
@epetitmediconecta , 

The separador is a komma, while your value uses a dot.
