### ISSUE TITLE
Onblur/onchange event problem

### ISSUE THREAD

**Issue by Ost-max** [RobinHerbots/Inputmask#1402]
When I use mask with groups: (\a\b\d\e)|(\a\b\c)|(\e\b\c\s\q) and try to get input field value by jquery

```
$("#im").on('change', function() {
    console.log(" val: " + $("#im").val());
});
```

I get empty value....

Also, it is works for other types of mask.

https://jsfiddle.net/q039op29/

**Comment by RobinHerbots** [comment]
@Ost-max , 

Fixed
