### ISSUE TITLE
Changing input field type from text to password on iPhone

### ISSUE THREAD

**Issue by danielpiterak** [RobinHerbots/Inputmask#1409]
Hi, I have a problem that the inputmask is changing the field to password type in Safari on iPhone. On other devices it's working really great. Below is the code of our installation and screenshot how is it working on iPhone. Here is the website www.dannypstyle.cz/products/kozena-slim-penezenka . Do you know where is the problem pls? Thanks.

`<script src="{{ 'inputmask.min.js'| asset_url }}"></script>
    <script src="{{ 'jquery.inputmask.min.js'| asset_url }}"></script>
    <script>
    $(document).ready(function(){
     $("#monogram").inputmask("(aa)|(a.a.)|(aaa)|(aa.a.)|(a.aa.)",{ showMaskOnHover: false, placeholder: " ", casing: "upper" });
    });
    </script>
    <div><label for="monogram">Monogram</label><input type="text" id="monogram" name="properties[Monogram]" maxlength="5" style="width:100px;"></div>`
- screenshot https://www.dropbox.com/s/78vt6uf8zapn5y8/File%2006-10-2016%2C%2008%2047%2024.png?dl=0

**Comment by RobinHerbots** [comment]
See #1393 

I suggest using a released version as the current version on github is a bit experimental.  There is also a regression in the numerics alias I still need to fix.

**Comment by danielpiterak** [comment]
Cool, it worked. Thanks a lot!
