### ISSUE TITLE
regex for mask

### ISSUE THREAD

**Issue by quasiperfect** [RobinHerbots/Inputmask#141]
how can i use a regex as a mask ?
i need to use this /^([A-Z]{1}[a-z]{3,11}){1}([- ]{0,1}[A-Z]{1}[a-z]{3,11}){0,1}$/

**Comment by RobinHerbots** [comment]
Hi quasiperfect,

That would be a cool feature!!  But it is not possible to just pass the
regex as a mask template.

Explore a bit at the examples in the numeric extensions to get an idea how
you can accomplish it for the moment.

When I see your regex definition, the mask needs tobe dynamic, I mean some
parts are optional.

That is currently very limited.

I am working on optional mask but it is far from finished.

best regards,

Robin

2012/11/27 quasiperfect notifications@github.com

**Comment by RobinHerbots** [comment]
Hi, 

The optional masks are implemented.  Maybe you can try to define your regex as a mask with optional parts.

Anyway I created a new milestone => version 2.3  to create a mask from a regular expression.  I don"t know if I can implement that, but it would be so incredible, if that would be possible, ...

**Comment by RobinHerbots** [comment]
@quasiperfect ,

I will start working on it.

**Comment by RobinHerbots** [comment]
$(selector).inputmask("Regex", { regex: "[0-9]*" });  => working

**Comment by RobinHerbots** [comment]
$(selector).inputmask("Regex", { regex: "[0-9]_[a-z]_" }); => working

I need a regex which can split up a regex in single character matching subregexes.  Any regex guru who wants to take the challenge?  So the above regex splits up in [0-9]\*  and [a-z].*;  this is already working, but now I need the same functionality for more advanced & complex regexes.

**Comment by sompylasar** [comment]
Why reinvent a regular expressions parser? https://github.com/eriksank/alt-regex-engine
There is a [walker](https://github.com/eriksank/alt-regex-engine/blob/master/lib/alt-regex-walker.js) that may be extended or rewritten to check for the input mask. Maybe elaborate towards this one and not build custom solution from the ground up?

**Comment by RobinHerbots** [comment]
@sompylasar, 

Ok,  I will have a look at this one.  Thx!

**Comment by MAAARKIN** [comment]
how i make regex that is not possible start with numbers but i can use numbers, for example:

a123marcos = accept
123marcos = not accept.

it's possible?

**Comment by RobinHerbots** [comment]
@MAAARKIN ,

Try this one $("#testmask").inputmask("Regex", { regex: "[A-Za-z]{1}[A-Za-z0-9]*"});

best regards, 
Robin

**Comment by MAAARKIN** [comment]
hi Robin, i think you should put this in the documentation, cause i only found this through google kkk and not in the documentation, and another thing, where i look this patterns, ...[a-z], {1}, where i find this patterns. ?

i need find pattern to email and i don't make those patterns

**Comment by MAAARKIN** [comment]
I can set the minimum number of characters without those underlines?

**Comment by RobinHerbots** [comment]
@MAAARKIN , 

The regex extension is still experimental.  I will add it in the documentation when I feel it is ready for it.
The usage of the regex extension is currently limited.  An email regex pattern will not parse.  The patterns are just regular expressions

@sompylasar , 

I just stumbled on regexpal which does highlighting of the different regex parts.  I will use that code to implement the parsing for the regex extension.

**Comment by RobinHerbots** [comment]
Yes use the clearIncomplete option

2013/7/26 MAAARKIN notifications@github.com

**Comment by MAAARKIN** [comment]
@RobinHerbots i think that i found one problem with the mask, but i don't know if exist that issue.

I define the mask, for example data-inputmask="'mask': '9999.9999.9999.9999'"

when i put 9999.9999.9999.9999 or any number in sequence works correctly, but if i put the number incomplete, for example 9999.9999.____.9999 and back the cursor for any position and continue put the numbers, when complete mask, he don't understand the "oncomplete".

**Comment by RobinHerbots** [comment]
@MAAARKIN ,

Can you open a new issue for this as this is not related to this issue.

How did you manage to type in 9999.9999.____.9999

**Comment by RobinHerbots** [comment]
first version of regex extension complete  - further enhancement on request
