### ISSUE TITLE
DAY and MONTH pattern issue

### ISSUE THREAD

**Issue by poligit** [RobinHerbots/Inputmask#1410]
Hi Robin,
assuming that the date is **07/10/2016** and I want to change it to **30/03/2017**
I put my cursor on the first digit = **0**7/10/2016 and start typing 3-0-0-3 ... instead of 30th of March the result is **d7.m0.2016** because 37 for a day is not possible and 00 or 30 for a month isn't as well.

https://jsfiddle.net/x3dn5fon/2/

Cheers, 
Gerhard

BTW: Your demo page (http://robinherbots.github.io/Inputmask/) isn't working.  (jquery.inputmask.bundle.js 404)
https://rawgit.com/RobinHerbots/jquery.inputmask/3.x/dist/jquery.inputmask.bundle.js

**Comment by RobinHerbots** [comment]
@poligit , 

Thx for reporting.

I will put some time in the date aliases soon.

**Comment by poligit** [comment]
the fix works! thanks!
