### ISSUE TITLE
androidHack: Caret positioning needs some fine tuning

### ISSUE THREAD

**Issue by RobinHerbots** [RobinHerbots/Inputmask#1412]
@gersteba,

IMaybe you can help with this if you want and have the time?

**Comment by gersteba** [comment]
@RobinHerbots ,

I can help with testing.

**Comment by RobinHerbots** [comment]
@gersteba , 

Can you have a test.  Caret positioning should be correct, only the android caret indicator is still off.  (you will see what I mean)

**Comment by gersteba** [comment]
@RobinHerbots ,

yes, I can confirm this.
Pasting is even not possible.

**Comment by RobinHerbots** [comment]
A non editable div does not allow to paste. I need to put the div behind the input Sa that we can paste data

**Comment by RobinHerbots** [comment]
@gersteba , 

Pasting should be possible now

**Comment by gersteba** [comment]
Hi!

When I keep tapping long on the field to show the context menu, the
placeholders are selected instead of the menu appearing.
So I cannot paste anything.

Am 10.10.2016 23:35 schrieb "Robin Herbots" notifications@github.com:

**Comment by gersteba** [comment]
@RobinHerbots ,

I tried your latest version - and it seems to work now!
Thank you!
