### ISSUE TITLE
Missing dot

### ISSUE THREAD

**Issue by danielpiterak** [RobinHerbots/Inputmask#1414]
Hi, I have this set up:

`$(document).ready(function(){
      $("#monogram").inputmask("(aa)|(a.a.)|(aaa)|(aa.a.)|(a.aa.)",{ showMaskOnHover: false, placeholder: " ", casing: "upper" });
    });`

Once the user use it here https://goo.gl/Zu9sz2 and writes "D.P" mask automatically shows the second dot. But once the input is not active it's without the dot. Am I doing something wrong? It should be with both dots or without any.

Second problem is how can I add Czech characters like "ščřžýý"? Thanks a lot for your help.

**Comment by RobinHerbots** [comment]
@danielpiterak , 

I will have a look at the first.  

For the second you need to extend the regex definition in the a definition. You may send a PR for it.

**Comment by RobinHerbots** [comment]
@danielpiterak , 

A quick fix is to just add the clearMaskOnLostFocus: false option.
This disables the clearOptionalTail function, which causes the removal of the dot.
