### ISSUE TITLE
jquery.val returns empty value

### ISSUE THREAD

**Issue by urielasecas** [RobinHerbots/Inputmask#1415]
Chrome's version is 53.0.2785.143

When I call input.val() in firefox I get the value, but that doesn't well in Chrome. I tried the 'hack' of disable > get the value > and enable the mask, but that didn't seemed to work, either.

The mask is a date one: 
`$('#birthday').inputmask('dd/mm/yyyy',{ "placeholder": "dd/mm/aaaa" });`

**Comment by RobinHerbots** [comment]
@urielasecas , 

Can you create a jsfiddle for it

**Comment by urielasecas** [comment]
Thanks, Robin. You can see it here: http://empleofacil.mx/completar-registro.php

Put a brakepoint in file validate.js line 283. The focus on date field, fill it and blur. That function is called and gets an empty value in chrome, but not in firefox.

Have a nice day.

**Comment by RobinHerbots** [comment]
@urielasecas , 

This is because the rgen extends on the valhook without taking other valhooks into account.

This is not a problem when your browsers support patching the native value property.  It seems that Chrome is using the valhook fallback.  I will see why the native value patch doesn't work on chrome anymore.

But for your problem, try by loading the rgen script first (before the inputmask)  The inputmask respects other valhooks.

**Comment by RobinHerbots** [comment]
I tried the valuepatching with CHrome 53.0.2785.143 and that seems to work as expected.

Just looked a bit deeper, ... the value is called, but the inputmask does not contain data.  I guess the datepicker prevents some events, so the inputmask is anaware of the input changes.

**Comment by urielasecas** [comment]
Thanks for your time, Robin. So, this will be fixed in the next version? How is that valuepatching that worked for you in order to implement it meanwhile?

**Comment by RobinHerbots** [comment]
@urielasecas , 

Euh I don't know if this will be fixed for the next release.  The valuepatching was my first guess as you said it worked in firefox.  But after looking into it, the valuepatching has nothing todo with it.

It is more a problem with the datepicker blocking events.  Creating a jsfiddle with the datepicker and the inputmask would help in investigating.

**Comment by urielasecas** [comment]
Thankyou, Robbin. Here is a simplified example on jsfiddle that works in firefox but not in Chrome 53.0.2785.143:
https://jsfiddle.net/3xa3ztkn/2/

**Comment by MehdiSaeedifar** [comment]
I have the same problem just in chrome.

**Comment by RobinHerbots** [comment]
@urielasecas , @MehdiSaeedifar , 

The jsfiddle showed me the problem.  type="date"

Which is supported on chrome and not on ff (ff uses fallback => text)
The inputmask does not mask when the native type=date implementaion is used, but was patching the value anyway which causes the empty value.
