### ISSUE TITLE
Decimal mask excluding zero with custom RadixPoint and GroupSeparator

### ISSUE THREAD

**Issue by kamihouse** [RobinHerbots/Inputmask#1418]
Hi guys.
I believe I have found a bug.

I am in Brazil, and our currency standard follows the sample schema: **R$ 1.000,00**.
I'm doing the following customization rules for apply a money mask:

```
<script>
    $(function() {
        $("#money").inputmask('decimal', {
            'alias': 'decimal',
            'radixPoint': ','
            'groupSeparator': '.'
            'autoGroup': true,
            'digits': 2,
            'digitsOptional': false,
            'rightAlign': false
            'placeholder': '0'
    });
</script>
```

When I applying the mask on complex values, such as **1.000,01**, get the expected result:
![exemplogh1](https://cloud.githubusercontent.com/assets/892340/19365347/b45e3724-9168-11e6-9468-c840e00d1667.gif)

---

But when I use rounded numerical values, such as **1.000**, **2.000**, **99.000**, the mask is disregarding the trailing zeros:
![exemplogh2](https://cloud.githubusercontent.com/assets/892340/19365359/c7ed252a-9168-11e6-9c2b-85c48966d870.gif)

There is another way to customize the mask for my area?
What can I do to consider the right zeros on this case? Thank you!

**Comment by RobinHerbots** [comment]
@kamihouse , 

I will have a look

**Comment by kamihouse** [comment]
@RobinHerbots, the problem persists on **version: 3.3.4-53** with informed values, not on type it.

You can reproduce it in this [Fiddle](https://jsfiddle.net/kamihouse/vkc3qo38/).

**Comment by RobinHerbots** [comment]
@kamihouse ,

I will really have a look now ;-)

**Comment by kamihouse** [comment]
@RobinHerbots, if I use `onBeforeMask` and return the value, everything is ok.
I hope this can help.

```
$('.moedaReal').inputmask('decimal', {
      radixPoint:",",
      groupSeparator: ".",
      autoGroup: true,
      digits: 2,
      digitsOptional: false,
      placeholder: '0',
      rightAlign: false,
      onBeforeMask: function (value, opts) {
        return value;
      }
});
```
