### ISSUE TITLE
Syntax for setting casing: "title" for all input fields

### ISSUE THREAD

**Issue by billkron** [RobinHerbots/Inputmask#1419]
How can I set casing: "title" for all input fields on a form?

I've got this:

$(document).ready(function () {
            $("#formName input[type=text]").inputmask({ casing: "title" });
        });

but I know the syntax isn't correct.

Any help would be appreciated.

Thank you!

**Comment by RobinHerbots** [comment]
Try with

Inputmask.extendDefaults({ casing: 'title' });

Op vr 14 okt. 2016 om 01:01 schreef billkron notifications@github.com:

**Comment by billkron** [comment]
Where would I put this line of code?

I tried it in the script tags at the bottom of the form, as well as inside the jquery document.ready() function, but it does not change the casing.

Thank you for your assistance--I appreciate it.

**Comment by billkron** [comment]
In the meantime, I added JavaScript function that accomplishes this. However, there is an undesirable side-effect of, when you try to highlight existing text in the field, the cursor is moved to the end of the text string. So, for example, if you want to highlight the entire contents of the field to delete its content, you can't.

I am very interested in trying to leverage your casing feature instead, though. So, if you still have a chance to respond about where this line of code should go in order to make it work as expected, I would greatly appreciate it. 

Thanks again for taking the time to respond!

**Comment by RobinHerbots** [comment]
@billkron , 

The line should be executed before you apply the masks.

Anyway which version of the inputmask do you use?

**Comment by billkron** [comment]
I'm using version 3.0 of inputmask. As far as where it should be placed, here is an example of what I tried (this was placed at the bottom of my form):

```
    <script>
        Inputmask.extendDefaults({ casing: 'title' }); // tried it here
        $(document).ready(function () {
            Inputmask.extendDefaults({ casing: 'title' }); // also tried it here
            $("#DateOfBirth").datepicker({
                dateFormat: 'mm/dd/yy',
                changeMonth: true,
                changeYear: true,
            }).inputmask("mm/dd/yyyy", { "placeholder": "mm/dd/yyyy" });
            $('#Zip').inputmask("99999[-9999]", { greedy: false, 'removeMaskOnSubmit': true });
            $("#HomePhone").inputmask("mask", { "mask": "(999) 999-9999", 'removeMaskOnSubmit': true });
            $("#WorkPhone").inputmask("mask", { "mask": "(999) 999-9999", 'removeMaskOnSubmit': true });
            $("#CellPhone").inputmask("mask", { "mask": "(999) 999-9999", 'removeMaskOnSubmit': true });
            $("#Email").inputmask("email");
        });
    </script>
```

**Comment by RobinHerbots** [comment]
You need at least version 3.3.2

**Comment by billkron** [comment]
Actually, I have version 3.3.2-91 installed (sorry for providing the wrong information).

**Comment by RobinHerbots** [comment]
@billkron , 

The only mask where the casing title would make a difference is the email mask.  As upcasing a number doesn't change it ;-)

I tried it locally and it works as expected.
Both positions where you inserted the default should work.

Can you make a jsfiddle which shows the problem?

**Comment by billkron** [comment]
I totally understand that with the fields I've referenced in the inputmask, only one of them would be affected by the casing default, but I'm clearly missing something else here. :-)

It sounds like you're saying that the casing default will only apply to the fields that I have specifically referenced in the inputmask. Is that correct? I was originally looking for this to be a catchall for any form field that accepts text input without having to directly reference specific fields. I have several other fields (e.g., FirstName, LastName, AddressLine1, etc.).

Is it your assertion that the casing defaults would apply to all form fields whether they are referenced in the inputmask or not? If so, then I will certainly do a jsfiddle, so you can see what I'm seeing.

Thank you for being so patient with me on this.

**Comment by RobinHerbots** [comment]
The casing is only applied for masked inputs.

Op di 18 okt. 2016 om 04:21 schreef billkron notifications@github.com:

**Comment by billkron** [comment]
That makes much more sense then. Thank you so much for your patience. And thank you for inputmask--it's fantastic!
