### ISSUE TITLE
colorMask - incorrect positioning

### ISSUE THREAD

**Issue by satodavan** [RobinHerbots/Inputmask#1421]
Generated div visually appears at the top of page, not under input — [jsfiddle](https://jsfiddle.net/satodavan/x82sjn49/) (see telephone field)

Also, generated div class is needed for further customization.

**Comment by madhurjya** [comment]
any update on it

**Comment by xavez** [comment]
I have the same problem with this otherwise excellent plugin. I suspect it has something to do with HTML order, unfortunately, I cannot seem to find the HTML in the DOM tree of my inspector to find out what is going on :-).

**Comment by RobinHerbots** [comment]
@satodavan , @madhurjya , @xavez , 

In the 4.x branch the colorMask is updated.  The positioning is more customizable through css and prototype fn.  See readme and have a try

**Comment by RobinHerbots** [comment]
@satodavan , @madhurjya , @xavez ,

Have a look at the updated jsfiddle using the 4.x branch..  You just need to add the padding in the css to make it 100%

https://jsfiddle.net/x82sjn49/34/

The colormask changes will be merged into 3.x branch also
