### ISSUE TITLE
TypeError: el.inputmask is undefined

### ISSUE THREAD

**Issue by MaciejOrman** [RobinHerbots/Inputmask#1424]
Hi,
I'm getting following Exception in JS Console in Firefox:

> TypeError: el.inputmask is undefined: 1089:114 

and in Chrome:

> TypeError: Cannot read property '_valueGet' of undefined: 1089

I'm using jquery.inputmask.bundle.js

Can you please fix this?

**Comment by RobinHerbots** [comment]
@MaciejOrman , 

Which version do you use?

**Comment by MaciejOrman** [comment]
The newest - 3.2.3-9

19.10.2016 18:03 "Robin Herbots" notifications@github.com napisał(a):

**Comment by RobinHerbots** [comment]
Which Mask do you use? Can you create a jsfiddle

**Comment by RobinHerbots** [comment]
@MaciejOrman , 

Can you retry with the current version on github

**Comment by MaciejOrman** [comment]
With Version 3.3.4-53 of jquery.inputmask.bundle.js I'm becoming the Exception not any more. Thanks Robert :)
