### ISSUE TITLE
Static text without showing the placholder

### ISSUE THREAD

**Issue by umartopia** [RobinHerbots/Inputmask#1425]
Can we apply the mask in a way that, we can specify the placeholder without actually displaying it to the user.
What I want is something like this:
xx/yy/zzzz
user should only types in xxsyyzzzz and the input should automatically add slashes in between while the user is typing in text.
I can currently achieve the same using placeholder, but in that case, the entire placeholder text is visible to user

**Comment by RobinHerbots** [comment]
@umartopia , 

I guess you mean the jitMasking : true option

**Comment by umartopia** [comment]
@RobinHerbots yes that's what I was looking for. Thanks a ton. BTW you have created a superb plugin :)
