### ISSUE TITLE
How to unmask to get val()?

### ISSUE THREAD

**Issue by devgiu** [RobinHerbots/Inputmask#1426]
I'm searching and I can't find the way to do this.
I'm using inputmask to "format" some values as currency this way:

```
Inputmask.extendAliases({
    euro: {
                        suffix: " €",
                        decimal: '.',
                        groupSeparator: ",",
                        alias: "numeric",
                        placeholder: "0",
                        autoGroup: !0,
                        digits: 2,
                        digitsOptional: !1,
                        clearMaskOnLostFocus: !1
                }
            });
```

My problem comes when I try to get the value from an input, because $('myfield').val() returns me the value masked, and maths operations returns me a NaN.

15.25 €

I need to do some calcs on "change" events of different inputs, and I would like to know if there are some way to get the unmasked value, to do this calcs.

Regards.

**Comment by RobinHerbots** [comment]
@devgiu ,

Use the autoUnmask and unmaskAsNumber options
