### ISSUE TITLE
Tab to switch input fields => positionCaretOnTab strange behavior

### ISSUE THREAD

**Issue by kheyse-autodesk** [RobinHerbots/Inputmask#1427]
When tabbing between input fields, the expected behaviour is that the content of the field in focus is completely selected.
When an inputmask (numeric) filter is applied, this is no longer the case and the caret is (often) put at the end of the field instead. Moreover, the behaviour sometimes changes after reloading the page.

The expected and faulty behaviour can be seen here: http://jsfiddle.net/brmncc6v/1/

**Comment by RobinHerbots** [comment]
Set thé positionCaretOnTab option to false. See readme.

**Comment by kheyse-autodesk** [comment]
Great! Thanks for the very quick response. (The behaviour with the flag on still seems to be a bit unstable)

**Comment by RobinHerbots** [comment]
@kheyse-autodesk , 

Updated your fiddle http://jsfiddle.net/brmncc6v/2/

Strange, the first field seems not todo the selection.

**Comment by RobinHerbots** [comment]
@kheyse-autodesk , 

Have a new try

**Comment by kheyse-autodesk** [comment]
You mean the jsfiddle? I haven't noticed a difference.

**Comment by kheyse-autodesk** [comment]
Yes! I did not find what changed in the jsfiddle, but when I copied the inputmask.bundle.js file into my project, I found that the positionCaretOnTab=false is more stable. 
It would be great if this fix could make it into the npm package.
