### ISSUE TITLE
Disable definitions '9' or..?

### ISSUE THREAD

**Issue by barskuk** [RobinHerbots/Inputmask#1429]
Hello,
I need to make a mask for Kyrgyzstan phone like this +996 (XXX) XX-XX-XX.
How can I make it with inputmask? Thank you!

**Comment by RobinHerbots** [comment]
Inputmask("+\9\96 (999) 99-99-99").mask(selector);

Op di 25 okt. 2016 om 22:00 schreef barskuk notifications@github.com:

**Comment by barskuk** [comment]
Thank you!
