### ISSUE TITLE
Time

### ISSUE THREAD

**Issue by theblang** [RobinHerbots/Inputmask#143]
It would be great to be able to use both date and time simultaneously as well as do am/pm.  Also, some examples for time would be really helpful.

**Comment by RobinHerbots** [comment]
Hi Mattblang,

try

$(input).inputmask("datetime");

You can find the implementation in the date.extensions.

best regards,

Robin

2012/12/18 mattblang notifications@github.com

**Comment by theblang** [comment]
Very nice!   Is there a way to do am/pm?  I didn't notice anything in date.extensions but I saw something in custom.extension.

**Comment by RobinHerbots** [comment]
Yes in the custom.extensions you can find AM/PM.  This extensions is not
written by me and should be merged in the date extensions, but I haven't
got the time to do it yet.

best regards,

Robin

2012/12/18 mattblang notifications@github.com

**Comment by theblang** [comment]
I see what I was doing wrong.  I built using the Ant XML and just realized that the custom.extensions aren't included.  After including them the am/pm worked.  Unfortunately, it doesn't seem to work when combined with date (e.g., "m/d/y h:s t").

**Comment by RobinHerbots** [comment]
That is possible because I took the custom extension as is.  Propably is
the t definition not know outside the alias.  When I find the time I will
look at it.  Or if you are willing to look at it, always welcome.

Anyway, I leave the issue open until solved.

best regards,

Robin

2012/12/20 mattblang notifications@github.com

**Comment by RobinHerbots** [comment]
Hi mattblang, 

There is a new alias datetime12 which should solve your issue ;-)

best regards, 

Robin
