### ISSUE TITLE
Regex Issue - Optional Space

### ISSUE THREAD

**Issue by SimonJulian** [RobinHerbots/Inputmask#1431]
Hi,

I'm trying to use the below regex for input validation, only the optional space doesn't seem to be allowed, the rest of the regex (both sides of the optional space) work as expected.

`[a-zA-Z]{1,2}[0-9][0-9a-zA-Z]?\s?[0-9][a-zA-Z]{2}`

I've tested the regex through a tester, and it works as expected, see : [https://regex101.com/r/sTqlNn/1](https://regex101.com/r/sTqlNn/1) , which also has some dummy data.

And here's in in a fiddle, as an example [https://jsfiddle.net/kkxfbd9m/](https://jsfiddle.net/kkxfbd9m/)

Any Ideas ?

Thanks,

**Comment by RobinHerbots** [comment]
@SimonJulian , 

try by escaping the \

[a-zA-Z]{1,2}[0-9][0-9a-zA-Z]?\s?[0-9][a-zA-Z]{2}

**Comment by SimonJulian** [comment]
Ah,

Really should have caught that myself, works 100% as expected now.

Thanks very much.
