### ISSUE TITLE
TypeError: Cannot create property 'pos' on boolean 'false'(…)

### ISSUE THREAD

**Issue by asolopovas** [RobinHerbots/Inputmask#1432]
Hi I am trying to use inputmask with webpack and vue. The problem I am faced with is that if I require it from entry module, it throws an error in console:

TypeError: Cannot create property 'pos' on boolean 'false'(…)

I have jQuery included globally in webpack.

This is my code----------------------
```
require('../libs/jquery.inputmask.bundle.min');
Vue.directive('mask', {
    bind: function (el, binding) {
        
        $(el).inputmask("999-99999999");
    },
});
```

**Comment by asolopovas** [comment]
https://gist.github.com/ksrb/47f9124c2f5be13f39dc645405a12608

**Comment by OlehDutchenko** [comment]
@asolopovas 
a fix that helped me
in inputmask/inputmask.js
on line 472 - replace part `void 0 === result.pos && (...` to  `void 0 === (typeof result == 'object' && result.pos) && (...`

```js
// line 472
result === !0 && (result = {
                pos: maskPos
            }), $.isFunction(opts.postValidation) && result !== !1 && !strict && fromSetValid !== !0 && (result = !!opts.postValidation(getBuffer(!0), result, opts) && result),
            void 0 === (typeof result == 'object' && result.pos) && (result.pos = maskPos), result === !1 && (resetMaskSet(!0),
            getMaskSet().validPositions = $.extend(!0, {}, positionsClone)), result;
```
