### ISSUE TITLE
Question: Versions of JQuery that will work?

### ISSUE THREAD

**Issue by Vaccano** [RobinHerbots/Inputmask#1433]
The readme does not list what versions of JQuery this will work with.

I have found myself locked into a really old version of JQuery (Version 1.8.3 from 2012).

Do you think the input mask will have problems with that old of a version?

**Comment by RobinHerbots** [comment]
@Vaccano , 

You need at least version 1.7

**Comment by Vaccano** [comment]
Sweet!  Thanks!
