### ISSUE TITLE
Is there a way to get raw data masked?

### ISSUE THREAD

**Issue by asolopovas** [RobinHerbots/Inputmask#1434]
Hi I was wondering is there a way to input raw data into masker and return masked version of it as well raw? Without using selector. Its required for vue.js input field masking because when I apply your masker directly onto the input field it kills reactivity.

**Comment by kailniris** [comment]
You have to wrap a directive around it.

```
<input type="text" v-model="myData" v-input-mask:mask="'9999 99 99'">

Vue.directive('input-mask', {
  bind: (el, binding) => {
    $(el).inputmask({
      mask: binding.value,
      oncomplete: () => {
        var e = new Event('input', { bubbles: true });

        el.dispatchEvent(e);
      }
    });
 }
});
```

**Comment by RobinHerbots** [comment]
@asolopovas , 

When you use the vanilla dependencylib, native events will be fired.

**Comment by asolopovas** [comment]
Great  I already figured it out your plugin works great. Thank you.
