### ISSUE TITLE
Possible to have a suffix for non-numeric input field?

### ISSUE THREAD

**Issue by bbonte** [RobinHerbots/Inputmask#1441]
Is it possible to set a prefix or suffix in the input field without using the 'numeric' alias? I would like to have the possibility to display a suffix for a 'normal' textual input field. At the moment it seems like the suffix option is only working when I also use the 'numeric' alias, limiting the user to typing numbers.

Thanks!

**Comment by RobinHerbots** [comment]
@bbonte , 

You can just add it to the mask.

Inputmask("prefix aaa-aaa suffix").mask("input")

**Comment by bbonte** [comment]
@RobinHerbots ,

Thanks, but in my case I don't have a mask, I only use the plugin for restricting input to numbers and to have the suffix inside of my input field. Do you also have a solution for this case? I included an example of how I use the plugin below. It works for numbers, but not for normal text (when it's not the numeric alias).

```
<input data-inputmask-alias="${(type == 'number') ? 'numeric' : ''}"
           data-inputmask-suffix=" ${unit}"/>
```

**Comment by RobinHerbots** [comment]
@bbonte 

The normal text should also be a mask if you want to force the prefix

something like "prefix _{_}"

**Comment by bbonte** [comment]
@RobinHerbots 

Ok, and is it possible to set a mask via the `data-inputmask-mask` attribute that would actually accept any String value and with no limit on the length?

**Comment by RobinHerbots** [comment]
@bbonte , 

```
 data-inputmask-mask="prefix *{*}"
```

**Comment by RobinHerbots** [comment]
@bbonte , 

```
<input data-inputmask-alias="${(type == 'number') ? 'numeric' : '${unit} *{*}'}"
           data-inputmask-suffix=" ${unit}"/>
```
