### ISSUE TITLE
Form not cleaning correctly when AutoUnmask option is set to true

### ISSUE THREAD

**Issue by juliocgs** [RobinHerbots/Inputmask#1442]
Hi, I'm having a problem with the mentioned option. I have a condicional form reset  so I must do it via JS .reset() method after checking a few things.

The problem is after the form is resetted, visually the values of field are empty but if you try to retrieve their value via JS, you will get the value they had before they were cleaned.

I've prepared a fiddle;
https://jsfiddle.net/juliuscgs/cc8bj6ys/1/

To simulate the error: Just fill something in the field and use the 'Clean' button. The event of button will reset the form and afterwards show an alert with the value of the field. It should show you a empty alert but you get an alert with the value you filled even though the field is empty. If you remove the autoUnmask option everything will work as it should.

Please, can I at least get a work around for this?

**Comment by RobinHerbots** [comment]
@juliuscgs,

https://jsfiddle.net/cc8bj6ys/4/

**Comment by juliocgs** [comment]
That does work, another way to achieve the desired result is to manually set the default value of the fields.
Either way, they are both a work around  as the issue still needs to be fixed with the autoUnmasked option, so I will keep this one open.

Thanks.

**Comment by RobinHerbots** [comment]
@juliuscgs , 

I will see if it can be fixed without the workarounds.

**Comment by juliocgs** [comment]
Thanks.

**Comment by KingGeneral** [comment]
this one try it https://jsfiddle.net/cc8bj6ys/5/

i think the mask is not bugged, but mistaken the form. 

@juliuscgs  @RobinHerbots

**Comment by RobinHerbots** [comment]
@KingGeneral , 

This is exactly what @juliuscgs said above.  This works but is a workaround for the form reset.

**Comment by juliocgs** [comment]
@KingGeneral , what you did is what I said:
>another way to achieve the desired result is to manually set the default value of the fields.

Anyway, I really appreciate the help

**Comment by RobinHerbots** [comment]
@juliuscgs , @KingGeneral, 

I made a cleaner fix for this.  Can you give it a try.

**Comment by juliocgs** [comment]
Sorry for being so late.
The issue is now fixed.

 Thanks @RobinHerbots
