### ISSUE TITLE
Colormask functionality

### ISSUE THREAD

**Issue by ghost** [RobinHerbots/Inputmask#1446]
Hi, Robyn!
Thanks for the great library, I've started to use it in the project recently.
I've seen the new feature Colormask is being developed, starting from the issue [972](https://github.com/RobinHerbots/Inputmask/issues/972).
Be the coincidence, I am also working on the changes, related to the color of the masks of the inputs.
So I wanted to ask, can these improvements be built on top of the inputmask functionality:
1. The option to make color of the mask not to be static, but change color of the mask and the value allogether, so there would be different colors before and after last valid position (including prefixes), like in this example
![1](https://cloud.githubusercontent.com/assets/23399170/20478007/25f6180c-affa-11e6-9eb1-b8eb342fa4f4.png).
or that example
![2](https://cloud.githubusercontent.com/assets/23399170/20478235/063d4bec-affb-11e6-9da2-e6b0370ca74b.png).
This option may be an alternative to colormask option, or maybe colormask option can be changed not to be a bool type. but type of the mask to be provided one way or another.
2. When the value for the input with the currency type is set the color of the decimal part of the mask is not set to the default color of value, which looks strange:
![4](https://cloud.githubusercontent.com/assets/23399170/20478683/e8d5359a-affc-11e6-9af3-e766d75843c6.png)
3. The possibility to provide class or color for the different parts of the mask, the value part and the mask (static part).
Also, identifier or class may be required for the wrapper div, so that it also could be found or to apply the styles to it.

**Comment by RobinHerbots** [comment]
@OzzyKh , 

The current implementation is very basic and is mainly added to support android via the androidhack. 
You are welcome to add and enhance the colormask functionality.  I guess adding extra classes for the different part of the mask will be sufficient to archieve to above mentioned items.

For item 2: This is because you did not entered the .00

Currently there are already 2 classes  im-static and im-caret

**Comment by ghost** [comment]
1. Ok, I'll look into this and see if the changes for the functionality enhancement can be made and no other issues would occur.
2. But you see, the value 110.00 is the valid value, it can be considered as complete value, even if I am not entering decimal part directly.
3. Maybe also class for the wrapper div then? So, we could, for example, add border if the value is not valid.

**Comment by RobinHerbots** [comment]
@OzzyKh , 

Great!
Yes, we can check if the value is complete and consider them as entered.  An extra class on the div can also be usefull.

It would also be nice if the colormask is an optional extension.  Maybe keep that in mind.  I will look into that also.  #1447

**Comment by ghost** [comment]
Ok, then. Thank you.

**Comment by RobinHerbots** [comment]
@ghost, 

Any update yet?

**Comment by RobinHerbots** [comment]
@ghost,

I updated the colormask.  The most styling part is now in the inputmask.css.  This should makes thing easier
