### ISSUE TITLE
Cannot write anything in input

### ISSUE THREAD

**Issue by andrey-prokhorov** [RobinHerbots/Inputmask#1448]
I am trying to use an example from documentation:

`<input type="text" id="date" />`

```
$(document).ready(function(){
  $("#date").inputmask("d/m/y",{ "placeholder": "dd/mm/yyyy" });
});
```

This code is not working with the latest version of inputmask (3.3.4-101), but working with old one (3.3.4-92), check also this example in plunker: http://plnkr.co/edit/imD8pkfbIjbqqqFWs3EF?p=preview

**Comment by RobinHerbots** [comment]
@andreyezy , 

WHen you look at the changelog you can read that I removed the definitions for d, m, y and others, as people expected that they provide full validation for dates etc.  So I left only the date aliases which provide the functionality.  I will replace the example from the readme.

Thx for reporting

**Comment by andrey-prokhorov** [comment]
Hi @RobinHerbots, thank you for your answer!

Yes, please add an example that shows how to specify date format like `dd-mm-yyyy` or `mm-dd-yyyy` in the latest version 👍 

Another question: you do have certain validation of dates in old versions (for ex. `3.3.4-92`), so that user cannot write month "13" or year "3000". But user can write date 31.02.2016 although it cannot be more that 29th of February.
Is that what you mean by "full validation for dates"?

**Comment by RobinHerbots** [comment]
@andreyezy , 

An example is already in the https://github.com/RobinHerbots/Inputmask#date--datetime-extensions
