### ISSUE TITLE
Error on serialize() if autoUnmask=true

### ISSUE THREAD

**Issue by billmn** [RobinHerbots/Inputmask#1449]
Hi guys,
I notice that using <code>$('#form').serialize()</code> with <code>"autoUmask": true</code> throw an error like:

<pre>"Uncaught TypeError: val.replace is not a function"</pre>

You can find an example here: http://jsfiddle.net/t37m0txu/142/

**Comment by RobinHerbots** [comment]
@billmn , 

It is due the unmaskAsNumber: true option.  jquery does not expect the value returned to be a number and fails on it.

unmaskasnumber does not follow the "rules" for a input type="text"

**Comment by billmn** [comment]
@RobinHerbots Ooook! Thank you for the explanation 👍

**Comment by sdbezerra** [comment]
Thanks For Help!
