### ISSUE TITLE
inputmask("remove") leaves max length restriction on field

### ISSUE THREAD

**Issue by rusifald** [RobinHerbots/Inputmask#145]
I am changing the text fields input mask depending on the value of a drop down box using this code:

switch ($("select[id$='ddlQuestion2']").val()) {
                case "2":
                    $("input[id$='txtQuestion2Answer']").inputmask({ "mask": "(999) 999-9999" });
                    break;
                case "3":
                    $("input[id$='txtQuestion2Answer']").inputmask("mm/dd/yyyy");
                    break;
                default:
                    $("input[id$='txtQuestion2Answer']").inputmask("remove");
                    break;
            }

It seemed like it was working just fine, but recently I started using a longer value for a non masked option.  If I add the phone/date mask and then remove it the field gets limited to 28 characters.  The Textbox itself is an asp.net textbox but doesn't have any kind of input length restrictions.  I'm not sure why the limit is being imposed.  Has anybody experienced this or know what I could do to completely remove any restrictions on the text box?

**Comment by RobinHerbots** [comment]
Hi Rusifald,

Can you retry with the latest version in the dev branch

best regards,

Robin

2012/12/20 rusifald notifications@github.com

**Comment by rusifald** [comment]
Sure I will report back.

**Comment by rusifald** [comment]
Based on a quick test the problem is resolved.  Thank you for fixing that so fast!
