### ISSUE TITLE
The behavior of allowPlus with a numeric mask has changed.

### ISSUE THREAD

**Issue by maubin-kl** [RobinHerbots/Inputmask#1451]
We updated from version 3.2.3 to 3.3.3.

Previously with a numeric mask and "allowPlus: true" if a user typed: +1234 and switched focus the + sign would stay visible and retrieving the value of the mask would also return with the + sign. 
If a user type: -1234 and switch focus the minus sign stays visible and is returned when retrieving the value.

Since 3.3.3 when a user type: +1234 and switch focus, the + sign disappear and is no longer returned when retrieving the mask value. The behaviour for minus sign is still identical to the older version.

I'm not sure if this is a bug or a desired behaviour change. 
If the behaviour is desired I believe that the allowPlus option has no meaning anymore.

I attached a jsfiddle to test it:

http://jsfiddle.net/3mdts3oe/

**Comment by RobinHerbots** [comment]
@maubin-kl , 

The allow-plus option is removed.  + Do you have a need for the option?
