### ISSUE TITLE
How to allow a specific range of numbers?

### ISSUE THREAD

**Issue by Whip** [RobinHerbots/Inputmask#1452]
I'm trying to understand the regex language used by the plugin but can't get the results I want. I have a text field for the user to fill out time in the format 04:00 or 06:00 etc. So I want to allow only numbers 00 through 12 before the colon and 00 after the colon.

Here's what I've got so far 
`$('#start-time').inputmask("(0|1)[0-9]:00");`
and the results are
`0-_0-_:00`

I'm totally stuck at this. I've tried dozens of variations. What is the correct way to do it?

**Comment by RobinHerbots** [comment]
@VeeK727 , 

The mask isn't regex.  The [] symbolize optional parts.  The 9 is a definition for numbers.  All the others are considered literals as there is no definition defined.

First, I see you discovered a bug  as (0|1)[à-9] should result in _0- as template and not _0-_0-_

Anyway for your case.  Look at the date extensions  Even when the user type in 24 hour format you will get it in 12 hour format.

```
Inputmask("hh:mm", { hourFormat: "12"}).mask(input)
```

**Comment by Whip** [comment]
I'm glad I accidentally improved the plugin, lol.

Thanks for your solution.
