### ISSUE TITLE
Per-element radixPoint overwrites defaults

### ISSUE THREAD

**Issue by Vasiliskov** [RobinHerbots/Inputmask#1454]
I've noted that if I have few numeric inputs with `data-inputmask` field and one of them has `radixPoint` set, all the others behave unexpectedly like if the default value gets screwed up. Take a look at the [jsFiddle](https://jsfiddle.net/vbekLtm6/1/) for an example.

**Comment by Vasiliskov** [comment]
Hello. Any news on fixing this? Or anything I can help with to get it fixed faster?

**Comment by RobinHerbots** [comment]
Hi @Vasiliskov,

Sorry that I didn't pay much attention to this serious issue.  I will investigate.

Does this also occur when applying the masks without  attributes?

**Comment by Vasiliskov** [comment]
Seems to mostly work with less attributes: https://jsfiddle.net/vbekLtm6/6/. 

The only issue I found for this one: if I use `.` or `,` as radixPoint, I can put it with numpad `.` key for both cases, but if I use space as a radixPoint, I need to actually use space key. Would be more convenient if I could put any radixPoint with numpad `.` key.

**Comment by RobinHerbots** [comment]
@Vasiliskov , 

I figured that it also occurs when setting the options via js and not with attributes.  
A good idea for the numpad dot key.  I will add that.

**Comment by Vasiliskov** [comment]
I didn't have a chance to dig deeper, I'm still quite bad in following asynchronous code. :) But it feels like there are two different storages for radixPoint value. And they are messed up under some conditions. Placeholder seems to be stored more consistently.

**Comment by RobinHerbots** [comment]
I found the problem. 
In the numeric extensions I have a definition : for the radixposition.  The placeholder is filled dynamically  with the radixpoint symbol.  But the mask caching can not distinguish between the masks.  So you get the placeholders from the first mask, while the others settings are as expected.  

I still need to think about a fix, but the numpad feature you said is already in place.

**Comment by RobinHerbots** [comment]
@Vasiliskov , 

Fixed
