### ISSUE TITLE
Strange behaviour when groupSeparator and prefix works together and try to delete any decimal.

### ISSUE THREAD

**Issue by arturoSoto** [RobinHerbots/Inputmask#1458]
Hello!
Thank you so much for this plugin.

I've defined an 'euro' currency mask and it works very well except when i try to delete any decimal, a point is removed.
E.g.
If I type '1001.22', it is automatically converted to '1.001,22 €'.
If I try to delete last decimal, it is converted to '1.00122 €'.

I create a [jsfiddle](https://jsfiddle.net/sotosamper1234/7vddjcwu/) that show this behaviour.
Look at 'Custom euro currency mask (complex)' input.

Thanks a lot.
Arturo

**Comment by RobinHerbots** [comment]
@arturoSoto , 

Can you retry with the latest.
https://jsfiddle.net/7vddjcwu/33/
