### ISSUE TITLE
Some Phone masks seem to be wrong (luxembourg)

### ISSUE THREAD

**Issue by DonDiegoAA** [RobinHerbots/Inputmask#1461]
Obviously I do not test every country, but for Luxembourg, for example, the mask seems erroneous.
After the prefix 352 there can be a variable number of digits, between 6 and 9. (https://en.wikipedia.org/wiki/Telephone_numbers_in_Europe)
But with inputmask I have to put 9 digits after the prefix.
How can I correct this in phone.js?
Thank you.

**Comment by DonDiegoAA** [comment]
After looking more closely at phone.js, and some tests, I rep)laced the luxembourg mask with these lines, and it seems to work 
`{ "mask": "+352-###-###", "cc": "LU", "cd": "Luxembourg", "desc_en": "", "name_ru": "Люксембург", "desc_ru": "" },
				{ "mask": "+352-####-###", "cc": "LU", "cd": "Luxembourg", "desc_en": "", "name_ru": "Люксембург", "desc_ru": "" },
				{ "mask": "+352-#####-###", "cc": "LU", "cd": "Luxembourg", "desc_en": "", "name_ru": "Люксембург", "desc_ru": "" },
				{ "mask": "+352-######-###", "cc": "LU", "cd": "Luxembourg", "desc_en": "", "name_ru": "Люксембург", "desc_ru": "" },`

**Comment by RobinHerbots** [comment]
@DonDiegoAA , 

Can you send a PR for the changes.

**Comment by DonDiegoAA** [comment]
I sent the PR, but I'm not sure that my new masks are optimized.

Thank you for this great plugin.

**Comment by RobinHerbots** [comment]
@DonDiegoAA , 

Thx!
