### ISSUE TITLE
Placeholder text a different colour than inputted text?

### ISSUE THREAD

**Issue by ryanlanglois** [RobinHerbots/Inputmask#1464]
It would improve the UX if the placeholder text could be a different colour than the text submitted by a user. Is this currently possible, or am I missing something?

Right now it's a bit confusing since it's hard to tell which text is placeholder while you're in the middle of typing.

**Comment by RobinHerbots** [comment]
@ryanlanglois , 

Have a look at the colormask option

**Comment by ryanlanglois** [comment]
@RobinHerbots thanks! Wasn't sure about that. Do you have working examples of the colormask?

**Comment by RobinHerbots** [comment]
@ryanlanglois , 

Just add the colorMask option and include the inputmask.css
