### ISSUE TITLE
DD/MM/YYYY as in demo - how to do it?

### ISSUE THREAD

**Issue by bboyspyder** [RobinHerbots/Inputmask#1470]
How can I get the DD/MM/YYYY masking to behave as in the demo.

I looked at the demo source code but the code for that seems ot be added into the bundle.js file which is different to the one in the GitHub zip file.

**Comment by RobinHerbots** [comment]
@bboyspyder , 

The zip contains the latest release and the demo uses the files on github.

You need the inputmask.js and the date extensions or you take the bundle which includes everything.

Then apply the dd/mm/yyyy alias
