### ISSUE TITLE
IE11 : SCRIPT438: Object doesn't support property or method 'isFinite'

### ISSUE THREAD

**Issue by stevenbriscoeca** [RobinHerbots/Inputmask#1472]
I am getting this error In IE11 : 
SCRIPT438: Object doesn't support property or method 'isFinite'

I am using : 
* jquery.inputmask.bundle.js
* Version: 3.3.4-128

Thank you!

**Comment by RobinHerbots** [comment]
@stephenbe , 

Which mask do you use?  I tried locally but the problem doesn't show up.

**Comment by stevenbriscoeca** [comment]
Hello Robin,

I am using : 
https://github.com/RobinHerbots/Inputmask/blob/3.x/dist/jquery.inputmask.bundle.js

This doesn't work for me :
http://s.codepen.io/stephendesjardins/debug/ObqGpv

you can see the code here : 
http://codepen.io/stephendesjardins/pen/ObqGpv

![2016-12-21_09-18-52](https://cloud.githubusercontent.com/assets/3018441/21392607/a93213bc-c75e-11e6-98d6-a2d91c57c896.png)

This is a corporate IE11 so I am wondering if you have the same version of me...maybe that is the problem

Thank you for the quick reply, I very much appreciate it.

Edit : It seems to be caused by https://github.com/RobinHerbots/Inputmask/blob/3b407c47089c10188f38410e5c1ea1b9eabad165/dist/jquery.inputmask.bundle.js#L256
```
Number.isFinite
```

In IE11 Number.isFinite returns undefined 
![image](https://cloud.githubusercontent.com/assets/3018441/21392765/6ec93b82-c75f-11e6-8745-ece4cc3d8918.png)

**Comment by stevenbriscoeca** [comment]
Works perfectly! I could not ask for a better response time! Amazing :+1:
