### ISSUE TITLE
Form can`t submitted with input[name=disabled]

### ISSUE THREAD

**Issue by dkrnl** [RobinHerbots/Inputmask#1473]
Hi!

This form example, can`t never submit:
```html
<form>
<input type="tel" name="tel">
<input type="checkbox" name="disabled" value="1" checked>
<input type="submit">
</form>
```

Submit blocked in if-statement this line: [inputmask.js#L2049](https://github.com/RobinHerbots/Inputmask/blob/3.x/js/inputmask.js#L2049)

Thx!

**Comment by RobinHerbots** [comment]
@dkrnl , 

It seemed caused by the name="disabled" which populates the disabled property on the form. I will add an extra check for the form element.
