### ISSUE TITLE
Alias for yyyy-mm-dd hh:mm:ss

### ISSUE THREAD

**Issue by gibacca** [RobinHerbots/Inputmask#1475]
How do I create an alias for 'yyyy-mm-dd hh:mm:ss'? Used to work as a mask, with 3.3.4 it needs an alias.
Looking at the definition for 'dd/mm/yyyy hh:mm' in jquery.inputmask.bundle.js, but it's not that clear to me how to add my own definition that is not as complex...

**Comment by Syno0** [comment]
Hi,

I'm not sure about the good way to do this but I found a solution like this : 

`$(".input").inputmask({
	mask: "y-1-2 h:s:s",
	placeholder: "yyyy-mm-dd hh:mm:ss",
	separator: "-",
	alias: "yyyy/mm/dd"
});`

Hoping this helps you

**Comment by gibacca** [comment]
Hmm, the date part works, but not the time part. Placeholder shows up as: 'yyyy-mm-dd h:s:s', and the date part can be filled in, but not the time part...

**Comment by gibacca** [comment]
I tried this:
$(".input").inputmask({mask: 'y-1-2 h:s:s', placeholder: 'yyyy-mm-dd hh:mm:ss', separator: '-', alias: 'datetime'})

But there seems to be an interaction between the day and the hours...

**Comment by RobinHerbots** [comment]
@gibacca , 

```
		Inputmask({
			mask: "y-1-2 h:s:s",
			placeholder: "yyyy-mm-dd hh:mm:ss",
			alias: "datetime",
			separator: "-",
			leapday: "-02-29",
			regex: {
				val2pre: function (separator) {
					var escapedSeparator = Inputmask.escapeRegex.call(this, separator);
					return new RegExp("((0[13-9]|1[012])" + escapedSeparator + "[0-3])|(02" + escapedSeparator + "[0-2])");
				}, //daypre
				val2: function (separator) {
					var escapedSeparator = Inputmask.escapeRegex.call(this, separator);
					return new RegExp("((0[1-9]|1[012])" + escapedSeparator + "(0[1-9]|[12][0-9]))|((0[13-9]|1[012])" + escapedSeparator + "30)|((0[13578]|1[02])" + escapedSeparator + "31)");
				}, //day
				val1pre: new RegExp("[01]"), //monthpre
				val1: new RegExp("0[1-9]|1[012]") //month
			},
			onKeyDown: function (e, buffer, caretPos, opts) {
			}
		}).mask("test4");
```

**Comment by RobinHerbots** [comment]
@gibacca , 

I added an alias in the date extensions for it.  Even more handy ;-)

**Comment by gibacca** [comment]
@RobinHerbots  Thanks for looking into this, I was trying to figure out the best way to add this to my code, but having this alias already defined helps :) Hope this can be used by more people...

**Comment by RobinHerbots** [comment]
Hi @gibacca , 

I created a project to refactor the datetime aliases.  So it will all change in future versions.

**Comment by gibacca** [comment]
@RobinHerbots Will the API change, or just the implementation?

**Comment by RobinHerbots** [comment]
@gibacca , 

Both, but I can keep a transition period.
I want a datetime alias where you pass a pattern for masking
