### ISSUE TITLE
Doesn't work with webpack (Module not found)

### ISSUE THREAD

**Issue by folmert** [RobinHerbots/Inputmask#1478]
Installing by:
`npm install --save-dev jquery.inputmask`
works.

Requiring module by:
`require('jquery.inputmask');`
doesn't work, it returns:

> ERROR in ./~/jquery.inputmask/dist/inputmask/inputmask.date.extensions.js
>     Module not found: Error: Can't resolve 'inputmask.dependencyLib' in 'C:\sites\YDR\branches\refactoring\tools\webpack\node_modules\jquery.inputmask\dist\inputmask'
>      @ ./~/jquery.inputmask/dist/inputmask/inputmask.date.extensions.js 9:48-107
>      @ ./~/jquery.inputmask/index.js
>      @ C:/sites/YDR/branches/refactoring/development/app/static/modules/analytics/analytics.js
>      @ multi main
> 
>     ERROR in ./~/jquery.inputmask/dist/inputmask/inputmask.numeric.extensions.js
>     Module not found: Error: Can't resolve 'inputmask.dependencyLib' in 'C:\sites\YDR\branches\refactoring\tools\webpack\node_modules\jquery.inputmask\dist\inputmask'
>      @ ./~/jquery.inputmask/dist/inputmask/inputmask.numeric.extensions.js 9:48-107
>      @ ./~/jquery.inputmask/index.js
>      @ C:/sites/YDR/branches/refactoring/development/app/static/modules/analytics/analytics.js
>      @ multi main
> 
>     ERROR in ./~/jquery.inputmask/dist/inputmask/inputmask.phone.extensions.js
>     Module not found: Error: Can't resolve 'inputmask.dependencyLib' in 'C:\sites\YDR\branches\refactoring\tools\webpack\node_modules\jquery.inputmask\dist\inputmask'
>      @ ./~/jquery.inputmask/dist/inputmask/inputmask.phone.extensions.js 9:48-107
>      @ ./~/jquery.inputmask/index.js
>      @ C:/sites/YDR/branches/refactoring/development/app/static/modules/analytics/analytics.js
>      @ multi main
> 
>     ERROR in ./~/jquery.inputmask/dist/inputmask/inputmask.js
>     Module not found: Error: Can't resolve 'inputmask.dependencyLib' in 'C:\sites\YDR\branches\refactoring\tools\webpack\node_modules\jquery.inputmask\dist\inputmask'
>      @ ./~/jquery.inputmask/dist/inputmask/inputmask.js 9:48-107
>      @ ./~/jquery.inputmask/index.js
>      @ C:/sites/YDR/branches/refactoring/development/app/static/modules/analytics/analytics.js
>      @ multi main
> 
>     ERROR in ./~/jquery.inputmask/dist/inputmask/inputmask.regex.extensions.js
>     Module not found: Error: Can't resolve 'inputmask.dependencyLib' in 'C:\sites\YDR\branches\refactoring\tools\webpack\node_modules\jquery.inputmask\dist\inputmask'
>      @ ./~/jquery.inputmask/dist/inputmask/inputmask.regex.extensions.js 9:48-107
>      @ ./~/jquery.inputmask/index.js
>      @ C:/sites/YDR/branches/refactoring/development/app/static/modules/analytics/analytics.js
>      @ multi main
> 
>     ERROR in ./~/jquery.inputmask/dist/inputmask/inputmask.extensions.js
>     Module not found: Error: Can't resolve 'inputmask.dependencyLib' in 'C:\sites\YDR\branches\refactoring\tools\webpack\node_modules\jquery.inputmask\dist\inputmask'
>      @ ./~/jquery.inputmask/dist/inputmask/inputmask.extensions.js 9:48-107
>      @ ./~/jquery.inputmask/index.js
>      @ C:/sites/YDR/branches/refactoring/development/app/static/modules/analytics/analytics.js
>      @ multi main
> 
>     ERROR in ./~/jquery.inputmask/dist/inputmask/inputmask.date.extensions.js
>     Module not found: Error: Can't resolve 'inputmask' in 'C:\sites\YDR\branches\refactoring\tools\webpack\node_modules\jquery.inputmask\dist\inputmask'
>      @ ./~/jquery.inputmask/dist/inputmask/inputmask.date.extensions.js 9:48-107
>      @ ./~/jquery.inputmask/index.js
>      @ C:/sites/YDR/branches/refactoring/development/app/static/modules/analytics/analytics.js
>      @ multi main
> 
>     ERROR in ./~/jquery.inputmask/dist/inputmask/inputmask.numeric.extensions.js
>     Module not found: Error: Can't resolve 'inputmask' in 'C:\sites\YDR\branches\refactoring\tools\webpack\node_modules\jquery.inputmask\dist\inputmask'
>      @ ./~/jquery.inputmask/dist/inputmask/inputmask.numeric.extensions.js 9:48-107
>      @ ./~/jquery.inputmask/index.js
>      @ C:/sites/YDR/branches/refactoring/development/app/static/modules/analytics/analytics.js
>      @ multi main
> 
>     ERROR in ./~/jquery.inputmask/dist/inputmask/inputmask.phone.extensions.js
>     Module not found: Error: Can't resolve 'inputmask' in 'C:\sites\YDR\branches\refactoring\tools\webpack\node_modules\jquery.inputmask\dist\inputmask'
>      @ ./~/jquery.inputmask/dist/inputmask/inputmask.phone.extensions.js 9:48-107
>      @ ./~/jquery.inputmask/index.js
>      @ C:/sites/YDR/branches/refactoring/development/app/static/modules/analytics/analytics.js
>      @ multi main
> 
>     ERROR in ./~/jquery.inputmask/dist/inputmask/jquery.inputmask.js
>     Module not found: Error: Can't resolve 'inputmask' in 'C:\sites\YDR\branches\refactoring\tools\webpack\node_modules\jquery.inputmask\dist\inputmask'
>      @ ./~/jquery.inputmask/dist/inputmask/jquery.inputmask.js 9:48-90
>      @ ./~/jquery.inputmask/index.js
>      @ C:/sites/YDR/branches/refactoring/development/app/static/modules/analytics/analytics.js
>      @ multi main
> 
>     ERROR in ./~/jquery.inputmask/dist/inputmask/inputmask.regex.extensions.js
>     Module not found: Error: Can't resolve 'inputmask' in 'C:\sites\YDR\branches\refactoring\tools\webpack\node_modules\jquery.inputmask\dist\inputmask'
>      @ ./~/jquery.inputmask/dist/inputmask/inputmask.regex.extensions.js 9:48-107
>      @ ./~/jquery.inputmask/index.js
>      @ C:/sites/YDR/branches/refactoring/development/app/static/modules/analytics/analytics.js
>      @ multi main
> 
>     ERROR in ./~/jquery.inputmask/dist/inputmask/inputmask.extensions.js
>     Module not found: Error: Can't resolve 'inputmask' in 'C:\sites\YDR\branches\refactoring\tools\webpack\node_modules\jquery.inputmask\dist\inputmask'
>      @ ./~/jquery.inputmask/dist/inputmask/inputmask.extensions.js 9:48-107
>      @ ./~/jquery.inputmask/index.js
>      @ C:/sites/YDR/branches/refactoring/development/app/static/modules/analytics/analytics.js
>      @ multi main
>

**Comment by RobinHerbots** [comment]
@folmert , 

This is solved in version 3.3.5.  See webpack section in the readme
