### ISSUE TITLE
jQuery dependency

### ISSUE THREAD

**Issue by haggen** [RobinHerbots/Inputmask#1480]
Hi there. I'm sorry if this is something obvious, after reading the README and the Wiki I'm not quite sure if I can use it without jQuery. It says "dependencyLibs: vanilla javascript" right in the start of the REAME, but I'm not sure I understand what that means. If it's possible an example would definitely clear things up. Thanks in advance!

**Comment by RobinHerbots** [comment]
Hi @haggen , 
You can use the inputmask without jquery, but then you have to load the inputmask.dependencylib.js from the extra folder.

Do you use a module loader or just load the scripts?

**Comment by haggen** [comment]
Hi @RobinHerbots thank you for replying so fast! I'm just loading the scripts.

**Comment by RobinHerbots** [comment]
@haggen , 

So in that case you just need to load the script s seperately.  Not the bundle.
First load tje dependencylib from the extra folder, after that you load the other files in the dist folder.
Use it like 

Inputmask("yourmask").mask(selector);

**Comment by haggen** [comment]
Oh I see, the file is not in the `dist` directory. Thanks man, it works now!
