### ISSUE TITLE
how to define some value fixed (But 9)

### ISSUE THREAD

**Issue by cappittall** [RobinHerbots/Inputmask#1481]
Hello! Thank you  for the great library. 

I would like to input phone nr with  $("#id_phone").inputmask("+90(599) 999-9999"); 

0 and 5 is ok. Its on its place. but I want to fix first digit "+9" . (non changeable)  
How can I fix that. I review and tried to read most of documents and Issues. Sorry but I could not fixed yet. 
Thank you in advance.

**Comment by RobinHerbots** [comment]
Hi @cappittall , 

You need to prefix the 9 with \\\\
$("#id_phone").inputmask("+\\\\90(599) 999-9999");
https://github.com/RobinHerbots/Inputmask#escape-special-mask-chars
