### ISSUE TITLE
hasOwnProperty check missing in reverseTokens (numericInput)

### ISSUE THREAD

**Issue by mvangelist** [RobinHerbots/Inputmask#1486]
Using latest version 3.3.5-10. Need to check for hasOwnProperty when using "for in loop". There are times when I get the object's prototypes back in the match. 
![screenshot at jan 10 16-44-46](https://cloud.githubusercontent.com/assets/8147653/21828248/1c5de608-d755-11e6-81db-8c44572278c2.png)

**Comment by RobinHerbots** [comment]
Hi @mvangelist,

Can you also give an example to reproduce, so I can add it to the unit tests.?

**Comment by RobinHerbots** [comment]
@mvangelist , 

Fixed
