### ISSUE TITLE
showMaskOnFocus mask stays shown

### ISSUE THREAD

**Issue by RobinHerbots** [RobinHerbots/Inputmask#1488]
#601 

I'm using the latest version, and I still have this problem. The default state for showMaskOnFocus is true, yet even though I am not focused on the input in question, the mask is still shown!

I'm not sure if this is because I'm using the data attributes like this:

@Html.EditorFor(model => model.ShippingCost, new { htmlAttributes = new { @class = "form-control", data_inputmask = "'mask': '¥ 9{*}[.9{*}]'" } })

It is in ASP.net MVC Razor view.

**Comment by RobinHerbots** [comment]
@Ciwan1859, 

Can you reproduce this in a jsfiddle?

**Comment by Umadevijuvva** [comment]
showMaskOnHover and showMaskOnFocus not working in MAC safari.I am using the latest version of JS file.My code is as below,

$(document).ready(function () {
		$(".bsMessage").inputmask({
		        "mask": "999/9999/99999",
		        showMaskOnFocus: false,
		        showMaskOnHover: false
		    });
		});

I am using jquery.inputmask.bundle.min.js

**Comment by RobinHerbots** [comment]
@Umadevijuvva , 

Ok I tested the http://jsfiddle.net/pnL3veks/1/
on Mac Sierra Safari 10 and that seems ok, ...   the mask doesn't show on hover nor on focus.

**Comment by Umadevijuvva** [comment]
Dear,

I am using OSX EI Captain MAC IOS 10.11.6,PFB image


![image](https://cloud.githubusercontent.com/assets/25683896/23018016/c6024d3a-f43c-11e6-8343-ae7b1d9af94e.png)

**Comment by RobinHerbots** [comment]
@Umadevijuvva , 

I tested on browserstack El Capitan with Safari 9.1, ... the mask doesn't show.  I guess I miss something.  Can you explain the exact problem again.

**Comment by Umadevijuvva** [comment]
Robin,

I have a textbox with mask,in some cases my textbox will be prefilled with numbers.When the user hovers or click inside the textbox and goes out of it again default value is getting cleared.I have the same problem before in windows and when i gave the properties showMaskOnFocus and showMaskOnHover to false issue is solved,but not for MAC.

Please let me know if more information is required.

**Comment by RobinHerbots** [comment]
@Umadevijuvva , 
Have a look at this jsfiddle.  http://jsfiddle.net/pnL3veks/8/

This shows the problem if I am correct?

**Comment by RobinHerbots** [comment]
@Umadevijuvva , 

And this version shows also the problem in all other browsers.

http://jsfiddle.net/pnL3veks/9/

**Comment by Umadevijuvva** [comment]
Yes Robin,more or less its the same issue.But if i remove the
noValuePatching property in your fiddle,it works in IE and Chrome.

**Comment by RobinHerbots** [comment]
@Umadevijuvva , 

Yes, it was just to show you.  I will submit a fix today.  It is because the safari browser does not support patching the native value property of the input and the fallback method failed also.

**Comment by RobinHerbots** [comment]
@Umadevijuvva , 

Have a retry with the current on github.

**Comment by RobinHerbots** [comment]
@Ciwan1859,

Any update on this?  Browser(s) used, ... can you reproduce in jsfiddle?

**Comment by Umadevijuvva** [comment]
Robin,

I am retrying version has to be deployed,will let you know ASAP.

**Comment by Umadevijuvva** [comment]
Robin,

Just noticed that i a using jquery.inputmask.bundle.min.js and the fix you just gave is in the core file inputmask.js.When i am including the core file ,i get an error

![image](https://cloud.githubusercontent.com/assets/25683896/23022857/5d859548-f453-11e6-92f4-37e5e97265d3.png)

Can you give an example how to call ?

**Comment by RobinHerbots** [comment]
@Umadevijuvva , 

It is also included in the minified file!

When using the inputmask.js only you should use 
Inputmask("yourmask",  { options }).mask(selector)

**Comment by Umadevijuvva** [comment]
Robin,

Could you please publish the minified version or send me the link?I could not find it

**Comment by RobinHerbots** [comment]
https://github.com/RobinHerbots/Inputmask/blob/3.x/dist/min/jquery.inputmask.bundle.min.js

**Comment by Umadevijuvva** [comment]
Robin,

It still doesnt work,same issue exists.Value gets disappered on hower or when we enter textbox or when we enter inside and exits the textbox also.

**Comment by RobinHerbots** [comment]
@Umadevijuvva , 

Have a look at http://jsfiddle.net/pnL3veks/12/

**Comment by Umadevijuvva** [comment]
Robin,

I am not using property greedy: false,just using the below code.I hope no other properties needs to be added apart from the below,


$(document).ready(function () {
		$(".textMsg").inputmask({
		        "mask": "999/9999/99999",
		        showMaskOnFocus: false,
		        showMaskOnHover: false,
		        
		    });
		});


Should the  noValuePatching: true be set???

**Comment by RobinHerbots** [comment]
@Umadevijuvva , 

No the only needed are as you mention in the example.  The noValuePatching is a dev option so don't use it.  Are you sure the older version isn't still in cache or so

**Comment by Umadevijuvva** [comment]
Robin,

Exactly,issue is with cache..it works as expected now.Many Thanks.
