### ISSUE TITLE
Empty / clear field on focus

### ISSUE THREAD

**Issue by fdan4824** [RobinHerbots/Inputmask#149]
I have looked at the instructions and searched the forums. I may be missing something obvious, but is there a way to clear the field when the field gains focus? 

It would be great if it restored the previous value in the event no data was entered (or if that was at least an option).

Thanks,
Dan

**Comment by RobinHerbots** [comment]
Hi Dan,

I do not understand what you mean exactly.

With the clearMaskOnLostFocus you clear the mask on loosing focus when no
data has been entered. Gaining focus again shows the 'empty' mask again.

With clearIncomplete you clear the mask when loosing focus unless the data
entry completes the mask.

Can you give me an example with the different steps and the desired result.

Best regards,

Robin

2012/12/27 fdan4824 notifications@github.com

**Comment by fdan4824** [comment]
This is about fields that already have data. For example a "not-negative decimal" field. When the page loads the value is  2.50, but I want to change it 4.75.

Currently, I have to delete the 2.50 and for some reason highlighting the field and typing doesn't wipe the data and neither does hitting the backspace or delete key. I have to backspace or delete through the entire length of the field. 

If I was not using an input mask, I would use the "onfocus" event to set the field to blank and store the value in a variable that could be retrieved "onblur." However, my understanding is that the input mask "takes over" those event and thus I can't create such events of my own.

Am I mistaken?

**Comment by RobinHerbots** [comment]
Hi Dan, 

You can still use those events even if the plugin uses them also.

I'm aware that the numeric extensions aren't optimal for the moment, but I am busy working on the optional masks (and other stuff besides inputmask).  Anyway I will have a look at the numeric mask soon.

You may always create a jsfiddle which exactly shows your problem, try adding the extra behavior via the blur event, and so I can also have a quick look at it.

best regards, 

Robin

**Comment by fdan4824** [comment]
OK. I guess I just jumped to a conclusion about the onfocus and onblur
events based on some past experience. I will work with and see where it
goes.

Thanks for your quick responses.

Dan

**Comment by RobinHerbots** [comment]
Hi Dan, 

The issues about backspace, delete, cannot overtype in numerics is solved

Best regards, 

Robin
