### ISSUE TITLE
Currency mask does not work correctly when groupseparator occurs as first character in the suffix

### ISSUE THREAD

**Issue by krajcot** [RobinHerbots/Inputmask#1494]
I'm using currency input mask with currency symbol Euro (€) and since version 3.3.4 it does not work correctly. In the earlier versions it worked OK, but not on Android devices. It did not work correctly even before on Android devices.
Example:
$(input).inputmask("currency", {
    groupSeparator: " ",
    autoGroup: true,
    suffix: " €",
    prefix: "",
    digits: 0
});
It seems, that problem causes combination space " " group separator and suffix.
For more details see example with latest version: http://jsfiddle.net/5wkwgkgx/8/
and with version 3.3.3: http://jsfiddle.net/5wkwgkgx/10/

**Comment by RobinHerbots** [comment]
@krajcot , 

Did I mention that I hate regression?  ;-)

I will fix asap

**Comment by RobinHerbots** [comment]
@krajcot , 

Can you retry to verify if the issue is resolved

**Comment by krajcot** [comment]
@RobinHerbots,

It seems that it works fine on a desktop and also on iOS, but on Android devices problem still remains. When I want to delete last number by pressing backspace button, all numbers after the first space are deleted.

**Comment by RobinHerbots** [comment]
@krajcot , 

Ok I will check if it can be fixed for android

**Comment by RobinHerbots** [comment]
@krajcot , 

It can be reproduces on desktop to when specifying the inputonly event.  So it is fixable.

**Comment by RobinHerbots** [comment]
@krajcot , 

I submitted a patch, can you retry on android

**Comment by krajcot** [comment]
@RobinHerbots ,

It is better now, but not perfect. First thing, after typing fourth number, cursor will jump  on previous position and numbers are typed in the middle of text instead of at the end. 
Second thing, during deleting numbers, when cursor comes to the gap, it is necessary to press backspace button twice to delete last number.

**Comment by RobinHerbots** [comment]
@krajcot , 

Ok, I can reproduce both.

**Comment by RobinHerbots** [comment]
@krajcot , 

I think this is fixed, can you confirm.
