### ISSUE TITLE
onCleared event doesn't fire with 'numeric' alias in some case

### ISSUE THREAD

**Issue by pavel-mironchik** [RobinHerbots/Inputmask#1495]
Hello.

I tested Inputmask ver. 3.3.4 in Firefox/Chrome on Ubuntu 16 and seems that I found a strange behaviour with 'numeric' alias.

I prepared the JSFiddle: https://jsfiddle.net/brunen9/qufom3L6/1/
It has two input fields with same mask. You first select all in #numeric1 and delete - alert will popup, then type anything in input and delete again - alert will popup too, as expected. Then select "12" in #numeric2 and delete - value will be "0.34", now select all and delete - nothing will happen (no alert), and type something one more time and delete - still nothing.

**Comment by RobinHerbots** [comment]
@brunen9 , 

Can you retry with https://jsfiddle.net/qufom3L6/2/ to confirm this is resolved.

**Comment by pavel-mironchik** [comment]
@RobinHerbots, it works well now. Thanks for your work!

**Comment by RobinHerbots** [comment]
@brunen9 , 

Great thx!
