### ISSUE TITLE
datepicker ui auto-opens

### ISSUE THREAD

**Issue by mcdanielisaac** [RobinHerbots/Inputmask#15]
When I have this script loaded and an instance of the datepicker ui, the datepicker automatically opens without a click and is positioned in a random position on the screen.  Also the form field that has focus is the last field using .inputmask.  Any thoughts as to how to get around these issues and still use both your script and datepicker?

**Comment by RobinHerbots** [comment]
Hi Isaac,

Can you send me an example of your code to reproduce the problem.

Robin

2011/10/17 mcdanielisaac <
reply@reply.github.com>

**Comment by mcdanielisaac** [comment]
Sure!  My jQuery code is below, if you need any other snippets let me know.

``` javascript
$(document).ready(function() {
    $(function() {
        $("#arrivalDate")
            .datepicker({
            minDate: '2/16/2012',
            maxDate: '2/25/2012',
            dateFormat: 'mm/dd/yy',
            buttonImage: 'images/calendar-icon.png',
            buttonImageOnly: true,
            showOn: 'both',
            hideIfNoPrevNext: true,
            showAnim: '',
            })
            .inputmask("m/d/y");
    })
});
```

**Comment by RobinHerbots** [comment]
the focus on the field causes the datepicker to showup but that's a feature
of the datepicker, .... you can change that behavior with the showOn
option.  About the random position.  I could not reproduce this.  Do you use
blockUI in combination? or another dialog-plugin?  Have you tried the same
code without .inputmask('m/d/y') ?

Robin

2011/10/17 mcdanielisaac <
reply@reply.github.com>

**Comment by mcdanielisaac** [comment]
I'm finding the random position issues is Chrome related.  The datepicker box appears in the correct position in other browsers.

When I remove the .inputmask('m/d/y') the datepicker acts as expected, hidden on load, correct position, and displays on focus and on button click.  

I was really hoping to leave the showOn option as 'both,' but it seems as though having the option for the datepicker to appear on focus causes the issues, so I'll just leave it as 'button' only.  Thank you for your help!

**Comment by RobinHerbots** [comment]
I will have a look at it in Chrome.  I tested it in FF.

2011/10/17 mcdanielisaac <
reply@reply.github.com>

**Comment by mcdanielisaac** [comment]
There does still seem to be an issue where the last field that has the input mask added, retains focus even if adding a .focus() to a field after the .inputmask call.  I tested in FF, Chrome, Safari with the datepicker taken out of my code to check.  Thanks for the help!

**Comment by RobinHerbots** [comment]
I have tested it in Chrome and didn't had any positioning problems.

2011/10/17 Robin Herbots robin.herbots@gmail.com

**Comment by RobinHerbots** [comment]
I cannot reproduce such behavior.  Which version of the inputmask do you
use?  Can you reproduce the issue on jsfiddle?

2011/10/17 mcdanielisaac <
reply@reply.github.com>

**Comment by mcdanielisaac** [comment]
I am using the Sept 30 version of inputmask.  Let me get a jsfiddle up and I'll send you the link.

**Comment by mcdanielisaac** [comment]
Robin -
Here is the jsfiddle that shows the issue I'm having.  Again thanks!

http://jsfiddle.net/mcdaniel_isaac/EEx2Z/

**Comment by RobinHerbots** [comment]
Hi Isaac,

Check out the latest version which fixes the issue.  It was causes by the
last change.  Setting the caret unconditionally when applying the mask, also
sets the focus on the input.

Robin

2011/10/17 mcdanielisaac <
reply@reply.github.com>

**Comment by mcdanielisaac** [comment]
Thanks Robin!  This fix corrected all my problems with datepicker and focus.  This really is a great script!!!
