### ISSUE TITLE
decimal doesn't display negative values when placeholder is not specified

### ISSUE THREAD

**Issue by MrCsabaToth** [RobinHerbots/Inputmask#1500]
I haven't isolated this in a small example, but I updated inputmask from a 2016 June version a couple of weeks ago. Suddenly negative values don't display. I didn't use any placeholder, since in my application there can be empty values, which are different than 0 values.

                var maskCfg = {
                    'alias': 'decimal',
                    'groupSeparator': ",",
                    'autoGroup': true,
                    'digits': 0,
                    'radixPoint': "",
                    'digitsOptional': true,
                    'allowMinus': true,
                    'prefix': '$ ',
                    'suffix': '',
                    //'placeholder': '0',
                    'autoUnmask': true,
                    'unmaskAsNumber': true,
                    'clearMaskOnLostFocus': false
                };
                $(element).inputmask('decimal', maskCfg);

**Comment by MrCsabaToth** [comment]
3.3.3 works good, 3.3.4 has the bug

**Comment by MrCsabaToth** [comment]
Not to self: commits to check between 3.3.3 and 3.3.4:
https://github.com/RobinHerbots/Inputmask/commit/cee9f100a5821c24659324776399711520573c13
https://github.com/RobinHerbots/Inputmask/commit/ec15c66ad4262f7ec693bc931f80cf69e6117c1c
https://github.com/RobinHerbots/Inputmask/commit/e199e7af716d3c61365ede362783ea1988218893
https://github.com/RobinHerbots/Inputmask/commit/72fc3bff2e5282a151d8ab2ceb1baee68f52d150
https://github.com/RobinHerbots/Inputmask/commit/39693b70184a25cc78b383df78ac572c96bf2bd0

maybe check if I include everything needed, right now:

                "\~/bower_components/jquery.inputmask/dist/min/inputmask/inputmask.min.js",
                "\~/bower_components/jquery.inputmask/dist/min/inputmask/jquery.inputmask.min.js",
                "\~/bower_components/jquery.inputmask/dist/min/inputmask/inputmask.extensions.min.js",
                "\~/bower_components/jquery.inputmask/dist/min/inputmask/inputmask.regex.extensions.min.js",
                "\~/bower_components/jquery.inputmask/dist/min/inputmask/inputmask.numeric.extensions.min.js",

**Comment by RobinHerbots** [comment]
@MrCsabaToth , 

Is this still an issue in version 3.3.5?

**Comment by MrCsabaToth** [comment]
I need to check since I'm using workarounds for a while now.

**Comment by miles82** [comment]
I have this issue in 3.3.5 and head (3.3.6-10), but not in 3.3.4 (maybe @MrCsabaToth was using head revision at the time which became 3.3.5?). Negative values are displayed as -0 if there is no placeholder defined, with placeholder they're displayed OK.

**Comment by MrCsabaToth** [comment]
I'm using a NuGe package and the 3.3.4 is the newest one there so I need to work a little more to try that

**Comment by MrCsabaToth** [comment]
Oh, there's a new NuGet package instead of upgrading the old one.... Reverting back from bower to NuGet then

**Comment by MrCsabaToth** [comment]
3.3.5 solves this

**Comment by miles82** [comment]
3.3.5 doesn't solve, but introduce, this for me :)

It's triggered by some weird combo of digitsOptional/groupSeparator. I use:
  digitsOptional: false,
  groupSeparator: '.',
  radixPoint: ','

And it doesn't work in 3.3.5. Works if digitsOptional is true or if placeholder is set or if prefix is set or if groupSeparator is not changed...

With 3.3.4:
https://jsfiddle.net/8umvaL48/

With 3.3.5:
https://jsfiddle.net/3rp9hte8/

**Comment by MrCsabaToth** [comment]
@miles82 I'll check if I have any workaround left in there anywhere. But certainly before 3.3.4 -> 3.3.5 upgrade it didn't even work with the workaround (if I have any).

**Comment by MrCsabaToth** [comment]
@miles82 Nice js Fiddles! I didn't focus on the initial value, but if it's possible to enter negative numbers and in my app I couldn't even enter. I'll check my parameters tonight.

**Comment by MrCsabaToth** [comment]
Oh, one of my example configuration is in my opening post.
I just tried one where:

            var maskCfg = {
                'alias': 'decimal',
                'groupSeparator': ",",
                'autoGroup': true,
                'digits': 0,
                'radixPoint': ".",
                'digitsOptional': false,
                'allowMinus': true,
                'prefix': '$ ',
                'suffix': '',
                //'placeholder': '0',
                'autoUnmask': true,
                'unmaskAsNumber': true,
                'clearMaskOnLostFocus': false
            };
            $(element).inputmask('decimal', maskCfg);

and it looked like working - I mean you can enter negative values, but I didn't test the initial value

**Comment by MrCsabaToth** [comment]
@miles82 if you add a `prefix: ' '` of any kind to https://jsfiddle.net/3rp9hte8/ it fixes it. Try other combinations as well. `autoGroup`, `autoUnmask`, `clearMaskOnLostFocus`, `suffix` doesn't seem to affect it.

**Comment by RobinHerbots** [comment]
@MrCsabaToth , 

Interesting.  I will see why.

**Comment by newmangreen** [comment]
I have same problem, our users can't enter negative numbers if placeholder: '0' option is not specified. @MrCsabaToth's last fiddle depicts the problem clearly.
