### ISSUE TITLE
How can i add Placeholder instead of empty place

### ISSUE THREAD

**Issue by venkateshparuchuri8** [RobinHerbots/Inputmask#1502]

**Comment by RobinHerbots** [comment]
@venkateshparuchuri8 , 

Can you provide an example of what you want

**Comment by venkateshparuchuri8** [comment]
$(selector).inputmask('(\\91)-xxxxx-xxxxx')
 i need place holder like this on input field

**Comment by RobinHerbots** [comment]
@venkateshparuchuri8 , 

$(selector).inputmask('(\91)-99999-99999', {
placeholder: "x"
});

**Comment by venkateshparuchuri8** [comment]
Thank You @RobinHerbots
