### ISSUE TITLE
Poor performance on decimal input mask

### ISSUE THREAD

**Issue by all-kozlov** [RobinHerbots/Inputmask#1505]
Hi, Robin!
Do you think it will be usefull not to format value on every keypress event?
When I press button on keyboard, events pushes in stack and user see delay before text in input format right..This delay grows proportionally time I'm pressing key..
May be format value only on last event,  wrapping event in setTimeout and break it if new event was triggered?

**Comment by RobinHerbots** [comment]
@all-kozlov , 

Yes, I'm working on the numeric extension, but I don't have much time.

So It can take a while.

**Comment by hoang-pham** [comment]
Was this issue fixed? Currently, when I type more numbers after the radix point, the performance is very bad and it causes hang web page
Ex: type 0.9999999999999999999  on [demo page](https://robinherbots.github.io/Inputmask/)

**Comment by smo76** [comment]
Is there an estimated date for 5.0.8 release? I am looking forward to absorbing this fix,

**Comment by RobinHerbots** [comment]
I pushed a fix for this.

Can someone have a try and give remarks.

**Comment by Techn1c4l** [comment]
@RobinHerbots Just tested it with a group separator, appears to work just fine. Previously it would cause sever page slowdown if there are more than 15 digits in integer and decimal parts combined.
