### ISSUE TITLE
Numerics: On inputs with maxlenght you can type one type more than maxlenght

### ISSUE THREAD

**Issue by ChristopherSchaefer** [RobinHerbots/Inputmask#1506]
On an Input with maxlength and alias: numeric or integer set you still can type one type more then maxlength is.

When you you type "123" then the input shows "12" when you remove "2" the input shows "13".

--> [https://jsfiddle.net/Chris_Schaefer/pfoc6vms/](https://jsfiddle.net/Chris_Schaefer/pfoc6vms/1)

My goal ist to write only numers into the input without an mask.

**Comment by an-kh** [comment]
I also have issue with this, and it's not only numeric, but with e-mail too.

**Comment by RobinHerbots** [comment]
@ChristopherSchaefer , @an-kh ,

This is fixed in the current release
