### ISSUE TITLE
There is probably an error in your mask definition or in the code.

### ISSUE THREAD

**Issue by Maslovsky-Alexey** [RobinHerbots/Inputmask#1508]
(9{0, 10})|(9{0,10},9{0,2})

Uncaught TypeError: Cannot read property 'nodeName' of null
    at Inputmask.mask (inputmask.js:198)
    at Object.initialize (global.setup.js:21)
    at global.setup.js:28
    at global.setup.js:29

**Comment by Maslovsky-Alexey** [comment]
Uncaught Inputmask: There is probably an error in your mask definition or in the code. Create an issue on github with an example of the mask you are using. (9{0, 10})|(9{0,10},9{0,2})

**Comment by Maslovsky-Alexey** [comment]
Uncaught Inputmask: There is probably an error in your mask definition or in the code. Create an issue on github with an example of the mask you are using. 9{0, 10}

**Comment by RobinHerbots** [comment]
@Maslovsky-Alexey , 

Can you remove the space 9{0, 10} => 9{0,10}

**Comment by Maslovsky-Alexey** [comment]
@RobinHerbots 
Thank you!
