### ISSUE TITLE
Issue on firefox

### ISSUE THREAD

**Issue by mvcmania** [RobinHerbots/Inputmask#151]
jquery.inputmask.js throws and error while calling setTimeout function in FireFox.

Recommendation:

line 283:

setTimeout( opts.onKeyValidation.call(this, result, opts), 0) "Current way of call"

it should be :

setTimeout(function() { opts.onKeyValidation.call(this, result, opts); }, 0)

**Comment by RobinHerbots** [comment]
fixed, 

best regards

Robin
