### ISSUE TITLE
Mask placeholder shown when using greedy and symbol before

### ISSUE THREAD

**Issue by plarivierext** [RobinHerbots/Inputmask#1510]
We are using a mask with pattern: "$ 9,999,999,999", using greedy, right align and right input.
When the value entered has a lower amount of digits than the maximum, the mask placeholder is shown: 
i.e.: $___12345 instead of $12345

jsfiddle to show the problem:
http://jsfiddle.net/9xf2e73u/

We are currently using 3.3.3

**Comment by RobinHerbots** [comment]
@plarivierext , 

That seems normal, the optional indicated it's optionality as a whole.

Anyway have a look at http://jsfiddle.net/9xf2e73u/2/
