### ISSUE TITLE
Weird Issue with decimal masking when value is like 0.55

### ISSUE THREAD

**Issue by ozkaramete** [RobinHerbots/Inputmask#1512]
Hi,

I have a weird issue when using the following masking options. I am using jquery.inputmask.bundle.js * Version: 3.3.5-33

`var maskOptions = {
            alias: 'decimal',
            radixPoint: ',',
            groupSeparator: '.',
            autoGroup: true,
            digits: 2,
            removeMaskOnSubmit: false
        };`

If the value is something like 12345.67 everything works fine and masking occurs correctly and displays my input field as 12.345,67

But if the value is in between 0 and 1 then masking occurs incorrectly. For example if the value is 0.50 then my input field shows 50 as the masked value. It should be 0,50 with comma as the radixPoint.

I am dynamically generating pages with Java and when the page is first generated i see the correct values in html source (ie. input field value attribute is correct). But when the document.ready function is called and when the inputmask is applied to the fields it just makes 0.50 -> 50

I wonder if there is something you can point me out. Thanks in advance.

**Comment by newmangreen** [comment]
I think "12345.67" works by accident. You should format decimal number coming from Java by converting dot to comma since dot is evaluated as groupSeparator.

**Comment by RobinHerbots** [comment]
@medhjai , @newmangreen , 

Can you have a try with the current on github.  Just submitted a fix for it
