### ISSUE TITLE
When I delete a decimal it goes to 00 instead of erasing it

### ISSUE THREAD

**Issue by stevenbriscoeca** [RobinHerbots/Inputmask#1515]
I have an input with a numeric mask.

```
<input type="text" class="js-inputmask" data-inputmask="'alias': 'numeric', 'groupSeparator': ' ', 'autoGroup': true , 'digits': 2, 'digitsOptional': false, 'radixPoint' : ','">
```

If I add a decimal and then erase it, it goes to 00...any option to just erase the decimal instead of replacing the numbers to 00?

On focus out it adds 00 as well, is this optional?

http://codepen.io/stephendesjardins/pen/zNMZZb

Using version : 3.3.5-33

Thanks!

**Comment by Vasiliskov** [comment]
Might be because of `'digits': 2, 'digitsOptional': false` part. It basically says "this number **must** have 2 decimal positions no matter what". So it shows them even if they are empty ( = 0).

**Comment by stevenbriscoeca** [comment]
Thank you, that fixed the problem! :+1:
