### ISSUE TITLE
Adding suffix to numeric masque causing cursor to jump before

### ISSUE THREAD

**Issue by stevenbriscoeca** [RobinHerbots/Inputmask#1516]
I extended numeric mask by adding a suffix and it causes the cursor to jump before when a space is added : 
![inputmask-bug](https://cloud.githubusercontent.com/assets/3018441/22833442/f84086e8-ef7f-11e6-97c8-95c32f47ced2.gif)

You can see here that at 4 the cursor goes back and messes up the number.

What I want : 
1 234 567 890

what I get : 
1 245 678 904 

This is my extend 

```
Inputmask.extendAliases({
  'numeric-fr': {
    alias: "numeric",
    suffix: "$"
  }
});
```

You can test it here for yourself http://codepen.io/stephendesjardins/pen/mRQwev

Using version : 3.3.5-33

Thanks!

**Comment by RobinHerbots** [comment]
@stephenbe , 

I cannot reproduce within your codepen.  Is there missing some option?  Anyway, can you retry with the current on github.

**Comment by stevenbriscoeca** [comment]
I just updated the codepen with the latest version found on github (3.3.5-167)

I still get the error. 

JS

```
Inputmask.extendAliases({
  'numeric-fr': {
    alias: "numeric",
    suffix: "$"
  }
});

Inputmask.extendAliases({
  'numeric-en': {
    alias: "numeric",
    prefix: "$"
  }
});

$('.js-inputmask').inputmask({
  inputEventOnly: true,
  rightAlign: false
})
```

HTML 
```
<label>   
 Masque Fr
<input type="text" class="js-inputmask" data-inputmask="'alias': 'numeric-fr', 'groupSeparator': ' ', 'autoGroup': true, 'digits': 2, 'digitsOptional': false, 'radixPoint' : ','" />
 </label>   
<label> 
   Masque en
      <input type="text" class="form-control js-inputmask" data-inputmask="'alias': 'numeric-en', 'groupSeparator': ' ', 'autoGroup': true, 'digits': 2, 'digitsOptional': false, 'radixPoint' : ','" />
  </label>  
```

I hope this helps

**Comment by stevenbriscoeca** [comment]
I answered right when you added the label wait for response haha

**Comment by RobinHerbots** [comment]
@stephenbe , 

;-)  I didn't expect it so quickly as I was silent for some time!
Anyway I can reproduce.  Why do you use the inputEventOnly: true option?  Setting it to false solves it, but I will try to fix for input fallback also.

**Comment by stevenbriscoeca** [comment]
@RobinHerbots I am trying to figure out why I added inputEventOnly...I am going to be honest say I completely forgot maybe pasted from a random issue I found because that option is not documented anywhere...

I think we can close this.

**Comment by RobinHerbots** [comment]
It makes the Mask behave like on Android. So I need to fix this. But the option is a dev option.

**Comment by RobinHerbots** [comment]
@stephenbe , 

I submitted a patch which makes the above work even when specifying the inputEventOnly.

**Comment by stevenbriscoeca** [comment]
Amazing, your dedication to this project is inspiring! thank you so much!!
