### ISSUE TITLE
Year Only Mask Stopped working

### ISSUE THREAD

**Issue by weisborg** [RobinHerbots/Inputmask#1518]
It had been a few months since I updated, so I got the latest version and now my Year Only Masks just have a y in the input and nothing can be typed.  Previously they worked with the mask below.  Is there an alternate way to do this now, or is there a bug in the latest version?

`element.inputmask("y", { "clearIncomplete": true, yearrange: { "minyear": 1900, "maxyear": 2099 }, "placeholder": "YYYY" });`

**Comment by RobinHerbots** [comment]
@weiribao , 

The y definitions is removed in the date extensions.  See changelog.

**Comment by weisborg** [comment]
Ok, I see where it just says all the single letter values are removed.  Doesn't really go into detail on it though.  The Documentation still mentions them at the top along with:

dd/mm/yyyy
mm/dd/yyyy
yyyy/mm/dd
dd.mm.yyyy
dd-mm-yyyy
mm.dd.yyyy
mm-dd-yyyy
yyyy.mm.dd
yyyy-mm-dd
datetime
datetime12
mm/dd/yyyy hh:mm xm
hh:mm t
h:s t
hh:mm:ss
hh:mm
date
mm/yyyy
shamsi

So, the letters are still used, but are just limited to groups now?  I don't see a Year Only Format though.  I even looked in code and only see the above.  So, is there no way to get a Year only format like I used before?

**Comment by an-kh** [comment]
@weisborg I use custom definitions to create the behavior like the one that was before:
```javascript
{
	mask: "y",
	definitions: {
		y: {
			validator: "(19|20)\\d{2}",
			cardinality: 4,
			prevalidator: [{
				validator: "[12]",
				cardinality: 1,
			}, {
				validator: "(19|20)",
				cardinality: 2,
			}, {
				validator: "(19|20)\\d",
				cardinality: 3,
			}],
		},
	},
}
```
In my example range is restricted from 1900 to 2099.
