### ISSUE TITLE
variable "undoValue" isn't initialized correctly

### ISSUE THREAD

**Issue by kiesslir** [RobinHerbots/Inputmask#1519]
Hi,

in function "submitEvent" you use variable "undoValue" in a condition. In my opinion, these variable is (...in some cases...?) never initialized and `undefined` during submit.

Therefore i got the same problems as described in [#1392](https://github.com/RobinHerbots/Inputmask/issues/1392).

Could you please have a look?

**Comment by RobinHerbots** [comment]
@kiesslir , 

Fixed in the current
