### ISSUE TITLE
IE vs Chrome

### ISSUE THREAD

**Issue by rusifald** [RobinHerbots/Inputmask#152]
Hi, I do most of my development in Chrome and everything has been going swimmingly, but it was brought to my attention that the same site on IE, the mask appears in the box but does not work correctly.  Entering a character in does not replace the mask.  To test go to the following URL in IE and choose phone number for the first step, then try to enter a phone number in.  The phone number in its entirety gets inserted into wherever your cursor is.  The exact same code works just fine in Chrome.

http://www.pilottravelcenters.com/myrewardstest/RegistrationExisting.aspx

Error:
![screenshot_error](https://f.cloud.github.com/assets/3090858/44248/6593e388-56b5-11e2-85ef-e67bccd7dee9.png)

**Comment by RobinHerbots** [comment]
hi rusifald,

Grab the latest version from the 1.x branch.  The issue is already resolved.

Best regards, 

Robin
