### ISSUE TITLE
jquery inputmask not working correctly with decimal

### ISSUE THREAD

**Issue by Alexchep** [RobinHerbots/Inputmask#1520]
I have some trouble with inputmask(decimal). I put a value in "radixPoint" : "." ; The user should see the period as a separator. Regardless of an entered symbol("." and ",") a dot should appear. If I put a period in "radixPoint", I can enter from the keyboard only period, as the comma can't be entered. And if I put a comma, then takes a period and a comma as comma. I want to enter a period or a comma and get a period.

Thanks for ur time!

$('[name=sum]').inputmask({
		alias: "decimal",
		rightAlign: false,
		groupSeparator: " ",
		radixPoint: ".",
		autoGroup: true,
		integerDigits: 13,
		digitsOptional: true,
		digits: 2,
		allowPlus: false,
		allowMinus: false,
        onKeyDown: function () {
			//console.log(arguments, this);
            if (event.which === 188) {
                console.log(event);
                event.preventDefault();
                event.key = ".";
                event.which = 190;
                event.keyCode = 190;
            }
        },
        onUnMask: function(maskedValue, unmaskedValue, opts) {
			var value = String(unmaskedValue)
				.replace(new RegExp(opts.radixPoint), '.')
				.replace(new RegExp(opts.groupSeparator), '');
			return parseFloat(value);
        }
	});

**Comment by RobinHerbots** [comment]
@Alexchep , 

When using the numeric keyboard this is already the case.  
The changes done in onKeyDown doesn't flow through to the keypress event. 

You can modify the  ":" definition in the numeric.extensions.js

**Comment by Alexchep** [comment]
thank u  )!

**Comment by RobinHerbots** [comment]
@Alexchep , 

Did you manage to make the change?
