### ISSUE TITLE
Question: how to set caret position to click point

### ISSUE THREAD

**Issue by noherczeg** [RobinHerbots/Inputmask#1522]
I'd like to make it possible so that if someone clicks in an input the caret lands where the click position was. I also do not care about groups/separators, or anything.

Currently whatever I do if I click anywhere in inputs, the caret is always pushed back to the left.

Is this possible through configuration?

**Comment by RobinHerbots** [comment]
@noherczeg , 

Have a look at the positionCaretOnClick option

**Comment by noherczeg** [comment]
@RobinHerbots I tried that already, but didn't work. I'll create a plunker for it.

**Comment by noherczeg** [comment]
You were right, something is messed up elsewhere in **our** codebsae.

I'll provide an plunker anyway as an exaple how it looks like when it works: http://plnkr.co/edit/Uv5sGy8AFMbkTf3RDuku?p=preview

Thanks!

**Comment by noherczeg** [comment]
Turns out somehow I was right actually. When I reopened the plunker it stopped working again. @RobinHerbots could you please check the link I sent above?

**Comment by RobinHerbots** [comment]
I just tried your plunker and it worked as expected, ... can you be more
specific what is still wrong?  Maybe on  which os, browser

Op do 16 feb. 2017 om 17:33 schreef Norbert Csaba Herczeg <
notifications@github.com>:

**Comment by noherczeg** [comment]
@RobinHerbots Nothing wrong with the lib, it was a mistake that I made in the project I'm using it in! I edited my previous comment as well, so yes, it now has the proper working example, and the issue is fixed in the project as well.
