### ISSUE TITLE
Bug: Using backspace  when caret is not at the end messes up static placeholders

### ISSUE THREAD

**Issue by noherczeg** [RobinHerbots/Inputmask#1525]
Reproducible by:
- go to: http://plnkr.co/edit/l0WatHkqtaOY5lqmc5SB?p=preview
- type the following characters: 1, 2, 3, 4
- click between 3 and 4
- start spamming backspace

Result: the #-s will move out of their position.

**Comment by noherczeg** [comment]
It seems to be the case with the `DELETE` key as well, if you start to push it at the `0+n`'th position

**Comment by igorlopasovsky** [comment]
I'm having the same issue in the latest version 4.x

**Comment by RobinHerbots** [comment]
@noherczeg , @igorlopasovsky ,

I updated the plunker to use the latest Inputmask from github.  All seems ok now.  Can you verif and give feedback.

http://plnkr.co/edit/UeSG3PeZ5hveJKZNI3pR?p=preview

**Comment by igorlopasovsky** [comment]
thank you very much Robin, I will test it out

**Comment by felipe-zapata** [comment]
It seems it's not working properly with the Delete key. If the second character of (12##34) is Deleted all the mask moves left.

**Comment by RobinHerbots** [comment]
@felipe-zapata , 

Fixed in 4.0.0.0-beta.55

**Comment by felipe-zapata** [comment]
Thanks a lot!
