### ISSUE TITLE
This line of code returns an unexpected value when unmasking as number

### ISSUE THREAD

**Issue by andrea-spotsoftware** [RobinHerbots/Inputmask#1527]
https://github.com/RobinHerbots/Inputmask/blob/3.x/js/inputmask.js#L1853

The problem happens when you have a numeric mask with `unmaskAsNumber = true` and you want to retrieve the number 0 calling `.unmaskedvalue()`

In general: `0 || somethingElse = somethingElse` so there is a problem when `onUnmask` returns correctly 0, because the || operator between 0 and the original masked value (lets say '0,00') causes this line to return '0,00' that is a string.

see this fiddle: https://jsfiddle.net/ufppk1te/8/

**Comment by andrea-spotsoftware** [comment]
see fiddle https://jsfiddle.net/ufppk1te/7/

**Comment by RobinHerbots** [comment]
Hi @andrea-spotsoftware , 

Thx for reporting.  It is fixed, but I will submit the fix together with other fixes ;-) (soon)
