### ISSUE TITLE
Bug: numeric input mask with autogroup and suffix, first digit appears twice

### ISSUE THREAD

**Issue by ctebah** [RobinHerbots/Inputmask#1528]
Demo: https://jsfiddle.net/a94edxqt/2/

We have quite simple input form, integer numeric mask, autogroup with comma as group character and suffix part. When user position cursor after the first character of the suffix, and we have no other characters (digits) in the field, first character we type appears twice.

Suffix here in the demo has a space as a first character. It is just to make the problem more obvious, space or no space, behaves the same.

**Comment by RobinHerbots** [comment]
This seems fixed. (even on v3.x)
