### ISSUE TITLE
jQuery.inputmask and Firefox

### ISSUE THREAD

**Issue by somaghoshCU** [RobinHerbots/Inputmask#153]
I am having an issue to get the jQuery.inputmask to work in Firefox. It works fine in Safari.

My field is masked as below:

$('.somefield').inputmask("9999999999");

In Firefox, the mask is shifted to the right as value is entered. A valid value cannot be entered without manually deleting the underscores.

Please advise!

**Comment by RobinHerbots** [comment]
Hi,

Which version of the inputmask are you using?

best regards,

Robin

2013/1/8 somaghoshCU notifications@github.com

**Comment by somaghoshCU** [comment]
Hi Robin,

I am using Version: 1.2.5.

Thanks,
Soma

**Comment by somaghoshCU** [comment]
Hi Robin,

I have found the following error messages in the Firefox console:

Timestamp: 1/8/13 2:05:19 PM
Error: Error: useless setTimeout call (missing quotes around argument?)
Source File: http://localhost:8080/domain/template/js/jquery.inputmask.js
Line: 283

Hope that would provide some more insight.

Thanks,
Soma

**Comment by RobinHerbots** [comment]
Hi Soma, 

Just grab the latest 1.2.6 (or the latest of the 2.x branch  if you want to use optionals in your mask).  

This issue was already fixed ;-)

best regards, 

Robin

**Comment by somaghoshCU** [comment]
Hi Robin,

The below issue is not working fine.

However, I have another issue and if you can please advise. I have two optional masks as below:

$('.yearsinbus').inputmask("9[99]");

$('.realvalue').inputmask("9[9].99");

When I enter a partial amount, say 5 for the first one, it is not automatically clearing up the mask even if the clearMaskOnLostFocus is set to true by default.

Thanks much,

Soma

**Comment by RobinHerbots** [comment]
Hi Soma,

Which version are you using?  the 1.x or 2.x?

best regards,

Robin

2013/1/9 somaghoshCU notifications@github.com

**Comment by somaghoshCU** [comment]
Hi Robin,

I am now using 2.x.

Thanks,
Soma

**Comment by RobinHerbots** [comment]
Hi Soma, 

I fixed the issue for the clearoptionaltail. 
You check with the latest 2.x version.

best regards, 

Robin
