### ISSUE TITLE
Version 3.3.5 and closure-compiler

### ISSUE THREAD

**Issue by dan-developer** [RobinHerbots/Inputmask#1539]
It's not exactly an issue, I think, but in version 3.3.4 when trying to compress the javascript files the error is displayed:

> ERROR - Parse error. '}' expected
> static || null !== test.fn && void 0 !== testPos.input ? static && null !== test.fn && void 0 !== testPos.input && (static = !1,

This error is not triggered in version 3.3.5.

The tool used is "closure-compiler" v20170218. Using the Yii2 asset / compress

Thank you.

**Comment by RobinHerbots** [comment]
@AndersonDan , 

This is already fixed in the current on github, ... not released
