### ISSUE TITLE
numeric input issue

### ISSUE THREAD

**Issue by wildsurfer** [RobinHerbots/Inputmask#154]
When I use current version from the repo, simple code

$("input").inputmask("decimal");

does not allow to input any digits (but placeholders are visible). 

Old veriosn 1.2.4 works just perfect

**Comment by RobinHerbots** [comment]
Hi windsurfer, 

Can you create an example on jsFiddle.   I tested with version 1.2.8 & 2.0.6 and on both version the decimal mask seems to work.  (besides the bugs already present before)

best regards, 

Robin

**Comment by wildsurfer** [comment]
http://jsfiddle.net/8TvjZ/1/

**Comment by djtyroon** [comment]
I have the same issue http://jsfiddle.net/KW4qn/61/

**Comment by RobinHerbots** [comment]
Hi wildsurfer, djtyroon, 

The issue is solved ;-)  

Be aware that there are 2 branches of the inputmask now.  The 1.x branch is the original inputmask and the 2.x branch adds optional masks. 

best regards

Robin

**Comment by wildsurfer** [comment]
Thanks!

**Comment by djtyroon** [comment]
Thanks

By the way Very nice script !
