### ISSUE TITLE
Demo site is not working

### ISSUE THREAD

**Issue by akram1905** [RobinHerbots/Inputmask#1543]
[Your Site](http://robinherbots.github.io/Inputmask/) has JS errors and not working.
I think it append after you applied Version: 3.3.5-144.

**Comment by RobinHerbots** [comment]
It is a problem with the bundle. I will fix it tomorrow.

Op do 16 mrt. 2017 22:08 schreef akram1905 <notifications@github.com>:

**Comment by RobinHerbots** [comment]
@akram1905 , 

Fixed
