### ISSUE TITLE
IE 8 problems with currency and jquery.inputmask.bundle.js

### ISSUE THREAD

**Issue by NurGuz** [RobinHerbots/Inputmask#1545]
Hi.

I have a problem with app in IE 8 and mask currency,

  isFinite(opts.digits)) {
                            var radixPosition = $.inArray(opts.radixPoint, processValue),  **rpb = $.inArray(opts.radixPoint, maskedValue);**

The error go into the code rpb = $.inArray(opts.radixPoint, maskedValue);. And the error is "Invalid operand to 'in': Object expected"

opts.radixPoint = ","
maskedValue = "120,00"

**Comment by RobinHerbots** [comment]
@NurGuz , 

Can you put this in a jsfiddle.

**Comment by NurGuz** [comment]
the error is in jquery.inputmask.bundle.js, in funcion onBeforeWrite.

**Comment by NurGuz** [comment]
u can try to edit the val of opts.radixPoint and maskedValue  in debugger moder and u will see this error

**Comment by NurGuz** [comment]
i think that the problem is that maskedValue not is an array, is a value "120,00"

**Comment by RobinHerbots** [comment]
@NurGuz , 

Yes but I need to know where the value 120,00 comes from.
What are the steps to reproduce.

```
Inputmask("currency", { radixPoint: "," }).mask(elem);
//what else

```

**Comment by NurGuz** [comment]
if i edit your code and write this, run

                          var radixPosition = $.inArray(opts.radixPoint, processValue);
                            var rpb;
                            try
                            {
                                rpb = $.inArray(opts.radixPoint, maskedValue);
                            }
                            catch (ex)
                            {
                                rpb = maskedValue.indexOf(opts.radixPoint);
                            }


The values that onBeforeWrite recive are:

opts.numericInput = false;
buffer = [1,2,0,,,0,0]

 onBeforeWrite: function (e, buffer, caretPos, opts)
...
var maskedValue = opts.numericInput ? buffer.slice().reverse().join("") : buffer.join("")
....

**Comment by RobinHerbots** [comment]
https://jsfiddle.net/u1x6a4Lu/2/

**Comment by NurGuz** [comment]
i use it for apply the mask

$(elem).inputmask("currency",
{
   groupSeparator: '.', radixPoint: ',', autoGroup: false, digitsOptional: true, prefix: '',
   showMaskOnHover: false, showMaskOnFocus: false
});

and elemen is and input of jqgrid
<INPUT name=dcNetFee class="editable inline-edit-cell ui-widget-content ui-corner-all" id=25020000A005_dcNetFee role=textbox style="WIDTH: 96%" type=text value=120.00 rowid="25020000A005">

**Comment by RobinHerbots** [comment]
@NurGuz , 

Can you have a try with the current.  I submitted a patch for ie8

**Comment by NurGuz** [comment]
Good!

**Comment by NurGuz** [comment]
Hi.

It's not okey. If you have 100,00 this is converter to 10000

**Comment by RobinHerbots** [comment]
@NurGuz , 

This case is also fixed now.
