### ISSUE TITLE
integer backspace bug when set maxLength attr.

### ISSUE THREAD

**Issue by vmurdiy** [RobinHerbots/Inputmask#1546]
Hi, check this bug.
https://jsfiddle.net/jk45qbtw/3/

I got this bug when set maxLength attr.

**Comment by dvpandianwipro** [comment]
This happens even with regex also
https://jsfiddle.net/jk45qbtw/6/

**Comment by RobinHerbots** [comment]
@vmurdiy , @dvpandianwipro , 

And it even happens with the simplest mask also.  https://jsfiddle.net/jk45qbtw/7/

I will have a look

**Comment by RobinHerbots** [comment]
@vmurdiy , @dvpandianwipro , 

Fixed!

**Comment by dvpandianwipro** [comment]
Thank you
