### ISSUE TITLE
Datetime with "." separator, month entry problem

### ISSUE THREAD

**Issue by newmangreen** [RobinHerbots/Inputmask#1548]
Hi,
I try to use following datetime format but month can't be entered, it holds at month digits by disallowing any key entry. After moving to year part, I can enter numbers again. But 2 digit month can't be entered.
(I used latest distribution version: 3.3.5-169, Browser: IE 11 and Chrome 56)

`
$(selector).inputmask('datetime', {
	mask: '1.2.y h:s:s',
	placeholder: '_'
});
`

Sample: 22.03.2017 14:45:50

**Comment by RobinHerbots** [comment]
@newmangreen , 

I will refactor the date.extensions soon, but meanwhile try with 

```
Inputmask('datetime', {
		    mask: '1.2.y h:s:s',
			placeholder: '_' ,
			separator: ".",
                        leapday: "29.02.",
			alias: "dd.mm.yyyy"
		}).mask("test4");
```

**Comment by newmangreen** [comment]
Thank you, it works.
