### ISSUE TITLE
Phone numbers in Android Chrome 56

### ISSUE THREAD

**Issue by fakofsky** [RobinHerbots/Inputmask#1549]
When i enter a phone number on the demo page, the pointer jumps. Appears on Android 7 Chrome 56 # @

**Comment by diegoagudo** [comment]
The new release 3.3.5-173 broke again in phone numbers in Android Chrome 56 and Samsung with Smart Keyboards.

**Comment by RobinHerbots** [comment]
@fakofsky , @diegoagudo , 

Retry with version 3.3.5-175

**Comment by diegoagudo** [comment]
For mask currency ou numeric keeping break

         $(el).inputmask("currency", {
                groupSeparator: '.',
                prefix: '',
                placeholder: '0,00',
                radixPoint: ',',
                rightAlign: false,
                numericInput: true,
                autoGroup: true
            });

**Comment by RobinHerbots** [comment]
@diegoagudo,

It is mostly due to the numericInput option.  But even when setting it to false it doesn't let you enter the radixpoint. (caret positioning)

But phone entry should be ok,

**Comment by RobinHerbots** [comment]
Remove Phone alias #1981
