### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by greerd** [RobinHerbots/Inputmask#155]
I am using a barcode scanner that changes "*" (asterisk) to "/J".  I can't change the barcode scanner and I need the inputmask. What can I do?

**Comment by RobinHerbots** [comment]
Hi greerd,

Can you give me the mask you are using?

So the barcode scanner replaces \* to 2 characters?  / and J  or does /J
represent one?  Isn't it \J?

best regards,

Robin

2013/1/17 greerd notifications@github.com
