### ISSUE TITLE
Multiple alternators

### ISSUE THREAD

**Issue by ivaninDarpatov** [RobinHerbots/Inputmask#1553]
Hey!

I've been trying to make a mask that uses more than one alternators sequentially like so:
mask: "(9)|(09)|(19)|(2f)"
where 'f' is a definition with a validator "[0-3]".
The point is to accept single digits, one-digit numbers with a zero in front and two-digit numbers under 24.

When the mask is applied like this, it takes every 2 digits, when the "(2f)" condition is in the front, it follows it. I was wondering if there is another way to use multiple alternators, since this one depends on the sequence.

Thanks

**Comment by RobinHerbots** [comment]
Hi @ivaninDarpatov , 

I need to verify  because it doesn't behave like expected.

**Comment by RobinHerbots** [comment]
@ivaninDarpatov , 

Working on it

**Comment by RobinHerbots** [comment]
@ivaninDarpatov , 

Can you have a try with the current on github.

**Comment by ivaninDarpatov** [comment]
Yes this will do the job, still there is one case which doesn't behave as expected.
If I try "([0]9)(19)|(2f)" instead of "(9)|(09)|(19)|(2f)", after typing '2'. the mask ignores the "[0-3]" validator for 'f', and accepts every digit entered. (same goes with "(0{0,1}9)(19)|(2f)")

**EDIT: 
The old one ("(9)|(09)|(19)|(2f)") also malfunctions when the last statement is followed by another symbol, like "(9)|(09)|(19)|(2f):"

**Comment by RobinHerbots** [comment]
@ivaninDarpatov , 

Thx for the feedback.  I will further investigate the cases you pointed out.

I am also thinking of changing the syntax a bit to allow 
(9|09|19|2f) as equivalent to (9)|(09)|(19)|(2f)  sounds like a good idea?

**Comment by ivaninDarpatov** [comment]
Sounds great, a bit more like the RexExp syntax.

**Comment by RobinHerbots** [comment]
@ivaninDarpatov , 

Exactly!

**Comment by madbmd** [comment]
Hello,
Expressions as follows : ^(.{1,35}(\\n|$)){0,4}$
does does not appear to be working properly. 
Even with the last update, the dot '.' with the alternators '()' is no longer supported.
My thanks in advance for your attention.

**Comment by RobinHerbots** [comment]
@madbmd , 

I created a new issue for it as you are talking about a regex mask. See #1620

**Comment by RobinHerbots** [comment]
@ivaninDarpatov , 

Current status: https://jsfiddle.net/vuL48jrk/11/

**Comment by RobinHerbots** [comment]
@ivaninDarpatov, 
And finally fixed!  
Many thx for reporting this issue!
