### ISSUE TITLE
suffix bug

### ISSUE THREAD

**Issue by marcelokohl** [RobinHerbots/Inputmask#1558]
I'm trying to use the suffix "years" and it's showing "yers". It removes the letter "a" from any word I try to use as a suffix.

  $('#cover-years').inputmask('decimal', {
    suffix:" years",
    rightAlign: false,
    onBeforeMask: function (value, opts) {
      return value;
    }
  });

**Comment by IvanZepeta** [comment]
Try something like this
I solved the same problem with this

$('#cover-years').inputmask('decimal', {
suffix:" years",
rightAlign: false,
definitions: {
 a: { validator: "" }
},
onBeforeMask: function (value, opts) {
return value;
}
});

**Comment by marcelokohl** [comment]
Thank you, this worked. 👍

**Comment by RobinHerbots** [comment]
@marcelokohl , @IvanZepeta , 

There was a regression due to some changes in the definitions, which causes this. 
This is now fixed so you can use the suffix years again without the workaround.
