### ISSUE TITLE
US datetime

### ISSUE THREAD

**Issue by weisborg** [RobinHerbots/Inputmask#1559]
There is a US version of datetime12 with date as mm/dd/yyyy, but a really long name.  There is no 24HR datetime for US though.  I just changed my datetime alias and placeholder to be mm/dd/yyyy.  The mask I left with 1/2/y which I guess works since mm/dd/yyyy inherits from dd/mm/yyyy which uses 1/2/y.  The way those are done is a little confusing, and I'm not sure how many layers of aliases are allowed.  Probably could have made the datetime12 US version just called datetime12US and make another similar to it called datetimeUS for the 24hr.

**Comment by RobinHerbots** [comment]
@weisborg , 

The new datetime implementation allows to specify an inputFormat
