### ISSUE TITLE
Alphanumeric is not working

### ISSUE THREAD

**Issue by bdalina54** [RobinHerbots/Inputmask#1564]
`<input data-inputmask="'rightAlign':'false','align':'left','alias': 'alphanumeric', 'digitsOptional': false, 'prefix': 'MI-', 'placeholder': ''" maxlength="50" type="text"  autocomplete="off" value="MI-"/>`

expected output

MI-S08JHD

if i removed the alias the prefix will not be enforce.

Alias

numeric - working
alphabetical - notworking in mine
alphanumeric - notworking in mine

$(selector).inputmask("MI-*******"); this works, but theres a limit of characters 

is there a better way 

$(selector).inputmask("MI-*{not set}"); 

:)

Yet thanks for this great work very helpful, @RobinHerbots

**Comment by RobinHerbots** [comment]
@bdalina54 , 

There is no alphabetical or alphanumeric alias.  

I suggest reading the readme.

Inputmask("MI-AAAAAA").mask(selector)

**Comment by bdalina54** [comment]
Thanks! 👍
