### ISSUE TITLE
Title casing special case "of"

### ISSUE THREAD

**Issue by levin-roski** [RobinHerbots/Inputmask#1565]
Hey there,

I want a general mask for many fields in a formular, which automatically manages title casing, but it should write a list of words lowercase. And remove double spacing or cases like ., ,. in user input. I tried and didn't manage to do that.

What I came up with is the mask:
```
Inputmask.extendDefinitions({
    's': {
        "validator": "[\(\)\.\+/ \*\,\:\_\°\-]",
        "cardinality": 1,
        'prevalidator': null,
        casing: "upper"
    },
    'A': {
        validator: "[A-Za-z\u0410-\u044F\u0401\u0451\u00C0-\u00FF\u00B5]",
        cardinality: 1,
        casing: "upper" //auto uppercasing
    },
    'a': {
        validator: "[A-Za-z\u0410-\u044F\u0401\u0451\u00C0-\u00FF\u00B5]",
        cardinality: 1,
        casing: "lower" //auto lowercase
    },
});

\'mask\': \'(A{1}a{*}s{1,3})|(9{+}s{1,3}){*}\', \'placeholder\': \'\', \'clearMaskOnLostFocus\': true:
```

And a function which I want to run, as the user blurs, which replaces chosen titled words (like "Of") with lowercased words (like "of). The function also replaces ,. ., and &nbsp;&nbsp;
It grabs the value of the field, replaces some chars and then I want to put it back into the element: $(el).val(newText); but this pasted value will be fixed by inputmask again and it's title case again.

That's why I did this:
`$("[data-inputmask]", afkatalog.view.katlist).on("focusin", function(event) {
	$(event.target).inputmask();
});
$("[data-inputmask]", afkatalog.view.katlist).on("blur", function(event) {
	$(event.target).inputmask('remove');
});`

But still the pasted val gets fixed.

Do you have a solution, or shouldn't I use an inputmask for that target?

Thanks!

**Comment by RobinHerbots** [comment]
@levin-roski, 

Maybe I can add a callback which allows a custom casing?

**Comment by levin-roski** [comment]
@RobinHerbots yes maybe it makes sense, how would you implement the functionality?

**Comment by RobinHerbots** [comment]
@levin-roski , 

I updated the casing option to allow a fn, which can implement custom behavior.  

casing: function(...) {
}

See readme.

**Comment by levin-roski** [comment]
@RobinHerbots 
first of all, thank you so much for implementing the feature. I can't figure out how to best use it for the given example. How would you replace "Of" with "of" with the function you built for the mask in my first post?

Thanks
Levin

**Comment by RobinHerbots** [comment]
@levin-roski ,

Grab the latest from github and try

```
		Inputmask({
			casing: function (elem, test, pos, vp) {
				var posBefore1 = vp[pos - 1],
					posBefore2 = vp[pos - 2];
				if (pos === 0 || posBefore1 && posBefore1.input === String.fromCharCode(Inputmask.keyCode.SPACE)) {
					elem = elem.toUpperCase();
				} else if (posBefore2 && posBefore2.input === String.fromCharCode(Inputmask.keyCode.SPACE) &&
					posBefore1 && posBefore1.input === "O" && /[f]/i.test(elem)) {
					elem = elem.toLowerCase();
					posBefore1.input = "o";
				} else {
					elem = elem.toLowerCase();
				}

				return elem;
			}
		}).mask("test3");
```

**Comment by levin-roski** [comment]
Hi @RobinHerbots thanks,
I already installed the latest version of Inputmask.

And pasted the code, that you gave me (title case of Inputmask didn't work, so I used the function inputmask) (.mask("test3") returned error function not found)

This is the code used:
`<input type="text" data-inputmask="\'mask\': \'A{*}\', \'placeholder\': \'\'" value="" placeholder="PLZ" class="form-control" name="plz" id="bla">`
```
$("[data-inputmask]", afkatalog.view.katlist).inputmask({
	casing: function (elem, test, pos, vp) {
		var posBefore1 = vp[pos - 1],
		posBefore2 = vp[pos - 2];
		if (pos === 0 || posBefore1 && posBefore1.input === String.fromCharCode(Inputmask.keyCode.SPACE)) {
			elem = elem.toUpperCase();
		} else if (posBefore2 && posBefore2.input === String.fromCharCode(Inputmask.keyCode.SPACE) &&
			posBefore1 && posBefore1.input === "O" && /[f]/i.test(elem)) {
			elem = elem.toLowerCase();
			posBefore1.input = "o";
		} else {
			elem = elem.toLowerCase();
		}

		return elem;
	}
});
```

This gives me errors:
![image](https://cloud.githubusercontent.com/assets/18506470/26520380/84f963a8-42d1-11e7-956a-aefea4fc8a00.png)

**Comment by RobinHerbots** [comment]
You need the latest version from GitHub to make it work

Op za 27 mei 2017 11:46 schreef LevinRoski <notifications@github.com>:
