### ISSUE TITLE
29 february of non leap-year

### ISSUE THREAD

**Issue by Erkin-M** [RobinHerbots/Inputmask#1567]
this is my input mask code

```
$(".datetime").inputmask('datetime', {
        mask: "1.2.y h:s",
        alias: "dd.mm.yyyy",
        placeholder: "DD.MM.YYYY hh:mm",
        separator: '.',
        hourFormat: "24"
    });
```

and in my client side is able to input date like this
**29.02.2011 12:31**

and in my controller datetime come as _DateTime.MinValue_ this give an error.
Any way to resolve this ?

[Fiddle](https://jsfiddle.net/s4j1su80/)

**Comment by RobinHerbots** [comment]
@soloinnet 
See updated https://jsfiddle.net/s4j1su80/1/

Add the leapday + take the latest from github

**Comment by Erkin-M** [comment]
updated, checked, work fine.
U best.
