### ISSUE TITLE
Method to check if field is validated

### ISSUE THREAD

**Issue by brunobg** [RobinHerbots/Inputmask#157]
I'm trying to integrate inputmask with https://github.com/Corollarium/validarium, but I'm not sure how to check if inputmask validated the field (i.e., all required characters were filled). Isn't there an easy way to do that? It seems that is what I want is onKeyValidation(), but with a method instead of a callback.

I suppose I should call isValid(), but it is not a trivial method to call. Any tips? Thanks.

**Comment by RobinHerbots** [comment]
Hi Bruno, 

Can't you use the oncomplete?

best regards, 

Robin

**Comment by brunobg** [comment]
Hi Robin,

I'd rather have some way to poll instead of using callbacks. Is there some way to call isComplete from the outside?

Thanks!

**Comment by RobinHerbots** [comment]
Hi Bruno,

No there isn't but I will add it.

best regards,

Robin

2013/1/22 brunobg notifications@github.com

**Comment by brunobg** [comment]
Thanks a lot!

**Comment by RobinHerbots** [comment]
Can you test with the latest version.  

   $('#blabla').inputmask('isComplete')

**Comment by brunobg** [comment]
I tested and it is almost ok. It works if the field is complete, but if any optional fields are presented it returns false. Example: mask is 99[9]. If the field contains 123, isComplete returns true, but if it contains 12, it returns false, even though it should be true. Am I doing something wrong? 

And thanks for the prompt help and patch!

**Comment by RobinHerbots** [comment]
I will have a look at it.

**Comment by RobinHerbots** [comment]
Hi Bruno,

I tested the 99[9] mask with branch 2.x and for me the isComplete is always correct.  Can you create a jsFiddle which shows the case.

best regards, 

Robin

**Comment by brunobg** [comment]
Hi, I tested now and it is working perfectly. Thanks a lot for your help!

**Comment by brunobg** [comment]
Hi Robin! Sorry to reopen this, but there is something odd going on. I made a small example for you to test: http://jsfiddle.net/QRGpA/1/

If I fill the entire field with a valid input, then type backspace, there is an error. I also get an error after the 5th digit on the second part of the string. Can I bother you once again to check what is going on? Thanks!

**Comment by RobinHerbots** [comment]
Hi Bruno,

No problem at all.  

I think I know what is happening.  

Every optional part is seen as a block.  What I mean  say mask 999[99]  123 = complete  1234 = incomplete 12345 = complete.

I will test the above optional mask for when it triggers complete and incomplete and verify if it is correct according what I describe above.  

Maybe this is not the behavior you expected?

best regards, 

Robin

**Comment by RobinHerbots** [comment]
Hi Bruno, 

I fixed the strange behavior for the 5th digit when entereing the mask.  The jsFiddle works now correct according my implementation but is not what you expected it tobe.

Best regards, 

Robin

**Comment by brunobg** [comment]
Ah, I see. what you describe is exactly the behavior I am getting. It makes complete sense.

So I suppose I can't have something like "a number from 5 to 8 digits", right? Something like 99999[9][9][9] won't work, and there is no way to know if 99999[999] is incomplete because the obligatory part is incomplete or because the optional part is incomplete. Or is there a way to tell these cases apart?

**Comment by RobinHerbots** [comment]
for 99999[999]   12345 = complete 12345123 = complete

maybe the callback

 onKeyValidation: $.noop, //executes on every key-press with the result of
isValid

can help

You keep track once you recieve complete and all consequent valid
keystrokes you consider as complete.

 99999[9][9][9]  should work    12345 complete 123451 complete  ,...

what you need is a mask like this 9{5,8}  which would mean 5 to 8 numbers,
...or something like repeatable maskparts, but that is not possible for the
moment.

2013/1/29 brunobg notifications@github.com

**Comment by brunobg** [comment]
Thanks Robin! I found another way around: I use a regexp to help validate the input, in addition to isComplete. It is a bit extra work, but it works nicely to complement the information I can get from inputmask.
May I suggest for a future release to provide information of each block? Something similar to a regex match with grouping parentheses. It would be wonderful.
Thanks a lot for all your help! You're great :)

**Comment by alexdresko** [comment]
I think it would be acceptable if isComplete returned true if at least one block (including the non-optional block) is satisfied. I agree the x{y,z} idea would be useful as well, but I think those are two separate issues. Further, addressing isComplete as I've suggested would allow similar functionality as x{y,z} via [9][9][9].... (which doesn't currently work).

**Comment by RobinHerbots** [comment]
@alexdresko , 

I will have a look at the  [9][9][9].... functionality.  

Robin

**Comment by RobinHerbots** [comment]
@alexdresko, 

I just tested with this mask 9[9][9][9]

and the complete get triggered on every opional part. 

1 => complete
12 => complete
123 => complete
1234 => complete
