### ISSUE TITLE
Error when bundling inputmask with numeric extension

### ISSUE THREAD

**Issue by Alex-Sokolov** [RobinHerbots/Inputmask#1570]
Update Inputmask to 3.3.5

After update fix aliases paths in webpack config:
```js
alias: {
  'inputmask': 'inputmask/dist/inputmask/inputmask.js',
  'inputmask.dependencyLib': 'inputmask/dist/inputmask/dependencyLibs/inputmask.dependencyLib.js'
}
```

Bundling with webpack finished with error:
```
ERROR in ./app/assets/javascripts/plugins/inputmask.js
Module not found: Error: Can't resolve 'inputmask/dist/inputmask/inputmask.numeric.extensions.js' in 'C:\WORKGit\Project\app\assets\javascripts\plugins'
```

Don't know why it start searching after update in same folder instead of node_modules

How importing plugin with extension (file contents of /app/assets/javascripts/plugins/inputmask.js):
```
import Inputmask from 'inputmask';
import 'inputmask/dist/inputmask/inputmask.numeric.extensions.js';

export default Inputmask;
```

Can you tell what I'm missing?

**Comment by RobinHerbots** [comment]
@Alex-Sokolov , 

Drop the aliases.

Only adding the below should do.

import Inputmask from "inputmask/dist/inputmask/inputmask.numeric.extensions";

**Comment by Alex-Sokolov** [comment]
Thanks! With you suggestion bundle finished without errors.

But how I need to include inputmask only with few extensions now? Will be documentation update about that?

**Comment by RobinHerbots** [comment]
@Alex-Sokolov , 

Yes I need to update the documentation for it, ....  (you aren't in the mood for it?  ;-)  )

```
import "inputmask/dist/inputmask/inputmask.numeric.extensions";
import "inputmask/dist/inputmask/inputmask.date.extensions";
import Inputmask from "inputmask/dist/inputmask/inputmask";
```
or to load all 
``` 
import Inputmask from "inputmask";
```

**Comment by iamgbayer** [comment]
I'm sorry for reopen the issue, but i have a same problem and using version **3.3.6**, using import,

```js
import Inputmask from 'inputmask';
```

same message from webpack
```
ERROR in ./~/inputmask/index.js
Module not found: Error: Can't resolve './dist/inputmask/inputmask.date.extensions' in '/project/node_modules/inputmask'
```

**Comment by RobinHerbots** [comment]
I will verify the webpack setup tomorrow

**Comment by RobinHerbots** [comment]
@guuibayer , 

Strange, tested the same in a project of mine and it works without problem.

so you did 
npm i inputmask --save-dev
in your js
import Inputmask from "inputmask";

Did you add something specific in the webpack config?

**Comment by andrea-spotsoftware** [comment]
@RobinHerbots can you provide an example of webpack configuration? 
I have a similar issue:

when i try to import the library like this: 
`import Inputmask from "inputmask/dist/inputmask/inputmask.numeric.extensions"; ` 
I get this error when i try to create an Inputmask (using it as a constructor):
`TypeError: inputmask_numeric_extensions_1.default is not a constructor`.


If i import like this:
`import * as Inputmask from "inputmask/dist/inputmask/inputmask.numeric.extensions"; ` 
everything is working fine.

I think it's something about webpack configuration.

**Comment by Zoopme** [comment]
> 
> 
> @Alex-Sokolov ,
> 
> Yes I need to update the documentation for it, .... (you aren't in the mood for it? ;-) )
> 
> ```
> import "inputmask/dist/inputmask/inputmask.numeric.extensions";
> import "inputmask/dist/inputmask/inputmask.date.extensions";
> import Inputmask from "inputmask/dist/inputmask/inputmask";
> ```
> 
> or to load all
> 
> ```
> import Inputmask from "inputmask";
> ```

Hi @RobinHerbots ,

Where the documentation says `import "inputmask/lib/inputmask.numeric.extensions";`, could you by any chance update the path so it does not throw an error when compiling with Webpack ?

**Comment by RobinHerbots** [comment]
@Zoopme , 

You are looking at the documentaion for version 5.0 which isn't released yet.  Anyway I updated the readme to reflect the correct path for version 5

**Comment by Zoopme** [comment]
> 
> 
> @Zoopme ,
> 
> You are looking at the documentaion for version 5.0 which isn't released yet. Anyway I updated the readme to reflect the correct path for version 5

Thanks @RobinHerbots. I did not notice the version since version 5 opens by default on the Github page.

**Comment by RobinHerbots** [comment]
@Zoopme , 

Maybe I need to change that
