### ISSUE TITLE
Mobile phone code update needed for Malaysia

### ISSUE THREAD

**Issue by jnaubry** [RobinHerbots/Inputmask#1571]
Just a short notice regarding MY mobile phone codes, currently the mask is as follow:
{ "mask": "+60-##-###-####", "cc": "MY", "cd": "Malaysia ", "desc_en": "mobile", "name_ru": "Малайзия ", "desc_ru": "мобильные" },

But according to one of my customer who leaves in Malaysia (and an article published [here](http://www.malaysianwireless.com/2010/11/11-digit-mobile-numbers-malaysia/)), new mobile phone numbers are formatted on 11-digit.

Hope this helps.

**Comment by RobinHerbots** [comment]
@jnaubry , 

Thx, I updated the phone.js
