### ISSUE TITLE
Prevent radix point to show when typing amount but keep decimals mandatory

### ISSUE THREAD

**Issue by stephsavoie** [RobinHerbots/Inputmask#1574]
Two decimals are mandatory every situations here so I'm using 'digitsOptional: false' to let the plugin fills decimal values with zeros (when needed). 

Example of data typed in input field and actual given output :
```
2 => 2,00
2,1 => 2,10
2,13 => 2,13
,13 = 0,13
```

But the option 'digitsOptional: false' brings me an issue where the radix point is appearing on the first keystroke by the user.    I successfully prevented radix point from showing on focus (showMaskOnFocus: false) and on hover (showMaskOnHover: false) but that's not enough.   I really need to prevent the radix point from showing UNTIL the user himself presses the radix point . 

'digitsOptional: true' works well for that specific case as it does not show the radix point on keystroke until the user enters it but that leaves the input field incomplete after input focus is lost because of the decimal not filled correctly
 
Here's my current config that works well in every other situations :
```
            let defaultOptions = {
                alias             : 'decimal',
                removeMaskOnSubmit: false,
                groupSeparator    : ' ',
                autoUnmask        : true,
                unmaskAsNumber    : true,
                digitsOptional    : false,
                autoGroup         : true,
                allowMinus        : false,
                allowPlus         : false,
                showMaskOnHover   : false,
                showMaskOnFocus   : false,
                integerDigits     : 6, 
                digits            : 2,
                prefix            : '',
                radixPoint        : (_getLangueCourante() === 'fr' ? ',' : '.')
            };
```

Is there a way to force decimals after leaving the input field AND do not show the radix point UNTIL the user pressed the radix himself?

Great plugin by the way.  Thanks!

EDIT : I also tried alias 'numeric' but it does the same thing.

**Comment by RobinHerbots** [comment]
@stephsavoie , 

No it is not implemented, by default, ... it will need an extra option to allow it.  enforceDigitsOnBlur ??

**Comment by stephsavoie** [comment]
@RobinHerbots   ...so the new option  "enforceDigitsOnBlur" would be similar to "DigitsOptional: false"  except that the new option would prevent the radix from showing until the user presses it, right?

**Comment by RobinHerbots** [comment]
Yep

Op ma 24 apr. 2017 15:14 schreef stephsavoie <notifications@github.com>:

**Comment by stephsavoie** [comment]
@RobinHerbots      

I just seen in your doc  that you added this new option few weeks earlier.  I tried it today on version 3.3.7 here and it works flawlessly.    Great job!

Many thanks for your help.

**Comment by RobinHerbots** [comment]
@stephsavoie, 

Sorry that I didn't notify you that I implemented it.

**Comment by stephsavoie** [comment]
@RobinHerbots,  no worries.
