### ISSUE TITLE
Wrong initial cursor position with Numeric and Prefix

### ISSUE THREAD

**Issue by dbeja** [RobinHerbots/Inputmask#1578]
If I setup a mask with alias Numeric and define a prefix (eg. £), when I click on the input box the cursor goes behind the prefix.
After I start entering digits, the prefix goes to the right place, but on the first click it doesn't.
I can improve this slighthly If I set positionCaretOnClick to none, then when I click on the right of the prefix, it works fine, but if I click on the left of the prefix, the cursor goes to the left of the prefix.

Here is the fiddle: https://jsfiddle.net/6kk8zc0y/

**Comment by RobinHerbots** [comment]
@dbeja, 

Why are you closing the issue?

**Comment by dbeja** [comment]
Sorry, was cleaning up some issues on my account and probably closed this by mistake. My fault.

**Comment by RobinHerbots** [comment]
@dbeja , 

Ok, no problem.  Maybe it is time for a fix ;-)

**Comment by dbeja** [comment]
That's great!
I'm available for help on the code or on testing this issue if you need.

**Comment by RobinHerbots** [comment]
@dbeja , 

Have a look at https://jsfiddle.net/6kk8zc0y/1/

I will merge the changes back to the 3.x branch also

**Comment by dbeja** [comment]
That was quick :)

Ok, so I did some tests and it works better but I still found one case where it stays behind the prefix.

1. Click on left of prefix (and it jumps to the right place)
2. Click below the input (outside the input, when input loses focus)
3. Click again on left of prefix

**Comment by RobinHerbots** [comment]
@dbeja ,

The numeric alias is an exception due to the optional sign in front.  Anyway have another try.

**Comment by dbeja** [comment]
Yes, looks perfect to me!

**Comment by RobinHerbots** [comment]
great

**Comment by jamesearlywine** [comment]
I'm having this same issue, and am using version 4.0.0.  When tabbing into the input, the cursor goes to the left of the prefix (in my case, "$") initially, until keys are pressed.  Is there something I can do to make it go the right? 

I'm using these settings: 

WHOLE_DOLLAR_AMOUNT: new InputMask("integer", {
      clearMaskOnLostFocus: false,
      groupSeparator: ',',
      autoGroup: true,
      groupSize: 3,
      prefix: '$',
      unmaskAsNumber: true,
      autoUnmask: true
  }),
