### ISSUE TITLE
 reverse input and mask problem in dir="rtl" 

### ISSUE THREAD

**Issue by mfgh** [RobinHerbots/Inputmask#1579]
do you solve reverse input and mask problem in dir="rtl" option ?
i have problem in using dir="rtl" option ,it reverse  input and mask
please help me..

**Comment by RobinHerbots** [comment]
@mfgh , 

I internally already fixed the mask reversing, but how would be the expected input.  I know from right to left but how should I see the caret placement?  

I will try to submit the patch for you to test today.

**Comment by mfgh** [comment]
hi,i am waiting for your patch
my right to left mask option problem not solved...

thanks ...

Code Example :

 $(selector).inputmask({mask :  "*{*}-a{1,5}-a{1,5}"  ,
                                        tabThrough:true,
                                        greedy:false  ,
                                         definitions: {
                                          '*': {
                                            validator:
"[0-9A-Za-z!@#$%&'*+/=?^`{|}~\\u0600-\u06FF\s]",
                                            cardinality: 1
                                          }
                                        }
                                        rightAlign:true


                                     });

<input id="selector" name="selector" type="text" dir="rtl" />

**Comment by RobinHerbots** [comment]
@mfgh , 

The current version in github includes the patch.  Have a try and give your feedback.
