### ISSUE TITLE
Change Event Problems for Masked Input

### ISSUE THREAD

**Issue by newmangreen** [RobinHerbots/Inputmask#1583]
[https://jsfiddle.net/newmangreen/ot3dqmLy/](https://jsfiddle.net/newmangreen/ot3dqmLy/)

We have 2 problems related with change event fire (See related items in jsfiddle):
1. If masked input changes(auto-completing year) during change event, mask buffer remembers old one and fires change on submit at following part:
```
submitEvent: function(e) {
    undoValue !== getBuffer().join("") && $el.trigger("change"), ....
},
```
2. If no change made to inputs, during submit change event fired. I made a basic fix to prevent this so problem is solved as below. This problem is also mentioned in #1519 and #1392:
```
(undoValue !== undefined && undoValue !== getBuffer().join("")) && $el.trigger("change")
```

**Comment by RobinHerbots** [comment]
. Thx. Can you send a pull request?

**Comment by RobinHerbots** [comment]
@newmangreen , 

I included the change,

**Comment by newmangreen** [comment]
Hi Robin,
First item is still not fixed as I tested in jsFiddle. We have some masked fields that their onchange event submits form and second onchange event causes unwanted wrong submit.

**Comment by RobinHerbots** [comment]
@newmangreen , 

Oh I see. , it's the timeout in the blur event which changes the undovalue again.

**Comment by RobinHerbots** [comment]
@newmangreen , 

Also fixed now, thx for reporting the issue and insisting.

**Comment by newmangreen** [comment]
That's awesome, thank you.

As we tested in our app, we saw another problem. I added it as 3rd item in jsFiddle. The problem is that when input mask has initial value and not changed by user, during submit its change event fired (in our case, causing wrong submits).

**Comment by RobinHerbots** [comment]
@newmangreen , 

And also fixed ;-)
