### ISSUE TITLE
Escape Phrase

### ISSUE THREAD

**Issue by Wr4i7h** [RobinHerbots/Inputmask#1586]
Hi,

How do you go about escaping a phrase/segment in a define regex?
Is there an escape function available? Im using your plugin and want to escape the domain part of an email address which is read in from the db.

**Comment by RobinHerbots** [comment]
@Wr4i7h , 

Can you explain a bit more.  Does the domain part changes on input?  Or does it stays static?  When is it determined?  Do you see it as a prefill?

**Comment by Wr4i7h** [comment]
So the email address is defined by a regex.
I want the domain part to be static(the user cannot change it).

For example:
"*{1,20}@domain.com"
where @domain.com must be static. Currently the 'a' and 'd' chars are not being escaped.
I was wondering if I will have to implement this on my side or if there is a simpler way to do so.

**Comment by RobinHerbots** [comment]
@Wr4i7h , 

Try with 
```
	Inputmask({
			regex: "[a-za-zA-Z0-9!#$%&'*+/=?^_`{|}~-]+(?:\\.[a-zA-Z0-9!#$%&'*+/=?^_`{|}~-]+)*@domain.com"
		}).mask("test3");
```

**Comment by Wr4i7h** [comment]
Nothing happens(the mask doesnt appear) and no error is thrown either.

**Comment by RobinHerbots** [comment]
@Wr4i7h , 

Which version do you use?

**Comment by Wr4i7h** [comment]
@RobinHerbots 

* Version: 3.2.8-36.
I've upgraded to 3.3.5 and its working perfectly.
Thank you for the assistance, much appreciated.

**Comment by RobinHerbots** [comment]
@Wr4i7h , 

Even better would be upgrading to the latest on github.  Anyway 3.3.6 is coming soon
