### ISSUE TITLE
Typing 0 in Currency does not work

### ISSUE THREAD

**Issue by SeanDKendle** [RobinHerbots/Inputmask#1589]
If I have a text input with a number in it, set to currency mask, I cannot select all, then type 0 to set the value in the textbox to "0.00".  I have to hit backspace or delete to get "0.00".

Is this a known issue?

**Comment by RobinHerbots** [comment]
@SeanKendle , 

Which version do you use as I cannot reproduce

**Comment by SeanDKendle** [comment]
Sorry, I don't get any sort of email or notification when someone replies.  Did you fix this?

**Comment by SeanDKendle** [comment]
Version: 3.3.4-18

**Comment by SeanDKendle** [comment]
I see that there is a new version 4.x out, I'll try using that and report back in the next few days, very busy right now.
