### ISSUE TITLE
Regex is not working

### ISSUE THREAD

**Issue by statuty** [RobinHerbots/Inputmask#1592]
$(element).inputmask("Regex", {
                regex: "^[1-9][0-9]?$|^0$|^100$|^-$"
            });
![2017-05-16_1651](https://cloud.githubusercontent.com/assets/22051773/26109349/fd2394c0-3a57-11e7-9556-04623579ac9e.png)
but this input must be empty

**Comment by RobinHerbots** [comment]
@statuty , 

The regex alias is removed so it should be 

```
  $(element).inputmask({
            regex: "^[1-9][0-9]?$|^0$|^100$|^-$"
        });
```
Anyway, not all regex syntax is already supported.  But I will add all cases to support the above regex.

The below should do what you expected

```
Inputmask({
			regex: "^(0|[1-9][0-9]?|100|-)$",
			greedy: false
		}).mask("test3");
`` `

**Comment by statuty** [comment]
Thank you! ;)
