### ISSUE TITLE
Working with asp.net UpdatePanel

### ISSUE THREAD

**Issue by tdinpsp** [RobinHerbots/Inputmask#1593]
If an input with a mask is within an UpdatePanel and there is a callback then after the callback the input mask functionality is lost.

**Comment by RobinHerbots** [comment]
@tdinpsp , 

An updatepanel in asp.net replaces it's content.  You will need to reapply the inputmask. 
Have a look at http://stackoverflow.com/questions/9026496/running-script-after-update-panel-ajax-asp-net
