### ISSUE TITLE
Cursor jumps to end using separator on Android 6.0.1

### ISSUE THREAD

**Issue by bvmensvoort** [RobinHerbots/Inputmask#1595]
**Issue**
Cursor skips to end on Android when typing a number after a separator.
This is not expected.

**Example**
Using mask 99-99-9999, value: 12-21-1111
Try to replace 2's by 3's.

Value: 13|-1-111
When cursor is just before the first -, and you type a number, the cursor moves to the end.
Result: 13-31-1111|

**Details**
Doesn't happen on iOS and Desktop.
Android 6.0.1, jquery 1.10, Inputmask: 3.x
[JSFiddle](http://jsbin.com/weqegemixe/edit?html,js,output)

**Comment by RobinHerbots** [comment]
@BMarinos , 

This is fixed in the 4.x branch.  Maybe you can have a test.  These changes will be merged back into the 3.x version.

**Comment by bvmensvoort** [comment]
Issue is resolved in 4.x. Many thanks!
