### ISSUE TITLE
Masks ignore backtick (ASCII 192 characters)

### ISSUE THREAD

**Issue by mnewnham** [RobinHerbots/Inputmask#1599]
Using versions 3.3.0 thru 3.3.6
Platform Windows
Browser Chrome,IE,firefox

This trivial mask: 
````javascript
$(".letters-numbers").inputmask({
  definitions: {
	"*": {
	validator: "[A-z0-9]"
	},
    },
});	
````
Will validate correctly except for the ` (backtick) ASCII 192 character

I can add a keydown trap to clear the problem
````javascript
$(".letters-numbers").on('keydown',function(e){
    var keyCode = e.keyCode || e.which; 
   if (keyCode == 192)
      return false;
});
````

**Comment by RobinHerbots** [comment]
@mnewnham ,

Try the below in a browserconsole and you will know your answer.
```
/[A-z0-9]/.test("`") //true
/[A-Za-z0-9]/.test("`") //false
```

**Comment by mnewnham** [comment]
sorry, thanks
