### ISSUE TITLE
Add onchange function to be called when content changes.

### ISSUE THREAD

**Issue by pottmi** [RobinHerbots/Inputmask#16]
An onchange function that would be called each time the contents of the field is changed could be very useful.  

The function should return a boolean that indicates if the field is formatted properly.  If the function returns false then the keystroke should be rejected much like the keystrokes are rejected for not matching the pattern associated with the masks.

This could be used to allow much more complicated pattern matching such as detecting the nuances of dates.

**Comment by RobinHerbots** [comment]
This can be accomplished with the current implementation.  See examples in jquery.inputmask.extentions.js

**Comment by kevb** [comment]
I don't see an example of this in jquery.inputmask.extentions.js

I would also like to fire an event when the value is changed, as well as when the the field is 'complete'.

If I'm just missing it, can you give a line number. Thanks.

**Comment by RobinHerbots** [comment]
That's because we agreed to solve it another way.

The oncomplete is implemented, for the change on every change you can use
keypress, keydown, keyup events or so.

What do you want to accoimplish?

regards,

Robin

2011/11/30 Kevin Bennett <
reply@reply.github.com
