### ISSUE TITLE
Space to skip optional masks

### ISSUE THREAD

**Issue by brunobg** [RobinHerbots/Inputmask#160]
Hey Robin,

I thought that optional masks in the middle of the field were not working (say 9999[9]-9999), until I realized I had to type the next character after them ('-' in this case). It seems to me natural that a plain space ' ' should work as well. What do you think?

I tried to understand the code to send a patch, but it was not that easy :| I suppose it should be something in isValid(), but I'm not sure.

Thanks!

**Comment by RobinHerbots** [comment]
Hi Bruno, 

I don't know if a space should be natural to indicate you want to skip the optional.  What if the mask itself contains a space?  The current implementation is: type what you need and the mask changes accordingly (if possible).

For a mask like 999[99]99 it is impossible to detect.  But you should write it like 99999[99].

Best regards

Robin

**Comment by brunobg** [comment]
Got it. It doesn't make sense to read spaces by default, you are right. Is there any easy work around to support it in some cases, though? I did some informal tests here and space is what most people type.

**Comment by RobinHerbots** [comment]
Also see dicussion on https://github.com/RobinHerbots/jquery.inputmask/commit/40585abdcbcbacb84e249894f34910eec11562b3#commitcomment-2527148

**Comment by RobinHerbots** [comment]
Checkout the latest version in 2.x branch (skipOptionalPartCharacter)

By default i used the space

best regards
Robin
