### ISSUE TITLE
UX problem with email mask

### ISSUE THREAD

**Issue by Finesse** [RobinHerbots/Inputmask#1600]
Users (that are not computer experts) often face a user experience problem when they try to use an input with the email input mask. When a user finishes typing email part before `@`, he takes the mouse and tries to place the cursor after the `@` in the mask. When he does it, the cursor becomes placed before the `@` (where it was before) and the user tries to do it again and again. He doesn't know to click the `@` or the `→` button on his keyboard.

![demo](https://cloud.githubusercontent.com/assets/9006227/26440469/ca4c7430-416f-11e7-9c57-1dbe1cbc64eb.gif)

As a result, users ask me to remove email input mask and return a plain input field.

Is there a way to workaround this problem?

**Comment by RobinHerbots** [comment]
@FinesseRus , 

I will see if I can solve this in a general way.

**Comment by Finesse** [comment]
I didn't expect such quick response, thank you

**Comment by ka-seo** [comment]
@FinesseRus ,
How you made this mask email with placeholder?
Please, share the code :)

**Comment by Finesse** [comment]
@ka-seo, this way: [codepen.io/anon/pen/ZKNRvB](https://codepen.io/anon/pen/ZKNRvB?editors=1010). You can also just go to [robinherbots.github.io/Inputmask](http://robinherbots.github.io/Inputmask/) and click the Demo button.

**Comment by RobinHerbots** [comment]
@FinesseRus ,

Fixed

**Comment by Finesse** [comment]
@RobinHerbots You are great, man! Thank you very much, I didn't expect it.
