### ISSUE TITLE
Change in behavior of mask from 3.3.0 to 3.3.6

### ISSUE THREAD

**Issue by mnewnham** [RobinHerbots/Inputmask#1601]
This inputmask for a US date
````javascript
$(".ui-mask-basic-date").inputmask("m/d/y",{
	placeholder: "mm/dd/yyyy",
});
````
Works correctly  in 3.3.0, putting a placeholder in the input field, but in 3.3.6 it just puts 'm/d/Y' into the field. The mask cannot be typed over.

**Comment by RobinHerbots** [comment]
Hi @mnewnham , 

I should have followed the semantic versioning and bumped to version 4, ... but I didn't.

I removed the d,m,y definitions as they caused many confusion for some in regards with the available aliases for date.  So or you use some of the date aliases or put the definitions back in your code and run the same mask.
