### ISSUE TITLE
Suggestion to customize brazilian phone

### ISSUE THREAD

**Issue by drma-tech** [RobinHerbots/Inputmask#1602]
{"mask": "+55-##-9####-####","cc": "BR","cd":"Brazil" "desc_en": "", "name_ru":"Бразилия","desc_ru": "" },
{"mask": "+55-##-####-####","cc": "BR","cd":"Brazil","desc_en":"", "name_ru":"Бразилия","desc_ru":""},

I was trying to customize to our new reality of number formats (the official formats available do not serve perfectly), but I do not know how to do exactly.

The situation is as follows: When starting with 9, the structure must have 9 digits (include the 9). But in any other situation, it must have 8 digits. But when I type 9 in this position that I showed in the example, it is not dynamic and leaves the last digit hidden (even enabled for typing), and can confuse the user.

**Comment by lucasbibiano** [comment]
maybe this can help you, @dhiogoacioli:

```
  $(selector).inputmask({ mask: function () {
    return ['(99) 9999-9999', '(99) 99999-9999'];
  }})
```

**Comment by drma-tech** [comment]
Actually, I was thinking of something more dynamic. Example: as you type the beginning of the number, the mask automatically changes.

This dynamism works perfectly for the "55", because it is at the beginning of the mask. But it does not work for the "9" because it is in the middle of the mask.

**Comment by sirbaconjr** [comment]
You can get some ideas from #836 
Our phone numbers are really complicated.

**Comment by sirbaconjr** [comment]
Here is a working regex for all brazilians phones 
`(\+55 [0-9]{2} ((7[0|7|8|9])|([2|3|4|5][0-9])|([7|8|9][0-9]{2}))[0-9]{2}-[0-9]{4})`

Including:
0800 999 9999
0300 999 9999
0500 999 9999
0900 999 9999

**Comment by RobinHerbots** [comment]
Remove Phone alias #1981
