### ISSUE TITLE
Major Problem with PHONE masking code.

### ISSUE THREAD

**Issue by VagyokC4** [RobinHerbots/Inputmask#1605]
I was having major issues with the phone masking code.  I was able to reproduce on your demo.

![2017-06-02_11-07-53](https://cloud.githubusercontent.com/assets/253250/26738732/21106df2-4784-11e7-9e79-0d2832b768c8.gif)

**Comment by RobinHerbots** [comment]
@VagyokC4 , 

You mean that the unmasking is totally useless?

**Comment by VagyokC4** [comment]
@RobinHerbots  Yes.  The normal control seems to work well.  Its when I use the phone mode that I run into issues.  I have another issue but I haven't been able to isolate it correctly yet, so I haven't posted it, but it is with the phone control and appears on my production environment, while browsing with a mobile phone.  It's as if the mask does not work, and numbers get scrambled (for example: locally I can use 18005551212, but on mobile, I can only get 180, and the mask prevents any other input)

**Comment by RobinHerbots** [comment]
@VagyokC4 , 

I will enhance the unmasking for the phone mask.  For mobile I'm working on some part of it.  Follow up coming commits.

**Comment by RobinHerbots** [comment]
Remove Phone alias #1981
