### ISSUE TITLE
Hidden Mask

### ISSUE THREAD

**Issue by skushnarev** [RobinHerbots/Inputmask#1607]
Greetings.
It is possible to disable the visibility of the mask, but with the preservation of all the functionality. What would the user not see the mask, but it worked and put the delimiter characters.

> Приветствую.
Есть возможность отключения видимости маски, но с сохранением всего функционала. Что бы пользователь не видел маску, но она работала и ставила символы разделители.

**Comment by RobinHerbots** [comment]
@skushnarev , 

The the jitMasking option.  See readme

**Comment by skushnarev** [comment]
@RobinHerbots 
Thank you! This is exactly what I needed!
