### ISSUE TITLE
How can i make it to allow only alphanumaric values

### ISSUE THREAD

**Issue by mahivitsit** [RobinHerbots/Inputmask#1609]
`$("#alphanumeric").inputmask({mask: "_CRAAAAAAAAA"});`

in the a bow _CR is constant, next nine charterers can be alphanumeric.

**Comment by RobinHerbots** [comment]
```
$("#alphanumeric").inputmask("_CR*{9}");
```

**Comment by RobinHerbots** [comment]
@mahivitsit , 

the * definition accepts all, ... why did I change that?  => fixed

**Comment by mahivitsit** [comment]
Thanks for your response, it is working 💯
