### ISSUE TITLE
Major issue with regex

### ISSUE THREAD

**Issue by MrAsterisco** [RobinHerbots/Inputmask#1611]
Consider the following code to apply a date mask (Italian format: DD/MM/YYYY) to a text field:

`this.inputmask("Regex", {regex: "^(([1-2][0-9])|3[0-1]|((0{1})?[1-9]))\/(((0{1})?[1-9])|(1[0-2]))\/20[0-9]{2}$" });`

This statement used to work just fine in version 3.3.5, while it's broken in 3.3.6.

Reading other issues, I have understood that you removed the "Regex" shorthand, but even using the "new" syntax that I found in #1592, the regex is not recognised anymore and does not work as expected.

_Just a comment: if you're making breaking changes in the API, you should never make them in a patch release. There's an [interesting reading about semantic versioning](https://www.jvandemo.com/a-simple-guide-to-semantic-versioning/) that I would suggest on this matter._

Thank you!

**Comment by RobinHerbots** [comment]
@MrAsterisco , 

I'm still advancing regex support within the inputmask.

Concerning the semver.  I know about it and already have read the doc.  The breaking change is discutable.  The only change is that I removed the regex alias extension.  When you load it back it will work as before.  There are not really breaking changes in the inputmask itself.  Maybe I should have  waited for a release until the new regex support is on par with the previous.

**Comment by RobinHerbots** [comment]
@MrAsterisco , 

But you are right, ... I will put the regex extension back until the internal regex support is far enough

**Comment by RobinHerbots** [comment]
@MrAsterisco ,

The Regex alias is back in version 3.3.7.  and dropped in the 4.x branch

**Comment by MrAsterisco** [comment]
Thank you very much, I'm upgrading my projects to version 3.3.7.
