### ISSUE TITLE
Bower failing for jquery.inputmask 3.1.57

### ISSUE THREAD

**Issue by aarestad** [RobinHerbots/Inputmask#1613]
Hey - we are seeing the following error when trying to resolve this plugin:

`No versions found in https://github.com/RobinHerbots/jquery.inputmask.git`

I see https://github.com/RobinHerbots/jquery.inputmask is pretty much empty - is there some sort of migration going on?

**Comment by aarestad** [comment]
I also tried to update the version to "~3.3.7-35" and still got the same failure.

**Comment by RobinHerbots** [comment]
@aarestad , 

Try https://github.com/RobinHerbots/inputmask.git

I renamed the repo some time ago, but by now reclaiming the jquery.inputmask the alias from jquery.inputmask to the newer inputmask repo in github is gone.

**Comment by aarestad** [comment]
That seemed to do it - thank you!
