### ISSUE TITLE
Bower not working now

### ISSUE THREAD

**Issue by RazumO** [RobinHerbots/Inputmask#1614]
in bower.json 
   "jquery.inputmask": "^3.1.61",

Console output:
   No versions found in https://github.com/RobinHerbots/jquery.inputmask.git

**Comment by ihnyp** [comment]
I have the same issue.

Console output:
bower jquery.inputmask#3.3.4           ENORESTARGET No tag found that was able to satisfy 3.3.4

**Comment by RobinHerbots** [comment]
@RazumO , @ihnyp , 

The bower resolving should work again.  Can you have a try.

**Comment by RazumO** [comment]
Works now. Thanks. @RobinHerbots

**Comment by mrkava** [comment]
Works, thank you

**Comment by ihnyp** [comment]
Works. 👍
