### ISSUE TITLE
jquery.inputmask alias to inputmask

### ISSUE THREAD

**Issue by RobinHerbots** [RobinHerbots/Inputmask#1615]
@cebe,

Renaming and renaming again restored the alias ;-)  

bower and npm  resolving seems to work again. 

You are great !!!!

**Comment by cebe** [comment]
haha, thanks :)

**Comment by samdark** [comment]
Would it stay like that forever? Is the alias permanent?

**Comment by RobinHerbots** [comment]
@samdark,
Yes unless GitHub decides otherwise. 😂

**Comment by petrabarus** [comment]
@RobinHerbots Thanks a lot! I really appreciate this!
