### ISSUE TITLE
Usage with rollup.js

### ISSUE THREAD

**Issue by andrea-spotsoftware** [RobinHerbots/Inputmask#1618]
Any chance to use this module with [rollup.js](https://rollupjs.org/)?
I tried adding rollup plugins that should help to load npm packages like [guide](https://rollupjs.org/#using-rollup-with-npm) suggests, but inputmask is not carried in my final bundle.
Anyone with the same experience?

**Comment by RobinHerbots** [comment]
@andrea-spotsoftware , 

I think it is better that you ask this question to rollup.js, maybe they can hint you.

**Comment by yogeshgadge** [comment]
Not sure who should provide receipe. inputmask does have that `dependencyLib` thing which I say is little different.
