### ISSUE TITLE
Want to perform operation inside the mask

### ISSUE THREAD

**Issue by ashish1354** [RobinHerbots/Inputmask#1626]
Hi,
Just want to create a mask for show result of multiplication.
I use this:-  $("#my_fx").inputmask("(25) x 9{1,} = ");
And i want result like:-
(25) x 2 = 50
(25) x 3 = 75
(25) is static and I will be able to change only second operand (2,3 etc) and want result automatically after '='.
How can I do this ?

**Comment by RobinHerbots** [comment]
@ashish1354 , 

First make the mask so it can accept the whole mask including the = 50 (for example)
Then you can implement the postvalidation which does the calculation and refreshed the value.
Have a look at the numeric extensions to see the postvalidation in action.

Create a jsfiddle with the mask,, that will make it easier to discuss when you have issues.
