### ISSUE TITLE
Letters, spaces and -

### ISSUE THREAD

**Issue by SparfiEA** [RobinHerbots/Inputmask#1627]
Hi everyone, 
I'm trying to add a mask on my input, but after several try i can't get it,  I'm trying to get an input where i can only type letters, have spaces , and this special char (-).
I just begun with those inputmasks,
Thanks for the help ;

For the moment i tried this : 
 $("#input").inputmask({
        definitions: {
            'A': {
                validator: "[a-zA-Z-_-\s]",
                }
            }
                });

**Comment by SparfiEA** [comment]
For the persons who would have the same issue;
i solved it by doing : 
               $("#input").inputmask("Regex", { regex: "[a-zA-Z- ]*" });
👍

**Comment by RobinHerbots** [comment]
@Sparfiax , 

In future versions you will need to use $("#input").inputmask({ regex: "[a-zA-Z- ]*" });  as the Regex alias is removed.
