### ISSUE TITLE
Mask to limit date field (dd/mm/yyyy)

### ISSUE THREAD

**Issue by Lyzzi** [RobinHerbots/Inputmask#1628]
Hi !
I did a mask for the format of a date as dd/mm/yyyy, and I need help to limit each field (ex : dd<31 ; mm<12; 1950<yyyy<2017).
I did it with a pattern : "^(0[1-9]|[12][0-9]|3[01])[- /.](0[1-9]|1[012])[- /.](19|20)\d\d$"
But I would like a mask in order to the user can't write a wrong date and don't have only an error message.
Thank you !

This is my code for now : 
**MAIN.JS :** 
requirejs(["node_modules/inputmask/dist/inputmask/inputmask"], function(inputmask){
    function tryMask() {
        inputmask({mask: "99/99/9999"}).mask(document.getElementsByName('dateDeQuoi'));
    }
    document.getElementsByName('dateDeQuoi')[0].addEventListener('input', tryMask);
});

**Comment by RobinHerbots** [comment]
@Lyzzi , 

Maybe you can start from the date alias and specify the yearrange option

```
requirejs(["node_modules/inputmask/dist/inputmask/inputmask.date.extensions"], function(inputmask){
function tryMask() {
inputmask("dd/mm/yyyy", { 
	yearrange: {
				minyear: 1950,
				maxyear: 2017
			}
}).mask(document.getElementsByName('dateDeQuoi'));
}
document.getElementsByName('dateDeQuoi')[0].addEventListener('input', tryMask);
});
```

**Comment by Lyzzi** [comment]
it works !

Thank you ! :D
