### ISSUE TITLE
Create better support for nuget

### ISSUE THREAD

**Issue by RobinHerbots** [RobinHerbots/Inputmask#163]
Optimize packages and automate builds with myget.  (to investigate any comments guides are welcome)

**Comment by williamthiago** [comment]
RobinHerbots, 
I keep sending manually to nuget, sometimes late, but I trying to keep updated
anytime, I grant access to account if desired

**Comment by RobinHerbots** [comment]
Hi William,

Wow, I can not expect you todo this every time.
Through myget you can automate this process but I haven't got the time to
investigate this further.

You may grant access to the account, ... once I handle issue 163 I can
start using it.

thank you,

Robin

2013/2/20 William Thiago notifications@github.com

**Comment by williamthiago** [comment]
Create an account on http://nuget.org/account/Register, then I will be able
to find your user and attach as owner.

[]s
William Thiago
65 9987-5138

**Comment by RobinHerbots** [comment]
Done

2013/2/20 William Thiago notifications@github.com

> Create an account on http://nuget.org/account/Register, then I will be
> able
> to find your user and attach as owner.
> 
> []s
> William Thiago
> 65 9987-5138
>

**Comment by RobinHerbots** [comment]
I will include the nuget building in the build script

**Comment by jmackay** [comment]
Robin, first let me say excellent job!

This is a great tool and has helped us out a lot.

I was having an issue with the leading 0 and notice it was fixed the other day, how often do you update the nuget packages?

**Comment by williamthiago** [comment]
jmackay,

I`m updating when Robin change version on jquery.inputmask.js (current
2.1.1c), but, Im ignoring minor changes (letters on version).
Next release will be updated when Robin change to 2.1.2.

I can change this behavior, what do you think about Robin?

**Comment by RobinHerbots** [comment]
I just added a new nuget package in the dist folder.  (William can you put this on nuget.  Thx)

The current setup isn't ideal as the 2.x and 1.x branches are both dev branches,... and so for the moment also the nuget packages.

I suggest to only push to nuget as I put a new nuget package in the dist folder.  I gonna create new dev branches for current dev.  And push to the 1.x and 2.x when there are enough changes and the code is stable again.

**Comment by RobinHerbots** [comment]
I already added the current on nuget .

Changed the content a bit to include the minified files, ... also changed the paths a bit, ...

**Comment by RobinHerbots** [comment]
@williamthiago 
I will put the updates on nuget in the future.  Thx for your help on this.

Robin

**Comment by williamthiago** [comment]
Its ok :D

If you need my help, just shout "fire!"

[]s
William Thiago
65 9987-5138

**Comment by RobinHerbots** [comment]
nuget building in the buildscript.

Is there a nuget builder for Linux?

**Comment by williamthiago** [comment]
I dont know =/

I find this project.. maybe....
https://github.com/monoman/NugetCracker/wiki/NugetCracker-Project

**Comment by RobinHerbots** [comment]
Adding the nuget building in the buildscript is sufficient.  There is no need for myGet which can automate the building.  Seems that the nuget.exe also works with mono.

Maybe I need to adapt the package to include mono as a target if needed.

**Comment by williamthiago** [comment]
Robin,
I saw that you already comfortable with deploy to nuget. You can remove my user from owners list if desired, using this link https://nuget.org/packages/jQuery.InputMask/2.1.12/ManagePackageOwners

good job ;)

**Comment by RobinHerbots** [comment]
@williamthiago , ok done

**Comment by WaltDaniels** [comment]
Robin, how often is the NuGet version refreshed?  Are we better off pulling directly from github, or is there something that can be done to automate the NuGet repo?

Thanks for a great plugin!

**Comment by RobinHerbots** [comment]
Hi Walt,

On github you always find the latest version, the new features, bugfixes,
... instable code sometimes.

Nuget is updated when I feel it is necessary.  When I think the plugin is
stable  ;-)  So it depends what you want

Thx for the compliment.  The plugin is the result of the feedback and ideas
of the cummunity!!

I still need to implement the e-mail mask, ... but I only will do it when
the inputmask is ready todo the e-mail mask the right way, ... something
like   _{1,20}@_{1,20}.*{3}  a mask with non-greedy repeatable sub-parts.
 The idea and first changes in the plugin are already present, .... but
there are too many other issues to continue on this as this will probably
introduce new issues ;-)

2013/4/2 Walt Daniels notifications@github.com

**Comment by sompylasar** [comment]
For email masks and the like, maybe use an alternate regex engine to be able to run partial regex matches and control the matching process? One of these is https://github.com/eriksank/alt-regex-engine but you may find a better alternative.
