### ISSUE TITLE
JavaScript error on Android device

### ISSUE THREAD

**Issue by ydimitrof** [RobinHerbots/Inputmask#1632]
Hey @RobinHerbots , I am seeing a JavaScript error when I am using an Android device ( currently a Pixel emulator ). Using the latest version of your library at the moment of typing this. Here is a screenshot.
![screen shot 2017-06-26 at 5 56 42 pm](https://user-images.githubusercontent.com/7790420/27546374-4659601c-5a9b-11e7-8320-2d0fec683fbd.png)

**Comment by RobinHerbots** [comment]
@BrainClot , 

Ok, thx for reporting, I will add an extra check on event.  It will be fixed on the next commit on 4.x.
