### ISSUE TITLE
importDataAttributes option

### ISSUE THREAD

**Issue by gabrielchiquini** [RobinHerbots/Inputmask#1633]
I have an input declared with `<input 'data-inputmask="9999999.99"'>` and when I try to replace mask with javascript `$('#id').inputmask('9999999-99.9999.9.99.9999', {"clearIncomplete": true })` , the mask continue being 9999999.99. Not even removing the mask solved the problem, so I added this line `if(!(userOptions && JSON.stringify(userOptions) === JSON.stringify({}))) attrOptions = '';` after the line 172 on inputmask.js.
It ignore the data attribute when it's passed options by javascript but I think it's not the best way to do this.

**Comment by RobinHerbots** [comment]
@gabrielchiquini , 

The data-attribute get the highest priority, this will have to change to allow your scenario and seems like more logical.

I will make the change.

**Comment by RobinHerbots** [comment]
@gabrielchiquini, 

Did some further thinking, maybe this isn't a good idea.  The data attributes are specific for one input and should hold priority.  Maybe a better option is to make the attribute import optional.  When you pass the option importDataAttributes: false to skip the imports.  Also if you do not  use data-attributes you can set the default to false and speed up things as a bonus.

What do you think?

**Comment by gabrielchiquini** [comment]
You're right, creating the option is the best idea.

**Comment by gabrielchiquini** [comment]
Thanks @RobinHerbots
