### ISSUE TITLE
ColorMask is not inserted into DOM

### ISSUE THREAD

**Issue by ydimitrof** [RobinHerbots/Inputmask#1635]
I have tried setting the colorMask: true but there's no modification of the DOM as I've seen in a 3.* version of the library. This directly affects the android hack since it relies on that mask element to function properly. The code I'm using to initialize the library is this:
```js
new Inputmask(
    {
        mask: "99/99/9999",
        placeholder: 'MM/DD/YYYY',
        showMaskOnHover: false,
        oncomplete: function () {
            $('.mask-input').parent().addClass('label-minimized');
        },
        onincomplete: function () {
            $('.mask-input').parent().removeClass('label-minimized');
        },
        clearIncomplete: true,
        insertMode: false,
        androidHack: "rtfm",
        colorMask: true
    }
).mask($('.mask-input'));
```  
In this example I am simply trying to see the div that masks the input.
The resulted HTML when the input is clicked is this:
![screen shot 2017-06-29 at 2 29 28 pm](https://user-images.githubusercontent.com/7790420/27685683-f2c127de-5cd7-11e7-8ef6-ff0757fe8ee6.png)
All this is tested on `Version: 4.0.1-3`

**Comment by RobinHerbots** [comment]
@BrainClot ,

The last element in the body should contain the div.

**Comment by ydimitrof** [comment]
@RobinHerbots I facepalmed myself so hard. Sorry for the issue, keep up the good work!

**Comment by ydimitrof** [comment]
@RobinHerbots found a typo in the dev file on line 2961. `maskTemplate += "<span class='im-static''>"` has an extra `'` in there. Also is there a tutorial/document for styling this mask ?

**Comment by RobinHerbots** [comment]
@BrainClot , 

There is not really a tutorial.  Have a look at the inputmask.css

So you want to use the colormask.  Please welcome all placement issues.  Suggestions to improve or better ways to make the div appear above (under) the input element.  There are cases where the div placement isn't correct.  

Btw the android hack enables the colormask automatically.  I'm currently working on improving support for android. (inputfallback) 

Thx for reporting the typo!

**Comment by ydimitrof** [comment]
@RobinHerbots I also had to change the way the coordinates for the div are taken. Using `$(input).position()` gave the relative coordinates to its parent. I changed it to `$(input).offset()` for  the window coordinates to be taken instead. I had to do this because the mask went top-left in my case. Anyway, this issue is resolved so I'm not going to bug you anymore. Again, keep up the good work! :)

EDIT: Now that I think of it, it would be a lot better if the DIV of the mask is before or after the masked input since we can use the classes of the parent element. In my case classes are dynamic and it would be a lot better to use CSS for element hiding than JS/jQuery.

**Comment by RobinHerbots** [comment]
@BrainClot , 

Thx for the feedback.  
About the css.  I agree, only the div needs to be positioned behind the input.  How can this be done with pure css dynamically?

I am thinking of moving as much as possible to css.  Feedback concerning that is welcome.

**Comment by RobinHerbots** [comment]
@BrainClot , 

What if i just surround the input with a div, this will simplify things a lot I guess.

**Comment by RobinHerbots** [comment]
@BrainClot , 

Almost there

**Comment by RobinHerbots** [comment]
@BrainClot , 

I updated the colormask functionality.  Can you have a try.  I have put as much as possible in the inputmask.css.  The div surrounds the input now.  There is also a prototype fn.  positionColorMask which eases custom positioning.

**Comment by ydimitrof** [comment]
@RobinHerbots works like a charm! Now we can style the mask according to its position and state of parent elements with ease ( we're using material design in our project and we must style ( hide/show ) the mask when the user has focused the input or it's dirty ).
Thanks for the great support and again, keep up the good work! :)
