### ISSUE TITLE
Mask jumping back position

### ISSUE THREAD

**Issue by brunoheringer** [RobinHerbots/Inputmask#1636]
I have a problem with the InputMask. 
When I type in a input with Mask, the cursor is jumping back one position when it find the separator caracter .
This is not happening with all browsers. I got this in the Cordova's InAppBrowser plugin on Cellphone Sony Xperia and Galaxy S6 Edge. In many others cellphones the mask worked correctly. 

For example if I enter in 123456789 for mask of 999-99-9999 results in: 123-56-8974.

123-|4_-____
123-5|4-____
123-56-|74__
123-56-89|74

**Comment by ydimitrof** [comment]
@brunoheringer are you using the Android Hack for this? If not, check out the docs for it at https://github.com/RobinHerbots/Inputmask/blob/4.x/README_android.md

**Comment by RobinHerbots** [comment]
@brunoheringer 

Can you send me the useragent you get for the inappbrowser,
