### ISSUE TITLE
Cannot delete after fill up all the mask Android Chrome browser Jsfiddle

### ISSUE THREAD

**Issue by NightsDream** [RobinHerbots/Inputmask#1637]
https://jsfiddle.net/b02gd4fh/1/

After filling up the mask, i try to delete and re-input the value, it seems I'm unable to do it.
The cursor are keep jumping to right whenever i try to delete the filled value.
Thanks

**Comment by ydimitrof** [comment]
@NightsDream if you haven't read the Android Readme, please do at https://github.com/RobinHerbots/Inputmask/blob/4.x/README_android.md

**Comment by RobinHerbots** [comment]
@NightsDream ,  @BrainClot ,

This is a valid issue.  I already added it to the unittests.  I will have a look why.

**Comment by NightsDream** [comment]
Anyway, I have revert back to old version. Old version working well for my case on android and desktop. 

https://jsfiddle.net/b02gd4fh/3/

**Comment by RobinHerbots** [comment]
@NightsDream , 

Version 3.x is the latest.  The 4.x is new development, there is no 4.x released yet.

**Comment by NightsDream** [comment]
@RobinHerbots, 

Oh, I thought 4.X is the latest version,
thx for telling me and the great plugin :)
