### ISSUE TITLE
Uncaught SyntaxError: Unexpected token ( in JSON at position 1

### ISSUE THREAD

**Issue by arturcesarmelo** [RobinHerbots/Inputmask#1639]
This error is driving me crazy!

![captura de tela 2017-07-04 as 00 16 14](https://user-images.githubusercontent.com/18191910/27813713-1731ddce-604e-11e7-81c3-a8e667a76619.png)

Here is my implementation

![captura de tela 2017-07-04 as 00 17 32](https://user-images.githubusercontent.com/18191910/27813729-3d329202-604e-11e7-93b8-da19d0c6b315.png)

Any one can help me?

**Comment by RobinHerbots** [comment]
@arturcesarmelo , 

Can you show me the data-inputmask attribute on the input elements.  The json parsing is very strict
