### ISSUE TITLE
Bug with DependencyLib (vanilla) and Microsoft Edge

### ISSUE THREAD

**Issue by bebleu** [RobinHerbots/Inputmask#1641]
Greetings,

I got a strange bug with inputmask.dependencyLib.js using webpack and Microsoft Edge.
Each time InputMask().mask() is called, Edge tries to reload the page. After some reload, he displays an error.

There is no way to reproduce this problem if developer console is open. And the problem appears only with Edge.

As a workaround, I setted an alias to use inputmask.dependencyLib.jquery in webpack.conf, and now everything seems to work.

Tested with Microsoft Edge 38.14393.1066.0

**Comment by RobinHerbots** [comment]
@bebleu , 

Thx for reporting.  I will have some tests myself.

**Comment by RobinHerbots** [comment]
@bebleu , 

I need more info.  I tried with microsoft Edge 14 & Edge 15 and I don't  see a problem.
