### ISSUE TITLE
DependencyLib.Event CustomEvent

### ISSUE THREAD

**Issue by dkochetov** [RobinHerbots/Inputmask#1642]
Hi!
`DependencyLib.Event = function CustomEvent(event, params) {`
recursive call.
In IE work very slowly.

**Comment by RobinHerbots** [comment]
I will do some tests. Thx for reporting

**Comment by RobinHerbots** [comment]
@dkochetov , 

Wow what was I thinking, ... I will submit a fix soon

**Comment by dkochetov** [comment]
Thanks! =)
