### ISSUE TITLE
Object doesn't support property or method '_valueGet' in version 3.3.7

### ISSUE THREAD

**Issue by tdinpsp** [RobinHerbots/Inputmask#1645]
Unhandled exception at line 1246, column 34 in http://localhost:49300/Scripts/jquery.inputmask.bundle.js

0x800a01b6 - JavaScript runtime error: Object doesn't support property or method '_valueGet'

I'm getting the above error which I didn't use to get, it only occurs on a postback within a modal popup.  It's probably something I'm doing wrong.  On the client side after the postback in order to apply the input masks again OnDocumentReady I'm calling the following:

    var inputs = document.querySelectorAll("input");
    Inputmask().mask(inputs);

Thanks.

**Comment by RobinHerbots** [comment]
@tdinpsp , 

Is this an ajax post?  Can you share some info about the masks used ?

**Comment by tdinpsp** [comment]
It’s not an ajax post in the sense that it is not contained within an UpdatePanel.  The mask itself is pretty simple “999”.  I did some further investigation and I think it is at least partially a browser issue combined with TextMode=”Number”.  Chrome has an issue but Internet Explorer does not.  As I said I figured the issue was likely to be something I did but maybe it is something you might run into more often in the future.

Tarang

**Comment by RobinHerbots** [comment]
@tdinpsp , 

Thx for the feedback.  I fixed the issue in the 4.x branch.  I will merge the change back to the 3.x branch soon.

It had todo with the unsupported  type=number, which in chrome is natively supported and the inputmask not being applied and ie does not support type=number and thus the inputmask was applied.....  calling the masking repeatedly, call for a removal of the mask before remasking and there came from.

**Comment by tonym99** [comment]
Where can I find this fix?  Which version of the jquery.inputmask.js file is this in?

Thanks!!

I get this error using IE11

<img width="763" alt="screenshot_69" src="https://user-images.githubusercontent.com/24207880/30325148-945906ae-9791-11e7-91c5-8a993ef4714f.png">

**Comment by RobinHerbots** [comment]
@tonym99 , 

Get version 3.3.8

**Comment by tonym99** [comment]
Thanks, this worked great!!

Tony
