### ISSUE TITLE
Git: fatal: Negative patterns are forbidden in git attributes

### ISSUE THREAD

**Issue by maxxdev** [RobinHerbots/Inputmask#1646]
After composer update when use git add * or git commit
getting error "fatal: Negative patterns are forbidden in git attributes
Use '!' for literal leading exclamation."
Investigated which file trigger error and found
\vendor\bower\jquery.inputmask.gitattributes text in last string is !k4E3n2s1E1n2d3m4E!
If comment/delete this string then git works success

| Operating system | windows 7

**Comment by RobinHerbots** [comment]
@maxxdev , 

Thx for reporting

**Comment by hlslaughter** [comment]
Still an issue BTW.
