### ISSUE TITLE
Can't input character at the end if it's also a placeholder on Android

### ISSUE THREAD

**Issue by alexey-m-ukolov** [RobinHerbots/Inputmask#1648]
**Inputmask**: 3.6.6, 3.6.7, 4.0.1-13 and probably others.
**dependencyLibs**: vanilla and jquery.
**Platform**: Android 4.4, Android 5.1, Android 6.0 and probably others.
**Browser**: Chrome 59, Firefox 54 and probably others.
**Example**: [https://jsfiddle.net/alexey_m_ukolov/wafv0L70/1/](https://jsfiddle.net/alexey_m_ukolov/wafv0L70/1/)

In Chrome it's impossible to input "10" in the input field, because it ends with the placeholder character. In Firefox the behaviour is even more wierd - caret jumps here and there, but I still can't input zero at the end.

I've traced the issue to this code: [https://github.com/RobinHerbots/Inputmask/blob/4.x/js/inputmask.js#L2641-L2645](https://github.com/RobinHerbots/Inputmask/blob/4.x/js/inputmask.js#L2641-L2645), but I can't understand what's going on there (or, rather, _why_ it is going on). When I comment out line with `inputValue = inputValue.replace(bufferTemplate, "");` everything works as expected, I can type anything I want.

What is the objective here, why is placeholder at the end of input being removed?

**Comment by alexey-m-ukolov** [comment]
Oh, it's a duplicate of #1617. Sorry, I've searched before opening an issue, but #1617 is not very specific. Hope additional information will be helpful.

Please let me know if I can be of any assistance.

**Comment by alexey-m-ukolov** [comment]
Thanks for the fix! Will it be added to the 3.x version?

**Comment by RobinHerbots** [comment]
@alexey-m-ukolov , 

Yes it will!  I'm further working on enhancing the inputfallback (android).  These changes will be added to the 3.x version and become 3.3.8.

**Comment by RobinHerbots** [comment]
@alexey-m-ukolov ,

Have a try with https://jsfiddle.net/wafv0L70/5/
