### ISSUE TITLE
Extra masking in onBeforeWrite is not working in android browsers

### ISSUE THREAD

**Issue by ghost** [RobinHerbots/Inputmask#1649]
https://jsfiddle.net/bawlochoro/uumhexh5/3/

I am trying to mask ssn field like this •••-••-1234 

mask: '999-99-9999',
      autoUnmask: true,
      onUnMask: function (masked, unmasked) {
        var val = '';
        var unmaskedIndex = 0;
        for (var i = 0; i < masked.length; ++i) {
          if (masked[i] === •) {
            val += unmasked[unmaskedIndex];
            unmaskedIndex++;
          } else {
            val += masked[i];
          }
        }
        return val;
      },
onBeforeWrite: function (event, buffer, caretPos, opts) {
        for (var i = 0; i < Math.min(buffer.length, 7); ++i) {
          if (buffer[i] !== '_' && buffer[i] !== '-') {
            buffer[i] = •;
          }
        }
      }

**Comment by alexey-m-ukolov** [comment]
@bawlo you really should state problem more clearly (what is expected result, what you got instead, etc), provide info like library and os versions and create an example on https://jsfiddle.net.

I've posted #1648 yesterday and because @RobinHerbots could clearly see what the problem was and could reproduce it, he [pushed a fix](https://github.com/RobinHerbots/Inputmask/commit/6dc37844e213553cc10fef9111d31751143135b6) within an hour.

**Comment by ghost** [comment]
https://jsfiddle.net/bawlochoro/uumhexh5/3/

@alexey-m-ukolov 
In desktop Chrome browser, I am getting the expected output but in android chrome browser, I am not getting the result.

**Comment by RobinHerbots** [comment]
@bawlo, 

On android the masking is based on the input event.  So when you manipulate the buffer and put the big dot instead of the valid input, the inputmask validates the big dot and the new input which fails as you only accept a numeric value.  

Maybe with onBeforeMask you can fix this.  in onBeforeMask you replace the bigdots again to their real value before it is presented to the validation.  Visually it will be manipulated again by the onbeforewrite

**Comment by ghost** [comment]
@RobinHerbots 
I could not fix it with onBeforeMask.

**Comment by RobinHerbots** [comment]
@bawlo , 

I had a look at it.  I will provide more context to the callbacks, ... "this" will be the inputmask object which will create much more possibilities.  W8 for more feedback

**Comment by RobinHerbots** [comment]
@bawlo , 

With the latest on the 4.x branch try

```
        Inputmask("999-99-9999", {
            passwordChar: '\u25CF',
            autoUnmask: true,
            onUnMask: function (masked, unmasked) {
                var val = '';
                var unmaskedIndex = 0;
                for (var i = 0; i < masked.length; ++i) {
                    if (masked[i] === this.passwordChar) {
                        val += unmasked[unmaskedIndex];
                        unmaskedIndex++;
                    } else {
                        val += masked[i];
                    }
                }

                return val;
            },

            onBeforeWrite: function (event, buffer, caretPos, opts) {
                for (var i = 0; i < Math.min(buffer.length, 7); ++i) {
                    if (buffer[i] !== '_' && buffer[i] !== '-') {
                        buffer[i] = opts.passwordChar;
                        console.log(buffer[i]);
                    }
                }
            },
            onBeforeMask: function (initialValue, opts) {
                var vps = this.maskset.validPositions;
                var output = $.map(initialValue.split(""), function (chr, ndx) {
                    if(chr === opts.passwordChar && vps[ndx]){
                        return vps[ndx].input;
                    }
                    return chr;
                });
                return output.join("");
            }
        }).mask("test3");
```

**Comment by RobinHerbots** [comment]
I forgot to push. Will do in the morning.

**Comment by bawlo** [comment]
It worked but I didn't get what happened in the onBeforeMask part!

**Comment by ghost** [comment]
Thanks for your help @RobinHerbots. Its working fine.

**Comment by bawlo** [comment]
One more bug: In Android devices, if I put cursor somewhere in between the value and start using backspace to delete then cursor moves to end every time.

**Comment by RobinHerbots** [comment]
updated fiddle for testing https://jsfiddle.net/uumhexh5/7/

**Comment by RobinHerbots** [comment]
@bawlo , 

Is this device specific?  Can you retest with the jsfiddle I provided.

**Comment by ghost** [comment]
I checked with Lenove P2 Android 7 then it did not work properly. Its allowing to type alphabets also and in Redmi Note 4 android 6 it was working properly.

**Comment by RobinHerbots** [comment]
@bawlo , 

There is probably an error occurring in Android 7.

**Comment by ghost** [comment]
Steps to reproduce in android 7 device: first time try to enter alphabets it wont allow, then enter numbers and remove them using backspace and start entering alphabets again then it will allow.

![92010e5a-2e40-46b8-ab13-0f708c2c3270](https://user-images.githubusercontent.com/5371638/28310678-de27f8f0-6bca-11e7-90e2-acadaa7fddc6.jpeg)

**Comment by ghost** [comment]
Any update on this @RobinHerbots ?

**Comment by RobinHerbots** [comment]
@bawlo , 

No, I haven't looked further in to this.  Can you provide some console output when you get the above on android 7?
