### ISSUE TITLE
GPS coordinates mask - regex

### ISSUE THREAD

**Issue by gkiosov** [RobinHerbots/Inputmask#1651]
Can't find any working solution for masking GPS coordinates like "-33.466350, 147.981122". Tried different regex — nothing working. For example:

$this.inputmask({
	regex: '^(-?\d{1,2}\.\d{6}),(\s*)(-?\d{1,3}\.\d{6})$',
	placeholder: ''
});

I can type everything I want.

regex: '^[a-z0-9]+$' works fine in the same field — I can type only small latin symbols and digits.

**Comment by RobinHerbots** [comment]
@gkiosov , 

Not all regex is currently supported.  I will add support for \d and \s.

You can always try to create the mask without regex syntax.

$this.inputmask("[-]9{1,2}.9{6}, [-]9{1,3}.9{6}", {
    jitMasking:true
});

(not tested)

**Comment by gkiosov** [comment]
It works. Thanks a lot!

**Comment by RobinHerbots** [comment]
@gkiosov , 

Btw, I did test the regex version.  Where does it fail?  Can you give some example.

**Comment by gkiosov** [comment]
I experimented more a bit: here is an examples  — http://kiosov.com/tmp/gps.html

First one (with /d) does not work at all — I just see placeholder with 'd' symbols. Second one (with [0-9]) works fine but I see dots as a placeholder and it types 's' instead of space when I hit the space button. No /d & /s support as you said above. Jit-masking is still the best.

**Comment by RobinHerbots** [comment]
@gkiosov , 

Retry but double escape the \d => \\d

**Comment by gkiosov** [comment]
Yep, it works. But I still see dots and comma (.,.) in the field with "\." or just "." — it stop working if I double escape "\\.". Looks like it's not about mask placeholder — just regex put it in the field.

I'm using your jit-masking version — it's ok for me.

**Comment by RobinHerbots** [comment]
@gkiosov , 

In the jitmasking version you need to replace the dots by * to be correct.

I pushed an update which resolves the dot issue for regex.

$this.inputmask({
regex: '^(-?\\d{1,2}.\\d{6}),(\\s*)(-?\\d{1,3}.\\d{6})$',
jitMasking: true
});
should do also
