### ISSUE TITLE
{'mask':'y'} no longer works as expected

### ISSUE THREAD

**Issue by malcolmvs** [RobinHerbots/Inputmask#1653]
A previous mask which made use of "y" as the inputmask no longer works (it should capture the year portion of a date).

http://jsfiddle.net/1uqa45o2/1/

Is there a particular reason for this?

**Comment by RobinHerbots** [comment]
@malcolmvs , 

This is because the y definition is removed.  It was causing much confusing with regards to the date aliases.
(and I know I should have followed the semver, but I didn't  ;-) )
Just copy the definition from an earlier version or define your own.

**Comment by malcolmvs** [comment]
Ah ok, thanks for the feedback
