### ISSUE TITLE
Masking does not work with form elements created with jQuery

### ISSUE THREAD

**Issue by dalamberts** [RobinHerbots/Inputmask#1658]
Hi,

I am adding a row to an input table using the following jQuery code.  Unfortunately, the masking does not work for the dynamically added elements.  

`  $("#add_scan_button").click(function(e) {
    e.preventDefault();
    str = "<tr>";
    str += "<td>";
    str += "<input type='id='scans_date' name='scans_date' data-inputmask='alias': 'mm/dd/yyyy' class='form-control'>";
    str += "</td>";
    str += "</tr>";
    $(str).prependTo(".table-scans > table > tbody");
      return false;
    })`

Now I tried added adding the following before the return false but it did not work either:
`  $("#scans_date").inputmask("99/99/9999");
   $(":input").inputmask(); 
  //Inputmask().mask(document.querySelectorAll("input"));`  

Am I missing something or is this a bug?

Any help would be greatly appreciated.

Ernie

**Comment by Nodws** [comment]
like with all dynamic elements they are added AFTER the DOM has been set, so you have to address the parent (element that was loaded in DOM) to read them

`$("body #scans_date").inputmask("99/99/9999");`

**Comment by mattkoch614** [comment]
@Nodws I tried this with a dynamically inserted input element (via select2) and your method didn't work for me. ``inputmask`` is still undefined when inspecting the element.

**Comment by dblosser0556** [comment]
I am having the same issue.  Is there a solution?

**Comment by RobinHerbots** [comment]
@dblosser0556, 

Do what @Nodws  says, althought the initial code of @dalamberts should also work.

Just leave the dom some time to create the element.  (settimeout or first check if you can find the new  element)

Normal flow is

- you define the elements in html
- they get parsed and defined in the DOM
- with js you apply the inputmask

When you add an element dynamically
- you create a new element in the dom
- with js you apply the inputmask on the new element

You can have a look at the dist/binding/inputmask.binding.js for an example which uses jquery to automate the binding.  But it is sufficient to just call Inputmask(... masking options ...).mask(selector for the newly created element); to apply the mask on the new element.

**Comment by dblosser0556** [comment]
I got this to work for me:

 

 

        $("button#addDependents").click(function () {

            $('#row0').clone().appendTo('#dependantTable tbody');

            

            dependents++;

            

            updateDepNo(0, dependents);

 

            $('#row' + dependents).css('display', '');

            

            // bind the input masks required for elements added to the dom.

            $('#row' + dependents).find("#dep_phone").inputmask();

            $('#row' + dependents).find("#dep_mobile").inputmask();

            $('#row' + dependents).find("#dep_email").inputmask();

 

            $('#dependent_count').val(dependents);

 

        });

**Comment by Gabriel-Valin** [comment]
> like with all dynamic elements they are added AFTER the DOM has been set, so you have to address the parent (element that was loaded in DOM) to read them
> 
> `$("body #scans_date").inputmask("99/99/9999");`

works for me! ty
