### ISSUE TITLE
Issue with phone-be inputmask (Liége phone number)

### ISSUE THREAD

**Issue by borisson** [RobinHerbots/Inputmask#1659]
The belgian phone inputmask doesn't seem to work with liégeois phone numbers. 

Phone numbers starting with 4x should be valid, but they get transformed to 46x. For example, the phone number of the Liége town hall is `04 221 81 11`, and that's not possible to enter as a valid number.

![mobile-phone](https://user-images.githubusercontent.com/1721156/28822850-30a4f862-76bb-11e7-83ef-6647a01307be.gif)

**Comment by RobinHerbots** [comment]
@borisson , 

Finally fixed in the current (4.x branch)
