### ISSUE TITLE
Integer part of negative decimal number becomes zero

### ISSUE THREAD

**Issue by newmangreen** [RobinHerbots/Inputmask#1660]
When input has a negative number that is set with "value" attribute, its integer part is removed by mask.
[https://jsfiddle.net/newmangreen/vpo5sLzu/](https://jsfiddle.net/newmangreen/vpo5sLzu/)  

(#1500 issue is related with this one. I opened new issue since workaround solution by adding placeholder="0" option produced other problems in our web-app.)

**Comment by newmangreen** [comment]
I retried in 5.x version but no chance. It even worsened the case:
placeholder:"0" is the default now and if I give empty placeholder, 
it is not possible to convert to positive value. 

Why placeholder:"0" is a problem, because when page loads, input mask initiates with zeros.
We don't want zero values without user action. If user clicks input then zeros may be added.

**Comment by newmangreen** [comment]
I fixed my code by adding placeholder:"0" option, if input value is negative. Problem still continues on converting positive value to negative value.

**Comment by RobinHerbots** [comment]
https://jsfiddle.net/robinherbots/n38pwmxq/1/

Doens't this work correct?
