### ISSUE TITLE
inputmask Date Format in mm/dd/yyyy hh:mm:ss AM/PM

### ISSUE THREAD

**Issue by chandrakamal1984** [RobinHerbots/Inputmask#1663]
Can any one help me

**Comment by chandrakamal1984** [comment]
Got it:

input.inputmask('datetime', {
                mask: "2/1/y h:s:s t\\m",
                alias: "mm/dd/yyyy",
                placeholder: "mm/dd/yyyy hh:mm:ss xm",
                separator: '/',
                hourFormat: "12"
            });

**Comment by howardsalter** [comment]
Did this break in 5.x? I'm not able to use 2/1/y or 2-1-y

**Comment by RobinHerbots** [comment]
Yes, the datetime alias is totally rewritten.  Have a read in the readme for the datetime alias.
