### ISSUE TITLE
small inconsistency in documentation

### ISSUE THREAD

**Issue by stephsavoie** [RobinHerbots/Inputmask#1665]
Hey there,   maybe a small inconsistency in your doc.. I though you would hear about it and make the necessary change if I'm good.

Long story short, option 'autoUnmask' seems to be documented as a default plugin option, but not as a 'numeric' extension option.  

I tried to overwrite default options with it, but didn't worked...  I finally had it working after setting it as an overwrite of the numeric extension, that's how I discovered it.

Maybe this could help someone else :)

Edit : I'm using version 3.3.7.

**Comment by RobinHerbots** [comment]
@stephsavoie , 

The autoUnmask is a default plugin option, but the numeric alias has it's own implementation, so you need to overwrite it in the extension.  , ... it is logical, but can be confusing.  I will need to document this within the set defaults section.

**Comment by RobinHerbots** [comment]
@stephsavoie , 

It is mentioned in the docs.  
(from readme)
But if the property is defined within an alias you need to set it for the alias definition.

**Comment by RobinHerbots** [comment]
@stephsavoie , 

I made a small update in the readme
