### ISSUE TITLE
Error from callback "onBeforeWrite" when setting a value by JavaScript 

### ISSUE THREAD

**Issue by stephsavoie** [RobinHerbots/Inputmask#1667]
I have a JavaScript error after trying to set a value by JS in the input field that has a callback "onBeforeWrite":

```Uncaught TypeError: Cannot set property 'forwardPosition' of undefined```

After value has been entered in the input field, the callback must fill zeroes in front of it, for a maximum of 6 characters.  Example : Entered 2342 in input field => gives "002342" on blur.

If I enter manually a value in the input field, it works.  My issue is only when setting the value by JavaScript.  Example :

```$('input').val('002342');```

[See this plunkr example](https://plnkr.co/edit/uIPJmBGQwOHMlGqnggQ1?p=preview)

Not sure why this happens or if I'm using the callback properly.  Based on other examples found, I should be ok...   Anyone can help on this?

**Comment by stephsavoie** [comment]
Any cue about this issue, anybody?

**Comment by RobinHerbots** [comment]
@stephsavoie , 

Try the version from github, instead of 3.3.7

**Comment by stephsavoie** [comment]
@RobinHerbots 

This issue has been resolved in version 3.3.8 so I updated without too much efforts.  

The nature of the project and the considerable amount of elements configured with Inputmask were a no-go to update to the newest version as this would probably imply a bunch of tests and fixes.   Probably later this year though.

Thanks for your time
