### ISSUE TITLE
InputMask breaks autocomplete on all other fields. Text input borked on Android mobile

### ISSUE THREAD

**Issue by Healyhatman** [RobinHerbots/Inputmask#1672]
Not sure if this is the right place to put this, since I'm using the version Chronoforms has implemented, but they did supposedly update it to the latest version.

**Issue 1**
When there's a field with an inputmask somewhere on the page, autocomplete on OTHER fields will only enter the last character
Platform: Chrome on Android mobile AND chrome desktop
EXAMPLE: A field has an inputMask (any inputmask whatsoever). A different field labelled Name has no input mask - try to use autocomplete to fill the field with "Kamron" - only "n" is entered. 

**Issue 2**
Fields without inputmasks lose text entered when the field loses focus
Platform: Chrome on Android mobile
EXAMPLE: A field has an inputmask. Type "hello" into a field without an input mask. Click outside of the field - field is cleared.
VARIATION: If you enter a number, then enter a letter, the number is wiped but the text remains and is preserved when the field loses focus

**Issue 3**
Fields without input masks have broken caret positioning when entering spaces or symbols such as "@"
Platform: Chrome on Android mobile
EXAMPLE: A field has an inputmask. Try to type an email address  into a field without an inputmask and the positioning of the typed letters goes haywire after the symbol.

**Comment by RobinHerbots** [comment]
@Healyhatman , 

Can you make some demo on jsfiddle, so it is easier to reproduce/investigate.

**Comment by Healyhatman** [comment]
Sorry @RobinHerbots no I couldn't make a jsfiddle. It happens using Chronoforms for Joomla, so not really feasible :) Sorry for not responding a few months ago!

**Comment by Healyhatman** [comment]
I don't think this is an issue anymore, or at least I don't care anymore :D
