### ISSUE TITLE
Please add version 4.x to NPM

### ISSUE THREAD

**Issue by kendrive** [RobinHerbots/Inputmask#1675]

**Comment by RobinHerbots** [comment]
@kendrive , 

I will release 3.8 soon.

**Comment by kendrive** [comment]
But in package.json version 4.0.1-28 is specified

**Comment by RobinHerbots** [comment]
@kendrive , 

Yes, but there is also the 3.x branch with version 3.8.  4.0 is for later.  Currently 3.8 & 4.x are mostly on par
