### ISSUE TITLE
On submitting the page fields marked with autoUnmask going with the mask

### ISSUE THREAD

**Issue by rafaeldl** [RobinHerbots/Inputmask#168]
ex.:
$('#date').inputmask({ "mask": "d/m/y", 'autoUnmask' : true}); //  value: 23/03/1973

when submitted your value is '23/03/1973' instead of  '23031973'. It is a bug?

**Comment by RobinHerbots** [comment]
Hi Rafael,

The autounmask works when you retrieve the value with jquery.val fn or if
the browser supports adjusting native properties it even works with the
javascript value property.

Firefox supports the autounmask with the value property.   For the submit
it will depend on how the values are retrieved by the browser.  Maybe you
can do a test when using firefox.  (feedback is welcome)

I never tested or investigated time in  the autounmask in a submit
scenario, but I will now ;-)

I will have a look at it soon and give feedback if it is possible.

best regards,

Robin

2013/2/5 Rafael Laurindo notifications@github.com

**Comment by vanomania** [comment]
@rafaeldl @RobinHerbots I just noticed the same issue.  My workaround was to mask a dummy field and then update the value in an onchange() 

```
<input type="text" id="maskedPhone" data-inputmask="'mask': '(999) 999-9999[ 9999]', 'placeholder':'(xxx) xxx-xxxx xxxx', 'autoUnmask' : true, 'clearMaskOnLostFocus':true" onchange="$('input[name=phone]').val($('#maskedPhone').val())"/>
<input type="hidden" id="phone"/>
<script lang="javascript">
    $(document).ready(function(){
        //if real field has initial value, initialize the dummy field
        $('#maskedPhone').val($('#phone').val());
        $(":input").inputmask();
    });
</script>
```
