### ISSUE TITLE
Julian Date Mask

### ISSUE THREAD

**Issue by Vaccano** [RobinHerbots/Inputmask#1684]
It would be nice to support a Julian date mask. 

Basically 1 to 366.

I tried doing a custom mask for this, but I couldn't find a way to have a variable cardinality.

**Comment by RobinHerbots** [comment]
@Vaccano, 

How would the format of a julian date mask be?

**Comment by Vaccano** [comment]
Julian date is just the day of the year counting from the start. 

So it would allow all numbers between (and including) 1 to 366. 

366 is for leap year. 

So 40 would be ok. But if another digit was attempted(400), it would be blocked.

**Comment by RobinHerbots** [comment]
@Vaccano, 

Ok, but would the mask just be a number from 1 to 366 or should it include other things like the year or so?

**Comment by RobinHerbots** [comment]
@Vaccano ,


Will this do?
```
	Inputmask({
		alias: "integer",
		min: 0,
		max: 366
         }).mask("test2");
````

**Comment by Vaccano** [comment]
That seems good.  Though that looks like it would allow 0, which I don't think is a valid value for Julian Date.

I don't think I realized that you could do integers like that when I asked for this.
