### ISSUE TITLE
Cursor jump in Android

### ISSUE THREAD

**Issue by argumentus** [RobinHerbots/Inputmask#1688]
Hi, Robin.

I have issue with jump cursor in Android.
Example: [https://jsfiddle.net/argumentus/4t657qb5/1/](https://jsfiddle.net/argumentus/4t657qb5/1/)
Testing on: Chrome 60.0.3112.116.
Phones:

1) LG G5 SE, keyboard LG, Android 7.0
2) Samsung  Galaxy Grand Prime, версия Android 5.1.1
3) huawei p2-6011, qwerty-keyboard, Android 4.1.2;
4) Redmi 3, keyboard Swiftkey, Android 5.1.1;

**Comment by RobinHerbots** [comment]
@argumentus , 

Is there a particular sequence you need to follow to reproduce?

Just tested on Android 6.0 and didn't see the problem.

**Comment by augcesar** [comment]
+1

**Comment by abrekhov** [comment]
Have the same issue: i've put mask like "+7 (999) 999-99-99", and only on real mobile device (I've been testing on meizu m2 mini with google keyboard) there is the problem. When I enter 0123456789 it becomes +7 (012) 567-98-43.

**Comment by peektoseen** [comment]
+1 huawei honor 5c - cursor jump on phone input field.

**Comment by abrekhov** [comment]
Problem dissapeared after I've changed input type from 'text'` to 'tel'! Thnx to previous issues.

**Comment by peektoseen** [comment]
Change "text" to "tel" not work for me.
[here](https://jsbin.com/reyetakovo) is jsbin
and [this](https://youtu.be/fPKrtmewXDo) what's going on if I will press keys from 1 to 0
Android 7.0

**Comment by peektoseen** [comment]
This happen if I select "Swype - Swype for Huawei" in "Language & input">"Default keyboard" . If I set "Gboard" as keyboard - all work fine.

**Comment by CezaryDanielNowak** [comment]
I found the reason of that, but already switched input-mask library so I can give description only:
- it happens when we handle 'input' event
- it does not happen when using 'keyup' event.
- it happens on Swype, Samsung and LG keyboards

So the easiest solution would be to use 'keyup' event on android browsers.

**Comment by RobinHerbots** [comment]
Hi @peektoseen 

Sorry that I didn't took time before to view at your example.

Can you please restest, with the current version.  I made some changes which should fix the problem

**Comment by peektoseen** [comment]
@RobinHerbots , I checked it out. Work just fine. Thank you very mutch. Fixed.
