### ISSUE TITLE
Input Mask OnComplete Issue

### ISSUE THREAD

**Issue by hkb261** [RobinHerbots/Inputmask#169]
When the last character of the mask does not accept an input from the user, the OnComplete event will never be raised.

For instance:

```
$('#phoneAreaCode').inputmask('(999)', {
    "oncomplete": function () {
        alert('Completed');
    }
    , 'autoUnmask': true
});
```

The last character is ')' which is not a user input.  In looking at the isComplete function, I noticed that you do not check whether the last character has a cardinality, therefore, ms["lastValidPosition"] will never equal to (aml-1).  To fix this I've added to your code my own fix (after line 656, var aml = getMaskLength()):

if (!ms.tests[ms.tests.length - 1].cardinality)
     aml = --aml;

A more complete solution would be to do a reverse loop from the end of the mask and subtract one from aml for each character that does not have a cardinality until reaching a character that does have one:

```
for (i = ms.tests.length - 1; i >= 0; i--)
{
    if (!ms.tests[i].cardinality)
        --aml;
    else
        break;
}
```

**Comment by RobinHerbots** [comment]
hi hkb261,

Thanks for bringing the issue up and the proposal solution.

I will fix this soon.

best regards,

Robin

2013/2/8 hkb261 notifications@github.com

**Comment by Darkless012** [comment]
Well I have discovered another issue in isComplete function. But haven't found solution yet.
When you have inputmask like: 

```
inputmask({ "mask":"[ ]99:99-99:99", "repeat":3, "greedy":false});
```

the greedy option allow to style mask nicely(eg. display dashes in input), but oncomplete function is never fired (even with proposed fix).
I would assume that oncomplete will be fired 3 times (after every correct input)

**Comment by RobinHerbots** [comment]
Hi Pavel,

What do you want to accomplish with this mask?

Your mask:

" 99:99-99:99 99:99-99:99 99:99-99:99"

" 99:99-99:99 99:99-99:99"

" 99:99-99:99"

"99:99-99:99 99:99-99:99 99:99-99:99"

"99:99-99:99 99:99-99:99"

"99:99-99:99"

And continue for the optional space left in and out

Is this correct?

I haven't fully tested the behavior of isComplete in combination with
the repeat and greedy option

best regards,

Robin

2013/2/11 Pavel Grochal notifications@github.com

**Comment by Darkless012** [comment]
Well, I'm doing intranet person attendance system. And they should fill the times they were present in company.
For simplicity I stated "9" instead of hours/mins.
It doesn't matter if the space is optional, " 99:99-99:99" is as good and repeat will never be more then lets say 5. But I want to color it with green color if they have filled the whole block (12:30-13:30).

If you can add more comments into your code I might be able to fix the issue. But I wasn't able to decode the iscomplete function easily.

**Comment by RobinHerbots** [comment]
The current implementation sees the repeat and greedy false only complete
as the whole mask (mask x repeat) is complete.  Repeat is not equal to
optional.

I see what you want to accomplish, but this is not implemented.  The repeat
was more meaned for numerics.  9  with a repeat of something.  Triggering
complete for every integer you type is a bit too much.

But I like the idea, ... i will add an option RepeatsAreOptional (or
something alike).  which will allow for the behavior.

best regards
Robin

2013/2/11 Pavel Grochal notifications@github.com

**Comment by cgamache** [comment]
+1 here. The "hh:mm t" preset suffers from this problem also.

**Comment by RobinHerbots** [comment]
@hkb261 , 

I finally took the time to fix this.

@Darkless012 ,

I will not add the option to treat repeats as optional as this will be solved when dynamic masks are implemented.
dynamic mask =  ex.  "9{1,5}" ~ 9 or 99 or 999 or 9999 or 99999

@cgamache ,

I will open a separate issue for the hh:mm t mask
