### ISSUE TITLE
"numericInput: true" divide the value attribute from input by 100

### ISSUE THREAD

**Issue by phcurado** [RobinHerbots/Inputmask#1690]
Here is the fiddle example:
https://jsfiddle.net/t37m0txu/868/

When the input value is 1000 it shows as 10. When numericInput is false this problem doesn't happen.

Thanks.

**Comment by weisborg** [comment]
I don't know that it is specifically dividing by 100.  It seems to just focus where 0 is in the string.  1111 does nothing.  Different combinations of 1's and 0's do random things too.  I just ended up having to stop using it.

**Comment by phcurado** [comment]
True, it's dividing by 100 in certain situations, others is just doing a random thing. It's been some time and I just give up using the 'numericInput : true', unfortunately.

**Comment by RobinHerbots** [comment]
Updated fiddle with 4.x https://jsfiddle.net/t37m0txu/1087/ (problem still present)

**Comment by RobinHerbots** [comment]
@phcurado , 

Have a try with the current 4.x

**Comment by phcurado** [comment]
@RobinHerbots just tried and it's working now. Thanks!!
