### ISSUE TITLE
Issue with currency mask and using pound sign (£)

### ISSUE THREAD

**Issue by ryandotdee** [RobinHerbots/Inputmask#1692]
Hello

When I use the currency mask, all is well until I change the prefix to £.  When I do this the following shows in the input field :

Â£ 0.00

`$('document').ready(function(){
		$(".mask_currency").inputmask({ alias : "currency", prefix: "£ " });
	});`

Any ideas?

**Comment by RobinHerbots** [comment]
@ryandotdee , 

Did you found a solution?
