### ISSUE TITLE
placeholder multi char for date

### ISSUE THREAD

**Issue by Givx** [RobinHerbots/Inputmask#17]
Hello, 

i want to have a choice when i use the input mask with the alias date or dd/mm/yyyy the place holder is yy/mm/yyyy. 

Thanks

**Comment by RobinHerbots** [comment]
What do you mean exactly?  the placeholder is yy/mm/yyyy  ?

the default placeholder is _

You can change this by passing the placeholder option

2011/11/15 Givx <
reply@reply.github.com

**Comment by RobinHerbots** [comment]
You mean instead of **/**/____ you want to choose whatever you want to
display?

You can use the labelify jquery plugin for this.

Regards,

Robin

2011/11/15 Robin Herbots robin.herbots@gmail.com

**Comment by Givx** [comment]
the default placeholder is _ ok, no problem but if i change this by passing the placeholder option by dd/mm/yyyy the display bug because each char is replace by dd/mm/yyyy

for example : 

```
                    $("#date").inputmask("date", {"placeholder": "dd/mm/yyy"});
```

Sorry for my english

**Comment by Givx** [comment]
This site explains what I mean http://www.conductiva.com/en/blog/post/76/Improvement-in-the-Masked-Input-Plugin-for-jQuery
but i would prefer your plugin because alias date it's great

**Comment by RobinHerbots** [comment]
I see what you mean.

I will add the feature.

**Comment by Givx** [comment]
Ok thanks 

Best regards,

Greg

**Comment by RobinHerbots** [comment]
Checkout the latest version ;-)
