### ISSUE TITLE
Not able to enter values for mask (9999 9999 9999 9999) credit card in Samsung S3. 

### ISSUE THREAD

**Issue by vijaychandramadrone** [RobinHerbots/Inputmask#170]
Hi Robin,

```
I am facing a small problem , i m not able to enter values in samsung s3 for credit card field.mask given format is inputmask({"mask" : "9999 9999 9999 9999"});.But same thing is working fine in desktop, IPad ,IPhone.
```

I tried this  function too which is partially success.
$("input[name='card_accountNumber']").inputmask({ "mask": "9999 ", "repeat": 4,"greedy": false }); 
Here i am able to enter only 13 numbers cursor is not moving forward after that.

Pls help me to over come this.

Thanks
Vijay

**Comment by RobinHerbots** [comment]
Hi Vijay,

Is there android running on the Samsung S3?  If so can you give me the
version of android and also the version of the plugin.

best regards,

Robin

2013/2/12 vijaychandramadrone notifications@github.com

**Comment by vijaychandramadrone** [comment]
Hi Robin,

Thanks fr the fast reply.Below is the configuration asked by u 
   Yes, my S3 is running on andriod.
   Version - 4.1.1
   Plugin Version is latest,downloaded from 1x branch of yours.

Robin  i think i made it work in my application with inputmask({"mask" : "9999 9999 9999 9999"});.
Actually problem is with me. In my html i have given maxsize="19" for the creditcard textbox .So when i m trying to input some value in the Creditcard text box ,mask( _ ) is taken as the value with space ( " " ),so which makes a total of 19 character in text box.My textbox maxsize is 19 which is taken by _ and " ".
When i increased the maxsize to 20, i m able to enter the values for creditcard in S3. 

But i m having a doubt y Desktop,IPad,IPhone not acted for the behavior which S3 did?
Y IPad,Desktop,IPhone accepted the values in credit card field when i have mentioned the maxsize as 19 ?

**Comment by RobinHerbots** [comment]
@vijaychandramadrone , 

Can you retry with the latest version of the inputmask

Robin

**Comment by RobinHerbots** [comment]
see issue 186.  Should be fixed now
