### ISSUE TITLE
Trouble with Materialize

### ISSUE THREAD

**Issue by YamilBracho** [RobinHerbots/Inputmask#1700]
Hi
I am using Materialize and I want to add validation for a field that represents an amount.
I put my include
    <script src="../style/js/jquery.inputmask.bundle.min.js"></script>
And then in my jquery ready event
 $('#txtMontoCuota').inputmask("999.999.999,99", { numericInput: true });  

But when i run my app, I am able to use letters and specials chars in txtMontoCuota

Any hitn to fix this ?

TIA;
Yamil

**Comment by RobinHerbots** [comment]
@YamilBracho , 

I will need more info.

Can you create a jsfiddle or alike with example code

**Comment by YamilBracho** [comment]
Hi
Thanks... I already solve it. The problem is I am using ASP.NET and it add a parent name to control name and Jquery was not able to find it..

Best Regards
