### ISSUE TITLE
Default Value

### ISSUE THREAD

**Issue by pafcosta** [RobinHerbots/Inputmask#1701]
Hi,

Thanks for your excellent work on this useful plugin.

I would like ask, how i can implement or if is already possible:

1. the user needs to insert a date, but by default must be empty for starts.
2. The user wants to insert today's date, but we wants to have "shortcut" to avoid to insert all date. For example, he inserts "00", the plugin replaces automatically with today's date. 

Is it possible to do it?

Thanks,
/pafcosta

**Comment by RobinHerbots** [comment]
@pafcosta ,

Read the readme and look for showmaskonhover, etc...
For inserting the current date hit <CTRL> <right arrow>
