### ISSUE TITLE
DatePicker InputMask format dd.mm.yyyy

### ISSUE THREAD

**Issue by newmandani** [RobinHerbots/Inputmask#1706]
I've got requirements to set date in such format of masked datepicker:
`dd.mm.yyyy` in English and
`дд.мм.гггг` in Cyrillic languages format.

The easyest task gonna make me creazy. 
Please, provide me with ideas of right `Inputmask` using in such task.

```
$('#dateFrom').datepicker({
    dateFormat: 'dd.mm.yyyy',
}).inputmask('dd.mm.yyyy', {
    placeholder: 'dd.mm.yyyy',
    showMaskOnHover: true,
    showMaskOnFocus: true
});
````

https://jsfiddle.net/danielnewman/fhjpjkp7/

**Comment by dellert** [comment]
+1

**Comment by newmandani** [comment]
I will reply to you @dellert tommorow, because I've resolved it. Can not remember even what was wrong, but will provide the code. 

One of the reason was i18next and one - wrong mask. But it is not for sure.

"dd.mm.yy" is right and no matter what is on placeholder. And if you try to translate with i18next you should redefine splitting characters from "." to "::", for example.

Tomorrow I'll provide my real solution.

**Comment by RobinHerbots** [comment]
@newmandani, @dellert , 

See #1924
