### ISSUE TITLE
colorMask + Remask = Duplicate im-colormask element (v3.3.8)

### ISSUE THREAD

**Issue by skycrazyk** [RobinHerbots/Inputmask#1709]
See error in jsfiddle http://jsfiddle.net/tors5L8q/1/

Duplicate .im-colormask element if update mask through option method :-(

for example: 
Error code: `myInput.inputmask.option({ mask: newMask});`
Error config: 
```
Inputmask({
  mask: CARD_MASK_DEFAULT,
  placeholder : '0',
  clearMaskOnLostFocus: false,
  colorMask: true
}).mask(myInput);
```

**Comment by RobinHerbots** [comment]
@icrazyk , 

The colormask isn't duplicating anymore in the 4.x branch. http://jsfiddle.net/tors5L8q/2/

**Comment by skycrazyk** [comment]
Thanks for good news!
