### ISSUE TITLE
inputmask disallows another keydown events

### ISSUE THREAD

**Issue by castamir** [RobinHerbots/Inputmask#171]
Inputmask is great visually, but disallows additional usage, then yours. Keydown function should be deactivable, or keystrokes should be nonstandard. E.g. byt using ctrl+your_keystroke. In my apps, home, end, pgdw, and pgup has totally different functionality, so I had to rewrite a lot of your code to even enable it.

Also other keystrokes are ignored (f1-f12), hell why? Your plugin looks great, but only looks. It seems useless to me.

**Comment by RobinHerbots** [comment]
instead of criticism, ... what do you suggest?  Home, end pgdn, pgup behave
as on normal input elements,  Filling the date of today with crtl - right
arrow is only when using the date extension, ... and these extensions are
examples of what can be done, ... but if you need other behavior, ... don't
complain but adapt it to your needs.

I really don't like your attitude, ... what the plugin and extensions offer
is what you get for FREE, if you need something else adjust the plugin or
use another one or write it yourself.

2013/2/15 Miroslav Paulík notifications@github.com

**Comment by castamir** [comment]
I only wanted to say that your keydown rules are too strict, when they disallow another key to be pressed with different behaviour. My advice is: set all your additional keystrokes as optional or allow them to be disabled. Suppresing everything except what you use is really terrible way. Such change would by handy for many...

**Comment by RobinHerbots** [comment]
Wjy didn't. you say so from the beginning. I shall see what I can do Best
regards, Robin

**Comment by RobinHerbots** [comment]
Hi Castamir, 

I removed the keydown event blocking.  Only for delete and backspace I use preventDefault but allow propagation.  This is needed to allow the delete, backspace functionality.

Can you give it a try and give some feedback.

best regards, 

Robin

**Comment by castamir** [comment]
Much better! I have one more question. Could you also allow TAB key and F1-F12 keys to have their default (browser) behavior? Everything else seems to be OK. Thank you.

**Comment by RobinHerbots** [comment]
Hi Miroslav,

Can you be more specific about tab key and f1-f12.  f-keys aren't affected
by the plugin.  What is the problem with TAB?

Which browser do you use?  Can you make a jsFiddls which shows the problem.

best regards,

Robin

2013/2/19 Miroslav Paulík notifications@github.com

**Comment by castamir** [comment]
In FF v18.0.2, when input with active inputmask is focused, keys TAB and F1-12 are ignored. Chrome works OK.

**Comment by RobinHerbots** [comment]
Hi Miroslav,

Can you retry with the latest version.

If there are other keys beside the tab or f-keys please let me know.

Best regards,

Robin

2013/2/19 Miroslav Paulík notifications@github.com

**Comment by RobinHerbots** [comment]
I updated the ignorables keycodes, with other possible affected keys.

I any probs let me know.

Best regards, 

Robin

**Comment by castamir** [comment]
Sorry for delayed answer. New version works perfectly. Thanks a lot.
