### ISSUE TITLE
Input mask not working on Android

### ISSUE THREAD

**Issue by aminmansouri2000** [RobinHerbots/Inputmask#1714]
input mask is not working in android by pressing (.) delimiter. And after pressing one character, no keys can be printed. It seems keypress event is not working.
the applied versions are :4.0.1-48 and 3.3.8
Sample Code:
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<input id="test1" name="test1"/>
<br/>
<script type="text/javascript" src="dist/jquery.js" charset="utf-8"></script>
<script type="text/javascript" src="dist/jquery.inputmask.bundle.js" charset="utf-8"></script>
<script>
	console.log(navigator.userAgent);
	$("#test1").inputmask("9{1,4}.9{1,4}.9{1,9}.9{1,2}", {
	    colorMask: false
	});
</script>
</body>
</html>

**Comment by RobinHerbots** [comment]
@aminmansouri2000 , 

You need to provide much more detail otherwise I cannot help.
Make a jsfiddle, and see if it is reproducible in browserstack.

Android version?  Browser & version?  Exact input sequence to reproduce.

I tested your mask in browserstack Samsung Galaxy S8 and don't experience a problem.

**Comment by aminmansouri2000** [comment]
Android Version: 4.4.2
Browser: Chrome, Version:59.0.3071.125
I Press one number like 1
then I press (.), cursor move to after first (.) ==> it is ok
I press another number, but no change in textbox => changes not working

**Comment by RobinHerbots** [comment]
@aminmansouri2000 , 

Which version of the inputmask are you using?  Try with the latest from github.

**Comment by aminmansouri2000** [comment]
versions 4.0.1 and 3.3.8 
yes

**Comment by RobinHerbots** [comment]
version 4.0.1-48 or 3.3.9-0 ?

**Comment by aminmansouri2000** [comment]
4.0.1-48

**Comment by RobinHerbots** [comment]
Just a jsfiddle to test against

https://jsfiddle.net/5mLzg52t/

**Comment by austre** [comment]
> Just a jsfiddle to test against
> https://jsfiddle.net/5mLzg52t/

Tested with my Galaxy S5 Android 6.0.1 and works smoothly.

**Comment by RobinHerbots** [comment]
@austre , 

Thx for the feedback.

@aminmansouri2000 , 

You have predictive text enabled?

**Comment by austre** [comment]
So, what minimal jquery version the inputmask needs?

I use chronoforms component with my joomla projects and it comes with jquery 1.11.1 and inputmask 3.1.27. Overwriting some files just to test how can i deploy inputmask 4x.

**Comment by RobinHerbots** [comment]
@austre , 

You better pick up v3.3.9 as 4.x is not released.

Inputmask does not require jquery, but should work with jquery 1.7

**Comment by austre** [comment]
A recent Chronoforms update comes with version 4.0.1-25 and now inputmask works fine at Android.
https://www.chronoengine.com/forums/posts/t103895/input-masks-borked-on-mobile?startat=20

**Comment by RobinHerbots** [comment]
@austre , 

They should use version 3.3.9 as the 4.x branch hasn't had a release yet.  The working version in the 4.x branch is 4.0.1-48.  But they should stick to 3.3.9 until 4.0 is released.

**Comment by RobinHerbots** [comment]
@aminmansouri2000 , @austre , 

Can this issue be closed?

**Comment by austre** [comment]
> They should use version 3.3.9 as the 4.x branch hasn't had a release yet. The working version in the 4.x branch is 4.0.1-48. But they should stick to 3.3.9 until 4.0 is released.

I should post this idea for them, but with no much hope they downgrade version. (ehehe)

About the hole case, for me, can be close. The Android bug did not occur in 4x versions.
