### ISSUE TITLE
Cursor bug in Android

### ISSUE THREAD

**Issue by ooaeoaii** [RobinHerbots/Inputmask#1715]
Hi, I used last available version of plugin and got cursor postion bug on my phone (Meizu MX4) when using a mask of this kind: "+380(99)999-9999".

When I type 0123456789 I get such result (only on mobile with Chrome browser, native phone browser is ok): +380(12)456-8973

I recorded a video: https://youtu.be/ppymv9XBppU
Browser/Android verison: https://imgur.com/a/e1f9U

Any solution for this problem?

**Comment by RobinHerbots** [comment]
@ooaeoaey , 

Do you use the version from github?  Which is the exact version number of the inpûtmask?

**Comment by RobinHerbots** [comment]
@ooaeoaey , 

Have a try with https://jsfiddle.net/5mLzg52t/1/

**Comment by ooaeoaii** [comment]
@RobinHerbots hi, example from jsfiddle works fine.
But I'm using npm version of `jquery.inputmask`. The latest version of it at that moment is `"^3.3.4"`.

Is it possible to upgrade it to latest version ? If not I will try later to replace it with `inputmask` which already is `"^3.3.9"`

**Comment by RobinHerbots** [comment]
@ooaeoaey , 

jquery.inputmask is the old package name.  Use inputmask package.  You should get a deprecation warning for jquery.inputmask

**Comment by RobinHerbots** [comment]
@ooaeoaey , 

Can this issue be closed?

**Comment by ooaeoaii** [comment]
@RobinHerbots Thx for answer. Yep, you can close issue.
