### ISSUE TITLE
yyyy-mm-dd format date

### ISSUE THREAD

**Issue by ziic** [RobinHerbots/Inputmask#1719]
jquery UI v 1.12.1, inputmask v3.3.9

$('#calender').datepicker({
  dateFormat: 'yy-mm-dd',
  changeMonth: true,
  changeYear: true
}).inputmask('yyyy-mm-dd');

Cannot select some dates. For example 13 December 2017

**Comment by oh4real** [comment]
I also just discovered v3.3.8 ```data-inputmask-alias="mm/dd/yyyy"``` and ```data-inputmask="'alias':'mm/dd/yyyy'"``` no longer works for dates 13 to 29. Only accepts 1-12 and 30/31. I rolled back to 3.3.7 and it's back.

Customer's couldn't enter birthdates. Not good.

**Comment by RobinHerbots** [comment]
I will fix this tomorrow.

**Comment by oh4real** [comment]
@RobinHerbots No rush. I look forward to seeming the commit. Nice to know it'll be updated.

Thanks much.

**Comment by RobinHerbots** [comment]
This seems to be caused by a PR #1664  I will revert this.

**Comment by RobinHerbots** [comment]
@ziic,  @oh4real , 

I reverted the PR.  Can you retry with the 3.x version on git.

**Comment by RobinHerbots** [comment]
@ziic ,  @oh4real , 

Version 3.3.10 fixes the issue
