### ISSUE TITLE
number range mask?

### ISSUE THREAD

**Issue by ikawka** [RobinHerbots/Inputmask#172]
Hello is it possible to have mask number in range?
I have a text box that should limit users to 255.255.255.255 IP

thank you

**Comment by RobinHerbots** [comment]
Hello ikawka,

Yes you can ;-)

Just define some custom definition.

and use a mask like $(selector).inputmask("255.255.255.255 IP", {
definitions: {

```
                '2': {
                    validator: "[0-2]",
                    cardinality: 1
                },
                '5': {
                    validator: "[0-5]",
                       cardinality: 1   }}});
```

or define an alias gor it

 $.extend($.inputmask.defaults.aliases, {

2013/2/19 ikawka notifications@github.com

**Comment by RobinHerbots** [comment]
Oeps I was too fast and it is too early in the morning ;-)

This in de extensions should do it

 $.extend($.inputmask.defaults.aliases, {
 "ip": {
            mask: "i.i.i.i",
            definitions: {
                'i': {
                    validator: "[0-255]",
                    cardinality: 3,
                    prevalidator: [
                                { validator: "[0-2]", cardinality: 1 },
                                { validator: "[0-25]", cardinality: 2 },
                    ]
                }
            }
        }});

or

$(selector).inputmask("i.i.i.i",  {
            definitions: {
                'i': {
                    validator: "[0-255]",
                    cardinality: 3,
                    prevalidator: [
                                { validator: "[0-2]", cardinality: 1 },
                                { validator: "[0-25]", cardinality: 2 },
                    ]
                }
            });

2013/2/19 Robin Herbots robin.herbots@gmail.com

**Comment by ikawka** [comment]
hello Robin, thank you so much, nice plugin by the way. I'm gonna try this.

**Comment by RobinHerbots** [comment]
Hi ikawka, 

I added the example in the jquery.inputmask.extensions.js, ... so grab the latest and use

$(selector).inputmask("ip");

best regards, 
Robin

**Comment by ikawka** [comment]
This one is almost flawless however it allowed me to input up to 299:

``` javascript
$(selector).inputmask("i.i.i.i", { 
definitions: { 'i': { 
      validator: "[0-255]", 
      cardinality: 3, 
      prevalidator: [ 
            { validator: "[0-2]", cardinality: 1 }, 
           { validator: "[0-25]", cardinality: 2 }, 
      ] 
} }); 
```

I don't get why because the 2nd validator clearly says 0-25

**Comment by RobinHerbots** [comment]
I see, ... strange, .... i will have a look

**Comment by RobinHerbots** [comment]
offcourse the regex for the ip was not restictive enough, ... fixed, just grab the latest version

Robin

**Comment by ikawka** [comment]
Tnx Robin, another thing on this particular mask might be considered is a non-greedy option per definition? so that
IPs like 10.10.10.12 for example can be a valid input as well...

**Comment by RobinHerbots** [comment]
Good idea.  I will adjust the alias.

Robin

2013/2/20 ikawka notifications@github.com

**Comment by RobinHerbots** [comment]
see issue 206
