### ISSUE TITLE
(critical error): numericInput option has no integrity at all

### ISSUE THREAD

**Issue by dhyegocalota** [RobinHerbots/Inputmask#1721]
When I use `numericInput` as `true` it does reverse the two first group digits.
Demo: https://jsfiddle.net/cydanbpw/1/

p.s. it can have more integrity errors like this

**Comment by RobinHerbots** [comment]
@dhyegofernando , 

Version? Platform? Browser?

**Comment by dhyegocalota** [comment]
Version: 3.3.9
Platform: osx
Browser: Chrome Version 61.0.3163.100 (Official Build) (64-bit)

**Comment by dhyegocalota** [comment]
@RobinHerbots which lines of the source code would you tell me to start checking?

**Comment by RobinHerbots** [comment]
@dhyegofernando , 

Inputmask.js  => checkval function  When you type it works correct.  It fails when setting a value, which is done by the checkval.

I will have a look at it also.

**Comment by weisborg** [comment]
I've also had to remove it from my masks-

`$(".Int5", context).inputmask("integer", { "clearIncomplete": true, "integerDigits": 5, "min": 0, "max": 99999, "allowPlus": false, "allowMinus": false });`

If I add it to a mask like this it does weird stuff with zeros- 41502 or 41500 becomes 415.  It is like it dumps the rest of the string after hitting a zero.

**Comment by RobinHerbots** [comment]
#1690

**Comment by RobinHerbots** [comment]
@dhyegofernando ,  @weisborg , 

Updates to the current

https://jsfiddle.net/cydanbpw/40/
