### ISSUE TITLE
problem with two separate alternaions

### ISSUE THREAD

**Issue by ivomasterche** [RobinHerbots/Inputmask#1722]
Demo: https://jsfiddle.net/ivomasterche/jk30ztrd/
I have simple mask with two separate alternations, first one has 4 possible values, second one has 2, if i select the 3rd or the 4th value from the first alternation the placeholder for the second alternation disappears.
As seen in the example:
placeholder before typing anything __-_-__  (correct)
when i start typing  

> 10-_-

  (not correct) or 

> 08-_ -

(not correct)
if i start 

> 01-_-__

 (correct)
This happens only if the first alternation has more possible values then the second one

**Comment by RobinHerbots** [comment]
@ivomasterche , 

I"m already aware and working on it.

**Comment by RobinHerbots** [comment]
mask: "(1|2|3)/(4|5)"  CacheDependency is invalid see highlights

Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.75 Safari/537.36
inputmask.js:1349 0 - [{"match":{"fn":null,"cardinality":0,"optionality":false,"newBlockMarker":true,"casing":null,"def":"1","nativeDef":"1"},"locator":[0,0,0,0],"cd":"","alternation":2},{"match":{"fn":null,"cardinality":0,"optionality":false,"newBlockMarker":true,"casing":null,"def":"2","nativeDef":"2"},"locator":[0,0,1,0],"cd":"","alternation":2},{"match":{"fn":null,"cardinality":0,"optionality":false,"newBlockMarker":true,"casing":null,"def":"3","nativeDef":"3"},"locator":[0,0,2,0],"cd":"","alternation":2},{"match":**{"fn":null,"cardinality":0,"optionality":true,"casing":null,"def":"","placeholder":""},"locator":[],"cd":""}]**
inputmask.js:1349 1 - [{"match":{"fn":null,"cardinality":0,"optionality":false,"newBlockMarker":true,"casing":null,"def":"/","nativeDef":"/"},"locator":[0,1],"cd":"0000"}]
inputmask.js:1349 1 - [{"match":{"fn":null,"cardinality":0,"optionality":false,"newBlockMarker":true,"casing":null,"def":"/","nativeDef":"/"},"locator":[0,1],"cd":"000,1,20"}]
inputmask.js:1349 2 - [{"match":{"fn":null,"cardinality":0,"optionality":false,"newBlockMarker":true,"casing":null,"def":"4","nativeDef":"4"},"locator":[0,2,0,0],"cd":"01","alternation":2},{"match":{"fn":null,"cardinality":0,"optionality":false,"newBlockMarker":true,"casing":null,"def":"5","nativeDef":"5"},"locator":[0,2,1,0],"cd":"01","alternation":2},{"match":**{"fn":null,"cardinality":0,"optionality":true,"casing":null,"def":"","placeholder":""},"locator":[],"cd":"01"}]**
inputmask.js:1349 3 - [{"match":{"fn":null,"cardinality":0,"optionality":true,"casing":null,"def":"","placeholder":""},"locator":[],"cd":"0200"}]
inputmask.js:1349 6 - [{"match":{"fn":null,"cardinality":0,"optionality":true,"casing":null,"def":"","placeholder":""},"locator":[],"cd":""}]
inputmask.js:1349 1 - [{"match":{"fn":null,"cardinality":0,"optionality":false,"newBlockMarker":true,"casing":null,"def":"/","nativeDef":"/"},"locator":[0,1],"cd":"0020"}]
inputmask.js:1349 5 - [{"match":{"fn":null,"cardinality":0,"optionality":true,"casing":null,"def":"","placeholder":""},"locator":[],"cd":""}]
inputmask.js:1349 3 - [{"match":{"fn":null,"cardinality":0,"optionality":true,"casing":null,"def":"","placeholder":""},"locator":[],"cd":"020,10"}]
inputmask.js:1349 1 - [{"match":{"fn":null,"cardinality":0,"optionality":false,"newBlockMarker":true,"casing":null,"def":"/","nativeDef":"/"},"locator":[0,1],"cd":"000,1,20"}]
inputmask.js:1349 1 - [{"match":{"fn":null,"cardinality":0,"optionality":false,"newBlockMarker":true,"casing":null,"def":"/","nativeDef":"/"},"locator":[0,1],"cd":"0020"}]

**Comment by RobinHerbots** [comment]
CD is correct

**Comment by RobinHerbots** [comment]
@ivomasterche,

This is fixed in the latest 4.x branch.

https://jsfiddle.net/jk30ztrd/2/

**Comment by ivomasterche** [comment]
Thank you...
