### ISSUE TITLE
version 3.x to 4.x regex issue

### ISSUE THREAD

**Issue by wesleywong** [RobinHerbots/Inputmask#1727]
inputmask with regex work in 3.x version but not in 4.x

`$("#example1").inputmask('Regex', { regex: "^[1-9][0-9]?$|^100$" });
or
$("#example2").inputmask({ regex: "^[1-9][0-9]?$|^100$" });`
expected result : 1-100
in 4.x weird behavior like below attached

![screen shot 2017-10-30 at 12 57 38 pm](https://user-images.githubusercontent.com/3807686/32155389-0b092698-bd72-11e7-9c68-775512b7b11a.png)

demo 
3.x - http://jsfiddle.net/wesleywong/6r43jeuw/3/ - work perfect
4.x - http://jsfiddle.net/wesleywong/6r43jeuw/4/ - weird behavior

**Comment by RobinHerbots** [comment]
@wesleywong , 

In version 4.x I removed the Regex alias.  You should use the internal regex support or add the Regex alias from version 3.x.

Anyway 4.x is still in development and hasn't had a release yet, 
The regex in 4.x has still some issues to be fixed.

**Comment by RobinHerbots** [comment]
Comment to myself:

Add support ^ and $ with | in regex

**Comment by RobinHerbots** [comment]
@wesleywong , 

I added support ^ and $ in the regex implementation.  The keepStatic prevents the latest 0 from 100 to be shown in an initial state.

Have a look at http://jsfiddle.net/Ldcgusnq/
