### ISSUE TITLE
webpack 3.8.1 build throws .inputmask is not a function.

### ISSUE THREAD

**Issue by MikeRankin** [RobinHerbots/Inputmask#1732]
from package.json

  "dependencies": {
    "ajv": "^5.3.0",
    "bootstrap": "4.0.0-beta.2",
    "codemirror": "^5.31.0",
    "datatables.net": "^1.10.15",
    "datatables.net-bs4": "^1.10.16",
    "datatables.net-buttons-bs4": "^1.4.2",
    "expose-loader": "^0.7.3",
    "font-awesome": "^4.7.0",
    "inputmask": "^3.3.10",
    "moment": "^2.18.1",
    "popper.js": "^1.11.0",
    "precss": "^1.4.0"
  },

from index.js
`
var Inputmask = require('inputmask');
`

from config.base.js
	resolve: {
		alias: {
            "./dependencyLibs/inputmask.dependencyLib": "./dependencyLibs/inputmask.dependencyLib.jquery"
        }
	},

from my html page inside a script tag
`
$('#startDate').inputmask("99-9999999"); // just trying to get anything to fire here.
`

If I take a peek inside the generated js file, I can see the inputmask code, but I can't seem to reference the inputmask function correctly.  Any idea what I'm doing wrong?  I don't see other people having this issue.

**Comment by corsik** [comment]
if used `var Inputmask = require('inputmask');`  should use `Inputmask({"mask": "(999) 999-9999", .... other options .....}).mask(selector);`

**Comment by ToujouAya** [comment]
@RobinHerbots 
I have same issue like that. If i used 
`var Inputmask = require('inputmask');`

I can not use via jquery plugin. Is it right ?

**Comment by RobinHerbots** [comment]
@ToujouAya , 

If you want to use the inputmask via the jquery plugin you also need to import jquery.inputmask

**Comment by franksantos** [comment]
> if used `var Inputmask = require('inputmask');` should use `Inputmask({"mask": "(999) 999-9999", .... other options .....}).mask(selector);`

Solve my problem! Great! Thanks
