### ISSUE TITLE
.inputmask fails when passed a number

### ISSUE THREAD

**Issue by elbweb** [RobinHerbots/Inputmask#174]
If using `$().inputmask({mask: 99999})` the function will fail.

This is mostly an annoyance if using data- tags and jquery's `$.data('foo')` function to pull the tags (as it automatically converts strings to a number if valid).

This can easily be avoided by either calling `.toString()` afterwards, or using `$().attr('data-foo')` when retrieving the value, but it seems like this should be a usable format to pass the mask in.

**Comment by RobinHerbots** [comment]
Hi elbweb,

I will fix this soon.

best regards,

Robin

2013/2/22 elbweb notifications@github.com

**Comment by RobinHerbots** [comment]
done
