### ISSUE TITLE
With numeric input set to true, input mask fails on mobile

### ISSUE THREAD

**Issue by patrickryan79** [RobinHerbots/Inputmask#1740]
Consider the following:

```
$('#test').inputmask("999999999", {
    numericInput: true
});
```
Testing with iPad via device simulator and my personal one, when attempting to type into the input the cursor just bounces around and you can't in put anything. This only occurs with right-to-left input (i.e. `numericInput: true`).

Thank you for the awesome work you've done.

**Comment by ghost** [comment]
Any update on this..

**Comment by RobinHerbots** [comment]
A fiddle to test against
https://jsfiddle.net/2nx737pd/

**Comment by RobinHerbots** [comment]
@ModestGenius , @rmovsoftcorpcom , 

Entry with numericinput true is now possible on mobile.  Still need to fix backspace and delete

**Comment by patrickryan79** [comment]
@RobinHerbots Thank you for the update. I can verify the fiddle is working as expected. The update caused strange behavior with their unique setup but it must be related to their setup. I'll investigate, but for now, thank you for taking the time to work on this.

**Comment by ghost** [comment]
@ModestGenius did you tried with Samsung Device/Keyboard. This still is the issue with Samsung devices.
I had tested it in S8, Duos, Galaxy tab and in all devices it get fail

**Comment by patrickryan79** [comment]
@rmovsoftcorpcom Not yet. I tested with safari mobile via simulator on my MAC. Due to the problems my client was having we've temporarily rolled back to 3.# which is working great.

**Comment by RobinHerbots** [comment]
@baiquan,
This is the issue to follow for the backspace

**Comment by RobinHerbots** [comment]
@ModestGenius , @baiquan, @ghost, 

The backspace issue should be fixed also.  Can you have a try on your devices.
