### ISSUE TITLE
Release 4.x on npmjs

### ISSUE THREAD

**Issue by Nekomant** [RobinHerbots/Inputmask#1741]
Please release 4.x version on npmjs if possible.

**Comment by danicholls** [comment]
Yes, can you mention if 4.x is stable, perhaps? I gather from #1727 that it isn't yet. Found your (wonderful) project on Github first, so was in the dark.

**Comment by RobinHerbots** [comment]
@Nekomant , @danicholls ,

As soon 4.x is stable and ready enough I will release and mention it in this issue.

**Comment by RobinHerbots** [comment]
@Nekomant , @danicholls , 

There is now a beta release on npm!

npm install inputmask@next
