### ISSUE TITLE
datetime alias does not provide with min & max option

### ISSUE THREAD

**Issue by abhishek-wiz** [RobinHerbots/Inputmask#1744]
I am using Version: 4.0.0-56.

Using datetime as an alias, i am not able to set min max year to be allowed in my date field. It works in 3.X version but then that doesn't work well in mobile.

Is there a way that min/max year can be set in the new version.

**Comment by RobinHerbots** [comment]
@DecipherGame , 

The datetime in is still a WIP.  But you can set min date by full date in the same format as the inputformat.
Have a look at the comments in the code

**Comment by abhishek-wiz** [comment]
I am using min/max year as below but it still does not restrict user to the required year.      

 `var today = new Date();
	var dd = today.getDate();
	var mm = today.getMonth()+1; //January is 0!
	var yyyy = today.getFullYear();
	if(dd<10){
	    dd='0'+dd;
	} 
	if(mm<10){
	    mm='0'+mm;
	} 
	var todayFormated = dd+'/'+mm+'/'+yyyy;
	$('#dob').inputmask("datetime", {inputFormat: "dd/mm/yyyy", "placeholder": "DD/MM/YYYY",min: "01/01/1900", max: todayFormated });	
`

**Comment by RobinHerbots** [comment]
@DecipherGame , 

Hmm, you are right, ... as I said it is still a WIP (not released)  The previous changes broke the min, max.

I will push a fix today.

**Comment by RobinHerbots** [comment]
@DecipherGame , 

Have another try, I pushed an update.

**Comment by abhishek-wiz** [comment]
@RobinHerbots ,

Amazing :+1: Thanks for the fix, its accepting min max dates now. But boundary conditions failing due to two reasons below, because of which it is considering any value in December month as invalid for boundary conditions set by me.

1. opts.min and opts.max adds one month to the date

I added min and max as
min: "01/01/1900", max: 20/11/2017

it got set as below in opts
max: {date: Wed **Dec 20** 2017 05:30:00 GMT+0530 (India Standard Time), day: "20", month: "11", year: "2017", rawyear: "2017"}
min:{date: Thu **Feb 01** 1900 05:30:00 GMT+0530 (India Standard Time), day: "01", month: "01", year: "1900", rawyear: "1900"}

2. Date entered also increases month by one
I entered 01/12
it took it as Jan 01 1900

I believe would need to reduce month by one

**Comment by RobinHerbots** [comment]
@DecipherGame , 

There is also a problem when you don't specify a min and max, ...  I need a better fix, .. ;-)

**Comment by RobinHerbots** [comment]
@DecipherGame, 

A new fix is available ;-)

**Comment by abhishek-wiz** [comment]
Thanks @RobinHerbots for the quick turnaround :), have tested the fix across multiple browsers and devices. The min and max date works like a charm :+1:  

The issue i raised can be closed. Though i made minor some observations, would like to highlight

1. On mobile devices specifically android, if i enter a  date suppose 12/02/198 and then do a backspace till 12/02/1 , once the focus is on 1 , and i enter 1 again, the focus stays there and does not move to the next digit, unlike desktop browsers. In this case user would feel like being stuck.

2. On mobile Safari, when entering anything in the text box, the focus shows way below the text box and behaves weirdly, even though the min and max worked perfectly here.

**Comment by RobinHerbots** [comment]
@DecipherGame , 

See #1749  & #1748 

Would it be possible to create a jsfiddle for issue #1749, that will be easier to see exactly what you mean and solve the issue.
