### ISSUE TITLE
Datetime alias improve caret positioning on android

### ISSUE THREAD

**Issue by RobinHerbots** [RobinHerbots/Inputmask#1748]
See #1744 

On mobile devices specifically android, if i enter a date suppose 12/02/198 and then do a backspace till 12/02/1 , once the focus is on 1 , and i enter 1 again, the focus stays there and does not move to the next digit, unlike desktop browsers. In this case user would feel like being stuck.

**Comment by abhishek-wiz** [comment]
Please try with below on android chrome

https://jsfiddle.net/ak2xm990/3/

**Comment by abhishek-wiz** [comment]
@RobinHerbots Tried with this, issue persists with the latest version 4.0.0-65. On doing backspace, the number where you stop, gets highlighted, and is confusing to the enduser. Would it be possible if we just have a cursor rather than higlighting the character?

**Comment by RobinHerbots** [comment]
Yes I will fix the highlighting, because it is indeed annoying on mobile.

**Comment by abhishek-wiz** [comment]
@RobinHerbots Hi, Did you get a chance to look into this?
