### ISSUE TITLE
Set upper case for characters and numeric input

### ISSUE THREAD

**Issue by PeerkeII** [RobinHerbots/Inputmask#175]
I read that it is possible to uppercase characters with the input mask. When using the "A" in the mask the character will then uppercase on typing. But on the same position in the input, it is possible to enter a numeric or a character, how should the mask look like when I want to uppercase the character?

**Comment by RobinHerbots** [comment]
I added a new definition in the extentions.js.

Just use $(selector).inputmask("#####");

Best regards, 

Robin
