### ISSUE TITLE
Samsung S series, Galaxy Note Series - Phone Mask Cursor Issue - follow-up

### ISSUE THREAD

**Issue by RobinHerbots** [RobinHerbots/Inputmask#1750]
See comment in #1490

Still getting this issue on all versions of Samsung Chrome (Galaxy S series, Galaxy Note series). Bug is not presenting on Samsung Firefox or any other combo of device/browser besides Samsung Chrome. Using version 3.3.10. Tested both in Browserstack and on actual device. Not using maxlength. Using in conjunction with Backbone, Marionette, and backbone-forms. Thank you for all your work!!

**Comment by uacode** [comment]
Hello, I test again on this link https://jsfiddle.net/gjdpfmqy/ , here is video https://youtu.be/751KQO7H4k8

**Comment by RobinHerbots** [comment]
@uacode , 

Can you have another try with https://jsfiddle.net/gjdpfmqy/15/

**Comment by uacode** [comment]
https://www.youtube.com/watch?v=etq-ZPawstw

But if I delete all text - seems works fine.

**Comment by RobinHerbots** [comment]
@uacode , 

The predictivetext disabler is not  working. I just pushed a fix.

Can you retry :

https://jsfiddle.net/gjdpfmqy/16/

**Comment by uacode** [comment]
https://www.youtube.com/watch?v=dav1TVwgM2I Not helped :(

**Comment by RobinHerbots** [comment]
@uacode , 
 Can you verify that the version loaded of the inputmask is version 4.0.0-61

I think it is some caching issue.

**Comment by uacode** [comment]
You're right, it is cache. I reopened URL (without slash) and input has changed style -
 works fine :+1: 
https://www.youtube.com/watch?v=HizwJdqgGmI

**Comment by RobinHerbots** [comment]
@uacode , 
Many thanks for taking the time to test.  
This kind of proves how important it is to make sure the predictive text doesn't interfere.  And that #1751 is very important for mobile..  

@bengrunfeld ,
Can you also have some testing.

**Comment by uacode** [comment]
@RobinHerbots Thank you very much for fix and dev! :)

**Comment by bengrunfeld** [comment]
Link to Codepen using Inputmask **3.x** that displays the bug: [https://codepen.io/bengrunfeld/pen/wPjJEg](https://codepen.io/bengrunfeld/pen/wPjJEg)

Link to Codepen using Inputmask **4.x** where the bug has been fixed: 
[https://codepen.io/bengrunfeld/pen/GOdmGM](https://codepen.io/bengrunfeld/pen/GOdmGM)

Tested on BrowserStack and native device. Samsung Galaxy `Note` series and `S` series are all working.

@RobinHerbots – Thank you so much!!!!!
@uacode – That you for your help with testing too!!

**Comment by RobinHerbots** [comment]
@bengrunfeld , 

Great to hear that it works on 4.x !

**Comment by umermughal** [comment]
Still not working on my A5 Samsung :(

**Comment by RobinHerbots** [comment]
@umermughal , 

Can you be more specific.   Against which version of the inputmask did you test?

**Comment by umermughal** [comment]
@RobinHerbots Actually I'm using this link for testing on my mobile
https://codepen.io/bengrunfeld/pen/GOdmGM
Currently, I'm unable to write any phone number. After entering the first digit it removes every digit immediately.

**Comment by RobinHerbots** [comment]
@umermughal, 

Do you have predictive text enabled on your phone?  Can I reproduce this in browserstack?

**Comment by RobinHerbots** [comment]
@umermughal , 

Try with this one  https://codepen.io/anon/pen/POvrQB
(Only some layout issues is left todo)

**Comment by umermughal** [comment]
@RobinHerbots New link is working fine(https://codepen.io/anon/pen/POvrQB) and yes my predictive text was enabled. Thanks for fixing can I know what changes you have done to fix this issue?

**Comment by RobinHerbots** [comment]
@umermughal, 

I added the option disablePredictiveText.  Read about it in the readme to understand what it does.

BTW does anyone has some tips and tricks to disable predictive text  on mobile devices from within the browser?  Device specific tricks.
