### ISSUE TITLE
Colormask & Bootstrap styled inputs styling issues

### ISSUE THREAD

**Issue by RobinHerbots** [RobinHerbots/Inputmask#1751]
See #1737 
Thanks @RobinHerbots for the release.
I would like to ask two things that might lead to other new issues.

If the original inputs are styled, when androidHack is used, I am expected to tweak the css in this repo to mimic the original look and feel, right? If so, that should be done solely in css since I couldn't find any callback to add css classes to the additional div helper.

I noticed, that if many input masks are present in the same page, when the user clicks on them (without pressing any key), multiple blink cursors will end up been displayed. http://g.recordit.co/pNRUhoJrlf.gif

At the end of the day I am trying to use input mast with a bootstrap 3.3.7 site:
https://jsfiddle.net/bcardiff/a4wukgsd/5/ that's why I noticed (1). And might found some stopper issues regarding bootstraps input addons and inputmask working together.

**Comment by RobinHerbots** [comment]
For testing (updated refs)

https://jsfiddle.net/a4wukgsd/7/

**Comment by RobinHerbots** [comment]
@bcardiff ,

The caret issue is solved.

**Comment by bcardiff** [comment]
For the record, I created a shameful fiddle for bootstrap 3.3.7 

* with inputmask v4: https://jsfiddle.net/bcardiff/bc8og8n2/
* with inputmask 3.3.11: https://jsfiddle.net/bcardiff/0qmrf8tn/

I'm definitely not proud of them and haven't tested to the extend it deserves, but it seems to be working so far.

**Comment by RobinHerbots** [comment]
See #2184
