### ISSUE TITLE
When Server give "700000000" the inputmask only read as "70"

### ISSUE THREAD

**Issue by yukopangestu** [RobinHerbots/Inputmask#1753]
Here is my setup for the inputmask:

`
$('.money').inputmask("numeric", {
    numericInput: true,
    placeholder: '0',
    groupSeparator: ".",
    digits: 0,
    autoGroup: true,
    autoUnmask: true,
    rightAlign: false
});
`

`<input name='estimated_value_of_the_property_to_cover' id='estimated_value_of_the_property_to_cover'  type='text' min='0' class='form-control money' value='' />`

Is there anything wrong with this? Thank you

**Comment by RobinHerbots** [comment]
@yupangestu , 

It is probably a bug due the numericInput option.

**Comment by yukopangestu** [comment]
Wao, thank you for the reply, after I put numericinput to false, it brings back joy, thank you

**Comment by RobinHerbots** [comment]
@yupangestu , 

;-)  great!!

Anyway I will fix the numericInput when I have some spare time.

**Comment by RobinHerbots** [comment]
Restested issue in v5.x.  => ok
