### ISSUE TITLE
How to use inputmask for none-input tag

### ISSUE THREAD

**Issue by essivision** [RobinHerbots/Inputmask#1754]
Hi,
I want to use this library for none-editable tag like label or span. I want to use separate group in price list. What should I do?

Thanks

**Comment by RobinHerbots** [comment]
@essivision , 

Just call inputmask as normal and it will format the value of the element according the provided mask.

**Comment by saigal06** [comment]
Unable to enter input in mobile browser using input mask..
On desktop its working fine.
its not working on android as well on iphone 7.
I have checked with Version: 4.0.4 and 4.0.6

 $("#Phone").inputmask("(999) 999-9999", { "clearIncomplete": true , completed: function () { jQuery("#AltPhone").focus() } });
