### ISSUE TITLE
Issue for complex comma delimited regex input mask

### ISSUE THREAD

**Issue by Shadetheartist** [RobinHerbots/Inputmask#1757]
The following regex handles comma delimited expression of possible imperial sizes (for the construction industry). 

This regex works on regexr, but not in the inputmask plugin.

![regex2](https://user-images.githubusercontent.com/8973930/33401043-dae99cce-d50c-11e7-9e1c-1c33a4bbe545.png)

**Comment by Shadetheartist** [comment]
Nevermind

**Comment by RobinHerbots** [comment]
@Shadetheartist , 
Can you provide the regex in a jsfiddle instead of in an image, so I can have a look at it.
Which version of the inputmask is used?

**Comment by chris-kruining** [comment]
@Shadetheartist this is probably not applicable in any way anymore but I'd like the challenge. based on the good/bad examples given this regex should cover all cases :: `^((?:,|^) *(?:\d*(?:\.|\/))?\d* *)+$`
