### ISSUE TITLE
IE8 error: Object doesn't support this property or method

### ISSUE THREAD

**Issue by cosm1c** [RobinHerbots/Inputmask#176]
In IE8, line 38 of jquery.inputmask.numeric.extensions.js fails due to the buffer being an object and not a string, and therefore not providing the indexOf method.

**Comment by RobinHerbots** [comment]
Grrr ie8  ;-)

Fixed!

Best regards, 

Robin

**Comment by luisrudge** [comment]
This is broken on IE8 in version 2.3.14.
I had to rollback to version 1.3.22.

**Comment by RobinHerbots** [comment]
@luisrudge , 

Can you explain a bit more the error.   

best regards, 

Robin

**Comment by luisrudge** [comment]
It's the same error, actually.
If i use the latest version with IE8 it throws this error:
'Object doesn't support this property or method'
The error occurs here:
https://github.com/RobinHerbots/jquery.inputmask/blob/2.x/dist/jquery.inputmask.bundle.js#L628

Thanks!

**Comment by RobinHerbots** [comment]
@luisrudge , 

It's the same error message but another error.

Which mask do you use?  As I tried with IE10 in IE8 mode but that works without problems.

**Comment by jkl1337** [comment]
A basic mask like 99999[-9999] will do the trick. I can confirm this problem right now. It fails in IE8 for the reason given by luisrudge. Seems to work in IE9 and IE10 in IE8 mode, but actual IE8 does not work.

**Comment by luisrudge** [comment]
I used the '99/99/9999' mask.

**Comment by RobinHerbots** [comment]
@jkl1337 , @luisrudge , 

Ok, I first need a real iE8 ;-)

**Comment by jkl1337** [comment]
Well this might not be a bug in jquery.inputmask. In the codebase I'm working on, a polyfill for Array indexOf was provided, (seems to be lifted off of MDN). jquery.each seems to be enumerating the prototype methods added to Array, so at that line (628), it is trying to dereference "indexOf" (the polyfill) as a maskset. By removing the indexOf implementation things seem to work ok for me.

**Comment by RobinHerbots** [comment]
@jkl1337,

Thx for the input.

@luisrudge, @jkl1337 , 

Can you have a try with latest version.
