### ISSUE TITLE
Unmask to leave static characters

### ISSUE THREAD

**Issue by Lukino** [RobinHerbots/Inputmask#1760]
Hello,
I cant find any escape character or something like that to leave mask character after unmask.
I have Number input, this is our format in Georgia "599 999 999".
so i want to make input 5__ ___ ___ or 500 000 000, with place holder.
but for API we need unmasked value like 512345678.
Unmask function is removing first '5' because it is part of mask an returns 12345678.

my question is, how i can write mask which will leave whole number, like 512345678

**Comment by RobinHerbots** [comment]
Use the onunmask callback.

**Comment by Lukino** [comment]
i think, i cant get my result by using onunmask callback.
because there is 2 params, masked and unmasked, i dont have even mask.
i am trying to discover how it works, i want something like escape character. 
and its function is only one, leave character from mask.
for example:
take '| ' this for 'leave mask character' escape symbol.

if i write mask |599 999 999
input must show 500 000 000 and i user will write 512 345 678
i will get unmasked value 512345678

**Comment by Lukino** [comment]
`            function unmaskedvalue(input) {
                if (input) {
                    if (input.inputmask === undefined) return input.value;
                    input.inputmask && input.inputmask.refreshValue && EventHandlers.setValueEvent.call(input);
                }
                var umValue = [], vps = getMaskSet().validPositions;
                for (var pndx in vps) vps[pndx].match && null != vps[pndx].match.fn && umValue.push(vps[pndx].input);
                var unmaskedValue = 0 === umValue.length ? "" : (isRTL ? umValue.reverse() : umValue).join("");
                if ($.isFunction(opts.onUnMask)) {
                    var bufferValue = (isRTL ? getBuffer().slice().reverse() : getBuffer()).join("");
                    unmaskedValue = opts.onUnMask.call(inputmask, bufferValue, unmaskedValue, opts);
                }
                return unmaskedValue;
            }`

here you wrote `vps[pndx].match.fn`. what is it, and where are you setting its function?

**Comment by RobinHerbots** [comment]
@Lukino , 

For the vps[pndx].match.fn have a look at insertTestDefinition...

But can't you just take the unmaskedvalue and add the 5 in front in the onunmask callback
```
Inputmask("599 999 999") {
    onUnMask: function(maskedValue, unmaskedValue, opts){
        return "5" + unmasked;
    }
}).mask(selector)
```

**Comment by RobinHerbots** [comment]
@Lukino , 

Can this issue be closed?

**Comment by mertasan** [comment]
it would be better to do it this way.

```
"autoUnmask": true,
onUnMask: function(maskedValue, unmaskedValue, opts){    
       return maskedValue.substr(0, 1)+""+unmaskedValue;
}
```
