### ISSUE TITLE
Safari - cursor moves to the end

### ISSUE THREAD

**Issue by Isabellle** [RobinHerbots/Inputmask#1761]
"version": "3.3.4"

Under Safari there is an issue; when you start typing, the cursor move to the end of the input. Have you ever heard about that issue?

I'm under Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36

**Comment by RobinHerbots** [comment]
@Isabellle , 

Have you tried with a newer version?

**Comment by Isabellle** [comment]
Thank you for your quick reply. I'm using yarn, `yarn add jquery.inputmask@4.0.0-65`, but only lets me download the 3.3.4

**Comment by RobinHerbots** [comment]
There is a deprecation warning on the jquery.inputmask package.  You should use inputmask package instead

**Comment by Isabellle** [comment]
Ok, thanks, this package has this version: 3.3.11 - I will try

**Comment by Isabellle** [comment]
Unfortunately it still moves the cursor. Not sure what I should try.
<img width="183" alt="capture d ecran 2017-12-01 a 16 10 42" src="https://user-images.githubusercontent.com/1710197/33488833-42b5c566-d6b2-11e7-9795-532f16fbc7cb.png">

**Comment by Isabellle** [comment]
I have not been able to reproduce it using a jsfiddle. I will investigate my code and keep you posted asap.

**Comment by Isabellle** [comment]
Problem was on my side and related to a keyup conflict. Thanks again for your assistance!

**Comment by RobinHerbots** [comment]
@Isabellle , 

Great that it is resolved!
