### ISSUE TITLE
How to write number 9 instead of a number placeholder

### ISSUE THREAD

**Issue by Masoud-Sharifi** [RobinHerbots/Inputmask#1762]
How to display number 9 in mask? for example a phone number with country code like this: +91 ________

**Comment by RobinHerbots** [comment]
Put \\ in front of the 9 in the Mask.

Op za 2 dec. 2017 07:39 schreef Masoud-Sharifi <notifications@github.com>:

**Comment by Masoud-Sharifi** [comment]
Thank's. It was very helpful.
