### ISSUE TITLE
Can onComplete be set via data attribute?

### ISSUE THREAD

**Issue by Vaccano** [RobinHerbots/Inputmask#1765]
Many javascript libraries allow binding to events.  For example: keydown.delegate="onKeyDown()";

I tried doing that with onComplete: data-inputmask-oncomplete.delegate="onComplete()"

But this did not work.  My binding system (Aurelia) allows for .trigger as well, I tried that too, but it did not work.

**So I am left wondering can events be attached via data attributes?**

**Comment by RobinHerbots** [comment]
Yes it can. I will make a small example tomorrow.

**Comment by Vaccano** [comment]
I would love an example for this.  But I was able to work around my issue another way.  So if you don't have time, I am fine.

**Comment by RobinHerbots** [comment]
@Vaccano , 

Here you got an example https://jsfiddle.net/ye16rcsk/

Any ideas or examples for improvement are welcome!
