### ISSUE TITLE
Enzyme testing

### ISSUE THREAD

**Issue by sepehr500** [RobinHerbots/Inputmask#1766]
Is there a way to write a test in enzyme for a react component that uses `inputmask`? I am struggling with doing this.

**Comment by RobinHerbots** [comment]
@sepehr500 , 

I don't have experience with Enzyme.  Maybe you can start with creating a jsfiddle with some sample code.

**Comment by sepehr500** [comment]
@RobinHerbot I really just want to write a unit test for my mask. I don't need enzyme. Do you know how I would do that?

**Comment by RobinHerbots** [comment]
I just use qunit for it.
Have a look at the qunit folder.
