### ISSUE TITLE
Bug with number mask (99 999 999)

### ISSUE THREAD

**Issue by ghost** [RobinHerbots/Inputmask#177]
Hi,

First, thanks for this awesome plugin, it's very useful.
However, i got an issue. When I try to create a mask (99 999 999), I can't get it work. Actually, I can type 7 numbers only...
For instance, please see http://jsfiddle.net/UQLWL/

Can you help me please ?

Thanks !

Olivier

**Comment by RobinHerbots** [comment]
I will have a look at it.

best regards, 

Robin

**Comment by RobinHerbots** [comment]
Hi Olivier, 

The issue is fixed.

best regards, 

Robin

**Comment by ghost** [comment]
Thanks a lot !

Regards,

Olivier
