### ISSUE TITLE
Caret position jumping randomly on Chrome 62 for Android 6.0

### ISSUE THREAD

**Issue by robertontiu** [RobinHerbots/Inputmask#1772]
Hey. I've noticed that there are a lot of issues about this behavior but I still couln't find a solution for it. Inputmask is a very useful plugin but if I can't use it on mobile browsers I'll be forced to find another option for masking inputs. 

I am using inputmask with react but I don't think the setup is influencing the outcome in any ways. Here are two examples that produce quite the same problematic behavior:

(new InputMask("[+99 ]99 99 99 99 [9]", {jitMasking: true, greedy: false})).mask(this.inputElement);

(new InputMask("numeric", {
			suffix: ",-",
			groupSeparator: ".",
			radixPoint: ",",
			placeholder: "0",
			autoGroup: true,
			digits: 0,
			digitsOptional: true,
			clearMaskOnLostFocus: false

		})).mask(this.inputElement);

Any help or info on how to fix this is highly appreciated.

**Comment by RobinHerbots** [comment]
Which version of the inputmask are you using?

**Comment by robertontiu** [comment]
Hey. I'm using 3.3.11

**Comment by RobinHerbots** [comment]
@liquidsoft , 

Can you retry with version 4.x from github

**Comment by robertontiu** [comment]
4.x works great. Many thanks for the help and for the awesome plugin :)

**Comment by mgomez** [comment]
como actualizo a la version 4x si uso npm?

**Comment by d4nc3r** [comment]
Will version 4.x be published to npm at all? I am not in a position to put 3rd party packages into our Prod app w/o them being accessible via package mgmt :(

**Comment by RobinHerbots** [comment]
@d4nc3r, @mgomez,

It will be published, but there are still some regressions to version 3.x. (datetime, regex, numeric) Or should I publish anyway?

**Comment by RobinHerbots** [comment]
@d4nc3r , 

I will release a beta version on npm.

**Comment by robertontiu** [comment]
As a side note, there were still some minor issues with 4.x so I decided to use an alternative for our production app. Inputmask is a very good prospect and with some larger browser coverage would be the most solid out there. So once again, thanks for putting the effort into it 👍

**Comment by RobinHerbots** [comment]
@liquidsoft , 

Would you be so kind to share which alternative you chose and what issues exactly hold you back to using inputmask?

**Comment by robertontiu** [comment]
Hi. As I remember there were some simillar issues on IPad and generally mobile Safari browsers with the carret jumping to other parts of the text. I ended up using imask (https://www.npmjs.com/package/imask) but it is fairly limited compared to inputmask and had to abandon some features that were initially intended.  Anyways, after a long run of development I can say that Safari on mobile is a big pain in the ass when it comes to UI/UX.
