### ISSUE TITLE
Invalid regular expression: /[0-9ï¼‘-ï¼™]/: Range out of order in character class

### ISSUE THREAD

**Issue by Chrifister** [RobinHerbots/Inputmask#1773]
Having difficulties getting inputmask 3.3.11 to work. Includes are:

jquery-3.2.1.js
datatables.js (version 1.10.16)
jquery-ui.js (version 1.12.1)
globalize.js
globalize.culture.en-CA.js
jquery.validate.js
additional-methods.js
inputmask.dependencyLib.jquery.js
jquery.inputmask.bundle.js

No errors on page load but a simple test calling:

`$('.phone').inputmask('(999)999-9999')`

causes:

Uncaught SyntaxError: Invalid regular expression: /[0-9ï¼‘-ï¼™]/: Range out of order in character class
    at new RegExp (<anonymous>)
    at insertTestDefinition (jquery.inputmask.bundle.js:1485)
    at defaultCase (jquery.inputmask.bundle.js:1524)
    at Object.analyseMask (jquery.inputmask.bundle.js:1607)
    at Object.Inputmask.analyseMask (jquery.inputmask.bundle.js:2858)
    at generateMask (jquery.inputmask.bundle.js:82)
    at generateMaskSet (jquery.inputmask.bundle.js:104)
    at HTMLInputElement.<anonymous> (jquery.inputmask.bundle.js:1372)
    at Function.each (datatables.js:10629)
    at Inputmask.mask (jquery.inputmask.bundle.js:1369)

Tried with the inputmask bundle file and basic inputmask file.

**Comment by Chrifister** [comment]
Looking through the file and some of the definitions had special characters in them. Fixing the definitions has fixed my problem. Works fine now.

**Comment by RobinHerbots** [comment]
@Chrifister , 

Ok great!
How did you obtain the files?

**Comment by Chrifister** [comment]
I downloaded the zip of the 3.3.11 release.

The changes I made are in inputmask.js (also worked in jquery.inputmask.bundle.js):

Line #1275 changed validator: "[0-9１-９]", to validator: "[0-9]",
Line #1280 changed validator: "[A-Za-zА-яЁёÀ-ÿµ]", to validator: "[A-Za-z]",
Line #1285 changed validator: "[0-9１-９A-Za-zА-яЁёÀ-ÿµ]", to validator: "[0-9A-Za-z]",

Shot in the dark but somehow those definitions resulted in an invalid regex trying to be created on line #1441 of inputmask.js. On that line, the following code:

new RegExp(maskdef.validator, opts.casing ? "i" : "")

was invalid because maskdef.validator value was "[0-9ï¼‘-ï¼™]". No idea how the definitions above resulted in that value. I don't have time to look through more closely and I only need basic functionality for a few masks. It's possible one of the includes before inputmask is somehow interfering. Since the original characters seem to be non-English character sets, which makes sense for localization, perhaps there's an issue with localization and/or Globalizer. Since we do not need localization and are dealing with English only, the changes will work for us.

So far it seems to be working for the masks I need.

**Comment by RobinHerbots** [comment]
@Chrifister, 

I guess it is an encoding problem.  I will close the issue for now. 

#1606

**Comment by vtalas** [comment]
hi @RobinHerbots 
I'm also facing this issue. It happens when I run it on `file:///` protocol. Workround is to use a webserver (e.g  `http-server`)

```
<!DOCTYPE html>
<html>
<head>
	<script type="text/javascript"   src="jquery-3.3.1.min.js"> </script>
	<script type="text/javascript" src="./node_modules/inputmask/dist/min/jquery.inputmask.bundle.min.js"> </script>
</head>
<body>

<input type="text" name="" class="xxx"> 

<script type="text/javascript">

	$(document).ready(function(){
 		$('.xxx').inputmask("99-9999999");  //static mask
	})
</script>
</body>
</html>
```

**Comment by andres-ripoll** [comment]
Hello, just add 'charset' property in the inputmask script tag

`<script type="text/javascript" src="jquery.inputmask.bundle.js" charset="utf-8"></script>`
