### ISSUE TITLE
dd-mm-yyyy HH:MM - 10 hours.

### ISSUE THREAD

**Issue by krbv** [RobinHerbots/Inputmask#1777]
Hi! 
With  inputFormat: "dd-mm-yyyy **HH**:MM"
I can't set 10 hours.

1940) HH: [ "[01][1-9]|2[0-3]... 
should be => HH:["[01][**0**-9]|2[0-3]..

**Comment by RobinHerbots** [comment]
@krbv, 

Thx for reporting!  I pushed the change.
