### ISSUE TITLE
define minimal length on dynamic mask

### ISSUE THREAD

**Issue by dizajnguru** [RobinHerbots/Inputmask#1778]
I try define mask for slovak mobile number with format `+421 9__ ___ ___`

my code:
```
$(input).inputmask('+421 \\9[99 999 999]',{
	'greedy':true,
	'placeholder':'________',
	'alias': 'numeric',
	'oncomplete': function () {
		$.ajax({
			...
		},
		success: function(data) {
			...
		}
	},
	'onincomplete': function () {
		...
	}
});
```

Everything is fine, but the mask is complete even when the entry is incomplete.

For example with my code:
input values= `+421 905 123 ___` // +421 9 is fixed char, 05 123 are entered numbers
inputmast result for this is complete, but its wrong. Its incomplete. I miss there checking minimum string length and for 2 days I'm trying to set it up.
Is it even possible? please help

**Comment by RobinHerbots** [comment]
@caesarSK , 

Can you try by  removing the alias entry.

**Comment by dizajnguru** [comment]
nope, wihtout change :(

**Comment by RobinHerbots** [comment]
@caesarSK , 

Can you provide a jsfiddle

**Comment by dizajnguru** [comment]
yes, here is [jsfiddle](https://jsfiddle.net/caesarSK/hntausmj/)

what I can:
- only numbers with specific format +421 912 345 678, where +421 9 is fixed value
- check string length - if the string is shorter => incomplete

**Comment by dizajnguru** [comment]
hi @RobinHerbots ,

is there a solution to my problem? do you know advise with this?

**Comment by RobinHerbots** [comment]
@caesarSK , 

Why do you add '+421 \\\\9[99 999 999]' and not '+421 \\\\999 999 999'

The [] make the entries optional

See https://jsfiddle.net/hntausmj/5/

**Comment by dizajnguru** [comment]
works :)
thx very much.
