### ISSUE TITLE
Problem with nodeName

### ISSUE THREAD

**Issue by arturcesarmelo** [RobinHerbots/Inputmask#1781]
I'd followed the instructions to use Inputmaks with webpack and now i'm facing this problem:

```console
Uncaught TypeError: Cannot read property 'nodeName' of null
    at Inputmask.mask (inputmask.js?f1d3:1325)
    at HTMLDocument.eval (Cnpj.vue?2408:14)
    at mightThrow (jquery.js?eedf:3583)
    at process (jquery.js?eedf:3651)
    ...
```

I've seen this  https://github.com/RobinHerbots/Inputmask/issues/1508 and i know that there's nothing wrong with the pattern of mask. I'v seen throughout web that many developer are solving this using ```$(document).ready()```. I'm using VueJS and my code is bellow:

```
<template>
	<div :class="'form-group col-md-' + (columns ? columns : 6)">
		<label>{{label}}</label>
		<input type="text" :v-model="model" class="form-control" id="cpf">
	</div>
</template>
<script>
	import Inputmask from 'inputmask';

	export default {
		name: 'inputCpf',
		props: ['columns', 'label', 'model', 'mask'],
		mounted() {
			Inputmask('999.999.999-99').mask(document.getElementById("cpf"));
		},
		data() {
			return {
				disabled: false
			}
		},
	}
</script>
```

Any help is welcome.

**Comment by RobinHerbots** [comment]
@arturcesarmelo , 

Can you verify that document.getElementById("cpf") returns the input.  Output the result to the console before calling inputmask.

**Comment by arturcesarmelo** [comment]
@RobinHerbots 
Thank you for open my eyes. In this component is everything ok, but i decided to check out the others and i found an id misspelled

**Comment by RobinHerbots** [comment]
@arturcesarmelo , 

You are welcome!
