### ISSUE TITLE
CSP nonce error

### ISSUE THREAD

**Issue by knoxcard** [RobinHerbots/Inputmask#1782]
Why are inline stylesheets being generated when that could be inside inputmask.css?

jquery.inputmask.bundle.min.js:9 Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'unsafe-inline' 'self' https://*.bootstrapcdn.com/ https://fonts.googleapis.com/ https://fonts.gstatic.com/ https://static.indospace.io/ http://dev-static.indospace.io http://dev.indospace.io http://dev-dispensary.indospace.io 'nonce-13ad641d-dbff-4d64-81a3-83c516eec2a8'". Note that 'unsafe-inline' is ignored if either a hash or nonce value is present in the source list.

**Comment by RobinHerbots** [comment]
@knoxcard , 

Correct, I will remove the css from the bundled file.
