### ISSUE TITLE
24 hour format resets 24:00 to 00:00

### ISSUE THREAD

**Issue by andreyvk** [RobinHerbots/Inputmask#1786]
Hi, 

First of all thanks for the great work!

This is probably not an issue for date/time, but it is an issue for certain cases (in insurance for instance) where user needs to input 24:00 instead of 00:00. How is it possible to override the default hh:mm mask so that "24:00" is a valid input?

**Comment by RobinHerbots** [comment]
@andreyvk , 

Which versiojn of the inputmask do you use?  I"m working on a new implementation for the datetime alias in version 4.x.

There you can define an inputformat like HHH (hours no limit, which allows entry of 24:00) , then you can set max option to 24:00.

There is still a lot things to test and to implement, but It already supersedes the old implementation.

You are welcome to try it out, so I can get some feedback, and I will help out when it doesn't work.

**Comment by andreyvk** [comment]
@RobinHerbots, thanks for the suggestion! Im using the latest in 3.x. I can definitely try the new version though. 

If I understand correctly I can just do:
```html
<input type="text" name="time" data-inputmask="'alias': 'HHH'" />
```
Is that it?

As i understand the new version is not production ready yet. However, we're not using inputmask for anything complex. Majority of uses falls onto numbers and rarely onto time masks (maybe smth else. Cant remember now). We have many clients using the system everyday so my concern is really about being stable.

**Comment by RobinHerbots** [comment]
@andreyvk , 

No more like 
```html
<input type="text" name="time" data-inputmask-alias="datetime" data-inputmask-inputFormat="HHH"  data-inputmask-max="24" />
```

You can also do it in version 3.x, but then you have to alter the definition validator in the date.extensions.

**Comment by andreyvk** [comment]
So there's no more `data-*` for html for version 4? Or is it only `data-inputmask`, which is deprecated?

**Comment by RobinHerbots** [comment]
@andreyvk , 

None, both are possible, .. also in version 3.x

**Comment by andreyvk** [comment]
@RobinHerbots oh ok. I was getting worried :) Big thanks for the support!

**Comment by mz87** [comment]
I also need an option to enter just time 24:00 (alias hh:mm), but I'm confused how to extend the inputmask.date.extensions.js to add new alias that will allow this without ruining default mask. 
Can you please help?

**Comment by Jan-ipb** [comment]
I have the same issue. I need the option to allow times to max: 24:00. 
In the documentation of datetime extension i found that inputFormat: HHH and max: 24 should work. But it only works if i use two inputs for Hours and Minutes. 
I found someone having the same issue here: 
https://stackoverflow.com/questions/52391659/how-to-define-hour-like-2400-and-dont-change-to-0000

https://jsfiddle.net/vy1jwuwn/50/

But no solution for this.
Please help

**Comment by toxpal** [comment]
I also need an option to enter 24 in some situations. I confirm that at least with v5, HHH doesn't work.

**Comment by RobinHerbots** [comment]
@toxpal ,  @Jan-ipb, 

In v5 try with "H2:MM"

https://jsfiddle.net/bq6ngrv3/2/

**Comment by toxpal** [comment]
Alright, let me test on my won project...

**Comment by toxpal** [comment]
Works fine for me

**Comment by SergioOrtiz4th** [comment]
I need the user to enter from 00:00 to 24:00 but 23:59 is the max, I already try max: 25 and nothing, I'v tried this regex ^(((([0-1][0-9])|(2[0-3])):?[0-5][0-9])|(24:?00)), but doesn't work either. H2:00 not working too, is there a way I could use this regex? or any better solution?
