### ISSUE TITLE
no way to select on focus and no option for that in documentation

### ISSUE THREAD

**Issue by robertkalinowski** [RobinHerbots/Inputmask#1787]
Such option exists in jquery.mask.js and works but jquery.mask.js plug-in does not give as good regex that I need as yours plugin Robin, just I miss this option or information how to make select on focus working...

**Comment by RobinHerbots** [comment]
@robertkalinowski , 

Can you make a jsfiddle with an example with jquery.mask.js.

**Comment by robertkalinowski** [comment]
Here you are:
https://jsfiddle.net/rob_kalinowski/mx6wkjcr/

**Comment by RobinHerbots** [comment]
@robertkalinowski , 

When you set positionCaretOnTab: false as option, you already get alike behavior when tabbing in.
But not when you click on it.  
I will add something alike.

**Comment by robertkalinowski** [comment]
thanks a lot, any estimate when this can be expected? rough estimate would be helpfull as do not know whether to wait or look for some alternative....

**Comment by tjfall3704** [comment]
I was having the same issue.   Your suggestion of using positionCaretOnTab: false worked for my needs.   Thanks

**Comment by RobinHerbots** [comment]
@robertkalinowski , @tjfall3704 , 

I added the positionCaretOnClick: "select" option to get the desired behavior.  (4.x branch)

https://jsfiddle.net/mx6wkjcr/13/

**Comment by robertkalinowski** [comment]
thanks a lot !!!
