### ISSUE TITLE
Japanese Dates

### ISSUE THREAD

**Issue by razor-1** [RobinHerbots/Inputmask#1788]
As part of adding Japanese localization to my project, I have been trying to find a way to set up my date inputmasks so that they will work with the common way that dates are formatted in Japan.  This is what I tried that got very close to working on 3.3.11:

```javascript
Inputmask.extendAliases({
    'jadate': {
        mask: 'y年1月2日',
        placeholder: '____年__月__日',
        alias: 'yyyy-mm-dd'
    }});
$('#birth').inputmask('jadate');
```

It works except the last field (for days) does not accept any input. Perhaps the issue is that there is no common separator?  I haven't found a working combination. Thank you

**Comment by RobinHerbots** [comment]
@razor-1 , 

Can you try with version 4.x (latest from github)

```
Inputmask.extendAliases({
    'jadate': {
        inputFormat: 'yyyy年mm月dd日',
        alias: 'datetime'
    }});
$('#birth').inputmask('jadate');
```

Also ceate a jsfiddle.

**Comment by razor-1** [comment]
thanks, that does seem to help: https://jsfiddle.net/szbtwc20/6/

Ideally I could use something other than the english 'y', 'm' and 'd' as placeholders but that doesn't seem to work in the above fiddle. but at least this is functional! thanks

**Comment by razor-1** [comment]
If there are docs on the new 4.x datetime, please point me to them so I can stop bothering you...

I noticed if I make the inputFormat to be 'yyyy.mm.dd' that the input doesn't skip over the '.' as it does with '/' or '-'

**Comment by RobinHerbots** [comment]
@razor-1 , 

I fixed the problem with the placeholder and also the . issue.  (See your fiddle)
I updated the readme.
