### ISSUE TITLE
input in mobile phone is Wrong

### ISSUE THREAD

**Issue by vladviolentiy** [RobinHerbots/Inputmask#1791]
site:https://nongrata.ga/test1.php

input phone number in Mobile google chrome is wrong. cursor often move to one symbols ago

**Comment by eXponenta** [comment]
Same bug.

**Comment by RobinHerbots** [comment]
@catvlad ,  @eXponenta , 

Retry by using version 4.x from github.

**Comment by pavlumik** [comment]
I have the same issue, in web browser (tried chrome and yandex browser) started on mobile devices. When input phone number cursor moves its position incorrectly when mask symbols (like ')' or '-') appeared.
Found issue on the version 3.3.8, but as verified the same behavior can be seen with 3.3.11 and 4.0.0-beta.14. Is there any configuration option which may help to overcome this issue? Thank you in advance!

**Comment by RobinHerbots** [comment]
@catvlad , @eXponenta , @pavlumik , 

Can someone provide a jsfiddle against the latest from github.  Also state which mobile device? Android version? IOS version? Which keyboard used?  Is predictive text enabled or not?

**Comment by mahnunchik** [comment]
The same issue

**Comment by WilixLead** [comment]
@RobinHerbots same issue on few android devices, Oppo Find 5 for example, android 6.0.1, google keyboard, tried with enabled and disabled predictive

**Comment by RobinHerbots** [comment]
Remove Phone alias #1981
