### ISSUE TITLE
Odd behaviour on backspace in middle of input (datetime)

### ISSUE THREAD

**Issue by zielinskikamil** [RobinHerbots/Inputmask#1793]
Hello,
I encountered odd behaviour when a user removes middle part of a date. I found it while playing with **datetime** alias but, it occurs on **dd/mm/yyyy** alias as well.

The problem:
When user type full date time e.g. 11/11/2111 22:33 and try to edit hours by selecting the second character of hours (11/11/2111 2**2**:33) and hits backspace, both typed hours are gone, resulting with 11/11/2012 **hh**:22. Please notice that user loses part of his inputted data.

The expected result would be to just remove one character and set in its place suitable placeholder. E.g.
11/11/2111 22:33 -> Select second hour character (11/11/2111 2**2**:33) -> hit backspace -> 1/11/2111 2**h**:33 (**h** should be highlighted and next typed digit should be placed there)

The things come even worst when user start hitting backspace multiple times.
STR:
11/11/2022 2**2**:22 -> hit backspace -> 11/11/2022 hh **:** 22 (colon become highlighted) -> hit backspace -> 11/11/2022 **h**h:22 -> hit backspace -> 11/11/202y hh:**2**2 -> hit backspace 11/11/20**2**y hh:m2  -> hit backspace -> 11/11/20yy hh:m**2** -> etc

Please notice that characters are highlighted and removed in an odd order.
The same issue occurs using 'dd/mm/yyyy' alias. You can reproduce it on [demo page](http://robinherbots.github.io/Inputmask/)

Issue with datetime alias can be reproduced [here](https://jsfiddle.net/u99mht64/)

Is there any solution or workaround for it?

**Comment by RobinHerbots** [comment]
@zielinskikamil , 

See #2163
