### ISSUE TITLE
add hungarian phone codes

### ISSUE THREAD

**Issue by vicsekm** [RobinHerbots/Inputmask#1794]
Hi, you have written a very useful plugin. I used it in all of my projects. I have written the Hungarian phone codes for it, and I use it in my projects. I send you the file feel free to merge it to you project if you wish.
Thanks for your work.
[phone-hu.txt](https://github.com/RobinHerbots/Inputmask/files/1639192/phone-hu.txt)

**Comment by RobinHerbots** [comment]
@vicsekm , 

Great!  Thx!

**Comment by vicsekm** [comment]
Sorry, but made some mistakes in it. I attached the fixed file.
[phone-hu.js.txt](https://github.com/RobinHerbots/Inputmask/files/1650017/phone-hu.js.txt)

**Comment by RobinHerbots** [comment]
@vicsekm , 

No problem.  Thx for the update.
