### ISSUE TITLE
Max length for numeric digits

### ISSUE THREAD

**Issue by mimi1038** [RobinHerbots/Inputmask#1796]
Hi,
I have field where I have to input number. Now number can be integer or decimal, the limit is only seven digits regardless of whether it's an integer or decimal. Is there any parameter to limit the input to seven digits regardless of whether it's an integer or decimal?

**Comment by gavrilovanton** [comment]
I really need to! The max value of the field should be 100 000, and I don't want user to be able to input numbers longer like 100 000 000 000 000... Now, It's infinite. MAX and MIN params isn't a good and practical solution.

**Comment by twg-group** [comment]
`<input maxlength="10" />`

**Comment by Davilink** [comment]
see https://github.com/RobinHerbots/Inputmask/issues/1828
