### ISSUE TITLE
Problem with negative currency in 4.x 

### ISSUE THREAD

**Issue by pepsikus** [RobinHerbots/Inputmask#1798]
Hi.
I have a problem with copying a negative amount from one input field to second, both masked as 'currency'.
At 1-st copy works fine, but at 2-nd isn't works properly (this is repeated cyclically). 
The digits in integer part are disappears (sets to 0).
This problem is existed only in 4.x branch (in 3.x works fine)
See examples:
(4.x) https://jsfiddle.net/61vu5afg/
(3.x) https://jsfiddle.net/f3nsoj1s/

Try to play with input to 2-nd field the several negative values one after another (-1250.47, -1252.47, -1300.01, -1300.05).

Thanks in advance.

**Comment by pepsikus** [comment]
I tested the 4.x jsfiddle just now.
It works fine since 4.0.0-100 version.

Many thanks to author for work.

**Comment by RobinHerbots** [comment]
@Pepsikus , 

There is still another issue when setting an initial value and start editing. But I'm working on that.
