### ISSUE TITLE
set an input readonly after applying a mask does not set the input to readonly

### ISSUE THREAD

**Issue by RobinHerbots** [RobinHerbots/Inputmask#18]

**Comment by Jaspal** [comment]
Hi,

When assign mask you can check if control has readonly then remove the mask 

Example
(function($) {
    $(document).ready(function() {
        $('.ssnmasked').focus(function() {
            if ($(this).attr("readonly")) {
                $(this).inputmask('remove');
            }
            else {
                $(this).inputmask('SSNMasked');
            }
        }).blur(function() {
            $(this).inputmask('remove');
        });
    });
})($);

It's work for me

**Comment by RobinHerbots** [comment]
Yes, I know but this doesn't cover the case when you have already added the
mask and want to set it readonly afterwards.

Actually my other plugin  jquery.readonly handles all this automatically.
 Readonly blocks all events, asp.net validators, ... and re-enables
everything when removing the readonly.

2012/5/9 Jaspal <
reply@reply.github.com

**Comment by RobinHerbots** [comment]
This issue will be solved together with issue 36

If you want this functionality know, you can use the jquery.readonly plugin
