### ISSUE TITLE
Currency mask

### ISSUE THREAD

**Issue by anteksiler** [RobinHerbots/Inputmask#180]
Hi there,

I would like the mask to add commas to numbers to represent currencies, for example:

If the user enters 1000, it should be converted to 1,000

and the user enters 1000000, it should be converted to 1,000,000

Is this possible?

**Comment by anteksiler** [comment]
I tried using:

```
.inputmask("decimal", { digits: 3 });
```

but it literally displays "decimal" on the input :D

**Comment by RobinHerbots** [comment]
Hi Ant,

This should do it:
    $('#inputId').inputmask("decimal", { autoGroup: true });

Btw don't forget to include the numeric.extensions.

best regards,

Robin

2013/2/28 Ant Eksiler notifications@github.com

**Comment by anteksiler** [comment]
Thanks for the help Robin.
