### ISSUE TITLE
Not able to input 31.12. in DD.MM date input in v4.x

### ISSUE THREAD

**Issue by johakr** [RobinHerbots/Inputmask#1803]
Hi,

using the following config

`
alias: 'datetime',
inputFormat: 'DD.MM.YYYY',
`

one is not able to input the 30rd or 31rd of december (e.g. 31.12.2017). 

Same issue for `DD.MM.` format.

It seems that there is something broken with the valid date check.

Issue occurs in current version of v4. It doesn't occur in #fe8eecd48f746ba2e2468f3d7a1ee6dea8a1cd7e

**Comment by RobinHerbots** [comment]
@johakr , 

It has something to do with the dots in-between.  I will need to verify that.
