### ISSUE TITLE
Problem with appearing mask

### ISSUE THREAD

**Issue by ramax495** [RobinHerbots/Inputmask#1804]
There is a problem in Opera on Androind and in Chrome on Windows 10. If form has several fields mask is not appeared when you go to masked-fileld from previous field by pressing next-button (→) on android or TAB-button on desktop.
Anf when you start enetering symbols, the mask has been appeared. And if mask contains other symbols (for example country-code in phone-mask) users usually enter it twice.

**Comment by RobinHerbots** [comment]
Which version do you use?

**Comment by ramax495** [comment]
The last one from github.
Version: 4.0.0-100

**Comment by RobinHerbots** [comment]
@ramax495 , 

Do you also have this on the demo page?

**Comment by ramax495** [comment]
yes.
https://olimpstar.ru/catalog/item/nike-fs-lite-run-4-852435-002/
press button "Купить в 1 клик" and form will appear.

**Comment by RobinHerbots** [comment]
@ramax495 , 

Why are you setting showmaskonfocus: false ?

**Comment by ramax495** [comment]
@RobinHerbots 
Thanks a lot! It's not my code and I haven't noticed this option...Sorry!
