### ISSUE TITLE
inputmask is not a function

### ISSUE THREAD

**Issue by nzulfigarov** [RobinHerbots/Inputmask#1805]
```

import validator from "../../vendors/bootstrapvalidator/dist/js/bootstrapValidator.min.js"
import InputMask from "inputmask"
import axios from "axios"
export default {
    name: "login",
    mounted: function() {
        "use strict";
        $(document).ready(function() {
          $('#phone').inputmask('+7 (999) 999-99-99');
        });
    },
};

```

this snippet give me
```
30.js:1654 Uncaught TypeError: $(...).inputmask is not a function
    at HTMLDocument.<anonymous> (30.js:1654)
    at fire (30.js:7792)
    at Object.fireWith [as resolveWith] (30.js:7922)
    at ready (30.js:8142)
```

Im new at Vue.
so if i use this
`var im = new Inputmask("99-9999999");
im.mask(selector);`
its work perfectly, but i cannot access to simple 
`$(selector).inputmask('unmaskedvalue');`
so only way i can unmask value is
`var unformattedDate = Inputmask.unmask("23/03/1973", { alias: "dd/mm/yyyy"}); //230319`
how turn on inputmask function?
p.s sry for eng.

**Comment by RobinHerbots** [comment]
import Inputmask from "inputmask" does not include the jquery.inputmask plugin.

You will need to also import the jquery.inputmask.
