### ISSUE TITLE
How to integrate to Visual Studio 2013?

### ISSUE THREAD

**Issue by Markowitz1** [RobinHerbots/Inputmask#1807]
Hi Robin,
I am very fresh in web programming.
I need to use following Currency Inputmask codes.
https://jsfiddle.net/theandybob/t37m0txu/

I have downloaded Inputmask-4.x files into my computer.
I need detailed explanation step by step how I can intagrate downloaded files into my Visual Studio 2013 asp.net project.

So please explain me step by step what I have to the with downloaded files.
Visual Studio 2013 provides me Jquery 3.3.1. 
Thanks in advance.

**Comment by RobinHerbots** [comment]
@Markowitz1 , 

There are several ways you can use to add the inputmask code, but as you use Visual studio 2013 and don't have much experience in web. Use the nuget package manager to install the inputmask package.

- Go to your project => right click on the project.  
- Search for something like manage nuget packages.
- A screen wil open from where you can search for packages.
- Find inputmask or jquery.inputmask (they are the same)
- Click install.
- After install a popup screen will open with some brief description how to use. 

Another simple way:
- copy jquery.inputmask.bundle.js from the dist folder from github.
- drop it in your scripts folder
- reference it with a script tag.

**Comment by Markowitz1** [comment]
It found two files by Robin Herbots. Which one I have to install?
https://prnt.sc/i7epig

**Comment by RobinHerbots** [comment]
Take the first one

**Comment by Markowitz1** [comment]
Install processis okey. What is next?
https://prnt.sc/i7erig

**Comment by RobinHerbots** [comment]
@Markowitz1 , 

Why did you choose an empty project?  Start with an MVC project of asp.net project.  That will be much easier.

**Comment by Markowitz1** [comment]
Please tell me what I should select here?
https://prnt.sc/i7ets3

**Comment by RobinHerbots** [comment]
I don't use VS2013 anymore, but it will be basic or internet app.  Show me the explanation of them

**Comment by Markowitz1** [comment]
https://prnt.sc/i7ex3h

**Comment by RobinHerbots** [comment]
Ok, if you don't need users with logins, ... pick basic, otherwise internet.  (I need to go to sleep ;-))

**Comment by Markowitz1** [comment]
Lets continue tomorrow. Thanks a lot.

**Comment by RobinHerbots** [comment]
@Markowitz1 , 

Ok, ... you can already add the package and try what you read in the popup!

**Comment by Markowitz1** [comment]
This is the screen after instalation. There is no pop up.
https://prnt.sc/i7ez7q

**Comment by Markowitz1** [comment]
Which one I have to install. 2143 download or 209056 download?
https://prnt.sc/i7f0tq

**Comment by RobinHerbots** [comment]
Both packages contain the same

**Comment by Markowitz1** [comment]
This is the screen after installation. No pop up opened here.
https://prnt.sc/i7f3b5

**Comment by Markowitz1** [comment]
This is the screen after inputMask installation.
https://prnt.sc/i7f75i

**Comment by Markowitz1** [comment]
I need to use **currency inputMask** right now, I want to use other inputMasks later.

**Comment by RobinHerbots** [comment]
Did it work out?

**Comment by Markowitz1** [comment]
https://prnt.sc/i7pkyn

**Comment by Markowitz1** [comment]
Please tell me what is wrong here?
https://prnt.sc/i8bl4h

**Comment by RobinHerbots** [comment]
@Markowitz1 , 

Have a read at https://github.com/RobinHerbots/Inputmask#classic-web-with-script-tag

**Comment by Markowitz1** [comment]
Fail again.
https://prnt.sc/i8q7du

**Comment by Markowitz1** [comment]
I have given all references but it is fail again. 
https://prnt.sc/i8qb6k

**Comment by RobinHerbots** [comment]
@Markowitz1 , 

What is the error?  I suggest you read some tutorial for using visual studio.  

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<input id="test1" name="test1"/>
<br/>
<script type="text/javascript" src="pathtojquery/jquery.js" charset="utf-8"></script>
<script type="text/javascript" src="pathtojqueryinputmask/jquery.inputmask.bundle.js" charset="utf-8"></script>
<script>
	console.log(navigator.userAgent);
	$("#test1").inputmask("currency"});
</script>
</body>
</html>
```

**Comment by Markowitz1** [comment]
I run this: https://prnt.sc/i8qk5l
And the error: https://prnt.sc/i8qk93

**Comment by Markowitz1** [comment]
I am succeded now :1st_place_medal: 
Thanks a lot for your support.
When I start to gain some money from my project I donate you :100:

**Comment by RobinHerbots** [comment]
@Markowitz1, 

Ok great ;-)

Only including the jquery.inputmask.bundle.js is sufficient.

**Comment by Markowitz1** [comment]
try

**Comment by Markowitz1** [comment]
I want to use € instead of $.
There are 4 results when I search "Currency" as you can see following picture.
https://prnt.sc/iasji7
Should I change these 4 results strings from $ to €?

**Comment by RobinHerbots** [comment]
$("#test1").inputmask("currency",{

prefix: "€"

});


Op di 6 feb. 2018 om 10:28 schreef Markowitz1 <notifications@github.com>:

**Comment by Markowitz1** [comment]
Thanks a lot... Very very thanks...

**Comment by Markowitz1** [comment]
I want to use point for thousand seperator.
I tried following code but it doesnt work. 

$("#test1").inputmask("currency", {
    groupSeparator: "."
});

**Comment by RobinHerbots** [comment]
Also specify the radixPoint.

Op di 6 feb. 2018 23:14 schreef Markowitz1 <notifications@github.com>:

**Comment by Markowitz1** [comment]
I want to use point for thousand seperator.
I want to use comma for decimal seperator.
Example: 1.234,56 €
Following code doesnt work.
$("#test1").inputmask("currency", {
    groupSeparator: ".",
    radixPoint: ","
});

**Comment by RobinHerbots** [comment]
@Markowitz1 , 

https://jsfiddle.net/aogoy853/

**Comment by Markowitz1** [comment]
Solved now thank you.
Probably last question.
Using document ready function is must or not?
$(document).ready(function () {
});

**Comment by RobinHerbots** [comment]
It is a must.  Read about it on the jquery website.

Op wo 7 feb. 2018 om 08:24 schreef Markowitz1 <notifications@github.com>:

**Comment by Markowitz1** [comment]
Last question;
I dont want user is able to enter below 1.234,56 €.
Is it possible to set minimum value to 1.234,56 € ?

**Comment by RobinHerbots** [comment]
Have a look at the readme for numeric.  Specify the min option

Op wo 7 feb. 2018 om 08:38 schreef Markowitz1 <notifications@github.com>:

**Comment by Markowitz1** [comment]
It says "Minimum value Default: undefined"
https://github.com/RobinHerbots/Inputmask/blob/4.x/README_numeric.md

**Comment by RobinHerbots** [comment]
so min : 1234.56

Op wo 7 feb. 2018 om 10:39 schreef Markowitz1 <notifications@github.com>:

**Comment by Markowitz1** [comment]
Perfect!
Another issue.
I need this;
min: 1234.56
value: min

**Comment by RobinHerbots** [comment]
You need to set it in the html.

Op wo 7 feb. 2018 om 11:27 schreef Markowitz1 <notifications@github.com>:

**Comment by Markowitz1** [comment]
**value: min** is possible in the html?

**Comment by RobinHerbots** [comment]
<input type="text" value="1234.56" />

Op wo 7 feb. 2018 om 11:31 schreef Markowitz1 <notifications@github.com>:

**Comment by Markowitz1** [comment]
I am looking for;
<input type="text" value="min from javascript" />
