### ISSUE TITLE
<input type= "number" is not working if the field is having any masking like ("999/999/999") in chorme Versions only.

### ISSUE THREAD

**Issue by senthilksp** [RobinHerbots/Inputmask#181]

**Comment by RobinHerbots** [comment]
Hi, 

I guess because type-"number" expects a number while the mask and placeholder are not real numbers.
Why do you use type="number"?

best regards, 

Robin

**Comment by senthilksp** [comment]
Hi Robin,

I am very happy for your quick reply. Thanks a lot.

I have defined input type="number" because when I am running my application in anroid versions (4.0 and above), I want to show numeric keypad alone. 

If I define input type="text", then samsung s3 gave me some problems like the keypad is jumping between number pad and character pad.  To avoid this difficulty, I am defining as input type="number".

Any fix or suggestions for this?

Regards,
Senthil.

**Comment by RobinHerbots** [comment]
I will have a look at it.

**Comment by espeiorin** [comment]
@senthilksp @RobinHerbots doesn't matter if you use input type="number", "text" or "tel", in android's default browser input mask will not work. If there's any thing I can do to help, please, let me know.
