### ISSUE TITLE
The input mask will get reset only when adding same digits for minutes (mm/dd/yyyy hh:mm xm ) in Android Chrome browser 

### ISSUE THREAD

**Issue by danukaw** [RobinHerbots/Inputmask#1812]
Hi RobinHerbots,

First of all thanks for the great work! 

We have been using inputmask version : 0.0.0-dev for all date/datetime input fields in our application. Recently we have uncounted an issue when adding minutes only in mobile web browsers ( e.g. mobile Chrome) 

The Issue is, when user tries to add same digit for minutes, the mask will get reset else it works just fine. I have done video as well. 

The Issue can be seen in below link.
https://drive.google.com/file/d/1IBeCdcx5xIbGb-b-YDFXRrmoBgmBxz2T/view?usp=sharing

If you could give us some kind of a idea to resolve this issue it would be a great help for us.

Thanks
Danunka

**Comment by alexisdiel** [comment]
Hi @danukaw ,

The alias `mm` (lowercase) is used for **months**, to **minutes** u need to use the `MM` format

**Comment by RobinHerbots** [comment]
@danukaw , 

I'm rewriting the datetime laiases.  See and try with version 4.x beta

**Comment by danukaw** [comment]
Hi RobinHerbots, I'l try with version 4.x beta and let you know.
