### ISSUE TITLE
is AM/PM possible in a datetime? Was this removed?

### ISSUE THREAD

**Issue by pbarney** [RobinHerbots/Inputmask#1815]
I recently upgraded from an earlier version and am having to rewrite all of my mask definitions.  Is "mm/dd/yyyy hh:mm xm" no longer an option? I can't seem to get AM/PM to work and the documentation doesn't match up with the release version at all.

Can you offer any help?

**Comment by RobinHerbots** [comment]
@pbarney , 

Which version do you use?

**Comment by RobinHerbots** [comment]
@pbarney , 

Added the definitions in the alias, and updates the readme

**Comment by pbarney** [comment]
I'm using version 4.0.0-100. Thanks for the update to the docs, and ESPECIALLY to the am/pm. That will help a lot. You need a tip jar!
