### ISSUE TITLE
"numeric-input-direction" mentioned in ReadMe section is not working

### ISSUE THREAD

**Issue by maheshkamalakannan** [RobinHerbots/Inputmask#182]
Hi Robin,

We were using your old version of jquery.inputmask.js which use '.browser' object. Since we have upgraded to jQuery-1.9.1.js where '.browser' object was deprecated, we were facing errors with the old version of jquery.inputmask.js. We have resolved this by upgrading to the recent version (v2.1) of jquery.inputmask.js. 

But the mask for currency value which was working in older version of inputmask.js is broken in the recent version. We are using the following plugins of recent version v2.1,
jquery.inputmask.js and jquery.inputmask.extension.js.

Below is the js script that we use to mask the currency field,

jQuery('#payAmount').inputmask('9,999.99', { numericInput: true });

The problem is - It does not allow to enter value from the right most caret position. But it allows to enter value from the caret before the decimal '.', which means it behaves as if the pattern is set to 9.99

Please let me know if this is a bug or am I missing anything.

Thanks,
Mahesh

**Comment by RobinHerbots** [comment]
Which version do you use exactly? I will verify this evening. V2.1.2 should word or take v1.3.4 from the 1.x branch
Best regards
Robin

**Comment by RobinHerbots** [comment]
You have to type the digit character to jump to the decimal part

**Comment by maheshkamalakannan** [comment]
Hi Robin, 
Thanks for the reply.
We are currently using v2.1.2. We tested in v1.3.4 and is not working in that too, same symptom is observed.

In earlier version when the numeric= true is set, the mask will place the cursor at the last position once the field get the focus. But now the cursor is positioned before the decimal point and also not allowing to enter more than one digit character before the decimal point.  As you said, when typing the first digit character, it jumps to the decimal part, but allows only one digit character to be typed before decimal point.

 Thanks in advance for your help.

**Comment by maheshkamalakannan** [comment]
The below script is working fine.

$("#payAmount").inputmask("decimal", { radixPoint: ".", autoGroup: true, groupSeparator: ",", groupSize: 3, digits: 2 });

But we would like to have the mask pattern shown to the user with the decimal point, for which we may need to use:

$('#payAmount').inputmask('9,999.99', { numericInput: true });

**Comment by RobinHerbots** [comment]
Hi @maheshkamalakannan ,

The latest 1.3.5 or 2.1.3 should fix the problem.  

You can also specify a radixPoint so the caret will first jump before the decimal (radix) point.  This allow you more to type as you pronounce a decimal nummer, ....  10 point 2  you type 10.2 and not 102

best regards, 

Robin

**Comment by maheshkamalakannan** [comment]
Thanks Robin. We have tested it in 2.1.3 and is working fine as expected.
