### ISSUE TITLE
Can't remove inputmask on focus?

### ISSUE THREAD

**Issue by mildmojo** [RobinHerbots/Inputmask#1820]
I'm trying to remove a currency mask when my input field is focused so it acts like a normal text box for editing, then restore the mask on blur for display. This doesn't seem to work for me; the input mask remains applied, even though I can record that the on-focus function fires.

```
  $('.cost input, .subtotal input').focus(function() {
    $(this).inputmask('remove');
  });
  $('.cost input, .subtotal input').blur(function() {
    $(this).inputmask('currency')
  });
```

I made a [reproduction codepen](https://codepen.io/anon/pen/oEBmbO) and tested in Firefox Developer Edition 59 and Chrome 63, both for macOS.

**Comment by RobinHerbots** [comment]
@mildmojo , 

Fixed in beta9

https://codepen.io/anon/pen/EQZzPe.

But in this case you could also use Inputmask.format on blur

**Comment by mildmojo** [comment]
Thank you!
