### ISSUE TITLE
jqlite is not defined in inputmask.dependencyLib.jqlite.js

### ISSUE THREAD

**Issue by sbm1990** [RobinHerbots/Inputmask#1822]
Hello I am getting this issue while using inputmask.dependencyLib.jqlite.js please help

**Comment by RobinHerbots** [comment]
Can you create a jsfiddle with your setup.

**Comment by RobinHerbots** [comment]
@sbm1990 , 

There seem to be a typo in the jqlite dependency lib.

**Comment by antonfrolovsky** [comment]
@RobinHerbots this error reproduce again if you install library from rails-assets.org

**Comment by RobinHerbots** [comment]
@antonfrolovsky , 

The change is only made in the 4.x branch.  I didn't push a new beta release yet for 4.x.  I'm not sure if rails-assets.org can fetch the beta.  (inputmask@next)

**Comment by antonfrolovsky** [comment]
@RobinHerbots got it, thanks for answer
