### ISSUE TITLE
Inputmask on Win10 with Touchscreen or even Chrome Touch Device Emulation not working

### ISSUE THREAD

**Issue by weisborg** [RobinHerbots/Inputmask#1824]
Some events are not getting to the mask library or something.  The browser appears to send touch events at least partially even when using the mouse due to the screen having touch capabilities.  When I click into the field with a mask the mask will either clear and when typing no mask gets applied, or the mask will remain and chars typed just move over like it is text in the field.  I see the same behavior when I turn on device emulation in Chrome on a PC with no touch devices. Even tabbing into the field with the keyboard doesn't work.

Things seem to operate fine on tablets and smartphones though and I see articles back a long while working on touch devices, so is touch on a PC messed up? I've even tried grabbing touch events and dispatching them as mouse events. Not much luck, but chaining a mouseenter before a mousedown improved a little.  Is there a specific order I could fire them, or specific events needed?  I don't think it will fix them all, but I'm up for trying anything at this point.

**Comment by RobinHerbots** [comment]
@weisborg , 

Can you provide an example on jsfiddle or is this reproducable on the demo page?  I tried in Chrome with desktop with touch and it seem to work without problems.
Which version did you use?

**Comment by weisborg** [comment]
Sorry for the delay, other stuff became a higher priority and I just got back to this.  When I have the user with the touchscreen monitor try the demo page, most of the masks work, but two of the masks don't and somehow even typed chars outside the bounds of the box- I think it was decimal and email.  The dates on that page worked though.  I was using 4.0.0-52 and -94.  The current build on the demo page was 4.0.0-beta.45 which is a little confusing on the numbering.  I replaced what I was using with it, but it still has issues on the PC with the touch screen monitor.  The issues occur even when the mouse is used since Windows 10 enters some type of different mode where touch events are sent for either.

It was nice having the datetime validations back...when they were removed before I had replaced them with a mask of numbers like 99/99/9999.  Now I use datetime with an inputFormat of mm/dd/yyyy, but neither one works right on the touch screen.  I used to set insertMode to false too to get a bigger cursor, but that doesn't work right with datetime and the cursor jumps all over the place.  There are some other date fields in the application that use both a mask and a datepicker that work fine though.  I think it is because the picker shows then puts focus back to the input so the mask gets the event it needs.  I tried emulating this behavior when touch events are received, but it didn't work.

**Comment by RobinHerbots** [comment]
@weisborg , 

Here a jsfiddle with the mask are there more options you add?

https://jsfiddle.net/vek9vaqh/2/

**Comment by weisborg** [comment]
clearComplete is true, placeholder is "mm/dd/yyyy".  I also use a class to set the value for all controls on the page like- $(".MyDateOnly").inputmask("datetime", { "clearIncomplete": true, "placeholder": "mm/dd/yyyy", "inputFormat": "mm/dd/yyyy" });

The input itself is- `<input type="text" autocomplete="off" class="form-control MyDateOnly" pattern="^\d{1,2}/\d{1,2}/\d{4}$" name="DOB" id="DOB" maxlength="10">`

The user with the touchscreen will be in sometime today or tomorrow and we can test some more.

**Comment by weisborg** [comment]
Well, that demo had those overflow issues, but for my date mask it ended up being another library that had some code to cleanup events. When it called .off(“input”) it broke the mask. I removed the calls from the other library and just have to remember not to call it twice on a control since no cleanup.
