### ISSUE TITLE
Error when setting float with 3 decimals after .

### ISSUE THREAD

**Issue by oldigor** [RobinHerbots/Inputmask#1825]
I'm using it to mask some numbers value.
These are the configuration:
```
function setCurrencyInputmask(element){
  $(element).inputmask({
    groupSeparator: '.',
    radixPoint: ',',
    prefix: "",
    alias: "currency",
    rightAlign: false,
    autoUnmask: true,
    nullable: false,
    removeMaskOnSubmit: true
  });
}
```

For exemplification, `setValue(X)` is the same as `.inputmask('setvalue', X)` or `.val(X)` (both give the same error).

```javascript
setValue(3);            // => 3,00 (Right)
setValue(3.3);         // => 3,30 (Right)
setValue(3.33);       // => 3,33 (Right)
setValue(3.333);     // => 3.333,00 (Wrong)
setValue(3.3333);   // => 3,33 (Right)
setValue(3.33333); // => 3,33 (Right)
...
```

**Comment by RobinHerbots** [comment]
@igorlemosvicente , 

The problem is I lose the initial type of the value.  jquery converts it to string.
So how to determine the initial intention.  Is the dot the radix point or is it a groupseparator?
I submitted a fix for vanilla & jqlite as dependencylib.  I still need to figure for jquery

**Comment by RobinHerbots** [comment]
@igorlemosvicente , 

Also fixed for jquery, but you need to use setvalue fn
