### ISSUE TITLE
Mask setting wrong value when numericInput is True

### ISSUE THREAD

**Issue by Tabgyn** [RobinHerbots/Inputmask#1826]
The masks are incorrect when setting a decimal value with numericInput as true

1500 should be 1500.00 but it is 15.00

https://jsfiddle.net/8Ldejeeq/87/

**Comment by RobinHerbots** [comment]
@Tabgyn , 

Try with version 4.x beta
https://jsfiddle.net/8Ldejeeq/94/

**Comment by Tabgyn** [comment]
Don't work with version 4.x beta

https://jsfiddle.net/8Ldejeeq/95/

**Comment by RobinHerbots** [comment]
Also see #1690

**Comment by Tabgyn** [comment]
I could suggest a way to align the cursor to the right of the decimal places, so I could remove the numericInput

**Comment by RobinHerbots** [comment]
@Tabgyn , 

Have a look at
https://jsfiddle.net/8Ldejeeq/108/

**Comment by Tabgyn** [comment]
How I limit the integers characters number with your last solution? I need limit this because the database.

**Comment by RobinHerbots** [comment]
@Tabgyn , 

https://jsfiddle.net/8Ldejeeq/122/

**Comment by Tabgyn** [comment]
Unfortunately no solution can be used. The numericInput option is not only keeping the caret at the end of the input, it is also causing the order of the values to be changed. Like 123456789.12 turns 654321789.12. Values above a million are incorrect.
The whole problem is around the numericInput option.
Unfortunately I'm not good with javascript, I did not even understand what your code does with this option.

**Comment by RobinHerbots** [comment]
@Tabgyn , 

I do not experience the behavior you describe when using the above jsfiddle.

**Comment by Tabgyn** [comment]
You are right, my fault. But I need to work on the onUnMask event because the value was losing the decimal places when performing the post.
I'll keep like this and keep testing, thank you Robin.

**Comment by fleonardelli** [comment]
Is there any solution for that? I have the same issue
