### ISSUE TITLE
Max length for decimal value

### ISSUE THREAD

**Issue by mouryaamit** [RobinHerbots/Inputmask#1828]
Hi, I am using currency alias, I want to limit user with max 9 digit non decimal and 2 digit decimal value. If I set max-length to 15 it allows user to enter 999,999,999,999 but i need user to stop at 999,999,999.00

**Comment by Tabgyn** [comment]
Maybe this can help u

https://jsfiddle.net/jLepcmsx/5/

**Comment by mouryaamit** [comment]
I tried to enter 12345678912 it gave me 345,678,912.21, it should give me 123,456,789.12

**Comment by Tabgyn** [comment]
Try this with 4.x

https://jsfiddle.net/jLepcmsx/10/

**Comment by mouryaamit** [comment]
closed #1828

**Comment by asyrafosman** [comment]
> Try this with 4.x
> 
> https://jsfiddle.net/jLepcmsx/10/

is the `integerDigits` option still exist in v5.x?

**Comment by RobinHerbots** [comment]
@asyrafosman ,

No the integerdigits option does not exist on 5.x.

**Comment by asyrafosman** [comment]
> @asyrafosman ,
> 
> No the integerdigits option does not exist on 5.x.

any other option/way we can use to limit the number of digits?

**Comment by asyrafosman** [comment]
> > @asyrafosman ,
> > No the integerdigits option does not exist on 5.x.
> 
> any other option/way we can use to limit the number of digits?

can we use the `max` option for that? 
so if 16 integer digits are equivalent to 9999999999999999 (9 repeats 16 times)

**Comment by RobinHerbots** [comment]
@asyrafosman,

Yes you can use the min & max option to limit the entry.
