### ISSUE TITLE
Unexpected token m in JSON at position 1

### ISSUE THREAD

**Issue by kevinkouketsu** [RobinHerbots/Inputmask#1829]
My jQuery code is: 
 $("input[name='date']").inputmask("99/99/9999",{ "placeholder": "dd/mm/yyyy" });

I've tried:
  $(":input").inputmask();
with data-inputmask in textbox too.

Im getting this error:
Uncaught SyntaxError: Unexpected token m in JSON at position 1

**Comment by RobinHerbots** [comment]
@shepher , 

Can you put this in a jsfiddle.  This will ease debugging.

**Comment by kevinkouketsu** [comment]
I don't know why but worked now.
Thanks
