### ISSUE TITLE
Show mask on keydown instead of on focus?

### ISSUE THREAD

**Issue by fdan4824** [RobinHerbots/Inputmask#183]
We have a situation where we are using "Over Labels." We are showing the field name inside the text input field. The problem is that when you click into field, the label disappears making it difficult to know which field you are in.

So, we found a solution to only have the label disappear on the first key stroke. The problem is that the input mask is showing up on focus and so until a key is pressed, both the mask and the label are appearing in the box.

Is it possible to have an option to have the mask only show up after the first keystroke?("keydown paste" is the event we are using to hide the the Over Label)

Thanks,
Dan

**Comment by RobinHerbots** [comment]
Hi Dan,
Can you make a jsfiddle which demostrates the problem. 
Best regards
Robin

**Comment by RobinHerbots** [comment]
Hi @fdan4824,

I think adding an option ShowMaskOnFocus is what you need.  I can add this which will be true by default, so I don't break the current behavior.  Putting it to false will not show the mask unless you type a valid char for the mask.

best regards, 

Robin

**Comment by fdan4824** [comment]
That sounds awesome. I apologize for the in responding and creating a
JSFiddle, but I am buried right now.

Thanks for your quick response!

Dan Fontenot

**Comment by RobinHerbots** [comment]
@fdan4824 ,

The latest version in the dist folder (2.1.4) contains the showMaskOnFocus.  (see also updated readme.)

In your case set showMaskOnFocus and showMaskOnHover to false.

best regards, 

Robin

**Comment by fdan4824** [comment]
I am not sure if I should respond to the closed issue or open a new issue. This now works great when clicking into a field. However, when tabbing into field, the mask still shows up.

Thanks,
Dan

**Comment by RobinHerbots** [comment]
Ow missed that one, ... I will submit the fix today

best regards,

Robin

2013/3/12 fdan4824 notifications@github.com

**Comment by RobinHerbots** [comment]
fixed ;-)
