### ISSUE TITLE
Bug when doing a .val with a negative number with a percentage input.

### ISSUE THREAD

**Issue by estraschnov** [RobinHerbots/Inputmask#1831]
See this http://jsfiddle.net/xfbc3Lrg/

For some reasons, setting the value with .val() works fine with positive numbers, but with negative numbers it shows '- %' and no number. On the other hand, typing a negative percentage works fine.

Any clue about what is going on?

**Comment by RobinHerbots** [comment]
Verified and this is solved in the current version.
