### ISSUE TITLE
Turkish character problem

### ISSUE THREAD

**Issue by midgard** [RobinHerbots/Inputmask#1832]
Hi,

I'm using email mask to my email field.

Problem is uppercase words.

Example:
I'm writing "YASİN@ADDRESS.NET" and mask converting this to "yasn@address.net"

I am losing character İ.

Can you help? Thanks.

(sorry for my poor English)

**Comment by RobinHerbots** [comment]
@midgard , 

 How do I type the I with a dot above?  Which character is this exactly?  Does there exist a lowercase equivalent of it?  Maybe you can try by removing the casing option in the email alias.  Have a look in inputmask.extensions.js.

**Comment by RobinHerbots** [comment]
@midgard , 
Can you try with the following
```
Inputmask({
            alias: "email",
            definitions: {
                "*": {
                    validator: "[0-9\uFF11-\uFF19A-Za-z\u0410-\u044F\u0401\u0451\u00C0-\u00FF\u00B5!#$%&'*+/=?^_`{|}~\-]"
                }
            }
        }).mask(selector);
```

**Comment by RobinHerbots** [comment]
@midgard , 

The Turkish charset should be supported now in the email alias.  (4.x beta)

**Comment by ufukcaneski** [comment]
> @midgard , Can you try with the following
> 
> ```
> Inputmask({
>             alias: "email",
>             definitions: {
>                 "*": {
>                     validator: "[0-9\uFF11-\uFF19A-Za-z\u0410-\u044F\u0401\u0451\u00C0-\u00FF\u00B5!#$%&'*+/=?^_`{|}~\-]"
>                 }
>             }
>         }).mask(selector);
> ```

it didn't work for me.
