### ISSUE TITLE
Using it as a jQuery extension under Laravel Mix environment

### ISSUE THREAD

**Issue by mmorote** [RobinHerbots/Inputmask#1833]
Hi, I've been trying to set inputmask to work as a jQuery(selector).inputmask(options) but after compiling (webpack under laravel mix settings), jQuery(selector).inputmask is undefined. How should I install and set my environment to work as desired? Are there aditional steps other than the ones you described in your 'Setup' section to make it work under Laravel Mix?

**Comment by RobinHerbots** [comment]
@mmorote , 

You also need to import jquery.inputmask.js

Also see #1795
