### ISSUE TITLE
Help : jquery.inputmask.bundle.min.js is not loading correctly via Webjar?

### ISSUE THREAD

**Issue by HachemZit** [RobinHerbots/Inputmask#1835]
i'm bit new to coding so my question is the same as the title. i'm working on javaEE web project in my pom.xml i have this.

          <dependency>
          <groupId>org.webjars</groupId>
          <artifactId>webjars-locator</artifactId>
          <version>0.30</version>
          </dependency>

        <dependency>
        <groupId>org.webjars</groupId>
        <artifactId>jquery.inputmask</artifactId>
         <version>3.3.1</version>
     </dependency>

and in my layout.html i loaded all my js paths like this :

     
     <script src="/webjars/jquery/jquery.min.js"></script>
    
    <script src="/webjars/bootstrap/js/bootstrap.min.js"></script>
    
    <script src="/webjars/fastclick/fastclick.js"></script>
    
    <script src="/webjars/nprogress/nprogress.js"></script>
    
    <script src="/webjars/jquery.inputmask/min/jquery.inputmask.bundle.min.js">
     </script>

     
     <script src="/js/custom.min.js"></script>

everything is working fine except jquery.inputmask , it's not working no effect on my input text (no masking no mouseover event )

**Comment by RobinHerbots** [comment]
@HachemZit , 

And do you have some code that calls the inputmask?

**Comment by HachemZit** [comment]
Thank you very much for trying to help me  here is the code when im using it but the input text is not changing acting like a regular input text no masking no mouseover event and also im using thymeleaf as template engine to view the page

   
              <div class="col-md-6 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>Input Mask</h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                      <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        <ul class="dropdown-menu" role="menu">
                          <li><a href="#">Settings 1</a>
                          </li>
                          <li><a href="#">Settings 2</a>
                          </li>
                        </ul>
                      </li>
                      <li><a class="close-link"><i class="fa fa-close"></i></a>
                      </li>
                    </ul>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                    <br />
                    <form class="form-horizontal form-label-left">

                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-3">Date Mask</label>
                        <div class="col-md-9 col-sm-9 col-xs-9">
                          <input type="text" class="form-control" data-inputmask="'mask': '99/99/9999'">
                          <span class="fa fa-user form-control-feedback right" aria-hidden="true"></span>
                        </div>
                      </div>
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-3">Phone mask</label>
                        <div class="col-md-9 col-sm-9 col-xs-9">
                          <input type="text" class="form-control" data-inputmask="'mask' : '(999) 999-9999'">
                          <span class="fa fa-user form-control-feedback right" aria-hidden="true"></span>
                        </div>
                      </div>
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-3">Custom Mask</label>
                        <div class="col-md-9 col-sm-9 col-xs-9">
                          <input type="text" class="form-control" data-inputmask="'mask': '99-999999'">
                          <span class="fa fa-user form-control-feedback right" aria-hidden="true"></span>
                        </div>
                      </div>
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-3">Serial Number</label>
                        <div class="col-md-9 col-sm-9 col-xs-9">
                          <input type="text" class="form-control" data-inputmask="'mask' : '****-****-****-****-****-***'">
                          <span class="fa fa-user form-control-feedback right" aria-hidden="true"></span>
                        </div>
                      </div>
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-3">TaxID Mask</label>
                        <div class="col-md-9 col-sm-9 col-xs-9">
                          <input type="text" class="form-control" data-inputmask="'mask' : '99-99999999'">
                          <span class="fa fa-user form-control-feedback right" aria-hidden="true"></span>
                        </div>
                      </div>
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-3">Credit Card Mask</label>
                        <div class="col-md-9 col-sm-9 col-xs-9">
                          <input type="text" class="form-control" data-inputmask="'mask' : '9999-9999-9999-9999'">
                          <span class="fa fa-user form-control-feedback right" aria-hidden="true"></span>
                        </div>
                      </div>
                      <div class="ln_solid"></div>

                      <div class="form-group">
                        <div class="col-md-9 col-md-offset-3">
                          <button type="submit" class="btn btn-primary">Cancel</button>
                          <button type="submit" class="btn btn-success">Submit</button>
                        </div>
                      </div>

                    </form>
                  </div>
                </div>
              </div>
              

 and it getting loaded but there is no effect on my input text

![vbc7f](https://user-images.githubusercontent.com/37044205/37024365-e79d7e50-2128-11e8-9e3b-9aa8e630c049.jpg)

**Comment by RobinHerbots** [comment]
@HachemZit , 

When using data attributes the inputmask is not autoapplied.  

Or you call in js  Inputmask.mask(selector)  or you can include the inputmask.binding.js

This is by choice as I don't like automagic, but prefer that the dev knows what, when and how the code is applied.

**Comment by HachemZit** [comment]
Thank you very much for your answers  , after adding inputmask.binding.js in static js of my project is working as intented but i did not find the right path to get it via webjar like the first file : <script src="/webjars/jquery.inputmask/min/jquery.inputmask.bundle.min.js"> any methods to get it like this?

**Comment by RobinHerbots** [comment]
Have a look at https://www.webjars.org/  and search for inputmask

Within the files you can find it.

**Comment by HachemZit** [comment]
Thank you very much , i hope you are having happy succesful life 
For the people wondering as it's said above just add the inputmask in the pom.xml file

         <dependency>
          <groupId>org.webjars.npm</groupId>
          <artifactId>inputmask</artifactId>
           <version>3.3.11</version>
           </dependency>

 and this line in js part 

     <script src="/webjars/inputmask/inputmask/bindings/inputmask.binding.js"></script>

**Comment by RobinHerbots** [comment]
@HachemZit , 

Thx!
