### ISSUE TITLE
Error when the value is erased using backspace

### ISSUE THREAD

**Issue by rafaelbco** [RobinHerbots/Inputmask#1841]
* JSFiddle: https://jsfiddle.net/rafaelbco/oy6vnpkz/2/
* Browser: Chrome Version 65.0.3325.146 (Official Build) (64-bit) on Linux
* Inputmask version: https://rawgit.com/RobinHerbots/Inputmask/4.0.0-beta.30/dist/jquery.inputmask.bundle.js

The error does not happen in the previous version: https://rawgit.com/RobinHerbots/Inputmask/4.0.0-beta.9/dist/jquery.inputmask.bundle.js

HTML:
```
<input type="text" id="my-input" />
```
JS
```
var inputMask = new Inputmask("99-99");
inputMask.mask(document.getElementById("my-input"));
```

Steps to reproduce:

1. Type "1" in the input element (or any other number).
2. Press backspace two times.

An error is displayed in the browser's console and the input mask stops working:
```
jquery.inputmask.bundle.js:123 Uncaught TypeError: Cannot read property 'slice' of undefined
    at getMaskTemplate (jquery.inputmask.bundle.js:123)
    at getBuffer (jquery.inputmask.bundle.js:346)
    at HTMLInputElement.keydownEvent (jquery.inputmask.bundle.js:669)
    at HTMLInputElement.ev (jquery.inputmask.bundle.js:643)
    at HTMLInputElement.dispatch (jquery.js:5183)
    at HTMLInputElement.elemData.handle (jquery.js:4991)
```

**Comment by RobinHerbots** [comment]
@rafaelbco , 

Thx for reporting, I did a major refactoring in some parts. 
I will fix this asap.

https://jsfiddle.net/oy6vnpkz/4/

**Comment by RobinHerbots** [comment]
Fixed!
