### ISSUE TITLE
CSS Unit Mask

### ISSUE THREAD

**Issue by maimairel** [RobinHerbots/Inputmask#1843]
Hi, 

I'm new to this plugin, it's great but I'm not sure how to add a mask for CSS length units.

1px, 2rem, 2.05em etc.

If I provide a regex for the mask then it doesn't work properly.
`[+-]?[0-9]+.?([0-9]+)?(px|em|ex|%|in|cm|mm|pt|pc)`

Please help! Thanks!

**Comment by RobinHerbots** [comment]
@maimairel , 

Please provide a jsfiddle first

**Comment by maimairel** [comment]
``$( this ).inputmask({
	regex: '[+-]?[0-9]+.?([0-9]+)?(px|em|rem|ex|%|in|cm|mm|pt|pc)'
});``

If I try typing 10px, then it would be 10ppx

**Comment by maimairel** [comment]
Here's a fiddle: https://jsfiddle.net/apz4uamk/5/

**Comment by maimairel** [comment]
It would be very useful if this is integrated as an extension 👍

**Comment by RobinHerbots** [comment]
@maimairel , 

Removing the [+-]? makes it working.  
I will verify why it doesn't work, but this is not trivial.  I'm currently working on the regex, as this improves the inputmask in general and is needed for the new datetime alias.

**Comment by RobinHerbots** [comment]
@maimairel , 

Send a pull request and I merge it.  Put it in inputmask.extensions.js.  (still I need to fix the issue ;-) )

**Comment by maimairel** [comment]
@RobinHerbots I'm completely lost on how to customize the extensions, so that's why I need help and can't submit a pull request :)

There are many issues using this regex, the units behind the decimal is behaving differently with each input.

Thanks!

**Comment by RobinHerbots** [comment]
@maimairel ,

```
  Inputmask.extendAliases({
        "cssunit": {
            regex: '[+-]?[0-9]+.?([0-9]+)?(px|em|rem|ex|%|in|cm|mm|pt|pc)'
        }
  });
```

**Comment by maimairel** [comment]
Thanks but that doesn't work properly. Like if you type 100px, it would become 100ppx.

Fiddle: https://jsfiddle.net/apz4uamk/21/

**Comment by maimairel** [comment]
10px -> 10ppx,
100px -> 100px
1000px -> 1000ppx

Even number of digits would return ppx, where odd number of digits would return px.

**Comment by RobinHerbots** [comment]
@maimairel , 

Of Course, I first need to fix the issue, so that this alias works correctly !!

**Comment by maimairel** [comment]
Thanks, waiting for the fix!

**Comment by RobinHerbots** [comment]
@maimairel , 

What actually happens when you type 10px that the p matches the .? in the regex.

10ppx is valid according the regex provided.  Why do you need the .? in the regex?

**Comment by RobinHerbots** [comment]
@maimairel , 

Ok, I see, it is for a decimal point.  Shouldn't the dot be escaped?  Otherwise the dot matches everything.
https://jsfiddle.net/apz4uamk/23/

**Comment by RobinHerbots** [comment]
@maimairel , 

Can you have a try with https://jsfiddle.net/apz4uamk/26/
