### ISSUE TITLE
Method oncomplete doesn't work correctly with jitMasking

### ISSUE THREAD

**Issue by k8adev** [RobinHerbots/Inputmask#1845]
When uses method oncomplete with jitMasking as true, it is triggered several times and not just when the mask is really completed.

Example
https://jsfiddle.net/keitoliveira/vf7b8jv5/9/

**Comment by RobinHerbots** [comment]
@keitoliveira , 

I will have a look at it.

**Comment by RobinHerbots** [comment]
@keitoliveira , 

Have a retry with the latest on github 4.x branch
https://jsfiddle.net/vf7b8jv5/10/
