### ISSUE TITLE
Element keeps the focus to itself in ie11

### ISSUE THREAD

**Issue by laurent-addstones** [RobinHerbots/Inputmask#1846]
Hello, I've encountered a strange behaviour while using inputmask in ie11 with the following code : 

`$(function () {`
`    $.each($("detailsForm input[id$=Amount]"), function(index, element) {`
`    $(element).inputmask({`
`        "alias": "decimal",`
`        "autogroup": 2,`
`        "allowMinus": true,`
`        "rightAlign": false,`
`        "groupSeparator": "\u00A0",`
`        "radixPoint" : "."`
`    });`
`var calculate = function() {`
`    $("#someAmount").val("4");`
`}`
`$.each($("#detailsForm input"), function(index, element) {`
`    $(element).blur(calculate);`
`});`

Here, once we click in and out of an input element, we go into an infinite loop in which calculate keeps getting called, and `$("#someAmount")` keeps the focus to itself, preventing the user to modify other inputs.

It only happens in ie11, and once I remove the inputmask, the behavior stops.
I tried to reproduce the bug in jsfiddle, didn't succeed. I am using the latest inputmask version (as of 03/18).

**Comment by pesinasiller** [comment]
same problem, did you find a solution?

**Comment by isaac-mercieca** [comment]
Hi, I am encountering the same issue, upon setting the value, on IE11 the element is taking focus, I have also managed to replicate the same issue on the demo provided in the description. Does anyone have any input were the issue is occurring please, this will help better to apply the solution. Thank you

**Comment by isaac-mercieca** [comment]
Further to my comment above the issue is occurring when updating the selectionStart and selectionEnd in the function caret. As in IE11 this is taking focus on the element.

**Comment by isaac-mercieca** [comment]
A pull request for the issue was added in #1979.

**Comment by dustinrpatterson** [comment]
I'm also having this issue in IE11
