### ISSUE TITLE
Unexpected Behavior With Special Characters

### ISSUE THREAD

**Issue by evandrobm** [RobinHerbots/Inputmask#1849]
I can't make it work on my web application, i have this:

$("#placa").inputmask("AAA-9999");

When user will type, after the first letter, the cursor jumps to the first number: A__-|____

If i remove the "-", and use $("#placa").inputmask("AAA-9999"); it works as expected, but with any special characters the bug happens.

I'm using version 3.3.11 and jQuery 3.2.1

**Comment by RobinHerbots** [comment]
@evandrobm , 

Have a look at https://jsfiddle.net/29yjvw7c/1/

Which files did you include? inputmask.js? or the bundle?  Extensions?
