### ISSUE TITLE
Problem with decimal mask and radix point

### ISSUE THREAD

**Issue by klzns** [RobinHerbots/Inputmask#185]
The first time I type the radixPoint in a decimal input it doesn't let me type any digits after the radixPoint.
I had to clear the radixPoint, type it again, and then type the decimals.

**Comment by RobinHerbots** [comment]
Hi Breno,

Can you specify the version you use and if there are any options given to
the mask.  In which browser did you test this.

best regards,

Robin

2013/3/13 Breno Calazans notifications@github.com

**Comment by klzns** [comment]
Hi, Robin,

I'm using Google Chrome; the inputmask version is 2.1.3 and I'm using like follow:

```
$(element).inputmask('decimal', { groupSeparator: '.', radixPoint: ',', autoGroup: true, repeat: 16 })
```

I'll update the plugin to see if it solves it self! If not, I'll let you know.

Thanks in advance,

Breno Calazans

**Comment by RobinHerbots** [comment]
Hi Breno,

Partially, ...there is some other issue in the decimal alias concerning the
radixpoint.

As soon that is fixed, I let you know.

Best regards,

Robin

2013/3/13 Breno Calazans notifications@github.com

**Comment by klzns** [comment]
Robin, for my issue, the update solved fine, thanks!

**Comment by ddesm59520** [comment]
Hi all,
I have some problems with the numerics Mask and negative mask. Withnumerics I can use my numkeybord point and when i use standard mask with negative like .inputmask('-999,99', { numericInput: true }); mask usage goes wrong. it align on left and if there was 50,50 it goes to -0505,0. I use some javascript to update mask on the fly from negative and not. I do prefer using numerics but I can't use negative and point numkeyboard.
can you help me. I can send you my class if you want. I want a numeric mask like 999,99 or -999,99 and when user clic on a nearby check box pass to 9999,99 or -9999,99.
Thx.

**Comment by RobinHerbots** [comment]
@ddesm59520 ,
In which browser do you test it?  I tested the negative mask and it works fine here.  But what you describe is what you get when a javascript error has occurred.  Can you make a jsFiddle which shows the problem?

best regards, 

Robin

**Comment by ddesm59520** [comment]
HI Robin,
 I am testing in IE10 (9 and 8 too) with jquery 1.7 in an aspx context in a override by a user control already existing. I custum it to use your jquery.input mask instead of eworld maskedtextbox.
I can send you a test project and the two classes which use jquery.inputmask and which I have put in a dll -> DomotiTools.
Do you agree this?

Thanks for your help.

Met vriendelijke groeten, | With kind regards, | Mit freundlichen GrÃ¼ÃŸen, | SincÃ¨res salutations,

David  DESMONS

**Comment by RobinHerbots** [comment]
Hi David,

Can you send a demo project in a zip.

best regards,

Robin

2013/3/19 ddesm59520 notifications@github.com

**Comment by ddesm59520** [comment]
Yes of course you have it, it is the .RAR
Maybe the antivir has delete it, I will resend it you with an asup at end, you will have to remove it.
Thx
