### ISSUE TITLE
Japan date

### ISSUE THREAD

**Issue by tranhuuhien1990** [RobinHerbots/Inputmask#1853]
Hi all,
I need to build a input mask as ______年__月__日, and i want a result as 平成１２年１２月１２日.
It's oke with inputmask, but I can't type 平成 from へいせい.

**Comment by RobinHerbots** [comment]
@tranhuuhien1990 , 

Can you create a jsfiddle so we can start from something.
My first guess, is that the regex in de inputmask.date.extensions.js does not allow the chars.  Have a look at the formatCode.

**Comment by tranhuuhien1990** [comment]
Thank you for rely, I use a shortcut key as replacement solution.

**Comment by RobinHerbots** [comment]
Can you elaborate a bit.  I'm willing to add support out-of-the-box but I need more feedback  and preferable an example to start from.
