### ISSUE TITLE
extreme buggy

### ISSUE THREAD

**Issue by VickG** [RobinHerbots/Inputmask#1855]
nothing works with this plugin ...
data-inputmask-clearmaskonlostfocus="false" 
does not honor that setting
does not initialize with jquery so I had to hack it to work
new InputMask().Initialize(document.querySelectorAll("#phone"),{
        mask: InputMaskDefaultMask.Phone, 
    });

**Comment by VickG** [comment]
when using auto-complete in browser, it does not respect that and just clears the field

**Comment by RobinHerbots** [comment]
@VickG , 

Are we talking about the same library?  The below syntax is not correct for the Inputmask.

``` 
new InputMask().Initialize(document.querySelectorAll("#phone"),{
mask: InputMaskDefaultMask.Phone,
});
```
