### ISSUE TITLE
How can I test "isComplete" within "onKeyDown"

### ISSUE THREAD

**Issue by NikolayVolkovR** [RobinHerbots/Inputmask#1856]
How can I test "isComplete" within "onKeyDown", for exapmle?

```
Inputmask({
            "mask": "(999) 999-9999",
            onKeyDown: function(buffer, opts) {
                ...
               // if (isComplete) do something
               // else do sometheing else
                ...
            }
        }).mask(input);
```
Thank you!

**Comment by RobinHerbots** [comment]
@NikolayVolkovR , 

What would be the difference as just acting on oncomplete?

**Comment by NikolayVolkovR** [comment]
When user enters complete value we enabling the "next button".
If user change value after complete, we should disable button.

So, onKeyDown we should check "is value still complete". If not, disable button.

**Comment by luckylooke** [comment]
I have found the possible way, but actually it does not work in my code.. here it is:
```javascript
   var testmask = document.getElementById("testmask");
   Inputmask("99999[-9999]").mask(testmask);
```
later on
```javascript
  testmask.inputmask.isComplete() // inputmask is not defined
```
inspired here: https://github.com/RobinHerbots/Inputmask/blob/3.x/qunit/tests_optional.js#L230

Why inputmask is defined on element in test, but not in my enviroment?  I have version 3.3.11 of inputmask lib.

Many thanks, happy coding :)

PS: I am against putting custom properties into native objects like DOM Element, so another way would be more appreciated. But until then at least this solution would be great, if it had worked. :)

**Comment by RobinHerbots** [comment]
@NikolayVolkovR , @luckylooke ,

Here is an example https://jsfiddle.net/ro93w486/9/

@luckylooke , 

Why are you against adding props to native objects.  It is not a prototype extension in this case.  It is a property on an instance.  I would say, it depends on how and the use case.

**Comment by luckylooke** [comment]
@RobinHerbots its because of possible conflicts with future native functionality or another lib, but your argument about instance is good enough, I did not realised at first glance. Thanks :)

**Comment by NikolayVolkovR** [comment]
@RobinHerbots , @luckylooke, 
Thanks a lot!
Nice coding! :-)
