### ISSUE TITLE
Cursor stays left of negative

### ISSUE THREAD

**Issue by TaylorRayHoward** [RobinHerbots/Inputmask#1857]
https://codepen.io/anon/pen/eMPOVK

Codepen for example.  When the input is null and you type a negative, the cursor stays on the left side of the negative.  This disallows someone to continue typing the number and having to either re-enter the negative 2 more times, or click into the input field specifically.

Additional Details: After more playing with it, if I remove the digitsOptional or groupSeparator it works as expected.  Also, it works correctly if there's a null in the field as opposed to a 0.

**Comment by RobinHerbots** [comment]
@TaylorRayHoward , 

I pushed a fix for this.  You can know continue typing.  See codepen.
