### ISSUE TITLE
jitMasking + disablePredictiveText causes android browser tab to stuck when clicked on "backspase"

### ISSUE THREAD

**Issue by ndeviant** [RobinHerbots/Inputmask#1862]
https://jsfiddle.net/ndeviant/j0jwewa1/

Everytime it shows when you finished input, and than press backspace, sometimes it appears if you press "backspace" button in the middle of input

- Tried on Meizu MX4 in chrome; 

and on browserstack on:
- Samsung Galaxy Note 4 Android, v4.4 Chrome;
- Nexus 6 Mozilla Android, v5 Mozilla;
- Motorola Moto G 2nd Gen Android, v5 Chrome;

In ios seems ok

You can achieve same result in desktop chrome, if you pick any mobile device in emulator in chrome, refresh the page (so disablePredictiveText will create "colormask"), and delete some numbers. Here is result:
![image](https://user-images.githubusercontent.com/25330222/38623177-9d66d272-3dad-11e8-9627-0c56b5510f36.png)

**Comment by RobinHerbots** [comment]
@ndeviant , 

This is on updated fiddle to reproduce the bug on a desktop browser. (which is good as this can be solved then)
https://jsfiddle.net/j0jwewa1/8/

**Comment by RobinHerbots** [comment]
@ndeviant , 

Can you retry with the current version.
You also need to include the inputmask.css when using the disablePredictiveText.

https://jsfiddle.net/j0jwewa1/9/

**Comment by ndeviant** [comment]
Checked on jsfiddle and on mine project with desktop, and android. Works like a charm.
Thank you, for your plugin and your work !
