### ISSUE TITLE
Question: How to disable caret positioning on click

### ISSUE THREAD

**Issue by igorlopasovsky** [RobinHerbots/Inputmask#1864]
Hey Robin,

Is it somehow possible to disable the click on input element? What I want to achieve is that user won't be able to change the caret position on click, it will always stay after the last entered character. I hide caret using CSS, that's working perfectly.

Many thanks

**Comment by RobinHerbots** [comment]
@igorlopasovsky , 

No this is currently not possible. I could add some extra case to the positionCaretOnClick option.
But why do you need that?  Would it not confuse the user when there is no caret?

**Comment by igorlopasovsky** [comment]
Hey Robin,

First, thank you very much for reply. To be honest, we would really welcome this feature. We are developing a web page for smartphones where our users need to enter a bank account number in special IBAN format. It's 26 characters, something like this **XX**XX **XXXX XX**XX XXXX XXXX XXXX where some of those characters (bold) are static. We need to make it completely bulletproof. It's very confusing when someone clicks in the middle and starts deleting or entering characters there. Because it's mainly for smartphones we don't need to see the caret at all. 

What do you think? :-)

**Comment by RobinHerbots** [comment]
@igorlopasovsky , 

I added an ignore option for positionCaretOnClick.  Have a try with the latest on github

**Comment by igorlopasovsky** [comment]
Thank you so much Robin, all working perfectly :)
