### ISSUE TITLE
Documentation: main distribution and extensions

### ISSUE THREAD

**Issue by pedrofurla** [RobinHerbots/Inputmask#187]
The README doesn't make it very clear what should be downloaded for using the main .js and the extensions one. 

The file in the dist/ dir contains .bundle extension, and the referred one in doc doesn't contain such extensions. There are three files in the js/ directory containing 'extension', which is a bit confusing.

**Comment by RobinHerbots** [comment]
@pedrofurla , 

I will update the readme. (a bit)

best regards, 
Robin

**Comment by RobinHerbots** [comment]
@pedrofurla,

I updated the readme in the usage section.

You may always contribute to the readme or get started in the wiki pages.

best regards, 

Robin
