### ISSUE TITLE
set value on field dont working

### ISSUE THREAD

**Issue by victortassinari** [RobinHerbots/Inputmask#1871]
I have a mask for money, in the format: R$ 1.000,00, in which the numbers already enter formatting by the cents (before the comma, from right to left).

I was able to configure the mask perfectly, including working on android devices. But I can not set a dynamic value for the input, the mask does not apply correctly.

Here's an example in jsfiddle:
https://jsfiddle.net/t1cmdyL6/

**Comment by RobinHerbots** [comment]
@victortassinari , 

I will look into this.
Btw the androidHack is renamed to disablePredictiveText and as value true

**Comment by RobinHerbots** [comment]
#1826 #1690

**Comment by victortassinari** [comment]
Not yet found a solution.

**Comment by RobinHerbots** [comment]
It's more a question of being very busy.  But i'm working on it

Op di 8 mei 2018 19:15 schreef Victor Tassinari Martins <
notifications@github.com>:

**Comment by RobinHerbots** [comment]
@victortassinari , 

Have a retry with the current ;-)
