### ISSUE TITLE
Fast typing text

### ISSUE THREAD

**Issue by alexdpts** [RobinHerbots/Inputmask#1872]
When i fast typing text, symbols appear at the right of the cursor. How can i fix it?

**Comment by RobinHerbots** [comment]
@alexdpts , 

Can you provide some extra info concerning the mask used, the version, os , browser

**Comment by alexdpts** [comment]
eg,  
data-inputmask="'alias': 'email'", or data-inputmask="'alias': 'phone'"
or manually created alias 'message' 
`message: {mask: "*{20,1000}",greedy: false,definitions: {"*": {validator: "[а-яА-ЯёЁa-zA-Z0-9\.\ \,\:\;\*\+-?\n]"}},onUnMask: function(maskedValue, unmaskedValue, opts) {return maskedValue;},inputmode: "verbatim"}`
os: windows 8.1 pro 64bit
browser: Google Chrome 65.0.3325.181 64bit
inputmask version: 4.0.0-beta.51    
Short video here: [https://drive.google.com/file/d/1bLw36IsekaNhLTv9GluOhUUQe2GbGeE1/view?usp=sharing](https://drive.google.com/file/d/1bLw36IsekaNhLTv9GluOhUUQe2GbGeE1/view?usp=sharing)

**Comment by RobinHerbots** [comment]
In which device is this. A touch device?

**Comment by alexdpts** [comment]
No. Notebook. Keyboard.
On touch devices it's ok - can not typing so quickly

**Comment by RobinHerbots** [comment]
@alexdpts , 

Does the notebook supports touch?  Which notebook is it?

**Comment by alexdpts** [comment]
Notebook supports touch. Asus Taichi 21. 
Problem arises when typing from hardware keyboard in "one screen" mode (when second screen with touch is off)

**Comment by RobinHerbots** [comment]
@alexdpts , 

Thx for the feedback.  Can you send the useragent string you get in the browser.

**Comment by RobinHerbots** [comment]
@alexdpts , 

Ok I can reproduce the behavior.

**Comment by RobinHerbots** [comment]
@alexdpts , 

Can you retry with version 4.0.0.0-beta.54

**Comment by alexdpts** [comment]
Thank you. I will try/
Useragent string: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36

**Comment by RobinHerbots** [comment]
@alexdpts , 

Does it work?

**Comment by alexdpts** [comment]
Yes, thank tou, but sometimes (rarely) cursor is skips over one "_" symbol in mask placeholder.
Can look 'li_ke this', for example.

**Comment by RobinHerbots** [comment]
@alexdpts,
Hmm ok , I will have another look at it and try to reproduce.

**Comment by alexdpts** [comment]
I noticed this 2 or 3 times from about 100 on the fields with the usual text masks.
for me it's not critical

**Comment by RobinHerbots** [comment]
@alexdpts , 

I'm going to close this one
