### ISSUE TITLE
Stuck before the @ on alias email

### ISSUE THREAD

**Issue by henriquecm** [RobinHerbots/Inputmask#1878]
If I type @ it gets erased and replaces by the mask @.
If I put the caret after the @, the mask adds another @ after the text. eg. `text@text@_._`

**Comment by RobinHerbots** [comment]
@henriquecm , 

Which version are you using and on which platform/browsr?

**Comment by henriquecm** [comment]
Inputmask version: 3.3.11
Android: 6 (Marshmallow)
Chrome 66

**Comment by henriquecm** [comment]
Just tested the last beta, and worked fine.

**Comment by RobinHerbots** [comment]
@henriquecm , 

Great!
