### ISSUE TITLE
ClearOnLostFocus Not Working

### ISSUE THREAD

**Issue by arielrz** [RobinHerbots/Inputmask#188]
Hi Robin, first... Excellent Job !!!!!!
And now the problems... ;-)
May be I'm doing some wrong, but try and try and didnt find anything wrong...
With the following setting, I think that the mask must clear on change textbox focus, but not... I typed 1234.5, correctly the textbox show me $ _1,234.5_ I think that when I press TAB the textbox must show 1,234.5 or $ 1234.5 or 12345, but not still show me the same "$ _1,234.5_"

$("#pipo").inputmask("$ 99,999.99", { numericInput: true, clearMaskOnLostFocus: true, radixPoint: '.'});

http://jsfiddle.net/KeMqg/2/

Thanks in advance.

**Comment by RobinHerbots** [comment]
@arielrz ,
The clearMaskOnLostFocus, only removes the mask when nothing is entered.  Ex for date removes dd/mm/yyyy when losing focus, nothing more.  

To have what you describe above you need to remove the mask on blut.

best regards, 

Robin

**Comment by arielrz** [comment]
Thanks !!! I'm do that.
