### ISSUE TITLE
Phone number with Optional Area Code

### ISSUE THREAD

**Issue by weisborg** [RobinHerbots/Inputmask#1884]
I think the normal Phone mask isn't complete yet from what I can tell and/or has no US validation at the moment, so I've been making my own.  Usually I've been doing just a mask of "(999) 999-9999".  Some data in my latest project is missing Area Code though and I need to allow either, so when read into an input the mask messes those up and clears it since incomplete.  Now, I'm trying this mask:

`$(".PhoneMask").inputmask("[\\(999\\) ]999-9999", { "clearIncomplete": true, "numericInput": true, "placeholder": ' ' });`

This seems to work ok, but has a few problems.  I can tab out of the input and have it completed without an area code, but it still renders the "(   ) " in front of the numbers even though it is optional.  I guess since my mask was a little more complicated I had to escape each of the parentheses too otherwise one of them rendered on the end of the string...possibly do to them meaning groups or something to the library.  The insertMode cursor is confusing on this too and usually for fields like SSN and such I set it to overwrite cursor so users can see where they are inputting easier.  Doing that with this only lets me type the right most char though.  Is there a better way to do this or maybe using the Regex mask that is back in?  I'm probably confusing it with the optional on the left, but the documentation showed it used in the middle too, so I figured it would allow it if I set numericInput so it types from the right.

**Comment by RobinHerbots** [comment]
@weisborg , 

Try with this mask

```
 Inputmask(["999-9999","\\(999\\) 999-9999"], { "clearIncomplete": true, "numericInput": true, "placeholder": ' ' }).mask("test3");
```

**Comment by weisborg** [comment]
That works pretty slick...I guess I never realized an array could be passed...probably scanned right by it in the documentation. Thanks.
