### ISSUE TITLE
Multiple masks starting with static characters

### ISSUE THREAD

**Issue by xaqtr** [RobinHerbots/Inputmask#1886]
For implementing IBAN masking I defined multiple masks for each countrycode like this:
`var masks = ["BE9{2} 9{4} 9{4} 9{4}", "BG9{2} 9{4} 9{4} 9{4} 9{4} 9{2}"]`

However I found that it won't work as expected. Only the first mask is used. In this case the "BE" can't be deleted, so I am just allowed to type the first mask. 

So any ideas how I can make this work or any other suggestions for this concrete problem?

**Comment by RobinHerbots** [comment]
@xaqtr ,

set the keepStatic option to false

```
Inputmask(["B(E|e)9{2} 9{4} 9{4} 9{4}", "B(G|g)9{2} 9{4} 9{4} 9{4} 9{4} 9{2}"], {
            keepStatic: false,
            casing: "upper"
        }).mask("test2");
```
