### ISSUE TITLE
How can I fix a character after numbers?

### ISSUE THREAD

**Issue by maxvictor** [RobinHerbots/Inputmask#1887]
Hello, I got an input named by "workload" and i want to fix the character "h" at the end of numbers.
I almost did it, but when I put "h" on mask it gives me 2 slots, not the character "h".
The code is:
```
$(document).ready(function () {
    $("#workload").inputmask({
        mask: ["99[9]"],
        placeholder: " ",
    });
});
```

So I only want to put an "h" at the end of the input.

**Comment by RobinHerbots** [comment]
See readme for escape special Mask chars

**Comment by RobinHerbots** [comment]
See readme
