### ISSUE TITLE
Both date and time in same masked textbox

### ISSUE THREAD

**Issue by CryptoTT** [RobinHerbots/Inputmask#1888]
Hello.

I can't seem to figure out how one would mask for both a date and a valid 24 hour format in same textbox. like "dd/mm/yyyy hh:mm", but this does not work.

Thank you in advance.

**Comment by RobinHerbots** [comment]
Which version of the inputmask are you using?

**Comment by CryptoTT** [comment]
jquery.inputmask.bundle.js:
Version: 3.3.11 and init them this way:
`$(":input[data-inputmask-mask]").inputmask();
        $(":input[data-inputmask-alias]").inputmask();
        $(":input[data-inputmask-regex]").inputmask("Regex");`
and tried
`<input data-val="true" data-inputmask-alias="mm/dd/yyyy hh:mm" data-val-required="Required" type="text" />`
which did not work.

**Comment by CryptoTT** [comment]
If you by any chance would have a jsfiddle example using data-inputmask attribute and datetime with 24 hour format, then I would love to see it.

**Comment by RobinHerbots** [comment]
@CryptoTT , 

Using Inputmask 4.x
https://jsfiddle.net/vy1jwuwn/

**Comment by RobinHerbots** [comment]
@CryptoTT ,

Using data attributes
https://jsfiddle.net/vy1jwuwn/1/

**Comment by CryptoTT** [comment]
Thank you so much, I can't believe that I could not get that to work, I feel kind of dumb right now.
Can the min, max value(datetime) be passed in data attributes too?
`<input data-inputmask-alias="datetime" data-inputmask-inputformat="dd/mm/yyyy HH:MM" data-inputmask-max="16/05/2018 11:10"/>`
above data-inputmask-max does not register, thats why I ask :)

**Comment by RobinHerbots** [comment]
@CryptoTT , 

Make sure to use version 4.x (beta).  Yes you can pass the min and max via data-attributes.

**Comment by CryptoTT** [comment]
I am unable to get the min property to work:
https://jsfiddle.net/vy1jwuwn/5/
The reason is that Im going to try and link it with anoter textbox, aswell as putting a max and min limit on them.

**Comment by RobinHerbots** [comment]
@CryptoTT ,

Have another try, ... i made some updates

**Comment by CryptoTT** [comment]
`<input data-inputmask-alias="datetime" data-inputmask-inputformat="mm/dd/yyyy HH:MM" data-inputmask-min="05/05/2018 11:10"/>`
Well, it kind of works, is it possible to first start filtering process when mm/dd is entered, as when year is not input only dates after 05 and monts after 05 is valid, meaning when no year entered , it should be understood as 9999?, is a tooltip feature maybe possible to display variables and limits when they are met?

**Comment by RobinHerbots** [comment]
@CryptoTT , 

Aah, of course, it should only take day and month into account when the year gets entered

**Comment by CryptoTT** [comment]
Currently it still takes day and month before the year is entered, so lowest date that can be entered is 05>/05>2018 when I use above example.

**Comment by RobinHerbots** [comment]
@CryptoTT , 

And have another try, ...

**Comment by CryptoTT** [comment]
Works perfectly now.
