### ISSUE TITLE
autoUnmask drops 9's from the unmasked numeric value

### ISSUE THREAD

**Issue by vanomania** [RobinHerbots/Inputmask#189]
Similar to the [README](https://github.com/RobinHerbots/jquery.inputmask#set-a-value-and-apply-mask) example:

```
<input type="text" id="contactNumber" 
    data-inputmask="'mask': '(999) 999-9999[ 9999]', 
    'placeholder':'(999) 999-9999 9999',
    'autoUnmask' : true, 
    'clearMaskOnLostFocus':true"
    onchange="alert($('#contactNumber').val())"/>
```

Entering a value of '5559973087' properly renders the input field as (555) 997-3087, but the alert renders the value as '55573087'

![input-field](https://f.cloud.github.com/assets/3915102/278703/203e9e0c-90f0-11e2-950e-a379c419c731.png)

![alert](https://f.cloud.github.com/assets/3915102/278705/3c85e2be-90f0-11e2-8f0a-556b8c00ebe3.png)

**Comment by RobinHerbots** [comment]
@vanomania ,

I will fix this asap.

best regards, 

Robin

**Comment by RobinHerbots** [comment]
@vanomania ,

The latest version fixes the issue.  Although specifying a placeholder the same as the mask can give strange results.

The optionals will not be cleared when not filled in as the 9999 from the placeholder are valid inputs for the mask.

best regards

Robin

**Comment by vanomania** [comment]
@RobinHerbots the 9 is still getting dropped with the latest,  but changing the placeholder to x's worked.  thanks!

**Comment by RobinHerbots** [comment]
Are you sure you took the latest version?  Cleared the browser cache.

Can you create a jsFiddle which shows the problem.

best regards,

Robin

2013/3/20 vanomania notifications@github.com

**Comment by RobinHerbots** [comment]
I updated the code but didn't update the version, ... so maybe try again
with the latest version

2013/3/21 Robin Herbots robin.herbots@gmail.com
