### ISSUE TITLE
positionCaretOnClick doesn't work on iOS

### ISSUE THREAD

**Issue by yustnip** [RobinHerbots/Inputmask#1891]
When click to empty space inside the masked field nothing happens on iOS (Safari, Chrome). On Android and desktop browsers it works well.

![screenshot from 2018-05-17 17-17-23](https://user-images.githubusercontent.com/9950871/40184355-b2cd6ec0-59f8-11e8-84a3-2d4b75044fe0.png)

**Comment by RobinHerbots** [comment]
@yustnip , 

Can you give some more info.
VCersion of the inputmask + exact mask and options used.

**Comment by yustnip** [comment]
@RobinHerbots 

Tested with 3.3.2-34 inputmask version and the current 4.0.0-beta.64.

Options: { mask: '+7(999) 999-99-99', showMaskOnHover: false, positionCaretOnClick: 'lvp' }

**Comment by yustnip** [comment]
The issue is also reproduced in the Inputmask demo.

![screencast-2018-05-18-09_28_04](https://user-images.githubusercontent.com/9950871/40219675-160a4860-5a7f-11e8-9826-75d6dfd93e98.gif)

**Comment by RobinHerbots** [comment]
@yustnip , 

Thx for the info.  I will look into it.

**Comment by RobinHerbots** [comment]
@yustnip , 

Do you still have the problem?  I retested on browserstack, and it works.

**Comment by ikasianiuk** [comment]
@RobinHerbots, I have the same problem on iOS mobile device (tested on iPhone 7 vesion: 3.3.11 and version: 4.0.1-beta.23). The first time you clicked the masked field cursor acts as it is supposed by default (it goes to the last valid position). But then when you click on the empty space inside the masked field, it doesn't return to the last valid position as it does on Android mobile devices and desktops.

**Comment by RobinHerbots** [comment]
@iramalyk , 

Thx for the feedback.
