### ISSUE TITLE
jquery.inputmask: clearIncomplete and placeholder don't appear to do anything when array of masks used

### ISSUE THREAD

**Issue by weisborg** [RobinHerbots/Inputmask#1892]
`$(".PhoneMask").inputmask(["999-9999", "\\(999\\) 999-9999"], { "clearIncomplete": true, "placeholder": " " });`

I can enter in a partial phone and click outside the field and it keeps the partial number and the rest of the mask in the field.  With placeholder set to a space it is still using _ too.  I've even tried other chars and it always uses _.

**Comment by RobinHerbots** [comment]
@weisborg , 

Strange I tested the above mask and the casing you describe work as expected.  Are you using an older version  of Inputmask?  Or the latest 4.x?

**Comment by weisborg** [comment]
Tried it with the latest and the one from around the time you posted the alternate mask for phone and phone with area code in my other thread.  They both do it.  It also ignores the rightAlign, but this new mask doesn't need it.

**Comment by weisborg** [comment]
It appears to be the call.  If I use:

`Inputmask(["999-9999", "\\(999\\) 999-9999"], { "clearIncomplete": true, "placeholder": " " }).mask(".PhoneMask");`

It works fine.

`$(".PhoneMask").inputmask(["999-9999", "\\(999\\) 999-9999"], { "clearIncomplete": true,  "placeholder": " " });`

Fails.
