### ISSUE TITLE
backward button not work property on iOS 11.3

### ISSUE THREAD

**Issue by wubaiquan** [RobinHerbots/Inputmask#1894]
I used data input mask { alias: "datetime", inputFormat: "yyyy-mm-dd" }
I can input date like "1982-11-11" , but when use backward button delete number,
I got this:
![may-20-2018 14-57-46](https://user-images.githubusercontent.com/4978396/40276548-98004592-5c3f-11e8-91c0-c4375a090087.gif)

input mask worked on Chrome, Safari and Android. only failed on iOS11.3.

I am using 4.0.0-beta.64. jQuery version is v1.11.1.

**Comment by RobinHerbots** [comment]
Van you have a try with 4.0 beta 65

**Comment by wubaiquan** [comment]
Beta 65 worked fine in my tests. Thanks very much.

**Comment by RobinHerbots** [comment]
I will release on npm next.

Op ma 21 mei 2018 13:02 schreef wubaiquan <notifications@github.com>:
