### ISSUE TITLE
Add definitions for hour and minutes

### ISSUE THREAD

**Issue by hansfn** [RobinHerbots/Inputmask#19]
Hi, I use this plugin in many of my projects, but I find myself adding definitions for hour and minutes every time. Could you please consider adding:

```
            'i': { //minute
                "validator": "[0-5][0-9]",
                "cardinality": 2,
                "prevalidator": [{ "validator": "[0-5]", "cardinality": 1}]
            },
            'H': { //hour
                "validator": "[01][0-9]|2[0-3]",
                "cardinality": 2,
                "prevalidator": [{ "validator": "[0-2]", "cardinality": 1}]
            },
```

**Comment by RobinHerbots** [comment]
Hi Hans,

This is already defined in the jquery.inputmask.extentions.js

regards,

Robin

2012/1/4 Hans Fredrik Nordhaug <
reply@reply.github.com

**Comment by hansfn** [comment]
I'm aware of jquery.inputmask.extentions.js. As far as I understand (and my testing shows) the definitions of "h" and "s" are local to the alias "hh:mm:ss". Since I need "hh:mm" I can't use that alias, and the "h" and "s" aren't recognized. 

I'm actually using "y-m-d H:i" now (with my additions above added to jquery.inputmask.js). I don't care if you use "H" and "i" or some other letters, but I think the addition of these definitions are needed.

**Comment by RobinHerbots** [comment]
Hi Hans,

I've made some changes in the dev branch.  I moved the h and i out of the
alias scope, but kept them in the extentions.js.  I also moved the
definitions for date, month and year to the extentions.js.

I think it's better to move all extentions besides the real basic as
numbers, etc to the extentions.js.  The user/developer has to decide wheter
he includes the full extention.js or part of it.  This keeps the total
footprint smaller.

Check out the dev branch and/or give your opinion about it.

best regards,

Robin

2012/1/4 Hans Fredrik Nordhaug <
reply@reply.github.com

**Comment by hansfn** [comment]
That solution makes 100% sense (and is completely acceptable for me). Thanks a lot! This issue can be closed.

PS! Don't forget to update the README ;-)

**Comment by RobinHerbots** [comment]
I should rewrite the whole readme ;-)   I will do this when I merge the dev
branch back to the master

2012/1/4 Hans Fredrik Nordhaug <
reply@reply.github.com

**Comment by RobinHerbots** [comment]
Solved in dev branch
