### ISSUE TITLE
Bower support

### ISSUE THREAD

**Issue by gustavohenke** [RobinHerbots/Inputmask#190]
Hey,
What do you think about supporting [Bower](http://twitter.github.com/bower/)? It's getting very popular, would be nice that jquery.inputmask were there too.

Thanks in advance :)

**Comment by RobinHerbots** [comment]
@gustavohenke ,

Great idea, thx for the tip.

**Comment by gustavohenke** [comment]
Thanks :)

**Comment by RobinHerbots** [comment]
@gustavohenke, 

I cuurently don't have the time to implement this, but I will someday (v2.4)

Robin

**Comment by gustavohenke** [comment]
Can I send a PR?

**Comment by RobinHerbots** [comment]
What do you exactly mean with a PR?

2013/5/14 Gustavo Henke notifications@github.com

**Comment by gustavohenke** [comment]
Pull Request :D

**Comment by RobinHerbots** [comment]
Offcourse you may do that ;-)  I would really appreciate if you could do
the initial setup for building the bower package.

best regards,

Robin

2013/5/15 Gustavo Henke notifications@github.com

**Comment by RobinHerbots** [comment]
@gustavohenke , 

Thx!!

Is the naming component.json required or is this free to choose?

**Comment by RobinHerbots** [comment]
I guess I need to extend the package a bit afterwards, ... 

Does the registration picks up any updates in the repo?

**Comment by gustavohenke** [comment]
`component.json` is the default, if you need to use another file name, you may define it in another JSON file called `.bowerrc`.

Bower work on top of a git repository that has tags compliant with [semver](http://semver.org/). If it doesn't find any tags, the default branch will be used.

**Comment by RobinHerbots** [comment]
@gustavohenke , 

I just tried to register at bower, but saw that it already was regsitered.

Anyway, I added the component.json to the build so that the version gets updated

**Comment by dignityinside** [comment]
+1 please add bower support!
