### ISSUE TITLE
duplicate number

### ISSUE THREAD

**Issue by mihakot** [RobinHerbots/Inputmask#1900]
data-inputmask-mask='99/99[/9999]'

on enter number (e/g/  1234567) , value willbe 11/22/3344

![image](https://user-images.githubusercontent.com/1734182/40616231-f4c858ec-6292-11e8-97ac-38abfbe1e41f.png)

PC, chrome

**Comment by RobinHerbots** [comment]
@mihakot , 

Can you create a jsfiddle for this.
Which version do you use?

**Comment by mihakot** [comment]
Create, but there is no reproducible problem.
The problem occurs when the object is cloned by clone (1,1).

version last

**Comment by RobinHerbots** [comment]
@mihakot , 

What do you mean exact by "when the object is cloned by clone (1,1)."

**Comment by mihakot** [comment]
var src = jQuery("#itemsList .item-source");
var cop = src.clone(0, 0);

**Comment by RobinHerbots** [comment]
@mihakot , 

Ok, I will have a look at it.

**Comment by RobinHerbots** [comment]
@mihakot , 

You probably don't need this anymore or solved it another way but, ...

I pushed a fix for this in version "5.0.4-beta.27".
I needed to cleanup the events before reassigning the inputmask.

**Comment by csrking** [comment]
This does work in that it fixes the duplicate-input issue for a masked input that is cloned but it seems that this is removing ALL of the hooked-up jQuery event handlers from the input before re-creating the input-mask ones.
So if I have a custom 'change' handler on the input that is cloned (which is also masked) then that custom event-handler gets removed; ideally this would not be the case.
