### ISSUE TITLE
Pre-filled inputs and NumericInput issue

### ISSUE THREAD

**Issue by moisesynfam** [RobinHerbots/Inputmask#1902]
Hi! I'm using version 4.0.1 and I'm getting a bug when the inputs values are pre-populated with a number with less than 3 integer digits an extra zero appears on the input. I'm using the default decimal mask with numericInput:true.
![image](https://user-images.githubusercontent.com/9721655/40692656-03f505b0-6381-11e8-9486-dff0c74acc89.png)

Once if I press delete once on the input the behavior goes back to normal but if i type without "deleting" the extra zero, it gets replaced with the numbers I type: 
![image](https://user-images.githubusercontent.com/9721655/40692735-87375928-6381-11e8-8c50-78038f028135.png)

This is the properties I'm using:
`Inputmask("decimal", {
       placeholder: '0',
       positionCaretOnClick: "none",
       radixPoint: ".",
       numericInput: true,
       rightAlign: false
     }).mask(".decimal-mask");`

Removing the placeholder seems load the input properly without the extra zero at the end.

**Comment by adlerdias** [comment]
@RobinHerbots I think this can be closed since it's fixed on last beta.
