### ISSUE TITLE
Value of numeric field acting weird after masking fields already masked

### ISSUE THREAD

**Issue by xSlok** [RobinHerbots/Inputmask#1903]
Hello!
first of all, thank you for the great lib!

I've been implementing the lib on my project and making default masks based on classes and got a weird behavior after calling the inputmask twice.
I'm doing this because I apply all the masks again after an ajax call to apply the mask to new fields

Is there a way to avoid this behavior or not apply the mask to fields already masked? 

here's the fiddle: https://jsfiddle.net/xslok/cbcw0c1y/

Thanks!

**Comment by xSlok** [comment]
I forgot to mention, this also happen to date fields, if there is no value when the mask is applied 
https://jsfiddle.net/xslok/7hnqoz08/

**Comment by RobinHerbots** [comment]
@xSlok , 

This is fixed in version 5.x

See https://jsfiddle.net/jkntvh5y/

(embarrassing late response, ... sorry)
