### ISSUE TITLE
how to apply mask with Ajax result

### ISSUE THREAD

**Issue by lenamtl** [RobinHerbots/Inputmask#1910]
Hi,

I append td with Ajax results and I'm wondering how to apply the mask in that case.

The mask work well on page load on other page but not when append from ajax

`$('<td>').html("<span id='tollfree'>"+resultContactList.contact_tollfree+"</span>"),`

Thanks

**Comment by RobinHerbots** [comment]
@lenamtl , 

Call the inputmask after you inserted the new html element
