### ISSUE TITLE
How do you format for TIME?

### ISSUE THREAD

**Issue by ouija** [RobinHerbots/Inputmask#1911]
Not sure how to utilize inputmask v4 for masking time(s);

With the older version, I was using something like:
`$('#time').inputmask({
	alias: 'hh:mm t',      
	showMaskOnHover: false,
	showMaskOnFocus: true
});`

I'm using the bundle version and my understanding was that this would include the datetime extensions.

What is the syntax I should be using?  Cannot seem to find recent documentation or examples for this, everything I find seems to be related to older versions.

Thanks

**Comment by RobinHerbots** [comment]
@ouija , 

Something like 
```
    Inputmask('datetime', {
            inputFormat: 'hh:MM TT',
        }).mask("test2");
```

**Comment by ouija** [comment]
Awesome!  Worked beautifully, thank you! 👍
