### ISSUE TITLE
Pressing the K and M keys

### ISSUE THREAD

**Issue by hrolick-git** [RobinHerbots/Inputmask#1912]
Hello. I have a question. I can not find a solution. 
Pressing the "K" in a field 00 is inserted two zero and pressing "M" = 00000 five zeros. How can I disable this feature?
_Thank you in advance for your response._

**Comment by RobinHerbots** [comment]
@hrolick-git , 

Have a look at the numeric extensions.  Maybe I should make these shortcuts optional.

**Comment by hrolick-git** [comment]
@RobinHerbots, thanks a lot for the quick response!
I hope this option will be available in the future.

Thank you for this wonderful plugin)

**Comment by shmidtelson** [comment]
@RobinHerbots Hello, you added an feauture?

**Comment by RobinHerbots** [comment]
@hrolick-git , @shmidtelson , 

Fixed in v5.0.0-beta.271

**Comment by aszorenyi** [comment]
@RobinHerbots I've just notice that this is a duplicate of an other issue created by me last year: #2024 .

Maybe you can close that one too. :)
