### ISSUE TITLE
oncomplete fires on every key stroke

### ISSUE THREAD

**Issue by voodoo6** [RobinHerbots/Inputmask#1915]
Hi,

Looking at this test page:
http://digin2018.webflow.io/input-mask-test

I initialise inputmask lke this:

```
$('#membership-number').inputmask('[AAA] [AAA] [999]', {
          oncomplete: function(buffer, opts) {
            console.log('Complete')
          },
          showMaskOnHover: false,
          clearMaskOnLostFocus: false,
          skipOptionalPartCharacter: " "
        });
```

See the console – 'complete' is logged on _every_ keystroke – **how do I make it fire only when the mask is _completed?_** (ie. only after the 9 characters are entered).

Many thanks

**Comment by RobinHerbots** [comment]
Why do you make the input optional?  Try with "AAA AAA 999"

**Comment by voodoo6** [comment]
Perfect, thanks Robin.

(To be honest, I didn't realise the [ ] made the mask optional!)
