### ISSUE TITLE
Behaviour of v3 with hours not possible anymore

### ISSUE THREAD

**Issue by ligoo** [RobinHerbots/Inputmask#1918]
In the v3, I used to `inputmask("hh:mm")` and it worked as intended. Meaning in a 24h system:

- When you entered "8", it understood that you don't wont to enter 8x hours but you meant 08 so it worked well
- Same goes for the minutes thing.

With v4, i tried: `inputmask("datetime", {inputFormat: "HH:MM"});` and other options (like with H: or h:) but doesn't work at all. Per example, when you try h:M it's only allowing one digit (?).

**Comment by RobinHerbots** [comment]
@ligoo , 

I added some prefill functionality back.  Can you have a try with the latest on github.

**Comment by eric-22** [comment]
I tested with latest of branch 4.x, it adds leading zero as it did on version 3.x with 24h format

**Comment by maximeLRT** [comment]
Hello,

I don't get the leading zero with version 4.0.2 with 24h format.
Can you confirm the fix ? Maybe i'm missing something.

https://codepen.io/anon/pen/qJxrKB?editors=1010

Thanks.

**Comment by alexismarquis** [comment]
I confirm that prefill doesn't work anymore in last 4.x versions.

**Comment by RobinHerbots** [comment]
@alexismarquis , 

Yes, I need to fix this.  I have been very busy with other things, but I will definitely start again to fix and enhance the inputmask.

**Comment by alexismarquis** [comment]
Okay, that would be great.

**Comment by RobinHerbots** [comment]
@alexismarquis , 

Can you have a try with version 4.0.5

**Comment by alexismarquis** [comment]
Looks good to me, thanks @RobinHerbots
