### ISSUE TITLE
Character inserted via AltGraph or Ctrl+Alt ignores mask validation

### ISSUE THREAD

**Issue by lmiguelmh** [RobinHerbots/Inputmask#192]
Any characters inserted with this keys like Ctrl+Alt+E (euro sign) or Ctrl+Alt+Q (arroba) are ignored by the mask validator (including the max length). A workaround may be:

``` javascript
$("#text").inputmask({"mask": "aaaa", "placeholder": "", onKeyDown: function (e, buffer, opts) {
 if(e.ctrlKey&&e.altKey) { // ALTGRAPH
  e.preventDefault();
 }
}
});
```

But I am not sure if this is the right way. BTW I am using a Latin American Spanish keyboard layout.
Miguel.

**Comment by RobinHerbots** [comment]
Hi Miguel,

Yes indeed, i will fix that.

best regards,

Robin

2013/3/21 lmiguelmh notifications@github.com

**Comment by RobinHerbots** [comment]
@lmiguelmh , 

Also fixed.

regards, 

Robin

**Comment by dsmalinsky** [comment]
Sorry to bother, I found the plugin pretty useful, thanks for an excellent piece of work.

I'm having problems also with latin chars like (áéÉ), If I copy & paste into the field, everything is ok, but using the keyboard for input filters the characters from the field.

I defined an extension, but probably I am missing something

``` javascript
(function (factory) {
        if (typeof define === 'function' && define.amd) {
            define("jquery.inputmask.extensions", ['jquery', 'jquery.inputmask'], factory);
        } else {
            factory(jQuery);
        }
    }(function ($) {
        //extra definitions
        $.extend($.inputmask.defaults.definitions, {
            'C': {
                validator: "[0-9a-zA-ZáéíóúÁÉÍÓÚ .,@*+_ñÑ]",  
                cardinality: 1,
                casing: "upper" //auto uppercasing
            }
        });
    }));
```

And then 

``` javascript
$(document).ready(function(){                   
        $("#campo1").inputmask("CCC");  //direct mask            
        $("#campo2").inputmask("C{4}");  //direct mask
        $("#campo3").inputmask("C{1,5}");  //direct mask
    });
```

Thanks in advance,
Diego

**Comment by RobinHerbots** [comment]
@dsmalinsky , 

I extended the base definitions with a part of the latin charset.  Can you have a try?

The above should work.  Maybe you have to escape some chars in the regex.

**Comment by dsmalinsky** [comment]
Hi, thanks for your quick response!

Just tried again.
a) The problem is only with Latin characters produced by a two-key combination in my spanish keyboard (example: áéíóúÁÉÍÓÚ). 
b) Latin Characters produced by a single key work ok (example: ñÑ)

If I paste the characters described in a) they work ok also, the problem is when the user types the latin chars into the field using two-key combinations. For example in order to type á I need to press \u00e5 followed by \u00e1

Maybe is something related to certain keycodes being ignored / blocked?

**Comment by RobinHerbots** [comment]
@dsmalinsky , 

\u00e5  is that the alt key or ctrl key ?

**Comment by dsmalinsky** [comment]
Neither. It's a different key. In my keyboard it has a single quote (') and another char (")

**Comment by RobinHerbots** [comment]
@dsmalinsky , 

Can you set a breakpoint in the keypressEvent and send me the event data

Some extra info http://mylingos.com/keyboards/spanishspain.html

**Comment by dsmalinsky** [comment]
I don't know if it helps, but I just used this page http://unixpapa.com/js/testkey.html

And when I press the key combination i'm getting:

<pre>
keydown  keyCode=229       which=229       charCode=0        
keydown  keyCode=229       which=229       charCode=0        
keyup    keyCode=219       which=219       charCode=0        
keyup    keyCode=65  (A)   which=65  (A)   charCode=0     
</pre>

Does this help?

**Comment by dsmalinsky** [comment]
And if I type a single key latin char (like ñ) I get

<pre>
keydown  keyCode=186       which=186       charCode=0        
keypress keyCode=241       which=241       charCode=241      
keyup    keyCode=186       which=186       charCode=0        
</pre>

**Comment by RobinHerbots** [comment]
@dsmalinsky , 

Why does the first don"t show a keypress?

**Comment by dsmalinsky** [comment]
I've been doing some research and it seems to be a problem shared by all the browsers running on linux (see https://bugzilla.mozilla.org/show_bug.cgi?id=308820)
- I can confirm this bug on Chrome Version 36.0.1985.125 and Firefox 31 under Ubuntu 14.04.
- Using the same browsers on a virtual machine with Windows do not show the bug.

I don't know if a hack is viable in order to solve this in an easy way for Linux (maybe using keydown instead of keypress?).

Regards,

**Comment by RobinHerbots** [comment]
@dsmalinsky, 

Can you confirm that it works on windows?

Can you have a test with http://jsfiddle.net/robinherbots/1x7j7evo/4/embedded/result/ on Chrome & FF under Linux?

**Comment by dsmalinsky** [comment]
I uploaded this test page http://www.stagingenv.com.ar/jquery.inputmask/test.htm
It works as expected on Windows (IE 8, Chrome 36, Firefox 31)
It filters dead key characters like ÁÉÍÓÚ and allows Ñ as described.

Here are the results from http://jsfiddle.net/robinherbots/1x7j7evo/4/embedded/result/:

Results using Chrome Version 36.0.1985.125 under Ubuntu 14.04 typing á on the first input:

<pre>
LEGACY >>> keydown: 229: c false: a false: s false: m false ||| ========== LEGACY >>> keydown: 229: c false: a false: s false: m false ||| ========== LEGACY >>> input: undefined: c undefined: a undefined: s undefined: m false ||| ========== LEGACY >>> keyup: 219: c false: a false: s false: m false ||| ========== LEGACY >>> keyup: 65: c false: a false: s false: m false ||| ==========
</pre>

Results using Firefox 31.0 under Ubuntu 14.04 typing á on the first input:

<pre>
LEGACY >>> input: undefined: c undefined: a undefined: s undefined: m false ||| ========== LEGACY >>> keyup: 0: c false: a false: s false: m false ||| ========== LEGACY >>> keyup: 65: c false: a false: s false: m false ||| ========== 
</pre>

Results using Internet Explorer 8 under Windows 7 typing á on the first input:

<pre>
 LEGACY >>> keydown: 186: c false: a false: s false: m false |||  ========== LEGACY >>> keydown: 65: c false: a false: s false: m false |||  ========== LEGACY >>> keypress: 225: c false: a false: s false: m false |||  ========== LEGACY >>> keyup: 186: c false: a false: s false: m false |||  ========== LEGACY >>> keyup: 65: c false: a false: s false: m false |||  ========== 
</pre>

Results using Chrome  36.0.1985.125 under Windows 7 typing á on the first input:

<pre>
LEGACY >>> keydown: 186: c false: a false: s false: m false ||| ========== LEGACY >>> keyup: 186: c false: a false: s false: m false ||| ========== LEGACY >>> keydown: 65: c false: a false: s false: m false ||| ========== LEGACY >>> keypress: 225: c false: a false: s false: m false ||| ========== LEGACY >>> input: undefined: c undefined: a undefined: s undefined: m false ||| ========== LEGACY >>> keyup: 65: c false: a false: s false: m false ||| ==========
</pre>

Results using Firefox 31 under Windows 7 typing á on the first input:

<pre>
 LEGACY >>> keydown: 0: c false: a false: s false: m false ||| ========== LEGACY >>> keydown: 65: c false: a false: s false: m false ||| ========== LEGACY >>> keypress: 0: c false: a false: s false: m false ||| ========== LEGACY >>> input: undefined: c undefined: a undefined: s undefined: m false ||| ========== LEGACY >>> keyup: 0: c false: a false: s false: m false ||| ========== LEGACY >>> keyup: 65: c false: a false: s false: m false ||| ========== 
</pre>

If I can help with any other tests, just let me know.

Thanks,

**Comment by RobinHerbots** [comment]
Can you also send the result using the second textbox

**Comment by dsmalinsky** [comment]
Sorry for the delay, here are the results for http://jsfiddle.net/robinherbots/1x7j7evo/4/embedded/result/ typing á on the second textbox. The only browser that produced some output was Firefox 31.0 under Ubuntu 14.04

Chrome Version 36.0.1985.125 under Ubuntu 14.04 typing á on second textbox:
No output

Firefox 31.0 under Ubuntu 14.04 typing á on second textbox:

<pre>
COMPOSITION >>> compositionstart: undefined: c undefined: a undefined: s undefined: m false ||| ========== COMPOSITION >>> compositionupdate: undefined: c undefined: a undefined: s undefined: m false ||| ========== COMPOSITION >>> compositionend: undefined: c undefined: a undefined: s undefined: m false ||| ========== 
</pre>

Chrome Version 36.0.1985.125 under Windows 7 typing á on second textbox:
No output

Firefox 31.0 under Windows 7 typing á on second textbox:
No output

Internet Explorer 8 under Windows 7 typing á on second textbox:
No output

**Comment by RobinHerbots** [comment]
@dsmalinsky , 

Ok thx.  Updated http://jsfiddle.net/robinherbots/1x7j7evo/5/

So for firefox on linux we have an alternative.  

Can you send for chrome some other inputs.  (only linux)

**Comment by dsmalinsky** [comment]
In chrome under Linux, all the inputs on the first textbox generate some output. However, all the same inputs on the second textbox didn't generate output.

Chrome 36 under Ubuntu 14.04 typing áéíóú on the first textbox

<pre>
LEGACY >>> keydown: 229: c false: a false: s false: m false ||| ========== LEGACY >>> keydown: 229: c false: a false: s false: m false ||| ========== LEGACY >>> input: undefined: c undefined: a undefined: s undefined: m false ||| ========== LEGACY >>> keyup: 219: c false: a false: s false: m false ||| ========== LEGACY >>> keyup: 65: c false: a false: s false: m false ||| ========== LEGACY >>> keydown: 229: c false: a false: s false: m false ||| ========== LEGACY >>> keydown: 229: c false: a false: s false: m false ||| ========== LEGACY >>> input: undefined: c undefined: a undefined: s undefined: m false ||| ========== LEGACY >>> keyup: 219: c false: a false: s false: m false ||| ========== LEGACY >>> keyup: 69: c false: a false: s false: m false ||| ========== LEGACY >>> keydown: 229: c false: a false: s false: m false ||| ========== LEGACY >>> keydown: 229: c false: a false: s false: m false ||| ========== LEGACY >>> input: undefined: c undefined: a undefined: s undefined: m false ||| ========== LEGACY >>> keyup: 219: c false: a false: s false: m false ||| ========== LEGACY >>> keyup: 73: c false: a false: s false: m false ||| ========== LEGACY >>> keydown: 229: c false: a false: s false: m false ||| ========== LEGACY >>> keydown: 229: c false: a false: s false: m false ||| ========== LEGACY >>> keyup: 219: c false: a false: s false: m false ||| ========== LEGACY >>> input: undefined: c undefined: a undefined: s undefined: m false ||| ========== LEGACY >>> keyup: 79: c false: a false: s false: m false ||| ========== LEGACY >>> keydown: 229: c false: a false: s false: m false ||| ========== LEGACY >>> keydown: 229: c false: a false: s false: m false ||| ========== LEGACY >>> input: undefined: c undefined: a undefined: s undefined: m false ||| ========== LEGACY >>> keyup: 219: c false: a false: s false: m false ||| ========== LEGACY >>> keyup: 85: c false: a false: s false: m false ||| ==========
</pre>

Chrome 36 under Ubuntu 14.04 typing áéíóú on the second textbox

<pre>
No output generated
</pre>

**Comment by RobinHerbots** [comment]
@dsmalinsky , 

FF/Linux should work now!

**Comment by dsmalinsky** [comment]
Just updated my sample page http://www.stagingenv.com.ar/jquery.inputmask/test.htm in order to test. 
I can only input É as the first char. Cannot type more than that (of course it accepts all the regular chars, but not another dead tilde latin character)

Tested with Firefox 31 under Ubuntu 14.04

**Comment by RobinHerbots** [comment]
@dsmalinsky, 

Can you send me the composition output  for those chars on FF/Linux?   Does the same char(s) work on FF/Windows?

**Comment by dsmalinsky** [comment]
Firefox 31.0 under Windows works ok with (http://www.stagingenv.com.ar/jquery.inputmask/test.htm) 
I can input ÁÉÍÓÚ without any problem

I assume "the composition output" you talk about are the results on http://jsfiddle.net/robinherbots/1x7j7evo/5/ on the second textbox (if not please send me the right link).

Firefox 31.0 under Ubuntu 14.04 typing áéíóúñá on second textbox:

<pre>
COMPOSITION >>> compositionstart: ||| ========== COMPOSITION >>> compositionupdate: á ||| ========== COMPOSITION >>> compositionend: á ||| ========== COMPOSITION >>> compositionstart: ||| ========== COMPOSITION >>> compositionupdate: é ||| ========== COMPOSITION >>> compositionend: é ||| ========== COMPOSITION >>> compositionstart: ||| ========== COMPOSITION >>> compositionupdate: í ||| ========== COMPOSITION >>> compositionend: í ||| ========== COMPOSITION >>> compositionstart: ||| ========== COMPOSITION >>> compositionupdate: ó ||| ========== COMPOSITION >>> compositionend: ó ||| ========== COMPOSITION >>> compositionstart: ||| ========== COMPOSITION >>> compositionupdate: ú ||| ========== COMPOSITION >>> compositionend: ú ||| ========== COMPOSITION >>> compositionstart: ||| ========== COMPOSITION >>> compositionupdate: á ||| ========== COMPOSITION >>> compositionend: á ||| ========== 
</pre>

**Comment by RobinHerbots** [comment]
@dsmalinsky , 

Grrr, I'm having a works on my machine experience.  I also tried on FF/Linux with a belgian keyboard and I can type all the above chars.

Which exact keyboard layout do you use in Ubuntu?  When I switch to your keyboard layout, my belgian keyboard should behave like yours I guess.

**Comment by dsmalinsky** [comment]
I'm using Spanish or Latin American keyboard layout. Tried in different computers both layouts with the same results, under Ubuntu 14.04
Please note that the characters ÁÉÍÓÚ are not produced pressing AltGraph or Ctrl+Alt, but instead pressing the dead tilde and then AEIOU.

My layout is pretty similar to Spanish keyboard layout on Wikipedia (http://en.wikipedia.org/wiki/QWERTY#Spanish)

In the image, you can see the dead tilde keys in red (http://upload.wikimedia.org/wikipedia/commons/7/74/KB_Spanish.svg)

**Comment by RobinHerbots** [comment]
@dsmalinsky , 

So to type it you just hit the dead key followed by AEIOU.  
I need to press Altgraph + the dead key + AEIOU

I will try the spanish keyboard layout and hit the buttons based on the above layout.  Sorry, but those input keys feel strange to me ;-)

**Comment by dsmalinsky** [comment]
Ok.
Just let me know if you need any other test from me.

Regards,
Diego

**Comment by RobinHerbots** [comment]
Hi Diego, 

Can you retest on FF/linux with version 3.0.65

**Comment by dsmalinsky** [comment]
It's working now!

Just tested on Firefox 31.0 under Ubuntu 14.04

**Comment by RobinHerbots** [comment]
@dsmalinsky, 

Chrome/Linux & FF/Linux should work now

**Comment by dsmalinsky** [comment]
Great news!

Just tested on Chrome and it works ok now :)

Thanks again!

**Comment by RobinHerbots** [comment]
@dsmalinsky , 

Would you mind retesting the issue in FF/Linux with the latest commit.

**Comment by dsmalinsky** [comment]
Hi @RobinHerbots, just tested on 
- Chrome Version 39.0.2171.65 (64-bit) under Ubuntu Linux 14.04
- Firefox 33.0 under Ubuntu Linux 14.04

Both browsers work as expected on http://www.stagingenv.com.ar/jquery.inputmask/test.htm

**Comment by RobinHerbots** [comment]
@dsmalinsky , 

Great!  Thx!
