### ISSUE TITLE
Assignment of empty value for  element with integer inputmask

### ISSUE THREAD

**Issue by cloudy-reports** [RobinHerbots/Inputmask#1920]
Hello, 
I'm not sure that it is a bug... But I have a strange situation.
I use Ubuntu 16.04, FireFox 60.0.2(64bit) and I have a next source code for using integer inputmask:

HTML
<input id="Settlement_Period_Value" name="Settlement_Period_Value" min="0" step="0" value="0"  size="" im-insert="true" placeholder="" type="text">

JS
$(this).inputmask("integer", {
allowMinus: false,
autoGroup: true,
digits: 0,
digitsOptional: true,
enforceDigitsOnBlur: false,
groupSeparator: " ",
nullable: false
positionCaretOnTab: false,
});

I have entered a value into the element. After that I made "select all()ctrl+A" and after that I have clicked Delete button. A value was removed from the element and I have changed a focus. After that a value of the element is became empty. But I need to have a zero(0) value of element. For example, in a case with Currency inputmask, after cleaning a value I can see 0,00 as value.

Have you an ideas? Thanks.

P.S. I have included a next js files:
nputmask.numeric.extensions.js
jquery.inputmask.js
jquery.inputmask.bundle.js

Version is the last(4.****).

**Comment by cloudy-reports** [comment]
Hello, can You get response on my request. Thanks.

**Comment by RobinHerbots** [comment]
@cloudy-reports , 

Try with adding the placholder: "0" option

**Comment by cloudy-reports** [comment]
Hello, thanks for response. I have added placeholder: "0" and I have added clearMaskOnLostFocus: false also. In this case integer element is working perfectly. Thank You very much.

P.S. a small remark. Need to use correct "placeholder" instead of "placholder".
