### ISSUE TITLE
Datetime inputFormat mm/dd/yyyy allows entry of 02/3 without padding the day

### ISSUE THREAD

**Issue by Josh68** [RobinHerbots/Inputmask#1922]
(This issue refers to `v4.0.0`)

Using the basic `datetime` alias with an `inputFormat` of `mm/dd/yyyy`, it is possible to type a `2` (immediately padded to `02` for February), followed by a `3`, which should be immediately padded to `03`, but is not.

At this point, no further input will be taken, because the date is already in an invalid state.

I would try a PR fix, but cannot take the time to decipher the validation flow in the datetime extension. If anyone wants to point me in the right direction, I can try fixing.

FYI, using `inputFormat` `dd/mm/yyyy` works as expected, because the day is validated before the month is entered. So putting in `30` or `31` for the day correctly disallows the subsequent entry of a `2`.

Thanks for the excellent library.

**Comment by Josh68** [comment]
I should also note, related to this issue, that default masking is quite messed up if I swap out `mm/dd/yyyy` for `m/d/yyyy`. Out of the box, I get something like this in the input: `m///yym/`

**Comment by RobinHerbots** [comment]
@Josh68 , 

The problem with m/d/yyyy is a problem with the placeholder logic.  I'm aware of that.  Try placeHolder: "_" for now.

I add some smarter logic for relating day and month.

**Comment by RobinHerbots** [comment]
This issue is still present in version 5.0.0.
