### ISSUE TITLE
jquery datepicker and inputmask no longer work together

### ISSUE THREAD

**Issue by antisniperspy** [RobinHerbots/Inputmask#1924]
I was using 3.3.11 and found some issues.

- Type 080818 into the date field, formats as 08/08/2018 (Good)
--- The formatting works fine if the decade is anything except '0' or '2,' so 080857 results in 08/08/2057 (Good), but the following examples do not work:
- Type 080808 into the date field, formats as 08/08/208y 
- Type 080823 into the date field, formats as 08/08/203y

I tried to update to 4.0.0 and these two plugins no longer work together.

[https://jsfiddle.net/fdt1w26m/](https://jsfiddle.net/fdt1w26m/)

**Comment by RobinHerbots** [comment]
@antisniperspy , 

Have a look at https://jsfiddle.net/fdt1w26m/12/
