### ISSUE TITLE
Decimal Overwrite from right to left

### ISSUE THREAD

**Issue by frazras** [RobinHerbots/Inputmask#1925]
I am trying to reproduce a behavior I saw in another jquery plugin. It can be found [here](https://www.jqueryscript.net/demo/Lightweight-Decimal-Integer-Input-Mask-Plugin-With-jQuery-Weight-Mask/). 
Basically, you enter numbers from the right and it percolates up from the decimal part to the integer part and overwrites the zeroes. Is this behavior possible with this input mask plugin?

**Comment by RobinHerbots** [comment]
@frazras , 

Maybe a bit late but have a look at https://codepen.io/robinherbots/pen/KKKbRqW
