### ISSUE TITLE
time mask from jQuery to vanilla

### ISSUE THREAD

**Issue by eric-22** [RobinHerbots/Inputmask#1926]
I use Inputmask for this :

```
$(selector).inputmask(
  "hh:mm", {
      placeholder: "00:00",
      insertMode: false
    }
)
```

Which works very well. But now, on a new project where jQuery is not allowed, I can't reproduce this mask

The alias `'hh:mm'` is defined in the bundle.js file, obviously I no longer load this file, i use : 

```
<script src="../../plugins/inputmask/inputmask.dependencyLib.js"></script>
<script src="../../plugins/inputmask/inputmask.js"></script>
<script src="../../plugins/inputmask/inputmask.extensions.js"></script>
<script src="../../plugins/inputmask/inputmask.numeric.extensions.js"></script>
<script src="../../plugins/inputmask/inputmask.phone.extensions.js"></script>
<script src="../../plugins/inputmask/inputmask.date.extensions.js"></script>
```

I tried to reproduce the mask with :

```
Inputmask("datetime",{
    mask: "h:s",
    insertMode: false
}).mask("#static_ff_form_etd")
```

But it doesn't work,
Can anyone help me on this ?

**Comment by RobinHerbots** [comment]
@eric-22 , 

Which version do you use?

**Comment by eric-22** [comment]
With jQuery i used version 3.3.10,
Here, i just download the branch 4.x a few hours ago

**Comment by RobinHerbots** [comment]
@eric-22 , 

In v4.x the datetime alias has changes and uses an inputFormat option.  Have a look at the readme

See #1918

**Comment by eric-22** [comment]
Thanks @RobinHerbots, it works fine !
