### ISSUE TITLE
Uncaught TypeError: $(...).inputmask is not a function

### ISSUE THREAD

**Issue by poornib55** [RobinHerbots/Inputmask#1933]
I'm using <script src="https://rawgit.com/RobinHerbots/jquery.inputmask/3.x/dist/jquery.inputmask.bundle.js"></script> in my file but getting the error as inputmask is not a function....

**Comment by RobinHerbots** [comment]
@poornib55 , 

I need more context.  Did you include jquery?

**Comment by ShamanFromSiberia** [comment]
You should try to replace $ with jQuery in your js. Like jQuery(...).inputmask

**Comment by sukrosono** [comment]
Good guess dude, i accidentally use syntax jq plugin but forgot to load the jq on the page.
Anyway, is it possible to improve the error msg, with this type error?

**Comment by RobinHerbots** [comment]
@brutalcrozt , 

When jQuery is not loaded it will throw an error saying "jQuery not loaded!" as from version inputmask@5.0.0-beta.235

**Comment by jpcmf** [comment]
@RobinHerbots I'm adding this to my webpack
```
entry: {
    app: './src/js/app.js',
    vendor: ['jquery', 'popper.js', 'bootstrap', 'inputmask'],
  },
```

and I'm getting this error
```
Uncaught TypeError: t(...).inputmask is not a function
```
What's wrong?

**Comment by RobinHerbots** [comment]
Hi,
Which version are you using of the inputmask?

**Comment by jpcmf** [comment]
@RobinHerbots fix it, thank you.
