### ISSUE TITLE
Double Clicking a Word in an Input Field Highlights the Entire Field

### ISSUE THREAD

**Issue by mlammert** [RobinHerbots/Inputmask#1935]
I am using inputmask to restrict certain characters and limit the number of characters on various fields by using regex.
```
$("#user-name-field").inputmask({ 
regex: gl_strUserNameMask,
placeholder: ""
});
```
Everything appears to be working fine from a masking point of view. However, I stumbled upon a strange issue where if I double-click on a word within the input field (that should typically highlight only that word) it will highlight everything within that field.

Any ideas as to why this would be happening and how I can rectify this issue?

Thanks!

**Comment by RobinHerbots** [comment]
@mlammert , 

Which version are you using of the inputmask?  Can you try with 4.0.1 beta 17

**Comment by mlammert** [comment]
I was using 4.0.0 beta 24.

I downloaded the latest version and dropped in the new `jquery.inputmask.bundle.min.js` file.

When I reloaded my web page, the entire page froze and gave a "there is a script causing this web page to run slowly" message in Firefox. I tried several time, cleared my cache, etc and could not get my page to function with the latest version file.

Thank you for your quick response and offer to help, but I think I need to move on and see if there is another solution for what I am trying to do.

BTW, this was the regex I was using `[ a-zA-Z'\-]{64}`

**Comment by RobinHerbots** [comment]
@mlammert , 

Can you provide some more feedback, as I tested your regex and don't experience any problem.  How many inputs are on the screen?

**Comment by mlammert** [comment]
The page that "froze" had two input fields on it. Both were being masked using similar regex'es.

I have tried to narrow this down to the most basic of code and I still get the issues.

Using jQuery 3.3.1 and jQuery UI 1.12.1.

Again, I appreciate the desire to help, but I was forced to move on to a different jQuery plugin that offers similar functionality (jquery.alphanum).
