### ISSUE TITLE
TypeError: getFn is undefined in 4.0.1-b.16

### ISSUE THREAD

**Issue by pbarney** [RobinHerbots/Inputmask#1936]
`TypeError: getFn is undefined` in jquery.inputmask.bundle.js line 149, column 17

Here is a basic implementation that worked with 4.0.0-100 but does not work with 4.0.1-b16

http://jsbin.com/qiqukugoni/edit

**Comment by RobinHerbots** [comment]
@pbarney , 

This should be fixed as from beta17
