### ISSUE TITLE
Unable to implement yearrange

### ISSUE THREAD

**Issue by terrym6263** [RobinHerbots/Inputmask#1937]
Inputmask.extendAliases({ 'jpnDate': { inputFormat: 'yyyy年mm月dd日', alias: 'datetime',placeholder: '_'} });
$('#birthdate').inputmask('jpnDate',{yearrange:{ minyear:1910, maxyear:2030 }});

I could not be able to implement extendAliases with yearrange.  Am I doing something wrong?

Thanks

**Comment by RobinHerbots** [comment]
@allora6263 , 

Have a look at the readme.  Yearrange is removed and replaced by min and max

**Comment by terrym6263** [comment]
Thank you
