### ISSUE TITLE
Selenium Webdriver ins't clicked and inputed

### ISSUE THREAD

**Issue by edminify** [RobinHerbots/Inputmask#1938]
Hi. Use RobinHerbots/Inputmask
Selenium doenst work (not see click)
Example
driver.findElement(By.name("signerSsn")).click();
driver.findElement(By.name("signerSsn")).sendKeys("3333-33-3333");

or
driver.findElement(By.xpath("//[@id="signerInfo"]/div/div[2]/div[4]/label/input")).click();
driver.findElement(By.xpath("//[@id="signerInfo"]/div/div[2]/div[4]/label/input")).sendKeys("3333-33-3333");
html:
//<input tabindex="10" type="text" name="signerSsn" data-inputmask="'mask': '999-99-9999'" data-msg-ssn="Please enter correct SSN" value="" class="form-control ssn" maxlength="100" placeholder=" ">
//
Please help

**Comment by RobinHerbots** [comment]
@edminify , 

Try with the vanilla dependency lib instead of jquery dependency, or have a look at the simulator.js in the qunit folder.  It has todo with native events vs jquery events

**Comment by edminify** [comment]
Please can you send me  vanilla dependency? Thanks)

**Comment by edminify** [comment]
o done 
 WebElement wb = driver.findElement(By.name("signerSsn"));
        JavascriptExecutor jse = (JavascriptExecutor)driver;
        jse.executeScript("arguments[0].value='222-222-2222';", wb);

**Comment by RobinHerbots** [comment]
Have a read in the readme forum theater vanille dependency. But your other solution also does the trick
