### ISSUE TITLE
Phone mask placeholder is changing after onincomplete checking

### ISSUE THREAD

**Issue by alexdpts** [RobinHerbots/Inputmask#1946]
If field incomplete, and not try to fill, phone mask placeholder is changing - characters 441 appear in the operator code instead of underlines.

Windows 8.1 pro 64bit
Google Chrome 67.0.3396.99 64bit
Inputmask Version: 4.0.1-beta.23

Using via data-inputmask attributes

Using standart phone mask data-inputmask="'alias': 'phone'"

a little video in attach
[phone mask.zip](https://github.com/RobinHerbots/Inputmask/files/2226621/phone.mask.zip)

**Comment by mupic** [comment]
A similar problem https://codepen.io/mupic/pen/zLWLWa

**Comment by RobinHerbots** [comment]
Remove Phone alias #1981
