### ISSUE TITLE
Phone Inputmask on iPhone 6 - ablility to start typing numbers wherever

### ISSUE THREAD

**Issue by PaulaBarszcz** [RobinHerbots/Inputmask#1948]
Hello,
I'm using version 3.3.11 of Inputmask.

The issue: On iPhone 6 it is possible to click in different parts of the phone input field and start typing numbers there.

On Android and on different operating systems on desktop the behavior is as expected - the user is forced to type numbers from left to right (even if they click at the end of the input field).

I checked it on iPhone 6 both at the preview of the website I'm working on and at Chris Coyier's Codepen:
https://codepen.io/chriscoyier/pen/PbOEqL
Two print-screens are attached.

Is there an easy way to force typing numbers from left to right on iPhone?

![codepen_inputmask](https://user-images.githubusercontent.com/31891675/43324871-77548046-91b5-11e8-874a-d3d42b38eff9.jpg)

![preview_inputmask](https://user-images.githubusercontent.com/31891675/43324879-7c929d0e-91b5-11e8-9c4f-2db569dca7d0.jpg)

**Comment by RobinHerbots** [comment]
@PaulaBarszcz , 

Did you have a try with a newer version of the inputmask?

**Comment by PaulaBarszcz** [comment]
@RobinHerbots ,
Yes, I tried with a version 4.0.0 and the problem was still present.

**Comment by RobinHerbots** [comment]
Van you use these 4.0.1 beta xx

Op ma 30 jul. 2018 08:25 schreef Paula Barszcz <notifications@github.com>:

**Comment by RobinHerbots** [comment]
Oeps the predictive text correction made noncense of my sentence.  Can you
also try the latest from github.

Op ma 30 jul. 2018 11:58 schreef Robin Herbots <robin.herbots@gmail.com>:

**Comment by PaulaBarszcz** [comment]
When I use the latest Inputmask version (4.0.1-beta.7), the problem on iPhone 6 still persists. And another problem occurs:

on Chrome on iPhone and on Chrome on Mac it is impossible to type correct number of digits into the phone number field (it stops accepting the numbers after 7 digits - I need to type 9 numbers for correct phone number). In our markup we have +48 before the number (international phone code for Poland).

I attach print screens. Do you have any idea what I should change?

![desktop1 phone_no numbers](https://user-images.githubusercontent.com/31891675/43514655-ebddf96e-9580-11e8-8e1c-ed32f6991b51.png)

![desktop2 phone_max numbers](https://user-images.githubusercontent.com/31891675/43514666-f30cde1c-9580-11e8-93b6-41c2a506f280.png)

![mobile1 phone_no numbers png](https://user-images.githubusercontent.com/31891675/43514681-fb417d68-9580-11e8-9c00-910dfddedafb.jpg)

![mobile2 phone_max numbers](https://user-images.githubusercontent.com/31891675/43514690-ff37d5fc-9580-11e8-8a6e-9faf4d868a8e.jpg)

**Comment by RobinHerbots** [comment]
@PaulaBarszcz , 

By beta version I mean the latest from github 4.0.1-beta.23

**Comment by PaulaBarszcz** [comment]
Ah, I chose the latest Tag from the Tag tab (on github, in the menu where
you search branches & tags), I thought it was the latest one. Now I know
better than that, thank you:) I will check Inputmask’s version
4.0.1-beta.23 next week, when I will be back at the office.
Thank you for your suggestions so far:)


W dniu śr., 1.08.2018 o 11:57 Robin Herbots <notifications@github.com>
napisał(a):

**Comment by PaulaBarszcz** [comment]
Hello,
I used version 4.0.1-beta.24.

On Mac on Chrome the bug with allowing only 7 digits (instead of 9) still persists.

On iPhone both on Safari and on Chrome the bug allowing to start typing numbers in the middle of the field still persists. And additionally (on iPhone on Chrome) when I typed digit 2 on positions 7. and 8. and later I typed digit 1 on position 9. - digit 1 "jumped" before two digits "2" (so I ended up with "___ ___ 122" ). So unfortunately the behavior did not improve.
Any suggestions what should I try? :)
I attach print screens from Mac-Chrome, iPhone-Chrome and iPhone-Safari (Inputmask version 4.0.1-beta.24).

![2018-08-06 version 4-0-1-24 mobile chrome png](https://user-images.githubusercontent.com/31891675/43702152-103cff9a-9959-11e8-819f-319d14eabcbf.PNG)

![2018-08-06 version 4-0-1-24 mobile safari](https://user-images.githubusercontent.com/31891675/43702156-14053778-9959-11e8-91c0-304b08947658.PNG)


![2018-08-06 version 4-0-1-24 desktop chrome](https://user-images.githubusercontent.com/31891675/43702158-16faa210-9959-11e8-8885-8dcfbb4fc9fb.png)

**Comment by RobinHerbots** [comment]
Hi @PaulaBarszcz , 

I will have a look.

Is this the correct mask you are using?

https://jsfiddle.net/n7h1r4pf/1/

**Comment by PaulaBarszcz** [comment]
Hi,

Thank you :)

No, our mask is different than "(999) 999-9999"; we are using:

 $('[data-mask-telefon]').inputmask('+48 999 999 999', {
      showMaskOnHover: false
 });

in a separate js file, in addition to inputmask.js and jquery.inputmask.js.
Mobile numbers in Poland consist of 9 digits (often with a space inserted between every three digits), preceded by a +48 prefix  (to identify country as Poland) :)

**Comment by RobinHerbots** [comment]
Updated fiddle  https://jsfiddle.net/n7h1r4pf/2/

**Comment by RobinHerbots** [comment]
https://codepen.io/robinherbots/pen/PBBVGp

**Comment by PaulaBarszcz** [comment]
Yes, the mask in https://jsfiddle.net/n7h1r4pf/2/ is correct - and here on Mac on Chrome it allows to type 9 digits as expected. (As compared to allowing to type only 7 out of 9 digits on Mac on Chrome on the preview of my website.)

About the main bug: on iPhone both on Safari and on Chrome the bug allowing to start typing numbers in the middle of the field still persists (print screens from iPhone from https://jsfiddle.net/n7h1r4pf/2/ are attached)

iPhone Chrome
![img_1580](https://user-images.githubusercontent.com/31891675/43708239-4f94aaec-996a-11e8-82fb-5875f2633973.jpg)

iPhone Safari

![img_1581](https://user-images.githubusercontent.com/31891675/43708244-53a64eec-996a-11e8-84c2-fcc87967ab12.jpg)

**Comment by RobinHerbots** [comment]
@PaulaBarszcz , 

Ok allowing to type chars in the middle of the mask is not really a bug.  It should only not mess up the sequence.

**Comment by PaulaBarszcz** [comment]
In https://jsfiddle.net/n7h1r4pf/2/  are you using the same version 4.0.1-beta.24 as I did in my preview, or did you add some modifications? 
I'm wondering: if you didn't change anything between 4.0.1-beta.24 and version used in https://jsfiddle.net/n7h1r4pf/2/ , then it would probably mean the problem lays within my website and not within Inputmask.
