### ISSUE TITLE
Decimal mask drops digits

### ISSUE THREAD

**Issue by WaltDaniels** [RobinHerbots/Inputmask#195]
When using this mask on an input: 

$(".currencyfield").inputmask('decimal', { digits: 2 });

each time you tab into, then out of the input control the left-most digit is stripped off.  This only happens if you've type a decimal point in the number.

**Comment by RobinHerbots** [comment]
@WaltDaniels ,

I didn't occur on Chromium, in browser did you test it?

Best regards, 

Robin

**Comment by WaltDaniels** [comment]
Robin,

I am using Chrome, Version 25.0.1364.172 m.  I notice that if I use the mouse to loose focus, the number is unchanged, however when I leave the input control via the "TAB" key, the leftmost digit is stripped.  ex: the number entered "123.45" becomes "23.45".  I see where this is occurring (in the onKeyDown function), but am hesitant to make changes since I don't fully understand the logic.

Thanks!

**Comment by RobinHerbots** [comment]
fixed in the latest version

Robin

**Comment by WaltDaniels** [comment]
Hey Robin, thanks for the quick turnaround.  I'm using NuGet to manage this package, and I see that it was updated today (3/25) however the version is 2.1.8.  According to the source here on GitHub we should be at 2.1.12.  Should I just use the GitHub files and not use NuGet?  Thanks again!

**Comment by RobinHerbots** [comment]
@WaltDaniels ,

The new packages are available on nuget.

Robin
