### ISSUE TITLE
Percentage not going over 100%

### ISSUE THREAD

**Issue by dlacaille-baytech** [RobinHerbots/Inputmask#1953]
Hi,
We have values that are over 100%. I know we can use a custom one but why is the `percentage` limited to 100%?

Thanks

**Comment by marcelolx** [comment]
@dlacaille-baytech There's no limitation

**Comment by RobinHerbots** [comment]
@dlacaille-baytech , 

Maybe a bit late but you can remove the limitation by using the max option.
max: undefined
