### ISSUE TITLE
DateTime not work for me

### ISSUE THREAD

**Issue by Tktenshi** [RobinHerbots/Inputmask#1956]
What am i do wrong?
```
Inputmask.extendDefaults({
   cardinality: 1,
   casing: "upper", 
   placeholder: "",
   greedy: true,
   showMaskOnHover: false,
   showMaskOnFocus: false,
   skipOptionalPartCharacter: "",
   removeMaskOnSubmit: true,
   autoUnmask: true,
});

const masks = {  
   masked_date: {alias: "datetime", inputFormat: "dd/mm/yyyy", placeholder: 'дд.мм.гггг'},
};

export const activateMask = (el, mask, onKeyValidation) => {
   Inputmask.extendDefaults({onKeyValidation : function (key, result) {handleKeyValidation(onKeyValidation, key, result, this)}});
   Inputmask(masks[mask]).mask(el);
};
```

![image](https://user-images.githubusercontent.com/10534860/43629527-2c8f1c96-9706-11e8-9b88-36ffd6c810ad.png)

When i typed the symbol, in input appears "dFtetime". And i can't erase it. 

And i don't want to see this
![image](https://user-images.githubusercontent.com/10534860/43629710-b307a630-9706-11e8-859e-db68540b0181.png)
How i can turn it off?

**Comment by cangoktas** [comment]
I'm having a similar issue, how could you fix it? @Tktenshi

**Comment by Tktenshi** [comment]
> I'm having a similar issue, how could you fix it? @Tktenshi

you just should import this =) thats resolve my problem)

import Inputmask from "inputmask";

before i import this 
import Inputmask from "inputmask/dist/inputmask/inputmask"; - thats was wrong
