### ISSUE TITLE
Can't insert characters with combinations of keys [End] / [Home]

### ISSUE THREAD

**Issue by lmiguelmh** [RobinHerbots/Inputmask#196]
Well, in an input text with any mask:
1.  Press any key ('a').
2.  Press [Home].
3.  Press any key ('a').
4.  Press [End].
5.  Repeat from step 1 again.

This behaviour varies with _placeholder=""_, or _insertmode=false_, being more evident with _placeholder=""_ and insertmode off (without).

**Comment by RobinHerbots** [comment]
@lmiguelmh,

Thx for the feedback! 

I will fix these issues soon.

Best regards, 

Robin

**Comment by RobinHerbots** [comment]
@lmiguelmh ,

Can you explain a bit more the problem?  It is not clear to me what the problem is.

Robin

**Comment by lmiguelmh** [comment]
You can't insert characters at the end (even if you had enough space left). Write a character and then press HOME, then END, and now try to insert another character. You'll see that you can't.

**Comment by RobinHerbots** [comment]
@lmiguelmh , 

That is because when you press end the caret moves to the end.  Repositioning the caret to a valid position renenables input.

**Comment by lmiguelmh** [comment]
Did you try with property `placeholder: ""`? 
Press: [char] [char] [END] [HOME] [char] [END] [HOME] [char] ...

**Comment by RobinHerbots** [comment]
@lmiguelmh ,

Now I see the problem!!  , ... I will fixed it asap.

Robin

**Comment by RobinHerbots** [comment]
@lmiguelmh, 

Should be fixed in the latest version.  Can you have a try!

Robin
