### ISSUE TITLE
Current version (4.0.1-beta.24) has console log 

### ISSUE THREAD

**Issue by DiscoDancer** [RobinHerbots/Inputmask#1960]
Hi.

Steps to reproduce:

1. Open file jquery.inputmask.bundle.min.js
2. Find console log

**Comment by RobinHerbots** [comment]
@DiscoDancer , 

Yes, I will remove them with the next commit   👍 

Thx

**Comment by DiscoDancer** [comment]
@RobinHerbots thanks for quick response, my star is on you 👍
