### ISSUE TITLE
Dynamic mask issue?

### ISSUE THREAD

**Issue by cosmoKenney** [RobinHerbots/Inputmask#1961]
I need to support the following values in a field.
A 7 digit number. 
The literal value SIP followed by 4 digits.
The literal value SIG followed by 4 digits.
The literal value JPA followed by 4 digits.
The literal value DEM followed by 4 digits.
So I've passed an array as the mask:
`['9-99-99-99','SIP-9999','SIG-9999','JPA-9999','DEM-9999']`
The problem is that as soon as I type the letter "S", "SIP-" comes up. If I backspace, then the entire SIP- goes away. So I have no way to enter SIG. 
What's the best way to proceed?

**Comment by cosmoKenney** [comment]
Here's an update. I switched over to using a regex:
```
//--------------
var options = {
	'autoUnmask': true,
	'positionCaretOnTab': false,
	'greedy': true,
	'placeholder': '_',
	'regex': '(?:(?:SIP|SIG|JPA|DEM)-\\d{4})|(?:\\d-\\d{2}-\\d{2}-\\d{2})',
	'casing': 'upper'
};
Inputmask( options ).mask( element );
//--------------
```
It works much better. Except when I type with caps-lock *off*, the mask won't accept the input.
Looks like I need to set autoUnmask to false so I can preserve the SIP/SIG/... in the value.
It's odd that the code in this fiddle that I found in issue #1136  doesn't work for me:
http://jsfiddle.net/c0pvjaxu/2/
I.e. in that fiddle typing lowercase letters get automatically uppercased. 
But in my code it doesn't.

**Comment by cosmoKenney** [comment]
@RobinHerbots is there any chance you an comment on this? I just need a suggestion on how to either make the regex mask case insensitive, or to force the user entered values to upper case.

**Comment by cosmoKenney** [comment]
I'm using: "inputmask": "^4.0.0",

**Comment by cosmoKenney** [comment]
This works with caps lock off, but is obviously not ideal since I can enter any combination of the allowed letters:
```
Inputmask.extendAliases({
        'myalias': {
            regex: "(?:\\d-\\d{2}-\\d{2}-\\d{2})|(?:[sSjJdD][iIpPeE][pPgGaAmM]-\\d{4})",
            placeholder: '_',
            casing: "upper"
        }
    }
);
Inputmask('myalias').mask("txt1");
```
http://jsfiddle.net/8dasL6bo/1/

**Comment by RobinHerbots** [comment]
@cosmoKenney, 

Probably is the answer much too late, but you need to set the keepStatic: false option
```
Inputmask(['9-99-99-99','SIP-9999','SIG-9999','JP\\A-9999','DEM-9999'],
            {
            	keepStatic: false,
                casing: "upper"
            }).mask("test1");
```

**Comment by cosmoKenney** [comment]
@RobinHerbots I'll check it out and see where I left it. It has been a few years. So I'm not exactly sure which of our apps this was in.
