### ISSUE TITLE
`digits` option ignored when first typing in the radix character

### ISSUE THREAD

**Issue by monovertex** [RobinHerbots/Inputmask#1962]
With Inputmask v4.X, when typing (in an empty input) the radix character first and then typing decimals, the `digits` limit is ignored and the user can type as many decimals as wanted.

The options used are:

```
    alias: 'decimal',
    placeholder: '',
    digits: 2,
    digitsOptional: true,
    groupSeparator: ' ',
    autoGroup: true,
    showMaskOnHover: false,
    showMaskOnFocus: false,
    clearIncomplete: false,
```

See a reproduction in this [JSFiddle](https://jsfiddle.net/2mLxkzw9/962/).

The same config works as intended in v3.X: [JSFiddle](https://jsfiddle.net/2mLxkzw9/963/).

Just to better illustrate the bug, here is a GIF with how to reproduce it:

![inputmask](https://user-images.githubusercontent.com/1837605/43761377-99a829e2-9a2d-11e8-8ee4-d78a9fc30da0.gif)

**Comment by BrenoFortunato** [comment]
I'm currently having the same problem, have you found any solution?

**Comment by monovertex** [comment]
We're currently using v3.X, as we are time constrained and there was nothing we needed in v4.X for the time being. I'll post an update in this issue if we come up with a workaround or a fix.

**Comment by BrenoFortunato** [comment]
Allright, thanks for the reply.

**Comment by CSChesterLP** [comment]
I've came across the same issue. Please fix it, I need 4.X :)

**Comment by RobinHerbots** [comment]
@CSChesterLP , 

I will fix this in v5.x

**Comment by CSChesterLP** [comment]
Thanks @RobinHerbots, I'll be waiting. Awesome job btw.

**Comment by Vahalas** [comment]
Came here to post about the same issue. Glad to see there will be a fix in 5.x! This is a really nice library. Thank you @RobinHerbots

**Comment by RobinHerbots** [comment]
@monovertex, @CSChesterLP , @Vahalas, @BrenoFortunato ,

Seemed already fixed in v5 ;)
https://jsfiddle.net/h9y63bn2/
