### ISSUE TITLE
Strange Calendar popup issue in IE Only when used with Daterangepicker

### ISSUE THREAD

**Issue by weisborg** [RobinHerbots/Inputmask#1965]
I have a mask like:

`$(".MyDateTime", context).inputmask("datetime", { "clearIncomplete": true, "placeholder": "mm/dd/yyyy HH:MM", "inputFormat": "mm/dd/yyyy HH:MM" });`

Applied to an input also using the Daterangepicker library with the same format.  We have about  a 50/50 split on users that type only and users that like to pick in a calendar, so I add the mask to validate the typers.

Works great in Chrome, but in IE when an input has a value or gets its value set in JavaScript something causes a focus event to get triggered which makes the calendars popup on all the inputs on the screen.  If I remove the mask everything loads as it should.

Is there any IE specific code causing a focus to trigger?  I only found a focus handler in the code.

**Comment by weisborg** [comment]
It looks like this isn’t about the datepicker specifically, but it firing a focus event in general. Even when just hovering over a mask field in IE11 it is putting focus on the input. There is an old issue where a comment about this happening with the placeholder got lost and probably should have been its own issue- https://github.com/RobinHerbots/Inputmask/issues/553

The placeholder when used with the mask sets the value of the input. I think this is causing the focus/input event to fire. Even when no custom placeholder is specified there is still the default one used. I think the way to fix this is setting whatever placeholder will be set in the normal HTML placeholder attribute until the control has focus. Once it is focused set it in the value of the input.

**Comment by weisborg** [comment]
Fix may end up being the opposite of what I thought.  It is the HTML placeholder attribute changing that fires input/change events, so on hover and mouse leave we actually need to leave that placeholder alone and not clear or restore it.

**Comment by weisborg** [comment]
As a temp fix I just replaced this.placeholder with originalPlaceholder.  In most cases it ended up being originalPlaceholder = originalPlaceholder, but I kept the place in code marked that way so I could tweak it later.  It eliminates placeholder text on hover...other than possibly setting the value instead when empty to the empty placeholder, I don't see much else that could be done.  I imagine that would mess things up or possibly have values left in fields that shouldn't be.  An empty mask on hover has always looked kind of weird anyway, so I'm fine without it since it fixes the issue in IE.

In other testing with a combobox library having the same issue, I found that even setting to an empty placeholder fires the event since placeholder was set at all IE still clears the empty and fires input/change events.

**Comment by weisborg** [comment]
Latest build seems to have made this worse and added even more places modifying the placeholder.  Every time it is touched IE fires events as if the field changed.

**Comment by RobinHerbots** [comment]
@weisborg ,

Can you please create a codepen with the inputmask and the daterangepicker.
After that I will fix the issue.
Thx
Robin

**Comment by weisborg** [comment]
It isn't just a calendar issue. The calendar was how it originally presented itself because it captures onChange and onInput. IE9+ has a flaw where any time the placeholder on an input is touched it fires change events as if the value of the field has changed. On hover or blur the library changes it with el.placeholder or input.placeholder. There are a few spots where it is set to the current mask, "", or originalPlaceholder. So, what happens is on hover or blur it fires events like onChange. Anything bound to that event will run even though the value of the input has not changed.

**Comment by RobinHerbots** [comment]
@weisborg , 

So, when I change the placeholder property of an input in ie9+  a change event is triggered?

**Comment by weisborg** [comment]
Yes. Dumbest thing I've ever heard, but true. Likely never will get fixed either since they are pushing Edge and updating the rest as little as possible. I had to update 4-5 of the libraries we used that all touched placeholder. We have several forms that do things onChange or onInput and they all go nuts in IE. We had to stop using placeholder in the HTML too since sometimes it would clear (or even the act of it getting set) and fire the events.

**Comment by RobinHerbots** [comment]
@weisborg , 

I pushed a possible fix (workaround).  Have a try.

**Comment by weisborg** [comment]
Looks like that works.  No issues involving placeholder now.  It is kind of funny too since a quick look at the change seems to be just detecting IE and updating the value instead of placeholder.  Updating value from JavaScript never fires events, but they messed up placeholder in IE bad enough where no matter how it is updated it fires events.  Thanks for the amazingly quick push.
