### ISSUE TITLE
Inputmask is not working.

### ISSUE THREAD

**Issue by AKrishma** [RobinHerbots/Inputmask#1967]
Input masking is stopped working. Previously it was working fine. but again its stopped working.
When we click on date field, its not let us enter anything. 
Refer Date of birth field in following link to check the issue.
https://showcase-eu-rel.unileversolutions.com/us/en/secure/sign-up-v2.html

let us know the resolution asap.

**Comment by DiscoDancer** [comment]
@AKrishma If you provide a codepen simulation of your error it will help (without HTML, CSS and JS not related to your issue). You can take [mine ](https://codepen.io/anon/pen/LBarwr) as a basis.

**Comment by RobinHerbots** [comment]
@AKridhma,
I'm on holiday and have limited access.  Which version are you using?

Op ma 13 aug. 2018 15:11 schreef Disco Dancer <notifications@github.com>:

**Comment by AKrishma** [comment]
@RobinHerbots, we are using https://github.com/RobinHerbots/Inputmask.git for inputMask and it contain 4.0.1-beta.29 version, as verified from its package.json

**Comment by RobinHerbots** [comment]
Which mask and options are you using?

Can you provide a codepen or jsfiddle.

Op di 14 aug. 2018 05:27 schreef Krishma Arora <notifications@github.com>:

**Comment by AKrishma** [comment]
code pen url is as below:
https://codepen.io/akrishma-the-bashful/pen/ZjZrRb 
here we are able to type in input field, but masking is not working.
But in this https://showcase-eu-rel.unileversolutions.com/us/en/secure/sign-up-v2.html we are not able to enter anything in date field.

**Comment by RobinHerbots** [comment]
The date aliases has been refactored since version 4.see changelog and
readme for more information.

Op di 14 aug. 2018 13:42 schreef Krishma Arora <notifications@github.com>:

**Comment by AKrishma** [comment]
Thanks for responding. Issue has been resolved.
