### ISSUE TITLE
Removing extraneous delimiters

### ISSUE THREAD

**Issue by matrixapps** [RobinHerbots/Inputmask#1974]
Hi,

If I have a field set with 5 optional numbers - e.g. **$("#field1").inputmask("[99999]");**
and I only enter 4 digits, the result in the field is 1234_.  The underscore gets submitted w/the form.  Is there a way to eliminate unused mask delimiters - e.g. only return 1234.

I tried _removeMaskOnSubmit_ but the underscore remains.  Do I have to manually remove the delimiters?

Thanks.

**Comment by matrixapps** [comment]
Can anyone please assist?

**Comment by jadamec** [comment]
Try `greedy:false` and input mask like `[9]{5}`, this should hide optional characters...

**Comment by rfossella** [comment]
Thanks for your comment, however this does not solve my issue.

I used:
$("#field").inputmask({ mask: "[9]{5}", greedy: false });

If I enter 4 (out of 5) characters the form is still processed as:
Object {field: "1234_", …}
field:"1234_"

I am still force to clean up the underscore on the backend.

Again, the underscore gets submitted w/the form. Is there a way to eliminate unused mask delimiters - e.g. only return 1234.

**Comment by RobinHerbots** [comment]
@matrixapps , @jadamec , @rfossella ,

Sorry for the late reply.

Anyway, when using a mask like [99999] it is optional as a whole or not optional at all.
[99999] and [9]{5} are the same masks.

You can use
```
Inputmask("9{0,5}").mask("test1");
or
Inputmask("[99999]", {
           removeMaskOnSubmit: true
}).mask("test2");
```

**Comment by rfossella** [comment]
Neither syntax gives me the desired result on the backend.

```
$("#contactExt").inputmask("[99999]",{removeMaskOnSubmit: true});
OR
Inputmask("[99999]", {removeMaskOnSubmit: true}).mask("contactExt");
```

On the form, if field #contactExt is **1234**, it correctly displays as **1234_**

When I inspect the value on node backend I still get the value **1234_**  

Am I misinterpreting your suggestion?  I thought {removeMaskOnSubmit: true} would simply yield **1234** (no underscores)

**Comment by RobinHerbots** [comment]
@rfossella , 

How do you submit to the backend?  A form submit? or other means?

**Comment by rfossella** [comment]
I serialize the form and make a POST AJAX call (via jQuery).

**Comment by RobinHerbots** [comment]
@rfossella ,

This is because you're not submitting the form in the classic way.  removemask**onsubmit** only works when submitting the form.

Anyway, try this (autoUnmask option)
```
 Inputmask("[99999]", {
            removeMaskOnSubmit: true,
            autoUnmask: true
        }).mask("test2");
```

**Comment by rfossella** [comment]
Perfect! **autoUnmask: true** did the trick.  

Thanks so much for following up w/me.
Rob
