### ISSUE TITLE
two part regexp \d{1,3}-\d{1,3} not allow to input 6 digits.

### ISSUE THREAD

**Issue by shcherbanikolay** [RobinHerbots/Inputmask#1975]
I try to to create input field with mask that allowed input year days in format \d{1,3}-\d{1,3}. There is an error when I try to input 123-456. It is not allowed to input last digit (only 123-45). After I delete one digit in first part of input (12-45), then I can input last digit (12-456), after that I go back to first part of input string and set third digit to it. The result is 123-456 as expected.

Why I can't input 6 digit (123-456) from first attempt?
My fiddle: [fiddle](http://jsfiddle.net/3bqy0nzg/)

**Comment by RobinHerbots** [comment]
@shcherbanikolay , 

Try with version 4.0.2.

See http://jsfiddle.net/3bqy0nzg/6/
