### ISSUE TITLE
Chinese / Japanese characters are unable to mask

### ISSUE THREAD

**Issue by owen26** [RobinHerbots/Inputmask#198]
I am trying to get a input field masked with Japanese mobile phone number format. It's straight forward if the input only contains 0-9 numeric characters. But the problem is it's quite common to use full-width numeric characters  ０－９in Japan and China, which are unable to be masked.

Also when I input full-width characters, the existing placeholders are pushing to the right hand side, which I think is an unhandled bug.

**Comment by RobinHerbots** [comment]
Hi,

How can I input full-width chinese characters on a belgian keyboard?  Can you send the console output after typing such character.
Best regards,
Robin

**Comment by owen26** [comment]
not sure how to check the console output. although there is no error displayed in firebug.

![image](https://f.cloud.github.com/assets/385786/327813/3efa1202-9b83-11e2-9bee-c64d10f8d176.png)
![image](https://f.cloud.github.com/assets/385786/327818/51b2f760-9b83-11e2-99af-2e6f8caf0263.png)
![image](https://f.cloud.github.com/assets/385786/327821/61f023fa-9b83-11e2-9b97-36780ffbc2bc.png)
![image](https://f.cloud.github.com/assets/385786/327836/380e9c50-9b84-11e2-91e6-9e0948127668.png)

**Comment by RobinHerbots** [comment]
Is the 3th one the one with the wide - characters?

How do you type such characters?  I have to google it I gues ;-)

**Comment by owen26** [comment]
Yes the 3rd one is the one with "full-width" wide characters.

I think if you don't mind, you can install a chinese or japanese input method from your OS and have a test with it. Both windows and mac provide built-in support for those input methods.

**Comment by RobinHerbots** [comment]
@owen26 , 

I will try that.

Robin

**Comment by RaphaelDDL** [comment]
(I'm translating the option names from my language, dunno if those are really the english names)

To get the JP keyboard on Windows (7): 
- Control Panel
- search for `keyboard`
- under `Region and Languages`, pick `change keyboard and other input methods`
- `Change keyboards...` on the window that follows
- on `General` tab, pick `Add` at the right
- Look for `Japan` > check `Microsoft IME` and click OK
- `Apply`
- Switch keyboard layout with `left ALT+ left SHIFT` until your language bar changes to JP with a red circle and another icon by its side.
-  Click on the icon beside the red circle one and change to one of the following:
- - `hiragana` (icon will become full-width `あ`);
- - `full-width alphanumeric` (icon will become full-width `Ａ`);
- - `full-width katakana` (icon will become full-width `カ`)

_They all have full-width numbers. But pick `full-width alphanumeric` so you can type using our letters in full-width mode._
- Ｈａｖｅ　ｆｕｎ　ｔｙｐｉｎｇ　ｗｉｔｈ　ｆｕｌｌ－ｗｉｄｔｈ　ｌｅｔｔｅｒｓ　ａｎｄ　ｎｕｍｂｅｒｓ　１２３４５６７８９０

By the way, the unicode version of that phrase above in full-width is `&#xfeff;&#xff0d;&#xa0; &#xff28;&#xff41;&#xff56;&#xff45;　&#xff46;&#xff55;&#xff4e;　&#xff54;&#xff59;&#xff50;&#xff49;&#xff4e;&#xff47;　&#xff57;&#xff49;&#xff54;&#xff48;　&#xff46;&#xff55;&#xff4c;&#xff4c;&#xff0d;&#xff57;&#xff49;&#xff44;&#xff54;&#xff48;　&#xff4c;&#xff45;&#xff54;&#xff54;&#xff45;&#xff52;&#xff53;　&#xff41;&#xff4e;&#xff44;　&#xff4e;&#xff55;&#xff4d;&#xff42;&#xff45;&#xff52;&#xff53;　&#xff11;&#xff12;&#xff13;&#xff14;&#xff15;&#xff16;&#xff17;&#xff18;&#xff19;&#xff10;`

so 1 - 0 is `&#xfeff;&#xff11;&#xff12;&#xff13;&#xff14;&#xff15;&#xff16;&#xff17;&#xff18;&#xff19;&#xff10;`

(used http://www.linkstrasse.de/en/%EF%BD%86%EF%BD%95%EF%BD%8C%EF%BD%8C%EF%BD%97%EF%BD%89%EF%BD%84%EF%BD%94%EF%BD%88%EF%BC%8D%EF%BD%83%EF%BD%8F%EF%BD%8E%EF%BD%96%EF%BD%85%EF%BD%92%EF%BD%94%EF%BD%85%EF%BD%92 to convert)

Might be annoying to add support to that, better make an extension since needs to have a unicode table or make a convert function for that.

Hope that helps you in testing the problem.

Best Regards,
Raphael DDL

**Comment by RobinHerbots** [comment]
http://stackoverflow.com/questions/6885879/javascript-and-string-manipulation-w-utf-16-surrogate-pairs

**Comment by RobinHerbots** [comment]
@owen26 , 

It's been a while ;-)

But can you have a try with the latest version from github.

**Comment by owen26** [comment]
hi robin,

Sorry for late reply. I tried the latest version of this plugin

> https://github.com/RobinHerbots/jquery.inputmask/blob/3.x/dist/jquery.inputmask.bundle.js

with the config of 

```
$('input').inputmask({
  mask: '999-9999-9999'
});
```

This time I'm unable to input any full-width numeric characters such as

> １２３４５６７８９０

I guess this is the expected behaviour with my config?

**Comment by RobinHerbots** [comment]
No, it should work.  Can you have a look in the keypress event and see whick code you get for the fullwidth numeric chars.

**Comment by RaphaelDDL** [comment]
@owen26 correct me if I'm wrong:

Keyboard as Japanese, set to Hiragana and using a simple page like this one: http://www.asquare.net/javascript/tests/KeyCode.html

When pressing any number from 1 to 0, the KeyDown for all is 229, what changes is the keyUp (1 = 49, 2 = 50, etc). After press, the auto-complete dropdown kicks in and when you pick the value, it won't trigger any other keyCode. But while you were using Up/Down to pick between full-width (２),half (2) or japanese hiragana (二), it _will_ trigger 38/40. Odd.

Anyways, just trying to help, not that I'll use the feature atm.

**Comment by RobinHerbots** [comment]
The input fires a compositionevent which i tranlate to keypresses.  What i
mean, see what keycode you get in the keypressevent from the inputmask;

Op 09:01 DI 9 Jun 2015 schreef Raphael DDL Oliveira <
notifications@github.com>:

**Comment by owen26** [comment]
@RobinHerbots 

I captured the keycode using the following code:

```
$('#telephone').on('keypress', function (e) {
  console.log(e.keyCode, e.which);    
});
```

unfortunately I'm unable to trigger keypress event when my input method is switched to full-width mode. When I switched back to half-width mode, it triggered as usual.

Personally I think it would be an acceptable behaviour for me, as the original reason I raise this bug is because full-width character interrupted the proper format of the mask symbols, which wouldn't be a problem if they are not allowed to be insert any more.

**Comment by RobinHerbots** [comment]
Try wih the compositionupdate event and watch the e.originalevent.data

**Comment by RobinHerbots** [comment]
@owen26, 

I made a jsfiddle http://jsfiddle.net/Lgcnxa2g/

Can you try some wide chars and tell me what you get in the textarea.

**Comment by owen26** [comment]
Hi Robin,

I tried your jsfiddle, but there is something seems not quite right. And when I type things(no matter what I typed), nothing comes out in the textarea. Please see the screenshot.
![qq 20150610081333](https://cloud.githubusercontent.com/assets/385786/8072472/c89c7244-0f48-11e5-8b81-d844a45f57ae.png)

I use the latest version of Chrome and Firefox under Windows 8.1

**Comment by RobinHerbots** [comment]
What are your exact keyboard settings?

Op 02:18 WO 10 Jun 2015 schreef Xinan notifications@github.com:

**Comment by owen26** [comment]
Ah, actually when I use the built-in Japanese input method, the TEXTAREA can show the correct characters I'm typing such as "１, ２, ３". But when I use Chinese input method, it shows nothing.

I think it might have something to do with these input method's native behaviour. Some input methods (especially for Asia languages) put the characters you are typing into a temporary place (usually marked with underscore), when you press ENTER, it will be converted to the final string and put in your input area. As the screenshots below:

![qq 20150610143729](https://cloud.githubusercontent.com/assets/385786/8076402/b1ff0fe8-0f7e-11e5-893c-d7fe7287812e.png)
![qq 20150610143801](https://cloud.githubusercontent.com/assets/385786/8076406/b4f9cd82-0f7e-11e5-90dd-553fbd7e8288.png)
![qq 20150610143905](https://cloud.githubusercontent.com/assets/385786/8076408/b7e61a96-0f7e-11e5-8817-a4623fd10b79.png)

This behaviour trigger events differently in JavaScript. In Japanese method, when I start type numbers, "keypress" event is not triggered, "compositionupdate" on the other hand, is triggered. With e.originalEvent.data set to the content of what I was typing. But when I press ENTER to convert the characters to the final words, "compositionupdate" is not triggered.

When I type numbers in Chinese method (full width mode), neither "keypress" nor "compositionupdate" was triggered.

I think maybe you can install some of the input methods to feel what I'm saying. And maybe the behaviour could be affected by individual computer settings. Since there are so many different input methods, the best way to solve this issue seems to be simply ignore those special characters.

**Comment by RobinHerbots** [comment]
@owen26 , 

In the keyboard layout I find multiple chinese keyboard layouts.  I don't know which one to take.  I tried some and they all produce correct output.
Does the Chinese method triggers an input event?  I can ignore this case, but I just want to reproduce at my machine to make sure there is no trivial fix.

**Comment by owen26** [comment]
@RobinHerbots ,

I suggest you can install a third party input method called Sogou, which is the most popular Chinese input method on the market. (they are like 90% market share).
http://pinyin.sogou.com/

 Unlike other languages, the Microsoft embed Chinese input method is almost never used in real world.

If your plugin compatible with Sogou, then it's compatible with most of the Chinese people.

**Comment by RobinHerbots** [comment]
@owen26, 

Can you provide some screenshots with some translation of the tool, so that I kown what I am doing ;-)

It is chinese only and it's all chinese to me if you know this expression ;-)

I managed to install and select the pinyin ime by guessing, ... now how do I type the chinese wide chars?

**Comment by RobinHerbots** [comment]
Ok, google translate on android to the rescue  ;-)

**Comment by weijer** [comment]
Chinese input method is not supported

**Comment by PlusA2M** [comment]
Same issue here. Using the latest version of Jquery plugin, the numeric input on while using Traditional Chinese (Using in HK, TW but not in China) Input method “Quick 速成”, with normal setting (should be output normal characters but not full-width characters), sometimes work but sometimes didn’t.

I am trying to mask 

1. Credit Card number (this work on both English and Traditional Chinese Input Methos)
`$(selector).inputmask("(9999-9999-9999-9999)|(999-999999-999)");`

2. Credit Card expiration date / CV2
`$(selector).inputmask("99/99");
$(selector).inputmask("999");`
// Everything is great with English input method, however, the input recognized  as spaces (same 1-9 input) while using Traditional Chinese Quick input method with half-width normal characters output (Win10 built-in)

**Comment by zhencai2020** [comment]
@RobinHerbots Were you able to solve this issue? I am having the same exact issue where the characters are mis-placed if I were to use the masking and have the chinese keyboard turn on.
