### ISSUE TITLE
Create new phone alias based on libphonenumber

### ISSUE THREAD

**Issue by RobinHerbots** [RobinHerbots/Inputmask#1982]

**Comment by RobinHerbots** [comment]
https://github.com/RobinHerbots/Inputmask/issues/1378#issuecomment-358948580

**Comment by sphereagency** [comment]
Not checked yet but that sounds perfect so far :)

**Comment by RobinHerbots** [comment]
https://github.com/catamphetamine/libphonenumber-js

**Comment by RobinHerbots** [comment]
https://github.com/RobinHerbots/inputmask.phone/issues/1
