### ISSUE TITLE
international phones inputmask multi problem

### ISSUE THREAD

**Issue by anllyksell** [RobinHerbots/Inputmask#1988]
In an issue before, you mentioned we should use jquery.inputmask-multi.min.js. I'm trying but is gives error.
Can you tell which js files should be added and in which order ??

**Comment by anllyksell** [comment]
And our input alias should be 'phone' or 'abstractphone' ??

**Comment by RobinHerbots** [comment]
@anllyksell , 

https://github.com/RobinHerbots/inputmask.phone (I will make it available on npm soon)
