### ISSUE TITLE
IE10 Input Mask Problem

### ISSUE THREAD

**Issue by Treyphor** [RobinHerbots/Inputmask#199]
In IE 10 they've added a little 'x' to the textbox you're typing in that will clear out the data. If you use this 'x' on a masked field and then type again it puts all the deleted characters back.

**Comment by RobinHerbots** [comment]
http://stackoverflow.com/questions/14498396/event-fired-when-clearing-text-input-on-ie10-with-clear-icon

**Comment by RobinHerbots** [comment]
Should be retested.

Fixed the paste event which should capture the change
