### ISSUE TITLE
existing input's inputmask problem

### ISSUE THREAD

**Issue by anllyksell** [RobinHerbots/Inputmask#1990]
I have written before about multi.js. I managed to inputmask the input for onkeyup event  and when submit button clicked, I remove mask. I'm trying when page loaded, existing inputs should have the inputmask that is proper for it. But inputmask's' method works only once in an event. I need inputmask method. Is there any way that I can match phonenumber with a mask and I can send it with inputmask ??

**Comment by RobinHerbots** [comment]
@anllyksell , 

Can you workout an example and link to your previous issue.

**Comment by anllyksell** [comment]
#1988 this one. I actually solved my problem. In multi.js file, there is a method called inputmasks. This method works once in an event. Like onkeyup, onload etc... In load event, I was trying to execute method in a loop and it was giving error after once. Then I assign 'onchange' event for inputs. And in $(document).ready, I dispatched change event for inputs and it worked.
