### ISSUE TITLE
When blur input, inputmask adds attr placeholder to input ... 

### ISSUE THREAD

**Issue by ffixitt** [RobinHerbots/Inputmask#1992]
#### System information

* Inputmask version: 4.0.1-beta.38
* Browser: Google Chrome
* Operating System: MacOS

When blur "datetime" alias, inputmask adds attr placeholder to input. How i can disable this options ? 
In version 4.0.0 doesn't do this.

**Comment by RobinHerbots** [comment]
@QuDDoSS , 

This is done to show the mask.  Can you give some more context.  You don't want to see the mask?

**Comment by ffixitt** [comment]
I want to do form styles like " Material design " and verify if is empty , if has placeholder and is focused .... and from start, input doesn't have placeholder 

`<input type="text" name="" >`

but when I blur empty input this transform to 

`<input type="text" name="" placehoder>`
