### ISSUE TITLE
Issue in Using dateformat mm/dd/yyyy

### ISSUE THREAD

**Issue by sundaralingam48** [RobinHerbots/Inputmask#1993]
I want to use only the date format of mm/dd/yyyy in textbox. When using the below code 
$(‘startDate input’).inputmask(“datetime”,{
inputFormat:”mm/dd/yyyy”,
showMaskOnHover:true,
shoeMaskOnFocus:true
});

But I am getting below error in my console

Uncaught TypeError: Cannot read property ‘min’ of undefined.

Please assist

**Comment by RobinHerbots** [comment]
Which version are you using?

Op ma 10 sep. 2018 19:17 schreef sundaralingam48 <notifications@github.com>:

**Comment by sundaralingam48** [comment]
I used 4.x beta version. I downgraded to 3.3.11 and it is working fine

**Comment by sundaralingam48** [comment]
Also, Found one more issue. When we just enter date without entering month and year and tabbing out and tab in to the same field then the focus is on year always.Its not coming to the place where we last entered .

**Comment by RobinHerbots** [comment]
@sundaralingam48 , 

Which browser do you use?  Can you make a codepen.

**Comment by sundaralingam48** [comment]
@RobinHerbots I am using google chrome

**Comment by RobinHerbots** [comment]
@sundaralingam48 , 

Did you try it on the demo page?
