### ISSUE TITLE
Display only mm/dd/yyyy

### ISSUE THREAD

**Issue by sundaralingam48** [RobinHerbots/Inputmask#1995]
I am using version 4.0.1-beta.39.
I wanted to know the steps to use only mm/dd/yyyy in my text field.
Please let me know the snippet for the same. For me it always displays date with time

**Comment by RobinHerbots** [comment]
Specificaties the dateFormat option.  See readme for dates

Op di 11 sep. 2018 17:41 schreef sundaralingam48 <notifications@github.com>:
