### ISSUE TITLE
Usage of data-inputmask-regex shows 'M' when I delete all symbols from 'inputmasked' field

### ISSUE THREAD

**Issue by AlexanderKapelyukhovskiy** [RobinHerbots/Inputmask#1998]
I'm using Inputmask in Ember project for entering price. I'm using 
`data-inputmask-regex="^\d{1,2}(\.\d{1,2})?$"`
for that. And it is working but there is problem.
The problem is that when I remove all symbols in input I can see symbol 'M'
https://prnt.sc/ktmcn0

**Comment by RobinHerbots** [comment]
@AlexanderKapelyukhovskiy , 

Which version are you using of the inputmask?

**Comment by AlexanderKapelyukhovskiy** [comment]
3.3.11

**Comment by RobinHerbots** [comment]
@AlexanderKapelyukhovskiy , 

Have a try with v4.0.2

**Comment by RobinHerbots** [comment]
@AlexanderKapelyukhovskiy , 

Can this be closed?

**Comment by AlexanderKapelyukhovskiy** [comment]
@RobinHerbots, I'm sorry I wasn't able to update and test with v4.0.2
Please feel free to close if nobody else complained about described issue.
