### ISSUE TITLE
Issue with 4.0.0 version

### ISSUE THREAD

**Issue by sundaralingam48** [RobinHerbots/Inputmask#1999]
I am seeing that inputmask for numeric field and date has an issue of focus and tabout in IE 11. IE is not responding after entering the field value.But same Seems to be working fine in chrome and Mozilla. 

We upgraded to 4.0.1.beta 39 but everything seems to be working fine there.
Please let me know when we will having the release version of this instead of beta.Please clarify

**Comment by RobinHerbots** [comment]
@sundaralingam48 , 

There is now the 4.0.2 release.
