### ISSUE TITLE
Optional Masks

### ISSUE THREAD

**Issue by RobinHerbots** [RobinHerbots/Inputmask#2]
Full implementation of optional masks

**Comment by stevenrobertscrew** [comment]
hi RobinHerbots.  Very cool that you've taken this on.  Can you describe what you mean by optional masks?

**Comment by RobinHerbots** [comment]
Simply that you can create a mask where some parts aren't required to fill in, to complete the mask , ....

**Comment by stevenrobertscrew** [comment]
yes of course! :)  very important feature.

**Comment by ghedwards** [comment]
This would be very handy right now.

**Comment by rawsp33d** [comment]
I have been trying to add this all morning, but the problem I am running into is that I cannot figure out how to override _val() to not display the full mask.

I would like it so a mask of '99999[-9999]' for example would show '12345-____' while the field has focus, but on blur to only show '12345', as the required part of the mask has been fulfilled (a la the original masked input plugin by Digital Brush).  This plugin easily blows that one away, but having this feature is very important to my clients.

**Comment by rawsp33d** [comment]
Please try out my pull request that attempts to add this feature, https://github.com/RobinHerbots/jquery.inputmask/pull/30

I have only tested this with the example mask given above ('99999[-9999]'), but I will continue testing and improving with all of the feedback I receive.

**Comment by RobinHerbots** [comment]
With optional masks I had something else in mind then your implementation. But I am willing to include the changes or the idea to clear the optional elements from the mask when losing focus. In a previous issue someone else also asked about that kind of functionality.

**Comment by rawsp33d** [comment]
I'm open to any implementation, I'm sure there are some better ideas out there.  I'll help out in any way I can--for this or any other feature.

What was the implementation idea you had?

**Comment by RobinHerbots** [comment]
Hi Ross, 

I added tweaked your implementation a bit and pushed (after some struggle) to the master & dev.

My implementation in mind that you can have optional parts anywhere in the mask & that the mask changes according your input (leaving out optional and reinserting on the fly)

**Comment by rawsp33d** [comment]
Hey, that would be awesome!  It's more abstracted (and therefore useful) than my idea.  Thanks for adding this in--my goal was to be able to use your awesome improved mask in production rather than Digital Brush's long outdated one, and with what we have done I am able to do so.

**Comment by dmartinsid** [comment]
It will be cool if have an option to have multiple masks.

Like:
(99) 9999-9999 or 
(99) 99999-9999

Using optional mask don't works
(99) 9999[9]-9999

**Comment by RobinHerbots** [comment]
Truly optional mask is net yet implemented !!

**Comment by dmartinsid** [comment]
Will be an awesome feature!

**Comment by RobinHerbots** [comment]
Optional mask are implemented, but have to evolve.

Please create an issue when your optional mask doesn't work.

**Comment by RobinHerbots** [comment]
Branch 2.x
