### ISSUE TITLE
Convert entered chars to lower/uppercase

### ISSUE THREAD

**Issue by gvdhoven** [RobinHerbots/Inputmask#20]
When using the input mask with dutch postal codes, i would like to transform the input to uppercase, without restricting the users to enter uppercase chars.

So the mask would become "9999 aa" but when the user enteres "1234 aa" the "a" is converted to uppercase without showing the lowercase "a" (e.g. immediate casing). Also, pasting the value "1234 aa" should be pasted as "1234 AA".

Solutions offered on the official page this plugin was forked from does not help with the "paste" issue.

Regards,
Gilles

**Comment by RobinHerbots** [comment]
Hi Gilles,

Seems a nice feature to add.

I will add this soon to the dev branch.

regards,

Robin

2012/1/16 Gilles van den Hoven <
reply@reply.github.com

**Comment by RobinHerbots** [comment]
checkout the dev branch, I added an option autoCasing

autoCasing: null = nocasing, autoCasing : "upper" = uppercasing , autocasing: "lower" = lowasercasing

https://github.com/RobinHerbots/jquery.inputmask/commit/a47a0050531f2364c7ec19db5fae36814c10b6a2

**Comment by gvdhoven** [comment]
Great stuff and really thanks for your fast pickup!

However (just to stretch you a bit) it would be really cool if you could set this on the definitions level. This would mean that you could (for instance) get a mask like this: '9999-Aaa' where only the first "a" is capitalized.

I don't have a use case for this however, so it might not be a good idea after all.

**Comment by RobinHerbots** [comment]
hehehe, ... actually I agree that it should be included at the definition
level.  I will extend the definitions soon ;-)

2012/1/16 Gilles van den Hoven <
reply@reply.github.com

**Comment by RobinHerbots** [comment]
dang I committed to the wrong branch, ....  anyway I moved the casing to the definition level, ... now it's up to you to find a use-case ;-)

latest can be found at both branches now

**Comment by gvdhoven** [comment]
super, forked it!
