### ISSUE TITLE
Year portion on date mask not prefilling correctly

### ISSUE THREAD

**Issue by jimithing277** [RobinHerbots/Inputmask#200]
Just upgraded to the latest version (was previously using version 1.2.2) and noticed that the behavior of entering the year in a date mask has a very undesirable behavior.

Specifically, when entering the following key sequence:

4213

In the previous version this would automatically fill in to show '04/02/2013'.  However, in the current version this now shows as '04/02/103y'.

Is this intentional?  If so, I find it quite undesirable and annoying from a usability standpoint.  I can see customers pounding at the door if we were to release with this behavior.  Is there a way to revert back to the previous logic used when entering dates?

**Comment by RobinHerbots** [comment]
@jimithing277 , 

I totally agree, ... this is not desirable, I will fix this asap.

best regards, 

Robin

**Comment by jimithing277** [comment]
Robin, that's great news!  Thank you for the prompt reply!

**Comment by RobinHerbots** [comment]
@jimithing277 , 

Fixed in the latest version.  (both branches 1.x & 2.x)
