### ISSUE TITLE
Issue with 4.0.2 release.

### ISSUE THREAD

**Issue by alex-konoval** [RobinHerbots/Inputmask#2003]
Hi guys, first of all thanks for all of your work.
One moment about last release: you have one breaking change `remove phone alias` which bring problems to the other libraries which have `imputmast` as dependency. It can be easy avoided if you will use bug fixes releases only if no breaking changes, and add minor release version if you have any changes like this.
I mean: for bug fixes - `4.0.2`, for `remove phone alias` or any other breaking change - `4.1.2`.
I hope you got my point. Thanks.

**Comment by RobinHerbots** [comment]
@alex-konoval , 

I understand and agree.  Strictly I should have updated the major version as it is a breaking change.
I can better life with updating the minor for (minor ) breaking changes. 

I will do so in the future.  Promise ;-)
