### ISSUE TITLE
4.0.1 or 4.0.2 version

### ISSUE THREAD

**Issue by ghost** [RobinHerbots/Inputmask#2004]
Hi Team
Please clarify whether to use 4.0.1 or 4.0.2 version. We have upgraded our project with 4.0.1 version on Friday and tested it in IE, chrome and Mozilla. It seems to be working fine.

**Comment by RobinHerbots** [comment]
@wototech , 

The only difference is that the v4.0.2 contains escaped unicode chars in the definitions while in version 4.0.1 they got translated by uglify.  So 4.0.2 is a re-uglify with a newer version which preserves the the escaped unicode chars in the definitions. Depending of how you include the scripts this can be important.
