### ISSUE TITLE
Issue with 4.0.1 version

### ISSUE THREAD

**Issue by ghost** [RobinHerbots/Inputmask#2005]
I am using version 4.0.1 version of inputmask.We copier from the dist folder of release version. It is restricting us to enter the ssn and date field in iPhone or Safari.Please assist

**Comment by RobinHerbots** [comment]
@wototech , 

There is an encoding problem with 4.0.1 caused by uglify.  Use 4.0.2.  If that doesn't work.  Please create a codepen with an example so I can test it myself.

Robin

**Comment by RobinHerbots** [comment]
@wototech , 
Did it work out?

**Comment by ghost** [comment]
We are still having this issue

**Comment by RobinHerbots** [comment]
See #2016
