### ISSUE TITLE
Input mask for date format mm/dd/yyyy v3.3.9

### ISSUE THREAD

**Issue by Rohilpatel17** [RobinHerbots/Inputmask#2009]
I am trying to implement the input mask on date field to format the string into mm/dd/yyyy. it works fine on Firefox and chrome, but not on IE 11. Can you please help me what version should I use that works on IE and all other most used browsers?
![date_issue](https://user-images.githubusercontent.com/25271719/45769159-62e70b00-bc04-11e8-8a61-24e8496b9cc5.PNG)

**Comment by RobinHerbots** [comment]
@Rohilpatel17 , 

Update to the latest v4.0.2
