### ISSUE TITLE
Non-conforming initial values

### ISSUE THREAD

**Issue by WaltDaniels** [RobinHerbots/Inputmask#201]
I have a situation where I am unable to pre-format the initial values for my <input> controls.  I would like to apply a 2-digit decimal mask (below). However, the improperly formatted initial values are being truncated.  In the example below, the initial value of "205.6400" gets truncated to "05.64".  Is there a pre-mask event that I can tie in to, or can the inputmask correctly fix-up numeric values when the mask type is "decimal"?

&lt; input type="text" class="numeric" value="205.6400" / &gt;
$(document).ready(function(){
   $(".numeric").inputmask("decimal", { digits: 2 });
});

**Comment by RobinHerbots** [comment]
@WaltDaniels ,

I will have a look at it.

Robin

**Comment by RobinHerbots** [comment]
@WaltDaniels , 

Fixed, I will publish the update on nuget later.

best regards, 

Robin

**Comment by WaltDaniels** [comment]
Thanks Robin, works great!
