### ISSUE TITLE
server side library

### ISSUE THREAD

**Issue by anllyksell** [RobinHerbots/Inputmask#2010]
hi, I'm trying to export word file with formatted inputs but it doesn't work in office. I need to do the masking in server side in .NET. Do you have any library that I can use ?

**Comment by RobinHerbots** [comment]
@anllyksell , 

No I haven't.  
Someone interested in inputmask#?

**Comment by RobinHerbots** [comment]
@anllyksell , 

Maybe this can help https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.maskedtextbox?view=netframework-4.7.2

**Comment by anllyksell** [comment]
There was a task I have to finish and it was hard in client side. But this really can help. Thanks so much
