### ISSUE TITLE
4.01 Cannot remove/disable placeholder when regex mask provided

### ISSUE THREAD

**Issue by aszorenyi** [RobinHerbots/Inputmask#2012]
Hi,

Just recently upgraded from v3 to v4 and I cannot disable the placeholder on inputs when a regex mask is bound.

e.g: If I have a regex like this: "^(-|(0|([1-9]\\d*)))$" then the input always has a placeholder with "-", even if I set it to an empty string.

**Comment by RobinHerbots** [comment]
@hunfatal , 

Try jitMasking: true option

**Comment by aszorenyi** [comment]
@RobinHerbots  Wow, that was a quick answer. And it solved the issue, thanks!
