### ISSUE TITLE
Issue with 4.0.2 version

### ISSUE THREAD

**Issue by ghost** [RobinHerbots/Inputmask#2016]
I am using version 4.0.2 version of inputmask.We copiedit from the dist folder of release version. It is restricting us to enter the date field in iPhone or Safari.Please assist

**Comment by RobinHerbots** [comment]
@wototech , 

I need more information.

When you try the demo page.  Do you also have the issue?
Can you send me the version of IOS and safari.

Can you also send the exact mask and options you are using.

thx
Robin
