### ISSUE TITLE
Inputmask numeric does no round up when digits is 0

### ISSUE THREAD

**Issue by dianavele** [RobinHerbots/Inputmask#2018]
Hi, I am using version 4.0.2 of inputmask and I have an issue related to inputmask numeric and the fact that when digits is set to 0, the value is not rounded, but truncated (for example 123.67 will be 123 instead of 124). If digits is set to 1 or more, the value is rounded correctlyt (123.67 will be 123.7)
Here is my code snippet:
```
 $(elem[0]).inputmask("numeric", {
                radixPoint: formats.DECIMAL_SEP,
                groupSeparator: formats.GROUP_SEP,
                digits: 0,
                showMaskOnHover: false,
                showMaskOnFocus: false,
                placeholder: '0',
                digitsOptional: false,
                autoGroup: true,
                clearMaskOnLostFocus: false
            });
```
I am testing on Chrome. 
Am I using it wrong or is this a known issue?
Thanks!

**Comment by RobinHerbots** [comment]
@dianavele , 

v 4.0.3-beta.2 fixes the issue
