### ISSUE TITLE
"Can not read property 'join' of undefined" when using Inputmask.format

### ISSUE THREAD

**Issue by salvadormarcos** [RobinHerbots/Inputmask#2019]
I'm getting the error _"Can not read property 'join' of undefined"_ when using **Inputmask.format** with the following configuration:

```
{
    alias: 'currency',
    digits: 3,
    digitsOptional: false,
    integerDigits: 4,
    prefix: '',
    groupSeparator: '.',
    radixPoint: ',',
    groupSize: 3,
    unmaskAsNumber: true,
    autoUnmask: true
}
```

Example in: https://stackblitz.com/edit/js-tbdmxj. Typing a value such as 5000.100 the above error occurs.

This error occurs on [this line](https://github.com/RobinHerbots/Inputmask/blob/05c39c87d22831ead051565cf67b730a2bcb27e4/js/inputmask.numeric.extensions.js#L443). During the debug, I realized that the **"buffer"** property of the **"maskSet"** object has an array, unlike the **"_buffer**" property, which is undefined. Is this right?

I did some testing by changing the above line to use **"buffer"** instead of **"_buffer"** and the example code worked as expected.

**Comment by RobinHerbots** [comment]
@salvadormarcos , 

Can you try again with the latest beta

**Comment by salvadormarcos** [comment]
It's working fine, thanks!
