### ISSUE TITLE
digits: 3 - error on transform

### ISSUE THREAD

**Issue by ghost** [RobinHerbots/Inputmask#2022]
Version: 4.0.3-beta.3

https://jsfiddle.net/dfv6gL8v/38/
Bug at "digits: 3" numeric on pre values. (German format)

**Comment by RobinHerbots** [comment]
@ghost, 

The first one is wrong right?

**Comment by RobinHerbots** [comment]
I guess we need an option tot specyfying the  input radix point.

There is otherwise no way to determineren a correct value

**Comment by RobinHerbots** [comment]
@ghost, 

Have a look at https://jsfiddle.net/dfv6gL8v/40/

Also have a read at https://github.com/RobinHerbots/Inputmask/blob/4.x/README_numeric.md#setting-initial-values
