### ISSUE TITLE
Numeric mask - Option to disable 'k' and 'm' key handlers

### ISSUE THREAD

**Issue by aszorenyi** [RobinHerbots/Inputmask#2024]
I have a lot of inputs on my forms with numeric (integer) input masks with auto group, and I just noticed that in v4 if i press 'k' then two zeroes, and when i press key 'm' 5 zeroes will be inserted to input. A property to disable this functionality would be great.

Or is there any option to turn this off which I didn't notice?

**Comment by smtaydemir** [comment]
+1

**Comment by BrockBelmonte** [comment]
I noticed the same thing and have not found an option to disable this yet. Let me know if you do!

**Comment by aszorenyi** [comment]
I've modified the script internally at the company and removed this feature.

**Comment by lsudnitsyn** [comment]
Could you advise how you fixed this issue, what did you change? I have version 4.0.6 and I noticed the same problem.

**Comment by aszorenyi** [comment]
According to #1912 this is resolved in v5-beta.
