### ISSUE TITLE
 change readme.txt file of the project located in nuget / input mask is not a function of jquery

### ISSUE THREAD

**Issue by jeanc1992** [RobinHerbots/Inputmask#2027]
**Describe the bug**
when a nuget package is installed, you recommend to copy the data that is opened in the readme.txt, so it does not work at all, this is because a bundle must be created with the same structure or layout of the folder of the route that it contains them.
example :
if the folder contains a subfolder where the files are located and the bundle name must contain almost the same path.
it is currently presented in this way:

 bundles.Add(new ScriptBundle("~/bundles/inputmask").Include(
                //~/Scripts/Inputmask/dependencyLibs/inputmask.dependencyLib.js",  //if not using jquery
                "~/Scripts/Inputmask/inputmask.js",
                "~/Scripts/Inputmask/jquery.inputmask.js",
                "~/Scripts/Inputmask/inputmask.extensions.js",
                "~/Scripts/Inputmask/inputmask.date.extensions.js",            
                //and other extensions you want to include
                "~/Scripts/Inputmask/inputmask.numeric.extensions.js"));

but when installing the nuget package a path is generated: scripts / inputmask / inputmask /
being this last folder where the files are located, producing that the bundle is not generated correctly and this is not recognized as a function of jquery.

for the above I recommend changing the path you set in the readme.txt because of the following:

      bundles.Add(new ScriptBundle("~/bundles/inputmask/inputmask").Include(
                //~/Scripts/Inputmask/dependencyLibs/inputmask.dependencyLib.js",  //if not using jquery
                "~/Scripts/Inputmask/inputmask/inputmask.js",
                "~/Scripts/Inputmask/inputmask/jquery.inputmask.js",
                "~/Scripts/Inputmask/inputmask/inputmask.extensions.js",
                "~/Scripts/Inputmask/inputmask/inputmask.date.extensions.js",
                //and other extensions you want to include
                "~/Scripts/Inputmask/inputmask/inputmask.numeric.extensions.js"));

placing the following in the layaut
@Scripts.Render("~/bundles/inputmask/inputmask")

[readme.txt](https://github.com/RobinHerbots/Inputmask/files/2494143/readme.txt)
greetings, I was willing without apologizing for my English, I had to use the google translator

**Comment by RobinHerbots** [comment]
@jeanc1992 , 

Yep the readme isn't updated since forever.  There also seems to be some issues when using nuget package references vs package .config.

npm package support is well integrated in visual studio and more suitable for providing js-libs.

I think of stopping support of nuget for the inputmask

What do you think?

**Comment by RobinHerbots** [comment]
@jeanc1992 , 

I updated the nuspecs, so in a next release the path will be correct according the readme.

Be aware that the package only work when using the package.config and not via package reference.
If someone has a solution for this besides using npm instead, let me know.
