### ISSUE TITLE
Breaking change

### ISSUE THREAD

**Issue by mrbabbs** [RobinHerbots/Inputmask#2028]
**Describe the bug**
Removing phone alias with a patch release breaks projects 

**To Reproduce**
1. Install inputmask@~4.0.0
2. Import 'inputmask/dist/inputmask/inputmask.phone.extensions'
3. update to inputmask@4.0.1
4. not found 'inputmask/dist/inputmask/inputmask.phone.extensions'

**Expected behavior**
According with https://semver.org/ a patch release version, should not break any existing api. Updating from 4.0.0 to any 4.x.x should be able to import 'inputmask/dist/inputmask/inputmask.phone.extensions'.

**Comment by RobinHerbots** [comment]
@mrbabbs , 

I know about semantic versioning and I know I violated it.

I will pay more attention to it in future releases!!

For now hava a look at https://github.com/RobinHerbots/inputmask.phone
