### ISSUE TITLE
trackbackPositions in console

### ISSUE THREAD

**Issue by abrambailey** [RobinHerbots/Inputmask#2032]
It looks like you left a console log in there
```
            function trackbackPositions(originalPos, newPos, fillOnly) {
                console.log("trackbackPositions");
                var result;
```
jquery.inputmask.bundle.js:1582  in Version: 4.0.3-beta.4

**Comment by RobinHerbots** [comment]
@abrambailey , 

I will fix this in the next commit.  I hope I can spend some more time again on the inputmask soon.  
Thx for reporting!
