### ISSUE TITLE
Run inputmask only on change event

### ISSUE THREAD

**Issue by novumcoder** [RobinHerbots/Inputmask#2034]
Currently the inputmask plugin runs everytime the user presses a key while focused on the input. In some cases this might be too strict as the plugin immadiately changes the input not allowing invalid values. I would like to run the inputmask either delayed or on change event, means, only when the focus is lost on input. Is that possible?

**Comment by RobinHerbots** [comment]
@novumcoder , 

You can use Inputmask.format to implement this.
https://github.com/RobinHerbots/Inputmask#format

**Comment by novumcoder** [comment]
Awesome. That's what i was looking for. Thanks a lot.
