### ISSUE TITLE
Doesn't work for input[type="url"]

### ISSUE THREAD

**Issue by yukipastelcat** [RobinHerbots/Inputmask#2035]
**Describe the bug**
Doesn't work for `input[type="url"]`.

**To Reproduce**
```javascript
const control = document.querySelector('input[type="url"]')
let mask = null
const type = control.getAttribute('type');

switch (type) {
  case 'tel':
    mask = 'phone';
    break;
  case 'url':
    mask = 'phone';
    break;
  default:
    break;
}
if (mask === null) return;
const maskedInput = new Inputmask(mask);
maskedInput.mask(control);
```

```javascript
Inputmask.extendAliases({
  phone: {
    mask: '+7 (999) 9999999',
    placeholder: '+7 (___) _______',
  },
});
```

**Expected behavior**
Mask `input[type="url"]` with phone mask.

**Live example**
https://codesandbox.io/s/o4q82vwjxq

**Desktop**
 - Windows 10
 - Chrome
 - 70.0.3538.102

**Comment by RobinHerbots** [comment]
@yukipastelcat ,

I will add support with the next commit.  
As a workaround you can allow it by passing the supportInputType option

https://codesandbox.io/s/py1m605837
