### ISSUE TITLE
Optional masks with both greedy false and true works the same

### ISSUE THREAD

**Issue by ilplotkin** [RobinHerbots/Inputmask#2037]
According to README, 

> When defining an optional mask together with the greedy: false option, the inputmask will show the smallest possible mask as input first.

I tried both true and false. One symbol placeholder was shown in both cases. What am I doing wrong? Is that possible to show full mask with optional parts?
```
<script src="jquery.js"></script>
<script src="jquery.inputmask.bundle.js"></script>
<input id="i1"><br>
<input id="i2"><br>
<script>
   $('#i1').inputmask({ mask: "9[-9999]", greedy: false });
   $('#i2').inputmask({ mask: "9[-9999]", greedy: true  });
</script>
```
Thank you

**Comment by RobinHerbots** [comment]
@ilplotkin, 

I will look at it.

**Comment by RobinHerbots** [comment]
@ilplotkin , 

I fixed the issue in the 5.x branch, i will back port it into version 4.x

**Comment by ilplotkin** [comment]
I tried 4.0.4. It works. Thank you very much.
