### ISSUE TITLE
Unmasked value of datetime alias, if empty, returns the placeholder

### ISSUE THREAD

**Issue by lucaspoffo** [RobinHerbots/Inputmask#2039]
When submiting a form with removeMaskOnSubmit or calling the unmaskedvalue function, on an empty input with datetime alias, it returns the placeholder of the mask. It is not the behavior of other masks.

Here is a fiddle showcasing the problem:
https://jsfiddle.net/FTZICA/364rwbht/3/

Currently overwritting the onUnMask function of datetime with:
```javascript
onUnMask: function(maskedValue, unmaskedValue, opts) {
    if(unmaskedValue) {
        unmaskedValue = Inputmask().aliases.datetime.onUnMask(maskedValue, unmaskedValue, opts);
    }
    return unmaskedValue;
}
```

-Version: 4.0.3

**Comment by RobinHerbots** [comment]
@lucaspoffo, 

Thx for reporting.  I added the fix in the 5.x branch.
