### ISSUE TITLE
Paste Problem

### ISSUE THREAD

**Issue by rafaelvasco** [RobinHerbots/Inputmask#204]
Paste only works if i select everything first with Ctrl-A or by mouse. Why is this ?

**Comment by RobinHerbots** [comment]
@rafaelvasco ,

Can you give a bit more information as I don't have the problem.

Browser, mask, version of hte inputmask

best regards, 

Robin

**Comment by rafaelvasco** [comment]
Browser: Chrome 26
Mask: AA-AAA-9999/99999-A[99]
Version: 2.2.1

I'll keep investigating. Could be some other jquery lirary conflicting too don't know.

**Comment by rafaelvasco** [comment]
Found the problem. It was on my side. There's no problem with your plugin which by the way is really great. Thanks
