### ISSUE TITLE
Date masked input with readonly attribute.

### ISSUE THREAD

**Issue by WaltDaniels** [RobinHerbots/Inputmask#205]
If you add the "readonly" attribute to an input field that has a date mask, the tab-key no longer allows you to exit the input field, the user gets "stuck" in the field and has to move to the next field using the mouse.  I tried this in Chrome and IE9.

**Comment by RobinHerbots** [comment]
@WaltDaniels , 

Fixed in the latest version and updated on nuget.

Good notice!

thx.

Robin
