### ISSUE TITLE
v5 - No More Minified Version?

### ISSUE THREAD

**Issue by toxpal** [RobinHerbots/Inputmask#2057]
I noticed that last 2 builds of v5 (beta 101 and beta 102) have no minified versions. In other words, "normal" and "minified" files are exactly the same:

https://github.com/RobinHerbots/Inputmask/blob/5.x/dist/jquery.inputmask.js
https://github.com/RobinHerbots/Inputmask/blob/5.x/dist/jquery.inputmask.min.js

What is the reason behind this?

**Comment by RobinHerbots** [comment]
Ik had some trouble debugging in chrome, with thé minification. So It
temporary disabled it. I will put it back on in thé next beta.
Best regards
Robin



Op wo 30 jan. 2019 17:32 schreef toxpal <notifications@github.com:

**Comment by toxpal** [comment]
Thank you for your quick response.
