### ISSUE TITLE
CDNJS out of date

### ISSUE THREAD

**Issue by 1337GameDev** [RobinHerbots/Inputmask#2059]
I just checked the [CDNJS location](https://cdnjs.com/libraries/jquery.inputmask), and it only has version **3.3.4**. 

Can this be updated? I am unsure if this is managed by you/your team, but just wanted to know if this is considered for updating and was forgotten. 

PS: Sorry if this isn't the correct category for this issue, but I figured this might be an oversight.

**Comment by RobinHerbots** [comment]
@1337GameDev , 

The entry was not created by me, ... 
But I created a new entry for Inputmask which should show newer versions. 
cdnjs/cdnjs#13242

**Comment by RobinHerbots** [comment]
[author] add inputmask lib #13242

**Comment by RobinHerbots** [comment]
@1337GameDev , 

https://cdnjs.com/libraries/inputmask
