### ISSUE TITLE
Only 1st placeholder is displayed for fields with same alias

### ISSUE THREAD

**Issue by toxpal** [RobinHerbots/Inputmask#2060]
Latest build of v5 (but noticed the same error in previous builds, like ~beta 50 or so...)

If the same page has multiple fields with the same alias, only the first field displays a placeholder when cursor is moved over. For example, I have 4 fields with **numeric** alias on the same page. This is how 1st field looks:

https://i.postimg.cc/6pgjTdJT/1.jpg

This is how remaining fields look:
https://i.postimg.cc/kMsTWr30/2.jpg

The same happens if I use **integer** alias. If I set 1st field alias to **numeric**, and set 2nd field to **integer**, both field have proper placeholders. 

If I set alias to **email** or specify mask manually (like **'mask':'9{2,3}'**) for multiple fields, all  placeholders are properly displayed, so only numeric and integer aliases have this issue.

Tested on latest versions of Vivaldi and Firefox (desktop) and Firefox on Android - behavior is the same.

**Comment by RobinHerbots** [comment]
@toxpal, 

Thx for reporting.  I will have a look at why this is happening.
Also see
https://codepen.io/robinherbots/pen/WPOdKw

**Comment by toxpal** [comment]
Thanks for your fast response. Just to be clear, I should mention that I initialize options for each field via HTML tags in source code (in case it's important for you to debug this issue). So my JS is as simple as:

`$("[data-inputmask]").inputmask({rightAlign:false});`

**Comment by RobinHerbots** [comment]
@toxpal , 

Ok this is fixed in the latest 5.x
Still the numeric alias itself  needs some fixes, but that will follow inthe coming days.
https://codepen.io/robinherbots/pen/WPOdKw

**Comment by toxpal** [comment]
That was super fast. Thanks!
