### ISSUE TITLE
v5 - currency mask reverses entered values

### ISSUE THREAD

**Issue by toxpal** [RobinHerbots/Inputmask#2063]
Happens with all v5 builds on all browsers.

When **currency** alias is used, everything works fine if user enters value manually. However, if HTML field has some value predefined (using standard **value="..."** format), InputMask reverses entered value.

In other words, if user enters **1.20**, it works fine. But if field has this value set by default (value="1.20"), InputMask will reverse this field, so its value will be displayed as **0.21**.

If last digit is not 0, InputMask won't reverse entered value, but will display some random number then.

See example here - https://jsfiddle.net/jg6vwfuk/

Needless to say, these numbers (1.20 and 3.17) are just examples, the same happens with all numbers.

**Comment by RobinHerbots** [comment]
@toxpal , 

Have a look at https://jsfiddle.net/robinherbots/oauk5exp/1/

I will need to fix that.

**Comment by toxpal** [comment]
Thanks for your follow-up. If I understand right, current workaround is to use additional **numericInput** option. Or was it always mandatory (so it's actually not a bug, but error in my own HTML code to set currency mask)?

**Comment by RobinHerbots** [comment]
It is a regression, caused by the ongoing refactoring of the numeric alias

Op do 7 feb. 2019 18:44 schreef toxpal <notifications@github.com:

**Comment by elexx** [comment]
If you open the [jsfiddle](https://jsfiddle.net/robinherbots/oauk5exp/1/) from [above](https://github.com/RobinHerbots/Inputmask/issues/2063#issuecomment-461520726), focus the first text field, then [tab] to the second text field and type "1.20" it still shows "0.21".

You can also reproduce this by selecting the value in the second text field by marking it with the mouse cursor and the start typing.

Is this problem related to the original one, or should I open a new issue for it?

**Comment by toxpal** [comment]
I confirm the same. Didn't test with TAB in the past, but yes, the issue exists. Only in my situation field becomes 0.20 (not 0.21), but it's still not the expected value (1.20)

**Comment by RobinHerbots** [comment]
@toxpal , @elexx , 

Can this one be closed?

**Comment by elexx** [comment]
Looks good to me. Thanks for fixing!

**Comment by toxpal** [comment]
Yes, works fine.
