### ISSUE TITLE
Set currency prefix to empty by default

### ISSUE THREAD

**Issue by toxpal** [RobinHerbots/Inputmask#2066]
Not really a big deal, but maybe we could at least _consider_ setting prefix for currency mask to be empty by default? I realize USD is a popular currency, but many people submit questions here asking how to remove $ prefix for currency mask, so it looks I'm not the only one who would prefer having no default prefix for currency mask.

I find it a bit strange that you need to initialize an additional option just to remove some specific string ($), when in virtually any other plugin you need to initialize an additional option only if you want to add some specific string.

Of course, it's not a big deal... :)

**Comment by omgbbqhaxx** [comment]
You can delete usd symbol with 

`prefix: "",`

### example usage: 

```
Inputmask.extendAliases({
        btcmask: {
              
                  alias: "currency",
                  prefix: "",
                  digits: 8,
                  
              }
});
$("#test").inputmask({ alias : "btcmask" });
```

**Comment by toxpal** [comment]
Thanks, but this is **exactly** what I wrote **myself** -

>  I find it a bit strange that you need to initialize an additional option just to remove some specific string ($)

**Comment by RobinHerbots** [comment]
@toxpal , 

Done :-)

**Comment by toxpal** [comment]
Thanks, will update my code accordingly now.
