### ISSUE TITLE
Who is still using version 1.x of the inputmask?

### ISSUE THREAD

**Issue by RobinHerbots** [RobinHerbots/Inputmask#207]
Hi all (who is interested ;-) )

Is there someone who still uses version 1.x of the inputmask?  If so is there a special reason for it?  Is there a need for further development for the 1.x branch or do you just keep using it because it does what you need for your project(s)?

I want to make the 1.x branch final, as-is and continue only on the 2.x branch.

**Comment by WaltDaniels** [comment]
Finalize it ... not used here.

**Comment by RobinHerbots** [comment]
@WaltDaniels , 

I don't have patience to wait further reactions.  1.x is final, ... let's concentratte on 2.x !!

Robin
