### ISSUE TITLE
Numeric mask with leading zeros like 00010 with direction of text from left to right

### ISSUE THREAD

**Issue by dheeram** [RobinHerbots/Inputmask#2072]
Hello,

I would like to thank you for providing a nice and good library to mask input.

I'm using 4.x version and would like to have a input mask which would be like 00010, as I type the number it should be 00001, 00012 and 00123 so on.
I used below one, 
$("#<FieldID>").inputmask({
			"mask": "99999",
			dir: "rtl",
			numericInput: true,
			placeholder: "00000",
			greedy: false
		});
but issue with this approach is after I blur out of the field everything is good, but when I come to the same input field using shift + tab the value is changing for 00010 to 01000 and again when I blur out of the field, it changes to 00010 and again when I do shift + tab, it changes back to 01000. Not sure why it not working. If I remember correctly it used to work with 3.x version. I don't remember exact version.

Any help or advise. Thank you and appreciate your help.

**Comment by RobinHerbots** [comment]
@dheeram , 

This seems fixed in version 5.x
