### ISSUE TITLE
v5 Beta 131+ inputformat breaks every single JS on page

### ISSUE THREAD

**Issue by toxpal** [RobinHerbots/Inputmask#2074]
Updated to v5 beta 131 a few days ago and noticed it breaks every single JS-based item on page.

For example, I use select2, CKEditor, Bootstrap DatePicker, and other elements on page. If I include  Inputmask v5 131 (or 132) on the same page, absolutely nothing works (including Inputmask itself). select2 dropdown doesn't work, CKEditor is not initialized, DatePicker doesn't display a popup with date selector, and so on.

See example - https://jsfiddle.net/yjefh4z2/1/

As soon as you remove **'inputformat':'yyyy-mm-dd'** everything starts working.

**Comment by toxpal** [comment]
The last working version was beta 130, I believe. Don't know why, but I have a feeling this is somehow related to this - https://github.com/RobinHerbots/Inputmask/issues/2061 (because if you click on input field in JSFiddle example above, you will see Inputmask adds tons of leading zeros.

**Comment by RobinHerbots** [comment]
@toxpal , 

Fixed in version 5.0.0-beta.133

**Comment by toxpal** [comment]
Jesus Christ, that was fast...

**Comment by RobinHerbots** [comment]
😀

Op vr 1 mrt. 2019 16:47 schreef toxpal <notifications@github.com>:
