### ISSUE TITLE
V5 Beta 131+ still has every single date/time mask broken

### ISSUE THREAD

**Issue by toxpal** [RobinHerbots/Inputmask#2076]
A few days ago I described a bug (which is present in beta 131 and above) and it was fixed (https://github.com/RobinHerbots/Inputmask/issues/2074), but it's only half the battle :) Every single date and time mask is still terribly broken in latest version (beta 133 at the moment).

For example, see this - https://jsfiddle.net/oy5ebr6j/

I included descriptions (what value is expected, and what value is actually displayed) in fiddle itself.

**Comment by RobinHerbots** [comment]
@toxpal , 

Fixed !!  Thx for informing me!
