### ISSUE TITLE
radixPoint on normal tags

### ISSUE THREAD

**Issue by spacedog4** [RobinHerbots/Inputmask#2079]
If I have my mask radixPoint settet to "," and two elements
```
<input value="550.50">
<p>550.50</p>
```

When I apply my mask on the both elements, the `p` element doesn't convert correctly

```
<input value="550.50"> <!-- becomes 550,50 -->
<p>550.50</p> <!-- becomes 55.050 -->
```

**Comment by RobinHerbots** [comment]
@spacedog4 , 
I tried with the current version and it seems to work.
Can you provide some extra info about your mask and options used.  Also which version are you using?
