### ISSUE TITLE
Auto clear mask on left over characters

### ISSUE THREAD

**Issue by rafaelvasco** [RobinHerbots/Inputmask#208]
If i have a mask say, 99/99/99 in this state 99/**/** how to , when i blur the input, clear everything and leave 99 ? Looked over and over at docs and couldn't find an option to it. Thanks.

**Comment by RobinHerbots** [comment]
@rafaelvasco ,

There is no option for it, ... you can remove the mask on blur and reapply on focus

Robin

**Comment by rafaelvasco** [comment]
By remove you mean calling a predefined command or manually removing ?

**Comment by RobinHerbots** [comment]
@rafaelvasco ,

Yes,   $(selector).inputmask('remove'); => on blur and on focus you apply the mask

best regards, 

Robin

**Comment by robsoncombr** [comment]
Hello,

I would believe that this is really an issue, let me know if I misunderstood the clearIncomplete purpose or I'm doing something wrong.

I set the following:
$(selector).inputmask('(99) [9]9999-9999', { placeholder:" ", skipOptionalPartCharacter: " ", clearIncomplete: true });

When I type only '(00) 00000-00' and leave the field (blur), it clears the content on the screen.
When I click on field again (focus) it shows it like empty, but with the <spaces> chars filled like '(  )      -  ' and move the cursor to the end of the value, expecting the last 2 characters.
When I type the first 0 it shows '(00) 00000-000', it sounds like that the real value (cache) was not cleared.

So I followed your suggestion on this issue, add the mask on focus and remove on blur, so I set the following:
    $(selector).focusin(function() {
        $(this).inputmask('(99) [9]9999-9999', {
            placeholder:" ",
            skipOptionalPartCharacter: " ",
            onincomplete: function() {
                $(this).inputmask('remove');
            }
        });
    });

It worked good, by adding and removing the mask, but now I get a new behavior, that is a problem, when I leave the field (blur), by clicking on another-next field, it removes the mask but it focus the field back.

If I have it set to a Phone field and I click on my Name field, it removes the mask for Phone and focus to Phone where I can type anything without mask.

My understanding is that clearIncomplete is broken and .inputmask('remove') should not focus the field.

Please let me know.

Thank you,

Robson Martins

**Comment by RobinHerbots** [comment]
@robsoncombr, 

I fixed the clearincomplete and also a focus issue in checkval.

Your initial mask on focus should show  '( ) - '  in your case.  (the placeholder does not replace but maps input places of the mask. )

Robin

**Comment by robsoncombr** [comment]
Hello there Robin,

Thank you very much for the fix, I just upgraded my .js and now I noticed a new issue, with Multiple Masks, that was not happening before. I will file a new Issue for verification.

Robson
