### ISSUE TITLE
decimal and showMaskOnFocus=false in 5.x broken

### ISSUE THREAD

**Issue by elexx** [RobinHerbots/Inputmask#2080]
**Describe the bug**
In 5.x (tested with branch head and with tag 5.0.0-beta.130) the alias "decimal" behaves differently to 4.x when using showMaskOnFocus=false.

**To Reproduce**
1. Go to https://jsfiddle.net/ado3e07c/
2. Click the inputfield
3. Type "12.34"
4. The input gets cut and the textfield shows "0.12"

**Expected behavior**
The input does not get cut and shows "12.34", like it did in 4.x.x (https://jsfiddle.net/ehrkg8xv/)

**Live example**
v5.x.x https://jsfiddle.net/ado3e07c/
v4.0.4: https://jsfiddle.net/ehrkg8xv/

**Desktop**
 - OS: Windows 7
 - Browser: Chrome 72, Firefox 56, Firefox 65

**Comment by RobinHerbots** [comment]
@elexx , 

Thx for the issue .  I'm working on the numeric alias.

**Comment by RobinHerbots** [comment]
@elexx , 

Can you have a try with the latest version 5.0.0

**Comment by elexx** [comment]
I updated the jsfiddle to 5.0.0-beta.322: https://jsfiddle.net/Ltgufx6n/
The behavior is not slightly different, typing `12.34` now results in `0.34`

I also tried with the latest version from 5.x branch (https://jsfiddle.net/gsxzh90d/) but with no different result than in 5.0.0-beta.322.

**Comment by RobinHerbots** [comment]
@elexx , 

Ok, showMaskOnFocus: false seems to be the problem.
I will see for a fix

Btw: jsfiddle doesn't seem to work here

**Comment by RobinHerbots** [comment]
@elexx , 

Have a try with version 5.0.0-beta.323

**Comment by elexx** [comment]
Yes you did it, the issue is fixed! (https://jsfiddle.net/2j9f8okz/ with 5.0.0-beta.323)
