### ISSUE TITLE
initializing inputmask 2nd time

### ISSUE THREAD

**Issue by toxpal** [RobinHerbots/Inputmask#2083]
I'm not sure if this a a bug or correct behavior, so a simple explanation will probably be enough.

Like many devs, I use AJAX requests to add dynamic content to pages. And data received from ajax has fields that I want to apply Inputmask to. So, I need to initialize Inputmask again (to apply it for dynamic content which didn't even exist during page load). Here's the problem:

After initializing Inputmask 2nd time, original Inputmask fields (the same that existed during original page load) don't work properly (but dynamic fields work OK).

I'm not sure if this is a bug (Inputmask doesn't check if some field already has mask applied, so it applies mask 2nd time to the same field, causing problems) or correct behavior (if so, how can I initialize Inputmask for dynamic fields without screwing original fields)?

So far, I only experience this issue with Inputmask, while other Jquery plugins (like select2) work properly after 2nd, 3rd, and Nth initialization. I created a fiddle with detailed comments - https://jsfiddle.net/5sdr0wbm/

**Comment by RobinHerbots** [comment]
@toxpal, 

Initializing the inputmask multiple times shouldn"t be a problem.  But you are keen to detect edge cases ;-)
Also, the numeric alias isn't complete yet and that why there isn't a release yet for 5.x.  I hope I can fix the numeric alias soon, so that the response on issues goes up!

Anyway, with the latest you can apply the inputmask multiple times.  Btw have a look at the code in the inputmask.binding.js which can be usefull.

**Comment by toxpal** [comment]
Thanks for your usual super-fast response.

> Also, the numeric alias isn't complete yet and that why there isn't a release yet for 5.x.

Actually, the same issue exists with other masks too, just result is different. While numeric mask reverses digits during 2nd initialization, other masks "convert" placeholder into non-removable text.

For example, here's the email mask - https://jsfiddle.net/e8trycso/1/

> Btw have a look at the code in the inputmask.binding.js which can be usefull.

Thanks. I got a feeling I might need to use binding stuff right before creating this ticket :)

**Comment by RobinHerbots** [comment]
Ok, this is because thé inpumask uses thé Placebolder as input when applying a second time. Ik will fix this tomorrow.

Best regards
Robin

**Comment by RobinHerbots** [comment]
@toxpal , 

Ok fixed.

**Comment by toxpal** [comment]
Yes, it looks demo is fixed... Then I spent 4 hours trying to find out why this fix doesn't work on my environment...

And then I found it! That's because demo fiddle uses vanilla lib and I use JQuery! If you switch from inputmask.min.js to jquery.inputmask.min.js (while keeping the same version .137), you will notice that original bug will re-appear. 

I couldn't find jquery.inputmask.min.js on your RawGit page, but I re-created the original fiddle to use JQuery at https://jsfiddle.net/a8h1cmry/

Just load **jquery.inputmask.min.js** (not vanilla inputmask.min.js) into the fiddle, and it will start working right away, so you can see the original bug for yourself.

I know you are probably tired of my findings already, but I hope it's the last one...

**Comment by RobinHerbots** [comment]
@toxpal, 

The above fiddle did not include the jquery.inputmask.js.

This is an updated fiddle.  Is there a problem I am missing?
https://jsfiddle.net/csb73pft/

**Comment by toxpal** [comment]
> The above fiddle did not include the jquery.inputmask.js.

Yes, that's because I couldn't find jquery.inputmask.js on your rawgit account (so I couldn't include it in the fiddle). That's why I suggested to load it manually, so fiddle will start working.

> This is an updated fiddle. Is there a problem I am missing?
> https://jsfiddle.net/csb73pft/

Unfortunately, yes :) Please take a look at the first input field with numeric value. It displays 1.20 instead of 120. If you enter 60, it will display 0.60, and so on. In other words, original bug (with numbers) still appears on JQuery version, while it was successfully fixed on vanilla version.

**Comment by RobinHerbots** [comment]
@toxpal , 

Well that is interesting, ...

**Comment by toxpal** [comment]
It surely is... First I thought the issue is caused by my code and/or some other JS file in my script, so I started removing JS one after one, simplifying code, etc., until I reached the point where whole code contained just several lines and only JQuery and Inputmask was loaded, but problem still existed. That's when I realize that demo fiddle used vanilla Inputmask, and... bingo.

**Comment by RobinHerbots** [comment]
@toxpal , 

I can reproduce it locally.  I wil see why it happens

**Comment by RobinHerbots** [comment]
@toxpal , 

It was caused by the numeric alias.   Why it comes up when using jQuery is because you use the jquery-plugin instead of the bare inputmask.  (See jquery.inputmask.js in lib folder)

Anyway, I would be nice if I could finish up the numeric alias, so I can continue on more interesting parts.

**Comment by toxpal** [comment]
> Anyway, I would be nice if I could finish up the numeric alias, so I can continue on more interesting parts.

Yes, that would be great. This fix works most of the time, but there are still some cases (especially when using currency/numeric mask) when problem still exists after 2nd initialization. Hope you will find some courage to complete this boring task in future :)
