### ISSUE TITLE
Regex by function?

### ISSUE THREAD

**Issue by BrainFeeder** [RobinHerbots/Inputmask#2085]
Is it possible to have a function pass a regex? I would like to switch to different regex patterns when a certain field has a certain value. I tried some stuff but it kept resulting in errors like '.replace is not a function'.

        $('input[name="vat"], input[name="temp[vat]"]').inputmask({
		regex: function() {
                    if(true) {
			    return "(BE 0[0-9]{3}\\.[0-9]{3}\\.[0-9]{3}|BE 1[0-9]{3}\\.[0-9]{3}\\.[0-9]{3}|BE [0-9]{3}\\.[0-9]{3}\\.[0-9]{3})";
                    }
                    else {
                        return "(0[0-9]{3}\\.[0-9]{3}\\.[0-9]{3}|1[0-9]{3}\\.[0-9]{3}\\.[0-9]{3}|[0-9]{3}\\.[0-9]{3}\\.[0-9]{3})";
                    }
		},
		casing: 'upper',
        });

**Comment by RobinHerbots** [comment]
I guess like this it should work

> ```
>     $('input[name="vat"], input[name="temp[vat]"]').inputmask({
> 	regex: (function() {
>                 if(true) {
> 		    return "(BE 0[0-9]{3}\\.[0-9]{3}\\.[0-9]{3}|BE 1[0-9]{3}\\.[0-9]{3}\\.[0-9]{3}|BE [0-9]{3}\\.[0-9]{3}\\.[0-9]{3})";
>                 }
>                 else {
>                     return "(0[0-9]{3}\\.[0-9]{3}\\.[0-9]{3}|1[0-9]{3}\\.[0-9]{3}\\.[0-9]{3}|[0-9]{3}\\.[0-9]{3}\\.[0-9]{3})";
>                 }
> 	})(),
> 	casing: 'upper',
>     });
> ```

**Comment by BrainFeeder** [comment]
Ahh Yes! Thank you for fast response!
