### ISSUE TITLE
how to use phone-codes mask in the latest inputmask library?

### ISSUE THREAD

**Issue by saravanan-cm** [RobinHerbots/Inputmask#2087]
**Phonecodes in latest version of inputmask**
Previously in my web app I used input mask version 3.2*. Now I upgraded it to latest version. It's started throwing some errors like phone-codes mask file is not found. In my old version it's there in `input-mask/dist/inputmask/phone-codes/phone.js`, But in the new version phone-codes folder itself is not there.

**Expected behavior**
phone codes mask should work.

**Desktop (please complete the following information):**
 - OS: Ubuntu 16
 - Browser: Chrome
 - Version: 73

**Additional context**
Kindly help me to resolve it ASAP. Did you deprecated this one or changed the name of it?

**Comment by RobinHerbots** [comment]
@saravanan-cm , 

The phone alias is moved to a separate repo.  

https://github.com/RobinHerbots/inputmask.phone

**Comment by saravanan-itilite** [comment]
Thanks @RobinHerbots  Got it.
