### ISSUE TITLE
The first character is truncated when masking.

### ISSUE THREAD

**Issue by alex-zzz** [RobinHerbots/Inputmask#2089]
**Describe the bug**
When I use the regex "\\ + 995 \\ d {9}" and the masked value starts with 5 or 9, the first character of the value is truncated.

**To Reproduce**
1. Apply mask to text input with an existing value starting with 5 or 9
2. See that first character of the masked value is truncated.

**Expected behavior**
Masked value is not truncated.

**Live example**
https://plnkr.co/edit/gJGTTt?p=preview

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Chrome
 - 72

**Smartphone (please complete the following information):**

**Additional context**

**Comment by RobinHerbots** [comment]
@alex-zzz , 

I will try to fix this this week.

**Comment by RobinHerbots** [comment]
@alex-zzz , 

Have a look at the new https://plnkr.co/edit/C5ei15BdhzOiUMYw7Y0l?p=preview

**Comment by alex-zzz** [comment]
Hi,
Thank you very much.
But it would be great if you provided a version for use with reqirejs.
I cannot test webpack module in my project unfortunately:(

**Comment by alex-zzz** [comment]
![image](https://user-images.githubusercontent.com/25524530/55264513-53b0dc00-527d-11e9-93f3-1c66567d6daa.png)

**Comment by RobinHerbots** [comment]
When exactly does the error occur?
Also requirejs should work.

**Comment by alex-zzz** [comment]
Thank you very much, I figured out the error described above. That was my mistake, I passed a string into the DateTime field.
But I ran into another issue. When I try to mask field with Date object value, I get wrong DateTime value. And if I try to format Date object value I get an error "(($.isFunction(...) && opts.onBeforeMask.call(...)) || actionObj.value).split is not a function"

https://plnkr.co/edit/IRiiFZ4WKue4Fkidn7yj?p=preview

What am I doing wrong?

Regarding the the question about requirejs, my project uses AMD approach and I can use your module in my structure

define("TsiJQueryInputMask", ["jQuery"], function () {

   your module
   
})

only if I replace "if ("function" == typeof define && define.amd) define([ "jquery" ], factory)" with "if ("function" == typeof define && define.amd) factory(root.jQuery)".

Thanks in advance!

**Comment by toxpal** [comment]
If I understand right, this update was released to v5 beta 142? Unfortunately, it breaks other numeric things. Remember when numerics were displayed incorrectly after initializing inputmask 2nd time? https://github.com/RobinHerbots/Inputmask/issues/2083

It was fixed, but version 142 makes it even worse :) Now, it's not even needed to initialize inputmask 2nd time, numerics are displayed incorrectly right from beginning. See here - https://jsfiddle.net/q6p5hx2t/

Downgrading back to 141 fixes the issue.

**Comment by RobinHerbots** [comment]
@toxpal , 

Thx for the feedback/
No it isn't due the changes specific to this issue, but changes on fixing the numeric alias.

Remember that the 5.x is beta, and can and will break things.
