### ISSUE TITLE
The long text doesn't scroll

### ISSUE THREAD

**Issue by ychumak** [RobinHerbots/Inputmask#209]
I have a long text input control, let say 'size=50'. When the text has reach the control's right side while I keep typing the it is not scrolling. So I don't see how my text is entering.

**Comment by RobinHerbots** [comment]
@ychumak , 

I will have a look at it.

best regards, 

Robin

**Comment by Talkless** [comment]
Same issue for me in Android (PhoneGap 2.9.0, jquery-mobile 1.3.1).

**Comment by RobinHerbots** [comment]
@ychumak , 

Can you have a try with the latest version.
