### ISSUE TITLE
After Xcode updating (10.2 (10E125) with Swift 5) listener object returns AppDelegate error «*** Terminating app due to uncaught exception 'NSGenericException', reason: 'This coder requires that replaced objects be returned from initWithCoder:'» 

### ISSUE THREAD

**Issue by VikhlyaevSergey** [RobinHerbots/Inputmask#2092]
But when I deleted, everything worked

**Comment by VikhlyaevSergey** [comment]
deleted listener object*

**Comment by VikhlyaevSergey** [comment]
Please fix it, I need you’re framework)))

**Comment by VikhlyaevSergey** [comment]
This error appears when I using .xib + Object (listener), but when I using only code, it’s works good!

**Comment by lbrdev** [comment]
Same

**Comment by RobinHerbots** [comment]
@VikhlyaevSergey , @lbrdev , 

Is this an issue for Inputmask?

**Comment by argomis** [comment]
Hello.
Same issue and same source, if I delete the MaskedTextFieldDelegate from the storyboad it works

**Comment by lbrdev** [comment]
@VikhlyaevSergey , @argomis we've mixed up repo. https://github.com/RedMadRobot/input-mask-ios/issues/69 issue in RedMadRobot's repo.
@RobinHerbots sorry, I think you can close this.
