### ISSUE TITLE
Optional with greedy: false behaves greedily when extra character are included in the optional

### ISSUE THREAD

**Issue by THammond9** [RobinHerbots/Inputmask#2094]
**Describe the bug**
I am not sure if this is a bug or not. Here is the mask:
mask: "[9{3}][-9{2}][-9{4}]", greedy: false

In version 3.3.5 (any version less than 4) the mask would behave like this:
123-45-67
but in latest version (any version => 4) the mask behaves like:
123-45-67__

**To Reproduce**
use the mask provided above in the latest version and see that it behave greedily after the first optional set.

**Expected behavior**
I would like (and expect) the mask to behave like it did in version 3.3.5. If this is a bug or expected behavior how can the mask be changed to work like it did in 3.3.5? If this is expected behavior why is it not greedy on the first optional set and greedy on the other optional sets?

**Live example**
[version 3.3.5](https://jsfiddle.net/cqx71pe5/1/) (expected/desired behavior)
[version 4.0.6](https://jsfiddle.net/pjuLngh9/)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 73.0.3683.86

**Comment by guredd** [comment]
Any plans fixing this? Facing same issue.

**Comment by RobinHerbots** [comment]
@guredd , 
Actually version 4 has the correct (logical) behavior.

[] marks an optional part, but that means the whole part.  So -9{4} == -9999  

You can use -9{0,4} to get the behavior

**Comment by guredd** [comment]
@RobinHerbots 
Nope, it does not work in Version: 5.0.3 with greedy: false and regex mode.

Sample code :
```html
<html lang="en">
<head>
 <script>
        $(document).ready(function() {
            $("#id").inputmask({
                regex: 'A(\\d{1}|\\d{3})',
                greedy: false,
                oncomplete: function () {
                    alert($("#id").val());
                }
            });
        });
    </script>
</head>
<body>
    <input id="id"/>
</body>
</html>
```

Enter A1 and you will get "A1_" as value. Placeholder remains inside value.

**Comment by RobinHerbots** [comment]
@guredd , 

The example you give is a total different scenario.  See #2277
