### ISSUE TITLE
Decimal - auto change comma to dot (numeric keyboard)

### ISSUE THREAD

**Issue by kpyrdol** [RobinHerbots/Inputmask#2098]
Hi! I was using old version of plugin but it is not working on mobile right now. I upgraded and I can't replace comma (from numeric keyboard) to dot. I was using 
` $('.change-dot').keydown(function (e) {
            if (e.keyCode === 188 || e.keyCode === 110) {
                $(this).val($(this).val() + '.');
                return false;
            }

        });`
and 
` $('.decimal-plus').inputmask('decimal', { allowMinus: false, radixPoint: '.', digits: 3 });`

It was working perfect, now I have to press dot, comma is not changing in my function. Can you provide such a functionality?

**Comment by RobinHerbots** [comment]
@kpyrdol , 

Fixed in   "version": "5.0.0-beta.300"
