### ISSUE TITLE
masks in the numeric extension can't unmask

### ISSUE THREAD

**Issue by dehy** [RobinHerbots/Inputmask#210]
$('#field').inputmask('decimal');
$('#field').inputmask('unmaskedvalue'); <== trigger an error

Example : http://jsfiddle.net/xZmVQ/2/

**Comment by RobinHerbots** [comment]
I will have a look at it.

Robin

**Comment by dehy** [comment]
The exact error is on line 1997 of `jquery.inputmask.bundle.js` v2.2.2

> 'undefined' is not an object (evaluating 'opts.regex.number')

Thank you and thanks for your jquery plugin ! :)

**Comment by RobinHerbots** [comment]
@dehy, 

The latest fixes the error, but the unmaking isn't type aware for the moment.

Robin
