### ISSUE TITLE
Why i am able to delete the mask?

### ISSUE THREAD

**Issue by avxkim** [RobinHerbots/Inputmask#2100]
![inputmask](https://user-images.githubusercontent.com/5739191/55741052-2bc83200-5a4e-11e9-82cb-b6067f76d2f5.gif)

Using latest version 4.0.6

Here's my mask:

```
let selector = document.getElementsByClassName('number-block__number-input')
Inputmask({
  mask: '+7 (799) 999-99-99',
  autoUnmask: true,
  showMaskOnHover: false,
  oncomplete: () => this.buttonIsDisabled = false
}).mask(selector)
```

When user deletes a mask, then i can't start to type my number with 7, any other number works, but not 7.

**Comment by RobinHerbots** [comment]
@heihachi88 , 

Can you have a try with version 5.x.

**Comment by avxkim** [comment]
@RobinHerbots, would try on this weekend, would post back.

**Comment by adlerdias** [comment]
@RobinHerbots 

it's working as expected in latest beta. so this issue can be closed.

https://jsfiddle.net/adlersd/gx7s1bha/

![masktest](https://user-images.githubusercontent.com/307859/69146688-1f5d8a80-0aaf-11ea-9c2b-94dc00142225.gif)
