### ISSUE TITLE
how can I add props hasMaskedValue to native object

### ISSUE THREAD

**Issue by cyhwinner** [RobinHerbots/Inputmask#2106]
Now I am write  Inputmask({ mask: '99/99/9999' }).mask(input).
but I want to use hasMaskedValue,what need to do

**Comment by cyhwinner** [comment]
i saw it，just not support

**Comment by RobinHerbots** [comment]
@cyhwinner , 

What do you mean exactly?

**Comment by cyhwinner** [comment]
originally, because of my careless i want to use hasMaskedValue via Inputmask class,  then i saw this method  only works in jquery ,sry

**Comment by RobinHerbots** [comment]
@cyhwinner , 

It also work without jquery, you need to call it on the inputmask object.

input.inputmask.hasMaskedValue()
