### ISSUE TITLE
Configure min date time and use same day and posterior time. Not Working

### ISSUE THREAD

**Issue by lenonestrella** [RobinHerbots/Inputmask#2107]
**Describe the bug**
It is not possible to configure a `min` datetime and use this date with a posterior time.

**To Reproduce**
1. Fill input with a valid date with a few hours after the minimum date configured (e.g 01/01/2019 20:30)
2. Check that is not possible to complete inserting the date. The number `9` is not inserted on the input, and the time is not inserted either.
3. Alternatively, use the `Fill Date` button to use JS to fill the date and time, and see the same problem occur.

**Expected behavior**
It should be possible to use a date time that is after the minimum date configured.

**Live example**
https://jsfiddle.net/1knmy3p4/3/

**Comment by RobinHerbots** [comment]
@lenonestrella,

This is fixed in version 5.0.7-beta.12
