### ISSUE TITLE
Multiple masks: random inserted character

### ISSUE THREAD

**Issue by xaqtr** [RobinHerbots/Inputmask#2109]
I get a strange behavior when using Inputmask 4.0.8 with multiple masks starting with static characters. In  [this fiddle](https://jsfiddle.net/w1sm9htj/) I defined multiple masks for IBANs. 

When you type "**D**", you are able to type either "**K**" or "**E**" next and this works. However, when you type "**P**" or "**S**" ( and many other characters), the character "**T**" gets inserted next automatically.

This is especially odd because it seems to work with [version 3.3.4](https://jsfiddle.net/23dezx1g/) but not with [version 3.2.5](https://jsfiddle.net/q4np2ecu/).

**Comment by RobinHerbots** [comment]
@xaqtr , 

Even with the latest beta the problem is there.

https://jsfiddle.net/tv5zf4p7/

I will have a look

**Comment by RobinHerbots** [comment]
@xaqtr , 

The char A is a mask definition so you need to escape it to use it as a static char.

https://jsfiddle.net/rfjegmk9/1/
