### ISSUE TITLE
Multiple masks not working correctly on international phone and US phone numbers

### ISSUE THREAD

**Issue by gabbaca** [RobinHerbots/Inputmask#211]
When trying to mask a us phone and an international phone, the mask always defaults to the US phone.

```
$("#Phone1").inputmask({ mask: ["999-999-9999 [x99999]", "+099 99 99 9999[9]-9999"] });
```

For example when typing +011 99 99 9999-9999 masks to 011-999-9999 x99

Here is demo http://jsfiddle.net/XzeSY/1/

**Comment by RobinHerbots** [comment]
@gabbaca , 

I noticed the same issue when trying the mask in issue 205.
I will try to fix it asap.

best regards
Robin

**Comment by RobinHerbots** [comment]
@gabbaca, 

The latest version fixes the issue. 

But I still need to fix when you type +01231 and you backspace to the beginning, the mask does not switch back to the first mask, .... selecting all and backspace works

I wil fix the backspace issue soon

Robin

**Comment by RobinHerbots** [comment]
Othe issue also fixed

**Comment by gabbaca** [comment]
Thanks for the quick fix Robin!

**Comment by gabbaca** [comment]
I was testing this mask with IE8 and it looks like there is an error with indexOf

**Comment by RobinHerbots** [comment]
pfff  not again, ... I ***\* IE8, ... i will have a test in ie8 tomorrow

**Comment by gabbaca** [comment]
Yeah I feel your pain :(

But I would like to thank you for a great plugin and all the hard work you've put into it.

**Comment by RobinHerbots** [comment]
the shared pain did it, .. ie8 issue fixed in the current ;-)

**Comment by gabbaca** [comment]
Looks good, thanks.

**Comment by RobinHerbots** [comment]
I found another issue.

The optional in the second mask is not working correctly.
I will  try to fix this.

**Comment by RobinHerbots** [comment]
fixed
