### ISSUE TITLE
If a decimal < 0.000001 (scale =  6), masked value incorrect.

### ISSUE THREAD

**Issue by Argun** [RobinHerbots/Inputmask#2110]
**Describe the bug**
If a decimal < 0.000001 (scale =  6), masked value incorrect.

**Live example**
https://jsfiddle.net/Argun/r0y3L9wb/

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: chrome
 - Version: 74.0.3729.131 (Official Build) (64-bit)

**Comment by RobinHerbots** [comment]
@Argun, 

Fixed in version 5.0.0-beta.298

https://jsfiddle.net/dc3jn76x/
