### ISSUE TITLE
The numeric mask removes the last digit after 'k' and 'm' keys

### ISSUE THREAD

**Issue by jajajaja** [RobinHerbots/Inputmask#2113]
**Describe the bug**
The numeric mask removes the last digit after 'k' and 'm' keys and loss of focus.

**To Reproduce**
1. Create a input with default numeric mask.
2. Enter '1' and press 'k' keys. As expected value is changed to '1000'
3. Change focus, for example by 'tab' key
4. Value in the input is changed to '100'

**Expected behavior**
Value is remaining '1000'

**Live example**
https://jsfiddle.net/jajajaja/e2a06fxo/8/

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version 73

**Additional context**
Version : 4.0.8
With attribute clearMaskOnLostFocus == false numeric mask works as expected.

**Comment by RobinHerbots** [comment]
@jajajaja , 

I updated the jsfiddle

https://jsfiddle.net/7tfLr12d/

Can you have a try.
