### ISSUE TITLE
Wrong behaviour when numericInput=true

### ISSUE THREAD

**Issue by arkadyzalko** [RobinHerbots/Inputmask#2115]
I'm using version 3.08 and I can't set properly using `val` or `setvalue` when I set `numericInput=true`.

The plugin inputmask doesn't recognize radix and replace it to `0`.

**To Reproduce**
1. Set inputmask 
```inputMasked.inputmask('currency', {
  placeholder: '0.00',
  prefix: '',
  min: 0,
  max: 1000.00,
  numericInput: true,
  inputType: 'number',
  radixPoint: '.',
  groupSeparator: ',',
})
```
2. run `inputMasked.val(1.23)`
4. See error: `inputMasked` displays `10.23` (*wrong value*)

**Expected behavior**
Run `inputMasked.val(1.23)` and displays `$ 1.23`

**Live example**
https://codepen.io/anon/pen/zQErKZ

**Additional context**
I've already tested using `setvalue` and I got the same result

**Comment by arkadyzalko** [comment]
Do you need help to fix this? I can create a PR.

**Comment by RobinHerbots** [comment]
@arkadyzalko , 

You may send a PR. 

best regards 
Robin
