### ISSUE TITLE
Mask displayed incorrect after I remove one digit

### ISSUE THREAD

**Issue by thangleBstar** [RobinHerbots/Inputmask#2117]
**Describe the bug**
Hi, 
I using in Reactjs in latest version, my apply in below:

```
const im = new InputMask('decimal', {
      radixPoint:",",
      groupSeparator: ".",
      autoGroup: true,
      digits: 2,
      digitsOptional: false,
      placeholder: '0',
      rightAlign: true,
      onBeforeMask: function (value, opts) {
        return value;
      }
    })
    im.mask(this.inputRef)
```

when input number e.g: 5,000,000.00 and remove 5 from the above number then i got 0,000.00. I see in many example it must be 0.00. How can i fix it? I want to see result like [here](https://jsfiddle.net/0syp89wr/9/)
Many thanks.

**Comment by RobinHerbots** [comment]
@thangleBstar ,

I updated the fiddle to the latest **beta** version. https://jsfiddle.net/xhsodfez/2/

For the issue.  In the current version this seems broken.  In the beta version I'm rewriting the decimal alias.  I will add this in the 5.x branch.

**Comment by RobinHerbots** [comment]
@thangleBstar , 

This is fixed in the latest v 5.x
