### ISSUE TITLE
Value shifted

### ISSUE THREAD

**Issue by dousee163** [RobinHerbots/Inputmask#2119]
`<input id="test11" value="2018-01-01 12:34">`

```
$('#test11').inputmask({
	alias: "datetime",
	inputFormat: "yyyy-mm-dd HH:MM"
});

```
The input value auto change to 2018-01-01 01:23.

**Comment by dousee163** [comment]
https://jsfiddle.net/dousee/vowjc4ak/1/

**Comment by toxpal** [comment]
Any update on this, please? The same issue also exists for dates, not only hours. Please see updated fiddle at https://jsfiddle.net/xcg6mvw0/ (it should display 11 as month, but it displays 01)

**Comment by toxpal** [comment]
Dates are broken badly :( 

Another example with even more errors - https://jsfiddle.net/9awqvkfj/1/

**Comment by toxpal** [comment]
I see a new version was just released, it says "shiftPositions update + keepstatic defaults update".

Does it mean this issue was addressed? I had to completely disable InputMask on my scripts now, would like to use it again because it's just great.

**Comment by RobinHerbots** [comment]
@toxpal , 

No, this is not related.  I will refocus on dates, so that this gets solved.

**Comment by toxpal** [comment]
Thank you in advance.

**Comment by toxpal** [comment]
I realize I'm pain in the ***, but do we have any hopes for this fix soon? :)

**Comment by RobinHerbots** [comment]
@toxpal , 

You are toxic ;-)

Yes yes, the next commit will fix.

**Comment by RobinHerbots** [comment]
@dousee163, @toxpal, 

The issue is fixed.

https://jsfiddle.net/f0gs5oka/

**Comment by toxpal** [comment]
Thank you, will definitely test it!

**Comment by toxpal** [comment]
Tested and dates seem to work well. Didn't test other things yet (to ensure new build doesn't introduce any regressions), but hopefully they will work as expected. 

Thank you for your plugin and prompt solutions once again.
