### ISSUE TITLE
isComplete

### ISSUE THREAD

**Issue by err0x1a** [RobinHerbots/Inputmask#212]
Firstly I would like to thank, I tested several plugins, and this is the only one that approaches perfection, thanks for the efforts.

I am having problem with the method isComplete, any field I try it gives this error:
- <HTMLInputElement> Object # has no method 'split'
- Line 684: return t = this.data("inputmask").masksets, p = this.data("inputmask").activeMasksetIndex, a = this.data("inputmask").opts, Q(this[0].split(""));

**Comment by err0x1a** [comment]
Hi, on the Notepad++ the line is 162, inside a: case "isComplete".

The solution is take the value of the element, like this:

Original: return isComplete(this[0].split(''));
Modified: return isComplete(this[0].value.split(''));

Hope this help.

**Comment by RobinHerbots** [comment]
@herz-atk ,

Thx for the compliment, ... but perfection is still a long way to go ;-)

Anyway the iscomplete isue is fixed.  (thx for the solution.
