### ISSUE TITLE
Question: validate regex

### ISSUE THREAD

**Issue by mrdo23** [RobinHerbots/Inputmask#2120]
Hi there,

I would like to force an input that does not match the regex expression to be treated as invalid with jquery (unobtrusive) validation: e.g if a user does not input a US zip code in the correct format, validation fails for that element. 
Currently, validation only checks that the input is not empty. Can this be done, preferably via a data attribute?
<input id="test4" name="test4" data-val="true" data-inputmask-regex="^[0-9]{5}(?:-[0-9]{4})?$" data-val-required="zip is required." />
Thanks in advance.

**Comment by RobinHerbots** [comment]
@mrdo23 , 

I think you have mistaken, and created the issue in the wrong project.

Best regards,
Robin

**Comment by mrdo23** [comment]
Hi there,
Thanks for taking the time to reply. I'm not quite sure what you mean? 
Are you saying that the library cannot influence validation or something else?
Thanks again.

**Comment by mrdo23** [comment]
Hi, it looks like unobtrusive validation will handle this natively. Thanks for taking the time to reply.
