### ISSUE TITLE
12Hr Format time Hour error

### ISSUE THREAD

**Issue by pikaclint** [RobinHerbots/Inputmask#2121]
Hi firstly thank you I love the mask you've made it is just what I needed.

**Describe the bug**
So based on the sample given it expects a 12 hour format time, if you first type in "09:20 AM" it is correct, now try typing again replace the 09 and type in 1 and you will get 19:20 AM.

**To Reproduce**
1. First type in "09:20 AM"
2. Next replace the 09 in "09:20 AM" and type in 1 and you will get 19:20 AM.

**Expected behavior**
My expectations are 1 cannot be typed when the digits next to it is between 3-9

**Live example**
https://jsbin.com/yeguhusiqu/edit?html,output

using google chrome

**Comment by RobinHerbots** [comment]
@pikaclint , 

Version 5.x already gives a better result.  If will show 12:20, but even that is not correct.  

I'm currently focussing on the numeric alias.  But I will fix this as soon I find some time.

I suppose the behavior should be when replacing 09 with one it shows 10:20 and put the caret after 1 ?

**Comment by pikaclint** [comment]
Hey man thanks for the fast response I think what you suggested would be a great fix. As long as it could avoid wrong data being inputted in the mask :)

**Comment by RobinHerbots** [comment]
@pikaclint, 

The latest 5.x beta fixes the issue
