### ISSUE TITLE
extra decimal on greedy input

### ISSUE THREAD

**Issue by DanTosto** [RobinHerbots/Inputmask#2123]
Hello. Great plugin. 
Doing almost everything I want, except for a couple situations with this 3-decimal greedy input.

I want to allow numbers from 0.001 to 999.999.
We seem to be getting an extra decimal point at times:

1. If the first char entered by user is a decimal: **..00** 
Ideally we should still see 0.000 and just move the caret to after the decimal. 
To see .000 without the leading 0 would also be ok.

2. A number >= 100: **100.00.**
The second decimal should be a 0

Please see https://jsfiddle.net/qdrczLps/1/

Thank you for your time.

**Comment by RobinHerbots** [comment]
@DanTosto, 

The extra dot is because you specify a placeholder like 0.000.  Just change it to 0 fixed the extra dot.  
Why don't you use the decimal alias?  (and a newer version of inputmask)

**Comment by DanTosto** [comment]
Changing the placeholder as you suggested fixes both mentioned issues. Thank you.
This input now does exactly what I want without an alias.
Also this version of inputmask has desirable behavior on datetime inputs that seems to be different in the current version.

Closing this issue. Thanks again.

**Comment by RobinHerbots** [comment]
@DanTosto , 

The idea is to surpass the functionality of the datetime masks.  But it is true that I'm not there yet.  The new inputmask core is better, but the extensions are not finished.   Version 5.0 will contain a rewritten numeric alias and a datetime alias which do at least the same as the datetime masks in version 3.x.

Please provide feedback (or better create issues) about the datetime masks so I can take it into acount.

**Comment by DanTosto** [comment]
Thank you Robin, much appreciated - I have created issue 2124 about the specific datetime difference I'm seeing between 3.3.4 and 4.0.8.
Given the flexibility of this plugin, I would not be surprised if there is a workaround or if I did something incorrectly, I'm still learning how to use it.
Cheers.
