### ISSUE TITLE
datetime behavior when Day portion is deleted

### ISSUE THREAD

**Issue by DanTosto** [RobinHerbots/Inputmask#2124]
I'm trying to use v4.0.8 to reproduce the behavior in this fiddle which uses 3.3.4 for a mm/dd/yyyy datetime mask: https://jsfiddle.net/cr15tL3q/2/
If we enter 01/01/2000 and the delete the Day portion, the input displays **01/dd/2000**.

Using 4.0.8 with almost the same code and deleting the Day, the input displays **01/20/00yy**.
https://jsfiddle.net/cr15tL3q/3/
This behavior is also seen on your Demo page.

I thought shiftPositions: false would address the shifting, how else can I adjust my code to keep the digit positions and get the desired behavior when deleting?

**Comment by RobinHerbots** [comment]
@DanTosto , 

See #2163
