### ISSUE TITLE
Allow space as part of the regular static input mask

### ISSUE THREAD

**Issue by admrbsn** [RobinHerbots/Inputmask#2125]
I wish there was a way to use the regular static input mask and allow for both numeric and spaces. For example, I'm using `mask: '+999999999999999'` for a simple international phone number. I could do, `regex: [0-9 ]{0,15}`, but then I lose the added plus sign in the beginning. Any way to allow numeric AND spaces and retain the plus sign in the beginning?

**Comment by RobinHerbots** [comment]
@admrbsn , 

add \\\\+ to the regex should do.

But I will keep the issue open because I want a mask like +(9| ){0,15} to work.

**Comment by Jogai** [comment]
Is there any work done on issues marked by "Enhancement"? This is one I could use.

**Comment by RobinHerbots** [comment]
> Is there any work done on issues marked by "Enhancement"? This is one I could use.

Not yet
