### ISSUE TITLE
Email mask doesn't validate if field type is email

### ISSUE THREAD

**Issue by trodicaro** [RobinHerbots/Inputmask#2126]
**Describe the bug**
When email mask applied to the input field, the mask works if the field type is text, and it doesn't if field type is email.

**Expected behavior**
It should show the placeholder "_@_._" on hover over. It should work as an input mask where, when typed it, it shows the remainder of the mask to fill in.

**Live example**
https://jsfiddle.net/1qe2rbtb/

![Screenshot from 2019-06-05 14-15-54](https://user-images.githubusercontent.com/4808140/58983497-953d9600-879c-11e9-9ded-84ffae13bbe5.png)

**Desktop (please complete the following information):**
 - Browser: Chrome
 - Version: 72.0.3626.119

**Comment by RobinHerbots** [comment]
@trodicaro , 

See https://github.com/RobinHerbots/Inputmask/issues/828#issuecomment-76715820
