### ISSUE TITLE
How to disable typing decimals first after text selected currency

### ISSUE THREAD

**Issue by hkooiker** [RobinHerbots/Inputmask#2128]
I have an inputmask of type currency with prefix: "€ ".
Now if i select the text in the input field and type "5" i expect the value to be € 5,00 but it show € 0,05.
How do i get this done?

**Comment by RobinHerbots** [comment]
@hkooiker , 

Is this in version 5?

**Comment by hkooiker** [comment]
Yes, this is in version 5.

**Comment by RobinHerbots** [comment]
@hkooiker , 

Ok working on it

**Comment by RobinHerbots** [comment]
@hkooiker , 

This issue is fixed in v 5.0.0-beta.193

**Comment by RobinHerbots** [comment]
@hkooiker, 
it is partially fixed.  I will try to push a final fix tomorrow/
