### ISSUE TITLE
v5 Beta - Field filling history steals focus

### ISSUE THREAD

**Issue by toxpal** [RobinHerbots/Inputmask#2129]
I'm using Inputmask along with other plugins, such as bootstrap-datepicker. Everything worked great with v5 Beta until recent builds.

Now, field typing history takes focus of input element, making other parts unusable. I know it's difficult to understand, so take a look at screenshots:

"Old" builds of v5 - https://i.postimg.cc/TwYfWqmF/before.png
As you see, InputMask (which I set to use YYYY-MM-DD format) works great with date picker.

Recent builds of V5 - https://i.postimg.cc/Dys0h6cP/after.png
Typing history appears and steals focus from date picker.

The same issue also exists with HH:MM input masks. However, it does NOT exists with email and numeric masks (they continue to work as usually). According to my experience, InputMask was always disabling field filling history for corresponding fields (so mask was properly visible), but recent builds changed this behavior for date and time fields.

**Comment by RobinHerbots** [comment]
@toxpal , 

This is related to Chrome autofill does not work with Inputmask #1330.

I will look further into this.

**Comment by RobinHerbots** [comment]
@toxpal, 

What is the behavior without inputmask?  Does it also try to autofill?

**Comment by toxpal** [comment]
Yes, it tries to do exactly the same without inputmask. However, having inputmask (currently using 5.0.0-beta.141 because it works best for my needs) disables such filling and all fields look perfect. However, it's not the case with recent builds because form history steals focus with new builds only.

P.S.In my situation, it's not autofilling, it's field history (values that I have been entering in the past) which breaks things. In other hand, maybe both autofill and form history work the same way, I'm not really sure. Just wanted to clarity if.

**Comment by RobinHerbots** [comment]
@toxpal , 

Inputmask should not alter default browser behavior as much as possible.  The previous versions did not allow the autofill from chrome to happen.  This is changed in more current versions.  Version 5.0.0-beta 191 does allow the autofill, but keeps focus to the input.  Can you have a try.  Otherwise you should open issues on the other plugins, as it also happens when not using the inputmask.  

I know the previous behavior fixed your problem, but for others it breaks desired behavior.

**Comment by toxpal** [comment]
> Version 5.0.0-beta 191 does allow the autofill, but keeps focus to the input. Can you have a try.

Of course. However, I only see Beta 190 in your repository at the moment?

**Comment by RobinHerbots** [comment]
Version 190 is the same ;-)

**Comment by toxpal** [comment]
Unfortunately, it's the same. Oh well, I can always continue using old builds :)

**Comment by RobinHerbots** [comment]
@toxpal , 

Look for eventruler in the code. And remove Case "focus"

```
	case "click":
	case "focus":
		args = arguments;
		setTimeout(function () { //needed for Chrome ~ initial selection clears after the clickevent
		eventHandler.apply(that, args);
		}, 0);
		return false;
```

**Comment by toxpal** [comment]
Thanks, will try tomorrow!

**Comment by toxpal** [comment]
I was able to fix it with `autocomplete="off"` for specific fields, so I don't need to modify your builds and can use new builds easily. Thank you for your support!
