### ISSUE TITLE
Mask doesn't update on Windows 8 mobile or Blackberry playbook

### ISSUE THREAD

**Issue by gavmck** [RobinHerbots/Inputmask#213]
When typing into a masked text input on Windows 8 mobile or Blackberry Playbook, the mask stays as per the original and doesn't remove itself as you type until you exit the field.

Have tried manually triggering keyup, keydown, keypress and change using a setInterval running whilst focused in the field, but seems to have no effect. Which event is updating the mask bound to?

**Comment by gavmck** [comment]
Just noticed same issue on Opera mobile on Android Nexus 4

**Comment by RobinHerbots** [comment]
@gavmck ,

I don't own a win8 mobile device or blackberry, ... so to solve this I need more info.

Can I download a virtual win8 mobile device emulator and a blackbarry one?  Can you submit the useragent string per device?  I will test the opera on android.

best regards, 

Robin

**Comment by gavmck** [comment]
Hey thanks for the fast reply! Great plugin by the way.

The windows 8 emulator is packaged up in the windows mobile SDK which you can grab here I think: http://dev.windowsphone.com/en-us/downloadsdk

I'll go find a blackberry emulator next. Will get the UA strings tomorrow as they're office test devices.

Thanks

**Comment by gavmck** [comment]
Do you have another tablet available? This appears to run a blackberry VM http://www.softpedia.com/get/Programming/Other-Programming-Files/BlackBerry-Playbook-Simulator.shtml

**Comment by gavmck** [comment]
Doing some testing over here today.

It appears Opera Mobile, Blackberry playbook and the Windows 8 mobile are not firing the onkeypress event.
Checked for support and they all say that they support onkeypress in my input.

Windows 8 mobile fires the keyup event
Opera Mobile fires a keyup event onfocus, but nothing after that. Just updates onblur
Playbook doesn't fire keyup or keypress

Will update with more info as I get it

**Comment by gavmck** [comment]
Strangely all browsers return true for: 'onkeypress' in document.createElement('input');

**Comment by gavmck** [comment]
Scratch that Opera fires keypress events after the mask area but not in it.

**Comment by sompylasar** [comment]
Just a thought. The "keypress" event might be present in the object because
of the standard and/or because a real keyboard may be somehow connected to
a Windows 8 device. But it never fires because the virtual onscreen
keyboard may generate input another way, e.g. paste a whole word from the
dictionary. AFAIK, there is the "input" event for these cases (inspect the
Google Search input for its DOM event handlers).

**Comment by RobinHerbots** [comment]
@gavmck , @sompylasar , 

I tested a bit for Opera mobile on android.  keydown, keypress, keyup get fired, but I cannot prevent the input by preventdefault or return false; also the caretpositioning is not working at all.  

Robin

**Comment by gavmck** [comment]
Been doing more Windows Mobile testing today.

JS can't seem to get past the .setValue() call in the keypressEvent function. I had to manually call keypressEvent(e) from the keyDownEvent function as keypress doesn't fire on that device. It seems that it's not possible to update the value of the input whilst typing in it.

**Comment by RobinHerbots** [comment]
@gavmck, 

This evening I will download the wp8 sdk and give it a try.    Propably there is another js error which prevents the creation of the _setValue fn, ... an so fails further in the event.

**Comment by RobinHerbots** [comment]
@gavmck ,

I will continure for the blackberry as the win8 phone sdk required windows 8.

http://developer.blackberry.com/devzone/develop/simulator/sim_index.html for the simulator

**Comment by RobinHerbots** [comment]
@gavmck ,

I just tested the latest version with the Blackbarry 10 Simulator and it all worked fine.  I tried with the "soft"-keyboard and with the hardware keyboard.
