### ISSUE TITLE
regex - wrong placeholder / mask

### ISSUE THREAD

**Issue by razvanioan** [RobinHerbots/Inputmask#2130]
**Describe the bug**
If I use custom regex mask, the placeholder is wrong

**regex used**

```javascript
[1-8][0-9]{2}(0[1-9]|1[012])(0[1-9]|[12][0-9]|3[01])(0[1-9]|[1-3][0-9]|4[0-6]|5[12])[0-9]{4}
```
Placeholder shows a 0 an 6th position
```
_____0______
```

The regex is correct, and there's no way that the 6th digit to be only 0

I've disabled the mask on hover and focus, but when starting to type, it keeps appearing, maybe a complete disable of the placeholder would be nice

I've used empty string as placeholder, which does what is supposed to, but that single zero keeps appearing

**To Reproduce**
1. Go to [JS Fiddle](https://jsfiddle.net/razvanioan/xrqyuL2z/3/)
2. Hover / Click / Type on the only input field
3. See the 0 on the 6th position

**Expected behavior**
No zero 

**Live example**
Add a link to a codepen, jsfiddle or other example page which shows the problem

**Desktop (please complete the following information):**
 - OS: MaxOSX 10.14
 - Browser safari, firefox,  chrome
 - Version 5 beta 172

**Comment by RobinHerbots** [comment]
@razvanioan , 

You can add the jitMasking: true option to disable the placeholder.

For the 0 in the placeholder.  When you take always the first of the variations in the regex the 6th place should be a 0.  The placeholder will change while you type and other variations are set.

**Comment by razvanioan** [comment]
Ok, it might be right, but the users do not know this and they will be confused when first focus on the input ...

I'll try disabling it with jitMasking though

Thanks
