### ISSUE TITLE
How To remove cursor "_" ?

### ISSUE THREAD

**Issue by zakymujayin** [RobinHerbots/Inputmask#2131]
How To remove cursor "_" ? because that cursor count as a character in database. 
i use validation min and max input. 
thanks.

1. https://i.postimg.cc/bvXjxMXw/evidence.png

2. https://i.postimg.cc/Xvw6Q83c/evidence-2.png

**Comment by RobinHerbots** [comment]
@zakymujayin , 

Try the autoUnmask option

**Comment by zakymujayin** [comment]
@RobinHerbots problem solved, thanks !
