### ISSUE TITLE
numeric - invalid regexp group only on firefox

### ISSUE THREAD

**Issue by razvanioan** [RobinHerbots/Inputmask#2132]
**Describe the bug**
Only on Firefox, the numeric alias (latest beta version 191):

* is producing a lot of errors on change: `invalid regexp group`
* deleting (one digit or entire selected value) doesn't reflect to the mask but the value is actually changed (blur & focus on the field updates it correctly)

On Safari or Chrome it seems to be working fine

PS: how to retrieve the actual value (unmasked) if suffix / prefix configured ?

**To Reproduce**
1. Go to [this CodePen](https://codepen.io/qdev/pen/rEVBOW?editors=1111)
2. Open firefox console (the errors do not show up on CodePen app console
3. Update input field value
4. See error in console
5. Try to delete (partial or entire selection). The value (mask) doesn't change (but the value actually does)

**Comment by RobinHerbots** [comment]
@razvanioan, 

Ok, named groups are not supported in firefox.

**Comment by RobinHerbots** [comment]
@razvanioan , 

I already made the fix in the numeric extensions.  But I didn't push a new bundle in the dist folder, as I was still working on another fix.  The next push will include the fix into the bundled files.
