### ISSUE TITLE
NumericInput = true causes random and incorrect behaviour

### ISSUE THREAD

**Issue by i3anaan** [RobinHerbots/Inputmask#2133]
**Describe the bug**
Using the options below, and other options we have tried, the mask never worked as we expected. In the end when suddenly a '(' appeared in the number input while this was not at all present in the mask we concluded that its not just a usererror on our side, but some serious issues on the package.

**To Reproduce**
```
const options = {
        placeholder: '',
        numericInput: true,
        greedy: false,
        mask: '[999.]{*}9{0,3}|[999.]{*}9{0,2}-',
      };
      Inputmask(options).mask(this.elementRef.nativeElement);
```

**Expected behavior**
Some number like input mask. Instead we were able to produce '1(2.1' as 'number'

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Chrome
 - Versie 74.0.3729.169 (Officiële build) (64-bits)

**Additional context**
Lost some serious sanity here.

**Comment by RobinHerbots** [comment]
@i3anaan , 

I like your additional context ;-)
I changed the mostly default template for reporting issues to a new especially for you!

Changing the mask to: '([999.]{*}9{0,3})|([999.]{*}9{0,2}-)', will fix the ( in the mask.  I'm not sure why you have put the - at the end.

For the "(" I opened a new issue to see what goes wrong.( #2134  )

**Comment by i3anaan** [comment]
Hey @RobinHerbots Thanks for the response, I'm honoured you changed the default template for me. I will try your suggestions and see if that helps.

btw, The `-` at the end is because we want to support entering negative numbers using `-`

**Comment by RobinHerbots** [comment]
@i3anaan , 

Why don't you use the numeric alias?

**Comment by i3anaan** [comment]
Using aliases is amazing, this just completely changed my opinion of this package. Can't believe how I missed that after scanning the features / documentation, thank you for pointing me to this!

Since you moved the `(` appearing to a seperate issue I will mark this as closed, thank you for the support and keep up the good work :)
