### ISSUE TITLE
Firefox + select2 + v5 Beta = broken select2

### ISSUE THREAD

**Issue by toxpal** [RobinHerbots/Inputmask#2136]
First of all, I want to say "thanks" for such a great plugin. I'm here not to complain, but unfortunately every build of v5 Beta breaks at least one new thing that worked well in previous builds. I realize it's Beta, but I also believe each Beta release should fix more bugs than it introduces, not vice-versa.

So, after I updated to Build 190 and tested it, my final thoughts were "**Finally. A build that doesn't break existing features**". Boy I was wrong... :) I use Vivaldi for browsing, and today I used Firefox when I noticed that select2 is completely broken in Firefox. After 30+ minutes of debugging I realized that inputmask is responsible for this. As soon as I revert back to Build 141 (the last one which worked for most of my needs) or even v4, select2 starts working again. In short, select2 search function doesn't work and multiple selects (with pre-selected values) don't work. 

Am I the only who has this issue? Found other reports about FF and v5 (https://github.com/RobinHerbots/Inputmask/issues/2132), but no similar report yet.

**Comment by RobinHerbots** [comment]
@toxpal , 

You are allowed to complain ;-)  select2 is an extension on html select?  Can you create a jsfiddle with an example.  Don't you have an error in the console?  It can be related to #2132.  The issue is fixed but not yet present in the dist folder.

**Comment by toxpal** [comment]
So I created fiddle... And it worked perfectly. Somehow, my script was totally broken... Took me another 20 minutes to find out what exactly causes this problem. Apparently, problem occurs when input feld contains any value. So here we go:

https://jsfiddle.net/8s95z1tv/ - does NOT work

Now, remove 99 from value and reload - select2 will start working instantly

**Comment by RobinHerbots** [comment]
I just published a new rebuild. I tried with firefox on linux.  

And it works without issues.

**Comment by toxpal** [comment]
Thank you, will try. Hopefully currency mask will be fixed in v5 some day too, and it will be as great as v4 was (is).

**Comment by RobinHerbots** [comment]
Almost there

**Comment by toxpal** [comment]
I also just noticed another FF bug. Thankfully, it's not minor one - https://github.com/RobinHerbots/Inputmask/issues/2138

**Comment by toxpal** [comment]
Sorry for disturbing you again, but the latest beta (305) breaks select2 again. Happens in all browsers for me. I ran beta 301 previously, this one worked great.

**Comment by RobinHerbots** [comment]
@toxpal, 

This is issue is related to #2214
