### ISSUE TITLE
How to display select all text on focus

### ISSUE THREAD

**Issue by patel33hardik** [RobinHerbots/Inputmask#2137]
Hi RobinHerbots

I am not able to get select all text when change focus using TAB in datetime mask. The cursor always set at the end when I press TAB. You can also check this problem in your demo page. I used HH:MM
i.e. this image shows that it was possible in version 3 but not in new.
![image](https://user-images.githubusercontent.com/44590578/59655895-3dad1a80-91df-11e9-9842-88490ea1a37a.png)

Thanks

**Comment by toxpal** [comment]
I confirm the same issue on my projects too.

**Comment by RobinHerbots** [comment]
@patel33hardik , 

Use the positionCaretOnTab option  (set to false)

**Comment by RobinHerbots** [comment]
Also see #2139

**Comment by patel33hardik** [comment]
Thanks for quick reply Robin,
I used the following code
        $(".time-field").inputmask('datetime', {
            inputFormat: 'HH:MM',
            placeholder: 'hh:mm',
            positionCaretOnTab: false
        });

The problem is still as it is. When I press TAB, cursor pointer is displayed at the end of content instead of default feature (select all content of the text box). So, At the moment, I have to stick with version 3.xx.

Notice weird thing, working in firefox but not in chrome.
https://jsfiddle.net/kLroz73n/

Thanks

**Comment by RobinHerbots** [comment]
@patel33hardik , 

I pushed a fix in version 5.x.

https://jsfiddle.net/n0g6artf/

**Comment by patel33hardik** [comment]
@RobinHerbots  
Thank you so much for your quick support.
It works perfectly.  👍 

One issue with this update is 
**I can not put the cursor at where I want.**
example: 10:20
i.e. if I want to put the cursor at the beginning (before 1 or before 2) using a mouse, It will not be allowed me.

**Comment by patel33hardik** [comment]
Hi, @RobinHerbots 

One issue with this update is
I can not put the cursor at where I want.
example: 10:20
i.e. if I want to put the cursor at the beginning (before 1 or before 2) using a mouse, It will not allow me.

It would be more consistent if it looks similar like input type=time but without AM and PM

**Comment by RobinHerbots** [comment]
Hi @patel33hardik, 

On the first click it will position the caret (cursor) at the first position which is not entered in the mask.  A second click will position the caret at the click position.
But you can change the behavior through the positionCaretOnClick option.  

For the type=time look.  You mean like  --:-- ?  You can set the pattern as placeholder.

**Comment by patel33hardik** [comment]
Hi @RobinHerbots 
Above works perfect, but when content selected, I could not click position. Double click works but It has to works with a single click.
i.e. when all content selected and I want to click(single click) any of the indexes, it's not allowed to me. Is that an option for that??
![image](https://user-images.githubusercontent.com/44590578/59883077-40825800-93f7-11e9-8621-2eb01a3c5022.png)
look at here https://jsfiddle.net/ohw2zqvc/

**Comment by toxpal** [comment]
I confirm the same. New build fixed the main issue, but another issue still exists - it's impossible to place mouse cursor BEFORE first symbol. For example, let's say value in the field is 15:30

It's impossible to place mouse cursor before 1 and before 3. Click itself works, but then typing indicator instantly jumps to 5 (or 0). Hope I explained it clearly enough.

**Comment by RobinHerbots** [comment]
@patel33hardik, 

I confirm the behavior. When all is selected, the click does nothing.  I will fix that.

@toxpal , 

I tried what you have explained, but it worked without issues.  So it is not clear to me what do you mean?

**Comment by toxpal** [comment]
Oh, I noticed it's needed to manually add positionCaretOnTab and then it works. My code didn't use this option, so typing indicator was jumping to 2nd symbol every time.

**Comment by RobinHerbots** [comment]
@patel33hardik ,  @toxpal , 

Have a look at: https://jsfiddle.net/pm6c0n2x/

Try the same in the field where there is no masking.  What is happening here?

**Comment by toxpal** [comment]
Just tested. So it looks that everything is good when positionCaretOnTab and positionCaretOnClick options are manually added to inputmask field (so masked fields act like non-masked field and don't re-position cursor).

Was such behavior (automatic jumping to 2nd character) done with some purpose?

**Comment by RobinHerbots** [comment]
@patel33hardik , @toxpal , 

It seems to be an issue with jsfiddle.
Here the same as the previous jsfiddle but in a code pen https://codepen.io/robinherbots/pen/qzrovd

@toxpal , 

Have a read in the readme.  The jump is to the first non-entry, so you can continue the mask.  A click in the input while the input is already in focus will set the caret at the position you clicked.  Different behaviors are configurable. See positionCaretOnClick in the docs.

**Comment by toxpal** [comment]
> The jump is to the first non-entry, so you can continue the mask.

Absolutely makes sense and is a good idea.

> A click in the input while the input is already in focus will set the caret at the position you clicked

In default setup (without using positionCaretOnTab, positionCaretOnClick) it doesn't happen. Typing indicator jumps by 1 position forward. Hence, it's literally impossible to use mouse and set typing indicator at the very beginning of input field (if field is already completely filled). Of course, there are always other options to do so:

1. Use additional options positionCaretOnTab, positionCaretOnClick you suggested.
2. Use mouse to set position at the very beginning of field, and right after typing indicator jumps 1 position forward, use left arrow key in keyboard to move indicator back.

...or maybe we just don't understand each other :)

**Comment by patel33hardik** [comment]
> @patel33hardik , @toxpal ,
> 
> It seems to be an issue with jsfiddle.
> Here the same as the previous jsfiddle but in a code pen https://codepen.io/robinherbots/pen/qzrovd
> 

Hi @RobinHerbots 
Thanks for resolves the issue. It might be the jsfiddle problem in this context.
But I might say, the new version is not entirely the same as version 3.x for DateTime.

**Issue 1-** When I click on any positions on content, that position would be selected (look at the image) in version 3.xx which is the best. This feature is not available in a new version I guess.
![image](https://user-images.githubusercontent.com/44590578/59984652-8a757300-966f-11e9-93c7-32fcfb525c1a.png)
**Issue 2-** When I select contents using TAB, It will not let me enter anything unless I do not enter between 0 to 2 in a new version while in old, It can be possible. 
For example, When I enter value more than two, it will convert in minutes in version 3.x
if I enter 8888 it will turn in 08:08 this could not be possible into the latest version.

I hope you understand what I meant to be

**Comment by RobinHerbots** [comment]
@patel33hardik , 

You need to create a new issue for this.  I'm still working on the new datetime implementation.  So that is an issue that needs fixing.
