### ISSUE TITLE
FireFox - mask doesn't disappear

### ISSUE THREAD

**Issue by toxpal** [RobinHerbots/Inputmask#2138]
Discovered another FF related issue. After mouse cursor is moved over empty input field and then moved away, inputmask stays visible forever.

Example - https://jsfiddle.net/9u7y0hv8/

**Comment by RobinHerbots** [comment]
It seems firefox needs some extra love.

**Comment by toxpal** [comment]
I noticed FF is really strict about Jquery/JSON stuff. For example, if you try to pass date like 10000-01-01 in JSON (which happened to me by mistake), all browser will work except FF. It break all related Jquery functions and page will not work

**Comment by RobinHerbots** [comment]
@toxpal , 

I pushed a fix in v5.x

**Comment by toxpal** [comment]
Yes, I'm watching your releases, so I upgraded after 2 minutes. Will test it.
