### ISSUE TITLE
Datetime paste month problem

### ISSUE THREAD

**Issue by MKMatriX** [RobinHerbots/Inputmask#2140]
when pasting or even $(node).inputmask("setvalue", value) deletion causes problems with date

**Live example**
http://jsfiddle.net/y17rg9u3/

**Please complete the following information:**
 - OS: windows 10
 - Browser: chrome 75
 - Inputmask version: 4.0.8

**Additional context**
seems to work good on 3xx versions

**Comment by RobinHerbots** [comment]
@MKMatriX , 

Try with the latest beta.

http://jsfiddle.net/gdk4oqa3/1/

**Comment by MKMatriX** [comment]
@RobinHerbots Thanks, still a little weird if you continue to delete, but now no undeletable "1"

**Comment by RobinHerbots** [comment]
@MKMatriX , 

What exactly do you mean with the delete behavior?  Suggestions are welcome.

**Comment by MKMatriX** [comment]
@RobinHerbots I mean that some numbers from years jump to days so "20.06.2019" will look as "02.0М.019Г" if you start to backspace from dot after six, while I expected it look like "ДД.ММ.2019"

**Comment by RobinHerbots** [comment]
@MKMatriX , 

Isn't that the case with the latest beta version?  I just tried and it bahaves like you would expect.  Which browser are you using?

**Comment by MKMatriX** [comment]
@RobinHerbots My bad, I pressed "insert" when saw cursor, If pressed works as I sad, if not works as expected. ^_^
