### ISSUE TITLE
start text from right

### ISSUE THREAD

**Issue by therepairshack** [RobinHerbots/Inputmask#2141]
**Describe the bug**
Say it.  Spit it out.  What is it exactly?

**Live example**
Add a link to a codepen, jsfiddle or other example page which shows the problem

**Please complete the following information:**
 - OS:
 - Browser
 - Inputmask version 

**Additional context**
How do you feel?  Do you want to talk about?  Why do you care?  ;-)

**Comment by RobinHerbots** [comment]
@therepairshack , 

Add the dir="rtl" option in your html.

https://jsfiddle.net/9q4rxyo7/
