### ISSUE TITLE
Using Group with Currency and insertMode: false don't allow to overwrite

### ISSUE THREAD

**Issue by Ayushij565** [RobinHerbots/Inputmask#2144]
**Describe the bug**
When i was trying to use currency alias with insermode:false and group:true then when i click on the field and try to enter number on it.It don't allow me to do so.

**Live example**
windowId.find('.currency6I2D').inputmask({'alias': 'currency','autoGroup': true,'integerDigits': 6, 'digits': 2, 'decimalProtect': false, 'digitsOptional': false,  'placeholder': '0', 'prefix': '', 'allowMinus': false, "positionCaretOnClick" : 'select',"insertMode": false});

**Please complete the following information:**
 - OS:Windows 10
 - Browser: Chrome
 - Inputmask version 

To Replocate this issue you can check on your demo page given for currency and set some maximum limit to text field.
For example if i set max limit to 10 and in field i added 123,456.78
Now tab and go to next field.
Now from mouse single click on field(Don't select complete text)
Now try to add some number it doesn't behave correctly.

**Additional context**
How do you feel?  Do you want to talk about?  Why do you care?  ;-)

**Comment by RobinHerbots** [comment]
@Ayushij565 , 

Can you retry with the latest 4.x version instead of 4.0.1 beta.29

**Comment by RobinHerbots** [comment]
@Ayushij565 , 

Just reread you're issue.  

> For example if i set max limit to 10
Do you mean you set a maxlength in the input?  

If so the behavior is correct as 
123.456.78
Typing a new char would result in 11 chars which is not allowed by the maxlength
1.234.56n.78

**Comment by knoxcard** [comment]
@RobinHerbots - you are kicking butt! Are you receiving/accepting pull requests? Seems like you handle it all on your own.

**Comment by RobinHerbots** [comment]
@knoxcard, 

I do accept pull requests, but I don't recieve many ;-)
Yes, this is a one man show.
