### ISSUE TITLE
Inputmask sends placeholder symbols as actual values

### ISSUE THREAD

**Issue by toxpal** [RobinHerbots/Inputmask#2145]
I noticed that Inputmask sends masks as actual values, which causes very odd behavior in scripts when user didn't complete field in full.

For example, if user simply enters "somebody" into email field, actual value of the field becomes "`somebody@__.__`" and such value is then submitted to the server. While it's not terrible, the problem with numeric values is.

For example, if I use `mask':'9{1,4}[.99]` and user enters 7.5 into the field, I expect value sent to the server be 7.5 or 7.50 (doesn't really matter). Instead, actual value submitted to server becomes `7.5_` which causes many problems.

Since Jsfiddle doesn't allow PHP code, I created a simple code to capture field values using JS, take a look - https://jsfiddle.net/cp023a9q/

**Comment by toxpal** [comment]
In short, it's the same issue as https://github.com/RobinHerbots/Inputmask/issues/2138 but now it exists in all browsers, not only in FF

**Comment by RobinHerbots** [comment]
@toxpal , 

Try the autoUnmask and removeMaskOnSubmit option.  See readme.

**Comment by toxpal** [comment]
Thanks, will look at these options. I submitted the issue because it worked as I expected (without using extra options) in some previous beta builds of v5, so I assumed it should always work this way. Maybe some previous builds had bug/regression that didn't apply masks permanently (so empty values were auto-unmasked) and I assumed it should be by default.

Probably the best idea is to re-read Readme after every new beta build for a while since there are many changes in builds now...

**Comment by toxpal** [comment]
So I tried both options (one by one, and also both at the same time) and it's even worse.

Previously, after typing 7.5, it sent value as 7.5_, causing my internal validations to fail (because of invalid number, obviously). So user at least saw an error that some value is invalid. Not great, not terrible...

Now, if I type 7.5, it sends value as 75. That is to say, if some user doesn't add 0 at the end (which happens often), field bypasses all validations in script (because 75 is obviously a valid number), but submitted value (75) is completely different from expected value (7.5).

Or do I really miss something?

**Comment by RobinHerbots** [comment]
@toxpal , 

Oh, ofcourse, ... the dot inside your mask is a static element in the mask so unmasking removes it.

Or you use the numeric alias or you can implement a custom unmasking which doesn't delete the dot.
You can use onUnMask callback for that.

**Comment by toxpal** [comment]
Thanks. I would like to use currency alias for this, but I switched to custom mask because currency had many problems in previous builds (especially when field contained . and/or 0), will try with recent builds to see how it works.
