### ISSUE TITLE
Bug after typing dot

### ISSUE THREAD

**Issue by bshafiei-ir** [RobinHerbots/Inputmask#2146]
When I type decimal numbers with dot, when I want edit again number format will missed.

![image](https://user-images.githubusercontent.com/19801131/59973424-0c549600-95b5-11e9-8fc6-498592883794.png)

@RobinHerbots

**Comment by RobinHerbots** [comment]
@bahmansh , 

Working on it.

**Comment by RobinHerbots** [comment]
@bahmansh, 

The issue is partially fixed.
Number corruption should be fixed.
Except when you enter 123456 and place a dot between 3 and 4 or somewhere else between.

Also working on that ;-)

**Comment by RobinHerbots** [comment]
#2152
