### ISSUE TITLE
Issue in new version for date-time

### ISSUE THREAD

**Issue by patel33hardik** [RobinHerbots/Inputmask#2147]
Hi @RobinHerbots 
I might say, the new version is not entirely the same as version 3.x for DateTime.

**Issue 1-** When I click on any positions on content, that position would be selected (look at the image) in version 3.xx which is the best. This feature is not available in a new version I guess.
![image](https://user-images.githubusercontent.com/44590578/59984652-8a757300-966f-11e9-93c7-32fcfb525c1a.png)
**Issue 2-** When I select contents using TAB, It will not let me enter anything unless I do not enter between 0 to 2 in a new version while in old, It can be possible. 
For example, When I enter a value between 3 to 9, it will convert in hours and minutes with appending 0 in version 3.x.
If I enter 8888 it will turn in 08:08 this could not be possible into the latest version.

I hope you understand what I meant to be

**Comment by RobinHerbots** [comment]
@patel33hardik, 

Yes this needs to be fixed in the new version.  

A link to the previous codepen for testing.
https://codepen.io/robinherbots/pen/qzrovd

**Comment by RobinHerbots** [comment]
@patel33hardik, 

Have a look at the codepen.  Both above mentioned issues should be solved.
