### ISSUE TITLE
Question: what is the inputmask.binding.js ? and inputmask.dependencyLib.js ?

### ISSUE THREAD

**Issue by redochka** [RobinHerbots/Inputmask#2148]
Hello,

What is the purpose of inputmask.binding.js ? and inputmask.dependencyLib.js ?

Thanks

**Comment by RobinHerbots** [comment]
@redochka , 

Initially the inputmask was a jquery plugin.  This means it was dependent on functionality provided by jquery.  Now you can also use the inputmask on vanilla javascript and with jqlite.  The dependencylib, provides the functions needed for the inputmask to work.  

The inputmask.binding is to automatically enable the inputmask when using data-attributes.  It uses jquery.  In my opinion, the dev should decide when the Inputmask is loaded/activated, but some people prefer that it initializes automatic.  So the binding calls it on document ready and on ajaxcomplete for you.
