### ISSUE TITLE
Suggestion: update documentation

### ISSUE THREAD

**Issue by toxpal** [RobinHerbots/Inputmask#2149]
I would suggest to update v5 readme because some default options are inaccurate, which may confuse some (especially new) users. For example:

```
groupSeparator (numerics)
Default: ""
```
Not true. Default separator is **,** (at least in currency).

```
prefix
Default: ""
```
Not true. Default is **$** (at least in currency).

If I (or someone else) finds other incorrect or out-of-date information, I will update this post.

**Comment by RobinHerbots** [comment]
@toxpal , 

Yes, this is true.  Depending the alias used the option default will vary.

It would be nice to extend/enhance the readme.  Send in a pul request with the changes.  I will coment if I don't agree and otherwise will merge them in.

**Comment by toxpal** [comment]
Alright, will try to update it.
