### ISSUE TITLE
Force numeric to empty (on blur) with '0' as value

### ISSUE THREAD

**Issue by gvdhoven** [RobinHerbots/Inputmask#215]
Hi Robin,

I wanted to use the decimal for an address (housenumber) but obviously the default (database) value is '0'. I don't want this '0' to be in the field. What method/regex would i have to use to empty '0' from the input?

Case:
- New user
- App assigns '0' to field
- App uses $(field).inputmask('99')
- Inputmask detects this '0' and clears it on pageload
- User enters '0' or '00' or '0000' etc. and blurs field
- Inputmask validator would empty this field.

Regards,
Gilles

**Comment by WaltDaniels** [comment]
I actually have a similar need ... let us set a default of either blank or '0' for numeric masks.

**Comment by RomeroMsk** [comment]
Option to set the value to 0 when bluring empty (value='') input will be useful too.

**Comment by RobinHerbots** [comment]
@Webunity , 

This will be custom behavior in the numeric alias. I will push the changes soon.

@WaltDaniels, 
The numeric alias allows for setting the placeholder to 0 which will result in a default of 0 for the mask.

**Comment by dvpandianwipro** [comment]
This issue is happening again in latest release(Version: 3.3.6-10). Integer is setting value as 0 on blur or clearing entered text. I could not set empty value.
https://jsfiddle.net/jk45qbtw/8/

**Comment by jtpetro** [comment]
A possible work around is to extend the integer alias to include `radixPoint:'.'`. 
https://jsfiddle.net/jtpetro/jk45qbtw/9/

**Comment by RobinHerbots** [comment]
@dvpandianwipro ,  @jtpetro , 

Fixed
