### ISSUE TITLE
Numerics do not work with the input event.

### ISSUE THREAD

**Issue by toxpal** [RobinHerbots/Inputmask#2151]
As always, each build of v5 breaks more things than it fixes :)

Today I noticed that autofilling doesn't work properly with numerics (worked fine weeks ago). Let's say you have a field:

`<input type="text" name="testfield" class"inputmask" data-inputmask="'alias':'integer'">`

Let's say you fill form multiple times and you enter these values into the field:
_1, 15, 45, 60, 188, 259_ (just an example)

So when you click on the same field next time, browser obviously lists these values as available for autofilling. Here's the problem: after you select any value from the list, only the last number is added to the field. So if I select autofill value **15**, input field value becomes **5**. If I select autofill value **259**, input field value becomes **9**. And so on...

Hope I explained it clearly enough.

**Comment by toxpal** [comment]
P.S. It happens with numerics only. Other masks (email, custom masks, etc.) work fine with autofilling.

**Comment by RobinHerbots** [comment]
This is related to issue #2143

**Comment by toxpal** [comment]
Just a quick update that this issue still exists in latest v5 build. Not a very big deal, but hopefully it will be fixed some day :)

**Comment by RobinHerbots** [comment]
@toxpal , 

Have a try with 5.0.0-beta.296

**Comment by toxpal** [comment]
A bit better. As long as number doesn't contain 2 digits and doesn't end with 0, it works :) In other words, numbers like 10, 20, 30, 40, 50, 60, 70, 80, 90 still have the same issue. But numbers like 110, 120, etc - don't have this issue anymore.

**Comment by RobinHerbots** [comment]
@toxpal , 

Ok, again with version 301

**Comment by toxpal** [comment]
Good news: it works.

Even more good news: I'm going out for 2 weeks, so you won't be receiving a truckload of new issues from me. Enjoy this peaceful time :)
