### ISSUE TITLE
Masking data on Edit

### ISSUE THREAD

**Issue by renanlucas07** [RobinHerbots/Inputmask#2153]
I'm using Inputmask on a rails app with delocalize for currency fields, what delocalize does is remove the thousands separator, and change the decimals separator to a dot. This is working fine.
But when editing a delocalized fieldthe value comes correctly from database, e.g:
i enter a value of 13.000,00 wich is thirteen thousand, it saves it correctly on database (13000.0)
but on edit the value appears as 1.300,00
my field is like this:
`<%= f.input :amount, as: :string, input_html: { class: "currency amount",`
          `data: { inputmask: "'alias': 'numeric', 'groupSeparator': ',', 'autoGroup': true, 'digits': 2,` `'digitsOptional': false" }
        } %>`

on database the amount field is a decimal.
i'm not sure if this is a issue with inputmask, but how am i supposed to mask this number correctly?
thanks in advance

**Comment by RobinHerbots** [comment]
@renanlucas07 , 

Which version of inputmask is used?

**Comment by renanlucas07** [comment]
I'm using a gem, jquery-inputmask-rails, turns out the gem uses version 2.5.5.
i was able to bypass the problem overriding the amount getter in my model, 

`def amount`
  `'%.2f' % read_attribute(:amount) rescue nil`
`end`

returning the number with 2 decimal places solves the issue, but i'll always have to convert the amount to decimal if i want to use it in math expressions.
i'm going to try installing the lib with npm, so i'm on the newst version
