### ISSUE TITLE
Added non-passive event listener to a scroll-blocking 'touchstart' event

### ISSUE THREAD

**Issue by knoxcard** [RobinHerbots/Inputmask#2154]
**jquery.inputmask.min.js:8** [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event.

Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

**Comment by RobinHerbots** [comment]
Duplicate #2135
