### ISSUE TITLE
Move + & - from numeric regex to options

### ISSUE THREAD

**Issue by gvdhoven** [RobinHerbots/Inputmask#216]
I have a currency field (price) and in that field i don't want the user to enter +0.00 or -0.00.
So with the default decimal implementation, i have to create a new definition omitting this from the regex. What if we would move the + and - to options and build the regex based on these options? Then you could have something like;
$(field).inputmask('decimal', { allowNegative: true, allowNegative: false });

**Comment by RobinHerbots** [comment]
@Webunity 

Great idea!  I will do that.

Robin

**Comment by gvdhoven** [comment]
Thanks you as always for your fast response.

**Comment by RobinHerbots** [comment]
@Webunity, 

See the latest numerics
