### ISSUE TITLE
Clear currency prefix on empty input

### ISSUE THREAD

**Issue by GershonR** [RobinHerbots/Inputmask#2160]
**Describe the bug**
When you enter a currency, it formats it and unmasks fine. But when there is no input the $ prefix persists, causing visual bugs with the angular material inputs.

![image](https://user-images.githubusercontent.com/9329121/61239801-58eb4700-a705-11e9-912f-dbc21a878890.png)

**Live example**
https://stackblitz.com/edit/angular-6-material-inputs-1bhuky

**Please complete the following information:**
 - OS: Win10
 - Browser: Google Chrome
 - Inputmask version: 4.0.8

**Solution**
There should be an option to clear the prefix when there is no input.

**Comment by RobinHerbots** [comment]
@GershonR , 

Can you have a try with the latest beta 5.x

**Comment by GershonR** [comment]
> @GershonR ,
> 
> Can you have a try with the latest beta 5.x

Latest beta seems to have fixed it, thank you!
To demo, I changed:
 `"inputmask": "^4.0.8"` to `"inputmask": "^5.0.0-beta.213"` in `package.json`

and no other changes were required!
