### ISSUE TITLE
Permission to use your library

### ISSUE THREAD

**Issue by bozsikarmand** [RobinHerbots/Inputmask#2161]
Hello,

I would like to use your inputmask library in one of my project.
Both private and commercial use is permitted by the MIT license, but to comply with its conditions to the fullest extent, I need to distribute the text of your license file in mine, and also a notice about your copyrights in the readme of my project if I understand it right.

Do you require anything else? :) 

Thanks,
Armand

**Comment by RobinHerbots** [comment]
Hi @bozsikarmand , 

That should be sufficient.

Best regards, 
Robin

**Comment by bozsikarmand** [comment]
I hope [this solution](https://github.com/bozsikarmand/armands.site/blob/master/README.md) is satisfactory for you. :)
