### ISSUE TITLE
In unfilled masks, static characters are duplicated

### ISSUE THREAD

**Issue by wnex** [RobinHerbots/Inputmask#2162]
**Describe the bug**
In unfilled masks, static characters are duplicated.
In the example, the number 7 is duplicated.

Mask: "+7 (999) 999-99-99",
Value: "+7 (123) 123-12-3_",
View:  "+7 (712) 312-31-23".

**Live example**
https://jsfiddle.net/0ujgqf7b/

**Please complete the following information:**
 - OS: Ubuntu 16
 - Browser Google Chrome Version 70.0.3538.110 (Official build), (64 bit)
 - Inputmask version 5.0.0-beta.158

**Comment by RobinHerbots** [comment]
@Nexonion,

Fixed in the current beta
https://jsfiddle.net/mnoq1k3y/
