### ISSUE TITLE
SSR with react redux

### ISSUE THREAD

**Issue by Lemaro86** [RobinHerbots/Inputmask#2164]
If I use inputmask last version 4.0.8 or betta version build crushed.

`var document = window.document, ua = navigator.userAgent, ie = ua.indexOf("MSIE ") > 0 || ua.indexOf("Trident/") > 0, mobile = isInputEventSupported("touchstart"), iemobile = /iemobile/i.test(ua), iphone = /iphone/i.test(ua) && !iemobile;
                                         ^

ReferenceError: navigator is not defined`

This spike
`global.navigator = {
    userAgent: 'node.js'
};`

or this spike:
`global.navigator = {}`

not working 

I think, need add check navigator, like here https://github.com/sanniassin/react-input-mask/pull/33

**Comment by RobinHerbots** [comment]
@Lemaro86, 

Can you also try when you install jsdom as node module? (besides the change in your PR)

Thx, 
Robin

**Comment by sibelius** [comment]
how did you solved it?

**Comment by Lemaro86** [comment]
Just copy in my own project and solved locally.
