### ISSUE TITLE
NumericInput: Pasting integers without selecting results in extra 0s

### ISSUE THREAD

**Issue by ferk6a** [RobinHerbots/Inputmask#2165]
**Describe the bug**
1. Go to the live example
2. Copy this into your clipboard: "540"
3. Focus the input, your caret should be at the end
4. Paste
5. You will end up with "$ 5,400.00", but I expected "$ 5.40".

Selecting however, works:
1. Copy this into your clipboard: "540"
2. Select the entire contents of the input
3. Paste
4. You will end up with "$ 5.40".

**Live example**
https://jsfiddle.net/nvux3ad5/

**Please complete the following information:**
 - OS: Linux
 - Browser: Firefox Developer 69
 - Inputmask Version: 5.0.0-beta.217

**Additional context**
This project is amazing, best I've seen so far. This is just one issue I found when heavy testing and comparing to my crude custom masking code that I had before.

**Comment by RobinHerbots** [comment]
See #2203

**Comment by RobinHerbots** [comment]
@fer22f,

The issue is fixed in 5.0.0-beta.290

https://jsfiddle.net/at8gh3qj/1/
