### ISSUE TITLE
NumericInput: Selecting the field and typing makes characters appear before radix

### ISSUE THREAD

**Issue by ferk6a** [RobinHerbots/Inputmask#2166]
**Describe the bug**
1. Go to the live example
2. Select the entire contents of the input
3. Type "3"
5. You will end up with "$ 3.00", but I expected "$ 0.03".

If you remove all the contents before, however, it works:
1. Go to the live example
2. Select the entire contents of the input
3. Delete it (backspace or delete)
4. Type "3"
5. You will end up with "$ 0.03".

**Live example**
https://jsfiddle.net/dte4k309/

**Please complete the following information:**
 - OS: Linux
 - Browser: Firefox Developer 69
 - Inputmask Version: 5.0.0-beta.217

**Additional context**
This project is amazing, best I've seen so far. This is just another issue I found when heavy testing and comparing to my crude custom masking code that I had before.

**Comment by RobinHerbots** [comment]
@fer22f,

By default when selecting all and start typing the input is considered integer.  But with the numericInput set to true I can agree that this shouldn"t be.

I will push a fix for this

**Comment by ferk6a** [comment]
Yep, I do see why, I ran into some issues when integrating with Vue [which stringifies when assigning to value](https://github.com/vuejs/vue/blob/f11449d916a468651d4fd5024c37e3eebbc9941f/src/platforms/web/runtime/modules/dom-props.js#L43-L50). Resolved by doing something like `:value="(value && +value) ? (+value).toFixed(2) : ''"`.

In this case, I think it does make sense though, because it's typing, just a different selection argument.

**Comment by RobinHerbots** [comment]
@fer22f , 

Have a try
https://jsfiddle.net/snqvcja2/

**Comment by RobinHerbots** [comment]
@fer22f , 

Just found another issue.

The initial value in your fiddle 0.20.  Set the caret at the end and start typing, ...

I will verify that also

**Comment by RobinHerbots** [comment]
@fer22f , 

The other issue is also fixed.  Can this be closed?

**Comment by ferk6a** [comment]
Yep, I think we are done. Thanks!
