### ISSUE TITLE
Alias not working in Vue.js

### ISSUE THREAD

**Issue by Herald85** [RobinHerbots/Inputmask#2167]
I found a very nice inputmask for a decimal number:
```
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.inputmask/3.2.6/jquery.inputmask.bundle.min.js"></script>
<input type="text" class="decimal" />
```
```
$(document).ready(function(){
  $(".decimal").inputmask({ 'alias': 'decimal', 'radixPoint': '.', 'groupSeparator': ',', 'autoGroup': true, 'digits': 2, 'digitsOptional': false, 'placeholder': '0.00', rightAlign : true});
});
```
This works great in JSFiddle. However when I try to use it with Vue.js, I'm getting an error. Here is the code:
```
function(Vue, options) {
    Vue.directive('mask', {
    bind: function(el, binding) {
        InputMask({ 'alias': 'decimal', 'radixPoint': '.', 'groupSeparator': ',', 'autoGroup': true, 'digits': 2, 'digitsOptional': false, 'placeholder': '0.00', rightAlign : true}).mask(el);
        }
    });
}
```
And this comes out if I try to type anything in the input field:
```
Uncaught TypeError: Cannot create property 'rewritePosition' on boolean 'true'
    at processCommandObject (inputmask:1245)
    at isValid (inputmask:1269)
    at HTMLInputElement.keypressEvent (inputmask:1585)
    at HTMLInputElement.ev (inputmask:1530)
```
The problem is caused by the presence of 'alias' property, without it the error is not there (but it obviously also doesn't work).

I can't find why alias should not work in Vue.js

Version of plugin is 5.0.0-beta.161

**Comment by RobinHerbots** [comment]
@Herald85 , 

Try a more recent beta version.

**Comment by Herald85** [comment]
> 
> 
> @Herald85 ,
> 
> Try a more recent beta version.

@RobinHerbots 
I updated to 5.0.0-beta.221 and unfortunately it's still there.

**Comment by Herald85** [comment]
@RobinHerbots 
I was able to pinpoint the problem. My compiler options have set --alwaysStrict and that causes the failure in function `processCommandObject` on lines 1118-1119, where you have this code:

`void 0 !== commandObj.rewritePosition && (maskPos = commandObj.rewritePosition, commandObj = !0, commandObj.rewritePosition = void 0);`
 
In other words you first set `commandObj` to true and then check the `rewritePosition` on `commandObj` and with --alwaysStrict this fails.

If I change the order: 

`void 0 !== commandObj.rewritePosition && (maskPos = commandObj.rewritePosition, commandObj.rewritePosition = void 0, commandObj = !0);`,

everything works just fine.

So I think it's a little bug and I would like to ask you to change it.

**Comment by RobinHerbots** [comment]
@Herald85 , 

Thx for the info.

I made the change.  Have a try with version 5.00-beta.228

**Comment by Herald85** [comment]
@RobinHerbots 
Thank you for the correction!
