### ISSUE TITLE
Ignore groupSeparator when groupSize is 1

### ISSUE THREAD

**Issue by gvdhoven** [RobinHerbots/Inputmask#217]
When i have the following code
$(field).inputmask('decimal', { groupSize: 1 });

The user is still able to enter the comma, although this isn't a valid decimal character (by default it is '.'). Suggestion to ignore the groupSeparator when groupSize is 1.

**Comment by RobinHerbots** [comment]
@Webunity , 

set groupseparator: "", ...

**Comment by gvdhoven** [comment]
Yes thank you, since that is now default you can close this issue.
