### ISSUE TITLE
Error clicking 'delete' when 'digits' is greater than 2

### ISSUE THREAD

**Issue by davidmds** [RobinHerbots/Inputmask#2172]
By placing the cursor to the left of 'radixPoint' and clicking 'delete' the plugin is adding zeroes to the left of 'radixPoint'.

Example: https://jsfiddle.net/davidmds/ashzw5u0/4/

Inputmask version: 4.0.8

**Comment by RobinHerbots** [comment]
@davidmds ,

Good catch!

It doesn"t occur in the new 5.x beta

https://jsfiddle.net/2tjz4a05/1/
