### ISSUE TITLE
Inputmask Remove Number Masks

### ISSUE THREAD

**Issue by btnkalyoncu** [RobinHerbots/Inputmask#2175]
Hello,

Firstly, thank you for this plugin.

I have a problem with masking. let me explain how.

I am making inputs like quantity, price and total 3 inputs. think like its only 1 row and when I add another row with FormRepeater the old input number comes different.

Before ; 1122,33
After ; 3322,11

When using form repeater I call inputmask again to cath new elemets but the old inputs become wrong.

If I use remove, also remove func. do the same think.

Before; 1122,33
After; 332211

Can you help me for this situation?

**Comment by RobinHerbots** [comment]
@btnkalyoncu , 

Which version are you using?

**Comment by RobinHerbots** [comment]
@btnkalyoncu , 

Checked the issue on the latest 5.0.0 version, and it works as expected
