### ISSUE TITLE
digits with suffix does not work

### ISSUE THREAD

**Issue by jamesRUS52** [RobinHerbots/Inputmask#2177]
digits does not work with suffix

data-inputmask="'alias' :'decimal', 'allowMinus':'true', 'min': '-100', 'max':'100', 'digits' : '2', 'suffix':' %'"

alias percentage also does not work with digits : 2

Please complete the following information:

OS: Win 10
Chrome 76.0.3809.100
Version: 5.0.0-beta.232

**Comment by RobinHerbots** [comment]
@jamesRUS52 , 

Can you have a try with version 5.0.0-beta-247

best regards,
Robin

**Comment by jamesRUS52** [comment]
It looks like work version with digits, but I think some error when value more max 
for example
I have
data-inputmask="'alias' :'decimal', 'min': '0', 'max':'1000', 'digits' : '2', 'suffix':' %'"
press 9 visible value 9 OK
press 9 visible value 99 OK
press 9 visible value 999 OK
press 9 visible value 100000 ERROR should be 1000 or 1000.00 or not changed 999

**Comment by RobinHerbots** [comment]
@jamesRUS52 , 

Yes, it should be 1000.  I will fix it.

**Comment by RobinHerbots** [comment]
@jamesRUS52, 

On version 5.x 252 your mask wil work.  But there is still an issue to fix when setting the max to ex.  1000.50. 
I know where is happens but I need to implement a proper solution yet.

**Comment by RobinHerbots** [comment]
@jamesRUS52 , 

Fixed. But I need to push a rebuild. (tomorrow)
