### ISSUE TITLE
"setvalue" for empty value and "clearMaskOnLostFocus=false" duplicates mask suffix

### ISSUE THREAD

**Issue by ilplotkin** [RobinHerbots/Inputmask#2181]
"setvalue" for empty value and "clearMaskOnLostFocus=false" duplicates mask suffix at the beginnig. Please see comments in the code below.

```<script src="jquery.js"></script>
<script src="jquery.inputmask.bundle.js"></script>
<input id="d1"><br>
<input id="d2">
<script>

   var d1 = $('#d1');
   var d2 = $('#d2');
   
   var m = {
      mask: '******XYZ',
      clearMaskOnLostFocus: false,
   };
   
   d1.inputmask(m);
   d1.inputmask('setvalue', '');    // shows 'XYZ___XYZ'

   d2.inputmask(m);
   d2.inputmask('setvalue', '123'); // shows '123___XYZ'

</script>
```
Tested on both 4.0.4 and 5.x.

Thank you.

**Comment by RobinHerbots** [comment]
@ilplotkin , 

Setvalue should now work as expected.

**Comment by ilplotkin** [comment]
Yes, this test example works with your latest commit. Thank you very much.
Is 4.x line is still supported?
Are there any breaking changes in 5.x line?

**Comment by RobinHerbots** [comment]
@ilplotkin, 

I have no time to update the 4.x branch.  So the only focus is on 5.x.  (5.0 will release soon)

The numeric aliases have changed in version 5.x and some minor options are removed.  Offcourse many enhancements ;-)
