### ISSUE TITLE
Chrome with foreign language Input Method Editor (IME) triggers redundant keypressEvent for while typing is in progress

### ISSUE THREAD

**Issue by yunyunzai** [RobinHerbots/Inputmask#2182]
**Browser:** Chrome Version 76.0.3809.132 (Official Build) (64-bit)
**OS:** Windows 10
**IME in trouble:** Sogou Version 8.9.0.2180

**Demo of the bug:**
![Chrome_Foreign_IME_Issue](https://user-images.githubusercontent.com/2230873/64401583-825a8c00-d03f-11e9-92d7-daedd6ea7780.gif)
jsFiddle: https://jsfiddle.net/yunyunzai/kpsb5wmv/

**Root Cause:** 
Multiple redundant keypressEvent are triggered for typing-in-progress input made by this type of IMEs. https://github.com/RobinHerbots/Inputmask/blob/b1e96445b29958b4bbbd727a144d773fe7ca9f48/dist/jquery.inputmask.js#L1373

**Proposed Solution:**
Chrome has its own way to identify this type of typing-in-progress input. This is a none-issue for the latest version of Firefox and IE. The above line should be replaced by:
`                                    keypress.which = entry.charCodeAt(0), ignorable = !1, (!e.originalEvent || e.originalEvent.inputType !== "insertCompositionText") && EventHandlers.keypressEvent.call(input, keypress);
`

**Comment by RobinHerbots** [comment]
@yunyunzai , 

I pushed a fix and rebuild.  Can you have a try.

**Comment by RobinHerbots** [comment]
@yunyunzai , 

Have a try with 5.0.0-beta.252

I did a quick try also on android chrome with predictive text.  While composing the input event is skipped as you proposed, but on compositionend the input is triggered to set the value.
Possible the input trigger will be double on firefox.  (https://github.com/w3c/uievents/issues/202)

**Comment by yunyunzai** [comment]
@RobinHerbots 

5.0.0-beta.252 fixed the issue perfectly! And I've tested with Android + Chrom and the issue was fixed flawlessly. I will go ahead close the issue and decline my PR.
Very appreciated!

Tested:
https://jsfiddle.net/yunyunzai/kpsb5wmv/

**Comment by yunyunzai** [comment]
@RobinHerbots 
Does the newest release 5.0.4-beta.40 not have this fix in?
I'm seeing the reappearance of the issue in the newest release. (haven't updated the lib since 5.0.0-beta.252)
