### ISSUE TITLE
isInputEventSupported method is creating a non-passive event

### ISSUE THREAD

**Issue by weisborg** [RobinHerbots/Inputmask#2185]
**Describe the bug**
isInputEventSupported method- in doing the secondary check setting "return;" to the attribute actually creates an event that isn't passive.  Even though the element is garbage collected, Chrome still throws a bunch of warnings for it. (Seems to be at least one warning for every input with a mask)

**Live example**
Use the library and look in console for warnings about the touchstart not being passive.

**Please complete the following information:**
 - OS: Windoze
 - Browser: Chrome, and most likely anything Chromium based like the new Edge and others.
 - Inputmask version : 4.0.6, but the 5 beta still does the same thing.  I think the secondary check is for some FireFox bug that may not even exist anymore.

**Additional context**
How do you feel?  Fine.  Do you want to talk about (it)? Just did, and removed the secondary check in my code to get rid of the warnings.  Why do you care?  Saves others time and trouble trying to track down where all the warnings are coming from.

**Comment by RobinHerbots** [comment]
@weisborg , 

Fixed in the latest 5.x ;-)
