### ISSUE TITLE
Does not work on XHTML pages.

### ISSUE THREAD

**Issue by ForbiddenEra** [RobinHerbots/Inputmask#2187]
Inputmask is not working on XHTML pages, at least for "live" masking.

http://localbuds.shaped.ca/masktest.xhtml -> not working
http://localbuds.shaped.ca/masktest.html -> working

When calling $(selector).maskinput, it will mask anything that is already set in it's value. In Firefox, if you enter a value and press refresh (not hard-refresh) FF will keep that value in the next render and this will get masked. Chrome doesn't seem to save the value on a soft refresh or at least I didn't see that behaviour with it.

I just recently came across a bug in Google's Closure library that also wouldn't work with XHTML, turned out to be because they were creating elements with uppercase names which isn't valid in XHTML. (ie. <INPUT> instead of <input>)

Unfortunately here, I do not get any errors so I have no idea what could be causing the issue. I tried enabling jitMasking as I thought that was what I needed for it to work, but apparently that must not be something other than "live masking of user inputs" as apparently it's disabled by default and the behaviour I am expect is working fine with the code I am using when served as html.

Anyone have any ideas where I should start digging? I'm surprised an error isn't being tossed, but unfortunately I see nothing on the console (in either FF or Chrome).

**Comment by ForbiddenEra** [comment]
Same problem, actually.

> From w3schools.com:
The HTML5 standard does not require lowercase tags, but W3C recommends lowercase in HTML, and demands lowercase for stricter document types like XHTML.

line 1682 of the non-minified jquery src (in dist) has ``isSupported = "INPUT"`` .. etc .. changing all "INPUT" to "input" in the source file fixed my problem (3 occurances). Will also change TEXTAREA to textarea, and any other elements I find...

see fixed now:
http://localbuds.shaped.ca/masktestfixed.xhtml

**Comment by RobinHerbots** [comment]
@ForbiddenEra , 

Thx for the information and solution.  I pushed an updated version which should work now.

Best regards, 

Robin
