### ISSUE TITLE
Wrong mask application on decimal field

### ISSUE THREAD

**Issue by alissonvinicius** [RobinHerbots/Inputmask#2188]
**Implementation**
`$('.js-decimal').inputmask('decimal', { digits: 8, digitsOptional: false, max: 999999999, placeholder: '0.00000000', rightAlign: false, showMaskOnHover: false });`

**Steps to reproduce**
1 - Type any numeric value.
2 - Double click on field to select the content.
3 - Type a dot and after that type any number.

**Example**
https://imgur.com/a/Ltf5qMn

**Please complete the following information:**
 - OS: Windows.
 - Browser: Chrome.
 - Inputmask version: 4.0.8

**Additional context**
Thanks for the assistance.

**Comment by RobinHerbots** [comment]
@alissonvinicius, 

This is also an issue in v5 beta.

**Comment by RobinHerbots** [comment]
@alissonvinicius , 

Fixed in version 5.0.0-beta.287
