### ISSUE TITLE
issue with $(field).val(..) in onincomplete / oncomplete

### ISSUE THREAD

**Issue by gvdhoven** [RobinHerbots/Inputmask#219]
See test case: http://jsfiddle.net/3tstg/17/
I also added 'percentage' aliases (value 0-100). Feel free to copy.

In this fiddle, if you replace

``` javascript
$(this)[0].value = 100;
```

with

``` javascript
$(this).val(100);
```

Then the final value will be '10' instead of '100'.

**Comment by gvdhoven** [comment]
p.s. function can be compacted to this:

``` javascript
function() {
  var x = parseFloat($(this).inputmask('unmaskedvalue'));
  $(this)[0].value = (isNaN(x) || x < 0) ? 0 : (x > 100) ? 100 : x;
}
```

But if you enter 100 you can't enter a value of '1' anymore. Possibly a bug in the created alias?

**Comment by RobinHerbots** [comment]
.val(100) works now, but there is an issue with iscomplete for the decimals, but there are already issues for that open.
