### ISSUE TITLE
Use inputmask without rounding

### ISSUE THREAD

**Issue by ngthaiduong31191** [RobinHerbots/Inputmask#2191]
I want to use Currency Input Mask without rounding 
current : 1.567 => 1.57
I want to display: 1.567 => 1.56

Any one can help me
I cannot find any function for this.
     
 radixPoint: decimalSep,
            groupSeparator: groupSep,
            suffix: suffixText,
            prefix: prefixText,
            autoGroup: true,
            autoUnmask: true,
            removeMaskOnSubmit: true,

**Comment by RobinHerbots** [comment]
@ngthaiduong31191 , 

Which version are you using of inputmask?

**Comment by RobinHerbots** [comment]
@ngthaiduong31191, 

I added a rounding option to the currency alias.

See readme_numeric.

**Comment by ngthaiduong31191** [comment]
> @ngthaiduong31191,
> 
> I added a rounding option to the currency alias.
> 
> See readme_numeric.

Thanks for your enthusiastic help for this issues. It's really helpful
