### ISSUE TITLE
inputmode not working

### ISSUE THREAD

**Issue by movedoa** [RobinHerbots/Inputmask#2193]
**Describe the bug**
I want to set inputmode to get the correct keyboard on touch devices but it its not working.
I tried it on Windows with Firefox and iOS Safari.
The attribute is never set.

**Example**
`oInput.inputmask('decimal', { positionCaretOnTab: false, inputmode: "numeric", radixPoint: ",", allowMinus: poWidgetFormat.AllowNegative, rightAlign: false, integerDigits: poWidgetFormat.MaxLength, digits: 0 });`

**Please complete the following information:**
 - OS: iOS and Windows
 - Browser Safari and  Firefox
 - Inputmask version 4.0.8 and 5.0.0-beta.258

**Comment by RobinHerbots** [comment]
@movedoa ,

I found a typo in inputmode.

Can you have a try with version  5.0.0-beta.270

Also verify that you os/browser supports it. https://caniuse.com/#feat=input-inputmode

**Comment by movedoa** [comment]
It works with your fix. Thx.
Is 5.0.0 ready for production?
If not could you backport this to 4?

**Comment by RobinHerbots** [comment]
@movedoa , 

I give you the choice.  I also released v4.0.9 with a fix for inputmode.

Although 5.0.0 beta is, in my opinion, superior to the 4.x branch already, there are some small issues to iron in the numeric alias, before I want to release 5.0.0.

**Comment by movedoa** [comment]
Thank you very much. Great work.
