### ISSUE TITLE
Time 24 Hours Issue.

### ISSUE THREAD

**Issue by pkgiriswamy** [RobinHerbots/Inputmask#2194]
**Describe the bug**
Hi, I really impressed your plugin thanks for the sharing this plugin with us.
recently I found one issue in the 'HH:MM:SS' mask type. the issue is when I enter the first number 2 in the input field afterward it is not taking any value in the field.
**Live example**
https://jsfiddle.net/6usdg27n/

**Please complete the following information:**
 - OS: Window
 - Browser: All 

Regards
Giriswamy

**Comment by RobinHerbots** [comment]
@pkgiriswamy , 

Upgrade to the 5.0.0 beta version

https://jsfiddle.net/ksjth8od/

**Comment by pkgiriswamy** [comment]
Hi Sir,
        Thanks for your replay, it's working but again it's having some issues.
   First type 24:55:55 in the input box then it will take 02:55:55, now clear the input value and again type 2 then it's taking 02( here 24 hours not taking), it's taking only 12 hours format. Thanks for advance for your help.
Regards
Giriswamy

**Comment by RobinHerbots** [comment]
@pkgiriswamy , 

No in fact it takes 23:59:59, but 24:55:55 it not possible as it should be 00:55:55.

Anyway you don't see it as a clock but as just time.

What do you expect?  That you can type 35:45:65 and 32565:55:55
Or do you want a limit on the hours?

**Comment by pkgiriswamy** [comment]
Thank you very much for quick replay, the first time value(24:55:55 into 02:55:55) it's taking auto-correct after, if I clear the value, I am not able to type 22 hours 55 minutes 55 seconds, it's taking 02 hours only.

Thanks for advance for replay.

**Comment by RobinHerbots** [comment]
@pkgiriswamy , 

You are correct.  I will see how to fix this.

**Comment by RobinHerbots** [comment]
@pkgiriswamy , 

I pushed an update which fixes your issue.
https://jsfiddle.net/y3wnL19s/

But I still need to see why you can't enter 22:55:55 with the previous datetime format.  So I keep the issue open.

**Comment by pkgiriswamy** [comment]
Hi Sir, 
Thanks for quick turnaround, the requirement here is when a user wants to type 23:58:45 has duration it should not allow the user to type numbers greater than 3 in the second digit of hh.
Thanks in advance.
Regards
Giri

**Comment by RobinHerbots** [comment]
@pkgiriswamy , 

Ok, you got my attention ;-)  I will see if I can fix the issue with not allowing 22 after 24.

**Comment by pkgiriswamy** [comment]
Thanks, for the quick replay and waiting for your response.

Regards
Giriswamy

**Comment by RobinHerbots** [comment]
@pkgiriswamy , 

https://jsfiddle.net/0sm9gz7a/

**Comment by pkgiriswamy** [comment]
Hi Robin, 
 Thanks for the quick replay, please check the below acceptance criteria for time 24 hours format.

Here are my acceptance criteria for date and time input.

1. User should able to give the input value in 24 hours format HH:MM:SS
2. When the user enters the first letter and 2 letters (HH)
   1. If the first letter greater than 2, then it should prefix 0.
    example:1. if I type 3 or 4( greater than 2) then it should be 03 or 04 hours
   2. if I type 2 then the second letter should be 0,1,2 or 3, it should not allow more than 3.
      example: max value is here 23 hours.
3. when user enter MM values
    1. if 3 letters are greater than 5, then it should prefix 0.
    example:1. if I type 3rd letter 6 or 7( greater than 5) then it should be 06 or 07 minutes and max value here 59 minutes.
4. When user enter SS values
    1. If the 5th letter greater than 5, then it should prefix 0.
    example:1. if I type 5th letter 6 or 7( greater than 5) then it should be 06 or 07 seconds and max value here 59 seconds.
5. when user copy and paste above all validations should work.

Thanks in advance, please help me with this one.

Regards
Giriswamy

**Comment by RobinHerbots** [comment]
@pkgiriswamy , 

Which case isn't handled? 
https://jsfiddle.net/0sm9gz7a/

**Comment by pkgiriswamy** [comment]
Hi Robin, Thanks for the quick replay,
2. When the user enters the first letter and 2 letters (HH)
If the first letter greater than 2, then it should prefix 0.
example:1. if I type 3 or 4( greater than 2) then it should be 03 or 04 hours
if I type 2 then the second letter should be 0,1,2 or 3, it should not allow more than 3.
example: max value is here 23 hours.

Regards
Giri

**Comment by RobinHerbots** [comment]
@pkgiriswamy , 

You mean when you type 24 it converts to 02:4M:SS  ?

**Comment by pkgiriswamy** [comment]
It should not allow 4 after (max value is 23:59:59) first letter 2 enter.

**Comment by pkgiriswamy** [comment]
Hi, If you don't mind, can we connect through a skype call? I can explain all the scenarios for you to understand.

Regards
Giri

**Comment by RobinHerbots** [comment]
@pkgiriswamy , 

I do understand the requirements, ... just need time to fix them, and will translate again into a delay for v5.00 :-(

**Comment by pkgiriswamy** [comment]
Thanks, Robin, I am eagerly waiting for your response.

Thanks in advance

**Comment by RobinHerbots** [comment]
@pkgiriswamy , 

Can you have a try with https://codepen.io/robinherbots/pen/BayByYm
