### ISSUE TITLE
bootstrap-datepicker: date bug in mobile version

### ISSUE THREAD

**Issue by vd1216** [RobinHerbots/Inputmask#2195]
Hi!
i use this plugin with datapicker (https://bootstrap-datepicker.readthedocs.io/en/latest/options.html#autoclose)
inputmask options         
$('.date_birthday input').inputmask({alias: '99-99-9999',clearMaskOnLostFocus: false});
in mobile version we have such bug:
if i remove this clearMaskOnLostFocus: false - inputmask remove last character in year(http://prntscr.com/pcwfz2)
and if i add clearMaskOnLostFocus: false than inputmask add extra character into datapicker (http://prntscr.com/pcwfmx)

how to fix it?

**Comment by RobinHerbots** [comment]
@vd1216 , 

Which version of inputmask are you using?

**Comment by vd1216** [comment]
* Version: 5.0.0-beta.272

**Comment by RobinHerbots** [comment]
@vd1216 , 

Can you create a jsfiddle or codepen, so it is easirer to see (debug) what happens.

**Comment by vd1216** [comment]
here you are) 
https://codepen.io/vd1216/pen/ExYBdXx?editors=1010
try it using mobile)
i use this version :
* jquery.inputmask.bundle.js
* Version: 4.0.9
because i couldn't find CDN for this Version: 5.0.0-beta.272

**Comment by marcelor** [comment]
I have the same problem (version 4.0.9 and latest beta).

**Comment by vd1216** [comment]
@RobinHerbots is it possible to fix this bug?

**Comment by RobinHerbots** [comment]
@vd1216 , 

Does this work for you?

https://codepen.io/robinherbots/pen/PoowBBJ?editors=1010

**Comment by vd1216** [comment]
@RobinHerbots  nope( 
the same behavior

**Comment by RobinHerbots** [comment]
On which mobile device are you testing?

**Comment by vd1216** [comment]
samsung galaxy s9+
chrome

**Comment by RobinHerbots** [comment]
@vd1216 , 

Even without the datepicker that doesn't work.  Probably due to the samsung keyboard.  Can you have a test with the google keyboard?  I can not set it up in browserstack on the samsung s9 .

**Comment by vd1216** [comment]
i tried it on iphone 7 with last iOS and have same problem ((
i think, there is something with touch events

**Comment by RobinHerbots** [comment]
@vd1216 , 

Strange. I tested Iphone 7 chrome in browserstack and don't experience a problem.

Did you use https://codepen.io/robinherbots/pen/PoowBBJ?editors=1010 ?

**Comment by vd1216** [comment]
yes i used this link.
in real devices it doesn't work.

**Comment by RobinHerbots** [comment]
Can you try installing the google keyboard on your samsung just to make sure that works.

**Comment by vd1216** [comment]
![1920x1080x80_Screenshot_20191008-124324_Chrome](https://user-images.githubusercontent.com/11242356/66385149-b02d4a80-e9c8-11e9-8a45-921d3a82f561.jpg)

**Comment by vd1216** [comment]
i installed google keyboard, and it doesn't work either.
look at november 111

**Comment by RobinHerbots** [comment]
@vd1216 , 

Ok I see.  Which event triggers the change in the datepicker?

**Comment by vd1216** [comment]
@RobinHerbots 
this._trigger("changeDate")
.on("changeDate"....
https://github.com/uxsolutions/bootstrap-datepicker

**Comment by RobinHerbots** [comment]
@vd1216 , 

The datepicker listens to keydown, keyup and paste.

On mobile the inputmask only relies on the input event, which emulates keydown and keypress.
With the help of the onKeyValidation option you can trigger keyup which will trigger the datepicker in time.

```
 $('#datepick-br').inputmask({alias: "datetime", inputFormat: "dd-mm-yyyy", 
                                onKeyValidation: function() {
                                  $(this).trigger("keyup");
                                }});
```

**Comment by vd1216** [comment]
@RobinHerbots thank you so much )

**Comment by RobinHerbots** [comment]
@vd1216, 

Ok, I integrated the fix, so you can now leave the onkeyvalidation out. (5.0.0-beta.281)
