### ISSUE TITLE
Can enter character 'e' in MaskNumber

### ISSUE THREAD

**Issue by ngthaiduong31191** [RobinHerbots/Inputmask#2197]
hi everyone, I'm using Mask Number. 
Actually: I can enter 'e' into this
Expect: Cannot enter 'e' because it's numeric text box

Can anyone can help? Thank you so much for checking this issue.

**Comment by RobinHerbots** [comment]
@ngthaiduong31191 , 

Which options are you using?  Which version do you use?  Which OS & Browser.

Can you create an example.

**Comment by ngthaiduong31191** [comment]
> @ngthaiduong31191 ,
> 
> Which options are you using? Which version do you use? Which OS & Browser.
> 
> Can you create an example.

Dear RobinHerbots , 

Sorry, it's my mistake. This issues happened when I choose type of  text box is number. 
And I try to change type to text, it's working fine. 

Thank you for your quick support.
