### ISSUE TITLE
Enter key not working in textarea

### ISSUE THREAD

**Issue by gboaron** [RobinHerbots/Inputmask#2198]
I set up a regex mask in a textarea. The regex is working fine. The only thing I need now is the [ENTER] key normal behavior so it starts a new line when I press this key.

 - Browser: Chrome and Mozzilla
 - Inputmask version: 5.0.0-beta.277

That's how I'm using the mask: 
$("#textarea").inputmask( { regex: "[a-zA-ZÀ-ú0-9:()/\\-,.?_@!$% ]*" } );

Thanks for any help!

**Comment by RobinHerbots** [comment]
@gboaron, 

You also need to allow enters in your regex.

regex: "[a-zA-ZÀ-ú0-9:()/\\-,.?_@!$% \\r\\n]*"

**Comment by gboaron** [comment]
OK Robin.
That worked. I tried just with \n
Thank you!
