### ISSUE TITLE
Currency field value can't be overwritten properly

### ISSUE THREAD

**Issue by toxpal** [RobinHerbots/Inputmask#2199]
Please accept my apologies if such issue already exists, but I couldn't find it. The bug exists in all builds of v5.

If alias is set to **currency** (somehow, I believe it might also affect "normal" decimals) and field contains some value, only a part of it can be changed. To see what I mean:

1. Visit https://jsfiddle.net/1kp76ygm/
2. Select whole value in field with mouse and start typing (just like you do when you want to completely replace existing value in some field) some decimal number
3. No matter what you type, number before **.** symbol becomes 0 and remains so.

**Comment by RobinHerbots** [comment]
@toxpal , 

No prob.  Can you have a new try.  The latest rebuild should have fixed this.

**Comment by toxpal** [comment]
All is good, issue closed!
