### ISSUE TITLE
strange compat issue with jquery.validate.unobtrusive

### ISSUE THREAD

**Issue by stevenrobertscrew** [RobinHerbots/Inputmask#22]
If I click in a field with a mask then click out of it, the validation error does not go away.  I believe this is because of the place holders (I'm using _ ) even though the mask clears after leaving the field.  This is also a problem with the base code from Josh.  Perhaps there is a way to ensure that the mask clearing is the first thing that happens before blur?  I know this is not Exactly your issue but it seems there is an opportunity here...

**Comment by RobinHerbots** [comment]
Hi Steven , I take the opportunity :-) Can you create an example on
jsfiddle.  I never used jquery.validate.
Op 27 jan. 2012 18:56 schreef "Steven" <
reply@reply.github.com>
het volgende:

**Comment by stevenrobertscrew** [comment]
and I've never used jsfiddle. :)  I will at least post a link to a page that demonstrates the problem.  Please give me a day or two.

**Comment by stevenrobertscrew** [comment]
upon further investigation, this is actually an issue with the underlying jquery.validate.js plugin.  The plugin uses the value property of the input to validate.  In my case the mask is (999) 999-9999 and when the user has not typed anything in the value property returns (___) ___-____.  I've tried setting the autoUnmask to true, but because the validate plugin uses value instead of val() the validation still fails.

if I could somehow remove the mask prior to validation firing and put it back after validation is done that might work as a work around, but I'm not sure how I can grab the current mask.

**Comment by stevenrobertscrew** [comment]
as a work around, I've done the following in the onfocusout

```
            if (element.value == "(___) ___-____") {
                $(element).val('');
            }
```

obviously this isn't optimal.  even if I could write something like

```
if (element.value == $(element).inputmask)
    //reset value
```

it would be an improvement, but it'd be even better if the mask itself reset the value property....

Just some ideas.

**Comment by RobinHerbots** [comment]
Can't you set an default value for jquery.validate ?  So that the "empty"
value equals the empty mask?

Otherwise, issue 5, would solve your problem.  But I need time to
investigate more on that.

Robin

2012/1/29 Steven <
reply@reply.github.com

**Comment by stevenrobertscrew** [comment]
Thanks, I CAN set the defaultValue property and then check the field isn't equal to that as a work around.  One thing that would make it cleaner...  is it possible to read the inputmask that has been applied to the field? e.g.  

```
var mask = $(element).inputmask("mask");
```

also, perhaps applying the mask could set the default value?  I'm unsure what the consequences of this would be.

**Comment by RobinHerbots** [comment]
If I set the default value for jquery.validate then the inputmask would be very bound to jquery validate.  I don't think that's a good idea.  

Anyway check out
https://github.com/RobinHerbots/jquery.inputmask/commit/cc534d986580e8803bc3881ebd3a90e654c194d0

getemptymask command added on dev branch ;-)

**Comment by stevenrobertscrew** [comment]
ok, this worked for me, at least as a 'good enough' until you manage to sort issue #5.  Anyway, being able to read what the mask was set to is a good feature.
