### ISSUE TITLE
How to allow only 1 dash in mask (Phone number)

### ISSUE THREAD

**Issue by gvdhoven** [RobinHerbots/Inputmask#220]
As you might have been noticing, i am implementing jquery.inputmask on a webshop.

The following struggle. I would like to allow decimals in a phone field. The format/mask is free  to enter for the user, but i would only allow one '-' for instance:
06-12345678

How can i restrict the dashes to one?

**Comment by RobinHerbots** [comment]
define a definitions with a clever regex or make a function which checks for the - to occur once

**Comment by gvdhoven** [comment]
Hi Robin, can you point me (via the wiki possibly) in a direction where i should implement this?

**Comment by RobinHerbots** [comment]
@Webunity ,

I will write a little example in the wiki, but I don't have much time.

anyway quick is make a definition with a function (see readme)
copy the regex from the \* definition add -  validate on it if success check if the buffer contains already a - return result

somethin like that ;-)

**Comment by RobinHerbots** [comment]
@Webunity, 

See the wiki!
