### ISSUE TITLE
DateTime : Hours shifts on the right

### ISSUE THREAD

**Issue by Wardenfar** [RobinHerbots/Inputmask#2201]
Hello,

I'm using your project for masking datetimes
I used the mask : "dd/mm/yyyy HH:MM" with alias : "datetime"
When i tap the date from a clear input it works but when i comeback to my page with the HTML value: "01/12/2002 11:52" => the input field become "01/12/2002 01:15" after i call jquery.inputmask

**Live example**
http://jsfiddle.net/d17avpb4/

**Please complete the following information:**
 - OS: Windows
 - Browser Chrome
 - Inputmask 5.x 

Thank you in advance

**Comment by RobinHerbots** [comment]
@Wardenfar , 

This issue seems to be fixed.
