### ISSUE TITLE
Inputmask is not working correctly with inputmode=numeric/decimal

### ISSUE THREAD

**Issue by Herald85** [RobinHerbots/Inputmask#2202]
Hi, I have created this alias:
`{alias: "numeric",
			radixPoint: ".",
			groupSeparator: ",",
			autoGroup: true,
			digits: 2,
			digitsOptional: false,
			placeholder: "0,0.00",
			rightAlign: true,
			clearMaskOnLostFocus: true}` which is working perfectly with inputmode="text" or even with inputmode="tel". I start typing digits, then press ".", cursor gets into decimal part and I can continue typing.

But if I use inputmode="numeric" or inputmode="decimal" it doesn't work like that anymore. Typing digits before "." still works, but only up to 3 digits (I guess because of grouping), after that nothing else happens. Pressing "." does nothing, pressing "," does nothing. I can get cursor into decimal part with right arrow, but even then only 1 digit is accepted and then cursor goes to the end of number. If I would like to enter second decimal digit, I need to go with left arrow before that and type it. It's really completely different behavior from inputmode="text".

Is that a bug or intended? My version is 5.0.0-beta.161, tested on desktop Chrome Version 74.0.3729.157 (Official Build) (64-bit)

**Comment by RobinHerbots** [comment]
Can you first retry with version ,5.0.0-beta.288

Op do 17 okt. 2019 16:22 schreef Herald85 <notifications@github.com>:

**Comment by RobinHerbots** [comment]
Do you Mean inputmode or inputtype?

Op do 17 okt. 2019 19:42 schreef Robin Herbots <robin.herbots@gmail.com>:

**Comment by Herald85** [comment]
Thanks for your response!

I tried with 5.0.0-beta.290, but the behavior is still the same.

**Comment by RobinHerbots** [comment]
Can you make a codepen. With the exact mask and options.

Robin

Op vr 18 okt. 2019 09:25 schreef Herald85 <notifications@github.com>:

**Comment by Herald85** [comment]
I apologize, the problem was further down in my implementation, nothing to solve.
