### ISSUE TITLE
Safari autofill not working ;c

### ISSUE THREAD

**Issue by FeST1VaL** [RobinHerbots/Inputmask#2205]
- I cant autofill input from iPhone. onBeforePaste just empty. 
- https://codepen.io/fest1val/pen/PoobMrq
- iOS 12.4.2 iPhone 6+
- Safari
- Inputmask 4.0.9

mask event oninput blocking value ;c its work but... http://skrinshoter.ru/s/211019/4UDbhfSv

**Comment by RobinHerbots** [comment]
@FeST1VaL , 

Can you retry with the latest version?  v5.0.0-beta...

**Comment by FeST1VaL** [comment]
Nope, just cant autofill ;c

Video: 
https://youtu.be/ztU23cgx3mw

Sandbox:
https://codepen.io/fest1val/pen/VwwXGXG

**Comment by RobinHerbots** [comment]
@FeST1VaL , 

Thx for the extra info.  I will have a look why.

**Comment by abordage** [comment]
Any news?
A similar problem with safari
Inputmask 5.0.1

**Comment by RobinHerbots** [comment]
DOes this also happen in https://codepen.io/robinherbots/pen/jOEKVKv

How exactly do you trigger the paste?  Is this on IOS or MacOS

**Comment by FeST1VaL** [comment]
@RobinHerbots, 
U codepen worked... i can paste my phone. Thx
