### ISSUE TITLE
Issues with Account format 

### ISSUE THREAD

**Issue by twigs67** [RobinHerbots/Inputmask#2206]
I'm not sure if it's designed this way, but I'm having an issue with creating a accounting numerical format. I have:

```
  new Inputmask("(,999){+|1}.00", {
    positionCaretOnClick: "radixFocus",
    radixPoint: ",",
    _radixDance: true,
    numericInput: true,
    placeholder: "0",
    definitions: {
        "0": {
            validator: "[0-9\uFF11-\uFF19]"
        }
    }
}).mask($("#amount_financed"))
```

It works correctly, but you have to click on the whole number and decimal numbers separately to add them, which is really annoying. Is there not a way for the user to start by entering the decimal places and then follow up with the whole numbers for a nice flow?

Thanks

**Comment by RobinHerbots** [comment]
@twigs67 ,
Can't you use the numeric alias? See readme.

**Comment by RobinHerbots** [comment]
```
	Inputmask("currency",  {
			numericInput: true
        }).mask("amount_financed");
```
