### ISSUE TITLE
How I can remove caret selection while edit datetime input?

### ISSUE THREAD

**Issue by AleksandrGucci** [RobinHerbots/Inputmask#2207]
Can I remove this selection, while editing input? Just like default input

1. Inputmask
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/34480893/67281031-31abcf00-f4d7-11e9-9778-1c5d74da4eb3.gif)

2. Expected
![ezgif com-video-to-gif-2](https://user-images.githubusercontent.com/34480893/67283511-7be37f00-f4dc-11e9-8128-a54c5d8706a4.gif)

I know about insertMode, but it's also not working as expected. Any suggestions?

**Comment by RobinHerbots** [comment]
@AleksandrGucci , 

I added a new option insertModeVisual.

Set this one to false.
