### ISSUE TITLE
Alias DateTime InputFormat: ' H2':MM' Problem

### ISSUE THREAD

**Issue by golaranjeira** [RobinHerbots/Inputmask#2208]
Robin Herborts Thank you for your work 

I am having a problem with this Inputmask({alias:'datetime',inputFormat: 'H2:MM'), the mask blocks the second digit only allowing 12, 22, 32,92,...
But I want to be possible to use all the numbers and have something like 98:59...
Can you describe the solution to this?

Thanks

**Comment by RobinHerbots** [comment]
@golaranjeira , 

Which version are you using of the Inputmask?

**Comment by golaranjeira** [comment]
@RobinHerbots  Version: 5.0.0-beta.290

**Comment by RobinHerbots** [comment]
@golaranjeira ,

https://jsfiddle.net/gm1vyq46/2/

**Comment by golaranjeira** [comment]
Thank you very much @RobinHerbots
