### ISSUE TITLE
DateTime - HH:mm format doesn't accept some numbers for minutes

### ISSUE THREAD

**Issue by toxpal** [RobinHerbots/Inputmask#2209]
This bug didn't exist in old builds of v5, but happens with recent builds (including the latest 292).

When field has "datetime" alias and mask set to "HH:mm", it's impossible to set some numbers as minutes using standard JS functions. In other words, inputmask replaces some numbers with 00.

See what I mean - https://jsfiddle.net/Ltznjvrb/

Click "set time" button and see what happens - instead of setting value to 14:02, value is set to 14:00. However, if you remove inputmask from text field, value can be set perfectly. Also, if you type value (14:02) manually, it also works fine, even if inputmask is used. But try to set it using JS function, and everything fails.

By the way, 14:02 is just an example. You can change JS function, so it tries to set value as 14:05, 14:09 or similar - result will be the same (14:00). But if you try to set value higher (when minutes exceed 10), it starts working again.

**Comment by RobinHerbots** [comment]
@toxpal , 

Fixed in version ... 293

**Comment by toxpal** [comment]
I knew it's going to take less than 24 hours to deploy a patch. As usually...
