### ISSUE TITLE
Clone field with inputmask

### ISSUE THREAD

**Issue by WaltDaniels** [RobinHerbots/Inputmask#221]
I have a table where I need to be able to clone a row and create an empty row via javascript.  I'm using the jQuery .clone() function, but the inputmask functionality isn't copied during the clone.

Any thoughts as to how I can clone a field with an inputmask?

Thanks!

**Comment by RobinHerbots** [comment]
@WaltDaniels , 

Maybe set the mask definitions via data-inputmask attributes and after cloning you call $.(":input").inputmask();

**Comment by RobinHerbots** [comment]
@WaltDaniels ,

Did the above work?

**Comment by WaltDaniels** [comment]
Yes, that seems to work, however I still am wondering why the jQuery ".clone(true)" (copying data & events) doesn't do the trick.  Thanks!
