### ISSUE TITLE
Placeholder option doesn't work for decimal alias

### ISSUE THREAD

**Issue by ArtemProkopenko** [RobinHerbots/Inputmask#2211]
Hi Robin,

**Configuration:**
`
$("#example").inputmask({
  alias: 'decimal',
  placeholder: '0',
});
`

**Expected Behavior (4.0.9):** If I erase the contents of the input, **the value 0 (zero) remains** in the field. 
This works for the latest stable version: https://codepen.io/bushart/pen/gOOXmoM
**Current Behavior (5.0.0-beta.290):** If I erase the contents of the input, the **value becomes an empty string**. https://codepen.io/bushart/pen/xxxPqPB

**Comment by RobinHerbots** [comment]
@ArtemProkopenko , 

In the codepen with version 5 you have used   placeholder: 0, which should be   placeholder: '0', instead.

**Comment by ArtemProkopenko** [comment]
@RobinHerbots ,
I made a change, but it still doesn't work.

**Comment by RobinHerbots** [comment]
Add ,
  clearMaskOnLostFocus: false

**Comment by ArtemProkopenko** [comment]
@RobinHerbots, Thanks, it seems to work.
