### ISSUE TITLE
digitsOptional: true + suffix not working as expected. can't enter decimal digits

### ISSUE THREAD

**Issue by wittich** [RobinHerbots/Inputmask#2212]
Hi there, I just try to get a currency input running using the iso code instead of the currency sign. It works quite well as long as I leave the `digitsOptional` parameter on `false`. When I set it to `true` I can't anymore input decimal digits.

```
    'alias': 'decimal',
    'groupSeparator': ',', 
    'suffix': " [EUR]", 
    'digits': 2, 
    'digitsOptional': true, // BUG
```
Here a (working) example: https://jsfiddle.net/wittich/5z8hesc4/

Any reason/explanation for that?

Regards

**Comment by RobinHerbots** [comment]
@wittich , 

This is fixed in version 5.0.0-beta.310

https://jsfiddle.net/0qxLcn62/
