### ISSUE TITLE
mask not being applied to vue model on beta

### ISSUE THREAD

**Issue by adlerdias** [RobinHerbots/Inputmask#2216]
- Describe the bug
mask is only being applied when typing. Pasting or applying mask to model doesn't work.

- Add a link to a codepen, jsfiddle or other example page which shows the problem
https://jsfiddle.net/adlersd/x8j9o2yq/

- OS:
Distributor ID:	Ubuntu
Description:	Ubuntu 19.10
Release:	19.10
Codename:	eoan

- Browser
Chromium 78.0.3904.97 snap
Mozilla Firefox 71.0a1
Mozilla Firefox 70.0.1

- Inputmask version
5.0.0-beta.302

**Comment by RobinHerbots** [comment]
@adlerdias , 

It has todo with the  positionCaretOnClick: 'select', option.

I will see how to fix this.

**Comment by adlerdias** [comment]
thank you fou the fast reply.

you are absolutely right, i updated fiddle with all possible values for the positionCaretOnClick.

is there any place that i can found how to run the tests?

**Comment by RobinHerbots** [comment]
@adlerdias , 

I pushed a fix for the issue.

To run the tests you need to run qunit.html.   Keep the focus on the window while running as otherwise some tests with focus will fail.

**Comment by adlerdias** [comment]
@RobinHerbots 

First of all thank you about the tests info.

I tested here and unfortunately for none and for select did not work. i've submited the tests as PR.

**Comment by RobinHerbots** [comment]
The fix is in version ...309

Op wo 13 nov. 2019 17:36 schreef Adler Dias <notifications@github.com>:

**Comment by RobinHerbots** [comment]
@adlerdias,

I will investigate why the initialvalue still fails with these options set.
Thx for the unittest!

**Comment by RobinHerbots** [comment]
@adlerdias , 

Ok, the unittest are working now ;-)

https://jsfiddle.net/wn8630L9/

It would be great if everyone created unittest for each issue.

**Comment by adlerdias** [comment]
thank you.

initial value with select is working, but value was not being selected due to a missing break in switch statement, so it was using ignore (next case ), i made a PR with it, still trying to figure a way to add a proper test to it.

if you don't mind i can extract tests from existent issues and submit as PR.
