### ISSUE TITLE
 Not compatible with jquery 3.4.1

### ISSUE THREAD

**Issue by ygmrblgn** [RobinHerbots/Inputmask#2217]
-  Not compatible with jquery 3.4.1,getAttribute is breaking 
- Visual Studio 2012
- ie,Chrome
- Inputmask version

**Comment by RobinHerbots** [comment]
@ygmrblgn , 

Can you create an example to reproduce the error.

Thx

**Comment by RobinHerbots** [comment]
@ygmrblgn , 

Which version of inputmask are you using?
