### ISSUE TITLE
When decimal input begins with a 'period' the incorrect digit limit is applied.

### ISSUE THREAD

**Issue by SPConnelly** [RobinHerbots/Inputmask#2219]
In my very simple example I have applied an input mask that allows for 3 integer digits and 4 decimal digits. However, if a leading period is typed into the input field (i.e. ".0000"), the mask correctly adds a leading zero but limits the decimal digits to 2 places resulting in "0.00" and no additional decimal places can be entered.

https://jsfiddle.net/fvbc8k7r/

- OS: Windows
- Browser: Chrome
- Inputmask version: 4.0.9

**Comment by RobinHerbots** [comment]
@SPConnelly , 

This is fixed with version 5.0.0-beta

https://jsfiddle.net/gxyu8zsr/

**Comment by SPConnelly** [comment]
That's great news!

Thank you for the reply.
