### ISSUE TITLE
clearIncomplete with optional mask

### ISSUE THREAD

**Issue by gabbaca** [RobinHerbots/Inputmask#222]
With the following phone mask and optional extension mask and setting clearIncomplete = true...

```
$("#phone").inputmask("999-999-9999 [x99999]",{ "clearIncomplete": true } });
```

If the optional mask part is not filled out completely the entire mask is cleared from the text box.

Is this by design?

**Comment by RobinHerbots** [comment]
@gabbaca ,

I verified and did some corrections.

The design. 

In your mask you have an optional part, translating the mask into 2 parts (masks)
"999-999-9999 " and "999-999-9999 x99999"

so typing 
1231231234 => mask iscomplete => no clear
12312312341 => mask incomplete => clear
123123123412345 => mask complete => no clear

I know it is a bit confusing as the optional tail gets cleared and the mask appears complete.
But that functionality was a quick win to implement the simple form of optional parts in a mask. (behavior like the bush plugin)

Anyway the behavior is like described above, and dynamic masks will solve this problem if you want the mask to be complete when you type for example 12312312341

The mask could be like this
$("#phone").inputmask("999-999-9999 [x9{1,5}]",{ "clearIncomplete": true } }); but this is not yet implemented

best regards, 

Robin
