### ISSUE TITLE
When using positionCaretOnClick: select and press end or right can't add number to the end

### ISSUE THREAD

**Issue by adlerdias** [RobinHerbots/Inputmask#2223]
I added a test as a PR.

It's possible to add a number at the begin of masked input, but can't add at the end(after radix point on latest beta.

I'll make an example soon as I got home again.

**Comment by RobinHerbots** [comment]
@adlerdias , 

For the unittests. I updated the simulator in the tests to correctly handle HOME, END, RIGHT, LEFT keys.

I will push a fix for this soon.

**Comment by RobinHerbots** [comment]
@adlerdias, 

Can you have a try with 5.0.0-beta.316

**Comment by adlerdias** [comment]
@RobinHerbots,

It's working flawlessly for every positionCaretOnClick.
We can definitely close this issue.
thank you
