### ISSUE TITLE
mask: option auto-chooses an option rather than denying input

### ISSUE THREAD

**Issue by 9mm** [RobinHerbots/Inputmask#2225]
Inputmask version: 4.0.9

This is my current code:

```
    $("#creditcardnumber").inputmask({
      mask: [
        "4999 9999 9999 9999",   
        "5999 9999 9999 9999",     
        "2999 9999 9999 9999",     
        "6999 9999 9999 9999 [999]",
        "3999 999999 99999"],   
      greedy: false,
      placeholder: "",
      clearIncomplete: true,
      keepStatic: false
```

The problem is when I type the number `1` it should prevent input because it doesn't match any of the masks. Instead, it auto-types `4` so the final output after pushing a single key is `41`

I would expect the mask to not allow anything because it doesn't match, and they can only type a 4,5,2,6, or 3

**Comment by RobinHerbots** [comment]
@9mm , 

I agree, but I will first test what the impact is on other masks when I change that behavior.

**Comment by 9mm** [comment]
Ah ok, well thanks. Is there an alternate way to do it where I can get that behavior in the meantime?

**Comment by RobinHerbots** [comment]
@9mm , 

Ok, 48 tests are failing, ...

To get the behavior you can define definition for 2,3,4,5,6, with validator [2] , ......

**Comment by 9mm** [comment]
Sorry, I don't completely follow your answer 😅

**Comment by RobinHerbots** [comment]
@9mm, 

I guess you mean defining definitions for it, ...

Anyway I have now only 6 tests failing, so i'm almost there.  I will push the change next week.

**Comment by RobinHerbots** [comment]
@9mm , 

Can you have a try with v5.0.0-beta.319

**Comment by 9mm** [comment]
Sure i will try in awhle when im back at my desk. Thanks for your great hard work, you have a great library Robin
