### ISSUE TITLE
Unable to input a date starting with "29/02" (dd/mm/yyyy)

### ISSUE THREAD

**Issue by xDEADC0DE** [RobinHerbots/Inputmask#2227]
- Windows 10 + Firefox
- Inputmask version: 4.0.9

Here's how InputMask is configured on my page:
```
<script type="text/javascript" src=".../js/jquery/jquery-3.4.0.js"></script>
<script type="text/javascript" src=".../js/jquery-ui/jquery-ui-1.12.min.js"></script>
<script type="text/javascript" src=".../js/jquery-ui/datepicker-fr.js"></script>
<script type="text/javascript" src=".../js/autoNumeric.min.js"></script>
<script type="text/javascript" src=".../js/inputmask/inputmask.js"></script>
<script type="text/javascript" src=".../js/inputmask/inputmask.date.extensions.js"></script>
<script type="text/javascript" src=".../js/inputmask/jquery.inputmask.js"></script>
<script language="JavaScript">
jQuery(function() {
	$("#startdate").inputmask({alias: "datetime", inputFormat: "dd/mm/yyyy", placeholder: " " });
```

This works fine, except when I try to input a leap day:
I can type "29/01" or "29/03", but not "29/02": the "2" never appears in the input.

I tried adding the following:
`leapday: "29/02/", separator: "/",`
but it didn't change anything.

**Comment by RobinHerbots** [comment]
@xDEADC0DE , 

Upgrade to version 5.0.0-beta

**Comment by xDEADC0DE** [comment]
Thanks for the quick reply!
Is there a list of breaking changes for moving from version 4.x to 5.x?

**Comment by RobinHerbots** [comment]
Best is to see in the changelog.md

**Comment by xDEADC0DE** [comment]
Oups, my bad! Google sent me to https://changelogs.md/github/robinherbots/jquery.inputmask/ which is out of date.

**Comment by RobinHerbots** [comment]
https://github.com/RobinHerbots/Inputmask/blob/5.x/CHANGELOG.md

**Comment by xDEADC0DE** [comment]
I tried 5.0.0-beta.314 but I still cannot input "29/02", and I get some new bugs.

Is there no way to add the leap day fix to version 4.0.9? Appart from that issue everything worked fine.

**Comment by RobinHerbots** [comment]
@xDEADC0DE , 

Can you create a jsfiddle with an example with the latest v5.

Maybe also mention which other masks give problems.

**Comment by xDEADC0DE** [comment]
I don't know how to create a jsfiddle with a specific library, but I'll try.

On the demo page (https://robinherbots.github.io/Inputmask/ ) I'm able to type "29/02", so I'll recheck my configuration.

**Comment by xDEADC0DE** [comment]
Got it to work!
I had to change this:
`$("#startdate").inputmask({alias: "datetime", inputFormat: "dd/mm/yyyy", placeholder: " "});`

into that:
`$("#startdate").inputmask("datetime", {inputFormat: "dd/mm/yyyy"});`

There's an issue with backspace/delete, but I think we can work around that.

**Comment by xDEADC0DE** [comment]
Oh, if I remove `placeholder: " "` it also works with InputMask 4.0.9!

**Comment by RobinHerbots** [comment]
@xDEADC0DE , 

Which issue did you have with backspace/delete?

**Comment by xDEADC0DE** [comment]
I'll create a new issue for it (if it's not already there).
