### ISSUE TITLE
How to: Replace character or insert extra one

### ISSUE THREAD

**Issue by Kariamba** [RobinHerbots/Inputmask#2228]
I have a list of numbers starting with 7 or 8. 8999 and 7999 are equal. So I want to get numbers starting only with 7 from usres.

Rules are simple:
- If first char is 7 then doing nothing (7 > 7).
- If first char is 8 then swap it to 7 (8 > 7).
- If first char isn't 7 or 8 then insert 7 on first position (9 > 79).

I use onBeforeWrite() method and return command object. I have done a lot of experiments, but couldn't achieve the aim. So, is it right way or shuold I use other method?

Can you explain command object more detail and add several examples to documentation?

Thank you.

**Comment by RobinHerbots** [comment]
@Kariamba , 

```
Inputmask({
				mask: "7999",
				definitions: {
					"7": {
						validator: function (chrs, maskset, pos, strict, opts) {
							if (chrs !== "7" && chrs !== "8") {
								return {
									c: "7",
									insert: {
										pos: pos + 1,
										c: chrs
									},
									caret: pos + 2
								}
							}
							return {
								c: "7"
							}
						}
					}
				}
			}).mask("test3");
```

**Comment by Kariamba** [comment]
@RobinHerbots.
Thank you, very, very much. Its works excellent.
