### ISSUE TITLE
Numeric regex allowing comma or dot as radixPoint

### ISSUE THREAD

**Issue by Herz3h** [RobinHerbots/Inputmask#2229]
I'm trying the following to allow decimal value either with dot or comma : 
```html
<input type="text" class="money-input">
```

```javascript
$('.money-input').inputmask({'regex': '^[0-9]{1,10}(,|\.)[0-9]{2}$'});
```

It almost works, except if I type ( pipe is where cursor sits):

12312|123.99

I can type another comma or dot (, or .), why is it doing this ???

**Comment by Herz3h** [comment]
This mask seems to be working as intended, don't know why though: 

```
[0-9]{1,10}((,|\\.)[0-9]{2})?
```

**Comment by RobinHerbots** [comment]
@Herz3h , 

It is the escaping. the regex is passed as a string which already consumes the escaping.  So you need double escaping.  This should explain https://javascript.info/regexp-escaping
