### ISSUE TITLE
Backspace selects the previous character.

### ISSUE THREAD

**Issue by xDEADC0DE** [RobinHerbots/Inputmask#2231]
On date InputMask (format "`dd/mm/yyy`"):
I can input a date without any issue ("`09/12/2019`", for example), but when I use backspace to delete the last digit of the year, the `9` is replaced with '`y`' and the second to last digit is selected.

This means that if I type `[backspace]` and then `[8]`, I get "`09/12/208y`" instead of "`09/12/2018`".

- link: This behavior appears on the demo page for InputMask: https://robinherbots.github.io/Inputmask/
- OS: Windows 10
- Browser: Firefox 52.5 ESR
- Inputmask version: At the time of writing, the demo page uses: https://rawgit.com/RobinHerbots/Inputmask/5.x/dist/jquery.inputmask.js

**Comment by RobinHerbots** [comment]
also see #2230

**Comment by RobinHerbots** [comment]
@xDEADC0DE , 

This is fixed
