### ISSUE TITLE
Numeric alias: backspace on groupSeparator deletes 2 numbers instead of 1

### ISSUE THREAD

**Issue by SimonBryatov** [RobinHerbots/Inputmask#2232]
- When focused after group separator and trying to delete via backspace, inputmask deletes 2 numbers instead of 1:

![image](https://user-images.githubusercontent.com/16355734/69724880-49115400-1136-11ea-8197-33012c2ce820.png)

![image](https://user-images.githubusercontent.com/16355734/69724917-60504180-1136-11ea-8cc4-c0f975fcb660.png)

- OS: Windows 10
- Browser Chrome 78.0
- Inputmask version 5.0.0-beta.314

Hope you'll fix it as soon as possible :)

**Comment by RobinHerbots** [comment]
@SimonBryatov , 

This is fixed in version 5.0.0-beta.321

Can you have a try?
