### ISSUE TITLE
Numeric alias: cannot clear input on blur

### ISSUE THREAD

**Issue by RobinHerbots** [RobinHerbots/Inputmask#2235]
Create a numeric mask.  
Type some number.
Select all and delete or backspace
Blur the input
The masktemplate should disappear but doesn"t

See demo page

Version: 5.x latest
Browser: all

**Comment by lequangminh** [comment]
please fix, tks

**Comment by lequangminh** [comment]
Not yet fix if input mask have space char, same ticket #1316
IE 11, Win 10 Pro,  * Version: 5.0.2-beta.1
Ex: Input -> Select all in textbox -> Press backspace or delete -> Not clear value in textbox (NG)
https://gyazo.com/05a0ce599f5d9df9f90657247de44a3f

inputmask("9999 - 99 - 99");
=> " - "

**Comment by RobinHerbots** [comment]
@lequangminh , 

Is this only in IE11?

**Comment by lequangminh** [comment]
> @lequangminh ,
> 
> Is this only in IE11?

In all browser (IE11, Edge, Chrome last ver...)

**Comment by RobinHerbots** [comment]
@RobinHerbots;

So in this codepen, select all and press delete or backspace and leave the input.
https://codepen.io/robinherbots/pen/KKwvBPo.

You are correct !  When there is an initial value it does not clear.  I will have a look.

**Comment by RobinHerbots** [comment]
@lequangminh, 
fixed in version Version: 5.0.2-beta.3
