### ISSUE TITLE
It is possible to display one date format but submit a different format?

### ISSUE THREAD

**Issue by sammuel-oliveira** [RobinHerbots/Inputmask#2236]
Hi, first of all, thanks for this useful tool. But, there is one thing that I couldnt resolve. 

It is possible to display one date format but submit a different format? In my case, I want to display a 'dd/mm/yyyy' format date, but submit in a 'yyyy-mm-dd' format. Is there one way to achieve this? 

Thanks in advance.

**Comment by RobinHerbots** [comment]
@sammuel-oliveira , 

You can specify an outputFormat in the datetime alias and set autoUnmask option to true.  See readme for datetime

Best regards, 
Robin

**Comment by sammuel-oliveira** [comment]
@RobinHerbots, very thanks for such a quick response. 

Indeed, those two options solved the problem in Javascript, but the problem remained when submitting the form. So, I changed 'removeMaskOnSubmit' to true and the submit keeped my custom 'outputFormat' also in backend. 

My alias configuration:

```javascript
'date': {
	alias: "datetime",
	autoUnmask: true,
	removeMaskOnSubmit: true,
	inputFormat: "dd/mm/yyyy",
	outputFormat: "yyyy-mm-dd",
	placeholder: '__/__/____',
	clearIncomplete: true
},
```

Thank you! 👍

**Comment by oscaroxy** [comment]
Hi, I don't understand how get the value with "outputFormat".
I define the inputmask like: 
```
$(selector).inputmask("datetime", {
                			removeMaskOnSubmit: true,
                			placeholder: 'dd/mm/yyyy',
                		        inputFormat: 'dd/mm/yyyy', 
                		        outputFormat:'yyyy-mm-dd',
                		        inputEventOnly: true
                		    });
```

If I use "$(selector).val()" then I'll obtain the value of text into input, that is if I write "05/05/2021" then I'll obtain `$(selector).val()` => 05/05/2021 and not 2021-05-05.
How have I to do?
thanks
