### ISSUE TITLE
Change digits number 

### ISSUE THREAD

**Issue by ChinSuOla** [RobinHerbots/Inputmask#2237]
$('#test1').inputmask("decimal",{
				placeholder: "0",
    digits: 2,
    digitsOptional: false,
    radixPoint: ",",
	positionCaretOnClick: "radixFocus",
    groupSeparator: ".",
    autoUnmask: true,
	unmaskAsNumber: true,
	greedy: true
	});

I want to change digits number with button? Pls help me thanksall

**Comment by RobinHerbots** [comment]
@ChinSuOla , 

Have a try with

```javascript
$("#test1").inputmask("option", {
  digits: 4
});
```
