### ISSUE TITLE
Placeholder with double spaces

### ISSUE THREAD

**Issue by silviomoreto** [RobinHerbots/Inputmask#224]
I am the jquery.inputmask (btw is the best input mask that Ive found).

I am trying to do a placeholder with a double space, like this:

```
$('#id_numbers').inputmask("9999999", {placeholder: '  '});
```

But the plugins doesnt apply the double spaces.There is a way to solve this?

**Comment by RobinHerbots** [comment]
@silviomoreto , 

With 2 spaces as placeholder you get a blank mask.  The placeholder gets mapped over the masktemplate.

Say in your case, if you had used inputmask("9999999", {placeholder: '12'} you get => 1212121

**Comment by silviomoreto** [comment]
Thank you @RobinHerbots 
do you have any plans to add a placeholder with a size higher than 1?

**Comment by RobinHerbots** [comment]
@silviomoreto ,

That is already the case. But I think you understand something else as the placeholder.  The placeholder hides away the definition and replaces it with the placeholder.

mask 99/99/9999 placeholder: "dd/mm/yyyy"   =>  shows dd/mm/yyyy as empty mask instead of **/**/____

**Comment by silviomoreto** [comment]
I think you misunderstood me.
Let's start with the reason to set double spaces as placeholder. If I use just one space, it doesnt seems like a character space (one space have almost half width of character `8`, for example).

So, to mimic the width of the characters I want to add two spaces. Now do you understand more my problem?

**Comment by RobinHerbots** [comment]
@silviomoreto ,

Yes now I see what you mean.  Can't this be fixed with some css?

**Comment by silviomoreto** [comment]
Do you know a way to solve by css?

And thanks again for the plugin and the support

**Comment by sompylasar** [comment]
@silviomoreto A monospace font applied to the input box?

**Comment by silviomoreto** [comment]
@sompylasar I want to keep using my font-family.. to use monospace and keep my font-family I would need to add to much js. I will try a work around for that. When finish I will do a pull-request

**Comment by sompylasar** [comment]
There are monospace fonts that visually match usual sans or serif fonts.
Good luck.
