### ISSUE TITLE
SSN Mask

### ISSUE THREAD

**Issue by RobinHerbots** [RobinHerbots/Inputmask#2242]
@RobinHerbots I have something that is similar to this issue. Since it is open, I thought this would be the appropriate place to put the question in. If we take the example above, https://jsfiddle.net/cecey8Ly/3/ and let's say, we have ssn value which consists of 9 digits and we want to be able to mask the numbers starting with zero as valid SSN, how would we do that? 
Right now, if we add the mask alias as numeric and specify the integer digits as 9, we cannot enter SSN values without a zero because the mask removes the leading 0 from the number.
**Sample test case**
_Actual Value:_ 012345678. 
_Masked Value_: 12345678

_Originally posted by @awalakaushik in https://github.com/RobinHerbots/Inputmask/issues/1883#issuecomment-562227157_

**Comment by RobinHerbots** [comment]
https://github.com/RobinHerbots/Inputmask/pull/2240#issuecomment-562587347

**Comment by RobinHerbots** [comment]
@awalakaushik,

We need to see if the validation is all possible in one regex.

**Comment by awalakaushik** [comment]
@RobinHerbots Sure. I agree. I'll try to do that over the weekend and see if I can create another pull request for the same with an example to it. Please let me know if you have any suggestions on how you want to do it.

**Comment by RobinHerbots** [comment]
http://rion.io/2013/09/10/validating-social-security-numbers-through-regular-expressions-2/

**Comment by RobinHerbots** [comment]
@awalakaushik, 

I updated your version of the ssn mask.  Can you have a try.

**Comment by awalakaushik** [comment]
Sure. I can do that. Thanks.
