### ISSUE TITLE
jitMasking and caret position with static characters

### ISSUE THREAD

**Issue by ben-woolnough** [RobinHerbots/Inputmask#2243]
Not a bug, but when jitMasking is true and you enter a character that comes before a static character (e.g. '/') it would be nice if the static character was automatically filled and the caret placed after it.

Fiddle to show current behaviour: [https://jsfiddle.net/suzmhwxp/](https://jsfiddle.net/suzmhwxp/)

The behaviour I'd like can be seen [here](https://cardjs.co.uk/) in the date field - after typing the second digit, the caret jumps after the forward slash.

Is there a way I can get it working this way in version 5.0.0?

Inputmask version: 5.0.0

Thanks!

**Comment by RobinHerbots** [comment]
@ben-woolnough, 

The current behavior is different, but I agree that the other behavior is more intuitive.
I shall see if I can update the jitmasking behavior.

**Comment by RobinHerbots** [comment]
@ben-woolnough , 

Have a try https://jsfiddle.net/pn9ejtcq/

**Comment by RobinHerbots** [comment]
Ow, just discovered that this doesn't work when you have multiple statics in sequence.

**Comment by RobinHerbots** [comment]
Fixed ;-)
https://jsfiddle.net/1wv2omb5/

**Comment by ben-woolnough** [comment]
That's amazing. Thank you!
