### ISSUE TITLE
group separator shown before being required

### ISSUE THREAD

**Issue by yankielap** [RobinHerbots/Inputmask#2245]
I have been using this component for about a year. I made an update recently because I was having trouble formatting coins expressed in scientific notation, it happens that I am now shown the thousand or group separator before being required. I observe that the same thing happens in the official demo, I have read the documentation in search of an option to regulate this behavior but I have not found anything. I attach an image indicating my difficulty. Thank you very much in advance.
![Screenshot_20191212_205733](https://user-images.githubusercontent.com/15002872/70761111-78bd8000-1d22-11ea-99ba-c07aa51835cf.png)

**Comment by RobinHerbots** [comment]
@yankielap 
That seems to be a new bug that slipped in.  I will try to fixed it asap.

Thx for reporting.

**Comment by RobinHerbots** [comment]
@yankielap , 

Fixed in version 5.0.1-beta.7
