### ISSUE TITLE
Backspace not removing characters in some cases

### ISSUE THREAD

**Issue by Evelyne28** [RobinHerbots/Inputmask#2246]
Hello :)
I've found an issue when trying to remove some characters using the Backspace key. In some cases it's not working at all.
I'm not sure if it's intended to be like this or not.

JSFiddle here: https://jsfiddle.net/bokmt3Lw/1/

For this example, if I would type in the first input 'abcd1234', then go after the character 'c' and press Backspace, nothing happens. Same goes when trying to remove 'a', 'b' or 'd'. I would expect it to look like this:  abd_-1234.
But if I would go after the digit '3' and press Backspace, this time it would work (value would look like this: abcd-124_)
The only way to remove the 'abcd' part is to position to the end of the string and press Backspace (remove everything character by character)

Second input works as expected. 

- OS: Windows 10
- Browser: Chrome Version 79.0.3945.79 (Official Build) (64-bit)
- Inputmask version: Version: 5.0.1-beta.7
https://rawgit.com/RobinHerbots/Inputmask/5.x/dist/jquery.inputmask.js

Thanks a lot!

**Comment by RobinHerbots** [comment]
@Evelyne28, 

Oh no, how did that slip in.

I will fix asap.
Thx for reporting

**Comment by Evelyne28** [comment]
Thanks a lot!

**Comment by Evelyne28** [comment]
I've updated the JsFiddle with another example: $(".testMask2").inputmask('aa-a{1,2}9{1,4}');
Here if the value would look like this: ab-cd1234, I am able to remove 'c' (will become ab-d1234), but not able to remove 'd' anymore. Also 'ab' characters cannot be removed as well. '1234' part works fine.

JsFiddle: https://jsfiddle.net/bokmt3Lw/2/

**Comment by RobinHerbots** [comment]
ok thx
