### ISSUE TITLE
Reinitialize mask is incorrect

### ISSUE THREAD

**Issue by ShurikEv** [RobinHerbots/Inputmask#2249]
When I reinitialize mask, text in input is invalid.
I need to conditionally change the behavior of the mask.

Example: https://jsfiddle.net/mr6Locn2/

In version 3.3.x it works

- OS: win10
- Browser: IE11, Chrome
- Inputmask version: 5.0.0

**Comment by ShurikEv** [comment]
https://jsfiddle.net/mr6Locn2/2/ - also works

**Comment by RobinHerbots** [comment]
@ShurikEv , 

Can you elaborate a bit more?  In version 5.0.0 there is a bug for iE11 which is fixed in version 5.0.1

**Comment by ShurikEv** [comment]
I use 5.0.1. A bug still exists

**Comment by ShurikEv** [comment]
I used inputmask('remove') - it's ok

**Comment by RobinHerbots** [comment]
@ShurikEv , 

When you remask the following code is  called

	if (maskset !== undefined) {
					if (el.inputmask !== undefined) {
						el.inputmask.opts.autoUnmask = true; //force autounmasking when remasking
						el.inputmask.remove();
					}

The unmasking causes the behavior, which needs enhancement.  
I will fix this for version 5.0.2

**Comment by RobinHerbots** [comment]
@ShurikEv , 

https://jsfiddle.net/sdrpwu2x/3/
