### ISSUE TITLE
Backspace does nothing on masked fields in Chrome

### ISSUE THREAD

**Issue by tslatt** [RobinHerbots/Inputmask#225]
In Chrome, any field that has masking on it won't allow me to hit backspace to delete the previous character or delete to delete the next character. I can put the cursor before the character I want to replace and type to replace it, but that is not intuitive to users. I downloaded the latest version of the scripts today, just to make sure the issue wasn't fixed already. Any idea what's going on? Any help would be greatly appreciated.

**Comment by RobinHerbots** [comment]
@tslatt ,

Can you provide more information.  The mask used etc.  I did a quick test in Chrome (Version 26.0.1410.64 m) and did not experience any trouble with the backspace.

**Comment by tslatt** [comment]
The form is in .Net. The Chrome version is 26.0.1410.64 m. One of the masks used, for example, is "99/99/9999" for a DOB. Unfortunately, this form is still in development, so I can't post a live example. Maybe you could give me a link to the working example you tested, so I can pass that on to the .Net developer to compare?

**Comment by tslatt** [comment]
Here's a little more info:

The form is written in .Net. One of the fields that this happens on is as follows:

<ax:MaskedEditExtender ID="meCustomerDob" TargetControlID="txtCustomerDOB" Mask="99/99/9999" AutoComplete="false" ClearMaskOnLostFocus="true" UserDateFormat="MonthDayYear" MaskType="Date" runat="server">/ax:MaskedEditExtender

Which renders as:

<input id="txtCustomerDOB" name="txtCustomerDOB" class="fieldMask hasOverLabel getValOnFocus" type="text" onblur="toggleMaskedLabels(this);">

The jquery initialization for this field is as follows:

$("input[name$='txtCustomerDOB']").inputmask("mm/dd/yyyy",{ //the mask
  "oncomplete": function(){ fieldMaskBlur($(this).attr("id"), "complete"); }, //if complete text was entered
  "onincomplete": function(){ fieldMaskBlur($(this).attr("id"), "incomplete"); }, //if incomplete text was entered
  "oncleared": function(){ fieldMaskBlur($(this).attr("id"), "cleared"); }, //if no text was entered
  "showMaskOnHover": false
});

Thank you so much for your quick response.

**Comment by tslatt** [comment]
Oops, the .net code and the html didn't render correctly in the comment. Not sure what to do about that.

**Comment by tslatt** [comment]
Here's an image of the code I was trying to put in the comment. Sorry.

![masking](https://f.cloud.github.com/assets/2651562/431375/01096328-ae87-11e2-8e47-146743bc74ad.png)

**Comment by tslatt** [comment]
Sorry, my .net developer worked on the issue some more, and it turns out the problem was with .net, NOT with the masking plugin. Thanks!
