### ISSUE TITLE
Question: Having a static "A" in the input mask without having it become an alphanumeric field

### ISSUE THREAD

**Issue by thomasjosif** [RobinHerbots/Inputmask#2251]
I had a look around but couldn't find any info on this.  I'm looking to create an input mask for Valve's Steam ID, and having an input mask like such: 
`$('[data-mask]').inputmask("STEAM_1:9:9{1,99}");`

Creates an input mask that looks like this: `STE_M_1:_:_` (because the A is getting detected as an alphanumeric mask)

What I really want is a mask that looks like this: `STEAM_1:_:_` (The first underscore is not a mask, rather part of the static STEAM_ text at the beginning of the ID)

If you need me to explain it further let me know.

Thanks :)

**Comment by RobinHerbots** [comment]
@thomasjosif, 

The A is defined in the definitions as an uppercase alphanumeric. You can solve this by double escaping the A 

$('[data-mask]').inputmask("STE\\\AM_1:9:9{1,99}");

**Comment by thomasjosif** [comment]
Works perfectly! Thanks Robin 👍

**Comment by rivasrus** [comment]
\\ not working

**Comment by rivasrus** [comment]
> @thomasjosif,
> 
> The A is defined in the definitions as an uppercase alphanumeric. You can solve this by double escaping the A
> 
> $('[data-mask]').inputmask("STE\\AM_1:9:9{1,99}");

`\\` not working

**Comment by thomasjosif** [comment]
> > @thomasjosif,
> > The A is defined in the definitions as an uppercase alphanumeric. You can solve this by double escaping the A
> > $('[data-mask]').inputmask("STE\AM_1:9:9{1,99}");
> 
> `\\` not working

This was over 2 years ago now, the library may have changed, or something else might be broken on your end.
I haven't touched this since then. The best bet would be looking if they changed their syntax.

**Comment by eguesbaya** [comment]
Hi, I am encoutering issues with " ", so I've tried escaping it using \ and \\ but none of them seem to make a difference.
I have tried with the following mask: '(999) 999-9999'
But when I try to enter '123456789', I get: (1__) ___-2345
Has anyone else experienced this?

**Comment by RobinHerbots** [comment]
@eguesbaya , 

Can you create an example on codepen or jsfiddle.  This should just work.
Inputmask("(999) 999-9999").mask(targetinput)

**Comment by eguesbaya** [comment]
> @eguesbaya ,
> 
> Can you create an example on codepen or jsfiddle. This should just work. Inputmask("(999) 999-9999").mask(targetinput)

Wow thank you so much for such a quick reply! It's a little tricky to reproduce a snippet as I work on a big Angular project, but my code looks something like this: https://codepen.io/eguesbaya/pen/XWyXZZX

**Comment by RobinHerbots** [comment]
Have a look at https://codepen.io/robinherbots/pen/wvQMmNM?editors=1111

**Comment by eguesbaya** [comment]
Thank you very much for taking the time to answer my question! The issue was linked to the Angular lifecycle, the mask is fine when instantiated in the class or in the constructor!

**Comment by khanfaysal** [comment]
![input-mask](https://github.com/user-attachments/assets/69d385f0-72b1-46a2-b634-5a06a31d4833)
I want to remove __ / __ horizontal two separate line means __ and  ___ only appear / . How to do this?
