### ISSUE TITLE
Input Mask restores old placeholder after changing it

### ISSUE THREAD

**Issue by ne3Vubeki** [RobinHerbots/Inputmask#2252]
Inputmask restores the old placeholder. I use inputmask 4.0.8 and Angular 8. Any browser. Element is `input`. After initializing the inputmask and placeholder by default, I change the placeholder to "", the placeholder is cleared, but when the `mouseleave` event fires in the input, the old placeholder is restored. This happens in the `inputmask.js`, inside the listener, when the variable `originalPlaceholder` is assigned, which is initialized only in the mask() method.
In previous versions, the inputmask was not assigned to the placeholder for the `mouseleave` event, and everything worked correctly
I could not find opportunities without initializing the inputmask to change the `originalPlaceholder`. Can you fix it?

**Comment by RobinHerbots** [comment]
@ne3Vubeki , 

I can make the originalPlaceholder available in the inputmask object?  So you can adjust the value.

**Comment by ne3Vubeki** [comment]
I think this would be a solution to the problem. Thanks!

**Comment by RobinHerbots** [comment]
@ne3Vubeki , 

Can you have a try with 5.0.4-beta.0

You will need to update the value or the originalplaceholder in input.inputmask.originalPlaceholder

**Comment by ne3Vubeki** [comment]
Unfortunately, version 5 does not work correctly for me. Can I make changes to version 4?
And yet, can I transfer corrections to the checkVal function from 5 to version 4?

**Comment by RobinHerbots** [comment]
@ne3Vubeki , 

What is not working correct in version 5?

**Comment by RobinHerbots** [comment]
I can also add an option to enforce to old behavior for the placeholder in version 5

**Comment by ne3Vubeki** [comment]
> @ne3Vubeki ,
> 
> What is not working correct in version 5?

This error was solved by my colleague. I can only say that with a digital mask you cannot enter more than one digit. So I rolled back to version 4.0.9. As soon as my colleague writes a bug report, I will give it to you. At the moment, I forked the library and transferred the corrections from version 5.
