### ISSUE TITLE
date.extensions incompatible with IE11

### ISSUE THREAD

**Issue by yevit** [RobinHerbots/Inputmask#2253]
Hi,

I've just tried updating to v5.0.1 but I'm having issues with IE11 which seems to be because the inputmask.date.extensions.js file contains ` `` ` characters now for string interpolation.

When I run the project I get the error `'":"SyntaxError: Invalid character\n   at ../inputmask/lib/extensions/inputmask.date.extensions.js '`

After rolling back to v4.0.9 it works fine.

**Comment by RobinHerbots** [comment]
@RichardTivey, 

You should use the files from the dist folder.

I will update the README

**Comment by yevit** [comment]
@RobinHerbots Thanks for the quick reply. 

I suspected that was the case and I was using the one in the dist folder in v4 but I think the inputmask.date.extensions.js file is missing from the dist folder in v5 - I don't seem to be able to find any of the extensions actually.

I'm using NPM

**Comment by darkadept** [comment]
I don't see any extensions in the dist folder either.

**Comment by RobinHerbots** [comment]
@rice2007 ,  @darkadept ,

The extensions are included in the inputmask.js or jquery.inputmask.js

No need to load the extension separately
