### ISSUE TITLE
Pasted value is getting mixed up

### ISSUE THREAD

**Issue by twoeyessoftware** [RobinHerbots/Inputmask#2255]
Hi Robin,
I whant the user to only enter the alias of an email adress. The '@' and the domainname should be fixed.

I'm using the following mask:
```
$('#test1').inputmask({
                mask: "*{1,64}[.*{1,64}][.*{1,64}][.*{1,63}]@\\d\\o\\m\\a\\i\\n\\n\\a\\m\\e\\.\\c\\o\\m"
            });
```

On tiping the alias into the TextBox it seems to be ok.
But when i paste something like 'contact' or 'info' into the TextBox the caracters will be mixed up od removed. The same Problem exists if a value was prefilled into the TextBox.

The result looks like this:
contact -> cntct@domainname.com
info -> if@domainname.com  

What can I do?
Thanks an best regards!
Roland

**Comment by RobinHerbots** [comment]
@twoeyessoftware, 

This is a regression.  I will see how to fix this.
