### ISSUE TITLE
jQuery.inputmask - swapped digits on paste with specific prefix

### ISSUE THREAD

**Issue by jurchiks** [RobinHerbots/Inputmask#2256]
Pasting into a masked input with the mask `+3719{8}`, if the pasted value starts with 27, the 2 is shifted to the end of the input (e.g. `27000000` is replaced with `70000002`). The same happens if the prefix is just `+37`, optionally with any fixed digits other than 2 after it. It's fixed if I remove the `+`, but it's a phone number, so not a great solution.

I've narrowed the bug down to this line: https://github.com/RobinHerbots/Inputmask/blob/5.0.2/lib/maskScope.js#L1863
It is at this point that the value becomes incorrect.

From my experiments, it looks like all values that start with `27` are affected, and it doesn't matter what follows, it will just put the `2` at the end. This is huge because we have over 16k users with phone numbers that start with `+37127...`.

Here's a fiddle to demonstrate: https://jsfiddle.net/jurchiks/uchqv5de/7/

- OS: Windows 10 Home 1903 build 18362.535
- Browser: Chrome 79.0.3945.117 (64-bit) and Firefox 73.0b3 (64-bit)
- Inputmask version: jquery, 5.0.2

**Comment by RobinHerbots** [comment]
#2255

**Comment by jurchiks** [comment]
@RobinHerbots doesn't seem to be the same, although I thought about it before making this.

**Comment by jurchiks** [comment]
Anyway, I've narrowed it down to a specific point in code: `isTemplateMatch` changes the `inputmask.caretPos.begin` to the incorrect index after the first digit, thus prepending instead of appending everything that follows `2`.

**Comment by jurchiks** [comment]
So, I cloned the repository and added a test for this case, but `npm test` doesn't run tests! It runs `grunt validate`, but the gruntfile contains no mention of tests at all. How do you run them?

**Comment by RobinHerbots** [comment]
@jurchiks , 

You need to run qunit.html in the qunit folder.

Anyway have a look at https://jsfiddle.net/md2goxhb/1/
I pushed a fix

**Comment by jurchiks** [comment]
Yep, works.

**Comment by jurchiks** [comment]
When could I reasonably expect a stable version?

**Comment by RobinHerbots** [comment]
Version 5.0.3 is a patch so very soon.  (After I fix #2255)

**Comment by jurchiks** [comment]
Awesome, thank you!
