### ISSUE TITLE
Decimal mask with maxlength turns integer into real number on maximum length

### ISSUE THREAD

**Issue by misostc** [RobinHerbots/Inputmask#2260]
- Describe the bug
Have an input with maximum length and decimal mask, with group separator

- Add a link to a codepen, jsfiddle or other example page which shows the problem
https://jsfiddle.net/4azov6ur/

- OS:
Ubuntu

- Browser
Chrome

- Inputmask version
5.0.3

**Comment by misostc** [comment]
[Gif of issue](http://i.imgur.com/h1UzHaN.mp4)

**Comment by RobinHerbots** [comment]
@misostc ,

Finally fixed!
