### ISSUE TITLE
decimal + prefix + groupSeparator + negative value = Maximum call stack size exceeded

### ISSUE THREAD

**Issue by thorn0** [RobinHerbots/Inputmask#2262]
Overall, `prefix` doesn't work well with negative values. 

Chrome 79.0.3945.117, Windows, Inputmask 5.0.3

**Steps to reproduce:**

1. Create a mask with this config: `{ alias: "decimal", prefix: '$', groupSeparator: "," }`, or just go to https://jsbin.com/nowoked/edit?html,js,output
2. Click on the input, so that it gets focused.
3. Press <kbd>-</kbd> (minus), <kbd>1</kbd>, <kbd>.</kbd> (dot), <kbd>2</kbd>.

**Actual results:**

1. The minus disappeared, the value of the input is `$1.2`.
2. Two errors in the console:

	```js
	inputmask.js:821 Uncaught RangeError: Maximum call stack size exceeded
		at resolveTestFromToken (inputmask.js:821)
		at handleMatch (inputmask.js:894)
		at resolveTestFromToken (inputmask.js:968)
		at handleMatch (inputmask.js:963)
		at handleMatch (inputmask.js:949)
		at resolveTestFromToken (inputmask.js:968)
		at getTests (inputmask.js:988)
		at getTestTemplate (inputmask.js:800)
		at getMaskTemplate (inputmask.js:756)
		at getBuffer (inputmask.js:1012)

	inputmask.js:882 Uncaught RangeError: Maximum call stack size exceeded
		at handleMatch (inputmask.js:882)
		at resolveTestFromToken (inputmask.js:968)
		at handleMatch (inputmask.js:894)
		at resolveTestFromToken (inputmask.js:968)
		at handleMatch (inputmask.js:963)
		at handleMatch (inputmask.js:949)
		at resolveTestFromToken (inputmask.js:968)
		at getTests (inputmask.js:988)
		at getTestTemplate (inputmask.js:800)
		at getMaskTemplate (inputmask.js:756)
	```

**Expected results:**

The value of the input should be `-$1.2`.

---

If we remove `groupSeparator` from the config, there is no errors, but the minus still disappears.

**Comment by RobinHerbots** [comment]
@thorn0 , 

The jsbin shows an email mask, which is not working.
I tried your mask locally with the latest build from git.  There seem to be no problem.
Can you review your example so I can see the error.

**Comment by thorn0** [comment]
Oh, sorry! https://jsbin.com/nowoked/edit?html,js,output

**Comment by RobinHerbots** [comment]
Ok, I see the problem.  I will fix this for v5.0.4.

**Comment by Rui-Nogaro** [comment]
@RobinHerbots  tested with version 5.0.4 and the problem keeps.

**Comment by RobinHerbots** [comment]
See #2476

**Comment by dresende** [comment]
This problem persists and sometimes it gives maximum call stack and other times it just removes the inserted value. I'm not sure what combination of options does it but what I can say is that if you use a prefix with a space and the group separator is a space, this doesn't work.

```js
{
    groupSeparator : " ",
    prefix : "€ ",
}
```

**Comment by RobinHerbots** [comment]
Merged in 5.x as f13732559 (PR #2882). The groupSeparator definition is now registered before prefix/suffix auto-escape, and the strip-negation-on-zero path matches the raw buffer — the 'Maximum call stack size exceeded' with decimal + prefix + groupSeparator + negative value no longer occurs. Covered by the isValid/format tests in qunit/tests_formatvalidate.js (#2262 rows).
