### ISSUE TITLE
Input mask alias doesn't works with dynamic masks

### ISSUE THREAD

**Issue by suvratsharma** [RobinHerbots/Inputmask#2264]
The below jsfiddle uses the latest in version 5 and as can be seen the decimal symbol(.) is not shown in field.
https://jsfiddle.net/1awcb2xL/

But it works in version 4 and below as show in below jsfiddle
https://jsfiddle.net/1wm9saht/

**Comment by RobinHerbots** [comment]
@suvratsharma , 

Don't combine an alias with a mask option.  Remove the alias and it will work.

**Comment by suvratsharma** [comment]
yeah, but I want to extend existing alias instead of creating a new one by copying all properties from numeric alias.
https://jsfiddle.net/64bmowtL/
It should work as per documentation and it used to work too in earlier versions.
Here is excerpt from documentation -
> However, the preferred way to alter properties for an alias is by creating a new alias which inherits from the default alias definition.
> 
> Inputmask.extendAliases({
>   'myNum': {
>     alias: "numeric",
>     placeholder: '',
>     allowPlus: false,
>     allowMinus: false
>   }
> });
> Once defined, you can call the alias by:
> Inputmask("myNum").mask(selector);

**Comment by RobinHerbots** [comment]
@suvratsharma , 

I agree but changing the mask itself is like changing the core element from the alias.  Most of the time the other options are set in function of the mask.  Altering the options is more in the context of defaults and behavior.
