### ISSUE TITLE
Double input event trigger

### ISSUE THREAD

**Issue by lowl11** [RobinHerbots/Inputmask#2265]
- Describe the bug:
If form submit triggers with event "input", on mobile devices form will be submitted twice. I upgraded inputmask version from 4.0.0. to 5.0.0 and you removed piece of code which fixed that problem (I guess). 
In EventRuler there is switch/case and in the case "input" removes piece of code starts with if (mobile)...

- JS Fiddle: https://jsfiddle.net/684uvbqp/

- OS: Android, IOS, Mobile browser

- Browser: Google Chrome 79.0.3945.130

- Inputmask version: 5.0.0

**Comment by RobinHerbots** [comment]
@Lowl11 , 

Can you workout a full example in jsfiddle.

**Comment by lowl11** [comment]
I cannot share with full example, I think part of code from library is enough

**Comment by RobinHerbots** [comment]
Yes, this is already fixed.
