### ISSUE TITLE
Apply max to numeric field as I type

### ISSUE THREAD

**Issue by Herz3h** [RobinHerbots/Inputmask#2268]
- Describe the bug

Using an input field and setting max value to this numeric input to 1000, the max value applies only when the blur event is triggered, not as I type the value..
- Add a link to a codepen, jsfiddle or other example page which shows the problem
https://jsfiddle.net/Luja13e5/
- OS:
Any OS
- Browser
Chrome 79
- Inputmask version
4.0.9

**Comment by RobinHerbots** [comment]
@Herz3h , 

Can you try the behavior of version 5

https://jsfiddle.net/fynt24g5/

**Comment by Herz3h** [comment]
It kinda works, if I type 123,00 then try to add any number after 3 it won't allow me.

Ideally it should round to the max value when input is beyond max value :)

Also, is there any upgrade path to v5 ?

**Comment by RobinHerbots** [comment]
@Herz3h , 

I can add an option for that behavior.  
For the upgrade path, ... best is to have a look at the changelog.  But most masks should work as before.

**Comment by Herz3h** [comment]
Would be neat !

Ok I'll check the changelog, ty for this awesome plugin :)
