### ISSUE TITLE
Angular reactive form Initial set value not masking properly in formcontrol

### ISSUE THREAD

**Issue by SabikAbtahee** [RobinHerbots/Inputmask#2270]
- There is a decimal in the reactive form formfield. If the radixpoint is set to "," then it does not show in the reactive form field for some reason.
- Link to stackblitz: https://stackblitz.com/edit/angular-pqjgpm
- OS: Windows 10 64 bit
- Chrome
- 5.0.3

**Comment by RobinHerbots** [comment]
@SabikAbtahee , 

There seem to be an error in your example

I removed  in appcomponent
ngOnInit() {
<strike> this.x();</strike>
    this.initForm();
  }

**Comment by RobinHerbots** [comment]
@SabikAbtahee , 

Also as you pass 555.6666 (notice . as radixPoint) you should add the inputType option

 inputType: "number",

**Comment by SabikAbtahee** [comment]
> @SabikAbtahee ,
> 
> Also as you pass 555.6666 (notice . as radixPoint) you should add the inputType option
> 
> inputType: "number",

If a g
