### ISSUE TITLE
Numeric field digitsOptional=false : positionCaretOnClick work fine but not positionCaretOnTab

### ISSUE THREAD

**Issue by philik** [RobinHerbots/Inputmask#2271]
My simple "euro" alias with  mandatory digits and comma digit separator.
euro : {
    alias: "numeric",
    groupSeparator: " ",
    digits: 2,
    digitsOptional: false,
    radixPoint: ','
}
**On an empty field** 
Focus with mouse click work fine.
But, when using TAB key from previous field, caret position is on the right end of field (ie :  0,00| ), not before the radix point (0|.00). So input is limited to digits.

Version: 5.0.4-beta.11

**Comment by RobinHerbots** [comment]
@philik , 

Can you retry with the latest 5.0.4-beta.22 as I cannot reproduce here.
Otherwise make a jsfiddle or codepen.

**Comment by philik** [comment]
Sorry, code error.
I found a conflict with another "focus" directive. No issue in InputMask.
