### ISSUE TITLE
24 hour format with 24:00 inclusive

### ISSUE THREAD

**Issue by RobinHerbots** [RobinHerbots/Inputmask#2272]
I need the user to enter from 00:00 to 24:00 but 23:59 is the max, I already try max: 25 and nothing, I'v tried this regex ^(((([0-1][0-9])|(2[0-3])):?[0-5][0-9])|(24:?00)), but doesn't work either. H2:00 not working too, is there a way I could use this regex? or any better solution?

_Originally posted by @SergioOrtiz4th in https://github.com/RobinHerbots/Inputmask/issues/1786#issuecomment-584756606_

**Comment by RobinHerbots** [comment]
@SergioOrtiz4th,

Can you have a try with version 5.0.4-beta.12

Inputmask("datetime", {
			inputFormat: "H2:MM",
			max: "24:00",
			placeholder: "HH:MM"
		}).mask(testmask);

**Comment by SergioOrtiz4th** [comment]
@RobinHerbots It works!, Thanks!!

**Comment by Quocnamit** [comment]
@RobinHerbots 

If I have inputFormat: 'dd/mm/yyyy H2:MM' and the max: "31/12/9999 24:00'. the max doesn't work for time part. do you have any idea on it
