### ISSUE TITLE
Unable to enter 4-digit years prior to 2000

### ISSUE THREAD

**Issue by EddyCwdry** [RobinHerbots/Inputmask#2275]
In the latest build of inputmask ( 5.0.4-beta.14) with a date mask ending in yyyy, the mask will turn an input of '19' into '2019' and not allow the user to enter a valid year starting in 19.

Fiddle - https://jsfiddle.net/t05hgem8/

Seems to happen across browsers and OS

**Comment by EddyCwdry** [comment]
It appears that this issue is due to the addition of the new 'min' property for date fields. Setting this does allow dates prior to 2000.

I think while this behavior is useful, the default behavior shouldn't assume a min date so close to the present, as it rolling to the latest version could break a large number of implementations in it's current state.

**Comment by RobinHerbots** [comment]
@EddyCwdry , 

I reverted the default mindate value.

Best regards, 
Robin
