### ISSUE TITLE
regex mask crashes for long input size

### ISSUE THREAD

**Issue by zhaken** [RobinHerbots/Inputmask#2276]
For simple text area if input size gets above certain number regex input mask crashes. I repeated it multiple times, unfortunately problem still persists. Here my code from .js file: 

let element = document.getElementById("textarea");

 let regexInputMask = new Inputmask({regex: "(\\+90-\\(\\d\\d\\d\\)-\\d\\d\\d-\\d\\d-\\d\\d)(," +
        " \\+90-\\(\\d\\d\\d\\)-\\d\\d\\d-\\d\\d-\\d\\d)*"});
regexInputMask.mask(element);

Please see the attachment for sample case.
![o36iw1USOI](https://user-images.githubusercontent.com/22324622/74815359-255f4380-530a-11ea-9651-9ddfc57e557a.png)

**Comment by RobinHerbots** [comment]
@zhaken , 

Can you have a try with the latest beta
