### ISSUE TITLE
Alternative for removed integerDigits property?

### ISSUE THREAD

**Issue by renanrfranca** [RobinHerbots/Inputmask#2278]
I'm not sure if this is the correct place to ask, apologies in advance if it isn't.

I'm trying to apply a mask where you can input up to 3 integer digits and 4 decimals (percentage), like so: "999,9999%". If I type 0 four times, I expect the input to ignore the last digit and display "000%", and if I type ',' I expect it to move to the decimal part of the mask and accept up to 4 additional digits.

Here's my attempt: https://jsfiddle.net/renanrfranca/5gu3ov8e/6/

So I've found that the "integerDigits" property while present in 4.x seems to have been removed, is there anything else I could use to that end?

I'm on Ubuntu/Firefox, inputmask 5.0.4-beta 8

**Comment by RobinHerbots** [comment]
@renanrfranca , 

You can the max option instead.

https://jsfiddle.net/oxy5b6ca/2/

But I see there is a bug when using a suffix and you insist typing 0 the mask continues in the decimals.

**Comment by RobinHerbots** [comment]
@renanrfranca , 

Fixed in 5.0.4-beta.26
