### ISSUE TITLE
Incorrect mask operation when deleting the value set through "value", "val", "setvalue".

### ISSUE THREAD

**Issue by KryukovDS** [RobinHerbots/Inputmask#2279]
- Describe the bug:

Mask example: '+7 (999) 999-99-99' and any similar, for example: '+\\972 (999) 999-99-99' 

The input mask behaves differently when printing a value from the keyboard and setting the value through the "value" attribute of the "input" tag, through "$ ('input'). Val ('...')", through "$ ('input' ) .inputmask ('setvalue', '...') ".

When setting the value in any way listed above, except for keyboard input, the mask does not disappear when the focus is lost after deleting the set value. And also the removal of the backspace button with the button does not occur on the placeholder of the mask, but on each literal.

- Add a link to a codepen, jsfiddle or other example page which shows the problem:

Detailed description with an example: https://jsfiddle.net/SinFx/d3zhv4nq/

- OS: Windows 10
- Browser: Chrome, Opera, IE and all
- Inputmask version: 5.0.3 - 5.0.4-beta.21

... Sorry for google translate.

**Comment by RobinHerbots** [comment]
@KryukovDS , 

Thx for the detailed issue.  I will see why the unmaskedvalue isn't handled the same and also the backspaces.  The masktemplates gets cleared on lost focus for me.

**Comment by KryukovDS** [comment]
@RobinHerbots, thanks for your work!

When I was compiling the example, the plugin version 5.0.4-beta.21 was connected, because the plugin is connected to the latest version (5.x) from via rawgit.com, now version 5.0.4-beta.22 is connected in the example. 

Now I observe the problem only with the fourth input, where the value was set via the input attribute "value =", the second and third inputs are working correctly. 

After entering numbers: http://joxi.ru/p273L4LcWNVvD2.jpg
After deleting the numbers: http://joxi.ru/n2YVzXzCZeK4EA.jpg

Also, all inputs, including the fourth, no longer have problems with the number of clicks on backspace.

**Comment by RobinHerbots** [comment]
@KryukovDS , 

Can you have a try with the latest beta version.

**Comment by KryukovDS** [comment]
@RobinHerbots, Thanks, it works!
