### ISSUE TITLE
Add Support for MinValue and MaxValue

### ISSUE THREAD

**Issue by WaltDaniels** [RobinHerbots/Inputmask#228]
Support for MinValue and MaxValue would be a nice addition to the numeric-based extensions.  For example, you may have a field the has a range entry of 1 - 24, it would be handy to be able to build that into the mask somehow.

**Comment by RobinHerbots** [comment]
#409 (duplicate issue)

**Comment by darkjedioverlord** [comment]
Has this been implemented?  If so, how is it used?

**Comment by RobinHerbots** [comment]
@darkjedioverlord , 

No not yet.

**Comment by RobinHerbots** [comment]
@WaltDaniels , 

I added min & max in the numeric alias.

Max is checked on the fly, the minvalue on blur.
