### ISSUE TITLE
Entry ban

### ISSUE THREAD

**Issue by iberk** [RobinHerbots/Inputmask#2280]
Hi! How to make a ban on entering the numbers 7 and 8 at the beginning of the mask?

**Comment by RobinHerbots** [comment]
@iberk ,

	Inputmask({
            regex: "[^78].*"}).mask("test4");

**Comment by iberk** [comment]
I use mask 8 (999) 999-9999 and if I use this regexp the mask disappears(

**Comment by RobinHerbots** [comment]
@iberk , 

The regex replaces the mask, ... 
What exactly do you want to archieve?

**Comment by iberk** [comment]
I live in Russia, users very often try to indicate the number 8 at the beginning of the number, and because of this, the number is displayed incorrectly. I am trying to make the user unable to set the first digit 8

**Comment by RobinHerbots** [comment]
@iberk , 

is 8 (812) 123-1234 a possible value?

is 8 (712) 123-1234 a possible value?

**Comment by RobinHerbots** [comment]
Maybe have a look at #2274.  That is a simular issue

**Comment by iberk** [comment]
> @iberk ,
> 
> is 8 (812) 123-1234 a possible value?
> 
> is 8 (712) 123-1234 a possible value?

no)

**Comment by RobinHerbots** [comment]
```
Inputmask({
	    mask: "8 (199) 999-9999",
            definitions: { 1 : { validator: "[0-69]" } }
	}).mask("test4");
```

**Comment by RobinHerbots** [comment]
Can this be closed?
