### ISSUE TITLE
RegEx \d for digit (instead of [0-9]) does not work

### ISSUE THREAD

**Issue by nivs1978** [RobinHerbots/Inputmask#2281]
I try to mask an input to accept only time in 24 hour format (only hours and minutes, no seconds). I use the following line of JavaScript (jQuery):
my_input.inputmask({ regex: '^([01]\d|2[0-3]):?([0-5]\d)$', insertMode: false });

but the 'd' characters tun up as the second digit in each group and not a 0 where you can type a number. It does not seem to support all RegEx. I also noticed some complaint that the or '|' character is not working either.

**Comment by RobinHerbots** [comment]
@nivs1978 , 

Try double escaping. '^([01]\\\d|2[0-3]):?([0-5]\\\d)$'

**Comment by nivs1978** [comment]
Thanks
