### ISSUE TITLE
DateTime mask validation issues and backspace problems

### ISSUE THREAD

**Issue by weisborg** [RobinHerbots/Inputmask#2283]
- Describe the bug: 
$("input.MyNoFutureDates").inputmask("datetime", { "clearIncomplete": true, "placeholder": "mm/dd/yyyy HH:MM", "inputFormat": "mm/dd/yyyy HH:MM", "min": "01/01/1753 00:00", "max": "03/03/2020 23:59" });

With version 4.0.6 there was a backspace problem (Looks like 2163 fixed it forcing insertMode and other stuff) where it would put a 0 (0d) in the day and a 1 (1m) in the month.  It wouldn't let the 1 get cleared and it would survive leaving the field and coming back, but could be cleared when coming back.

Version 5.0.4 seems to fix this, but now when typing it seems to make some broad assumptions-  Anything in the day is assumed to be less than 10, so if i intend to type 01/28 it will put in 01/02 as soon as I hit the 2 for 28.  I know validating a date as someone types must be really annoying since things like 2/29 would be valid this year, but not all others. There has always been a weird shifting that takes place and crosses mask char boundaries too when del/backspace were used making the problem even worse (Year characters shift to day, etc). Did something major change with the library where I need to change my definition?

- OS: Windows 10
- Browser: Chrome
- Inputmask version: 4.0.6 and 5.0.4

**Comment by RobinHerbots** [comment]
@weisborg , 

I created a jsfiddle with the latest version and see no problem.  Can you confirm.

https://jsfiddle.net/robinherbots/ca8kspLy/2/

**Comment by RobinHerbots** [comment]
Also see #2286 (fixed)

**Comment by weisborg** [comment]
Sorry it took so long to get back to you.  Fiddle works fine.  Testing to see what else is causing it.  Bootstrap was just upgraded on our site, and there is some dropdown.js file binding key and input events to it as well that could be causing problems.

**Comment by weisborg** [comment]
Just noticed you had a slightly newer version.  Updated to it along with fixing a casing issue in some other code and it is working now.  (I had a method that converts chars as they type to uppercase and keeps cursor position...this is a really dumb thing I know but our users have trouble finding shift keys, so with a lowercase placeholder I think it was in a loop trying to modify that or something since it stayed lowercase, but the insertmode changed).  Changed the placeholder to uppercase so it leaves it alone.  Closing issue since it seems to be working now.
