### ISSUE TITLE
Using min with alias integer not working correctly because of postValidation

### ISSUE THREAD

**Issue by AlexM1dn1ght** [RobinHerbots/Inputmask#2284]
This is something that works on version 4 but not 5. 

When using alias : integer and a min value, the mask does not allow to input a value which starts with digits under the min value.

So for example, if I have a min of 250, I cannot enter 1500 because as soon as I enter 15 the rest is blocked.

I have traced the problem to the postValidation function (line 2484 of the dist/inputmask.js file version 5.0.4-beta.27). For some reason the value is tested for each character entered. So as soon as the value of the input has at least the length of the min value, it is tested with a "lesser than" and of course the test fails.

Working 4.x version : https://jsfiddle.net/3Lgfrhce/
Broken 5.x version : https://jsfiddle.net/4vy6Lg8f/

Steps to reproduce : start entering the value 1500 in the input field. Version 4 allows "1500" but version 5 blocks after entering "15".

**Comment by RobinHerbots** [comment]
@AlexM1dn1ght , 

Fixed in Version: 5.0.4-beta.29

**Comment by AlexM1dn1ght** [comment]
Thank you for the quick fix! Really appreciated.
