### ISSUE TITLE
data-inputmask: Currency format

### ISSUE THREAD

**Issue by stojsins** [RobinHerbots/Inputmask#2293]
Hi. I'm new here, this is my first post.
Forgive me if I break some rule, please instruct me in the right way if I do so.

I'm using next field mask for currency field:
`data-inputmask:'alias' : 'currency' , 'prefix' : '€ '`
And I have currency in format
`€ 1,234,567.00`
Can I somehow change currency format to
`€ 1.234.567,00`

Thank you.

**Comment by RobinHerbots** [comment]
@stojsins, 

add the radixPoint option.
`data-inputmask:'alias' : 'currency' , 'prefix' : '€ ' , 'radixPoint' : ',' `

**Comment by stojsins** [comment]
@ RobinHerbots,
Thank you very much for support. It is fine now.
