### ISSUE TITLE
Assigning input.value results in incorrect unmaskedvalue() result

### ISSUE THREAD

**Issue by MaximBalaganskiy** [RobinHerbots/Inputmask#2294]
- Describe the bug
Assigning an unmasked string to the `input.value` results in an incorrect `unmaskedvalue()` result which contains the mask

- Add a link to a codepen, jsfiddle or other example page which shows the problem
https://jsfiddle.net/djfb72q6/2/

As far as I could trace, `generatedInput === undefined` for mask characters which triggers the following condition
https://github.com/RobinHerbots/Inputmask/blob/69cf0a550cb3322f757e980b864a51172481995c/lib/maskScope.js#L1928

- OS:
Windows 10

- Browser
Chrome

- Inputmask version
5.0.3

**Comment by mertasan** [comment]
I have the same problem. Same as **unmasked** value and **masked** value in 5.0.3 version.

But there is no problem in 5.0.1 version.

`<input type="text" id="kkno-mask" maxlength="19" autocomplete="new-password" data-parsley-no-focus data-parsley-group="kkdogrula" data-parsley-trigger-after-failure="null" data-parsley-kkartno required="" />`

```
element.inputmask({ 
    "mask": ["4999 9999 9999 9999", "5999 9999 9999 9999", "6999 9999 9999 9999", "3999 999999 99999"],
    "keepStatic": false,
    "greedy": false, 
    "placeholder": "_",
    "clearIncomplete": false,
    "autoUnmask": true,
    onUnMask: function(maskedValue, unmaskedValue, opts){
        return maskedValue.substr(0, 1)+""+unmaskedValue;
    }
    .....other lines......
});
```

Version 5.0.3 onUnMask results:
```
// maskedValue: 4999 9999 9999 9999
// unmaskedValue: 4999 9999 9999 9999
```

Version 5.0.1 onUnMask results:
```
// maskedValue: 4999 9999 9999 9999
// unmaskedValue: 4999999999999999
```

**Comment by MaximBalaganskiy** [comment]
Looks like this has been fixed since 5.0.5

**Comment by mertasan** [comment]
@MaximBalaganskiy i will test it. thank you.

**Comment by MaximBalaganskiy** [comment]
Not reproducable in 5.0.5
