### ISSUE TITLE
URL mask broken

### ISSUE THREAD

**Issue by toxpal** [RobinHerbots/Inputmask#2296]
Using the latest 5.x version of Inputmask + latest version of Chrome.

URL mask seems to be broken. No matter if I use input type="text" or input type="url", if I apply URL mask, field displays "**http//**" And this is where problems begin:

1. It should say **http://** (note that **:** is missing in Inputmask)

2. If I click the field, cursor gets focused right after **ht**, which doesn't make any sense.

3. I can't even fix URL by adding **:** manually because it only allows to enter symbols at the end of input mask, so my URL looks like http//: which is obviously invalid.

4. Not really a problem, but a suggestion - change default prefix from http to https because there are not many sites using http now, and all modern browsers display them as insecure by default, so even remaining webmasters migrate to https.

**Comment by RobinHerbots** [comment]
Hi @toxpal , 

I pushed an update with an updated  implementation for the url mask.

But I see still some problems, ...

Initially you get the \<caret>http;// 
- type: f    => ftp://\<caret>
- type: h    => http\<caret>://
  - type: s => https://\<caret>
  - type \<whatever> => https://\<whatever><caret>
- type \<whatever> = \<caret>http;//

If I set the https:// initially, ... how do I switch back to http://

**Comment by toxpal** [comment]
> If I set the https:// initially, ... how do I switch back to http://

I didn't think of that. So default "http://" is probably a better idea. Will test and let you know how URL works for me now.

**Comment by RobinHerbots** [comment]
@toxpal , 

Maybe you can reread my first comment as there was some info missing ;-)

**Comment by toxpal** [comment]
Seems to work fine for me. When I type whatever, I always get http(s)://whatever, no matter the caret position. In other words, caret doesn't jump before http like in your last example. Using the latest version of Vivaldi.

**Comment by RobinHerbots** [comment]
@toxpal , 

Can you try with this codepen  https://codepen.io/robinherbots/pen/GRZKzZV

**Comment by toxpal** [comment]
Sure. Still the same - caret is always promptly placed at the end of URL (after ://). Tested with Firefox too; works the same way, which is fine for me.
