### ISSUE TITLE
Option to make placeholder always visible

### ISSUE THREAD

**Issue by datimson** [RobinHerbots/Inputmask#23]
I'd like to have the placeholder visible even when mouse hover = false so that it is more intuitive for users particularly on touch devices that don't have mouse hover.

**Comment by RobinHerbots** [comment]
I know I should update the documentation (and I will on release 1)

You can use the option clearMaskOnLostFocus and put it on false
ex: $(input).inputmask("9999", { clearMaskOnLostFocus: false });  

You can also change the defaults.

$.extend($.inputmask.defaults, {
    clearMaskOnLostFocus: false
});

Robin
