### ISSUE TITLE
Date inputmask cannot be typed over

### ISSUE THREAD

**Issue by 1madkins** [RobinHerbots/Inputmask#230]
I downloaded all the files and integrated them into my development website. All the inputmasks seem to work perfectly except for dates. I have tried
$("#date").inputmask("m/d/y");
$("#date").inputmask({"mask": "mm/dd/yyyy"});
and many others. In every case, the textbox shows the mask, but you cannot type anything in.
![capture](https://f.cloud.github.com/assets/4306313/449295/370361a0-b26e-11e2-979f-c1860c4ab7ce.png)

**Comment by 1madkins** [comment]
Scratch that. There was a reference in my application to another inputmask function that I was trying out.

**Comment by 1madkins** [comment]
Well, I though I got it working, but I guess not. I created the following barebones page and it exhibits the same behavior. The SSN field woks properly, but you can't type over the mm/dd/yyyy in the Birthdate field.

```
<script src="http://code.jquery.com/jquery-latest.js"></script>
<script src="js/jquery.inputmask.js"></script>

<script>
    $(document).ready(function(){  
        $("#SSN").inputmask({"mask": "999-99-9999"});
        $("#Birthdate").inputmask({"mask": "mm/dd/yyyy"});
    });
</script>

<label for="SSN">SSN</label><input type="text" id="SSN" name="SSN" value=""/><br/>
<label for="Birthdate">DOB</label><input type="text" id="Birthdate" name="Birthdate" value=""/>
```

**Comment by RobinHerbots** [comment]
@1madkins ,
Huh?  I thought I already answered this.

anyway, you have to include the date extensions to use the date masking.  Or use the jquery.inputmask.bundle.js in the dist folder.

use   $("#Birthdate").inputmask("mm/dd/yyyy");

**Comment by 1madkins** [comment]
Grrr! That was one of the many things I tried, but I had put it before the main script. After I swapped them it worked perfectly. Thank you so much!
