### ISSUE TITLE
'integer' mask uses last maxlength for all inputs

### ISSUE THREAD

**Issue by WaltDaniels** [RobinHerbots/Inputmask#231]
Using .inputmask('integer') to apply a mask on multiple input controls uses the length of the last control for all controls.

HTML:

```
    <input id="testInput" class="maskinteger" maxlength="4" />
    <input id="testInput2" class="maskinteger" maxlength="2" />
```

Non-working Script:

```
    <script>
        $(document).ready(function () {
            $('.maskinteger').inputmask('integer');
        });
    </script>
```

Working Script:

```
    <script>
        $(document).ready(function () {
            $('.maskinteger').each(function () {
                $(this).inputmask('integer');
            });
        });
    </script>
```

I have not tried this with any other mask aliases, but assume that they have issues as well.

**Comment by RobinHerbots** [comment]
@WaltDaniels, 

I will have a look at it , but I first have to stabilize the 2.x base, because the changes for the optional and multimask have some problems.

**Comment by RobinHerbots** [comment]
@WaltDaniels , 

The latest version should fix this.  Can you have a test.

best regards, 

Robin
