### ISSUE TITLE
Placeholder color

### ISSUE THREAD

**Issue by andreaguru** [RobinHerbots/Inputmask#2310]
Hi Robin, I know that the topic has been discussed some years ago, but currently I am still facing this issue: how can I change the color of the placeholder? 
I do not see the option colormask anymore in the code.

Thanks

**Comment by RobinHerbots** [comment]
@andreaguru , 

The option is removed.  When there is enough interest, I can add the option back at a later time.

**Comment by andreaguru** [comment]
ok, thanks. I would like to mention another small issue, here how to reproduce it:
1) use a date mask and write a date, e.g. "01.01.2000"m placeholder used is DD.MM.YYYY
2) start deleting the part "01.01" from the end

The result is that the mask shows 02.0M.000Y

Is it a knows issue?

Thanks

**Comment by fcojgodoy** [comment]
@andreaguru, can you try [::placeholder](https://developer.mozilla.org/en-US/docs/Web/CSS/::placeholder)

**Comment by Andrew-Marks-Trisept** [comment]
Count me as interested, I guess.

This was the first thing I noticed and wished was there when implementing a date input with masking.  I think for a lot of inputs, like phone number or currency, it's not really needed.  But for dates, you don't want it to just have underscores or empty space between the separators, you want it to say something like "MM/DD/YYYY".  But if it's all the main text color, at a glance it looks like the input is already filled in.  Maybe `::placeholder` would help with the initial display, but ideally the text would turn from grey to black as the user typed.

Looks like this has come up a few times.  I'm curious why it was removed.

Thanks

**Comment by jingfee** [comment]
I would also like to sign up as interested in having this feature back.

**Comment by stepanjakl** [comment]
Please re-implement the color mask option 🙏

**Comment by RobinHerbots** [comment]
#972

**Comment by RobinHerbots** [comment]
Colormask is rising from the ashes :-)

**Comment by skyndfly** [comment]
@RobinHerbots Hello, does it mean that the ability to change the color of the filler will appear soon?

**Comment by RobinHerbots** [comment]
Yes

**Comment by skyndfly** [comment]
@RobinHerbots great news. Thank you!

**Comment by RobinHerbots** [comment]
Still work in progress, but you can have a try by including the colormask.js instead of inputmask.js and use colormask with the same options as inputmask.  Also load the colormask.css which you can tune and use to change the colors. 
Suggestions for optimizing the css are always welcome.
