### ISSUE TITLE
mask on dynamic elements

### ISSUE THREAD

**Issue by iamszt** [RobinHerbots/Inputmask#2314]
i have created a textbox using jquery but the mask is not working on. my code is 

$("body").append(`<input data-inputmask-alias="datetime" data-inputmask-inputformat="dd/mm/yyyy" inputmode="numeric">`)

**Comment by RobinHerbots** [comment]
@iamszt , 

Once you add the element to the dom you need to call the Inputmask function on it.

$(select your newly added element).inputmask();

**Comment by iamszt** [comment]
thanks
problem solved
