### ISSUE TITLE
unmask regression?

### ISSUE THREAD

**Issue by ilplotkin** [RobinHerbots/Inputmask#2315]
Looks like regression in `unmask` starting from 5.0.2?
```
Inputmask.unmask('(123)456-78-90', '(999)999-99-99'); // '1234567890'    in 5.0.1
Inputmask.unmask('(123)456-78-90', '(999)999-99-99'); // '123)456-78-90' in 5.0.2 and up
```

**Comment by PedT** [comment]
I'm having the exact same problem. When the field i'm using a mask with comes pre-filled as the page loads, the unmask function does not work properly.

But if I clear the field and type in manually, the unmask function works properly.

**Comment by RobinHerbots** [comment]
@ilplotkin , @PedT , 

The unmask is more intelligent but not what most users/devs expect.  I will change the behavior so that it returns the value as before.

**Comment by RobinHerbots** [comment]
@ilplotkin ,, @PedT , 
Can you have a try with the latest vesrion on github.

**Comment by ilplotkin** [comment]
@RobinHerbots 
In 5.0.4-beta.38, it works as expected.
Thank you very much.
