### ISSUE TITLE
Some characters from cyrillic input not working?

### ISSUE THREAD

**Issue by elgolondrino** [RobinHerbots/Inputmask#2316]
$('.cyr').inputmask({
        regex: "^[аАбБвВгГдДеЕёЁжЖзЗиИйЙкКлЛмМнНоОпПрРсСтТуУфФхХцЦчЧшШщЩъЪыЫьЬэЭюЮяЯ]+$"
            });

NOT WORKING characters [бюжэхъ]. When typed they are removed

**Comment by elgolondrino** [comment]
Hey. is there anybody?

**Comment by brandshopru** [comment]
I have the same problem(
iOS Safari
