### ISSUE TITLE
Money mask problem for 3 digital numbers

### ISSUE THREAD

**Issue by pietrach** [RobinHerbots/Inputmask#2317]
I have a problem with formatting money numbers when edit existing record.
For example:
- for number 1.01 in input appears 0.10
- for number 10.01 is ok

**Comment by RobinHerbots** [comment]
@pietrach , 

Can you provide a jsfiddle or codepen.  

Also which version are you using?

**Comment by pietrach** [comment]
@RobinHerbots The topic is no longer valid. Everything is ok now.
