### ISSUE TITLE
How to create a new phone (HU) definitions?

### ISSUE THREAD

**Issue by mrpamacs** [RobinHerbots/Inputmask#232]
Hi

Can you help me in the following regular expression that could be validated in the plugin?

"/^(([2-9][0-9])-([0-9]{3}-[0-9]{3}))|((1|30|20|70)-([0-9]{3}-[0-9]{4}))$/"

Examples of acceptable samples:
1-123-4562
20-222-2222
22-222-234

Thx

**Comment by RobinHerbots** [comment]
@mrpamacs, 

I started to write a little tutorial for this in the wiki, but I haven't found the time to finish it.
I am busy fixing the plugin for multiple and optional masks.  After that I will have a look at this.

You can already start to split up the regex.

best regards, 

Robin

**Comment by RobinHerbots** [comment]
@mrpamacs, 

The entry in the wiki is finished.

Anyway, this regex is an interesting test case for the regex extension.
So I will use this one to further enhance the regex extension implementation.

best regards, 

Robin

**Comment by RobinHerbots** [comment]
@mrpamacs , 

I don't know if you are still following this but you can use

$("#testmask").inputmask("Regex", { regex: "(([2-9][0-9])-([0-9]{3}-[0-9]{3}))|((1|30|20|70)-([0-9]{3}-[0-9]{4}))" });

To restrict the input.  But in this case there is no visible masking. (only restriction).
