### ISSUE TITLE
What is the purpose of displayFormat ?

### ISSUE THREAD

**Issue by gelambert** [RobinHerbots/Inputmask#2324]
[The doc states](https://github.com/RobinHerbots/Inputmask/blob/5.x/README_date.md#displayformat) :
> Visual format when the input looses focus

Is it supposed to work ?
I checked the source code of [inputmask.date.extensions.js](https://github.com/RobinHerbots/Inputmask/blob/5.x/lib/extensions/inputmask.date.extensions.js) and it appears to me that this option is currently ignored.

Thanks for your help !

**Comment by RobinHerbots** [comment]
@gelambert , 

No it is not yet implemented.  The purpose.  Ex while editing you show  23/03/2020, while when you leave the field you show 23 March 2020

**Comment by gelambert** [comment]
@RobinHerbots ,

Understood. Thanks for your quick answer !
