### ISSUE TITLE
Why does mask characters appear before the set position

### ISSUE THREAD

**Issue by sampathkumarm** [RobinHerbots/Inputmask#2325]
For example, if i have a mask 99/99/9999 and when i start inputting values in the field it adds '//' before even completing set inputs. That means the first slash should appear only after entering 2nd value and the second slash after entering the 4th value in the input field. Also after deleting the slash stays until it the focus is gone from the element.

My simple setting is:
```
$('#dob').inputmask({
  placeholder: '',
  mask: '99/99/9999',
  showMaskOnFocus: false,
  showMaskOnHover: false,
  jitMasking: true,
});  
```
![image](https://user-images.githubusercontent.com/6489309/81994095-f4866600-95fb-11ea-80b5-949cf32317ad.png)

Please suggest a fix, client does not want to see the mask characters until the position is reached.

**Comment by ramgaikar** [comment]
Hey, I am also looking for similar solution.
`Inputmask('*** - *** - ***')`

For this mask, When I enter 1 char, I see mask characters, which I dont want.

<img width="380" alt="Screenshot 2020-05-21 at 7 18 03 PM" src="https://user-images.githubusercontent.com/13679778/82565332-ddb1b780-9b97-11ea-8f70-0214462d3906.png">

Please sugest a fix @RobinHerbots

**Comment by sampathkumarm** [comment]
Is this even possible or do we need to look for another library? Please suggest as this needs to be fixed by the next release that’s on 06/04 @RobinHerbots

**Comment by RobinHerbots** [comment]
Hi @sampathkumarm , @ramgaikar ,

I made an example in https://codepen.io/robinherbots/pen/GRpLwMM

What exactly do you expect different?

**Comment by ramgaikar** [comment]
> Hi @sampathkumarm , @ramgaikar ,
> 
> I made an example in https://codepen.io/robinherbots/pen/GRpLwMM
> 
> What exactly do you expect different?

Hey,
Awesome. Thanks. Didn't knew about jitmasking option. Thanks a ton

**Comment by sampathkumarm** [comment]
> Hi @sampathkumarm , @ramgaikar ,
> 
> I made an example in https://codepen.io/robinherbots/pen/GRpLwMM
> 
> What exactly do you expect different?

OMG, I am really sorry. I know why it was not working even though you see I have '**jitMasking**' enabled in my code. The issue is I have been using 2 versions of this library (3.2-3.9 and 5.04). It's my bad.

@RobinHerbots, I know this is a really dumb question but can we use both versions without affecting each other?

Thanks for your reply @RobinHerbots

**Comment by sampathkumarm** [comment]
Not a library issue, instead issue was cause of using multiple versions.
