### ISSUE TITLE
Removing the negative sign isn't triggering an onChange

### ISSUE THREAD

**Issue by matheusml** [RobinHerbots/Inputmask#2337]
It's important to mention that I'm using React.
When you:
- Type a negative number, in a number mask
- Go to the negative sign, and backspace it
- In the input, the value will be shown properly, but that didn't trigged an `onChange` event, so the value won't change

![ezgif-4-1d4c30b7afda](https://user-images.githubusercontent.com/444202/84276547-d3d10380-ab08-11ea-9140-a1c700b6ca2b.gif)

- Here's a codepen: https://codesandbox.io/s/gracious-rgb-2xe9i?file=/src/App.js:335-414
- OS: MacOS
- Browser: Chrome
- Inputmask version: 5.0.3

**Comment by RobinHerbots** [comment]
@matheusml ,

Can you have a try with the latest version
