### ISSUE TITLE
Grouping integer

### ISSUE THREAD

**Issue by gdesjonqueres** [RobinHerbots/Inputmask#234]
Hi,

I have an input text field which content is an integer, I need to group every three digits like this: 1000000 => 1 000 000,
I'm using the following code:

$(document).ready(function() {
$("#quantity").val(25278500);
$("#quantity").inputmask("integer", {autoGroup: true, groupSeparator: " ", groupSize: 3, rightAlignNumerics: false});
alert($("#number").inputmask('unmaskedvalue'));
}

My number doesn't get formatted when I load the page but only as I start typing in the input field.
I still get the masked value when calling .inputmask('unmaskedvalue')

Thanks, if you could have a look

**Comment by RobinHerbots** [comment]
@gdesjonqueres , 

This will be fixed in the next release.  

best regards, 

Robin

**Comment by RobinHerbots** [comment]
@gdesjonqueres ,

Check with the latest version.

Best regards, 

Robin
