### ISSUE TITLE
JQMigrate issue

### ISSUE THREAD

**Issue by SteveDavis-82** [RobinHerbots/Inputmask#2349]
JQMigrate shows warnings for items like $.isFuction() and $.isArray()

I realize the library itself doesn't have an issue, due to the existence of the dependency lib which will provide a substitution when the methods are actually removed from Jquery - However, implementing it this way causes problems for teams updating to the newest jquery as JQMigrate only shows the first instance of a given warning.  This means InputMask can mask issues during the migration process in other libraries and code.

Rather than using the dependency lib for this purpose, native JS code should be used to prevent interference with Jquery migration efforts.

**Comment by RobinHerbots** [comment]
Hi @SteveDavis-TR , 

Thx for the heads up and accompanied PR.
