### ISSUE TITLE
Using "decimal" mask

### ISSUE THREAD

**Issue by pkkini** [RobinHerbots/Inputmask#235]
Hello,
I have a requirement which needs me to use the decimal mask and at the same time display a "%" at the end of the number.

e.g. initial focus will display % only. When the user types -14.67, it should show -14.67%.

Is this possible?

Thanks in advance.

**Comment by RobinHerbots** [comment]
@kodak57 , 

In the current implementation of decimals this is not possible.  But I will implement this in milestone 2.4.

For the moment put the percentage after the input field.

best regards, 

Robin

**Comment by pkkini** [comment]
Robin,
Thanks for the quick reply. I have tried using the mask "9[9].9[9]%" to solve this problem. The only thing missing from this is that negative values are not allowed. Is there any change that can be applied to this mask to allow negative values?

Thanks agan.

**Comment by RobinHerbots** [comment]
@kodak57 

 "[-]9[9].9[9]%"

**Comment by mtomas-mpm** [comment]
Have you implemented the percentage mask yet? Have you plans for it?
In version 2.5.8 I've seen a "todo" in the suffix field of "decimal" mask, it could be enough for me. 

For the moment I'm using your proposed mask ("[-]9[9].9[9]%") but I'm interested too in manage the percentage value as base1. So show it multiplying by 100 and getting value dividing by 100. To get the value I can use unmaskedvalue method with the onUnMaskValue callback, but is there any "automatic" way to set the value multiplied by 100? Exploring plugin I've found onBeforeMask callback but it's not called when i set the value throug val() method of jQuery... any ideas?

Thanks

**Comment by RobinHerbots** [comment]
sufixes and prefixes are now supported by the numeric alias
