### ISSUE TITLE
jQuery version fails entirely in noConflict mode

### ISSUE THREAD

**Issue by smerriman** [RobinHerbots/Inputmask#2352]
https://jsfiddle.net/esv4ohLk/

When jQuery is in noConflict mode (which is, eg, always the case in WordPress), the script doesn't work at all. Standard practice for all jQuery plugins to include a wrapper, and this doesn't:

```
(function( $ ) {

})( jQuery );
```

**Comment by RobinHerbots** [comment]
@smerriman , 

It is not the jQuery.noconflict which is the problem but more like described in #2349 .

Anyway it is fixed in the latest version.
