### ISSUE TITLE
Minimum jQuery version?

### ISSUE THREAD

**Issue by MikeRich88** [RobinHerbots/Inputmask#2355]
What is the minimum jQuery version supported? This is not actually defined anywhere that I can find.

My site is using the last jQuery 1.x version. If that version is not supported, then will the full non-dependency version of Inputmask work fine?

**Comment by MikeRich88** [comment]
I can report that 1.x works fine.

**Comment by Healyhatman** [comment]
> Inputmask is a javascript library which creates an input mask. Inputmask can run against vanilla javascript, jQuery and jqlite.

jQuery isn't required at all :) If this is no longer an issue remember to close it

**Comment by MikeRich88** [comment]
> > Inputmask is a javascript library which creates an input mask. Inputmask can run against vanilla javascript, jQuery and jqlite.
> 
> jQuery isn't required at all :) If this is no longer an issue remember to close it

Of course, but, if I am already using jQuery for other reasons, then I can use the smaller version of Inputmask.

Although now that I look at it, jquery.inputmask.min.js is only about 3 KB smaller than inputmask.min.js.

Oh well. Thanks either way, we are using this to good effect with a phone number input form, invalid phone number submissions have fallen since implementing this solution.

**Comment by RobinHerbots** [comment]
Hi @MikeRich88 , 

I think jQuery 1.4 is the minimum, when using jQuery as dependency.
