### ISSUE TITLE
Reset Definitions

### ISSUE THREAD

**Issue by blasss** [RobinHerbots/Inputmask#2361]
I would like to setup a set of definitions from scratch, as I require to model another "mask language".
Is it possible to reset the initial definitions?
I already realized that a already defined masksymbol can be overwritten by simply redefining it with the empty string. But this only helps if you know all definitions. If you need to define a masksymbol with different options, you inherently get all previously defined options for this masksymbol.

**Comment by RobinHerbots** [comment]
@blasss , 

If I understand correctly, you want to disable the definition inheritance.

**Comment by RobinHerbots** [comment]
@blasss , 

Ok, I can add an option  usePrototypeDefinitions with a default true to reflect the current behavior.  Set this option to false to disable this.

What do you think?

**Comment by blasss** [comment]
Sorry for this late reply, but I've been on vacation for the last two weeks.
The implemented option is exactly what I need and I'm confident that this will fulfill my requirements.
Thanks for your fast and solid help.
