### ISSUE TITLE
No version data in latest build

### ISSUE THREAD

**Issue by toxpal** [RobinHerbots/Inputmask#2364]
Not sure how long this issue exists (my recent download of this package was a few months ago), but I noticed latest build has basic information (years, version, etc.) missing. See https://github.com/RobinHerbots/Inputmask/blob/5.x/dist/jquery.inputmask.min.js for yourself, it displays:

 * dist/jquery.inputmask.min
 * **<%= pkg.homepage %>**
 * Copyright (c) 2010 - **<%= grunt.template.today('yyyy') %> <%= pkg.author.name %>**
 * Licensed under the **<%= pkg.license %>** license
 * Version: **<%= pkg.version %>**

**Comment by RobinHerbots** [comment]
@toxpal, 

Fixed!

Thx!
