### ISSUE TITLE
inputmask no longer a function

### ISSUE THREAD

**Issue by weisborg** [RobinHerbots/Inputmask#2366]
What happened between 5.0.4 beta 37 and beta 54?  Existing code no longer runs saying $(...).inputmask(...) is not a function.  I've tried both inputmask.js and jquery.inputmask.js.  When I first started using the library it was called jquery.inputmask.bundle.js because there was a jquery.inputmask.js and additional masks and it had them all.  The naming has become a little confusing, but I'm guessing the one without jquery is for node or something.

**Comment by RobinHerbots** [comment]
@weisborg, 

Fixed.

Some trouble with es6 imports.
