### ISSUE TITLE
Dependency error

### ISSUE THREAD

**Issue by tabuna** [RobinHerbots/Inputmask#2368]
Hi, thanks for your hard work.

After updating `5.0.4` I get the error:
>  ERROR  Failed to compile with 1 errors                                                                                                                                      11:33:52 AM
> 
> This dependency was not found:
> 
> * jqlite in ./node_modules/inputmask/dist/inputmask.js
> 

At the same time, if you downgrade to `5.0.3`, then everything is fine.

**Comment by RobinHerbots** [comment]
Can you give an example of how you import thé library?

Op vr 7 aug. 2020 10:39 schreef Alexandr Chernyaev <notifications@github.com

**Comment by tabuna** [comment]
Like this:
> import Inputmask from 'inputmask';

**Comment by RobinHerbots** [comment]
@tabuna , 

It should be fixed now.  v5.0.5

**Comment by tabuna** [comment]
Yes, it works now. thank
