### ISSUE TITLE
inputmask datetime initialization defaulting month to 02

### ISSUE THREAD

**Issue by GitHansel** [RobinHerbots/Inputmask#237]
Chrome/Firefox:
$("#time").inputmask("datetime");
$("#time").val(new Date(Date.parse("09/09/2013")));

The above code shows 09/02/2013 00:00.  If given:

$("#time").inputmask("datetime");
$("#time").val(new Date()); //today's date is May 19, 2013 21:39

Shows: 19/02/2013 21:39

IE9 does not show the initialized date at all.

**Comment by RobinHerbots** [comment]
@GitHansel ,

I will have a look at it as soon the the dev branch is ready for a new 2.x release.

best regards, 

Robin

**Comment by RobinHerbots** [comment]
@GitHansel, 

It will depend on the culture used.  The datetime alias uses dd/mm/yyyy hh:mm as mask.  
Robin
