### ISSUE TITLE
Inputmask.remove(document.getElementById(selector)) is not working in Node after version 5.0.5 update

### ISSUE THREAD

**Issue by lossantis** [RobinHerbots/Inputmask#2373]
- Describe the bug

The "Inputmask.remove(document.getElementById(selector))" was working normally in my node application, but in the version 5.0.5  it is returning the error:

`Uncaught TypeError: Cannot read property 'dependencyLib' of undefined at HTMLInputElement.ev (inputmask.js:1479)`

This error is occurring only in the Node library.

- OS: Linux
- Browser: Chrome
- Input mask version: 5.0.5 (Node Library)

**Comment by RobinHerbots** [comment]
@lossantis, 

Can you try with version 5.0.6-beta.6

Can you provide some context.  By node library, you mean using it as a module?

**Comment by lossantis** [comment]
This specific issue was fixed in the beta version. Thanks.

But, after to remove, it's showing a new issue:

```
Uncaught TypeError: Cannot read property 'split' of undefined
    at DependencyLib.off (inputmask.js:1748)
    at HTMLInputElement.ev (inputmask.js:1482)
```

Answering your questions, "Can you provide some context. By node library, you mean using it as a module?", I'm importing your library inside a JQuery Plugin, using requires.

**Comment by RobinHerbots** [comment]
@lossantis , 

Can you provide some example code to get the Cannot read property split of undefined.

Thx

**Comment by lossantis** [comment]
I've created a JQuery Plugin, like this:

```
   Plugin.prototype._addMask = function () {
        try {
            Inputmask(this.options).mask(this.element);
        } catch (error) {
            console.log('Unable to add mask');
        }
    };

    Plugin.prototype._removeMask = function () {
        const unmaskedValue = this.element.inputmask.unmaskedvalue();

        if (unmaskedValue === undefined) {
            return;
        }

        Inputmask.remove(this.element);
        $(this.element).val(unmaskedValue);
    };
```
I use `_addMask` when I create de element, and the `_removeMask` while submitting the form. If I have a validation error in the submit, I add the mask again.

**Comment by RobinHerbots** [comment]
@lossantis , 

Can you also share your submit code.
