### ISSUE TITLE
v5.0.5+ breaks stuff

### ISSUE THREAD

**Issue by toxpal** [RobinHerbots/Inputmask#2374]
I know I submitted a lot of issues in the past, and I was always trying to provide as much details as possible, but I believe this report will be the most useless... Because I don't even know what is wrong this time.

After upgrading to 5.0.5 yesterday, I started receiving dozens of complaints that some parts of web app stopped working. To be more specific - users can't submit some forms (after they click submit button, nothing happens). So after debugging, I found that only forms with Inputmask placeholders can't be submitted. No errors in console, everything seems to work fine, except that submit buttons don't work...

So I did my best to debug the issue, and found that forms start working instantly after I remove this part from input field:

`data-inputmask="'alias':'datetime','inputformat':'HH:MM'"`

No issues happen with other masks (for example, `data-inputmask="'alias':'datetime','inputformat':'yyyy-mm-dd'"` works fine). The same issue exists in latest 5.0.6 beta as well.

The previous version I used in my app was 5.0.4-beta.35, which worked fine.

**Comment by RobinHerbots** [comment]
@toxpal, Can I see that somewhere happen on a live site? or test site?

Did you also try with Version: 5.0.6-beta.6

**Comment by toxpal** [comment]
Yes, it also happens with 5.0.6-beta.6

It's a custom client management system used internally by my employees, but I will try to do my best to setup a similar test environment within next few weeks (hopefully a bit sooner if I manage to get all the essential work done)

**Comment by rapidclarity** [comment]
I have experienced a similar situation, but perhaps I can shed some light.  **InputMask v5.05** causes Internet Explorer to break because InputMask is now using the **.includes** function which is not supported in all browsers.
See:  [https://stackoverflow.com/questions/31340868/includes-not-working-in-all-browsers/31340895](https://stackoverflow.com/questions/31340868/includes-not-working-in-all-browsers/31340895)
Perhaps this will help in this issue.

**Comment by toxpal** [comment]
In my case, it was with latest versions of Firefox and Vivaldi. 

What sucks a lot is that I can't reproduce the issue by creating a simple form. My app uses many other JS/Jquery elements (like datatables, moment, and so on) and it only happens on some forms. Since I couldn't share my custom CMS with public, I'm still trying to find what exactly causes this break.

**Comment by toxpal** [comment]
Just downloaded 5.0.6-beta.15 and everything seems to be OK again.
