### ISSUE TITLE
Minified version of input mask breaks Webpack / Terser minification. Error "$" is redeclared

### ISSUE THREAD

**Issue by Pete-PlaytimeSolutions** [RobinHerbots/Inputmask#2377]
- After upgrading InputMask v5.0.3 - v 5.0.5, when using input mask in an Angular 9/10 project(s), on compiling with "ng build --prod", which used Terser as the minification package, the build fails with error 
    "$" is redeclared

There seems to be an issue with a toplevel "$(" function, (in the minified code) that clashed with other libraries such as Jquery, etc.

- OS: Windows
- Inputmask version 5.0.4 and 5.0.5 (InputMask v5.0.3 works without issue)

**Comment by RobinHerbots** [comment]
@Pete-PlaytimeSolutions ,

I assume you do 
import Inputmask from "inputmask" 

Can you provide some more logs from the build?

**Comment by Pete-PlaytimeSolutions** [comment]
Yes, I do use 
import Inputmask from "inputmask"


1. On running the build, **ng build --prod**, 
it appears everything compiles OK.

2. After completing the compilation, It then starts the mangle/compression process, via the Terser library
    Firstly, the css optimization executes sucessfully,



3. Then the javascript optimization executes 
    e.g. **92% chunk asset optimization TerserPlugin**

but errors out, without producing any output..

This is the only output I get from the logs...

**_ERROR in scripts.17681fe55d1c5ef9854b.js from Terser
"$" is redeclared [scripts.17681fe55d1c5ef9854b.js:3646,6]**
    at ee (.\angularApp\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:1:19541)
    at On.visit (.\angularApp\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:1:120363)
    at On._visit (.\angularApp\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:1:80860)
    at AST_SymbolConst._walk (.\angularApp\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:1:52292)
    at AST_VarDef.<anonymous> (.\angularApp\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:1:66920)
    at On._visit (.\angularApp\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:1:80910)
    at AST_VarDef._walk (.\angularApp\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:1:66886)
    at AST_Const.<anonymous> (.\angularApp\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:1:66297)
    at On._visit (.\angularApp\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:1:80910)
    at AST_Const._walk (.\angularApp\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:1:66218)_



**One other minor issue I have noticed at runtime**, 
As the site first loads, when using InputMask via webpack.
On startup there is always an initial error, in the javascript console.

Uncaught ReferenceError: require is not defined
    at scripts.3436311b52dcf41fe7fd.js:1

Which references this line.
**var window=require("../global/window")**

It doesn't appear the effect anything, but it always appears that there is an error for the site.


These are the files being included:
              "./node_modules/inputmask/lib/dependencyLibs/inputmask.dependencyLib.js",
              "./node_modules/inputmask/dist/inputmask.js",
              "./node_modules/inputmask/lib/extensions/inputmask.extensions.js",
              "./node_modules/inputmask/lib/extensions/inputmask.date.extensions.js",
              "./node_modules/inputmask/lib/extensions/inputmask.numeric.extensions.js",
              "./node_modules/inputmask/dist/bindings/inputmask.binding.js"

regards

Pete

**Comment by RobinHerbots** [comment]
@Pete-PlaytimeSolutions , 

Can you share your options used for the terserplugin.

**Comment by Pete-PlaytimeSolutions** [comment]
The angular 9/10 CLI tools / build process, doesn't give you the ability to configure any of the options used for the terserplugin.
I couldn't tell you what it uses under the hood... sorry

**Comment by RobinHerbots** [comment]
@Pete-PlaytimeSolutions , 

Ah is angular using the terser plugin by default.  I will have a try myself.

**Comment by Pete-PlaytimeSolutions** [comment]
yes it does. 
Currently, I don't think they expose much of the config, just a high level, optimize: true/false, in the angular.json, I think...

**Comment by RobinHerbots** [comment]
Hi @Pete-PlaytimeSolutions , 

I quickly generated a new angular project with ng new added some input and applied the inputmask and got no errors for a production build.  Is it possible to provide some example project?

**Comment by RobinHerbots** [comment]
@Pete-PlaytimeSolutions ,

Is this issue still valid?  (If so reopen)
