### ISSUE TITLE
Selecting prefix breaks the grouping by thousands functionality

### ISSUE THREAD

**Issue by marc-flywheel** [RobinHerbots/Inputmask#2379]
- Describe the bug
Selecting / highlighting only some of the first prefix characters in a numeric masked input on a clear input can break the first thousands grouping.  This was happening for our testers if they click into currency fields on a mobile device using a finger and it was highlighting by default if the clicking is a bit clumsy.  The issue is created consistently in desktop browsers.  
Mask details:
- numeric alias
- 2 decimal places with "." radix
- group separator of ","
- prefix at least 2 characters long.  
Enter at least 5 digits to force a thousands separator to appear
The smallest thousands group will either be 2 or 4 digits instead of 3.  
Exiting the field will trigger the incomplete event on the mask.

An example
Prefix: "ABCD"
If you highlight the entire prefix (eg. "ABCD") and then type 123456 then the grouping works as expected and you end up with a mask showing "ABCD1,234,560.00"  
If you highlight just the initial characters (eg: "AB") and then type 123456 then the grouping breaks and you end up with a mask showing: "ABCD123,4560.00" (first group is 4 digits)
If you highlight just the initial characters (eg. "ABC") and then type 123456 then the grouping breaks ad you end up with a mask showing: "ABCD12,345,60.00" (first group is 2 digits)

- Add a link to a codepen, jsfiddle or other example page which shows the problem
This happens on the currency demo on this page: https://robinherbots.github.io/Inputmask/index.html
On a fresh page load, select just the "$" in the prefix (not the space beside it) and start typing numbers.  The first thousands separator will give a group of 2 digits instead of 3.
![image](https://user-images.githubusercontent.com/21365517/90443150-be98c800-e0a9-11ea-9804-acf0ccdeda0b.png)

- OS: Windows 10 
- Browser: Tested in Chrome 84 and Firefox 79
- Inputmask version: 5.0.5

**Comment by marc-flywheel** [comment]
Someone just demonstrated a different way to get the same result:

Using the currency demo field:
- click into the currency field 
- type 1
- click into a different field
- click into the currency field again - making sure you're clicking to the left of the value (cursor ends up just to the right of the "$"
- type 23456 
The masked value is "$ 2,345,61.00"

**Comment by Shaker96** [comment]
Hi, is there a fix to this issue? I was able to reproduce it by moving the cursor (with the arrow left key) all the way to the Left, so it is before the prefix (in this case $) and start typing would cause the mask to output "$12,34.00" . it is configured as integer and has ".00" as suffix

**Comment by RobinHerbots** [comment]
@marc-flywheel , @Shaker96 ,

This nissue should be fixed.  Can you have a try.
