### ISSUE TITLE
inputmask with required="required"

### ISSUE THREAD

**Issue by RaphaelDDL** [RobinHerbots/Inputmask#239]
Hello there,

I was wondering..Is there a way to have both HTML attribute `required="required"` (and it's styling `:required` and `:invalid`) on form elements and inputmask to work together? 

What i mean is that when we apply inputmask on an element with the `required`, the styling isn't applied to them:

Without inputmask:
![inpurreq](https://f.cloud.github.com/assets/1087109/549050/09456dd8-c2f1-11e2-830a-eb9ef8a230db.png)

With inputmask:
![inpurreqmask](https://f.cloud.github.com/assets/1087109/549051/094313e4-c2f1-11e2-95c1-1077185c60f1.png)

The CSS that makes it red when on focus, having `required="required"` as attribute and empty (which is `invalid`):

`input:focus:required:invalid { border:1px solid red;}`

Probably has to do with the fact that when we hover and/or click on the input, the mask applies some text (for e.g., the mask was `(99)[9]99999999`, it writes `(__)_________`) which does not  trigger the `:invalid` since it's filled with something.

Best Regards,
Raphael DDL

**Comment by RobinHerbots** [comment]
@RaphaelDDL, 

This is a jquery-validate issue (actually a missing feature).

You have to modify the 

```
    // http://jqueryvalidation.org/required-method/
    required: function( value, element, param ) {
        // check if dependency is met
        if ( !this.depend(param, element) ) {
            return "dependency-mismatch";
        }
        if ( element.nodeName.toLowerCase() === "select" ) {
            // could be an array for select-multiple or a string, both are fine this way
            var val = $(element).val();
            return val && val.length > 0;
        }
        if ( this.checkable(element) ) {
            return this.getLength(value, element) > 0;
        }
        return $.trim(value).length > 0;
    },
```

You have to include a check to ignore the empty mask $(selector).inputmask("getemptymask")

maybe someting like 

..
  return $.trim(value).length > 0 && $(element).inputmask("getemtymask") != value;
...

best regards, 

Robin
