### ISSUE TITLE
d/mm/yyyy is converted to d/m//yyyd

### ISSUE THREAD

**Issue by emilymeroni** [RobinHerbots/Inputmask#2394]
Dear team, 

I tried to insert a very simple format as such: d/mm/yyyy 
but the mask is incorrectly shown like this: d/m//yyyd

As soon as I start typing, the date is correctly formatted. 

Check the [link](https://jsfiddle.net/emilarah/Lmqf41zd/2/)

Is this issue on your radar already? Any chance it will be fixed soon?

Cheers!

Emily

**Comment by RobinHerbots** [comment]
@emilymeroni , 

There is still an issue with the placeholder and some dattime formats.

For now you could use a placeholder llike "_"

See https://jsfiddle.net/robinherbots/pzjo5384/2/

**Comment by emilymeroni** [comment]
Hi Robin, thank you for your reply. 

I need the literal format, so for now I just convert it to a supported format, so d/mm/yyyy becomes dd/mm/yyyy.

Thank you!

**Comment by RobinHerbots** [comment]
Hi @emilymeroni,

Your issue with the datetime alias is fixed in 5.0.9-beta.60
https://jsfiddle.net/h7k9jbaz/
