### ISSUE TITLE
Suppress DateTime year autocomplete?

### ISSUE THREAD

**Issue by SteveDavis-82** [RobinHerbots/Inputmask#2395]
- Description: oncomplete event fires before a user has finished entering the intended date due to autocomplete when using a year starting with 20.  (Prior to upgrading to v5, the version we were using previously did not autocomplete, and mask oncomplete event is the trigger we have used to send the value to the server. (to be fair, the previous version we were using was several major versions old, so I'm unsure when autocomplete was added))

- Fiddle: https://jsfiddle.net/1gy4upkt/3/
Enter a date 

- OS: All
- Browser: All
- Inputmask version: 5.05

I did not see anything in the documentation mentioning autocomplete, is there an undocumented option that would suppress autocomplete for datetime?  If not, could one be added?

**Comment by SteveDavis-82** [comment]
Any thoughts on this PR?

**Comment by RobinHerbots** [comment]
@SteveDavis-TR , 

The issue is implemented.
