### ISSUE TITLE
Get placeholder of a input

### ISSUE THREAD

**Issue by ghost** [RobinHerbots/Inputmask#240]
Hi, I don't no if this is the right place, but there is a way to get the placeholder of a input, something like this:

$('#my-input').inputmask('placeholder');

Thanks

**Comment by RobinHerbots** [comment]
@spacelab-x ,

That option does not exist.  Why do you need it? You know already the placeholder at the definition of the mask.

Can you explain the use of this?

Best regards, 

Robin

**Comment by spacelab-sp** [comment]
Hi, I need to validate a input, if the input is empty.

But, I think I can get the unmasked value, right? Oh, thats it, my mistake.

Thank you!
