### ISSUE TITLE
Removing the mask from Input results in TypeError: Cannot read property 'dependencyLib' of undefined

### ISSUE THREAD

**Issue by payapula** [RobinHerbots/Inputmask#2403]
### After removing the mask on a input field programmatically and submitting the form results in the TypeError: Cannot read property 'dependencyLib' of undefined

I was able to reproduce the error in codesandbox [React] - https://codesandbox.io/s/inputmask-undefined-error-yqug4

In order to get the error you need to 
1. Click on button 'Enable the Mask'
2. Then Click on button 'Remove the Mask'
3. Enter any value (you can even leave it blank)
4. Click on Submit.

You will be getting this error - _Uncaught TypeError: Cannot read property 'dependencyLib' of undefined_

Upon investigation, I found that without enabling the Mask, the Input element don't have the property **inputmask**. However after enabling the mask we have new property for the input with key **inpuptmask**

After clicking on Remove mask this property is set to undefined. **inputmask: undefined**

Which is getting evaluated on the code as undefined when we are submitting the form.

The below piece of code is producing error and its from **_node_modules/inputmask/dist/inputmask.js_**

```
   var EventRuler = {
            on: function on(input, eventName, eventHandler) { 
                 var $ = input.inputmask.dependencyLib, ev = function ev(e) {
                    e.originalEvent && (e = e.originalEvent || e, arguments[0] = e);
                    var that = this, args, inputmask = that.inputmask, opts = inputmask ? inputmask.opts : void 0, 
   {/*error line*/}  $ = inputmask.dependencyLib;
                 <...>
             }
 } }
```

I am not sure but undefined check on the **inputmask** could resolve this issue hopefully.

![image](https://user-images.githubusercontent.com/7134153/94701789-ae3b6480-035a-11eb-9b3f-3874b355bbd8.png)

Below is the screenshot of error in dev tools.
![image](https://user-images.githubusercontent.com/7134153/94701987-e2af2080-035a-11eb-9ee9-9bcdaf349a3b.png)

Please let me know if you need any additional details.

- Copy of https://github.com/RobinHerbots/Inputmask/issues/2369#issuecomment-701445070
- OS: Mac & Windows
- Browser : Chrome
- Inputmask version : 5.0.5

**Comment by RobinHerbots** [comment]
Hi @payapula ,

The issue is fixed in verion 5.0.6-beta.19.

There was a problem with unbinding the submit event.  I also added an extra check in the dependencyLib.

Best regards, 
Robin
