### ISSUE TITLE
Change mask on submit

### ISSUE THREAD

**Issue by soyaforcemeat** [RobinHerbots/Inputmask#2404]
Hi!
Great job!
I use your plugin as {$('.selector').inputmask({"mask": "+7 (999)999-99-99",  'removeMaskOnSubmit' : true});}
and receive data as  9999999999. Is it possible to change mask on submit to receive data like  89999999999?

**Comment by payapula** [comment]
Hi @soyaforcemeat 

This is already available. You just need to pass correct options when setting the mask. 
Have you checked [autoUnmask](https://github.com/RobinHerbots/Inputmask#autounmask) ?

**Comment by soyaforcemeat** [comment]
Thank you!
Can you provide an example of using?
I change option as {$('.selector').inputmask({"mask": "+7 (999)999-99-99", 'autoUnmask' : true});}
but receive data as  +7 (999)999-99-99. I need what input mask is +7 (999)999-99-99 and receive data as 89999999999 (change +7 to 8 and remove quotes and minuses)

**Comment by payapula** [comment]
@soyaforcemeat  I have created a [fiddle](http://jsfiddle.net/7hysvLrp/1/)

If I can understand your question correctly, then you want the +7 to change to 8 automatically. What we need to understand here is +7 is a constant and cant be edited, so there is no way you could change that automatically. If you want you can change that to 8 in your code after receiving the value on submit handlers.

This mask
---> +7 (999)999-99-99

Would return

---> +7 (123) 456-78-90 (**autoUnmask** false)
---> 1234567890 (**autoUnmask** true)
---> 1234567890 (**removeMaskOnSubmit** true)

Where the value entered is = 1234567890

Please feel free to modify the example and post your question here for better understanding. Thank you!

**Comment by soyaforcemeat** [comment]
Yes exactly

If input is 1234567890, in UI input mask is +7 (123) 456-78-90, at the server receives data masked as 81234567890

**Comment by payapula** [comment]
That should not be possible, if UI input is +7 (123) 456-78-90 the data received should be 1234567890. 
If you want you can prepend a 7 in the data received. 

I am not sure how you are getting 8 🤷🏾‍♂️

Can you reproduce this in online fiddle/sandbox? like this one ->  [fiddle](http://jsfiddle.net/7hysvLrp/1/)

**Comment by soyaforcemeat** [comment]
Of course it's not possible in this situation, but it's my aim. I want to get this result. 
In my crm input is validated by country code (+7 is russian code for external use, 8 is the same but for internal use) and input must be numeric, it's decline nonnumeric symbols. For local calls you can use as +7 or 8, it's equal. But if you call from outside country you need to use +7.

**Comment by RobinHerbots** [comment]
Hi @soyaforcemeat , @payapula , 

I updated the provided jsfiddle to provide the 8 in front.  Have a look at http://jsfiddle.net/ut98poy5/2/
You can use the onUnMask option and the autoUnmask option for this.

Sorry for the late response but I cannot justify time for the Inputmask currently.

**Comment by soyaforcemeat** [comment]
Great! Simple and elegant!
But in my case works this variant 
{$('.dhvc-form-control-phone-mask').inputmask({"mask" :"+7 (999) 999-99-99", 'removeMaskOnSubmit': true,
  onUnMask: function(masked, unmasked, opts){
  	return "8" + unmasked;
  }});};
Don't know why, but autoUnmask makes no effect
Thank you!
