### ISSUE TITLE
NumericAliases cursor

### ISSUE THREAD

**Issue by craigrs84** [RobinHerbots/Inputmask#241]
Is it possible to use the NumericAliases extension without having the cursor jump around strangely?

regarding the cursor, we want it to behave like a normal textbox but it would just filter what we are able to type.

no special handling of radix point, etc. overwriting characters (as if you had pressed the insert key), etc.

**Comment by RobinHerbots** [comment]
@craigrs84, 

I will add an option to skip the radix handling.

skipRadixDance ;-)

best regards, 

Robin

**Comment by RobinHerbots** [comment]
@craigrs84 ,

In the dev branch the option is added.  You can already experiment with it if you want or wait until the new releae in the 2.x branch.

best regards
Robin

**Comment by craigrs84** [comment]
Thank you! That was very quick ill check it tomorrow

**Comment by RobinHerbots** [comment]
Be aware that the dev branch isn't fully stable at the moment.  There are issues when making selections and deleting them with numerics and dates.

**Comment by RobinHerbots** [comment]
Check the latest version (skipradixdance option
