### ISSUE TITLE
replace characters

### ISSUE THREAD

**Issue by oghanbari** [RobinHerbots/Inputmask#2411]
hi, i am using integer mask, i want when i type character "1" it get replaced with "۱" how can i do it? these are persian numbers ,please guide me
i am looking how can i replace integer characters with another ascii code
1->۱
2->۲
3->۳
....
thanks

**Comment by RobinHerbots** [comment]
@oghanbari , 

Can I consider this issue as a duplicate of #2412?

**Comment by oghanbari** [comment]
yes its duplicate of #2412
thanks again.
