### ISSUE TITLE
how can i apply groupSeperator for integer custom definition?

### ISSUE THREAD

**Issue by oghanbari** [RobinHerbots/Inputmask#2412]
hi, how we can apply groupSeperator : ',' for this custom definition?
 input.inputmask( "f{*}");

Inputmask.extendDefinitions({
        //Persian character and numbers (and space!)
        'f': {
            validator: "[0-9\u060C-\u0638\u0639-\u0648\u06A9\u06AF\u06CC\u067E\u0686\u064A\u0649\u0626\u0698 ]",
            cardinality: 1
        }
});

**Comment by RobinHerbots** [comment]
Hi @oghanbari, 

Can you have a try with the following.
```
	Inputmask.extendAliases({
			"PersianInteger": {
				alias: "numeric",
				digits: 0,
				definitions: {
					'f': {
						validator: "[0-9\u060C-\u0638\u0639-\u0648\u06A9\u06AF\u06CC\u067E\u0686\u064A\u0649\u0626\u0698 ]",
						cardinality: 1
					}
				},
				_mask: function (opts) {
					return "(" + opts.groupSeparator + "fff){+|1}";
				},
				groupSeparator: ","
			},
		});

		Inputmask("PersianInteger").mask("test3");
```

**Comment by oghanbari** [comment]
hi, thanks for your reply, yes its working
