### ISSUE TITLE
Question about data-attributes

### ISSUE THREAD

**Issue by levipadre** [RobinHerbots/Inputmask#2417]
Hi,

I don't know if it's a bug or not, but I'm using data-attributes and I was able to hide the underline with showmaskonfocus and showmaskonhover attributes.
`<input type="text" data-inputmask="'mask': '9'" data-inputmask-showmaskonfocus="false" data-inputmask-showmaskonhover="false" maxlength="1">`
This is all fine, but when I type a number and after remove it (backspace), the underline appears.

How can I hide it? Preferrably with data-attribute.

**Comment by RobinHerbots** [comment]
@levipadre , 

 <input type="text" data-inputmask="'mask': '9'" data-inputmask-jitmasking="true">
