### ISSUE TITLE
CVV masking not working

### ISSUE THREAD

**Issue by yudiznilay** [RobinHerbots/Inputmask#2419]
**Expected**
CVV mask working. It has same format in jquery as CardNumber and ExpiryDate.
**Result**
Cursor goes to end.
**Link to jsfiddle**
https://jsfiddle.net/yudizsolutions/vkfe16a0/3/
- OS:
MacOS catalina
- Browser
All browsers
- Inputmask version
inputmask 5.x

Waiting for your reply.

**Comment by RobinHerbots** [comment]
@yudiznilay, 
Have a try with 
```
$('.card-number').inputmask({ mask: "9999 9999 9999 9999", keepStatic: true, "placeholder": "0000 0000 0000 0000" });
$('.expiry').inputmask({ mask: "99 / 99", keepStatic: true, "placeholder": "MM / YY" });
$('.cvv').inputmask({ mask: "999", keepStatic: true, "placeholder": "000" });
```

**Comment by yudiznilay** [comment]
Thanks @RobinHerbots. It is working with your format.
