### ISSUE TITLE
numeric Input mask on 1 char field

### ISSUE THREAD

**Issue by sas1973** [RobinHerbots/Inputmask#242]
I have a numeric alias on 1 char input text field and it wont allow me to enter any numbers. Any idea??

This is what i have as code..

 <div id="inpField" style="left: 28.6em; padding:0px 3px 0px 3px;">
<input id="NUM_18" name="FNUM_18" type="text" class="numeric" value="2" size="1" maxlength="1" style=""></input>

<script type="text/javascript">$(document).ready(function () {$("#NUM_18").inputmask('integer'); });</script>

</div>

**Comment by sas1973** [comment]
I am not sure why html code did not get posted ... Trying again...

"div id="inpField" style="left: 28.6em; padding:0px 3px 0px 3px;">
input id="FIELD_NUM_18" name="FIELD_NUM_18" type="text" class="ui-widget ui-state-default ui-corner-all   highlightme dataFieldNormal numeric " value="1" size="1" maxlength="1" style=""></input>

script type="text/javascript">$(document).ready(function () {
                        $("#FIELD_NUM_18").inputmask('integer'); });</script>
</div"

I had to take out the "lt" symbols for html code to show up.

**Comment by RobinHerbots** [comment]
@sas1973 , 

Fixed in the latest 2.x branch.

best regards, 

Robin

**Comment by sas1973** [comment]
Thanks.
