### ISSUE TITLE
jitmasking ssn

### ISSUE THREAD

**Issue by smo76** [RobinHerbots/Inputmask#2420]
I cannot get jitMasking to work with ssn mask. 

`Inputmask.extendAliases({
			'ssn': 
                         {
autoUnmask: true,
				placeholder: " ",
				jitMasking: true
			}}).
`

If I use my own custom mask as such. I will get desired results 

` Inputmask.extendAliases({'customSsn': {
				autoUnmask: true,
				placeholder: " ",
				mask: "999-99-9999",
				jitMasking: true
			}})`

- OS: windows 10
- Browser chrome
- Inputmask version 5.0.5

**Comment by RobinHerbots** [comment]
@smo76 , 

Fixed in 5.0.6-beta.20
