### ISSUE TITLE
Input Mask for search fields (partially filled mask)

### ISSUE THREAD

**Issue by docwaremm** [RobinHerbots/Inputmask#2425]
Version: input mask 5.0.3
Usage: Standalone (no jquery)
Combination: vanilla js along with mdc.textfield for rendering purposes

We want to use the library to give users a feedback on the possible input format. We have the possiblity to search for a serial number, e.g. 999-9999-99.

Using 
Inputmask({positionCaretOnClick: "none", 
           "mask" : "999-9999-99."}).mask(searchField);

allows to modify the cursor position for the next input easily, so that it works same as for the keyboard (where by default it is possible to change cursor pos). This would allow to make an entry like e.g.
___-3_15-20 

It is possible to send such unfinished value to the server easily and to work with such value for a search query. A database query could be e.g. %3%1520 or ???3?1520 - either way it would be possible to retrieve data on the partial input.
However, if the search value is being reapplied (including mask) to the textfield it would turn out as
315-20__-__

This can be reproduced e.g. by having text-field with such a static value (___-3_15-20 ) and masking that input field. In UI it would change the displayed value right away.

Which is not the value that we entered before.

Is there any chance to improve the behaviour in means of being able to use it for search with partial information? Is there a chance using hooks / properties already? Using "optional" syntax may not work as intended as imho we most likely would lose the placeholder details.

At present the library behaves differently between
-editing manually (where it is possible to enter only partial data, leaving place holders in between) and
- loading/pasting/focussing/ ... where it would remove any place holder gaps

Thanks alot already for your help!

**Comment by docwaremm** [comment]
![grafik](https://user-images.githubusercontent.com/60660746/98835104-4a6b8780-2440-11eb-8779-a8fbb9a4c285.png)

**Comment by RobinHerbots** [comment]
@docwaremm, 

That seems like a nice feature.  I will add an option for that.

**Comment by docwaremm** [comment]
Great news. So far I found a solution in means of hacking myself into it like ...

                    if (void 0 !== charCode) if (void 0 === maskset.validPositions[ndx] && inputValue[ndx] === getPlaceholder(ndx) && isMask(ndx, !0) && !1 === isValid(ndx, inputValue[ndx], !0, void 0, void 0, !0)) {
                        maskset.p++;
                        if ((charCode === inputmask.opts.placeholder) && (inputmask.opts.partialSearchMask === !0)) {
                            inputmask.caretPos = {
                                begin: ndx + 1,
                                end: ndx + 1
                            };
                        }
                    } else {

So what I do is check if the flag (freshly introduced) partialSearchMask is set to true, and if the current char would be a place holder, then I simple change the caret position. Not sure if that is a good solution.

**Comment by RobinHerbots** [comment]
@RobinHerbots ,

Can you have a try with version 5.0.6-beta.23

**Comment by docwaremm** [comment]
Tried with the beta. Guess at the very beginning there was still my version active (lovely browser cache). In the end it worked just fine, also pasting worked.

Compared to my (temporary) workaround/hack there's no additional option required to trigger the behaviour. Though i noticed I still should set the feature "positionCaretOnClick" to "none" - when using the mask way. more intuitive to specify the next char then when filling the search mask.

Thanks for the fast solution! Can you already forsee like when this version / feature will be considered 'stable' in your eyes?
