### ISSUE TITLE
IE11: Object doesn't support property or method 'includes'

### ISSUE THREAD

**Issue by jeffwlawson** [RobinHerbots/Inputmask#2427]
As of version 5.0.4+, this no longer works with IE11.  It throws this error "Object doesn't support property or method 'includes'" in the jquery.inputmask.js file.

This appears to be related to [this commit](https://github.com/RobinHerbots/Inputmask/commit/378a7d171d3b9983b3039d356f4041ee55532194) where includes() was added in, which is not supported in IE11.  

Rolling back to version 5.0.3 appears to resolve the issue.

**Comment by RobinHerbots** [comment]
@jlaw84 , 

This is already fixed in version 5.0.6-beta...
