### ISSUE TITLE
Expiration Date Min/Max Input

### ISSUE THREAD

**Issue by CeanFritz** [RobinHerbots/Inputmask#2429]
Hi,

Thank you for your work on this plugin. It has saved me countless hours writing validation scripts. I have noticed a small issue when I try to use the min and max values for credit card expiration dates.

I am not sure if this is correct, but I have the data-inputmask-max as "12/2099" and data-inputmask-min as "11/2020". It works as for the max value as expected and doesn't allow values like "03/2020" past the min. However, if you input something like "03/20"; then press 1 or 0, you get "03/2000". Which is below the min value. As long as the user has put "03/202", it restricts the next number to 1-9 and doesn't allow 0.

I put my input field in a jsfiddle. Sorry in advance for any extraneous attributes. This code came directly out of my MVC project.
https://jsfiddle.net/6dhub3ay/

Thanks again,
Cean

**Comment by Quocnamit** [comment]
Same issue !

**Comment by RobinHerbots** [comment]
@CeanFritz,

Fixed in the latest version
