### ISSUE TITLE
[HELP] Value unmasking question

### ISSUE THREAD

**Issue by pocketcap** [RobinHerbots/Inputmask#2430]
Per https://github.com/RobinHerbots/Inputmask#value-unmasking, I want to unmask a string, but it returns me a blank string.

JSFiddle: https://jsfiddle.net/yahuiwang/09x6dgnu/8/

Did I use it incorrectly? Any help would be appreciated.

**Comment by danielwermann** [comment]
Hi @pocketcap 

I am not sure if the unmask works as you were trying to use it, but in any case you could try the following:

```
function test(){

var unformattedDate = Inputmask.unmask("23/03/1973", { alias: "[99]/[99]/[9999]"}); //23031973
alert("unformattedDate: " + unformattedDate);
}

```

**Comment by pocketcap** [comment]
@danielwermann Thanks~ It works.

**Comment by RobinHerbots** [comment]
Hi @pocketcap, @danielwermann , 

As the datetime alias has progressed I should have updated the README also.

For date values you need/can specify an outputFormat.  So you can choose how to unformat it.

I updated your jsfiddle => https://jsfiddle.net/f58h9asx/

```
function test(){
      var unformattedDate = Inputmask.unmask("23/03/1973", { alias: "datetime", inputFormat: "dd/mm/yyyy", outputFormat: "ddmmyyyy"});//23031973
      alert("unformattedDate: " + unformattedDate);
}
```
