### ISSUE TITLE
HandleNativePlaceholder function prevents use of dynamic placeholders.

### ISSUE THREAD

**Issue by subarachnid** [RobinHerbots/Inputmask#2433]
In our application we have to set the placeholder of some masked fields dynamically depending on the value of another field. The problem is that inputmask always restores the initial/original placeholder on blur events. Is there an option to disable this feature so that the placeholder is never restored/changed by inputmask?

Demo: https://jsfiddle.net/uq3r1bk4/

**Comment by RobinHerbots** [comment]
Hi @subarachnid ,

I fixed the issue in version 5.0.6-beta.22 

Have a look at https://jsfiddle.net/y8zoLm4j/
