### ISSUE TITLE
onBeforeMask does not seem to work

### ISSUE THREAD

**Issue by nadirkhanlou** [RobinHerbots/Inputmask#2434]
Hi.

I have a simple input box and I am using "999-999999-9" as a mask. However, I want to change the input that I type in the box before validating it (for example change 1s to 0s). I used 'onBeforeMask' but it never seems to execute the function (i never see the "before: " output in my console log) when I type something it. It only works when I paste something in the box.
```
$("#input").inputmask({
        mask: "999-999999-9",
        onBeforeMask: function (value, opts) {
            console.log("before: ", value);
            return value;
        }});
```
I would appreciate it if anyone could help me.

EDIT: I was able to work around my issue by using onBeforeWrite instead of onBeforeMask, but the question stands. Why doesn't onBeforeMask work?

Thanks,
Alireza

**Comment by RobinHerbots** [comment]
Hi @nadirkhanlou , 

You can read about the onbeforemask option here https://github.com/RobinHerbots/Inputmask#onbeforemask
That option only works for pasting and initial values.

An alternative solution could be the casing option.  The use is straightforward, but I admit finding this option for this case isn't ;-)

```
Inputmask({
			mask: "999-999999-9",
			casing: function (elem) {
				if(elem == "1") return "0";
				return elem;
			}}).mask("test3");
```
