### ISSUE TITLE
showMaskOnFocus: false causes 'Illegal invocation' error

### ISSUE THREAD

**Issue by MattPurland** [RobinHerbots/Inputmask#2436]
- Describe the bug
Adding showMaskOnFocus: false causes an Illegal invocation error to occur when entering a value

- Add a link to a codepen, jsfiddle or other example page which shows the problem
https://jsfiddle.net/ytsm8r2j/11/

- OS:
Windows 10 64bit

- Browser
Chrome 87.0.4280.88

- Inputmask version
5.0.6-beta.22

**Comment by RobinHerbots** [comment]
@MattPurland , 

Fixed in version 5.0.6-beta.24
