### ISSUE TITLE
 letter "a" gets change to _

### ISSUE THREAD

**Issue by Abishek-Rajagopal-Commits** [RobinHerbots/Inputmask#2445]
My Ember Code :
`    $("#example1").inputmask({
    mask: "*{1,100}."+"cal.com",
    greedy: false,
    definitions: {
      '*': {
       casing: "lower"
      }
    }
  });`

My html or hbs code:
`    <input type="text" id="example1" class="mystyle" name="domain_name"  autocomplete="off" class="required"/>
        `
Output in the input field:
`_.c_l.com`

Output Required:
`_.cal.com`

Kindly please help

Screenshot: https://drive.google.com/file/d/1-Nm1cf6hz2-Ulw9P-G_err_jVOcHMY-G/view?usp=sharing

**Comment by RobinHerbots** [comment]
Hi @Abishek-Rajagopal-Commits , 

That is because "a" is a definition symbol.  You need to escape the a.

```
$("#example1").inputmask({ mask: "*{1,100}."+"c\\al.com", greedy: false, definitions: { '*': { casing: "lower" } } });
```

**Comment by Abishek-Rajagopal-Commits** [comment]
@RobinHerbots 
the above given will only be applicable if "cal.com" in a static one. what if i use a variable and alter the domain dynamically.

For Example:
`$("#example1").inputmask({ mask: "*{1,100}."+suffix, greedy: false, definitions: { '*': { casing: "lower" } } });`

and give values based on the input i get for suffix.

please help

**Comment by RobinHerbots** [comment]
@Abishek-Rajagopal-Commits ,

This will do

```
var suffix = "cal.com";
		$("#test2").inputmask({ mask: "*{1,100}."+ suffix, greedy: false, usePrototypeDefinitions: false, definitions: { '*': { validator: "[0-9\uFF10-\uFF19A-Za-z\u0410-\u044F\u0401\u0451\u00C0-\u00FF\u00B5]", casing: "lower" } } });

```

**Comment by Abishek-Rajagopal-Commits** [comment]
Thanks a lot its working

**Comment by Abishek-Rajagopal-Commits** [comment]
Hi RobinHerbots,
                 How can include special characters in this like /- and other before suffix.
                 [0-9\uFF10-\uFF19A-Za-z\u0410-\u044F\u0401\u0451\u00C0-\u00FF\u00B5]
                 the above only allows numbers and alphabets

**Comment by RobinHerbots** [comment]
@Abishek-Rajagopal-Commits , 

The [0-9\uFF10-\uFF19A-Za-z\u0410-\u044F\u0401\u0451\u00C0-\u00FF\u00B5] is a regex.  So add you special chars or ranges between the []
