### ISSUE TITLE
[DateTime] How to update min/max?

### ISSUE THREAD

**Issue by VARGA-Peter** [RobinHerbots/Inputmask#2449]
Changing the `min`/`max` values after the first call aren't considered. How can I update these values or what else can I do?

**Comment by VARGA-Peter** [comment]
**_My solution:_**
I call the remove method when the static window closes and initialise it when the static window opens. Before I have ran the initialisation when the document was loaded.

I understand the logic/reason why it's how it is, but may be it could be re-considered to update some values when the input field gets the focus.

**Comment by VARGA-Peter** [comment]
Another solution would be to add a function "UpdateSettings" and this function then updates the internal settings with the new values since the object was created.

**Comment by VARGA-Peter** [comment]
OK, I see you don't consider it as important as this issue is without any comment.
I provide you the following example so you understand better why it's useful to update the min/max values dynamically:

Just imagine a numeric input field for an alarm where the input field contains either minutes or hours of the reminder - like in Outlook.

So, next to this input field are 2 radio buttons [Minutes & Hours]. When for example the radio button "Minutes" is selected so the max value should be 180 [so the alarm rings 3 hours in advance] and when the "Hours" radio button is selected the max value should be 24 [the alarm rings 1 day in advance].

Currently, how can I implement this? Each time a radio button is clicked destroy and create the inputmask?

**Comment by RobinHerbots** [comment]
@VARGA-Peter ,
Sorry that I didn't respond yet.  But I don't have much spare time currently, to spend on the inputmask.  There are also +500  other issues waiting to be resolved.
Your issue is valid,  and there is the option method which allows changes on an existing inputmask instance.   But I should verify if it work properly on the min/max options.

**Comment by RobinHerbots** [comment]
When you use the option method it will work but it will basically set the new or changed option and reapply the mask.
