### ISSUE TITLE
Not working on IE for Windows Phone 8

### ISSUE THREAD

**Issue by mattnibs** [RobinHerbots/Inputmask#245]
Not that this probably a high priority but it's not working correctly on Internet Explorer for Windows Phone 8. Inputted characters do not correctly fill the mask, the mask text just shifts over.

**Comment by RobinHerbots** [comment]
@mnibecker , 

Yes I know see issue 213.

But, I will have a look at it soon.

Best regards, 

Robin

**Comment by mattnibs** [comment]
Thanks!
