### ISSUE TITLE
How do I remove the character"_" at the end of the value?

### ISSUE THREAD

**Issue by andriireblian** [RobinHerbots/Inputmask#2450]
Hello @RobinHerbots !
Could you help me remove the character "\_" when I choose country which support 8 or 9 numbers (for example: Ireland), please?
If I enter 8 numbers and take the focus away from the input, then the character "\_" remains.

- OS: Windows 10
- Browser: Chrome Version 87.0.4280.141 (Official Build) (64-bit)
- Inputmask version: 5.0.4-beta.33

**Comment by jimbo1999uk** [comment]
Did you manage to find a solution to this? I'm having the same problem and saving underscores to the database. as they're coming through in the form data.

I recently updated from 3.3.4 to 5.0.7 and this didn't happen before the update. I've looked through the docs but struggling to find anywhere which will turn off this behaviour.

**Comment by claudiogg88** [comment]
add

 placeholder: '' 

to options

**Comment by RobinHerbots** [comment]
@andriireblian ,

You will need to make the extra character optional or work with an alternating mask.

Something like

```
	Inputmask(
		{
			mask: "99 99 99 99[9]",
			greedy: true
		}).mask("#test2");
```
