### ISSUE TITLE
cant enter the leap year using jit masking

### ISSUE THREAD

**Issue by SIVARAMAN-krg** [RobinHerbots/Inputmask#2453]
Inputmask("mm/dd/yyyy", { jitMasking: true}).mask(this.id);

**Comment by SIVARAMAN-krg** [comment]
In mm/dd/yyyy format we can only enter 02/29 and we can't enter the year in jit masking....so please solve this issue

**Comment by RobinHerbots** [comment]
@SIVARAMAN-krg ,
The issue is fixed.
