### ISSUE TITLE
Date field results into buggy output: 30/02/yy0y

### ISSUE THREAD

**Issue by anandphulwani** [RobinHerbots/Inputmask#2456]
- **Describe the bug**: 
Enter these keys in "date" field, one with "dd/mm/yyyy" format, results into: **30/02/yy0y**
   - 3
   - 0
   - 2
   - 2
- **Add a link to a codepen, jsfiddle or other example page which shows the problem**
I am using the first "date" field in the "Demo" section on the webpage https://robinherbots.github.io/Inputmask/
- OS: Windows 10
- Browser: Firefox Developer Edition 85.0b7 (64-Bit)
- Inputmask version: 5.0.6-beta.29

**Comment by RobinHerbots** [comment]
@anandphulwani , 

Ok thx for reporting.  Fixed.

**Comment by anandphulwani** [comment]
Cheers, well done.

**Comment by namratapatel78** [comment]
@RobinHerbots 
I am still getting this issue in Android device with Firefox browser. It is not working in [demo](https://robinherbots.github.io/Inputmask/#/demo) link as well.

Enter 01/01/2000 and then try to clear the date. 0 is not getting removed from day or month.
