### ISSUE TITLE
setvalue() "removes" number before comma when "positionCaretOnClick" and "digitsOptional" are set.

### ISSUE THREAD

**Issue by VARGA-Peter** [RobinHerbots/Inputmask#2457]
I have this MCVE:

     <input type="text" name="strange" placeholder="Strange" id="strange">

     $("[name='strange']").inputmask({
            alias:                  'numeric',
            digits:                 2,
            digitsOptional:         false,
            positionCaretOnClick:   "select",
            suffix:                 " €",
     });
     $("[name='strange']").inputmask("setvalue", 12.36);

**And now this strange behaviour:**
In this constellation the value `0.36` is set. If I remove `positionCaretOnClick` **or** `digitsOptional` then the value is correctly set to `12.36`.

This means `positionCaretOnClick` and `digitsOptional` cannot be used together.

What is the reason? I can remove for the moment `positionCaretOnClick` but it would be nice when it would work with both attributes.

**Comment by RobinHerbots** [comment]
@VARGA-Peter,

Fixed in version 5.0.6-beta.35
