### ISSUE TITLE
Unable to enter dot, input mask not allowing special characters

### ISSUE THREAD

**Issue by Abishek-Rajagopal-Commits** [RobinHerbots/Inputmask#2458]
`$("#example").inputmask({ mask:"*{1,255}", 
greedy: false, 
usePrototypeDefinitions: false, 
definitions:
 { '*': { 
validator: "[0-9\uFF10-\uFF19A-Za-z!#$%&'.*+/=?^_`{|}~\.\-\u0410-\u044F\u0401\u0451\u00C0-\u00FF\u00B5]", 
casing: "lower" }
 } 
});
`

**Comment by RobinHerbots** [comment]
@Abishek-Rajagopal-Commits , 

I think it's due the character set used.  But have a try with this.
``
	$("#example").inputmask({
			regex: ".{0,255}",
			casing: "lower"
		});
``
