### ISSUE TITLE
iPhone shows pure numeric keyboard for decimal input

### ISSUE THREAD

**Issue by VARGA-Peter** [RobinHerbots/Inputmask#2459]
I have this MCVE:

    <input type="text" name="price" placeholder="Price" id="price">

    Inputmask.extendAliases({
         'SfdCurrency': {
             alias:                  "numeric", /* can be also decimal */
             digits:                 2,
             digitsOptional:         false,
             radixPoint:             ",",  /* can be also . */
    });

    $("[name='price']").inputmask({
         alias: 'SfdCurrency',
    });

On iPhone [10 & 11 & 12] the pure numeric keyboard is shown [see the below screenshot] which doesn't have the comma which means that in order to enter digits after the comma the user has to click "*behind*" the comma. Android shows a keyboard with comma so any decimal number can be entered without an additional click after the comma sign.

[![enter image description here][1]][1]

**My question:**

What am I doing wrong because iPhone doesn't show a keyboard with comma for a decimal number?

  [1]: https://i.stack.imgur.com/n8nCf.png

**Comment by RobinHerbots** [comment]
@VARGA-Peter ,

Can you set the inputmode option to decimal.

**Comment by VARGA-Peter** [comment]
Thank you Robin. Yes, now in the lower left corner the comma appears.
