### ISSUE TITLE
Bug in iframes

### ISSUE THREAD

**Issue by Elnadrion** [RobinHerbots/Inputmask#2461]
Hi! I'd noticed strange behavior of the caret, when I tried to apply inputmask to the inputs in iframe.
Look by yourself: https://codepen.io/M_A_X_NSK/pen/BaQNyJq
When you trying to type - carret moving in the far right position after each typed symbol
This bug reproduces in each browser and device I've tried
I've tried 5.0.3, 5.0.5 and 5.0.6-beta.32 versions

P.S. Why I even need this? I have the popup window https://prnt.sc/xzp0o3 that displays on my site from another service (carrotquest.io if you're interested 😁) via iframe. Guys from this service are half-assed and they can't do this masks in their own service. That's why it would be wonderful to use this plugin

**Comment by RobinHerbots** [comment]
@Elnadrion ,

Fixed in 5.0.6-beta.39
