### ISSUE TITLE
How to implement group separator for string value not numeric?

### ISSUE THREAD

**Issue by brandontan92127** [RobinHerbots/Inputmask#2463]
There is a groupSeparator attribute but not working for string value for input.
I am going to separate string value by ',' for each 3 characters.
For example if the value is 'abcdefghijklmn' then the mask value must be 'ab,cde,fgh,ijk,lmn'
Is it impossible for string value to separate like this?

**Comment by RobinHerbots** [comment]
@Frozen1110 , 

Have a try with
```
Inputmask({
			mask: "aaa(,aaa){*}",
			jitMasking: true
		}).mask("test3");
```
