### ISSUE TITLE
Wrong decimal numeric value with init value (Edit value)

### ISSUE THREAD

**Issue by RayhanYulanda** [RobinHerbots/Inputmask#2465]
I have a problem numeric with init value. 
Init value : `2042.09`
Should be :  `2.042,09`
But it gives : `204.209,00`
```
$(".target").inputmask('numeric', {
            radixPoint:",",
            groupSeparator: ".",
            allowMinus: false,
            unmaskAsNumber: true,
            digits: 2,
            removeMaskOnSubmit: true,

            autoUnmask: true,
            digitsOptional: false,
        })
```

- JSFiddle : https://jsfiddle.net/0mfjg5t6/7/
- OS: Windows 10
- Browser : Chrome
- Inputmask version : 5.0.5

Another try :
I've tried to make it with this example https://github.com/RobinHerbots/Inputmask/blob/5.x/README_numeric.md#setting-initial-values but the next problem is, it affected the others input
Here is it the code https://jsfiddle.net/pb60wmqd/7/

@RobinHerbots

**Comment by RayhanYulanda** [comment]
I've tried to make it with this example https://github.com/RobinHerbots/Inputmask/blob/5.x/README_numeric.md#setting-initial-values but the next problem is it affected the others input
Here is it the code
JSFiddle : https://jsfiddle.net/pb60wmqd/7/

**Comment by RobinHerbots** [comment]
Have a read in the readme for the numeric extensions.  The inputType option.

**Comment by RayhanYulanda** [comment]
Do you mean numericInput? Can you help me with the code in the fiddle? @RobinHerbots

**Comment by RayhanYulanda** [comment]
Thanks a lot for the clue. Found it!

Maybe can help the others
```
$("#target").inputmask('decimal', {
            radixPoint:",",
            groupSeparator: ".",
            allowMinus: false,
            unmaskAsNumber: true,
            digits: 2,
            removeMaskOnSubmit: true,
            inputType: "number", //Just adding this

            autoUnmask: true,
            digitsOptional: false
        })
```
