### ISSUE TITLE
Min Date not working properly. It always accepts '2000' year.

### ISSUE THREAD

**Issue by victorlm125** [RobinHerbots/Inputmask#2467]
When a min is defined (01/01/2010 for example) in a datetime alias, dates with '2000' year value are acceppted when you are typing the year.

I assume that the correct behaviour would be as the previous digits, so it doesn't let me type not allowed digit.

Can I deactivate the 'autofill' feature?

https://stackblitz.com/edit/angular-date-inputmask

Inputmask version 5.05

**Comment by adlerdias** [comment]
Hello,

I think you can try using the beta version in your dependencies.

`"inputmask": "next",`

**Comment by victorlm125** [comment]
Is this bug fixed or is implemented the deactivation of 'autocomplete' ?

**Comment by adlerdias** [comment]
i'm not sure what you mean by: implemented deactivation of 'autocomplete'.

I think it was a bug, since you defined the min value as

`min: '01/01/2010'`

here your example updated with next version of inputmask

https://stackblitz.com/edit/angular-date-inputmask-ycqmxx?file=package.json

**Comment by victorlm125** [comment]
I speak about the predictive feature with dates. For instance with a mask of dd/MM/yyyy: 

Typing key 05/10/20 -> 05/10/20**00**

The library fills the last two digits but I want the system doesn't autocomplete it.

Can I deactivate this feature?

**Comment by RobinHerbots** [comment]
I will add the option very soon.

Op vr 26 feb. 2021 11:09 schreef victorlm125 <notifications@github.com>:

**Comment by RobinHerbots** [comment]
@victorlm125 , 

See issue #2395
