### ISSUE TITLE
No mask shown on focus when another handler of focus event erases value 

### ISSUE THREAD

**Issue by dzhivtsov** [RobinHerbots/Inputmask#247]
No mask is shown on focus when another handler of focus event erases value.

Such behavior was noticed while using http://mths.be/placeholder to support placeholders in IE.

To reproduce this behavior the code below can be used. This code simulates default placeholder behavior. On blur placeholder text is added, on focus is erased. 

<input type="text" value="mytestvalue"/>
    <script type="text/javascript" src="http://code.jquery.com/jquery-1.10.1.min.js"></script>
    <script type="text/javascript" src="jquery.inputmask.js"></script>
    <script>
        $('input').focus(function () {
        if ($(this).val() == ''){
            $(this).val('');
        }
    }).blur(function () {
        if ($(this).val() == '') {
            $(this).val('mytestvalue')
        }
    }).inputmask("mask", {
        "mask": "99-99-99",
        showMaskOnFocus: true,
        showMaskOnHover: false,
        autoUnmask: true,
        clearMaskOnLostFocus: false
    });
    </script>

**Comment by RobinHerbots** [comment]
@DixonBY , 

Can you retest with the latest version or make a jsfiddle if it isn't solved.

Robin

**Comment by dzhivtsov** [comment]
Another strange issue appeared. 

If clearMaskOnLostFocus equals true, than after hovering the input twice the input is cleared.

If clearMaskOnLostFocus equals false, than after blur the input the placeholder is not shown again.

http://jsfiddle.net/3xxGu/3/

Thanks,
Denis

**Comment by RobinHerbots** [comment]
Can you specify the browser and version as I cannot reproduce the problem on chrome & IE10

**Comment by dzhivtsov** [comment]
I reproduced this behavior on IE9 and IE8.

**Comment by RobinHerbots** [comment]
@DixonBY , 

I see what you mean. (ie9)  

I will have a look at it.
