### ISSUE TITLE
persian/arabic currency mask with regex

### ISSUE THREAD

**Issue by moonrider441** [RobinHerbots/Inputmask#2472]
Hi 
I implemented a regex for currency with persian/arabic/latin characters. but in output not showing in right pattern.

This is my pattern:
```
$element.inputmask({
    regex:'(?[0-9\u0660-\u0669\u06F0-\u06F9]{0,2})(,[0-9\u0660-\u0669\u06F0-\u06F9]{3})*'
});
```

when im typing in input, i see this output:
٨٩,٤٥٦,٧٨
٨٩,٤٥٦,٧
٨٩,٤٥
٨٩,٤

but the true output is like this:
٨,٩٤٥,٦٧٨
٨٩٤,٥٦٧
٨٩,٤٥٦
٨,٩٤٥
٨٩٤

What i missed ?
plz help me.

**Comment by RobinHerbots** [comment]
@moonrider441,

You are using a lookahead in the regex, so the syntax should be 

$element.inputmask({
    regex:'(?**=**[0-9\u0660-\u0669\u06F0-\u06F9]{0,2})(,[0-9\u0660-\u0669\u06F0-\u06F9]{3})*'
});

But also the lookahead syntax is currently not implemented.

	case "(?=": //lookahead
				break;
			case "(?!": //negative lookahead
				break;
			case "(?<=": //lookbehind
				break;
			case "(?<!": //negative lookbehind
				break;

But I will see if I alradu can add a simple lookahead implementation.

Also,

٨٩٤  is that the equivalent of 123 ??  Sorry but I have no notion of how persian or arabic characters should look like.  But I guess I can test this with latin characters?

**Comment by moonrider441** [comment]
@RobinHerbots
Tnx for reply.
Yes ٨٩٤ is that the equivalent of 894 and the persian and arabic currency format is same as latin currency format.
and i told you i want the currency format in persian/arabic/latin language that all of them are same as current currency alias format.
look at this example::
latin format: 
12,000,000,000
persian format: 
۱۲,۰۰۰,۰۰۰,۰۰۰
arabic format:
۱۲,۰۰۰,۰۰۰,۰۰۰

I finded the currency format regex from stackoverflow and when the page is loaded in edit mode this regex are working fine but when im typing it has problem. 

Your currency alias work fine in all mode (edit mode and typing mode) but not support these "\u0660-\u0669\u06F0-\u06F9" ascii codes.
if your currency alias support the persian/arabic ascii codes my problem will be solve.

**Comment by RobinHerbots** [comment]
@moonrider441 ,

Can I parse or convert the ۱۲,۰۰۰,۰۰۰,۰۰۰ to 12,000,000,000 somehow?  Also do you want the format to one of the 3 above or that you can type all types?

**Comment by moonrider441** [comment]
@RobinHerbots 

> Can I parse or convert the ۱۲,۰۰۰,۰۰۰,۰۰۰ to 12,000,000,000 somehow? 

Yes you can do it but its not necessary.

--------------------------------------------------

> Also do you want the format to one of the 3 above or that you can type all types?

Your currency format is true and work fine but you just accept latin numeric ascii.
I suggest you to accepting **persian/arabic numbers ascii code** in all numeric alias like currency alias.

**Comment by moonrider441** [comment]
Hi again
@RobinHerbots

did u do any update for persian and arabic character in currency mode ?
i need this option in my project

**Comment by RobinHerbots** [comment]
@moonrider441 ,

I pushed some change to the number alias extension, to easily add the extra chars.
Can you already prepare a jsfiddle or alike with the currency alias.  I will add the changes to have some tests if it works that way.

**Comment by RobinHerbots** [comment]
@moonrider441 ,

Kan you have some tests with the latest version from github

**Comment by moonrider441** [comment]
@RobinHerbots 

Hi and tnx for updating. 
I tested and it work fine.
tnx <3
