### ISSUE TITLE
mask with repeat : 

### ISSUE THREAD

**Issue by rharsh** [RobinHerbots/Inputmask#2473]
Robin
Thanks for the excellent inputmask. Only one issue when giving
$(".mask-pattern").inputmask({ "mask" : "AAAA,",  "repeat" : 4,  "greedy" : false, "placeholder" : " " })

I have defined what A stands for, and its working fine, however by repeat = 4  and greedy = false, the mask gives
[    ,    ,    ,    ,]  : I thought the repeat mask would only repeat if required, so the mask should have been
[    ,] only and if a user types something after the , then only the mask will be repeated. Not a big problem, but I thought I will just point it out. 

Or does the repeat & greedy only work with masks of single character - like you have shown in examples viz.
9 repeat= 5 greedy=false, -- > will give either 9 or 99 or 999 or 9999 or 99999

Regards

**Comment by RobinHerbots** [comment]
@rharsh , 

Have a try with
```
$(".mask-pattern").inputmask({"mask": "(AAAA[,]){0,4}", jitMasking: true})
```

**Comment by chungyentsai** [comment]
Robin,

Thank you for the excellent library, it has saved me a lot of work. 
Currently, I am trying to use data-inputmask for a list of emails separated by ", ". 

My extendDefinitions are:
'*': {
    validator: "[0-9A-Za-z!#$%&'*+/=?^_`{|}~\-]",
    casing: "lower"
}

i'm trying with this, but it's not working properly
'mask': '({1,20}[.{1,20}][.{1,20}]**[.{1,20}]**@{1,20}[.{1,10}][.*{1,2}][, ]){1,5}'

It forces me to reach 20 characters in the [.{1,20}] portion before the @ and i can't skip any optional [ ]

now im using 
*{1,20}[.*{1,20}][.*{1,20}][.*{1,20}]@*{1,20}[.*{1,10}][.*{1,2}][, ][*{1,20}[.*{1,20}][.*{1,20}][.*{1,20}]@*{1,20}[.*{1,10}][.*{1,2}][, ][*{1,20}[.*{1,20}][.*{1,20}][.*{1,20}]@*{1,20}[.*{1,10}][.*{1,2}][, ][*{1,20}[.*{1,20}][.*{1,20}][.*{1,20}]@*{1,20}[.*{1,10}][.*{1,2}][, ][*{1,20}[.*{1,20}][.*{1,20}][.*{1,20}]@*{1,20}[.*{1,10}][.*{1,2}][, ][*{1,20}[.*{1,20}][.*{1,20}][.*{1,20}]@*{1,20}[.*{1,10}][.*{1,2}][, ]]]]]]

where the structure is:  mask[optional[optional[optional[optional]]]]
