### ISSUE TITLE
Prevent/Not allow decimal (comma) input

### ISSUE THREAD

**Issue by RayhanYulanda** [RobinHerbots/Inputmask#2474]
I need to add just integer prevent the decimal value (in my case prevent to typing `,`). i tried delete the radixpoint property, but it can't read the group separator. Is it possible to make it with this package?
```
$("#area").inputmask('numeric', {
            radixPoint:",",
            groupSeparator: ".",
            allowMinus: false,
            unmaskAsNumber: true,
            removeMaskOnSubmit: true,
            inputType: "number",

            autoUnmask: true,
        })
```
- OS: Windows 10
- Browser : Chrome
- Inputmask version : 5.0.5

**Comment by RobinHerbots** [comment]
@RayhanYulanda , 

Use the integer alias.
```
$("#area").inputmask('integer');
```
