### ISSUE TITLE
How to define default settings?

### ISSUE THREAD

**Issue by levipadre** [RobinHerbots/Inputmask#2477]
Is there a way to define default settings, so I don't have to add to every inputmask, only when I need to override?
Like every inputs have these settings for me:
`showMaskOnHover: false,
  showMaskOnFocus: false,
  placeholder: ''`

**Comment by RobinHerbots** [comment]
@levipadre , 

Sometimes you need to read the readme  ;-)

https://github.com/RobinHerbots/Inputmask#set-defaults

**Comment by levipadre** [comment]
Thank you, I missed it somehow.
