### ISSUE TITLE
InputMask for Phone Number accepts also text !

### ISSUE THREAD

**Issue by AWIXOR-zz** [RobinHerbots/Inputmask#2479]
- Describe the bug

If you use the inputmask for the phone number, the input will also accept letters and this should not be possible, only numbers must be accepted.

- Inputmask version
 `"inputmask": "^5.0.5"`

**Comment by RobinHerbots** [comment]
@AWIXOR ,

Can you give an example of the mask used.

**Comment by AWIXOR-zz** [comment]
Hey @RobinHerbots  this is an example with surveyjs:  [Demo](https://surveyjs.io/Examples/Library/?id=custom-widget-inputmask&platform=jQuery&theme=modern#content-result)

letters are also accepted on the phone number inputmask.

**Comment by RobinHerbots** [comment]
@AWIXOR , 

After exwploring the code from surveyjs a bit I found they use this mask as phone: , {
+#(###)-###-####

When I look in the Inputmask.Extensions.js I wee the definition for #272 


	"#": { //hexadecimal
		validator: "[0-9A-Fa-f]",
		casing: "upper"
	}
