### ISSUE TITLE
Datetime alias with day auto-fill problem

### ISSUE THREAD

**Issue by eduardo-mior** [RobinHerbots/Inputmask#2480]
When you press any number greater than 3 it automatically substitutes the value for 01. This worked perfectly until version 5.0.6-beta.29, in this version the auto-filling of 0 stopped working. In version 5.0.6-beta.31 the auto-completion of 0 is back in operation but with problems. On the day he has this problem that replaces the number with 01, in the month it works well.

https://user-images.githubusercontent.com/32434418/109884209-5ed7c800-7c5b-11eb-86f4-2487cd13cabb.mov

```javascript
$(`#myDateField`).inputmask("datetime", {
      inputFormat: "dd/mm/yyyy",
      jitMasking: true,
      showMaskOnHover: false
});
```

- OS: Any
- Browser Any
- Inputmask 5.0.6-beta.40

**Comment by RobinHerbots** [comment]
@eduardo-mior , 

Thx for the notifying me about this.

Fix in 5.0.6-beta.42
