### ISSUE TITLE
Mask ignored for inputs with `type` set to `email`

### ISSUE THREAD

**Issue by hitmanmcc** [RobinHerbots/Inputmask#2489]
Hello. I was playing around with your library and I came across an issue with masks.
It seems like masks are ignored in `input`'s with attribute `type` set to value `email`.

**Here is an example for an `input` with `type="text"`, which works fine and applies the casing rule I want to have applied, which is to see all letters to lowercase:**
- https://codepen.io/hitmanmcc/pen/RwozXjV

**And here is an example for an `input` with `type="email"`, which does not work as expected, you can type in uppercase letters which means the mask is not being applied:**
- https://codepen.io/hitmanmcc/pen/MWbMNEx

Additional details:
- OS: Mac OS Big Sur version 11.2.3
- Browser: Chrome Version 89.0.4389.90 (Official Build) (x86_64)
- Inputmask version: 5.0.3 (also tested with 5.0.5)

I don't know if this is expected behaviour or not, so that's why I'm inquiring. Thanks.

**Comment by hitmanmcc** [comment]
Perusing through your code I see you have a check for input type and I see you have a list of supported types: `supportsInputType: ["text", "tel", "url", "password", "search"]`. Any particular reason for not including email here?

**Edit:** I guess it's related to this issue: https://www.w3.org/Bugs/Public/show_bug.cgi?id=24796

**Comment by RobinHerbots** [comment]
@hitmanmcc , 

Exactly.
https://html.spec.whatwg.org/multipage/input.html#do-not-apply
![image](https://user-images.githubusercontent.com/318447/112318413-4e8c9900-8cad-11eb-8bb4-d36691296a8c.png)
