### ISSUE TITLE
Multiple Masks Stopped to Work : after commit # a6192ba278

### ISSUE THREAD

**Issue by robsoncombr** [RobinHerbots/Inputmask#249]
Hello Robin,

After the last commit, my Multiple Masks field stopped to work.

https://github.com/RobinHerbots/jquery.inputmask/commit/a6192ba27828a3385ab692822968fa7c02f18c4a

I have the following setting: $(selector).focusin(function() { $(this).inputmask({ mask: ["999.999.999-99", "99.999.999/9999-99"], placeholder:" ", clearIncomplete: true }) });

Also tried: $(selector).focusin(function() { $(this).inputmask({ mask: ["999.999.999-99", "99.999.999/9999-99"] }) });

It was working before, if you enter less than 11 chars it is considered incomplete, 11 chars it assumes the first mask, more than 11 and less than 14 incomplete, 14 second mask.

The problem is that it ignores the second mask, just the first one works.

Robson.

**Comment by RobinHerbots** [comment]
@robsoncombr , 

I will have a look ;-)

**Comment by RobinHerbots** [comment]
Why do you use the focuin?

Anyway I just tested your mask and it cleared when the active mask is incomplete and otherwise not.

Can you describe the problem better or create a jsfiddle to point to the problem.
Best regards, 

Robin

**Comment by robsoncombr** [comment]
Hello Robin,

The problem is not related with the 'clear' event anymore, the problem here is that the second mask is ignored.

If I do: $(selector).inputmask({ mask: ["999.999.999-99", "99.999.999/9999-99"] });

It _just_ assumes the first mask 999.999.999-99 it does not allow me to type more than 11 characters.

http://jsfiddle.net/C4Qme/

**Comment by RobinHerbots** [comment]
You have to type as you think, ... try typing 12.34 when typing the dot (or space) as third character will make the switch to the other mask.

**Comment by RobinHerbots** [comment]
But I do notice another issue on deleting. 

I will fix that, already

**Comment by robsoncombr** [comment]
Oh, awesome.

I'm sure that it was automatically before, it was assuming the first mask until 11 char and second mask after 12 char. But well, it worked as you mentioned, I can type 123 and it assumes the first mask and 12. and it switches to the second mask.

Thanks.
