### ISSUE TITLE
jquery.inputmask.js not working in IE 11

### ISSUE THREAD

**Issue by bogdan0083** [RobinHerbots/Inputmask#2493]
- Describe the bug
The browser throws Syntax Error. I guess it's because of arrow functions usage in file: https://github.com/RobinHerbots/Inputmask/blob/5.x/dist/inputmask.js

Right at the start there are multiple arrow functions. I guess this is what causes the issue.

- Add a link to a codepen, jsfiddle or other example page which shows the problem
Unfortunately I can't add the link to jsfiddle or codepen because IE 11 is not supported on those js playgrounds but I'll try to find a way to provide the example.

- OS: Windows 7, 8.1
- Browser: Internet Explorer 11
- Inputmask version: 5.0.6-beta.50 (latest as of now)

Thank you in advance! ❤️

**Comment by bogdan0083** [comment]
I fixed the issue.

Initially I took the jquery.inputmask.js from the dist/ folder on this repo, but it turns out the files are not transpiled to es5 syntax there.

Downloading plugin directly from npm solved the issue.

**Comment by RobinHerbots** [comment]
@bogdan0083 , 

Hmm that should also work when taking the files from the distfolder.
Probably is this causes by switching to the terser minification.  I will need to check this.

**Comment by RobinHerbots** [comment]
@bogdan0083 ,
5.0.6-beta.51 from the dist folder should work again.
