### ISSUE TITLE
jitMasking removing a decimal after the comma

### ISSUE THREAD

**Issue by eduardo-mior** [RobinHerbots/Inputmask#2494]
Sorry for my English. I am Brazilian.
I am creating a number input.
I am using alias "decimal", and digits "2" and "jitMasking" true.
For some reason, the input only allows 1 decimal digit.
If I remove "jitMasking" it works correctly with the 2 decimal digits.

With jitMasking false:
```javascript
$("#floatInput").inputmask( {
    alias: "decimal",
    digits: 2,
    jitMasking: false
});
```
![image](https://user-images.githubusercontent.com/32434418/112347636-cb1b7980-8ca5-11eb-8c88-8e3de5d69941.png)

With jitMasking true (bug):
```javascript
$("#floatInput").inputmask( {
    alias: "decimal",
    digits: 2,
    jitMasking: true
});
```
![image](https://user-images.githubusercontent.com/32434418/112347985-23eb1200-8ca6-11eb-8c89-28e86d4e2ec1.png)

- OS: Any
- Browser: Any
- Inputmask version **5.0.6-beta.50**

**Comment by eduardo-mior** [comment]
Any news?

**Comment by eduardo-mior** [comment]
Any predictions of when this can be corrected?

**Comment by RobinHerbots** [comment]
@eduardo-mior, 

The issue is fixed.

**Comment by eduardo-mior** [comment]
Worked perfectly.
