### ISSUE TITLE
Does a map file exist?

### ISSUE THREAD

**Issue by VARGA-Peter** [RobinHerbots/Inputmask#2496]
Is there a map file which can be included? I am referring to this Chrome Inspector message:

`DevTools failed to load SourceMap: Could not load content for https://rawgit.com/RobinHerbots/Inputmask/5.x/dist/jquery.inputmask.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE`

**Comment by RobinHerbots** [comment]
I removed the option for the production build.  So future versions won't show the message.
