### ISSUE TITLE
skipRadixDance breaks decimal input with and without group separator

### ISSUE THREAD

**Issue by pdecat** [RobinHerbots/Inputmask#250]
Using [the latest 2.x bundle](https://github.com/RobinHerbots/jquery.inputmask/blob/2880d4a7a9d8a08aaa319ba9b0f66c4f0006b010/dist/jquery.inputmask.bundle.js), the skipRadixDance option breaks decimal input with and without group separator.

The most noticeable effect is the misplacement of the radix separator (without grouping) or its vanishing (with auto grouping).
- OK: data-inputmask="'alias': 'decimal'"
  input : 12345.67
  result : 12345.67
- KO: data-inputmask="'alias': 'decimal', 'skipRadixDance': 'true'"
  input : 12345.67
  result : 1234567.
- KO: data-inputmask="'alias': 'decimal', 'groupSeparator': ' ', 'autoGroup': 'true', 'skipRadixDance': 'true'"
  input : 12345.67
  result : 1 234 567

**Comment by RobinHerbots** [comment]
@pdecat , 

Fixed in the latest version.  There is still an issue in decimals when setting a initial value, but I will fix that soon.  There is already an another issue open for that.

Robin

**Comment by pdecat** [comment]
Fix confirmed.

Thanks!
