### ISSUE TITLE
alias, regex error

### ISSUE THREAD

**Issue by cadot-info** [RobinHerbots/Inputmask#2503]
i use regex in alias, it's perfect and amazing but this regex can't run
Inputmask.extendAliases({
    'phone_fr': {
        regex: "^(0|\+33 )[1-9] ([-. ]?[0-9]{2} ){3}([-. ]?[0-9]{2})$",
    }
});

i use chrome on linux.

**Comment by RobinHerbots** [comment]
Hi @eldinomick , 

Can you have a try with (notice the \\\\ before the +33)
```
'phone_fr': {
regex: "^(0|\\+33 )[1-9] ([-. ]?[0-9]{2} ){3}([-. ]?[0-9]{2})$",
}
});
```

**Comment by cadot-info** [comment]
Thank you very much !!
it run.

**Comment by RobinHerbots** [comment]
@eldinomick ,

Also thank you for the donation!!

**Comment by cadot-info** [comment]
it's small but if everybody same that, you are billionnaire ;-) 

InputMask it's a good job, thanks for your share. 

Good day, friend  

Le 2021-04-27 13:40, Robin Herbots a écrit :

> @eldinomick [1] , 
> 
> Also thank you for the donation!! 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [2], or unsubscribe [3].
 

Links:
------
[1] https://github.com/eldinomick
[2]
https://github.com/RobinHerbots/Inputmask/issues/2503#issuecomment-827540392
[3]
