### ISSUE TITLE
Entering a time before the declared "min time" is always valid?

### ISSUE THREAD

**Issue by mashedcreative** [RobinHerbots/Inputmask#2506]
- **Describe the bug**

I'm not sure if this is meant to be the case, or am defining it incorrectly, but I'm trying to restrict times for a simple time range. Between **12:00** and **21:00**. `max` seems to be working but `min` does not, I am able to insert times before `12:00`, see example below.

`var isValid = Inputmask.isValid('10:00', { alias: "datetime", inputFormat: "HH:MM", min: '12:00', max: '21:00' });
  console.log("isValid", isValid);  //is true - should be false?`

` var isValid = Inputmask.isValid('22:00', { alias: "datetime", inputFormat: "HH:MM", min: '12:00', max: '21:00' });
  console.log("isValid", isValid); //is false - this is correct`

- **Inputmask version** - Version: 5.0.6-beta.56

**Comment by RobinHerbots** [comment]
@mashedcreative ,

This is fixed in 5.0.7-beta.12
