### ISSUE TITLE
Cannot read property 'dependencyLib' of undefined

### ISSUE THREAD

**Issue by polyakov-developer** [RobinHerbots/Inputmask#2508]
Sometimes I have an error like this - "Cannot read property 'dependencyLib' of undefined at HTMLInputElement.ev". Until version 5.0.0, there is no such error.

- OS: macOS
- Browser: Chrome
- Inputmask version: 5.0.5

<img width="557" alt="Screenshot 2021-05-17 at 14 49 52" src="https://user-images.githubusercontent.com/51357467/118484443-e5ab2580-b71f-11eb-9bb4-597225ca6897.png">
<img width="1372" alt="Screenshot 2021-05-17 at 14 49 36" src="https://user-images.githubusercontent.com/51357467/118484448-e6dc5280-b71f-11eb-874d-d0558b40d3cf.png">

**Comment by RobinHerbots** [comment]
@polyakov-developer ,

Duplicate issue see #2369
