### ISSUE TITLE
zero get's lost

### ISSUE THREAD

**Issue by ghost** [RobinHerbots/Inputmask#251]
please check this JSFiddle:

http://jsfiddle.net/mWPQX/

$( '#code' ).val('01060'); --> The Zero between 1 and 6 get's lost!

in minor version .18 it wors, but in .22/25/26 it didn't

Sam

**Comment by ghost** [comment]
in minor version .18 it worked, but in .22/25/26 it didn't

**Comment by RobinHerbots** [comment]
@wuSam , 

This is caused by the refactoring of the plugin.  I will fix this first priority.

Best regards, 

Robin

**Comment by RobinHerbots** [comment]
@wuSam 

Version 2.2.27 fixes the issue.

http://jsfiddle.net/mWPQX/2/
