### ISSUE TITLE
Accept comma or dot on Android

### ISSUE THREAD

**Issue by SergioSchimidtke** [RobinHerbots/Inputmask#2513]
In google crome for windows 10, you can type ("." or ",") and the conversion occurs automatically, regardless of the decimal separator used.

For Android only the decimal separator used is accepted.

Is it possible to get the same behavior as desktop on Android?

This will be particularly useful for Android devices that only show the "." on the numeric keypad.

**Comment by RobinHerbots** [comment]
@SergioSchimidtke ,

This should work with version 5.0.7
