### ISSUE TITLE
Why Inputmask prevent onChange React event after paste?

### ISSUE THREAD

**Issue by someden** [RobinHerbots/Inputmask#2514]
onChange event on input with mask doesn't fire after paste, is it a bug or there is some reasons for that?

<img width="402" alt="Screenshot 2021-06-03 at 11 53 51" src="https://user-images.githubusercontent.com/7009699/120618482-c9b7bb80-c463-11eb-816f-32a904df87dc.png">

Example: https://codesandbox.io/s/modest-shape-irzfg?file=/src/index.js
Inputmask version: 5.0.6

**Comment by hxdev** [comment]
Got the same problem with a credit card autocompletion, `oncomplete` or onChange will never call. Still didn't find the solution for this.

**Comment by hxdev** [comment]
I can reproduce this on the official demo page https://robinherbots.github.io/Inputmask/

On the `Date:` field, just try to paste this value `011290`, the `InComplete` will be called instead of `Complete`

**Comment by vildhjarta8** [comment]
+1, faced the same issue.

**Comment by mrAzay** [comment]
fix this, plz

**Comment by AMBULATUR** [comment]
+1, copy-paste don't work

**Comment by eduardo-mior** [comment]
I had the same problem.
To correct I did this: 
```javascript
Inputmask.extendDefaults({
    onBeforePaste: function () {
        if (this.el) {
            setTimeout(() => {
                $(this.el).trigger("input");
            }, 50);
        }
    }
});
```
This forces Inputmask to fire an input event after something is pasted. By default InputMask cancels the input event when someone pastes something.

**Comment by mankowitz** [comment]
@eduardo-mior didn't work for me.

**Comment by eduardo-mior** [comment]
@mankowitz A few days ago InputMask was updated to fix this issue. Try using the latest beta version of InputMask in your project.
For me this works perfectly.

@mankowitz see https://github.com/RobinHerbots/Inputmask/pull/2543

**Comment by RobinHerbots** [comment]
@mankowitz , 

Have a try with the latest beta from npm.

Best regards,
Robin

**Comment by someden** [comment]
@RobinHerbots it doesn't work on 5.0.7-beta.18, there is no change event on paste and there is no value on input, but it should be
![Screenshot 2021-09-28 at 13 46 24](https://user-images.githubusercontent.com/7009699/135073539-313c0e52-d28c-42eb-8877-7445cb86028e.png)
https://codesandbox.io/s/youthful-dream-q4rrw

**Comment by RobinHerbots** [comment]
@someden , 

Another fix, broke things ;-)  I pushed version 5.0.7 beta 19

**Comment by RobinHerbots** [comment]
There also seems to be a difference between the behavior of the react onchange and the native one.  See updated codesandbox.
https://codesandbox.io/s/morning-star-zfftj?file=/src/index.js

**Comment by someden** [comment]
Yep, Inputmask prevent onChange React event, not native. So, it would be good if Inputmask will consider this react event somehow
