### ISSUE TITLE
Datetime format not proper

### ISSUE THREAD

**Issue by sampathkumarm** [RobinHerbots/Inputmask#2515]
I am trying to format the **new Date()** to **08/06/2021 11:00:00 AM PDT** format but unsuccessful. Below is the codepen to reproduce the issue.

https://codepen.io/msampathkumar/pen/KKWBmrO

Please help resolve the issue.

OS: Windows
Browser: Chrome
Inputmask version (5.0.6)

**Comment by GKersten** [comment]
I am seeing the same issues, curious if there is any update about this

**Comment by RobinHerbots** [comment]
@sampathkumarm , @GKersten,

Can you have a try with the latest version.  5.0.7-beta.40
