### ISSUE TITLE
set <input value=""> and apply mask problem with decimal and custom radix point

### ISSUE THREAD

**Issue by jhnwsk** [RobinHerbots/Inputmask#252]
Hi Robin,

The input masks work awesomely for me when the default value is not set. However, I am struggling with this. I mask my currency inputs like thin on body load.

``` javascript
var handleInputMasks = function (container) {
    $.extend($.inputmask.defaults, {
        'autounmask': true
    });
    $(".mask-currency", container).each(function (i, obj) {
        $(obj).inputmask(
            {
                alias: 'decimal',
                radixPoint: ',',
                digits: 2,
                autoGroup: true,
                groupSeparator: ".",
                rightAlignNumerics: false
            });
    });
```

In my body, I have an input field 

``` html
<input type="text" class="mask-currency" placeholder="0,00" value="100,00" name="money">
```

I'd expect it to show up as `100,00` but unfortunately it does show as `10.000`. I am guessing the radix point `,` got ignored. The same behaviour occurs if the inputs value uses the usual `.` as the radixPoint.

So I decided to try and set the input mask AFTER setting the value with jQuery.

``` javascript
function setMaskedMoney(number, field) {
        field.val(number.toFixed(2).replace(".", ","));
        field.inputmask(
            {
                alias: 'decimal',
                radixPoint: ',',
                digits: 2,
                autoGroup: true,
                groupSeparator: ".",
                rightAlignNumerics: false
            }); //123456  =>  € ___.__1.234,56
    }
```

Regardless of what I do with the `number` all the dots and points are skipped and just the number gets masked with autogroupping.

Am I missing something? Or is this some kind of bug?

Thanks!

**Comment by RobinHerbots** [comment]
@jhnwsk , 

It's an issue whitin checkval.

I will fix this soon.

Robin

**Comment by jhnwsk** [comment]
@RobinHerbots,

Hey, thanks for checking. I did a little bit of debugging and my assumption was that while parsing the existing value for an input the decimal extension within the `definitions` this code:

``` javascript

if (isValid != false && !strict && chrs != opts.radixPoint) {
    var newPos = opts.postFormat(buffer, pos + 1, false, opts);
    return { "pos": newPos };
}
```

does not move the position when it hits the `radixPoint` and then after the `groupSeparator` gets added we kind of get trapped, never passing the radix point.

On the other hand I also saw that the `radixPoint` has a special behaviour going on when it's being input in live mode.

``` javascript

if (opts.numericInput && c == opts.radixPoint) {
    var nptStr = input._valueGet();
    var radixPosition = nptStr.indexOf(opts.radixPoint);
    caret(input, seekNext(radixPosition != -1 ? radixPosition : getMaskLength()));
}
```

so I was guessing that maybe this is missing from "passive mode" where the entire value is already there. Hence the radixFandango ;) Actually removing `autogroup` and `groupSeparator` fixes all problems.

There's another thing. If you just set `groupSeparator` to '.' for example. And place the caret so as to change `20|00,22` to `20200,22` what you get instead is `20020,22`. Meaning, the insertion happens after the digit right to the caret. Is that a separate issue?

Maybe I'm just blurring your perception of this actually. I am a jQuery newbie :)

**Comment by RobinHerbots** [comment]
@jhnwsk , 

What you describe is fixed in the latest version..

**Comment by jhnwsk** [comment]
@RobinHerbots,

Cool! I'll download and test it right away.

**Comment by RobinHerbots** [comment]
@jhnwsk , 

The latest should fix the initial value.
