### ISSUE TITLE
set value without triggering any event

### ISSUE THREAD

**Issue by avalon1412** [RobinHerbots/Inputmask#2521]
I have some problem, i wanna set value without triggering any event.
this because i wanna make input decimal, which can use . or , key
when , key pressed i modify element value directly with adding . char
that already work but problem when i press on end input, it cant modify input because triggering masking function.
ex. 
12(cursor here)3 then i press , key, it success change value to 12.3
but if
123(cursor here) then i press , key, it supposed change to 123, but it not work
so i wanna know if there any solution for changing value without triggering masking event

**Comment by RobinHerbots** [comment]
@avalon1412 ,

With version 5.0.7 the decimal substitues , and . already out-of-the-box.
