### ISSUE TITLE
Numeric mask limit not working with digits

### ISSUE THREAD

**Issue by lebadapetru** [RobinHerbots/Inputmask#2522]
Inputmask version: `5.0.6`

I cannot limit the integer part of the value and i couldn't find any answers to it. I don't know if it's a bug but i would appreciate some help

```
Inputmask({
        groupSeparator: false,
        radixPoint: '.',
        alias: "numeric",
        placeholder: "0",
        autoGroup: true,
        integerDigits: 9,
        digits: 2,
        digitsOptional: false,
        numericInput: true,
        clearMaskOnLostFocus: false
      }).mask(el.value);
```

**Comment by RobinHerbots** [comment]
@lebadapetru , 

The integerDigits option is removed.  You can use the min and max instead.  Have a look at the readme.

**Comment by cah-brian-gantzler** [comment]
Note that integerDigits is still being used in tests https://github.com/RobinHerbots/Inputmask/blob/5.0.8-beta.17/qunit/tests_setvalue.js#L51
