### ISSUE TITLE
Add new option "stripLeadingZeroes" to the numeric extension

### ISSUE THREAD

**Issue by olegbaturin** [RobinHerbots/Inputmask#2523]
Leading zeros are always stripped. Add new option **stripLeadingZeros** with default value true to the numeric extension.

[Here](https://github.com/RobinHerbots/Inputmask/blob/e675abbc54e5aa37d1cc05d8b5cb8777362d6c03/lib/extensions/inputmask.numeric.extensions.js#L501) we can add an option **stripLeadingZeroes** check and skip leading zeros stripping if it false.

**Comment by RobinHerbots** [comment]
Hi @olegbaturin,

Done!  (finally)
