### ISSUE TITLE
hh:ss mask not working

### ISSUE THREAD

**Issue by nikhiltechnology** [RobinHerbots/Inputmask#2525]
$('.hourminute').inputmask(
        "mm:ss", {
        placeholder: "MM:SS", 
        insertMode: false, 
        showMaskOnHover: false
    });

- Describe the bug - Not taking input
- OS: windows,linux
- Browser : firefox
- Inputmask version - 3.3.11

**Comment by RobinHerbots** [comment]
Did you tried with the latest version?
