### ISSUE TITLE
Little help - decimal & thousands seperator

### ISSUE THREAD

**Issue by bassti1** [RobinHerbots/Inputmask#2528]
Hi

I am a complete newbie, so apologies for outlayer request. This project is included in WP's eform and lacks support there.

I would appreciate if anyone would help me write a RegEx mask code, which would add thousand separators and decimal separator to numbers.

The desired end-result (numbers) look like this:
1,000,000.40
5,000.30
100.00
(additional requirement: before typing in, nothing is shown)
(additional requirement: if decimal numbers are not typed in, they show as 00)

I was advised to go with 9,999,999.99 but when empty it shows commas and a dot. It also requires decimals to be written in. 

Thanks in advance for help.

Peter

**Comment by RobinHerbots** [comment]
Hi @bassti1 ,

Have a read at https://github.com/RobinHerbots/Inputmask/blob/5.x/README_numeric.md

**Comment by bassti1** [comment]
Hi @RobinHerbots 

Thank you for your reply. I don't find the solution on the link you've provided. 

I believe there should be a super easy solution to my problem, or?

**Comment by RobinHerbots** [comment]
```
Inputmask("currency").mask("test1");
```

**Comment by bassti1** [comment]
I tried to insert it as presented below and it does not work ..
https://ibb.co/H2YH3fj

**Comment by RobinHerbots** [comment]
Is that using inputmask underneith?

If so try tot only enter currency.
