### ISSUE TITLE
crash the input value

### ISSUE THREAD

**Issue by sandrey1** [RobinHerbots/Inputmask#2529]
- Describe the bug

| - is cursor mark.

Use $('input').inputmask({mask: 'a{+} XYZ 9'});

I. crash the input value

1. Type "abcd1" (result "abcd XYZ 1|")
2. Press left arrow ("abcd XYZ |1"), shift+home, del (result "|_ XYZ 1")
3. Type "abc" and uuups - result "abc| XY1" (no Z)
4. Type "de" - result "abcde| 1" (no " XYZ")

II. and more

1a. Paste from buffer "abcd1" (result "abcd XYZ 1|")
2a. Press left arrow, backspace (result "abcd| XYZ 1")
All ok. And now
1b. Paste from buffer (or set value) "abcd XYZ 1" (result "abcd XYZ 1|")
2b. Press left arrow, backspace and uuups - result "abcd XYZ |1"
3b. Press backspace, backspace (result "abcd XY|Z 1")

- OS: Windows
- Browser: Chrome, FF
- Inputmask version 5.0.6
- jquery version 3.6.0

**Comment by RobinHerbots** [comment]
@sandrey1 ,

Thx for the issue.  I will investigate this.

**Comment by RobinHerbots** [comment]
@sandrey1 ,

Fixed in Version: 5.0.8-beta.76
