### ISSUE TITLE
Different behaviour configuration by attribute vs initialization

### ISSUE THREAD

**Issue by mikeleber** [RobinHerbots/Inputmask#2530]
I want to set the output format via data-attribute-outputFormat but i can´t get it work. It´s working for direct initialization but not with the attribute. Here my fiddle showing the problem: https://jsfiddle.net/mike_leber/upms95kg/10/

Would be nice if you can get me a little hint :-)

**Comment by mikeleber** [comment]
Any news/planings in thus issued?

**Comment by RobinHerbots** [comment]
@mikeleber,

The issue is fixed in version 5.0.7-beta.32

**Comment by mikeleber** [comment]
Great news, many thanks :-)
