### ISSUE TITLE
min doesnt work in datatime in "H2:MM" format

### ISSUE THREAD

**Issue by kamilpinas** [RobinHerbots/Inputmask#2532]
Hi.
There is a problem with datatime alias and format **H2:MM**.
max prop works very well but when i declare min i still can input **00:00** like it doesnt even work
```
Inputmask({
            
            alias:'datetime',
            inputFormat:'H2:MM',
            placeholder:'0',
            min:'12:59',
            max:'33:33',
            insertMode: false,
            insertModeVisual: true,
            shiftPositions: false,
            clearMaskOnLostFocus: false,
            preValidation,
        })
```

- OS: windows 10
- Browser : Opera/chrome
- Inputmask version : 5.06

**Comment by RobinHerbots** [comment]
@kamilpinas ,

This is fixed in version 5.0.7-beta.12
