### ISSUE TITLE
"^0|\\d{2}\\.\\d{2}\\.\\d{4}$" doesn't  allow to type a date starting with "0".

### ISSUE THREAD

**Issue by Granada2013** [RobinHerbots/Inputmask#2536]
Hello!
In my project I have a date field that can be filled with 0 (if the date is unknown) or a date format dd.mm.yyyy otherwise,
To mask this field I use the following regex: {regex: "^0|\\d{2}\\.\\d{2}\\.\\d{4}$" }.
The problem occurs if I want to type a date starting with 0 (eg. 01.12.2021) - it allows to type 0 and thats all.
What can I do with this problem?

version 5.0.6

**Comment by RobinHerbots** [comment]
@Granada2013 , 

Have a try with this:
```
		Inputmask({
			regex: "[0]|[0-9]{2}\\.[0-9]{2}\\.[0-9]{4}",
            keepStatic: true
		}).mask("test2");
```
