### ISSUE TITLE
Cant type dot on iphone

### ISSUE THREAD

**Issue by vasiliysmirnov** [RobinHerbots/Inputmask#2541]
- Describe the bug
Cant type dot on iphone on your demo page (inputmode="decimal")

- Add a link to a codepen, jsfiddle or other example page which shows the problem
https://robinherbots.github.io/Inputmask/
- OS: iPhone 12 Pro (in browserstack)
- Browser (safari)
- Inputmask version - in source code there are 5.x

<img width="482" alt="Screenshot 2021-08-24 at 15 25 29" src="https://user-images.githubusercontent.com/13482625/130616650-fb903692-27a3-4ec3-831a-780eb4a77ce4.png">

**Comment by RobinHerbots** [comment]
@vasiliysmirnov ,

I see, i will fix this in the coming days.
Also see #2542

**Comment by RobinHerbots** [comment]
@vasiliysmirnov,

Can you have a try with version 5.0.7-beta.18
