### ISSUE TITLE
How can I replace the dot for comma while tipping?

### ISSUE THREAD

**Issue by andref98** [RobinHerbots/Inputmask#2542]
_class_input.Add("data-inputmask", " 'digits': 2, 'radixPoint': ',', 'alias': 'decimal', 'rightAlign': false, 'groupSeparator': ' ', 'placeholder': ' ', 'autoUnmask': true, 'onUnMask': 'mask1', 'onBeforePaste': 'paste'");

I am creating the mask by attributes, and If the user types a dot I want that in the input appears a comma. 
Thank you for your time.

**Comment by RobinHerbots** [comment]
@andref98

I will create a substitute list as an option, which contains substitutes for entered chars.  In the numeric alias I wil add , and . as substitutes.

**Comment by RobinHerbots** [comment]
Hi @andref98,

I added the substitutes option and for the decimal alias it is added automatically.

Have a try with 5.0.7-beta.18
