### ISSUE TITLE
Issue with global Inputmask.prototype reference (easy fix)

### ISSUE THREAD

**Issue by antch** [RobinHerbots/Inputmask#2544]
**Description:** Using inputmask in certain build environments can cause a JavaScript error when calling `mask()`:
```
core.js:4352 ERROR TypeError: Inputmask.prototype.analyseMask is not a function
    at generateMask (mask-lexer.js:40)
    at generateMaskSet (mask-lexer.js:91)
    at inputmask.js:87
    at Array.forEach (<anonymous>)
    at Inputmask.mask (inputmask.js:84)
```

**Reproduction:** I don't have one, but hopefully the issue is apparent. This is occurring when using Inputmask from an Angular Custom Element that imports via ES6 `import`.

**Browser:** Chrome 92
**Inputmask version:** 5.0.6

**Analysis:**

I troubleshot this issue for awhile, and only after I changed my import to `node_modules/inputmask/bundle` did I see the more helpful stack trace above. This is happening because `Inputmask` is exported to window in [`inputmask.js`](https://github.com/RobinHerbots/Inputmask/blob/5.x/lib/inputmask.js#L354), but is not imported in [`mask-lexer.js`](https://github.com/RobinHerbots/Inputmask/blob/5.x/lib/mask-lexer.js) which means that the `Inputmask.prototype` being imported is the one from `window.Inputmask` -- this does not have an `analyseMask` function in my environment.

**Fix:**
By explicitly importing in `mask-lexer.js`, the error goes away:
```
import Inputmask from './inputmask';
```

**Comment by RobinHerbots** [comment]
@antch , 

Thx for the issue!  I will submit a patch asap.

**Comment by antch** [comment]
Thank you for getting to this so quickly. Just FYI, I also ran into #2285 and this `import` fixes that as well, at least for me.
