### ISSUE TITLE
Issue with leapday 

### ISSUE THREAD

**Issue by thekapit4n** [RobinHerbots/Inputmask#2546]
after i update the library to latest version (Version: 5.0.7-beta.15), I notice now datetime input not properly handle leap year . Its allow user to enter all the year when even though already fill in :  29/02/yyyy.

i use file "inputmask.js" and declare using vanilla javascript, below is my initialization :

var selectorDOB = document.getElementById("dob");
Inputmask('datetime',{
    alias 		 :'datetime',
    inputFormat  : "dd/mm/yyyy", 
    outputFormat : "dd/mm/yyyy",
    separator: '/',
    leapday: "29/02/",
}).mask(selectorDOB);

HTML
<input type="text" class="form-control" id="parentdob" name="question_1" required="" style="min-width: 100%;" /> 

Thank you in advance.

**Comment by RobinHerbots** [comment]
@thekapit4n ,

This should be fixed in version 5.0.7-beta.23

**Comment by thekapit4n** [comment]
Hi @RobinHerbots , thank you for your response. yes now this issue has been fixed. cheers!!
