### ISSUE TITLE
I using dynamic mask but I can't working "allowMinus" option

### ISSUE THREAD

**Issue by ozknozsrt** [RobinHerbots/Inputmask#2547]
- Describe the bug

Hello there,

I using mask as that:

This for integer input

```js
input.inputmask("(.999){+|1}", {
	positionCaretOnClick: "radixFocus",
	radixPoint: ".",
	_radixDance: true,
	numericInput: true,
	allowMinus: true,
	placeholder: "0",
	definitions: {
		"0": {
			validator: "[0-9\uFF11-\uFF19]"
		}
	}
});
```

This also for decimal input

```js
input.inputmask("(.999){+|1},99999", {
	positionCaretOnClick: "radixFocus",
	radixPoint: ".",
	_radixDance: true,
	numericInput: true,
	placeholder: "0",
	definitions: {
		"0": {
			validator: "[0-9\uFF11-\uFF19]"
		}
	}
});
```

I defined in this way but i can't insert minus sign.
There is a certain solution or do you have an alternative solution?
Thanks

- Add a link to a codepen, jsfiddle or other example page which shows the problem
https://jsfiddle.net/fzuydsLm/

- OS: Windows 10
- Browser: Chrome 93.0.4577.63
- Inputmask version: 4.0.9
- jQuery version: 3.4.1

**Comment by RobinHerbots** [comment]
@ozknozsrt ,

The allowMinus options is from the numeric alias.  

See https://jsfiddle.net/yxdf13jb/3/  and use a newer version from the inputmask.

**Comment by ozknozsrt** [comment]
Thanks, this is as below I solved.

```js
$(input).inputmask({
    'alias': 'decimal',
    'radixPoint': ',',
    'groupSeparator': '.',
    'autoGroup': true,
    'rightAlign': false,
    'digits': 2,
    'suffix': ` $`,
    'digitsOptional': false,
    'placeholder': '0.00',
    'autoUnmask': true
});
```
