### ISSUE TITLE
Multiple masked inputs in the same page

### ISSUE THREAD

**Issue by Macharius92** [RobinHerbots/Inputmask#255]
Hi,

First let me thank you for this master piece of work ;)

The fact is i have a little problem not so easy to solve from my side. Let me explain. We have pages with two input fields in which we want the user to enter a time (format : hh:mm).

What we do is something like :

``` html
<span class="mask-hour">
  <input type="text" id="T1" />
  <input type="text" id="T2" />
</span>
```

and in the `$(document).ready`we are doing stuff like this :

``` javascript
$('input:text', '.mask-hour').inputmask('hh:mm', { clearIncomplete : true});
```

The issue is that when i'm typing a valid hour (like 13:37) in my T1 input and i move my mouse over the T2 input, the T2 input is automatically filled with the value entered in the T1 input.

From my understanding of your code, i think that the active buffer should be linked to the input and not global to the plugin...

I haven't time right now to make a correction but i will try to submit you something if you don't do it before me ;)

**Comment by Dalmadog** [comment]
Hi,
I'm a Macharius92 co-worker.

The activeMasksetIndex may have to be refreshed in mouseenter.inputmask, mouseleave.inputmask and maybe any other event bindings in jquery.inputmask.js, just before using any getActiveBuffer function just like this :

activeMasksetIndex = this.data('inputmask')['activeMasksetIndex']; // Missing line

The small problem is I haven't any single idea about sideeffects of these changes.

If you add this only in the hover events bindings, you'll fix the bug for entering a value in T1 then hovering over T2 and seing T1 copying in T2 but you'll have the same value copying from T1 to T2 when you clic in T2, so you may want to refresh activeMasksetIndex for focus/blur aswell... Maybe clicking...

Therefor having to check for more sideeffects if any.

**Comment by RobinHerbots** [comment]
@Macharius92 , @Dalmadog , 

The scoping should be fixed in the latest version.

**Comment by Dalmadog** [comment]
Thank you...

With activeMasksetIndex refreshing in all bindings, I see these problems :
- sideeffect #1 - refreshing activeMasksetIndex in each event binding solve the bugs but quite destroys the "clearIncomplete: true" behaviour.
- sideeffect #2 - clic in T1, then enter "12", then click in T2 then enter "13", all without doublequote.
  First textbox will be "12:__", second will be "13:12".
- sideeffect #3 (related to #2 i guess) - clic in T1, then enter "1234", then clic in T2 then hit the suppr. key.
  First textbox will be "12:34", second will be "23:4_".

That's all I see for the moment...

**Comment by RobinHerbots** [comment]
@Dalmadog , 

Can you confirm the fix? with version 2.2.32

**Comment by Dalmadog** [comment]
Yes mostly but
Clic in T1, enter "1234", then clic in T2 -> T1's value disapear.

If you then enter T2's value, you can have T1's value but if T2 is not initialized, T1's value can't be writen (or is considered incomplete and made "" back because of clearIncomplete : true)

**Comment by RobinHerbots** [comment]
@Dalmadog 

see issue 223

**Comment by Dalmadog** [comment]
It's in the onBlur of T1, the if (!isComplete(buffer)) is true and erase it. It works well for T2.

For information, if you got 3 textboxes, you can't input T1 or T2 until T3 is full. If T3 is empty, T1 and T2 will reset to empty no matter what you type.
After filling T3 then T1 and T2,if you clear T3, T1 and T2 does not auto-clear until clicking out each of them. In that situation, hovering over T1/T2 does not clear them.

**Comment by Dalmadog** [comment]
It's very strange, at line 741in the isComplete definition, in the case of 3 textbox T1, T2 and T3,
(T3 unfilled) after putting a full value, for T1 and T2, activeMasksetIndex is set at 0 (int), but for T3 activeMasksetIndex it's set at "0" (string).

If I try to convert all of activeMasksetIndex in string before copying in currentActiveMasksetIndex, that still doesn't work...

**Comment by Dalmadog** [comment]
This is not related to 223... This works the same on other types of mask.

If you can understand me because this is quite complex :
- The same behaviour with 3 "9999" masks.
- For one mask in 'aaaa', the second with '9999', the third with 'hh:mm', you can only fill the third and never the first or the second.
- For one mask in 'aaaaa', the second with '99999', the third with '*****', you fill T3, then T2, then clic in T3 remove one char in the middle, put another one at the same place and clic out => T2 and T3 are still filled.
  But, you fill T3, then T2, then clic in T3 remove one char in the middle, try to put it in the end (fail) and then come back put another one at the same place you first delete and clic out => T3 clears.

We were trying all of this because we were thinking that somehow, for the qualifying tests (not input validation "i can type letter", for "output" validation ie "I typed a valid hour") only the last mask qualifies the fields.

We also didn't understand which var contains the "current mask number".

**Comment by RobinHerbots** [comment]
@Dalmadog ,

Try again with version 2.2.33

**Comment by Macharius92** [comment]
@RobinHerbots 

I've just made a little test and everything seems fine ;) It's marvelous and even Wunderbahr !

I will make more tests tomorrow at work (can't access my app now) and i will close the issue if it's OK.

Many thanks for your help ;)

**Comment by Macharius92** [comment]
@RobinHerbots 

Nice it's working as expected with the scoping ! Issue solved ;)
