### ISSUE TITLE
Numeric shortcut not working for decimal places

### ISSUE THREAD

**Issue by gracykaur93** [RobinHerbots/Inputmask#2553]
Hello. I have a question. I can not find a solution.
We have below shortcuts available  for numeric data type,
 - "K"= 000 (three zeros) 
-  "M" = 000000 (Six zeros). 

eg :
5k.00 = 5,000.00
5m.00 =5,000,000.00
but if we write 
5.6k = 560.00
5.6m=560,000.00

Inputmask version: 5.0.6-beta.19

Thank you in advance for your response.

**Comment by RobinHerbots** [comment]
Hi @gracykaur93 ,

The inputmask sees the dot as a radixpoint and so jumps to the fraction part.  K and m just inserts 000 or 000000 without extra logic.

The K and M shortcutsq should be applied on the whole entry.  
I will see how to fix this.

**Comment by gracykaur93** [comment]
Thanks for the quick reply.
Will wait for the updated version.

**Comment by RobinHerbots** [comment]
@gracykaur93,

The issue is fixed in version 5.0.7-beta.41
