### ISSUE TITLE
Setting a value dynamically with document.getElementById().value

### ISSUE THREAD

**Issue by Macharius92** [RobinHerbots/Inputmask#256]
Hello again @RobinHerbots 

I'm not sure it's really an issue but i can't understand why it doesn't work. You wrote in the readme :

``` javascript
$(document).ready(function(){
   $("#number").val(12345);

   var number = document.getElementById("number");
   number.value = 12345;
});
```

In my page i have an masked input field wich is initially empty and a list of records below. When i'm clicking on one of the records i populate the fields above. I'm using custom javascript function called setValue (made years before to work with our own components) to set the value. It's done the old fashion way :

``` javascript
document.getElementById('myComponentId').value = '13:37';
```

When i'm using my function and i'm hovering the masked input field, it considers it as incomplete whatever the mask is. I've tested it with IE9 and Chrome 27.
If i'm using the jQuery way :

``` javascript
$('#myComponentId').val('13:37');
```

the mask is well completed and the field not emptied on hovering.

I hope  there's a trick to make it works because i can't rewrite my entire framework using jQuery instead of old fashioned javascript ;)

**Comment by RobinHerbots** [comment]
@Macharius92 , 

The value property patch works only if supported by the browser.  The fallback is the jquery val function which always work.

Feel free to suggest some solutions to hookup in the value property.  Firefox surely support the rewrite of properties like value.  I should invest some time to check the current status of support for it in the different browsers.

Best regards, 

Robin

**Comment by Macharius92** [comment]
@RobinHerbots 

Correct me if i'm wrong. You expose a val function on your objet which extends the jQuery val function by checking if the value is correct against the defined mask ?

So we should find a way to extend the 'standard' value property as you've done for the jQuery val() ?

**Comment by RobinHerbots** [comment]
@Macharius92 , 

Have a look at the function patchValueProperty.  It tries to rewrite the native value property and if it fails it patches the jquery val fn. The jquery.val patching should be rewritten as a valhook for jquery, but I haven't got the time yet..  Offcourse is the code above it the intersting part.

**Comment by Macharius92** [comment]
@RobinHerbots 

Seems like it's not so easy to make it fully cross browser compatible.

For what i saw till now, i think you have a problem with the getOwnPropertyDescriptor. The value of an input is a data property ant not an accessor property. (see [MSDN](http://msdn.microsoft.com/en-us/library/dd548686.aspx)) So the descriptor returned doesn't expose a get property. I haven't look further about the **defineGetter** but i think that there is the same problem.

Moreover, the behaviour is different between browsers. In IE9, it seems that the affectation of the valueProperty doesn't work. When i look at it with an alert, it shows undefined. In Chrome, it shows an Object as expected.

I think that an immediate workaround for my issue is to rely on jQuery to set values in my fields and i will try to explore a more cross browser solution if it's possible (i think that it will become harder if we look the behaviour on IE6/IE7/IE8...)

**Comment by RobinHerbots** [comment]
@Macharius92 , 

thx for the link.  I will read that one. And try to make at least a better implementation.

**Comment by RobinHerbots** [comment]
@Macharius92 , 

There is still room for improvement, but currently the fallback will cover most cases.
