### ISSUE TITLE
The requested module './inputmask.js' does not provide an export named 'default'

### ISSUE THREAD

**Issue by mr-layco** [RobinHerbots/Inputmask#2560]
Hi,

Not sure if this is me doing it wrong, or if there is an issue.

I have a html file which has a script tag of type=module to a javascript file i have created called 'testmask.js'.

```
<body>
   <input type="text" id="mask" />
   <script src="testmask.js" type="module"></script>
</body>
```
I have taken a copy of the vanilla js [inputmask.js](https://github.com/RobinHerbots/Inputmask/blob/5.x/dist/inputmask.js) file from the 'dist' folder and imported this into my 'mask.js' file using the es6 import as suggested in the [docs](https://github.com/RobinHerbots/Inputmask#in-your-modules) as per the below example

```
//es6
import Inputmask from "./inputmask.js";

var selector = document.getElementById("mask");

var im = new Inputmask("99-9999999");
im.mask(selector);
```

When loading the html file the following error appears in my console dev tools (Chrome)

```Uncaught SyntaxError: The requested module './inputmask.js' does not provide an export named 'default'```

Am i missing something with this?

Thanks,
Ian.

**Comment by RobinHerbots** [comment]
@mr-layco ,

Good question ;-)  It has propbably todo with the webpack libraryTarget which is currently umd.

**Comment by RobinHerbots** [comment]
@mr-layco ,

The import statement in the readme is in context of a module loader like webpack.  Not for using it directly as an es6 module.

**Comment by RobinHerbots** [comment]
@mr-layco ,

I will add an extra inputmask.es6.js file in the dist folder.

**Comment by mr-layco** [comment]
> @mr-layco ,
> 
> I will add an extra inputmask.es6.js file in the dist folder.

Thank you very much kind sir and thanks for an amazing inputmask :-)

**Comment by RobinHerbots** [comment]
@mr-layco , 

Can you have a try with the update?  copy both inputmask.js & inputmask.es6.js.
//es6
import Inputmask from "./inputmask.es6..js";

var selector = document.getElementById("mask");

var im = new Inputmask("99-9999999");
im.mask(selector);

**Comment by mr-layco** [comment]
Hi @RobinHerbots ,

Successfully tested with the example given.

I'll have a good play with it over the next few days and let you know if there are any issues (not that i think there will be).

Thanks for doing this.

:-)
