### ISSUE TITLE
Paste event doesn't trigger 'input' event

### ISSUE THREAD

**Issue by alexandrbig** [RobinHerbots/Inputmask#2563]
Hi @RobinHerbots, 

I've tried to investigate why paste doesn't work and stuck on [this line](https://github.com/RobinHerbots/Inputmask/blob/962bc9c3bce00ee9e005a6252f0df7ee92830946/lib/inputHandling.js#L149) of `checkVal` method.
This code is barely readable, but if you refactor it there are some variables:

```js
const caretPos = result ? result.forwardPosition : inputmask.caretPos.begin;
const event =  initiatingEvent || new $.Event("checkval")
const triggerEvents = initiatingEvent && (initiatingEvent.type === "input" || initiatingEvent.type === "paste") && inputmask.undoValue !== inputmask._valueGet(true);

writeBuffer.call(inputmask, input, getBuffer.call(inputmask), caretPos, event, triggerEvents);
```

So if take a look into `triggerEvents` variable we see last condition `inputmask.undoValue !== inputmask._valueGet(true)` which seems checks if the value of the input is not equal to `inputmask.undoValue` which equals to mask placeholder and prohibits triggering of events.

But within paste event `inputmask._valueGet(true)` returns the mask placeholder if the input was empty, even when the input (`this.el`) has proper value. It leads whole expression to become `false` and it doesn't trigger any other event.

![image](https://user-images.githubusercontent.com/2073337/140799529-00be8ba1-53a8-4a70-a56d-91d2dc5811d8.png)
Note: breakpoint in `_valueGet` on paste event, before `writeOut` of `checkVal`

* Could you check why `inputmask._valueGet(true)` returns the mask placeholder instead of inserting value?
* As a quick fix for paste event we could avoid check for the placeholder and use optional chaining:
```js
const triggerEvents = initiatingEvent?.type === "input" && inputmask.undoValue !== inputmask._valueGet(true) || initiatingEvent?.type === "paste";
```

https://github.com/ngneat/input-mask/issues/38

Please share your thoughts.

Thank you.

**Comment by RobinHerbots** [comment]
@alexandrbig ,

I did some investigation and it seems that the native input always trigger the input event after pasting, regardless wheter the value has changed.  I thought it only calls the input event when the value has actually changed.

I will change the behavior.

Sorry for the hassle.

**Comment by RobinHerbots** [comment]
@alexandrbig , 

Can you have a try with 5.0.7-beta.28

**Comment by alexandrbig** [comment]
Hello @RobinHerbots, 
I've tried locally with the git repository demo page, and it works! Input event fired on paste! :)

> Sorry for the hassle.

No worry, I am happy to help! 
Thank you for your great and fast work!

Could you release the fix to npm? 
Thank you in advance.

**Comment by RobinHerbots** [comment]
Done

**Comment by alexandrbig** [comment]
@RobinHerbots sorry for the late reply, but it works perfectly with angular app!

Thank you for your great work!!!
