### ISSUE TITLE
InsertMode toggle not functioning

### ISSUE THREAD

**Issue by ganjea** [RobinHerbots/Inputmask#2565]
Hey there,
during testing I've noticed that the insertMode toggle does not function.

Configuring "insertMode: true/false" works as expected, however during typing switching between those modes via the insert key (https://github.com/RobinHerbots/Inputmask#insertmode) is not toggling the mode. Tested with different Browsers on Windows 10.

A look through the open and closed issues did not yield any information. Additionally, a glance at the source code yields commented out code (https://github.com/RobinHerbots/Inputmask/blob/5e74affee5c2ad35a44774f5a855d4290e93de1d/lib/eventhandlers.js#L46).

The change seems to be have made with the commit https://github.com/RobinHerbots/Inputmask/commit/c02deef0041857a4779d4d5ca9d0f100edcc98a7.

Could you please clarify the status on the insertMode toggle?

**Comment by RobinHerbots** [comment]
@ganjea ,

I don't know why I commented the functionality.  I enabled it again and made some minor enhancement.

**Comment by ganjea** [comment]
Thank you for the honesty, quick response and fix!
