### ISSUE TITLE
hh:mm masks, Firefox and IE

### ISSUE THREAD

**Issue by Dalmadog** [RobinHerbots/Inputmask#257]
Hi again Robin,

First, thank you for your work yesterday, I think you solved a very important bug there.

This one is not a very important bug but I just wanted you to be informed.

I noticed some strange small bugs for Firefox 21.0 (on Win XP or Win7) that don't occurs in IE8 (XP) and IE9 (7). These may be related to #223

Reproduction steps :
If you have a hh:mm mask, you can type 12:34 inside. Then you delete the '2'. The value is now '13:4_'.

1st little problem, in both IE and Firefox you can't clic after the 4, you have to move there using the keys.

2nd little problem, when after the '4', in FF you can't type a '5', in IE you can (the value transforms into '13:45').

3rd little problem, in Firefox, only after unsuccessfully tried to type the '5', if you come back between the 1 and the 3 in the '13:4_' field (using the arrow keys or the clic), you can type '2' to have '12:34' again but then if you clic outside the box, the value clears.

**Comment by RobinHerbots** [comment]
@Dalmadog , 

Can you retry with the latest version

**Comment by Macharius92** [comment]
@RobinHerbots 

Dalmadog is not working on my project anymore. But i've just tested with the latest version.

1st issue is solved in both browsers. (tested with IE10 and FF22)

2nd issue is OK for FF

3rd issue seems OK too !

So i think you can close this issue ;)
