### ISSUE TITLE
Plans for removal of `navigator.userAgent`

### ISSUE THREAD

**Issue by stsrki** [RobinHerbots/Inputmask#2571]
Hello. 

Recently we received a notification from one of our users to let us know that Google is making the `navigator.userAgent` obsolete. According to this documentation https://blog.chromium.org/2021/05/update-on-user-agent-string-reduction.html

I must admit I wasn't aware that this was a problem so it got me a little off guard. So I had to check where it is used and indeed it was used in a few places, where Inputmask library was one of them.

My question is. Are there any plans to remove the usage of `navigator.userAgent` from Inputmask?

**Comment by RobinHerbots** [comment]
@stsrki ,

Thx for the info.  I will read the documentation and see how to make the necessary changes.

**Comment by RobinHerbots** [comment]
@stsrki,

For backward compatiobility it's best to use both features.  I can use the userAgentData if available and otherwise fallback to the old useragent string.  I will push a commit soon.

**Comment by stsrki** [comment]
@RobinHerbots thanks!
