### ISSUE TITLE
Email mask with a fixed domain

### ISSUE THREAD

**Issue by twoeyessoftware** [RobinHerbots/Inputmask#2576]
Hi, 

i have a problem with my email mask. 
I will mask only the local part of the email. It works fine as long as i have no 'a' on my domain. If i have an 'a' in the domain, it is converted to a placeholder. 

Here is my code:
$('#id').inputmask({
                mask: "*{1,64}[.*{1,64}][.*{1,64}][.*{1,63}]@domain.com",
                onBeforePaste: function onBeforePaste(pastedValue, opts) {
                    return pastedValue = pastedValue.toLowerCase(), pastedValue.replace("mailto:", "");
                }
            });

**Comment by RobinHerbots** [comment]
@twoeyessoftware ,

You need to escape the a.

$('#id').inputmask({
mask: "{1,64}[.{1,64}][.{1,64}][.{1,63}]@dom\\\\ain.com",
onBeforePaste: function onBeforePaste(pastedValue, opts) {
return pastedValue = pastedValue.toLowerCase(), pastedValue.replace("mailto:", "");
}
});
