### ISSUE TITLE
Comma input turns to decimal

### ISSUE THREAD

**Issue by clusian** [RobinHerbots/Inputmask#2577]
The currency input mask out of the box appears to change a comma input into a decimal. I do not want this. I would like to keep the groupSeperator formatting as is, but if a user is typing in a currency value and would like to enter in a comma, I would like this to stay a comma and not be turned into a decimal. 

I am using the following mask:

inputmode="decimal" type="text" aria-required="true" data-inputmask="'alias': 'numeric', 'groupSeparator': ',', 'digits': 2, 'digitsOptional': true, 'showMaskOnHover': false, 'showMaskOnFocus': false, 'rightAlign': false"

I am on version 5.0.7

**Comment by RobinHerbots** [comment]
@clusian , 

I added an option to the numeric alias to enable/disable the behavior.

Set substituteRadixPoint: false option to diable.
 Version: 5.0.8-beta.4
