### ISSUE TITLE
Support for right aligning masks?

### ISSUE THREAD

**Issue by gvdhoven** [RobinHerbots/Inputmask#26]
Hi Robin,

The following use case is at hand; people are allowed to enter a country code phone number (for instance 31 for the Netherlands, but 352 for Luxemburg).

So i have used the following code:
$('#phonecode').inputmask('99999');

This would mean that there can be 5 numbers entered.

Here comes the tricky part:
- Since it is a number (could also be used for money fields), i would like to have this field right aligned (style=text-align: right;) 
- But i would like the mask to be 'removed' when the focus is lost. For instance, if i enter now something like "31" for the netherlands, the field stays like "31___" and is right aligned.

Do i miss some settings/options or is this an enhancement?

**Comment by RobinHerbots** [comment]
try

$('#phonecode').inputmask({ mask: '9' , greedy: false, repeat: 5 });  The
aligning can be set with css. (Numeric input is partially implemented.  I
will finish this within when I find the time)

Robin

2012/2/14 Gilles van den Hoven <
reply@reply.github.com

**Comment by gvdhoven** [comment]
This works, but gives me the following 'bug'. On the field above, i have set;
$('#countrycode').inputmask('AA');

So when i hover over that field, it shows the mask (as __ )

On the non-greedy field, no masking is shown when i hover. It would be nice if it was possible to:
1) have the entire mask there when the focus is on the field
2) have the remaining mask there when the field is hovered (i am aware that the field might look strange if it is right aligned and masking chars are added)

This makes it more in line with the non greedy mask i think..

**Comment by RobinHerbots** [comment]
I guess you mean when the input looses focus the placeholder or placeholder
remainder shouldn't be visible?

clearPartialMaskOnLostFocus?  ;-)

2012/2/14 Gilles van den Hoven <
reply@reply.github.com

**Comment by gvdhoven** [comment]
No not really

For instance; the fields are like this (next to each other):
- countrycode
- phonecode

case 1:
Countrycode is empty / The focus is in/on the phonecode field / So no mask is shown in the countrycode field.
When i hover/move with my mouse over the countrycode field, the placeholders (e.g. mask "__") appears, but only when my mouse is over the countrycode field.

case 2:
The focus is in/on the countrycode field, which is empty, so it displays the mask "__" as expected. However, when hovering over the phonecode field, no placeholders appear. So the behaviour that displays placeholders on hover is different on these fields.

case 3:
Countrycode is not empty, only has "N" so field shows "N_". When the focus moves to the next field, the "_" stays there. I think this is the "ClearMaskOnIncomplete.." setting, right?

I hope this clarifies some.

**Comment by gvdhoven** [comment]
oke, i am a bit further now;

$('#phonecode').inputmask({ mask: '99999', numericInput: true });
aligns right and seems to work, however, mask remains when <5 numbers are entered.
eg: "123" gives "__123" also when not in the field.

$('#phonecode').inputmask({ mask: '99999', numericInput: true, greedy: false });
Clears the field on blur, no matter what i enter.

$('#phonecode').inputmask({ 'mask': '9', 'repeat': 5, 'greedy': false, 'numericInput': true  });
does not seem to work at all. Text is left aligned instead of right aligned without greedy setting, no masking shows.

So the following code snippet gives untill now the best result. It is consistent with hovering the field,
but it lacks the powerfull "clear any mask on blur but leave entered digits" setting :)
$('#phonecode').inputmask({ 'mask': '99999', 'numericInput': true  });

**Comment by RobinHerbots** [comment]
there is already an onincomplete event/function called when the mask is
incomplete and loses focus.  You can clear the placeholders there.

2012/2/14 Gilles van den Hoven <
reply@reply.github.com

**Comment by RobinHerbots** [comment]
$('#phonecode').inputmask({ 'mask': '9', 'repeat': 5, 'greedy': false,
'numericInput': true  });
does not seem to work at all. Text is left aligned instead of right aligned
without greedy, no masking shows.

This is not supported for the moment.

$('#phonecode').inputmask({ mask: '99999', numericInput: true, greedy:
false });
Clears the field on blur, so i changed it to

the adding   clearMaskOnLostFocus: false

What do you understand by clearing the mask, .... ex    123-456___
should it change to 123-456 or to 123456

Robin

2012/2/14 Gilles van den Hoven <
reply@reply.github.com

**Comment by gvdhoven** [comment]
Good point, but in this case i have no dashes or specific format, so clearing the field should result in 12456
With what you mean is that i could set something like this in the incomplete/lose focus function:
$('#phonecode').val($('#phonecode').inputmask('unmaskedvalue');)

edit:
Changed the code now to this:
            $('#phonecode')
                .focus(function() { $(this).inputmask({ 'mask': '99999' }); })
                .blur(function() { $(this).inputmask('remove'); })
                .css('text-align: right;');

Since bluring out of the incomplete mask still left the placeholder which is, in regards to inputmask 100% valid, but not for my usecase ;)
