### ISSUE TITLE
Nuget package error

### ISSUE THREAD

**Issue by chamikasandamal** [RobinHerbots/Inputmask#260]
jquery.inputmask.regex.extensions.js is not available in the nuget package. so url mask is not working.

**Comment by RobinHerbots** [comment]
@chamikasandamal ,

The url mask is in the jquery.inputmask.extensions.js or did you wrote an url mask using the regex extension?

The regex extension isn't included as it is still experimental.

Robin

**Comment by chamikasandamal** [comment]
@RobinHerbots ,
I'm using the alias available on jquery.inputmask.extensions.js and it is displaying "http://ar" and there is no definition for "r". i found something on the regex extension. in above code only letter "a" is editable and cannot enter anything after "r"

**Comment by RobinHerbots** [comment]
@chamikasandamal ,

Can you try by removing the r in the mask field of the extensions.  
The url mask is not written by me and I didn't test it yet.  Maybe It needs some update ;-)

**Comment by RobinHerbots** [comment]
@chamikasandamal , 

The url alias is fixed in the latest version 2.2.39

best regards, 

Robin
