### ISSUE TITLE
How can I do Alphanumeric easily?

### ISSUE THREAD

**Issue by glrodasz** [RobinHerbots/Inputmask#261]
I have been looking for the way of do the alphanumeric but I am confuse if can be do by this plugin. There is a way of to do this?

**Comment by RobinHerbots** [comment]
$(selector).inputmask("******");

**Comment by RobinHerbots** [comment]
or

$(selector).inputmask("*", { greedy: false, repeat: 20 });

**Comment by glrodasz** [comment]
Thanks! That works fine!
