### ISSUE TITLE
Problem with decimal mask and values less than 1

### ISSUE THREAD

**Issue by nicomdp** [RobinHerbots/Inputmask#263]
I have problems with values like 0.12. When I type 0. te mask dissapear and I can't type any more digits.

This is my configuration:

$('#ID').inputmask('decimal', {'digits':2, radixPoint: '.', groupSeparator: ',', groupSize: 3, autoGroup: true, numericInput: false });

Thanks in advance.

**Comment by nicomdp** [comment]
Here is the full code: 
http://jsfiddle.net/nicomdp/PwUDy/

**Comment by RobinHerbots** [comment]
@nicomdp ,

The issue is fixed in the latest version.

You should remove the numericInput: false option from your mask.

Best regards, 

Robin

**Comment by nicomdp** [comment]
Thanks man!
