### ISSUE TITLE
#263 is not fixed for IE

### ISSUE THREAD

**Issue by nicomdp** [RobinHerbots/Inputmask#266]
I still have problems with the decimal mask in IE. In Chrome works fine.

**Comment by RobinHerbots** [comment]
@nicomdp , 

Can you be more specific!

I tested under ie9 & IE10 and it seems fine.

**Comment by nicomdp** [comment]
I tested with numericInput: false. With true works fine. Thanks!

**Comment by RobinHerbots** [comment]
Why did you set numericInput to false?
