### ISSUE TITLE
Add event change,blur jquery

### ISSUE THREAD

**Issue by alonenascimento** [RobinHerbots/Inputmask#267]
input mask plugin does not allow event jquery?
trying to use :
$("#field").mask("999.999.999-99");

  $("#field").change(function(){
        alert("hi");
    });

does not working.

**Comment by RobinHerbots** [comment]
@alonenascimento , 

Can you provide an example on jsfiddle as I cannot reproduce the problem.

best regards, 

Robin

**Comment by RobinHerbots** [comment]
@alonenascimento , 

Is this specific to a certain browser?  The change event is working fine.

**Comment by alonenascimento** [comment]
@RobinHerbots 
i'm using chrome
jsfiddle example:

http://jsfiddle.net/g662Q/

the blur event work fine, but i cant do the same with change event

**Comment by RobinHerbots** [comment]
@alonenascimento , 

That's because you are using the maskedinput plugin from Bush  ;-)

Check this http://jsfiddle.net/g662Q/2/  which uses the inputmask plugin instead !

best regards, 

Robin
