### ISSUE TITLE
#263 is about initial values

### ISSUE THREAD

**Issue by kyrel** [RobinHerbots/Inputmask#268]
Hi!
Though I can see that some <1 problems are solved, the one that I reported in #263 with
http://jsfiddle.net/nsqNV/
seems to be still there.
If you preinit your input with a value in HTML which is <1, the whole field goes dot.
Thanks for your work and sorry for being so persistent

**Comment by RobinHerbots** [comment]
@kyrel , 

It was fixed, but some commit reverted it I guess.

Thx for reporting again and I will fix it this evening

Best regards, 

Robin

**Comment by RobinHerbots** [comment]
@kyrel , 

Have another try !

**Comment by kyrel** [comment]
Yep, works like a charm!
Thanks for quick response!
I'm thus closing the issue :)

**Comment by RobinHerbots** [comment]
Ok thx!
