### ISSUE TITLE
Feature: RTL support

### ISSUE THREAD

**Issue by gvdhoven** [RobinHerbots/Inputmask#27]
This is somewhat related to my previously entered issue, but it would complicate the previous issue to much, therefore a new issue.

When, in a normal input field, you have the following configuration:
- style="text-align: right;"
- maxlength="5"
- $('field).inputmask({ mask: '99999', clearIncomplete: true });
- And start typing text "123"

You get: "123__"

But, since we right align the text, we would expect: "__123"

So i added the "dir" property: dir="RTL" which nicely right aligns.
But, typing "123" puts the cursor before the 1; giving "__|123" while the cursor should be "__123|"
Also, tabbing out of this field clears the field entirely.

Again, it could be that i am missing settings, but inputmask should respect the dir property.

**Comment by RobinHerbots** [comment]
Also, tabbing out of this field clears the field entirely. => because you specified clearIncomplete: true

I will add input direction detection support in the plugin (like numericInput actually)

**Comment by RobinHerbots** [comment]
Can someone explain the following.

we have an input with dir="rtl"

We have the following text  :    1111-aa and 1111aa
When I copy/paste the first I get   aa-1111 while copying the second gives 1111aa.  Why is that.

What is the logic behind this behavior.

**Comment by RobinHerbots** [comment]
see commit https://github.com/RobinHerbots/jquery.inputmask/commit/369eb8b62bd07ec3c264dd7913529c94cb8d055b

the greedy: false , functionality will be added later see issues.
