### ISSUE TITLE
Alternator Mask not working properly

### ISSUE THREAD

**Issue by luco** [RobinHerbots/Inputmask#2713]
When trying to use the alternator mask, it's not working properly:

```
if (document.querySelector(".cpfcnpjmask")) {
		Inputmask({
			mask: ['999.999.999-99', '99.999.999/9999-99'],
			keepStatic: true
		}).mask(document.querySelector(".cpfcnpjmask"));
	} 
```

![image](https://github.com/RobinHerbots/Inputmask/assets/246373/5b1d1bf5-19d5-404c-bf9a-7cfc96e197d0)

Right after inserting another number:

![image](https://github.com/RobinHerbots/Inputmask/assets/246373/84859555-1e92-4e39-8829-f4afc8a61762)

**Comment by RobinHerbots** [comment]
@luco ,

Can you retry with 5.0.9-beta.7
