### ISSUE TITLE
Wrong caret position after dynamically changing a mask on keyup

### ISSUE THREAD

**Issue by eshiota** [RobinHerbots/Inputmask#272]
I have a credit card input, and its mask should dynamically change after a some keyup events (e.g. its default mask is "9999 9999 9999 9999", but after typing "37" it should change to AMEX format "9999 999999 99999").

However, after calling `inputmask("9999 999999 99999")`, the caret position goes to the second to last position instead of the last one.

Here's a very simple example:

``` javascript
$(function () {
  $("input").inputmask("9999 9999 9999 9999");

  $("input").on("keyup", function (event) {
    var value = $(this).inputmask("unmaskedvalue");

    if (value.length === 2 && value === "37") {
      $("input").inputmask("9999 999999 99999");
    }
  });
});
```

Tested on Chrome 27.0.1453.116, Safari 6.0.4, Firefox 21.0.

**Comment by RobinHerbots** [comment]
@eshiota, 

Fixed in the latest version.

Best regards, 

Robin

**Comment by levipadre** [comment]
I have similar issue but when you paste the number. I modified the code to catch the first 2 characters:
https://jsfiddle.net/7fxqo3r8/2/ but it doesn't work.
