### ISSUE TITLE
Cursor position not correct for partial entry

### ISSUE THREAD

**Issue by kjdenim** [RobinHerbots/Inputmask#273]
I'm using a input mask for an ssn field.  If the field is completed fully, then completed partially, the cursor position is not correct.

Please see an example here: http://jsfiddle.net/PtPWX/

Enter the full ssn.
Tab over to the second field
Tab back to ssn, enter a partial value
Tab over to the second field
Click on ssn, the cursor appears at the end as though the field was complete and numbers cannot be typed without first backspacing.

Thank you.

**Comment by RobinHerbots** [comment]
@kjdenim , 

Fixed in version 2.2.50

**Comment by kjdenim** [comment]
Thank you for the quick turnaround.
