### ISSUE TITLE
Problem with inputmask("remove")

### ISSUE THREAD

**Issue by LuizAntenor** [RobinHerbots/Inputmask#278]
hi guys, I'm having problems with InputMask, does not work in this case InputMask ("remove") does not remove the mask, other times I used it worked in the same way here just gave me this problem anyone know say why? (jquery used https://github.com/RobinHerbots/jquery.inputmask/blob/2.x/js/jquery.inputmask.js)

$(document).ready(function () {
        $("input[name=group1]").change(function () {

```
        if ($(this).val() == 'PHONE')
            $("#search").inputmask("mask", { "mask": "(99)9999-9999" });
        else
            $("#search").inputmask("remove");

        $("#search").focus();
        $("#search").val("");
    });
});
```

**Comment by RobinHerbots** [comment]
@LuizAntenor , 

I will have a look at it

Best regards, 

Robin

**Comment by RobinHerbots** [comment]
@LuizAntenor , 

Fixed in the latest version

**Comment by Roxizz** [comment]
s
