### ISSUE TITLE
Decimal separator hangs

### ISSUE THREAD

**Issue by dicash** [RobinHerbots/Inputmask#2788]
Open https://robinherbots.github.io/Inputmask/#/demo
Try entering `1234.12341234123412341234` in decimal input - the webpage will hang.

**Comment by Techn1c4l** [comment]
I suggest you limit the `digits` option to 9-10. Most of the time you don't even need more than 2-3 decimal places, unless you are developing some scientific software where precision matters that much.

**Comment by Techn1c4l** [comment]
Fixed in c45a51b0fc142d737e81d21d1b32f4c1037ffdfa. @RobinHerbots please close this issue.
