### ISSUE TITLE
it is not possible to use escaped characters as a separator in dates

### ISSUE THREAD

**Issue by skrasnoyarov** [RobinHerbots/Inputmask#2791]
@RobinHerbots Hello! Can you tell me how can I set the escaped characters that are used to display dates as the date separator?
For example: dd\\dmm.yyyy.

I use \\d as a separator and it doesn't work on version 5.0.8. [codesandbox](https://codesandbox.io/p/sandbox/inputmask-4lrgly?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clwarg8ks00063b6j97v2sr6m%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clwarg8kr00023b6jtrb1tvfl%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clwarg8ks00033b6ju9lapg7g%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clwarg8ks00053b6j294wpoe1%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clwarg8kr00023b6jtrb1tvfl%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwarg8kr00013b6j78wqvdpm%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%257D%255D%252C%2522id%2522%253A%2522clwarg8kr00023b6jtrb1tvfl%2522%252C%2522activeTabId%2522%253A%2522clwarg8kr00013b6j78wqvdpm%2522%257D%252C%2522clwarg8ks00053b6j294wpoe1%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwarg8ks00043b6jdevqvvrk%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clwarg8ks00053b6j294wpoe1%2522%252C%2522activeTabId%2522%253A%2522clwarg8ks00043b6jdevqvvrk%2522%257D%252C%2522clwarg8ks00033b6ju9lapg7g%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clwarg8ks00033b6ju9lapg7g%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)
The same is true for \\m, \\y.

Is this a bug or is it done on purpose and there is no longer an opportunity to use it like this?

On version 3.3.0, this feature was: [codesandbox](https://codesandbox.io/p/sandbox/inputmask-old-ykr3qq?file=%2Fpublic%2Findex.html%3A31%2C9&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clwas4d4o00063b6j3s97qfrb%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clwas4d4o00023b6j8dbedw6e%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clwas4d4o00033b6j27h0dvce%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clwas4d4o00053b6jfkoq7yma%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clwas4d4o00023b6j8dbedw6e%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwas4d4o00013b6jizeixf50%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clwaucl8h00023b6jbiritea1%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A10%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A10%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clwauf1r700023b6ju1bvxt87%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A31%252C%2522startColumn%2522%253A9%252C%2522endLineNumber%2522%253A31%252C%2522endColumn%2522%253A9%257D%255D%252C%2522filepath%2522%253A%2522%252Fpublic%252Findex.html%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clwas4d4o00023b6j8dbedw6e%2522%252C%2522activeTabId%2522%253A%2522clwauf1r700023b6ju1bvxt87%2522%257D%252C%2522clwas4d4o00053b6jfkoq7yma%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwas4d4o00043b6j9w5y3hb2%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clwas4d4o00053b6jfkoq7yma%2522%252C%2522activeTabId%2522%253A%2522clwas4d4o00043b6j9w5y3hb2%2522%257D%252C%2522clwas4d4o00033b6j27h0dvce%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clwas4d4o00033b6j27h0dvce%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A14.93288590604027%257D)

Thank`s for your attention!

- OS: macos Monterey 12.5.1
- Browser arc
- Inputmask version 5.0.8

**Comment by Techn1c4l** [comment]
Confirming that, even the example from the documentation doesn't work:
`jQuery('#field').inputmask({ 'alias': 'datetime', 'inputFormat': 'm \\months', escapeChar: '\\' });`

**Comment by RobinHerbots** [comment]
> Confirming that, even the example from the documentation doesn't work: `jQuery('#field').inputmask({ 'alias': 'datetime', 'inputFormat': 'm \\months', escapeChar: '\\' });`

The documentation does not use the datetime alias.

Anyway, it is fixed.

A correct example with the datetime alias would be
```
    Inputmask('datetime', {
      inputFormat: "m \\m\\on\\t\\h\\s",
    }).mask("#test1");
```

Have a look at https://robinherbots.github.io/Inputmask/#/documentation/datetime#supported-symbols
