### ISSUE TITLE
Placeholder weird behavior

### ISSUE THREAD

**Issue by stsrki** [RobinHerbots/Inputmask#2797]
We got this report from one of our users: https://github.com/Megabit/Blazorise/issues/5560

I'm not sure if this is the correct behavior. I would assume that the placeholder would behave the same as for regular input, i.e., show a hint until the user starts to write value. But in this case, the placeholder becomes a part of the value.

Can you please clarify?

**Comment by RobinHerbots** [comment]
The behavior is correct.  The placeholder is to pass a placeholder for the mask and not to be confused with the placeholder of the input.  passing "_" will fill the unfilled characters with "_" (mask 99-99-99 => \_\_-\_\_-\_\_), when passing a placeholder like "abcd" this wil be used to fill the unfilled characters.  mask 99-99-99  => ab-cd-ab

See https://robinherbots.github.io/Inputmask/#/documentation#placeholder-1

**Comment by stsrki** [comment]
Thanks for the clarification. It helps us to plan for the next steps.
