### ISSUE TITLE
Inputmask does not work on android 2.1

### ISSUE THREAD

**Issue by RobinHerbots** [RobinHerbots/Inputmask#28]
Backspace character does not always fire, .keydown event

**Comment by robo-corg** [comment]
I am seeing the same issue. It looks like there are certain events android keyboards can generate that make the stored cursor work around for android to get out of whack such as delete last word.

**Comment by Treyphor** [comment]
I'm on android version 4.2.2 and still having issues with the input mask. It seems to work until I try and hit backspace. It appears to delete what's there but when I go to type something else it puts back all the stuff I deleted. Does anyone know a way to make it work?

**Comment by Talkless** [comment]
Here I have screenshot of strange mask behaviour in Android 2.2 or 2.3.3:
http://i.imgur.com/CsFNffw.png

It's kinda skipping in accumulating way. More characters I write, more spaces I get.

It's OK in Android 4.x versions though.

My setup:

input.inputmask({
 "mask" : mask,
 "placeholder" : "?",
 "clearMaskOnLostFocus" : false
});

Where mask is made of "*".

Version 2.4.2
