### ISSUE TITLE
Numeric mask mouse navigation not possible

### ISSUE THREAD

**Issue by kyrel** [RobinHerbots/Inputmask#280]
With a numeric mask attached to an input I can't use the mouse to shift cursor position in the input

**Comment by RobinHerbots** [comment]
@kyrel, 

If I fix this, the caret will not position itself to the correct inputposition when clicking inside the input.

What behavior would you suggest, taken the above into account?

best regards, 

Robin

**Comment by kyrel** [comment]
I'm not sure I get that question.
You mean that there's some logic that positions the cursor upon initial clicking into the field which is currently not in focus and this logic could be broken?
Then I could suggest only executing this logic upon first click in a field without focus, while subsequent clicks would put the cursor into a position user points to

**Comment by RobinHerbots** [comment]
@kyrel , 

Fixed in version  2.3.38
Can you have a try
