### ISSUE TITLE
Numeric mask behavior when part of value in input selected

### ISSUE THREAD

**Issue by kyrel** [RobinHerbots/Inputmask#281]
I have an input with a decimal mask and "1000" entered in it.
I'm selecting "1" using Shift+arrows. I'm then entering "2" from keyboard.
I expect the result to be "2000" (selected range being replaced with what I've entered), but instead it's "200"

**Comment by RobinHerbots** [comment]
@kyrel , 

Fixed in the latest version.

**Comment by kyrel** [comment]
Cool, thanks!
