### ISSUE TITLE
datetime + placeholder are not working properly

### ISSUE THREAD

**Issue by skrasnoyarov** [RobinHerbots/Inputmask#2811]
- Describe the bug
 When I use alias "datetime" and mask "HH:ss" with placeholder "00:00", the placeholder doen`t work correctly. In the field it has the form "ss:00". But it should be "00:00". It works correctly in version 5.0.8.

- Add a link to a codepen, jsfiddle or other example page which shows the problem
- [сodesandbox](https://codesandbox.io/p/sandbox/inputmask-5-0-9-datetime-f6ql9s?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clzidm9uy00063b6lqd8hjyj9%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clzidm9uy00023b6laq2h30lt%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clzidm9uy00033b6l8oeu6s09%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clzidm9uy00053b6lf524st6i%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clzidm9uy00023b6laq2h30lt%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clzidm9uy00013b6lxpgf5spo%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%257D%255D%252C%2522id%2522%253A%2522clzidm9uy00023b6laq2h30lt%2522%252C%2522activeTabId%2522%253A%2522clzidm9uy00013b6lxpgf5spo%2522%257D%252C%2522clzidm9uy00053b6lf524st6i%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clzidm9uy00043b6lqh4460w3%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clzidm9uy00053b6lf524st6i%2522%252C%2522activeTabId%2522%253A%2522clzidm9uy00043b6lqh4460w3%2522%257D%252C%2522clzidm9uy00033b6l8oeu6s09%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clzidm9uy00033b6l8oeu6s09%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)
- OS: macos 12.5.1 monterey
- Browser Chrome 126
- Inputmask version 5.0.9

**Comment by Techn1c4l** [comment]
The `placeholder` option is meant to be used to specify a single character. In your case, set the value to `placeholder: '0'`.

**Comment by skrasnoyarov** [comment]
@Techn1c4l  I tried it, it didn't help. I noticed that it works with the rest of the characters, only with zero like this

**Comment by Techn1c4l** [comment]
Just checked, it appears version 5.0.9-beta.70 introduced this bug. Try using version 5.0.9-beta.62, works fine for me.

**Comment by skrasnoyarov** [comment]
it's not so critical for me right now and I'll stay on version 5.0.8 for now. Can you fix it in newer versions?

**Comment by Techn1c4l** [comment]
> it's not so critical for me right now and I'll stay on version 5.0.8 for now. Can you fix it in newer versions?

I'm sure the author of the library will fix this eventually. I'm just helping with the issues section here.

**Comment by skrasnoyarov** [comment]
@Techn1c4l ok. Thank`s for your help!

**Comment by RobinHerbots** [comment]
@skrasnoyarov ,

The issue should be solved in inputmask@5.0.10-beta.10.
