### ISSUE TITLE
Datetime mask `dd.mm.yyyy` leading to Uncaught InternalError: too much recursion

### ISSUE THREAD

**Issue by raphisuter** [RobinHerbots/Inputmask#2814]
Original Bug Report at PrimeFaces: https://github.com/primefaces/primefaces/issues/12428

InputMask: 5.0.9 (copied from https://github.com/RobinHerbots/Inputmask/issues/2813 as I am not an expert)

Configuration:

```javascript
{
alias: "datetime"
autoUnmask: false
clearIncomplete: true
clearMaskOnLostFocus: true
inputFormat: "dd.mm.yyyy"
placeholder: "_"
showMaskOnHover: false
}
```

Steps to reproduce:
precondition: value is set to `10.03.2018`
1. start to write 20.11.2024 (first 1 will be substituted for a .)
2. cursor will land before year part and not jump over . (don't have to change the year)
3. navigating with arrow keys to front
4. press 1
5. stack trace in the console (Uncaught InternalError: too much recursion)

CodePen: https://codepen.io/melloware/pen/bGProzd

this issue is kind of similar to https://github.com/RobinHerbots/Inputmask/issues/2813 as it was coming up from the same error observed in PrimeFaces. Thanks to @melloware for analysing the problem.

**Comment by RobinHerbots** [comment]
Hi @raphisuter ,
It seems it's due to the dots in de inputformat.  I will see how to fix this.

**Comment by RobinHerbots** [comment]
@raphisuter , @melloware,
Could you have a try with version Version: 5.0.10-beta.5

**Comment by melloware** [comment]
@RobinHerbots sure thing!  Will get back to you.

**Comment by melloware** [comment]
from my preliminary testing it seems to be working for me.

**Comment by melloware** [comment]
I think this is safe to close @RobinHerbots
