### ISSUE TITLE
Numeric mask seems to not fire change on form submit without blur

### ISSUE THREAD

**Issue by kyrel** [RobinHerbots/Inputmask#282]
If I navigate away from the numeric-masked field and then submit the form, my knockout model has correct value in its observable.
If I press Enter with focus still on the numeric-masked value, the knockout model's observable has the previous value.

I know I'm going a bit into specifics of my use case, but I guess that this behavior means that the field's change event has not fired by the moment my form's submit event has fired, which is not correct. Of course, removing the mask makes this undesired behavior go away.

Hope the description ain't too clumsy :)

**Comment by RobinHerbots** [comment]
@kyrel, 

Fixed in the latest version
