### ISSUE TITLE
Mask (99) 9999[9]-9999 does not work

### ISSUE THREAD

**Issue by tiagonicastro** [RobinHerbots/Inputmask#283]
I'm using the 2,x bundle pack. But the mask (99) [9]9999-9999 does not work.on Chrome.

It keeps showing all the numbers like (99) 99999-9999. When I put just 10 numbers shows (99) 99999-999_

**Comment by RobinHerbots** [comment]
I added a help page in the wiki for it.

https://github.com/RobinHerbots/jquery.inputmask/wiki/Howto:-Entering-optional-masks
