### ISSUE TITLE
Error on first character with insertMode = false

### ISSUE THREAD

**Issue by kjdenim** [RobinHerbots/Inputmask#285]
I'm on v2.2.59 and using a input mask for an ssn field. After tabbing into the field, entry of the first character throws a javascript error.

Please see an example here: http://jsfiddle.net/PtPWX/

Click on the Some Text field
Shift-Tab over to the ssn field
Type a number - javascript error and entry is skipped

Thank you.

**Comment by RobinHerbots** [comment]
@kjdenim , 

Fixed in 2.2.50 (nuget will follow tomorrow )
best regards, 

Robin

**Comment by RobinHerbots** [comment]
I mean version 2.2.60
