### ISSUE TITLE
Editing impossible under some circumstances

### ISSUE THREAD

**Issue by andgas** [RobinHerbots/Inputmask#286]
When using inputmask with these properties: {"mask": "999.999.999", placeholder:"_"}
whe have the problem that after inserting "123" then moving back with the cursor and replacing the 2 and then moving the cursor after the 3 but before the first dot no more digits can be inserted!

Inserting somewhere else works but not after the last digit.

And another question: When we do not completely fill an input field with all nine digits and switch to another browser tab and then back to the tab with the input field then the cursor is not at the same position where it was when we switched but at the end of the input field. Is there a way to keep the curser at the right position?

**Comment by RobinHerbots** [comment]
@andgas , 

I will have a look at issue 1.

For issue 2, when you tab into a masked field, the whole content is selected, or do you see other behavior?

best regards, 

Robin

**Comment by andgas** [comment]
Hi Robin,

thank you for your quick response.

In issue 2 I described a problem when switching to an other _browser tab_ 
using the mouse and then switching back to the tab with the previously 
focused
input field with the mask. Then the cursor is not at the same position but 
at the end of the field (at least in Chrome and IE). This is really a 
minor problem but if it can be fixed with only a little effort it would be 
nice.

Thank you very much for your inputmask plugin we really appreciate working 
with it.

Bye

Andreas

---

```
·        ·     
```

mailto:andreas.gassner@witt-gruppe.eu    ·    http://www.witt-gruppe.eu 

Josef Witt GmbH    ·    Schillerstraße 4-12    ·    92637 Weiden
Geschäftsführung: Wolfgang Jess (Vorsitzender),
Jürgen Angstmann, Stephan Merck, Stefanie Zühlke-Schmidt
AG Weiden, HRB 1435

Online-Shops:
http://www.witt-gruppe.eu/einkaufswelten/online-shops-der-witt-gruppe/

---

Deutschland rundet auf - Unsere WITT WEIDEN-Filialen sind dabei!
Mehr erfahren Sie unter http://www.deutschland-rundet-auf.de

---

 before printing this e-mail, please consider if it is really necessary

Von:    Robin Herbots notifications@github.com
An:     "RobinHerbots/jquery.inputmask" 
jquery.inputmask@noreply.github.com
Kopie:  Andreas Gaßner andreas.gassner@witt-gruppe.eu
Datum:  05.07.13 15:25
Betreff:        Re: [jquery.inputmask] Editing impossible under some 
circumstances (#286)

@andgas , 
I will have a look at issue 1.
For issue 2, when you tab into a masked field, the whole content is 
selected, or do you see other behavior?
best regards, 
Robin

**Comment by RobinHerbots** [comment]
@andgas , 

Issue 1 should be fixed with the latest version.

I will have a look at the second.

**Comment by RobinHerbots** [comment]
@andgas 

issue 2 should also be fixed in 2.2.66

**Comment by andgas** [comment]
Hi Robin,

thank you very much for your help. Unfortunately we have the same problems with the new version 2.2.66 (tested with Chrome and Firefox). Could you please again have a look at it? Thanks in advance.

Best regards

Andreas

**Comment by RobinHerbots** [comment]
Hi @andgas ,

Can you create a jsfiddle for the 2 cases, and describe the exact steps to reproduce.

best regards, 

Robin

**Comment by andgas** [comment]
Hi Robin,

here is the jsfiddle url:

http://jsfiddle.net/KfH9Q/

Bye

Andreas

**Comment by RobinHerbots** [comment]
You have to link to rawgithub instead of raw.github.

Updated fiddle  http://jsfiddle.net/KfH9Q/1/

**Comment by RobinHerbots** [comment]
@andgas , 

Hmm I am missing something.

Let's start with issue 1.

initial => **_.**_.___
I type 123 => 123.**_.**_
I select the 2 and type 4   => 143.**_.**_
I move the caret with the arrow key after the 3 (before the .)
I type 5 => 143.5__.___

What is the problem?

**Comment by RobinHerbots** [comment]
inital should be "**_.**_.___" but the editor removes some part ;-(

**Comment by andgas** [comment]
Hi Robin,

When we type your example:

initial => **_.**_.___
I type 123 => 123.**_.**_
I do not select the 2 but move the cursor between 2 and 3 then type "backspace" and type 4 => 143.**_.**_
I move the cursor with the arrow key after the 3 (before the .)
I type 5 => 143.**_.**_

The difference is if you select the digit which has to be changed or if you just remove it with backspace or delete.

**Comment by RobinHerbots** [comment]
Ok, that's something else.  I will have a look at that.

Robin

2013/7/15 Andreas Gaßner notifications@github.com

**Comment by sislamoglu** [comment]
I have the very same problem here is my mask

999:99  (Doing a hour / minute ) duration with a place holder of zero

I enter 007:20 and it saves alright,
But when editing text, I see value right as "007:20" from source code, but javascript converts it to "720:00" removing zeros infront....

**Comment by RobinHerbots** [comment]
@sislamoglu, 

When does he change it to 720:00,   On what action?  Can you also provide a jsfiddle

best regards, 

Robin

**Comment by sislamoglu** [comment]
Here you go :)

http://jsfiddle.net/cwdnR/

**Comment by RobinHerbots** [comment]
@sislamoglu , 

I see, ... It's the checkval which skips the 0 as he sees them equal to a placeholder.  

I will have a look at it.

**Comment by RobinHerbots** [comment]
@sislamoglu ,

Have a look at http://jsfiddle.net/cwdnR/1/
Your case is fixed in verion 2.2.70

**Comment by sislamoglu** [comment]
Lovely, thank you :)

**Comment by RobinHerbots** [comment]
@andgas, 

Issue 1 is solved.
issue 2 sets back the caret at the first valid position to enter input

**Comment by RobinHerbots** [comment]
@andgas, 

issue 3??

**Comment by andgas** [comment]
@RobinHerbots 

thank you very much. Everything is working fine now.
