### ISSUE TITLE
Numeric field -> autogroup and autounmask

### ISSUE THREAD

**Issue by repa7** [RobinHerbots/Inputmask#287]
Hi Robin,

If I use a numeric mask with autogroup the autounmasked value contains the groupseparator char too but I think it is not part of the number it is only part of the mask. 
Of course the radix point is part of the number.

What do you think?

Regards,

Cs.

**Comment by RobinHerbots** [comment]
@repa7 , 

This can be solved by using jquery.globalize, which can parse the decimals depending the used culture.

I was thinking to add a postparse callback within autounmask which can handle the different cases per alias definition, but I concluded that this is a bit out of scope of the plugin.
