### ISSUE TITLE
Can't tab out of a readonly field

### ISSUE THREAD

**Issue by gilbertg** [RobinHerbots/Inputmask#288]
Created an inputmask input using simply 'integer' alias. Set that input to reaodonly. Can tab in-but not out again. Non-readonly is fine

**Comment by RobinHerbots** [comment]
@gilbertg , 

Which version are you using from the plugin?  And also in which browser did this occur?

best regards, 

Robin

**Comment by gilbertg** [comment]
oops, that be important information yes. 
Plugin v2.2.0 
Browser: Chrome (latest) 27.0.1453.116 m

**Comment by RobinHerbots** [comment]
@gilbertg , 

Can you retry with version 2.2.63.

Best regards
Robin

**Comment by gilbertg** [comment]
Looks good thanks Robin
