### ISSUE TITLE
Problem with mask of zip code on 6th symbol

### ISSUE THREAD

**Issue by SlavaPoddubsky** [RobinHerbots/Inputmask#290]
I use next mask:
$('.zipcode-field').inputmask({mask: ["99999", "99999-9999"]});

In process of input after 5th symbol there is no reaction after press down on 6th symbol and it's ok after. Maybe it isn't bug but I can't resolve this delay on '-' symbol.

**Comment by RobinHerbots** [comment]
@SlavaPoddubsky , 

I see the "problem",(actually extra feature)   The current behavior is correct as the next char to enter is - and is needed to make the mask awre that you want to input the second mask.

I will see that I can implement this, that it will accept directly the next valid input for the second mask.

best regards, 

Robin

**Comment by RobinHerbots** [comment]
added case in the unittests

**Comment by RobinHerbots** [comment]
@SlavaPoddubsky , 

Fixed

best regards, 

Robin

**Comment by SlavaPoddubsky** [comment]
It works fine!
U da man!!!
Thanks a lot!
:+1:

**Comment by RobinHerbots** [comment]
@SlavaPoddubsky , 

;-)

You can now even simplify your mask like this $(selector).inputmask({ mask: "99999[-9999]", greedy: false });

**Comment by SlavaPoddubsky** [comment]
Ok, thanks!
