### ISSUE TITLE
Auto upper-casing seems broken

### ISSUE THREAD

**Issue by MarcDiethelm** [RobinHerbots/Inputmask#291]
If I use something like

```
.inputmask("AAA")
```

It literally only allows the uppercase letter A.

**Comment by RobinHerbots** [comment]
@MarcDiethelm , 

You have to include the jquery.inputmask.extensions.js which contains the definition for the A-definition.

best regards, 

Robin

**Comment by MarcDiethelm** [comment]
Oh my bad then... Thanks a lot!
