### ISSUE TITLE
Deleting password field content when switching from Alpha to Numeric keyboard + backspace issue

### ISSUE THREAD

**Issue by elodbarna** [RobinHerbots/Inputmask#293]
Hi,
I am using the jquery-masked-input-min-1-3-1.js for an <input type="password" name="regpwd" class="regtext password"/>. 
The mask I use is: 
$.mask.definitions['k'] = "[a-zA-Z0-9!@#$%^*_-]";
$(".step1 [name=regpwd]").mask("kkkkkkkkk?kkkk", {placeholder: "", deleteIfNotMatchingMask: false});

While testing on Nexus 7, Chrome, Andorid 4.2.2 I found two issues:
1. If a switch from Alpha to Numeric keyboard and start typing some numbers, it deletes the part entered before.
2. And continuing step1, after typing some numbers I delete all of them using the backspace, but tha last one cannot be deleted, itt goes after the cursor.

Do you have any solutions? Thank you!

**Comment by RobinHerbots** [comment]
@elodbarna , 

You need to open an issue with the correct plugin as this is the jquery.inputmask plugin.  Not jauery-masked-input

**Comment by elodbarna** [comment]
Ok, sorry!
