### ISSUE TITLE
onLoad 

### ISSUE THREAD

**Issue by jalanbyers** [RobinHerbots/Inputmask#294]
Is there a way to get the input mask to appear on page load (rather than by hover or focus)?

**Comment by RobinHerbots** [comment]
@jalanbyers ,

Yes by specifying the clearMaskOnLostFocus: false option.  (and grabbing the latest version as there was a little bug which caused it not to show initially)

best regards, 

Robin

**Comment by jalanbyers** [comment]
Like a charm, thanks!!

Alan
