### ISSUE TITLE
Option to set initial position of caret

### ISSUE THREAD

**Issue by kyrel** [RobinHerbots/Inputmask#295]
I'm having the following usecase.
The user has a phone number in clipboard.
It could be 911-404-11-12 or +79114041112 or something like that.
I have a field with a mask of +7 (999) 999-99-99
If I place the caret in the start of the field and insert the value from clipboard, everything inserts properly for all scenarios of value formats I'm interested in.
However, if I leave the caret where it positions automatically (after '(' ), then the '7' from clipboard gets inserted, not skipped, which is not what I desire.
If I had an option of specifying whether or not to skip initial mask characters on first click on an unfocused field, it would perfectly solve my problem :)

**Comment by RobinHerbots** [comment]
@kyrel , 

With the paste event the inputmask works with the data it gets from the inputelement.  In your case

example with a paste of +79114041112 at the initial caret position
+7 (+79114041112___) ___-__-__  and you expect +7 (911) 404-11-12

I don't like the idea op the initial positioning of the caret.  I want that a paste like this just works.

I added it in the qunit-tests and will try to fix it asap.

**Comment by RobinHerbots** [comment]
@kyrel , 

Have a try with that latest version ;-)
