### ISSUE TITLE
Problem with remove mask

### ISSUE THREAD

**Issue by LuizAntenor** [RobinHerbots/Inputmask#297]
if i try remove any mask, 

$("controle").inputmask("remove");

in the submit in page, the system try access the _valueGet and error occurs, in this point

$input.closest('form').bind("submit", function () { //trigger change on submit if any
                        if ($input[0]._valueGet() != getActiveMaskSet()["undoBuffer"]) {
                            $input.change();
                        }
                    });

so the valueget is undefined

in chrome console(F12) has this error
Uncaught TypeError: Object #<HTMLInputElement> has no method '_valueGet'

**Comment by RobinHerbots** [comment]
@LuizAntenor , 

Should be solved in v2.2.72

Robin
