### ISSUE TITLE
Issue with reset of inputmask field

### ISSUE THREAD

**Issue by SlavaPoddubsky** [RobinHerbots/Inputmask#298]
1) I created next input:
<input name="name" value="" data-inputmask="'mask': '(999) 999-9999', 'showMaskOnHover': false" />

2) I created code in JS file:
$(":input").inputmask();

3) When I'm entering phone number and after reset form with method form.reset() all other fields are resetted and fields with mask too, BUT when mask field has focus,  old value is restored.

**Comment by SlavaPoddubsky** [comment]
This issue appeared after last changes in Issue #297.

**Comment by RobinHerbots** [comment]
@SlavaPoddubsky , 

Fixed in the latest version

best regards, 

Robin
