### ISSUE TITLE
Max Length not wokring for Regex

### ISSUE THREAD

**Issue by tajeet** [RobinHerbots/Inputmask#299]
have a  input element  <input id="txtCompanyName" maxlength="10" >

and in the JS i'm using 

$('#txtCompanyName').inputmask("Regex", { regex: "[a-zA-Z-0-9_|@$&#:',_)(;.\s\\]_" });

the max length attribute does not work. Am I doing something wrong. ?
tried to debug and in the inputmask.js at line 798 the getMaskLength() return 2 everytime. 

 if (getMaskLength() > maxLength && maxLength > -1)

**Comment by tajeet** [comment]
input id="txtCompanyName " type="text" class="span11" maxlength="10"

**Comment by RobinHerbots** [comment]
@tajeet , 

I fixed the maxlength issue in the latest version but be aware that the regex.extensions is just an experiment.  
For simple cases it will work but it cannot handle complex regexes for the moment.

best regards, 

Robin
