### ISSUE TITLE
Date Extension Year Range

### ISSUE THREAD

**Issue by telemetry** [RobinHerbots/Inputmask#300]
Unable to implement this snippet from the readme regarding date extension:

$("#date").inputmask("date", {yearrange: { minyear: 1900, maxyear: 2000 }}); //specify year range
});

I would like to only use dates in the past ( Date of Birth )
When I input only 2 Digits for example 77 ( for 1977 ) it defaults to 2077.

is it possible for this to default to 19 Century before 20th century

Apologies if this is not the correct place for this comment its my first post on github.

Thanks

**Comment by RobinHerbots** [comment]
@telemetry , 

This is the perfect place to open issues ;-)

I will have a look at it

best regards, 

Robin

**Comment by RobinHerbots** [comment]
@telemetry , 

This is fixed in the latest version. Can you have a try.

best regards, 

Robin

**Comment by telemetry** [comment]
Hi Robin,

I have tested this and it works great. Thanks for putting in the time to look at this.

Terry

**Comment by snshafiee** [comment]
Hi Robin, I have the same issue and as I can see it has been resolved but I am using the latest version of Inputmask (ver 3.3.11) and I still have this issue. When I input only 2 Digits for example 78 ( for 1978 ) it defaults to 2078 . would you please help me to fix this one in new version? Thanks
