### ISSUE TITLE
Setting/Removing and setting again a mask

### ISSUE THREAD

**Issue by Macharius92** [RobinHerbots/Inputmask#301]
Hi @RobinHerbots,

I would like to be able to set a mask on an input, remove it and then put it again.

When i do this :

``` javascript
$('#myinputID').inputmask('hh:mm', { clearIncomplete: true });
$('#myinputID').inputmask('remove');
$('#myinputID').inputmask('hh:mm', { clearIncomplete: true });
```

After the 1st line i have the mask.
After the 2nd, my input is free to enter anything i want.
After the 3rd i still can enter what i want.

Any idea ?

**Comment by RobinHerbots** [comment]
@Macharius92, 

Yes, fixed

**Comment by Macharius92** [comment]
@RobinHerbots 

Thanks a lot, i've juste tested it with my colleague and it works fine with IE8, FF22 and Chrome... But it fails under with IE7 !

Seems like the 2 "delete" lines in the remove are the reason but don't know why. It says me that the object doesn't support this action ;)
