### ISSUE TITLE
Problem with removing a mask with IE7

### ISSUE THREAD

**Issue by Macharius92** [RobinHerbots/Inputmask#302]
HI @RobinHerbots,

Since your commit for #301 , remove still doesn't work with IE7 (but everything's fine with FF and Chrome)

It seems that the following lines are throwing an exception :

``` javascript
delete input._valueGet;
delete input._valueSet;
```

**Comment by RobinHerbots** [comment]
@Macharius92 

Oh my, ... IE7   ;-)

**Comment by Macharius92** [comment]
@RobinHerbots 

Yeah i know but since we address multiple clients with various environments and various IT restrictions, we need to ensure cross-browser compatibility (even IE6 if we can...)

**Comment by RobinHerbots** [comment]
@Macharius92 , 

Fixed in the latest version

Robin
