### ISSUE TITLE
oncomplete function is called more times when pasting a value

### ISSUE THREAD

**Issue by ghost** [RobinHerbots/Inputmask#303]
My mask looks like this:

``` javascript
jQuery("#test").inputmask("DE 99 99999999 9999999999",{ "oncomplete": function(_el){alert("complete") } });
```

When I'm pasting the complete value **DE21870500001234567891** the oncomplete function is called more times. When I'm typing the value by keyboard it works fine an the oncomplete function is called one time.

Please can you help me?

**Comment by RobinHerbots** [comment]
@phlp85 , 

Fixed in version 2.3.13

Best regards, 
Robin
