### ISSUE TITLE
Setting inputmasked value with jQuery val does not work

### ISSUE THREAD

**Issue by gibacca** [RobinHerbots/Inputmask#305]
I have a field with inputmask '9'. When I try setting it to a value of '1' using jQuery val function, it does not seem to set the field. I am using the latest minified dist bundle. See the js fiddle here for the example: http://jsfiddle.net/Wauwf/10/

**Comment by RobinHerbots** [comment]
Have a look at the new fiddle http://jsfiddle.net/Wauwf/12/

**Comment by gibacca** [comment]
Looks good, thanks for the quick fix!
