### ISSUE TITLE
Regex does not work as I expected for time values

### ISSUE THREAD

**Issue by arame** [RobinHerbots/Inputmask#307]
I want to ensure the user can only enter in time values.
The requirements are that you can enter hours 0 -23 and optionally you can enter a decimal point and 5, 25 or 75
So valid values are 
8
0.25
23.75
4.5
So for my input field; <input type="text" id="txtInput" class="classInput" />
I have
    $(document).ready(function () {
        var regexTime = "^[0-9]|[1][0-9]|[2][0-3]?[.5]|[.25]|[.75]$";
        $(".classInput").inputmask('Regex', { regex: regexTime });
    });

But I enter any number and there is no masking or validation at all.

**Comment by arame** [comment]
I managed to solve the problem with this;
    $.extend($.inputmask.defaults.definitions, {
        't': { //Time
            validator: "([1][0-9]|[2][0-3][.]([2]|[7])[5])",
            cardinality: 5,
            prevalidator: [
                        { validator: "[0-9]", cardinality: 1 },
                        { validator: "[1][0-9]|[2][0-3]|[0-9][.]", cardinality: 2 },
                        { validator: "[1][0-9]|[2][0-3][.]|[0-9][.]([2]|[5]|[7])", cardinality: 3 },
                        { validator: "[1][0-9]|[2][0-3][.]([2]|[5]|[7])|[0-9][.]([2]|[7])[5]", cardinality: 4 }
            ]
        }
    });
$(document).ready(function () {
        $(".classInput").inputmask('t');
});

So that is good, but I do wonder why you would use the regular expressions library?

**Comment by RobinHerbots** [comment]
@arame

Just back bron Holiday :-) 

I will have a look at the regex tomorrow.

Bes regards
Robin

**Comment by RobinHerbots** [comment]
@arame , 

Is that a correct regex?

**Comment by RobinHerbots** [comment]
@arame , 

Can you have a try with the latest version and 

var regexTime = "([0-9]|[1][0-9]|[2][0-3]?)\\.(5|25|75)";
$("#input4").inputmask('Regex', { regex: regexTime });

**Comment by arame** [comment]
Thank you for that.
That solution did not work. I entered 34.45 and the mask did not stop me from doing so. I am using version 2.3.17

**Comment by RobinHerbots** [comment]
@arame , 

The above only works after version 2.3.22

**Comment by arame** [comment]
OK that was my fault for not doing what you said. I updated the latest version from Nuget, I now have 2.3.23.
However it still allows me to type "345". If I type a "3" then the only valid character that can follow it should be "."

**Comment by RobinHerbots** [comment]
@arame , 

In which browser did you test?  I cannot type 345.

Did you cleared the cache?

**Comment by RobinHerbots** [comment]
@arame , 

Check this http://jsfiddle.net/yt7P2/

**Comment by arame** [comment]
I am using ie9.
I find that in the jsfiddle the mask does not prevent me from typing in any character.

**Comment by RobinHerbots** [comment]
@arame, 

I will do a test in IE9

**Comment by RobinHerbots** [comment]
@arame , 

It seemed a problem with the jsfiddle in IE9

Try this one http://jsfiddle.net/yt7P2/2/

**Comment by arame** [comment]
That one worked, thank you very much.

**Comment by arame** [comment]
How do I mark that as correct?

**Comment by RobinHerbots** [comment]
You don't have to mark anything.  I closed the issue.
