### ISSUE TITLE
Paste problem on IE8

### ISSUE THREAD

**Issue by mbalbinot** [RobinHerbots/Inputmask#309]
I'm having a problem when I'm pasting a value on IE8.

My defaults:
        $.extend($.inputmask.defaults, {
            'placeholder':" ",
            'autoUnmask': true,
            'clearMaskOnLostFocus':true
        });

One of my masks:
        $(document).ready(function(){
            $(".maskCNPJ").inputmask("99.999.999/9999-99");
        });

When I paste a value, like 00000000000000, and leave the field, it shows empty.

I'm having this problem with all masks on IE8...
When I type the value, all works fine, but, on paste...

In Chrome all works fine...

Thanks,

**Comment by RobinHerbots** [comment]
@mbalbinot , 

Can you have a try with the latest version

**Comment by mbalbinot** [comment]
Now it's working fine!!!
Thanks
