### ISSUE TITLE
Problem with clearEmpty

### ISSUE THREAD

**Issue by ghost** [RobinHerbots/Inputmask#31]
```
$("#main-phone").inputmask({"mask": "99 (99) 999.9999", "placeholder": "-", clearEmpty: false });
```

I'm trying to show the current value of the input all the time (value="-- (--) ---.----") and not only on the hover and focus.
I tried searching everything but found nothing. Can you help?

**Comment by RobinHerbots** [comment]
You have to use

clearMaskOnLostFocus: false

best regards

Robin

2012/2/26 Benjamin Alijagić <
reply@reply.github.com

**Comment by RobinHerbots** [comment]
Robin Herbots wants you to try Dropbox! Dropbox lets you bring all your photos, docs and videos with you anywhere and share them easily.

Get started here: http://www.dropbox.com/link/20.isVXM2Wodd/NjE4NjgyMDA4OTc?src=referrals_bulk9&eh=489dbcf
- The Dropbox Team

---

To stop receiving invites from Dropbox, please go to http://www.dropbox.com/bl/ddc9e86fda74/reply%2Bi-3392135-4e353f769efcd9497749a4a79a80b5e2c79e34e1-318447%40reply.github.com
