### ISSUE TITLE
Is it possible to have just the mm/yyyy mask.?

### ISSUE THREAD

**Issue by athahar** [RobinHerbots/Inputmask#311]
I was trying to use the following for month/year mask 

$("#businessEstablished").inputmask("mm/yyyy", {
    "placeholder": "mm/yyyy",
    "baseYear": 1900
});

Instead of getting teh desired output, it seemed to render the following on focus -
mm/y/yymm/yyyymm/yyyy

Any thoughts?

**Comment by sh4d0w28** [comment]
1. It seems to me, that placeholder is usually a single symbol, is it nesessary to use a whole expression for it?
2. jquery.inputmask.date.extensions.js  has no "mm/yyyy" mask. When i tried dd/mm/yyyy, this works well.

$("#date").inputmask("dd/mm/yyyy", {"placeholder": "_","baseYear": 1900 });

**Comment by sh4d0w28** [comment]
sorry. i was wrong about placeholder. Second statement still seems to be actual.

**Comment by RobinHerbots** [comment]
@athahar ,

Try with $("#businessEstablished").inputmask("m/y", {
"placeholder": "mm/yyyy"
});

**Comment by RobinHerbots** [comment]
@athahar, @sh4d0w28, 

I will create an alias for it someday.

**Comment by athahar** [comment]
Thanks Robin.

**Comment by RobinHerbots** [comment]
@athahar, 

see latest version
 best regards, 
Robin
