### ISSUE TITLE
Hiding numbers when skipping optional mask (second one)

### ISSUE THREAD

**Issue by ablockchainfan** [RobinHerbots/Inputmask#312]
Posted the issue at stackoverflow but no answers yet.

http://stackoverflow.com/questions/18319361/jquery-inputmask-hiding-numbers-when-skipping-optional-mask-second-one

Is this a bug? or incorrect use.

**Comment by RobinHerbots** [comment]
I will have a look tomorrow

**Comment by RobinHerbots** [comment]
@vipink70, 

Fixed in the latest version.
