### ISSUE TITLE
Empty placeholder problem

### ISSUE THREAD

**Issue by prainho** [RobinHerbots/Inputmask#314]
//this is working 
$("#decimal").inputmask({ "mask": "9", "repeat": 10, "placeholder": ""});

//this isn't working.
//it only works if placeholder is not an empty string
$("#decimal").inputmask({ "mask": "9", "repeat": 10, "placeholder": "", numericInput: true });

**Comment by RobinHerbots** [comment]
@prainho, 

Why do you use an empty placeholder?

**Comment by prainho** [comment]
I want to do something like this: http://igorescobar.github.io/jQuery-Mask-Plugin/

Where I don't have any placeholder and the textbox is empty and when I start write the mask is applied only when I type something.

**Comment by RobinHerbots** [comment]
@prainho , 

You can use

$(selector).inputmask("integer");

or

$(selector).inputmask({ "mask": "9", "repeat": 10, greedy: false, numericInput: true });
