### ISSUE TITLE
decimal question

### ISSUE THREAD

**Issue by prainho** [RobinHerbots/Inputmask#315]
How can I define a decimal with integer part equal to 7 and decimal part equal to 2

Valid values decimal(7,2)
1.234.567,89
123.456,78
12.345,67
1.234,56
123,45
12,34
1,23
0,12

I've tested 

$("#decimal").inputmask("decimal", { "repeat": 7, radixPoint: ",", autoGroup: true, groupSeparator: ".", groupSize: 3, digits: 2 });

but this doesn't work because when I insert 1.234.567 I can't insert the decimal part.

if I do this:

$("#decimal").inputmask("decimal", { "repeat": 9, radixPoint: ",", autoGroup: true, groupSeparator: ".", groupSize: 3, digits: 2 });

Then I can insert 123.456.789 and I don't want this

**Comment by RobinHerbots** [comment]
@prainho ,

see issue #259
