### ISSUE TITLE
ERROR: no method '_valueGet' 

### ISSUE THREAD

**Issue by prainho** [RobinHerbots/Inputmask#316]
Just do this and try paste a value:

var $decimal = $("#decimal");
                $decimal.inputmask("decimal", { allowMinus: true, "repeat": 10, radixPoint: ",", autoGroup: true, groupSeparator: ".", groupSize: 3, digits: 2 });
                $decimal.on("paste", function (e) {
                        $decimal.inputmask("remove");
                        var previousValue = $decimal.val();
                        setTimeout(function () {
                            var currentValue = $decimal.val();
                        }, 0);
                    });

You will get this error Uncaught TypeError: Object #<HTMLInputElement> has no method '_valueGet'

**Comment by RobinHerbots** [comment]
@prainho, 

What are you trying to accomplish?  Why do you remove the mask within the paste event?

**Comment by prainho** [comment]
In the paste event I want to do additional tests to ensure that is a real decimal and that it's a valid decimal based on a custom validation. so on the paste event I remove the plugin, do what I need to do and in the end I set the plugin again. now you plugin is not expecting the remove in the paste event and I get that error. 

This can also be done if you tell me how can I disable for instance the paste event.

**Comment by RobinHerbots** [comment]
@prainho , 

Why don't you rely on the plugin for the decimal validation?  Or do you need some additional calculations.
