### ISSUE TITLE
2.x version changelog

### ISSUE THREAD

**Issue by klzns** [RobinHerbots/Inputmask#317]
Hi,

I would like to know what breaking changes are introduced in this version. I'm using an older version, and _apparently_ it's all fine, but I would like to know if something that changed may break something around here that I might not be seeing.

Thanks,

**Comment by RobinHerbots** [comment]
@brenoc, 

Version 2.x offers the same functionality as 1.x but with addition of multiple & optional masks.  An upgrade should be safe.

best regards, 

Robin

**Comment by klzns** [comment]
Thanks!
Em 26/08/2013 02:39, "Robin Herbots" notifications@github.com escreveu:
