### ISSUE TITLE
Problems to set value when input is readonly

### ISSUE THREAD

**Issue by nicomdp** [RobinHerbots/Inputmask#318]
When I set value and the input has the attribute readonly, it doesn't apply the mask and when I force to set the mask, the unmasked value is set to blanks.

**Comment by RobinHerbots** [comment]
@nicomdp , 

That because the events are blocked in readonly mode.  But I will have a look to reenable the setvalue.

**Comment by RobinHerbots** [comment]
@nicomdp , 

Can you retry with the latest version.

Best regards, 

Robin
