### ISSUE TITLE
Parenthetical Grouping doesn't seem to work at all

### ISSUE THREAD

**Issue by Flyarbonkers** [RobinHerbots/Inputmask#320]
All parenthetical grouping of patterns for the purposes of repetition of matched groups doesn't seem to work at all. Simple example:

(abc)+(def)

gets you ONLY "abcdef", NOT "abcabcdef" or other variations.

Other counts fail, too.

(abc){2,4}(def)

just gets you "abc" and then stopped dead.

**Comment by RobinHerbots** [comment]
@Flyarbonkers , 

You are talking about the regex extension I suppose.

Yep that doesn't work.  I will fix that soon.

**Comment by Flyarbonkers** [comment]
My apologies for not including a working example of the problem. I have all of 45 mins. of experience with jquery.inputmask and was simply putting it thru it's paces while evaluating it against others in it's general field, and discovered that the referenced idiom didn't work. This was my first problem post on Github, ever. I will attempt to do better in future.

Following is my example to demo the problem which I should have posted initially.

$("#FirstEmailEdit").inputmask('Regex', { regex: "(abc)+(def)" });

**Comment by RobinHerbots** [comment]
@Flyarbonkers, 

Fixed in the latest version in the 2.x branch
