### ISSUE TITLE
currency mask not work

### ISSUE THREAD

**Issue by gabrielnn77** [RobinHerbots/Inputmask#321]
$(selector).inputmask('€ 999.999.999,99', { numericInput: true });
expected: "€ **_.**_.___,__"
actual: "**,_**.**_.**_ €" and read only

same result with 
 $(selector).inputmask( '$ 999 999 999.99' ,{numericInput:true,radixPoint:'.' } );

**Comment by RobinHerbots** [comment]
@gabrielnn77, 

That is due a refactoring.  I will fix this asap.
 best regards, 

Robin

**Comment by RobinHerbots** [comment]
@gabrielnn77 , 

Can you have a try with the latest version. 2.3.24

**Comment by gabrielnn77** [comment]
i try with 2.3.26
$('#money').inputmask('€ 999.999.999,99', { numericInput: true }); 
only allows me to write the last character
ex. € **_.**_.___,_9

**Comment by RobinHerbots** [comment]
@gabrielnn77 , 

Have a look at http://jsfiddle.net/3yDW4/

**Comment by gabrielnn77** [comment]
I expect the same behavior as with decimal, but it can only write to the last position
see the example

**Comment by RobinHerbots** [comment]
@gabrielnn77 , 

On which browser are you testing?  Do you have problems in the jsfiddle?

**Comment by gabrielnn77** [comment]
firefox 23, in linux
same problem in jsfiddle, and in my server

**Comment by gabrielnn77** [comment]
http://jsfiddle.net/3yDW4/3/

**Comment by RobinHerbots** [comment]
@gabrielnn77, 

Can you explain a bit more the problem.  I tested with FF 23 on Linux and I can type without probs.

**Comment by gabrielnn77** [comment]
I will try to explain (i don't speak english...)
whit that mask i only can type in the lasth position
by ex. € **_.**_.___,_x <------ only can type in this position, not in the integer part
if i want to write 10 (integer ten), i have to write 1000
__,_1
__,10
_1,00
10,00
ome users complained it's confusing

with 'decimal' i can type in any place (before and after the radix point), and pressing the character ',' the cursor moves at the integer or float part

**Comment by RobinHerbots** [comment]
@gabrielnn77, 

I see what you mean.  I will fix that soon.

best regards, 

Robin

**Comment by RobinHerbots** [comment]
@gabrielnn77 ,

Fixed in the latest version

**Comment by electricfan** [comment]
any ideas how to change the currency symbol in the inputmask currency please?

**Comment by RobinHerbots** [comment]
@electricfan ,

with the prefix or suffix option
