### ISSUE TITLE
As well as maximum length, is there a minimum length check somewhere?

### ISSUE THREAD

**Issue by Flyarbonkers** [RobinHerbots/Inputmask#322]
I'm trying to do something trivial and I keep getting stuck. New to this library, so pointers would be very welcome.

I'm trying to validate a username field whose user input requirements are listed as the following:

'A username must be between 8 and 40 characters in length, consist of uppercase & lowercase letters, numbers and the special characters @,#,$, and ~.'

Additionally, as a lazy but easy way to indicate to the user that they haven't met the length requirement I plan to blank the field on entries less than 8 characters in length.

My 1st attempt was:

$("#NameEdit").inputmask('Regex', { regex: "[0-9A-Za-z\@#\$~]{8, 40}", "clearIncomplete": true });

This led to erratic behavior; I didn't see any examples where clearIncomplete was used with Regex and so I probably got the syntax wrong which would account for this.

So I tried defining my own extend and did this:

```
      $.extend($.inputmask.defaults.definitions, {
          'f': {  //masksymbol
          "validator": "[0-9A-Za-z\@\#\$\~]",
          "cardinality": 1,
          'prevalidator': null
      }});
      $("#NameEdit").inputmask({ "mask": "f", "repeat": 40, "greedy": false, "clearIncomplete": true});
```

but upon exiting the field it clears everything every time unless the field has exactly 40 chars in it. Which kind of makes sense since I don't have any place to specify the lower bounds of 8.

I tried various iterations of lots of other things (messing with the cardinality and changing the validator and so on...), all to no avail. To achieve the effect I'm looking for I've basically gotten rid of the clearIncomplete from the above and then do a hardcoded length check in the submit processing. Bleck. Clumsy.

If "repeat" only had a syntax like "repeat": 8-40 or some such that satisfies clearIncomplete when the lower bounds is reached I can see this working with what I have above.

Something as trivial as this has to have an easy way to do it with such a powerful validation system is this. I simply have to be missing something obvious/going about it all wrong. Any help would be appreciated.

**Comment by RobinHerbots** [comment]
see issue #202

**Comment by RobinHerbots** [comment]
@Flyarbonkers , 

You can use 

```
$("#test1").inputmask('*{8,40}', { clearIncomplete: true, greedy: false });
```

**Comment by jcmafra** [comment]
Hi, Robin, I'm working with Materialize 1.0.0  and experiencing issues in an input required with jquery.inputmask/3.3.4 :
1 -  If the input is empty required message is not been showing.
2 - I tried to use '*{10,11}' in order to control the minlength but had no success too. So if I type only one char the input is validated.

My source:
`
  $("#stdPhone").inputmask({
    mask: ["(99) 9999-9999", "(99) 99999-9999", ],
    keepStatic: true,    
  });
`

Could you please helpe me?

**Comment by PTAHume** [comment]
see if this helps https://stackoverflow.com/questions/72732945/how-to-set-minimum-length-for-form-input-with-jquery-inputmask/72739668#72739668 as a workaround
