### ISSUE TITLE
Problem with a mask in firefox

### ISSUE THREAD

**Issue by telray** [RobinHerbots/Inputmask#323]
jquery 1.8.3
jquery.inputmask 1.x
firefox 23.0.1

http://jsfiddle.net/telray/NZTst/2/

Input to introduce any of the characters and try to remove them backspace.
And only one character is deleted. If you click on the "check length" is displayed causing incorrect length.
In Chrome all right.
What to do?

**Comment by RobinHerbots** [comment]
@telray , 

DId you try upgrading to the latest version?  (2.3....)

**Comment by RobinHerbots** [comment]
@telray, 

You are correct I will have a look at it.

**Comment by RobinHerbots** [comment]
@telray, 

This seems like an bug in FF 23.x

It does correctly return the caret positioning.  Very strange.  I will have a further look at it.

**Comment by RobinHerbots** [comment]
@telray , 

It has todo with the . as validator.

**Comment by telray** [comment]
@RobinHerbots ,

In v2.3 you used
if (greedy == true && opts.placeholder == "") opts.placeholder = " "; in function getMaskTemplate(mask)
and my placeholder "" does not work.
Can you suggest another way of how to implement a mask to check all characters?

**Comment by RobinHerbots** [comment]
@telray, 

Have a look at http://jsfiddle.net/NZTst/7/  ;-)

**Comment by telray** [comment]
@RobinHerbots ,

Big Russian thank you! =)
All works in v2.x.
