### ISSUE TITLE
Lists of masks from inputmask-multi

### ISSUE THREAD

**Issue by andr-04** [RobinHerbots/Inputmask#324]
Hello. I'm the developer of the plugin [inputmask-multi](https://github.com/andr-04/inputmask-multi) which is using your plugin as a core. My plugin worked with v1.2.2 of your plugin inputmask.

Since v2.3.0 your plugin has the same functionality. So it will be nice if you add ability to use lists of masks which I've implemented already for the phone numbers.

**Comment by RobinHerbots** [comment]
@andr-04 , 

Seems like a good idea!

But you added a cc (country code I guess) and some descriptive fields..  Maybe I can add that kind of descriptive meta too.

best regards, 

Robin

**Comment by RobinHerbots** [comment]
@andr-04 , 

The current version can read the inputmask-multi format.  Expose the metadata.  The mask can be a function, so I can sort the incoming masks,

**Comment by andr-04** [comment]
Good solution!

What are your views on writing an extension of inputmask which will sort a list of phone masks and use a function as a mask? How to make it better?

**Comment by RobinHerbots** [comment]
You read my mind ;-)

That was the idea to write the phone implementation as an alias extension
for inputmask.    Let's first try to mimic the exact behavior as
inputmask-multi.

Enhancements can come later.

2013/9/4 Andrey Egorov notifications@github.com

**Comment by RobinHerbots** [comment]
@andr-04, 

I made a first commit of the phone alias.  The mask definitions get loaded and sorted.  However the mask switching isn't correct, yet.  I will have to tune the decision to switch the masks probably.
to be continued ;-)

**Comment by RobinHerbots** [comment]
@andr-04, 

Will you add the phone.extension to your repo or do I keep it here?

**Comment by andr-04** [comment]
Excuse me, I didn't watch your changes yet. If it works and if you agree I'll add your extension to my repo. But this extension must be in your repo as well.

**Comment by RobinHerbots** [comment]
@andr-04 , 

I need to create some additional tests in the qunit for it.  
I will keep the ref to your repo in the extension and keep the base phone-codes-json as an example.  The other phone-codes I will leave out and add a readme to get the files from your repo. If this is ok.

Feel free to add the extension to your repo.

best regards, 

Robin
