### ISSUE TITLE
Decimal mask with min and max limits

### ISSUE THREAD

**Issue by efreibe** [RobinHerbots/Inputmask#328]
Validating decimal numbers with a maxlength value makes inconsistent the use of decimal separator.
For example, defining a maxlength="5" allows me to enter 5 significant digits but if I use the decimal separator then I'm allowed to enter as much as 2 significant digits (assuming that I've configured 2 decimals).
I think that maybe is better to check this field for maximum and minimum values, this will dispense the need of specifying maxlength on input fields and results in a more clearer functionality.

**Comment by RobinHerbots** [comment]
@efreibe , 

I agree, but I will fix that later.

**Comment by RobinHerbots** [comment]
@efreibe , 

You can use integerDigits and digits option.
For a min and maxvalue see #409
