### ISSUE TITLE
"numericInput": true

### ISSUE THREAD

**Issue by itpmngt** [RobinHerbots/Inputmask#329]
When using {"numericInput": true}

$("#stones").inputmask({"mask": "9999 t", "numericInput": true })

the field is alignRight, but the caret stays in the first left position. The problem is that it does not accept any character on that position. Clicking in the placeholder of the last (fourth) character it works as expected.

Interesting is that if I double-click in the field it positions the caret in the last character - having a look in the code, the double-click validates the field, and positions the caret in the last position - what I think should be the default behaviour for a numeric field.

I think this is a easy fix and/or setting, but I'm still not acquainted with the whole functionality so rather log an issue.(tests were done on v2.36)

BTW, this is a great masking plugin, I like the approach of bringing the values to a  buffer, it does brings incredible flexibility to the amount of 'stuff' that can be done - great job.

Best,

Joe Rosa

**Comment by RobinHerbots** [comment]
@itpmngt , 

Fixed in version 2.3.38

Best regards, 

Robin

**Comment by itpmngt** [comment]
Hi Robin

Thanks for the prompt action - much appreciated.

There is a side effect: it is reversing the value. e.g. if we type '70' in the field and then $(this).val() - it returns '07' All numeric values go 'nuts' :-)

Any suggestion?

Thanks

Joe Rosa

**Comment by RobinHerbots** [comment]
Hi Joe,

Which version of the inputmask are you using?  And on which browser?  In my
tests it runs correctly.

Yes those numerics drive me crazy too  ;-))

2013/9/12 Joe Rosa notifications@github.com

**Comment by itpmngt** [comment]
Hi Robin

Yes, you're right. Seems the issue relates to the autoUnmask option. So to re-create the problem using the latest version (2.3.40) on Chrome - Windows:

$("#stones").inputmask({"mask": "9999 t", "numericInput": true, "autoUnmask": true })

Thanks

Joe Rosa

**Comment by RobinHerbots** [comment]
@itpmngt , 

Fixed in the latest version.

Best regards, 

Robin
