### ISSUE TITLE
Backspacing at the beginning of a form acts like a DEL

### ISSUE THREAD

**Issue by dmt2501** [RobinHerbots/Inputmask#33]
Great work with this plugin! It's been really useful.

I have one issue with it's positioning:

1) Go here:
http://jsfiddle.net/pmV9t/1/

2) Enter any random date

3) Move cursor to the very beginning of the form, and press backspace.

Result:
When you're at the very beginning of a form/textbox, pressing backspace should not do anything because backspace only deletes what's behind your cursor. However, when you press it here it deletes the character in front of it.

**Comment by RobinHerbots** [comment]
fixed !
