### ISSUE TITLE
Issue removing characters from masked inputbox

### ISSUE THREAD

**Issue by bfeldhake** [RobinHerbots/Inputmask#330]
Couple of different scenarios here.

1) I've got a mask list handling a currency mask for me, and input works as expected. However, if I've entered $100,000.00 and try to remove any characters, it automatically changes my input box to the last mark in the list.

[$100,000.00 after deleting a character changes to $   , 10,000.00]

2) I get unpredictable results when pressing backspace in date masked inputs. For example, removing the first digit of the month works as expected, but removing the second digit of the month messes up the rest of the formatting. (MM/DD/YYYY format)

[09/10/2013 after removing the "9" from the month shows 01/02/Y013]

See (http://jsfiddle.net/rEbp3/) for examples.

**Comment by bfeldhake** [comment]
Not sure if this is more relevant to #330 or #331, but in a date masked input, if I highlight a character(s) and press delete or backspace, I can no longer place my cursor in front of the character(s) that were just removed and begin typing.

[09/17/2013, highlight 17 and backspace. Cursor can no longer be placed before the DD that remains, but instead always hops to the end of the field]

I get similar but not the same behavior in a phone masked field. [(999) 999-9999] If I click just before the dash and backspace 3 times, everything works as expected. But if I highlight the 3 numbers before the dash and press backspace, my cursor jumps to the end.

http://jsfiddle.net/rEbp3/1/

**Comment by RobinHerbots** [comment]
@bfeldhake , 

Can you have another try with the latest version.

**Comment by bfeldhake** [comment]
Everything from the most recent comment seems to be fixed!

There appears to still be some issues with the initial money scenario, though. (Though I opted to go another route with my solution for this, so it's not as pressing.)

Thanks!
