### ISSUE TITLE
Cursor always jumps to end of masked input.

### ISSUE THREAD

**Issue by bfeldhake** [RobinHerbots/Inputmask#331]
See (http://jsfiddle.net/rEbp3/) for examples.

When masked field is empty (Currency2) the cursor stays where it is supposed to be, but every other field hops the cursor to the end of the string before letting you put it back where you intended it to be.

Try placing the cursor in the DD portion of the MM/DD/YYYY field.

**Comment by RobinHerbots** [comment]
@bfeldhake , 

See new behavior in the latest version
