### ISSUE TITLE
Issue assigning value to input with list of possible masks.

### ISSUE THREAD

**Issue by bfeldhake** [RobinHerbots/Inputmask#332]
I've got a currency input with 9 possible masks (simplest way I found to handle currency input). Assigning a value of 100000.00 to the input auto-fills the mask incorrectly.

The result looks like $1 0,0 0,0 0.00.

**Comment by RobinHerbots** [comment]
@bfeldhake , 

I will have a look at it.

I already made some changes for the case when deleting input and for the caret positioning

**Comment by RobinHerbots** [comment]
@bfeldhake , 

Fixed in the latest version
