### ISSUE TITLE
When both showMaskOnFocus and showMaskOnHover are used, optional parts not displayed when using "tab" to input

### ISSUE THREAD

**Issue by dlikhten** [RobinHerbots/Inputmask#333]
Example:

$("...").inputmask(mask: "(999) 999-9999[x9999]", greedy: true)
- Let us say the user FIRST enters `(123) 456-7891` The input will hide the optional part.
- When the user hovers of the field, the mask will be `(123) 456-7891x____`
- HOWEVER if the user does not hover, but rather uses "tab" or the "next" / "prev" buttons on an iOS device, the mask will be `(123) 456-7891`

**Comment by RobinHerbots** [comment]
@dlikhten , 

Fixed in the latest version.
