### ISSUE TITLE
Problem with inputmask("remove")

### ISSUE THREAD

**Issue by saucemax** [RobinHerbots/Inputmask#337]
Business case:
   Mask on page load
   Show mask for duration of page use
   Remove mask on submit (do not save the mask)

Issue:
   Trying to remove the mask during the submit event doesn't work.  Setting a break point at line 121 is moot as the page is posted as I begin to step through code. I created a switch case, "removeimmediately", and moved all the code inside the timed out function (beginning at line 121) into a local function which is then called on timeout from the original remove case and immediately from the new case.

   I only mention this because I think either I've missed something or this is an oversight and can be easily remedied.  And I think the business case provided here is common enough to warrant a fix for the next patch.

Thanks.

**Comment by RobinHerbots** [comment]
@saucemax, 

Can you specify the version you are using.

Best regards, 

Robin

**Comment by saucemax** [comment]
I was using an older version but upgraded for this specific issue and now am using the latest.  Issue is in both releases.  The issue is the timeout.  It's not an issue for other events... blur and the like.  But for submission it's not working.  Now again, perhaps I've missed something, but this is what I've found.
Thanks,
-Robert

**Comment by RobinHerbots** [comment]
@saucemax , 

Is this still a problem with the latest version?  As the remove does not contain a timeout anymore.
