### ISSUE TITLE
patchValueProperty fails in Chrome

### ISSUE THREAD

**Issue by ekidd** [RobinHerbots/Inputmask#34]
It appears the if statement to sniff for **lookupGetter** is being ignored by Chrome, causing errors with _valueGet().

**Comment by RobinHerbots** [comment]
It seems that there is some issue in chrome (& chromium) for the **lookupGetter**

I added an extra check for succesfull retrieving the property, otherwise we fallback to the 'old' functionality with jquery.val patch

best regards, 
Robin
