### ISSUE TITLE
Not able to enter numeric value is textbox: Andriod device

### ISSUE THREAD

**Issue by PankajShrivastava** [RobinHerbots/Inputmask#340]
Currently we are facing issue which is happening in Andriod device. In our application there are few fields which accepts numeric value, but user is not able to enter any value there. When user tries to enter any value in these fields nothing is getting typed neither numeric nor alphabets. For example these are zipcode, dateofbirth, phone number

I suspect we are using jQuery(compId).mask(mask); and this is creating issue and doesn;t allows to enter any value.

I am pasting my sample code which we are using for these fields
<textbox name="..."  @converter('..MaskedNumberConverter', regExToBean='[^0-9]', patternExToUI='99999-9999')" 
                        maxlength="10" constraint="Before_Start" 
                        onCreate="@command('formatTextbox', uuid=self.getUuid(), unmaskedValue='99999?-9999', maskedValue='#####-####')" >
                    </textbox>

and in formatTextBox we are calling js and mask function is called.

Any help will be highly appreceated. Again thanks in advance.

**Comment by RobinHerbots** [comment]
HI,

Which masking plugin are you using as I suspect this is not the
jquery.inputmask.

best regards,

Robin

2013/9/27 PankajShrivastava notifications@github.com
