### ISSUE TITLE
Wrong incomplete state when using TAB

### ISSUE THREAD

**Issue by daltones** [RobinHerbots/Inputmask#341]
Hi RobinHerbots! First of all, thanks for the great plugin!

I've had this issue and it can be seen in jquery.inputmask demo page.
- Focus first date input with mouse click.
- Complete it.
- Press TAB to focus next date input.  (-> Complete state for first date)
- Complete it.
- Press TAB. (-> Incomplete state for second date!)

The problem seems to occur with all kind of masks.

I found this issue on Chrome and Firefox.

(Sorry if the English is bad)

**Comment by RobinHerbots** [comment]
@daltones , 

Fixed in the latest version.

See demo page

best regards, 

Robin
