### ISSUE TITLE
Problem with multi-mask & selection

### ISSUE THREAD

**Issue by daltones** [RobinHerbots/Inputmask#343]
When the input is multi-mask and there's a selection range, just the first mask definition works.

I don't know if is complicated work with a generic range. But I think it's important at least handle the whole selection case, because when some input was focused by TAB (pressed on previous input), the whole text is selected.

The problem can be seen here: http://jsfiddle.net/3AAym/3/

Thanks!

**Comment by RobinHerbots** [comment]
@daltones , 

I will have a look at it.

Best regards, 

Robin

**Comment by RobinHerbots** [comment]
@daltones , 

Fixed in the latest version.

I need to add some test cases for partial selection.  

best regards, 

Robin

**Comment by daltones** [comment]
Thanks @RobinHerbots! =)
