### ISSUE TITLE
Decimal Mask and Disabled Input Control

### ISSUE THREAD

**Issue by bmw46033** [RobinHerbots/Inputmask#344]
It appears If an Input html control is disabled and you set the val() via JQuery, the mask is not applied.  It is only applied if the control is enabled.

We have calculated fields where we want the mask applied to the result but the user cannot edit the input box.

**Comment by RobinHerbots** [comment]
@bmw46033 , 

Can you specify the version of the inputmask & in which browser.
I tested on Chrome and don't have a problem.

**Comment by bmw46033** [comment]
I am using 2.x and IE10.  I re-downloaded 2.x and it is working now.  Thank you.  Must have been just a prior build issue.
