### ISSUE TITLE
redundant spaces in the field

### ISSUE THREAD

**Issue by glosswordteam** [RobinHerbots/Inputmask#350]
There are some redundant spaces in fields when spaces are used in the mask.

Example:

``` php
$('#example').inputmask( { mask: "9 9 9 9", greedy: false, placeholder: "" } ); // 3 spaces
$('#example').inputmask( { mask: "9 9 9 9", greedy: true, placeholder: "" } ); // 7 spaces
```

I've found that this is inside writeBuffer(). I guess, all spaces should be removed after joining the buffer.

InputMask version: 2.3.60

**Comment by RobinHerbots** [comment]
@glosswordteam, 

That was because the placeholder were translated to " " when greedy true.
I changed the behavior in the latest version.

Can you have a test.

**Comment by glosswordteam** [comment]
I see 3 spaces in both greedy modes. Enabled greedy mode has beed fixed, but spaces still exist.
Let me illustrate:

![image](https://f.cloud.github.com/assets/201113/1397685/ec763492-3c8c-11e3-8dd2-362544483d51.png)

**Comment by RobinHerbots** [comment]
@glosswordteam, 

That is because you also have 3 spaces in your mask.  The placeholder is used for the mask definitions and not for non masking elements.  What do you want to accomplish?
