### ISSUE TITLE
Brazil phone-codes

### ISSUE THREAD

**Issue by fals** [RobinHerbots/Inputmask#352]
Currently the extension supports "+55-##-####-####" to Brazil format. But there're regions at Brazil that already uses "+55-##-#####-####" with nine digit at the second pattern!

**Comment by RobinHerbots** [comment]
@fals , 

I did the update in the phone-codes.

Can you have a try

**Comment by fals** [comment]
I tried it, but the pattern didn't make the nineth digit optional.

**Comment by RobinHerbots** [comment]
Try with 5512123451234  and then try typing 551212341234 didn't the mask
made the switch?  (if not did you cleared your browser cache)

You can also type 55121234<space>1234

2013/10/18 Filipe Augusto Lima de Souza notifications@github.com

**Comment by fals** [comment]
Works typing space into the optional digit!

**Comment by RobinHerbots** [comment]
I missed the minus  try also with 55121234-1234

2013/10/18 Filipe Augusto Lima de Souza notifications@github.com

**Comment by fals** [comment]
Woking well here! Great job! Thank you!
