### ISSUE TITLE
Hide mask on non-empty input

### ISSUE THREAD

**Issue by mirzagitov** [RobinHerbots/Inputmask#355]
When ShowMaskOnFocus = false, showMaskOnHover = false mask is hidden unless you type a valid char for the mask.

Is it possible to add option like ShowMaskOnNonEmpty?

Mask prevents input text length detecting by other plugins, even if placeholder = "".
And I also can move caret to the empty space using arrow buttons.

Sorry for my English=)
Thanks!

**Comment by RobinHerbots** [comment]
@moongrate , 

Can you provide the mask pattern you are using?

**Comment by mirzagitov** [comment]
$.extend($.inputmask.defaults.definitions, {
    'V': { 
        "validator": "[0-9A-HJ-NPR-Z]",
        "cardinality": 1,
        'prevalidator': null
    }
});
$.extend($.inputmask.defaults, {
    placeholder: "",
    showMaskOnFocus: false,
    showMaskOnHover: false
});

$(object).inputmask({ "mask": "V", "repeat": 17});

Setting greedy to false solves the problem.

**Comment by mirzagitov** [comment]
http://jsfiddle.net/qz7QU/

**Comment by RobinHerbots** [comment]
@moongrate , 

Fixed in the latest version.

best regards, 

Robin
