### ISSUE TITLE
Uncaught TypeError: Object #<Object> has no method 'prop' 

### ISSUE THREAD

**Issue by hack3r3d** [RobinHerbots/Inputmask#357]
When using this plugin with Drupal 7.20 and I get this error in my console.

Uncaught TypeError: Object #<Object> has no method 'prop' 

I'm building my form using the Drupal Form API.

The element I'm looking at adding a mask to has the id of edit-contact-phone.

jQuery(document).ready(function($) {
    $('#edit-contact-telephone').inputmask({'mask': '802-555-5555'});
});

Is this an issue with this plugin not working with jQuery v1.4.4?

**Comment by RobinHerbots** [comment]
@hack3r3d , 

Probably. The plugin makes use of jquery.valhooks.  Those are introduces in jquery 1.7 I guess.

**Comment by hack3r3d** [comment]
That would make sense. Now I'll look at getting drupal's jquery updated. Thanks for the cool plugin.

**Comment by hack3r3d** [comment]
Yep, upgrading jquery to 1.8 fixed it.
