### ISSUE TITLE
Email regex does not work

### ISSUE THREAD

**Issue by VladimirPal** [RobinHerbots/Inputmask#359]
Hi!
From your documentaion:

Example simple email regex:

```
$(document).ready(function(){
   $("#numeric").inputmask('Regex', { regex: "[a-zA-Z0-9._%-]+@[a-zA-Z0-9-]+\\.[a-zA-Z]{2,4}" });
});
```

But it does not work
![](https://www.evernote.com/shard/s18/sh/6c7eee2d-6834-4b56-997b-286020b06ae8/0b545ccf8d10f4eb8279976ed1a5634c/deep/0/2Tbank.png)

**Comment by RobinHerbots** [comment]
@Cheguevara , 

Can you specify the version an browser you use. Can you provide a jsfiddle.

**Comment by VladimirPal** [comment]
I had a version 2.3.0, installed by bower.
With 2.3.65 no problem.
