### ISSUE TITLE
Undo redo operations not working properly

### ISSUE THREAD

**Issue by devrus91** [RobinHerbots/Inputmask#363]
Steps to reproduce:
1. go to http://jsfiddle.net/FhKxV/2/
2. Highlight all text in input
3. Press Ctrl+X
4. Press Ctrl+Z

Expected Result:
value will be restored after pressing Ctrl+Z
Actual result:
input was blank (with empty value)

**Comment by RobinHerbots** [comment]
@ruslanfedoseenko 

Fix in version 2.3.69

**Comment by RobinHerbots** [comment]
does not work in the jsfiddle ? but otherwise it works

**Comment by RobinHerbots** [comment]
@ruslanfedoseenko , 

Now it is fixed!!  See jsfiddle.
