### ISSUE TITLE
Input mask adapter for angualr

### ISSUE THREAD

**Issue by greengerong** [RobinHerbots/Inputmask#365]
Angular adapter for angualr : [https://github.com/greengerong/green.inputmask4angular](https://github.com/greengerong/green.inputmask4angular)

**Comment by RobinHerbots** [comment]
@greengerong , 

This is not really an issue I guess ;-)

Thx for writing an agular adapter.  I haven't used angular yet, maybe I should.  I am a bit of a Backbone fan.
