### ISSUE TITLE
currency $ 100.51 with autoUnmask returns 10051

### ISSUE THREAD

**Issue by andywolk** [RobinHerbots/Inputmask#366]
autoUnmask removes everything. May this be fixed?

Also. How to set a non-constant count of digits?
.inputmask("$ 999,99", options ); // not only 5
.inputmask("$ 999'999,99", options ); // or 8

**Comment by RobinHerbots** [comment]
@andywolk , 

The unmasking is correct behavior.  The mask is unaware that your masks is a currency.
Dynamic masks are not yet supported.  You can mimmick the behavior be defining multiple masks or masks with optional parts.

**Comment by RobinHerbots** [comment]
@andywolk , 

I will add this functionality to the decimal extension later

**Comment by RobinHerbots** [comment]
@andywolk , 

You can now use the onUnMask option to hook into the unmasking process.
Anyway, I will also enhance the decimal extension to return a decimal instead of an unmasked string.
