### ISSUE TITLE
Support for Android default browser

### ISSUE THREAD

**Issue by RobinHerbots** [RobinHerbots/Inputmask#368]

**Comment by RobinHerbots** [comment]
Someone has a problem with the stock browser?

**Comment by FransVDB** [comment]
Hi Robin,
I've tested the inputmask plugin on my Android smartphone (Sony Xperia Mini Pro, Android 4.0.4) and the plugin doesn't work on the stock browser. The software and hardware keyboards don't type anything in inputfields that have a mask.
Textfields with masks work as expected though.

I've done some debugging, and it seems that the jquery keyup, keydown and keypress events aren't fired on input fields.
However, when you apply a numeric mask, the events are fired after all...

Example
This doesn't work:
$("#test1").inputmask("***\* ***\* ***\* ****");

This works fine:
$("#test2").inputmask("decimal", { "radixPoint": ",", "autoGroup": true, "groupSeparator": ".", "groupSize": 3 , "digits": 2});

Can anyone else confirm this?

**Comment by RobinHerbots** [comment]
@FransVdb, 

Thx for the feedback!

I will have a look.

**Comment by RobinHerbots** [comment]
@FransVdb , 

Can you sent the useragent string?

**Comment by FransVDB** [comment]
@RobinHerbots 
Mozilla/5.0 (Linux; U; Android 4.0.4; nl-be; SonyEricssonSK17i Build/4.1.B.0.587) AppleWebkit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30

Done some more testing today, some masks seem to work, others don't. I'll post a jsfiddle example later.

**Comment by FransVDB** [comment]
@RobinHerbots 

I found the problem. If you set the maxlength property of an inputfield as the same length of the mask (or less), none of the keyboard events get fired. Propably because the character is added in the inputfield first, and then the placeholder gets deleted, this would cause the length of the string to be longer then the maxlength, so the events won't fire.

This only happens on Android though, no other browsers I've tested seem to have this problem.

I made a jsfiddle example: http://jsfiddle.net/4ta2K/

Sorry if I caused any confusion, your plugin does fully work on Android, just don't set the maxlength property :)

**Comment by RobinHerbots** [comment]
@FransVdb, 

Now they will both work on android stock browser.
See latest tweak in js.jquery.inputmask

You can verify in the jsfiddle example.

**Comment by FransVDB** [comment]
Alright, it works now. Thanks for the fix!

But I ran into another issue, the auto-suggest or auto-complete feature of the keyboard messes up the mask when typing. If I turn off auto suggest, everything works perfectly.
It seems like the auto-suggest feature inserts multiple characters at once, and the plugin doesn't delete the wrong ones.

I tried this, but no luck so far.
input type="text" id="test" autocomplete="off" autocorrect="off" autocapitalize="off" autosuggest="off" spellcheck="false"

**Comment by RobinHerbots** [comment]
@FransVdb, 

I will need to listen to the input event for android devices.  For Mobile Chrome it already does.

**Comment by Talkless** [comment]
I have problem inside Cordova application in Android 2.2 and 2.3.3. I guess it's using default Android browser..?

Take a look:

http://i.imgur.com/CsFNffw.png

I've wrote comment there (maybe I've better wrote it here..?):
https://github.com/RobinHerbots/jquery.inputmask/issues/28#issuecomment-29609854

**Comment by RobinHerbots** [comment]
@Talkless , 

Thx for the feedback.  

I will have a look at it later.

**Comment by Enfree** [comment]
Reproduced again. Take a look:
http://jsfiddle.net/qmfkt3aq/3/
No keydown/keyup events fires. Was tested under android default browser version 4.2.2(was reproduced), but under 5.2 browser version all works fine.

**Comment by RobinHerbots** [comment]
@Enfree , 

Are you sure it works under 5.2?  Or is just the ime autosuggest disabled?

**Comment by Enfree** [comment]
@RobinHerbots,
Sorry, probably the fiddle was bad :( . Thats new one: http://jsfiddle.net/ovymcefh/
Was tested on Android default browsers under:
LG D410 (browser version 5.2.34) inputs works
OnePlus 1 (5.1.1) inputs works
Philips W3568 (4.2.2) first input doesnt work
Samsung GT-S 7562 (4.0.4) first input doesnt work

Reproducing doesnt depends on autosuggest.

**Comment by time-wcrp** [comment]
Many thank.
