### ISSUE TITLE
change event possibly firing inappropriately

### ISSUE THREAD

**Issue by sabr49** [RobinHerbots/Inputmask#37]
First off thank you for an amazing plugin. 

I have been working with an old version of the plugin (.3.5) but have noticed this behavior in the current version as well - in the version I have the following code fires on blur :

bind("blur.inputmask", function() {
                    var input = $(this);
                    input.removeClass('focus.inputmask');
                              if (_val.call(input) != undoBuffer) {
                                input.change();
                        }

In my case I was masking a date field (.inputmask("m/d/y")).

If the user tabs into the field when blank and then tabs out without making any changes then the following is true:
_.val.call(input) == "__/**/**" (I am not using the autoUnmaskoption as I normally want the slashes saved with my data)
undoBuffer = ""

This causes the change event to fire.

To me it would seem if the user hasn't entered any data and just tabbed into and out of the field that the change event should not be triggered even if I am not using the autoUnmaskoption.

Is this the correct behavior?

**Comment by RobinHerbots** [comment]
Hi, I agree, I will have a look at it.  

Robin

**Comment by sabr49** [comment]
Ok great. If I could add one more thing, just because this has come up in our testing.

The following three scenarios in my mind should yield $(xx).val() = ""
1. Tab in and out without entering data
    A. No change event fired
2. Click in and out without entering data
   A. No change event fired.
3. If the field currently has data in it, and then the user erases the entire field
  A. Change event fired.
      a. The current value of the field should not be the value of the mask. It should be blank. I believe this is true even if    you want to save the mask with your data.

**Comment by RobinHerbots** [comment]
Hi, Ive made some changes in the dev branch which should cover case 1-3, can you check this?

**Comment by sabr49** [comment]
Will do. I'll have some downtime at work today to look at it. Thanks a
ton for your responsiveness.

Steven

On Mar 26, 2012, at 8:23 AM, Robin Herbots
reply@reply.github.com
wrote:

**Comment by RobinHerbots** [comment]
Ok thx, 

I also added case a in the dev branch.  ....

**Comment by sabr49** [comment]
Ok. So scenario 1 and 2 look great. However scenario 3 I think is not
covered, and you may argue that it is acting correctly the way it is.

Again, going back to the example I am testing which is a d/t field with a
mask of m/d/y "**/**/__". If I enter 3/26/2012 into the field and tab off I
get the following written to the console (using the following
$('.inputMask').change(function() { console.log({change: $(this).val()}) }))

>  "3/26/2012"

Now, if I go back to the field and clear it out completely and tab off, I
get a change event and the console records:

>  "**/**/__"

Now, I know that the code that is running after the change event fires
(copied below) will clear out the field setting its value to blank and any
subsequent calls to $('.inputMask').val() will equal blank, however, when
change fires, it is still the value of the mask. So, if say I had something
hooked to the input fields change event that retreives $(this).val() it
will incorrectly equal the value of the mask instead of blank.

Let me know your thoughts.

Steven

if (nptValue != undoBuffer) {
$input.change();
}
if (opts.clearMaskOnLostFocus) {
if (nptValue == _buffer.join(''))
input._valueSet('');
else { //clearout optional tail of the mask
clearOptionalTail(input, buffer);
}
}

**Comment by RobinHerbots** [comment]
Are you sure you took the latest version on the dev branch?  The code you
copied below is only running in certain options and does not handle the
return in this case.  Checkout hte changes in patchvalueproperty fn.

Robin

Op 26 maart 2012 16:10 schreef sabr49 <
reply@reply.github.com

**Comment by sabr49** [comment]
I apologize.. Strange, didn't see that branch before when I when I was
looking for it.. Looks awesome and is working correctly.

Thanks so much for your help.

On Mon, Mar 26, 2012 at 10:26 AM, Robin Herbots <
reply@reply.github.com

**Comment by RobinHerbots** [comment]
No problem ;-)  I thank you for the input!!

I will merge the changes to the master branch this evening.

best regards,

Robin

Op 26 maart 2012 16:37 schreef sabr49 <
reply@reply.github.com
