### ISSUE TITLE
autoUnmask does not seems to work with form.serialize()

### ISSUE THREAD

**Issue by Rouche** [RobinHerbots/Inputmask#371]
Hi,

I am masking using this:

inputmask('$ 999 999 999.99', { numericInput: true, autoUnmask : true });

when posting via Ajax, i receive this server side: $ ___ 345 634.56

Is there something i do wrong? or the serialize() does not work? For information this plugin is removing the mask on serialize() http://digitalbush.com/projects/masked-input-plugin/

**Comment by RobinHerbots** [comment]
@Rouche 
Can make a jsfiddle With the maskedinput to show the unmasking with form.serialize

**Comment by Rouche** [comment]
For what its worth:
http://jsfiddle.net/mMkG9/5/

But jsfiddle wont show the received json. when i check the network of my application the mask is there in the form data.
limit:$ ___ ___ __4.57
comments:

**Comment by RobinHerbots** [comment]
@Rouche, 

The idea was that you provide an example of the maskedinput and not the inputmask  ;-)

**Comment by Rouche** [comment]
Sorry :P

http://jsfiddle.net/mMkG9/10/

**Comment by RobinHerbots** [comment]
@Rouche, 

I added the name attribute to enable the serialize function todo it's job.

http://jsfiddle.net/mMkG9/11/

I type 123456 in inputmask
and 123456 in maskedinput

click on send
result => input_mask=123456&masked_input=

**Comment by RobinHerbots** [comment]
And a working fiddle for IE http://jsfiddle.net/mMkG9/14/

**Comment by Rouche** [comment]
this is definatelly weird. There must be a conflicting JS somewhere.

I added the optional ? in front of mask so clicking send takes partial numbers.

http://jsfiddle.net/mMkG9/15/

On the jsfiddle, yours is ok and maskedinput doesn't work.

Oh well, i guess there will be nothing easy :/

**Comment by RobinHerbots** [comment]
maybe you call an unmask for the maskedinput. somewhere?

Anyway, maybe you can post the plugins you are loading so I can verify for eventual conflicts.

best regards, 

Robin

**Comment by Rouche** [comment]
I just implemented a spring formatter to make sure everything is ok for now.

if i have time ill try to debug.

thanks for the help.

**Comment by Rouche** [comment]
Plugins:

```
<link rel="stylesheet" th:href="@{/assets/css/bootstrap.css}" />
<link rel="stylesheet" th:href="@{/assets/css/fuelux.css}" />
<link rel="stylesheet" th:href="@{/assets/css/bootstrap-responsive.min.css}" />
<link rel="stylesheet" th:href="@{/assets/css/font-awesome.css}" />
<link rel="stylesheet" th:href="@{/assets/css/bootstrap-editable.css}" />
<link rel="stylesheet" th:href="@{/assets/css/jquery-ui-1.10.3.custom.css}" />
<link rel="stylesheet" th:href="@{/assets/css/bootstrap-override.css}" />

<script type="text/javascript" th:src="@{/assets/scripts/jquery-1.10.2.min.js}"></script>
<script type="text/javascript" th:src="@{/assets/scripts/jquery-ui-1.10.3.all-lightness-none-none.min.js}"></script>
<script type="text/javascript" th:src="@{/assets/scripts/loader.js}"></script>
<script type="text/javascript" th:src="@{/assets/scripts/i18n/jquery.ui.datepicker-en.js}" charset="UTF-8"></script>
<script type="text/javascript" th:src="@{/assets/scripts/jquery.cookie-1.3.1.js}"></script>
<script type="text/javascript" th:src="@{/assets/scripts/jquery.maskedinput.js}"></script>
<script type="text/javascript" th:src="@{/assets/scripts/jquery.inputmask.js}"></script>        
```

**Comment by ahocquet** [comment]
I have exactly the same issue.

autoUnmask doesn't work when submitting the form. Worst, it even breaks the $.serialize() jquery function :

```
$('form#RfqForm').serialize()
TypeError: undefined is not a function
```

It appears that's because you return a real Number in  onUnMask function.

**Comment by RobinHerbots** [comment]
@ahocquet , 

I wil have a look.

**Comment by RobinHerbots** [comment]
http://jsfiddle.net/mMkG9/34/  pointing to the problem

**Comment by Rouche** [comment]
interesting.

Ive never been able to point out where it was.

GG.

**Comment by RobinHerbots** [comment]
@ahocquet , 
I now return a string instead of a number and jquery serialize works now.

@Rouche , 
I meaned the problem with returning a number instead of text
I will do some test for unmasking on submit.  Maybe I can do a remove of the mask before submit?

As an option ?  removeMaskOnSubmit??

**Comment by Rouche** [comment]
Maybe, but i dont know jQuery enough to tell if you can register before the serialize() and not break anything.
