### ISSUE TITLE
unmaskedvalue didn't work for non-text field types

### ISSUE THREAD

**Issue by glosswordteam** [RobinHerbots/Inputmask#372]
Hello,

I've found that when input type differs from the "text", unmaskedvalue returns incorrect values. Try input type="tel", for example.

**Comment by glosswordteam** [comment]
See jQuery.extend($.valHooks

**Comment by RobinHerbots** [comment]
@glosswordteam , 

Yep I need to verify all input type=???

**Comment by RobinHerbots** [comment]
@glosswordteam ,

fixed in version 2.4.25

**Comment by glosswordteam** [comment]
Thank you. Will take a look.
