### ISSUE TITLE
Multi Mask for Mulit Lingual Sites

### ISSUE THREAD

**Issue by afattahi54** [RobinHerbots/Inputmask#373]
First I want to mention that the idea of having data-inputmask for inputs is great! With this feature the UI developers can easily configure the mask of the input  without any codings !!

Well I have another issue. My site is multi lingual so the mask may change base on each locale. 

Does the component supports changing the mask base on each locale.

 <input data-inputmask-fa_IR="'mask': '99-9999999'" data-inputmask-en_US="'mask': '99-9999999'" lang="fa_IR"/>

In this way the component, will get correct mask base on lang property.

If I want to speak more generally, is it possible to have more than one mask and select the correct one base on some property.
Is it possible to change the mask on the fly.

I appropriate if the solution has as less coding as possible ;)

Regards,
Alireza Fattahi

**Comment by RobinHerbots** [comment]
@afattahi54 , 

The mask option can be a function so you can put in whatever logic you want.  You only need to return a mask pattern or an array of mask patterns.

$(selector).inputmask({ mask: function(opts){
   //return mask based on whatever
}});

To change the mask on the fly you just have to call .inputmask( with the new mask)

Offcourse speaking of data-inputmask, the idea is to keep the data-inputmask attribute simple in format and informative in the html syntax.  We do not want to intrude the html with javascript put into strings!

So to solve this the aliases come in handy.

Just define your alias with all logic and options you need and in the input you put data-inputmask="'alias': 'myfancyalias'"
