### ISSUE TITLE
Looks like $.valHooks functions are used wrong

### ISSUE THREAD

**Issue by andywolk** [RobinHerbots/Inputmask#374]
Problems occur when $.valHooks is used by more than one plugin. Inside of jQuery between plugins setters and getters run sequentially, but inputmask plugin breaks this logic. The first problem is definitions.
Definitions from jQuery 1.10.2:
get: function( elem ) ...
set: function( elem, value ) ...

Inputmask does not provide elem:
var valueGet = ... function () { return this.value; };
var valueSet = ... function (value) { return this.value = value; };

Without .call(scope) "value" equals "elem"? I don't think this is good. Therefore any next plugin gets this.value with the elem inside.

May be? :
var valueGet = ... function (elem) { return elem.value; };
var valueSet = ... function (elem, value) { elem.value = value; return elem;};

The second problem is how a default getter/seter is called.
I see ".call":
var result = valueSet.call(elem, value);

.call is used when you want to control the scope that will be used in the function called. Since our definition "function (elem, value)" uses elem, and does not use "this", we should not use the .call:
var result = valueSet(elem, value);

I suggest to review the whole hooks logic.

**Comment by RobinHerbots** [comment]
@andywolk , 

Hmm, I think you are mixing things up.

The valhook definition in the inputmask is

``` javascript
   jQuery.extend($.valHooks, {
                                    text: {
                                        get: function (elem) {
                                            var $elem = $(elem);
                                            if ($elem.data('_inputmask')) {
                                                if ($elem.data('_inputmask')['opts'].autoUnmask)
                                                    return $elem.inputmask('unmaskedvalue');
                                                else {
                                                    var result = valueGet.call(elem),
                                                        inputData = $elem.data('_inputmask'), masksets = inputData['masksets'],
                                                        activeMasksetIndex = inputData['activeMasksetIndex'];
                                                    return result != masksets[activeMasksetIndex]['_buffer'].join('') ? result : '';
                                                }
                                            } else return valueGet.call(elem);
                                        },
                                        set: function (elem, value) {
                                            var $elem = $(elem);
                                            var result = valueSet.call(elem, value);
                                            if ($elem.data('_inputmask')) $elem.triggerHandler('setvalue.inputmask');
                                            return result;
                                        },
                                        inputmaskpatch: true
                                    }
                                });
```

The valueGet and valueSet are intenal to inputmask

**Comment by andywolk** [comment]
Not always, Robin.
This depends on what these variables contain (due to conditional clause):
var valueGet = $.valHooks.text && $.valHooks.text.get ? $.valHooks.text.get : function () { return this.value; };
var valueSet = $.valHooks.text && $.valHooks.text.set ? $.valHooks.text.set : function (value) { return this.value = value; };

**Comment by RobinHerbots** [comment]
@andywolk , 

Offcourse!!!  

I will fix that asap.

Thx

Robin

**Comment by RobinHerbots** [comment]
See latest commit

**Comment by andywolk** [comment]
Thanks, Robin! 
Will work for $.valHooks, but what about valueProperty and **lookupGetter**  (not tested, just question: what if someone uses the same scheme?):
function patchValueProperty(npt) {
...
   if (valueProperty && valueProperty.get) {
       ...
      npt._valueGet = function () {...};
      npt._valueSet = function (value) {...};
      ...
   } else if (document.__lookupGetter__ && npt.**lookupGetter**("value")) {
      ...
      npt._valueGet = function () {..};
      npt._valueSet = function (value) {...};
      ...
   }

**Comment by RobinHerbots** [comment]
@andywolk, 

Yes if someone uses the same _valueXXX then that could break functionality.

**Comment by andywolk** [comment]
Let this issue be opened for a while.
There is a project https://github.com/plentz/jquery-maskmoney
A few days ago I suggested to take the hook's logic from the inputmask: https://github.com/plentz/jquery-maskmoney/issues/97
I foresee problems with an implementation.

**Comment by RobinHerbots** [comment]
;-) lol
