### ISSUE TITLE
When using regex extension valid text is considered invalid

### ISSUE THREAD

**Issue by bes11** [RobinHerbots/Inputmask#375]
If I use regex extension like this:

``` javascript
$('#inp3').inputmask(
    'Regex',
    { regex: "[0-9]{3}", clearIncomplete: true }
);
```

and type `111` into input then text will be cleared when input loses focus.

jsfiddle: http://jsfiddle.net/dznL8/6/
Type `111` into every text input. Since `111` is a valid text for all of them, inputs should not be cleared on losing focus. But 2nd and 3rd text input will be cleared.
This example also shows that using `repeat: '*'` exhibits the same behavior.

**Comment by RobinHerbots** [comment]
@bes11 , 

Yes, this is not yet implemented.  I will fix that later.
best regards, 

Robin

**Comment by bes11** [comment]
OK, any plans or ETA on this?

**Comment by RobinHerbots** [comment]
http://jsfiddle.net/dznL8/7/ (updated references)

**Comment by RobinHerbots** [comment]
For the repeat \* I cannot determine wheter the mask is complete or not.  I will fix that by adding an undefined state to the iscomplete.

**Comment by RobinHerbots** [comment]
@bes11, 

The case of repeat \* is solved.
The regex partially.  It will not clear but it cannot yet determine wheter the mask is complete.

**Comment by RobinHerbots** [comment]
@bes11 , 

Fixed
