### ISSUE TITLE
Improvement to decimal extension

### ISSUE THREAD

**Issue by andersonrocha** [RobinHerbots/Inputmask#376]
Does not could make it implement the functionality of the existing plugin meioMask decimal, where the mask is always visible decimal with zeroes and as you typing values ​​will be completing the mask from right to left, including the decimal digits? See an example:
http://www.meiocodigo.com/projects/meiomask/#mm_demos

It is an interesting and useful feature. I've seen many systems that use meioMask only due to this feature of the decimal.

**Comment by RobinHerbots** [comment]
see #243

**Comment by andersonrocha** [comment]
Demand is somewhat similar.
In case the decimal field will always have the value 0.00.
As the user is typing the value, the value will be inserted from right to left.
For example: if the field being 0.00 and the user wants to enter a value of 15.00, typing just 15, the field will be 0.15. If you type one more zero, will be 1.50. So 1500 should be entered for the field to stay with 15.00.
In case the radix point is fixed and does not require typing of the same.

**Comment by RobinHerbots** [comment]
@AndersonRocha , 

Using the current decimal alias with placeholder : "0" ,digits :2 and digitsOptional : false you have something simular.

but for entering 15.00 you type 15  To my feeling that is much more natural.
