### ISSUE TITLE
Imporvement for allowing operators by the users

### ISSUE THREAD

**Issue by Babuit25** [RobinHerbots/Inputmask#377]
Hello Robin,

Firstly thanks for the wonderful plugin. I have been using this plugin in my framework developed newly. I have a reqirement were i would like to allow characters by module developers to be used only with in their modules.

Here i have a seperate function in the pageUtils called setMasks were i pass three parameters (field id, maks, options) to the inputMask() function.

```
        pageUtils.setMasks("#searchFild",{
                mask:"upper-case",
                repeat:6,                   
                greedy:false,
                                    allowChars:"%$"    <---------
        });
```

Here i have the difficulty in adding the allowChars property to the particular mask. (please check the above code). This allowChars should be accessed by the mask, whenever it is assigned in the mask.

Please advise on how to do this new property

Thanks
Babu A

**Comment by RobinHerbots** [comment]
@Babuit25 , 

Can you explain a bit more what you want to accomplish.
What is the allowChars for?  

The mask can be a function, so within that function you can do whatever you want.  It passes the options.
(see phone extension for an example)

**Comment by Babuit25** [comment]
Robin,

Consider a search box in one of the application module, i have a mask applied to it. 

```
    pageUtils.setMasks("#searchFild",{
        mask:"upper-case",
        repeat:6,                   
        greedy:false,
        allowChars:"%$"    <---------
    });
```

So in this case, the user can enter 
1. uppercase alphabets  and  also
2.  allowChars will allow only two operators ie (% and $) in the target input box.

I have created a  new alias called allowChars, which has the property allowOptionalCharsProp, but this again becomes a different mask. 

```
    (function ($) {
        $.extend($.inputmask.defaults.aliases, {
            'allowChars': {
                mask: "e",
                greedy:false,
                repeat:'*',
                allowOptionalCharsProp:"",
                rightAlignNumerics: false, //align numerics to the right
                definitions: {
                    "e": {
                        validator: function(chrs, buffer, pos, strict, opts){
                            return new RegExp("^([a-zA-Z"+ opts.allowOptionalCharsProp +"])$").test(chrs);
                        },
                        cardinality: 1
                    }
                }
            }
        });
    })(jQuery);


    pageUtils.setMasks("#workFlowFSD1",{
                    mask:"allowChars",
                    repeat:6,                           
                    allowOptionalCharsProp:"*&",
                    greedy:false
    });
```

I just want to allow the  developers a provision to add operators or character depending upon their requirement. ie ( allowChars:"%$") like this.

This allowChars should be accessed by all the masks, something similar like just an example. (repeat:"*") 

Thanks

**Comment by RobinHerbots** [comment]
You can access the allowChars by opts.allowChars

2013/11/12 Babuit25 notifications@github.com

**Comment by RobinHerbots** [comment]
@Babuit25, 

Can I close this issue?

**Comment by Babuit25** [comment]
Hi Robin,

I still could not solve this problem, higly require your help. I have a requirement were I should give a new property called allowChars  [  allowChar:"%&" ] . With this property the domain owners can assign whatever operators they want.
Many number of masks are used our project both page level, module level etc, so with those already existing masks, i wanted to introduce one more property called "alloChars:"%^" with that, so that they can allow, as per their scope.

```
        pageUtils.setMasks("#workFlowFSD2",{
                mask:"agentCode",
                repeat:10,                          
                allowchars:"*&",  <<--------------
                greedy:false
        });
```

This is my requirement, is there any possiblity to that.

**Comment by RobinHerbots** [comment]
@Babuit25 , 

Are all your masks defined as aliases?  If so you can pick up the allowChars option from those alias definition.  

As I understand you want to define which chars are extra allowed, and all masks should pick that up.  Is that correct?

**Comment by Babuit25** [comment]
Yes Robert. You are correct. All the masks are defined as alias. Could give please me an example to use that. Here is the part of the definitions and alias

```
    jQuery.extend(jQuery.inputmask.defaults.definitions, {
        'A': { 
            validator: "[A-Za-z]",
            cardinality: 1,
            casing: "upper", //auto uppercasing
            definitionSymbol: "^"
        }
        'allowChars':{
            validator: function(chrs, buffer, pos, strict, opts){
                return new RegExp("^([a-zA-Z"+ opts.allowChars+"])$").test(chrs) ;
            },
            cardinality: 1
        }
    });

    Now here in alias, how can i refer to the allow chars definition

    jQuery.extend(jQuery.inputmask.defaults.aliases, {
        'uppercase': {
            mask: "A",              
            greedy:false,
            repeat:'*'

        }
    });
```

Now here when i use this mask "uppercase", do i will have to uppercase mask property and also the allowchar &\* operators will be allowed along with that ?
        pageUtils.setMasks("#workFlowFSD2",{
                mask:"uppercase",
                repeat:10,  
                allowchars:"*&", <<----------------------
                greedy:false
        });

**Comment by RobinHerbots** [comment]
The definition should be a single char.  Maybe you can join the definitions
like below

 jQuery.extend(jQuery.inputmask.defaults.definitions, {
        'A': {

```
        validator: function(chrs, buffer, pos, strict, opts){
            return new RegExp("^([a-zA-Z"+
```

opts.allowChars+"])$").test(chrs) ;
            },

allowChars: "",
cardinality: 1, casing: "upper", //auto uppercasing definitionSymbol: "^" }
});

2013/11/26 Babuit25 notifications@github.com

**Comment by Babuit25** [comment]
Hi Robert,  

I have created a seperate mask, called "allowChars", which has the property called allowOptionalCharsProp, which can accept any operators. But as per our idea, i wanted to use the common property which can be used to in any masks

```
      jQuery.extend(jQuery.inputmask.defaults.definitions, {
        'A': { 
            validator: "[A-Za-z]",
            cardinality: 1,
            casing: "upper", //auto uppercasing
            definitionSymbol: "^"
        }
        'w':{
            validator: function (chrs, buffer, pos, strict, opts) {
                return new RegExp("^(["+opts.allowOptionalCharsProp+"])$").test(chrs) ;
            },
            allowOptionalCharsProp:'',              
            cardinality:1
        }
    });
```

---

```
    jQuery.extend(jQuery.inputmask.defaults.aliases, {
        'allowChars':{
            mask:'w',               
            greedy:false,
            repeat:'*'
        }   
    });
```

---

```
    pageUtils.setMasks("#workFlowFSD3",{
            mask:"allowChars",
            repeat:"*",                         
            allowOptionalCharsProp:"*&a",  <---------- It is working only on the allowChars Mask.
            greedy:false
    });
```

 But if i use this allowOptionalCharsProp in the below uppercase masks, it does not work, 

```
    pageUtils.setMasks("#workFlowFSD2",{
            mask:"UpperCase",
            repeat:"*",                         
            allowOptionalCharsProp:"*&a",  - 
            greedy:false
    });
```

 Please let clarify? Is there any way which i can do it. Or there is no fesiblity to do it in this plugin.
 Thanks for you information.

**Comment by RobinHerbots** [comment]
It is only possible as the validator in the definition picks up the value
of allowchars.  Otherwise it cannot be done

2013/11/26 Babuit25 notifications@github.com
