### ISSUE TITLE
Optional masks don't work

### ISSUE THREAD

**Issue by renatojf** [RobinHerbots/Inputmask#378]
If you have a mask like "(99) 9999[9]-9999" and tab out of the input field with only 8 digits (the mask is for 9), you will end up with the result "(99) 99999-999_"

The clearMaskOnLostFocus never gets triggered.

http://jsfiddle.net/Pjuxr/

**Comment by RobinHerbots** [comment]
https://github.com/RobinHerbots/jquery.inputmask/wiki/Howto:-Entering-optional-masks

**Comment by renatojf** [comment]
That is SO BAD. I don't even have words to describe how foolish that is. Whatever, I'll search for a better jQuery mask input.

**Comment by RobinHerbots** [comment]
as I would care  ;-)

**Comment by renatojf** [comment]
You should. Specially when you are developing stuff for other people to use.

**Comment by err0x1a** [comment]
This is sad, Robin updates the best plugin for masks in the web and you still critique his work?

Good lucky finding another, but this one has an excellent maintenance, a dedication unmatched, bugs that are fixed every day... other masks have different bugs that developers do not care.

You just have to create a routine to run what you want, exactly as described in the link he said.

Oh, I forgot that this generation is the JQuery generation, where everything is ready, you just need act like a robot.

Next time don't be a dick, and try to solve the problem "renatojf".

**Comment by renatojf** [comment]
When you search for a MASK plugin, you expect it to act like a MASK plugin. If I need to type in the special characters, the spaces, etc. then I don't need a mask.

That's my point. I'm not being a dick, I'm being reasonable because his plugin doesn't do what it say it does in the docs. And I already solved the problem.

**Comment by RobinHerbots** [comment]
@herz-atk , 

THX !!

@renatojf , 

Actually I do care, but with comments like yours I cannot help you.  
And if you already solved the problem, why don't you share your solution to everyone?

**Comment by renatojf** [comment]
Sure, download https://github.com/fabiomcosta/jquery-meiomask and be happy.

**Comment by RobinHerbots** [comment]
@renatojf 
Shouldn't there be a minimum age to participate on GitHub?

**Comment by renatojf** [comment]
It should. Specially when you try to develop things for other people.

**Comment by JCMais** [comment]
Really, this is really necessary?

If you are not satisfied, go on, it's an open source project, with a very permissive license, change it, improve it, send a pull request, or create a fork and work only on it, make your own project from it, and lets us all be happy. 

BUT if you are not willing to do anything, and just start blaming the author, shut up and grow up. I'm really tired of people in the community that doesn't help with anything and act like they are throwing money away using something that is free.

**Comment by felixjet** [comment]
@renatojf thx for the link, same problem here
