### ISSUE TITLE
Backspace gives strange results on masks with a fixed numeric part

### ISSUE THREAD

**Issue by FransVDB** [RobinHerbots/Inputmask#379]
Hi,
I ran into a problem when I was testing the inputmask plugin. Backspace gives sometimes very strange results on masks with a fixed numeric part.

Example:
$("#card").inputmask({"mask": "6703 9999 9999 9999 9"});
This will give you a input field with this mask: 6703 ____ ____ ____ _

When you fill in 6703 1234 5678 9012 3 and press backspace once, you get this result: 6703 12_4 5__8 9_12 _
When you leave out the fixed part (6703), or change it with text, backspace works just fine.

I made a jsfiddle example: http://jsfiddle.net/5nfN7/

**Comment by RobinHerbots** [comment]
@FransVdb , 

http://jsfiddle.net/5nfN7/1/ (updated reference)

I will have a look at it asap.

best regards, 

Robin

**Comment by FransVDB** [comment]
@RobinHerbots,

Thanks for looking into this.

I've tested your plugin a few months back (my project got shelved then) and I don't remember having this problem before.
So I've done the tests again with release 2.3.0 and everything works fine.

The issue only occurs in release 2.4.0 and the latest dev release. Thought this might help you investigating.

Thanks again!

**Comment by RobinHerbots** [comment]
@FransVdb , 

Fixed in the latest version
