### ISSUE TITLE
How to change inputmask mask based on dropdown context?

### ISSUE THREAD

**Issue by ylluminate** [RobinHerbots/Inputmask#38]
I'm using inputmask to format telephone numbers.  I'd like to set it up so that I am able to change the mask based on context of whether it's the USA/Canada, UK, or other countries.  Ie,:
`$("#user_phone").inputmask("mask", { "mask": "(999) 999-9999" });`

Presently this context would be changing based on a dropdown for the country code.  How would I implement this such that the mask will change context based on dropdown?

**Comment by RobinHerbots** [comment]
Hi, 

You can bind to the change event of the dropdown, and then apply a mask as you did before, depending on the selected value of the dropdown.  Unmasking of the previous mask is done automatically by applying a new mask.

best regards, 

Robin

**Comment by RobinHerbots** [comment]
Something like this, ....

$('#dropdownId').change(function() {
    var choice = $(this).val();
    switch(choice){
        case 'option1':
            $('#input').inputmask('(999) 99999999');
            break;
        case 'option2':
            $('#input').inputmask('999/99999999');
            break;
    }
});

Op 5 april 2012 09:48 schreef George Plymale <
reply@reply.github.com

**Comment by ylluminate** [comment]
Thanks Robin, got that working.  I am curious about an issue I'm seeing.  It seems as though with blur enabled to give error feedback that it's doubling input.  I've been simply trying to figure out where the error's coming into play and posted this: http://stackoverflow.com/questions/10035193/how-to-debug-user-entry-issues-in-javascript-with-webkit-developer-tools/

However, after yanking out some code, I found that when removing the following code stopped this multiplication of digit entry:

```

        $("#user_phone").blur(function () {
            var phone = $("#user_phone").inputmask('unmaskedvalue');

            if (phone.length != 10) {
                $("#user_phone").addClass("show_field_with_errors");
            } else {
                $("#user_phone").removeClass("show_field_with_errors");
            }
        });
```

Any idea as to why this may be occurring?
