### ISSUE TITLE
pull regex from elements' attributes

### ISSUE THREAD

**Issue by eidylon** [RobinHerbots/Inputmask#380]
Hi, maybe there's a way to do this, if not it would be lovely to have added. 

I want to be able to pull a regex validation from an attribute on the selected elements,
something along the lines of the following: 

$('input[type=text][regex]').inputmask('Regex', { regex: function () { return $(this).attr('regex') } });

I also tried these: 

$('input[type=text][regex]').inputmask('Regex', { regex: $(this).attr('regex') });
$('input[type=text][regex]').inputmask('Regex', { regex: this.attr('regex') });

**Comment by RobinHerbots** [comment]
@eidylon, 

This is a great idea, but I will extend it to not only work for passing a regex, but also for other stuff.
I'm thinking of data-inputmask-regex="......", .... and so on, and that the attribute gets merged into the options

BTW, you can already do something simular with the data-inputmask attribute.

<input data-inputmask="'alias': 'Regex', 'regex': 'your regex'" />

**Comment by RobinHerbots** [comment]
@eidylon , 

Fixed in the 3.0.3

use data-inputmask-regex attribute
