### ISSUE TITLE
Browser crashes after number of individual optional characters

### ISSUE THREAD

**Issue by andrewrota** [RobinHerbots/Inputmask#381]
I'm trying to set several optional characters after the mask so the input field looks like this: `_ _ - _ _` but the user can continue to enter a certain number of characters after that without repeating the initial pattern.

The following code has worked for me:

```
$(document).ready(function(){
    $("input").inputmask({"mask": "**-**[*][*][*][*][*]", "greedy": false});
});
```

However, when I increase the number of optional characters at the end of the mask it crashes the browser.

For example, this crashes my browser (latest version of Chrome).

```
$(document).ready(function(){
    $("input").inputmask({"mask": "**-**[*][*][*][*][*][*][*][*][*][*][*][*][*][*][*][*][*][*][*][*][*][*][*][*][*][*][*][*][*][*][*][*][*][*][*][*][*][*][*][*][*]", "greedy": false});
});
```

So, (shown here with the declarative configuration), this works well for me: http://jsfiddle.net/wEC2E/2/.  However if I want to increase the number of optional characters it crashes.

Am I implementing this feature the wrong way, or is there a limitation when using optional characters?  I apologize if this has already been called out as an issue but I couldn't find anything on it.

**Comment by RobinHerbots** [comment]
@andrewrota , 

The current implementation of optional masks will generate all combinations possible with including and excluding the optional part.  When I look at your example that will be alot of combinations ;-)  That will take too long and the browser will crash.

However, I'm working on that.  (dynamic masks)

But why don't you use a mask like "**-**[****************************]"

**Comment by RobinHerbots** [comment]
@andrewrota , 

http://jsfiddle.net/wEC2E/4/

**Comment by andrewrota** [comment]
@RobinHerbots, thanks for your quick response and for the alternate solution.  It looks like the solution you provided will do exactly what I need.  The placeholder option adds the functionality I was looking for where the optional characters have no visible mask.  Thanks!

```
<input data-inputmask="'mask': '**-**[******************]', 'greedy' : false, 'placeholder': '__-__                    '" />
```
