### ISSUE TITLE
Show mask without hover/focus

### ISSUE THREAD

**Issue by andrewrota** [RobinHerbots/Inputmask#382]
Is is possible to have the mask shown without hover or focus on the input field?  So the mask would be visible even if the user is not focusing or hovering on the input.

**Comment by andrewrota** [comment]
Apologies for the issue; I figured it out (`clearMaskOnLostFocus: false`).

**Comment by RobinHerbots** [comment]
You have to set the clearMaskOnLostFocus  option to false

2013/11/21 Andrew Rota notifications@github.com

**Comment by RobinHerbots** [comment]
Ha, at the same time ;-)

No problem!

2013/11/21 Robin Herbots robin.herbots@gmail.com

**Comment by akvaliya** [comment]
It disappears on form submit. Any solution to that?
