### ISSUE TITLE
gray text for mask, black text for entered characters

### ISSUE THREAD

**Issue by aveyD** [RobinHerbots/Inputmask#383]
This seems like it may be too much work as you would have to do something on each key press. For example, a date mask:

YYYY-MM-DD

then you start typing:

2013-11-DD

but it would do something like this under the hood:

< span class="blacktext" >2013-11-< /span >< span class="graytext" >DD< /span >

Or is this not a reasonable request?

If this is not possible how do i have the mask always show up as YYYY-MM-DD and then become "____ - __ - __" when i click in the input? (clearMaskOnLostFocus: false) and something else i would assume...

Thanks

**Comment by RobinHerbots** [comment]
@aveyD , 

It's a nice idea, but something for later.

Did you try the yyyy-mm-dd alias?  $(selector).inputmask("yyyy-mm-dd");

**Comment by aveyD** [comment]
this is the closest behavior to what i want to accomplish:

$('.date-field').inputmask("9999-99-99", { "placeholder": "YYYY-MM-DD", clearMaskOnLostFocus: false });

but when you mouse click in the input i want it to change from the placeholder to " ____ - __ - __ " cause it's a little hard to tell the difference between the mask and the Y's, M's, D's and what numbers the user has entered.

**Comment by RobinHerbots** [comment]
@aveyD,

What about this http://jsfiddle.net/CNCW8/

**Comment by aveyD** [comment]
oh yes, that works except i have to change it to this:

$("#date").inputmask("9999-99-99", { placeholder: "_" });

because when i click in the input it changes from the YYYY-MM-DD to yyyy-mm-dd. not sure why this is happening unless it's because there is no definition for 'y', 'm', or 'd'...?
Thanks for your help!

**Comment by RobinHerbots** [comment]
did you check the jsfiddle?

2013/11/26 David notifications@github.com

**Comment by aveyD** [comment]
yes, i put the placeholder with "YYYY-MM-DD" on my input and in my JS i put:

$('.date-field').inputmask('yyyy-mm-dd', { placeholder: '_' }).datepicker();

and when the mouse is not in the input it shows up as YYYY-MM-DD but when i click in the input it changes to yyyy-mm-dd and i cannot enter any values. I'm not sure if my datepicker is highjacking something...? If i change it to:

$('.date-field').inputmask('9999-99-99', { placeholder: '_' }).datepicker();

it works. Not sure why.

**Comment by aveyD** [comment]
Oooohhhhhhh, i figured it out. I was only including the jquery.inputmask.js ... not the jquery.inputmask.bundle.js

so it didn't have those definitions and alias' for 'y', 'm', and 'd'... 

edit: you can close this issue, unless you want to keep it on for fixing the half gray, half black text feature.

**Comment by RobinHerbots** [comment]
@aveyD , 

Great !! ;-)

I 'll keep the issue open for the above idea.  I also want to implement masking on non-input fields or explore was is possible in the direction of colored masks.

Robin

**Comment by RobinHerbots** [comment]
@aveyD , 

There is the colormask now
