### ISSUE TITLE
When selecting an item from the browser's autofill/autocomplete feature, input value is lost on field blur

### ISSUE THREAD

**Issue by pdecat** [RobinHerbots/Inputmask#386]
When selecting an item from the browser's autocomplete, the selected value is put into the field but then lost when the field looses the focus.

Here is a demo:
1. Go to http://jsfiddle.net/K655F/1/
2. Type 1999 into the "Year" field
3. Exit the field (an alert is shown on all browsers)
4. Submit the form once to enable the browser's autofill/autocomplete (ignore the error)
5. Re-run the JsFiddle
6. Click in the "Year"
7. Select 1999 from the browser's autofill/autocomplete
8. Exit the field (an alert is shown on modern browsers)
9. Selected value is lost

For modern browsers, handling the onChange event could be an option:
OK: Firefox 25, Chrome 31 and IE10.
KO: IE8 and IE9.

More details available at:
- http://stackoverflow.com/questions/11708092/detecting-browser-autofill
- http://furrybrains.com/2009/01/02/capturing-autofill-as-a-change-event/

**Comment by pdecat** [comment]
Same behaviour confirmed with jquery 1.8 through 1.10 and jquery.inputmask 2.3 through 2.6.

**Comment by pdecat** [comment]
One more thing: the placeholder must be empty to get the browser's autocomplete.

**Comment by alejandro-fiore** [comment]
+1

**Comment by asartz** [comment]
+1

**Comment by DanielGrobelny** [comment]
+1

**Comment by RobinHerbots** [comment]
I will have a look.

**Comment by Oikio** [comment]
Hello, same problem as in #641, investigated in Firefox.
IE11 does not want to open autocomplete on masked fields.

**Comment by RobinHerbots** [comment]
Fixed in the latest commit 

http://jsfiddle.net/K655F/7/
