### ISSUE TITLE
How to always display the placeholder, not only on focus or hover?

### ISSUE THREAD

**Issue by pdecat** [RobinHerbots/Inputmask#387]
Hi Robin,

is it possible to _always_ display the placeholder, not only when a field has the focus or when the pointer hovers it?

Regards,
Patrick.

**Comment by RobinHerbots** [comment]
Yes,

set clearMaskOnLostFocus: false,

2013/11/27 pdecat notifications@github.com

**Comment by pdecat** [comment]
I tried that, but it does not seem to work : http://jsfiddle.net/AtY8h/1/

**Comment by RobinHerbots** [comment]
I will have a look at it

2013/11/27 pdecat notifications@github.com

**Comment by RobinHerbots** [comment]
http://jsfiddle.net/AtY8h/2/

you have to set the boolean false not a "false" string

2013/11/27 Robin Herbots robin.herbots@gmail.com

**Comment by pdecat** [comment]
Oops ;)

Thanks!
