### ISSUE TITLE
Navigation with Tab and mask with Visual

### ISSUE THREAD

**Issue by Rouche** [RobinHerbots/Inputmask#388]
Hi, 
With a Maske dinput like this:

$('#selector').inputmask('999 %', { numericInput: true, placeholder: ' ' });

Navigating with a tab do not select the field and seems to lock in a position where you
cannot write anything.

Fiddle:
http://jsfiddle.net/hwS7Z/3/

Seems to be in relation to the isRTL (because of numeric input i guess), position should be set completelly to the right. It now position to left of mask. And remove selection.

**Comment by RobinHerbots** [comment]
@Rouche , 

Fix in the latest 2.x branch

Can you have a try.

Best regards, 

Robin

**Comment by Rouche** [comment]
Yep. Perfect!

Thanks!
