### ISSUE TITLE
Decimal extension - Cursor position on get-focus, autofill/autocomplete and remove mask on lost focus

### ISSUE THREAD

**Issue by dehaaneric** [RobinHerbots/Inputmask#389]
Hi all, 

First, many thanks to the author @RobinHerbots for creating this wonderful plugin.

I hope someone can help me accomplish the following, and hopefully it's supported:

http://jsfiddle.net/PenEF/3/
- When I use the tab-key to jump to the next input box, the cursor is placed at the beginning. I would like to see the cursor at the decimal point: **_.**_.___|,00. Although when you 'click' the box, this happens nicely.
- The mask is still applied when leaving the textbox, even when 'clearMaskOnLostFocus' is explicitly set to true.
- If the user exits te textbox, I would like to autocomplete the output, for example:
  "**100,**" results in "__100,00" or without mask "100,00".

The Ajax Control Toolkit has this behaviour: http://www.asp.net/AjaxLibrary/AjaxControlToolkitSampleSite/MaskedEdit/MaskedEdit.aspx. Look at the "Enter a Number (format: 9,999,999.99):" example.

Many thanks in advance.

**Comment by RobinHerbots** [comment]
Hi tweek82,

I will have a look at the first.

the clearMaskOnLostFocus only removes the mask when there was no input yet

for the thirth you can use something like see http://jsfiddle.net/PenEF/4/ (tab
out the field)

or you can use the decimal alias.  inputmask("decimal")

2013/12/2 tweek82 notifications@github.com

**Comment by RobinHerbots** [comment]
@tweek82 , 

First issue fixed in latest version of 2.x branch.

Can you have a try.

Best regards, 
Robin

**Comment by dehaaneric** [comment]
Hi @RobinHerbots, thanks for your quick reply. I will take a look at the changes as soon as possible and will give my feedback here.

Thnx again.

**Comment by dehaaneric** [comment]
Hi @RobinHerbots,

I did some tests and added some more functionality to make it more act like the AjaxControlToolkit MasedEditInput experience.

New jsfiddle: http://jsfiddle.net/4VTtM/3/

<strong>Failed test: navigation between inputs with tab</strong>
Using the tab-key to navigate between input fields, does not place the cursor at the decimal-seperator. But sometimes, after waiting for a few seconds, it works... Tested in JSfiddle and my own application with Chrome, FF and IE11.

<strong>Own extension - More auto complete with zero's</strong>
Your extension written on the KeyPress works perfectly. Exactly what I asked. Later on, I also wanted all the gaps to be auto-filled with zero's. Don't ask me why, but in the old webforms application we've rewriting, it's a requirement... So therefore I used the $.blur() event on the textbox.

<strong>Own extension - Decimal input behaviour</strong>
When the cursor was placed behind, the decimal-seperator, the added digits where appended to the left. I used the onKeyDown event to 'overwrite' the existing digit(s) and limit the input to two.

I'm not that good at javascript, so excuse me for the code :)

Perhaps you can take a look at the tab-issue?

Many thanks!

**Comment by RobinHerbots** [comment]
@tweek82, 

I tested the tab functionality on your fiddle but it seems ok.

I'm just tabbing through the fields.

**Comment by RobinHerbots** [comment]
@tweek82 , 

Can you give some feedback to the numeric extension.  Missing things?
