### ISSUE TITLE
Conflict with jqueryui datepicker

### ISSUE THREAD

**Issue by rsauchuck** [RobinHerbots/Inputmask#39]
Great plugin! I have run into some issues with the jQueryUI datepicker, though. Whenever I try to set the date via datepicker. teh month comes out incorrect and the date is truncated tot eh first character. So selecting April 26 2012 gives me "26/01/2___" instead

here is a snippet
It has some .net embedded in it
$("#<%= uiDateText.ClientID %>")
            .datepicker({  
                numberOfMonths: 1, 
                showAnim: 'blind',
                changeMonth: true,
                changeYear: true,
                constrainInput: true,
                dateFormat: '<%= GetDateFormat() %>', 
                monthNames: [<%= GetMonthNames() %>],
                monthNamesShort: [<%= GetMonthNamesShort() %>],
                dayNames: [<%= GetDayNames() %>],
                dayNamesShort: [<%= GetDayNamesShort() %>],
                dayNamesMin: [<%= GetDayNamesMin %>],
                <% if (ShowButtonImage = true) then %>
                <%= "buttonImage: '" + GetButtonImageURL("Images/calendar.jpg") + "'," %>
                <%= "showOn: 'button'," %>
                <% else %>
                <%= "showOn: 'focus'," %>
                <% end if %>
                buttonImageOnly: true,
                showButtonPanel: true,
                nextText: '&gt;',
                prevText: '&lt;'
            });

```
    }
    var dateFormatforMask;

    $("#<%= uiDateText.ClientID %>").inputmask("d/m/y");
```

**Comment by RobinHerbots** [comment]
Strange, we also use the datepicker plugin and have no problems.

What is the output of   '<%= GetDateFormat() %>', ?  Maybe try without the
 constrainInput: true, option.

(it's better to use  $("#<%= uiDateText.ClientID %>").inputmask("date"); //
gives better datehandling)

regards,

Robin

Op 12 april 2012 15:41 schreef rsauchuck <
reply@reply.github.com

**Comment by rsauchuck** [comment]
Thanks for the quick response!

I added this
$.extend($.inputmask.defaults.aliases, {
            'date': {
                mask: "d/m/y"
            },
            '<%= GetDateFormat() %>': {
            alias: "date"
        }
    });

and removed the datepicker constrain input (good catch)

and made the suggested update 

$("#<%= uiDateText.ClientID %>").inputmask("date");

It seems to have eliminated the conflicts. I have one other issue but I am opening another ticket as it does not relate directly to this issue.

**Comment by rsauchuck** [comment]
grrr the problem came back.

**Comment by RobinHerbots** [comment]
By using inputmask('date'); why don't you use the predefined mask in
inputmask.extentions?

Can you simulate the problem on jsFiddle or send me the 'rendered'
asp.netoutput.

best regards,

Robin

Op 12 april 2012 20:37 schreef rsauchuck <
reply@reply.github.com

**Comment by rsauchuck** [comment]
Thanks again Robin. It seems the problem only occurs when the datepicker input field already has content in it. The server is per-populating the date field either from the server or based on the current date. I see the correct date briefly then it gets reformatted.

input type="text" id="ctl00_ContentPlaceHolder1_txtFromDate_uiDateText" value="3/13/2012" name="ctl00$ContentPlaceHolder1$txtFromDate$uiDateText" class="hasDatepicker"

'''
$(function() {

```
    if  ($("#ctl00_ContentPlaceHolder1_txtFromDate_uiDateText").attr("disabled")){

        $("#ctl00_ContentPlaceHolder1_txtFromDate_uiDateText")
        .datepicker({  
            numberOfMonths: 1, 
            showAnim: 'blind',
            changeMonth: true,
            changeYear: true,
            beforeShow: function() {$('#ui-datepicker-div').css("z-index", 91); },            
            dateFormat: 'm/d/yy',
            monthNames: ['January','February','March','April','May','June','July','August','September','October','November','December',''],
            monthNamesShort: ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec',''],
            dayNames: ['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'],
            dayNamesShort: ['Sun','Mon','Tue','Wed','Thu','Fri','Sat'],
            dayNamesMin: ['Su','Mo','Tu','We','Th','Fr','Sa'],
            buttonImage: 'http://localhost/ToolCommerceDev/Images/calendar.jpg',
            showOn: 'button',

            buttonImageOnly: true,
            showButtonPanel: true,
            nextText: '',
            prevText: '',
            disabled: true
        })
    }else{

        $("#ctl00_ContentPlaceHolder1_txtFromDate_uiDateText")
        .datepicker({  
            numberOfMonths: 1, 
            showAnim: 'blind',
            changeMonth: true,
            changeYear: true, 
            beforeShow: function() {$('#ui-datepicker-div').css("z-index", 91); },               
            dateFormat: 'm/d/yy',
            monthNames: ['January','February','March','April','May','June','July','August','September','October','November','December',''],
            monthNamesShort: ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec',''],
            dayNames: ['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'],
            dayNamesShort: ['Sun','Mon','Tue','Wed','Thu','Fri','Sat'],
            dayNamesMin: ['Su','Mo','Tu','We','Th','Fr','Sa'],
            buttonImage: 'http://localhost/ToolCommerceDev/Images/calendar.jpg',
            showOn: 'button',

            buttonImageOnly: true,
            showButtonPanel: true,
            nextText: '',
            prevText: ''
        });

    }

    //$("#ctl00_ContentPlaceHolder1_txtFromDate_uiDateText").inputmask("date");
    switch('m/d/yy') { 
        case 'mm/dd/yy' || 'm/d/yy': 
            $('#ctl00_ContentPlaceHolder1_txtFromDate_uiDateText').inputmask('mm/dd/yyyy'); 
            break; 
        default: 
            $('#ctl00_ContentPlaceHolder1_txtFromDate_uiDateText').inputmask('dd/mm/yyyy'); 
    } 


});
```

'''

**Comment by RobinHerbots** [comment]
hi  rsauchuck, 

Can you retry the issue with the latest changes in the dev branch.  Also take the extentions.

Best Regards, 

Robin
