### ISSUE TITLE
Mask shifts in date field when editing field after text highlighted

### ISSUE THREAD

**Issue by Macrofig** [RobinHerbots/Inputmask#390]
This is easily reproducible in Chrome and Firefox.

If the text is highlighted then replaced the mask seems to shift. For example, the mask `mm/dd/yyyy`, will turn to `01/12/2014` but then, after selecting the data and replacing it with new data, you get: `01/md/dyyy`.

Not a huge issue but it does make one do a double take.

I can try to get more information on which browsers this occurs in if needed.

**Comment by RobinHerbots** [comment]
@Guamaso ,

I wil have a look at it

best regards, 

Robin

**Comment by RobinHerbots** [comment]
@Guamaso, 

The shift in the placeholder is fixed in the latest 2.x branch

**Comment by Macrofig** [comment]
Awesome, thanks!
