### ISSUE TITLE
[date] selecting/highlighting part of date and typing new figure renders mask to have an offset

### ISSUE THREAD

**Issue by adelina1985a** [RobinHerbots/Inputmask#391]
Example date: 13/12/2013
I select the day (first 2 digits: 13) and the field turns into: 1d/dm/m013
I select the month (3rd and 4th digit: 12) and the field turns into: 13/1m/m013
After completing the dates, for instance 11/12/2013, 13/11/2013 respectively, the dates, despite being correct, don't pass validation, namely inputmask("isComplete") returns false.

**Comment by RobinHerbots** [comment]
@adelina1985a , 

Which version are you using and can you give the exact mask you are using.

**Comment by adelina1985a** [comment]
Sorry for the late reply, I thought I would be notified if I started the issue as I don't want to subscribe to the entire repo.
The version in use is 2.4.6 but I'm afraid I don't know what exact mask you're referring to, the date format is dd/mm/yyyy if that helps.

**Comment by RobinHerbots** [comment]
@adelina1985a , 

Fixed in the latest 2.x version.
