### ISSUE TITLE
integer / decimal allowMinus not working with input type number

### ISSUE THREAD

**Issue by MartinVerges** [RobinHerbots/Inputmask#393]
Hello,

wen using a HTML5 input type="number"... field, its not possible to use the allowMinus: false option. If you try to put a minus in this field its working well, but if you change the value by up/down key you can move to values below zero.

Hope you can fix that issue. Thanks for the great plugin.

Best Regards
Martin

PS: Workaround is using min="0" to prevent this problem.

**Comment by RobinHerbots** [comment]
@MartinVerges , 

Thanks for the input.  I will have a look at it in milestone 2.7

**Comment by vijjj** [comment]
Hi Robin,

In normal input:text field, allowMinus:false option is not working in version 3.0.30. Please find the test case below. I could't find a corresponding one in tests.js

test("numeric alias with allowMinus:false - vijjj", function () {
    var $fixture = $("#qunit-fixture");
    $fixture.append('<input type="text" id="testmask" />');
    $("#testmask").inputmask("numeric", {
        radixPoint: ".",  
        integerDigits:6,
        //digits: 2,
        allowMinus: false
    });

```
$("#testmask")[0].focus();
$("#testmask").Type("123456");
caret($("#testmask"), 0);
$("#testmask").SendKey("-");

equal($("#testmask").val(), "123456", "Result " + $("#testmask").val());
$("#testmask").remove();
```

});

**Comment by RobinHerbots** [comment]
@vijjj , 

allowminus and input type=text is fixed.

**Comment by RobinHerbots** [comment]
@MartinVerges , 

The inputmask does not work in combination with type=number

Maybe a question to everyone.  What should be expected.  The plugin changes the type to text and applies the mask or the plugin just ignores the input or the first option and we mimick the behavior of type = number.

**Comment by RobinHerbots** [comment]
@MartinVerges , 

I opted the second option.  When the type=number the input is ignored.
