### ISSUE TITLE
How to set mask in variable

### ISSUE THREAD

**Issue by silvioprog** [RobinHerbots/Inputmask#395]
Hello,

Can I set a masked value in variable using this plugin? E.g. (pseudo code):

``` js
var val = "56300000";
var cep;
cep = $.inputmask(val, "99.999-999");
console.log(cep); // the result would be 56.300-000
```

Thanks!

**Comment by RobinHerbots** [comment]
Hi Silvio,

The inputmask works on inputfields, so you cannot call it directly to
format some value to a masked one.

You can workaround it be defining a input then apply the inputmask, set the
value with jQuery.val and then get the value.

Anyway I like the idea and I will add that functionality.

best regards,

Robin

2013/12/15 Silvio Clecio notifications@github.com

**Comment by silvioprog** [comment]
Hello Robin,

I fixed it with your idea:

``` js
$.extend($.fn.fmatter, {
    cnpj: function(cellvalue, options, rowdata) {
        var dummy = $("<input>").attr("type", "hidden").val(cellvalue).inputmask("99.999.999/9999-99");
        var val = dummy.val();
        dummy.remove();
        return val;
    }
});
```

Please tell me if you implement this feature, I use it in other languages ​​and think beautiful. :)

Thank you very much for your help bro! :+1:

**Comment by RobinHerbots** [comment]
@silvioprog , 

Valueformatting in jqgrid with the inputmask plugin.  That is a nice use case ;-)

**Comment by RobinHerbots** [comment]
@silvioprog , 

You can know do this!  Thx for the idea!

``` js
$.extend($.fn.fmatter, {
    cnpj: function(cellvalue, options, rowdata) {
                return $.inputmask.format(cellvalue, { mask: "99.999.999/9999-99"});
    }
});
```

**Comment by rakstk01** [comment]
> Hello Robin,
> 
> I fixed it with your idea:
> 
> ```js
> $.extend($.fn.fmatter, {
>     cnpj: function(cellvalue, options, rowdata) {
>         var dummy = $("<input>").attr("type", "hidden").val(cellvalue).inputmask("99.999.999/9999-99");
>         var val = dummy.val();
>         dummy.remove();
>         return val;
>     }
> });
> ```
> 
> Please tell me if you implement this feature, I use it in other languages ​​and think beautiful. :)
> 
> Thank you very much for your help bro! 👍

$.extend($.fn.fmatter, {
    cnpj: function(cellvalue, options, rowdata) {
        var dummy = $("<input>").attr("type", "hidden").val(cellvalue).inputmask("99.999.999/9999-99");
        var val = dummy.val();
        dummy.remove();
        return val;
    }
});

**Comment by rakstk01** [comment]
> Hello Robin,
> 
> I fixed it with your idea:
> 
> ```js
> $.extend($.fn.fmatter, {
>     cnpj: function(cellvalue, options, rowdata) {
>         var dummy = $("<input>").attr("type", "hidden").val(cellvalue).inputmask("99.999.999/9999-99");
>         var val = dummy.val();
>         dummy.remove();
>         return val;
>     }
> });
> ```
> 
> Please tell me if you implement this feature, I use it in other languages ​​and think beautiful. :)
> 
> Thank you very much for your help bro! 👍



> @silvioprog ,
> 
> You can know do this! Thx for the idea!
> 
> ```js
> $.extend($.fn.fmatter, {
>     cnpj: function(cellvalue, options, rowdata) {
>                 return $.inputmask.format(cellvalue, { mask: "99.999.999/9999-99"});
>     }
> });
> ```

Hello, I'm stuck on this issue. Could you please write how to use the example you gave?

Thanks
