### ISSUE TITLE
Error editing the integer value (Mask: decimal, Digits: 3)

### ISSUE THREAD

**Issue by manrueda** [RobinHerbots/Inputmask#396]
I have an input like this: 

``` HTML
<input data-inputmask="'alias':'decimal','radixPoint':'.','digits':'2'"></input>
```

Trying to edit the integer part of the number, the cursor moves but the value is not changed. If I remove the decimal limit of the declaration of the mask, the error does not occur and i can freely change the value.

It is a bad implementation of the mask or really an error?

**Comment by RobinHerbots** [comment]
@ManRueda , 

I will have a look at it.

best regards, 
Robin

**Comment by RobinHerbots** [comment]
@ManRueda , 

Fix in the latest version in the 2.x branch

**Comment by manrueda** [comment]
Thanks for fix it so fast

Regards.-
