### ISSUE TITLE
IE8 paste event for data input mask field is not working.

### ISSUE THREAD

**Issue by pavanik** [RobinHerbots/Inputmask#397]
I'm having a problem when I'm pasting a value on IE8.

I used input mask for phone number.

$(document).ready(function(){
$(".homephone").inputmask("(999)999-9999");
});

We have applied the validation rule for phone number field. 

Steps that we are following are below

1) First we are deleting one number from the field. Then its displaying the error message.
2) Then we copying the phone number(without phone format just plain numbers) and pasting in the field. After onchange event the error message is still existing and the value in field resetting to back.

Please suggest me on this.

**Comment by RobinHerbots** [comment]
@pavanik , 

Can you simulate the behavior in an jsfiddle.

That will be much easier to debug the correct situation.

Best regards, 

Robin

**Comment by RobinHerbots** [comment]
@pavanik , 

Is this issue still valid?
