### ISSUE TITLE
Allow input that doesn't validate against mask

### ISSUE THREAD

**Issue by rauchmat** [RobinHerbots/Inputmask#398]
Is it possible to allow input that won't validate against the mask?

Example:
mask: "AT99 9999 9999 9999 9999"
- When the input starts with "AT" I wan't to see the mask with the definition from above.
- When the input start with any other character (not "AT") I don't want to have a mask, therefore supporting arbitrary inputs.

**Comment by RobinHerbots** [comment]
@mattreek , 

Maybe try this:

``` javascript
 $("#test2").inputmask({
                mask:
                    function (opts) {
                        $.extend(opts.definitions, {
                            'Y': {
                                validator: "[B-Zb-z]",
                                cardinality: 1,
                                casing: "upper"
                            },
                            'Z': {
                                validator: "[A-SU-Za-su-z]",
                                cardinality: 1,
                                casing: "upper"
                            }
                        });
                        return ["YZ*************************", "AT99 9999 9999 9999 9999" ];
                    }
            });
```

**Comment by rauchmat** [comment]
@RobinHerbots ,

Thanks for your reply. Although your variant is better than mine, it isn't exactly what I wanted, because it doesn't allow arbitrary inputs (in length and characters) for strings not starting with 'AT'. My approach was to remove the mask, when the first two characters are different from 'AT' and mask the input again otherwise, but I couldn't make it work. Do you have an idea, how I could accomplish this behavior?

**Comment by RobinHerbots** [comment]
Use the onKeyValidation callback which is executed on every validation
(keystroke)
Verify the input and remove the masking with ...inputmask("remove").

Eventually also bind on the input event todo the reverse.  (reapplying the
mask)

2014/1/7 mattreek notifications@github.com

**Comment by rauchmat** [comment]
onKeyValidation wasn't sufficent because it wasn't triggered, when I hit the BACKSPACE key to delete the "AT" prefix of the mask. I tried onKeyUp and it works finally. It's not the most elegant solution but in case somebody needs it here is the code anyway: http://jsfiddle.net/mattreek/z5wN9/1/.

Thanks for your support!
