### ISSUE TITLE
Having mmm (Jan, Feb,... ) in DateFormat

### ISSUE THREAD

**Issue by umartopia** [RobinHerbots/Inputmask#400]
Currently the plugin does not allow us to have a format which has mmm (Jan, Feb, ...)

Can you please let me know whether it is possible or not?

ITS URGENT

**Comment by RobinHerbots** [comment]
@umartopia, 

Out of the box this is not possible, but it is sure possible to implement.
What are you requirement?  What I mean do you want the user to enter jan, feb, ... or the number and show it as the text?

**Comment by umartopia** [comment]
I want the user to enter jan/feb/mar and while reading I need to read it as number
i.e.: user will enter 12/jan/2013 and I need to read it as 12/01/2013
However, even if we are not able to read it as 12/01/2013 then also it is OK...... But user must be able to enter it as 12/jan/2013

**Comment by RobinHerbots** [comment]
@umartopia, 

You can start from the alias dd/mm/yyyy.  override the definition of 2 to allow typing  jan, feb etc, ...

and then implement the onUnMask to convert the jan feb, etc to 01, 02, etc

**Comment by melloware** [comment]
+1 for this feature also to convert the mmm properly. Thanks!
