### ISSUE TITLE
optional mask at the begginning

### ISSUE THREAD

**Issue by rrd108** [RobinHerbots/Inputmask#401]
Hi, 

I want to work with Hungarian date format what is yyyy-mm-dd and let the user type dates in a loose format, like if they type just "5" I would like to set the date to 2013-12-05 (actual year, actual month, given day). onincomplete callback would be perfect for this, but as I use "y-1-2" for mask when the user type "5" it is added as a part of the year.

I am sure it is possible but an not find out how. Could you give me a hint?

**Comment by RobinHerbots** [comment]
@rrd108 , 

What do you want exactly?  What I mean, do you always want the year and month prefilled or not?  Just how can the mask know that you mean 5 as a day and not 2015?

Anyway I would start from the yyyy-mm-dd alias and then override the definition for y. Set a prefill in the prevalidator and return  the char and new position.

**Comment by rrd108** [comment]
Thanks. That is enough help for me.
