### ISSUE TITLE
Multiple inputs masked, Integer mask doesn't allow typing

### ISSUE THREAD

**Issue by albatrocity** [RobinHerbots/Inputmask#402]
I'm having an issue with a basic form using two masked inputs. I want to mask a telephone input and an integer input for comma-grouped numbers. I've made a [JSFiddle](http://jsfiddle.net/vA4cu/) that replicates the issue.

``` javascript
    $("input#user_loan_size").inputmask("integer", {
        autoGroup: true,
        groupSeparator: ",",
        groupSize: 3
    });
    $("input#user_phone").inputmask("(999)-999-9999");
```

It seems that I can add as many basic (non-integer) masks as I want, but as soon as I add an integer mask, I can't enter anything into the other inputs. In the example above, only the phone mask works and I am unable to type in the integer-masked input.

Conversely, if I define the integer mask second:

``` javascript
    $("input#user_phone").inputmask("(999)-999-9999");
    $("input#user_loan_size").inputmask("integer", {
        autoGroup: true,
        groupSeparator: ",",
        groupSize: 3
    });
```

I can only type in the integer-masked input. The mask on the phone input is still visible, but I can't type in it.

Am I binding these incorrectly or is this a bug? Thanks in advance for any guidance.

**Comment by ermish** [comment]
+1 
I also noticed this problem when I updated to the latest version.

**Comment by albatrocity** [comment]
@xasion noticing that the current state of the [2.6 branch](https://github.com/RobinHerbots/jquery.inputmask/tree/2.6) doesn't suffer from this issue. At least not that I've noticed.

**Comment by RobinHerbots** [comment]
@albatrocity , @xasion ,

I will have a look at it.
Best ragards
Robin

**Comment by RobinHerbots** [comment]
@albatrocity, @xasion , 

Fixed.  http://jsfiddle.net/vA4cu/1/

**Comment by albatrocity** [comment]
Awesome. Thanks Robin!
