### ISSUE TITLE
QUnit issues

### ISSUE THREAD

**Issue by rbirkby** [RobinHerbots/Inputmask#403]
Hi,

I've downloaded the trunk tarball from github and ran the qunit tests and got 5 errors. Does this mean trunk is in an unstable state?

![image](https://f.cloud.github.com/assets/203034/1849910/00741424-76c0-11e3-830b-55c9239b733d.png)

I also ran the tests tagged with 2.4.0 and there is a similar number of test failures.

Thanks,
Richard

**Comment by RobinHerbots** [comment]
No, branch 2.x is or should be stable but the qunit tests already include
some tests for unimplemented features and known issues.

2014/1/6 Richard Birkby notifications@github.com

**Comment by rbirkby** [comment]
What about the global variable pollution - for example, inputmask is defining an 'i' global variable.
It looks like inputmask sets 5 global variables:
- i
- unmaskedvalue
- isComplete
- mask 
- rsltValid

Generally, I find that JQuery plugins define their variables on the JQuery object, not on window.

**Comment by RobinHerbots** [comment]
I will have a look at those.

2014/1/6 Richard Birkby notifications@github.com

**Comment by rbirkby** [comment]
A binary search tracked down this commit as the bad commit which introduced these globals:

https://github.com/RobinHerbots/jquery.inputmask/commit/ce7a9a993943192d8fc73431ffb1e13f84b93c9e

**Comment by RobinHerbots** [comment]
@rbirkby, 

The global definitions are fixed.

Do you happen to know some good memory profilers for javascript?

**Comment by rbirkby** [comment]
Thanks. 

Re: Memory Profilers - I just tend to use the stock Chrome DevTools profilers - although the real-time memory graph in IE11 DevTools is really useful - until IE11 crashes, which it does regularly.

**Comment by RobinHerbots** [comment]
;-)

How did you tracked down the commit which introduced the issue?

2014/1/7 Richard Birkby notifications@github.com

**Comment by rbirkby** [comment]
I would like to say I used git bisect, but I don't know git that well, so I simply did a manual binary search on github.

**Comment by RobinHerbots** [comment]
:-D

2014/1/7 Richard Birkby notifications@github.com
