### ISSUE TITLE
IE8 and inputmask('decimal', { allowMinus: false, allowPlus: false })

### ISSUE THREAD

**Issue by avoev** [RobinHerbots/Inputmask#405]
I noticed that this causes the signedExpression in 
jquery.inputmask.bundle.js:2332

var signedExpression = "[" + (opts.allowPlus ? "+" : "") + (opts.allowMinus ? "-" : "") + "]?";
to return an empty [], which breaks in IE.

The fix is just to add a space somewhere: i.e. ..."[ " + (opts.allow ... which will effectively return
[{SPACE}] and it will fix the IE problem.

Is this something we can entertain?

**Comment by RobinHerbots** [comment]
@avoev, 

Thx for reporting.  I will submit the fix asap.
