### ISSUE TITLE
Regex mask is not working with knockout

### ISSUE THREAD

**Issue by mrapaka** [RobinHerbots/Inputmask#406]
If I change the value of a text box which have regex mask through script side in knockout then it is not reflecting in the textbox(It is changing to new value then immediately it is again converting to old value).

Any suggesions would be appreciated.

**Comment by RobinHerbots** [comment]
@mrapaka , 

Is this only with the regex mask or also with other masks?

Can you make a jsfiddle which shows the problem?

best regards, 

Robin

**Comment by mrapaka** [comment]
Hi Robin,
Thank you for your response.
Js fiddle is in http://jsfiddle.net/bxfXd/3329/
It is working fine in Firefox but not in IE9. Initially I checked my app in IE, thats why I opened this discussion. Pl check why it is not working in IE9.

**Comment by RobinHerbots** [comment]
http://jsfiddle.net/bxfXd/3344/ (updated refs)

@mrapaka,

This is because knockout uses the native value property to set the value and does not use jquery.val.

In firefox I am able to override the native value property, but in IE9 & chrome it is not possible.

Can you modify the way knockout sets his values?  

Anyway I will also see if there is an alternative way to detect value setting throught the input event

**Comment by mrapaka** [comment]
Hi Robin,

The updated jsfiddle example is also not working for me. After updating the value of textbox in knockout subscriber, It is hitting the blur/mouse leave events of inputmask.js. In that it is resetting to old value.

**Comment by RobinHerbots** [comment]
Yes I know it is not working in jsfiddle, I just updated the references for
testing.

I explained why it probably is not working in IE9.  The best solution would
be that knockout uses jquery.val, then it will work for all browsers.

Maybe I can add a workaround, to first check that there is another value in
the textbox then expected.

2014/1/13 mrapaka notifications@github.com

**Comment by RobinHerbots** [comment]
@mrapaka , 

I tried again with http://jsfiddle.net/bxfXd/6301/  (updated to inputmask 3.2.x)

And it works in IE9
