### ISSUE TITLE
dd/mm/yyyy mask: script fails

### ISSUE THREAD

**Issue by Skiv22** [RobinHerbots/Inputmask#407]
when setting minimal year for date mask 1000, and entering date 01/01/1000 - script fails on year entering on 3rd symbol and doesn't allow to finish. Tested in IE, FF, Safari. In Chrome works fine.

**Comment by RobinHerbots** [comment]
@Skiv22 , 

Can you give the exact mask with options you are using as I cannot reproduce the behavior.

best regards, 

Robin
