### ISSUE TITLE
Min And Max Values For Numbers

### ISSUE THREAD

**Issue by bassrock** [RobinHerbots/Inputmask#409]
I can not find a min an max number shortcut ont eh current number masks and have to generate a regex for it. It would be great if these shortcuts were defined on the number masks.

**Comment by RobinHerbots** [comment]
@bassrock , 

I know and I totally agree.  Also see #328.

I will fix that in version 2.7.

More suggestions for numerics are always welcome!

**Comment by bassrock** [comment]
Sounds good!

**Comment by hllewelyn** [comment]
Wouldn't this be better served using HTML5's [number input type](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input), and min / max attributes?

**Comment by maartendra** [comment]
This would be a great addition. Is there any news on this? @RobinHerbots

**Comment by RobinHerbots** [comment]
Duplicate issue.  See #228

**Comment by d8v15** [comment]
there three topics pointing to each other as the answer, yet none gives the answer. any update on min/max function?

**Comment by RobinHerbots** [comment]
@d8v15 , 

This is not yet implemented.

**Comment by darkguy2008** [comment]
It's 2017, not yet?

**Comment by joaopedroraldi** [comment]
That's sad :cry:

**Comment by RobinHerbots** [comment]
@joaopedroraldi ,

I suggest reading the readme's
