### ISSUE TITLE
Can't seem to apply masks based on class selector

### ISSUE THREAD

**Issue by connectedtrips** [RobinHerbots/Inputmask#41]
When I use $("#date").inputmask... the library works fine, but when I try to use it as class it doesn't apply the mask.

I'm using this in tandem with your extensions library too.

**Comment by connectedtrips** [comment]
My bad!

**Comment by RobinHerbots** [comment]
What was the problem?

**Comment by connectedtrips** [comment]
Not sure to be honest, I tried applying using a class multiple times and it didn't work then automagically it worked correctly. Sorry I can't be more helpful :(

Cheers,
  Ger

Developer 
Connectedtrips
www.connectedtrips.com

**Comment by RobinHerbots** [comment]
inputmask failt when the selector passed a non input as element, .... the inputmask should check on this!

**Comment by RobinHerbots** [comment]
fix in dev branch
