### ISSUE TITLE
IE9 "Object doesn't support property or method 'preventDefault' " Error when deleting input

### ISSUE THREAD

**Issue by chaenu** [RobinHerbots/Inputmask#410]
When using IE9 and trying to delete something, there's an error: "Object doesn't support property or method 'preventDefault' ". Line 1127: if (e) e.preventDefault();

You can reproduce it in the demo: http://robinherbots.github.io/jquery.inputmask/

I'll try to fix it.

**Comment by paramby** [comment]
jQuery inputmask plugin

Issue in IE - Object doesn't support property or method 'preventDefault'
Resolution:-
1) In jquery.inputmask.js (unminified version)

Find/Search & Replace/Comments as below-
if (opts.showTooltip) { //update tooltip
$input.prop("title", getActiveMaskSet()["mask"]);
}
//if (e) e.preventDefault();  -- Comment this line and Replace with below line
if (e) e.preventDefault ? e.preventDefault() : e.returnValue = false;

2) In jquery.inputmask.min.js (minified version)
Find/Search & Replace/Comments as below-
-- Replace this line
f.showTooltip&&m.prop("title",l().mask);b&&b.preventDefault()}}

-- With this
f.showTooltip&&m.prop("title",l().mask);b&&(b.preventDefault ? b.preventDefault() : b.returnValue = false);}}
