### ISSUE TITLE
Setting autoUnmask doesn't send unmasked value on submit

### ISSUE THREAD

**Issue by gldmelo** [RobinHerbots/Inputmask#412]
Hi, I'm having issues regarding the use of autoUnmask: true for integer numbers:

js code is like the following, on a separate file:

function aplicarMaskNumero(campo) {
        $(campo).inputmask('integer', { numericInput: true, autoGroup: true, groupSeparator: ".", groupSize: 3, autoUnmask: true });
}

Then if i put 1111111111111 inside the input field:

$('#nomeCampo').val();  // nomeCampo is the input field I applied the mask.

I get this from Firebug console:
"1.111.111.111.111"

I'm using Firefox 26 and Firebug for testing.

Is this a bug ? or I'm missing something?

Also, the mask allows me to type many dots like: 111.111.... then it corrects when i type in another number.

Thanks for your time!

**Comment by RobinHerbots** [comment]
@gldmelo , 

See also issue #366.

I will handle numerics in release 2.7.  You can use the onUnmask callback to properly unmask the integer value.
The one with the multiple dots is a bug.  

I will fix that later.

best regards, 

Robin

**Comment by gldmelo** [comment]
Hello @RobinHerbots ,

I tried to answer yesterday but i think my message wasn't saved, somehow.

I did what you sugested and it worked. Here's how my method looks now:

```
function aplicarMaskNumero(campo) {
    $(campo).removeAttr('data-val-number');
    $(campo).inputmask('integer', {
        autoGroup: true, groupSeparator: ".", groupSize: 3, autoUnmask: true,
        onUnMask: function (value)
        {
            var exp = /[^0-9]{1,3}/g;
            return value.replace ( exp, '' );
        }
    });
}
```

I also wrote one for decimals too.

```
function aplicarMaskNumeroDecimal(campo) {
    $(campo).removeAttr('data-val-number');
    $(campo).inputmask('decimal', {
        autoGroup: true, groupSeparator: ".", groupSize: 3, radixPoint: ",", digits: 2, autoUnmask: true,
        onUnMask: function (value) {
            var exp = /([^0-9]{1,3})+([^,]([^0-9]){1,2}){0,1}/g;
            return value.replace(exp, '');
        }
    });
}
```

best regards

**Comment by RobinHerbots** [comment]
@gldmelo , 

Great that it worked out and thx for sharing you solution.

I will include something simular in the numerics extension later.

best regards, 

Robin
