### ISSUE TITLE
Placeholder breaks down after selecting all input symbols besides the first one

### ISSUE THREAD

**Issue by anazinkin** [RobinHerbots/Inputmask#413]
I'm using custom extension

$.extend($.inputmask.defaults.aliases, {
        "date_rus": {
            mask: "1/2/y",
            placeholder: "дд/мм/гггг",
            alias: "datetime",
            clearMaskOnLostFocus: false
        }
    });

Steps to reproduce:
1. Type "1"  - result is (1д/мм/гггг)
2. Hold down Shift and click mouse to the end of input, all symbols besides the first one should be selected.
3. Type symbol 1 - result is (11/дм/мггг) - placeholder is broken.

**Comment by RobinHerbots** [comment]
@anazinkin, 

I created a jsfiddle http://jsfiddle.net/XjQWf/ but I cannot reproduce the problem.

Which browser are you using?

**Comment by anazinkin** [comment]
Chrome
I can't reproduce this in jsfiddle also.
Version of plugin is 2.2.71, but it reproduces with latest version as well.
Seems to be conflict with something else in our environment.
Thanks a lot for reply

**Comment by anazinkin** [comment]
Here that i mean with 2.2.71

http://jsfiddle.net/gG4wG/

**Comment by anazinkin** [comment]
The same with 2.4.0 version
http://jsfiddle.net/V89Kg/
Can you reproduce the case?

**Comment by RobinHerbots** [comment]
Yes I see the case in version 2.4.0.

You should use 2.4.18.

How did  you get version 2.4.0?  Are you using bower?

2014/1/22 anazinkin notifications@github.com

**Comment by anazinkin** [comment]
I downloaded it from https://github.com/RobinHerbots/jquery.inputmask/releases page
No, I'm not using bower.

**Comment by RobinHerbots** [comment]
I will need to update the git tags (releases).

Use the version in the dist folder of the 2.x branch

**Comment by RobinHerbots** [comment]
I updated the tags/releases

**Comment by anazinkin** [comment]
Great! My problem is fixed. Thanks!
