### ISSUE TITLE
Infinite loop, sript on page used too mutch memory.

### ISSUE THREAD

**Issue by joostburg** [RobinHerbots/Inputmask#415]
I want an input field where people can input initials like J.K or D.I.R or K.I.L.P but the script is infinite looping till memory is full.

//Data attribute
data-inputmask="'mask': 'A.', 'repeat': '*'"

//jQuery in document ready
$(":input").inputmask();

It works with the first 2 characters but on the third get a infinite loop or something.

Versions:
jquery.inputmask.extensions-2.4.19.js
jquery.inputmask-2.4.19.js

**Comment by RobinHerbots** [comment]
@joostburg , 

Fixed in version 2.4.20

best regards, 

Robin

**Comment by joostburg** [comment]
Thanks works like a charm!

**Comment by marcelo2605** [comment]
Add * as value for repeat break my page. I'm using version 4.0.0

```
var maskCelular = new Inputmask({
  "mask": "(99) 99999-9999 ",
  "repeat": "*",
});
```

**Comment by RobinHerbots** [comment]
@marcelo2605 ,

I'm working on it!  See projects

**Comment by marcelo2605** [comment]
Nice! Thanks Robin.

**Comment by RobinHerbots** [comment]
@marcelo2605 , 

Version 4.0.1-beta.36 fixes this

**Comment by marcelo2605** [comment]
Hey @RobinHerbots, maybe I was doing it wrong. What I need is repeat the mask while user keep typing to phone numbers:

```
var maskPhoneRepeater = new Inputmask({
  "mask": "(99) 99999-9999 ",
  "repeat": "*",
});
```
But this not happens.

**Comment by RobinHerbots** [comment]
@marcelo2605 , 

Look at https://codepen.io/robinherbots/pen/MqbQpV

**Comment by marcelo2605** [comment]
Yes, you're right. This is a problem in my application. Thanks.
