### ISSUE TITLE
crashing value, when mark&replace

### ISSUE THREAD

**Issue by ghost** [RobinHerbots/Inputmask#417]
see here (jsfiddle used in an old issue):
http://jsfiddle.net/bZT3j/7/ 

if you load the jsfiddle-url, the Number:
01 650 103 002 0001 DE101 5170
appears in the input.

if you now mark for instance the "002" and then try to overwrite it with for instance 003,
then the value crashes at the end of the input, but ONLY at the moment of overwriting the last character!

**Comment by RobinHerbots** [comment]
@wuSam , 

I will have a look!

**Comment by ghost** [comment]
thanks!

**Comment by RobinHerbots** [comment]
@wuSam, 

The latest version in branch 2.x fixes the issue.

Best regards, 

Robin

**Comment by ghost** [comment]
thanks

**Comment by ghost** [comment]
i think, this is an issue again.
http://jsfiddle.net/bZT3j/7/

value of input:
01 650 103 002 0001 DE101 5170

if i mark "02" from the "002"-block, and replace it with for example "01", the it seems broken

**Comment by RobinHerbots** [comment]
Fixed in version 2.5.2

2014-03-06 10:32 GMT+01:00 wuSam notifications@github.com:

**Comment by ghost** [comment]
great! you rock!
