### ISSUE TITLE
Date Year Completion

### ISSUE THREAD

**Issue by toddca** [RobinHerbots/Inputmask#419]
I want to type 07/15/67 and have it auto populate with 1967 for the year however it is using 2067 instead. Basically anything below 15 I want 20xx and anything above 15 I want 19xx. Anyone have any ideas on how I can achieve this?

**Comment by RobinHerbots** [comment]
@toddca , 

Create a new alias.

``` javascript
$.extend($.inputmask.defaults.aliases, {
   'myDate': {
            alias: "dd/mm/yyyy",  //define here the base
            determinebaseyear: function (minyear, maxyear, hint) {

               //put here your logic to determine the year 

               return your calculated year
            },
        },
});
```
