### ISSUE TITLE
Email Address Mask?

### ISSUE THREAD

**Issue by WaltDaniels** [RobinHerbots/Inputmask#42]
Love the plug-in.  Got tired of using of using the Bush plugin that hasn't been updated in forever.  Question ... is it possible to make an email mask (with the @ sign)?

**Comment by RobinHerbots** [comment]
Hi Daniel, 

creating input restriction for an email is possible.  Creating a dynamic mask for email not yet.  With dynamic I mean that you see ______@___ and that the part before and after the @ sign is not restricted in length.

Best regards, 

Robin

**Comment by htowens** [comment]
A dynamic email mask would be a very nice addition, +1 from me.

**Comment by bertoost** [comment]
Yeah that would be cool!

**Comment by ghost** [comment]
Would be awesome! Another +1 :)

**Comment by anteksiler** [comment]
+1 from me too :)

**Comment by ikawka** [comment]
+1

**Comment by RobinHerbots** [comment]
Hi all, 

About an email mask (alias).

How exactly should an email mask behave?   Visible with a template? _____@____.___ or just restrict on input and no visible feedback?  Ideas suggestions.

Robin

**Comment by anteksiler** [comment]
Hi Robin, I think it should look search for a pattern like this : _@_.com

and should look like this at first: _@_._

So the user know that he has to fill in 3 places and the input should have an "@" sign in the middle.

**Comment by RobinHerbots** [comment]
Shouldn't it be better  _@_.___  where the first and middle underscore autoexpand until @ or . is pressed or a space to go the the next part (like in optional masks)

**Comment by RobinHerbots** [comment]
=>    $(selector).inputmask("_{1,20}@_{1,20}.*{3}")

**Comment by RaphaelDDL** [comment]
Better this one, no?
=> $(selector).inputmask("_{1,20}@_{1,20}._{3}[._{2}]") 

Since there are e-mails from country TLDs like 'something@example.com.br'

**Comment by RobinHerbots** [comment]
Yes, .... indeed ;-) , ....

2013/4/8 RaphaelDDL notifications@github.com

**Comment by MCodeKitty** [comment]
Great plugin - replacing Bush plugin for me as well.

+1 for me too!

**Comment by RobinHerbots** [comment]
@MCodeKitty ,

Thx for the compliment and that you like the inputmask plugin :-)

Best regards, 

Robin

**Comment by michaelwatkins** [comment]
Great plugin!  I tried $(selector).inputmask("_{1,20}@_{1,20}._{3}[._{2}]") for email without success.  The mask appeared in the textbox as _{1,20}@_{1,20}._{3}._{2}.  Any suggestions?  Thank you.

**Comment by RobinHerbots** [comment]
@michaelwatkins ,

That's because this functionality still has to be developed ;-)

**Comment by romainwurtz** [comment]
+1

**Comment by vnazarenko** [comment]
+1

**Comment by Kompas** [comment]
+1

**Comment by RobinHerbots** [comment]
after issue #277 I will start on this one

**Comment by Macharius92** [comment]
I would suggest to use the following since they are new TLDs coming ;)

$(selector).inputmask("_{1,20}@_{1,20}._{2,6}[._{2}]")

http://icannwiki.com/index.php/.africa

http://icannwiki.com/index.php/.paris

**Comment by RobinHerbots** [comment]
You can use this mask if you are only interested in input restriction.

$(selector).inputmask('Regex', { regex: "[a-zA-Z0-9._%-]+@[a-zA-Z0-9-]+\\.[a-zA-Z]{2,4}" });

**Comment by iamchriswick** [comment]
Hi,

Has support for ______@___ been added to the plugin?

**Comment by RobinHerbots** [comment]
@iamchriswick , 

No not yet.

**Comment by oboshto** [comment]
Nice plugin. Very helpful +

**Comment by RobinHerbots** [comment]
There is a first version of the email alias available in the jquery.inputmask.extensions.js  branch 3.x

$(selector).inputmask("email");

Any suggestions for enhancement are welcome.

**Comment by YoussefTaghlabi** [comment]
You should probably start using http://qunitjs.com/ for unit testing.

**Comment by RobinHerbots** [comment]
I already do

**Comment by MarkoSh** [comment]
How to use dynamic email-or-phone? i need some
email|+7 (999) 999-99-99 mask

**Comment by Nikhil783** [comment]
Hi,

Has support for ___@.com has been added to the plugin?

Thanks

**Comment by RobinHerbots** [comment]
@Nikhil783 , 

Yes, use the email alias

**Comment by STPJ** [comment]
Just pointing out that it's been 5 years this feature is requested.
And still in need today (I need it).

I understand it's during your free time, but we have been all really patient ;)

**Comment by RobinHerbots** [comment]
@STPJ , 

Try with Inputmask("email").mask(selector)

**Comment by STPJ** [comment]
Thanks it worked.
Is there a way to put this threads as 'Solved' instead of 'Close'

Google brought me here.

**Comment by RobinHerbots** [comment]
@STPJ , 
;-)

I can only set the issue on close.

**Comment by mugukamil** [comment]
@RobinHerbots hey, Robin, Very good plugin, thanks for it.
I have this code, but still shows "@" symbol in my input...

```
$(".js-email").inputmask({
    regex: "^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+.[A-Za-z]+$",
    placeholder: ""
})
````

**Comment by RobinHerbots** [comment]
@mugukamil , 

Thx.

What is the problem with showing the @?  Maybe setting jitMasking option to true is what you want.

**Comment by mugukamil** [comment]
@RobinHerbots thanks, its work. 

problem was, that even I set placeholder to "", it shows "@"

**Comment by Moutinho24** [comment]
The following code returns this in the input
[Imagem](//i.imgur.com/gBOgALK.png)
`$('#email_subs').inputmask("email");`

**Comment by RobinHerbots** [comment]
Did you include the inputmask.extensions
Je?

**Comment by buste** [comment]
How to accept capital letters for email?

**Comment by CrdMarco** [comment]
When I try to enter incomplete data in the email input, I am notified of a red error in the tag, but the form is not blocked at the time of submission. I mean the submission button.
```
<form>
   <div class="form-group">
            <label> Email</label>
            <input id="target" class="form-control" type="text" required="" />
  </div>
  <button type="submit">Save</button>
</form>

javascripts:
import Inputmask from "inputmask";
new Inputmask({ alias: "email" }).mask($("#target"));
```
Why? am I wrong?

**Comment by WTplayer** [comment]
Hi ! ( sorry for my English, I'm French)
I'm working on a web app and i'm using this plug-in but i just saw that to put a mask on a input, it must be a type text, in fact the email mask doesn't work on a input with a email type.

Is it normal ? Or is there anyway to go over this ?

Example : https://jsfiddle.net/zyfpca7t/

**Comment by osirion** [comment]
Please note, the default 'email' alias only allows 20 characters in the local (before "@") portion of an email. Please update this to allow 64 characters as per the RFC:

"That limit is a maximum of 64 characters (octets) in the "local part" (before the "@") and a maximum of 255 characters (octets) in the domain part (after the "@") for a total length of 320 characters. However, there is a restriction in RFC 2821 on the length of an address in MAIL and RCPT commands of 254 characters"

**Comment by Getode** [comment]
$('input[type=email]').inputmask('email'); - not working, only for type=text?

**Comment by cobermiller** [comment]
> $('input[type=email]').inputmask('email'); - not working, only for type=text?

Having the same issue
