### ISSUE TITLE
RegexMask -> inputmask("isComplete")

### ISSUE THREAD

**Issue by Pezhvak** [RobinHerbots/Inputmask#420]
i used your email mask sample, it worked awesome and i really enjoyed it.. but i can't verify if it's completed or not, when i try to check it returns 'undefined'.

**Comment by RobinHerbots** [comment]
@Pezhvak , 

The regex extension still needs some enhancements, but that will come later. (after release 2.7)
To determine completion you have to check it yourself for the moment.

**Comment by RobinHerbots** [comment]
@Pezhvak ,

fixed!
