### ISSUE TITLE
Repeating characters on Android Chrome

### ISSUE THREAD

**Issue by andrewrota** [RobinHerbots/Inputmask#421]
**Demo:** http://jsfiddle.net/PX7G7/1/

**JS Code:**

``` javascript
$(document).ready(function () {
    $(".input").inputmask({
       "mask": "****"
    });
});
```

**Steps to reproduce:**
1. Touch input field to open keyboard
2. Touch '1' on keyboard.
3. Touch '2' on keyboard.  The '2' character is added as expected.  **Then immediately the '1' and '2' character are again appended to the input field.  The input field now reads '1212' even though only two characters were inputted.**

_If the mask is longer, then when you input another character it appends that character then appends all characters again.  This process repeats for each character you input._

**Device:**  Samsung Galaxy S4 SCH-I545
**OS:** Android 4.2.2
**Browser:** Chrome
**User Agent String:** Mozilla/5.0 (Linux; Android 4.2.2; SCH-I545 Build/JDQ39) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/29.0.1547.72 Mobile Safari/537.36

**Comment by RobinHerbots** [comment]
See #416
