### ISSUE TITLE
maxlength value is multiplied by 2 when using inputmask("decimal")

### ISSUE THREAD

**Issue by andreimitrus** [RobinHerbots/Inputmask#425]
Hi, i found this issue while using your plugin. It seems that when using the decimal extension the maxlength's value is multiplied by 2.

Example here: http://jsfiddle.net/NVJB8/

**Comment by RobinHerbots** [comment]
@andreimitrus, 

I know, that is to be able to reactcorrectly on the paste event.

Pasting data when there is already a mask concatenates the value.

ex for dates:  paste 23/03/1973 => 23/03/1973dd/mm/yyyy once the value is pasted the plugin picks that up and masks the value.  If I don't tweak the maxlength there is no place for the initial paste value.
 Anyway the mask prevents typing more characters then the initially given maxlength.

**Comment by andreimitrus** [comment]
Yes you are right.
I can see that in my example the number of characters are limited to the initial maxlength. The problem was that I've seen a case, which I cannot reproduce right now, where this limitation wasn't actually working.
If I run into the problem again I'll come up with a better example.

Thank you.
