### ISSUE TITLE
jQuery input mask is not scrolling the the content when the width is small

### ISSUE THREAD

**Issue by babupca** [RobinHerbots/Inputmask#428]
In my project i use the jQuery input mask, for setting many masks. Recently i saw an issue were the text is not visible when the content is more and the width of the text field is small.

Basically if an input field is with a width of 100px and content is more than width of the 100 px, then the content will be automatically scrolling towards the left side. but in my case, the content is not scrolling and the text is added behind the text box.

As per my knowledge, the issue should in the jQuery input mask plugin. If any have already faced this issue and fixed it, please let me know it.

**Comment by RobinHerbots** [comment]
@babupca,

Which version are you using?

**Comment by babupca** [comment]
I used this jquery.inputmask-2.x,but with in the js file it is mentioned as like this
/**
- @license Input Mask plugin for jquery
- http://github.com/RobinHerbots/jquery.inputmask
- Copyright (c) 2010 - 2013 Robin Herbots
- Licensed under the MIT license (http://www.opensource.org/licenses/mit-license.php)
- Version: 0.0.0
  */

and also I just noticed, in mozilla firefox it is working fine, ie( the content is scrolling towards left when the width is small) and internet explorer & chrome the content is not scrollling towards left.

**Comment by babupca** [comment]
I have added the jsfiddle link. Could you please check this in firefox (its working), chrome and ie9
http://jsfiddle.net/SEXAj/127/

**Comment by babupca** [comment]
hi robin, Do you have any solution for this problem ?

**Comment by RobinHerbots** [comment]
@babupca , 

Just use the latest version of the 2.x branch. 
See updated jsfiddle http://jsfiddle.net/SEXAj/128/

**Comment by babupca** [comment]
Thanks Robin. It is working now.

**Comment by gbrauser** [comment]
It appears this issue has re-appeared in the latest version (we are using version 3.2.1-113).  I switched to the latest 2.x version (as this thread indicates) and the issue went away.

**Comment by RobinHerbots** [comment]
@gbrauser , 

It's better to switch to the latest 3.x version as the 2.x is already old.

**Comment by mttkgn** [comment]
@RobinHerbots This issue still exists with the latest 3.x version. Will this be corrected?

**Comment by RobinHerbots** [comment]
In which browser did you test?

**Comment by mttkgn** [comment]
Chrome and IE9 look fine. It appears that it's only an issue in IE11, which is what we have in our environment.

**Comment by RobinHerbots** [comment]
@mttkgn , 

It seems like a bug in IE11

https://connect.microsoft.com/IE/feedback/details/1015764/ie11-scrollleft-for-text-input-elements-is-always-0

**Comment by mttkgn** [comment]
@RobinHerbots,

Ahh of course...thanks for looking into it!! I'll monitor for any changes on Microsoft's end. 

Fantastic work on this plugin by the way! It's the only one I found that's robust enough to handle general masking and currency masking in any suitable way. Many thanks!
