### ISSUE TITLE
Modifying value after mask has been applied

### ISSUE THREAD

**Issue by bodrick** [RobinHerbots/Inputmask#429]
I'm currently running into an issue where I'm defining my masks via either data attributes and I've also tried just within the onload event.  I'm reading in some data from an ajax query which runs after the masks have been defined.  The problem is as soon as I hover over, or select the field with the mask the value is lost.

If I just go ahead and set the value directly as a test, the same thing happens, if I set the value before the mask is defined no problem, set the value after the mask is defined and the value gets lost as soon as you hover over the field, edit the field etc.  I tried to disable the showMaskonhover and showmaskonedit, but the problem still happens if you edit the field then click out of it.

Here is a jsfiddle : http://jsfiddle.net/2yueC/7/

**Comment by RobinHerbots** [comment]
@bodrick ,

fixed in version 2.4.25
