### ISSUE TITLE
On chrome or safari inputmask('remove') not working

### ISSUE THREAD

**Issue by Jaspal** [RobinHerbots/Inputmask#43]
Hi Robin,

I want put mask on onfocus event and onblur display normal text unmask

Here is my code but it's not working i also tried $('#txtSSN').inputmask('remove'); on blur but this is not working on chrome. can you please suggest me ASAP

(function($) {
$(document).ready(function() {

```
        $('.ssn').focus(function() {
            //alert('in');
            $(this).inputmask('ssnMasked');


        }).blur(function() {

        $('#txtSSN').inputmask('unmaskedvalue');


        });
    });
})($);
```

**Comment by RobinHerbots** [comment]
Hi Jaspal,

I will have a look at it tomorrow.

best regards 

Robin

**Comment by RobinHerbots** [comment]
Hi Jaspal, 

I made a fix for the remove option for webkit browsers (tested on Chrome).

A questions.  Why do you want to remove the mask when loosing focus?

And btw in your code you use a different selector in the focus (this) and the blur (#txtSSN) , ...  

best regards, 

Robin

**Comment by Jaspal** [comment]
Hi Robin,

Actually we already using Microsoft AjaxToolkit but during testing we found MaskEdit control not working on Chrome/Safari so i used your jquery. It's our business requirement for some fields we need to display Masked only onfocus and onblur need to display unmasked value

Here is my exact code
(function($) {
$(document).ready(function() {

```
    $('.ssn').focus(function() {
        //alert('in');
        $(this).inputmask('ssnMasked');


    }).blur(function() {

    $(this).inputmask('remove');


    });
});
```

})($);

 <asp:TextBox ID="txtSSN" CssClass="ssn" runat ="server">/asp:TextBox

**Comment by Jaspal** [comment]
Thanks i really appreciate your help it's working.
