### ISSUE TITLE
autoCasing in jQuery input mask

### ISSUE THREAD

**Issue by babupca** [RobinHerbots/Inputmask#430]
Hi Robin,

I have a requirement, where, when a user type small letter, the alphabets has to be updated to capital automatically at the same time. I saw one conversion in issues list,where you were talking about the autoCasing, this will work i think 

But in the latest version which i downloaded, it does not contains the autoCasing.

Can you assist me, in doing this. 

Thanks.

**Comment by RobinHerbots** [comment]
@babupca, 

In jquery.inputmask.extensions.js you will find the definition A and # which will autouppercase all input.  If you need the opposite you will have ti define your own definition.

In the readme it is explained https://github.com/RobinHerbots/jquery.inputmask#auto-upperlower--casing-inputmask

BTW in the dist folder you find the jquery.inputmask.bundle.js which combines the plugin and all extensions.

best regards, 

Robin
