### ISSUE TITLE
Pasting doesn't apply mask

### ISSUE THREAD

**Issue by rizowski** [RobinHerbots/Inputmask#431]
Hello, 

I have been trying to incorporate your plugin into a site I work on. Your plugin has a lot of features that I love. But there are a few things that are a little weird. 

If you try to paste values into the field it doesn't apply the mask. It instead shoves the mask over to the right. It seems to be a similiar problem with Galaxy Tablet chrome. When typing something in it just moves the mask to the side as the numbers are being entered into the field.

Like so:  [555___-____]

http://jsfiddle.net/8Q2wD/

**Edit** Steps
1) Enter in a number
2) Delete it
3) Paste and it will move the mask.

As for Galaxy Tablet
Chrome - just start typing.

**Comment by RobinHerbots** [comment]
@rizowski, 

Can you specify the browser(s) you are testing on?

**Comment by rizowski** [comment]
@RobinHerbots Yes I am currently running Chrome V33. I also updated the steps on what is causing it as I saw that it did apply the mask on immediate paste.

**Comment by RobinHerbots** [comment]
@rizowski 

Can you have some tests and send me the output

http://jsfiddle.net/Tpr6N/21/
http://jsfiddle.net/Tpr6N/22/

http://jsfiddle.net/UJvN7/

**Comment by rizowski** [comment]
I am getting a few problems. This is tested in chrome for right now, until I can get my hands on the galaxy tablet.

First:
keydown keypress input 5 keyup 5 keydown 5 input keyup keydown keydown paste input 555555555 keyup 555555555 keyup 555555555

Second: 
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/33.0.1750.70 Safari/537.36 => keydown caret: {0,0} keypress caret: {0,0} input 5 caret: {1,1} keyup 5 caret: {1,1} keydown 5 caret: {1,1} input caret: {0,0} keyup caret: {0,0} keydown caret: {0,0} keydown caret: {0,0} paste caret: {0,0} input 555555555 caret: {9,9} keyup 555555555 caret: {9,9} keyup 555555555 caret: {9,9}

Third: 
Branch 2.5 is still causing the issue. I can't screen cap because it loses focus. There is also a error with Input on line 1395.
![woops](https://f.cloud.github.com/assets/574835/2128843/e38f9c3a-927f-11e3-9516-bbe00e3f0ca9.PNG)

**Comment by RobinHerbots** [comment]
@rizowski , 

I just fixed the error.  When I find some time I will do some debugging on android chrome.  I know there are still some problems with chrome.

Looking at the first fiddle the paste event is correctly triggered

**Comment by rizowski** [comment]
I can verify this has fixed the typing problem on the Galaxy Chrome tablet. It has also fixed the pasting issue on chrome. I will also test on other browsers as I go throughout the day today.

**Comment by RobinHerbots** [comment]
@rizowski , 

The paste event problem is fixed.
For issues on android, you may open new issues.  Also see milestone 2.5

best regards, 

Robin

**Comment by AbdullahWeb007** [comment]
Please use autoUnmask: true, this will fix your pasting issue as like 555__-_______
$('#selector').inputmask({ "mask": "99/99/9999", 'autoUnmask' : true});
