### ISSUE TITLE
Variable length mask issue

### ISSUE THREAD

**Issue by xMANIGHTx** [RobinHerbots/Inputmask#432]
Hallo,
your script is the best input mask around at the moment so thanks for your job!
That said I notice a minor "bug" with the implementation.
Let's make the IP mask example where you have 3 optional numbers separated by dots "."
If I enter for example 192.12.22.13 and I want to go back and fix the 12 to 128 i simply cannot. I have to delete everything after 192. 
In my opinion this behaviour is not intuitive. It would be more intuitive with variable length mask parts if I place my caret before the divider (dot in this case) and add chars to fill until the max provided lenght. It may be complex implementation maybe but I guess it's an essential one to render variable masks really usable.
Thanks again.

**Comment by RobinHerbots** [comment]
@xMANIGHTx, 

Thx for the compliment.

About the bug ;-)  I totally agree and I am already working on it.  See miletone 2.6

**Comment by xMANIGHTx** [comment]
Wow this is a great news! This change will make it a no brainer for people who wants decent maskin in their form fields! Sorry I didn't see it I'm a newbie to github :)
Waiting eagerly for the 2.6 then! :D Thanks again for your great work!

**Comment by RobinHerbots** [comment]
Thuis is fixed in the la test version-
