### ISSUE TITLE
Tab and autoselect mask parts

### ISSUE THREAD

**Issue by xMANIGHTx** [RobinHerbots/Inputmask#433]
Hallo Robin,
I was so amazed by your script that I couldn't stop thinking about it :) and tonight I had an idea that, in my opinion, could improve even more the usability.
After all this is an helper to form editing, to make form insert more usable and quick and lower the insert errors, so any idea in that direction, even small improvements could make a big improvement I guess.
Anyway... the idea is to use the "tab" and "back-tab" (shift+tab to go back) inside masked inputs to skip to the various mask parts and eventually auto-select that mask part for immediate input replacement. 
This would be useful for both fixed and dynamic length mask parts. For fixed it would be useful during editing of already filled textbox, for dynamic length parts it would be useful both during initial insert and editing.
So in the IP example, you could skip to the next triplet both pressing the dot "." or "tab" AND you could go back to the previous triplet pressing "shift+tab", in doing this if the triplet you skipped to is already filled in, it will be auto-selected.
This will be a big enanchement in any literal-separated mask input (phone numbers, email, credit card, IP, whatever...).
Also I would render those two as optional, so that you can decide if to use them or not both globally or just for some input boxes.
For the tab you could just have some setting like "always" and "none" or go more in detail and allow to decide to use it "always", "never", "only for empty fields", "only for non empty fields" or using your functionality wich detects is the field is partially complete or complete or valid add even more option (I think to start just the first two could do enough btw).
Same for the autoselect functionaity, wich should work both by pressing tab or (in the example above) the dot ".", you can give the options "on/off".
Hope this can be useful to you :)

**Comment by RobinHerbots** [comment]
@xMANIGHTx , 

Thx for the idea!  

and any ideas are always welcome!

 I see pros and cons in the concept.  It could improve usability, but changes the default behavior of tab & shift tab.

I was thinking of an option to create a mask over multiple input element, ... so tabbing will select the different parts.

I will keep the issue open for later.

**Comment by xMANIGHTx** [comment]
The multiple inputs is another option of course.
Anyway I think that making those two as an option would leave the user with the choice. Also giving the ability to choose as an option (for the tabbing) always, never, only for empty, only for non empty, an so on will give great flexibility on when to apply the behaviour not to break normal functionality.

Apart from the tabbing, do you think the autoselect feature would be good in any case? It could be a nice improvement for edititing when skipping parts? (for example with the dot "." in the IP example or with the "-" in  a phone number example and so on...)

**Comment by RobinHerbots** [comment]
For the optional parts there is already the skipOptionalPartCharacter option .  With this you can specify the char to use for skipping an optional part.  Default is space.

So for ip you can skip a part by pressing dot or space.

**Comment by xMANIGHTx** [comment]
Yes I mean auto-selecting the part you skipped to. For example 255.10.20.30 you are in the 255 part, press the dot you find yourself on the 10 part BUT with the 10 already selected.
I guess this could be a nice function to speed up editing (together with the fix we already discussed yesterday in the other topic of course). And this also can be make optional (like autoselect: "on/off")

**Comment by PrimozRome** [comment]
This would also be very useful for date. I have form for entering documents where each document has multiple dates for input. Usually dates are all within same month so in 99% you only edit 'dd' part of year. I would love to have functionality when on blur only for example first part of mask is selected.

**Comment by RobinHerbots** [comment]
@xMANIGHTx , @PrimozRome ,

I will implement tabbing inside the mask parts as an option.

**Comment by manight** [comment]
Thank you Robin this is great news. Also I think the biggest thing is how you listen and evaluate comments from your user base! This really makes a difference.
About the auto-select feature, I found this resource, maybe it can be helpful if you are likely to consider this feature as well: http://jsbin.com/anadox/3/edit

**Comment by RobinHerbots** [comment]
The idea is to tab between the mask-parts and auto-select that part, so
that you can directly overtype the content.

2014-02-13 15:45 GMT+01:00 manight notifications@github.com:

**Comment by manight** [comment]
Oh yes :) Didn't understand you meant to implicit implement the auto-select also! I guess this behaviour (the autoselect) should happen even if you skip by other means. In the previous example with space or dot "." this should also auto-select I guess, just like if you skip with tab (that's why I considered it a feature on its own I guess)

**Comment by RobinHerbots** [comment]
Milestone 2.7

**Comment by manight** [comment]
Go go go!! :)

**Comment by RobinHerbots** [comment]
It's about time to think about this enhancement
