### ISSUE TITLE
Carret at the end of the line wont erase characters until moved on Galaxy devices

### ISSUE THREAD

**Issue by rizowski** [RobinHerbots/Inputmask#434]
Galaxy tablets and phones on both Firefox and Chrome have this issue. When you are at the end of the mask and you try to delete any characters the carrot will delete the last character and then return back to the end of the mask. This will not allow you to delete anymore characters until you manually move the carrot inside the mask.

1) 123-45-6789|  -> press delete
2) 123-45-678_| -> cursor deletes last character and then returns back to the end of the mask.
3) 123-45-678|_ -> will erase all characters if you move cursor to this position.

**Comment by RobinHerbots** [comment]
@rizowski, 

Can you have a test with http://jsfiddle.net/UJvN7/26/

**Comment by rizowski** [comment]
Chrome it is fixed. For firefox it is not applying the mask.

Ex:
____-____
5555___-___

Cleared the cache to confirm.

**Comment by RobinHerbots** [comment]
http://jsfiddle.net/UJvN7/27/show/

**Comment by RobinHerbots** [comment]
I also tested it in Chrome Mobile and Firefox mobile, and there are still alot of issues depending on the kind of input (numbers vs characters).

As I cannot make it fully work on android and spend too much time on that I decided to leave the support out, until the events are more reliable or if someone finds a fully working solution.

**Comment by RobinHerbots** [comment]
see #465
