### ISSUE TITLE
Pass reference of $input (or mask options) to the 'onUnmask' function.

### ISSUE THREAD

**Issue by jimithing277** [RobinHerbots/Inputmask#436]
Robin,

I'm in a situation where I want to custom handle the logic of 'unmasking' an input.  The issue is that as it stands right now I have no way to get a reference to the options the current mask is using within the 'onUnmask' function.

Is there any way you could either:

1) Modify the call to 'onUnmask' so it would actually use '$input' as the context to the 'call()' method.  This way I could get a reference to the input within my handler by using the 'this' keyword.

or

2) Pass in the mask options as another parameter to the 'onUnmask' call?

Thanks,
Greg

**Comment by RobinHerbots** [comment]
@jimithing277 , 

Ok, I will add both ;-)

**Comment by RobinHerbots** [comment]
@jimithing277 , 

Done!

**Comment by jimithing277** [comment]
As always, your responsiveness is greatly appreciated, and keep up the great work with your plugin!
