### ISSUE TITLE
Possible bug with "skipOptionalPartCharacter" settings?

### ISSUE THREAD

**Issue by jimithing277** [RobinHerbots/Inputmask#437]
Robin,

I have a simple mask setup as follows: "9[9]9".  Upon testing some basic input it appears that the 'space' key is not being honored as optional input with the "skipOptionalPartCharacter" being set to its default value of " ".

For instance, if I type the following input "9(SPACE)9" I expect that the input would look as follows within the control: "9_9".  However, it won't let me advance past the first "9".

Is this by design?  Is it possible I'm missing something simple?  I expected that any character marked as optional would truly be, well optional :-)

Thanks,
Greg

**Comment by RobinHerbots** [comment]
Optional means you don't need to input it.

In your case the only valid input is   99 or 999  So the second position
must be 9 (numeric).

The skipOptionalPartCharacter is used in another case  say mask 9[9]-9.  A
valid input for the second position is 9 or -  as the second 9 is optional.
 The skipOptionalPartCharacter is like an alias for the fixed part.

So typing 123  => 12-3
typing 1-23 => 1-2
typing 1space23 => 1-2    (space is default skipOptionalPartCharacter)

It seems that the optionals create a lot of confusion.  Maybe a question to
all who is interested.  How do you think the optionals should work.  Maybe
give an example.

2014-02-17 18:16 GMT+01:00 jimithing277 notifications@github.com:

**Comment by Nagarjuna-B** [comment]
Could you explain what the mask - 9[9]9 means? I too, like OP, was under assumption that the middle 9 is optional, meaning it should allow both 99 and 999. But that is not happening! If I just type 99 the isComplete gets set to false, shouldn't it be set to true!?. If I want to skip middle one, I couldn't find a way how to skip it. As OP mentioned, after entering first 9, hitting space does nothing. Hitting right arrow will put the cursor at the end, which again won't let you enter anything.
