### ISSUE TITLE
allowMinus and maxlength

### ISSUE THREAD

**Issue by nupply** [RobinHerbots/Inputmask#439]
The maxlength attribute does not include the groupSeparator but does include the minus sign when allowMinus is set. This is a problem if the mask is being used to allow say a range of numbers from -999 to 999 using maxlength 3. The actual range allowed is -99 to 999.

**Comment by RobinHerbots** [comment]
@nupply , 

The idea is not to use the maxlength but some other option to define the number range.
But that will be for milestone 2.7

**Comment by RobinHerbots** [comment]
Fixed

**Comment by blaiseliu** [comment]
@RobinHerbots What is the "other option" instead of `maxLength`? Are you suggesting some regex pattern or 999 something? Is there some convenient parameter like maxValue or minValue to use?

**Comment by RobinHerbots** [comment]
@blaiseliu , 

In the numeric alias and derivatives you have the min and max option.  I definitly need to update the documentation, .... anyone who wants to do this for me?
