### ISSUE TITLE
Decimal bug

### ISSUE THREAD

**Issue by RomeroMsk** [RobinHerbots/Inputmask#440]
Hello.
Thank you for this great plugin!
Want to tell you about strange behaviour of 'decimal' input with fixed digits.
Try this example: http://jsfiddle.net/85FDJ/ with following steps:
1. Focus textarea (if not autofocused).
2. Press Shift+Tab to focus input (value will get into selection).
3. Press point or comma key (nothing happens).
4. Press right arrow to switch off the selection and move caret into the end of input.
5. Try to input any symbols: digits or point - nothing happens.
6. Press tab to blur input - value will be cleared.

Without 'digits' option bug will not reproduce.
Checked in Chrome and FF, Windows 7.

**Comment by RobinHerbots** [comment]
@RomeroMsk, 

Thx for reporting.  I will have a look at it.

best regards, 

Robin

**Comment by RobinHerbots** [comment]
@RomeroMsk, 

Fixed see jsfiddle

**Comment by RomeroMsk** [comment]
Tested on my site, bug fixed. Thank you!
