### ISSUE TITLE
maxlength attr of the input changed automatically ?

### ISSUE THREAD

**Issue by YAmikep** [RobinHerbots/Inputmask#441]
Hi,

The maxlength attr of the input is changed when I apply a mask. why ?

Here is the mask:

`$(".mask-pincode").inputmask("9999");`

The maxlength was 4, it is now 8.

`<input class="mask-pincode"  maxlength="8" name="pin_code" type="text">`

Thanks

**Comment by RobinHerbots** [comment]
@YAmikep, 

This is to allow for pasting a value.

When ypu already have a mask placeholder the length of the mask, then there is no place anymore for pasting in some extra value.  ex.   You got **_-**_  and you paste 123-456.  Then the pasted value gets something like ___-___123-456 and the plugin makes this the correct 123-456 value.

The initial maxlength is still assured by the plugin.

Robin
