### ISSUE TITLE
Mask wont allow input with Insert mode enabled

### ISSUE THREAD

**Issue by rizowski** [RobinHerbots/Inputmask#442]
The cursor will only stay at the beginning of the mask even if you are inputting the correct characters with insert mode on.
|____-____

Non working browsers:
- Windows XP IE8
- Chrome-34(Beta)
- Chrome (Release)
- Firefox
- IE 8
- IE 9

Still testing:
- IE 10

Used a VM from here:
http://www.modern.ie/en-us/virtualization-tools#downloads

**Comment by RobinHerbots** [comment]
@rizowski , 

Can you more specify the problem.  (mask etc)
I tried on the emulated ie8 and it worked fine.

**Comment by rizowski** [comment]
Let me update the bug. I found out that insert was on. Is insert handled or a setting that can be enabled? I didn't find anything in the docs. If Insert is on any browser it doesn't allow input.

**Comment by RobinHerbots** [comment]
@rizowski , 

Pressing insert toggles between insert and overwrite.  I just tested in chrome with the demo page and it seems ok.

**Comment by rizowski** [comment]
After looking it over I found that I was on a previous version. It seems that it is working now.
