### ISSUE TITLE
Enable Placeholder option for Decimal mask

### ISSUE THREAD

**Issue by YoussefTaghlabi** [RobinHerbots/Inputmask#445]
Consider the following scenario using the following configuration in v2.5.2:

```
$(<SELECTOR>).inputmask("decimal", { 
                radixPoint: ".", 
                groupSeparator: ",",
                groupSize: 3,
                digits: 2,
                autoGroup: true,
                placeholder: "0"
            });
```

Ideally, this should result in a placeholder of: `0.00`

**Comment by RobinHerbots** [comment]
@YoussefTaghlabi , 

Yep, I agree but that I will do in milestone 2.7

**Comment by RobinHerbots** [comment]
@YoussefTaghlabi, 

This is implemented in the current version
