### ISSUE TITLE
Issue when pasting with multi-mask

### ISSUE THREAD

**Issue by jimithing277** [RobinHerbots/Inputmask#448]
Currently using version 2.5 and noticed that there appears to be an issue when attempting to paste a value in to an input with multiple masks defined.

I have an input with the following masks:

"99.99" and "99.99.99

Pasting the value of "22.22" in to the control will reproduce the issue.  You'll notice that the input will display the second mask even though my pasted value should have triggered the active mask set to be the first one.

JSFiddle with example: http://jsfiddle.net/4KBK7/

Steps to reproduce:

1) Ensure input does not have focus
2) Click in to the input giving it focus (cursor should be at the start)
3) Paste the following value from your clipboard: "22.22"
4) You will notice that the second mask set is selected even though the value I pasted should have selected the first mask set.

**Comment by RobinHerbots** [comment]
@jimithing277 , 

I'm want to totaaly rework the multiple mask option, as I am not happy with the current implementation.  

I also want to improve the selection of the active mask.

For your mask.
Can you try this one 99.99[.99]  with greedy: false
on blur the trailin.__ will disappear.
Robin

**Comment by RobinHerbots** [comment]
@jimithing277 , 

Fixed in 3.x

http://jsfiddle.net/4KBK7/5/
