### ISSUE TITLE
By changing the mask of the field value is lost

### ISSUE THREAD

**Issue by joseh-henrique** [RobinHerbots/Inputmask#45]
How to change the mask of a field X without losing its content based on certain choices made ​​in another field.

**Comment by RobinHerbots** [comment]
Hi Joseh-henrique,

You should just apply the new mask.  Can you specify the version you use of the inputmask and also which browser.

best regards

Robin

**Comment by RobinHerbots** [comment]
With the latest version it should be fixed.  Tested with Chrome, FF, IE9
