### ISSUE TITLE
 Decimal mask doesnt have the "clearIncomplete" and "onincomplete" concepts

### ISSUE THREAD

**Issue by YoussefTaghlabi** [RobinHerbots/Inputmask#450]
Consider the following scenario using the following configuration in v2.5.4:

```
$(<SELECTOR>).inputmask("decimal", { 
    radixPoint: ".", 
    groupSeparator: ",",
    groupSize: 3,
    digits: 2,
    autoGroup: true,
    placeholder: "0",
    clearIncomplete: true,
    onincomplete: function(){
        console.log( "incomplete" )
    }
});
```

The  `onincomplete` doesnt fire for the `decimal` mask 

Ideally, the `onincomplete` function should fire once the user blurs out from the input, and the input value is invalid.

Also, using the configuration above, a user can type in the following: `12,`.
This is an invalid entry since the groupSize is set to 3.
Having  `clearIncomplete` set to `true`, should clear out this field.

**Comment by RobinHerbots** [comment]
Also see comment in #447

**Comment by RobinHerbots** [comment]
@YoussefTaghlabi , 

Iscomplete and unmasking to number implemented.
However invalid input should never be possible
