### ISSUE TITLE
Adding parentheses as a negative format for Decimal and Integer aliases (100)

### ISSUE THREAD

**Issue by YoussefTaghlabi** [RobinHerbots/Inputmask#451]
A negative number can be represented by either a dash `-100` or parentheses `(100)`.
As of now, only the following format is supported `-100`.
Is it possible to add this feature?

Also a user doesn't have to go all the way to the left of the number to add the negative sign; Pressing the `-` key anywhere in the input field, should "toggle" the negative sign ( Either add `-` to the left of the number, or wrap it in `()` depending on the user configuration).

**Comment by RobinHerbots** [comment]
@YoussefTaghlabi, 

Nice thought.  Thank you for the many input.  I really appreciate that.
I will definitly implement it.

**Comment by YoussefTaghlabi** [comment]
Milestone 2.6?
Thanks!

**Comment by RobinHerbots** [comment]
@YoussefTaghlabi , 

I'm working on the () as negationsymbol.  But I have a question about.  Does the parentheses have to surround the prefix/suffix symbols or not??    $ (123) or ($ 123)
