### ISSUE TITLE
Decimal alias: changing digits to 0 leaves a trailing radixPoint

### ISSUE THREAD

**Issue by YoussefTaghlabi** [RobinHerbots/Inputmask#452]
Consider the following scenario using the following configuration in v2.5.4:

```
$(<SELECTOR>).inputmask("decimal", { 
    radixPoint: ".", 
    groupSeparator: ",",
    groupSize: 3,
    digits: 2,
    autoGroup: true,
    placeholder: "0"
});
```
- Type in the following data into the input field: `1234.56`
  ( This gets masked to: `1,234.56` )
- Change the digits option to 0:

```
$(<SELECTOR>).inputmask("decimal", { 
    digits: 0
});
```

Expected Result: `1,234`
Actual Result: `1,234.`

Please note that the user can still add/remove the radixPoint, which shouldn't be the case since the `digits` option is set to `0`.

**Comment by RobinHerbots** [comment]
I will have a look at it.  Milestone 2.6

**Comment by RobinHerbots** [comment]
@YoussefTaghlabi , 

Fixed.
