### ISSUE TITLE
Phone extention backspace problem

### ISSUE THREAD

**Issue by newsec** [RobinHerbots/Inputmask#454]
Hi! I'm testing phone extention on http://robinherbots.github.io/jquery.inputmask/
1) Type +7123
2) Press backspace 3 times. Expect +7 value, actual +7(6__)
3) Press backspace 1 time. Empty input, caret after second symbol.
4) Press backspace 1 time. Input value +1(___)
etc...

**Comment by RobinHerbots** [comment]
@newsec, 

I will have a look at it.
