### ISSUE TITLE
Select all & Cut Misbehaving in IPad Air

### ISSUE THREAD

**Issue by nitishdhar** [RobinHerbots/Inputmask#456]
If in a numeric masked field, you Select All and Cut the numbers out of the field which removes the formatting as well as preventing any more numbers to be entered until selecting another field and then returning, Once returning to that field, the same number is automatically filled that were cut initially along with the formatting.

**Comment by RobinHerbots** [comment]
@nitishdhar , 

Can you sen me the user agent string.

**Comment by nitishdhar** [comment]
@RobinHerbots - Its being tested in a remote location. Have requested the user agent. Will let you know. Meanwhile any guesses what's happening?

**Comment by RobinHerbots** [comment]
I guess an unhandled input event, ... this will be common for mobile I
think, ...I will have a look at it when times allows.

2014-03-21 3:46 GMT+01:00 Nitish Dhar notifications@github.com:

**Comment by nitishdhar** [comment]
@RobinHerbots - This is one of the user agents - 

IPAD Air 

Mozilla/5.0 (iPad; CPU OS 7_0_6 like Mac OS x) 
AppleWebKit/537.51.1 (KHTML, like Gecko) 
Version/7.0 Mobile/11B651 Safari/9537.53

**Comment by RobinHerbots** [comment]
@nitishdhar , 

I have read that on the Ipad (Safari) the paste event is not triggered in javascript.
If that is the case we need to find a workaround to detect the changes.

**Comment by RobinHerbots** [comment]
@nitishdhar , 

This should be fixed by the latest commit.
