### ISSUE TITLE
Dynamically created inputs

### ISSUE THREAD

**Issue by borodyadka** [RobinHerbots/Inputmask#459]
Hi, i want to use inputmask in my project with that [bootstrap snippet](http://bootsnipp.com/snippets/featured/multiple-fields). But inputmask doesn't work with new inputs.
And i don't know how do it with `$.live()` method.

I'm using Firefox 28 on Xubuntu GNU/Linux if it's does matter.
Sorry for my bad english.

**Comment by YoussefTaghlabi** [comment]
You cant do it with the live method. 
btw, live method is getting deprecated.

To stay consistent with both jQuery and Bootstrap, you can do the following:
- As an example, Add the following data attributes to your input 

```
data-toggle="mask" data-mask-opts="digits" 
```
- Add this script to your page  

```
$(function(){
    $( document.body ).on( "focus.YourCustomNamespace.mask", "[data-toggle=mask]", function (e){
        e.preventDefault();

        var element = $( e.target ),
            data = element.data()
        ;

        if( !data( "_inputmask" ) ){
            element.inputmask( data( "maskOpts" ) );
        });
    });
});
```

This is an unobtrusive way of implementing inputmask, using jQuery and Bootstrap design patterns.

**Comment by RobinHerbots** [comment]
Maybe use the data-inputmask attribute?

2014-03-19 17:05 GMT+01:00 Youssef Taghlabi notifications@github.com:

**Comment by borodyadka** [comment]
Thanks for responses.
@YoussefTaghlabi unfortunately your example doesn't work.
@RobinHerbots thanks, but doesn't works too.

I resolved my problem:
on the end of snippet js, but before attach to DOM i've added

``` js
$( document ).on( 'click', '.btn-add', function ( event ) {
    event.preventDefault();

    var field = $(this).closest('.form-group');
    var field_new = field.clone();

    $(this)
        .toggleClass('btn-default')
        .toggleClass('btn-add')
        .toggleClass('btn-danger')
        .toggleClass('btn-remove')
        .html('–');

    field_new.find('input').val('');
    field_new.find('input').inputmask(); // here we manually added inputmask to new element
    field_new.insertAfter( field );
} );
```

**Comment by RobinHerbots** [comment]
Yep, you need to call the inputmask to allow the data-inputmask to work.

I chose to not do this automatically for the data-inputmask attribute to
give the dev the freedom and choice

2014-03-20 13:56 GMT+01:00 Pavel Kilin notifications@github.com:
