### ISSUE TITLE
Error in maxlength setting mask twice

### ISSUE THREAD

**Issue by mtomas-mpm** [RobinHerbots/Inputmask#461]
Due to an error in my code I was setting the mask of an input twice, the collateral effect in the mask is that the maxlength of the input is doubled (https://github.com/RobinHerbots/jquery.inputmask/blob/2.x/js/jquery.inputmask.js#L1266). I've solved in my code and all works fine, but is there any way to check if the mask is setted in the input before setting up?

A dummy jsFiddle with the behavior: http://jsfiddle.net/5n3pM/2/

Thanks,

Marc.

**Comment by gigermocas** [comment]
When I remove an inputmask the "maxlength" doesn't get reset to the previous value, shouldn't it be the default behavior?

**Comment by RobinHerbots** [comment]
The current version leaves the maxlenght Malone. Zo thuis ons is fixed
