### ISSUE TITLE
Android Chrome fails with input type number

### ISSUE THREAD

**Issue by dotnector** [RobinHerbots/Inputmask#462]
Using the stock Chrome browser on a Nexus 7 with droid 4.4.2 the plugin fails when using  
input type="number"

It simply does not apply the mask to that input type.

http://jsfiddle.net/dotnector/Kc3CA/

**Comment by nsoeffers** [comment]
I also noticed this in chrome on a laptop. 

I think it has something to do with: https://codereview.chromium.org/100433008/#ps60001
As I see the following error: Failed to read the 'selectionStart' property from 'HTMLInputElement': The input element's type ('number') does not support selection.

**Comment by RobinHerbots** [comment]
see #465
