### ISSUE TITLE
Android: Issue in deleting spaces between mask sets if placeholder is set to blank or space

### ISSUE THREAD

**Issue by sidwaseem** [RobinHerbots/Inputmask#464]
Hi Robin,

I have a requirement where i need to mask input[type=tel] to accept credit card number and don't want to reveal mask when user starts typing, which is achieved by setting placeholder=' '. everything working fine on desktops but on android devices Caret position is stucked at spaces.

Here is the scenario.
$( 'input[data-rule-credit-card]' ).inputmask(  '9999 9999 9999 9999', { 'placeholder' : '  '} );

On Android Devices - ( tested on Samsung S3, S4, Nexus 5, Moto G ( Kitkat 4.4.2 ) )
Enter  -> 5432 1234 4567 8765
Delete 8765 -> 
5432 1234 4567 |      -> Caret position is stucked after removing 8. 

The same thing is working fine with default placeholder text.
5432 1234 4567 |____ 

$.inputmask version: 2.5.0

Can you guide me where to fix it in code?

**Comment by RobinHerbots** [comment]
see #465
