### ISSUE TITLE
Value formatting, inputmaks.format() gives error

### ISSUE THREAD

**Issue by ancc** [RobinHerbots/Inputmask#468]
Hi,

when using the example:
var formattedDate = $.inputmask.format("2331973", { alias: "dd/mm/yyyy"});
it gives an error:
Uncaught TypeError: Cannot call method 'toString' of null

example: (copy-paste of minified inputmask because of the mime type)
http://jsfiddle.net/LKJsT/

**Comment by ancc** [comment]
ok, for alias the extensions are needed, but if I use 
var formattedDate = $.inputmask.format("2331973", { mask: "dd/mm/yyyy"});

then formattedDate value will be "dd/mm/yyyy" not the formatted date eg "23/03/1973"

**Comment by RobinHerbots** [comment]
That is because the "dd/mm/yyyy" mask does not exist.    The are no mask
definitions for d,m & y so it is interpreted as static.

2014-03-26 15:35 GMT+01:00 ancc notifications@github.com:

**Comment by ancc** [comment]
thanks! I got it, now it works!
