### ISSUE TITLE
$.inputmask.format doesn't work correctly when numericInput: true

### ISSUE THREAD

**Issue by gigermocas** [RobinHerbots/Inputmask#469]
I'm trying to use $.inputmask.format to format a value directly but I'm having inconsistent results in comparison with an input set up with the same mask options when the "numericInput" option is set to true.

When numericInput is set to true, $.inputmask.format inverts the actual mask and doesn't fill in the mask right-to-left.

In this jsfiddle I was expecting to see the same result in the first two examples:
http://jsfiddle.net/AfFaK/1/

I can easily solve it by reversing the input value, and the resulting output but that shouldn't be needed I think,

**Comment by RobinHerbots** [comment]
@gigermocas , 

I fixed it in the 2.6 branch which will become the main branch soon.

**Comment by RobinHerbots** [comment]
Also fixed in 2.x
