### ISSUE TITLE
Phone Number Mask Issue

### ISSUE THREAD

**Issue by Jaspal** [RobinHerbots/Inputmask#47]
Hi Robin,

I used phone number mask in project but when user press home and try to delete it's not working because pointer just before ( the bracket. can you please tell how to fix this

 $("#phone").inputmask("mask", {"mask": "(999) 999-9999"});

Thanks

**Comment by RobinHerbots** [comment]
Hi Jaspal,

I will fix this asap ;-)  Probably by Monday.

best regards,

Robin

2012/5/10 Jaspal <
reply@reply.github.com

**Comment by RobinHerbots** [comment]
Checkout the latest version 0.6.0 !!

**Comment by Jaspal** [comment]
Thanks i really appreciate.

You Rocks :)
