### ISSUE TITLE
Apply a variable mask according to the length of the text entered

### ISSUE THREAD

**Issue by thiagotalma** [RobinHerbots/Inputmask#470]
You can apply a variable mask according to the length of the text entered? 

For example, if you type: 
1234, the mask will be "99-99" 
12345, the mask will be "999-99" 

Note that the user will enter only numbers. The mask is changed according to the size of the string, instead of changing when the user types the character "-". 

The way the script is now, to use the optional mask, the user must press the "-".

**Comment by RobinHerbots** [comment]
@thiagotalma, 

Cuurently that is not implemented.  But this will be a nice feature.

How do you see this?  Thatthe mask is changed to 99-99 when the focus on the field is lost?

**Comment by thiagotalma** [comment]
See this. It is the ideal behavior.
http://jsfiddle.net/FWUG3/

**Comment by RobinHerbots** [comment]
http://jsfiddle.net/FWUG3/1/ some first tests based on the current implementation in 3.x

**Comment by thiagotalma** [comment]
Very good!

`#code` works perfectly. 
`#code2` works fine on initial fill, but if you delete a character gives error. Problem is also with the tab. 
`#code3` and `#code4` have no changes from the current version, right?

Good would be able to adapt the code of  `#code`.

**Comment by RobinHerbots** [comment]
@thiagotalma , 

What error do you get in code2?

**Comment by thiagotalma** [comment]
Try entering all characters and then delete the last. 
Unlike the `#code`, this does not update the mask, the placeholder remains. 

And also I can not change the field using the TAB.

**Comment by thiagotalma** [comment]
Now is working perfectly! 
Have you changed anything?

**Comment by thiagotalma** [comment]
@RobinHerbots , has a little problem, see: http://jsfiddle.net/FWUG3/2/ 

In the first field I am forced to press the space.

**Comment by RobinHerbots** [comment]
@thiagotalma, 

Code2 fixed + needed space fixed.

The selection between the different masks will not cover all cases, but there is an option determineActiveMasksetIndex which can be used to implement the needed behavior.

Todo code3 & code4 behavior in combi with the code1 & code2

**Comment by thiagotalma** [comment]
Perfect!

**Comment by amr2fxg** [comment]
Hi guys, 
I'm using this mask of code2 so the user can either use 9999-9999 or 99999-9999, but I'm not able to paste anything using jquery.val() or .value  to restore the data on that field. It simply does not accept it.  Is there any workaround for that?

NOTE: already tried pushing only numbers and masked values.
Thanks

**Comment by RobinHerbots** [comment]
@amr2fxg , 

I'm still working on the new implementation of multiple masks.  I will fix that soon.

**Comment by RobinHerbots** [comment]
@amr2fxg , 

Now you should be able to paste a value.

**Comment by amr2fxg** [comment]
Dear @RobinHerbots,
Now I'm able to paste but it does not persist, as a validated value I mean. 
So the content goes away when mousehover or focus. Have a look please:

http://jsfiddle.net/amr2fxg/LF9p7/

Thanks in advance

**Comment by RobinHerbots** [comment]
@amr2fxg , 

Fixed.  See http://jsfiddle.net/LF9p7/5/

**Comment by thiagotalma** [comment]
@RobinHerbots you are the man!

**Comment by amr2fxg** [comment]
I just realize this issue is present when using jquery-2.1.0.js.     Works with 1.6.4.
Thank you @RobinHerbots !!

**Comment by RobinHerbots** [comment]
@amr2fxg , 

Oh no, I should work on the latests versions of jquery.  I will have a look.

**Comment by RobinHerbots** [comment]
@amr2fxg , 

Fixed.

http://jsfiddle.net/LF9p7/8/

**Comment by pnihar** [comment]
if (!androidDetection && id === 'claimnumber') {
--
  | return "'mask': ['A-9999-999999','A-9999-9999999']"; 

i need a  condition where i could enter  both  mask 
it is only accepting for Older versions  of chrome and  IE  . is there any specific reason is this fixed in 5.0.3  do you want me to update  . willl that be a fix  ??


         "validation": "^(C{1}-?\\d{4}-?\\d{6,7})$",


    "RobinHerbots/jquery.inputmask": "github:RobinHerbots/Inputmask@3.3.11",
@RobinHerbots

**Comment by RobinHerbots** [comment]
@pnihar , 

Have a try with version 5.x 
https://jsfiddle.net/robinherbots/cd7b2hgn/3/
