### ISSUE TITLE
Date Mask & AJAX Calendar Extender

### ISSUE THREAD

**Issue by jasonhoelz** [RobinHerbots/Inputmask#471]
Not sure if this is something you'd consider implementing...  I wanted to use your date input masks in conjunction with the AJAX calendar extender.  The input mask allows you to pick the date and it populates the textbox, however, when you tab off the field the input mask itself is put back in the textbox and remains there (until you hover or click in the box again).

<asp:TextBox ID="txtDateTime" runat="server" data-inputmask="'alias': 'date'" />
<ajaxToolkit:CalendarExtender ID="CalendarExtender1" TargetControlID="txtDateTime" runat="server" />

Thanks for the great input masks!

**Comment by RobinHerbots** [comment]
@jasonhoelz , 

Can you make a jsfiddle to make it more visible.

**Comment by jasonhoelz** [comment]
I just switched from using the AJAX calendar extender to use the jQuery ".datepicker()".  It works perfectly in conjunction with your date inputmask - this way I get my free form dates validated, and I can use the datepicker if I want.
$("#txtDateTime").inputmask("mm/dd/yyyy");
$("#txtDateTime").datepicker();

Thanks!
