### ISSUE TITLE
maskedValue on "onUnMask" is reversed when RTL

### ISSUE THREAD

**Issue by gigermocas** [RobinHerbots/Inputmask#472]
relates to #469 

onUnMask() isn't being called with the correct value for "maskedValue" when "numericInput" is true. It should be reversed as it is done with "unmaskedValue" according to isRTL

http://jsfiddle.net/DpmPv/

**Comment by RobinHerbots** [comment]
@gigermocas , 

Fix in 2.x & 3.x
