### ISSUE TITLE
Any way to turn off autocomplete?

### ISSUE THREAD

**Issue by ttback** [RobinHerbots/Inputmask#473]
I realize when you start inputting years with 18.., it jumps to 2018. I have a project that requires older dates in the range of 1800s, and the only way I can stop this behavior is setting a really small min value for the yearrange. Is there a way to simply turn off the autcomcomplete feature?

**Comment by RobinHerbots** [comment]
@ttback , 

There is no option yet, but this will do:

``` javascript
$("#test3").inputmask("date", {
                yearrange: { minyear: 1500, maxyear: 2099 },
                determinebaseyear: function (minyear, maxyear, hint) {
                    return hint + "00";
                }
            });
```

**Comment by ttback** [comment]
Thanks. I think this blocks entering anything out of the range?

**Comment by RobinHerbots** [comment]
yes

**Comment by sshmyg** [comment]
What about 'phone' alias? 
Is any way to turn off autocomplete?
