### ISSUE TITLE
Date mask allowing invalid date entry

### ISSUE THREAD

**Issue by jimithing277** [RobinHerbots/Inputmask#477]
Current version: 2.4.20

This issue can currently even be recreated on the current demo site (http://robinherbots.github.io/jquery.inputmask/) using the 'mm/dd/yyyy' example.

Steps to reproduce:

1) Enter a date of '04/05/2014'
2) Place cursor at the '0' within the DAY portion.
3) Enter '3'.

You'll see that the control allows for a date of '04/35/2014'.

The same issue appears to happen with day modifications as well:

Steps to reproduce:

1) Enter a date of '03/29/2011'
2) Place cursor at the '0' within the MONTH portion.
3) Enter '2'

You'll see that the control reads '02/29/2011' which is _NOT_ a valid date nor leap year.
# Observations

I could have sworn that at one point the mask library was handling these situations.  So, I wound up rolling back our source control to the last version we were on which was 2.2.17 and that version does indeed appear to correctly handle these situations.

For the first example the mask actually cleared out the second input position of the day when the entire input became invalid.  It's almost like the current version only validates within the region you are in and doesn't take in to account the entire input whereas the previous version almost validated each individual character input in relation to the entire input.
# Desired behavior:

For the first example I would expect all positions after the first day character to clear out.

So if the input read '04/05/2014' and I entered a '3' at the first day position it would then read: "04/3_/____". 

For the second example I would expect the same behavior.  If the input read "03/29/2011" and I entered a "2" for the second position within the month the input would clear the remaining invalid entries and leave us with:

"02/**/__**".

If there's any possible way to achieve this it would be greatly appreciated.  I know that maintaining this library is probably a ton of work so I want to again thank you for all your work and efforts!

**Comment by RobinHerbots** [comment]
@jimithing277 ,

I will fix that in milestone 2.7

**Comment by Luckypul** [comment]
I have solved thi problem for date dd/mm/yyyy with two lines of codes in prevalidator and i think work (i have tested) (lines signed with ==>:
 prevalidator: [{
                        validator: function (chrs, buffer, pos, strict, opts) {

```
                        var isValid = opts.regex.val1pre.test(chrs);
    ==>              if(pos == 0 && chrs == '3' && buffer[1] > '1' && buffer[1] != 'g') {isValid = false}
                        if (!strict && !isValid) {
                            isValid = opts.regex.val1.test("0" + chrs);
                            if (isValid) {
                                buffer[pos] = "0";
                                pos++;
                                return { "pos": pos };
                            }
                        }
                        return isValid;
                    }, cardinality: 1
```

---

 prevalidator: [{
                        validator: function (chrs, buffer, pos, strict, opts) {

```
                        var frontValue = buffer.join('').substr(0, 3);
                        if (frontValue.indexOf(opts.placeholder[0]) != -1) frontValue = "01" + opts.separator;
                        var isValid = opts.regex.val2pre(opts.separator).test(frontValue + chrs);
```

   ==>                         if(pos == 3 && chrs == '1' && buffer[4] > '2' && buffer[4] != 'g') {isValid = false}
                            if (!strict && !isValid) {
                                isValid = opts.regex.val2(opts.separator).test(frontValue + "0" + chrs);
                                if (isValid) {
                                    buffer[pos] = "0";
                                    pos++;
                                    return { "pos": pos };
                                }
                            }
                            return isValid;
                        }, cardinality: 1
                    }]

**Comment by Luckypul** [comment]
I test 'g' my placeholdes is "gg/mm/aaaa".
Is suggestion for solve problem.

**Comment by jimithing277** [comment]
Robin,

Is version 3.0 live?  I recently updated our jquery.inputmask library via NuGet Manager and it looks like it pulled down version 3.0.  I'm noticing several issues across the board with our masks at this point and didn't know if this version was actually live and production ready?

Date entry is a bit flaky at this point where entering something like "3414" inputs a date of "03/04/1014" whereas previously it would properly prefix the year with "20".

Link: http://jsfiddle.net/p65wx/

**Comment by RobinHerbots** [comment]
Yes version 3.0 is live.  This is a major version update and there are some
breaking changes esspecially for the extensions which modify the buffer.
I also need to update the documentaion, but haven't got the time.

When there are modifications in the buffer you need to specify  which part
to update.  You can find an example in the date-extension (datetime)

I will fix the date-extension as I forgot to update some parts.

2014-04-23 15:26 GMT+02:00 jimithing277 notifications@github.com:

**Comment by RobinHerbots** [comment]
@jimithing277 , 

I know this took too long, ... but anyway it is fixed in the current version.

**Comment by knaos** [comment]
@RobinHerbots Is th is working now? Because in the DEMO page it is not validating for real dates?
