### ISSUE TITLE
number mask work incorrect if i set maxlength attr.

### ISSUE THREAD

**Issue by guxuede** [RobinHerbots/Inputmask#479]
hi,dear guy.

**Comment by RobinHerbots** [comment]
@guxuede , 

Can you explain a bit more.  Give an example.

Robin

**Comment by guxuede** [comment]
<input id='mynumber' type='text' maxLength="7"/>
js:
 $('mynumber').inputmask("decimal",{allowMinus: false,rightAlignNumerics:false,autoUnmask: true,autoGroup: true,groupSeparator: ",",groupSize: 3,digits: 4});
jsfiddle:http://jsfiddle.net/guxuede/38GAw/
then 
Problem 1:
1.enter some number to input.
2.and execute:$('mynumber').val() at browser console ,but it return incorrect value.
Problem 2:
1.double click mynumber input element to select all.
2.input some number to change it.some time the input box display wrong value.

i think may be i use wrong autoUnmask: true after I realized that decimal not support autoUnmask.
when i remove autoUnmask attr.it works ok.
but the problem is interesting when maxLength and autoUnmask used together.

please close this issue if i use wrong autoUnmask attr.

**Comment by guxuede** [comment]
Add that:
when i keep autoUnmask:true.and remove maxLength,it works too.

**Comment by RobinHerbots** [comment]
Updated you fiddle http://jsfiddle.net/38GAw/1/

Can you have a new test ;-)
