### ISSUE TITLE
in time format hour is taking "dot" too. 

### ISSUE THREAD

**Issue by vipul550** [RobinHerbots/Inputmask#480]
when i type like 1.:11:PM is accepting please provide me solution for this

**Comment by RobinHerbots** [comment]
@vipul550 , 

I will fix that in milestone 2.7

**Comment by vipul550** [comment]
any quick fix  to implement via regx or just basic jquery? as i already done in production and now i am getting this error

**Comment by RobinHerbots** [comment]
I will have a look

**Comment by RobinHerbots** [comment]
@vipul550 , 

Which version do you us e of the plugin? And which mask or alias?

**Comment by vipul550** [comment]
i am using for time, mask: "h:s t\m",            placeholder: "hh:mm xm",            alias: "datetime",
version is latest as i took from github only folder name was 3.x dont know the excat version

**Comment by RobinHerbots** [comment]
Fixed in the latest 3.x branch.

Be aware that there is no release yet for the 3.x branch.

best regards,

Robin

2014-04-15 10:15 GMT+02:00 vipul550 notifications@github.com:
