### ISSUE TITLE
Clear incomplete mask when applying the mask

### ISSUE THREAD

**Issue by thiagotalma** [RobinHerbots/Inputmask#482]
We have an option to clear the incomplete mask when the user is entering and leaving the field. 

How do we indicate that a field should be cleared when it was already loaded with incomplete mask on page load?

**Comment by RobinHerbots** [comment]
milestone 2.7

**Comment by thiagotalma** [comment]
:+1:

**Comment by RobinHerbots** [comment]
@thiagotalma , 

Fixed in the latest version

**Comment by thiagotalma** [comment]
Thanks!  :+1: 
You are the man!
