### ISSUE TITLE
mask date MM/YY : year on two digits only

### ISSUE THREAD

**Issue by YAmikep** [RobinHerbots/Inputmask#483]
Hi,

I had the following mask before "mm/yyyy" which worked but I would like to change it to only 2 digits for the year.
Changing it to "mm/yy" or "mm/YY" does not seem to work.
Is that a bug?

Thanks

**Comment by YAmikep** [comment]
Is it actually not supported at all?
Thanks.

**Comment by RobinHerbots** [comment]
@YAmikep, 

It is not defined as an alias so not supported. (yet)

I will implement it in milestone 2.7

**Comment by YAmikep** [comment]
I saw that the 2.x version is no longer maintened. The current 2.x version is 2.5.10 so just to know, when can I expect the 2.7 version with this change? Thank you.

**Comment by RobinHerbots** [comment]
@YAmikep, 

I t will be in the 3.x version, .... 2.7 is the milestone, ...  (maybe I should update the milestones ;-))

The first 3.x release will come soon, (milestone 2.6)

**Comment by YAmikep** [comment]
I do not understand what you mean when you say that it will be in the 3.x... 2.7 is the milestone and then you say that 3.x is the 2.6?
Sorry I am confused.

**Comment by RobinHerbots** [comment]
To make it short, your issue will be implemented in branch 3.x.

The changes in 2.6 where major so I decided to bump the major version to 3

2014-04-25 15:31 GMT+02:00 Michael Palumbo notifications@github.com:

**Comment by YAmikep** [comment]
Ok got it thanks.
Is there any timeline for the 3.x versions?

**Comment by JackMcKenzie57** [comment]
Was two-digit year ever implemented?

**Comment by RobinHerbots** [comment]
@JackMcKenzie57 , 

Not yet.

**Comment by zeskysee** [comment]
Any update on this issue?

**Comment by RobinHerbots** [comment]
@zeskysee , 

milestone 3.4

**Comment by hielh** [comment]
Hi, is there any solution to use year on two digits only?
can you please give me an exemple.

Regards,
Hicham

**Comment by ronco** [comment]
Is there any way to do this with the current release?  Could it be done with a custom `extendDefintions`?

**Comment by ronco** [comment]
@hielh As a limited workaround I was able to do this to add a new definition for 2 digit year (Y):

```
  Inputmask.extendDefinitions({
    //poor man's 2 digit year for inputmask
    Y: {
      validator: "\\d{2}",
      cardinality: 2
    }
  });
```

It allows me to make use of a mask like `m-d-Y` to get `mm-dd-YY`.  It's not as good as the built in date aliases as I don't think all the correct date checking and min-max range enforcement works, but it's good enough for my purposes for now.  Hope that helps.

**Comment by JackMcKenzie57** [comment]
I am also interested in this feature FYI.   Our page has a lot of dates
invariably in the current century, it looks kind of lame with all those
2015's,   We need DD/MM/YY though.

**Comment by hielh** [comment]
@ronco  TankY for your share, nice solution ;)

**Comment by TheKidCoder** [comment]
+1

**Comment by ncramer** [comment]
+1 on a standard offering for mm/yy as well. In the meantime, I've extended definitions to allow a 'M/Y' alias that implements "smart" month entry using the following snippet. Some may find it useful. If you know how to improve it, feedback appreciated.

```
Inputmask.extendDefinitions({
    M: {
        validator: "0[1-9]|1[012]",
        cardinality: 2,
        placeholder: 'm',
        prevalidator: [{
            validator: function (chrs, maskset, pos, strict, opts) {
                var isNumeric = new RegExp("[0-9]");
                if(!isNumeric.test(chrs)) return false;
                if(chrs > "1") {
                    maskset.buffer[pos] = "0";
                    return {
                        "pos": pos+1,
                        "c": chrs,
                    };
                }
                else return true;
            },
            cardinality: 1
        }]
    },
    Y: {
        validator: "\\d{2}",
        cardinality: 2,
        placeholder: 'y',
    }
});
```

**Comment by JackMcKenzie57** [comment]
Also hoping and waiting for MM/DD with default/year suppression to current
year

**Comment by JackMcKenzie57** [comment]
thanks for that tip

**Comment by jmonschke** [comment]
@RobinHerbots Do you have a specification for what you want to be able to support with variations of the `mm/yy` mask? Would a PR to add this be welcomed?

**Comment by RobinHerbots** [comment]
@jmonschke, 

It is planned to totally rewrite the date alias.  See projects

**Comment by JackMcKenzie57** [comment]
My personal interests have to do with very tight/dense screen layouts, for
instance to fit two date ranges and some text on a single line along with
descriptive text.   4 x 4 characters for the year makes this impossible.
Examples using US style MM/DD/YY:


 I would be to be able to enter MM/YY only defaulting day of month, for
example

Another thing that would be convenient is DD/MM

For entries that are predictably around the current date, a current year
window range would be nice.  This is to say, if the range window was 45
days and current date is within 45 days of end or beginning of year, year
is next year

*Mask*

*Entry*

*Current Date*

*Window*

*Result*

MM/01/YY

9/17





09/01/17

MM/31/YY

9/17





09/30/17

MM/31/YY

4/17





4/31/17

MM/31/YY

9/31





Invalid Date

DD/MM

9/30

1/1/17-12/31/17



09/30/17

DD/MM

9/30

1/1/18-12/31/18



09/30/18

DD/MM

11/28

1/1/17-12/31/17



11/28/17

DD/MM

11/28

1/1/18-12/31/18



11/28/18

DD/MM

9/30

11/28/17

45

09/30/17

DD/MM

12/15

11/28/17

45

12/15/17

DD/MM

01/15

11/15/17-02/15/18

45

01/15/18

DD/MM

01/15

11/01/17

45

01/15/17

DD/MM

01/15

11/28/17

45

01/15/18

DD/MM

01/15/18

11/01/17

45

01/15/18

DD/MM

01/15/17

11/28/17

45

01/15/17

**Comment by RobinHerbots** [comment]
@JackMcKenzie57 , 

I will try to block some time so I can start working on the new date alias which will allow the format.

**Comment by bdalina54** [comment]
is there an available format for this fullmonth/year = September/2017 = ? /YYYY

**Comment by JackMcKenzie57** [comment]
Forwarding a prior email for consideration, in response to your recent
request for specs for MM/YY mask.   The prior response was to do with a
DD/MM input with year defaulted.  Not sure if what you are proposing could
cover similar territory or if the possibility is there for a DD/MM input.

In any case, some of this would also possibly apply to an MM/YY.

Would YY/MM return just a month/year string or would the day of the month
be defaulted?  Again. my wish is to be able to enter a full calendar date
without the need to display or enter the year.

I had this idea of a "window" to specify what day would be returned.

Being able to specify the default year with respect to the current year
would be lovely.  It would also be useful to allow MM/YY specify a window
for year default.   My users enter date ranges that would typically be in
the recent past.  So if they were to enter a pair like

12/15 - 01/15 that would for them quite unequivocally mean 12/15/16 -
01/15/16.  They hate having to enter the year and it crowds the display, in
their minds, unnecessarily.

**Comment by RobinHerbots** [comment]
@JackMcKenzie57 , 

Have you already took a look at the new datetime alias in the 4.x branch?
You can now specify the inputformat you require.

**Comment by JackMcKenzie57** [comment]
OK I will look at that.  I guess I missed the announcement.  Thank you for
all you do ! 😇

**Comment by sorin-pereteanu-ascendro** [comment]
Hi,
Do you have any ideea how to set a date alias in this format 'mm.yyyy' (with dot)? With slash works well, but not with dot.

Thanks

**Comment by RobinHerbots** [comment]
@JackMcKenzie57 , 

This should already work.  Which version do you use?

**Comment by Seedmanc** [comment]
Same problem here about **mm.yyyy**, using 3.3.11. Seems like the entry for that format is missing from the bundle, only the one for mm/yyyy is present. At least adding it fixes the issue.

**Comment by RobinHerbots** [comment]
@Seedmanc , 

Version 4.x allows for specifying a dateformat.
