### ISSUE TITLE
Setting a value with document.getElementById().value

### ISSUE THREAD

**Issue by ghost** [RobinHerbots/Inputmask#484]
Hello @RobinHerbots 

I have a problem, if I try use the inputmaks plugin on Chrome and IE. (latest versions)
Anyway, It's working properly on Firefox.

My problem is that, if I set a new value widht document.getElementById().value, the maks doesen't work.

I'm enclosing the example:
http://jsfiddle.net/tnr2e/3/

How can I solve this problem? Unfortunatelly, I can't use in my model the jquery selector.

Best regards,

Viktor

**Comment by RobinHerbots** [comment]
@vtothviktor, 

That is because firefox allows to modify the native value property while chrome and IE don't.  The fallback is jquery.val or trigger the setvalue event.  Why can't you use jquery.val?

Maybe try this one http://jsfiddle.net/tnr2e/4/

**Comment by ghost** [comment]
Hello @RobinHerbots,

Thank you so much. The setvalue event was good.
I can of course, but in this case I sholuld rewrite my code.

Best regards,

Viktor
