### ISSUE TITLE
Jquery minimum version

### ISSUE THREAD

**Issue by xMANIGHTx** [RobinHerbots/Inputmask#485]
Hallo Boss, does this work with Jquery 1.9.1? I saw you are using 1.10.x in the demo.
I'm asking since I would like to use this along with Telerik .NET controls and they are struck at 1.9.1, otherwise I'll have to load a double jQuery to use this script.
I can't find anywhere what is the minimum jQuery version to run along with the script.
Sorry for posting here if it's not the right place.

**Comment by RobinHerbots** [comment]
;-)  The minimum version of jQuery is 1.7

2014-04-13 20:15 GMT+02:00 xMANIGHTx notifications@github.com:

**Comment by xMANIGHTx** [comment]
Hey! That’s AWESOME thanks. So there must be some other things interfering with my code.. I’ll do some other tests.
Can’t wait for the “tabbing and autoselect on skip inside the mask” to be implemented!!
Great job so far

Da: Robin Herbots [mailto:notifications@github.com] 
Inviato: domenica 13 aprile 2014 21:17
A: RobinHerbots/jquery.inputmask
Cc: xMANIGHTx
Oggetto: Re: [jquery.inputmask] Jquery minimum version (#485)

;-) The minimum version of jQuery is 1.7 

2014-04-13 20:15 GMT+02:00 xMANIGHTx notifications@github.com:
