### ISSUE TITLE
escape special mask chars

### ISSUE THREAD

**Issue by luizcruz00** [RobinHerbots/Inputmask#486]
Hi Robin!

Congratulations for this fantastic work!

It's the first time I use a jQuery plugin, So I can say your work is very easy to understand, because even beginners can use!

I created a mask for chassis vehicle, with the following format "InputMask (." # # # # - # # # # - # - # # # # - # # # # "); "and it is working perfectly. 

Now, I would like to prevent the user can enter the following letters: "I, O, Q" 

Which function should I use? "escape special chars mask"? 

I saw the bellow statement, but I don´t undestand what to do!

$(document).ready(function(){
    $("#months").inputmask("m \months");
});

Please, could you give a hand?

Regards! 

Luiz Cruz

**Comment by RobinHerbots** [comment]
Hi Luiz,

Thx ;-)

You have to create a custom definition for it. (see
jquery.inputmask.extensions.js)

```
$.extend($.inputmask.defaults.definitions, {
  'c': {
        validator: "[A-HJ-NPR-Za-hj-npr-z\u0410-\u044F\u0401\u04510-9]",
        cardinality: 1,
        casing: "upper"
    }
});
```

and use ." c c c c - c c c c - c - c c c c - c c c c "

What you mention is for the case you have a defintition m but you want it
to use as a fixed part like the m in months.  By escaping you tell the
plugin to not treat it as a mask definition.

2014-04-14 0:06 GMT+02:00 luizcruz00 notifications@github.com:

**Comment by luizcruz00** [comment]
Hi Robin!

Thank you very much!

The extension you provided works perfectly!

Now I understood we need to inform what _"is allowed"_ instead to set what _"is
not allowed"_.

Please, I need one more tip!

I would like to alert the user when he type a letter that is not allowed in
the "VIN" information "onkeydown"

I read we can use  "onKeyUp / onKeyDown option"  to do some extra
processing of the input when certain keys are pressed.

Please, could you tell me how can I alert " the letter you entered is not
allowed!...."

When the user enters the letters "I, O, Q?

Best Regards!

Luiz

2014-04-14 4:08 GMT-03:00 Robin Herbots notifications@github.com:

**Comment by RobinHerbots** [comment]
@luizcruz00 , 

Use the onKeyValidation callback

**Comment by luizcruz00** [comment]
Hi Robin!

Thank you!

I hope I'm not abusing your generosity!

but unfortunately, I have no idea how can I use the Function(result) to
alert when the user enter I,O,Q!

I already tested the _"IsComplete"_ function and it worked perfectly!
_onKeyValidation_ works the same way as *"IsComplete"? *

Please,how should we refer to characters not allowed?

$(document).ready(function(){
   $("#EditRecordChassi").inputmask("cccc-cccc-c-cccc-cccc",
              { onKeyValidation: function (result) {
                                       _//do something??_
                                console.log(result);
                                } });
});

Regards!

Luiz

2014-04-15 3:21 GMT-03:00 Robin Herbots notifications@github.com:

**Comment by RobinHerbots** [comment]
@luizcruz00 , 

verify the result. 
 If(result === false) 
add some class or css styling to indicate the fault entry 
else remove class or css styling

**Comment by luizcruz00** [comment]
Hello Robin!

Thanks for your help, but unfortunately I feel that this goes far beyond my
reach!

I'm really newbie, sorry for my lack of knowledge!

Regards!

Luiz

2014-04-15 18:37 GMT-03:00 Robin Herbots notifications@github.com:
