### ISSUE TITLE
Typing problems on Android

### ISSUE THREAD

**Issue by awudarowicz** [RobinHerbots/Inputmask#487]
There are two different problems with typing on Android devices. It depends on Android version:
1. For Android 4.2 (and propably other modern versions) - In newest version of jquery.inputmask mask doesnt work. The mask is moving to the right while we typing text. What is strange: In older plugin version everything was ok!
2. For Android 2.3 - The text is strangely jumping when it detects mask char. For example when we have mask 99-99 it jums after '-'. And typing incrasing numbers it will look like: 12-43. I've recorded it and you can see this in action here:
   https://www.dropbox.com/s/3qekwg6169y5uw9/20140414_101401.mp4

**Comment by dcbrilho** [comment]
Same problems here... Testing on Samsung S4 (Android 4.4.2)...

**Comment by andrew-veresov** [comment]
Having same troubles - Android 4.3

**Comment by RobinHerbots** [comment]
see #465
