### ISSUE TITLE
How to remove (skip) a small cross

### ISSUE THREAD

**Issue by gorkovv** [RobinHerbots/Inputmask#488]
How to remove (skip) a small cross, which is shown on the right only in IE?

**Comment by RobinHerbots** [comment]
That has nothing todo with the inputmask, it is an IE thing.  Anyway you
can hide it with css, .. ms-clear or something.  (google it)

2014-04-15 8:58 GMT+02:00 kib1org notifications@github.com:

**Comment by gorkovv** [comment]
Thanks for the tip!
::-ms-clear {display: none;}
