### ISSUE TITLE
add some unit testing (qUnit)

### ISSUE THREAD

**Issue by RobinHerbots** [RobinHerbots/Inputmask#49]

**Comment by MarcDiethelm** [comment]
I would like to encourage you to do this. Your plugin is obviously complex and changes in one place affect functionality in other places and different use cases. Automated testing would bring a great improvement in quality and currently you seem to have some problems with regressions.

**Comment by RobinHerbots** [comment]
@MarcDiethelm , 

I totally agree, .... but if I only had the time, ... or if someone could create an initial setup with some basic steps to get started.  That would be greatly appreciated.

Robin

**Comment by RobinHerbots** [comment]
added qunit base - more testing will come

I need sometthing to mimic real keyboard input

**Comment by MarcDiethelm** [comment]
Funny. I'm working on it right now. I'm using [JSRobot](http://tinymce.ephox.com/jsrobot). It depends on a Java Applet (which might be problematic). I'll have something to show in a day, the basic setup is there. But I need to go to bed now unfortunately.

**Comment by RobinHerbots** [comment]
Hi Marc,

That would be great.  I would like to keep the qunit testing as framewiork.
 Maybe an async call from qunit which executes the jsRobot stuff.

2013/7/16 Marc Diethelm notifications@github.com

**Comment by RobinHerbots** [comment]
@MarcDiethelm ,

I created a little sendkeys fn which does the job for input. See qunit folder tests;js
The unittesting already showed some degression for the oncomplete. 

It's easy and definitely needed for the stability of the plugin.
