### ISSUE TITLE
Right aligned values jump slightly on :focus

### ISSUE THREAD

**Issue by hanneslinder** [RobinHerbots/Inputmask#490]
When using the plugin to mask input values as right aligned decimals, clicking / focusing the input causes the input values to jump slightly to the left side.
I did not find any css properties that could be responsible for this effect and setting a different padding-right on :focus does not seem to work either.

This behavior can be observed on the official demo page in the 'Decimal' field.

Any help would be appreciated.

**Comment by RobinHerbots** [comment]
@hanneslinder, 

You are right, I never did attention to it, but I also see the small itch ;-)

I guess it is  npt.scrollLeft = npt.scrollWidth; in the caret function which causes that.
Maybe you can comment that line out to verify.  
Your feedback is welcome and appreciated.

I will also have a look at it when time allows.

**Comment by hanneslinder** [comment]
Perfect! 
Commenting out that line seems to solve the issue :)
