### ISSUE TITLE
Version 3.0 seems not working

### ISSUE THREAD

**Issue by ghost** [RobinHerbots/Inputmask#491]
I created a test html page as below. Cant enter any character. Whats wrong
Cant paste the html here. Put it at http://jsfiddle.net/6nNJs/  .But please keep in mind its only for html sharing

**Comment by RobinHerbots** [comment]
@hjunior81 , 

The is nothing to see in the html.  Can you create a jsfiddle, then it will be more clear why it is not working.

best regards, 
Robin

**Comment by ghost** [comment]
Cant paste the html here. Put it at http://jsfiddle.net/6nNJs/ .But please keep in mind its only for html sharing

**Comment by RobinHerbots** [comment]
@hjunior81 

See http://jsfiddle.net/6nNJs/2/

**Comment by ghost** [comment]
Yes. Thats the problem. As you see both inputs are not writable. Thanks.

**Comment by RobinHerbots** [comment]
What browser are you using??

2014-04-16 8:11 GMT+02:00 hjunior81 notifications@github.com:

**Comment by ghost** [comment]
Firefox 26 or Internet Explorer 10.
Firefox; cant write any character
IE; doesnt format number and also writes as left aligned

**Comment by RobinHerbots** [comment]
@hjunior81 , 

Can you retry with http://jsfiddle.net/6nNJs/3/

**Comment by ghost** [comment]
Ok friend. Its working both Firefox and IE. Thanks.
