### ISSUE TITLE
The dd/mm/yyyy format is incompatible with jquery.datepicker

### ISSUE THREAD

**Issue by ghost** [RobinHerbots/Inputmask#492]
The mask alias dd/mm/yyyy is incompatible with jquery.datepicker. It should be dd.mm.yyyy i think, since datepicker has this as default (at least german or turkish). Or is there another way to get same behavior by using dd.mm.yyyy like option.separator:'.'?

**Comment by RobinHerbots** [comment]
This is culture dependent

for now just use the dd.mm.yyyy alias.

I will refactor the datetime alias to allow to give a date pattern as an
option. Maybe in combination with jquery .globalize

But that will be for later

2014-04-16 13:02 GMT+02:00 hjunior81 notifications@github.com:

**Comment by ghost** [comment]
For now i tested using mask:"d.m.y" and it works for now.
