### ISSUE TITLE
Loosing 0 when pasting to masked input with number prefix

### ISSUE THREAD

**Issue by mirzagitov** [RobinHerbots/Inputmask#493]
Example: http://jsfiddle.net/McZBb/

**Comment by RobinHerbots** [comment]
@moongrate, 

I see, it is the not so intelligent guess, who thinks he may skip the leading zeros as the fixed part contains a zero.

Replacing in the pasteevent line checkVal(input, false, false, pasteValue.split(''), true); with
checkVal(input, false, false, pasteValue.split(''), false); will do.

But I will have a look if to fixed it in general.

**Comment by RobinHerbots** [comment]
This issue is resolved in version 5.0.0-beta

http://jsfiddle.net/973c2e5x/
