### ISSUE TITLE
unmaskedvalue returns same as input

### ISSUE THREAD

**Issue by ghost** [RobinHerbots/Inputmask#494]
Please see http://jsfiddle.net/6nNJs/5/  Press hit button. Thanks again.

**Comment by RobinHerbots** [comment]
@hjunior81 , 

I still need to fix that for decimals, that the unmaskedvalue returns a numeric value.

milestone 2.7

**Comment by ghost** [comment]
Im using 3.x branch. Will you merge it when finished?

**Comment by RobinHerbots** [comment]
2.7 is the milestone.

I will do the changes in 3.x.

**Comment by ghost** [comment]
Will it take long time my friend. Im in hurry a bit.

**Comment by jpirok** [comment]
I'm having an issue with $(element).inputmask('unmaskedvalue') as well.  http://jsfiddle.net/jpirok/B9VWk/
Using a number in a text field I get no value from this function.

Edit: This is happening in 3.0.2 and 3.0.5 as well.

**Comment by RobinHerbots** [comment]
@hjunior81 , 
@jpirok , 

Fixed in the lastest version .

Updated http://jsfiddle.net/B9VWk/7/

**Comment by jpirok** [comment]
Great thanks!
