### ISSUE TITLE
Phone Mask

### ISSUE THREAD

**Issue by himadriganguly** [RobinHerbots/Inputmask#495]
Love the plugin and its really great. Thanks a RobinHerbots for contributing to the open source. Wish you all the best.

I am new to this plugin so want to know how to mask the phone number such as (+91)-#####-##### where +91 will be fixed. I am using jquery.inputmask.phone.extensions.js along with jquery.inputmask.js.

Another issue is that when i am using <input data-inputmask="'alias': 'phone'" /> and $(document).ready(function(){
    $(":input").inputmask();
});
the input box is displaying the format +_(___)**_-_**_ but don't taking any input.

Please help.

Thanks a lot.

**Comment by RobinHerbots** [comment]
@himadriganguly , 
The phone extension loads the masks through ajax, so you need to specify the correct url to fetch the masks.

Anyway when you only need (+91)...  just use a simple mask like

$(selector).inputmask("(+\91)-99999-99999");

**Comment by himadriganguly** [comment]
Thanks a lot RobinHerbots for your help. Another help i want from you is that can you please show me how to load phone extensions.

Wish you all the best.

**Comment by RobinHerbots** [comment]
@himadriganguly, 

Look inside the phone extension.

Specify the url of the file

**Comment by RobinHerbots** [comment]
and verify the result of the ajax call inside
