### ISSUE TITLE
Decimal mask radixPoint ignored or mishandled while setting js decimal

### ISSUE THREAD

**Issue by ghost** [RobinHerbots/Inputmask#499]
Please have a look at 
http://jsfiddle.net/6nNJs/7/  Hit the "Set Decimal Number" button. The result should be 12.345,67 i think since the radixPoint:',' and groupSeparator:'.'

Am i wrong?

**Comment by RobinHerbots** [comment]
@hjunior81 , 

Try with http://jsfiddle.net/6nNJs/9/

**Comment by ghost** [comment]
Same problem. Tested with Firefox 26

**Comment by ghost** [comment]
Will it take long time my friend. Im in hurry a bit.

**Comment by RobinHerbots** [comment]
@hjunior81 , 

When you try the 2nd button it works.  There is no awareness of types for now.

**Comment by ghost** [comment]
Think about a widget. I will use it for decimal inputs. So when i get the value with unmaskedValue it will return js number of 12345.67 . When i want to set it a value i will set 12345,67 (why not 12.345,67 this is another case to discuss). Does it seem correct? Am i missing something?

**Comment by RobinHerbots** [comment]
@hjunior81, 

I do agree and understand the need for it.  I just pointed to a quick workaround.

I should be possible to set the value with a javascript decimal into the decimal extension.

**Comment by RobinHerbots** [comment]
@hjunior81 , 

Fixed in the latest version
