### ISSUE TITLE
Cursor hops between last typed character & the end of the field (Samsung S3)

### ISSUE THREAD

**Issue by nitishdhar** [RobinHerbots/Inputmask#501]
The text cursor jumps back and forth between the end of the input field and the last character typed. This is observed to happen on a Samsung S3 device.

![cursor hop](https://cloud.githubusercontent.com/assets/1340144/2764120/d97a9f26-ca0e-11e3-9a15-d8953ee5d612.PNG)

**Comment by RobinHerbots** [comment]
see #465

**Comment by nitishdhar** [comment]
@RobinHerbots - Hey thanks I went through it. So just to clarify, the library has the fix for this now?

thanks again

**Comment by RobinHerbots** [comment]
@nitishdhar , 

Android support is still poor.  When you only use numerics, you will have the most of luck.
There is some kind of backspace detection, but it will not work for every case.

Anyway, I guess the new way on mobile are the composioning events.  Although I expected at least something in the data property as  described in the specs.
