### ISSUE TITLE
"placeholder" setting ignored

### ISSUE THREAD

**Issue by glosswordteam** [RobinHerbots/Inputmask#502]
Conditions are:
1) $.extend($.inputmask.defaults.definitions, { "A": { validator: "[A-Za-z ]" } }
(latin characters and space character)
2) $("object").inputmask({ mask: "A", placeholder: "", repeat: 16 } )
(no placeholder, length is 16)

In version 3.0.0 the result is "testAtest", however version 2.4.7 works ok -- "test test".

How to reproduce:
http://jsfiddle.net/5n3pM/10/

// Windows Chrome

**Comment by RobinHerbots** [comment]
@glosswordteam , 

I will fix that asap.

**Comment by glosswordteam** [comment]
Thanks!  )

**Comment by RobinHerbots** [comment]
Done
