### ISSUE TITLE
onincomplete: Uncaught RangeError: Maximum call stack size exceeded. 

### ISSUE THREAD

**Issue by ttback** [RobinHerbots/Inputmask#504]
I had following code snippet to handle case when user did not finish input a full date. I have the input default to something like 01/01/1980, and need to restore the value if user doesn't finish the mask. 
{
 "clearIncomplete": false,
 "onincomplete": function() {
                    $dateInput.val(month+"/"+day+"/"+year);
 }

This will trigger an infinite loop for some reason, the mask is 
            $dateInput.inputmask("mm/dd/yyyy", {
                "placeholder": "mm/dd/yyyy",

I can't see why this is happening.

**Comment by ttback** [comment]
Simply clicking the date input element seems to trigger 20 incomplete calls.

**Comment by RobinHerbots** [comment]
I will have a look ASAP

2014-04-23 17:18 GMT+02:00 [T] notifications@github.com:

**Comment by RobinHerbots** [comment]
Can you workout an example as I cannot reproduce the issue.

best regards,

Robin

2014-04-24 9:14 GMT+02:00 Robin Herbots robin.herbots@gmail.com:
