### ISSUE TITLE
input blocked

### ISSUE THREAD

**Issue by radio-programa** [RobinHerbots/Inputmask#505]
Sometimes, when Selenium, rarely at hand, after removing all the input in the form and clicking on the input with the mask 99-999 or [X] 999 99 99 999 I can not write. Only when you click anywhere on, the problem disappears.

**Comment by RobinHerbots** [comment]
@radio-programa , 

Can you simulate this somehow in a jsfiddle or something alike?

**Comment by edminify** [comment]
Hi. Use RobinHerbots/Inputmask
Selenium doenst work (not see click)
Example
 driver.findElement(By.name("signerSsn")).click();
 driver.findElement(By.name("signerSsn")).sendKeys("3333-33-3333");

or
      driver.findElement(By.xpath("//*[@id=\"signerInfo\"]/div/div[2]/div[4]/label/input")).click();
      driver.findElement(By.xpath("//*[@id=\"signerInfo\"]/div/div[2]/div[4]/label/input")).sendKeys("3333-33-3333");
Please help
