### ISSUE TITLE
On focus mask is getting selected and also cursor does not focus to the last number

### ISSUE THREAD

**Issue by babupca** [RobinHerbots/Inputmask#507]
Hi Robin,

I have two problem with this mask.

I wanted to achieve the following, by default the place holder will be having four zeros. The mask is working fine, but having some problem with the focus and the cursor area 
0000 
0001
0011
0111
1111
1. When i tab from sector to state text box, the state textbox gets placeholder content gets selected. I tried to remove this selection, but failed
2. In continuation to the above problem, when the state textbox cotent beign selected, i pressed the left arrow, now the cursor stayed at the first position and typed from there, but cannot able to type any numbers, it does not allow to type any numbers.

At the same when i manually clicked the state textbox, now the cursor automatically moved towards last number

I think this will create confusion for the user and he may leave the form without entering any details.

Here is my jsfiddle link. --   http://jsfiddle.net/Y6LNV/7/

Kindly give some help in this problem.

Thanks

**Comment by RobinHerbots** [comment]
@babupca, 
1.  This is the behavior of an input tabbing in selects the input.  But if you comment out the last call to caret in the keyup event It will not select the contents.  The idea for later is to implement a defaultvalue which the mask is aware off and select the content based on the input.
2. As the placeholder is valid input the mask cannot determine wheter this is a placeholder or input.
   You can set the insertMode option to false to overwrtite, but that seems broken in version 3.x with the options you used.  

I will first have a look at the 2nd issue.

**Comment by babupca** [comment]
Thanks Robin. It would be greatful if you could give some solution in your next near realease.

**Comment by RobinHerbots** [comment]
@babupca , 

The above does already work.  Only need to fix the overwrite mode for numericinput.

**Comment by babupca** [comment]
ok thanks.
