### ISSUE TITLE
Require the user to enter the decimal part of the number

### ISSUE THREAD

**Issue by thiagotalma** [RobinHerbots/Inputmask#508]
I have found no way to start filling the decimal mask for cents. Decimals are only filled after the user enters the separator character. 

It would be too good an option to start typing the decimal part, making it obvious to the user that is a monetary value, for example.

**Comment by lucasbraum** [comment]
Try this:

```
<input type="text" class="mascara" id="mascara" >
<script type="text/javascript">
      $(document).ready(function(){
        $(".mascara").inputmask('999.999.999,99', { "placeholder": "", numericInput: true, showMaskOnFocus: false, showMaskOnHover: false});
        });
</script>
```

There are some optionals fields, but you can remove them if you want.

**Comment by thiagotalma** [comment]
Thus I have a fixed mask. 
The decimal mask is free fill. 

I could use that way, but now the script gives error when using optional mask in numeric fields.

``` JAVASCRIPT
$("#code1").inputmask('[99999999]9,99', { numericInput: true});
```

`Cannot read property 'isGroup' of undefined`

See: http://jsbin.com/vonalavo/3/edit/

**Comment by RobinHerbots** [comment]
Use the numeric or decimal alias and set digitsOptional : false as option
