### ISSUE TITLE
How to show mask by demand?

### ISSUE THREAD

**Issue by lucasbraum** [RobinHerbots/Inputmask#509]
I would like to show my mask by the user demand. The user starts to typing and the mask starts to show up by steps.

For exemple: When I start to typing, the full mask appears. But if I will type just U$ 2,90, I wouldn't like to see the role mask (999.999.999,99).

This is my code:

```
<input type="text" class="mascara" id="mascara" >
<script type="text/javascript">
      $(document).ready(function(){
        $(".mascara").inputmask('999.999.999,99', { "placeholder": "", numericInput: true, showMaskOnFocus: false, showMaskOnHover: false});
        });
</script>
```

Thanks

**Comment by RobinHerbots** [comment]
@lucasbraum , 

Isn't the decimal alias an option?  (btw I am working on a numeric alias which enhances the decimal alias to allow currency input etc

**Comment by RobinHerbots** [comment]
user the numeric alias
