### ISSUE TITLE
Why the checkbox does not work?

### ISSUE THREAD

**Issue by erikcordeiro** [RobinHerbots/Inputmask#510]
Hi, All...
Could anyone tell me why the checkbox does not work in this code?

Script part:
1..... $(document).ready(function () {
2.......... $("#txtCalendar").inputmask({ alias: "date", placeholder: "_" });
3............... $("#chk1").click(function () {
4.................... if ($("#chk1").prop("checked")) {
5......................... $("#txtCalendar").val("01/01/2014");
6.................... } else {
7......................... $("#txtCalendar").val("");
8.................... }
9.......... });
10.....});

Body part:
< input type="checkbox" id="chk1" />
< input id="txtCalendar" />

The problem is that the checkbox does not change state if the InputMask of txtCalendar is enabled.
Just comment the line 2 ($("#txtCalendar").inputmask...) to everything works. Or replace $("#txtCalendar").val to document.getElementbyId("txtCalendar").value, but I got the same problem that Macharius92 in https://github.com/RobinHerbots/jquery.inputmask/issues/256.

Please, any help?

**Comment by RobinHerbots** [comment]
@erikcordeiro , 

Can you make a jsfiddle for it.  That is easier to verify.

**Comment by erikcordeiro** [comment]
Ok.. 
http://jsfiddle.net/erikcordeiro/MdYuS/

**Comment by RobinHerbots** [comment]
@erikcordeiro , 

Fixed in 3.0.6
