### ISSUE TITLE
clearIncomplete should ignore optional trailing part

### ISSUE THREAD

**Issue by rickstricker** [RobinHerbots/Inputmask#511]
I'm using a mask of '999-999-9999 [x99999]' and when I set clearIncomplete to true it always clears unless the optional part is completely filled out.

**Comment by RobinHerbots** [comment]
@rickstricker , 

You are right.  I will have a look at it.  

Thx for reporting.

**Comment by RobinHerbots** [comment]
@rickstricker , 

Just a question.  When should the mask clear?
When I type 123-123-1234  it is ok  but what if I type 123-123-1234 x1
The mask is not complete because the optional part is not complete.

**Comment by rickstricker** [comment]
Great question.  We want the optional part, at least in the case of an extension, to be a variable length up to the number of 9s specified.  We're taking phone numbers from the general population, so we have no idea how long their extensions might be.  That's the way it works in the jquery maskedinput plugin as well.  We switched to inputmask because it works better with knockout. Thanks!

**Comment by RobinHerbots** [comment]
@rickstricker , 

The inputmask sees the optional part as a whole.  This is logical behavior.  
For your desired behavior.  you need a mask like 

```
 $("#test1").inputmask('999-999-9999 [x9{0,5}]', { clearIncomplete : true});
```

**Comment by prithvichauhan88** [comment]
I am facing similar issue here, when I use masking for independent input type it works fine.
`$("#selector").setAttribute('data-inputmask', '"mask": "999-99-9999","clearIncomplete": true');`

But when I use same masking in grid with jqGrid, having incomplete value it's not clearing the incomplete value.
```ColumnModels.push({
                        editoptions: {
                            dataInit: function (element) {
                                $(element).inputmask({ mask: '999-99-9999', "clearIncomplete": true });
                            })}});
```

Any idea about this?

**Comment by RobinHerbots** [comment]
@prithvichauhan88 , 

The value is set afterwards in jqgrid?  Just a guess try to trigger a blur event on the elements.  

Otherwise if you can make some jsfiddle with some example. in a new issue.
