### ISSUE TITLE
decimal with prefix

### ISSUE THREAD

**Issue by zassq** [RobinHerbots/Inputmask#512]
Hi,

It is an awesome plugin! Thanks bro!
I've tried to apply prefix with decimal extension, but it didn't work.

Doing like this:

```
$(element).inputmask(
"decimal", { autoGroup: true,  groupSeparator: ',', groupSize: 3, prefix: '$'}
);
```

I've tried numeric as well, but somehow the autoGroup didn't work.

Did I do anything wrong? Or, how can I get it works?
Thanks.

**Comment by RobinHerbots** [comment]
@zassq , 

I am working on a new alias numeric which will allow that. In the current decimal alias the prefix isn't implemented.

**Comment by RobinHerbots** [comment]
@zassq , 

A first version of the numeric alias is available. (no grouping yet)

```
$(element).inputmask(
"numeric", { prefix: '$ '}
);
```

**Comment by RobinHerbots** [comment]
@zassq, 

prefix and suffix now supported

**Comment by zassq** [comment]
@RobinHerbots Awesome! Thanks!
