### ISSUE TITLE
'RegEx' filter is very slow

### ISSUE THREAD

**Issue by potar** [RobinHerbots/Inputmask#513]
The problem is: a browser stops responding or updating results very slowly during editing of input.

I created a test case:
http://jsfiddle.net/3Mmdt/4/
Please try to edit the input quickly/slowly. If you have an opportunity, use Firefox or IE, please.

The question is: can I somehow speed up the validation of input. 

I would greatly appreciate if you could recommend me something.

**Comment by RobinHerbots** [comment]
@potar , 

Can you have a test with http://jsfiddle.net/3Mmdt/5/

**Comment by potar** [comment]
@RobinHerbots Still have the same problems. Besides, the mask doesn't work properly in your example (http://jsfiddle.net/3Mmdt/5/). For instance, I can't remove '%1'

**Comment by RobinHerbots** [comment]
@potar , 

Which browser do you use as I can delete perfectly.

**Comment by potar** [comment]
@RobinHerbots 
Browsers that were used for testing:
Chrome 34.0.1847.131
Firefox 16.0.1

Usually, I get:
https://www.dropbox.com/s/g3nvbhuu8apq9zi/Screenshot%202014-05-02%2012.53.50.png

I have created a new jsfiddle (http://jsfiddle.net/3Mmdt/6/) based upon your solution. You will see "%1%1%1%1%1%1%1%1%1%1%1%1%1" there. 

So, the test case for removing problem is:
1) Put the cursor ('|') in the middle of the string "%1%1%1%1%1%1|%1%1%1%1%1%1%1"  
2) Delete the string to the end. You will get:
"|%1%1%1%1%1%1%1"
3) Start deleting from the end and move to the beggining:
"%1%1%1%1%1%1%1|"
In the end, you will get something like:
"|1%%1%1%1%1%1"
Thus, removing doesn't work properly. I have tested this on Firefox 16.0.1

You can try another test case: try to use "delete" button for removing (not "backspace").  The problem is I can't delete more then one char.

**Comment by RobinHerbots** [comment]
Yep, I will have a look at it

**Comment by potar** [comment]
It might be a problem in V8 [http://en.wikipedia.org/wiki/V8_(JavaScript_engine)]. I have noticed: if the regexp below can be evaluated by a browser in "console" mode, there won't be any problems with jquery.inpumask perfomance:

<pre>
/^(([a-zA-Z]+|(%[1-1])|[_.-]|\s)\\?)*$/.test("sdfdsca\\sssssssssssssssssssssssssssssssssssssssssss\\ssssss1\\1\\1\\1\\1\\1\\11\\1\\1\\1\\1\\1\\")
</pre>

Some thoughts about V8 are here:
https://code.google.com/p/v8/issues/detail?id=2254

**Comment by RobinHerbots** [comment]
@potar , 

Thx for the info.

**Comment by potar** [comment]
@RobinHerbots ,

I fixed the performance problem by rewriting a regexp. The problem was connected to backtracking. The most useful tips and tricks I found in this book:
http://books.google.com.ua/books?id=ED6ph4WEIoQC&lpg=PA93&ots=2Vnc2J3ccE&dq=javascript%20regex%20atomic%20grouping&hl=uk&pg=PA89#v=onepage&q=javascript%20regex%20atomic%20grouping&f=false
