### ISSUE TITLE
Intergroup selection with editing leads to next input group(s) breakage

### ISSUE THREAD

**Issue by dhilt** [RobinHerbots/Inputmask#515]
The problem can be reproduced by this scenario:

 -- get field with mask 'dd/mm/yyy'
 -- input correct value (01/01/2014)
 -- select "1/2" of month and year
 -- type "6"
 -- enjoy broken year (01/06/10y4)

Try your demo http://robinherbots.github.io/jquery.inputmask/

![jquery inputmask intergroup selection with editing leads to last input group breakage](https://cloud.githubusercontent.com/assets/4365660/2880020/0f1954d6-d470-11e3-91c1-24df95a99b6a.png)

This works for all cases. For example IP-case:
 -- correct IP init (100.100.100.100)
 -- select "0.1" of first and second groups 
 -- type "9"
 -- get critical broken IP (109.001.001.00_) 
...while we would see such as 109._00.100.100 or 109.___.100.100 (but don't touch two last groups!)

Thanks!

**Comment by mfeingold** [comment]
Any idea on the ETA for this fix?

**Comment by RobinHerbots** [comment]
@dhilt, @mfeingold , 

I'm working on it.

**Comment by rbirkby** [comment]
Any chance broken tests could not get checked into git? Or get ignored in some way?

It's disconcerting to download the latest code from github and get 7 failing tests.

**Comment by RobinHerbots** [comment]
That is called test driven development ;-)

That are cases I know who fail, ... so when I solve the issue they will
pass and I can also verify for possible degression.

2014-05-08 13:40 GMT+02:00 Richard Birkby notifications@github.com:

**Comment by RobinHerbots** [comment]
For the date alias this is fixed.

**Comment by RobinHerbots** [comment]
@dhilt , 

I know it has been a while for this issues, but ;...

Would you expect that entering the 6 as described above will not be allowed as it would result in a broken year?

**Comment by dhilt** [comment]
@RobinHerbots I think that current behaviour that I see in the demo page is fine: correct change in the 1st group and minimal break in the 2nd one. This is really more useful than preventing a change at all in that case... Thanks!

**Comment by RobinHerbots** [comment]
@dhilt , 

Hmm, but it is actually wrong as the year is invalid at that point.  I would prevent the entry unless valid

**Comment by dhilt** [comment]
@RobinHerbots I guess it is not a fantastic scenario when the User really wants to change month and to corrupt year in the same time. Such kind of selection is pretty artificial I think, so it most likely that the User understands what he is doing... I'm trying to imagine. When the User does a selection through both of month and yaer groups it seems very reasonable that he wants to get changes there and there and he surely doesn't want to get nothing changed.

May be some kind of survey will be a good suggestion here) I vote for current behaviour
