### ISSUE TITLE
Space turn to 'r'

### ISSUE THREAD

**Issue by SilentImp** [RobinHerbots/Inputmask#516]
@name.inputmask("Regex", {regex: "[а-яА-Я\s]*"})
With such mask when i press space i get … "r". How may i fix it?

**Comment by DynaRowan** [comment]
Not sure if this intended, but a workaround I use: (only if you don't use the option skipOptionalPartCharacter)
@name.inputmask("Regex", { "regex": "[а-яА-Я\s]*", "skipOptionalPartCharacter": "" });

**Comment by RobinHerbots** [comment]
@SilentImp , @DynaRowan , 

I already fixed the issue, but it is not published to github yet,
