### ISSUE TITLE
JQuery dependency

### ISSUE THREAD

**Issue by mfeingold** [RobinHerbots/Inputmask#517]
How difficult would it be to refactor the code so that the JQuery dependency is separated out into some sort of adapter. Once it is done another adapter can be created to make inputmask into an angular directive without dependency on JQuery

**Comment by RobinHerbots** [comment]
@mfeingold, 

Can you motivate a bit why you would remove the jQuery dependency.
Anyway, it can be done.

**Comment by mfeingold** [comment]
The motivation - sure. I (as well as many others) use [angular](https://angularjs.org/) in all my frontend development. It is very powerful and its popularity grows fast. Angular itself does not relay on JQuery for anything, so you do not need to include it in your project - unless you need to use some advanced components (i.e. inputmask). 

In my case inputmask is the only reason I need JQuery, which means that majority of the code JQuery brings along is not used and just sits there consuming resources.

Angular has its own implementation of the subset of JQuery core functionality called JQLite [you can check it here](https://docs.angularjs.org/api/ng/function/angular.element). The API of whatever is implemented as a part of JQLite is fully compatible with corresponding JQuery stuff. Moreover if JQuery is loaded, angular falls back on the JQuery implementation, but if the JQuery is not loaded and the component relays on something which is not a part of JQLite - you are SOL.

I ran into this problem working on my [ng-scroller](https://github.com/Hill30/NGScroller) directive. To eliminate JQuery dependency I had to port from JQuery implementation for a few methods (i.e. before and offset). I would like to do the same for the inputmask component - so that it can be wrapped up as an angular directive. I just think that the efficient way of doing it would be to implement it in a separate adapter, so that the developers using it over JQuery would not be affected

**Comment by JCMais** [comment]
@RobinHerbots Also, this will add the option for Node.js developers to use the library for validation purposes.

**Comment by RobinHerbots** [comment]
@mfeingold,  @JCMais, 

Ok, good idea.  But I first need to fix some issues and further stabilize the 3.x version.
This will be for the next milestone.  

best regards, 
Robin

**Comment by mfeingold** [comment]
Any ETA on this?. It looks like we are at the point where it would really help us. And just to remind you - once we have this separation we can take care of the Angular part

**Comment by RobinHerbots** [comment]
@mfeingold , 

Althought the dependencylib is stil a WIP, you can already see in it what is needed to support jqlite.

I already started the dependencyWrapper for jqlite.  See inputmask.dependencyLib.jqlite.js.

I guess the biggest todo is the namespaced events.  (I know I can workaround that in the inputmask code but I prefer to keep it and do a simple implementation in the dependencyLib)

**Comment by RobinHerbots** [comment]
@mfeingold , @JCMais , 

The vailla dependencyLib is fully working.   Is there someone working on jqLite?

**Comment by JCMais** [comment]
I'm not, but great work!

**Comment by mfeingold** [comment]
Looks great. I will have a look.

**Comment by artptr** [comment]
@RobinHerbots 
Today I tried to implement vanilla dependencyLib into my proprietary app module, but found that it's not work. Input behaved like without the Inputmask. There wasn't errors in the console. And a simple implementation on Plnkr works great, so I can't understand what's wrong with it. Now I use the jquery version, but I hope that the vanilla version will work for me too.

By the way, my module has system.js loader with babel transpiler, but I will move to a webpack-based builder. Maybe the problem caused by system.js, I haven't any idea. Maybe you can suggest something that could help me to find the problem?

**Comment by RobinHerbots** [comment]
@artptr , 

Can you give some code/config example.  That will make it easier to point to the problem.  I tested with requirejs.

**Comment by artptr** [comment]
@RobinHerbots ,
I'm sorry. I made a minimal example with the same architecture, but it works well. I think that there is a bug in my app.

**Comment by RobinHerbots** [comment]
@mfeingold , @JCMais , 

jqlite dependencylib is finished and working
