### ISSUE TITLE
Fixed number of decimal points

### ISSUE THREAD

**Issue by scottned** [RobinHerbots/Inputmask#519]
Is it possible to use the 'decimal' alias to ensure a fixed number of digits that are always visible.  For example, if I enter a "1" into a blank field, the output is "1.00"?  I'm trying to create a currency input and I'd like the output to always look something like $ 9,999.99

I've tried a few things and looked through the code, but haven't gotten it to work yet.

Here's a fiddle I was playing with:  http://jsfiddle.net/scottned/8Jpdd/4/

One other odd behavior I noticed:
1) Enter "12345"
2) Place your cursor between the 3 and 4 and press "."

**Comment by RobinHerbots** [comment]
@scottned ,

on http://jsfiddle.net/8Jpdd/9/  you see an example of the new numeric alias.
It is not yet finished and feature complete but it gives an idea

**Comment by scottned** [comment]
Thanks Robin.  That's great!  Only thing now is "autoGroup" seems to have stopped working.

**Comment by RobinHerbots** [comment]
I know, I am working on it

2014-05-09 1:17 GMT+02:00 Scott Nedderman notifications@github.com:

**Comment by RobinHerbots** [comment]
@scottned , 

Have a look at http://jsfiddle.net/8Jpdd/14/

Autogroup + 0 as placeholder
