### ISSUE TITLE
Remove not working with multiple masks

### ISSUE THREAD

**Issue by dcbrilho** [RobinHerbots/Inputmask#520]
Hi,
Remove function is not working when multiple masks are in use.
The control remains masked. Setting another mask doesn’t work, also.
All browsers, latest version, simple use.
Thanks!

**Comment by RobinHerbots** [comment]
I will have a look, ...

**Comment by david-crespo** [comment]
An illustration: keyup is supposed to remove mask for both, but it only works for the box with a single mask.

![inputmask-issue2](https://cloud.githubusercontent.com/assets/3612203/2965147/bc5434ba-daef-11e3-95ff-124370368d02.gif)

```
$('#x').inputmask("9999 9999 9999 9999");

$('#x').on("keyup", function (event) {
    $('#x').inputmask("remove");
});


$('#y').inputmask({ mask: ["9999 9999 9999 9999"] });

$('#y').on("keyup", function (event) {
    $('#y').inputmask("remove");
});
```

[JSFiddle](http://jsfiddle.net/z3KBA/3/)

**Comment by RobinHerbots** [comment]
@dcbrilho , 

The current implementation of multiple masks is just a temporary solution to be compatible with inputmask 2.x.

I'm working on the alternator syntax which will replace the current implementation.
