### ISSUE TITLE
Problem with S4 with kitkat 

### ISSUE THREAD

**Issue by mike-pun** [RobinHerbots/Inputmask#522]
We are having serious problems on a Samsung S4 with 4.4.

When we type 12 in the mm field, it jumps to 01/20xx, so we cannot input dates in the month of October, November and December.

There is also a problem when we backspace. It get stuck at the slash.

**Comment by mike-pun** [comment]
This problem is repeatable in the simulator. We are using a very simple mask of

$("#txx").inputmask("dd/mm/yyyy");

and this is happening. Does not happen in 4.3. Any ideas?

**Comment by RobinHerbots** [comment]
@mike-pun , 

Is this solved?  Or just closed?

**Comment by RobinHerbots** [comment]
see #465
