### ISSUE TITLE
Military time at "h:s t" mask. Jumping cursor problem

### ISSUE THREAD

**Issue by dhilt** [RobinHerbots/Inputmask#523]
Before all: in previous versions (2012) discussing behavoiur was correct!

The way to reproduce problem:
 1) take clear time-input masked as "h:s t" (hh:mm xm)
 2) type "15" at "hh" (you may type an hour from 13 to 24)
 3) get "03:mm pm" (this is very good)
 4) cursor position at the end of value (after "pm")

But in (4) we expected it's position to be at minutes (at first letter of "mm").

Here's fiddle working on actual plugin version: http://jsfiddle.net/dhilt/CYgHa/.
And here is somebody's stand of 2012 version: http://bseth99.github.io/projects/jquery-ui/5-jquery-masks.html (the 2nd field, Time).

Thanks!

**Comment by RobinHerbots** [comment]
@dhilt , 

Thx for reporting.

I will fix this asap

**Comment by dhilt** [comment]
i've done pull request to solve this problem, hope all is right
https://github.com/RobinHerbots/jquery.inputmask/pull/526

**Comment by RobinHerbots** [comment]
@dhilt, 

I had already fixed the issue but couldn't commit yet due to other issues.

Best regards, 

Robin

**Comment by RobinHerbots** [comment]
What do you mean?  This is already fixed.  Check it out on your jsfiddle

2014-07-09 10:44 GMT+02:00 d.alexanov notifications@github.com:

**Comment by dhilt** [comment]
sorry, i've looked at src and didn't understand it and didn't try it... all is perfect
i've killed my prev. comment but e-mail notification was sent, just ignore it please
and thanks at all!
