### ISSUE TITLE
Strange behavior when switching between masks

### ISSUE THREAD

**Issue by david-crespo** [RobinHerbots/Inputmask#525]
I am trying to use two masks, one for American Express credit cards (9999 999999 99999) and one for everything else (9999 9999 9999 9999). 

I almost have it, but I'm having a strange problem: as you can see below, when I type 37 the mask switches properly to the Amex one. However, when I erase the 7 and change it to an 8 to make the mask switch back, the 3 disappears.

Am I doing something wrong? Thanks for the help.

![inputmask-issue](https://cloud.githubusercontent.com/assets/3612203/2964446/8f7bbfd4-dae6-11e3-879c-72188d87e412.gif)

[JSFiddle](http://jsfiddle.net/s2QGh/)

```
$.extend($.inputmask.defaults.definitions, {
    'a': {  // matches 37 and 34, amex prefixes
        "validator": "3(4|7)",
        "cardinality": 2,
        'prevalidator': [{ validator: "3", cardinality: 1 }]
    },
    'o': {  // matches two-digit number except 34 and 37
        "validator": function (chrs, buffer, pos, strict, opts) {
            return /\d\d/.test(chrs) && chrs != "34" && chrs != "37";
        },
        "cardinality": 2,
        'prevalidator': null
    }
});

$('#x').inputmask({
    mask: ["o99 9999 9999 9999", "a99 999999 99999"]
});
```

**Comment by JCMais** [comment]
Off topic message: @david-crespo what you used to make this gif?

**Comment by david-crespo** [comment]
[LICEcap](http://www.cockos.com/licecap/)

A coworker showed it to me and I was immediately addicted. It is incredible.

**Comment by RobinHerbots** [comment]
@david-crespo , 

Yes the demo with LICEcap is cool ;-)

The current implementation of multiple masks in version 3.x is a bit crappy.  I need to take some time to fix and stabilize.

Anyway the switching is based on the implementation of determineActiveMask function.  This can be overridden by your own logic by implementing determineActiveMasksetIndex in the options.
(I need to update the documentation)

**Comment by david-crespo** [comment]
Thanks! I'll take a look there.

**Comment by Doopin** [comment]
Now possible. 
Consider your field has this ID #cc

`$("#cc").on("input", function() {
      var value = $("#cc").val().replace(/\D/g, '');
      var mask;
      if ((/^3[47]\d{0,13}$/).test(value)) { // American Express
           mask = '9999 999999 99999'
      } else if ((/^3(?:0[0-5]|[68]\d)\d{0,11}$/).test(value)) { // Diner's Club
           mask = '9999 999999 9999'
      } else if ((/^\d{0,16}$/).test(value)) { // Other Credit Cards
           mask = '9999 9999 9999 9999'
      } else {
           mask = 'remove'
  }
  
  if($('#cc').attr('data-currentmask') != mask) {
          $('#cc').attr('data-currentmask', mask);
          $('#cc').inputmask(mask, { placeholder: '' });
   }
});`

I found this solution [here](https://medium.com/hootsuite-engineering/a-comprehensive-guide-to-validating-and-formatting-credit-cards-b9fa63ec7863)
