### ISSUE TITLE
Cannot delete chars on Android 4.4.2

### ISSUE THREAD

**Issue by jblandry** [RobinHerbots/Inputmask#528]
On Chrome-Android 4.4.2 (Nexus 4).

I cannot delete my chars once I've written something.

ex: http://absolunet.com/en/contact-us/contact-form (Phone field)
I know it's an old version but I tried with the latest version and I've got the same problem.

**Comment by RobinHerbots** [comment]
see #465

**Comment by jblandry** [comment]
Still doesn't delete chars correctly with '(999) 999-9999 [ext: 99999]' pattern :(

**Comment by RobinHerbots** [comment]
@jblandry , 

I know, but keeping all the android issues open makes no sense as the keypress events and backspace and others don't fire and thus the plugin is unaware of the input.  In issue #465 you find more information.
