### ISSUE TITLE
inputmask does not work with WatiN

### ISSUE THREAD

**Issue by vtortola** [RobinHerbots/Inputmask#53]
Hi,

I'm using WatiN ( http://watin.org/ ) to test the UI, but when the test runs the mask does not appears.

Any idea why?

Thanks!

**Comment by RobinHerbots** [comment]
Hi, 

Can you try it with following function in jquery.inputmask.js changed to this

function clearOptionalTail(input, buffer) {  }

Is it possible to send me a little demo sln, so I can test it.

best regards, 

Robin

**Comment by vtortola** [comment]
Hi,

I don't understand what do you want me to do with the "clearOptional" function, how should I call it?

I have created a solution at vtortola.net/files/jQueryInputMaskAndWatiN.zip.

It shows two problems:

**MaskAndWatiNProblem.html**: Has a simple page with an INPUT and a inputmask. When you run the console application, it uses WatiN to test it. But when WatiN type on the input, the mask disappears, so it cannot be tested properly.

**KnockOutAndInputMaskProblem.html**: Contains a simple KnockOutJs template that is bound to a simple object with a date, but when I apply the inputmask "dd/mm/yyyy" to the control, the INPUT value looks totally wrong. If I apply the inputmask "99/99/9999" it works as expected. KnockOutJs is being shipped with MVC 4 as the preferred framework for SPA (Single Page Applications), probably you already know :D

Thanks!

**Comment by RobinHerbots** [comment]
Hi, 

For the KnockOut... html, ... you use dd/mm/yyyy as a mask, but should have called it like an alias

$('#myDateTest').inputmask({ "mask": "dd/mm/yyyy", 'autoUnmask': false, clearMaskOnLostFocus: false });

=> $('#myDateTest').inputmask("dd/mm/yyyy", { 'autoUnmask': false, clearMaskOnLostFocus: false });
or (if you use the latest in the dev branch)
$('#myDateTest').inputmask({ "alias": "dd/mm/yyyy", 'autoUnmask': false, clearMaskOnLostFocus: false });

For Watin.

Probably the way watin types it's text.  When I find some time I will check it in the source of watin (or watir)

**Comment by vtortola** [comment]
Oh I see, it works now, thanks.

I hope that it is possible to use WatiN and inputmask :) I will try to find out the source of the problem as well.

I have opened a bug in WatiN to see if they can show some light here: https://sourceforge.net/tracker/?func=detail&aid=3529778&group_id=167632&atid=843727

cheers.

**Comment by RobinHerbots** [comment]
Hi, 

Can you test the your code with say Firefox instead of IE.

Which version of IE do you use.  I think the CreateJavaScriptFireEventCode in  IEFireEventHandler.cs should be changed according the version used of IE.  

Robin

**Comment by RobinHerbots** [comment]
I did some further testing and in the keydown keypress event the args e.which || e.charCode || e.keyCode always return 0, ... I also tried with some patching in de watin code.

in IEFireEventHandler

 private string CreateJavaScriptFireEventCode(NameValueCollection eventObjectProperties, string eventName)
        {
            var scriptCode = new StringBuilder();
            var window = _ieElement.ParentWindow;
            if (IE.GetMajorIEVersion() > 8 && eventName.ToLower().Contains("key"))
            {
                scriptCode.Append("var newEvt = document.createEvent('KeyboardEvent');");

```
            //init keyboardevent
            scriptCode.AppendFormat("newEvt.initKeyboardEvent('{0}',true, true, null, false, false, false, false, null, {1});", eventName.ToLower().Replace("on", ""), eventObjectProperties.GetValues(0)[0]);

            var reference = _ieElement.GetJavaScriptElementReference();
            scriptCode.AppendFormat("{0}.dispatchEvent(newEvt);", reference);
        }
        else
        {
            scriptCode.Append("var newEvt = document.createEventObject();");
            CreateJavaScriptEventObject(scriptCode, eventObjectProperties);

            var reference = _ieElement.GetJavaScriptElementReference();
            scriptCode.Append(string.Format("{0}.fireEvent('{1}', newEvt);", reference, eventName));
        }

        return scriptCode.ToString();
    }
```

**Comment by evanlarsen** [comment]
Is there a way I could use knockoutjs with your pluggin and also have the options of 'autoUnmask': true, clearMaskOnLostFocus: true?

For some reason, if I have these set to true with knockoutjs also binding to the same fields then when I mouse over the fields it will clear the input values along w/ the mask.

**Comment by RobinHerbots** [comment]
Hi Evan,

Can you send an sample so I can verify the issue.

Best regards,

Robin

2012/6/11 evanlarsen <
reply@reply.github.com

**Comment by RobinHerbots** [comment]
Hi Evan, 

I opened a new issue for this. (63).

Can you explan your problem a bit more. How did you bind ? data-bind: value?

**Comment by evanlarsen** [comment]
sorry for the delay, I'll provide an example tonight.
