### ISSUE TITLE
Difficulties when setting masked fields with Watir

### ISSUE THREAD

**Issue by ashtony42** [RobinHerbots/Inputmask#530]
I'm using Watir Classic 3.7.0 on Ruby 1.9.3 in attempt to enter fields that have been recently masked. Many of the build in methods are not co-operating very well, so I'm working on finding other solutions.

Is there a way to inject javascript that may temporarily disable the masking feature to allow a field to be entered? Alternatively, is there a script that could be injected to achieve this that might be friendly with the input masking code?

the closest success I have is the simple:
`$("#id").value = "new value!";`

however, this usually results in the field clearing itself when focused again.

**Comment by RobinHerbots** [comment]
@ashtony42 , 

Is using jQuery.val not an option for setting the value?
Otherwise try setting the value as you do above and trigger the setvalue event

**Comment by ashtony42** [comment]
I didn't have success calling val or setvalue, but after a while I've come up with another solution as wacky as it may be.

After you set the field like above with the `.value =` , follow it up by calling the onpaste event for the field.

my final solution is a bit like this:
`element.value = '1231231234'
    element.fire_event('onpaste')`

**Comment by RobinHerbots** [comment]
@ashtony42 , 

Normally the setvalue should also work.  Another option is to use the type and  sendkey from the simulator.js found in the qunit directory

**Comment by ashtony42** [comment]
I attempted the sendkey solution as well, and at first it seemed to have miraculously worked. The extra dilemma I have with it though is that it also needs to work on a machine while the user is locked, at which point sendkeys would error out on me. :^/
