### ISSUE TITLE
onincomplete with multiple mask

### ISSUE THREAD

**Issue by satsyuk** [RobinHerbots/Inputmask#532]
$("#input").inputmask({ "mask": ["999.999", "aa-aa-aa"],
            'onincomplete': function() { alert("input incomplete"); }
Input comptele but onincomplete running

**Comment by RobinHerbots** [comment]
@satsyuk , 

Multiple masks aren't stable yet on the 3.x branch. (better use 2.5.10)

I will have a look.

**Comment by RobinHerbots** [comment]
replaced by alternators
