### ISSUE TITLE
Cursor Auto positioning

### ISSUE THREAD

**Issue by solenoo** [RobinHerbots/Inputmask#535]
How can I make my cursor to stop auto position itself on the first empty space, instead I want to make it like on the demo page to be able to freely move it left and right.

**Comment by RobinHerbots** [comment]
@solenoo , 

Can you make an example on jsfiddle

**Comment by solenoo** [comment]
I was able to find my mistake, sorry for disturbing you :)

**Comment by RobinHerbots** [comment]
@solenoo , 

No problem, always feel free if you have any questions.

best regards, 

Robin
