### ISSUE TITLE
Triggering incomplete function

### ISSUE THREAD

**Issue by solenoo** [RobinHerbots/Inputmask#536]
I have this boolean that is set to false by default, and I set it to true on complete and false on incomplete. When I complete a mask and start deleting what I've just typed the incomplete function is not triggered, how can I trigger it.

**Comment by RobinHerbots** [comment]
The incomplete only triggers on blur

2014-05-22 17:23 GMT+02:00 solenoo notifications@github.com:

**Comment by RobinHerbots** [comment]
Use the onKeyValidatiin
