### ISSUE TITLE
clearIncomplete error

### ISSUE THREAD

**Issue by nnnx** [RobinHerbots/Inputmask#537]
when i use this options:

```
$.extend($.inputmask.defaults, {
    autoUnmask: false,
    clearIncomplete: true
});
```

when the focus of the field and type some chars (not complete field) i do submit form and getting $.val() - have error:
![err1](https://cloud.githubusercontent.com/assets/7686446/3073811/cd1ed0b4-e30c-11e3-82eb-c528f6f59469.png)

**Comment by RobinHerbots** [comment]
@serious-andy, 

Can you make a jsfiddle to simulate the problem.

**Comment by nnnx** [comment]
@RobinHerbots

http://jsfiddle.net/hBX9f/4/

errors in opera, firefox

**Comment by RobinHerbots** [comment]
http://jsfiddle.net/hBX9f/5/
