### ISSUE TITLE
License Agreement

### ISSUE THREAD

**Issue by landondurnan** [RobinHerbots/Inputmask#54]
Wasn't sure how else to contact you.  I wanted to know if you're considering a license for this plugin?

**Comment by RobinHerbots** [comment]
Hi Landon,

I mentioned the MIT - license in the js-files.

Should I include a seperate license file? Or maybe I should include it in
the readme.  Any advice is welcome!

best regards,

Robin

2012/5/23 Landon Durnan <
reply@reply.github.com

**Comment by landondurnan** [comment]
Ah, you're right!  I didn't think about looking at the original source as I did the Google compile and it removed those comments.   The only suggestion I could think is to mention the license in the README, otherwise, awesome work.
