### ISSUE TITLE
auto grouping and limiting integerDigits in 3.x

### ISSUE THREAD

**Issue by gigermocas** [RobinHerbots/Inputmask#540]
There appears to be some problems with auto grouping (numeric) while limiting the number of integerDigits in 3.x:

The value "123456789" is formatted as "1,234,567", using alias "integer".
The same value is formatted as "1,234,567.9", using the alias "decimal".

Both results should be "123,456,789"

The options used were:
groupSeparator: ","
autoGroup: true,
integerDigits: 9

http://jsfiddle.net/Gzb6L/

The same fiddle works fine in the previous 2.x branch;

**Comment by RobinHerbots** [comment]
@gigermocas , 

Indeed the nex 3.x does not exclude the groupseparators in the count for integersdigits.

I will fix that.

**Comment by RobinHerbots** [comment]
@gigermocas , 

Fixed
