### ISSUE TITLE
Error when used with frameworks that extend array prototype

### ISSUE THREAD

**Issue by ardennis** [RobinHerbots/Inputmask#541]
Hi Robin,

I'm getting an error when using the plugin with a framework, such as Ember.js, that extends the array prototype.  It looks like this is due to the use of for...in loops to iterate over arrays.  The problem being that this iterates through all properties of the object, including non-enumerable prototype additions.

Here's a fiddle demonstrating the problem:  http://jsfiddle.net/Ymash/

**Comment by RobinHerbots** [comment]
@ardennis , 

fixed in version 3.0.31
