### ISSUE TITLE
Don't work for Android 4.4 Google Chrome browser

### ISSUE THREAD

**Issue by subtronic** [RobinHerbots/Inputmask#542]
Hello.
When i try fill input (mask looks like -  `+7 (999) 999 99 99`), i can fill any word.
Example, i can fill this field some thing like than - `+7 (fdsfsdf2352523523523523)`, and after field blur input just formatted to `+7 (235) 235 23 52`.

It's happend, becouse KeyUp event don't return to callback valid object. This object have e.keyCode = 0.

**Comment by subtronic** [comment]
I found a problem.
Problem with my keyboard - flesky.
With Google keyboard all works fine.

**Comment by RobinHerbots** [comment]
see issue #465
