### ISSUE TITLE
Multiple inputs..

### ISSUE THREAD

**Issue by gjdevlin** [RobinHerbots/Inputmask#544]
Is it possible to have an input mask where I can enter dates on a long field like this:

mm/dd/yyyy;mm/dd/yyyy;mm/dd/yyyy

So far I've tried something like this:

 $('.screeningdates').inputmask({
        mask: ["99/99/9999", "99/99/9999", "99/99/9999","99/99/9999"]
    });

**Comment by RobinHerbots** [comment]
@gjdevlin, 

Try something like 

$(".screeningdates").inputmask({ alias: "mm/dd/yyyy", mask: "(1/2/y - ){3}1/2/y", placeholder: "_" });

best regards, 

Robin

**Comment by gjdevlin** [comment]
Robin - I know this is closed but I have a simple textboxfor in MVC and tried to implement the following:

$("#SCREENING_DATES").inputmask("Regex", {regex: "([0-9][0-9]/[0-9][0-9]/[0-9]{4}[ ;]+)*"});

on the textbox - all I got was "Regex"? Any tips for MVC use? Am I missing something?

**Comment by RobinHerbots** [comment]
Did you include the regex extension in the bundleconfig? Did you use the nuget package?

**Comment by gjdevlin** [comment]
Robin - you can close this! :-) I included it this morning after reading your post. I was thinking about this on Friday when I left for home but I thought that the original file daisy chained up to the extensions but I guess you have to include them. Thanks!
