### ISSUE TITLE
Date extension: Invalid date with CTRL-right on some one digit days

### ISSUE THREAD

**Issue by friskm** [RobinHerbots/Inputmask#545]
Hi,

Seems that if with date mask "yyyy-mm-dd" I do CTRL-right on date 2014-06-02 (2nd June), the mask is filled 2014-06-2d (missing zero before 2) leaving the date incomplete.

Additionally, oncomplete does not to get triggered even after CTRL-right gives a valid date. Shouldn't it get triggered at least after leaving the control?

**Comment by RobinHerbots** [comment]
@friskm, 

I will have a look at both issues.

**Comment by samiraguiar** [comment]
Any news on this?
This also happens with datetime. In that case, it reuses the [`onKeyDown`](https://github.com/RobinHerbots/Inputmask/blob/690ba66a3778701a4a978193b79b42e1163c155b/js/inputmask.date.extensions.js#L122) function from the date mask, resulting in an invalid format (e.g.: `09/09/2016 hh:mm:ss`).

Is the right fix to just reimplement this function for each different datetime format?
BTW, I could help on this.

**Comment by RobinHerbots** [comment]
@samiraguiar , 

The initial idea was/is to rewrite the whole date mask, ... but there are so many other issues to fix, ...

Reimplementing the function for the different masks can solve this.  So, if you want to help on this, you are welcome..

Fix it, write a small unittest and submit a PR.  Even just writing unittest for different masks would be very helpfull.  For example to finally support android.  I need a unittest for every case where it fails. If you want more info let me know.
