### ISSUE TITLE
Disable replacement and buffer in when using numeric mask

### ISSUE THREAD

**Issue by SimenB** [RobinHerbots/Inputmask#547]
Hi!

I asked a question on SO, but haven't gotten an answer. Could someone here maybe shed some light on it?

http://stackoverflow.com/questions/24031515/how-to-disable-replacement-and-buffer-in-jquery-inputmask

**Comment by RobinHerbots** [comment]
@SimenB , 

I will have a look

Copy from SO

We have an input-field with a maxlength attribute. In this field, we only want to accept numbers, so we added jQuery.inputmask. (Must be IE8 compatible, so no type="number"). https://github.com/RobinHerbots/jquery.inputmask

See Fiddle: http://jsfiddle.net/QdLBT/

The problem(s): When entering text, and then using backspace, any text that "overflowed" will come back.

In addition, having the cursor in the middle of the input'ed text, and entering new numbers will replace the numbers already there (like having insert enabled on the keyboard).

This behavior was not there using inputmask v1.2.2, but is present using the latest v3.x branch. In v1.2.2 the mask respected the maxlength, i.e. just filtering out all that's not a number

**Comment by RobinHerbots** [comment]
@SimenB , 

Fixed in the latest version.

**Comment by SimenB** [comment]
Wow, that was fixed incredibly fast. Thank you!
