### ISSUE TITLE
phone mask error

### ISSUE THREAD

**Issue by tenq** [RobinHerbots/Inputmask#549]
Hi, I want to use:

$('#test').inputmask('(99) 9999[9]-9999');

for this entry: 29999679867  -> (29) 99967-9867

But, last number not appear, see:

![jquery inputmask-error](https://cloud.githubusercontent.com/assets/5042499/3278498/91568470-f3c2-11e3-9705-a4aed389dc9e.png)

Not permit write last number... how I get this work?

sds

**Comment by RobinHerbots** [comment]
@tenq , 

Can you make a jsfiddle for an example as I don't have a problem here.

best regards, 

Robin

**Comment by tenq** [comment]
Ok, see:

http://jsfiddle.net/tenq/55B88/

in Brazil, some places have 8 digits on cell phone, anothes has 9 digits... with Masked input and meio mask, using this:
http://pedroelsner.com/2012/07/mascara-jquery-para-novo-digito-de-celular-em-sao-paulo/

thanks for help

**Comment by spacelab-sp** [comment]
Use multiple masks (you need a extra js jquery.inputmask-multi.js):

$('#test').inputmask({mask:['(99) 9999-9999', '(99) 99999-9999']});

**Comment by tenq** [comment]
thanks, but optional masks have a sintax: 

$('#test').inputmask('(99) 9999[9]-9999');

Does not run?

**Comment by RobinHerbots** [comment]
@tenq , 

See at this http://jsfiddle.net/cU6DP/2/

That will make things more clear when you try the examples.  Type exactly as described.

best regards, 
Robin

**Comment by tenq** [comment]
Ok, sorry for complicated inputs, rs

using version 3.0.36, works perfect!

Thanks a lot!

**Comment by penihel** [comment]
View http://jsfiddle.net/8wjsscj0/

I have a error when set the value of input.

i have a observable (ko) with "(12) 1234-1234" value

Set set to input, but the result is "(12) 12341-234_"

I expected "(12) 1234-1234"

Could understand the problem?
