### ISSUE TITLE
Focus event being triggered when applying mask to the fields

### ISSUE THREAD

**Issue by jonhkr** [RobinHerbots/Inputmask#551]
Hi,
I found an estrange behavior when using inputmask plugin, when I apply the mask to one field a focus event is triggered and the cursor appears in the field.

This is bad because sometimes the focus goes to the last field of the form.

Is there any option to remove this behavior or is it a bug?

**Comment by RobinHerbots** [comment]
@jonhkr , 

Which version do you use?

**Comment by RobinHerbots** [comment]
@jonhkr , 

Which browser do you use??  Is this related to #553 ?

**Comment by jonhkr** [comment]
I'm using version `3.0.10`
It is not a browser specific problem, currently I'm testing on chrome and firefox.

**Comment by jonhkr** [comment]
To simulate the problem you can create a form with many fields and apply `inputmask` to some random fields. I do this using css classes.
Depending on the order the mask is applied the focus will be set to the fields, say the last mask set is on the last field, the focus will be in that field as well.

**Comment by RobinHerbots** [comment]
@jonhkr , 

Can you retry with the latest version.  current is 3.0.45

**Comment by RobinHerbots** [comment]
@jonhkr ,

Can you retry with the latest version.
