### ISSUE TITLE
IE 11 not allowing focus to leave input text field

### ISSUE THREAD

**Issue by Aragorn450** [RobinHerbots/Inputmask#553]
I'm seeing a problem with IE 11 where if you have an input field with a mask and click in there, you are not able to click out of it again without entering **something** into the input box. You can see http://jsfiddle.net/Aragorn450/Wmg3Z/ for an example.

I think that the problem code was submitted on Jan 14, 2014 in commit https://github.com/RobinHerbots/jquery.inputmask/commit/bd37f36075c112c7822aabc772371ff92b83edb7

In this commit, a section was added to [line 877](https://github.com/RobinHerbots/jquery.inputmask/commit/bd37f36075c112c7822aabc772371ff92b83edb7#diff-4121f1d590eb81455f5a4711e574b57dR877) of jquery.inputmask.js:

```
if (msie1x)
    $el.bind("input.inputmask", pasteEvent);
```

What those two lines are doing is when focus is given to a field with a mask (for instance, #ie_danger in this example), trying to click outside that field before filling it out (#options, or anywhere else for that matter) doesn't work while using IE 11. Focus is instead given back to #ie_danger and there is no way to move off of that field.

If even a single character of valid input is entered into the field, then the user is able to move to another field. This is completely different than the behavior of both Chrome and Firefox. Both of them allow the user to click onto another field as needed and do not hinder the input process.

As a test, I have created another fiddle at http://jsfiddle.net/Aragorn450/AgG7g/ This one uses a modified version of the jquery.inputmask.js file which removes the two lines in question. From my testing, this solves the problem and it functions correctly for IE 11.

So, what's going on? And what's the purpose of those two lines? And can they be removed?

**Comment by RobinHerbots** [comment]
@Aragorn450, 

Those 2 lines are used to handle the ms-clear.  Besides an input event there is no other way to detect a click on the X.

I will have a look at it.

**Comment by Aragorn450** [comment]
What I'm especially confused about is that this hasn't been reported before since it seems to be an easy problem to replicate. When I tried to replicate it in jsfiddle, I fully expected to not be able to since we do a lot of crazy stuff on our site...

Anyway, the problem here is that because of that extra bind, the pasteEvent function is being called every time the field goes out of focus. That pasteEvent function does a setTimeout and in that, it does a click on the field. Which then brings the focus back to it again. So it could also be fixed by not doing the click...

**Comment by RobinHerbots** [comment]
@Aragorn450 , 

Can you just do a test.  Can you retry your fiddle without the html placeholder.  I'm just curious what triggers the input event. (and I don't have IE11 available for the moment)

**Comment by RobinHerbots** [comment]
@Aragorn450 , 
Fixed in the latest version.
http://jsfiddle.net/Wmg3Z/13/

Seems that IE11 when using an html placeholder triggers the input event.

**Comment by Aragorn450** [comment]
Yeah, that looks good to me now. Sorry for the late response...

By the way, you can always go to https://modern.ie/ for Virtual Machines of Windows from Microsoft. They have pretty much every Windows/IE version combination possible and have VM files that run in Hyper-V, Virtual PC, VirtualBox (Win/Mac/Linux), VMWare (Win/Mac) and Parallels (Mac).

Or there's http://www.browserstack.com/ too. Which, from https://modern.ie/ you can get a 3-month free trial for that too.
