### ISSUE TITLE
OnBeforePaste happens right after the actual paste

### ISSUE THREAD

**Issue by SimenB** [RobinHerbots/Inputmask#554]
EDIT: Just figured out that the mask strips whitespazce on it's own, of course. The problem still stands, though

Hi again!

When pasting into a field, there's a timeout with 0 (probably an IE8-hack). This means that the browser has already stripped out the extra input at the end of the text, if a maxlength is defined.
https://github.com/RobinHerbots/jquery.inputmask/blob/3.x/dist/jquery.inputmask.bundle.js#L1223

``` javascript
function pasteEvent(e) {
    if (skipInputEvent === true && e.type == "input") {
        skipInputEvent = false;
        return true;
    }

    var input = this, $input = $(input);
    //paste event for IE8 and lower I guess ;-)
    if (e.type == "propertychange" && input._valueGet().length <= getMaskLength()) {
        return true;
    }
    setTimeout(function () {
        var pasteValue = $.isFunction(opts.onBeforePaste) ? opts.onBeforePaste.call(input, input._valueGet(), opts) : input._valueGet();
        checkVal(input, true, false, pasteValue.split(''), true);
        if (isComplete(getBuffer()) === true)
            $input.trigger("complete");
        $input.click();
    }, 0);
}
```

Is there some way to enforce a maxlength of an input-field using inputmask instead of native HTML?
If not, is there some way to apply the mask before it's pasted into the field?
JSFiddle: http://jsfiddle.net/HK2X9/2/

When pasting e.g. 'h j123 hj  h456 ', I want the end-result to be '12345'. Kind of extreme example, but yeah.

**Comment by RobinHerbots** [comment]
@SimenB , 

Fixed in the latest version

**Comment by SimenB** [comment]
Again, incredibly fast fix. Thank you!
