### ISSUE TITLE
Phone mask using phone-codes and TAB

### ISSUE THREAD

**Issue by vblain** [RobinHerbots/Inputmask#556]
Hi Robin,

first of all great work on this, you saved hours of work. On to the issue I have found.

When using the phone-codes to create a phone mask I'm unable to tab out of the field. When tabbing in the mask will also add random numbers.

I tried creating a jsFiddle http://jsfiddle.net/DLuza/ but I can't seem to get the phone-codes.json to load preventing input.

Any help would be appriciated.

Vince

**Comment by RobinHerbots** [comment]
@vbs1 , 

In the current implementation of multiple masks you need to include jquery.inputmask-multi.js

http://jsfiddle.net/DLuza/1/

Anyway, that will change in the future and there are still issues with multiple masks in the 3.x branch

**Comment by RobinHerbots** [comment]
@vbs1 , 

The multi masks are replaced by the alternator.
