### ISSUE TITLE
Class removes equals sign problem when submit a page.

### ISSUE THREAD

**Issue by lveeramani** [RobinHerbots/Inputmask#557]

**Comment by RobinHerbots** [comment]
@lveeramani , 

Can you explain a bit more what the problem is.  An example?

**Comment by lveeramani** [comment]
I have validate the US phone number with input mask. When it will failure i will add class error in that control. Its working fine in firebox. In chrome when i try to add with your existing class 'focus.inputmask' to 'focus.inputmask error' the "class=" removes. It will show only "class" in the attribute. So i cannot able to add the error class.

**Comment by RobinHerbots** [comment]
@lveeramani , 

Can you provide a code example. or even better a jsfiddle.

**Comment by lveeramani** [comment]
function WebForm_OnSubmit() {  
        if (typeof (ValidatorOnSubmit) == "function" && ValidatorOnSubmit() == false) {
            for (var i in Page_Validators) {              

```
            try {
                var control = document.getElementById(Page_Validators[i].controltovalidate);
                if (control.className != null) {
                    control.className = control.className.replace("error", "");
                }

                if (!Page_Validators[i].isvalid) {                   
                    if (control.className != null) {                                                                          
                        control.className = control.className + " error";                            
                    }
                    else {
                        control.className = "error";
                    }
                }
            } catch (e) { }
        }
        return false;
    }
    return true;
}
```

**Comment by RobinHerbots** [comment]
@lveeramani , 

Can you retry with the latest version.
