### ISSUE TITLE
Retrieving Phone Number from Database

### ISSUE THREAD

**Issue by himadriganguly** [RobinHerbots/Inputmask#558]
I am using this plugin with Rails and when in view the phone number is displayed from the database it is converting 9 to _.

Please help.

**Comment by RobinHerbots** [comment]
Hi Himadri,

Can you provide some example phonenumbers and the options you are using for
the inputmask.

best regards,

Robin

2014-06-27 21:20 GMT+02:00 Himadri Ganguly (nickname - Joy) <
notifications@github.com>:

**Comment by himadriganguly** [comment]
Hi Robin!

Here is my code https://gist.github.com/himadriganguly/86b3ca983458466996c5

And some example phone number is (+91)-9804120099 only the first 9 i.e after (+91)- is converted to _ but the last 99 is as it is.

Thanks.

**Comment by RobinHerbots** [comment]
@himadriganguly, 

Have a look at http://jsfiddle.net/tju9L/

Which version do you use?

**Comment by himadriganguly** [comment]
Hi Robin!

Thanks a lot for the help.

Changed the code and now it is solved. And here it is   

//Indian Mobile Number Inputmask
$("input.mobile").inputmask("(+\91)-99999-99999"); 
v = $("input.mobile").attr('value');
$("input.mobile").val(v);
