### ISSUE TITLE
Strange behavior on mouseenter event removes data type

### ISSUE THREAD

**Issue by lucianacampello** [RobinHerbots/Inputmask#559]
Hi. 
After entering the date, left the field and move the mouse over the date field is cleared.
I did debug and this behavior happens on the mouseenter event.

**Comment by RobinHerbots** [comment]
Can you make a jsfiddle or provide some example code of the inputmask you are using.

Which version do you use of the inputmask?

**Comment by ingro** [comment]
I noticed this behaviour too with Chrome, works fine on Firefox. If I comment the bindings "mouseenter.inputmask" and "mouseleave.inputmask" everything works fine.

**Comment by RobinHerbots** [comment]
Can you provide a bit more informstion. How do you set the value? Or what do you do exactly?

**Comment by lucianacampello** [comment]
I have a component for date and i had to change the jquey.inputmask on mouseenter to works. 
see part of my code here: http://notepad.cc/share/acHO2132pL

**Comment by RobinHerbots** [comment]
@lucianacampello , @ingro , 

The problem is that the inputmask isn't aware of the value change when setting value through the value property.

In firefox this works because FF allows for patching the native value property while chrome and others don't.

The best way to set the value is by using the jquery.val fn or if you want the use the native value then you have to trigger a setvalue event on the inputfield.

Anyway I will try to find a better solution for detecting the change so that the inputmask can pick the value up.

**Comment by ingro** [comment]
Thank you @RobinHerbots, I will try to use jquery.val and see if it fixes my problem.

**Comment by RobinHerbots** [comment]
@lucianacampello , @ingro , 

I added a fallback, which does not work 100% as I would want, but at least the value isn't cleared anymore.

Have a try ;-)  In FF all perfect, in chrome and IE the fallback.  Best solution is to always use jquery to set the value which should work in all cases

**Comment by lucianacampello** [comment]
Thank you :D

2014-08-04 6:48 GMT-03:00 Robin Herbots notifications@github.com:

> @lucianacampello https://github.com/lucianacampello , @ingro
> https://github.com/ingro ,
> 
> I added a fallback, which does not work 100% as I should want, but at
> least the value isn't cleared anymore.
> 
> Have a try ;-) In FF all perfect, in chrome and IE the fallback. Best
> solution is to always use jquery to set the value which should work in all
> cases
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/RobinHerbots/jquery.inputmask/issues/559#issuecomment-51038552
> .

## 

Luciana Campello
@IFPE: Graduando em Análise e Desenvolvimento de Sistemas - 6º Período
Contatos:
- skype: luciana.campello
- telefones: +55 81 86497279(oi)
                          30335771
