### ISSUE TITLE
IDE Syntax Error

### ISSUE THREAD

**Issue by Pezhvak** [RobinHerbots/Inputmask#560]
I use your bundle (jquery.inputmask.bundle.js) and PHPStrom seems to have problem with part of your code.
![screenshot 2014-06-28 20 07 48](https://cloud.githubusercontent.com/assets/3134479/3421143/3fb87b50-feda-11e3-86ef-56354682a816.png)

it's very annoying because entire folder structure gets red because of that.

**Comment by RobinHerbots** [comment]
@Pezhvak , 

And do you happen to know why it has a problem?  I guess because the focus.inputmask is not a valid classname.

**Comment by RobinHerbots** [comment]
@Pezhvak , 

Can you retry with the latest version.

**Comment by Pezhvak** [comment]
problem solved!
one other thing, everytime i update your plugin i have to change your initial comment starting style from /*\* into /*!

that way js-uglifier wont remove your license information (changing second star into exclusive mark flags the comment block as important so it wont remove it)

**Comment by RobinHerbots** [comment]
Can you try if js-uglifier also works when setting /**!  

Because I use the closure compiler from google and it need /*\* to leave the comment alone ;-)
