### ISSUE TITLE
Dynamic Part Input Mask  Issue

### ISSUE THREAD

**Issue by macd004** [RobinHerbots/Inputmask#562]
I want let user to input like this:
AB001/2014-07-01
CCDE3414/2014-07-04
before /  user can input  anything them want
after / user only can input date format 
how can i suppose to set the mask ?
thank you

**Comment by RobinHerbots** [comment]
Something like  $("#test1").inputmask("*{+}/y-m-d");

2014-07-03 12:15 GMT+02:00 macd004 notifications@github.com:

**Comment by macd004** [comment]
it's work!  thank you Robin :）
