### ISSUE TITLE
decimal mask not working properly

### ISSUE THREAD

**Issue by utkarshb** [RobinHerbots/Inputmask#563]
for the following 
HTML:
<input type="text" id="test"  value=""/>
Jquery:
$("#test").inputmask("decimal",{ integerDigits: 4, autoGroup: true, groupSeparator: ',', groupSize: 3, digits: 1, allowMinus: false, allowPlus: false });

when i type 5th digit. the textbook value clears and only 1st digit remains.

**Comment by RobinHerbots** [comment]
Which version do you use?  So you type 1234.5  and it should show 1,234.5

2014-07-03 12:48 GMT+02:00 utkarshb notifications@github.com:
