### ISSUE TITLE
It shouldn't allow "-0" as an integer.

### ISSUE THREAD

**Issue by laxmikantG** [RobinHerbots/Inputmask#564]
Hello Robin,

I have found that inputting -0 is allowing in an integer. I don't think anyone would require to input "-0" in an integer field. However, I think there should be some option which should allow or disallow to use "-0" in an integer field (I looked for it but could not find). 
         Actually I  have a bug from client that,it should not allow -0 in an integer field. As I am using _inputmask()_ plugin I don't want to do some custom patchwork for this. Please help  :)

This is my HTML Code:

```
<input type="text" class="MODE_ALPHANUMERIC" id="F_07_0020" name="F_07_0020" value="" data-inputmask="'alias': 'integer', 'integerDigits': '11', 'allowMinus':true, 'groupSeparator': ',', 'autoGroup': true, 'groupSize': '3'" >
```

jQuery Code:

```
   set_numeric = function(){
    $(".MODE_ALPHANUMERIC").inputmask();
    }
```

Thank you in advance!

**Comment by RobinHerbots** [comment]
@laxmikantG , 

Ok I will fix that.

**Comment by laxmikantG** [comment]
Hello Robin,
Any specific reason you have removed this?
Please let me know. 
Thanks

**Comment by RobinHerbots** [comment]
@laxmikantG , 

No.

I will start working on it.

**Comment by RobinHerbots** [comment]
@laxmikantG , 

There is already a first fix.
Not all cases are covered, but that will come soon.  I also want this to work for decimals

**Comment by laxmikantG** [comment]
Okay, Thanks

**Comment by RobinHerbots** [comment]
@laxmikantG , 

While I was working on this I stumble on the following.

Say the user wants to type -123.  in that case when using a placeholder "0" you type - resulting in -0 

Continuing the input 123 result in -123.
In my current effort I have:
 type -0 results in 0 but typing only - results in -0 as the above should be possible.

I could maybe hook an extra postprocessing on blur to remove the -

**Comment by RobinHerbots** [comment]
The -0 will be cleared on blur.

**Comment by laxmikantG** [comment]
Many thanks for solving :)
