### ISSUE TITLE
Decimal Mask, autoGroup strips radixPoint

### ISSUE THREAD

**Issue by bomanry** [RobinHerbots/Inputmask#565]
I have mask setup as follows:

$(".reimask").inputmask("decimal", { radixPoint: ".", digits:2, autoGroup: true, groupSeparator: ",", groupSize: 3, rightAlign: false });

The mask works very well.  The only problem I am having is when the value in the textbox is 0.00 when the page loads.  The radixPoint gets removed and the value in the textbox becomes 000.  I can successfully type 0.00 and it works fine.  It only removes the "." on loading the page the first time.

If I turn autoGroup:true to autoGroup:false, it doesn't remove the radixPoint on page load.  But then the groupSeparator doesn't work automatically which is what I want.

I am not sure if this is a bug or I am doing something wrong.  

I am using version 3.0.33

Please advise.

Thank You,

Bo

**Comment by RobinHerbots** [comment]
Can you retry with version 3.0.50

**Comment by bomanry** [comment]
Hello Robin,

I downloaded the latest zip file from GitHub and extracted the zip, 
copied all the *.js files into my source folder.

It WORKS!  Thanks.

Quick question though.....I installed 3.0.33 initially from NuGet which 
still has 3.0.33.  How is that going to affect update notifications from 
NuGet?

I had files like jquery.inputmask.extensions-3.0.33.js and they were 
bundled in App_Start like:

//bundles.Add(new ScriptBundle("~/bundles/inputmask").Include(
       // "~/Scripts/jquery.inputmask/jquery.inputmask-{version}.js",
       // 
"~/Scripts/jquery.inputmask/jquery.inputmask.extensions-{version}.js",
       // 
"~/Scripts/jquery.inputmask/jquery.inputmask.date.extensions-{version}.js",
       // 
"~/Scripts/jquery.inputmask/jquery.inputmask.numeric.extensions-{version}.js"));

Which I replaced with what is below to use the downloaded version:

```
   bundles.Add(new ScriptBundle("~/bundles/inputmask").Include(
```

"~/Scripts/jquery.inputmask/jquery.inputmask.js",
"~/Scripts/jquery.inputmask/jquery.inputmask.extensions.js",
"~/Scripts/jquery.inputmask/jquery.inputmask.date.extensions.js",
"~/Scripts/jquery.inputmask/jquery.inputmask.numeric.extensions.js"));

I just wanted to get the update notifications from NuGet at some point 
but this will definitely work for now.

Thanks again for an awesome product.

**Comment by RobinHerbots** [comment]
The nuget updates will come through. Only the first time you will need to
adjust the bundleconfig again and manually delete the files you got from
GitHub.
I will release a new version on nuget soon.
Best regards
Robin
Op 4 jul. 2014 20:37 schreef "manrysj" notifications@github.com:
