### ISSUE TITLE
autoUnmask: true, numericInput: true => value is reversed

### ISSUE THREAD

**Issue by kochelmonster** [RobinHerbots/Inputmask#567]
Please watch the bug live in

http://jsfiddle.net/bL2TA/13/
(second field)

**Comment by RobinHerbots** [comment]
@kochelmonster , 

Thx for repoting all issues.

I will fix them soon.

best regards, 

Robin

**Comment by RobinHerbots** [comment]
@kochelmonster , 

Fixed in version 3.0.72
