### ISSUE TITLE
Add prefix to decimal.

### ISSUE THREAD

**Issue by thearabbit** [RobinHerbots/Inputmask#569]
I would like to add prefix like "$" in decimal.

```
$("[data-inputmask=decimal]").inputmask(
        "decimal", {prefix: "$", radixPoint: ".", digits: 2, autoGroup: true, groupSeparator: ",", groupSize: 3, allowMinus: false }
    );
```

Pl help me.

**Comment by RobinHerbots** [comment]
Which version of the inputmask are you using?

2014-07-09 11:00 GMT+02:00 yuomtheara notifications@github.com:

**Comment by tamagokun** [comment]
Same. ~~Using 3.0.51~~

Scratch that version number. I assumed what was in bower.json was accurate. oops!

Using 3.0.0

**Comment by RobinHerbots** [comment]
What is the problem with it, as I see no problem with it.

Can you make a jsfiddle.

2014-07-09 13:09 GMT+02:00 Mike Kruk notifications@github.com:

**Comment by tamagokun** [comment]
http://jsfiddle.net/c5Q8L/

Looks like prefix and suffix are not working.

If this works for you in 3.0.51 maybe tag a release so bower can pick up that version?

**Comment by RobinHerbots** [comment]
See http://jsfiddle.net/c5Q8L/4/

I will tag a release for version 3.0.52

**Comment by tamagokun** [comment]
Awesome. Thank you!
