### ISSUE TITLE
Auto-completion of  time hours, minutes & seconds in date extension

### ISSUE THREAD

**Issue by magnusburton** [RobinHerbots/Inputmask#570]
Hey!

I'd like to suggest an auto-completion feature for the date extension. I want to be able to write not the whole month number but a piece of it (write a 5 instead of 05 and for hours, write 7 instead of 07).

Here're some examples what this auto-completion feature would do:
(HH:mm) Instead of typing 07:07 I wanna type 7:7
(HH:mm) Instead of typing 07:04 I wanna type 7:04
(dd-mm-yyyy) Instead of typing 07-04-2014 I wanna type 7-4-14 (or 7-4-2014)

Hope this makes sense!

**Comment by RobinHerbots** [comment]
That is already in there.  Only not for the minutes.

2014-07-09 13:03 GMT+02:00 Magnus Burton notifications@github.com:

**Comment by magnusburton** [comment]
@RobinHerbots Oh I'm sorry. It doesn't work for the hours either? As in the readme file it says that auto complete only works for days, months and years.

**Comment by RobinHerbots** [comment]
@magnusburton , 

For hours it works.  I need to update the readme.  I will fix it in the minutes part.

Anyway thx for the suggestion.

**Comment by magnusburton** [comment]
@RobinHerbots Sorry but my tests indicate that hours does not work. I simply can't enter just an 8 in the hours part so I have to enter 0 and then 8...

**Comment by RobinHerbots** [comment]
@magnusburton , 

No problem.  I will have a look at it.

Can you give the mask options you are using.

best regards, 

Robin

**Comment by magnusburton** [comment]
@RobinHerbots inputmask("hh:mm");

Thank you for this great plugin though, really like it :)

**Comment by RobinHerbots** [comment]
@magnusburton , 

Ah offcourse, the logic is part of the datetime alias.

Try with  $("#test1").inputmask({
                alias: "datetime",
                mask: "h:s",
                placeholder: "hh:mm"
            });

**Comment by magnusburton** [comment]
@RobinHerbots Thank you so much, work great!

I can consider this one closed...

**Comment by RobinHerbots** [comment]
@magnusburton , 

With the latest commit you can use the simple "hh:mm" again to obtain the same result.
Also included minutes and seconds.  (type for ex: 88 => 08:08)

**Comment by torian257x** [comment]
well... how to do it now? hh:mm doesnt work any longer
