### ISSUE TITLE
Change event not firing on multi-mask

### ISSUE THREAD

**Issue by nickpearson** [RobinHerbots/Inputmask#572]
I'm new to jquery.inputmask (which is awesome), and I've run into something that doesn't seem to be working right. Forgive me if this is a simple oversight.

The `change` event fires correctly when using built-in masks, but when I attempt to define my own multi-mask, everything (seemingly) works, but no `change` event is fired.

I made a quick example with jsFiddle: http://jsfiddle.net/qkL3F/3/

Background: I'm trying to get better time handling. Using the built-in `h:s` works pretty well, but when using the 12-hour format, typing `145` results in `2:5_` rather than the `1:45` I would expect. Similarly, typing `233` results in `11:3_` instead of `2:33`. I see that the library is simply wrapping the hours. (`14` in 24-hour time is 2pm in 12-hour time, hence the `2` in the `2:5_` result above. Same with the second example, with `23` turing into `11`.)

Here's the multi-mask code that works (except for the `change` event not being fired):

``` javascript
$('.time-2').inputmask({
  mask: [
    { mask: '2:s' }, // 2-digit hour (10, 11, 12)
    { mask: '1:s' }  // 1-digit hour (1, 8, etc.)
  ],
  definitions: {
    '2': { validator: '(1[0-2]|0[1-9])', cardinality: 2 },
    '1': { validator: '[1-9]',           cardinality: 1 }
  }
});
```

Any help or pointers would be greatly appreciated. And thanks for the awesome library.

**Comment by RobinHerbots** [comment]
@nickpearson , 

Multi masks is being replaced by the alternator masks.  The change event should work now.

**Comment by nickpearson** [comment]
Thanks @RobinHerbots! I'll give it a try.
