### ISSUE TITLE
Can't enter uppercase letters

### ISSUE THREAD

**Issue by annames** [RobinHerbots/Inputmask#574]
Hello,

I'm using your plugin with inputmask 3.0.55 on a form that allows grade entry for tests in a class. I have fields that must allow either a timed score (such as MM:SS format) or an "X" to indicate that a particular student did not complete the test. I am replacing long-standing code that did not work with IE 11 or Chrome, so there is a lot of data in the wild and many existing users who are familiar with this functionality and so I can't change it; I must allow a time (in a variety of user-selected formats) or an upper- or lowercase X.

This all works fine, and having multiple masks is very cool (thanks!), except that a couple of lines of event handling code in inputmask-multi are preventing me from entering uppercase letters.

In the mask function, lines 195 and 198 cause a "return true" if e.shiftKey is true... but that will be true even if the shift key is being held down in order to uppercase a letter. I changed that section of code to the following:

```
                if (e.ctrlKey || k == opts.keyCode.SHIFT || e.altKey) {
                    return true;
                }
            } else if (e.type == "keypress" && (e.ctrlKey || k == opts.keyCode.SHIFT || e.altKey)) {
                return true;
            }
```

and it all works great. Without that change, the code exited before ever calling the keypressEvent function in inputmask, so my letter mask (with /[xX]/ validator) always failed for uppercase X (but worked fine for lowercase x).

Is this a reasonable change to make? Should the other key references here also use the opts.keyCode values or are they best left as they are?

Thanks,
Ann

**Comment by annames** [comment]
And I see you've already fixed it!

Do you have a target date for the next release? We're using the NuGet package, so if I'm out of sync with that my colleagues will ask when we can get back in sync.

Thank you very much for taking care of this so quickly. I really appreciate it!

**Comment by RobinHerbots** [comment]
The next releaze will be in august .
