### ISSUE TITLE
It should support  padding!

### ISSUE THREAD

**Issue by laxmikantG** [RobinHerbots/Inputmask#579]
Hi Robin, 
I was looking for a `padding` like option, but could not find anything to add padding to a character or a number in `data-inputmask` for a `textfield`.
Let me know if there is something to add padding for a number or text from a textfield. like this:

```
            setPadding(2, 6); // should return "000002"
            setPadding(99.5, 8); // Should return "00000099.5"
            setPadding('abc123', 10, '#'); //Should return ####abc123
```

I hope you understand my requirement.
Thank you in advance!!

**Comment by RobinHerbots** [comment]
@laxmikantG , 

Hmmm, I not sure this belongs to a general masking plugin.  Maybe as an extra within the numeric extensions.
