### ISSUE TITLE
Not auto unmasking on submit & reversing value on inputmask remove

### ISSUE THREAD

**Issue by marumehrts** [RobinHerbots/Inputmask#580]
HI, i've implemented this on a few inputs, as following
$(selector).inputmask('999,999,999.99', {
        numericInput: true,
        rightAlignNumerics: false,
        greedy: false,
        autoUnmask: true,
        removeMaskOnSubmit:true
    });
But when submitting the form, keeps the masked value, like ___%2C_78%2C990.00
and when I force $(selector).inputmask('remove'); before submitting, it unmasks but also reverses the value

**Comment by RobinHerbots** [comment]
@marumehrts , 

Can you have a retry with the latest version or otherwise create an example in jsfiddle.
