### ISSUE TITLE
e-mail mask doesn't allow - and _ characters

### ISSUE THREAD

**Issue by IefSels** [RobinHerbots/Inputmask#581]
Dear Robin,

You made us very happy with the jquery.inputmask library, but we encountered a small problem when trying to validate e-mailaddresses.
It seems that the minus- and underscore characters are not allowed.
Could you help us with that?

We believe it can be fixed by adding -_ to the 'validator' key in the 'definitions' object in 'aliases'.

Thank you!
Ief from Belgium

**Comment by MatthiasWarmenbol** [comment]
Dear Sir,
You make me very happy too if you fix it! 
Thank you, come again!
Mr. W (also from Belgium).

**Comment by RobinHerbots** [comment]
@IefSels, @MatthiasWarmenbol , 

I added ! # $ % & ' \* + - / = ? ^ _ ` { | } ~ as extra possibe chars for email.
I you make a donation I would be happy too ;-)
