### ISSUE TITLE
The "showMaskOnFocus" problem.

### ISSUE THREAD

**Issue by vachudj** [RobinHerbots/Inputmask#582]
Hi Robin,
I have registered strange behavior of the **showMaskOnFocus** functionality.
Basically I'm not able to make it working properly.
If I change original condition on the line 1413:

`if (opts.showMaskOnFocus && !$input.hasClass('focus-inputmask') && (!opts.showMaskOnHover || (opts.showMaskOnHover && nptValue == ''))) {`

to 

`if (opts.showMaskOnFocus && $input.hasClass('focus-inputmask') && (!opts.showMaskOnHover || (opts.showMaskOnHover && nptValue == ''))) {`

so specifically I have changed this:

(`!$input.hasClass('focus-inputmask') => $input.hasClass('focus-inputmask')`)

and **showMaskOnFocus** function then began to work.

Is it possible to check it on your end and if you find it as correct fix try to change source code on your end ? We prefer to use original library instead of our side update version.

Thank you very much for your time to check this situation in advance.

KR

Jan Vachuda

**Comment by RobinHerbots** [comment]
@vachudj, 

Can you make a jsfiddle of it, showing the original issue.  What is not working with the showMaskOnFocus?

Which browser and which options where you using?
