### ISSUE TITLE
input number

### ISSUE THREAD

**Issue by stmn** [RobinHerbots/Inputmask#583]
Hi,

something like this absolutely doesn't work for me:

$("input[type=number]").inputmask("integer", { allowMinus: false });

There's no problem with text input. Tested on FF 30.
Can ya fix that? :smile: 

I'ill try check later whats the reason.

**Comment by stmn** [comment]
OK, found it: :(

```
if ($el.is(":input") && $el.attr("type") != "number") {
```

**Comment by rogah** [comment]
Hi, I'm also getting issues to use the plugin with the input element of type number. The plugin is throwing the following exception:

_Uncaught InvalidStateError: Failed to read the 'selectionStart' property from 'HTMLInputElement': The input element's type ('number') does not support selection._

It looks like it's intentionally unsupported. Is there any specific reason for that?

``` html
<input type="number" />
```

**Comment by RobinHerbots** [comment]
@rogah , 

Which version do you use?  As input type=number is not supported.

**Comment by daniel-g** [comment]
Why does type=number is not supported?

**Comment by RobinHerbots** [comment]
@daniel-g , 

Because type=number is rather limited in use for masking an input.  No other chars allowed than 0-9,. and also no caret positioning.
