### ISSUE TITLE
Does not work on Android

### ISSUE THREAD

**Issue by slawsork** [RobinHerbots/Inputmask#584]
Hi. I have problem with plugin on Android devices: Samsung Galaxy Note 3 / Android 4.4.2;
Samsung Galaxy S4 / Android 4.4.2; xiaomi mi3 / Android 4.4.2 (in default android browsers).
I use date mask in format 'yyyy' and 'yyyy/mm/dd'. For these android devices when I start type digits, placeholder is not disappeared and I cannot remove it. I tried to use version: 3.0.29 and version: 3.0.56  , but it's does not work. 
Link to jsfiddle http://jsfiddle.net/bHnFN/5/.

See screenshot of problem (Samsung Galaxy S4 / Android 4.4.2; default browser)

![screenshot_2014-07-25-17-25-06](https://cloud.githubusercontent.com/assets/6538999/3703586/39fe99b0-140b-11e4-974a-cc9d71a44e66.png)

Thank you.

**Comment by phongsi** [comment]
Hey, i had a very similar issue. It could be one or a combination of many reasons. I didnt explore enough to figure out exactly. It could be that the "keypressed" event is deprecated on your mobile browser -> http://www.w3.org/TR/DOM-Level-3-Events/#event-type-keypress, in that case you could add the input event. It can also be that the numeric keys on the android keyboard return a 0 keycode -> https://code.google.com/p/chromium/issues/detail?id=118639, in this case there is no good way to get the key unless you look at the input field.

**Comment by phongsi** [comment]
This may or may not help you, but this works for me on my Verizon LG G2 chrome browser. My mask is mm/dd/yyyy. This could work for your yyyy/mm/dd mask. I'm on 3.0.55 release version.
All I did was modify the mobileInputEvent function.

```
function mobileInputEvent(e) {
                if (skipInputEvent === true && e.type == "input") {
                    skipInputEvent = false;
                    return true;
                }
                var input = this;

                //backspace in chrome32 only fires input event - detect & treat
                var caretPos = caret(input),
                    currentValue = input._valueGet();

                currentValue = currentValue.replace(new RegExp("(" + escapeRegex(getBufferTemplate().join('')) + ")*"), "");

                //correct caretposition for chrome
                if (caretPos.begin > currentValue.length) {
                    caret(input, currentValue.length);
                    caretPos = caret(input);
                }
                if ((getBuffer().length - currentValue.length) == 1 && currentValue.charAt(caretPos.begin) != getBuffer()[caretPos.begin]
                    && currentValue.charAt(caretPos.begin + 1) != getBuffer()[caretPos.begin]
                    && !isMask(caretPos.begin)) {
                    e.keyCode = opts.keyCode.BACKSPACE;
                    keydownEvent.call(input, e);
                } else {

                    //hack on some android chrome
                    if (currentValue.length < 10) {
                        e.keyCode = opts.keyCode.DELETE;
                        keydownEvent.call(input, e);
                    } else {
                        val = $(this).val();
                        beforeCursor = val.substring(0, caret(input).begin);
                        digits = beforeCursor.match(/\d/g);
                        lastDigit = digits[digits.length - 1];
                        e.keyCode = lastDigit.charCodeAt(0);
                        insertPos = val[caret(input).begin].match(/\d|\w/g) ? caret(input).begin-1 : caret(input).begin;
                        keypressEvent.call(input, e, true, lastDigit.charCodeAt(0), true, true, insertPos);
                        caret(input, getLastValidPosition()+1);
                    }
                   // end hack
                }
                e.preventDefault();
            }
```

The last else is where I added a block.

**Comment by RobinHerbots** [comment]
see #465
