### ISSUE TITLE
Option to start input with decimal point

### ISSUE THREAD

**Issue by YodaJM** [RobinHerbots/Inputmask#587]
When using the numeric extension for decimal numbers, I think it would be quite useful to be able to start input in the field by typing a decimal point.  For example if entering 25% as a decimal number, it would be nice to just type .25 and the plugin could add the leading 0 if the field was empty when the decimal point was entered.  The final value would be 0.25.

Currently you have to type 0 first before the decimal point registers.  And if you type just .25 the value becomes 25 with no decimal point.

I apologize if this is an option already that I just can't figure out how to enable.

Thanks!

**Comment by RobinHerbots** [comment]
@YodaJM , 

In version 2.x it was already in, but due to the refactoring in version 3.x it is gone.  

I will readd it, thx for reporting

**Comment by GBirch** [comment]
I would like to add my vote for re-adding this feature.  Unless you have, and I don't understand how to enable it (I've tried setting the new radixFocus to true, but that doesn't seem to do it).  I can't find a version number in the code.  As a by-the-by, thank you for your work on this plugin - it's great!

**Comment by svdavidh** [comment]
Glad this feature was implemented. I also was wondering how to enable this option, I've tried various options, but wasn't able to get the decimal point working without typing the leading integer followed by the '.'

**Comment by RobinHerbots** [comment]
@svdavidh , 

What mask do you use?

**Comment by svdavidh** [comment]
I'm using a decimal mask set up like this:

```
input.inputmask('decimal', {allowMinus: false, allowPlus: false, autoGroup: true, groupSeparator: ',', rightAlign: false, digits: 2});
```

**Comment by YodaJM** [comment]
Thanks for reimplementing this!

The following options seem to work to allow starting by typing a '.'
`$("#input2").inputmask('decimal', { digits: 2, placeholder: "0", digitsOptional: false });`

I have noticed however that this only works if you click on the textbox with the mouse.  When you click on the textbox the cursor jumps in between the first 0 and the decimal point like 0|.00, which correctly allows the user to type a decimal point to start decimal entry. However, if you use the Tab key to navigate through form inputs, the placeholder (or entered value) is highlighted and then a number must be typed first before the decimal point can be typed.

I've setup a jsfiddle that exhibits this behavior in FF and Chrome.  It's possible that it is a browser behavior that is unavoidable.  Or perhaps my options on the inputmask are not correct. 

http://jsfiddle.net/m9cbtfuh/1/

Thanks again!

**Comment by RobinHerbots** [comment]
@YodaJM , 

Fixed in the latest commit

**Comment by YodaJM** [comment]
It's getting very close now, but there are still two issues.
In the same fiddle: http://jsfiddle.net/m9cbtfuh/1/

If you click on the 2nd text box, the cursor still jumps between the 0 and decimal point, 0|.00, as it did before.  But now if you type a decimal point, a second decimal point is entered making the input like 0.|.00, and you can enter any number of digits making the input like, 0.12345.00.

Tabbing into the box is working correctly if you type a decimal point or a number other than 0.  If you type a 0 it behaves identically to the above problem, the input becomes 0.|.00, with two decimal points, and then you can type any number of digits.

It is possible I need different options for the mask,

``` javascript
$("#input2").inputmask('decimal', { digits: 2, placeholder: "0", digitsOptional: false });
```

**Comment by RobinHerbots** [comment]
@YodaJM , 

Can you have a retry with the latest commit.

**Comment by YodaJM** [comment]
It work's perfectly now!

Thanks again for all the help reimplementing this (and improving it over the original functionality)!
