### ISSUE TITLE
Decimal format value doesnt apply grouping.

### ISSUE THREAD

**Issue by ghost** [RobinHerbots/Inputmask#588]
When applying a numeric mask with grouping using inputmask.format, character groups are not displayed.  The mask works fine when applying to an input, just not with format value.

http://jsfiddle.net/sPa9K/14/

entered:   1111111.11
result:       1111111.11
expected: 1,111,111.11

**Comment by RobinHerbots** [comment]
@swd120 , 

fixed in 3.0.58

**Comment by ghost** [comment]
Awesome!  Thanks Robin!
