### ISSUE TITLE
Changing the 'datetime' to use dd-mm-yyyy

### ISSUE THREAD

**Issue by janhartmann** [RobinHerbots/Inputmask#589]
Hi,

I am trying to change the behavior of the 'datetime' mask to use dd-mm-yyyy hh:mm instead of dd/mm/yyyy hh:mm.

I have tried the following:

```
$("input.datetime").inputmask("datetime", { "placeholder": "dd-mm-yyyy hh:mm" });
```

But it still uses the forward-slash?

Jan

**Comment by ghost** [comment]
Try this:

```
$("input.datetime").inputmask('datetime', {
    mask: "1-2-y h:s",
    alias: "dd-mm-yyyy",
    placeholder: "dd-mm-yyyy hh:mm",
    separator: '-'
});
```

**Comment by janhartmann** [comment]
This works, perfect - thanks!! :-)

**Comment by buttflattery** [comment]
@swd120  can you please explain what is the format that is provided in the `mask: "1-2-y h:s",` , it certainly isn't a regex, and  am unable to understand how is this expression `"1-2-y h:s"` is interpreted ?
