### ISSUE TITLE
AMD support

### ISSUE THREAD

**Issue by SimenB** [RobinHerbots/Inputmask#591]
Hi!

Now that jQuery ships with full fledged AMD support, would you consider doing the same to this? A shim currently works fine, so it's not really a problem of course.

**Comment by RobinHerbots** [comment]
@SimenB , 

I added amd module support in version 3.0.59 but haven't got the chance to test it.  Can you have a try?

**Comment by SimenB** [comment]
Awesome, thank you!
I'm currently on vacation, but I'll be able to test it at work next week (Wednesday)

**Comment by ingro** [comment]
I tried with version 3.0.60 but with no luck, I fixed by changing the require function in:

``` javascript
if (typeof define === 'function' && define.amd) {
    define([
        'jquery'
    ], factory);
} else {
    factory(window.jQuery);
}
```

**Comment by SimenB** [comment]
As you can see in this issue https://github.com/jquery/jquery-ui/pull/1029#issuecomment-21145521 from when jQuery UI went and made all of their modules into AMDs, the author of AMD recommends against named modules. So @ingro's solution seems the right one (again, I'm on vacation, so can't test it).

That issue also contains the monster commit that actually added the define calls to the source code, so you can check out how they did it. (Exactly like @ingro's solution)
They renamed the files as well to remove the prefix. Have you considered doing that? (we already do it, and just chuck all the files into it's own directory).

**Comment by RobinHerbots** [comment]
@ingro , @SimenB 

Thx for the help and info. 

Removing the prefix seems a good idea.

**Comment by artemkaint** [comment]
Removing the prefix was a bad idea. Now I could not use amd with bower because bower connect bundle file

**Comment by RobinHerbots** [comment]
@artemkaint , 

I didn't remove the prefix yet, but I know with the bundled file there is a problem because then the amd setup is wrong.  He cannot find ./jquery.inputmask.

Maybe I should drop the bundled file because that is a bit against the point of using AMD.

**Comment by SimenB** [comment]
Have you considered building the bundled file with r.js? That way people not using AMD would be able to just add the single script line to their site.

Build for pages without AMD: http://requirejs.org/docs/faq-optimization.html#wrap
And you can exclude your own jQuery dependency like this: http://requirejs.org/docs/optimization.html#empty

I don't know if this would break it for people using the bundled file in an AMD environment, but those people shouldn't really use the bundled file like you said anyway.

**Comment by RobinHerbots** [comment]
@SimenB , 

Yes, I'm thinking the same.  Thx for the links.  I will read them.
