### ISSUE TITLE
Decimal digits setting doesn't autofill missing digits after decimal point.

### ISSUE THREAD

**Issue by YodaJM** [RobinHerbots/Inputmask#592]
In 2.x, when the digits setting was specified, the input field would autofill up to the number of digits set on the blur event. Entering 1.1 would be set to 1.10 if digits is set to 2.

In 2.x, when no decimal point was entered the input field would not autofill a decimal point or any digits. To match the behavior above, entering 1 should be set to 1.00 if digits is set to 2.

This option still correctly limits the number of digits after the decimal point.

Thanks!

**Comment by ioleo** [comment]
Try setting `clearMaskOnLostFocus: false`

**Comment by RobinHerbots** [comment]
@YodaJM , 

You need to set the digitsOptional: false option
