### ISSUE TITLE
IE 8 js error in inputmask-multi

### ISSUE THREAD

**Issue by annames** [RobinHerbots/Inputmask#593]
Hi - thanks for your attention to the uppercase letters issue! Now I have a fun IE 8 problem. :-) I have already patched this for my own purposes, but maybe you have a better idea.

I had my multiple masksets working fine in IE 10, IE 11, and Chrome, but got what seemed to be an infinite loop in IE 8. A whole awful lot of troubleshooting later, I tracked it down to something in the $.map call in the mask function on line 170 of inputmask-multi. A combination of things came together to cause this problem:
- When you pass an array to a function in javascript (I didn't know this before, so I learned something!) it comes out as a generic object on the other side.
- IE 8's javascript engine has no indexOf method on Array, so like many other people who have to support legacy browsers, we add this method to the Array prototype.
- Any methods you might have added to the Array prototype before passing the array as a function parameter come out as object members on the other side.

I found that while inputmask started out with a maskset array something like this:

`maskset = [ {mask: '[X]', ... }, {mask: '[99.9'], ... } ]`

In IE 8 it looked like something like this after being passed to multMaskScope in inputmask-multi:

`masksets = { {0: {mask: '[X]', ... }}, {1: {mask: '[99.9]', ... }, {'indexOf': {function...} }`

This object is no longer what we expect... it has an additional member for the patched indexOf method!

Something about this blows up either the $.map call itself, or the recursive call to inputmask within it. Sorry I didn't bother tracking it down any further - it took me a while to get to this point, at which time I decided to just convert masksets back to an array at the very top of multiMaskScope in inputmask-multi:

```
function multiMaskScope(actionObj, tmpMasksets, opts) {
            /* Arrays (e.g., tmpMasksets) get passed as generic objects.
             *      In IE8 the array in the caller got patched with an "indexOf" method, which ends up looking like an array element in the generic object here
             *      This in turn blows up the $.map call in the mask function, so let's turn it back into an array */
            var masksets = [];
            var masksetIndex = 0;
            for (tmpMasksetIndex in tmpMasksets) {
                var thisItem = tmpMasksets[tmpMasksetIndex];
                if (thisItem.mask) {
                    // If it has a mask, it's a thing we want
                    masksets[masksetIndex] = thisItem;
                    masksetIndex++;
                }
            }
            ...
```

That's working for me in IE 8-11 and Chrome. There may be a better way to convert back to an array, I don't know. (The jQuery method for this purpose doesn't work, because masksets doesn't have a length attribute.) Or maybe you'd rather pass masksets as a non-array object to begin with? Or something else?

Thanks!

**Comment by RobinHerbots** [comment]
Hallo Ann,

I should pay more attention to the older browsers.  As this I have seen
before.

Hmm but also, the inputmask-multi is only a temporary solution for multiple
masks.  (read far from perfect)  I added a notice in the file.

I fixed it by just checking in the $.map that the ndx is an real index and
not something else like "indexof"'.

I also noticed some errors in the qunit test for ie in general.  I will
also have a look at these.

Best regards,

Robin

2014-08-05 17:15 GMT+02:00 annames notifications@github.com:

**Comment by annames** [comment]
I know we're living on the edge a bit with inputmask-multi. :-) With the changes I've mentioned it's working fine for our purposes. (Wasn't I surprised when I found out my time-score fields for test grade recording also had to accept an "X" to indicate the test wasn't taken!)

Thank you for taking the time to look at older IE issues. I really appreciate it!
