### ISSUE TITLE
Line 146 of inputmask.numeric blows up in IE 7

### ISSUE THREAD

**Issue by annames** [RobinHerbots/Inputmask#594]
I wouldn't bother you with an IE 7 problem (sadly, we do still have to support this browser) except that once again I've already patched it on my end and have code to offer you - I'm just not sure if I understand what the code is trying to do, and therefore if my patch will work in all cases.

Line 146 of inputmask.numeric looks like this:

`if (matchRslt["0"][0].indexOf("0") == 0 && pos >= opts.prefix.length) {`

Every browser I've tried that is newer than IE 7 shows `matchRslt["0"]` = `matchRslt["0"][0]` = some string value from my input field. However, in IE 7, `matchRslt["0"][0]` returns `undefined`, and so the call to indexOf blows up.

I replaced that line with this:

```
                                    var strRslt;
                                    if ($.isArray(matchRslt["0"])) {
                                        strRslt = matchRslt["0"][0];
                                    } else {
                                        strRslt = matchRslt[0];
                                    }
                                    if (strRslt.indexOf("0") == 0 && pos >= opts.prefix.length) {
```

and it works fine in all tested browsers (IE 7-11 and Chrome). I was just wondering - is `matchRslt["0"]` ever going to be an array? I only found it returning a string. Why did the code need to do `matchRslt["0"][0]`?

Thanks!

**Comment by RobinHerbots** [comment]
@annames , 

Thx for reporting and please keep bothering me if you have problems even on older browsers ;-)

I already patched the file.  The ["0"][0] is not needed.  I guess a copy-paste error or a typo.  ;-)

New release will come soon.

**Comment by annames** [comment]
Typos happen. :-) Thanks for fixing!
