### ISSUE TITLE
inputmask.numeric escaped suffix does not autoUnmask

### ISSUE THREAD

**Issue by kochelmonster** [RobinHerbots/Inputmask#595]
Please watch the bug here: http://jsfiddle.net/4LL46/5/

**Comment by RobinHerbots** [comment]
@kochelmonster , 

Escaping in a suffix prefix shouldn't be necessary.  I will fix that too.

**Comment by RobinHerbots** [comment]
@kochelmonster , 

See new http://jsfiddle.net/4LL46/6/

No more need to escape the suffix/prefix and autounmask is now working.
