### ISSUE TITLE
Referring to Issue 366

### ISSUE THREAD

**Issue by mjortman** [RobinHerbots/Inputmask#596]
Hi - I was wondering if you had finished the changes you mentioned in #366 with regards to the change to decimal. I'm using the following data-inputmask, and having the same problem that person did:

'alias': 'decimal', 'groupSeparator': ',', 'autoGroup': true, 'digits': 2, 'digitsOptional': false, 'prefix': '$ ', 'placeholder': '0'

So when I enter $123.45 it's coming in as 12345. You mentioned updating the decimal extension to handle this differently, so I was wondering if that was done. Or, should I do something like the user did in #412 for now?

Thanks in advance!

**Comment by RobinHerbots** [comment]
@mjortman , 

Which version do you use?  This should work.  Also specify the autoUnmask: true option

**Comment by mjortman** [comment]
This was 100% user error. Sorry about that. I was stripping off characters to save to the database in decimal format, and stripped the '.' by accident....

Sorry about that. And thanks again for an amazing masking tool!
