### ISSUE TITLE
Decimal mask oncomplete not firing on delete, or on last char of char group.

### ISSUE THREAD

**Issue by ghost** [RobinHerbots/Inputmask#597]
Sorry - had to go with JSbin because jsfiddle is down
http://jsbin.com/xuxacola/4/edit

Using char groups of 3  (Same result when changing to other sized char groups)

Enter 123456789 in the input box:
Expected:
1
12
123
1234
12345
123456
1234567
12345678
123456789

Actual:
1
12
1234
12345
1234567
12345678

Enter 123456789 in the input box - then press backspace:
Expected:
12345678

Result:
No event fired.

**Comment by RobinHerbots** [comment]
@swd120 , 

Finally fixed ;-)
