### ISSUE TITLE
Interting when copy/paste values

### ISSUE THREAD

**Issue by lmbelo** [RobinHerbots/Inputmask#598]
When I try to copy and paste a value to a masked input the pasted value comes inverted.

See mask representation:
$('#cnpj').inputmask({"mask": "99.999.999/9999-99", "numericInput": true, "rightAlignNumerics": false, "autoUnmask" : true});

if I copy 17.250.633/0001-50 it pastes 05.100.033/6052-71. 

Is that a bug or am I doing something wrong?

**Comment by RobinHerbots** [comment]
@lmbelo , 

This is definitly a bug.  I will fix that.

**Comment by penihel** [comment]
I have the same problem

**Comment by RobinHerbots** [comment]
@lmbelo , @penihel , 

Fixed in the latest version.

**Comment by lmbelo** [comment]
Great. I'm going to try it right now.

**Comment by andreasba** [comment]
@RobinHerbots, I would like to re-open this:

```
        $("#ISBN").inputmask("numeric", {
            rightAlign: false
        });
```

If I enter the text manually everything is fine.

However, If I paste 978-3498064365 for example it makes "-3498064365978" out of it.

Andreas

PS: I am on the lastest version

**Comment by RobinHerbots** [comment]
@lmbelo , 

I will have a look at it.

You would expect -9783498064365 right?

**Comment by andreasba** [comment]
@RobinHerbots I would expect the pasted number to be "9783498064365" :)

Thanks :)

Andreas

**Comment by RobinHerbots** [comment]
@andreasba , 

Hmm why do you use the numeric alias in that case?

"9{*}" works fine in that case

**Comment by RobinHerbots** [comment]
@andreasba , 

Or you can use 

```
Inputmask("numeric", {
            allowMinus: false
        }).mask(testmask);
```

**Comment by andreasba** [comment]
Thanks @RobinHerbots, "9{*}" did the trick, not sure why I did not come up with this simple solution (the solution your last post does not work as I was using this already)

**Comment by RobinHerbots** [comment]
@andreasba , 

It does work with the latest version on github

**Comment by fhott** [comment]
When I paste a value greater then 1000,00, the input trade the first hundred number and put on the last position, like:
I pasted 12.503,25 and turn 21.503,25
Same issue on number like 123.456.789,22 and turn 623.451.789,22

Configs: 
    prefix: "",
    groupSeparator: ".",
    radixPoint: ",",
    allowMinus: false,
    allowPlus:false,
    numericInput: true

**Comment by RobinHerbots** [comment]
Can you open a new issue for this.

**Comment by fhott** [comment]
Of course!
https://github.com/RobinHerbots/jquery.inputmask/issues/1295
