### ISSUE TITLE
Optional mask incorret when value is set by $.val(  )

### ISSUE THREAD

**Issue by lmbelo** [RobinHerbots/Inputmask#599]
When a optional value is supressed the result mask is displayed incorrect.

See mask:

$('#input-fone').inputmask('(99) 9999[9]-9999');

If i set $('#input-fone').val( 4195399778 ) it cames like (41) 95399-778_ and should be (41) 9539-9778

**Comment by RobinHerbots** [comment]
@lmbelo , 

First, I do understand what you mean.
But on the other hand, ... (41) 95399-778_ is as valid as (41) 9539-9778 according the definition.  So on which base should the plugin decide that the one of the 2 is what the user wants (and in a generic way).

Setting a value like "419539-9778" would always result in (41) 9539-9778.

Anyway for now you can use $('#input-fone').inputmask ( { mask: ['(99) 9999-9999', '(99) 99999-9999']});  which will do what you want.  But you have to include the extra inputmask-multi.js.

In the future the inputmask-multi will not be needed anymore but I am still working on that.

**Comment by RobinHerbots** [comment]
see issue #612

**Comment by lmbelo** [comment]
It really works great!

Great attention. 

Thanks for your work.
