### ISSUE TITLE
Keep persistence

### ISSUE THREAD

**Issue by FakeArShui** [RobinHerbots/Inputmask#6]
Please provide the options of keeping the mask persistence.

Thanks....

Moreover, I couldn't find any explaination of cardinality and prevalidator regardings definitions

'd': { //day
                    "validator": "0[1-9]|[12][0-9]|3[01]",
                    "cardinality": 2,
                    "prevalidator": [{ "validator": "[0-3]", "cardinality": 1}]
                },

**Comment by RobinHerbots** [comment]
As you can see in the example, the validator test for 2 characters.  And the mask d (day) takes 2 characters => cardinality
the prevalidator test the first character(s)

The validation of the day takes place after typing 2 characters.  The prevalidator validates the first one.

You can persist the mask by defining it in the defaults, ... see also in the readme how to apply default settings.  But keeping the masks passed by direct options is a good idea.  I will make the changes soon.

Best regards, 

Robin

**Comment by RobinHerbots** [comment]
https://github.com/RobinHerbots/jquery.inputmask/commit/93804ca40c874a205d60e794fe3d3f7699beb33d

**Comment by FakeArShui** [comment]
Thanks for your speedy response.

It seems that my comment may lead to some kind of confusion, what I am talking about is the ability to keep the mask persistent at the UI level, not the value returned from the masked input box, i.e. the input mask is always visible at the textbox (just like the ClearMaskOnLostFocus Option for maskededitextender).

If seems that there is some reasons forced you to write your own one rather that relying on the ajax controlkit, my reason is that ajax control lacks the options of changing the separator ( as some project don't like / for it).

how about this:
'y': { //year
                    "validator": "(19|20)\d\d",
                    "cardinality": 4,
                    "prevalidator": [
                        { "validator": "[12]", "cardinality": 1 },
                        { "validator": "(19|20)", "cardinality": 2 },
                        { "validator": "(19|20)\d", "cardinality": 3 }
                        ]
                }

I think this is reasonable to put some kind of dependency in this problem, not only they are commonly used, but also it can remove duplication from the setting (as I need to define the date format both for the ui datepicker and this plugin.

Moreover, I think the validation for year is a bit greedy, as the validation of the date (in particular the year is a bit out of scope), as user can rely on (jquery validation plugin (http://docs.jquery.com/Plugins/validation) and jquery date validation plugin (http://keith-wood.name/uiDatepickerValidation.html)).

**Comment by RobinHerbots** [comment]
I added the clearMaskOnLostFocus option, so know you can choose wheter you want to show the mask all time.

About adding some degree of interopability (or dependency) between say ui-datepicker and the inputmask, ... I don't know, that's a bit like forcing someone to use the ui-datepicker for dates when using the inputmask plugin.  (Maybe I can add this functionality as an optional extention on the plugin.)

For the validation.  You are free to use another mask for the year like 9999 or whatever mask you created.  So I don't see that as a problem.  Thx for the links, I will check out uiDatepickerValidation.

Robin

**Comment by FakeArShui** [comment]
It seems that clearMaskOnLostFocus  doesn't persist input mask after the input lose focus (tested on IE8 and Chrome)

**Comment by RobinHerbots** [comment]
I tested on FF and IE9, ...

Can you send me an example so I can test it myself.

thx

Robin

2011/4/14 FakeArShui <
reply@reply.github.com>

**Comment by RobinHerbots** [comment]
See https://github.com/RobinHerbots/jquery.inputmask/commit/f44595ea46f2ed39ba057746fc2e9c99d6f167f4 for fix.

Robin

**Comment by FakeArShui** [comment]
Thanks, it work on IE6, IE8 and Chrome
