### ISSUE TITLE
default decimal value setting in decimal mask

### ISSUE THREAD

**Issue by babupca** [RobinHerbots/Inputmask#600]
We currently use the decimal mask, were we require default two integer digits, which i mentioned in the definitions.

Here,
1.  when i type only 3 then, it value should be 3.00
2.  when i type 3.2, then it should be 3.20 

How to achieve this with the decimal mask, please let me know if you have any solution.

jsfiddle link: http://jsfiddle.net/BA251281/wk8yr04z/15/

weight:{
    mask:"decimal",
    integerDigits:5
    digits:2,
    allowMinus:false
}

**Comment by RobinHerbots** [comment]
@babupca , 

Try with     $("#weighMask").inputmask({
        alias: "decimal",
        integerDigits: 5,
        digits: 2,
        digitsOptional: false,
        placeholder: "0",
        allowMinus: false
    });

But I know in version 2.x there was an autofill for the digits. #592 

I will implement this again.

**Comment by babupca** [comment]
One more senario, where when i tab from one text field to another field, the placeholder gets selected. Now the user wants to enter  .34 only, then it directly enters the value in the integerDigits space. 

intial value: 0.00
entered value: .34
output value:  34.00

Please check the jsfiddle link
http://jsfiddle.net/BA251281/wk8yr04z/28/ 

It will be good, if the user is allowed to enter (dot) followed by the digits directly, after the text field gets selected, instead of pressing the left arrow key

**Comment by gaganshera** [comment]
Hi, 
I have a similar scenario. What I need is that initially my input field will show no placeholder.
When a user enters a value in the field, it should automatically append a ".00" to the end of the number.
i.e. 
Initially input field will be blank.
Value entered by user: 6
Value shown to user: 6.00

Can you help me out?

**Comment by RobinHerbots** [comment]
@gaganshera , 

That's the way the above mask should work, as the  clearMaskOnLostFocus: true, is by default true.
But I see that's not the case.  It initially shows the 0.00.

I will fix that.

**Comment by gaganshera** [comment]
@RobinHerbots ,
thanks for the quick reply.
I was able to get it to work but only by providing a non-empty prefix in the options.
Here's a jsfiddle link:
http://jsfiddle.net/gaganshera/tfe6esyq/

Hope its of some help.

**Comment by RobinHerbots** [comment]
@gaganshera , 

Thx for the info & jsfiddle.

**Comment by RobinHerbots** [comment]
fixed in the latest commit (entry with radixpoint)
