### ISSUE TITLE
decimal mask infinite loop (readonly input)

### ISSUE THREAD

**Issue by manrueda** [RobinHerbots/Inputmask#603]
Hi, recently i make an update of plugin in mi site and one of my decimal declarations now gets into an infinite loop when the input tag have the readonly attribute.

Here a JSFiddle example: http://jsfiddle.net/8dp27wem/

Here is the declaration:

``` javascript
this.control.inputmask({
    alias: "decimal",
    autoGroup: true,
    digits: 2,
    groupSeparator: ".",
    groupSize: 3,
    integerDigits: 50,
    radixPoint: ","
});
```

Anyone know how to solve this or another way to get it work?
Thanks!!

**Comment by RobinHerbots** [comment]
@ManRueda , 

In which browser did you test as I don't see the problem in FF or Chrome.

**Comment by manrueda** [comment]
@RobinHerbots 
I'm working on Chrome 36.0.1985.125 over Windows.

EDIT: I'm sorry, the example was incorrect, the bug happen but not with that example. I'm working in another example.
Thanks.

EDIT 2: I can't recreate the bug in JSFiddle or in another example. Only happen in my code. I rollback to a previous version of the plugin and not have this problem. Do what do you want with the issue, close it or something.
Sorry for the waist of time..
Thanks!!

**Comment by RobinHerbots** [comment]
I found an infinite loop for the decimal extension, but i'm still searching for the cause. So issue stays ipen ;)

**Comment by manrueda** [comment]
Great, i keep watching the issue for updates....

Thanks.-

**Comment by RobinHerbots** [comment]
@ManRueda , 

Latest version should fix the infinite loop
