### ISSUE TITLE
Multiple Masks - Paste / Reset Form

### ISSUE THREAD

**Issue by ghost** [RobinHerbots/Inputmask#604]
Hello Robin. I just found 2 possible bugs:
1. When using Multiple Masks, we can't paste on the field (try this value: "65.303.734/0001-95").
2. When using Multiple Masks, and we reset the form, the values on fields with Multiple Mask will appear on mouseover.

Example:
http://codepen.io/anon/pen/LJDtf

Thanks

**Comment by RobinHerbots** [comment]
@spacelab-x , 

The current implementation of multiple masks is just a temporary solution to be compatible with inputmask 2.x.

I'm working on the alternator syntax which will replace the current implementation.

**Comment by spacelab-sp** [comment]
Hello Robin, there is no more a "Multiple Masks JS", your implementation is done?

I tried with the new JS and Multiple Masks seems that is not working anymore as before. Or I need another JS?

http://codepen.io/anon/pen/Dkuxz

In the example I have the mask ['9999-9999', '99999-9999'].
But when I fill the field, 8 digits become: 99999-999

**Comment by RobinHerbots** [comment]
You need to specify the keepStatic option see the readme

**Comment by spacelab-sp** [comment]
I tried, worked a bit... but, when I type 99999-9999 and delete some numbers the mask don't update, and stay 99999-999, the correct would be 9999-9999. In the old multiple masks works :(

Is this a thing to work on or is working as espected?

**Comment by RobinHerbots** [comment]
@spacelab-x , 

The more I think about, I agree.  When deleting, the mask should revert if possible.
So I will fix that, 
For now the mask switches when you delete until the "decisiontaker".  Anyway, you can still use the inputmask-multi code.  You will find it in legacy, althought the new alternators work much better and also allow all other functionality of the inputmask. (callbacks etc..)

**Comment by penihel** [comment]
Anything new? I'm having this problem with an application in production

**Comment by RobinHerbots** [comment]
@spacelab-x , @penihel , 

Ok I guess it"s about time to start fixing this ;-)

**Comment by spacelab-sp** [comment]
I'm glad that you have not forgotten :+1: 

Thanks Robin

**Comment by RobinHerbots** [comment]
@spacelab-x , 

Fixed in the latest commit.

**Comment by err0x1a** [comment]
Great Robin, is working!

Well, thanks again for your dedication, soon I will donate a bit more for the project.

**Comment by RobinHerbots** [comment]
okido, .. how many names do you have?  ;-)

**Comment by err0x1a** [comment]
haha, sorry... I have two, spacelab-x is for the company where I work.
