### ISSUE TITLE
Date Alias highlighting first character when selected

### ISSUE THREAD

**Issue by mjortman** [RobinHerbots/Inputmask#606]
Hi - I apologize if this has been mentioned before, but a quick search didn't turn up anything.

I am using the "alias: mm/dd/yyyy" for a date mask, and when doing so it highlights the first "m" when the box gets focus. Normally this is no big deal, but on iPhone 5's after the highlight you are prompted with the Cut/Copy/Paste dialog. I don't see any other mask selecting the first character the way this does, so I wondered if there was something I could do to turn it off. 

This occurs in the JSFiddle that you pointed someone to in #550 as well.

Thanks!

**Comment by RobinHerbots** [comment]
@mjortman , 

Set the insertMode: true option.  It is for marking the overwrite mode.  You can also toggle the option by pressing the insert key.

**Comment by mjortman** [comment]
Thanks for the quick response. I apologize for my delay.

This worked perfectly, both on the mobile browsers I tested, and the desktop. Thanks again!
