### ISSUE TITLE
Email Address Mask sends test@local.__

### ISSUE THREAD

**Issue by henriquelbsouza** [RobinHerbots/Inputmask#608]
I am trying to add a local mail address such as "user@localserver" but he sends user@localserver.__ because of the mask.

I should be able to send "user@localserver".

Best regards,
Henrique

**Comment by henriquelbsouza** [comment]
Just to you know, adding [] in the '.com' part will solve.

Like that:

``` javascript
"email": {
            mask: "*{1,20}[.*{1,20}][.*{1,20}][.*{1,20}]@*{1,20}[.*{2,6}][.*{1,2}]",
            greedy: false,
            onBeforePaste: function (pastedValue, opts) {
                pastedValue = pastedValue.toLowerCase();
                return pastedValue.replace("mailto:", "");
            },
            definitions: {
                '*': {
                    validator: "[0-9A-Za-z!#$%&'*+/=?^_`{|}~\-]",
                    cardinality: 1,
                    casing: "lower"
                }
            }
        }
```

Is that right? I could fix it and commit if you wish.

**Comment by henriquelbsouza** [comment]
Here is an example.
http://jsfiddle.net/p4z4zfxz/1/

**Comment by RobinHerbots** [comment]
@henriquelbsouza , 

You are right!  Thx for the pull request.

There are also other cases to consider like jsmith@[192.168.2.1].

**Comment by henriquelbsouza** [comment]
@RobinHerbots,

true... do you have any example of an extension that can validate multiple masks? if you have, I can try to fix that too :smile: 

Sorry but I am not very familiar with JS and jQuery or regex... hehe

**Comment by RobinHerbots** [comment]
See issue #612
