### ISSUE TITLE
Alternator mask with keepStatic option cannot switch to an alternative at the end

### ISSUE THREAD

**Issue by RobinHerbots** [RobinHerbots/Inputmask#612]
See  console.log("try alternate match"); in jquery.inputmask.js

ex:

 $("#test2").inputmask({ mask: ["+55-99-9999-9999", "+55-99-99999-9999", ], keepStatic: true });

typing 1212345123 => should result in +55-12-1234-5123
type extra 4 => switch to +55-12-12345-1234

Without the keepStatic option you make the decision while you type as with optional masks.
type 1212345123 => +55-12-12345-123_
type 121234-5123 => +55-12-1234-5123

**Comment by lmbelo** [comment]
Looks great. I'm going to try it.

**Comment by RobinHerbots** [comment]
@lmbelo , 

Not too fast.  Wait until this issue is fixed.

**Comment by lmbelo** [comment]
Hahaha... Waiting for release.

**Comment by henriquelbsouza** [comment]
:+1: I had this problem using JQuery MaskedInput a while ago.

I don't know if this helps you:
http://jsfiddle.net/3xvxq0wj/1/ (with your example +55-99-99999-9999)
cheers.

**Comment by RobinHerbots** [comment]
@henriquelbsouza , 

No, that solution works but is just a specific case.  I want a generic solution which can handle multiple cases.  Something like I did with jquery.inputmask-multi (see in legacy), but then better ;-)

**Comment by henriquelbsouza** [comment]
Yes, that was my solution for Brazilian São Paulo cellphone numbers that added a new digit in front of the others... 

Well, if you need anything let me know.
