### ISSUE TITLE
Decimal mask error alert

### ISSUE THREAD

**Issue by manrueda** [RobinHerbots/Inputmask#615]
Hi, i'm trying the last commit, because fix the #603  issue, and now when i create the mask the plugin gives me this message.

**jquery.inputmask: There is probably an error in your mask definition or in the code. Create an issue on github with an example of the mask you are using.**

``` javascript
    function (m) {
        var m, l = (m = m.split("")).length, s = this.split(""), j = 0, h = "";
        for (var i = -1; ++i < l; )
            if (m[i] != "#") {
                if (m[i] == "\\" && (h += m[++i])) continue;
                h += m[i];
                i + 1 == l && (s[j - 1] += h, h = "");
            }
            else {
                if (!s[j] && !(h = "")) break;
                (s[j] = h + s[j++]) && (h = "");
            }
        return s.join("") + h;
    }
```

The mask definition it's the same of the las issue:

``` javascript
    control.inputmask('decimal', {
        autoGroup: true,
        digits: 2,
        groupSeparator: ".",
        groupSize: 3,
        integerDigits: 50,
        radixPoint: ","
    });
```

**Comment by RobinHerbots** [comment]
@ManRueda , 

Great and not great!  

Not great that your mask still has the infinite loop and great that the plugin can detect  the issue.

I will do some more testing with your mask.  Can you reproduce it in a simple html page?

**Comment by manrueda** [comment]
I found a few things, the mask definition isn't the problem, even in my system in another page i have the same mask and works well, and in the problematic page every mask crash, even a simple 'decimal'.
My site load pages dynamically by AJAX in modal windows, the first load a date mask works perfect but if y close and open that modal the mask crash.

The plugin keeps some kind of cache or relation with the DOM objects?

**Comment by RobinHerbots** [comment]
@ManRueda , 

That is interesting.  Maybe the $.inputmask.masksCache.

Maybe try to reproduce with a fiddle which creates an input with an inputmask destroy and recreate.

Just tried to reproduce with adding input with inputmask dynamically but it keeps working.

**Comment by manrueda** [comment]
I tried too, with differents methods to remove and create the objects. And works well...

**Comment by manrueda** [comment]
Hi Robin, I'm going crazy... The second time i run inputmask, no matter the object where i run it, the mask definition is the problem. If i run the same defininion over another object the error throw aswell.

There are some kind of method to clean the plugin or something like that? I remove the masksCache of that declaration but then crash.

**Comment by RobinHerbots** [comment]
@ManRueda ,

Can you simulate the problem in an example?  If not, can you put your site online, so that I can have a look.

What other plugins do you use?  version jquery?

**Comment by manrueda** [comment]
@RobinHerbots ,

I spent the last few hours trying to reproduce the error in JSFiddle but i can't.
I can't put the site online, it's a members sites and because the security policy i can't.

I'm using jQuery 1.11.0 // jQuery Migrate Plugin 1.2.1 // jQuery UI 1.10.4 // Kendo UI 2013.3.1119

Sorry can't help you more...

**Comment by RobinHerbots** [comment]
@ManRueda , 

Can you send a stripped down version of the site?  One page?
Are you using some extensions on some prototypes?  array?  object? string?

**Comment by manrueda** [comment]
@RobinHerbots ,

In the night i'm going to try to make an simple version....

What do you mean with "extensions on some prototypes?". In the inputmask object or in general?

**Comment by RobinHerbots** [comment]
@ManRueda, 

Ok,
Extensions on native javascript objects in general.

**Comment by manrueda** [comment]
@RobinHerbots ,

i can't do anything last night... sorry.
I have a few (no overwrited) functions on Number's prototype, but take it off and the error still there.

**Comment by RobinHerbots** [comment]
@ManRueda , 

No problem.

I keep your issue for the last to solve before releasing 3.1 ;-)

**Comment by manrueda** [comment]
@RobinHerbots ,

I'm so sorry Robin, you lost a lot of time searching for this bug....
I found a prototype change on String's object, the mask function. i'm going to kill somebody here... hahaha

There is no bug, only a diabolic function in my code...

**Comment by RobinHerbots** [comment]
@ManRueda , 

;-)  I'm glad that you found it!!

Can you maybe share the prototype change on the string object, so I can maybe prevent this or make my code more robust.

**Comment by manrueda** [comment]
@RobinHerbots 

Here you got the function, obviously somebody copy and paste this function from some forum... hehe

``` javascript
String.prototype.mask = function (m) {
        var m, l = (m = m.split("")).length, s = this.split(""), j = 0, h = "";
        for (var i = -1; ++i < l; )
            if (m[i] != "#") {
                if (m[i] == "\\" && (h += m[++i])) continue;
                h += m[i];
                i + 1 == l && (s[j - 1] += h, h = "");
            }
            else {
                if (!s[j] && !(h = "")) break;
                (s[j] = h + s[j++]) && (h = "");
            }
        return s.join("") + h;
    };
```

Thanks a lot!!

**Comment by RobinHerbots** [comment]
@ManRueda , 

Huh??? That is the minified mask definition from the numeric alias?
Did you found that in the prototype or in your code?

```
$.extend($.inputmask.defaults.aliases, {
    'numeric': {
        mask: function (opts) {
            if (opts.repeat !== 0 && isNaN(opts.integerDigits)) {
                opts.integerDigits = opts.repeat;
            }
            opts.repeat = 0;

            opts.autoGroup = opts.autoGroup && opts.groupSeparator != "";

            if (opts.autoGroup && isFinite(opts.integerDigits)) {
                var seps = Math.floor(opts.integerDigits / opts.groupSize);
                var mod = opts.integerDigits % opts.groupSize;
                opts.integerDigits += mod == 0 ? seps - 1 : seps;
            }

            opts.definitions[":"].placeholder = opts.radixPoint;

            var mask = opts.prefix;
            mask += "[+]";
            mask += "~{1," + opts.integerDigits + "}";
            if (opts.digits != undefined && (isNaN(opts.digits) || parseInt(opts.digits) > 0)) {
                if (opts.digitsOptional)
                    mask += "[" + ":" + "~{" + opts.digits + "}]";
                else mask += ":" + "~{" + opts.digits + "}";
            }
            mask += opts.suffix;
            return mask;
        },
```

**Comment by RobinHerbots** [comment]
@ManRueda , 

After some verification, no it is not, ... but it is the same code that the alert showed in the first message!!!

**Comment by manrueda** [comment]
@RobinHerbots ,
This function was in my code... Yes, it's the same, the plugin use this function name inside the plugin?

**Comment by RobinHerbots** [comment]
@ManRueda , 

No, but have a look at this !!

```
     } //hide placeholder with single non-greedy mask
            if (opts.mask["mask"] != undefined) {
                ms = generateMask(opts.mask["mask"].toString(), opts.mask);
            } else {
                ms = generateMask(opts.mask.toString());
            }
        }
```

It is allowed to pass an object with metadata like
{ "mask": "+32(47#)##-##-##", "cc": "BE", "cd": "Belgium", "city": "Mobile Phones" },

**Comment by manrueda** [comment]
@RobinHerbots ,

We never use metadata to pass the definition... But the same name of the function breaks the code.
Change my function's name and everything it's wonderful...

**Comment by RobinHerbots** [comment]
@ManRueda , 

I will adjust my code to take this into account, so all the grief gets his purpose ;-)
