### ISSUE TITLE
Text align input mask

### ISSUE THREAD

**Issue by ErikPham** [RobinHerbots/Inputmask#619]
Hi. I want input switching from text-align: right => text-align: left is how to do? Thank you

**Comment by RobinHerbots** [comment]
@PhucPM , 

I guess you mean the rightAlign option.  Set it to false.

**Comment by ErikPham** [comment]
Thank @RobinHerbots.
I am also a wonder anymore when I use jQuery to Submit Form then autoUnmask not work. However, when the Submit Button using it to work normally. Is there any way to solve the problem there?

**Comment by RobinHerbots** [comment]
@PhucPM , 

Fixed in version 3.1.4

**Comment by johnqiuwan** [comment]
rightAlign: false is not working

**Comment by RobinHerbots** [comment]
@johnqiuwan , 

Can you provide some more info about the mask you use and the options.  Also in which browser and OS.  I tested it here locally and it works fine.
