### ISSUE TITLE
Optional part update

### ISSUE THREAD

**Issue by corredor28** [RobinHerbots/Inputmask#626]
Steps to reproduce: http://jsfiddle.net/1e206jnc/2/
1. Fill in the masked input with a value without optional part (e.g. 3:44)
2. Focus elsewhere
3. Return to the masked input
4. Try to update to value with the optional part (like 33:44) without having to manually clear the input before

Is this the expected behavior? If so, is there any way to accomplish that?
Thanks!

**Comment by RobinHerbots** [comment]
@corredor28 , 

No that is not expected.  I will have a look at it.

I also updated your fiddle (ref to inputmask)  http://jsfiddle.net/1e206jnc/3/

**Comment by RobinHerbots** [comment]
@corredor28 , 

Fixed in version 3.1.6

**Comment by corredor28** [comment]
Cool, thanks!
