### ISSUE TITLE
Decimal Value for score grade - Value not mask correct when loading

### ISSUE THREAD

**Issue by lincolnpires** [RobinHerbots/Inputmask#627]
Hey Robin, 
First, congratulations for the plugin. The input masks seems to work awesomely.

I am facing a problem with decimal using alternator static masks:
When the default value is not set, it woks correcty.

![image](https://cloud.githubusercontent.com/assets/4206274/4002275/0e422d4e-296b-11e4-990b-48eb5b3b3d62.png)

But, when the value is loaded, it does not work as I wanted.

Here what I've done:

``` html
<input class="imt" type="text" value="2.2"></input>
<input class="imt" type="text" value="10"></input>
<input class="imt" type="text" value="10.0"></input>
<input class="imt" type="text" value="88"></input>
<input class="imt" type="text" value="0"></input>
```

``` javascript
$(document).ready(function(){
   $(".imt").inputmask({ mask: ["9,9", "99,9" ], keepStatic: true });
});
```

When the values are filled like that, it loads:
![image](https://cloud.githubusercontent.com/assets/4206274/4002258/dc2b6f28-296a-11e4-99fd-aedcbc600671.png)

Can you help me with this? Suggest something.

I am just testing the features to use in a project.
Best Regards, thank you.

**Comment by RobinHerbots** [comment]
@lincolnpires , 

I will have a look at it.

Why don't you use the numeric or decimal extension?

**Comment by lincolnpires** [comment]
Hey, thanks.

Hope I am using correctly the plugin.

I will try that! :+1: 

Success.

**Comment by RobinHerbots** [comment]
@lincolnpires , 

Can you retry the above with version 3.1.3

**Comment by lincolnpires** [comment]
Hello @RobinHerbots
Now it is working...
Thank you!

If I find any other issue to improve this plugin, I will let you know.

Best regards.
