### ISSUE TITLE
AMD Support in Ver 3.60

### ISSUE THREAD

**Issue by babupca** [RobinHerbots/Inputmask#629]
Hi Robin,

Some weeks before i took the latest bundle 3.0.60 ver to update to the old version from Ver 3.0.33. 

In 3.60 version, AMD support introduced, is not seems to be working. When i debug and checked, the jQuery object does not have the inputmask object in it.

it say jQuery.inputmask : is undefined

requirejs.config({
    baseUrl: 'js',
    paths: {
           jquery:'lib/jquery.min',
           mask:'lib/mask/jquery.inputmask.bundle'
    }
    shim: { //add the dependencies that should be loaded synchronously
            'mask': ['jquery'],  
    }

Do i need to do any other settings, to solve this problem..

Thanks
Babu A

**Comment by RobinHerbots** [comment]
@babupca , 

See issue #591.

You need to use the files in dist/inputmask when using requirejs (AMD).
The bundled file does not work for the moment in combination with AMD.  And also take version 3.1

**Comment by babupca** [comment]
Thanks Robin
