### ISSUE TITLE
date autocomplete error

### ISSUE THREAD

**Issue by manrueda** [RobinHerbots/Inputmask#630]
Hi @RobinHerbots ,

I have some problems with date's mask in Internet Explorer. (chrome works well). With the declaration 'dd/mm/yyyy' when i put for example a 3 into the first digit automatically assumes its a 03. I can't enter 3x numbers like 30 or 31.

Here is an example: http://jsfiddle.net/r8eLuwpo/

**Comment by RobinHerbots** [comment]
@ManRueda , 

Fixed in version 3.1.5

**Comment by manrueda** [comment]
Thanks @RobinHerbots !!! i'll try it tomorrow morning...
