### ISSUE TITLE
the mask does not reset to delete digits, mask adds two zeros to the right

### ISSUE THREAD

**Issue by link007** [RobinHerbots/Inputmask#631]
The mask does not reset to delete digits.

If I have a three digit number to edit and delete it to put only one, the mask adds two zeros to the right and the user has to delete them by hand. Note: I require capture currency type 

Ex: change from 100.00 to 5.00 

I have 100.00:

![screen shot 2014-08-25 at 10 09 16 pm](https://cloud.githubusercontent.com/assets/1317528/4040408/e88bed84-2ce3-11e4-909f-d5933953af7e.png)

delete three digits (100) until only (  .00) 

![screen shot 2014-08-25 at 10 09 57 pm](https://cloud.githubusercontent.com/assets/1317528/4040412/f0642ecc-2ce3-11e4-9e10-b73a328f0d3a.png)

after I write my new digit: 5, and the mask adds two zeros to the right

![screen shot 2014-08-25 at 10 10 21 pm](https://cloud.githubusercontent.com/assets/1317528/4040414/f7df0f64-2ce3-11e4-9f9d-481fd12daf7f.png)

same thing happens if I delete everything from right to left

thank you !

**Comment by RobinHerbots** [comment]
@link007 , 

Yes I know.  I will have a look at it.

**Comment by RobinHerbots** [comment]
@link007 , 

This is fixed

**Comment by link007** [comment]
Excellent! Thank you!!
