### ISSUE TITLE
Quint simulator js 

### ISSUE THREAD

**Issue by babupca** [RobinHerbots/Inputmask#632]
I wanted to use the Qunit Simulator, for testing the entire mask, which i have created. I used the require js to make Qunit masksimulator module to test all the mask.

So tired to use you simulator code in the require js. I added simulator in the path and depencey as jquery in the shim.

But still it is failing when it encountres the $.fn.type method, because of this, the value is always empty and it is failing.

if you have any suggestion, pls post.

**Comment by RobinHerbots** [comment]
@babupca , 

Post some example code as otherwise it is a bit guessing for a solution.

you need to pass jquery as $ in the function arguments.

**Comment by babupca** [comment]
Here is the code
1. The first test case works (the hello world case)
2. Second case fails, in the jQuery("#testmask").Type("00000");. It shows error as 
   Error
   Result :
   Expected: "0"
   Result:""
   Diff:"0"""

I have just placed your simulator code, in a seperate js and added it the require js path and in for the dependency as 'simulator:['jquery']

define(['jquery','codes','simulator','QUnit'], function(jQuery,codes){ 
    //load the Qunit CSS
    jQuery('head').append('<link href="http://code.jquery.com/qunit/qunit-1.14.0.css" rel="stylesheet" type="text/css" />');

```
QUnit.config.autostart = false;
QUnit.load();   

QUnit.test( "hello test", function( assert ) {
  assert.ok( 1 == "1", "Passed!" );
});
QUnit.test("numeric  type 00000 ", function () {
    var fixture = jQuery("#qunit-fixture");
    jQuery(fixture).append('<input type="text" id="testmask" />');
    jQuery("#testmask").inputmask({
        mask:"numeric", 
        groupSeparator: ",",
        autoGroup: true,
        integerDigits: 9
    });
    jQuery("#testmask").focus();        
    jQuery("#testmask").Type("00000");
    equal(jQuery("#testmask").val(), "0", "Result " + jQuery("#testmask").val());
    jQuery("#testmask").remove();
});

//Start the Qunit
QUnit.start();
```

});

**Comment by RobinHerbots** [comment]
The simulator.js just assumes that jQuery is mapped to $.  Make sure jquery is mapped to $.  There is no closure fn which pass jQuery to $ in the simulator.js.  

Maybe I should add that.

**Comment by babupca** [comment]
I think this i have done already, by wrapping your code with require js stuff. But still it did not return the value to the input field. so the test case fails. I'm still checking why this does not work. 

define(['jquery'], function($){ 
//Your simulator code. 
});

**Comment by RobinHerbots** [comment]
@babupca, 

In the simulator there where also some global definitions.  When you wrap them they aren't global anymore.  I updated the simulator.js and the tests.

Can you have another try.

**Comment by babupca** [comment]
sorry Robin. I was on a long week end for Ganapathy festival in india for three days. I will check that  today and let inform you.

**Comment by RobinHerbots** [comment]
@babupca , 

Relax, no problem! 
I just have googled at Ganapathi Bappa ;-)  I hope you enjoyed the festivities!

**Comment by babupca** [comment]
@RobinHerbots 

:) Yes Robin. This is the first (Ganasha) god to be worshipped in my religion, after that only other gods will follow (like shivaperumaan, muru god, perumal god etc). I really enjoyed three days with my family. 

I tested it now, but still i get the error. I tried to show up the require js, combined with the jquery inputmask in fiddle. but it is not working.  

My small request, if you have bit of time, please test mask with the requirejs. I also try to check what is the issue.  You can use the jsfiddle link, 

jsfiddle
http://jsfiddle.net/BA251281/bofxce7e/4/

**Comment by RobinHerbots** [comment]
@babupca , 

Try with http://jsfiddle.net/bofxce7e/6/

Just press run one more time if it doesn't load directly.

**Comment by babupca** [comment]
Thanks Robin. This worked.
