### ISSUE TITLE
Is white-space char as groupSeparator possible?

### ISSUE THREAD

**Issue by barthenry** [RobinHerbots/Inputmask#633]
Hello,
is it possible to have white-space character as groupSeparator? When I use something like this:

``` html
data-inputmask="'alias': 'decimal', 'groupSeparator': ' ', 'autoGroup': true"
```

I get weird behavior: I can type up to 3 digits, any digit more resets the whole input and I start up with only the last typed digit. Any other string character works well.

I have 3.0.4 version but I tested it with current as well.

**Comment by RobinHerbots** [comment]
@barthenry, 

In theory yes ;-)
, but you have to change the char of skipOptionalPartCharacter to another char.

I never tested it.

**Comment by Ettemlevest** [comment]
Hi Robin,

traditionally in Hungary we are using a white-space character for separating number groups. Thanks to your advice this plugin can represent numbers in Hungarian style. I changed the skipOptionalPartCharacter option to a character that I hope will not broke the functionallity.
But I just wanted to let you know that this can be possibly an issue in the future for others aswell.

**Comment by RobinHerbots** [comment]
@Ettemlevest , 

Thx for the info.  Maybe I can add that kind of logic into the decimal extension.  So that this works out of the box.

**Comment by RobinHerbots** [comment]
@barthenry , @Ettemlevest , 

The latest commit allows the groupSeparator : " " out of the box

**Comment by twg-group** [comment]
What about  this : ", " (comma with white-space)  why so poorly?

**Comment by RobinHerbots** [comment]
@twg-group , 

Hmm that never came to mind to allow a groupseparator of more then one char.  Let's make a new issue for this.
