### ISSUE TITLE
broken phone number

### ISSUE THREAD

**Issue by macklay** [RobinHerbots/Inputmask#635]
if im enter this numbers in input with phone input mask plugin: 126659859
masked input  show phone with only one bracket: +1(2665-9859
(this bug work too on demo page http://robinherbots.github.io/jquery.inputmask/)

please help

**Comment by RobinHerbots** [comment]
@macklay , 

What would be the correct phone number?  For which country?

**Comment by macklay** [comment]
@RobinHerbots,

Im try check this mask from phone-codes.json:
{ "mask": "+1(###)###-####", "cc": ["US", "CA"], "name_en": "USA and Canada", "desc_en": "", "name_ru": "США и Канада", "desc_ru": "" }

This mask allow "+1" and any 10 digits, and when Im try enter 126659859 - this numer must be allowed by this mask. But after 8 digit Im cant enter digits anymore and furthermore, see broken number with only one bracket

**Comment by RobinHerbots** [comment]
Hi Nick ,

I will have a look.

2014-09-02 7:30 GMT+02:00 Nick Smirnov notifications@github.com:

**Comment by RobinHerbots** [comment]
@macklay , 

The latest version allows for the input again.

**Comment by macklay** [comment]
@RobinHerbots, im trying latest version and version in demo page. My broken phone(126659859) worked in chrome, but still not worked correctly in firefox

**Comment by RobinHerbots** [comment]
@macklay , 

Strange, ... I guess the sorting isn't working properly in FF.  I will verify that.

**Comment by RobinHerbots** [comment]
@macklay, 

The current commit should fix the issue in FF.

Can you confirm.
