### ISSUE TITLE
inputmask( {alias: numeric} ) not being cleaned in Google Chrome and IE

### ISSUE THREAD

**Issue by lmbelo** [RobinHerbots/Inputmask#637]
I'm with some trouble when cleaning the folowing mask in Google Chrome and IE:

$(".container #input-number").inputmask({ alias: "numeric", groupSeparator: ".", groupSize: 3, radixPoint: ",", digits: 2, autoGroup: true, digitsOptional: false, placeholder: "0", rightAlignNumerics: true });

I have this routine to empty fields, set fields to "":

function clearFields(form){

```
$(':input', form).not(':button, :submit, :reset') .each(function(i,e){
        $(e).val( $(e).attr('value') || "").prop('checked',  false).prop('selected', false)
    }
)

$('option[selected]', form).prop('selected', true)
$('input[checked]',   form).prop('checked',  true)
$('textarea',  form).each(function(i,e) { $(e).val($(e).html()) })
```

}

function call:

  clearFields( $(".container #frm-data") );

I have tried to empty with $(".container #input-number").val(""), but same result.

In FireFox it works great!

Am I doing something wrong?

**Comment by RobinHerbots** [comment]
I will have a look at it

2014-09-03 16:56 GMT+02:00 lmbelo notifications@github.com:

**Comment by RobinHerbots** [comment]
@lmbelo, 

Can you put an example in a jsfiddle as I don't have a problem here.  Tested in Chrome

**Comment by RobinHerbots** [comment]
@lmbelo , 

Can you retry with the latest version
