### ISSUE TITLE
val('') function sets the empty mask

### ISSUE THREAD

**Issue by mtomas-mpm** [RobinHerbots/Inputmask#638]
Hi,

I've found an issue in version 3 of the control, when I set the empty value on the control, it sets the empty mask:
Sample on jquery.inputmask v3
http://jsfiddle.net/mftpfdn2/1/

On inputmask v2, it works as I expect:
http://jsfiddle.net/nrjeptfc/3/

I have found no method to clear completely the input, or any property to force this behavior, perhaps I could work with the autounmask and unmaskedvalue properties to solve the problem, but I've a lot of masks and  it's a bit work to clear only some of the mask chars for each, for example in a date, I only want to remove the mm, dd, .. strings but not the slash char, or in the fiddle sample, I would remove the _ chars but not the - when the mask is incomplete.

Thanks in advance,

Marc.

**Comment by RobinHerbots** [comment]
@mtomas-mpm, 

Fixed in version 3.1.11

**Comment by mtomas-mpm** [comment]
Great! Thanks a lot Robin! Temporally I've solved it using onunmask with similar code you posted! But I'll undo it to use the new version! Better!

Marc
