### ISSUE TITLE
Question about letter "s"

### ISSUE THREAD

**Issue by sverhagen** [RobinHerbots/Inputmask#639]
I do not understand why the following configuration lets me enter some numbers where the letter `s` should go?

```
{
    "definitions": {
        "_": {
            "validator": "."
        }
    },
    "mask": "ID: 9{+} Description: _{+}"
}
```

Expected input mask:

```
ID: _ Description: _
```

Actual input mask:

```
ID: _ De__cription: _
```

**Comment by RobinHerbots** [comment]
@sverhagen , 

This is because the s is defined as a definition in the date.extensions.

You have to escape the s by \\

"mask": "ID: 9{+} De\\scription: _{+}"

**Comment by sverhagen** [comment]
@RobinHerbots Thank you, that was really helpful.

You have crafted a great plugin, and that is much appreciated. Again, I say, much appreciated. But the entire experience would possibly be a little greater if you were able to spend a little bit of time on the documentation. Some things already were hard to understand, and this particular question I'm  unsure how I would have ever answered that from the existing documentation. But again, great work on the plugin!

**Comment by RobinHerbots** [comment]
@sverhagen,

This case is actually described in the readme, but I agree that I whould spend some time to documentation.  See issue #533
