### ISSUE TITLE
Credit Card Expiration Date

### ISSUE THREAD

**Issue by christianhaller** [RobinHerbots/Inputmask#64]
Hi Robin,
I need a mask like mm/yy (2 digits for month, 2 digits for year)

perfect:
date should be now or in the future

How can I set the cardinality for years to 2 digits?

**Comment by RobinHerbots** [comment]
Hi Christian,

You have to create a new defintion or adjust the defintion for y (year).
 You can find more info by looking at the date.extentions.

best regards,

Robin

2012/6/13 Christian Haller <
reply@reply.github.com

**Comment by christianhaller** [comment]
Thx Robin.
I made it :)

**Comment by RobinHerbots** [comment]
Maybe you can share your code so others can use it too?

2012/6/13 Christian Haller <
reply@reply.github.com

**Comment by christianhaller** [comment]
Sorry, I forgot this. I will post it today :)

**Comment by yevt** [comment]
@christianhaller Maybe now?

**Comment by sancao** [comment]
could you pls to share your code @christianhaller, i also need one like that?

**Comment by TerraTech** [comment]
@christianhaller Here, hold my tequila:
```javascript
$('#expires_mmyy').inputmask({alias: 'datetime', inputFormat: 'mm/yy'});
```
@yevt @sancao 
Hope that helps others trying to figure out how to work with formatting _datetime_.

**Comment by knoxcard** [comment]
@TerraTech - very nice!

I actually created this solution...

```
$('#cardExpiration').inputmask({
	mask: '9M/yY',
	definitions: {
		'M': {
			validator: '[0-9]'
		},
		'y': {
			validator: '[1-2]'
		},
		'Y': {
			validator: '[0-9]'
		},
	}
})
```

**Comment by knoxcard** [comment]
@TerraTech - you rock! I am now using your solution, in lieu of what I had before.

```
$('#cardExpiration').inputmask({
	mask: '9M/yY',
	definitions: {
		'M': {
			validator: '[0-9]'
		},
		'y': {
			validator: '[1-2]'
		},
		'Y': {
			validator: '[0-9]'
		},
	}
})
```

**Comment by knoxcard** [comment]
@RobinHerbots - any input in regards to adding a limited year range on this code...

```
$('#expires_mmyy').inputmask({alias: 'datetime', inputFormat: 'mm/yy'});
```

**Comment by knoxcard** [comment]
OH WOWZERS! Got date range to work!

```
$('#expires_mmyy').inputmask({
   alias: 'datetime', 
   inputFormat: 'mm/yy'
   min: '08/19',
   max: '01/30'
});
```

lets say you want a 10 year date range from today's date dynamically...

include the moment.js library...
```
https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js
```

then...
```
min: moment().add(1, 'M').format('MM/YY'),
max: moment().add(10, 'Y').format('MM/YY')
```
