### ISSUE TITLE
Question: How can I get the mask applied to an element?

### ISSUE THREAD

**Issue by jpirok** [RobinHerbots/Inputmask#640]
if I have an element:

< input id="maskedelement" type="text" >

and the following javascript:

$().ready(function() {
    $('#maskedelement').inputmask("999-999");
})

what line of code would I use later on to see the mask that is applied to #maskedelement?

Thanks!

**Comment by RobinHerbots** [comment]
@jpirok, 

So you want to retrieve the 999-999?

**Comment by jpirok** [comment]
Yes.

**Comment by jpirok** [comment]
The purpose of this is that I don't see a function for 'isValid' that I can use on an inputmask, like:

$('#maskedelement').inputmask('isValid')

so I need to use the inputmask static method:

$.inputmask.isValid($('#maskedelement').inputmask("getunmaskedvalue"), $('#maskedelement').inputmask("getmask"))

to get a true false on the current inputmask.

**Comment by RobinHerbots** [comment]
@jpirok , 
Can't you use the onComplete callback?

I will add the mask to the getmetadata fn

**Comment by jpirok** [comment]
Ok, so the onComplete callback implies/means that the mask has been
satisified.  I guess I didn't read it that way.  Thanks for your help!

On Mon, Sep 8, 2014 at 10:02 AM, Robin Herbots notifications@github.com
wrote:

> @jpirok https://github.com/jpirok ,
> Can't you use the onComplete callback?
> 
> I will add the mask to the getmetadata fn
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/RobinHerbots/jquery.inputmask/issues/640#issuecomment-54821699
> .

## 

Jason Pirok

**Comment by RobinHerbots** [comment]
@jpirok , 

You can get the mask by calling the getmetadata.
