### ISSUE TITLE
phone autocomplete leaves a 1

### ISSUE THREAD

**Issue by dudo** [RobinHerbots/Inputmask#641]
`$('.phone).inputmask("(999) 999-9999")` is behaving a bit oddly for me. When the browser tries to auto complete the phone number, all that is left is a 1.

![screen shot 2014-09-08 at 11 30 09 am](https://cloud.githubusercontent.com/assets/2963800/4190516/3e08f6a6-3786-11e4-8a32-d713934ab05e.png)

This is happening in 2 separate apps for me. Am I doing something wrong?

**Comment by RobinHerbots** [comment]
@dudo , 

See issue #386

**Comment by RobinHerbots** [comment]
Fixed in the latest commit.

Can you verify.

**Comment by Oikio** [comment]
@RobinHerbots similar behavior as @dudo described. Input mask is '999999999', autocomplete filled just last number.
Tested on Firefox 32.0.3 Windows 8 with jquery.inputmask 3.1.31.

**Comment by RobinHerbots** [comment]
@Oikio, 

Can you test with the dev version.  In version 3.1.31 does not contain the fix

**Comment by Oikio** [comment]
@RobinHerbots fills everything correctly, thanks.

**Comment by dudo** [comment]
Verified! You're a gentleperson and a scholar. More beer money en route.

**Comment by RobinHerbots** [comment]
@dudo , 

;-)
