### ISSUE TITLE
support for email Mask with subdomain in the address

### ISSUE THREAD

**Issue by babupca** [RobinHerbots/Inputmask#642]
Robin, I tried with the latest email mask available in inputmask extension. This seems to be not supporting the email with the sub domain. It is removing the some of the email address. May be we should change the mask below. 

mask: "_{1,20}[._{1,20}][._{1,20}][._{1,20}]@*{1,20}[._{2,6}][._{1,2}]",

babu@us.lufthansa.com 
email@subdomain.domain.com

jsfiddle link
http://jsfiddle.net/BA251281/vngkd5bs/10/

**Comment by babupca** [comment]
I have updated within my module 
jQuery.inputmask.defaults.aliases [‘email’].mask = new mask.

**Comment by RobinHerbots** [comment]
@babupca , 

I will update the alias, but didn't found the time todo so.

**Comment by babupca** [comment]
@RobinHerbots ,

I understand Robin. But many Thanks, for your continued effort to support us and develope the plugin more in your busy timings.
Just wanted to say, as per my knowledge, there is none other plugin in the market which has this much functionalities. Great plugin.

**Comment by RobinHerbots** [comment]
@babupca , 

Thx, ... just submitted the updated email-alias

**Comment by babupca** [comment]
Thanks Robin
