### ISSUE TITLE
Multiple masks doesn't work properly

### ISSUE THREAD

**Issue by necrosisoff** [RobinHerbots/Inputmask#643]
Robin, good day!

I've trying to do credit card number masked input. My config is `{"keepStatic":false,"mask":"(9{4}[ ]9{4}[ ]9{4}[ ]9{4})|(9{4}[ ]9{6}[ ]9[5])|(9{9}[ ]9{9})"}`. On focus in input I see right placeholders like `____ ____ ____ ____`, but while I typing mask transforms into somthig unexpectable like `123412341234 ____`. That I doing wrong?

Thanks

**Comment by RobinHerbots** [comment]
Hi Viktor,

Why do you add the optional spaces?  Better would be
 $("#test7").inputmask({"keepStatic":true,"mask":"(9{4} 9{4} 9{4}
9{4})|(9{4} 9{6} 9[5])|(9{9} 9{9})"});

But the alternation doesn't work!  I will have a look at that.

best regards,

Robin

2014-09-10 9:10 GMT+02:00 Viktor Donos notifications@github.com:
