### ISSUE TITLE
Mask causes problems in ie

### ISSUE THREAD

**Issue by senja006** [RobinHerbots/Inputmask#645]
nekinshop.ru. 
In the form (http://joxi.ru/cXURVP3JTJD8fOJ_UWA) click to book call (http://joxi.ru/43URVP3JTJDDfKnTuqo). Errors appear on the blank fields (http://joxi.ru/IHYRVIwyTJDpAr19v-E). Put the cursor in the first field (http://joxi.ru/UnYRVIwyTJCGedEqs34),  and then in a field where you installed the mask number, without having to fill the first field (http://joxi.ru/o3YRVIwyTJBweTkv098). Аnd here the problems begin. Тhe cursor is constantly jumping between these fields.  And the browser freezes

**Comment by RobinHerbots** [comment]
@senja006 , 

Which version do you use of the inputmask which version of IE and which masks with options are you using?

**Comment by senja006** [comment]
ie11, ie10. http://joxi.ru/gW8SVP3JTJDYfDx_BwQ. http://joxi.ru/QW8SVIwyTJDIApKLzn0

**Comment by RobinHerbots** [comment]
@senja006 , 

Can you simulate the problem in a jsfiddle.

**Comment by senja006** [comment]
can not reproduce this problem. Only online nekinshop.ru. I have all the validation is based on your plugin. And soon surrender the project

**Comment by RobinHerbots** [comment]
Can you try with the latest version.  I will have a look at nekinshop.ru (as far I can read it ;-) )

In which script are you setting the inputmask?

**Comment by senja006** [comment]
I have installed through Bower and thought that this is the last version of the plugin. It turns out there is. With the latest version of everything is working fine. In ie no errors. Thanks for the help.
http://joxi.ru/i-ASVP3JTJDafFgO_PQ. CodeKit can not determine the version of the plugin.

**Comment by RobinHerbots** [comment]
@senja006 , 

Great!
