### ISSUE TITLE
A dot (.) in Regex Causes Errors

### ISSUE THREAD

**Issue by barofusa** [RobinHerbots/Inputmask#647]
The following is a simple example of a regular expression as "[0-9]+.[0-9]".

Issue number #1:  Once the dot is typed, nothing can be updated to the left of the dot.

Issue number #2:  Using the backspace does not remove characters left of the dot, but just repeatedly copies the character over proceeding characters.

It appears the dot is treated differently than other characters.  Is there a flag or setting to remove this special functionality?

**Comment by RobinHerbots** [comment]
@barofusa , 

Is this about the regex alias?

**Comment by barofusa** [comment]
Sorry I am still a bit new to using the inputmask, but I believe the answer is yes.

Simple example : $('input').inputmask("Regex", { regex: '[0-9]+.[0-9]' })

**Comment by RobinHerbots** [comment]
@barofusa, 

No problem.  I will have a look at it.

**Comment by mzf** [comment]
You can use 

```
\\\.
```

 it works well!

**Comment by RobinHerbots** [comment]
@barofusa , 

Works in the current
