### ISSUE TITLE
Is there a method like $el.inputmask("destroy")

### ISSUE THREAD

**Issue by ghost** [RobinHerbots/Inputmask#648]
To prevent a memory leak i think we need a method like "destroy". Or i couldnt see it?

**Comment by RobinHerbots** [comment]
@hjunior81 , 

Try remove

**Comment by EvilJordan** [comment]
I know you just closed this, but remove does not remove all bound events from the input. It would be great if 'destroy' was added to completely remove everything bound to the element.

**Comment by RobinHerbots** [comment]
@EvilJordan , 

remove should already remove all events bound.  I will review the functionality

**Comment by RobinHerbots** [comment]
I see I am missing the submit and reset event on the form.

**Comment by EvilJordan** [comment]
Glad I could help! Thanks!
