### ISSUE TITLE
problem with "'+7 (999) 999-99-99'"

### ISSUE THREAD

**Issue by nnnx** [RobinHerbots/Inputmask#650]
i have html:

```
<input type="text" class="form-control phone" value="+7 (923) 123-45-67" name="staff[phone]"/>
<script>
    $(document).ready(function() {
        $('.phone').inputmask("mask", {"mask": "+7 (999) 999-99-99"});
    });
</script>
```

its work good,
but if value of input but when the input value starts with a number 7 - input becomes empty

examle: "+7 (705) 123-45-67"

**Comment by RobinHerbots** [comment]
@serious-andy , 

I will have a look, probably the value is filtered in checkval.  Maybe I should add an option to disable the intellicheck.

**Comment by nlfonseca** [comment]
I have the same problem.

**Comment by paveltyk** [comment]
Have this issue too.
The mask of "+375 (99) 999-99-99" would strip off all leading "3", "5" and "7".

**Comment by RobinHerbots** [comment]
Working on it
