### ISSUE TITLE
Error while typing a decimal number

### ISSUE THREAD

**Issue by manrueda** [RobinHerbots/Inputmask#652]
When i was typing a decimal number in a field with a simple decimal definition, the code throws a 'Invalid operand to 'in' : Object expected'

In the code (jquery.inputmask.numeric.extensions.js:148) i saw the line:

``` javascript
$.inArray(opts.radixPoint, maskset.buffer.join(''))
```

but i think must be something like this:

``` javascript
$.inArray(opts.radixPoint, maskset.buffer)
```

Because the buffer is an array and inArray only works with arrays and no with strings.
I done the change in my local code and it works, i was going to do a pull request, but i don't know how do you manage the grunt process.

**Comment by RobinHerbots** [comment]
Thx!!

I have submitted a patch with the change.

2014-09-17 16:22 GMT+02:00 Manuel notifications@github.com:

**Comment by YasserHosny** [comment]
I faced the same issue
