### ISSUE TITLE
Date and Time Mask, while inputting a date without a time

### ISSUE THREAD

**Issue by jamezamm** [RobinHerbots/Inputmask#654]
I have a date and time mask, the code is shown below:

``` javascript
$("#element").inputmask({
            mask: "1/2/y h:s:s",
            placeholder: "__/__/____ __:__:__",
            alias: "datetime",
            hourFormat: "24",
            showMaskOnHover: false
        });
```

Is there a way, that when the user inputs a **date without a time**, the time placeholder part (**hh:mm:ss**) is removed.
_In other words, I wish that the time portion is optional._

Thanks in advance.

**Comment by RobinHerbots** [comment]
Try with:

$("#element").inputmask({
            mask: "1/2/y [h:s:s]",
            placeholder: "**/**/____ **:**:__",
            alias: "datetime",
            hourFormat: "24",
            showMaskOnHover: false
        });

2014-09-18 9:52 GMT+02:00 jamezamm notifications@github.com:

**Comment by jamezamm** [comment]
Thanks for the swift reply. It worked.

Is there a way to refresh/update input mask? As I am using jquery date picker with input mask. 
After selecting a date, the time portion doesn't get removed immediately.

**Comment by jamezamm** [comment]
Solved. On datepicker select, I manually triggered the blur event of the field. Thanks again. Great plugin.

**Comment by jamezamm** [comment]
After inputting the date only. The time portion is being removed. But the time portion mask is being shown on hover, even while I have **showMaskOnHover: false**.

Any thoughts?

**Comment by RobinHerbots** [comment]
Use the greedy: false option

2014-09-18 10:27 GMT+02:00 jamezamm notifications@github.com:
