### ISSUE TITLE
Strange behavior while using delete key.

### ISSUE THREAD

**Issue by kot-lex** [RobinHerbots/Inputmask#655]
Hi Robin!

Thank you for your work of developing such a great plugin!
I've faced a strange issue with delete key. 
Here is jsfiddle: http://jsfiddle.net/yeswuuzg/ and gif screencast http://g.recordit.co/vs9wLAuEcY.gif
Steps to repoduce the issue:
Paste (or type) "12 OK 345678" into text field.
Then move your caret to the very beginning of the string and try to delete data with delete key. 
It will only delete first two characters.
Then, if you move caret to the end and try to delete everything with backspace, it will delete all but the last two characters.

Any suggestions?
Thanks,
Aleksei.

**Comment by kot-lex** [comment]
And one more thing thats's probably connected.
If you type two digits into text field then move caret to the begining and try to type anything it won't appear. Looks like issue with validation (result in onKeyValidation callback is false while the character is correct and fits the mask)

**Comment by kot-lex** [comment]
The issue from the last comment only appears when i use custom definition.

**Comment by RobinHerbots** [comment]
@kot-lex , 

I updated the jsfiddle a bit to make it more clear why the delete stops and other things are happening.
http://jsfiddle.net/yeswuuzg/2/

I will have a further look at it.

**Comment by kot-lex** [comment]
@RobinHerbots, 
Thank you! It's definetly more clear now.
I suppose it's will be possible to override that logic in a custom validator function, isn't it?
