### ISSUE TITLE
Stop limiting length of email prefix

### ISSUE THREAD

**Issue by ostrolucky** [RobinHerbots/Inputmask#656]
Please stop limitting length of email prefix to 20 chars. Maybe change it's mask from
`mask: "*{1,20}[.*{1,20}][.*{1,20}][.*{1,20}]@*{1,20}[.*{2,20}][.*{2,6}][.*{1,2}]",`
to 
`mask: "*{1,}[.*{1,}][.*{1,}][.*{1,}]@*{1,20}[.*{2,20}][.*{2,6}][.*{1,2}]",`?

I don't see a point in limiting it, as now you can't type in e-mails like alexandra.schwarzbacherova@domain.com

**Comment by JCMais** [comment]
It should be 64 btw. http://tools.ietf.org/html/rfc5321#section-4.5.3.1

Related: http://stackoverflow.com/questions/386294/what-is-the-maximum-length-of-a-valid-email-address

**Comment by RobinHerbots** [comment]
@gadelat , @JCMais , 

I know the email alias is not fully compliant yet.  There are still some limitation in the use of quantifiers in combinaton of optionals with quantifiers inside.

For now I will just put the length to 64.

**Comment by RobinHerbots** [comment]
@gadelat, @JCMais , 

Modified the length.
