### ISSUE TITLE
onhover for the decimal mask placeholder

### ISSUE THREAD

**Issue by babupca** [RobinHerbots/Inputmask#657]
If i use the decimal mask with the place holder, the placeholder is always shown.. and the value is setting by default in the text field. 

Just want to know is it possible to show the place holder (0.000) value only on focus similar like the flno mask in the jsfiddle. Currently i tried to use showMaskOnHover: true, showMaskOnFocus: true both, but it is not working for the decimal masks.It is working only for the mask (9)

jsfiddle link
http://jsfiddle.net/BA251281/ug16s3tw/5/ 

```
$("#item1").inputmask({
    alias:"decimal",
    integerDigits:6,
    digits:3,
    allowMinus:false,        
    digitsOptional: false,
placeholder: "0"
});    
$("#flno").inputmask({
    mask:'9',
    repeat:4,
    placeholder:"0000",
    numericInput: true,
    rightAlign: true
});
```

**Comment by RobinHerbots** [comment]
@babupca , 

I will fix that.

**Comment by babupca** [comment]
Thank you.

**Comment by RobinHerbots** [comment]
@babupca , 

The latest commit fixes the issue.
