### ISSUE TITLE
Normal and minified bundle

### ISSUE THREAD

**Issue by thiagotalma** [RobinHerbots/Inputmask#658]
I do not know the reasons you have changed the configuration to generate just a bundle file minified. 

This is not ideal. Development need to debug something and only with the minified file is impossible. 

I suggest you generate the 2 files, normal and minified .

**Comment by RobinHerbots** [comment]
@thiagotalma , 

Hmm, yes, ... i should leave minification up to the dev using the lib actually.

It's due to the new build with grunt & uglify task.  , ... I will change it.

**Comment by thiagotalma** [comment]
@RobinHerbots  The idea was to have the two versions of the file   :smirk:

The original file for the development and minified for production.

**Comment by RobinHerbots** [comment]
@thiagotalma , 

I know ;-)

Fixed!

**Comment by thiagotalma** [comment]
:+1:
