### ISSUE TITLE
cutting does not remove value

### ISSUE THREAD

**Issue by zakness** [RobinHerbots/Inputmask#659]
When trying to perform a cut event on an input, the value is not removed.

http://jsfiddle.net/zakness/kLhttc7s/

Tested in Firefox, Chrome, and Safari.

**update:** on Mac

**Comment by RobinHerbots** [comment]
@zakness , 

Do you mean a cut bu rightclick select cut?  CTRL-X works.

**Comment by kot-lex** [comment]
@RobinHerbots I have the same issue. Cut doesn't work when I call it from context menu or in mobile browser (safari on ios).

**Comment by RobinHerbots** [comment]
@zakness , @kot-lex , 

Yep, right click select cut is not handled.

I will fix that.

**Comment by zakness** [comment]
@RobinHerbots I haven’t tested this on Windows yet, but on Mac both right-click _and_ cmd+X do not work.

**Comment by kot-lex** [comment]
@RobinHerbots I've found that cut doesn't work correctly even with ctrl+x. It "cuts" value from the field, but clipboard remains empty. 
When I'm trying to cut text via context menu the result is the opposite: text is copied to clipboard, but still present in the field.

Tested in Chrome, Firefox, IE11 on Windows 8.

**Comment by RobinHerbots** [comment]
@kot-lex , 

Thx for the feedback.  I will implement this when time allows.

**Comment by RobinHerbots** [comment]
@zakness , @kot-lex , 

can you have a test with the latest commit.

**Comment by zakness** [comment]
works great, thanks!
