### ISSUE TITLE
Error thrown when using onBeforePaste

### ISSUE THREAD

**Issue by zakness** [RobinHerbots/Inputmask#660]
1. Include `onBeforePaste` option in call to `inputmask()`
2. Try pasting something into the masked input

```
TypeError: undefined is not an object (evaluating 'pasteValue.split')
```

http://jsfiddle.net/zakness/jwwactrw/

Commenting out the `onBeforePaste` option removes the issue.

Tested in Firefox, Chrome, and Safari.

**Comment by RobinHerbots** [comment]
@zakness , 

The onbeforepaste must return a value, ... anyway I patched it to check for a return.  And updated the readme

**Comment by zakness** [comment]
Ah, thanks!
