### ISSUE TITLE
Feature request: add a few more callbacks like onKeyPress

### ISSUE THREAD

**Issue by kot-lex** [RobinHerbots/Inputmask#661]
Hi! 

I've been trying to fix a bug with delete key described in https://github.com/RobinHerbots/jquery.inputmask/issues/655 in an onKeyDown callback. But I've realized that onKeyDown is being called when keydownEvent has already been handled the pressing of the delete key.

Is there a possibility to add callbacks for all key events (keyPress, keyDown, keyUp), which will be executed before inpumask keypressEvent, keydownEvent, keyupEvent  functions?

Solution migth look like that:

``` javascript
            function keypressEvent(e, checkval, k, writeOut, strict, ndx) {
                //Safari 5.1.x - modal dialog fires keypress twice workaround
                if (k == undefined && skipKeyPressEvent) return false;
                skipKeyPressEvent = true;

                var input = this, $input = $(input);

                e = e || window.event;
                var k = checkval ? k : (e.which || e.charCode || e.keyCode);

/**************** NEW CALLBACK ******************************/
                var currentCaretPos = caret(input);
                var keypressResult = opts.onKeyPressBefore.call(this, e, getBuffer(), currentCaretPos.begin, opts);
                handleOnKeyResult(input, keypressResult, currentCaretPos);

                //prevent further execution of keypressEvent
                if  (typeof keypressResult === 'object' && keypressResult.stop)
                {
                    return false;
                }

                ....

```

Thank you!

**Comment by RobinHerbots** [comment]
You can bind to the events.

**Comment by kot-lex** [comment]
@RobinHerbots Yes, I can. But I'd like to get access to the inputmask data like buffer, caret postition, etc.

**Comment by RobinHerbots** [comment]
@kot-lex , 

Issue #655, does not need to be solved by manipulating the keydown or keypress events.  The behavior is causes by a position mismatch due to the empty placeholder. The caretposition should be corrected to the position as if there where a placeholder.  

Another possible fix is to use a custom definition which contains the logic to fix the above.

**Comment by kot-lex** [comment]
@RobinHerbots 
As I can see, problem in that issue is a bit deeper.
The behavior is extactly the same with non-empty placeholder. 
Check out this fiddle: http://jsfiddle.net/yeswuuzg/3/

**Comment by RobinHerbots** [comment]
@kot-lex , 

See http://jsfiddle.net/yeswuuzg/4/
You need to specify the same definitionsymbol for the new definition as definition 9 to allow shifting values over.  The deletes in the updated fiddle both work.  But the Z definiton also allows other chars then the 9 def.  In that case the shifting is not allowed.
