### ISSUE TITLE
when empty input and remove mask and apply the mask again the mask is not good

### ISSUE THREAD

**Issue by zehunter** [RobinHerbots/Inputmask#662]
Hi,

i try to use a check box to enable/disable 3 fields (type=text) or enable them.

mask is like this : 

 $("#multi_1").inputmask("€ 999 999,99", {numericInput: true,"placeholder": " "});

==> i can see "€     ,   " in field.

my code is quite simple like this : 
             if(this.checked)
                    {
                        $("#multi_1").removeAttr('disabled');
                        $("#multi_2").removeAttr('disabled');
                        $("#multi_3").removeAttr('disabled'); 
                        $("#multi_1").inputmask("€ 999 999,99", {numericInput: true,"placeholder": " "});
                        $("#multi_2").inputmask("€ 999 999,99", {numericInput: true,"placeholder": " "});
                        $("#multi_3").inputmask("€ 999 999,99", {numericInput: true,"placeholder": " "});
                    }
                    else
                    {
                        $("#multi_1").inputmask('remove');
                        $("#multi_2").inputmask('remove');
                        $("#multi_3").inputmask('remove');  
                        $("#multi_1").val('');
                        $("#multi_2").val('');
                        $("#multi_3").val('');
                        $("#multi_1").attr('disabled','disabled');
                        $("#multi_2").attr('disabled','disabled');
                        $("#multi_3").attr('disabled','disabled');  
                    }

but first time i disable and enable with the checkbox the mask is not correct :
==> i can see "     ,  €" in field.

next time i click and click again (disable then enable) mask is correct again : 
==> i can see "€     ,   " in field.

any idea why???

**Comment by RobinHerbots** [comment]
@zehunter , 

I will have a look at it.

**Comment by zehunter** [comment]
thx!

**Comment by zehunter** [comment]
Hi,

just wanted to know if you have any clue about this problem, and if you will be able to fix it.

regards,

**Comment by RobinHerbots** [comment]
@zehunter , 

I just tested it but see no problem.  Is this in a specific browser?  Can you make a jsfiddle which shows the problem.

best regards, 

Robin

**Comment by zehunter** [comment]
i will do it this week end no problem :) maybe some additionnal
framework/Jquery plugins conflict
