### ISSUE TITLE
keepStatic does not work with certain patterns

### ISSUE THREAD

**Issue by markbrouch** [RobinHerbots/Inputmask#663]
When using multiple masks, I found that `keepStatic` does not work with certain mask patterns.

`"mask": ["99-9999-99","99-99999-99"]` works as expected, allowing for an optional 7th digit by making the middle group length 5 instead of 4.

`"mask": ["99-99999-9","99-999999-9"]` (moving the second dash over 1 space) does not allow user to input a 7th digit.

**Comment by RobinHerbots** [comment]
@markbrouch , 

I will have a look

**Comment by RobinHerbots** [comment]
@markbrouch , 

The above pattern now works.  It is possible that there are other masks which won't work.  But keep reporting so that I can fix them overtime.

Best regards, 

Robin

**Comment by markbrouch** [comment]
Great thanks! I found another pattern which I will open a new issue for.
