### ISSUE TITLE
Mask does not work on input type="tel"

### ISSUE THREAD

**Issue by markbrouch** [RobinHerbots/Inputmask#664]
When using `input`s with attribute `type="tel"` input masks will not be applied.

**Comment by RobinHerbots** [comment]
@markbrouch , 

Only if the browser supports the input type, the mask is not applied.  So this is expected.

**Comment by markbrouch** [comment]
This seems like a bad approach. How would you suggest applying a phone mask to a field in modern browsers and still be able to use the `type="tel"` attribute so that mobile users get the correct keyboard?

**Comment by RobinHerbots** [comment]
@markbrouch , 

It is a lack of time approch.  I added inputtype tel to the supported types.  Can you have a test and give some feedback.

**Comment by markbrouch** [comment]
Works great, thanks for your quick response!

When can I expect to get this feature in a bower update?

**Comment by RobinHerbots** [comment]
@markbrouch , 

It will be available on bower today or monday.

best regards, 

Robin

**Comment by kunaldhoot** [comment]
Input type tel is not working for Iphone.

**Comment by RobinHerbots** [comment]
@kunaldhoot , 

Please do some more effert then just noting that it doesn't work.

IOS version?  Inputmask Version?  Which mask?  Create a codepen of jsfiddle with an example.  Open a new issue.
