### ISSUE TITLE
Multiple Mask - Can't add another char if leave the input

### ISSUE THREAD

**Issue by spacelab-sp** [RobinHerbots/Inputmask#665]
Hi Robin,

if the first part of the mask is completed, and I leave the input, It's not possible to add another char, only if I delete some value.

See the example:
http://codepen.io/anon/pen/feDtI

**Comment by RobinHerbots** [comment]
@spacelab-x , 

I don't have a problem here (chrome)  On which browser did you test?

**Comment by spacelab-sp** [comment]
Hmm, sorry Robin, try now adding the value on the begin? (here is Chrome too..)

**Comment by RobinHerbots** [comment]
@spacelab-x , 
Ok, but that is another case.  So you fill in mask1, put the caret to the top and try typing again.  That is because the alternation is not triggered in that case.

I can fix that.

**Comment by spacelab-sp** [comment]
Ok, thanks!

You must have more important things to solve, do on your time.
This is not a bug that cause much problems.
