### ISSUE TITLE
The problem of input in mask "decimal"

### ISSUE THREAD

**Issue by hapcoun** [RobinHerbots/Inputmask#666]
Hello
Sorry for my English
I use a inputmask "decimal". There is a problem. When you edit a number and if after this number 0 - it disappears. 
For example: 
2 000 000 
Select the 2 and enter another number, for example 3. 
Result 300 000 
And so on 
40 000 
2 000 
100 
50 
2

**Comment by RobinHerbots** [comment]
@hapcoun , 

I will have a look.

**Comment by RobinHerbots** [comment]
@hapcoun, 

Fixed in the latest version
