### ISSUE TITLE
Can I make mask for the Time format?

### ISSUE THREAD

**Issue by abhishekbhalani** [RobinHerbots/Inputmask#667]
I have started use this plugin. In my application there is time format like eq. 12:40 AM OR 12:25 PM

so how can I mask on text box.. can you pls reply me.

**Comment by RobinHerbots** [comment]
Try with

$(selector).inputmask("'hh:mm");

2014-09-25 14:12 GMT+02:00 Abhishek notifications@github.com:

**Comment by RobinHerbots** [comment]
Use hh:mm t

**Comment by abhishekbhalani** [comment]
thanks Robin, but I test with given format "hh:mm t" mask http://jsfiddle.net/89pa2w7m/2/
can you check it please.

**Comment by RobinHerbots** [comment]
Check this updated fiddle http://jsfiddle.net/89pa2w7m/3/

2014-10-01 15:41 GMT+02:00 Abhishek notifications@github.com:
