### ISSUE TITLE
Wishlist: changelog

### ISSUE THREAD

**Issue by Talkless** [RobinHerbots/Inputmask#669]
I am currently resuming some suspended project which uses 2.5 version, and I noticed that there are no changelog is this project. It would be nice to have changelog at least from now on... It's kinda feels risky to upgrade without looking through (possibly) braking changes.

**Comment by RobinHerbots** [comment]
@Talkless , 

Can't you have a look at the commits.  That is a changelog ;-)

**Comment by RobinHerbots** [comment]
You can click on the release and then you see the commits for that release.
