### ISSUE TITLE
Limiting the values in the between 0-100.00 

### ISSUE THREAD

**Issue by babupca** [RobinHerbots/Inputmask#670]
Is there any option in numeric or decimal mask by which we can limit the values between 0-100 for the decimal mask or numeric mask. When i checked the mask plugin, i don't see any such options. In future is there any possibility of adding it.

I'm aware that, we can use the regex to achieve this requirement. But want to know whether is there still any possible options in our mask plugin.

$(targetField).inputmask({
       mask:"Regex",
       regex:"(100)|(0*\d{1,2})+(.[0-9][0-9]?)"
});

Suppose decimal mask contains the integerDigits:3 and digits:2.
In this case, the user's can set the limitation of the numbers as per their wish.  so here i wanted to 
limit from 0 - 100 for integerDigits and .0-99 for decimal digits.

Finally -  100.99

**Comment by RobinHerbots** [comment]
@babupca , 

See issue #228 

I still need to implement this.

**Comment by babupca** [comment]
ok Robin.

**Comment by nstankov23** [comment]
I think, this will help ^(100(\.0{0,2}?)?$|([1-9]{0,1})([0-9]{1})((\.[0-9]{0,2})|(\,[0-9]{0,2}))?)$
