### ISSUE TITLE
allowPlus:false, allowMinus:false generates invalid regex?

### ISSUE THREAD

**Issue by cstansbury** [RobinHerbots/Inputmask#671]
The following code that exists on [line 207 of the numeric extension](https://github.com/RobinHerbots/jquery.inputmask/blob/3.x/js/jquery.inputmask.numeric.extensions.js#L207) generates and uses a regex of "[]" if both allowPlus and allowMinus are set to false. This breaks in IE8, and (not being the regex expert) I'm left wondering if this is really considered a valid regex at all?

``` js
if (!isValid) {
  var signed = "[";
  if (opts.allowMinus === true) signed += "-";
  if (opts.allowPlus === true) signed += "\+";
  signed += "]";
  isValid = new RegExp(signed).test(chrs);
}
```

The temporary workaround in IE8 is to 'allowPlus', but that doesn't seem ideal. Any thoughts?

**Comment by RobinHerbots** [comment]
@cstansbury , 

I just removed the regex and replaced it with a simple check. on + & -
