### ISSUE TITLE
numeric mask not seems to be allowing 001

### ISSUE THREAD

**Issue by babupca** [RobinHerbots/Inputmask#674]
Just noticed, the the numeric mask is not allowing the numbers starting from zero. (for example : 001)

When i entered '0' and again one more zero, it does not allow the second zero. Is this the default behaviour. But at the same time when i use mask:"9" it is allowing me to type 001.

0 - allowed.
00 - it is not allowed.
wanted to achieve this form  - 001

**Comment by RobinHerbots** [comment]
@babupca , 

For a pattern like you described you need to define your own mask.

inputmask("999")

**Comment by babupca** [comment]
@RobinHerbots ,

In Version: 3.0.33.1, the numeric mask was accepting the numbers 001, but in this version  
Version: 3.1.26, it is not accepting this type of number.

**Comment by RobinHerbots** [comment]
@babupca, 

Yes, because in the older version this wasn't handled yet.  What is wrong with using 999?

**Comment by babupca** [comment]
:+1: 
I just solved the issue by renaming the numeric to numeris in numeric input mask extension

Initially i created an custom alias named  'numeric' extended with  jquery.inputmask.defaults.aliases. After some time i took the new version, in that the aliases name was "numeric", here since i already created a custom aliases name, this was overriding the core numeric alias. 

So  i commented by my custom numeric aliases and used the plugins numeric mask, since it was having this same functionality, which mask:'9' has with it. 

:) Now again when i took the latest version, this functionality was lacking. So now again i uncommented my custom numeric mask and changed the plugin numeric mask to numerics.
