### ISSUE TITLE
Multiple masks pattern not working - with keepstatic

### ISSUE THREAD

**Issue by markbrouch** [RobinHerbots/Inputmask#676]
Hi, I found another pattern that does not work with multiple masks:
`mask: ["99-9999-9", "99-9999999-9"]`

**Comment by RobinHerbots** [comment]
This one is related to #665

**Comment by artemkaint** [comment]
+1
if maskset has two similar masks ('+372-####-####', '+372-###-####') inputmask behaves poorly http://joxi.ru/cVEtVP3JTJAATJKkpAs  ie mask became +372-#######-####.

**Comment by RobinHerbots** [comment]
@artemkaint , 

I'm working on it
