### ISSUE TITLE
Hide mask's items that have multiple options

### ISSUE THREAD

**Issue by artemkaint** [RobinHerbots/Inputmask#678]
For example
[''+370(##)###-##-##','+375(##)###-##-##'']

When user enter '37' widget will show first mask with empty third element - +37 _ ( _ _ ) _ _ _ - _ _ - _ _

Similar solution was implemented in https://github.com/andr-04/inputmask-multi

**Comment by RobinHerbots** [comment]
@artemkaint , 

That is a good idea.

**Comment by andychups** [comment]
+1

**Comment by RobinHerbots** [comment]
@artemkaint , 
@andychups , 

Something like https://jsfiddle.net/wrnf0fh6/ ?

**Comment by andychups** [comment]
Hi! Look at this case: https://jsfiddle.net/c5fthj3b/ (type 3)

I mean case with "disable autofill", from this issue: https://github.com/RobinHerbots/jquery.inputmask/issues/636

**Comment by RobinHerbots** [comment]
@andychups , 

Thx for the case.
Working on it.

**Comment by RobinHerbots** [comment]
@andychups , 

Finally fixed ;-)
