### ISSUE TITLE
decimal mask with digitsOptional and placeholder; value trims with jQuery.val(aDecimalString)

### ISSUE THREAD

**Issue by vijjj** [RobinHerbots/Inputmask#679]
Hi Robin,

One integer digit is getting trimmed when a decimal value in string format is set using jQuery('#input').val("aDecimal") in input:text field having options digitsOptional:false and placeholder:'0'  set in 'decimal' alias.

Quite strange that document API works while jQuery API fails

<pre>
test("inputmask(\"decimal\") - digitsOptional:false placeholder:\"0\" jQuery.val ", function () {
    var $fixture = $("#qunit-fixture");
    $fixture.append('<input type="text" id="testmask" />');
    //the below options are set to get decimal padding by default; i.e. input 10 changes to 10.000
    $("#testmask").inputmask("decimal", { alias:"decimal",integerDigits:9,digits:3,digitsOptional: false,placeholder: '0' });//doesn't work
    //$("#testmask").inputmask("decimal", { alias:"decimal",integerDigits:9,digits:3,placeholder: '0' });//working, but .000 goes away on focust lost (we need this)
    //$("#testmask").inputmask("decimal", { alias:"decimal",integerDigits:9,digits:3,digitsOptional: false });//working, but won't get the default placeholder
    $("#testmask").val("2000.000"); // doesn't work
    //$("#testmask").val(2000.000);//works
    //document.getElementById("testmask").value = "2000.000"; // working as expected

    equal($("#testmask").val(), "2000.000", "Result " + $("#testmask").val());
    $("#testmask").remove();
});
</pre>

html element: <input type="text"
inputmask version: 3.1.27
jQuery: 1.11 and 2.1.0
Tested Browsers: Chrome 37.x.x, FF 25.x.x, I.E. 10

Appreciate if you could have a look. If you could point out the potential code part where we need to dig into, we could also pitch in analyzing it (in case you are not managed to figure it out quickly)

Thanks
Vijesh

**Comment by RobinHerbots** [comment]
@vijjj , 

I will have a look at it.  It could be helpfull  if you created a jsfiddle with the different test with options that you already did.

**Comment by vijjj** [comment]
Sorry for the delay.
Here is the JSFiddle http://jsfiddle.net/vijjj/cyp43cbq/

One observation: The issue occurs when the number of decimal part matches the 'digits'. Example ("4000.00") is there in the JSFiddle

**Comment by vijjj** [comment]
@RobinHerbots 

My colleague has identified the problem. The caret symbol (^) is missing in the regular expression used in 'truncateInput' function

<pre>
function truncateInput(inputValue) {
   return inputValue.replace(new RegExp("^(" + escapeRegex(getBufferTemplate().join("")) + ")*$"), "");
}
</pre>

Ran all the test cases successfully including the one I have added. 3 test cases failed with or without the above change.
Please verify this.

**Comment by RobinHerbots** [comment]
This is because the buffertemplate in this case 0.000 is stripped.

Anyway the truncateinput is legacy and not needed anymore, and can be
removed.

2014-10-07 10:42 GMT+02:00 vijjj notifications@github.com:

**Comment by vijjj** [comment]
Okay.
If possible, please include the fix in the next update (3.1.28)

**Comment by RobinHerbots** [comment]
Yes, I will ;-)

2014-10-09 8:05 GMT+02:00 vijjj notifications@github.com:
