### ISSUE TITLE
Inconsistent behaviour of date extensions

### ISSUE THREAD

**Issue by janbuchar** [RobinHerbots/Inputmask#681]
Greetings,

I'd like to make a datetime input with a "hh:mm dd.mm.yyyy" format (the mask is "h:s d.m.y"). I noticed that when I use for example "dd.mm.yyyy" and hit the "5" key, the input automatically fills the day with "05" and moves the cursor to the month part. Can this be achived with the first mask? I don't see a reason for this behaviour not being consistent for all date "fields".

EDIT:  I'm using version 3.1.27

**Comment by RobinHerbots** [comment]
@Teyras , 

Your mask uses the simple definitions for dates.  Have a look at the datetime alias.  Start to extend on that alias and it should work.

Anyway I plan to rewrite the datetime alias to allow it to pass a date/time format to be used and automate all the rest.

**Comment by janbuchar** [comment]
It's not that I couldn't hack it up to work somehow :) What I don't understand is why I need to use a different format to achieve the behaviour that I would expect on any datetime input.

**Comment by RobinHerbots** [comment]
@Teyras , 

Have a look at the definition of m and d and compare it to the definition used in the datetime alias.  The behavior is defined in the definition
