### ISSUE TITLE
Decimal - Ignore groupSeparator and radixPoin

### ISSUE THREAD

**Issue by manrueda** [RobinHerbots/Inputmask#682]
Hi @RobinHerbots 

A few days ago i get the las change of the plugin to my project and i notice a malfunction in the groupSeparator and radixPoint. Even if i put the chars in the opts of the mask, the input use de default points.

Here is a jsfiddle with the bug: http://jsfiddle.net/ManRueda/pg83az9t/

Thanks in advance...

**Comment by RobinHerbots** [comment]
For the first two add a t. You have a typo for radixPoint. For the integer i will have a look.

**Comment by manrueda** [comment]
Oooh @RobinHerbots sorry, i feel like an idiot with this kind of errors...

Here is an update of the fiddle, if i put the the radixPoint option in the integer mask works fine.
http://jsfiddle.net/ManRueda/pg83az9t/1/

And i'm sorry again...

**Comment by RobinHerbots** [comment]
I updated the integer alias to reset the radixpoint to ""

**Comment by manrueda** [comment]
Hi @RobinHerbots 

Here is a new test: http://jsfiddle.net/pg83az9t/2/
Now the example number 4 does something very strange... 

Greetings

**Comment by RobinHerbots** [comment]
@ManRueda , 

Ok fixed!  Thx
