### ISSUE TITLE
'Currency' extension has doesn't allow decimals after auto group

### ISSUE THREAD

**Issue by CurtisFuller** [RobinHerbots/Inputmask#683]
I have am using the "numeric.extensions.js"  and am using the currency alias.  (This also happened with numeric alias)...  Numbers up to $ 99.99 work great.  Once it gets to $100, it stops allowing the user to enter a decimal.    The same problem exists on your demo page (http://robinherbots.github.io/jquery.inputmask/) if you try to enter a number such as 123.45 it will not work. 

I think I've been able to track it down to being an issue with the auto group.  If I change the group size to 6 instead of three, then I can go up to 99999.99 without having the issue.  If I turn off autogroup the problem goes away.  

 Please let me know if there is a way I can fix this. I'm a newbie, and I tried to decipher the code to do it myself, but it is definitely beyond my abilities. 

Thanks!

**Comment by RobinHerbots** [comment]
@Curtisf , 

I will fix that asap.

**Comment by RobinHerbots** [comment]
@Curtisf , 

Fixed!

**Comment by CurtisFuller** [comment]
Thank you!

_Curtis Fuller_
Director of Charter School Operations
_Charter School Services Corporation *_(A Division of Building Hope)*
_Office: (954) 767-1070_
_Direct: (727) 223-6391_
_Website: www.charterschoolcorp.org http://www.charterschoolcorp.org/_
