### ISSUE TITLE
Browserify expects package.json main to be a string not array

### ISSUE THREAD

**Issue by kellycampbell** [RobinHerbots/Inputmask#684]
Browserify gives this error when trying to load jquery.inputmask:

path.js:313
        throw new TypeError('Arguments to path.resolve must be strings');
        ^
TypeError: Arguments to path.resolve must be strings
    at Object.exports.resolve (path.js:313:15)
    at /Users/kellyc/Projects/firefly/gerrit/firefly2/client/node_modules/browserify/node_modules/resolve/lib/async.js:97:37
    at fs.js:271:14
    at Object.oncomplete (fs.js:107:15)

package.json docs say this about main. The second paragraph seems to mean it must be just a module id, not an array of modules:

The main field is a module ID that is the primary entry point to your program. That is, if your package is named foo, and a user installs it, and then does require("foo"), then your main module's exports object will be returned.

This should be a module ID relative to the root of your package folder.

For most modules, it makes the most sense to have a main script and often not much else.

**Comment by RobinHerbots** [comment]
You are right. I will update the package.json
