### ISSUE TITLE
RadixFocus problem

### ISSUE THREAD

**Issue by lucafik** [RobinHerbots/Inputmask#686]
Hi

I have a problem with a radixFocus. 

It doesnt seem to work.

$(document).ready(function(){
           $("#textfield").inputmask({mask: "[99].[99]", greedy: true, radixPoint: ".", radixFocus: true, numericInput: true  });  
        });

Am I missing something important? Is there any other way to contact the author(s)?

Thanks,
Filip

**Comment by RobinHerbots** [comment]
@lucafik , 

I will have a look at it tomorrow.

What do you want to archieve?

**Comment by lucafik** [comment]
@RobinHerbots 

I want to achieve the following:
1. when input field gains focus, it focuses in front of the radix point. We start typing, it types ciphers of the whole number (not decimal) with numericInput=true.
2. when we position a caret to the beginning of the input field, we should be able to type the whole number. (which is actually working right now), but with numericInput=false.

So I need 2 different behaviors, 1st when the field gains focus, and 2nd when we position the caret.

You should also be able to see the desired behavior here:
1. Open stage.adjumed.net/Web/Faelle.aspx
2. Login with the following data (password=demo), by clicking on "Anmelden"
http://pokit.org/get/img/afa3113c31f447b9868ca3f852235184.jpg
3. Pick "STR Main Form (superior)" from the dropdown list
http://pokit.org/get/img/e530834124cd95dee1c85f8962209a4c.jpg
4. Click "Neuen Fall anlegen" (image above)
5. Input form opens, scroll down to numeric input fields, for example Laktat, INR
http://pokit.org/get/img/27ebdc06fbd2d44beb21597900e8aefd.jpg

You can see the desired behavior on these fields + we need radixFocus to work when field gains focus. This is implemented with AjaxControlToolkit.

Thanks a lot!

**Comment by lucafik** [comment]
Dear Robin,

any news on this topic? Dont want to put pressure, just would like to know if its on your list.

Thanks,
Filip

**Comment by RobinHerbots** [comment]
Hi Filip,

Yes I will add an option to position after the radixpoint, but currently
time does not allow.

best regards,

Robin

2014-10-22 14:01 GMT+02:00 lucafik notifications@github.com:

**Comment by RobinHerbots** [comment]
@lucafik , 

Have a look at http://jsfiddle.net/q3pd37xb/

Why don't you use the numeric alias.

**Comment by RobinHerbots** [comment]
http://jsfiddle.net/q3pd37xb/4/

**Comment by lucafik** [comment]
Thanks, that worked. The only problem now is the placeholder. I cannot set it to " __ . __ ". I have tried with setting the placeholder parameter to " _ " and " __ . __ " but no luck. 

with " _ "
1. It shows up as ' _ . __ ' (just one _ before the radix)
2. After I input the value, then select and delete the value and than blur, it gives me 0.00 or 0.20 or some strange value. It should be "__ . __" again.

*comment: for some reasong typing "__ . __" is only possible with spaces. please ignore them.

**Comment by RobinHerbots** [comment]
@lucafik , 

Can you retest with the latest version.

**Comment by lucafik** [comment]
@RobinHerbots 

http://jsfiddle.net/3cp4n39f/1/

I've  set the placeholder to " _ "
1. On click, caret doesnt position itself before the radix point (with placeholder set to "0" it does)
2. it shows just one _ before the radix point (should show two, since integerdigits = 2)

or am i missing something?

**Comment by RobinHerbots** [comment]
This behavior comes from the numeric alias.  (mostly used with placeholder 0 or empty)

Have a look at http://jsfiddle.net/3cp4n39f/2/   

Use the second mask as a start and add what is missing. (add onBeforeWrite for the digits autofill)

**Comment by lucafik** [comment]
Without numeric alias I go back to initial problem - typing in the field. You can see here what is the problem with 2nd, 3rd and 4th mask.

http://jsfiddle.net/3cp4n39f/5/
