### ISSUE TITLE
Digits after update from 3.1.27 to 3.1.28

### ISSUE THREAD

**Issue by luisdelcid** [RobinHerbots/Inputmask#687]
Thank you for this amazing plugin!

Now, if I type a number > 100 with this mask data-inputmask="'alias': 'numeric', 'groupSeparator': ',', 'autoGroup': true, 'digits': 2, 'digitsOptional': false, 'prefix': '$', 'placeholder': '0', 'rightAlign': false" works great on 3.1.27 version but on 3.1.28 version if I try to insert digits does not work, for numbers < 100 works fine

Example:
10.99 on 3.1.27 works
10.99 on 3.1.28 works
100.99 on 3.1.27 works
100.99 on 3.1.28 does not work

**Comment by RobinHerbots** [comment]
@luisdelcid , 

Fixed!
