### ISSUE TITLE
alternative solution to make auto uppercase work

### ISSUE THREAD

**Issue by babupca** [RobinHerbots/Inputmask#688]
Hi Robin, 

Is there any way to achieve the a 5(nos/char) mask which accepts (one upper alphabet or nos) at the start, including 4 nos.

I tried to achieve this with the help of regex, but this makes user to press the uppercase button to make the char to uppercase. The auto uppercasing is not working with the regex mask.

Example 
Mask for the A9999 or 12345

Jsfiddle link 
http://jsfiddle.net/BA251281/91j73d8g/8/

**Comment by RobinHerbots** [comment]
@babupca , 

 $("#bCode2").inputmask("A|99999"); 

See http://jsfiddle.net/91j73d8g/9/

**Comment by babupca** [comment]
@RobinHerbots 

:+1:  Thank you  :)
