### ISSUE TITLE
Add callback in mask options to be processed when mask is validated

### ISSUE THREAD

**Issue by jpirok** [RobinHerbots/Inputmask#689]
I have a feature request.  I'm not sure if this fits into your roadmap or if the feature is already present and I'm just not seeing how to implement it. 

I would like to be able to pass a callback function that returns a boolean value. That value would be evaluated when the "Completeness" of the mask is determined and would affect whether or not the inputmask sent complete or incomplete.

For example:

$('#someinput').inputmask("date", { 
   completionRule: function(unmaskedvalue, maskedvalue) { 
    if(new Date(maskedvalue) > new Date()) 
        return false;
   else
        return true;
    }
}

If the date mask is satisfied, incomplete would be the result for this inputmask if the date in the mask was in the future.

Thank you for your excellent work on this project!

**Comment by RobinHerbots** [comment]
@jpirok , 

Can't you use the oncomplete or onKeyValidation?

Robin

**Comment by jpirok** [comment]
The issue is that those functions don't affect whether or not the mask returns incomplete or complete.  What I'm requesting would happen when the logic for assessing completeness, and affect whether iscomplete or incomplete is returned.

**Comment by RobinHerbots** [comment]
Zo jou want a hook into the is complete function

**Comment by jpirok** [comment]
Yes.

**Comment by RobinHerbots** [comment]
See options isComplete. The hook is already present. Maybe not in the docs. I will verify tomorrow.

**Comment by jpirok** [comment]
Thanks!

On Mon, Oct 20, 2014 at 2:51 PM, Robin Herbots notifications@github.com
wrote:

> See options isComplete. The hook is already present. Maybe not in the
> docs. I will verify tomorrow.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/RobinHerbots/jquery.inputmask/issues/689#issuecomment-59819923
> .

## 

Jason Pirok

**Comment by jpirok** [comment]
Line 1911 in the source (this is in the defaults) contains this definition:

isComplete: undefined //override for isComplete - args => buffer, opts - return true || false

is this the hook you were mentioning?

**Comment by RobinHerbots** [comment]
Yes

**Comment by jpirok** [comment]
What is the opts parameter for the callback?

On Tue, Oct 21, 2014 at 9:21 AM, Robin Herbots notifications@github.com
wrote:

> Yes
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/RobinHerbots/jquery.inputmask/issues/689#issuecomment-59925836
> .

## 

Jason Pirok

**Comment by RobinHerbots** [comment]
It passes the options used in the mask.
