### ISSUE TITLE
Base year needs improvements

### ISSUE THREAD

**Issue by dpeacock** [RobinHerbots/Inputmask#690]
I'm trying to use an alias of  'mm/dd/yyyy' and 'yyyy/mm/dd' which is working great.  One issue I'm coming across is I always want to enter dates in the past, not the future - for example for a date of birth.  It looks like inputmask has logic to support only entering two characters.  It recognizes if I start entering '70' into the year that I probably don't mean a year in 70xx, and assumes I mean 2070.  That's great, but in my case I actually mean 1970.  I added the following line of code in hoping if I said the max year is next year, it might pick the min year instead:

$.inputmask.defaults.aliases['dd/mm/yyyy'].yearrange.maxyear = new Date().getFullYear() + 1;

Unfortunately this is not the case.  Now if I try to enter '70' it simply blocks my input.  Diving a little further into this, I took a look at the source.  I am guessing this is a result of the determinebaseyear function.  The only time minyear is returned is when when it is greater than the current year, so this doesn't seem to help me.

I would think it would be useful to have some sort of configuration option which would prefer the base of the min year instead of the max year.  Better yet, maybe the configuration could be a little smarter.  Perhaps it could choose the base of whichever the date is closer to.  For example, if I were to enter '70' I would expect 1970, because 1970 is closer to this year (2014) than 2070.  If I were to enter '05', then I would expect 2005 instead of 1905.

Let me know if you need a better explanation of this.

**Comment by RobinHerbots** [comment]
That would be a good enhancement. I will implement it xhen time allows.

**Comment by brownbl1** [comment]
+1. If this was handled more intelligently by default, that would be sweet! In the meantime though, for anyone who would like this functionality now, it's fairly simple to define an alias and override the `determinebaseyear` functionality. Something like this worked for me.

``` javascript
$.extend($.inputmask.defaults.aliases, {
   date: {
      alias: "mm/dd/yyyy",
      determinebaseyear: function (minyear, maxyear, hint) {
         return minyear;
      }
   }
});
```

**Comment by RobinHerbots** [comment]
This issue is obsolete
