### ISSUE TITLE
[IE 8/9] Inputmask plugin clears form on page load when included on the page.

### ISSUE THREAD

**Issue by zenmedia** [RobinHerbots/Inputmask#691]
Hi,

I am currently working on a project which has a requirement to use internet explorer from 8+.

While this plugin works fine in internet explorer 10+ we found that on internet explorer 8 and 9 it clears (hides the content) of the form, even if it has just been included on the page and not being called.

We have checked the html and all of the relevant fields have the value="" attribute populated, and the values "pop-up" for a very brief period of time and then vanishes again.

This happens with V2.x and V3.x

Regards
Ryan

**Comment by RobinHerbots** [comment]
Can you create a jsfiddle which shows the problem.  Does this only happens on the native browser or also in ie10 in ie8 mode?

**Comment by zenmedia** [comment]
Hi Robin,

After some further investigation, i found that this is an incompatibility with other javascript plugins on the page, i will do some further investigation and if i come back to this plugin being the problem i will let you know.
