### ISSUE TITLE
Mask issue in Android with Swype Keyboard

### ISSUE THREAD

**Issue by dpeacock** [RobinHerbots/Inputmask#692]
When using a mask in Android with the default keyboard, everything seems to work great.  When I switch my Input method to use the Swype keyboard for some reason it doesn't seem to play well with the masks.  For example if my mask is MM/DD/YYYY and I start entering a date it comes up as 1MM/DD/YYYY, then 10MM/DD/YYYY.  I also tried using a simple m-d-y mask and I get a similar result of 10__/**/__**.

Is inputmask supposed to play well with Third Party keyboards such as Swype?  Are there any existing configurations today to prevent this?

**Comment by dpeacock** [comment]
Sounds like some of the keyboards don't fire on key up/down/pressed events and instead fire 'input' events.  Is there a way this could get incorporated?

See:
http://stackoverflow.com/questions/18951584/keyboard-swipe-javascript-event

**Comment by RobinHerbots** [comment]
@dpeacock , 

I have a fallback method based on the inputevent.

Can you retry with the latest version on github
