### ISSUE TITLE
Issue with Mask and input values where input values match portion of mask

### ISSUE THREAD

**Issue by jason16v** [RobinHerbots/Inputmask#693]
Hello,
I'm having a bit of an issue I'm hoping someone can help with...

Say I have a mask such as '+31 9999999999999999'
The mask is retrieved and applied to a field
next, I retrieve a phone number from a database and set the value to the masked field
The value from the db is something like 31123456789
where 31 is part of the phone number and not the country code in this case. 

What I see input mask is doing is assuming the 31 portion of the phone is the country code leaving me with only  +31 123456789 where 31 is no longer part of the phone number portion.

Any recommendations on how to prevent this behavior would be gladly accepted. I've looked at cardinality, escape characters etc... to no avail.

**Comment by RobinHerbots** [comment]
Yes the assumption is wrong. I will fix this.

**Comment by RobinHerbots** [comment]
@jason16v , 

Fixed in the latest commit.
A new bundle and release will follow soon.
