### ISSUE TITLE
Problem with Jquery Datepicker only because of using inputmask

### ISSUE THREAD

**Issue by adlbtt** [RobinHerbots/Inputmask#694]
Hi,

I am using a jquery datepicker. when I select a date from date picker it appears in the input fields but calender switch to today's date. It does not remain on the same place where I have selected date. This is happening only because of I am using inputmask. If I remove it it works fine.

Thanks in advance.

**Comment by RobinHerbots** [comment]
@adlbtt, 

Can you make a jsfiddle for this. 

Robin

**Comment by adlbtt** [comment]
Hi,

Thanks for your reply.
Here is the jsfiddle link

http://jsfiddle.net/zf2x9307/26/

But in this link my calender is not able to select the date because input mask is calling on it. If I remove it then It works fine. I dont know why it is happening on jsfiddle but it is working on my machine. But my primary problem is that whenever you select a date from the datepicker from my project It selects the date from the calender but when you click calender again it starts from the todays date, not from the date which I selected before.

Please any suggestion.

**Comment by adlbtt** [comment]
Hi,

Thanks for your reply.
Here is the jsfiddle link

http://jsfiddle.net/zf2x9307/26/

But in this link my calender is not able to select the date because input mask is calling on it. If I remove it then It works fine. I dont know why it is happening on jsfiddle but it is working on my machine. But my primary problem is that whenever you select a date from the datepicker from my project It selects the date from the calender but when you click calender again it starts from the todays date, not from the date which I selected before.

Please any suggestion. I need it

**Comment by RobinHerbots** [comment]
@adlbtt , 

The dateformat of jquerui is not exactly the same as in the inputmask.

I updated the fiddle as example

http://jsfiddle.net/zf2x9307/28/

**Comment by fstani** [comment]
@RobinHerbots 

This issue seems to be back on the 4.x release branch:

I've updated the fiddle with the link to the 4.x
http://jsfiddle.net/cm84znyh/
