### ISSUE TITLE
Cursor skips to end

### ISSUE THREAD

**Issue by osCMattiFinn** [RobinHerbots/Inputmask#695]
This issue is possibly related to the fact that the input was previously hidden.

Using a mask for phone, after entering the first number the cursor skips to the end.

Using: jQuery("#customerPhone").inputmask("mask", {"mask": "(999) 999-9999"});

**Comment by RobinHerbots** [comment]
@osCMattiFinn , 

Can you make a jsfiddle which shows the problem.

Robin

**Comment by RobinHerbots** [comment]
@osCMattiFinn , 

I tested the mask and see no problem.
