### ISSUE TITLE
support for periods

### ISSUE THREAD

**Issue by kiesslir** [RobinHerbots/Inputmask#697]
Hi,

i simply want mask "mm.yy-mm.yy" to specify a period like "02.14-07.15" which means "from february 2014 until july 2015"

With "$(".validate_date_mmyymmyy input").inputmask("m.y-m.y", {placeholder:'mm.yy-mm.yy' });" i got "mm.yy-m-.y.mm.y"

Regards,
 Rig

**Comment by RobinHerbots** [comment]
@kiesslir , 

The y definition takes 4 places.

Change your mask to m.99-m.99
