### ISSUE TITLE
Hang on combination of optional mask and repeat

### ISSUE THREAD

**Issue by gmta** [RobinHerbots/Inputmask#698]
Inputmask hangs on the following code:

<code>
$('...').inputmask('[ ]{+}');
</code>
Using version 3.1.33

**Comment by RobinHerbots** [comment]
I don't know what do you want to accomplush with that mask, but the case is interesting to investigate.  
Thx for reporting

**Comment by gmta** [comment]
I gave you a simplified case for debugging purposes. I believe the original mask was something like:

```
9{4}[ 9{4}]{+}
```

Which would be a simple way of grouping every 4 digits, regardless of how long the input is.

**Comment by RobinHerbots** [comment]
@GMTA , 

This issue is still actual!!!  Time to solve it! ;-)

**Comment by RobinHerbots** [comment]
@GMTA , 

Fixed !
