### ISSUE TITLE
Sequentional optional parts do not fully match

### ISSUE THREAD

**Issue by gmta** [RobinHerbots/Inputmask#699]
When trying to write a simple group-by-4 mask, it was possible to enter only spaces after the first group of digits.

```
$('...').inputmask('9999[ 9999][ 9999]');
```

After entering the first four digits, it is possible to enter two spaces. This should not be possible according to the above mask? The workaround is to wrap the optional parts in eachother:

```
$('...').inputmask('9999[ 9999[ 9999]]');
```

Using version 3.1.33

**Comment by RobinHerbots** [comment]
Thx for reporting!
I will have a look.

**Comment by BugFixerr** [comment]
May I hope for a fix soon?

**Comment by RobinHerbots** [comment]
@BugFixerr , 

I will fix it for the current milestone

**Comment by RobinHerbots** [comment]
To better understand the problem try .inputmask('9999[+9999][-9999]');

**Comment by RobinHerbots** [comment]
@GMTA , @BugFixerr , 

Fixed in the latest version.  Can you have a try.

How do you use the optionals?  With the greedy true (default) or false ?

**Comment by gmta** [comment]
Tested the latest version; could not trigger the bug anymore. Seems to be fixed! Thank you very much.

Optionals are used with the default setting (greedy).
