### ISSUE TITLE
on focus: can't deselect

### ISSUE THREAD

**Issue by ostrolucky** [RobinHerbots/Inputmask#700]
``` javascript
el.focus(function() {
return false;
}
```

Doesn't work when `el` is inputmasked. It looks like jquery.inputmask focuses it always additionally.

**Comment by ostrolucky** [comment]
was this fixed?

**Comment by RobinHerbots** [comment]
@ostrolucky , 

Well I'm not sure what you want to accomplish, but the current 5.0.0-beta version does not steal focus unless you focus the input.

If this is not what you meant, let me know and create an example to make it more clear to me.

Best regards,
Robin
