### ISSUE TITLE
Negative numbers - Mask fails

### ISSUE THREAD

**Issue by manrueda** [RobinHerbots/Inputmask#701]
Hi @RobinHerbots ,

I have an issue with the numeric mask, if i set the value with something like '-5000,77' the field makes something strange.

Here is an example: http://jsfiddle.net/ManRueda/8cgk7nLq/

**Comment by RobinHerbots** [comment]
I will fix it asap

**Comment by RobinHerbots** [comment]
@ManRueda , 

Fixed!  A new release will come later today.

**Comment by manrueda** [comment]
@RobinHerbots ,

Works perfect!

Thanks
