### ISSUE TITLE
No-space mask - Strange behavior

### ISSUE THREAD

**Issue by manrueda** [RobinHerbots/Inputmask#702]
Hi @RobinHerbots ,

This is a visual issue, something insignificant, but if you can fix it someday it's going to be great hahah

If i declare a mask that doesn't allow space, the space bar it blocked but i can move in the filed with the direction arrows of the keyboard. 
When i read the value, with the unmaskedvalue method, the space it's erased but in the field the space is visible.

Example: http://jsfiddle.net/ManRueda/m20039Lv/

Thanks!!

**Comment by RobinHerbots** [comment]
@ManRueda , 

What about this one http://jsfiddle.net/m20039Lv/2/

**Comment by manrueda** [comment]
@RobinHerbots ,

Works great!
Thank!!
