### ISSUE TITLE
eval in plugin code cuases browser-policy warning

### ISSUE THREAD

**Issue by MaximDubrovin** [RobinHerbots/Inputmask#704]
Chrome warning, for example:

![error screenshot](https://photos-2.dropbox.com/t/1/AABiRKuSsAoT78H2aTHhTkj0tuTT7Z_bq0lZOdTNA2ak4w/12/331877732/png/1024x768/3/1414252800/0/2/Screenshot%202014-10-25%2020.46.18.png/4AywGhdzshYAFjvWyN-JuKTETCcxTsf4hfGjxKjhOUY)

Text version:

```
Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".
jquery.inputmask.js?a0f90707c41a8d8256325d3346495372acc35c8c:987
```

I disallowed `eval()` in my app's Content Security Policy which is key thing to security. 

But inputmask [uses it](https://github.com/RobinHerbots/jquery.inputmask/blob/3.x/dist/jquery.inputmask.bundle.js#L985). Bad thing that inputmask plugin de-facto only and the best plugin for masks. 

@RobinHerbots, Is there any way for plugin do not use such dangerous functionality?

**Comment by RobinHerbots** [comment]
I will see what i can do.

**Comment by MaximDubrovin** [comment]
I made a little drama from it. 

Eval, actually, not evil if other security holes closed such as:
- block inline scripts
- allow only connections that your app uses
- sanitize user data when pasting it to html (< > stuff from `<script>` and etc)

Since I did it, I don't worry about eval.

But with time developers will more and more adapt Content Security Policy and face with this warning.

**Comment by RobinHerbots** [comment]
@MaximDubrovin , 

Where did you found an eval in the current version?

**Comment by MaximDubrovin** [comment]
Browser throws warning at [this line](https://github.com/RobinHerbots/jquery.inputmask/blob/3.x/dist/jquery.inputmask.bundle.js#L999)

Version at the top of the file is 3.1.34

**Comment by RobinHerbots** [comment]
@MaximDubrovin , 

It was causes by new Function("/*cc_on ...  for the conditional compilation for ie1x detection

Fixed in the latest commit.

**Comment by MaximDubrovin** [comment]
Thank you
