### ISSUE TITLE
[Phone Extension] Duplicating the Last digit

### ISSUE THREAD

**Issue by mshahrouri** [RobinHerbots/Inputmask#705]
If you try to enter a 3 digits country code the control will duplicate the last number.

here is an example: Jordan country code is +962 if you try and enter 96 in the control the control will display 9622, see the screenshot 
![3](https://cloud.githubusercontent.com/assets/951528/4782852/7b1fb428-5d09-11e4-8a29-f641b6dafa5c.jpg)

**Comment by RobinHerbots** [comment]
@mshahrouri , 

Finally fixed. 

Grab the latest version from github
