### ISSUE TITLE
As of 3.1.33 use of `format` fires an error

### ISSUE THREAD

**Issue by krivaten** [RobinHerbots/Inputmask#707]
Recently ran `bower update` and noticed my use of format was firing back an error. Here is my code:

```
var phone = '5551112222';
$.inputmask.format(phone, { mask: '(999) 999-9999' })
```

I started rolling back versions and it looks like the issue first appeared in version _3.1.33_. I will look through the logs and see if I can track down the culprit in the changes, but just wanted to post it here in case anyone had noticed it.

Thanks for the great plugin!

**Comment by RobinHerbots** [comment]
@krivaten , 

I tested in Chrome FF and IE10 and see no problem.

Can you provide more info.

**Comment by krivaten** [comment]
Thanks for looking into it. I looked in to it some this afternoon and the console error I am getting is in reference to the 3rd line in the function `trackbackAlternations`:

```
for (var tndx in tests) for (var activeTest = tests[tndx], i = 0; tll > i; i++) targetLocator[i] == activeTest.locator[i] && i > equality && (equality = i, 
```

The error I get is `Uncaught TypeError: Cannot read property '0' of undefined`

To give some more context, I am using this in a phonegap Ember app and am parsing the value as a string before passing it to inputmask. Oddly, I have been unable to duplicate the issue in JSBin, which leads me to believe it might be conflicting with Ember somewhere.

It's just odd that it was working in 3.1.32 but not 3.1.33.

Digging in to it now to see if I can find a solution.

**Comment by RobinHerbots** [comment]
@krivaten, 

The trackbackAlternations is a WIP which slipped in.

Anyway, if you find a cause, I would be happy to hear about it.

**Comment by RobinHerbots** [comment]
@krivaten , 

Can you retry with version 3.1.36

best regards, 

Robin

**Comment by kaishin** [comment]
I'm having the same issue with the same mask.

**Comment by RobinHerbots** [comment]
@kaishin , 

On which version did you test?

**Comment by kaishin** [comment]
@RobinHerbots I'm using `3.1.37`

**Comment by kaishin** [comment]
Removing the `(` "fixed" it for me.

**Comment by RobinHerbots** [comment]
@kaishin , 

Which browser are you using as I cannot reproduce the error.

Can you make a jsfiddle for it?

**Comment by YodaJM** [comment]
I encountered this error recently and was able to track down the culprit in my case.  I had some legacy code that was setting Array.prototype.sortByProp function.  Removing that stops the error from occurring.  I found this answer on stackoverflow that explains the problem: http://stackoverflow.com/a/4760279

Here's a jsfiddle where the error occurs: http://jsfiddle.net/esqqer52/
If you uncomment the 2nd way of setting the function prototype, the error no longer occurs.

Using Chrome and IE I get the same error kaishin mentioned: Uncaught TypeError: Cannot read property '0' of undefined 

Using Firefox I get the following error in Firebug: TypeError: activeTest.locator is undefined

**Comment by kaishin** [comment]
I used the latest version from master and it's working fine! Not idea if that was intentional or not.

**Comment by RobinHerbots** [comment]
@YodaJM , 

Thx for the information.  Those bugs by prototype extentions always come and go ;-)
I added some dummy extentions in the qunit tests so that this won't happen again.

@kaishin, 

;-)  Yes it was the intention to fix the problem ;-)
