### ISSUE TITLE
Numeric keypress not filtering after decimal if digit set to 0

### ISSUE THREAD

**Issue by DrSammyD** [RobinHerbots/Inputmask#708]
I'm creating a data-binding for inputmask, but there seems to be an issue with pasting values.
[jsFiddle](http://jsfiddle.net/DrSammyD/X7y2k/64/)

Everytime I change the value, the input buffer filters out the pasted decimal point on my number but doesn't filter out the numbers from after the decimal point. This is an issue with setting the value. As you can see from the jsfiddle, it works up until you set `digits:0`

I think it has something to do with the onKeyDown removing the decimal at the end. Is there a way to filter out the decimal and everything after it?

**Comment by RobinHerbots** [comment]
@DrSammyD, 

It is because with digits = 0 there is no radixPoint or digits definition in the mask.  The mask assumes all numbers are integers.  I will fix that.

**Comment by RobinHerbots** [comment]
@DrSammyD , 

fixed in the latest commit.
