### ISSUE TITLE
removeMaskOnSubmit has no reason to depend on autoUnmask

### ISSUE THREAD

**Issue by vemv** [RobinHerbots/Inputmask#709]
In my particular case, I don't want `$('#xxx').val()` to return the unmasked value, but I do want inputs to get unmasked on submission.

This desired behavior is not possible due to the following line:

```
if (opts.autoUnmask && opts.removeMaskOnSubmit)
```

I see no reason why one option should be coupled to the other. Modifying the library to:

```
if (opts.removeMaskOnSubmit)
```

doesn't break anything and allows what I need.

Could you please consider making this change?

**Comment by RobinHerbots** [comment]
@vemv , 

Changed with the latest commit.

**Comment by vemv** [comment]
Thank you very much @RobinHerbots !
