### ISSUE TITLE
Can't seem to replace current char?

### ISSUE THREAD

**Issue by ghedwards** [RobinHerbots/Inputmask#71]
Is there a way I can do something like the following using prevalidator or validator?

As the user types 23 ( for 24 hour time ), I would like to modify the string to become 11

I've tried using the buffers, but the best I can do is 13, which is replacing the first character, but not the second?

To add to this, the plan is to also set the am / pm to "pm" in this scenario ( in my Fork - currently commented out ), which appears to be working o.k.

Cheers
Gareth.

**Comment by RobinHerbots** [comment]
Hi Gareth,

I will have a look at it.  How is the alias called in your repo?

Robin

2012/6/19 ghedwards <
reply@reply.github.com

**Comment by RobinHerbots** [comment]
Check out the latest version in dev.
The isValid now expects a json object as return with pos and c (character)

Just have a look at the extentions.  .... return { "pos": pos, "c": yournewtransformedchar }
