### ISSUE TITLE
decimal number incorrectly formatted to integer

### ISSUE THREAD

**Issue by VeteranCoder** [RobinHerbots/Inputmask#710]
I discovered a problem with the "integer" mask, and I think I fixed the problem locally, but I don't know the code and my fix might not be complete.  

The scenario: Input that was previously designed to be decimal was changed to integer.  The database fields are decimal.  The data read from the database has one or more zeros after the decimal, so "1234" comes up as "1234.00".  When the mask is applied, it simply removes the radixPoint "." producing "123400" as the integer value.

The code I changed, that appears to resolve the problem, is in jquery.inputmask.numeric.extensions.js:

```
       onBeforeMask: function (initialValue, opts) {
            if (isFinite(initialValue)) {
                // incoming number has a decimal, and is being formatted to whole number.
                if (opts.radixPoint === "" && initialValue.indexOf(".") > 0) {
                    initialValue = initialValue.substring(0, initialValue.indexOf("."));
                    return initialValue;
                }
                return initialValue.toString().replace(".", opts.radixPoint);
            } else {
```

I added the block just above the  return statement above "else", which was the whole "if" block before.  This strips off the trailing zeros (or whatever is there).  The mask definition I am using is:

```
    $(".decimal").inputmask("integer", {
        autoGroup: true, groupSeparator: ",", groupSize: 3, greedy: false, clearMaskOnLostFocus: true,
        removeMaskOnSubmit: true, autoUnmask: true
    });
```

Thanks!

**Comment by RobinHerbots** [comment]
@VeteranCoder, 

Yes see issue #708.

Thx for sharing your solution.

Best regards, 
Robin
