### ISSUE TITLE
determineLastRequiredPosition() has a syntax error

### ISSUE THREAD

**Issue by spicymikey** [RobinHerbots/Inputmask#712]
It appears this function is missing a return statement on the line (#1028) that is returning the definition array

This: 
returnDefinition ? { "l": bl, "def": positions[bl] ? positions[bl]["match"] : undefined } : bl;

Needs to be changed to this:
return  returnDefinition ? { "l": bl, "def": positions[bl] ? positions[bl]["match"] : undefined } : bl;

**Comment by RobinHerbots** [comment]
@spicymikey , 

When I look at the determineLastRequiredPosition in js/jquery.inputmask.js that is already the case.

**Comment by spicymikey** [comment]
Could I have accidently modified the js file myself?   I should have done a refresh first to check for that.    I reinstalled .35 and all seems correct.   Sorry.
