### ISSUE TITLE
Set countrycode via javascript/jquery and don't allow user to delete it

### ISSUE THREAD

**Issue by arturoliveira** [RobinHerbots/Inputmask#714]
Is it possible to set the countrycode via javascript/jquery like:

``` javascript
$(selector).inputmask({'countrycode':'+351'});
```

and don't allow the user to delete it

**Comment by RobinHerbots** [comment]
@arturoliveira ,

try 
$(selector).inputmask(''+351-999 999");

**Comment by arturoliveira** [comment]
@RobinHerbots it's an option but this way i won't use the ability to have several masks taken from json configuration files
Any other option ?

**Comment by RobinHerbots** [comment]
Ok, what do you want to accomplish exactly?

2014-11-04 23:21 GMT+01:00 arturoliveira notifications@github.com:

**Comment by arturoliveira** [comment]
What i wan't is to use the inputmask phone extension and based on a selection of another input set the country code and the url so that the user only has to type the phone number and the country code is set automatically and cannot be changed.

Was i clear ?

**Comment by RobinHerbots** [comment]
@arturoliveira , 

Something like   $("#test8").inputmask("phone", { countrycode: "351", nojumpsThreshold: 4, "url": "https://rawgit.com/RobinHerbots/jquery.inputmask/3.x/js/phone-codes/phone-codes.js" });

But the best result will be if you also specify separate phone-codes per country you want to support.

See be & nl example.

On the change event of the country dropdown you call the inputmask with the correct options depending the selection in the dropdown.

It would be nice if you define the possible phone-codes for a country that you share it, so I can include it in the project.
