### ISSUE TITLE
3.1.35 breaks this fiddle

### ISSUE THREAD

**Issue by DrSammyD** [RobinHerbots/Inputmask#715]
I have a fiddle that was on your latest dist and it broke a couple hours ago.
http://jsfiddle.net/DrSammyD/ynnm9796/2/

I reverted back to 3.1.34 and it worked again
http://jsfiddle.net/DrSammyD/ynnm9796/0/

**Comment by RobinHerbots** [comment]
First thing tomorrow.

**Comment by RobinHerbots** [comment]
@DrSammyD , 

Fixed in 3.1.36  http://jsfiddle.net/ynnm9796/3/

**Comment by DrSammyD** [comment]
hmm not quite,
If you click on decrease value in this jsfiddle it works with [3.1.34](http://jsfiddle.net/ynnm9796/4/)

But not with [3.1.36](http://jsfiddle.net/ynnm9796/5/)

**Comment by RobinHerbots** [comment]
@DrSammyD , 

I tested both and they seem to work both fine.  Maybe the latest commit which does some fixes in the numeric alias fixed it.

Can you confirm

**Comment by DrSammyD** [comment]
Yes, I can verify that it is working with latest but not 3.1.36.

**Comment by DrSammyD** [comment]
I just wanted to let you know that changes from 3.1.38 to 3.1.39 broke my fiddle again, but this time something to do with the datetime mask

[Working fiddle with 3.1.38](http://jsfiddle.net/n2o9qca4/3/)

[Not working fiddle with 3.1.39](http://jsfiddle.net/n2o9qca4/4/)

**Comment by RobinHerbots** [comment]
@DrSammyD , 

Looking at the code, ... I do not understand how it works by switching 1/2/y to 2/1/y.

Lucky coinsidence I guess.  Anyway, I will refactor the date alias to work with date patterns, instead of different inheriting aliases ;-)

**Comment by DrSammyD** [comment]
in your definitions for the datetime alias `1` is defined as the day's place, and `2` is defined for the month's place. The definitions get inherited so switching them just uses those definitions I believe. At least that's the way I read your code.

**Comment by DrSammyD** [comment]
https://github.com/RobinHerbots/jquery.inputmask/blob/3.1.38/dist/inputmask/jquery.inputmask.date.extensions.js#L103

that's where you define the `1` and `2` definitions.

**Comment by RobinHerbots** [comment]
@DrSammyD , 

I know but there is more then just the definition.  The key are the regex definitions defined in the alias.
