### ISSUE TITLE
Value gets selected while entering the last digit for the texts with  maxlength

### ISSUE THREAD

**Issue by laxmikantG** [RobinHerbots/Inputmask#716]
Hello @RobinHerbots 

Issue is with the `text` fields containing `maxlength` attribute 

```
<input type="text" maxlength="12" class="MODE_ALPHANUMERIC" id="F_07_0020" name="F_07_0020" value="" data-inputmask="'alias': 'integer', 'integerDigits': '12', 'allowMinus':true, 'groupSeparator': ',', 'autoGroup': true, 'groupSize': '3'" >
```

When user enters the last character (say 12th Character in this case), all value gets selected. And if user tries to enter next (13th) character, all the value gets removed and only one (13th) character  displays.  
But the behaviour should be :
- It should not select the value while entering the last digit. 
- It should not allow to enter characters more than that of `maxlength`. 

It works fine if I remove the plugin. Plugin should not change the DOMs default behaviour. 

![image](https://cloud.githubusercontent.com/assets/1826523/4898636/fb82e2ba-6412-11e4-8bbb-57c243ce5c62.png)

**Comment by laxmikantG** [comment]
@RobinHerbots :- 
I have updated the plugin to latest version to pull the fix for #732 . It seems updated version also fixes this issue. Since closing this issue.
Thank you

**Comment by RobinHerbots** [comment]
@laxmikantG , 

Yes that was due to some code in the keyup event.

**Comment by laxmikantG** [comment]
@RobinHerbots : -- 
Sorry, It did not work. Its working sometimes. But not on every field. Could you please check it? OR Let me know, if I can check in any specific function or in event. 
Thank you

**Comment by RobinHerbots** [comment]
@laxmikantG, 

Can you workout an example where in it occurs.

**Comment by RobinHerbots** [comment]
@laxmikantG , 

Is this issue still occuring?

**Comment by laxmikantG** [comment]
@RobinHerbots  :- Sorry for delay in reply. 
I did not check this with latest version. But I had fixed at our end by commenting following lines: 

```
  ...}, $(npt).data("_inputmask", data), $(npt).is(":visible")) {
               var scrollCalc = $(npt).css("font-size").replace("px", "") * end;
               npt.scrollLeft = scrollCalc > npt.scrollWidth ? scrollCalc : 0, 0 == opts.insertMode && begin      == end && end++, 
               npt.setSelectionRange ? (
            // Reason: Disable text selection after entering last digit
            /* npt.selectionStart = begin, npt.selectionEnd = end */
            // Reason : For normal TAB key behaviour (execute original code for TAB key event)
            event.keyCode == $.inputmask.keyCode.TAB ? (npt.selectionStart = begin, npt.selectionEnd = end /* END */) : true)  : npt.createTextRange && (range = npt.createTextRange(),
            range.collapse(!0), range.moveEnd("character", end), range.moveStart("character", begin), 
            range.select());
        }...
```

We disabled the selection manually, I'm not sure if this is a good idea  ;)
Thank you
