### ISSUE TITLE
Esc key pressed while value is selected in the text field, string reduces to 6 digits  

### ISSUE THREAD

**Issue by laxmikantG** [RobinHerbots/Inputmask#717]
@RobinHerbots,

Hello Again, 

A strange bug found in decimal fields. If we press `Esc` key while the value in the decimal field is selected, then it automatically reduces to 6 digits. 
Same also happen on demo page at  http://robinherbots.github.io/jquery.inputmask/.
Please refer Screengrab:
![screengrab ](https://cloud.githubusercontent.com/assets/1826523/4915870/893542f4-64d3-11e4-8f50-8fadc0e545f4.png)

Thanks in advance!

**Comment by RobinHerbots** [comment]
@laxmikantG , 

The pressing escape reverts the value to the value before focus

**Comment by laxmikantG** [comment]
Okay, Noted. This behaviour is the feature of your plugin, then I wonder if it could be an optional. On our side a modal popup comes on `Esc` event.
Thank you

**Comment by RobinHerbots** [comment]
@laxmikantG , 

Ok done.  Set the undoOnEscape option to false.  (latest commit)

**Comment by laxmikantG** [comment]
Thank you
