### ISSUE TITLE
[Number] 0,00 value problem - extra radix point

### ISSUE THREAD

**Issue by ioleo** [RobinHerbots/Inputmask#718]
Given this mask:

``` js
 $amount.inputmask("decimal", {
    radixPoint: ",",
    digits: 2,
    digitsOptional: false,
    autoGroup: true,
    groupSeparator: " ",
    groupSize: 3,
    allowPlus: false,
    allowMinus: false,
});
```

The input with value `130,00` (or any non-zero) behaves as expected. But when applied to an input with value `0,00` I'm getting this weird behaviour:
- initially, the input looks OK (it has `0,00` displayed)
- when I focus on the input with "tab" and input some number (eg. `123` it also works as expected

However when I focus on the input with mouse click and input some number (eg. `123`) this happens:
- only the first digit is allowed (`1`), the rest is blocked
- the value displayed is `1,00,`
- i can't type any more numbers on the integer side... I have to "delete" the additional rafix point `,`

It seems as if the widget misinterprets the initial value.

**Comment by ioleo** [comment]
After adding:

``` js
if ($amount.val() == '0,00') {
  $amount.val('0');
}
```

The issue is fixed... BUT, the initial value is displayed as `0,`.

> Note: this is a workaround. Not actually solveing the issue.

~~I want to ALWAYS add the decimal points. Eg. if user inputs `123,` I'd like the value to be changed to `123,00`. Is it possible somehow?~~

Nevermind. Adding `clearMaskOnLostFocus: false` does exacly that.

**Comment by ioleo** [comment]
``` js
if ($amount.val() == "0,00") {
    $amount.val(0);
}

$amount.inputmask("currency", {
    prefix: "",
    radixPoint: ",",
    groupSeparator: " ",
    allowPlus: false,
    allowMinus: false,
});
```

Note: this code works as expected. However, if I remove the `if` - the problem with `0,00` value is still there, only now when I try to type `123` instead of `1,00,` I am getting `1,00,00` (and the `2` and `3` are blocked).

**Comment by ioleo** [comment]
Another "curious" thing is: when the value is `1,00,00` (or `1,00,` in the first example)... when I "hover" my mouse over the field - the value is "corrected" to `1,00` (in both cases).

**Comment by ioleo** [comment]
OK.. I'm getting deeper into internals.. 

I've modified the `onKeyDown` and display the buffer in the console. Here are the results:

For initial value `131,30`, when I enter any number:
- the buffer is `["1", "3", "1", ",", "3", "0"]`

For initial value `0,00`, when I enter any number:
- the buffer is `["0", ",", "0", "0", -1: undefined]`

~~And thats probably the reason.. if I understand it correctly, it thinks it has `0,00` as integer part and the radixCharacter and decimal part are not found.~~

_Edit: nope.. for valid numbers like `1,00` the initial buffer also displays the `-1, undefined`.. so it seems its not related to the issue._

Only question is... why? Where is the bug?

**Comment by ioleo** [comment]
Actually, it's even worse... the same problem appears for `0,01` initial value.

For `1,01` and `1,00` it works as expected. So it breaks when the integer part == 0.

**Comment by ioleo** [comment]
I give up.. tried to debug this, but with variables called ndx, bs, tst and minumum comments I just can't figure it out..

What I found is if I add [here](https://github.com/RobinHerbots/jquery.inputmask/blob/3.1.36/js/jquery.inputmask.js#L736) a console log... then:

For number `131,30`, when the `,` character is checked, the `if` is not evaluated.
For number `0,10`, when the `,` characters is checked, the `if` **is** evaluated.

And this seems to be the cause of this bug.. it seems that whatever logic is in that `if` block, it should be applied to valid numbers (and not radical points). And for `0,10` that block is evaluated.

**Comment by ioleo** [comment]
Another note: for value `0.13` and options `radicalPoint: "."` the bug also appears. So it's not caused by `,` as radicalPoint character.

**Comment by ioleo** [comment]
@RobinHerbots I'm sorry to spam and bother you, but what part of code is executed, when you hover over the input? It seems to "fix" the value, so I'd like to call it in `onBeforeMask`.

**Comment by ioleo** [comment]
I've tried programmatically triggering the `setvalue.inputmask` and `mouseenter.inputmask` but it didn't help :/

**Comment by ioleo** [comment]
So.. if initially the value is OK and programmatically calling the events does not prevent the error from happening later, while triggering these events AFTER the error does fix the issue

There is one other possibility:
- on init, everything is OK
- after the first key is pressed, something goes fishy

**Comment by ioleo** [comment]
I fixed it ^______________^
`<victory dance>`

**Comment by RobinHerbots** [comment]
@loostro , 

Hi, first thx for sharing the issue and for seeking to a solution!

But the issue was caused by a the radixhandler in the numeric extension.  It made the radixpoint a valid match for a wrong test.

Can you have a test with the latest commit

**Comment by ioleo** [comment]
@RobinHerbots Yeah I've realized after submitting the PR, that the source of the problem is in `postFormat`. However it was late and I had much more work, so I just stopped there :)

I'll try to test sometime this weekend and get back to you. Thanks.
