### ISSUE TITLE
AutoUnmask should not remove decimal from number values.

### ISSUE THREAD

**Issue by markbrouch** [RobinHerbots/Inputmask#721]
When a mask `numericInput = true` and `autoUnmask = true`, it should not remove the `.` from the value, as that changes the actual value. For instance, 10.5 becomes 105 which would be incorrect.

**Comment by RobinHerbots** [comment]
You can override the default functionality by implementing the onUnMask.
See numeric alias for an example.

2014-11-06 23:27 GMT+01:00 Mark Brouch notifications@github.com:
