### ISSUE TITLE
Some odd behaviour in decimal mask while pressing the backspace

### ISSUE THREAD

**Issue by babupca** [RobinHerbots/Inputmask#722]
Actual  : 123213.123
Result on pressing Backspace from integerDigits : 000000123

Steps to reproduce:
1. focus the field one input field in jsfiddle
2. start typing all the 6 integerDigits in full and also 3 digits continiously. 
3. After typing all the digits, you are at the right end. now press the LEFT arrow key to the start of the integerDigits, just before the radix point(dot)
4. Press the BACKSPACE from there, it start overwriting the numbers to ZERO's. Just keep pressing the BACKSPACE to the start of the integerDigits
5. Now you will notice all integerDigits are converted to ZERO's and also the radixpoint are also gone
6. Final result is 000000123

Please advise on this issue.

**Comment by babupca** [comment]
Forgot to add the jsfiddle linke
http://jsfiddle.net/BA251281/ug16s3tw/

**Comment by RobinHerbots** [comment]
I cannot reproduce the behavior you mention.  Tested in Chrome

2014-11-07 8:57 GMT+01:00 babu notifications@github.com:

**Comment by RobinHerbots** [comment]
@babupca , 

But I see that you can totally delete the integer part resulting in .123 which should be 0.123

**Comment by babupca** [comment]
Robin i'm also using chrome browser. But I can able to reproduce the issue. May be my steps is not much clear i think, again i will clearly mention it.
1. initially it will be  - 0.000
2. Now Type - 123221.123 (Note : digits values of (123) is required then only you can reproduce it) 
3. Now move your cursor to  before the decimal point --   123221(cursor Here).123 
4. Now Start pressing the BACKSPACE 
5. Now you will see  --   Keep pressing the BACKSPACE, untill all numbers are replaced by ZERO

123220.123
123200.123
123000.123
120000.123
100000.123
000000123  - final result (here radix point is also removed)

Here instead of deleting the integerDigits, it is replacing with ZERO's and also the radixpoint also gets removed.

![issue](https://cloud.githubusercontent.com/assets/2504343/4950969/dbbf1754-6661-11e4-919c-70786ae70089.png)

**Comment by RobinHerbots** [comment]
@babupca , 

On which platform are you testing?

**Comment by babupca** [comment]
@RobinHerbots,

I use windows 7 and in that i have chrome browser installed.

**Comment by RobinHerbots** [comment]
@babupca, 

Which versionof chrome are you using?  Do you have the same in IE or FF?

**Comment by babupca** [comment]
@RobinHerbots 

in both the browsers it is occuring 
Chrome Version 38.0.2125.111 
Firefox 
I don't have the latest ie, so i did not test in that.

**Comment by RobinHerbots** [comment]
Can you retest with latest verdion?

**Comment by babupca** [comment]
@RobinHerbots ,

Yes robin let me check it now.

**Comment by babupca** [comment]
@RobinHerbots ,

I think this issue is fixed.
