### ISSUE TITLE
input type email does not render email alias

### ISSUE THREAD

**Issue by KrunchMuffin** [RobinHerbots/Inputmask#724]
I was going crazy trying to figure out why the email alias was not working, turns out `input type="email"` will break it. Is this a known issue? I couldn't find anything about it.

**Comment by RobinHerbots** [comment]
@KrunchMuffin, 

Only input type text & tel are tested and allowed.  It is not yet documented in the readme.

Does the type="email" sets some restriction on the input?  I will need to verify

**Comment by KrunchMuffin** [comment]
There is no restriction.

> The email type is used for input fields that should contain an e-mail address. Depending on browser support, the e-mail address can be automatically validated when submitted. Some smartphones recognize the email type, and adds ".com" to the keyboard to match email input.
> http://www.w3schools.com/html/html5_form_input_types.asp

Will also show the `@` symbol on keybaord

**Comment by RobinHerbots** [comment]
@KrunchMuffin , 

Just tested with the type-email and enabled it in the inputmask but it doesn't play well.
It needs further testing.  The caret positioning seem to fail.

You can enabled it by modifying the  function isInputTypeSupported(inputType) {.

**Comment by KrunchMuffin** [comment]
I enabled it, but in Chrome I got
`Uncaught InvalidStateError: Failed to set the 'selectionStart' property on 'HTMLInputElement': The input element's type ('email') does not support selection.`

**Comment by Mottie** [comment]
Related to [#828](https://github.com/RobinHerbots/jquery.inputmask/issues/828#issuecomment-76715820)... modern browsers no longer support selecting text in input type email and number. See that other issue for more details.

**Comment by brada1703** [comment]
Any update on this? I realize this is a few years later, but I'm having the same issue.
