### ISSUE TITLE
Prevent onincomplete from firing if nothing entered

### ISSUE THREAD

**Issue by KrunchMuffin** [RobinHerbots/Inputmask#725]
I know technically that it is incomplete, but if the field is not required, I don't want to fire the onincomplete event if they tab to it and off of it. Is there a way to do that?

**Comment by RobinHerbots** [comment]
@KrunchMuffin , 

You can add a check for it's requirement within the onincomplete, or only add a function to the callback when it is needed.

**Comment by KrunchMuffin** [comment]
Ya, I just did a check for `val().length`, I thought it would add the mask in the val(), but it doesn't. Thx!
