### ISSUE TITLE
Clearing country name for phone numbers is field is cleared

### ISSUE THREAD

**Issue by mikerockett** [RobinHerbots/Inputmask#728]
Literally just found this plugin - really think it's awesome!

One question: If one begins entering a phone number (`alias: phone`), and the country is shown, how do I get it to remove the country if the field is cleared? Any specific event?

I'm using a similar setup (to the demo) with `.next().text()`.

**Comment by RobinHerbots** [comment]
There is the oncleared callback which you can use.

**Comment by mikerockett** [comment]
Perfect, thanks :+1:
