### ISSUE TITLE
Home button doesn't work

### ISSUE THREAD

**Issue by answer261** [RobinHerbots/Inputmask#729]
Have founded such issue when typing some text and clicking on home button, text cursor doesn't stand at the beginning of the input. 
Can you give me some advise to fix it? Thanks!
http://jsfiddle.net/vp9090gq/

**Comment by RobinHerbots** [comment]
I will have a look on wednesday.

**Comment by RobinHerbots** [comment]
@answer261 , 

Fixed in the latest commit.

**Comment by RobinHerbots** [comment]
http://jsfiddle.net/vp9090gq/1/

**Comment by answer261** [comment]
@RobinHerbots big thanks!
