### ISSUE TITLE
Input mask displaying regex and breaking on key press

### ISSUE THREAD

**Issue by inoda** [RobinHerbots/Inputmask#730]
Before typing:
![](https://dl.dropboxusercontent.com/spa/q811k4gyl5w9pcc/12dgcva1.png)

On key press:
![](https://dl.dropboxusercontent.com/spa/q811k4gyl5w9pcc/5svcf2p4.png)

I'm trying to implement the currency extension. I have included the jquery.inputmask and jquery.inputmask.numeric.extensions file.

![](https://dl.dropboxusercontent.com/spa/q811k4gyl5w9pcc/33puv03v.png)

**Comment by RobinHerbots** [comment]
I will have a look on wednesday.  Can you make a jsfiddle for it.

**Comment by RobinHerbots** [comment]
@inoda , 

I do not see a problem here.

Can you make a jsfiddle which shows the problem.

Robin

**Comment by inoda** [comment]
I think there was other JS code interfering with your plugin.

On Wed, Nov 12, 2014 at 3:28 AM, Robin Herbots notifications@github.com
wrote:

> @inoda https://github.com/inoda ,
> 
> I do not see a problem here.
> 
> Can you make a jsfiddle which shows the problem.
> 
> Robin
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/RobinHerbots/jquery.inputmask/issues/730#issuecomment-62691056
> .

## 

*Isaac Noda http://www.isaacnoda.com/ *| Web Developer
- LinkedIn https://www.linkedin.com/in/isaacnoda
- GitHub https://github.com/inoda
- Twitter https://twitter.com/isaac_noda
