### ISSUE TITLE
Numeric mask - Error with an asigment

### ISSUE THREAD

**Issue by manrueda** [RobinHerbots/Inputmask#731]
Hi @RobinHerbots ,

I was testing some modules of my project and find that the plugin fails when a certain number is assigned to the input. I don't known why this happens, but with the number in the example is easy to reproduce.

Example: http://jsfiddle.net/ManRueda/r1okb5by/

**Comment by RobinHerbots** [comment]
I will check it tomorrow.  I made a change in check val which probably causes it.  I will add the cases in the qunit tests.

**Comment by manrueda** [comment]
Hi @RobinHerbots 

There are any news about this issue??

Thanks!

**Comment by RobinHerbots** [comment]
@ManRueda , 

It's on my todo list.  It will be fixed this week.

**Comment by RobinHerbots** [comment]
@ManRueda , 

Just a thought, ... you jave integreDigits set to 6 and give it a number 8100000 (7integers)

which result in 810.000, which is just thinking about the mask correct but when seen in numbers totally wrong.  Should this result in 999.999 ?
