### ISSUE TITLE
Decimal adds extra trailing zeros in the end of mantissa

### ISSUE THREAD

**Issue by laxmikantG** [RobinHerbots/Inputmask#732]
Hello Robin,

In decimal fields, have observed an issue. If the user inputs lesser digits in fractional part than in `data-inputmask` attribute then, the plugin adds remaining trailing zeros in the field. 

```
<input type="text"  data-inputmask="'alias': 'decimal', 'integerDigits': 3, 'digits': 10, 'allowMinus':true, 'groupSeparator': ',', 'autoGroup': true, 'groupSize': 3" value="" name="something" id="something">
```

In this field, if user only inputs `2.0`, then onblur it becomes `2.0000000000`, They're exactly same but the behaviour is not as expected. Can you please fix this too?

Thank you

Apart from this, I wanted to know one more thing from you. Can we get the type of the field? i.e integer', 'decimal', etc. I mean does your plugin support the feature?  Something like, `$input.data_inputmask.alias` Please let me know.

Thank you

**Comment by RobinHerbots** [comment]
@laxmikantG , 

The latest commit fixes the first.  It will autofill the digits only when there are required on blur.

You can get info from the mask by getting the metadata (getmetadata)  But it does not return the alias but the mask used.

**Comment by laxmikantG** [comment]
@RobinHerbots :- Thanks for solution, as well as for the answer.  :+1: :+1:
