### ISSUE TITLE
date mask Text field getting selected on TAB-OUT (only in Mozilla Firefox)

### ISSUE THREAD

**Issue by babupca** [RobinHerbots/Inputmask#733]
NOTE: This issue is occuring only in mozilla firefox.

On tab out from the text field, i wanted to auto populate the date in the text field. I added it and it is working fine in chrome browser, but not in FIREFOX browser.

EX:   dd.mm.yyyy  ( if i type 12 and tabout the month and year should be autopoluted and moved towards the next field. But instead, it is selecting the field in mozilla firefox.

Let me know, how to fix this issue.

Jsfiddle link
http://jsfiddle.net/BA251281/w1ogv3e0/4/ 
![textfield_selection_error](https://cloud.githubusercontent.com/assets/2504343/5069407/c7246e68-6e7f-11e4-8ea4-bc96fece2f59.png)

**Comment by RobinHerbots** [comment]
@babupca , 

This is because setting the value in the tab-out refocuses the input.  I will see what I can do.

**Comment by babupca** [comment]
@RobinHerbots ,

Please note that, this issue is occuring only in Mozilla firefox browser.

**Comment by babupca** [comment]
@RobinHerbots ,

Hi Robin, I was just trying this today and it is fixed i guess. This seems to be tabbing to the next input field instead of same field, which was the issue.

Could you please check this please. Other wise we can close this defect.

**Comment by babupca** [comment]
@RobinHerbots ,

Hi Robin, I was just trying this today and it is fixed i guess. This seems to be tabbing to the next input field instead of same field, which was the issue.

Could you please check this please. Other wise we can close this defect.

**Comment by RobinHerbots** [comment]
@babupca , 

Is this a hitch in the matrix?

**Comment by babupca** [comment]
@RobinHerbots ,

Yes it was. but now it seems to be fixed.
