### ISSUE TITLE
Mask On Divs

### ISSUE THREAD

**Issue by afattahi54** [RobinHerbots/Inputmask#734]
Hi,

Is it possible to apply this mask on static contents like div:
Please see http://igorescobar.github.io/jQuery-Mask-Plugin/

Regards,
Alireza Fattahi

**Comment by RobinHerbots** [comment]
@afattahi54 , 

Yes and no, ... you can use the $.inputmask.format fn and set the result on the div.
You cannot currently select a div or other element then an input as target.

Maybe I can add that functionality.

**Comment by SnidelyWhiplash** [comment]
This would be awesome. I'd like to use inputmask on a `contenteditable` element. Bump? Or @RobinHerbots can you provide a quick demo of how one might use `$.inputmask.format` to achieve this? Thanks for a great plugin!

**Comment by RobinHerbots** [comment]
@SnidelyWhiplash , 

contenteditable element with an inputmask that is yet another nice feature to add ;-)

This is about formatting static content on say a DIV like in the above mentioned div.

something like => $("thediv").text($.inputmask.format("1231231234", { mask: '(999) 999-9999' }));

**Comment by simasalmani** [comment]
@RobinHerbots, thanks for this great plugin and it would be awesome if you could add the functionality of applying inputmask on static contents.

**Comment by lilibit1985** [comment]
Dear mr @RobinHerbots ,

First of all, you 've done a greate job. This plugin is awsomawesome!
Could you please add the functionality to apply this mask on static contents like div,too? 
Thank you in advance for any help you can provide.

Best Regards 
lilibit1985

**Comment by RobinHerbots** [comment]
@afattahi54 , @SnidelyWhiplash @simasalmani , @lilibit1985 , 

I added support for masking elements (tested on div) with the contenteditable attribute.

Masking on static elements will come very very soon.

http://jsfiddle.net/paqujz5w/

**Comment by RobinHerbots** [comment]
http://jsfiddle.net/paqujz5w/2/

**Comment by afattahi54** [comment]
Thanks it is very hopeful and we switched to this plugin !!
It seems that the mask is not working on all elements. Please see http://jsfiddle.net/paqujz5w/7/

The test2 div will not update with mask!

``` html
 <div id="test1" style="width: 200px;">123456789</div>

<table>
    <tr>
        <td id="test1" style="width: 200px;">123456789</td>
    </tr>
</table>
```

**Comment by RobinHerbots** [comment]
Only on divs and contenteditable elements. Maybe i also shoyld allow on other elements.

**Comment by afattahi54** [comment]
It will be very good if you can allow it to work on all HTML elements. The project I mentioned,  http://igorescobar.github.io/jQuery-Mask-Plugin/, do this static mask  on all elements .

By the way, I have switch to your plugin and it seems the most full featured mask until now!

**Comment by RobinHerbots** [comment]
The latest commit allows for masking other html-elements.

**Comment by afattahi54** [comment]
Thanks for that !

**Comment by dhg** [comment]
Not sure if I'm missing something, but was digging through this thread and found the linked "working" mask on a static element by @RobinHerbots, but it doesn't seem to work anymore (http://jsfiddle.net/paqujz5w/2/)? 

Was wondering if this has been deprecated or is used differently now?

**Comment by RobinHerbots** [comment]
@dhg , 

Masking on a "static" element is working again.
