### ISSUE TITLE
the caret position goes to the last symbol

### ISSUE THREAD

**Issue by pchelailya** [RobinHerbots/Inputmask#736]
same error as 
https://github.com/RobinHerbots/jquery.inputmask/issues/272

old mask 9999 9999 9999 9999

function check_ApplicationCreditCardNumber_symbol(){
        var input = context.find('#ApplicationCreditCardNumber');
        var result=validate_CC_type();
        if(!(result.card_type ==undefined) &&  result.card_type.name==='maestro' ){
            $(input).inputmask({mask:"99999999 9999999999",placeholder: "0"});
        }
    }

after check_ApplicationCreditCardNumber_symbol
the caret position goes to the last symbol
plz fix this

**Comment by pchelailya** [comment]
"version": "3.1.38",

**Comment by RobinHerbots** [comment]
@pchelailya , 

Refixed in the latest version
