### ISSUE TITLE
Compilation error with YUI compressor

### ISSUE THREAD

**Issue by tetronomis** [RobinHerbots/Inputmask#737]
The YUI compressor returns an error on this line: "missing ) in parenthetical"

var ua = ("function" == typeof ScriptEngineMajorVersion ? ScriptEngineMajorVersion() >= 10 : /_@cc_on (@_jscript_version >= 10) ||@_/ !1, 
        navigator.userAgent)

**Comment by RobinHerbots** [comment]
@tetronomis , 

The code isn't needed anymore.  So I removed it and so resolves the issue.
