### ISSUE TITLE
Unicode values mangled on dist versions

### ISSUE THREAD

**Issue by dslack** [RobinHerbots/Inputmask#738]
Using the library for the first time, and found that the unicode values for definitions like 'a' and '#' are being mangled (most likely by uglify).

For example,  
A: { validator: "[A-Za-zА-яЁёÀ-ÿµ]"

See https://github.com/mishoo/UglifyJS2/issues/54

**Comment by RobinHerbots** [comment]
@dslack , 

Thx for reporting, I will try to fix that asap.

**Comment by dslack** [comment]
Awesome!  thanks for the quick commit!

**Comment by AhmadBeyranvand** [comment]
You can search "definition" in `inputmask.js` and change letter range.
Example: (I was Added Arabic and Persian Characters to validator in "a" validator)
`
definitions: {
                "9": {
                    validator: "[0-9]",
                    cardinality: 1,
                    definitionSymbol: "*"
                },
                a: {
                    validator: "[A-Za-z\u0410-\ufeff]",
                    cardinality: 1,
                    definitionSymbol: "*"
                },
                "*": {
                    validator: "[0-9A-Za-z\u0410-\u044f\u0401\u0451\xc0-\xff\xb5]",
                    cardinality: 1
                }
            }
`
You can get Unicode characters codes form[Unicode Site](http://unicode.org)

**Comment by RobinHerbots** [comment]
@ahmadb1881 , 

You can change the definitions with 
```
Inputmask.extendDefinitions( { "9": { validator: "[0-9]", cardinality: 1, definitionSymbol: "*" }, a: { validator: "[A-Za-z\u0410-\ufeff]", cardinality: 1, definitionSymbol: "*" }, "*": { validator: "[0-9A-Za-z\u0410-\u044f\u0401\u0451\xc0-\xff\xb5]", cardinality: 1 } });
```
There is no need to change the inputmask.js.
