### ISSUE TITLE
Plugin sends null instead of 0

### ISSUE THREAD

**Issue by gmrash** [RobinHerbots/Inputmask#739]
Hello, 
I use inputmask currency for my field. I need to send value to database, but it does not send value 0.

$( '#order_paid_sum' ).val(0)
//Rails log shows:  "paid_sum"=>""

$( '#order_paid_sum' ).val(500)
//Rails log shows:  "paid_sum"=>"500"

```
$('#order_paid_sum').inputmask("currency", { prefix: "", groupSeparator: " ", removeMaskOnSubmit:      true });

function check_paid_status(val){
    if (val == 1) {
        $( '#order_paid_sum' ).val(0)
    } else if  (val == 2) {
        $( '#order_paid_sum' ).val(500)
    }
}

check_paid_status($('#order_order_paid_status_id').val())

$('#order_order_paid_status_id').change(function () {
    check_paid_status($(this).val())

});
```

**Comment by RobinHerbots** [comment]
@gmrash , 

On submit it send the 0.00 (verified) but when getting the 0 with .val() it returns nothing because it matches the initial mask.

Add the autoUnmask: true option to get the desired result.

**Comment by gmrash** [comment]
Thank you, It works.
