### ISSUE TITLE
inputmask & jscalendar mouse over issue

### ISSUE THREAD

**Issue by gibacca** [RobinHerbots/Inputmask#74]
When I use jscalendar (http://www.dynarch.com/projects/calendar/old/) to populate a field controlled by input mask, then move the mouse over and then out of the field, the field content changes to either empty, or "previous value" - inserted by actually typing into the field.
For an example, see my site at http://ec2-23-23-238-65.compute-1.amazonaws.com/search/index, use the calendar widget to insert the dates, and then move the mouse as described above.
I noticed this change a month or 2 ago, I think this used to work correctly with jscalendar before.

**Comment by petefaux12** [comment]
We had this issue as well, for now we added some buffer initialization to the mouseenter.inputmask function and the blur.inputmask functions that looks like this:

```
                    buffer = new Array();
                    for (var i = 0; i < input._valueGet().length; i++) {
                        buffer[i] = document.getElementById(input.id).value.charAt(i);
                    }
```

**Comment by RobinHerbots** [comment]
Hi, 

I will have a look at it.

best regards, 

Robin

**Comment by RobinHerbots** [comment]
Hi Gibacca, 

Can you retest with the latest version.

Best regards, 

Robin

**Comment by petefaux12** [comment]
that change appears to work well for me.  :-)

**Comment by gibacca** [comment]
Yes, indeed, I do not see the content disappearing on mouseover... Thank you.
