### ISSUE TITLE
JS Runtime Error - IE 8

### ISSUE THREAD

**Issue by manrueda** [RobinHerbots/Inputmask#740]
Hi @RobinHerbots 

I was trying the last change to use the fix about the big numbers, and now the plugin crash on every mask, but only in IE8. I track the error line to this change 0ef26ee0068cbf0836dd4a5e189e9085d32cba2d where you add the line "if (e) e.preventDefault();" and crash on it.

I can't give you a jsfiddle because i can't run it on IE8.

Thank!!

**Comment by RobinHerbots** [comment]
Sorry i didn't test on ie8.  I will fix that asap.

**Comment by manrueda** [comment]
Thanks @RobinHerbots !!

**Comment by RobinHerbots** [comment]
@ManRueda , 

Is this only happening in the real IE8 or also in IE10 in IE8 mode?

**Comment by RobinHerbots** [comment]
@ManRueda , 

Can you confirm that it is fixed?

**Comment by manrueda** [comment]
@RobinHerbots 

Works great!!!

Thank!
