### ISSUE TITLE
numeric display

### ISSUE THREAD

**Issue by innah** [RobinHerbots/Inputmask#743]
Hi,

I've an element with this parameters:

``` javascript
$('.weight-mask').inputmask({alias: 'numeric', groupSeparator: "'", autoGroup: false, groupSize: 3, digits: "2", digitsOptional: false, prefix: "", suffix: " kg", placeholder: "0.00", rightAlign: false, greedy: true});
```

But, when i write "100" without ".00", the input convert into "100.0. kg". Do you know where is the problem ?

If i change "placeholder" to "0", i can't write "0" or "0.00" because he disable the result and i can't save my input because i need a value.

Thank you very much.

**Comment by RobinHerbots** [comment]
@innah , 

Can you try with placeholder set to "0" and add the autoUnmask: true option,

**Comment by innah** [comment]
@RobinHerbots ,

The value is always invisible when I began to "0" or "0.00". So I can not save the form. Perhaps a problem with Chrome?

**Comment by RobinHerbots** [comment]
@innah , 

Can you workout a jsfiddle to make it more clear.

**Comment by innah** [comment]
@RobinHerbots ,

http://jsfiddle.net/8tnyrjz3/

Many thanks

**Comment by RobinHerbots** [comment]
@innah , 

try using with the options in http://jsfiddle.net/8tnyrjz3/2/

**Comment by innah** [comment]
It works! Thank you very much :)
