### ISSUE TITLE
Android issue with Text previsioning enabled

### ISSUE THREAD

**Issue by mserioli** [RobinHerbots/Inputmask#745]
Hi all.

I'm having strange behaviour on a Samsung Galaxy Tab Android 4.1.2 using (now) chrome 39.0.2171.59. It happens also with native browser and firefox 33.1

The problem appears when Text Previsioning is enabled. I'm using the following inputmask

```
<input id="_elem_id" name="elem" class="form-control valid" type="text" value="12.00" 
    autocomplete="off" aria-required="true" maxlength="7" aria-invalid="false" 
    style="text-align: right;">

$(function() {
    $("#_elem_id").inputmask("decimal");
});
```

When I input values into this input type values are replaced with different one.

for example input 11.123 from keyboard will result into 11.11

Input 76 result in 77.

While input 76, it displays 77 in text field, but if I select keyboard suggestion the textbox content became: 77767.

Disabling text provisioning everything goes ok!

Hope there an explanation!

Thank you and congratulations for the project, it is very useful

**Comment by kamilklosowski** [comment]
Hello,

I've came across to same issue. 

Any help will be appreciated.

**Comment by mserioli** [comment]
Hi and thank you for the rapid fix proposed. Is seems better now: 

If I write 12 it do not modify into 11,

 but if I wrote for example

13.1 -> it works

If I wrote 2 decimals, for example
13.12 -> 13.113.12

Thank you very much

**Comment by RobinHerbots** [comment]
@mserioli , 

Thx for the feedback.

I'm aware of the above problem.  It is causes due that typing 13.1 is a composition and 13.12 a second, but with the complete input from the previous.  
I should read a bit about the composition events again.  Does the composition adds to the input of replaces it?  A solution to the above is could be just replacing the whole input  and masking on the new composition data.

For the moment the masking is done on compositionend.  Later I can add masking on compositionupdate to get a more visual feedback when typing if that is possible.

**Comment by mserioli** [comment]
@RobinHerbots

Thank you for your quick reply 

The composition add the input between the inputed text. Tomorrow I will be more precise, I have not a tablet with me rigth now.

**Comment by mserioli** [comment]
@RobinHerbots 

Here you are the sequence of inputs -> results on my tablet:

1 => 1
12 => 12
12. => 12.
12.1 => 12.1
12.12 => 12.1<b>12.12</b>

Then when I focus over the input field It's be converted into: 12.121

**Comment by mserioli** [comment]
@RobinHerbots

Thank you for experimental commit. Now the behaviour is the same as explained above:

1 => 1
12 => 12
12. => 12.
12.1 => 12.1
12.12 => 12.1<b>12.12</b>

Buf when the input type lose focus the result is displayed correctly.

It still have problems with more complex  pattern, like date mask field

Thank you!

**Comment by RobinHerbots** [comment]
@mserioli, 

Now that i'm busy with android.  Shoot the problems of the other mask too.

I tried the email mask and that is working.  I noticed a missing keypress event, when typing numeric chars and that is probably why the above occurs.

**Comment by mserioli** [comment]
@RobinHerbots

I'm using a mask like this

```
inputmask("d-m-y",{ "placeholder": "_" })
```

When I type text the mask is translated to the right:

```
1__-__-____
12__-__-____
121__-__-____
1210__-__-____
12102__-__-____
121020__-__-____
1210201__-__-____
12102010__-__-____
```

**Comment by RobinHerbots** [comment]
@mserioli , 

Why don't you try .inputmask("date", { insertMode: true });

**Comment by mserioli** [comment]
@RobinHerbots

Not working

1 => 1_-**-__**
12 => 12-**-__**
121 => 12-1_-____
1210 => 12-10-____
12102 => 10-**-__**
121020 => 10-**-__**
1210201 => 01-**-__**
12102010 => 01-**-__**

Nothing change using insertmode.

Thank you!

**Comment by RobinHerbots** [comment]
@mserioli , 

Did you try with the latest commit?

**Comment by mserioli** [comment]
@RobinHerbots

Yes, with the last. As you can see the bahaviour change from last comment and previous.

And changing to .inputmask("date", { insertMode: true }); have no impact!

**Comment by RobinHerbots** [comment]
Very strange as on my Galaxy Ace3 S727R5 Chrome the date alias is working fine when using insertMode: true

**Comment by mserioli** [comment]
@RobinHerbots 

maybe you are using a different pattern? For the day and month all is ok, but it lacks on the year.

I'm using d-m-y

**Comment by mserioli** [comment]
@RobinHerbots 

Re-tested it more carefully.

It works using

```
.inputmask("date",{ insertMode: true })
```

but using

```
.inputmask("d-m-y",{ insertMode: true })
```

it doesn't. So the problem now is in datetime pattern.

**Comment by mserioli** [comment]
Hi @RobinHerbots 

Do you, by any chance, have verified the behaviour above?

Thanks!
