### ISSUE TITLE
Extra (

### ISSUE THREAD

**Issue by lynxlive** [RobinHerbots/Inputmask#748]
On the current version there seems to be an extra ( in the front of all masked fields... so phone numbers are ending up like ((555) 555-555, social security numbers are ending up like (555-55-555, etc.

**Comment by lynxlive** [comment]
While working on figuring out what this is, I found that if I do a mask like this:

$('.ssn').inputmask({ 
mask: "###-##-####", 
greedy: false, 
definitions: { '#': { validator: "[0-9]", cardinality: 1}} });

it works fine, but if I have it like this:

var ssns = [{ "mask":  "###-##-####" }];
$('.ssn').inputmask({ 
mask: ssns, 
greedy: false, 
definitions: { '#': { validator: "[0-9]", cardinality: 1}} });

it places the extra ( at the front of the field in the mask

**Comment by RobinHerbots** [comment]
I will fix that asap!!
