### ISSUE TITLE
input mask problem on Kindle Fire

### ISSUE THREAD

**Issue by petefaux12** [RobinHerbots/Inputmask#75]
I was wondering if anyone else happens to see this issue.  I have tested this on a couple android devices, and it appears that the problem is specific to the Kindle. 

The date input mask starts out looking like:   ////**/__**
Then typing a value will often trigger the input to automatically fill out numbers like:   12/22/2222   (after entering a one and a 2)

If you put the cursor in the date field and just let it sit there, you will notice that the field kind of blinks, sometimes with the normal mask  **/**/____ and other times with the above mask, so it appears that there might be an issue with focus being stolen and returned?  Does that make sense?  If anyone has any thoughts on this, I would appreciate any help you can give.

**Comment by RobinHerbots** [comment]
Hi Pete,

Which version of Android is running on it?  Can you simulate the problen
when using the android SDK virtual devices.

Robin

2012/6/20 petefaux12 <
reply@reply.github.com

**Comment by petefaux12** [comment]
The kindle fire uses a "modified"  2.3 version.   Working on testing in the emulator, but I'm going to guess that this might be related to that "modified" word....  :-)

**Comment by RobinHerbots** [comment]
, .... can we run a copy of the kindle fire image into an emulator?  You
can extract the image with the android sdk tools.

2012/6/20 petefaux12 <
reply@reply.github.com

**Comment by jaboc83** [comment]
This also happens on the Tablet S and Transformer tablets running Android 4 but only in Browser. Not Firefox or Chrome.

**Comment by RobinHerbots** [comment]
Hi Jake, 

With which browsers did you had the problem.  Can you simulate it on a an emulator?

robin

**Comment by jaboc83** [comment]
Android Browser on Android 4.0 on two different Android Tablets (Transformer and Tablet S), and Amazon Silk on Kindle Fire.  I don't have an android emulator.

**Comment by RobinHerbots** [comment]
Can someone send me the user agent string from a kindle fire?

**Comment by jaboc83** [comment]
Regular:

Mozilla/5.0 (Linux; U; Android 2.3.4; en-us; Kindle Fire Build/GINGERBREAD) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1

Silk Mode:

Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6_3; en-us; Silk/1.1.0-80) AppleWebKit/533.16 (KHTML, like Gecko) Version/5.0 Safari/533.16 Silk-Accelerated=true

**Comment by RobinHerbots** [comment]
I requested access to the KDK (Kindle Development Kit - currently in beta).  When I got the SDK I should be able to reproduce the problem and have a look.

**Comment by garaboncias** [comment]
I investigated this problem and it seems issue only occur when input type="tel". I reproduced with vanilia android 2.2 and 2.3. 
Jelly bean seems ok. 
Somehow keydown/keypress/keyup event triggered several times.

**Comment by RobinHerbots** [comment]
Thanks for the feedback!!

input type=text doesn't work properly under 2.2 either

2012/9/21 garaboncias notifications@github.com

**Comment by RobinHerbots** [comment]
see issue 186
