### ISSUE TITLE
Nested alternator groups not working

### ISSUE THREAD

**Issue by rogerfar** [RobinHerbots/Inputmask#750]
I am trying to validate the following:

((9{1,3})|(S|N)(E|W))-9{1,3}

Valid combinations should be:
999-999
SE-999
NE-999
SW-999
NW-999

But with the multiple groups I get the result:
(S))-123

Is there a way to nest alternators?

**Comment by RobinHerbots** [comment]
@rogier21 , 

Complexer (like nested) alternators are not yet working as they should.
For the moment try to simplify by defining them as multiple mask.  ["999-999", "SE-999", ...

It is planned to further optimize the alternators.

**Comment by rogerfar** [comment]
Ok great thanks!

I actually fixed it with definitions:

```
$('.lsd-mask').inputmask({
    mask: "(9{1,2})|(NW)-9{1,2}-9{1,3}-9{1,2} W9",
    greedy: false,
    definitions: {
        "N": {
            validator: "[nNsS]",
            cardinality: 1,
            casing: "upper"
        },
        "W": {
            validator: "[wWeE]",
            cardinality: 1,
            casing: "upper"
        }
    }
});
```

**Comment by RobinHerbots** [comment]
@yesman85 , 

(9{1,3})|(S|NE|W)-9{1,3} is currently working

Still working on 
(9{1,3})|((S|N)(E|W))-9{1,3} , .... which is actually wrong as it would result in 

123-123
(S)(W)-123
.....

anyway, the mask should work and not crash in this case
