### ISSUE TITLE
The .inputmask('unmaskedvalue')  is not working on specified masks

### ISSUE THREAD

**Issue by bakbul** [RobinHerbots/Inputmask#751]
i've this mask 
$('#example').inputmask('decimal',{radixPoint:',', groupSeparator: '.', digits: 2,autoGroup: true, numericInput: true});

then i want to get the decimal value of the input without dots. Ex: the mask value is 1.234,56 but when i want to get the unmasked value i supposed to be 1234,56.

I tried to get $('#example')..inputmask('unmaskedvalue'). However, it is given the following script error, b.regex is not defined.

Thank You for your attention.

**Comment by RobinHerbots** [comment]
@bakbul , 

Can you try with removing the numericInput: true option

**Comment by bakbul** [comment]
it remains same without the numeric input parameter

**Comment by bakbul** [comment]
Actually, i don't want to assign the value as masked, i just want to visualize it. What I really want to do that, the user will see value 1.234,56 but the real value is stored like 1234,56 in the input. Therefore, I can assign it as a decimal data type.

**Comment by RobinHerbots** [comment]
@bakbul , 

Can you make a jsfiddle for it as removing the numericinput: true options works here.

**Comment by bakbul** [comment]
http://jsfiddle.net/bu3z9c9o/1/

**Comment by bakbul** [comment]
I've fixed it using the 3.0 version of the package, thank you :)

**Comment by RobinHerbots** [comment]
@bakbul , 

In your fiddle you get the unmaskedvalue, then you set the value back to the input, which will be masked again by the inputmask and then you alert the value retrieved with $.val.

I updated your fiddle to show 2 ways you can solve this.
http://jsfiddle.net/bu3z9c9o/2/

Just alert the unmaskvalue or set the autoUnmask option to true.  Maybe it is also interesting to read about the removeMaskOnSubmit

**Comment by bakbul** [comment]
that would help, thank you :)
