### ISSUE TITLE
IE7 Date mask using date extension

### ISSUE THREAD

**Issue by liammcsheffrey** [RobinHerbots/Inputmask#752]
Hi,

When in IE7, using the date extension, it is only possible to enter the day into the input (dd/mm/yyyy).

So for instance, enter 12, and it is not possible to continue entering the mm and yyyy in IE7.

Is this a known issue?
![ie7](https://cloud.githubusercontent.com/assets/8490037/5247195/4226517e-7968-11e4-8ad5-1a39e23d71c9.png)

Any help much appreciated!

**Comment by liammcsheffrey** [comment]
Issue occurs when setting up selector with: ("dd/mm/yyyy", { "placeholder": "dd/mm/yyyy", "clearMaskOnLostFocus": false }).

Can use ("d/m/y", { "placeholder": "dd/mm/yyyy", "clearMaskOnLostFocus": false }); and it works OK, but leap years are not validated

**Comment by RobinHerbots** [comment]
@liammcsheffrey , 

Thx for the feedback, I will verify it on ie7

**Comment by liammcsheffrey** [comment]
Thanks - hopefully not too difficult to fix. We still need to make our websites support IE7 unfortunately!

**Comment by RobinHerbots** [comment]
@liammcsheffrey , 

The issue is fixed.  See latest commit in the date extensions.
A new bundle and release will follow soon.

**Comment by liammcsheffrey** [comment]
Excellent! Many thanks
