### ISSUE TITLE
Numeric mask - The decimal autocomplete doesn't work

### ISSUE THREAD

**Issue by manrueda** [RobinHerbots/Inputmask#753]
Hi @RobinHerbots 

I just find an issue that i think was fixed some time ago. If i set a decimal mask, write 100 for example and press TAB, the decimal part does not complete automatically.

Example: http://jsfiddle.net/ManRueda/1ndmwf4L/

**Comment by RobinHerbots** [comment]
@ManRueda , 

You have to set digitsOptional: false as option.

http://jsfiddle.net/1ndmwf4L/1/

**Comment by manrueda** [comment]
@RobinHerbots 

Ohhh I knew it was that property, but I could not find in the documentation...

Thanks!!!
