### ISSUE TITLE
Numeric inputMask doesn't rounds value

### ISSUE THREAD

**Issue by mtomas-mpm** [RobinHerbots/Inputmask#754]
Hi,

I'm using your control to show some calculated percentages, and when I'll try to set a value with more decimal digits than the defined on the mask, the value is truncated, and I'll expect to be rounded.

JSFiddle: http://jsfiddle.net/nmu49ufe/

Is there any plan to correct it? Or I'll must round the value before to set to the input mask?

Thanks a lot,

Marc.

**Comment by RobinHerbots** [comment]
@mtomas-mpm , 

It is not yet planned, but it sounds like a nice idea.  
I will add a rounding option

**Comment by mtomas-mpm** [comment]
Oh thanks! I'll implement a temporary solution waiting for the next release.

**Comment by mtomas-mpm** [comment]
Cool! it's working fine on the same fiddle posted on the first comment: http://jsfiddle.net/nmu49ufe/

**Comment by miguellobato84** [comment]
if the number of decimals is 0, is is not rounding properly

**Comment by miguellobato84** [comment]
Not a solution, but working in my case:

                onBeforeMask: function(initialValue, opts) {
                    if (opts.isNegative = undefined, initialValue = initialValue.toString().charAt(initialValue.length - 1) === opts.radixPoint ? initialValue.toString().substr(0, initialValue.length - 1) : initialValue.toString(), 
                    "" !== opts.radixPoint && isFinite(initialValue)) {
                        var vs = initialValue.split("."), groupSize = "" !== opts.groupSeparator ? parseInt(opts.groupSize) : 0;
                        2 === vs.length && (vs[0].length > groupSize || vs[1].length > groupSize || vs[0].length <= groupSize && vs[1].length < groupSize) && (initialValue = initialValue.replace(".", opts.radixPoint));

>                         if (2 === vs.length && 0 === opts.digits && parseFloat("0." + vs[1]) > 0.5)
>                             initialValue = (parseInt(vs[0]) + 1).toString() + opts.radixPoint + vs[1].toString();

                    }
