### ISSUE TITLE
jQuery input mask with two different user inputs

### ISSUE THREAD

**Issue by herby86** [RobinHerbots/Inputmask#755]
Hey,

I'm not sure, if it's a bug or I'm doing something wrong. I want to create an input, which takes two different values by the user. It should look like this [X.XXX$ for X years]. The Xs are input values. Is it possible to realize that with jquery.inputmask?

I tried the following but it won't work:

$(document).ready(function(){
   $('.query').inputmask({
       mask: '9.999$ for 9?9 years',
       placeholder: '1.000$ for 2 years'
   });
});

Is there a possibility to attach "fix" default text AFTER an user input?

Thanks a lot!

**Comment by RobinHerbots** [comment]
@herby86 , 

See http://jsfiddle.net/jaokqLxe/
