### ISSUE TITLE
composer?

### ISSUE THREAD

**Issue by ghost** [RobinHerbots/Inputmask#756]
Tried to get this go with composer. Is it possible you will add a composer.json file later?

**Comment by RobinHerbots** [comment]
@brownrl , 

Can you send a PR for the composer.json.  Do I need to register the package?

**Comment by RobinHerbots** [comment]
@Senn0 , 

I know ;-)

**Comment by senneclaeskens** [comment]
@RobinHerbots ok :-), wasn't aware because you asked if you had to register the package.
btw: nice library, I really like it!

**Comment by ghost** [comment]
There are a number of Javascript packages that do composer gists. For example bootstrap and jquery.

While the focus can be said to be PHP, it's useful for all sorts of things. For the time being here is what I am doing in my project composer.json.

``` json
"repositories": {
    "inputmask": {
        "type": "package",
        "package": {
            "name": "RobinHerbots/jquery.inputmask",
            "version": "1.0.0",
            "source": {
                "url": "https://github.com/RobinHerbots/jquery.inputmask",
                "type": "git",
                "reference": "c95fe993f91e1da2069a26d84eaa372835842286"
            }
        }
    }
  }
```

Then in the require part:

``` json
"RobinHerbots/jquery.inputmask": "1.*"
```

This unfortunately locks me into a certain commit. So I will need to check from time to time and update which commit. Not the end of the world...

**Comment by RobinHerbots** [comment]
https://packagist.org/

**Comment by RobinHerbots** [comment]
@brownrl ,@Senn0 ,

I added a composer.json and regitered at the http://packagist.org/

I also added a service hook but I'm not sure that works already.  We shall see on the next release.

Can you have a try and any suggestion to improvement is welcome ;-)

**Comment by ghost** [comment]
AWESOME!!!!!! thank you so much.

I know that "javascripts" aren't the intended purpose of composer... but composer is becoming more of the catch all way of tying everything together in a project.
