### ISSUE TITLE
Certain phones not inputable

### ISSUE THREAD

**Issue by DimanKuskov** [RobinHerbots/Inputmask#758]
There is no way to input +996557111600 phone, although +996(###)###-### is specified in phone-codes. After inputing 996 the next symbol is forced to be 6.
The problem is related to bracets in mask, which makes the mask break into tokens by tokenizer. Replacing mask with +996-###-###-### helps to solve the problem, but spoils the view.

**Comment by gregbiv** [comment]
any update? same issue

**Comment by RobinHerbots** [comment]
@gregbiv , 

No not yet, but if you look at the assigns, you can see that I plan to look into it.  All related issues.

**Comment by RobinHerbots** [comment]
@DimanKuskov , @gregbiv , 

Fixed with the latest commit
