### ISSUE TITLE
Not pasting value in masked input field

### ISSUE THREAD

**Issue by lmbelo** [RobinHerbots/Inputmask#759]
I'm trying to use the following mask on a input field:

$('#input-cnpj').inputmask(
            {
                "mask": "99.999.999/9999-99", 
                "numericInput": true, 
                "autoUnmask" : true  
            }

When I paste the value, the cursor is set on the end of the mask after "-99" and so the value is not pasted. So, if i press "Home" button, the cursor is positioned to the beggining of the mask and so the value is pasted. To see what was happening I tryed to use the event "onBeforePaste" and the parameter passed to function returned a string like this "15720358000197__-____/**_.**_.__". The pasted value is on beggining and the mask comes as following.

**Comment by RobinHerbots** [comment]
@lmbelo, 

Which version do you use?  And on which browser.

**Comment by lmbelo** [comment]
Version in Readme.md: 3.x
Version in dist files: 3.1.32

Tested on Chrome, Firefox and IE

**Comment by RobinHerbots** [comment]
@lmbelo , 

I made a jsfiddle for it http://jsfiddle.net/hdqnadhj/

The problem i see is when you paste the value repeatedly, it gets reversed.

**Comment by lmbelo** [comment]
Is not getting reversed, is not getting pasted. But in your example it works. I have 3 places on my application that uses this mask and both presents problems with paste.

**Comment by lmbelo** [comment]
Is there a way to show to you?

**Comment by lmbelo** [comment]
I saw that you are using jQuery 1.11.0 on jsfiddle and I use http://code.jquery.com/jquery-latest.min.js that cames with 1.11.1. Could be a problem?

**Comment by RobinHerbots** [comment]
Can you try with latest verdion of inputmask

**Comment by RobinHerbots** [comment]
You can chat with gmail or skype.

**Comment by lmbelo** [comment]
Ok, I'm going to try it.

**Comment by lmbelo** [comment]
It's working pretty well in new released version

**Comment by RobinHerbots** [comment]
@lmbelo , 

Ok, that is good news ;-)
