### ISSUE TITLE
Multiple masks

### ISSUE THREAD

**Issue by ishytow** [RobinHerbots/Inputmask#760]
Hi,

1) Is it possible to set more then two masks for one input (e.g. mask: ["9+9", "99+99", "99+99+99"])?
2) is it possible to set masks as ["99+99+99", "+99+99+99+99"]. Steps:
1. user complete first mask 12+34+56
2. continue typing and plugin toggles to the next mask +12+34+56+4_ ... 
   Is it possible or is there any workaround?

Thanks,

Best regards,
Ilya Shytov

**Comment by RobinHerbots** [comment]
@ishytow , 

Have a look at http://jsfiddle.net/8gx6szh5/

**Comment by ishytow** [comment]
Thanks a lot!
But is it possible to set mask list as it is here: http://jsfiddle.net/8gx6szh5/1/. Where the third mask is "+99+99+99", Can I some how make first plus optional (e.g.: "[+]99+99+99")?

http://jsfiddle.net/8gx6szh5/2/ - this is more clear example

**Comment by RobinHerbots** [comment]
@ishytow , 

There are still some issues in the alternation for multiple masks.
I will have a look at the mask in the second example and see how to fix it.

**Comment by ishytow** [comment]
Thank you very much!
I will wait with impatience.

**Comment by VolodymyrMuzyka** [comment]
Hi!
Please check this http://jsfiddle.net/79m65yt3/2/ , I believe it's related.. 
We have masks like this: '0X XXXX XXXX' OR '04XX XXX XXX' OR '1300 XXX XXX' OR '1800 XXX XXX' OR '13X XXX' and they are working fine with version 2.5.10.. latest 3.1.61 doesn't.

Test cases which works on 2.5.10:
1) type 1300 than space - not allowed. i.e. 1300 000 000 not possible to enter
2) type 132 than space -132 000 not possible.

Thank you,
Vlad

**Comment by RobinHerbots** [comment]
@ishytow , 

Your alternation is finally working.

@aeont , 

I created a separate issue for your case  #1132

**Comment by VolodymyrMuzyka** [comment]
Thank you! Tested on 3.3.2-106 - all works as expected
