### ISSUE TITLE
Windows Phone IE input with inputmask doesnt seem to work

### ISSUE THREAD

**Issue by NikoKyriakid** [RobinHerbots/Inputmask#761]
It renders the mask-placeholder dd/mm/yyyy but when you type numbers using software keys the position jumps to the end of mask. However the dd gets its value but the mm not. After the jump you can edit only the last digit of the year mask part.

**Comment by RobinHerbots** [comment]
@k-nickos , 

Windows Phone is untested, but I will have a look at it.  Within an emulator or so.

**Comment by NikoKyriakid** [comment]
@RobinHerbots 
Great plugin btw. If you would like to test it, just for you to know the browserstack emulators doesn't apply the mask to the input at all I think. So the input becomes simple text input. However the 2 actual windows phones that I tried, they applied the inputmask but with this issue.

**Comment by RobinHerbots** [comment]
@k-nickos , 

I tested with the WinPhone 8.1 emulator with visual studio and see no problem.

**Comment by marnen** [comment]
I'm not the one who was asking about this.

**Comment by RobinHerbots** [comment]
@marnen , 

Sorry ;-)

**Comment by HumungusFungus** [comment]
Hello @RobinHerbots,

We are facing the same problem in Windows Phone 8.1. Do you have an estimated time for publishing version 3.3?

Thank you very much.

**Comment by HumungusFungus** [comment]
Hello @RobinHerbots,

Is there any new about this issue?

Thank you very much.

**Comment by RobinHerbots** [comment]
@NickKyriakidis , @HumungusFungus ,

Can someone give some more feedback.  Is this still the case.  Does it bahave the same for all masks or just for a specific one.  Is this reproducible throught emulation?  Browserstack?  Visual Studio?

Is there some error?
