### ISSUE TITLE
Typing polish letter "ż" deletes all characters typed before :(

### ISSUE THREAD

**Issue by julex18** [RobinHerbots/Inputmask#762]
ex. $("#City").inputmask('Regex', { regex: "[a-zA-ZęóąśłżźćńĘÓĄŚŁŻŹĆŃ /-]{0,50}" });

**Comment by RobinHerbots** [comment]
@julex18 , 

Is this in all browsers?

**Comment by julex18** [comment]
I tested it in Chrome 39.0.2171.95 m, Firefox 34.0.5, IE 11 

InputMask Version: 3.1.47 (didn't test other versions)

If I paste ż or Ż it's ok but if I type it then everything before gets deleted. 

The key combination on Polish programmer's keyboard (the standard windows choice for Polish) is right alt + z, maybe it's some key scancode thing.

Other polish chars are ok (śćźńłóęąź)

Simplest page (to exclude other script's interference):
<html><body>
    <script src="js/ext/jquery-1.8.3.min.js"></script>
    <script src="js/ext/jquery.inputmask.bundle.min.js"></script>
    <input id="input1" />
    <script type="text/javascript">
        $('#input1').inputmask('Regex', { regex: "[a-zA-ZęóąśłżźćńĘÓĄŚŁŻŹĆŃ /-]{0,50}" });
    </script>
</body></html>

**Comment by RobinHerbots** [comment]
@julex18 , 

Thx for the feedback, I will have a test, but I first need to setup my keyboard to polish.;-)

**Comment by julex18** [comment]
You might find these useful:
http://en.wikipedia.org/wiki/%C5%BB (Ż letter wiki page)
http://www.symantec.com/business/support/index?page=content&id=TECH186866 (same issue! and they attached a js file so maybe searching it by Ż char code will lead to their solution)

**Comment by julex18** [comment]
@RobinHerbots ,

Did you have a chance to test it?

**Comment by RobinHerbots** [comment]
@julex18, 

Not really.  But I will do it before the end of the week.

**Comment by julex18** [comment]
@RobinHerbots ,

this project had the exact same issue https://github.com/xing/wysihtml5/issues/16 
while this code is a regex mask that works with polish ż: http://www.thimbleopensource.com/download/jquery/jquery.filter_input.js

**Comment by RobinHerbots** [comment]
@julex18 , 

I tested your mask on Chrome and FF under Linux and both work fine.  So it might be related to the OS and/or browser.  On which browser(s)  did you test?

I also verified the above mentioned projects, ... but there solutions seems like skipping the keydown when   if (event.altKey || (!event.ctrlKey && !event.metaKey)) {
           return;                 return;
         }               }
but that might disable default functionality.

**Comment by julex18** [comment]
Yes, I'm using Windows, also in https://github.com/xing/wysihtml5/issues/16 they're talking about windows. Maybe the symantec code I mentioned earlier has a better fix - at least I can't find "metaKey" in their source. I tested on Chrome 39.0.2171.95 m, Firefox 34.0.5, IE 11 all on Windows.

**Comment by RobinHerbots** [comment]
@julex18 , 

Fixed with the latest commit.

A new release will follow soon

**Comment by julex18** [comment]
@RobinHerbots 

Thank you very very much :) 

A hint for other users: the encoding of the file containing mask regex definition is also important, ex $('#fname').inputmask('Regex', { regex: '[a-zA-ZęóąśłżźćńĘÓĄŚŁŻŹĆŃ]{0,50}' }); not all polish characters were allowed until we changed file encoding from ANSI to UTF8.
