### ISSUE TITLE
delete key should trigger 'input' event too since it also change the displayed input value

### ISSUE THREAD

**Issue by dreamershl** [RobinHerbots/Inputmask#765]
in keypressEvent(), after writeBuffer(), it will smartly trigger the "input" event. In the keydownEvent(), after 'delete' key, it also call writeBuffer() to change the display. But this time, it omit the "input" event. 

It is not so  right. Because, the input is also changed for the "delete". Suggest to add the "input" event triggering whenever calling writeBuffer(). One use case for this is Angular. 

Angular will monitor the input change events, such as "input", "change" and adjust its model&view value accordingly. 

Because of the mentioned, the angular can work with the input smoothly. While the delete will encounter the problem. The angular won't be able to update its underlying model & view value automatically.

**Comment by RobinHerbots** [comment]
@dreamershl , 

Can you have a test with the latest commit

**Comment by dreamershl** [comment]
Thanks for the promptly reply. 

Still get issue. The latest version key handling is different from the 3.1.33. Now there are 2 writebuffer. The opts.onKeyDown handler will be in the following lines. 

```
     var keydownResult = opts.onKeyDown.call(this, e, getBuffer(), currentCaretPos.begin, opts);
     handleOnKeyResult(input, keydownResult, currentCaretPos);
```

The handleOnKeyResult() won't pass the flag to trigger the event. 

Personally feel 3.1.33 process is better, because it won't call write buffer 2 times. 

Currently I am implementing the numericInput for the numeric extension. That is why I need re-format the display after receive the user input. for example, when user type 1,2,3,4,5. It will be displayed as 0.001, 0.012,0.123, 1.234, 12.345.

**Comment by RobinHerbots** [comment]
I agree. I will refactor to eliminate the second writebuffer.
It seems that alot of people prefer the "classic" way for inputting numerics. I also plan to reimplement this.

**Comment by dreamershl** [comment]
Another small suggestion. The new initial process simulate the input by triggering the 'input' for each character. it is a little bit slow  (for mobile phone). I prefer to the old way, format the string in one go and set them to the interface. (DOM process is pretty slow since it involves the display.) Thanks.

**Comment by RobinHerbots** [comment]
Android support is still experimental.
