### ISSUE TITLE
NuGet files don't include version number in them

### ISSUE THREAD

**Issue by adam-resdiary** [RobinHerbots/Inputmask#766]
The latest version of the nuget package (3.1.47) doesn't include the version number in the filename. So instead of:

```
jquery.inputmask-3.1.47.js
```

You get

```
jquery.inputmask.js
```

This doesn't match the documentation, which says:

```
bundles.Add(new ScriptBundle("~/bundles/inputmask").Include(
                        "~/Scripts/jquery.inputmask/jquery.inputmask-{version}.js",
                        "~/Scripts/jquery.inputmask/jquery.inputmask.extensions-{version}.js",
                        "~/Scripts/jquery.inputmask/jquery.inputmask.date.extensions-{version}.js",
                        "~/Scripts/jquery.inputmask/jquery.inputmask.numeric.extensions-{version}.js"));
```

And it also caused our bundles to break when updating from version 3.0.23.

So what I'm wondering is:
- When was this changed and why? I had a look at the commits, but couldn't find any obvious info about this.
- Can it be changed back?
- If it can't be changed back, can the documentation in the README be updated, maybe with a note explaining that it was changed in version X, and you need to fix your bundles when upgrading to version Y?

Thanks.

**Comment by RobinHerbots** [comment]
@adam-resdiary , 

The reason was to bring it more inline with other packaging systems like npm and bower.  
I see not much advantage in including the version in the name of the files.  You can always verify the version by nuget or by opening the file.  

I updated the readme

**Comment by adam-resdiary** [comment]
That's fair enough - I think there's a small issue with the build you might wanna fix though. Looks like the version number isn't being set:

![image](https://cloud.githubusercontent.com/assets/4849264/5437868/73c1c70a-846b-11e4-89de-b9d94af0fd1b.png)

**Comment by adam-resdiary** [comment]
Sorry for not mentioning that before - I just assumed it was intentional at first. Stupid of me.

**Comment by RobinHerbots** [comment]
@adam-resdiary , 

You need to use the files in the dist folder.  Or are those coming from the nuget package?

**Comment by RobinHerbots** [comment]
@adam-resdiary , 

You are right.  The version is missing.  I will update the build for nuget

**Comment by adam-resdiary** [comment]
No worries.

**Comment by RobinHerbots** [comment]
@adam-resdiary , 

The is e new nuget package available with version in the files , .. all those systems  ;-)
