### ISSUE TITLE
pasting value into currency mask results in incorrect value

### ISSUE THREAD

**Issue by sjk07** [RobinHerbots/Inputmask#769]
trying to paste a value such as $123.22 into an input results in $1230.22

try it here:
http://jsfiddle.net/sefhsoqd/

**Comment by RobinHerbots** [comment]
@sjk07 , 

I will fix this asap

**Comment by sjk07** [comment]
@RobinHerbots 
Awesome, works like a charm =]
Thanks for the quick fix

**Comment by FilipeZhou** [comment]
Actually, I think that numbers with mask "999.99" have been fixed when pasting into currency mask.
But I tested with numbers like "1000" or "1000.00" and got "100.00". I think that something strange occurs when using autoGroup active to mask.

**Comment by RobinHerbots** [comment]
Also fixed now.
