### ISSUE TITLE
pasting email into email mask incorrect formatting

### ISSUE THREAD

**Issue by sjk07** [RobinHerbots/Inputmask#771]
When trying to paste an email (ex. beer@run.com) the result shows up as beer@run.com__ and invalidates

fiddle: 
http://jsfiddle.net/2dkjbywa/1/

The paste does work as expected if the entrie mask _@_ is highlighted

**Comment by RobinHerbots** [comment]
@sjk07 , 

Fixed in the latest version 3.1.49
