### ISSUE TITLE
input mask shows decimal even if digitsOptional is true, if integerDigits are set

### ISSUE THREAD

**Issue by egucciar** [RobinHerbots/Inputmask#772]
Please look into/resolve this issue with the inputmask if the only difference between the two is that integerDigits are being set. Left - shows decimal point. Right - does not.

http://jsfiddle.net/35Lrkcno/

**Comment by RobinHerbots** [comment]
@egucciar , 

I will have a look.

**Comment by egucciar** [comment]
@RobinHerbots Thank you

**Comment by RobinHerbots** [comment]
@egucciar , 

Just put the greedy option to false.

See http://jsfiddle.net/35Lrkcno/1/

**Comment by egucciar** [comment]
@RobinHerbots thanks, I'll do that. But why would the decimal show for one and not the other even when both are greedy:true?

**Comment by RobinHerbots** [comment]
That is because the second mask is infinite and the greedy option is ignored in that case. In the first mask all integers are allocared, but due that the placeholder is empty it is not visible. When you specify a placeholder it will be more clear what I mean. Best is ro specify the greedy falde.

**Comment by RobinHerbots** [comment]
@egucciar , 

Why don't you use the currency alias?

**Comment by egucciar** [comment]
@RobinHerbots i'll check out the currency alias...I'm just picking up this code after someone else had implemented it...so I'm not sure why it is done this way
