### ISSUE TITLE
If alias used and (showMaskOnFocus: false) mask will show when typing

### ISSUE THREAD

**Issue by sjk07** [RobinHerbots/Inputmask#773]
When setting both `showMaskOnHover: false`, `showMaskOnFocus: false` and using an alias the mask will still show when typing. But, it works correctly if you use the `{mask: "99999"}` property

Fiddle me:
http://jsfiddle.net/1ft2whbz/1/

Edit: 
maybe i was wrong about it working with the mask property?
http://jsfiddle.net/1ft2whbz/3/

**Comment by RobinHerbots** [comment]
@sjk07 , 

If you don't want a visible mask also when you start typing, set the placeholder to "" or use the regex alias

**Comment by calina-c** [comment]
Having the same problem:

This works perfectly:
```$('#cvc').inputmask({'mask': '999', 'placeholder': '', showMaskOnFocus: false, "clearIncomplete": true});```

But when using alias instead of mask, showMaskOnFocus and showMaskOnHover seem to have absolutely no effect. The placeholder and mask still show.
```$('#expirationDate').inputmask({'alias': 'datetime', 'placeholder': '', inputFormat: "mm/yy", showMaskOnFocus: false, "clearIncomplete": true});```
