### ISSUE TITLE
How can I get the decimal currency value without dollar sign?

### ISSUE THREAD

**Issue by burakkilic** [RobinHerbots/Inputmask#774]
Hi;

I have the following code:

http://jsfiddle.net/8Jpdd/241/

When I get the value, I am getting the dollar sign. How can I get rid of the currency sign and only get the decimal value?

**Comment by sjk07** [comment]
All you have to do is add `prefix: ""` to the options.

http://jsfiddle.net/yvfaLb4c/1/
