### ISSUE TITLE
[Numeric] Automatic overwrite after radix point

### ISSUE THREAD

**Issue by dehaaneric** [RobinHerbots/Inputmask#775]
Hi,
I'm wondering if it's possible to automaticly overwrite existing digits that are behind the radix point.

For example, start situation:
€ 1.000.000,|00

When typing, the '00' wil be overwritten:
€ 1.000.000,12|

Now, with the default setup, I need to press delete two times.
$(myselector).inputmask("decimal", { radixPoint: ",", autoGroup: true, groupSeparator: ".", groupSize: 3, digits: 2 });

Many thanks for this great plugin.

**Comment by RobinHerbots** [comment]
@tweek82 , 

You press the insert button to switch to overwrite mode or set the digitsOptional to false.  Best used when the placeholder set to "0"

**Comment by dehaaneric** [comment]
Jeah thanks @RobinHerbots - that worked

**Comment by pavel-mironchik** [comment]
@RobinHerbots is overwrite digits after radix point default behavior now? I mean - without insert button pressed and with digitsOptional == true (default value). I use version 3.3.5-19, but also see this on the demo page, check this video: https://drive.google.com/file/d/0BzAMsjLtoLg-UDJBZGliUllVeTg/view
