### ISSUE TITLE
When two masks specified backspace clears the whole input instead of last char

### ISSUE THREAD

**Issue by ghost** [RobinHerbots/Inputmask#780]
Hello,
when I specify two alternative masks for an input, like this:

``` javascript
$('input').inputmask({
    mask: ['999 99 99 999', 'aa 999 99 99 999']
});
```

and then enter "123 45" into the input and the press backspace the whole input is being cleared instead of just wiping the last digit.

I tried also version with one mask containing optional part, defined like this:

``` javascript
mask: '[aa ]999 99 99 999'
```

but then the inputmask pattern is visible for the whole time despite of having the showMaskOnHover and showMaskOnFocus set to false. I think it might be related with the optional part being declared in the beginning of the mask.

**Comment by RobinHerbots** [comment]
@tomaj-miszczu , 

I will have a look at the first.  For the second you need to add the greedy: false option.

**Comment by ghost** [comment]
Thanks! About the second thing - already did that. Maybe I didn't describe the issue precisely enough. The thing is that the masking template (doesn't matter which one) is visible since the page loads in the input and it shouldn't because it's defined so in the config.

BTW great work with this plugin!

**Comment by RobinHerbots** [comment]
@tomaj-miszczu , 

Thx.

And has the input focus at that moment?  Can you make a jsfiddle to make it more clear what you mean.

**Comment by ghost** [comment]
Nope it's not focused. Of course, here's jsfiddle for that issue: http://jsfiddle.net/sskr5qoa/

**Comment by RobinHerbots** [comment]
@tomaj-miszczu , 

Thx for the fiddle. I will have a look.

**Comment by RobinHerbots** [comment]
http://jsfiddle.net/sskr5qoa/6/
