### ISSUE TITLE
Always show mask

### ISSUE THREAD

**Issue by TiGR** [RobinHerbots/Inputmask#784]
Currently mask appears only onfocus or onhover. I couldn't find nothing about this neither in docs, in code or in issues. Is it possible to make mask be visible constantly?

**Comment by RobinHerbots** [comment]
@TiGR , 

Set the clearMaskOnLostFocus: false option

**Comment by TiGR** [comment]
Thanks, that works as supposed to.

**Comment by akvaliya** [comment]
It disappears on form submit. Any solution to that?

**Comment by KiddoV** [comment]
The ``clearMaskOnLostFocus: false`` will keep mask showed with full opacity. Is there anyway to make the opacity down when not focus, so it will be the same as the normal behavior for the default ``placeholder``?
