### ISSUE TITLE
Zip code with optional mask?

### ISSUE THREAD

**Issue by unicron** [RobinHerbots/Inputmask#787]
@RobinHerbots in the case of zip code mask offered in #290 (99999[-9999]), when the user enters "123456" it displays as "12345-6" which is correct.  

However, if the user hits backspace, "6" disappears but the "-" remains, displaying as "12345-".  The expected result is "12345".

Backspace again and the "-" disappears along with the "5" to display as "1234".  

Is there a way to accomplish the expected result, removing the optional "-" mask on backspace?

**Comment by RobinHerbots** [comment]
@unicron, 

I will have a look at it.

**Comment by RobinHerbots** [comment]
@unicron , 

try with .inputmask("99999[-9999]", { greedy: false });

**Comment by wppunk** [comment]
The US zip code can be `99999` (five digits) or `99999-9999` (five digits + four digits). With the `gready` option, we have a great mask, but the `isComplete` method is still working incorrectly:
- `123` is incomplete
- `12345` - is complete
- `12345`-1 is complete
- `12345-123` is complete
- `12345-1234` is complete
In a nutshell, if you print five or more digits, it's a complete mask.

So, the solution is:
`.inputmask("(99999)|(99999-9999)", { keepstatic: true });`

The `keepstatic` option must show the 1st mask on init and the 2nd mask if a user printed the 6th or more digits.
