### ISSUE TITLE
why not work? $("#searchMax").inputmask( "9{1,4}" );

### ISSUE THREAD

**Issue by FairSite2C** [RobinHerbots/Inputmask#789]
$("#searchMax").inputmask( "9{1,4}" );

I am expecting an input that would accept between 1 and 4 numerals. 

Instead I get:

_{1,4}

has to be sometimes simple I am not understanding. Guidance is appreciated.

**Comment by FairSite2C** [comment]
this works but seems unwieldy compared to what I tried above.

$("#searchMax").inputmask({ "mask": "9", "repeat": 4, "greedy": false });

**Comment by RobinHerbots** [comment]
The first should work. I will have a look on friday. Best regards Robin

**Comment by FairSite2C** [comment]
thanks. I'll keep checking back. This lib is great.

**Comment by RobinHerbots** [comment]
@FairSite2C , 

Adding the greedy: false option should give the desired result.

But that shouldn't be neccesary, as the syntax already specifies the optionality.  
I will fix that.

**Comment by FairSite2C** [comment]
I think I caused you work when it was all my fault. I tend to be lazy and got the src from this link. As far as I know it could be a gazillion years old.

```
<script src="http://cdn.b3website.com/jquery-inputmask/jquery.inputmask.bundle.min.js"></script>"
```

when I downloaded the source off this git page and pointed to the package this particular example worked just fine. 

So the morale of the story is  the latest is usually the greatest.
