### ISSUE TITLE
backspace on one selected digit  removes previous digit as well.

### ISSUE THREAD

**Issue by kenaku** [RobinHerbots/Inputmask#791]
If you select any digit and hit backspace key - it also removes one digit before that.
You can reproduce it everywhere, for example http://jsfiddle.net/sskr5qoa/

**Comment by RobinHerbots** [comment]
@kenaku , 

I will fix that in for the next release.

**Comment by RobinHerbots** [comment]
@kenaku , 

Fixed.

**Comment by kenaku** [comment]
Thanks, Robin!

**Comment by FilipeZhou** [comment]
@RobinHerbots 

I have just have similar problem, but testing with numbers.
For example, if I have "10101" and select the second "1" to delete, I get "101".

**Comment by RobinHerbots** [comment]
@FilipeZhou 
Yes you are right. I will fix it tomorrow.

**Comment by RobinHerbots** [comment]
@FilipeZhou , 

Fixed!
