### ISSUE TITLE
Auto apply mask on set value in Google Chrome

### ISSUE THREAD

**Issue by lmbelo** [RobinHerbots/Inputmask#795]
When I set a value to a masked input, if I don't houver or focus the input field the mask isn't showed.

$("input").inputmask({
            "mask": "99.999.999/9999-99", 
            "numericInput": true, 
            "rightAlignNumerics": false, 
            "autoUnmask" : true,
            "placeholder": "",
                        "showMaskOnHover": true,
                        "showMaskOnFocus": true
        });

$("input").val( "12312312312314" ); //The mask isn't showed while I don't focus or houver the input

and so if i try to get the value it comes blank: $("input").val() == ""

**Comment by RobinHerbots** [comment]
Hi @lmbelo , 

I will have a look at it.

**Comment by RobinHerbots** [comment]
@lmbelo , 

Have a look at http://jsfiddle.net/mdeh9fzt/

**Comment by lmbelo** [comment]
Working fine on your fiddle but keeps trouble on my app with the same approach. Has a way to you look for with Skype? Maybe you could suggest something... Thankyou anyway

**Comment by RobinHerbots** [comment]
@lmbelo , 

Is your project online?  Then I can have a look.

**Comment by lmbelo** [comment]
Unfortunately, because it is a commercial application, I can not provide access for you. It would not be possible to make contact on Skype?

**Comment by RobinHerbots** [comment]
You may contact me during day hours (Belgium)

**Comment by lmbelo** [comment]
I will. Thanks

**Comment by lmbelo** [comment]
Hi. Coul'd we chat on skype now? ***

**Comment by RobinHerbots** [comment]
Yes but only chat, no voice

Op Thu Jan 15 2015 at 13:47:16 schreef lmbelo notifications@github.com:

**Comment by lmbelo** [comment]
alright

**Comment by RobinHerbots** [comment]
I've send a connect request

Op Thu Jan 15 2015 at 13:50:47 schreef lmbelo notifications@github.com:

**Comment by lmbelo** [comment]
******_|| used plugins ||**_****
- bootstrap;
- inputmask;
- jQuery numberformat;
- jQuery UI;
- cldr and globalize;
- datatables.

**\* work around ***
- After apply values, call $("input").trigger('setvalue.inputmask');

**Comment by RobinHerbots** [comment]
@lmbelo , 

jQuery.numberformat is the one causing trouble.  They also patch the valhook but only call the original one when there data attribute isn't found.  Due to this the valhook af other plugins get never called, which is why the value wasn't formatted by the inputmask.

```
 $.valHooks.text.set = function( el, val )
    {
        // Get the element, and its data.
        var $this   = $(el),
            data    = $this.data('numFormat');

        // Does this element have our data field?
        if( !data )
        {

            // Check if the valhook function already exists
            if( $.isFunction( origHookSet ) )
            {
                // There was, so go ahead and call it
                return origHookSet(el,val);
            }
            else
            {
                // No previous function, return undefined to have jQuery
                // take care of retrieving the value
                return undefined;
            }
        }
        else
        {
            var num = $.number( val, data.decimals, data.dec_point, data.thousands_sep );

            // Make sure empties are set with correct signs.
//          if(val.indexOf('-') === 0 && +num === 0)
//          {
//              num = '-'+num;
//          }
            // Otherwise, don't worry about other valhooks, just run ours.
            return el.value = num;
        }
    };
```
