### ISSUE TITLE
Safari(Windows) strange behaviour on delete

### ISSUE THREAD

**Issue by kenaku** [RobinHerbots/Inputmask#797]
When you remove symbols from mask - it doesn't shifts back, but leaves empty space.
This bug can be reproduced only on Windows Safari.

**Comment by RobinHerbots** [comment]
@kenaku , 

Is this on the latest version of Safari on Windows?  Does this also appear on OSX?

**Comment by kenaku** [comment]
@RobinHerbots 
Yes, latest version.
No, Safari on OSX works just fine.

**Comment by RobinHerbots** [comment]
@kenaku , 

I tested the demo page with Safari 5.1.7 on Windows 8 and it seem to work fine.

Can you provide more info.  Mask used?  Maybe a jsfiddle?
