### ISSUE TITLE
Regex with placeholder, not working?

### ISSUE THREAD

**Issue by kamilklosowski** [RobinHerbots/Inputmask#798]
Hi,

Not sure it's bug or feature, but inputmask wont work with placeholder.

Fiddle: http://jsfiddle.net/yocgpp7q/

**Comment by RobinHerbots** [comment]
The regex alias currently doesn't support a placeholder or any visual.

Op Thu Jan 15 2015 at 11:23:11 schreef kamilklosowski <
notifications@github.com>:

**Comment by kamilklosowski** [comment]
Is there any chance to implement this in future releases?

**Comment by RobinHerbots** [comment]
@kamilklosowski , 

Yes that will be implemented in  the future but

Have a look at http://jsfiddle.net/yocgpp7q/1/  
You can also use the second mask

**Comment by kamilklosowski** [comment]
This isn't solution to my problem - i've receive regex from backend unfortunately.
So im looking forward to next releases :)

Thanks

**Comment by monomorph** [comment]
There still is now way to get a placeholder working with the RegEx-extension?

**Comment by RobinHerbots** [comment]
@monomorph , 

Unfortunately no.  Maybe it's time to spend  some time  to the regex-extensions.

**Comment by monomorph** [comment]
@RobinHerbots,

is it you maintaining all the extensions too, or are other people involved?

**Comment by RobinHerbots** [comment]
@monomorph, 

No, it is a one-man show.

**Comment by monomorph** [comment]
So, go ahead. Plz add "Placeholder support" to the RegEx entension... ;-)

**Comment by RobinHerbots** [comment]
@kamilklosowski , @monomorph , 

I added direct regex support to the inputmask core.  Can you have a try and give some feedback.  I only tested with some simple regexes. 

See the jsfiddle for a usage example.  

See updated http://jsfiddle.net/yocgpp7q/16/

**Comment by monomorph** [comment]
Fine, this comes up at the right time. I just got new specs for a project I'm using your inputmasks on. I'll try it out within the next few days and will give feedback.

Thanks for your efforts!

**Comment by hxss** [comment]
So how about show all static symbols in placeholder and let user to write only dinamic content(classes, groups, sets, etc)? For example http://jsfiddle.net/yocgpp7q/25/
And why this regex work only by using data attribute? http://jsfiddle.net/yocgpp7q/26/

**Comment by RobinHerbots** [comment]
@hxss , 

About the second one see http://jsfiddle.net/yocgpp7q/28/  You need to escape twice to pas \ in js.

For the static symbols, it should but the regex isn't correctly interpreted.  I will see why and submit a fix.

Thx for reporting.
