### ISSUE TITLE
Delete key not working properly

### ISSUE THREAD

**Issue by FilipeZhou** [RobinHerbots/Inputmask#799]
Hi!

I used currency input in demo page to observe the problem.
I typed "1,234,567.00" and start to delete using delete key from start. So, from "$ |1,234,567.00" I got "$ 2|34,567.00". Another problem is when I try to delete "$| 1,234,567.00" and I get "$ 1|,234,567.00".
When the cursor is right before the groupSeparator I also cannot delete anything.

**Comment by RobinHerbots** [comment]
@FilipeZhou , 

This is fixed, except for the case with the cursor right before the groupseparator
