### ISSUE TITLE
Regex not working. I'm new to this plugin

### ISSUE THREAD

**Issue by celsomtrindade** [RobinHerbots/Inputmask#801]
So, i'm trying to make a custom mask and i want to allow special characters, like " _ - / () "
But i cant.. This is the jquery code i'm using:

$('.m-tel').inputmask({
    mask:'(**)*********',
        regex:'/^[a-zA-Z0-9-_]+$/'
});
What should i do?

**Comment by RobinHerbots** [comment]
@celsomtrindade , 

If you want to use the regex extension then you cannot use it like above; but like this

``` javascript
$('.m-tel').inputmask("Regex", {
regex:'/^[a-zA-Z0-9-_]+$/'
});
```

Be aware that the regex alias does not show any placeholder.
