### ISSUE TITLE
isComplete for "integer" alias does not validate negative values

### ISSUE THREAD

**Issue by jmanos** [RobinHerbots/Inputmask#804]
The default _isComplete_ event does not validate negative values as true for the _integer_ alias. Both _numeric_ and _decimal_ work fine.

Therefore, toggling the leading minus sign ("-") on an input will trigger the _oncomplete_ event for positive input but not for negative input.

The user could overwrite the _isComplete_ function to solve this on his/her own, but solving the issue out-of-the-box seems more intuitive to me.

**Comment by RobinHerbots** [comment]
@jmanos , 

I will have a look at it

**Comment by RobinHerbots** [comment]
@jmanos , 

Ok fixed!  A new release will follow soon.
