### ISSUE TITLE
Does not work spaces

### ISSUE THREAD

**Issue by senja006** [RobinHerbots/Inputmask#806]
Using a mask 'validator': "[А-Яа-яA-Za-z ]". Do not work spaces in Yandex Browser.

**Comment by RobinHerbots** [comment]
@senja006 , 

Can you provide some more info.  Does it work on other browsers?  

Do you use it on Android? Windows? other?

**Comment by senja006** [comment]
Mac OS, Maverick. At my friends does not work in any browser. They also Mac.

**Comment by RobinHerbots** [comment]
@senja006, 

I will have a test on OSX tomorrow.

**Comment by a13x3y** [comment]
On windows fine work on Yandex Browser and Mozilla. Others not tested.

**Comment by RobinHerbots** [comment]
http://jsfiddle.net/9u3wvpbz/  (convenience for testing)

**Comment by senja006** [comment]
does not work with the first entry on the page. and then everything is fine. it can be seen here house.yarkevich.ru

**Comment by senja006** [comment]
everything works fine. a conflict with another plugin occurred. I'm sorry for what your time is spent

**Comment by RobinHerbots** [comment]
@senja006 , 

Great that it works now!  Which plugin was causing conflicts?

**Comment by senja006** [comment]
yes it's not even a plugin, and the effect of tympanus.com. http://joxi.ru/BA0d0qXFw7g9Ay

**Comment by RobinHerbots** [comment]
;-)
