### ISSUE TITLE
Year input mask?

### ISSUE THREAD

**Issue by ryexley** [RobinHerbots/Inputmask#808]
Having some trouble figuring out how to configure a mask for a field that is _just_ a four-digit year input, with a max year of the current year. Any help would be greatly appreciated.

**Comment by RobinHerbots** [comment]
@ryexley , 

Have a look at http://jsfiddle.net/1uqa45o2/1/

**Comment by prem4git** [comment]
I am trying this in 3.1.63 but doesn't work like expected as my placed holder became yy/y even though i specified it as yyyy. Was this introduced in a particular version?
