### ISSUE TITLE
I use the .inputmask({ alias: "hh:mm t" }); and it will not stop invalid key press

### ISSUE THREAD

**Issue by cfitzh2o** [RobinHerbots/Inputmask#809]
I have a textbox time field, I want it to show something like 03:03 pm.  I apply the alias inputmask({ alias: "hh:mm t" });  and I am allowed to physically enter characters in the number portion and the the mask is ignored, so I can type values that look like asdfsajdfasdfjaslkdj.  Am I doing something wrong?

![masknotworking](https://cloud.githubusercontent.com/assets/7062507/5924325/6cf42c0c-a620-11e4-8393-9bdf3d909abd.png)

**Comment by RobinHerbots** [comment]
@cfitzh2o , 

Which js files did you load?  You need to include the date extensions or use the bundle.

Have a look at http://jsfiddle.net/1uqa45o2/2/

**Comment by cfitzh2o** [comment]
I installed the entire package with the NuGet package manager in a Visual Studio 2012 project so that file is installed.  I am using an include tag for the main library at the top of the page.  Confusing isn't it?
![library](https://cloud.githubusercontent.com/assets/7062507/5938831/4252de36-a6c4-11e4-9356-4a9cedeff5c5.png)
![script](https://cloud.githubusercontent.com/assets/7062507/5938858/6d1ce5a8-a6c4-11e4-9831-b213dacb5afe.png)

**Comment by RobinHerbots** [comment]
@cfitzh2o , 

You alse need to include the date extensions.
