### ISSUE TITLE
onKeyDown is not available in the latest version

### ISSUE THREAD

**Issue by babupca** [RobinHerbots/Inputmask#810]
Hi Robin,

I have been using onKeyDown option in many of my masks. Recently i downloaded and used the 3.1.57. This version does not have the onKeyDown option. I have made date related autocomplete in onKeyDown, now it seems to be not working.

Kindly suggest me, what can be done or the alternative way

**Comment by RobinHerbots** [comment]
@babupca , 

Use   onBeforeWrite: function (e, buffer, caretPos, opts) {  if(e.type == "keydown" .... instead

**Comment by babupca** [comment]
@RobinHerbots ,

I used the method as you said above. 
1. keydown is not working, only keypress is working. 
2. I have put my entire logic within this condition, when TAB key is pressed, this is occuring as  
   undefined. It cannot able to capture the TAB event keyCode.
   if (e.keyCode == jQuery.inputmask.keyCode.TAB) {

**Comment by babupca** [comment]
@RobinHerbots ,
1. Sorry there is no issue with the keydown, it is working.
2. e.keyCode always giving undefined. I just compared with the previous version by debuggin in chrome. When tabbing out in the older version onKeyDown it clearly shows as 
   type = keydown
   which = 9
   and  keycode = 9

But in the new version on tab out the textbox, it is shown as

type = blur
which = 0
and keycode = 0

Thats why it is giving as undefined.

**Comment by RobinHerbots** [comment]
@babupca , 

Can you provide a mask as example so I can work with that.

What about just binding to the keydown event instead of the onbeforewrite callback?

**Comment by babupca** [comment]
@RobinHerbots ,

This is about the date auto complete on tabout. I have written some logic
for day , month , year  and time , which has to be pre filled on tabbed
from the txt field or the jqgrid. I will give example by tomorrow.

Actually I'm using the mask in form and also in jqgrid, so I'm not sure
whether it will work for jqgrid.

I have started to home today. So will give update by tomorrow.

**Comment by babupca** [comment]
@RobinHerbots ,

Please find the below jsfiddle link. 

http://jsfiddle.net/ug16s3tw/48/

I have done the Date, Month, Year and Time (Hour and Minutes) has the autocomplete 

Below are set of ways you can try
1. When you press only ZERO at the caret postion 0 and tab, you will get the current date, month, year autopopulated. 
    Type: 0d-mmm-yyyy  
    Press Tab
    Result : 12-JAN-2015
2. When you press 1 and tab, current month, current year and day 1 along with Zero is autopopulated like this ( 01- JAN-2015)
    Type: 1d-mmm-yyyy  
    Press Tab
    Result : 01-JAN-2015​
   
   ---
   
    Type: 12-mmm-yyyy  
    Press Tab
    Result : 12-JAN-2015​
3.  Month can be auto-populated, when you type first or the second character of the month.
    For example
    Type: 01-Jmm-yyyy
     Press Tab 
     Result : 01-JAN-2015
4. Year can be autopopulated 
    For example
    Type: 01-JAN-yyyy
    Press Tab
    Result: 01-JAN-2015
   
   ---
   
    Again year can also be partially auto-populated
    For example:
    Type: 01-JAN-19yy
    Press Tab
   
   ##  Result: 01-JAN-2019
   
    If you type the three numerics, the current year will be populated
    Type: 01-JAN-191y
    Press Tab
    Result: 01-JAN-2015

**Comment by RobinHerbots** [comment]
@babupca , 

I readded the callback.  http://jsfiddle.net/ug16s3tw/49/

**Comment by babupca** [comment]
@RobinHerbots ,

Thanks a lot Robin.
