### ISSUE TITLE
Cannot initialize the plugin

### ISSUE THREAD

**Issue by tggm** [RobinHerbots/Inputmask#812]
Hello,

I'm always getting this error after including the scripts:

TypeError: $.inputmask is undefined
$.extend($.inputmask.defaults.aliases, ....

I'm using jquery 2.1.1

And initializing the plugin with:

```
$("input[data-inputmask]").inputmask();
```

Example input element:

[input class='form-control' type='text' Id='testweb2_number1_value1598' Name='testweb2_number1_value1598'  data-inputmask="'alias': 'decimal', 'digits': 2, 'radixPoint':','" /]

What am I missing?

Thank you!

**Comment by RobinHerbots** [comment]
you first need to include jquery.inputmask.js then the needed extentions.
Or are you using requirejs?

Op 19:49 VR 30 Jan 2015 schreef tggm notifications@github.com:

**Comment by tggm** [comment]
I'm not using require.js

I've included all the scripts in the correct order and even tried multiple combinations. The documentation is confusing in this aspect. Aditionally, I still don't understand if this works with jquery 2.x.x

**Comment by RobinHerbots** [comment]
@tggm , 

Have a look at http://jsfiddle.net/pdojg6us/

What part is confusing in the doc about the things to include?

**Comment by tggm** [comment]
Well, even using the version on jsfiddle, 3.1.59, I can't get past this error:

TypeError: $.inputmask is undefined
return $.extend($.inputmask.defaults.definitions, {

jquery....mask.js (line 1274, col 11)

Probably some interaction with bootstrap or the theme I'm using.

**Comment by RobinHerbots** [comment]
@tggm , 

Maybe another plugin is using the same namespace?

**Comment by tggm** [comment]
You're right! It was Jasny-Bootstrap!

It now works!
