### ISSUE TITLE
time mask, backspace behavior on android chrome

### ISSUE THREAD

**Issue by sebreunion** [RobinHerbots/Inputmask#817]
Hi,

I'm using this great plugin but i'm facing an issue on mobile browser (android chrome at least).

I'm using $("#time").inputmask( 'h:s' );

After i input a value, say 12:30, i'm unable to completely erase the value.

On desktop, after i pressed backspace 2 times and erased the last 2 digits (30), i'm able to press backspace 2 more times to erase all the input. The 3rd backspace key press erase the "2" digit as it should.
On mobile, the first 2 backspace press behave normally erasing the last 2 digit (30) but after that, it get stucks after the group separator so i unable to erase the first 2 digits. To do such things, i have to manually put the cursor between the 2 and the : (doing this on mobile is anythyng but easy...)

Thanks for any clue to solve this behavior.

Sorry for my bad english.

**Comment by RobinHerbots** [comment]
@sebreunion, 

Don't worry about your english, I understand you just fine!

Android support is still buggy, but the next milestone I will dedicate on mobile support.  The biggest problem is the autosuggest/autocomplete which messing  things up.  I already tried with compositionevents and input event only masking, but it is never good enough.  So any feedback on mobile is more welcome.

**Comment by RobinHerbots** [comment]
@sebreunion , 

Can you retry with the latest version on github

**Comment by sebreunion** [comment]
@RobinHerbots 

Thanks for the update !

A first quick test shows that all is working fine with the last version.

Thx
