### ISSUE TITLE
masking a password field

### ISSUE THREAD

**Issue by haldiggs** [RobinHerbots/Inputmask#821]
I have a requirement that has be changing a field type to 'password' when a user is entering a social security number.

the mask is 

```
regexp = /^\d{3}-\d{2}-\d{4}$/;
message = "match pattern xxx-xx-xxxx";
$("#MultiPurposeId").inputmask("999-99-9999", { placeholder: " " });
```

This may not be possible but when I change the field type to password I lose the mask

```
$('#MultiPurposeId').attr('type', 'password');
```

is there anyway to keep the mask so the password field still has to hit the regex at least?

better yet... maybe what I am looking for is simply to mask the users input but still receive the correct value on submit... this looks like it can do that

**Comment by RobinHerbots** [comment]
@haldiggs , 

Why do you need the type=Password ?

**Comment by haldiggs** [comment]
lol, you're asking me?? Kidding, but not really... the requirements are not mine. The client wants to make sure that a user cannot see the SSN being entered while another user is using the keyboard. Similar to the reason the have a little plastic hood over a banking pin entry area.

**Comment by RobinHerbots** [comment]
@haldiggs , 

;-)

That seems more a validation problem than a masking one.

**Comment by haldiggs** [comment]
yeah on the data entry side I did solve it my simply switching the mask and type but I had this as a display item on another screen after it had been entered. They wanted to be able to show the customers Last4 and X's like XXX-XX1234. 

So like I said above, I was able to create the mask but I guess I was hoping the mask would stay so it would end up with something like _**-__-_**\* when used as a password field. 

No problem. I explained the issue with this to the client and they seemed to understand. I'm just using the password field as usual and hiding the input.

Thanks for getting back to me.

**Comment by licarus** [comment]
Hi,
I ran into a similar issue where I need to mask the input (password type) but only limit it to just numeric (i.e. PIN number). I noticed that as soon as I changed the type to password, the mask wasn't evaluated at all. 
I also noticed that in version 2.4.4, I'm still able to use the Password type and also limit it to just numeric but in version 3.1.48 doesn't work anymore. Is this on purpose?
Maybe you have a better way of doing this? I just want to limit it to numeric but not showing what's being entered.
Thanks

**Comment by haldiggs** [comment]
Take a look at the form validation.io project on github. Using that and its callback feature I was able to validate the input of my password fields

-----Original Message-----

**Comment by licarus** [comment]
Ok. I'll check it out. thanks

**Comment by RobinHerbots** [comment]
Type=password is judt disabled. I never thought about it in the context of plain inputrestriction.  I will have some tedts tomorrow and reenable it.

**Comment by licarus** [comment]
Oh awesome. when you have republished the latest code, could you post it here so I can grab them? thanks.

**Comment by RobinHerbots** [comment]
@licarus , 

Committed the changes to github, but not yet released.
