### ISSUE TITLE
Uncaught TypeError: Cannot set property 'buffer' of undefined

### ISSUE THREAD

**Issue by seanford** [RobinHerbots/Inputmask#822]
Example:

var temp = '8345006561444';
var formattedTemp = $.inputmask.format(temp, { alias: "*_**-__-_**-****"});
alert(temp);
alert(formattedTemp);

Line 2 will throw the error:
Uncaught TypeError: Cannot set property 'buffer' of undefined

**Comment by RobinHerbots** [comment]
@seanford , 

Try by replacing the alias with mask, ... as the pattern is not an alias I guess.

$.inputmask.format(temp, { mask: "_**---_*"});
