### ISSUE TITLE
Add a change log

### ISSUE THREAD

**Issue by achwedyk** [RobinHerbots/Inputmask#823]
We're using your library and we wanted to upgrade to the newest version. However there is no change log and it's hard to say what was changed and if there are any breaking changes.
I suggest adding a change log. See http://keepachangelog.com/
Thanks

**Comment by RobinHerbots** [comment]
@achwedyk,

After reading on keepachangelog I cannot say, read the commit log  ;-)

I can give it a try.

**Comment by achwedyk** [comment]
Thanks!
