### ISSUE TITLE
Issue in Android  (Samsung GALAXY S5)

### ISSUE THREAD

**Issue by kimzhu1980** [RobinHerbots/Inputmask#825]
In the system default browser, when I press the "<X" delete button, the pointer will go to the beginning of the text box, and automatically put "1" in the textbox. Event though I update to latest version, I still got the same issue.

My tag:

$("#test").inputmask("99/99/9999")

**Comment by RobinHerbots** [comment]
@kimzhu1980 , 

Can you retry with the latest version
