### ISSUE TITLE
ios 8, safari, on first visit unable to enter any characters

### ISSUE THREAD

**Issue by chrishoadley** [RobinHerbots/Inputmask#826]
This seems to be happening on ios 8 safari only. When you first visit the site and attempt to enter the birth date and phone number you are unable to enter any characters at all. Once you refresh you are able to from then on out. If you clear your cache you will still be able to fill in the form. It is only on the first visit. Very strange.

Any help would be appreciated.

The site in question.
http://big8subs.firehousesubs.com/Home/Sweepstakes

**Comment by RobinHerbots** [comment]
@chrishoadley , 

I see you are using version 2.5.  Can you retry with the current version first.

**Comment by chrishoadley** [comment]
Thank you for the reply Robin, i'm going to give it a try. We were weary of upgrading as last time we upgraded (not sure of version) we were having Android issues, input going in backwards. I'll let you know how it goes.

**Comment by sngreg** [comment]
I am seeing the same issue with iOS simulator and iOS 8.4, The initial focus of the text fields doesn't load the mask but pulls up the mobile keyboard, when I move focus to another field it shows mask and then I can type in the field.

**Comment by RobinHerbots** [comment]
@sngreg, 

Thx for the feedback.

@gersteba, 

Can you verify that the focus event is triggered initially?

**Comment by gersteba** [comment]
@RobinHerbots ,

Here is a new fiddle logging the focus events:
https://jsfiddle.net/gersteba/tzLa2oy9/27/

**Comment by sngreg** [comment]
@RobinHerbots / @gersteba   - Here is a quick example of what I am seeing. This is being run xcode iOS simulator. iPhone 6 / iOS 8.4 As you can see on initial focus, the input is taking focus and the keyboard does pop up (not shown in the gif but it does show up) but the automask doesn't show and I cannot type in the input until I lose focus and then re focus.

![bepdmmxi3z](https://cloud.githubusercontent.com/assets/6288003/18669213/e1989324-7f07-11e6-8cd0-fe57ee0e36c8.gif)

My mask json looks like this and everything functions the way we want on desktop and iOS 10, it just seems like iOS8 / 9 having a couple weird focusing issues on initial focus.

```
 currency: {
      alias: 'currency',
      rightAlign: false,
      numericInput: true,
      autoUnmask: true,
      max: 1000000,
      showMaskOnFocus: true,
      showMaskOnHover: false,
      clearMaskOnLostFocus: true,
      onUnMask: function (maskedValue, unmaskedValue) {
        return parseInt(unmaskedValue.replace(/,/g, ''), 10);
      }
    },
    percentage: {
      alias: 'percentage',
      rightAlign: false,
      numericInput: true,
      digitsOptional: false,
      autoUnmask: true,
      showMaskOnFocus: true,
      showMaskOnHover: false,
      max: 30,
      onUnMask: function (maskedValue, unmaskedValue) {
        return parseInt(unmaskedValue, 10);
      }
    },
```

**Comment by RobinHerbots** [comment]
@sngreg , 

Can you make a jsfiddle for it.

**Comment by RobinHerbots** [comment]
@sngreg , 

Can you have a retry with the latest version on github.

**Comment by sngreg** [comment]
Thanks @RobinHerbots  I will try this out today. Sorry I didn't get around to making a fiddlers. I will keep this post updated when I try

**Comment by sngreg** [comment]
@RobinHerbots It looks like this was fixed on Safari and iOS safari. Thanks for the quick response and update!

**Comment by RobinHerbots** [comment]
@sngreg , 

Thx for testing this.
