### ISSUE TITLE
The problem with Russian phone codes

### ISSUE THREAD

**Issue by telray** [RobinHerbots/Inputmask#827]
If I'm being used by Russian codes, and a lot of them, the plug begins to slow down very much.
And they can not be used
The old version https://github.com/andr-04/inputmask-multi works correctly.

Example - http://jsfiddle.net/telray/jLLjm6j1/1/

**Comment by RobinHerbots** [comment]
@telray , 

There are still problems in the alternations.  I will have a look at it soon.

**Comment by RobinHerbots** [comment]
http://dialcode.org/Europe/Russia/

**Comment by RobinHerbots** [comment]
@telray , 

I imported the russian phone codes from inputmask-multi, it is a huge list.  Is this kind of detail needed?

**Comment by telray** [comment]
@RobinHerbots , yes. I need this huge list.

**Comment by ghost** [comment]
Yes, the browser is extremely slow.

**Comment by Soul-git** [comment]
Problem still exists. When choosing a mask for Russia - a very long time of execution of the script. At values ​​more masks 400-500 problems .
Sorry , I write through the auto translator .

**Comment by ghost** [comment]
Я так понял, что это будет не скоро
`modified the milestone: 3.5`

**Comment by RobinHerbots** [comment]
Remove Phone alias #1981
