### ISSUE TITLE
Numeric extension doesn't seem to support min/max values

### ISSUE THREAD

**Issue by matthew-dean** [RobinHerbots/Inputmask#830]
I've tried a number or ways to set up an integer mask with min/max values, but I'm not getting anywhere.

I've done:

```
<input type="text" data-inputmask="'alias': 'integer', 'min': '0', 'max': '255'" />
```

I've also tried:

```
$input.inputmask('integer', { min: 0, max: 255 });
```

It limits the field to integers, but it doesn't seem to limit the integer range. Does something need to be added for this to work?

**Comment by RobinHerbots** [comment]
@matthew-dean , 

I will fix this for integer.
