### ISSUE TITLE
Mask cache - 2 definitions for same mask

### ISSUE THREAD

**Issue by StonesEditeurs** [RobinHerbots/Inputmask#831]
Hi,

We have a trouble using jquery.inputmask when 2 elements have the same mask, but with each one its definition.

This is the code used to apply the masks :

```
        $("#Element_1").inputmask({
            mask: "Z{1,*}",
            definitions: {
                'Z': {
                    validator: function (chrs, buffer, pos, strict, opts) {
                        return { pos: pos, c: 'A' };
                    },
                }
            }
        });

        $("#Element_2").inputmask({
            mask: "Z{1,*}", // <= Same mask
            definitions: {
                'Z': {
                    validator: function (chrs, buffer, pos, strict, opts) {
                        return { pos: pos, c: 'B' };  // <= another definition
                    },
                }
            }
        });
```

Looks like there is a cache for masks, because in this example the first mask+definition is applied to both elements.

We were expecting mask/definition to be indpendant for each plugin instance.
Otherwise, the developper need to be sure that each mask/definition is using a unique letter (in the same web page) : not very usefull in our scenario.

Do you know a workaround for this issue ?

Thanks for your help.

Alain.

**Comment by RobinHerbots** [comment]
@StonesEditeurs , 

Normally you should define your definitions in advance and then use them on the view/page.  The maskcache is to speed up things a bit.

But the caching doesn't take the definition into account.  I will make a fix for this.

**Comment by StonesEditeurs** [comment]
Hi Robin,
Thanks for your quick answer.
I will wait for the fix.
Regards.
