### ISSUE TITLE
How i fix that number problem?

### ISSUE THREAD

**Issue by bilalyilmax** [RobinHerbots/Inputmask#835]
http://jsfiddle.net/70ou3fjp/1/

```
$("input").inputmask({alias:'numeric', groupSeparator: '.', radixPoint: ",", autoGroup: true, digits: 2, digitsOptional: false, placeholder: '0,00', suffix: " TL" });
```

if i use that options, it doesn't work right.
if you enter tree number, u should see last zero return comma.. 
like; **123,0, TL** but it must **123,00 TL**
How i fix that problem?

**Comment by RobinHerbots** [comment]
@bilalyilmax , 

I will have a look.

**Comment by RobinHerbots** [comment]
It was due to the placeholder 0,00 you were using.  In the numeric alias you only specify the placeholder for the numbers.  Anyway, the extension now detects this and changes it automatically.
