### ISSUE TITLE
Numeric max filter

### ISSUE THREAD

**Issue by ghost** [RobinHerbots/Inputmask#837]
Hello,

When applying a max filter to a numeric input if a value is entered above the max the input seems to lose focus and the user can not delete digits until the mouse re-enters the input box.

Example here: http://jsfiddle.net/oj1q43h4/ 

Try entering a value above 5000 e.g. 6000, it will correctly cut off at 600 but you can not delete characters.

Test on Mac OS X Chrome, Firefox and Windows IE11

**Comment by RobinHerbots** [comment]
@beardfu , 

Fixed in the latest version
