### ISSUE TITLE
auto Selection of the text field is not happening in the latest version 3.1.59

### ISSUE THREAD

**Issue by babupca** [RobinHerbots/Inputmask#838]
Hi Robin,

I think the auto selection is removed in the latest version wihich is 3.1.59

When i was using the 3.1.26 version, on Tab from one text field to another text field, the auto selection of the text field is not happening.

I think i have raised a bug #733 (Tab issue), which was another issue, only in the firefox. It was fixed, but now in none of the text field on tab out, auto selection is not happening.

Could you please help me out on this issue.

**Comment by babupca** [comment]
Please tab from the Name Field to the weight field in the jqgrid. Weight field is not selected in the latest version and in the older version weight field is selected.

Version 3.1.62-7
jsfiddle - inputmask latest version 3.1.59 and above
auto selection not happening on tab out one jqgrid field to another field

## http://jsfiddle.net/BA251281/CzVVK/1425/ 

Version 3.1.26
jsfiddle - inputmask older version 3.1.26
auto selection happening on tab out one jqgrid field to another field

http://jsfiddle.net/BA251281/d1xncg3s/1/

**Comment by babupca** [comment]
@RobinHerbots ,

Could you please suggest me temporary option to fix this issue for current time, until this issue fixed.

**Comment by RobinHerbots** [comment]
@babupca , 

Just for a test I added some extra inputs outside the jqGrid

http://jsfiddle.net/d1xncg3s/2/

Anyway I will have a look.

**Comment by RobinHerbots** [comment]
@babupca , 

I see the difference, but it is actually jqgrid which should fix this.  Removing the inputmask, also does not select the input on tab.  

First try to convince them to make there tabbing behave like it should.

**Comment by babupca** [comment]
@RobinHerbots ,

You are right Robin. I have searched the trirand blog, and found that, they does not implemeted this functionality. 

--> http://www.trirand.com/blog/?page_id=393/feature-request/select-element-text-in-cell-edit-mode

They have suggested some functionality, but i did not used those option, instead i used the dataInit event in jqgrid, within that i have added this small piece of code. It worked fine.

--> type:"focus",fn:function(e) { jQuery(this).select();}
