### ISSUE TITLE
No message with HTML5 validation

### ISSUE THREAD

**Issue by carlosvini** [RobinHerbots/Inputmask#841]
Normally there is a message when you don't fill required fields like this:

```
<input required="true"  type="text" name="cep">
```

But when i mask it, the message is not shown, i suppose it has to do with the field being focused.

Is there something i can do to fix this?

**Comment by RobinHerbots** [comment]
@jp7carlos , 

I guess this can be solved by using the html pattern attribute.  I will try to build that in so that the required is autotranslated to the pattern attribute.

**Comment by carlosvini** [comment]
It seems to be a good idea, as long as it doesn't change fields that already have a pattern attribute.
I guess it will only work for simple patterns, since translating multiple patterns or functions wouldn't be possible.

**Comment by ownede** [comment]
Annoying issue, worth fixing.

**Comment by trodicaro** [comment]
Is this still an active issue? We are using this library in a project and this issue has come up. Would be helpful to have a solve, or at least a comment on here as to how to fix.

**Comment by trodicaro** [comment]
I'm using this snippet on my form as a hack:
```
        document.querySelector('form button[type="submit"').onclick = function() {
            document.querySelector('form').reportValidity();
        }
```

**Comment by RobinHerbots** [comment]
@trodicaro, 

I fixed the issue in the 5.x branch.
Can you have a try with the version from github.

**Comment by trodicaro** [comment]
Thank you for being so responsive! That would be amazing if fixed! I tried updating to 5.x and am having issues with the date fields: they would show the placeholder "mm/dd/yyyy" but won't allow entering of  data. I required the library and applied the mask likeso: 

`<script src="{% static "vendor/inputmaks.min.js" %}"></script>
<script>
    $(document).ready(function () {
        Inputmask("mm/dd/yyyy").mask(document.querySelectorAll("input[name*='date']"));
    });
</script>`
![Screenshot from 2019-05-28 11-21-40](https://user-images.githubusercontent.com/4808140/58494630-2a0c1800-813b-11e9-8be7-fe3b893a519b.png)

**Comment by trodicaro** [comment]
And actually, I can see that on no data submitted, I get the desired error message, but alas, I cannot enter data ...

**Comment by RobinHerbots** [comment]
@trodicaro , 

The date masks are replaced by the datetime alias. 
```
Inputmask("datetime", { inputFormat: "mm/dd/yyyy"}).mask(input);
```
The 5.x branch is still beta.  The masking is better then al the previous versions, but the datetime and numeric alias are a rewrite from scratch and it will take some more time to stabilize.
So if you switch for production be sure to test the masks used. 

I hope I can release 5.0 soon.

**Comment by trodicaro** [comment]
Ah, I read a similar comment you made on this datetime alias, but didn't get the implications of it.

For version, I also tried 4.x, but I think I was making the same mistake about the datetime (was the alias introduced in 4.x?). Nevertheless, I will try it.

**Comment by leomoty** [comment]
I've had the same issue, so I just got the latest beta (245), and still doesn't seem to work for me.

When the field becomes focused the mask is autoapplied and no validation message is ever shown.

If I apply a `setCustomValidity` message and then clear it on blur/keypress, the native required message shows afterwards, which is also not the desired effect.

**Comment by RobinHerbots** [comment]
@leomoty, 

The fixed was reverted.  It has todo with the focus.  Once a value is set it will remove the validation error.

**Comment by leomoty** [comment]
Hey @RobinHerbots, thanks for your input, what is weird for me is:

1. Submit form
2. Field is empty, thus `setCustomValidity` is called
3. `form.reportValidity` is called and the message is shown
4. Press tab 
5. Blur is called, I am cleaning my `setCustomValidity` message here
6. native required validity message is shown

I didn't expect (6) to happen this way, keep in mind my input has `required=required`. If no custom validity message exists, then no message is shown, as expected.

**Comment by RobinHerbots** [comment]
@leomoty ,

I pushed a new fix.  Can you have a try.  I hope this one doesn't interfere.

**Comment by leomoty** [comment]
@RobinHerbots, not really I am not able to reproduce my problem faithfully in jsfiddle. Albeit I didn't add any event handlers. For now I have disabled `required` and will depend on my custom validity. It is validated on the backend anyways.

Thanks!

**Comment by RobinHerbots** [comment]
Here a small demo.   Just click the submit button.

https://jsfiddle.net/7jcz9gyn/
