### ISSUE TITLE
Form reset doesn't get same value as initial mask

### ISSUE THREAD

**Issue by bdmay96** [RobinHerbots/Inputmask#842]
Hi

I ran into a problem when doing a form reset on an input using the "integer" mask, where the initial input value had decimals.  What would happen is I set the input to some value (12.34), and when I use the integer mask, it strips off the decimals (12), and that's working fine.  

But when you trigger the reset, I think that it takes the original value and enters every character with the keypress event.  This doesn't work, because the mask only blocks the radix from being entered, and doesn't strip the decimals (1234).

Here's a fiddle with a simple example.
http://jsfiddle.net/tctosr91/

I'm still trying to figure out what's going on exactly, but I think the problem is that the onBeforeMask event isn't called when the value is set through the reset event.

Thanks.

**Comment by RobinHerbots** [comment]
@bdmay96 , 

Fixed ;-)
