### ISSUE TITLE
0 is inserted ahead of number to meet the mask

### ISSUE THREAD

**Issue by ttback** [RobinHerbots/Inputmask#844]
So on Android(not seeing this on Desktop or iOS), when I have a mask set up for Date, mm/dd/yyyy, when I input 03/1, the input element becomes 03/01 without me typing the 0. Do you know what might trigger this behavior?

**Comment by RobinHerbots** [comment]
@ttback , 

See #465

**Comment by ttback** [comment]
@RobinHerbots  Thanks, will try the latest inputmask out now

**Comment by ttback** [comment]
@RobinHerbots Great, it is working for me on Android 4.2 now.
By the way, a side question, what does the nojumps flag do? I thought it was related to the jumpy behavior. But I haven't figured out what it does so far.

**Comment by RobinHerbots** [comment]
@ttback , 

You can find it in the readme also, but it is used to change the caret behavior on 'static' positions in the mask.

say mask 99-999999  with nojumps set to true the caret will not jump over the - automatically but stay before.  This can be usefull with multiple masks.
