### ISSUE TITLE
Phone mask slows any browser on any computer

### ISSUE THREAD

**Issue by hiddenman** [RobinHerbots/Inputmask#846]
Hi,

Thank you for you good extension. However, when i define a simple mask like:

  $("#phone").inputmask({
       alias: "phone",
       url: "js/phone-codes/phone-codes.js",
       countrycode: "7",
       nojumpsThreshold: 4
  });

And then try to enter data, it validates/formats my data correctly. However, when i reach the end of the string and just try to type any new symbols/digits (while i'm not allowed to enter anymore due the maximum length of the Russian phone),  my browser becomes frozen and  eats all CPU of my modern superfast computer. After few seconds it unfreezes.  I'm afraid it would be a pain on older computers.

Please, take a look.

Thank you.

**Comment by RobinHerbots** [comment]
@hiddenman , 

I know and i'm looking into it.

**Comment by hiddenman** [comment]
I can help you with testing/debugging, if you want.

**Comment by RobinHerbots** [comment]
Thx. I  reply back on monday.

**Comment by RobinHerbots** [comment]
@hiddenman , 

The slow down is caused by the getTests function.  For example for the russion phonecodes there are +- 2400 alternations per call to getTests and that function is also called multiple times.  So to speed things up I need to enable caching on this.  The caching mechanism is already in place but It needs more investigation in which cases the cache needs to be cleared.

What could help is a unittest which test every variation in the russion phone codes + finding cases where caching makes the mask fail.  
In the code you will find 

``` javascript
if (false && cacheable !== false && getMaskSet()['tests'][pos]) {
```

Just remove the false && cacheable!== false check to enable the cache usage

**Comment by hiddenman** [comment]
@RobinHerbots Hi,

Thank you, will try.  One more question: is it possible to disable phonecodes tests if we do not need them?   All we want is to check whether the typed number starts from the correct country code and has correct length (according to the country code).  
That would be enough in the most cases.

Btw, one more question which is more important (imho) that correct phonecode - local phone format.  In many countries customers are get used to type their phones in a local format which often starts with digit 8.  Most of the customers  enen doesn't now their country code and type phones like  8 499 272 50 60, while it must be +7 499 272 50 60.

Is it possible to allow users to type in both formats somehow?  Google's libphonenumber understands that, jquery masked-input-plugin  allows that (just by writing regexp like  7|8  XXX XX XX), so it would be nice to have that in your plugin.

**Comment by RobinHerbots** [comment]
$(selector).inputmask("7|8 999 99 99");

**Comment by hiddenman** [comment]
@RobinHerbots Thanks. Actually, that doesn't work as expected.  

Here is how it looks like:

http://ibin.co/1vokZGTfPnJJ

Here is what i can type here:

http://ibin.co/1vokW8u0OZcO
while it must be like 7 499 272 50 60.

And i can't delete 7 and put 8 on its place.

I defined it as you said: $("#phone").inputmask("7|8 999 99 99");

**Comment by hiddenman** [comment]
@RobinHerbots Oops, sorry, i should have defined it as $("#phone").inputmask("7|8 999 999 99 99"); 
So i've just changed it and yes, it works.  Two glitches:
1. I can't delete the digit 7 by using keyboard.  Backspace just doesn't work.  I have to select by mouse this 7 and then press 8
2. Selecting by mouse hardly works, it always clears the selection and so on, so it will be a pain for a user.

**Comment by RobinHerbots** [comment]
@hiddenman , 

Have a look at http://jsfiddle.net/v42kbLnu/1/

**Comment by hiddenman** [comment]
@RobinHerbots Thanks, that makes sense. Second example is better. Because users will try to delete the 7 and will be upset because they can't :-)

**Comment by hiddenman** [comment]
@RobinHerbots Btw, one problem with your example where you say "Don't think just type 8 over the 7" - it's not possible to put cursor at the beginning of the input field by mouse. Just try, it will move it to the next digit, so it's only possible to press then the right arrow few times. But users prefer mouse and will be angry about that, imho.

**Comment by RobinHerbots** [comment]
@hiddenman , 

The cursor is positioned before the 7 when clicked, unless you already typed the 7.
Anyway, I'm further optimizing the behavior for the first to get the behavior of the second.

**Comment by RobinHerbots** [comment]
@hiddenman , 

Have a look again at the fiddle.  This issue may be closed
