### ISSUE TITLE
Email with dot - paste not working

### ISSUE THREAD

**Issue by ghost** [RobinHerbots/Inputmask#847]
Hello,

I´ve using the inputmask on my website for a while, but now I had to add various emails to my forms, and it was easier to copy and paste them from a table I received, but when I paste them, all emails lose the dots, like in the following example:

email: test.test@test.com
result: testtest@testcom

That happens even on the demo page (my script is copied from the documentation btw).

Sorry if it´s a known issue, didn´t find anything about this in my search.

**Comment by RobinHerbots** [comment]
Fixed in the latest version
