### ISSUE TITLE
onUnMask for Numeric values

### ISSUE THREAD

**Issue by bippesbrandao** [RobinHerbots/Inputmask#848]
Hi,
thanks for this great extension!

I'm working with numbers in the german format which is "1.000,00". I'm getting an unexpected result for the unmasked value:
e.g.
<input id="testinput" name="whatever" type"text" value="1000.33" data-inputmask="'autoUnmask': true, 'alias': 'numeric', 'groupSeparator': '.', 'radixPoint': ',','autoGroup': true, 'digits': 2">

Masked value = "1.000,33" as expected.

CONSOLE:
jQuery('#testinput').inputmask('unmaskedvalue')

Actual result:
"1000,33"

Expected result:
"1000.33"

What is happening is, that the changed radixPoint is not taken into account when unmasking the value. Most likely you want to have floats in the backend when working with numeric input types.

A possible fix could look like this:
$.inputmask.defaults.aliases.numeric.onUnMask = function(maskedValue, unmaskedValue, opts) {
    var processValue = maskedValue.replace(opts.prefix, "");
    processValue = processValue.replace(opts.suffix, ""), processValue = processValue.replace(new RegExp($.inputmask.escapeRegex.call(this, opts.groupSeparator), "g"), "");
    if (opts.radixPoint !== '.' ) {
        processValue = processValue.replace(opts.radixPoint,".");
    }
    return processValue;
}

best regards
Arne

**Comment by bippesbrandao** [comment]
Sorry, input field has been filtered:
data-inputmask='autoUnmask': true, 'alias': 'numeric', 'groupSeparator': '.', 'radixPoint': ',', 'autoGroup': true, 'digits': 2

value=1000.33

**Comment by RobinHerbots** [comment]
@bippesbrandao , 

This is done because some backends (like ASP.NET/MVC) expects the value to be submitted into the users culture.  Otherwise the default binder on the can't resolve the value as a proper decimal.  Anyway you can modify the behavior in the onunmask callback.

Maybe a should add an extra option to allow retieval of the value as a number.

**Comment by bippesbrandao** [comment]
Ah ok, I wasn't aware of that, but anyway an additional option would be the best as it wouldn't break backwards compatibility.

**Comment by RobinHerbots** [comment]
@bippesbrandao , 

I added unmaskAsNumber option in the numeric alias

**Comment by niklasravnsborg** [comment]
Hey there! I'm having the exact same issue. I have to use the german format (`1.000,00` instead of `1,000.00`).

``` html
<input data-inputmask="'alias': 'numeric', 'groupSeparator': ',', 'autoGroup': true, 'digits': 2, 'digitsOptional': false, 'placeholder': '0', 'unmaskAsNumber': true">
```

This doesn't work. :cry: I'm still getting the international format. How did you solve it, @bippesbrandao?

**EDIT:** Solved it! 

``` html
<input data-inputmask="'autoUnmask': true, 'alias': 'numeric', 'groupSeparator': '.', 'radixPoint': ',', 'autoGroup': true, 'digits': 2, 'unmaskAsNumber': true">
```

**Comment by broject** [comment]
`<input type="text" data-mask="" data-inputmask="'alias': 'yyyy-mm-dd'">`
is working....

you wrote:
`<input data-inputmask="'autoUnmask': true, 'alias': 'numeric', 'groupSeparator': '.', 'radixPoint': ',', 'autoGroup': true, 'digits': 2, 'unmaskAsNumber': true">`
is not working......

i from mongolia, how to use as 1,000.25 ??
@RobinHerbots said " EDIT: Solved it! " but not solve it!!!!!!!

**Comment by RobinHerbots** [comment]
@broject ,

I didn't say that, ... @niklasravnsborg  said that!!  ;-)

Ok @broject , what is the problem and how can I help you?  Preferable create a new issue accompanied with a jsfiddle to illustrate the problem.
