### ISSUE TITLE
'change' event is not firing when used in datemasks with onkeyDown events.

### ISSUE THREAD

**Issue by babupca** [RobinHerbots/Inputmask#849]
We use the date mask for From and To fields for the entire application.

Here for the date mask's, i have written a autopopulate for the date, month, year and also time, this autocomplete method is called inside the onkeydown method from the framework side in mask, which is common for all the date related masks.

We have a scenario, where on 'chage' event of the From date, we have to set the To date also as From Date. But this seems to be not working, when we have used the onKeyDown in the mask.

http://jsfiddle.net/BA251281/ug16s3tw/67/ 

$("#item1").on("change",function(e){  
        var item1Val = $(this).val();
        $("#item2").val(item1Val);  
 }); --> Not working

$("#item1").on("blur",function(e){
      console.log("Test");
      var item1Val = $(this).val();
      $("#item2").val(item1Val);  
 });
But on blur it is working fine, eventhough, we have used the onKeyDown in the mask.

**Comment by RobinHerbots** [comment]
@babupca , 

Probably because the autocomplete functiuonality sets the value with jQuery.val and the mask does not see that as a change anymore when loosing focus.  
I will see what I can do about it.

A quick fix would be to just trigger trhe change event in the autocomplete.

**Comment by RobinHerbots** [comment]
@babupca , 

This seems fixed.  Can you have a try to confirm.

**Comment by babupca** [comment]
Thanks Robin, it works fine now
