### ISSUE TITLE
(URGENT) MaskEdit not working on IE

### ISSUE THREAD

**Issue by Jaspal** [RobinHerbots/Inputmask#85]
i am getting error on input._valueGet() object doesn't support property or method on IE.

It's urgent can you please take a look and help me to fix this issue

**Comment by RobinHerbots** [comment]
Hi Jaspal,

Which version of IE?

I will have a quick look this evening.

best regards,

Robin

2012/7/17 Jaspal <
reply@reply.github.com

**Comment by Jaspal** [comment]
IE8

**Comment by Jaspal** [comment]
we have a release today and we found the maskedit not working on IE.can you please help me to fix ASAP

**Comment by RobinHerbots** [comment]
Do you have the problem also on ie9 in ie8 mode?

I tested with the latest version and have no problem.

Can you create an example on jsfiddle

best regards,

Robin

2012/7/17 Jaspal <
reply@reply.github.com

**Comment by Jaspal** [comment]
function SetMasked() {
        //alert('in');
        jQuery('.zipmasked').focus(function() {
            if (jQuery(this).attr("readonly")) {
                jQuery(this).inputmask('remove');
            }
            else {
                jQuery(this).inputmask('ZipMasked');
            }
        }).blur(function() {
            jQuery(this).inputmask('remove');
        });

Getting error In Inputmask.js .bin("onblur") event

**Comment by Jaspal** [comment]
or if i remove .onblur from my implementation then it's working fine but my requirement is onblur we need to display unmasked value in control

**Comment by RobinHerbots** [comment]
Hi Jaspal, 

Can you retest with the latest fix.

Robin
