### ISSUE TITLE
Calling val() on masked input causes Javascript to crash

### ISSUE THREAD

**Issue by darkphoenixff4** [RobinHerbots/Inputmask#850]
Yeah, title says it all.  For some reason, when I call val on a masked input, either to get the value or to set it, the Javascript stops processing at that point.  This only happens on masked inputs, so...

**Comment by RobinHerbots** [comment]
@darkphoenixff4 , 

I tested locally and see no problem.  Can you provide some more information.  The mask used.  The version? Which browsers?  Maybe an example.

**Comment by darkphoenixff4** [comment]
I'm using version 3.1.61 on Firefox 36.0.1 on openSUSE.  The mask is A9A 9A9 (Canadian postal code pattern).  Oddly, it works fine in Firefox for Windows, so it seems to be a problem specific to Firefox for Linux.

**Comment by RobinHerbots** [comment]
@darkphoenixff4 , 

Can you try the jsfiddle http://jsfiddle.net/b2qr2hjz/1/

I tested on Firefox36.0.1 on Ubuntu/Gnome3

**Comment by darkphoenixff4** [comment]
Yeah, it works fine on mine.  It's odd.  I'm starting to wonder if I have a library conflict of some kind in my code.  Unfortunately, I can't just upload the page I'm working on, as it's not supposed to be publicly available until some time next week, or I'd just do that.

Edit: Okay, I tried turning off everything Javascript related except jQuery and InputMask, I turned off all of my Firefox plugins except Firebug, and I tried pulling the code from Github directly.  Same result.

**Comment by RobinHerbots** [comment]
@darkphoenixff4 , 

Do you get any error in the console?

Is there a way to share the page?

**Comment by darkphoenixff4** [comment]
No errors in the console, and not right now, unfortunately.  Not until next week, at any rate.  I'll toss a link in here once it goes live, though.

**Comment by darkphoenixff4** [comment]
This one's actually starting to confuse me.  I finally launched the page at https://consultant.everydaystyle.ca/G2/scripts/Servlet/index.php?servlet=EConsultant&language=EN , but for some reason, now it's working... sometimes.  I can't seem to find any logical pattern to it; just sometimes with Firefox on Linux it works, and some times it doesn't.  Anyway, the best way to test is to fill out Mailing Address and then try Shipping Address' "Same as Mailing" option, which uses val() to copy the values from Mailing to Shipping.  Thanks.
