### ISSUE TITLE
NuGet Version Mismatch

### ISSUE THREAD

**Issue by jimithing277** [RobinHerbots/Inputmask#852]
Current NuGet Gallery version is pulling down 3.1.57.  Running in to an issue that appears to be addressed in your latest distribution from GitHub.  Any reason why NuGet is using an out-dated version?

Shouldn't it pull down whatever is available on GitHub?

Thanks!

**Comment by RobinHerbots** [comment]
@jimithing277 , 

It should have been on 3.1.61.  I will have a look.

**Comment by jimithing277** [comment]
Thanks @RobinHerbots!

Did you mean 3.1.62-45? I noticed that's the version showing in the GitHub dist folder.

**Comment by RobinHerbots** [comment]
@jimithing277 , 

Version 3.1.62 is unreleased
