### ISSUE TITLE
IE8 doesn't support window.getSelection js error

### ISSUE THREAD

**Issue by coolblades** [RobinHerbots/Inputmask#853]
Problem:
In function caret, the test for window.getSelection is incorrect.
In the code it is testing with window.getSelection() which cause the code the executed instead of just test for existence.

Solution: 
change the test to window.getSelection. Two places in the function need to be updated.

Once I made the change IE8 is happy again.

Thanks

**Comment by RobinHerbots** [comment]
Thx !!
