### ISSUE TITLE
jQuery .val() removes periods from email fields

### ISSUE THREAD

**Issue by park896** [RobinHerbots/Inputmask#854]
If you use the email inputmask on a field like this
`$("#txtEmailAddress").inputmask('email');`

and then subsequently use jquery.val method to set the value, the valHooks setup by your plugin are removing the periods from email addresses, both before and after the @ symbol. So p.v@p.com becomes pv@pcom after the call to `.val()`.

 `$("#txtEmailAddress").val('p.v@p.com');`

I am using version 3.1.61 which i believe is the latest.

EDIT: I have found that if I add a period to the definition for the \* in the email mask definition that it "fixes" this problem. However, I can't say that this doesnt cause other problems down the road.

```
    email: {
        mask: "*{1,64}[.*{1,64}][.*{1,64}][.*{1,64}]@*{1,64}[.*{2,64}][.*{2,6}][.*{1,2}]",
        greedy: !1,
        onBeforePaste: function(pastedValue) {
            return pastedValue = pastedValue.toLowerCase(), pastedValue.replace("mailto:", "");
        },
        definitions: {
            "*": {
                validator: "[0-9A-Za-z!#$%&'*+/=?.^_`{|}~-]",
                cardinality: 1,
                casing: "lower"
            }
        }
    }
```

**Comment by jonesnc** [comment]
I'm also experiencing this exact problem.

**Comment by RobinHerbots** [comment]
Hi, have a look at issue #847
It is already fixed but not yet released.

**Comment by park896** [comment]
Thanks. Yes that appears to be the same issue i guess i didnt find it in my searches because it was related to pasting.
