### ISSUE TITLE
email inputmask "isComplete" always returns true

### ISSUE THREAD

**Issue by hiddenman** [RobinHerbots/Inputmask#855]
Hi,
I have a simple email input field, defined like:
$("#email").inputmask("email");

And then goes simple check:

if  ( !$('#email').inputmask("isComplete") ) {
error handling here
}

However, when user inputs only first part of the email, isComplete always returns true.

How do i check email for completion?  The regex in your email mask definition contains the second part as required, but it doesn't check that.

Does isComplete work with dynamic masks? If not, what should i do to check validity of the user email?

Thank you in advance.

**Comment by hiddenman** [comment]
Just found, that it happens only when user inputs first part without @.

For example, if he enters "akornilov" and press Submit, isComplete returns true. However, if he enters "akornilov@", then isComplete returns false and requires the full email address.

**Comment by RobinHerbots** [comment]
I will have a look at it on monday.bThx for the extra info

**Comment by crreddys** [comment]
clearIncomplete is not working for email in Version: 3.1.62 but was working in Version: 3.1.55

$("#Email").inputmask("email", { "clearIncomplete": true });

when i enter invalid email id and jump to next control text is not getting cleared, this was happening in previous version.
