### ISSUE TITLE
NumericInput Causes err

### ISSUE THREAD

**Issue by StevenLangeraert** [RobinHerbots/Inputmask#856]
$("#priceInput").inputmask("9{1,3}.9{2}", { numericInput: true, autoUnmask: true });

**Comment by RobinHerbots** [comment]
numericInput and quantifiers doesn't work.

For the moment use the numeric alias.

**Comment by RobinHerbots** [comment]
@StevenLangeraert , 

The above mask is now working.

**Comment by StevenLangeraert** [comment]
Thanks!
