### ISSUE TITLE
$.inputmask.isValid("1A", { mask : "1A" }) returns false

### ISSUE THREAD

**Issue by fgarit** [RobinHerbots/Inputmask#858]
Hi,
In version 3.1.62-67 (jquery.inputmask.min.js + jquery.inputmask.extensions.min.js),

$.inputmask.isValid("1", { mask : "1" }) returns true
$.inputmask.isValid("A", { mask : "A" }) returns true
but
$.inputmask.isValid("1A", { mask : "1A" }) returns false

You can replace 1 by any digit actually, you'll get the same result.

$.inputmask.isValid("1B", { mask : "1B" }) returns true

This seems like a bug to me.
Thank you in advance
Florent

**Comment by RobinHerbots** [comment]
@Flo-G , 

Yes, I will have a look at it.

**Comment by RobinHerbots** [comment]
@Flo-G , 

Fixed.

**Comment by fgarit** [comment]
Thank you
