### ISSUE TITLE
Regex Latin Characters

### ISSUE THREAD

**Issue by err0x1a** [RobinHerbots/Inputmask#859]
I'm trying to limit user to fill only letters and latin chars, but is not working.

Is my approach wrong or something to work on Regex?
http://codepen.io/anon/pen/QwoKjN

Thanks

**Comment by err0x1a** [comment]
Hm! Seems to be a bug with Mac. Windows 8 is fine.

Well, I'm changing my mind, I'll let the user fill in anything, I can't take the risk of not receiving some data.

Thanks.

**Comment by RobinHerbots** [comment]
what about just $(selector).inputmask("a", { repeat: "*", greedy: false});

**Comment by lena773** [comment]
Hello,

I have a Problem. How can i delete a inputmask(). I mean, that i have ratio, in one choice must be the mask, in other no. So when i change the choice, mask stay on.

Thank you in advance

**Comment by RobinHerbots** [comment]
@lena773 , 

 $(selector).inputmask('remove');

**Comment by lena773** [comment]
thank you^^

**Comment by err0x1a** [comment]
Robin, It works, I can fill áãà, but the idea was to use Regex to not let the user enter some type of character (like numbers, punctuation). 

$("#test").inputmask('Regex', {regex:'[ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖ×ØÙÚÛÜÝÞßàáâãäåæçèéêëìíîïðñòóôõö÷øùúûüýþÿa-zA-Z ]+'});

http://codepen.io/anon/pen/QwoKjN
