### ISSUE TITLE
Mask does not overwrite selection if it's complete

### ISSUE THREAD

**Issue by eshiota** [RobinHerbots/Inputmask#86]
When a mask is complete (all characters typed in), and I select the whole input text (by double-clicking it, for example), typing a new character does not overwrite the selection (it does nothing, actually). The only way to overwrite a complete mask, in this case, is by hitting delete to erase the input, and start typing again.

This only happens when the mask has the `insertMode : true` option. I'm I missing something?

**Comment by RobinHerbots** [comment]
Hi Eduardo,

I already see the problem.  I will fix this soon.

best regards,

Robin

2012/7/17 Eduardo Shiota Yasuda <
reply@reply.github.com

**Comment by RobinHerbots** [comment]
the latest version should fix it ;-)

**Comment by eshiota** [comment]
Worked like a charm on IE8, IE9, Chrome 20, Firefox 13, Safari 5, Opera 11 and iOS 5.1.1.

Thanks!
