### ISSUE TITLE
Using alias 'url' limits the length to 60 characters.

### ISSUE THREAD

**Issue by nagyt234** [RobinHerbots/Inputmask#863]
I'm using version 3.1.62 with Yii2 and it seems that input length is limited to 60 characters if the format alias 'url' is used. Any idea?

**Comment by RobinHerbots** [comment]
@nagyt234 , 

The url alias was written by someone else, and indeed there is a limitation in length.

I guess I should update the alias.

**Comment by skinysmn** [comment]
Hi the problem steel appeare! is there any way to avoid this limitation?
