### ISSUE TITLE
Indian currency support

### ISSUE THREAD

**Issue by destanoglu** [RobinHerbots/Inputmask#866]
Hi,

Current version of inputmask does not support Indian currency format (Rs 15,98,54,875.00)
I have made a few changes and add "secondaryGroupSize" option to standart options. If you wanna take a look at the changes please look in inputmask.js and search for "OD_Edit" tag in this plunker http://plnkr.co/edit/qnPdf3fy7I6ASTBgvJjp 
If these changes are suitable for you, will you please insert them to your version.

**Comment by RobinHerbots** [comment]
@feralanPaladin , 

It looks ok, but can you send a pullrequest.  Make the changes in the numeric alias.

best regards, 

Robin

**Comment by akashk92** [comment]
it's very complicated to understand can you make it simple I want the same results for currency indian
@feralanPaladin

**Comment by destanoglu** [comment]
@akashk92 
My solution simple is to add another property ( "secondaryGroupSize" ) valued 2 to the mask options.
I also modified the main inputmask.js file by adding just a few lines;
                        if ( opts.secondaryGroupSize ) {
                            reg = new RegExp( "([\d?])(([\d?])([\d?]{" + opts.secondaryGroupSize + "}?)+)$" );
                        }
                        while ( reg.test( bufVal ) ) {
                            bufVal = bufVal.replace( reg, "$1" + opts.groupSeparator + "$2" );
                            bufVal = bufVal.replace( opts.groupSeparator + opts.groupSeparator,, opts.groupSeparator );
                        }

You can also track the modifications from the given plunker. Unfortunately I have not send a pool request yet.

**Comment by akashk92** [comment]
How do I do the same thing using data-input-mask attribute.
Because on form submit fail the masking gets removed from inputs and they becomes normal input fields

As the above solution is working perfectly

**Comment by destanoglu** [comment]
I have not used neither data-input-mask attribute not form submit operation. I simulate the submit action and get the masked values from inputmask manually using its API.
But if you have done the required additions, you should easily use data-input-mask as normal object creation, just by adding "secondaryGroupSize" attribute.

**Comment by akashk92** [comment]
Yes i've done required addition, 
but according to doc they are asking to send only one json object,
But we need to send two json object options like
.inputmask($.extend({}, genericCurrency, indianCurrency)); 
GenericCurrency and Indian currency are 2 objects

So how do we pass 2 objects in data-input-mask attribute

**Comment by destanoglu** [comment]
$.extend simply combines these two objects and generates a new object. So you should simply import the newly generated object into data-input-mask attribute. I hope this will solve your problem.

**Comment by akashk92** [comment]
I guess this could be the solution,
but How do I get the combined new object??

**Comment by destanoglu** [comment]
I think I can't get your point right. Does not extend method's return value enough for you?

**Comment by akashk92** [comment]
yeah got it. I am getting complete object.
thanx

**Comment by ghost** [comment]
is it part of any PR 
it doesn't work with latest version 4.0.0

**Comment by destanoglu** [comment]
No, not really. Unfortunately, you should modify the master.

11 Oca 2018 05:57 tarihinde "Vsoft" <notifications@github.com> yazdı:

**Comment by RobinHerbots** [comment]
@feralanPaladin , @akashk92 , @rmovsoftcorpcom , 

Can someone create a new extension for this and send a PR.  (also include some unittests)
So this can stay better supported.  If generic enough I can integrate it back into the numeric alias.

**Comment by mouryaamit** [comment]
@RobinHerbots @akashk92 @feralanPaladin is this supported in 4.x
couldn't find any proper release even in 3.x

**Comment by plugpulled** [comment]
@RobinHerbots Any update on this for version 4?

**Comment by RobinHerbots** [comment]
@meetajhu , 

I'm have some issues which hold back a refactoring of the current currency implementation.  Once this is done, I will implement indian currency support.

**Comment by mouryaamit** [comment]
@RobinHerbots it's been a long time, do we have any updated on this.

**Comment by krishghata** [comment]
How to do this on version 4.0.4?
Is it possible that this will supported out of the box?

**Comment by RobinHerbots** [comment]
@mouryaamit , @krishghata , 

Do you have some docs about the format?

**Comment by mouryaamit** [comment]
@RobinHerbots  you can refer to https://en.wikipedia.org/wiki/Indian_numbering_system
general format XX,XX,XX,XXX.YY
the decimal place will be 2 value
grouped with 2 digits except the last which is a group with 3 digit

**Comment by plugpulled** [comment]
@RobinHerbots  https://nosir.github.io/cleave.js/

Under **Numeral**  formatting check style ‘Indian Lakh’

**Comment by RobinHerbots** [comment]
@mouryaamit , @meetajhu ,

Just as a preview (not complete yet)
Have a try with
```
  Inputmask("(,99){*|1}(,999){1|1}.99",
             {
                 positionCaretOnClick: "radixFocus",
                 _radixDance: true,
                 radixPoint: ".",
                 numericInput: true,
                 placeholder: "0"
             }
         ).mask("test2");
```

**Comment by RobinHerbots** [comment]
@mouryaamit ,

There is the indianns alias now.  Can you give some feedback.

**Comment by rickylall** [comment]
> @mouryaamit ,
> 
> There is the indianns alias now. Can you give some feedback.

Using the indianns alias. And the InputMask test2 in your previous comment I am facing an issue.
The group separator (,) is coming before the number.

Like ,12,345
```
    $("#amount").inputmask("(,99){*|1}(,999){1|1}", { 
        prefix: "",
        inputmode: "text",
        positionCaretOnClick: "radixFocus",
        _radixDance: !0,
        radixPoint: ".",
        numericInput: !0,
        placeholder: "",
    });
```

**Comment by RobinHerbots** [comment]
@rickylall ,

You should try with

```
 $("#amount").inputmask("indianns");
````
