### ISSUE TITLE
Android Chrome Browser

### ISSUE THREAD

**Issue by kaarthikraajan** [RobinHerbots/Inputmask#867]
we are using input mask plugin in our project to get the formatted field from user as follows

xx-xxx-xx

when user delete the last two x using the backspace in chrome browser and still want to delete the remaining content it is not allowing the user to go beyond the hyphen even if we press the backspace key. I found that Android is not triggering any key up/down event for its back space key.

is there any solution for this issue?

**Comment by kaarthikraajan** [comment]
is there any update?

**Comment by kaarthikraajan** [comment]
Thank you for marking this to your next upcoming version 3.3, I appreciate your immediate response.

**Comment by RobinHerbots** [comment]
@kaarthikraajan , 

Can you retry with the latest version on github
