### ISSUE TITLE
Email mask incorrectly including underscore

### ISSUE THREAD

**Issue by Mottie** [RobinHerbots/Inputmask#868]
If I use the main demo email example and type in the following:
 <kbd>1</kbd>  <kbd>&rarr;</kbd> <kbd>&rarr;</kbd> <kbd>1</kbd>

The underscore placeholder becomes included with the email address.

Video: https://www.screenr.com/o66N

**Comment by RobinHerbots** [comment]
@Mottie , 

It should be possible to skip input in the position, but that case the mask should stay invalid until the placeholder is filled in.
