### ISSUE TITLE
Get unmasked value in oncomplete

### ISSUE THREAD

**Issue by Alex-Sokolov** [RobinHerbots/Inputmask#874]
Hi! Use this great plugin, but have small problem
I need to send value from field for statistic purposes with this code (value could be 10 or 12 numbers):

``` js
$('#Inn').inputmask({
    mask: "9999999999[99]",
    autoUnmask: true,
    removeMaskOnSubmit: true,
    oncomplete: function (e)
    {
        var inn = e.target.value;
        $.getJSON('/sendData?inn=' + encodeURIComponent(inn));
    }
});
```

```
XHR finished loading: GET "http://localhost/sendData?inn=2311113226__".
```

Only when I get another call for unmasked values all goes ok:

``` js
$('#Inn').inputmask({
    mask: "9999999999[99]",
    autoUnmask: true,
    removeMaskOnSubmit: true,
    oncomplete: function ()
    {
        var inn = $('#Inn').inputmask('unmaskedvalue');
        $.getJSON('/sendData?inn=' + encodeURIComponent(inn));
    }
});
```

```
XHR finished loading: GET "http://localhost/sendData?inn=2311113226".
```

Is it right way to get unmasked value in "oncomplete" hanlder?

P.S.: Using jQuery 1.11.2 and jquery.inputmask 3.1.62

**Comment by RobinHerbots** [comment]
@Alex-Sokolov , 

You can also just do 

```
$('#Inn').inputmask({
    mask: "9999999999[99]",
    autoUnmask: true,
    removeMaskOnSubmit: true,
    oncomplete: function ()
    {
        var inn = $('#Inn').val();
        $.getJSON('/sendData?inn=' + encodeURIComponent(inn));
    }
});
```

**Comment by Alex-Sokolov** [comment]
Thanks!
There is a chance to get new unmasked value as one of parameter in oncomplete-callback in future versions?

**Comment by RobinHerbots** [comment]
That would imply extra processing for every mask used.    Calling the val
function does this exactly when the autounmask option is given.

Op di 14 apr. 2015 om 10:47 schreef Alexander notifications@github.com:

**Comment by Alex-Sokolov** [comment]
Ok! I think `var inn = this.value;` will work the same way for simple text input

**Comment by RobinHerbots** [comment]
No only on firefox this will work. or on contenteditable where no native
value property is defined.

Op di 14 apr. 2015 om 12:54 schreef Alexander notifications@github.com:

**Comment by Alex-Sokolov** [comment]
I tried in Google Chrome and that's work: in `this` show current `<input>`

**Comment by RobinHerbots** [comment]
@Alex-Sokolov , 

Oh yes, dependent the mask used it will give the same result.
