### ISSUE TITLE
clearIncomplete only works on trail

### ISSUE THREAD

**Issue by AidanOrton** [RobinHerbots/Inputmask#88]
We are using your plugin to mask date input.

If a user enters "01/01/____" and blurs, it correctly clears, as clearIncomplete is set.

However if they enter "**/01/2012" or "01/**/2012" it does not clear on blur.  Is this expected behaviour?

Thanks,

Aidan

**Comment by RobinHerbots** [comment]
try the latest which fixes the issue ;-)
