### ISSUE TITLE
contenteditable decimal

### ISSUE THREAD

**Issue by Dodotree** [RobinHerbots/Inputmask#882]
TypeError: Argument 1 of Range.setStart is not an object.

When you try to erase  the number, instead of entering zero it leaves nothing and then I can't enter anything at all with this error. Also caret behaves strangely, randomly going to the far left. It works better with  mask: "9{1,10}", but also develops caret problems in Fire Fox if mouse moves out of the field. If I use <input> tag it works fine, so it's content editable issue.
Can you please look at this?
I used bundle.js

**Comment by RobinHerbots** [comment]
@Dodotree , 

Can you give some more details.

Does it happen in all browsers or in a specific one?

**Comment by Dodotree** [comment]
In FireFox,Safari, Chrome.
As far as I can tell, the caret position at some point becomes undefined and then I can do nothing to change that. Sometimes it happens right away, sometimes I can manage to put the cursor in between numbers and it works a little, but if I try to erase or move to the start/end it breaks. Sometimes it randomly jumps to the first position of the line with the caret already undefined.

It happens when I use any of the contenteditable: td or a div inside td. If I use an input tag everything is fine.

**Comment by RobinHerbots** [comment]
@Dodotree , 

on a specific os?  with any mask?

**Comment by Dodotree** [comment]
Systems have no influence on it, I have number of macs and windows. 
Yes, 'decimal' alias. Or any digital.

If I don't use alias and put "9{1,10}" it works until I delete everything in the cell and then move mouse out of the field. The latter one is the most confusing behavior and happened at least on FireFox ( at which point I gave up trying )

**Comment by RobinHerbots** [comment]
FIxed
