### ISSUE TITLE
Backspace w/ Conditional Mask

### ISSUE THREAD

**Issue by Hypnotec** [RobinHerbots/Inputmask#883]
First, thank you for your support with this project.

Second, I am having an issue when handling backspaces and conditional masks.

See: https://jsfiddle.net/b85r457c/

I have dug around through closed and open issues alike and have found similar topics, but none as described (I believe).

As you will see, with the attached sample, if you input "22" followed by "%" then hit backspace, the user is left with "2" instead of "22".  The same may be seen with it as "22.23%" as well as anywhere else where conditional input is treated as such.  Is this a simple update to the parameters used, or is there something I can do to address this?

**Comment by Hypnotec** [comment]
I suppose it is worth mentioning that if I add the following attribute...

```
            definitions: {
                '.': {
                    validator: "[.]",
                    cardinality: 1
                },
                '%': {
                    validator: "[%]",
                    cardinality: 1
                },
            }
```

... I have no issue.

**Comment by RobinHerbots** [comment]
@Hypnotec , 

In the first case he sees the . and % as static content and jumps over it as convenience when deleting.  But as they are also optional this gives the aboved described (strange) behavior.

Adding them to the definitions makes them not be treated as static content.

I will see if I can fix this,

**Comment by RobinHerbots** [comment]
@Hypnotec , 

This works with verison 5.0.0-beta

https://jsfiddle.net/b85r457c/
