### ISSUE TITLE
Tab out does not work when element is readonly

### ISSUE THREAD

**Issue by mjacobus** [RobinHerbots/Inputmask#884]
Hey there. When I set the read-only attribute on a element and try to loose focus on that element with tab it just won't work. It stay stuck on the masked element.

``` javascript
$('#money').inputmask();
$('#money').attr('readonly', 'readonly');
```

As a workaround I wish I could disable the mask, but it seems it is not a feature here. I think that is a nice-to-have.

Cheers!

**Comment by RobinHerbots** [comment]
@mjacobus , @Sovetnikov,

Fixed
