### ISSUE TITLE
Entering a period on a blank 'numeric' alias input not allowed

### ISSUE THREAD

**Issue by jmanos** [RobinHerbots/Inputmask#888]
Currently, entering a period into a blank _numeric_ alias is not allowed. 

This is an understandable behavior since '.' by itself is not considered a numeric value; however, many users will not type the leading 0 for decimal values. If the user does not pay attention to the value in the input, the user could easily type a number much larger than they meant (e.g. 3567 instead of .3567).

In one of my applications I simply check for a period on empty input elements during the `keydown` event and add "0." to the input's value instead of what they entered:

``` javascript
$(".numeric-input").inputmask("numeric", { allowPlus: false, placeholder: "" });
$(".numeric-input").on("keydown", function (event) {
    var $this = $(this);
    //if a period is entered and the input is empty, replace with 0.
    if ((event.keyCode==190 || event.keyCode==110) && $this.val() == "") {
        event.preventDefault();
        $this.val("0.");
    }
});
```

Since "0." is counted as a numeric value, this solution fits my purposes; however, it would be nice to have this sort of functionality included in the plugin.

What are your thoughts?

**Comment by jmanos** [comment]
Though I doubt this will affect how you would implement this, I changed my own implementation a little and figured I should include it here. My Script now uses the `keypress` event instead of `keydown` and the `which` property of KeyboardEvent instead of `keyCode`. So it is now:

``` javascript
$(".numeric-input").inputmask("numeric", { allowPlus: false, placeholder: "" });
$(".numeric-input").on("keypress", function (event) {
    var $this = $(this);
    if (event.which==46 && $this.val() == "") {
        event.preventDefault();
        $this.val("0.");
    }
});
```

**Comment by RobinHerbots** [comment]
@jmanos , 

Sounds good, I will add the functionality to the numeric alias.
