### ISSUE TITLE
For 'decimal' or 'numeric' alias, how to show blank for zero values?

### ISSUE THREAD

**Issue by Guy--L** [RobinHerbots/Inputmask#891]
This seems like a simple thing.  When the input has a zero value, show nothing in the input.  But I cannot find how to do this.  0 => ''.  This is a request for initial values as retrieved from the http response.

Do you have a way?  (I saw a prior issue requesting this; but the answer did not address the issue directly.)

**Comment by RobinHerbots** [comment]
duplicate of #786
