### ISSUE TITLE
currency suffix having character 'A'

### ISSUE THREAD

**Issue by itbaran** [RobinHerbots/Inputmask#893]
Hi I have a function for different currencies masking:

```
function input_mask_currency_id(id,currency){
        currency=currency.replace("A", "\\A");
        $('#'+id).inputmask("decimal", {
            autoUnmask:true,
            autoGroup: true,
            groupSeparator: ",",
            groupSize: 3,
            removeMaskOnSubmit: false,
            digits:2,
            allowMinus: false,
            allowPlus: false,
            suffix: " "+currency
        });
    }
```

---

when I want to submit this from form with ajax it does unmask all currencies like "USD", "GBT" but it does not unmask "AED"
what is the problem with currencies having character "A"

**Comment by RobinHerbots** [comment]
There is a definition A. So you need to escape the A in the suffix.  See readme

**Comment by itbaran** [comment]
Thanks RobinHerbots for prompt answer ;)
I did do escape as in the first line currency=currency.replace("A", "\A");
am I right? or I should do something else

**Comment by itbaran** [comment]
I should mention it is well working when masking!
but the problem is when unmasking the "21,332 AED",
It sends "21332 AED" and does not remove "AED"

**Comment by RobinHerbots** [comment]
Offcourse the suffix and postfix is autoescaped.  I will have a look at the unmasking. Can you make a jsfuddle with the example mask

**Comment by itbaran** [comment]
Hi, you can find it is not unmasked when form submitted:

http://jsfiddle.net/itbaran/n37t0fx1/14/

**Comment by RobinHerbots** [comment]
@itbaran , 

set the  removeMaskOnSubmit: true,

http://jsfiddle.net/n37t0fx1/15/

**Comment by itbaran** [comment]
I know, if I don't want to use removeMaskOnSubmit?
what should I do?

**Comment by RobinHerbots** [comment]
@itbaran , 

Indeed when you submit though an ajax call you can unmask without the option 

See http://jsfiddle.net/n37t0fx1/16/
