### ISSUE TITLE
Change mask default for allowPlus and allowMinus

### ISSUE THREAD

**Issue by afattahi54** [RobinHerbots/Inputmask#896]
How can I change the default value of allowPlus and allowMinus to false. I tried below but no luck:

```
$.extend($.inputmask.defaults, {
    placeholder: '',
    allowPlus:false,
    allowMinus:false
});
```

**Comment by RobinHerbots** [comment]
I will update the readme with an example.

**Comment by afattahi54** [comment]
Thanks, It will help a lot!

**Comment by RobinHerbots** [comment]
@afattahi54 , 

Have a look at https://github.com/RobinHerbots/jquery.inputmask#set-defaults
