### ISSUE TITLE
numeric input in mobile

### ISSUE THREAD

**Issue by afattahi54** [RobinHerbots/Inputmask#897]
It seems that the decimal with group  seperator is not working on mobile devices. You can test it on http://robinherbots.github.io/jquery.inputmask. Here what is happen
Type 1  :      input will be 1
Type 2  :      input will be 12
Type 3  :      input will be 123
Type 4  :      input will be 1,234
Type 5  :      input will be 51,234 <<< Here you will see an error

I have tested on Android 4.4 with chrom. The desktop version of chrom works fine.
I have noticed that after typing '4' the cart position moves to first place ( before 1 ) and this makes the error happens.

**Comment by simasalmani** [comment]
Hi @RobinHerbots ,
I'm having the same problem,
looking forward to its correction
thank  you in advance

**Comment by RobinHerbots** [comment]
@afattahi54 ,  @simasalmani , 

Can you retest with the latest version

**Comment by afattahi54** [comment]
I have tested this on an LG device android 4.4 and it is fixed. Thanks !
