### ISSUE TITLE
Repeating a character and a number On Mobile

### ISSUE THREAD

**Issue by afattahi54** [RobinHerbots/Inputmask#898]
Consider this mask:

``` javascript
input.inputmask( "IR999999999999999999999999" );
```

It accepts the input starts with 'IR' with 24 numbers, It works fine on desktop. But on mobile this happens

You type '1'  : Input will be 'IR1'
You type '2'  : Input will be 'IR12'
You type '9'  : Input will be 'IR129'
You type '8'  : Input will be 'IR1298'
You type '8'  : Input will be 'IR8' <<< The mask will be deleted

This happens if you repeat one number  
You can see it on http://robinherbots.github.io/jquery.inputmask 'License plate'. If you type '3','B','B' The input box will be 'B'

**Comment by afattahi54** [comment]
Thanks for adding to to next release !

**Comment by RobinHerbots** [comment]
@afattahi54 , 

I will try to fix it the next release, but it is possible that it is currently not possible on Android.

**Comment by zacblazic** [comment]
This also happens in the decimal example (with group separator), which is what I'm using it for. In addition to not being able to enter duplicate numbers, it won't let you enter more than 4 non-duplicate numbers.

**Comment by lilibit1985** [comment]
I have the same problem. i would appreciate it if you could look into this matter.

**Comment by RobinHerbots** [comment]
@afattahi54 , 

This should be fixed. Can you retry with the latest version.

**Comment by afattahi54** [comment]
I have tested this on an LG device android 4.4 and it is fixed. Thanks !

**Comment by afattahi54** [comment]
I have also test it on apple ios 9 it works fine

**Comment by shamspopalzai32-beep** [comment]
> Consider this mask:
> 
> input.inputmask( "IR999999999999999999999999" );
> It accepts the input starts with 'IR' with 24 numbers, It works fine on desktop. But on mobile this happens
> 
> You type '1' : Input will be 'IR1' You type '2' : Input will be 'IR12' You type '9' : Input will be 'IR129' You type '8' : Input will be 'IR18298' You type '8' : Input will be 'IR8' <<< The mask will be deleted
> 
> This happens if you repeat one number You can see it on http://robinherbots.github.io/jquery.inputmask 'License plate'. If you type '3','B','B' The input box will be 'B'

**Comment by RobinHerbots** [comment]
@shamspopalzai32-beep ,
Is this on a certain device? Browser?
