### ISSUE TITLE
Clear field option

### ISSUE THREAD

**Issue by ryanbuening** [RobinHerbots/Inputmask#9]
If user doesn't enter the required amount of numbers/mask specified, on exit/blur of field, clear out the entire field.

**Comment by RobinHerbots** [comment]
See version 0.3.7 - added clearIncomplete option (default = false)

**Comment by ryanbuening** [comment]
Awesome. Will check it out. Thanks.
On Jun 15, 2011 6:20 AM, "RobinHerbots" <
reply@reply.github.com>
wrote:
