### ISSUE TITLE
Conditional mask not working very well (99) 9999[9]-9999

### ISSUE THREAD

**Issue by matheusdavidson** [RobinHerbots/Inputmask#900]
The conditional mask (99) 9999[9]-9999 will not work very well.

It works when the user press "-", but when you just type: 99 99999999(without using the [9] condition and not pressing "-") it will display: (99) 99999-999

Any help?

**Comment by RobinHerbots** [comment]
@matheusdavidson , 

Have a look at http://jsfiddle.net/tedch2qm/

**Comment by matheusdavidson** [comment]
thats perfect @RobinHerbots.
I knew i was doing someting wrong, plugin is awesome by the way! :smile:
