### ISSUE TITLE
Static masks fails when we set value="2015" for an input field where data-inputmask was "2999"

### ISSUE THREAD

**Issue by manukeerampanal** [RobinHerbots/Inputmask#903]
Static masks fails when we set **value="13156543210"** for an input filed where **mask** was **"19999999999"**. 

The input tag is as follows:
**<input id="phone_home" name="phone_home" class="inputmasker" type="text" value="13157056276" data-inputmask="19999999999">**

The function I wrote to get masked is as follows :
**$(".inputmasker").inputmask("mask", {"mask": $(".inputmasker").attr("data-inputmask")});**

The value I saw after the masking is as follows:
**1156543210_**

**Browsers Tested:**
1. _Firefox v37.0.2_
2. _Google Chrome v21.0.1180.64_

**Comment by RobinHerbots** [comment]
http://jsfiddle.net/dt9vsd8r/

**Comment by RobinHerbots** [comment]
@manukeerampanal , 

Fixed see jsfiddle

http://jsfiddle.net/dt9vsd8r/1/

**Comment by manukeerampanal** [comment]
@RobinHerbots :+1:
