### ISSUE TITLE
decimal : extra number after delete and typing new numbers

### ISSUE THREAD

**Issue by wlasiukk** [RobinHerbots/Inputmask#904]
https://jsfiddle.net/5ds0kdct/

Steps to reproduce : 
1) enter the field
2) press home to be at beginning of field value
3) press DEL key - whole value will be deleted (first issue!)
4) start typing new value eg : 12. After second number entered there will be "121,00" value in field, last "1" is added by library.

**Comment by RobinHerbots** [comment]
@wlasiukk , 

I will have a look at it.

**Comment by RobinHerbots** [comment]
@wlasiukk , 

Fix in the latest commit

**Comment by wlasiukk** [comment]
Thank You very much for fixing it
