### ISSUE TITLE
New user; getting errors, configuration isssue?

### ISSUE THREAD

**Issue by dselec** [RobinHerbots/Inputmask#907]
Hi, sorry, I'm sure this is me.
Moving over from the Bush mask to inputmask.
Referencing jquery.inputmask.js in project.
Getting: Error: Unable to get property 'text' of undefined or null reference
or the same for 'InGroup' fro another field.
Thanks!

**Comment by RobinHerbots** [comment]
Can you give some code sample or jsfiddle.  That will make it alot easier to see the problem.  Best regards Robin

**Comment by dselec** [comment]
Hi Robin,
It happens in the quantifier:
[cid:image003.jpg@01D089AE.6E612740]
How I am calling it:
[cid:image002.png@01D089AE.6E5C6C50]
If I remove all the orginal *mask stuff, and use inputmask, I get the ‘text’ error, and if I only try the email link with inputmask, I get the ‘isGroup’ error.
I know I must have something misconfigured, just not spotting it.

You have done some wonderful work, thanks for your efforts!
Dan

**Comment by RobinHerbots** [comment]
@dselec , 

I can't see the images.   Can you make an example in jsfiddle or retry to send the screenshots.

**Comment by dselec** [comment]
Updated jquery, now all is well.
This project had an older version.
Thanks!
