### ISSUE TITLE
Problem with radixPoint on submit

### ISSUE THREAD

**Issue by billmn** [RobinHerbots/Inputmask#909]
Hi all,
I'm using "currency" mask with EURO format like this number: **€ 123.456.789,22**

This is the configuration that I have used:

``` javascript
$(".input-currency").inputmask('currency', {
    prefix: '€ ',
    autoGroup: true,
    radixPoint: ',',
    groupSeparator: '.',
    autoUnmask: true,
    removeMaskOnSubmit: true
});
```

The problem is that when I submit the form or get the input value, the **radixPoint** remain the same instead of reset to '.'

Infact I'm obtaining an incorrect format like: **123456789,00** instead of **123456789.00**

How can I solve this?
Thank you!

**Comment by RobinHerbots** [comment]
I know it is not in the readme yet but you can use the unmaskAsNumber option. See numeric extendions

**Comment by billmn** [comment]
It works ... Thank you!
