### ISSUE TITLE
oncomplete event doesn't fire when numericInput: true?

### ISSUE THREAD

**Issue by gkinsman** [RobinHerbots/Inputmask#91]
This seems to be an issue with RTL, though I don't really know where exactly the issue is.

Test Case:

HTML
`<input id="decimal"><div id="complete"></div>`

JS

``` javascript
$('#decimal').inputmask('9', {
    numericInput: true,
    "onincomplete": function () {
        $('#complete').html('incomplete');
    },
    "oncomplete": function () {
        $('#complete').html('complete');
    }
});
```

After a little investigation, it seems that the isValid function returns false even when the buffer matches the mask. 

``` javascript
if (isValid(firstMaskPos, buffer[firstMaskPos], buffer, true) == false || (opts.greedy === false && buffer.length < maskL)) {
    if (buffer[firstMaskPos] != getPlaceHolder(firstMaskPos) && buffer.length < maskL) {
        var offset = prepareBuffer(buffer, - 1, isRTL);
        if (pos.end != 0) p = p + offset;
        maskL = buffer.length;
    }
    shiftL(firstMaskPos, opts.numericInput ? seekPrevious(buffer, p) : p, c);
    writeBuffer(input, buffer, opts.numericInput && p == 0 ? seekNext(buffer, p) : p);
} else if (opts.oncomplete && IsComplete(input)) opts.oncomplete.call(input);
```

In this snippet, the second branch is never executed with numeric RTL's.

The onincomplete function fires fine, as it's executed on the blur event instead of the keypress event.

**Comment by RobinHerbots** [comment]
Hi George,

I will have a look at it soon.

best regards,

Robin

2012/7/26 George Kinsman <
reply@reply.github.com

**Comment by RobinHerbots** [comment]
see issue 93
