### ISSUE TITLE
File header incorrect version displayed

### ISSUE THREAD

**Issue by KrunchMuffin** [RobinHerbots/Inputmask#911]
When I download, the version says "Version: 0.0.0-dev" instead of 3.1.63

**Comment by RobinHerbots** [comment]
Have a look in the dist folder

**Comment by KrunchMuffin** [comment]
ok, I see that. I checked 3 different files. In the download zip, download from the website and the js folder. So for the latest version we should be checking the dist folder all the time?

**Comment by RobinHerbots** [comment]
That is correct. :-)

Op 16:08 VR 15 Mei 2015 schreef Derek notifications@github.com:
