### ISSUE TITLE
Each character repeats on Mobile

### ISSUE THREAD

**Issue by thomstark** [RobinHerbots/Inputmask#912]
Hi. I'm running these masks:

`$("div.phone_us input").inputmask({mask:"(999) 999-9999", "clearIncomplete":true});
$("div.height input").inputmask({mask:"9'9[9]\"", greedy:false, "clearIncomplete":true});
$("div.weight input").inputmask({mask:"99[9]lbs", greedy:false, "clearIncomplete":true});`

On Android Mobile (not tested on iPhone), the following bug occurs:

Type any digit (e.g., 2), the digit is added twice. Hit backspace to delete the repetition, type the next digit (e.g., 6), that digit is added twice.

And so on. 

It also does not allow you to enter the same digit three times in a row on mobile. On desktop it is fine.

**Comment by afattahi54** [comment]
I have same issue as mentioned 
https://github.com/RobinHerbots/jquery.inputmask/issues/898
https://github.com/RobinHerbots/jquery.inputmask/issues/897
For now on i just disabled them, this function may help

```
function isDeviceSmartPhone(){      
    if ((/iP(od|hone)/i.test(window.navigator.userAgent)) || 
         (/Android/i.test(window.navigator.userAgent) )) {
        return  true;
    }else{      
        return false ;      
   }   
} 
```

and change inputmask function as below

``` javascript
    (function(){
    // Store a reference to the original remove method.
    var originalInputmaskMethod = jQuery.fn.inputmask;    
    // Define overriding method.
    jQuery.fn.inputmask = function(){
    //if this is an smart device do not add inputmask
        if (isDeviceSmartPhone()){
               return;
          }else{
               originalInputmaskMethod.apply( this, arguments );
          }
        }
     })();
```

**Comment by Maahsima** [comment]
Same isssue :( When do you think we will have the fix of this ?! Thanks in advance

**Comment by dcleblond** [comment]
I don't know if this is the issue or not, but I've had a lot of problems with a lot of different input mask plugins. Apparently the Samsung stock keyboard sends the KeyDown event incorrectly.

**Comment by FRAGnatt** [comment]
Same issue ;(((( Robin, please tell. When you can fix this ?

**Comment by RobinHerbots** [comment]
@thomstark ,  @afattahi54, @Maahsima , @dcleblond , @FRAGnatt ,

This issue is solved.  Be aware that this does not mean that all android issues are solved.

**Comment by afattahi54** [comment]
Thanks ! But I tried the numeric mask, and it seems it does not accept repeating numbers , for example you can not enter 1233 or 1244 . The mask remove the repeating number and all the user entered data

**Comment by nfort** [comment]
@afattahi54 i have this problem on sumsung s4. Do you know how it's fix?

**Comment by nfort** [comment]
@RobinHerbots Sumsung s4 4.4.2 Chrome

**Comment by afattahi54** [comment]
@nfort I think it is planned for release 3.5

**Comment by RobinHerbots** [comment]
@afattahi54 , @nfort ,

The latest version does accept the input.  Tested in android chrome browser.
