### ISSUE TITLE
Ajax call is causing cursor to jump to the right upon keyup

### ISSUE THREAD

**Issue by shahvaiz** [RobinHerbots/Inputmask#913]
I have an ajax call that runs upon keyup. Each time the user presses a key, the cursor jumps to the end. For example, if the field is $253,009 and the user attempts to remove the '3', the resulting value will be $25,009 and the cursor will jump to the right of the '9'. When I disable the ajax call, the cursor does not jump. Alternatively, if I disable the mask while keeping the Ajax call, the cursor does not jump either.

These are the settings I am using:

$('#id_property_value').inputmask("currency", {
  "rightAlign": false,
  "placeholder": "",
  "digits": 0,
  "integerDigits": 7,
  "allowMinus": false,
  "autoUnmask": true
});

Any idea what could be causing this?

Thanks!

**Comment by RobinHerbots** [comment]
@shahvaiz , 

What do you do in the ajax-call?  Can you provide some more code.

**Comment by shahvaiz** [comment]
I was able to isolate the issue and create a JSFiddle. The issue has to do with 'keyup'. Each time the user tries to delete a random character, the keyup method triggers the 'inputmask' method and the cursor resets to the end. If I change it to act upon 'blur', the cursor behaves correctly.

https://jsfiddle.net/shanif/oeytxoy8/

**Comment by RobinHerbots** [comment]
Why do you call the inputmask function on every keyup?

Op di 19 mei 2015 om 04:55 schreef Shahvaiz Hanif <notifications@github.com

**Comment by shahvaiz** [comment]
Ah, you're right. I moved the inputmask function outside of keyup, and it works perfectly now. Thanks!
