### ISSUE TITLE
Add inverse property

### ISSUE THREAD

**Issue by kidchenko** [RobinHerbots/Inputmask#916]
In other plugins exists an inverse property that in money, start inputs by decimal digits

**Comment by RobinHerbots** [comment]
use numericInput: true

Op di 19 mei 2015 om 16:47 schreef José Barbosa notifications@github.com:

**Comment by kidchenko** [comment]
#644

**Comment by kidchenko** [comment]
numericInput: true show it

![image](https://cloud.githubusercontent.com/assets/5432753/7706963/d642ed1e-fe23-11e4-97b7-0ae86026cdd6.png)

here my code

![image](https://cloud.githubusercontent.com/assets/5432753/7706991/ff9d682e-fe23-11e4-9865-f724fa058aa8.png)

**Comment by RobinHerbots** [comment]
The inverse is already available but is not working for complexer masks.

See issue #644
