### ISSUE TITLE
Decimal separator conversion

### ISSUE THREAD

**Issue by billmn** [RobinHerbots/Inputmask#919]
I'm using the "numeric" mask with this configuration:

``` javascript
$(".input-mask").inputmask('numeric', {
    radixPoint: '.',
    autoUnmask: true,
    rightAlign: false,
    unmaskAsNumber: true,
    removeMaskOnSubmit: true
});
```

When I try to press "," (comma), instead of prevent it, I would replace it with "." (dot) ... is it possibile?

Thank you

**Comment by RobinHerbots** [comment]
@billmn , 

Added

**Comment by billmn** [comment]
:+1:

**Comment by billmn** [comment]
If I empty a field and tried to use "," (comma) as a decimal separator, the script prevent it ... is it normal?

**Comment by RobinHerbots** [comment]
@billmn , 

Can you make a jsfiddle for it as I don't see the problem here.

**Comment by billmn** [comment]
Sure! https://jsfiddle.net/8ho816gv/

If you try to edit a populated field "comma" being replaced with "dot" ... with an empty field, the script prevent to type "comma"

**Comment by RobinHerbots** [comment]
In which browser are you testing?

**Comment by billmn** [comment]
Chrome 43.0.2357.132 64bit on OS X Yosemite

**Comment by RobinHerbots** [comment]
@billmn , 

So you cannot type a comma in the first field?  Can you try in another browser.  

I tried with windows 8.  I will try in Linux this evening.  

Do you get something in the console?

**Comment by billmn** [comment]
With Safari and Firefox works fine!

**Comment by RobinHerbots** [comment]
@billmn , 

I will try to find a hackintosh to install Chrome on osx yosemite.

**Comment by RobinHerbots** [comment]
@billmn , 

Now I see what you mean.  Overtyping 1234.56 with komma does not work.

I will fix that

**Comment by RobinHerbots** [comment]
@billmn , 

Fixed with the latest commit

**Comment by billmn** [comment]
Great work!!!
thank you

**Comment by Dekabrist** [comment]
Hi there! I have same problem!
I can`t type comma if I set "radixPoint: '.'"  option...
Can we solve this? :)
Version: 3.3.6

**Comment by RobinHerbots** [comment]
@Dekabrist , 

I can solve that, but can you describe the defferent steps so it is clear what exactly I need to fix.  (create a new issue for it)
