### ISSUE TITLE
How to get the input mask from an element?

### ISSUE THREAD

**Issue by gkinsman** [RobinHerbots/Inputmask#92]
Is it possible to extract the mask from an already masked element? Or do I need to store the mask on the element as a workaround?

I can't seem to find any property on the help page, or through my own testing to extract it. This would be a pretty useful feature.

Cheers
George

**Comment by RobinHerbots** [comment]
Hi George, 

No you cannot retrieve the applied mask template.  Why would you need that?

Robin

**Comment by gkinsman** [comment]
Perhaps for display issues, but I can do it at the point the mask is applied instead. Ignore this!
