### ISSUE TITLE
Firefox: cursor jumps to the right when clicking anywhere on the value

### ISSUE THREAD

**Issue by shahvaiz** [RobinHerbots/Inputmask#921]
On Firefox, when you initially click anywhere on the value, the cursor jumps to the right. On subsequent clicks, the cursor does not jump. It works correctly on Chrome and Safari. I'm using the latest code via c6e8183.

**Comment by RobinHerbots** [comment]
Can you provide some more info as i don't see a problem here.  FF/linux && FF/windows

**Comment by evdinursan** [comment]
I have the same issue. I upgraded to the latest version and I've seen this behavior on Firefox 38.0.1 and also on Internet Explorer 11.0. On Chrome it's working perfect.

This is how I'm enabling inputmask using jquery:

$(".numeric-mask").inputmask({
        alias: 'decimal',
        radixPoint: $("#hfDecimalSeparator").val(),
        clearMaskOnLostFocus: true,
        groupSeparator: $("#hfDecimalGroupSeparator").val(),
        autoGroup: true,
        insertMode: false
    });

**Comment by evdinursan** [comment]
It behaves exactly the same - I'm using the latest version 3.1.64-70 and I'm using the jquery.inputmask.bundle.js file - made the test in Firefox and IE - the same behavior and also in Chrome - it's working.

If I'm clicking for the first time in a textbox, the carret goes at the end (selectedCaret.begin = selectedCaret.end = total number of characters in that textbox) but if I'm clicking the second time in the same text box it behaves normally (selectedCaret.begin = 0 and selectedCaret.end = total number of characters).

Thank you!

**Comment by RobinHerbots** [comment]
@evdinursan , 

You are right.  I will have a closer look.

**Comment by RobinHerbots** [comment]
@evdinursan , 

Ok, now it should be ok ;-)

**Comment by evdinursan** [comment]
Yes it is! Thank you!!!!

**Comment by shahvaiz** [comment]
Works perfectly for me as well. Thank you!
