### ISSUE TITLE
Chrome 43.0.2357.81 breaking change

### ISSUE THREAD

**Issue by mseppy** [RobinHerbots/Inputmask#923]
With the update of Chrome to version 43, we get the following error:

**Uncaught TypeError: Cannot read property 'masksets' of undefined  jquery.inputmask.js:750**
`(anonymous function)   @jquery.inputmask.js:750`
`jQuery.fn.extend.val       @jquery-2.1.0.js:7248`
`focusedIsDirty         @jquery.dirtyforms.js:254`
`onFocus                @jquery.dirtyforms.js:245`

We have confirmed it is Chrome 43, because doing the same thing in 42 does not produce the error. The page uses Slick grids, and we are applying telephone formatting and editor.

```
this.init = function () {
        $input = $("<INPUT type=text class='editor-text' />")
      .appendTo(args.container)
      .bind("keydown.nav", function (e) {
          if (e.keyCode === $.ui.keyCode.LEFT || e.keyCode === $.ui.keyCode.RIGHT) {
              e.stopImmediatePropagation();
          }
      })
      .focus()
      .select();
        $input.inputmask("mask", { "mask": "(999) 999-9999" });
    };
```

It's happening in the patchValueProperty() method:
![image](https://cloud.githubusercontent.com/assets/12613894/7817901/28f4e6ca-03a6-11e5-9929-2949231284da.png)

**Comment by RobinHerbots** [comment]
@mseppy , 

Which version of the inputmask are you using?

**Comment by TheKidCoder** [comment]
I am also seeing this error. Using version 2.5.10.

**Comment by TheKidCoder** [comment]
I found that upgrading to version 3 fixed the issue.
