### ISSUE TITLE
Decimal looses digits

### ISSUE THREAD

**Issue by evdinursan** [RobinHerbots/Inputmask#924]
Since the yesterday update (I think), if I'm doing a calculation and set a field with a float value, the textbox which has the inputMask enabled doesn't display the digits, though it's configured to have two digits. At the beginning, the initial value (0) is displayed correctly as 0,00 (using ro culture).

The textbox is being rendered like this:

<input id="PaymentReferenceValue" class="form-control numeric-mask valid" type="text" value="0,00" readonly="readonly" placeholder="" name="PaymentReferenceValue" data-val-required="Valoarea platii in moneda de referinta: Camp obligatoriu." data-val-number="Valoarea platii in moneda de referinta *: Format incorect. Formatul trebuie sa fie de tip numar." data-val="true" data-inputmask="'digits': '2'" style="text-align: right;" ffpdm="8ykx8k9ijgijpn9g2cv0gl" aria-required="true" aria-invalid="false" aria-describedby="PaymentReferenceValue-error">

The input mask is triggered through jquery like this:

$(".numeric-mask").inputmask({
        alias: 'decimal',
        radixPoint: $("#hfDecimalSeparator").val(),
        clearMaskOnLostFocus: true,
        groupSeparator: $("#hfDecimalGroupSeparator").val(),
        autoGroup: true,
        insertMode: false
    });

And the method which makes the computations looks like this:

function updateReferenceValue(refExchangeRateInput, paymentInput) {
    var paymentReferenceValueInput = $("#paymentReferenceValueParent > input[type='text']");

```
var paymentValue = Globalize.parseFloat(paymentInput.inputmask('unmaskedvalue'));
var exchangeRate = Globalize.parseFloat(refExchangeRateInput.inputmask('unmaskedvalue'));
var paymentReferenceValue = paymentValue / exchangeRate;
console.log(paymentReferenceValue);
paymentReferenceValueInput.val(paymentReferenceValue);
```

}

In the console log, the displayed value is correct with all the digits.

Thank you.

**Comment by evdinursan** [comment]
Made a bit of a research - I don't know if it will help you or not but this is what I got:

a) as I've told you I'm not using en culture, so in my case - the decimal separator is ","
b) on the method onBeforeMask (jquery.inputmask.bundle.js line 2255) you're splitting the initial value which is OK but later in that method, you do 

initialValue = Math.round(parseFloat(initialValue) \* digitsFactor) / digitsFactor;

and in my case, these is what I have:

initialValue = 80,81773892455493
valueParts = ["80", "81773892455493"]
decPart = 81773892455493

so this is perfect, but then, when you compute the initialValue again, the parseFloat(initialValue) gives me 80.

**Comment by RobinHerbots** [comment]
@evdinursan, 

Thx for the extra info.  The parseFloat expects a . as radixpoint and so truncates to the "valid value".

I will fix that asap.

**Comment by evdinursan** [comment]
Thank you very much! It's working perfect!!!!!
