### ISSUE TITLE
IsValid on inputs

### ISSUE THREAD

**Issue by Shalxxx** [RobinHerbots/Inputmask#925]
Hi. I love this plugin, but I would really appreciate some visibile way showing if the input is valid or not. Especially when using regular expression. Let say by using some class or attribute.

For example when I make inputmask checking email address, phone number or required input, I would like to now when conditions are fullfilled.

Thanks.

PS: Sorry for my english

**Comment by RobinHerbots** [comment]
@Shalxxx , 

You can use the  
      oncomplete: $.noop, //executes when the mask is complete
      onincomplete: $.noop, //executes when the mask is incomplete and focus is lost
     onKeyValidation: $.noop, //executes on every key-press with the result of isValid. Params: result, opts
callbacks for that.  

oncomplete  add valid class 
on incomplete remove the valid class
or something on onKeyValidation

See the readme.
