### ISSUE TITLE
String with decimals is stripped to integer value before onBeforeMask

### ISSUE THREAD

**Issue by jgladch** [RobinHerbots/Inputmask#926]
I thought that #924 would hopefully help solve this issue, but since I'm not using the 'numeric' alias it doens't apply.

The issue:
- I'm trying to set up ATM-like currency input masking as mentioned in #644 
- One of my fields (`price`) is a string formatted with decimals `'12.34'`
- I need to set up an `onBeforeMask` hook in order to adjust this value for the input mask (multiply by 100 so that the decimals show up correctly when masked)
- When I inspect the `value` passed to my `onBeforeMask` function for this field, I see only the integer value. IE. (`21`, in this case since the field is reversed)
- This is a major problem as I need to preserve the decimal places for this price field.

Any help here would be tremendously appreciated.

**Comment by RobinHerbots** [comment]
@jgladch , 

What do you got already?  Which mask / options /etc

**Comment by jgladch** [comment]
``` js
template.$('input').inputmask({
    mask: '$999999.99',
    numericInput: true,
    placeholder: ' ',
    autoUnmask: true,
    greedy: false,
    clearMaskOnLostFocus: true,
    onBeforeMask: function (value) {
      // Value is stripped of decimals here!
      return value;
    },
    onUnMask: function (maskedValue, unmaskedValue) {
      return (Number(unmaskedValue) / 100).toFixed(2);
    }
  });
```

**Comment by jgladch** [comment]
Apologies! This was caused by our application code. Thanks again!
