### ISSUE TITLE
Having some issues with mask "numeric" and digitsOptional

### ISSUE THREAD

**Issue by pudgeball** [RobinHerbots/Inputmask#927]
Hey there,

I'm having some weird handling of 0 when it comes to one of my inputs when I have digits set to 2 and digitsOptional set to false.

If I enter 0.00 it thinks the user has entered nothing and my 0 doesn't persist.  Similarly if you enter just 0. it again doesn't persist the value.  However sometimes if I enter a valid value for example, 55, and then click away.  Then change delete that value it will enter a 0 which will persist after clicking away again.

I'm wondering if this is a bug or just something that I'm not doing correctly.  I would like to be able to enter 0 (or 0.00) even when digitsOptional is set to false.

My code looks like:

``` javascript
$el.inputmask('numeric', {
    placeholder: '0',
    clearIncomplete: false,
    showMaskOnFocus: true,
    showMaskOnHover: true,
    autoGroup: true,
    digits: 2,
    digitsOptional: false,
    radixPoint: '.',
    groupSeparator: ','
});
```

And here is a fiddle showing my problem: https://jsfiddle.net/s5acgmyz/

**Comment by RobinHerbots** [comment]
This is simular to #786

**Comment by pudgeball** [comment]
Yeah it's basically the same issue.  You talk about removing postFormat from the numeric alias.  What sort of issues are stopping you from doing so?  I would love to be able to submit a PR fixing it, if I could.

**Comment by RobinHerbots** [comment]
@pudgeball , 

The postformat is needed for the grouping.  So I need to define a dynamic masks which automatically deals with that.  Maybe I can add an extra check in the postvalidation and generate a new mask definition there if needed.  

An other approuch could be to just rewrite the whole numeric alias again and only use the postvalidation function.

Anyway feel free ;-)

**Comment by RobinHerbots** [comment]
Follow issue #786.  I will close this one

**Comment by pudgeball** [comment]
Will do! Thanks!
