### ISSUE TITLE
Is numeric carret position broken?

### ISSUE THREAD

**Issue by Rouche** [RobinHerbots/Inputmask#928]
Or there is something i dont understand.

Very simple code with latest vetsion http://jsfiddle.net/wnsjomyd/2/

When you put enough numbers, 1234567 in this example. the carret position seems to jump in opposite position.
Like i click between 4 and 5 it will jump between 2 and 3. 

Is there any way to stop this? I expected it should not jump at all. or stay on the complete right like when its empty or on the left of the decimal separator?

I tryed nojumps, radixfocus, removing options without succes.

Thanks.

**Comment by RobinHerbots** [comment]
@Rouche , 

I see it.  I will fix it before monday.

best regards, 

Robin

**Comment by Rouche** [comment]
Sweet! Thanks!
