### ISSUE TITLE
Provide convinient method to unmask value

### ISSUE THREAD

**Issue by smashercosmo** [RobinHerbots/Inputmask#929]
We have access to formating function $.inputmask.format, that takes value and mask options and returns masked value. We need a reverse method that will return unmasked value. 
P.S. Yes I know that there is $(element).inputmask('unmaskedvalue'), but it would be nice to have it as an instance method. It could be $.inputmask.unmask or $.inputmask.deformat or whatever)

**Comment by RobinHerbots** [comment]
@smashercosmo , 

Ok, but how do you see it exactly? That you provide a value and some inputmask options and it returns the unmaskedvalue?  Or you provide a masked input and you want to retrieve the unmaskedvalue?

Btw $.inputmask is removed.  Use inputmask.format instead.

**Comment by smashercosmo** [comment]
Yes, I want to be able to use inputmask internal methods without applying the plugin to input field. If, for example, we have mask "blabla 9{0,}" and a string value "blabla 12345", I want to pass these as an arguments to some function like $.inputmask.unmask(value, mask) and get "12345".
