### ISSUE TITLE
Numeric input only fires oncomplete after n+1 inputs

### ISSUE THREAD

**Issue by gkinsman** [RobinHerbots/Inputmask#93]
When using a numeric input with no decimal places, the oncomplete event is only fired when the input is actually complete, and another valid keypress is made.
### Sample Code

``` html
<input style="display: inline;" id="integer">&nbsp;&nbsp;&nbsp;
            <div style="display: inline;" id="intcomplete"> </div>
```

``` javascript
$('#integer').inputmask('000', {
    numericInput: true,
    "oncomplete": function() {
        showComplete('intcomplete');
    },
    "onincomplete": function() {
        showIncomplete('intcomplete');
    },
    "oncleared": function() {
        showClear('intcomplete');
    }
});
```

Steps to reproduce:
1. Type three numbers
2. Field should fire oncomplete event
3. Type another number
4. Field fires oncomplete event

**Comment by gkinsman** [comment]
As a side note, if there were more comments in the code it might be easier for others to contribute fixes. I'm looking through it, but it's quite difficult to determine what's going on.

**Comment by RobinHerbots** [comment]
Hi George,

I will fix this as soon I found some spare time.  Thx for investigating
further on the issue.

But I numeric input needs some refactoring and/or alignment with the
'normal' input.

best regards,

Robin

2012/7/30 George Kinsman <
reply@reply.github.com

**Comment by gkinsman** [comment]
No worries, thanks for being so proactive :).

**Comment by RobinHerbots** [comment]
checkout the latest version
