### ISSUE TITLE
Escape optional marker, quantifiable marker, alternator marker and backslash not working

### ISSUE THREAD

**Issue by zeskysee** [RobinHerbots/Inputmask#930]
If i want use the following character/marker in my masking, I would like to able to escape them to make them static character: 
- optional marker [ ]
- quantifiable marker  { }
- alternator marker |
- backslash \

E.g.
mask pattern: 999-\[aaa\]
mask placeholder: _**-[_**]

mask pattern: 999\|aaa
mask placeholder: _**|_**

Or maybe any other way to make those marker and backslash work like static value?

**Comment by RobinHerbots** [comment]
@zeskysee , 

Try double escaping them.  \\[

**Comment by zeskysee** [comment]
Double escape also not working.

Please refer to the fiddle
http://jsfiddle.net/zeskysee/s1r6aow8/
- Escape special character row

**Comment by zeskysee** [comment]
#933
