### ISSUE TITLE
Avoid inputmask set the maxlength 

### ISSUE THREAD

**Issue by afattahi54** [RobinHerbots/Inputmask#932]
Is it possible to set inputmask on an input in the way that the inputmask does not change the  maxlength of the input?!

Or is it possible to change the maxlengh of an input after the inputmask  applied? below did not worked:

input.inputmask( "f{0,13}"); //f is a validator 
input.attr('maxlength', 123);

**Comment by RobinHerbots** [comment]
@afattahi54 ,

input.inputmask( "f{*}"); //f is a validator 
input.attr('maxlength', 123);

**Comment by lilibit1985** [comment]
It s working! Thanks
