### ISSUE TITLE
phone-codes.js is missing when installing with bower

### ISSUE THREAD

**Issue by ansaus** [RobinHerbots/Inputmask#937]
it doesnt include phone-codes.js when I install it with bower. so I cant use phone masks. 
I just type "bower install jquery.inputmask"

**Comment by newenegue** [comment]
+1

It would be great to have this working with bower.

**Comment by RobinHerbots** [comment]
@ansaus , @newenegue ,

Should be available in the next release.  under extra/phone-codes/...

**Comment by newenegue** [comment]
@RobinHerbots Thanks!
