### ISSUE TITLE
Default Enter key function getting lost on an input mask text field

### ISSUE THREAD

**Issue by kumar29** [RobinHerbots/Inputmask#938]
I have an onchange handler on a text input which gets fired whenever I type in the field and hit Enter key.
<input type="text" class="date-type" onchange="alert('Value changed')"/>

After applying input mask plugin, the onchange handler gets removed. The alert does not come up when I hit Enter. Is there a way to not lose this function which is baked into the browser?

<script>
        $(function(){
           $(".date-type").inputmask("mm/dd/yyyy");
        })
</script>

Thanks,
Kumar

**Comment by RobinHerbots** [comment]
@kumar29 , 

Can you create a jsfiddle with an example as I tested the issue and the change event get triggered even when the inputmask is applied on the input and I type Enter

best regards, 
Robin

**Comment by kumar29** [comment]
Hi Robin,

Thanks for looking at this quickly. Here's a fiddle
http://jsfiddle.net/0wzzretd/1/

I enter a date and hit enter, the alert doesn't show. But if I remove the plugin, typing a value and hitting Enter pops up the alert.

Thanks,
Kumar
