### ISSUE TITLE
Format javascript date object

### ISSUE THREAD

**Issue by skysurfer72** [RobinHerbots/Inputmask#939]
Hi.
I want to apply the mask for date in italian format (dd/mm/yyyy).
I have got two problems:
1) I can't apply the format using data-inputmask.
 <input id="prova2" data-inputmask="d/m/y'" ng-model="miaData" />
2) If i apply the input mask via javascript in this way:
$("#prova2").inputmask("dd/mm/yyyy", { placeholder: '_', showMaskOnHover: false, insertMode: false });
and i create a javascript date object:
$rootScope.miaData = new Date(1972, 11, 3);
I will see this date in the input
03/12/2000
If i don't apply the mask i see:
Sun Dec 03 1972 00:00:00 GMT+0100 (ora solare Europa occidentale)

Thank you.

**Comment by RobinHerbots** [comment]
@skysurfer72 , 

for the first use data-inputmask-alias="dd/mm/yyyy"
For the second I would need to implement the    onBeforeMask: function(initialValue, opts) callback

I will add this to the date aliases in milestone 3.4

**Comment by RobinHerbots** [comment]
This is fixed in the latest version.
