### ISSUE TITLE
Request: Have unmasked value respect decimal

### ISSUE THREAD

**Issue by Soupy** [RobinHerbots/Inputmask#94]
It would be nice if, when getting the unmasked value for a numeric input that has decimals, that the unmasked value include the decimal.

For example, if I have the mask  "$ 9,999.99" and I enter 123, the unmasked value should be "123.00".

Thank you for considering this enhancement.

**Comment by gkinsman** [comment]
Would this be considered a bug rather than an enhancement? :)

**Comment by RobinHerbots** [comment]
An enhancement ;-)

the unmask function is not aware of datatypes, so unmasking means stripping
away masking stuff

2012/7/31 George Kinsman <
reply@reply.github.com

**Comment by RobinHerbots** [comment]
it's a feature ;-)

**Comment by RobinHerbots** [comment]
I will not implement this.  You can parse the decimal value with jquery globalize or something
