### ISSUE TITLE
Suppport for HTML5 numeric pad format for mobile devices

### ISSUE THREAD

**Issue by btruong** [RobinHerbots/Inputmask#941]
Please see https://jsfiddle.net/8mo1mem0/

In order to activate the numeric pad format for mobile devices, we are using an HTML5 pattern attribute:
attribute="pattern="\d*""

However, adding this attribute appears to break the input for desktop browser where when you submit it, it will give the following error: (However, it seems to be ok on Safari so perhaps this is a browser specific thing and perhaps html5 validation attributes always occur before js validation?)

"Please match the requested format"

It would be great to have this plugin work with the HTML5 pattern attribute so that we do not have to set conditions to detect mobile browsers before adding in the pattern attribute.

**Comment by RobinHerbots** [comment]
@btruong , 

I tried your fiddle on some android devices, but it does not make the numeric keyboard layout pop-up by default.  On which mobile devices did you use it?
