### ISSUE TITLE
CTRL-x / Cut issue

### ISSUE THREAD

**Issue by gwelr** [RobinHerbots/Inputmask#948]
Further to https://github.com/RobinHerbots/jquery.inputmask/issues/659
Apparently, the cut issue is not over yet. When I cut a value from an masked input, the value is corretly removed from the field but it is not added to the clipoard. 

EG: clipboard has 123456
Inputmask field has 654321
cut 654321 => inputmask field is empty
paste in another field => 123456 and not 654321

using jquery.inputmask plugin from the Yii2 project, jquery.inputmask is 3.1.63. According to me, the https://github.com/RobinHerbots/jquery.inputmask/issues/659 fix is included into 3.1.63.

**Comment by gwelr** [comment]
Posted to https://github.com/yiisoft/yii2/issues/8747 as well as I can't tell if the issue is in jquery.inputmask or in the Yii2 plugin.

**Comment by RobinHerbots** [comment]
Ate you using the numericinput option?

**Comment by danielczestki** [comment]
Issue is in the jquery.inputmask
I have the same problem. i do not use numeric input option

**Comment by paulpolushkin** [comment]
I have the same issue. The clipboard does not contain a value after I try to cut it from an input with mask.

**Comment by gwelr** [comment]
Any chance to get an update on this one ? I see the ticket assignment was removed on July 28...

**Comment by paulpolushkin** [comment]
Thank you!
