### ISSUE TITLE
Set specific inputmask option on already initialized control

### ISSUE THREAD

**Issue by brownbl1** [RobinHerbots/Inputmask#949]
Similar to how jQuery ui datepicker lets you set options piecemeal on an existing datepicker via the `$("#datepicker").datepicker("option", { ... })` method, I'd like to be able to add or update an option on an existing inputmask control. Is this currently supported?

Currently, it seems that if I try to do this, it overwrites the previous options

```
$("#input1").inputmask("date", {
  insertMode: false
});

$("#input1").inputmask("date", {
  oncomplete: function () { ... }
});
```

such that insertMode is now true but oncomplete is set and working fine. The goal is to be able to use an alias like date and extend it once for all controls with a given class with default options. Then, piecemeal, I'd like to update individual controls that have specific settings or requirements and have it build on the previously set options that are not part of the alias.

I know I could create more aliases, but I think that is not an ideal solution because you have to completely reinitialize the inputmask each time. Thoughts?

Great work on this plugin, by the way. I'm loving it.

**Comment by brownbl1** [comment]
Additionally, it would be great to have the `$().inputmask("option", "mask")` method functioning as a getter where `mask` could be any valid option.

**Comment by RobinHerbots** [comment]
Sounds great!  I will add both.

Op 21:18 VR 12 Jun 2015 schreef itslittlejohn notifications@github.com:
