### ISSUE TITLE
add some demo page

### ISSUE THREAD

**Issue by RobinHerbots** [RobinHerbots/Inputmask#95]

**Comment by RobinHerbots** [comment]
Demo-page added -  need some more examples but it's a start  ;-)

**Comment by travisdahl** [comment]
Where is the demo? It would be nice to have a link to a working demo in the readme

**Comment by RobinHerbots** [comment]
http://robinherbots.github.io/jquery.inputmask

**Comment by RobinHerbots** [comment]
Demo link added to readme

**Comment by travisdahl** [comment]
Thanks! You are awesome!
