### ISSUE TITLE
Min value doesn't work with allowMinus

### ISSUE THREAD

**Issue by jpontet** [RobinHerbots/Inputmask#951]
Hi Robin!

I have found this issue where if you set the option "allowMinus: true" and you then wish to limit the negative number and so add the option "min: -999" for example, you can still enter more than "-999" into the mask. We are also using the "decimal" alias.

See this fiddle: https://jsfiddle.net/apvmL5y4/

Any ideas?

**Comment by RobinHerbots** [comment]
@jpontet , 

The check for the minvalue happens on blur only.  I may update it to also check the value on entering data.

**Comment by jpontet** [comment]
Thanks @RobinHerbots . This is a feature we need- any advice on how to add it?

**Comment by RobinHerbots** [comment]
@jpontet , 

Use the postValidation callback in the numeric alias.

I did already a little test, but what would be the common desired behavior.  Should the plugin convert to the minvalue when you try to type a value less then the minvalue or should it just not allow it?

**Comment by jpontet** [comment]
We would like the same behaviour as the maxvalue i.e just not allow it. I would appreciate any code you can share. Thanks

**Comment by RobinHerbots** [comment]
Have a look at the postValidation callback in the numrric extensions. You only need to uncomment it.

**Comment by jpontet** [comment]
Thanks for pointing me in the right direction @RobinHerbots

**Comment by jpontet** [comment]
@RobinHerbots looking at the numeric extension the postValidation callback is not commented out. Do you mean it should be commented? I have tried this and it doesnt validate positive or negative numbers...

**Comment by jpontet** [comment]
@RobinHerbots I have created a solution as per the following which is good enough for the time being. However the biggest restriction being that it will reject opts.min being more than 1 digit e.g. '5' will work as a min option but '55' will not- let me know what you think!

```
postValidation: function(buffer, opts) {
                var isValid = !0, maskedValue = buffer.join(""), processValue = maskedValue.replace(opts.prefix, "");
                processValue = processValue.replace(opts.suffix, "");
                processValue = processValue.replace(new RegExp($.inputmask.escapeRegex(opts.groupSeparator), "g"), "");
                isValid = "," === opts.radixPoint && (processValue = processValue.replace($.inputmask.escapeRegex(opts.radixPoint), "."));
                processValue = processValue.replace(new RegExp("^" + $.inputmask.escapeRegex(opts.negationSymbol.front)), "-");
                processValue = processValue.replace(new RegExp($.inputmask.escapeRegex(opts.negationSymbol.back) + "$"), "");

                // For non-negative values
                if (isFinite(processValue) && processValue.indexOf('-') === -1) {
                    if (isFinite(opts.max) && isFinite(opts.min)) {
                        // Valid max & min options
                        if ((parseFloat(processValue) <= parseFloat(opts.max)) &&
                        (parseFloat(processValue) >= parseFloat(opts.min))) {
                            isValid = true;
                        }
                    } else if (isFinite(opts.max) && (parseFloat(processValue) <= parseFloat(opts.max))) {
                        // Ensure value is not greater than max option
                        isValid = true;
                    } else if (isFinite(opts.min) && (parseFloat(processValue) >= parseFloat(opts.min))) {
                        // Ensure value is greater than min option
                        isValid = true;
                    }
                }
                // For negative values
                if (processValue.indexOf('-') >= 0 && opts.allowMinus) {
                    if (isFinite(processValue) && isFinite(opts.min)) {
                        // Value should be greater than min option 
                        if ((parseFloat(processValue) >= parseFloat(opts.min))) {
                            isValid = true;
                        }
                    } else if (processValue.indexOf('-') === 0) {
                        // Allow leading negative
                        isValid = true;
                    }
                }

                return isValid;
            }
```

**Comment by RobinHerbots** [comment]
@jpontet , 

I just posted a fix for the issue.
