### ISSUE TITLE
Number Mask With Fix Nine in it

### ISSUE THREAD

**Issue by afattahi54** [RobinHerbots/Inputmask#958]
If I want to have a mask which fix starts with "1234" and has a dash with for number after it , I can use 

```
input.inputmask ({"1234-999"});
```

How ever if I want a mask which fix  starts with "1239" and has a dash with for number after it ,the below mask is not working

```
input.inputmask ({"1239-999"});
```

As the "9" is a special character in mask and can not be used in the fix part of the mask ?! 
Any comment on how to solve this ?!

**Comment by RobinHerbots** [comment]
You need to escape the fixed 9

Op 09:16 ZA 20 Jun 2015 schreef afattahi54 notifications@github.com:

**Comment by afattahi54** [comment]
That worked, thanks !

```
input.inputmask ({"123\\9-999"});
```
