### ISSUE TITLE
Grouping causes the repeat count to be incorrectly calculated

### ISSUE THREAD

**Issue by gkinsman** [RobinHerbots/Inputmask#96]
It seems that the groupSeparator is included in the repeat count for the decimal mask, but there's also an off by one error. With the following code, typing "1111111" ends input, and on tab triggers an onincomplete event. Note that there are only 9 characters in total in the masked input ("1,111,111"), instead of the repeat count, 10.

``` javascript
$('#decimal').inputmask('decimal', {
    numericInput: true,
    autoGroup: true,
    repeat: 10,
    "oncomplete": function() {
        $('#deccomplete').html('complete');
    },
    "onincomplete": function() {
        $('#deccomplete').html('incomplete');
    },
    "oncleared": function() {
        $('#deccomplete').html('');
    }
});
```

``` html
<input style="display: inline;" id="decimal">
<div style="display: inline;" id="deccomplete"> </div>
```

Also related to this: when not using autoGroup: true, the decimal point counts as a character in the repeat, meaning it can't be used as a sort of max length property. I've noticed that in general the repeat tends to act as a max character length, rather than numeric length. Would it be possible to have a max numeric property of some sort, that doesn't take decimal places, groupSeparators or negative signs into account?

**Comment by RobinHerbots** [comment]
who ever wanted numeric support in this plugin ??  ;-) (never heard of the autonumeric plugin?? which already included everything!)  hehehe

a max numeric property isn't a bad idea, ... if we add this option for the decimal and alike aliases and based on this calculate the repeat property

**Comment by gkinsman** [comment]
Actually I haven't, it looks awesome, thanks! It probably gets me all I need for numeric masking, so I can keep using this for dates/weird masks :). I still think it'd be a good idea to get the numeric masking right here too though.

**Comment by RobinHerbots** [comment]
I agree, I will add some numericLength property or so, ...  which takes the grouping etc into account.  Are there other features missing for the decimals you are thinking of? A whishlist?

I really appreciate your input.

**Comment by gkinsman** [comment]
Not yet, though there may be more as I experiment further. For now the biggest thing holding back my usage is optional masks; I haven't been able to figure out a way to declare optional single characters in a mask. That would be useful, though I haven't mentioned it since I see it's slated for 2.0.

Glad to be of help, this is one of the richest masking plugins I've seen and I'd love to be able to use it :).

**Comment by RobinHerbots** [comment]
Yes, it was implemented before, but it was not fail proof and I decided to
leave it out, until later.  There is some kind of optional functionality
when used at the end.  Just put the end in [].  You can find it in the
readme.

2012/8/1 George Kinsman <
reply@reply.github.com

**Comment by gkinsman** [comment]
Ah, yes I was trying to get that working and was wondering why it wasn't. Might want to update the docs to mention it only works at the end.

**Comment by RobinHerbots** [comment]
I will not add a numericlength property but I will change the masklength that it doesn't take the groupseparator into account.

**Comment by RobinHerbots** [comment]
The latest now takes the groupîng and radix character into account.
