### ISSUE TITLE
isValid doesn't work for particular mask

### ISSUE THREAD

**Issue by azhuchkov** [RobinHerbots/Inputmask#961]
I want to validate input value before applying plugin (because plugin amends current input value and in this case I just want to erase current value). But there is no way to invoke isComplete and $.inputmask.isValid fails for mask.

**Comment by RobinHerbots** [comment]
@azhuchkov , 

Can you provide the mask you are using?

**Comment by azhuchkov** [comment]
I tried something like: 

```
$.inputmask.isValid('DE123123131', {mask: 'DE9{9}'});
```

**Comment by RobinHerbots** [comment]
I will have a look

**Comment by RobinHerbots** [comment]
@azhuchkov , 

When you are using a version above 3.1.63 you need to use

```
inputmask.isValid('DE123123131', {mask: 'DE9{9}'});
```
