### ISSUE TITLE
Auto position cursor at end of data on focus

### ISSUE THREAD

**Issue by gbronzer** [RobinHerbots/Inputmask#965]
I'm trying to figure out how to auto position the cursor when a user tabs into an input mask that is partially completed. Our specific scenario deals with phone numbers where we prefill the area code with a default and want to start the cursor after the area code.

I can easily detect if they just have the area code and just position the cursor, but I'd like it to be intelligent in case they have more or less filled in. The issue is I can't figure out a way to know where the finished data is in the masked value.

The mask is (999) 999-9999. For example, if they've only got 2 digits pre-existing, the position is 3, but if they have 7 existing, then the position would be 10 due to the mask's () and -.

Is there a way to pull this off by querying inputmask for where it's tracking what's already been filled?

Thanks!

**Comment by RobinHerbots** [comment]
@gbronzer , 

I added an option positionCaretOnTab.  Set it to true to position the caret

**Comment by gbronzer** [comment]
I'm using a nuget package that's older but I migrated your additions into it and it works perfectly. Thanks so much for an awesome plugin and your awesome support!
