### ISSUE TITLE
Date mask

### ISSUE THREAD

**Issue by violin0631** [RobinHerbots/Inputmask#966]
Hi.
I want to input date like as '2015/02' and i created mask is 'yyyy/mm' but it is not working.
I try with masks are 'y/m' or 'mm/yyyy', it worked but with mask is 'y/m' i can't input years > 2099, i've set:  {yearrange: { minyear: 1900, maxyear: 2299}

**Comment by RobinHerbots** [comment]
@violin0631 , 

Try with Inputmask 5.0.0
