### ISSUE TITLE
Hexadecimal mask

### ISSUE THREAD

**Issue by fredcido** [RobinHerbots/Inputmask#967]
What would be the format if I want to allow hexadecimal color masks?

**Comment by RobinHerbots** [comment]
What do you mean exactly with hexadecimal color masks?

**Comment by fredcido** [comment]
White: #FFFFFF
Red: #FF0000

How do I use # and define just 0-9 and A-F ?

**Comment by RobinHerbots** [comment]
Define a custom definition.   I will also add the hex definition in the  inputmask. extensions

**Comment by fredcido** [comment]
How do I define a literal # instead of it understanding as maskSymbol?

**Comment by RobinHerbots** [comment]
You need to escape it or don't  include the inputmask. extensions

**Comment by RobinHerbots** [comment]
get the  latest inputmask and try \\#######

**Comment by Zapnologica** [comment]
So does # = Hexadecimal character?
