### ISSUE TITLE
Custom masks doesn't work with current release

### ISSUE THREAD

**Issue by garcia-jj** [RobinHerbots/Inputmask#968]
I'm trying to write some custom masks, like this:

```
inputmask.extendAliases({
    cpf        : { mask:  '999.999.999-99' },
});
```

But I'm getting an error saying that `inputmask` is not defined. And trying to use `$.inputmask` solves the error, but my custom mask is not registered.

There is some piece of code I'm missing.

**Comment by RobinHerbots** [comment]
The inputmask class is only defined  in the current unreleased version.  The readme on github is also already updated for th e unreleased version.  You have to extend $.inputmask.aliases with $.extend from jquery

**Comment by garcia-jj** [comment]
@RobinHerbots, thank you for your support. It works for me using this code.

```
    $.extend($.inputmask.defaults.aliases, { cpf        : { mask:  '999.999.999-99' } });
```
