### ISSUE TITLE
Date mask bug

### ISSUE THREAD

**Issue by jimithing277** [RobinHerbots/Inputmask#969]
Using a date mask of "mm/dd/yyyy" if you enter 06/30/2015 and then place the cursor at the "3" and enter "4" you are left with:

"06/d0/2015"

You can duplicate this using the demo on the site.  

Expected behavior would be for the end result to show "06/04/2015".  Apparently this happens whenever the second digit of the day portion is "0" and you enter a value in the first digit between 4 and 9.

**Comment by RobinHerbots** [comment]
@jimithing277 , 

This works in version 5.0.0
