### ISSUE TITLE
Losing focus on an empty input triggers onincomplete

### ISSUE THREAD

**Issue by gkinsman** [RobinHerbots/Inputmask#97]
Decimal (and derived) input types trigger an onincomplete when focusing the input, and then blurring it. 

Inputs also fire an onincomplete when entering numbers that don't fit the full length, which is odd given that decimal implies that it can be _up to_ the repeat number, unless I'm mistaken.

This may be desired behaviour, but if so it would be really useful to have a document outlining the behaviours of these events. I'm already working on a document of current behaviours, which I'll make public soon.

**Comment by RobinHerbots** [comment]
You are correct but what would be best?  In the other case the incomplete event will never trigger.

**Comment by gkinsman** [comment]
What is the meaning or need for an incomplete event for decimals? It seems that they could be treated as full length optional masks, in which there is no concept of incompletion. Corollary to that, there's also no real place for a complete event either, for the same reasons.

Perhaps instead the complete could be fired on blur, though that would perhaps conflict with the change event, I'm not sure. I do think though that firing an incomplete weakens the meaning of the event, making it less useful.

**Comment by RobinHerbots** [comment]
I changed it so the incomplete event isn't triggered anymore, however now the complete event is triggered, but this seems more correct in that context.

Actually those are more validation events which do not really belong in the inputmask plugin.  These event should better be handled with jquery.validation or something alike.  I committed the changes to the dev branch
