### ISSUE TITLE
Some Country Code masks do not work

### ISSUE THREAD

**Issue by badh0r53** [RobinHerbots/Inputmask#970]
Test Data:
     49 (Germany) doesn't work. After typing 49, ( appears with no ending ).
     52 (Mexico) doesn't work. After typing 52, I can't type more digits.
     84 (Vietnam) doesn't work. After typing 84, I can't type more digits.
     86 (China) doesn't work. After typing 49, ( appears with no ending ).
     592 (Guyana) adds an extra 2 after typing 592, and I can't type more digits.
    598 (Uruguay) adds an extra 8 after typing 598, and I can't type more digits.

Test environments:
     Failed in online sample -> http://robinherbots.github.io/jquery.inputmask/
     Failed local testing using snapshot -> 3.1.64-97
     Originally worked using snapshot -> 0.0.0

**Comment by RobinHerbots** [comment]
@JosephChandler , 

Thx, I will need to verify case by case.  

What do you mean exactly that it worked using snapshot 0.0.0 ?

**Comment by UtamaruMonster** [comment]
Don't know if its related.
When typing 372 code, witch is Estonia, inputmask shows USA and Canada plus it adds 222.
What you get is 372222 and no possibility to do anything but delete.

**Comment by RobinHerbots** [comment]
@JosephChandler ,  @UtamaruMonster ,

Fixed in the current version on github

**Comment by hotleadru** [comment]
Hi. 
Same problems.

Have a troubles with different masks in once countries.

49 (Germany) doesn't work. After typing 49, ( appears with no ending ).
52 (Mexico) doesn't work. After typing 52, I can't type more digits.
84 (Vietnam) doesn't work. After typing 84, I can't type more digits.
86 (China) doesn't work. After typing 49, ( appears with no ending ).
592 (Guyana) adds an extra 2 after typing 592, and I can't type more digits.
598 (Uruguay) adds an extra 8 after typing 598, and I can't type more digits.

When you fill phone from Germany http://prntscr.com/cenqe8 it's get only one mask but in the JS we have many masks http://prntscr.com/cenr1b
And when you delete { "mask": "+49-###-###", "cc": "DE", "cd": "Germany", "desc_en": "", "name_ru": "Германия", "desc_ru": "" }, It's start showing other masks.

**Comment by RobinHerbots** [comment]
@hotleadru , 

Due to new changes it is broken again.  I'm working on the phone mask currently. 

Thx for the info!
