### ISSUE TITLE
Placeholder color

### ISSUE THREAD

**Issue by afattahi54** [RobinHerbots/Inputmask#972]
Is it possible to change placeholder color ?!

**Comment by RobinHerbots** [comment]
@afattahi54, 

Not yet, I will need to investigate the possibilities first

**Comment by slaphead** [comment]
Is this possible yet, would really like to change the color of the placeholder.

**Comment by RobinHerbots** [comment]
@afattahi54 , @slaphead , 

Have a look at the new  colorMask option. (also include the inputmask.css)

**Comment by satodavan** [comment]
How to use this feature?
I added colorMask:true option and had included styles from inputmask.css. Input became transparent. 
Div was added by script to the end of the body. How to place generated div into the input's parent container?

**Comment by RobinHerbots** [comment]
The div appears at the end of the body in the html but is visually placed above (actually underneath) the input.  What is the problem?  Doesn't the mask work or didn't you see a difference?  The default color of the colormask is grey and you don't see a clear difference with a normal mask.

**Comment by satodavan** [comment]
In my case I have div visually appears at the top of page, not under input.
And how to add class to generated div?

**Comment by RobinHerbots** [comment]
@satodavan , 

Can you create a new issue for it, with a jsfiddle which shows your case.  
I will have a look then

**Comment by madhurjya** [comment]
I was facing the same issue I have resolve this issue by modifying  on Version: 3.3.5-19 at line no 710 also on line no 717 (for resize)
Replace   "var offset = $(input).position()" with "var offset = $(input).offset()"; and then need to put z-index for dynamic div (if required).

**Comment by lebadapetru** [comment]
any updates here?  I still cannot change the input's placeholder color. For some reason, my placeholder opacity is 0 when using inputmasking and i would like to fix that to be as it should be by default

**Comment by geoquant** [comment]
also need help styling the placeholder...

**Comment by eduardo-mior** [comment]
@geoquant use this css:
```css
input::placeholder,
input:-moz-placeholder,
input::-moz-placeholder,
input::-webkit-input-placeholder {
    color: #C5C5C5 !important;
}
```

**Comment by Antibreez** [comment]
@RobinHerbots Hello! Can you please tell why is **colorMask** option was droped? Is there any way to split input value by color (inputed value - one color, left placeholder value - another color). I have inputmask with phone number and placeholder chars "0". I need to divide by color entered digits and lefted "0" chars. Can you please suggest something? :)
