### ISSUE TITLE
Decimal mask accepts "123,456." (RadixPoint with no number after it)

### ISSUE THREAD

**Issue by afattahi54** [RobinHerbots/Inputmask#973]
The decimal mask mentioned at http://robinherbots.github.io/jquery.inputmask/ , accepts "123,456."  which is not a valid decimal. It has RadixPoint with no number after it.
Can it be fixed ?!

**Comment by RobinHerbots** [comment]
@afattahi54, 

I can strip the radixpoint on blur

**Comment by afattahi54** [comment]
It will be great thanks!

**Comment by RobinHerbots** [comment]
fixed
