### ISSUE TITLE
Avoid using valhooks

### ISSUE THREAD

**Issue by ronin** [RobinHerbots/Inputmask#978]
So I had problem that after selecting value from dropdown, inputmask was resetting value to the previous one. It took me some time to find that the issue was with jquery-number plugin, which is also using valhooks and they were conflicting with inputmask.

I've described this problem in a blog post here http://www.visuality.pl/posts/use-less-jquery-javascript-plugins. Problem was only showing in Safari browser. My solution was to remove jquery-number plugin.

But I think you can remove use of valhooks since it doesn't look like they are used or maybe I wasn't looking long enough.

**Comment by RobinHerbots** [comment]
@ronin , 

Have a look at https://github.com/customd/jquery-number/issues/71

Tha valhook is used for browsers which don't allow for patching the original val property.
