### ISSUE TITLE
Numeric masks go beyond maxlength

### ISSUE THREAD

**Issue by rcdmk** [RobinHerbots/Inputmask#98]
Hi.
I have a field where I have to type in some decimal numbers like "0.25" and my field have a maxlength attribute of 4, to restrict the size of the input, but it did not work.

I've seen that the default repeat value for the decimal mask is 10, and its exaclty the maximum of chars I can type in my input, even having a maxlength of 4:

```
 <input maxlength="4" id="someId" />
 <script>$("#someId").inputmask("decimal");</script>
```

**Comment by RobinHerbots** [comment]
Hi,

I will fix this soon.

best regards,

Robin

2012/8/2 RCDMK <
reply@reply.github.com

**Comment by rcdmk** [comment]
Just to follow-up, this is not fixed inthe actual version. It keeps allowing to pass the `maxlength` attribute, but this time restricting to 5 instead of 10 characters:

```
<input maxlength="4" id="someId" />
<script>$("#someId").inputmask("decimal");</script>
```

**Comment by rcdmk** [comment]
I realised that setting greedy to false solves this problem.

**Comment by RobinHerbots** [comment]
This is fixed but can be confusing sometimes, ..

ex with decimal alias and autoGroup true maxlength 4

This only allows 3 numbers as the autoformatiing will apply formatting as of the fourth number 1234 => 1,234 not allowed as the maxlength is 4.

But I will add something like maxnumericlength

best regards, 

Robin
