### ISSUE TITLE
decimal mask with integerDigits 0 and groupSeparator shows an error.

### ISSUE THREAD

**Issue by maubin** [RobinHerbots/Inputmask#980]
When you have a "decimal" mask, integerDigits set to 0 and set the groupSeparator set it promps an error.

jsfiddle that shows the error: http://jsfiddle.net/yumv1ds6/
jsfiddle without the error and without the groupSeparator parameter : http://jsfiddle.net/an22kkn3/

I know it doesn't make sense to set a groupSeparator when you have integerDigits set to 0 but it doesn't show an error with other options like autoGroup and groupSize. 

The issue occurred because we have a "form designer" that let you modify the different options of the decimal mask and we initialize the mask with all the options listed whatever the values set. 

I can go around the bug by not passing the groupSeparator when my integerDigits is 0 without problem. If you decide that it's not a bug and don't want to handle internally I won't mind.

**Comment by RobinHerbots** [comment]
I wil fix that tomorrow morning.  Thx for reporting!

**Comment by RobinHerbots** [comment]
@maubin , 

Fixed.  see http://jsfiddle.net/yumv1ds6/1/
