### ISSUE TITLE
Inputs are ignored on FF 39 on Android 5.0.2

### ISSUE THREAD

**Issue by ghost** [RobinHerbots/Inputmask#982]
Using you first example on the demo page (http://robinherbots.github.io/jquery.inputmask/), I encounter the following problems on my Android 5.0.2 using Firefox 39:
1. I klick on the input field and I see the mask dd/mm/yyyy and the on screen keyboard pops up
2. I hit a number on the keyboard (e.g. 5). The mask stays unchanged, the inputs get ignored.
3. I hit a second number (e.g. 5). The mask disappears, the inputs still gets ignored.

On the same mobile device, none of the examples seems to work.

I try to use the inputmask in a project and encountered the above error. To make it easier to reproduce I used your demo page.

**Comment by RobinHerbots** [comment]
@educo-adymorz , 

Can you retest with the latest version

**Comment by ghost** [comment]
Sorry for the late reply.
My coworker did and it worked fine.
Thank you for the fixes.
