### ISSUE TITLE
Masking not working properly

### ISSUE THREAD

**Issue by shivabhusal** [RobinHerbots/Inputmask#984]
`$('input[id*="extension"]').inputmask('9{5}');`
![image](https://cloud.githubusercontent.com/assets/8004593/8905661/cf06d714-3487-11e5-821f-913079de2b4c.png)

Expected: We should not be able to create a void in between the digits as in the picture/snip or type digits in between empty space

**Comment by RobinHerbots** [comment]
@shivabhusal , 

This is a masking plugin not a validation plugin.

You set a mask of 5 numbers.  You got 5 places where you only can input numbers.  The mask is just incomplete.  

Maybe you can use the clearincomplete option to clear invalid input on blur.
