### ISSUE TITLE
Bug in minified version of regex extension.

### ISSUE THREAD

**Issue by warriorpostman** [RobinHerbots/Inputmask#987]
Hope this is the right place to log this issue...I found a bug while using the minified regex extension script (testing in Firefox). The mask was non-functional, and in the Firefox dev console, I got the error "ReferenceError: Inputmask is not defined". I edited the minified script from `Inputmask` -> `inputmask`, and everything worked perfectly after that!

So, is this just a bug in the build process that produces the minified script?

I can create a pull request to demonstrate the difference, if you like.

Thanks.

**Comment by RobinHerbots** [comment]
@warriorpostman , 

It should be Inputmask and not inputmask.  Did you also updated the inputmask.js ?

Can you create a jsfiddle to show the problem in FF.

**Comment by warriorpostman** [comment]
Hi there, really sorry for the late response. Due to time constraints, I ended up referencing the minified bundle JS for the work I was doing. It's possible my initial problem was maybe caused by including the scripts (inputmask, inputmask extension, jquery input plugin) in the wrong order?  But I was never able to verify this.

**Comment by RobinHerbots** [comment]
@warriorpostman , 

No problem.  There was actually a leftover of the inputmask ref in the numeric alias.  ;-)

Anyway keep reporting any trouble you find!
