### ISSUE TITLE
Regex for input mask date

### ISSUE THREAD

**Issue by CHOUAIAR** [RobinHerbots/Inputmask#988]
How can I allow the client to type another digit then 1/2 in the year case?

thanks in advance

**Comment by RobinHerbots** [comment]
@CHOUAIAR , 

I know I need to update the readme for the extensions, ...

but you can use     yearrange: {
                minyear: 1900,
                maxyear: 2099
            }, options for that.

**Comment by RobinHerbots** [comment]
@CHOUAIAR , 

Use  Inputmask 5.0.0
