### ISSUE TITLE
Focus loop on IE9 with numeric.extensions

### ISSUE THREAD

**Issue by williamsrb** [RobinHerbots/Inputmask#989]
IE9 crashes when using inputmask.
But before the crash, something happens like a loop of focus in the input.
The html file hosted with scripts:
http://textuploader.com/a1xjv

Inputmask version: 3.1.64-118
Jquery version: 1.10.2

**Comment by williamsrb** [comment]
Also happens on IE11

**Comment by RobinHerbots** [comment]
Can you try with the latest version pn github

**Comment by williamsrb** [comment]
I've tried the latest version, 3.1.64-150, still not working.
http://textuploader.com/a12ld
You can reproduce de problem too, just save the html file and open in InternetExplorer9+.

**Comment by RobinHerbots** [comment]
I will fix it on monday

**Comment by solsticesurfer** [comment]
Problem still occurs in IE11 using the latest build (Sept 9)

**Comment by RobinHerbots** [comment]
@solsticesurfer , 

Can you provide some more info on how to reproduce the problem.  Or create a jsfiddle.

I tried in IE11  and also in IE9 mode but the example above just keeps working.

**Comment by dluk** [comment]
I think I also have the same problem with latest version (3.2.1-55) and IE11, it is not possible to leave an empty input when using these options `{
            "alias": "integer",
            "groupSeparator": " ",
            "autoGroup": true,
            "autoUnmask": true,
            "unmaskAsNumber": true,
            "allowMinus": false,
            "allowPlus": false,
            "integerDigits": 5
        }`

**Comment by dluk** [comment]
Found out that with parameters `{ "alias": "integer", "groupSeparator": " ", "autoGroup": true, "autoUnmask": true, "unmaskAsNumber": true, "allowMinus": false, "allowPlus": false, "integerDigits": 5 }` the problematic one is "autoGroup": true, when I set it to false, you can leave the empty input. FYI: jQuery version 2.1.4

**Comment by RobinHerbots** [comment]
@dluk , 

Can you retest with the latest version.

**Comment by dluk** [comment]
Look's like it's fixed. Thanks!

**Comment by RobinHerbots** [comment]
@dluk , 

That's great!
