### ISSUE TITLE
Issue using datamask-input attributes and event handlers

### ISSUE THREAD

**Issue by gbronzer** [RobinHerbots/Inputmask#992]
I'm using the datamask-input-XXX attributes to make it easier to handle different inputs on the same page. Then I just call $(selector).inputmask() to set them up. That works great.

However, I now need to add an "onBeforePaste" handler and I can't seem to do that. If I put it in an attribute, it doesn't seem to get called. If I put it as the options in the initial setup call, it seems to ignore all the attributes and completely breaks the masking.

Am I missing something obvious on how to mix these to methods of setting options?
**Examples:**
This breaks the input mask completely.

``` javascript
    jQuery("input.phoneMask").inputmask({
        "onBeforePaste": function (pastedValue, opts) {
            return phoneNumOnPaste(pastedValue, opts);
        }
    });
```

This method masks ok, but the onBeforePaste is never called.

``` html
<input class="numberOnly phoneMask " data-inputmask-greedy="false" data-inputmask-mask="(999) 999-9999" data-inputmask-onbeforepaste="function (pastedValue, opts) { alert(pastedValue); return true; }" data-inputmask-placeholder="(###) ###-####" data-inputmask-positioncaretontab="true" id="CellPhone" maxlength="40" name="CellPhone" onchange="$(this).addClass('chg');validPhoneNumber(this, false, true);" onkeypress="enablePhoneMask(this);" size="20" type="text" value="(704) 564-6544">
```

**Comment by gbronzer** [comment]
FYI, browsing issues I saw issue 949 about setting options on initalized intputMasks. That might be a solution in this scenario. After my generic initialize, I could set the OnBeforeMask option explicitly. The issue related to replaced options also seems similar to my issue where you can specify options on the initial call or in attributes but not both.

**Comment by RobinHerbots** [comment]
@gbronzer , 

Yes issue #949 is related.  I will fix this in milestone 3.3

**Comment by gbronzer** [comment]
@RobinHerbots ,

Fantastic! Thanks for such a great tool!

**Comment by brownbl1** [comment]
@RobinHerbots @gbronzer 
Thanks for the fix! If dist is stable, should we update now or wait for the official release if it's not?

**Comment by RobinHerbots** [comment]
@itslittlejohn , 

I guess that is totally up to you ;-)
