### ISSUE TITLE
Windows Phone User unable to set Date

### ISSUE THREAD

**Issue by Domtaholic** [RobinHerbots/Inputmask#993]
Hi Robin,

this was discussed in other Issues but you never used a Phone to test this as i see and never postet a solution cause it looked fine for you.

We used you´re mask for our Form and Masked the Date like this:

$('input.dateValidate').inputmask("mask", {"alias": "dd.mm.yyyy", "placeholder": "TT.MM.JJJJ", showMaskOnHover: false});

As tested with a Windows Device with the IE installed there, we´re unable to set a Date, so the user is unable to fill the Form. The Caret jumps after i type a 2 for the day to the first y and im unable to set the Month. Either to complete the Year.

Could you please test with a Device. 

Cheers

**Comment by RobinHerbots** [comment]
@Domtaholic , 

I would love to solve the issue but I don't have a Windows Phone at hand.

**Comment by Domtaholic** [comment]
@RobinHerbots ,

thx for fast reply. 

Is there any chance you can get one for testing the next couple of days? 

Our release Date is in 2 weeks. Any Device Labs near you or a friend of you with one?

We got a Lumia 535 and a 530, both has the same problems. 

If there is anything i can do for you just let me know.

Cheers

**Comment by RobinHerbots** [comment]
@Domtaholic, 

Have a look if the caret positioning works correclty on the windows phone. =>  inputmask.js caret fn.

Or donate some money to buy a cheap windows phone  ;-)

**Comment by Domtaholic** [comment]
Sorry i don´t get what that means: "=> inputmask.js caret fn."

**Comment by RobinHerbots** [comment]
@Domtaholic , 

Debug the caret function into the inputmask.js file with the windows phone device.

**Comment by Domtaholic** [comment]
@RobinHerbots 

Okay will spend some time today on this one. 

Any tips about debugging this and any thoughts why the caret jumps on Windows Phone?

**Comment by RobinHerbots** [comment]
@Domtaholic , 

Check for script errors, ... caret positioning (caret function) and also to the composition events.

If I got a real device it would be really handy  ;-/

**Comment by abbazabacto** [comment]
@RobinHerbots May I first thank you for your wonderful plugin, I use it a lot and it really makes the UX on my sites great, especially this date-inputmask.

For windows phone (8.1) the problems I see are the following:
- when i start typing it ignores the ONLY the first digit i enter, which leads to sometimes failing the second, with "09" the 0 would fail, but the 9 wouldnt be accepted by the regexp for month.
- when i remove a digit with the backspace, i see the same problem as above occuring.
- like said ONLY the first digit, so if it starts typing all is well

I unfortunatly dont have the ability to debug the above mentioned function, you could try out:
http://blogs.msdn.com/b/visualstudioalm/archive/2014/04/04/diagnosing-mobile-website-issues-on-windows-phone-8-1-with-visual-studio.aspx (especially the "Debugging Without a Visual Studio Project"-part).

Hope this helps, keep up the good work!

**Comment by RobinHerbots** [comment]
@Domtaholic , 

Try again with the latest version
