### ISSUE TITLE
Can you help me convert this regex to a mask?

### ISSUE THREAD

**Issue by jpontet** [RobinHerbots/Inputmask#995]
@RobinHerbots or anyone else. I have this regex for an email mask- can you help me convert it to a mask alias? Im not sure how to do the mask paramater or definitions.

`^[_A-Za-z0-9%+-]+(\.[_A-Za-z0-9%+-]+)*@([A-Za-z0-9]([A-Za-z0-9-]*[A-Za-z0-9])?\.)+[A-Za-z]{2,50}$`

**Comment by RobinHerbots** [comment]
@jpontet , 

Have a try with

```
$(selector).inputmask("Regex", { regex: "^[_A-Za-z0-9%+-]+(\.[_A-Za-z0-9%+-]+)*@([A-Za-z0-9]([A-Za-z0-9-]*[A-Za-z0-9])?\.)+[A-Za-z]{2,50}$"});
```

**Comment by jpontet** [comment]
Ah thanks @RobinHerbots . I was hoping to still have the masking! :) Is that possible?

**Comment by RobinHerbots** [comment]
@jpontet , 

That is a feature I'm want to add to the regex alias.

Why don't you use the email alias?  You can still check against the regex on the complete callback

**Comment by jpontet** [comment]
Ill try that!
